- core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java
There has been errors when an active sync enabled secondary master get promoted to primary. It is caused by active sync manager trying to access UFS when master is in secondary mode. UFS client are not initialized for mount points on secondary master so error occurs when active sync manager accesses it during snapshotting and server stopping process.
This fix updated active sync manager to avoid unnecessary access to UFS client on a secondary master.
> Fix active sync manager error on secondary master

- dev/jenkins/build.sh
in order to properly clean subdirectories that are git repos
see https://stackoverflow.com/questions/9314365/git-clean-is-not-removing-a-submodule-added-to-a-branch-when-switching-branches
> Run git clean with two -f

- webui/pom.xml
The maven build actually executes the generate-sources phase twice
because the maven-sources-plugin calls the generate-sources phase during
its attach-sources target. This causes the UI module to install node/npm
AND run npm install twice during the build. Moving these plugins from
generate-sources to process-sources (the next step in the maven
lifecycle) prevents the extra calls and saves time during the build.
> Prevent UI from installing dependencies twice

- integration/docker/Dockerfile
The issue is that alluxio docker image only supports two users: alluxio and root, but in the customer env, they have more users and the data of each user are isolated. So we need to make alluxio docker image can support run container by specifying during running time. 
This feature by default is disabled.
> Support dynamic user to run alluxio

- core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
- core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileSystem.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioHdfsFileSystem.java
- shell/src/main/java/alluxio/cli/fs/command/LoadMetadataCommand.java
We used to have a command `fs loadMetadata`
This PR restores loadMetadata command, but as a client-side optimization without storing all returned `ls` results, preventing OOM for massive amount of small files.
This optimization is experimental, going to branch-2.3-fuse only for now
Fix https://github.com/Alluxio/alluxio/issues/12088
> Add loadMetadata command

- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
- core/transport/src/main/proto/grpc/raft_journal.proto
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTest.java
This change implements the quorum join process for new master.
Ratis provides an API for update quorum member list. To implement an automatic join comparable with what we did with Copycat, the new master will send a join request to the quorum leader after it initialized the journal. The leader will  atomically convert the request to a raft configuration change and apply it to the quorum. 
This operation is a noop for a master that is already in the quorum.
> Enable new master to join an existing quorum

- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStore.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreTest.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- tests/src/test/java/alluxio/client/fs/LocalCacheManagerIntegrationTest.java
- remove restore logic to a separate background thread meanwhile open the cache manager in a "readonly" mode to other query threads. in this way, early queries will suffer from low hit ratio but hopefully they will catch up.
- handle capacity exceeding gracefully: instead of failing the restore and delete all pages on disk, just remove the excessive pages
> Fix slow and contented local cache restart

- core/client/fs/src/main/java/alluxio/client/block/stream/GrpcBlockingStream.java
- core/common/src/main/java/alluxio/util/LogUtils.java
- core/common/src/test/java/alluxio/util/LogUtilsTest.java
When printing a request proto as a log message or exception message, some requests contain large payloads. Those large payloads make it difficult to inspect the message. This change truncates individual lines of message.
> Avoid printing long proto lines in messages and exception descriptions

- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
Sometimes a Ratis client decides to timeout and close connection when master tries to gain primacy. This change makes the master to notify Ratis client to reconnect when an exception is throw, so we don't just keep retrying on a closed client.
> Make Ratis client retry on catchup failures

- core/client/fs/src/main/java/alluxio/client/meta/RetryHandlingMetaMasterConfigClient.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
- core/server/worker/src/main/java/alluxio/worker/file/FileSystemMasterClient.java
In a cluster with multiple masters using embedded journal, when network partitioned the original leading master, leadership changes to a new leading master. The workers hang in GRPC connections with the previous leading master and don't register with the new leading master.
This PR adds the timeout to periodical connections (operations) between workers and leading masters to prevent workers from hanging forever.
> Add worker master periodical connections timeout

- core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java
Fix bug: fuse pod hang forever if open&read many files without close  the files
Root cause:
`mBlockInStream` in `AlluxioFileInStream` won't be released even reading to end of the block.
In this case, `BlockWorkerClient` will be held in `BlockInStream`. Given many files opened, `BlockWorkerClient` in the pool will be exhausted and the following operations will be blocked.
Fix:
Release `mBlockInStream` after reading to end of the block.
> Fix deadlock of racing worker client acquisition and file completion

- shell/src/main/java/alluxio/cli/bundler/CollectInfo.java
When `collectInfo` is printing the help message in `printHelp()` the output already starts with "usage:". The extra "USAGE:" string is redundant.
Also add one missing option into the message.
> [SMALLFIX] Remove collectInfo redundant printout

- shell/src/main/java/alluxio/cli/fs/FileSystemShellUtils.java
- tests/src/test/java/alluxio/client/cli/fs/command/CpCommandIntegrationTest.java
Previously if we try to use wildcard to copy files in path with special characters like '.', '+', '^', "$', '*', the cp will fail.
This test fix the escape function to escape special characters used in regrex pattern matching.
> Fix cp with wildcard and special characters

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- tests/src/test/java/alluxio/client/fs/UfsSyncIntegrationTest.java
Marking paths as sync during the sync is inaccurate, because the syncs for descendants are run in a separate thread pool. Therefore, only mark the root path as synced after everything is finished. This also reduces the number of entries in the sync cache, instead of marking each path in the tree.
Fixes #12106
> Update sync status after processing the entire sync

- shell/src/main/java/alluxio/cli/fs/FileSystemShellUtils.java
- tests/src/test/java/alluxio/client/cli/fs/command/CpCommandIntegrationTest.java
Previously if we try to use wildcard to copy files in path with special characters like '.', '+', '^', "$', '*', the cp will fail.
This test fix the escape function to escape special characters used in regrex pattern matching.
[This is an auto-generated PR to cherry-pick committed PR #12135 into target branch branch-2.2]
> Port changes of [#12135] to branch-2.2

- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
In an unlucky situation when raft server throw an exception while losing primacy, the master will attempt to shutdown but stuck in a deadlock of `RaftJournalSystem::losePrimacy -> System::exit -> ProcessUtils::stopProcessOnShutdown -> RaftJournalSystem::stop`. It can be fixed with throwing directly within `losePrimacy`.
> Fix deadlock when raft journal throws exception

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/raft/LocalFirstRaftClient.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalWriter.java
- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
- core/server/master/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java
- tests/src/test/java/alluxio/client/cli/JournalToolTest.java
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTest.java
Current the raft client for writing journal entries will always checking for leadership and send the request through network interface, introducing significant overhead. This change implements a raft client which attempts sending messages directly to local server first, and falls back to the default client if the local server is no longer a leader.
The client also has built-in retry function for raft client which is closed due to timeout.
> Implement a local first raft client for improved journal performance

- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
Ratis leader sometimes send a request to a follower to install a snapshot that is older than the follower's log. This change implements a check to avoid reloading the state machine after such snapshots are downloaded to prevent some accounting issue.
> Avoid reloading old snapshots

- core/common/src/main/java/alluxio/util/CommonUtils.java
- core/common/src/test/java/alluxio/util/CommonUtilsTest.java
- shell/src/main/java/alluxio/cli/bundler/CollectInfo.java
- shell/src/main/java/alluxio/cli/bundler/command/AbstractCollectInfoCommand.java
- shell/src/main/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommand.java
- shell/src/main/java/alluxio/cli/bundler/command/CollectConfigCommand.java
- shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java
- shell/src/test/java/alluxio/cli/bundler/InfoCollectorTestUtils.java
- shell/src/test/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommandTest.java
- shell/src/test/java/alluxio/cli/bundler/command/CollectConfCommandTest.java
- shell/src/test/java/alluxio/cli/bundler/command/CollectEnvCommandTest.java
- shell/src/test/java/alluxio/cli/bundler/command/CollectLogCommandTest.java
Manually cherry-picking as [#9940 ] is not in 2.3.
This adds 3 features to `collectInfo`
1. With `--exclude-logs <filename-prefixes>`, `--include-logs
<filename-prefixes>` and `--additional-logs` the user is able to specify
log files to take or not take. By default only Alluxio-relevant files
under `${ALLUXIO_HOME}/logs` are included and unrecognized files are
ignored.
For example, `alluxio collectInfo --additional-logs alluxio_gc
--exclude-logs master collectLog <tmp-dir>` will include all
`alluxio_gc*` files (supposedly for GC logs) and exclude all `master*`
files like `master.log.*` and `master.out`.
`alluxio collectInfo --include-logs master collectLog <tmp-dir>` will,
however, take only the `master*` files like `master.log` and
`master.out`.
2. With `--start-time <datetime>` and …
> Port [#11783] to branch-2.3

- minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
Some tests are still a bit flaky after having moved to github-actions and increasing this a little more seems to help.
> Increase timeout for MultiProcessCluster

- core/server/common/src/main/java/alluxio/RpcUtils.java
Logging java stack trace hurt the performance of listing a large number of miss files, remove java stack trace to fix the performance issue.
> Remove java stack trace log to fix list miss file status perf

- conf/log4j.properties
There are a large number of logs from Ratis with info level. Change the log level to WARN to avoid it.
> Avoid logging log info from ratis

- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalUtils.java
- core/server/master/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java
- tests/src/test/java/alluxio/client/cli/JournalToolTest.java
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTest.java
Master log shows the following error:
```
"2020-09-14 17:19:37,127 WARN  RaftServerProxy - FaultToleranceScaleEmbeddedJournalR-masters-1_19200: Failed to initialize the group directory /tmp/alluxio/journal/JobJournal.  Ignoring it
java.lang.IllegalArgumentException: Invalid UUID string: JobJournal
at java.util.UUID.fromString(UUID.java:194)
at org.apache.ratis.server.impl.RaftServerProxy.lambda$null$0(RaftServerProxy.java:197)"
```
It's because Ratis scans all directories under the configured path now and calls out the ones that are not named as a raft group id. Since we have `JobJournal` as a sub directory of the master journal directory, it is detected by Ratis which will log an error. This change addresses this issue by moving Ratis journal path to be one level deeper so it does not …
> Move raft journal to an isolated directory

- core/server/common/src/main/java/alluxio/master/BackupManager.java
- core/server/common/src/main/java/alluxio/master/journal/JournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/noop/NoopJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/BufferedJournalApplier.java
- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/SnapshotReplicationManager.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSystem.java
- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
- core/server/master/src/main/java/alluxio/master/backup/AbstractBackupRole.java
- core/server/master/src/main/java/alluxio/master/backup/BackupWorkerRole.java
- tests/src/test/java/alluxio/client/cli/fsadmin/BackupCommandIntegrationTest.java
This change fixed a few issues related to backup:
- Make backup interrupt correctly when raft journal needs to reload from a snapshot. Currently if backup occurs right before a journal reload it can buffer up some entries and then corrupt journal by resuming after the reload is completed. This change added an interrupt callback to make sure backup is correctly canceled and journal is resumed before a reload happens.
- Block backup when journal is being reloaded. When a raft journal is being reloaded, the backup should not happen because it will capture inconsistent state while the master metadata is re-applied from snapshot.
- Cancel backup sub-tasks properly. Currently when a backup is cancelled due to error or interruption, the sub-tasks do not explicitly respond to interrupt signals, …
> Fix backup coordination and error handling

- integration/dataproc/alluxio-dataproc.sh
- integration/emr/alluxio-emr.sh
both scripts were incorrectly setting the property key "alluxio.underfs.hdfs.version"
this previously worked because alluxio defaulted to using 2.7,
but once this was updated to use 3.3.0 to be compatible for java 11,
the fallback default no longer worked
> Fix underfs.version property in emr and dataproc scripts

- integration/docker/Dockerfile
- integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
- integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml
This solves the issue related to https://github.com/docker-library/openjdk/issues/76
In a container based on java alpine, commands like `jmap`, `jstack` don't work, and the pid of alluxio processes like `AlluxioWorker` is 1. 
Before:
```
bash-4.4$ jps
1 AlluxioMaster
904 Jps
bash-4.4$ jstack 1
1: Unable to get pid of LinuxThreads manager thread
```
After:
```
bash-4.4# jps
357 Jps
6 AlluxioWorker
```
> Run alluxio processes with tini in containers

- stress/shell/src/main/java/alluxio/stress/cli/Benchmark.java
We fixed passing of parameters for clustered benchmarks before, but did not fix it for non clustered benchmark
> Fix passing of parameters to benchmarks

- integration/emr/alluxio-emr.sh
in emr 5.25, which we refer to in our docs, the presto version is 0.220. the connector we bundle with the tarball only works with 0.227+. if we configure the alluxio catalog that uses our bundled connector and the presto version is incompatible, presto will fail to start.
this change checks for the emr version and ensures that it is >= 5.28, which is the first version that uses presto 0.227. here we are assuming that presto will be backwards compatible
i have tested this with both emr 5.25 and 5.28 to ensure the catalog is configured as described
> Do not configure alluxio catalog for older versions of presto in emr

- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
When a backup is interrupted, there is a chance that the resume callback cannot be canceled and thus happens after the server is already resumed by the journal reload process. While it makes sense for backup to crash the master if resume fails to complete and master cannot accept new journal entries, it is completely fine for master to continue if backup tries to resume an already resumed journal. This change updates the journal to not throw if someone attempts to resume after the journal is already resumed.
> Fix backup worker crashing master on interruption

- core/server/common/src/main/java/alluxio/master/journal/raft/LocalFirstRaftClient.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalWriter.java
Fixed two flaky issues related to server start:
- Using same clientId for normal APIs and raw APIs can cause collision in message caching.
- Sometimes server failed to retry on AlreadyClosedException because it is wrapped in a different class.
> Fix flaky server start

- tests/src/test/java/alluxio/server/tieredstore/LostStorageIntegrationTest.java
Fix #12187
With this PR, root user and none-root user can pass the `LostStorageIntegrationTest` by exexuted
```bash
```
the following is the test by root user.
```bash
[root@c2eaf3f187f2 alluxio]# /softwares/apache-maven-3.6.3/bin/mvn test -Dtest=LostStorageIntegrationTest -pl tests
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.alluxio:alluxio-shaded-hadoop:jar:3.3.0
[WARNING] 'version' contains an expression but should be a constant. @ org.alluxio:alluxio-shaded-hadoop:${ufs.hadoop.version}, /projects/github/alluxio/shaded/hadoop/pom.xml, line 23, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, …
```
> Fix LostStorageIntegrationTest failure on user 'root'

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Metrics are modified concurrently, so we need to use concurrentHashMap
> Use concurrentHashMap for metrics

- dev/scripts/check-docs.sh
@bf8086 this will display a stacktrace when `jekyll build` fails within docs check
> Add --trace to jekyll build cmd to display error

- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Revert the S3 client build way in https://github.com/Alluxio/alluxio/pull/12261/files
This is because the new builder will cause ceph failed to run with Alluxio S3 client.
The error message is 
Caused by: java.lang.IllegalArgumentException: Unable to create an UnderFileSystem instance for path: s3a://alluxios3a
Suppressed: java.lang.UnsupportedOperationException: Client is immutable when created with the builder.
at com.amazonaws.AmazonWebServiceClient.checkMutability(AmazonWebServiceClient.java:920)
at com.amazonaws.AmazonWebServiceClient.setEndpoint(AmazonWebServiceClient.java:226)
> Change back the S3 client build way

- .github/workflows/checkstyle.yml
- .github/workflows/java11_integration_tests.yml
- .github/workflows/java11_unit_tests.yml
- .github/workflows/java8_integration_tests.yml
- .github/workflows/java8_unit_tests.yml
Uploading github-actions artifacts is extremely flaky. Just look at https://github.com/actions/upload-artifact/issues/84#issuecomment-635056117 (Note the many +1 on the issue even after the issue has been closed.).
This tries to make sure that the test isn't marked as failure because archiving the artifacts failed on some files.
> Do not fail github-actions even when archiving artifacts fails

- underfs/adl/pom.xml
- underfs/wasb/pom.xml
Hadoop-azure 2.10.0 contains an important performance fix for listing flat directory with large numbers of files. Alluxio currently uses 2.7.3. With this fix, listing a dir with 8m files takes 20 min, down from hours.
Ref: https://issues.apache.org/jira/browse/HADOOP-15547
> Bump hadoop-azure pkg version to 2.10.0

- core/common/src/main/java/alluxio/cli/ValidationResults.java
- core/common/src/main/java/alluxio/cli/ValidationTool.java
- core/common/src/main/java/alluxio/cli/ValidationUtils.java
- integration/tools/hms/src/main/java/alluxio/cli/HmsValidationTool.java
Change the output to a validation object so that Json serialization can handle it better.
> Change the output of validation tools to an object

- shell/src/main/java/alluxio/cli/TestRunner.java
A small improvement to the printout so that the printed command can be run by users.
Example:
```
$ alluxio runTests
**runTest --operation BASIC --readType NO_CACHE --writeType ASYNC_THROUGH**
2020-10-20 16:09:47,021 INFO  BasicOperations - writeFile to file /default_tests_files/BASIC_NO_CACHE_ASYNC_THROUGH took 18 ms.
2020-10-20 16:09:47,025 INFO  BasicOperations - readFile file /default_tests_files/BASIC_NO_CACHE_ASYNC_THROUGH took 4 ms.
$ alluxio runTest --operation BASIC --readType NO_CACHE --writeType ASYNC_THROUGH
```
> [SMALLFIX] Improve runTests command

- integration/docker/entrypoint.sh
When running with non-root user in alluxio-worker container, non-root user may not have the write permission to the tiered store directories. This PR fixed this issue by changing the permission of tiered store dirs to 777.
> Improve entrypoint.sh to better support dynamic non-root user

- pom.xml
See Release Note: There are no other major changes other than addressing of the security vulnerability.
https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.1.md
> Upgrade JUnit 4.13 to 4.13.1 to fix security vulnerability

- pom.xml
- shaded/client/pom.xml
- shaded/hadoop/pom.xml
#12338
This is a workaround for MSHADE-148, which leads to an infinite loop when building Alluxio.
There are two scenarios.
- Releasing Alluxio
Maven build with `-Prelease`. 
- If using newer than `3.3.x` version of maven, you also have to use sequential build, Like `mvn clean install -Prelease xxxx`.
- If using lower version maven before `3.3.x`, you can use parallel build, e.g. `mvn clean install -T 4 -Prelease xxxx`
- Not Releasing Alluxio
If you are not releasing Alluxio, you can build Alluxio like before, please don't add the `-Prelease` into you build command line. e.g. `mvn clean install -T 4 xxxx`
This patch adds a -Prelease. If present, it will set createDependencyReducedPom true. The consequences are:
If you are releasing Alluxio with this profile, you are fine as long as …
> Add a releaseProfile to generate dependency reduced pom

- core/common/src/main/java/alluxio/resource/CloseableIterator.java
- core/common/src/test/java/alluxio/resource/CloseableIteratorTest.java
- core/server/common/src/main/java/alluxio/master/BackupManager.java
- core/server/common/src/main/java/alluxio/master/journal/DelegatingJournaled.java
- core/server/common/src/main/java/alluxio/master/journal/JournalEntryIterable.java
- core/server/common/src/main/java/alluxio/master/journal/JournalUtils.java
- core/server/common/src/main/java/alluxio/master/journal/JournaledGroup.java
- core/server/common/src/main/java/alluxio/master/journal/NoopJournaled.java
- core/server/common/src/test/java/alluxio/master/journal/JournalUtilsTest.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryIdGenerator.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeTreeBufferedIterator.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
- core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- core/server/master/src/main/java/alluxio/master/meta/PathProperties.java
- core/server/master/src/main/java/alluxio/underfs/MasterUfsManager.java
- core/server/master/src/test/java/alluxio/master/MockMaster.java
- core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeBufferedIteratorTest.java
- core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
- core/server/master/src/test/java/alluxio/master/journal/ufs/UfsJournalCheckpointThreadTest.java
- table/server/master/src/main/java/alluxio/master/table/AlluxioCatalog.java
- table/server/master/src/main/java/alluxio/master/table/Database.java
- table/server/master/src/main/java/alluxio/master/table/transform/TransformManager.java
Currently when a user iterate through the inode tree journal entries, a few threads are created to iterate through different directories. The threads will be closed when the iteration completes, but if an iteration is not fully completed, then the threads are leaked and never get properly shutdown.
This change modifies the `JournalEntryIterable` interface to return a closeable iterator of the journal entries, so the user of the iterator can explicitly shutdown the threads by calling the `close()` method or using the `try-with-resource` pattern.
The majority of the logic are in `InodeTreeBufferedIterator` class and `CloseableIterator` class.
> Fix memory leak in inode tree iterator

- stress/shell/src/main/java/alluxio/stress/cli/UfsIOBench.java
Parallel task were writing to the same file, and thus failing because of that. 
Introduces a class level unique id to prevent that.
> Fix parllel UfsIO test

- core/common/src/main/java/alluxio/util/CommonUtils.java
- integration/tools/hms/src/main/java/alluxio/cli/HmsValidationTool.java
- integration/tools/hms/src/main/java/alluxio/cli/hms/UriCheckTask.java
- integration/tools/validation/src/main/java/alluxio/cli/SshValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/ValidateEnv.java
Add a timeout value to this task so it doesn't hang for long periods of time (2min+ in my tests) when connecting to bad / unreachable URIs. Also improved the error message to be somewhat more helpful.
> Improve UriCheck validation tasks

- integration/tools/hms/pom.xml
This should help with the validation tools working with older version of hive metastore.
> Downgrade hive client version in validation tools

- core/client/fs/src/main/java/alluxio/client/file/cache/TimeBoundPageStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStoreOptions.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStoreOptions.java
- core/client/fs/src/test/java/alluxio/client/file/cache/store/LocalPageStoreTest.java
With this change, we can tell if `TimeBoundPageStore` is used when creation `PageStore` from logs
> Print out PageStoreOptions correctly

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
- tests/src/test/java/alluxio/client/fs/UfsSyncIntegrationTest.java
Fix https://github.com/Alluxio/alluxio/issues/12372
Before this PR, running 
```
bin/alluxio fs ls -Dalluxio.user.file.metadata.sync.interval=0 /path
```
will trigger syncing inodes:
(1) `/path`
(2) `/path/{children}`
(3) `/path/{children}/{children}` (added to pending inode queue when `InodeSyncStream` traversing (2))
Reading (3) is unnecessary w.r.t. the command we are interested. This PR check and prevent setting flag `syncChildren` unnecessarily.
In addition, this patch also saves one unnecessary RPC on ls command.
> Prevent unnecessary inode syncing

- core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- core/client/fs/src/main/java/alluxio/client/block/stream/GrpcBlockingStream.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
Some client requests to workers may take a long time, especially if UFS is involved. In order to avoid spurious errors, the timeout should be much longer, but we also log a message every minute while the client is waiting.
> Use longer remote io timeouts to account for slow operations

- .github/workflows/checkstyle.yml
Currently, all newly created PRs that run GH actions jobs will download all of the maven dependencies for the first run of GH actions. This leads to unnecessary network bandwidth usage and slows down each job by 2-3 minutes. This only affects the _first_ GH action run of each PR though. Subsequent actions will be able to utilize that PR branch's cache.
In order for the first GH actions PR run to utilize a cache _on the first run_, there needs to be a cache created from the default branch of the repo[[1]]. By running this small checkstyle and findbugs once a day, it will force any new dependencies to be added to the cache that all new PRs would then be able to utilize.
[1]: https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions …
> Add a GH action to default branch to utilize build cache

- libexec/alluxio-config.sh
Ratis recommend disabling `org.apache.ratis.thirdparty.io.netty.allocator.useCacheForAllThreads` to reduce unnecessary GC pressure. This has shown to reduce up to 10% memory overhead in some performance tests.
> Disable useCacheForAllThreads for Ratis

- integration/tools/pom.xml
- integration/tools/validation/src/main/java/alluxio/cli/UfsDirectoryValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/hdfs/HadoopConfigurationFileParser.java
- integration/tools/validation/src/main/java/alluxio/cli/hdfs/HdfsConfValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/hdfs/HdfsProxyUserValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/hdfs/SecureHdfsValidationTask.java
- integration/tools/validation/src/test/java/alluxio/cli/hdfs/HdfsConfValidationTaskTest.java
Improvements now provide more context for a few cases
- insufficient permissions to access
- HA configured but not used (nameservices)
- more info about checks which require additional configuration
- advice about XML parsing
> Improve hdfs validation task error messages

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Note that job retention time only kicks in when the JobMaster is at capacity in terms of number of jobs stored.
> Decrease default job retention time

- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
Ratis by default echo the journal message back after it is applied. This wastes a lot of memory and CPU time. This change makes the state machine explicitly return empty message since the journal write doesn't really care about the response content.
> Simplify journal writer response

- core/base/src/main/java/alluxio/wire/MountPointInfo.java
- core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
- core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- core/common/src/main/java/alluxio/grpc/GrpcUtils.java
- core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
- core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
- core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
- core/common/src/test/java/alluxio/wire/MountPointInfoTest.java
- core/server/master/src/main/java/alluxio/master/file/meta/options/MountInfo.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- job/server/src/main/java/alluxio/job/plan/stress/StressBenchDefinition.java
- stress/common/src/main/java/alluxio/stress/worker/UfsIOParameters.java
- stress/shell/src/main/java/alluxio/stress/cli/UfsIOBench.java
- tests/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java
Previously any ufs with credentials would need the credentials resupplied when running speed test.
This change removes that hassle for the user.
> Enable ufsIOtest to retrieve configuration from a mount point

- core/base/src/main/java/alluxio/exception/ExceptionMessage.java
- job/common/src/main/java/alluxio/job/plan/migrate/MigrateConfig.java
- job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java
- job/server/src/test/java/alluxio/job/plan/migrate/MigrateDefinitionRunTaskTest.java
- job/server/src/test/java/alluxio/job/plan/migrate/MigrateDefinitionSelectExecutorsTest.java
- shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
- tests/src/test/java/alluxio/job/plan/migrate/MigrateIntegrationTest.java
DistributedCp and DistributedMv now no longer needs the complicated folder to folder operation and now only handles file to file. Removing a bunch of code that does folder to folder work.
> Simplify MigrateDefinition

- core/server/worker/src/main/java/alluxio/worker/block/UfsInputStreamCache.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/block/UfsInputStreamCacheTest.java
- core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockReaderTest.java
Re-introduce the stream cache, removed in https://github.com/Alluxio/alluxio/commit/9fc3a7dac72be6909cf0286527f1e34645999a22.
This version is very similar to the previous one, but is more concurrent, without global locks.
> Implement concurrent ufs input stream cache

- core/common/src/main/java/alluxio/underfs/UnderFileSystemFactoryRegistry.java
- integration/tools/validation/src/main/java/alluxio/cli/UfsVersionValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/ValidateEnv.java
This new task helps expose some more information about available UFS versions to users. The cases for configuration and corresponding outputs are defined below.
- UFS version not configured: skip validation
- UFS version configured, but doesn't exist in list of valid versions: error with info and list of available versions
- UFS version configured, but list of versions empty: this indicates the UFS doesn't support versioning (i.e. non-HDFS), and directs the user to change configuration
- UFS version configured and exists in available version list: success
> Add UFS version validation task

- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
- dev/scripts/src/alluxio.org/build-distribution/cmd/root.go
#12491
In last PR, I'm sorry that, I tested it in intellij go build debug launcher, so it can works, like the following
```bash
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/mbl/projects/github/alluxio-2/dev/scripts #gosetup
/usr/local/go/bin/go build -o /private/var/folders/hj/jty18sr93t3_cbkb01szbv3w0000gn/T/___go_build_main_go -gcflags "all=-N -l" /Users/mbl/projects/github/alluxio-2/dev/scripts/src/alluxio.org/build-distribution/main.go #gosetup
"/Users/mbl/Library/Application Support/JetBrains/IntelliJIdea2020.1/plugins/intellij-go/lib/dlv/mac/dlv" --listen=localhost:63311 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec /private/var/folders/hj/jty18sr93t3_cbkb01szbv3w0000gn/T/___go_build_main_go -- single -skip-ui -debug …
```
> Fix custom ufs module doest not affect issue

- pom.xml
Update oshi version from 4.2.0 to 5.3.5 to solve the jvm crash problem mentioned int #12502.
Fixes #12502
> Update oshi dependency version from 4.2.0 to 5.3.5

- core/common/src/main/java/alluxio/worker/block/BlockStoreLocation.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/allocator/GreedyAllocator.java
- core/server/worker/src/main/java/alluxio/worker/block/allocator/MaxFreeAllocator.java
- core/server/worker/src/main/java/alluxio/worker/block/allocator/RoundRobinAllocator.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockStoreLocationTest.java
- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
This changes `BlockStoreLocation.anyDirInTierWithMedium` to `anyDirInAnyTierWithMedium`. The new name should be easier to understand.
The explanation for method `anyDirInTierWithMedium` is: 
```
/**
* Convenience method to return the block store location representing any dir in any tier
* with specific medium.
*
* @param mediumType mediumType this returned block store location will represent
* @return a BlockStoreLocation of any dir in any tier with a specific medium
*/
```
The new name is more precise. The old name `anyDirInTierWithMedium` makes me think it's one of the directories in a specific tier, that has the specific medium. Rather, it means a directory in ANY tier, with the specific medium.
> [SMALLFIX] Improve block location naming

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
Add a configuration for Ratis retry cache expiry time. This affects the size of the Ratis server retry cache, which can consume a lot of memory if there is a high volume of journal writes in a short period of time.
> Add configuration for Ratis retry cache expiry time

- core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
- core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
- core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java
- core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
- core/server/master/src/main/java/alluxio/master/file/contexts/CheckAccessContext.java
- core/server/master/src/test/java/alluxio/master/file/PermissionCheckTest.java
- core/transport/src/main/proto/grpc/file_system_master.proto
the Hadoop client `access` API is called by Hive to check permission for a table storage location. The default implementation is a simplification of the actual permission check on the Alluxio master and can be inconsistent in many cases. This change implemented the `access` so the same server side permission checker is used to check certain permission regarding an Alluxio location.
> Implement access API for Hadoop client

- integration/tools/pom.xml
Fix the maven release issue introduced by #12452 
`maven release:prepare` showing the following error when directly using `${hadoop.version}` for `alluxio-shaded-hadoop`
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.1:prepare (default-cli) on project alluxio-parent: The version could not be updated: ${hadoop.version}
```
This PR change to use ufs-hadoop profiles to get the shaded hadoop version
> Use profile properties for shaded hadoop version

- docs/en/core-services/Caching.md
This change:
1. Adds Allocator as a section. This is an open interface configuring the allocation strategy, but is not documented.
1. Adds Reviewer as a section. This is a new interface added in 2.4.1.
1. Fixes multiple typos and updates a few doc link formats.
> [DOCFIX] Add Allocator & Reviewer sections to Caching.md

- docs/cn/compute/Flink.md
- docs/en/compute/Flink.md
The Flink documentation was removed a while ago
EN version was lost in https://github.com/Alluxio/alluxio/commit/7c59f07833951131fae9f5a448753c9331714b8f It was not moved to a new address, presumably lost in the doc structure refactor. The history and intention of that commit has lost track.
CN version was removed in https://github.com/Alluxio/alluxio/commit/9cb40db8171c02399fb656525b9caf13eb3f62fc#diff-4f1b02166fb51e7e45ddba897b5926d53bdc5cda08d0a76629a04e1075fdadd5 In order to keep in sync with the EN doc.
This change intends to bring the Flink doc back. Please note that this change does not attempt to keep the Flink doc up-to-date with the current Alluxio. That will be done in a separate PR.
> [DOCFIX] Add flink doc back

- table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java
This submits requests for the partition statistics in batches of partitions, to avoid overflowing the HMS when requesting for tables with a large number of partitions.
> Get a chunk of PartitionColumnStatistics at a time from Hive

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
Fix #12420 When hostname & bind.host not specified, local hostname is chosen as the connect host of the service by default, which may cause an UnknownHostException when the **LOCAL** service hostname cannot be resolved by a **REMOTE** client. This problem can be avoided by specifying alluxio.<service_name>.hostname or alluxio.<service_name>.bind.host using an IP address. But it is really troublesome when deploying lots of nodes with different IP addresses. 
Add alluxio.service.use.ip to support using ip as the connect host when enable.
> Support using IP as connect host

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- shell/src/main/java/alluxio/cli/fs/command/AbstractDistributedJobCommand.java
Increase default active jobs size because this increases performance for smaller file size distributedCp/Load cases without hurting the large files. (The only increased cost is increased memory usage but the memory usage here isn't large.)
> Increase Active Jobs Size for DistributedJobCommands

- docs/_data/table/cn/security-configuration.yml
The default security type in English doc is SIMPLE, but in Chinese is NOSASL.
The authentication mode. Currently three modes are supported: NOSASL, SIMPLE, CUSTOM. The default value SIMPLE indicates that a simple authentication is enabled. Server trusts whoever the client claims to be
The default type is also SIMPLE in code
```
public static final PropertyKey SECURITY_AUTHENTICATION_TYPE =
new Builder(Name.SECURITY_AUTHENTICATION_TYPE)
.setDefaultValue("SIMPLE")
.setDescription("The authentication mode. Currently three modes are supported: "
+ "NOSASL, SIMPLE, CUSTOM. The default value SIMPLE indicates that a simple "
+ "authentication is enabled. Server trusts whoever the client claims to be.")
.setConsistencyCheckLevel(ConsistencyCheckLevel.ENFORCE)
.setScope(Scope.ALL)
.build();
```
> [DOCFIX] Fix error default security type in chinese

- core/server/worker/src/main/java/alluxio/worker/grpc/UfsFileWriteHandler.java
- tests/src/test/java/alluxio/client/fs/io/FileOutStreamIntegrationTest.java
We have been using default `CreateOptions` when creating a UFS file. This can fail in some configuration when a file is written to an Alluxio directory not backed by a UFS one. This change adds the option when UFS file writer creates the UFS file so the directory is created automatically.
https://github.com/Alluxio/alluxio/issues/12621
> Fix creating UFS file without a parent directory

- docs/cn/ufs/COSN.md
- docs/en/ufs/COSN.md
core-site.conf and core-site/properties -> core-site.xml
COS_* -> COSN_* for bucket, data, and region placeholders
> [DOCFIX] Fix naming inconsistencies in COSN docs

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Disable the default jnifuse property to avoid the following exception when mounting alluxio-fuse
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnifuse in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
at java.lang.Runtime.loadLibrary0(Runtime.java:870)
at java.lang.System.loadLibrary(System.java:1124)
at alluxio.jnifuse.AbstractFuseFileSystem.<clinit>(AbstractFuseFileSystem.java:38)
at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:119)
> Disable default jni fuse

- shaded/hadoop/pom.xml
This fixes classloading issue related to erasure coding by making sure the UFS has a private copy of the class.
> Relocate erasure coding

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeLockManager.java
Add Inode lockPool size and edge lockPool size metrics, so that we can monitor the lock pool size.
> Add lock pool metrics

- integration/emr/alluxio-emr.sh
Before this fix, presto would fail to start on emr 5.30 or above due to class conflicts, because we are using alluxio bundled connector. 
Switch to using presto's  built-in connector
> Fix presto initialization error due to alluxio connector

- table/server/master/src/main/java/alluxio/master/table/AlluxioCatalog.java
- tests/src/test/java/alluxio/server/ft/journal/TableMasterJournalIntegrationTest.java
The PR aims to fix the bug that when Alluxio master is restarted, it fails to recognize the `remove_table` journal entry during journal replaying, and stuck there forever.
Fixes #12627
> Add support for handling 'remove_table' journal entry

- core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
Add the debug logging since the actual flush failure will be overwritten by the last meaningless failure like `ratis.protocol.AlreadyClosedException` or `NoMoreRetriesException`.
The actual flush failure will sometimes give us helpful information or annoying meaningless logs, that's why i mark it as debug for now. Will be better to have an exception duplication-checking and only log the no-duplicate exceptions. And also link the exception to meaningful configuration suggestions.
> Add clearer ratis flush exception logging

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
Add ratis configuration so that users can change it when they have larger journal entries (e.g. introduced by Alluxio catalog service).
> Add ratis size related configuration

- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
This change does 2 things:
1. When a tier mgmt task fails because the destination dir is full, it logs a warning instead of error
2. Adds a unit test that verifies a failed tier move issued by a tier mgmt task fail consistently
> Improve logging for tier mgmt task

- core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
This change offers an option to make the Alluxio client NOT throw an exception when the given AlluxioURI is incorrect. Rather, it finds the correct cluster address from the configuration and connects correctly.
Some client has some stale code invoking Alluxio like this:
```
// The cluster just gone through an upgrade, the master address changed
// master1:19998 -> master1:19998,master2:19998,master3:19998
FileSystem fs = FileSystem.Factory.get();
// This path is hard coded in the code
AlluxioURI path = new AlluxioURI("alluxio://master1:19998/path");
// This fails because of BaseFileSystem.checkUri()
fs.listStatus(path);
```
It's very hard to dig all the client code and update them one by one. In the upgrade, the design intention is, the admin configures this …
> Disable authority check

- docs/en/operation/User-CLI.md
- table/server/common/src/main/java/alluxio/table/common/ConfigurationUtils.java
Fix: #12675
The mount option of attachdb differs from docs and code.
> Fix table mount option description in docs to "mount.option."

- core/transport/pom.xml
- pom.xml
#12596 
Introduce https://github.com/salesforce/proto-backwards-compat-maven-plugin to help prevent proto changes which can break backwards compatibility.
This plugin can fail the build when some field in a proto file is removed. Such as:
diff --git a/core/transport/src/main/proto/grpc/table/layout/hive/hive.proto b/core/transport/src/main/proto/grpc/table/layout/hive/hive.proto
index 538fbe02a0..829ed6f023 100644
--- a/core/transport/src/main/proto/grpc/table/layout/hive/hive.proto
+++ b/core/transport/src/main/proto/grpc/table/layout/hive/hive.proto
@@ -28,7 +28,6 @@ message SortingColumn {
ASCENDING = 0;
DESCENDING = 1;
}
required SortingOrder order = 2;
}
The plugin will trigger a build failure for notification:
[INFO] BUILD FAILURE
[INFO] …
> Add maven plugin for proto lock

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalWriter.java
- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalWriterTest.java
There are always chances that some new big journal entries are added unexpectedly which violates the underlying assumption of the raft implementation. 
This PR reduces the possibilities of flushing a single big journal entry by introducing journal size check and flush when reach journal batch size.
> Flush when written journal reach to the given batch size

- integration/fuse/pom.xml
other integrations may also have a similar `native` profile. renaming to `fuse-native` to distinguish
> Rename native flag for fuse to fuse-native

- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
Avoid throwing RuntimeException when hostname is not resolved on metrics reporting
Fix: https://github.com/Alluxio/alluxio/issues/12672
> Avoid RuntimeException for unresolved hostname during metrics reporting

- core/server/master/src/main/java/alluxio/master/journal/tool/JournalTool.java
- core/server/master/src/test/java/alluxio/master/journal/tool/JournalToolTest.java
The journal dumper is broken when running against non-local UFS journal like HDFS.
The inputDir was new File(HDFSUri).getAbsolutePath() which is invalid.
> Fix ufs journal dumper input directory

- core/base/src/main/java/alluxio/util/io/PathUtils.java
- core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
- core/server/master/src/test/java/alluxio/master/file/PersistenceTest.java
Currently, Alluxio writes the temporary file of async persistence to the path, which is the same as the destination file path. The computing framework, like presto, will pick up the tmp files, which is leftover there for some reason, fail to clean up, etc.
This change writes the tmp file of async persistent to the sub dir of the mount point.
> Write async persistent tmp file to sub-directory of mount point

- docs/_data/table/Alluxio-FUSE-parameter.csv
- docs/_data/table/en/Alluxio-FUSE-parameter.yml
- docs/en/api/POSIX-API.md
And JNI-Fuse general usage docs for choosing between two POSIX API implementation, installation, and configuration.
> [DOCFIX] Add JNI-Fuse general usage docs

- docs/en/operation/User-CLI.md
- table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java
- table/server/underdb/hive/src/main/java/alluxio/table/under/hive/Property.java
This PR aims to add an Hive UDB option in `table attachdb` command, to allow mounting partitions in Hive tables that don't share the same location prefix with that of the table.
Fixes #12651
> Add 'attachdb' option for mounting diff prefix partitions

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/test/java/alluxio/ConfigurationTestUtils.java
- core/server/common/src/main/java/alluxio/master/StateLockManager.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/test/java/alluxio/master/journal/JournalContextTest.java
- tests/src/test/java/alluxio/client/fs/io/FileOutStreamIntegrationTest.java
This PR disables the interruption threads once we give up on the back up process. Previous behavior causes all future RPCs to fail because it is not able to obtain shared state lock.
This PR also updates the default value for alluxio.master.lost.worker.file.detection.interval to 5mins from 10secs.
> Fix backup lock acquisition

- core/server/worker/src/main/java/alluxio/worker/block/AsyncBlockRemover.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockLockManager.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/AsyncBlockRemoverTest.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockLockManagerTest.java
aim to fix the symptom of #12444 and #11309
Use `tryLock()` instead of `lock()` when locking worker blocks to prevent forever waiting for block locks.
and replace https://github.com/Alluxio/alluxio/pull/12507/files
This PR fixes the symptom of frozen AsycBlockRemover caused by failing block lock acquisition by using tryLock.
> Prevent removeBlock from waiting indefinitly

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/StateLockManager.java
- core/server/master/src/main/java/alluxio/master/backup/BackupLeaderRole.java
- core/server/master/src/main/java/alluxio/master/backup/BackupWorkerRole.java
Currently delegated backup would timeout on suspend when the primary master takes long time to acquire exclusive lock during busy hours. This change adds a function in state lock manager to allow suspend of journal before every retry of lock, which should greatly improve the chance of keeping secondary master ready during the locking stage.
> Fix backup suspend timeout

- webui/master/src/store/metrics/reducer.tsx
- webui/master/src/store/metrics/test/reducer.test.tsx
Issue: metric graphs were always showing the first 24 data points. This small fix makes sure to show the latest 20 items (to match the comment stating `// only push the latest 20 points of data`)
> Show the latest 20 data points for Web UI Metrics graphs

- job/server/src/main/java/alluxio/job/plan/stress/StressBenchDefinition.java
Previously, `toMap()` can produce configurations with values set to null, which causes errors when parsing the configuration. 
Now we use a safer `getMountSpecificConf` to obtain the configurations that we need.
> Fix speedtest for s3

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Fixes a race condition where if a file is scheduled for async persist changes in between submitting the async persist request and starting the async persist request, the wrong data will be written for the original file.
I was able to reproduce this consistently with a unit test and adding a timing delay to the job service.
Not including the test because it would require a hook in the job service for timing delays, perhaps this is something we can add in the future when we have a framework for controlling timings between different services.
For reference the test:
```
@Test
public void persistMultiRename() throws Exception {
String testFilePath = "/testPersist/multiRenameTestFile";
FileSystemTestUtils.createByteFile(sFileSystem, testFilePath, WritePType.MUST_CACHE, 2); …
```
> Address race condition for async persist

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/MasterJournalContext.java
- core/server/common/src/main/java/alluxio/master/journal/raft/LocalFirstRaftClient.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
Existing Alluxio master with embedded journal will attempt to write to the quorum even after it stepped down in various failure situation, journaling a bunch of inconsistent master states as a result. Even though the new master has a catchup process to wait for these journal entries before serving request, there is a chance for the old leader to send it after the period ends and corrupt the journal.
This change updates the journal writer to only write to local raft server by default. This should prevent any remote write request from an old leader at the cost of some temporary request failures during the fail over.
> Prevent leader from writing to embedded journal after stepping down

- pom.xml
Bump version of proto-backwards-compatibility plugin to 1.0.6 to support ARM64 platform
> Bump version of proto-backwards-compatibility plugin to 1.0.6

- shell/src/main/java/alluxio/cli/fs/command/AbstractDistributedJobCommand.java
- shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
- shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
Commands like distributedLoad and distributedCp submits jobs to the cluster job service. The command creates 1 job for each file. By default the command allows up to 3000 jobs to be submitted and waiting for completion. When there are many distributedLoad/Cp commands running by many users, there may be too many jobs in the queue for the job service.
This change intends to add a way to throttle the job submission speed at the command side. Especially when the distributedLoad/Cp jobs are submitted with automated scripts, we may want less than 3000 jobs to run with each command. Maybe find a balance between speed and resource claim, like 1000 or 500.
Volume control on Alluxio job service is beyond the scope of this PR.
Example:
```
$ bin/alluxio fs distributedLoad --job-count 1000 / …
```
> Add an option for active job count

- core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java
When the worker has a large number of blocks the request can be big for worker register and block heartbeat. Adding a little debug log for better traffic visibility.
> [SMALLFIX] Add debug log on BlockMaster request size

- integration/docker/entrypoint.sh
The current logic includes extra variables such as `PATH` or `HOSTNAME` due to regex matching
> Fix false positives in dockerfile env.sh

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
two improvements:
1. Added new counter "Client.CachePutInsufficientSpaceErrors" indicating the failed put due to insufficient space made after eviction attempts.
2. Remove unnecessary cleanup which may artificially bump error counters
3. Remove unnecessary directory cleanup which has potential race condition to fail put unnecessarily
> Cleanup counters in local client cache

- pom.xml
Current version of leveldbjni dependency cannot support ARM64 platform,
this change bump the version to 5.18.4 to support ARM64 platform.
A special rocksdbjni version for aarch64 has been released by rocksdb community. [1][2]
[1] https://github.com/facebook/rocksdb/releases/tag/v5.18.4
[2] facebook/rocksdb#6250
Fix #12818
> Bump the version of leveldbjni to 5.18.4 to support ARM platform

- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
Many calls to TieredBlockStore.allocateSpace comes from TieredBlockStore.requestSpace either through 
"ShortCircuitBlockWriteHandler -> DefaultBlockWorker" or
"UnderFileSystemBlockReader"
(Block Expansion)
All usages of this has forceLocation true and evictionAllowed true.
So instead of https://github.com/Alluxio/alluxio/pull/12486 having the effect of using lower tier storage probabilistically. The code instead probabilistically evicted more things in the first tier leading to more churn.
> Do not have the ProbalisticReviewer unnecessarily reject

- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
Creating ForkJoinPool with unreasonable arguments will lead to IAE without a message, which is confusing. The logic is below:
```
package alluxio.concurrent.jsr;
public ForkJoinPool(int parallelism, ForkJoinWorkerThreadFactory factory,
UncaughtExceptionHandler handler, boolean asyncMode, int corePoolSize, int maximumPoolSize,
int minimumRunnable, Predicate<? super ForkJoinPool> saturate, long keepAliveTime,
TimeUnit unit) {
// check, encode, pack parameters
if (parallelism <= 0 || parallelism > MAX_CAP || maximumPoolSize < parallelism
|| keepAliveTime <= 0L)
throw new IllegalArgumentException();
```
Before:
```
2021-02-04 12:19:29,867 ERROR ProcessUtils - Uncaught exception while running Alluxio master @localhost:19998, stopping it and exiting. Exception …
```
> Avoid IllegalArgumentException without message from ForkJoinPool

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
`System.currentTimeMillis()` can return incorrect time, and InodeSyncStream can return negative elapsed time for a sync job.
This changes time calculation to use Java 8 new time implementation for precision and thread safety.
Ref: https://stackify.com/heres-how-to-calculate-elapsed-time-in-java/
> Fix incorrect time calculation in InodeSyncStream

- job/server/src/main/java/alluxio/master/AlluxioJobMasterRestServiceHandler.java
- job/server/src/main/java/alluxio/worker/AlluxioJobWorkerRestServiceHandler.java
- shell/src/main/java/alluxio/cli/LogLevel.java
`logLevel` command currently only works for master and workers. This change enables the command to set log level on job master/workers.
> Support logLevel for job master/worker

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
For the existing code of `AlluxioJniFuseFileSystem`, it use a `2048` ReadWrite lock pool as the guards for each fd, there are 3 reason why I purpose to remove it by a double check.
- Reduce the heap memory for the `LOCK_SIZE`, now the constant is `2048`, so the reason seems too weak.
- We can only have 2048 lock in the same time, if there are more other unrelated files operation, they will hang for waiting lock resource other then acquire lock.
- `2048` is a hard code here, and we can use double check to replace these unnecessary locks, this PR will clear the code.
- Synchronized block is recommend to use if we have no strong reason to use `ReentrantReadWriteLock`. We don't use the readlock at all, we also don't use fair lock. So, to simplify code, we'd better to replace it.
> Replace lock to double check to reduce heap memory cost

- integration/docker/Dockerfile
- integration/docker/Dockerfile.fuse
Add profiler(https://github.com/jvm-profiling-tools/async-profiler) to docker image for further investigation on performance bottleneck.
Signed-off-by: cheyang <cheyang@163.com>
> Add async-profiler to docker images

- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/jnifuse/AbstractFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/jnifuse/LibFuse.java
- integration/fuse/src/main/native/libjnifuse/jnifuse_helper.cc
Without this feature, create file could be failed caused by that both the owner and group are all 0 from the mock fuse context, and non-root user have no permission to change owner and group.
> Support get_fuse_context for JNI-fuse

- core/common/src/main/java/alluxio/AbstractClient.java
Before:
```
$ bin/alluxio fs ls /
Failed to connect to FileSystemMasterClient @ localhost:19998 after 8 attempts
```
After:
```
$ bin/alluxio fs ls /
Failed to connect to master (localhost:19998) after 8 attempts of FileSystemMasterClient
```
> Improve error message on connection failure

- docs/en/overview/Getting-Started.md
The default behavior has been changed to `ASYNC_THROUGH` so the user no longer needs to run `./bin/alluxio fs persist`. I also added some additional steps using `./bin/alluxio fs free` to demonstrate the caching.
> [DOCFIX] Adjust steps in en/overview/Getting-Started.md

- docs/en/operation/Remote-Logging.md
Besides some small wording improvements, this adds 2 corrections:
1. BOTH `ALLUXIO_LOGSERVER_HOSTNAME` and `ALLUXIO_LOGSERVER_PORT` MUST be set to make the remote logger active
2. The client remote logger needs some more params to work
> [DOCFIX] Improve remote-logging doc

- core/common/src/main/java/alluxio/conf/PropertyKey.java
When running Alluxio client in a environment without com.sun.management, an UnsatisfiedLinkError will be thrown. The current code only catches `Exception` so not able to catch `UnsatisfiedLinkError`.
Also the current implementation can give incorrect ram disk size in a containerized environment. Improve the description to reflect that.
Related to https://github.com/Alluxio/alluxio/issues/12882
> Catch UnsatisfiedLinkError for alluxio.worker.ramdisk.size, improve desc

- docs/en/operation/Basic-Logging.md
- docs/en/operation/User-CLI.md
- shell/src/main/java/alluxio/cli/LogLevel.java
This addresses some missing points in https://github.com/Alluxio/alluxio/commit/0c72e4e63688dbee776b24139f86cf2b495150cd
1. Add relevant doc mentioning the job master and job workers are now supported
2. Improve the relevant doc
3. When `--target` is not specified, all targets should include the job master and job workers
4. Identified a few issues in the `logLevel` command. Added TODOs for further PRs to resolve.
> Update logLevel help message and related doc etc

- docs/en/operation/Basic-Logging.md
1. Some classes like `InodeSyncStream` uses TRACE level log, mention that.
2. Add a way to add a separate logger for certain classes. This can be helpful in many scenarios.
> [DOCFIX] Improve Basic-Logging doc

- core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerImpl.java
- core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
PR3 for #12830
Move asyncCache logics to DefaultBlockWorker so that it can be called by both internal client and outside gRPC client.
> Move asyncCache logics to DefaultBlockWorker

- core/server/common/src/main/java/alluxio/master/journal/MergeJournalContext.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/test/java/alluxio/master/journal/JournalContextTest.java
Before this change, syncMetadata writes an inode journal entry and then
two additional updateInode entries to complete the file. This combines
three entries into one so that we do not have a failure mode where the
first inode entry is inserted and incomplete files are left behind.
pr-link: Alluxio/alluxio#12875
change-id: cid-bdfcf60239984c608870b47f50a9c3e74f4c1b9f
> Combine createFile and completeFile when sync metadata

- docs/en/deploy/Running-Alluxio-On-a-Cluster.md
Updated from the deprecated `./bin/alluxio formatMaster` to `./bin/alluxio formatMasters`, added some reference links, and adjusted some wording.
> [DOCFIX] Update single-master Alluxio cluster docs

- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
- dev/scripts/src/alluxio.org/build-distribution/cmd/root.go
Support multiple custom versions of hadoop when tarballing with the generate-tarball.sh
#12406 only support single hadoop version.
> Support multiple custom versions of hadoop by generate-tarball

- docs/en/compute/Spark-On-Kubernetes.md
The default k8s API server port is (for recent version of Kubernetes) 6443, not 8443.
This PR also adjusts and adds notes.
> [DOCFIX] Adjust Spark on Alluxio in K8s docs

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- tests/src/test/java/alluxio/client/fs/UfsSyncIntegrationTest.java
Before this change, if any path was successfully synced, we return success from syncMetadata. 
After this change, we only return success if there was no failures and all paths have been synced without interruption.
This also fixes an issue where an interrupted syncmetadata is considered synced by the file system master and will not be synced again until sync interval passes.
> Report error if any of the sync paths failed in syncMetadata

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
Skip creating parent directory for object stores to improve performance. 
Passed UFS contract tests and other object store related tests.
> Skip object store parent creation

- docs/en/deploy/Running-Alluxio-On-Kubernetes.md
I added a section to point users towards the configuration steps for Alluxio workers. Without configuring/disabling Alluxio worker short-circuit access, the Worker Pods will never start.
> [DOCFIX] Clarify steps to configure Alluxio on k8s

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
- docs/en/operation/Basic-Logging.md
Add information on UFS call logging:
(1) time elapsed for each UFS call
(2) add a new flag to control log UFS calls that takes time longer than defined threshold.
> Add logging on slow UFS calls

- docs/en/operation/User-CLI.md
- `format`: commented out incorrect description
- `formatMaster`: refactored as `formatJournal`
- added `formatMasters`
- `job`: added `-- cancel <id>` to usage description
- `runTests`: added `runTest`
- `copyDir`: updated description to include `conf/masters`
- `version`: added `-r, revision` to usage description
- `checkConsistency`: added `-t` flag
- `copyFromLocal`: added flags
- `copyToLocal`: added flags
- `count`: added `-h` flag
- `cp`: added flags
- `du`: added `-g` flag
- `free`: added `-f` flag
- `getSyncPathList`: added this new command
- `persist`: added flags
- `setfacl`: added flags
- `startSync`: added this new command
- `stopSync`: added this new command
- `updateMount`: added this new command
- No changes
> [DOCFIX] Update User CLI documentation

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/BackupManager.java
Support to skip corrupt journal entry when recovering from backup, similar to the implementation in `alluxio.master.journal.raft.BufferedJournalApplier#applyToMaster`.
We can configure `alluxio.master.journal.tolerate.corruption` to control whether it is enabled or not.
Fix https://github.com/Alluxio/alluxio/issues/12959
> Support to skip corrupt journal entry when recovering from backup

- conf/alluxio-site.properties.template
This is a follow-up to PR #12871 where the "Getting Started" doc was adjusted to reflect the `alluxio.user.file.writetype.default` value changed from `MUST_CACHE` to `ASYNC_THROUGH`. 
- This default value can be seen in [PropertyKey.java](https://github.com/Alluxio/alluxio/blob/master/core/common/src/main/java/alluxio/conf/PropertyKey.java#L2117)
> [DOCFIX] Adjust alluxio-site.properties.template to use ASYNC_THROUGH

- core/common/src/main/java/alluxio/metrics/MetricKey.java
Add per minute description to cluster throughput metrics.
Cluster throughput metrics are calculated by (total cluster bytes / minutes lasted)
> Add per minute description to cluster throughput metric

- integration/fuse/bin/alluxio-fuse
[`jps`](https://docs.oracle.com/javase/7/docs/technotes/tools/share/jps.html) is part of the JDK, but not of the JRE. By removing this dependency and only relying on `ps` Alluxio FUSE can be run with Java JRE, which is much lighter than the JDK.
Another reason to remove the `jps` depencency is that the jps documentation mentions that:
> _NOTE: This utility is unsupported and may not be available in future versions of the JDK._
I tested this with both OpenJDK 8 JRE and OpenJDK 11 JRE.
> Remove dependency on Java JPS

- integration/docker/Dockerfile.fuse
The current image deletes the FUSE JNI libraries resulting in an error: https://github.com/Alluxio/alluxio/issues/13052
Keep the FUSE JNI libraries in the image.
> Keep FUSE JNI libraries in image

- docs/en/deploy/Running-Alluxio-On-Docker.md
The current tutorial is broken as documented in https://github.com/Alluxio/alluxio/issues/12943 .
The `docker run` command to run the alluxio-fuse image was missing `--security-opt apparmor:unconfined` to allow it to create mounts. This fixes the tutorial.
Fix https://github.com/Alluxio/alluxio/issues/12712
Fix https://github.com/Alluxio/alluxio/issues/12943
> [DOCFIX] Add security opt parameter to run the FUSE docker image

- docs/en/deploy/Running-Alluxio-On-Docker.md
The command to ensure the bind-mounted directory on the host is created with the right permissions was still absent from the documentation. Otherwise following the tutorial could give a `Permission denied` error when trying to create the FUSE mount in the bind-mounted volume.
See also this comment: https://github.com/Alluxio/alluxio/issues/12943#issuecomment-786817860
> [DOCFIX] Create host mount in Docker FUSE documentation

- job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java
Sometimes, source file is not available at the time of migrate. Do not create target file in that case.
> Open the source file before creating target file during migrate

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Remove unused String constant USER_BLOCK_WORKER_CLIENT_READ_RETRY in PropertyKey.java
Fixes Alluxio/new-contributor-tasks#571
> [SMALLFIX] Remove unused Strings constant in PropertyKey.java

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Unused String constant USER_BLOCK_WORKER_CLIENT_POOL_SIZE in PropertyKey.java is removed.
Fixes Alluxio/new-contributor-tasks#570.
> [SMALLFIX] Remove unused String constant in PropertyKey.java

- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
The `disableurivalidation` variable name is the opposite of its meaning.
> [SMALLFIX] Fix variable name with incorrect meaning

- core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java
- core/client/fs/src/main/java/alluxio/client/block/stream/BlockOutStream.java
- core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java
- core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java
- core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java
- core/client/fs/src/main/java/alluxio/client/block/stream/UfsFallbackLocalFileDataWriter.java
- core/client/fs/src/test/java/alluxio/client/block/stream/LocalFileDataWriterTest.java
- job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java
- job/server/src/main/java/alluxio/job/plan/replicate/ReplicateDefinition.java
- job/server/src/main/java/alluxio/job/util/JobUtils.java
- job/server/src/test/java/alluxio/job/plan/replicate/ReplicateDefinitionTest.java
In issue #13005, `distributedLoad` failed due to reserving too much space (e.g., 128MB space reserved just for loading 300KB files). 
When write concurrency is high, it can take a lot of wasted space and possibly causing `distributedLoad` failed.
This PR
1. makes better estimation on DataWriter to reserve bytes 
2. optimizes the performance of `distributedLoad` by reducing master RPCs by moving `getStatus` call out of loop
Fix https://github.com/Alluxio/alluxio/issues/13005
> Allocate real blockSize when loading files for distributedLoad

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
- integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
- integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml
When using Alluxio worker in Kubernetes, the Daemonset template mounts the directory `/opt/domain`. However previously when doing so the worker would crash with the following error:
```
2021-03-13 00:32:55,274 INFO  GrpcDataServer - Alluxio worker gRPC server started, listening on /0.0.0.0:29999
2021-03-13 00:32:55,275 INFO  AlluxioWorkerProcess - Domain socket data server is enabled at /opt/domain/b7f2d035-e081-4a55-a9d3-a87351d8daad.
2021-03-13 00:32:55,281 WARN  RetryUtils - Failed to Starting gRPC server (attempt 1): java.io.IOException: Failed to bind
2021-03-13 00:32:55,482 WARN  RetryUtils - Failed to Starting gRPC server (attempt 2): java.io.IOException: Failed to bind
2021-03-13 00:32:55,883 WARN  RetryUtils - Failed to Starting gRPC server (attempt 3): java.io.IOException: …
```
> Move container level securityContext to pod level

- core/common/src/main/java/alluxio/extensions/ExtensionsClassLoader.java
Some extensions perform resource loading during initialization which can fail in the URLClassLoader logic. This change adds a fallback logic to look for resource in the default class loader.
> Add resource loading fallback logic to ExtensionClassLoader

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Property `alluxio.user.block.remote.read.buffer.size.bytes` is only used by tests. Hide it in the doc.
> [SMALLFIX] Hide test only property

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java
- core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
- core/server/master/src/main/java/alluxio/master/file/meta/NoopUfsAbsentPathCache.java
- core/server/master/src/main/java/alluxio/master/file/meta/UfsAbsentPathCache.java
- core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
- core/server/master/src/test/java/alluxio/master/file/meta/AsyncUfsAbsentPathCacheTest.java
- core/server/master/src/test/java/alluxio/underfs/UfsStatusCacheTest.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java
Cherry-pick  committed PR #12956 into target branch branch-2.3
-----------
Add a time stamp to indicate last refreshed time on the absent cache
entries.
Use absent cache to avoid UFS accesses when possible in the metadata
sync and load Metadata processes.
Added more comprehensive integration tests that ensures the number of
accesses to the UFS through SleepingUnderFileSystem and unit tests for
the absent cache.
fixes #12833 because now instead of checking /a, /a/b, /a/b/c for non
existent directories, we will only access the UFS once for /a because of
absent cache. We know /a/b, /a/b/c can not exist on the UFS.
Co-authored-by: David Zhu <david@alluxio.com>
pr-link: Alluxio/alluxio#12956
change-id: cid-1c836c95416214ca0256a0d62feafe78d7cf8489
> Fix regression in AbsentUfsPathCache

- core/common/src/main/java/alluxio/util/io/FileUtils.java
- integration/fuse/bin/alluxio-fuse
- integration/fuse/src/main/java/alluxio/fuse/StackFS.java
- integration/fuse/src/main/java/alluxio/fuse/StackMain.java
Support StackFS operations with alluxio-fuse script
```
$ integration/fuse/bin/alluxio-fuse mount -s fuseMount fuseBeMounted
Starting StackFS process: mounting src local path "fuseBeMounted" to dst local path "fuseMount" with options="-obig_writes"
$ integration/fuse/bin/alluxio-fuse stat
pid	mount_point	source_path
94231	fuseMount	fuseBeMounted
$ integration/fuse/bin/alluxio-fuse umount fuseMount
Unmount fuse at fuseMount (PID: 94231).
```
Support write related operations in StackFS.
> Support write,chmod,chown,rename in StackFS

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Each Inode Cache entry takes up about 300 ~ 350 bytes. So a 10 million default max size is already 3 ~ 3.5 GB when full.
This is also not accounting for the EdgeCache which has the same default max size as inode cache and while smaller than inode cache in average. Isn't that much smaller.
> Reduce default inode cache size

- core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java
- core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerDataReader.java
- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerDataWriter.java
- core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java
- core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
- core/client/fs/src/test/java/alluxio/client/block/stream/BlockInStreamTest.java
- core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java
- core/common/src/main/java/alluxio/util/io/BufferUtils.java
- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/common/src/main/java/alluxio/worker/block/io/DelegatingBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/FuseManager.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/grpc/BlockReadHandlerTest.java
- core/server/worker/src/test/java/alluxio/worker/grpc/BlockWriteHandlerTest.java
- job/server/src/test/java/alluxio/job/plan/replicate/ReplicateDefinitionTest.java
- shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
- tests/src/test/java/alluxio/client/fs/UfsSyncIntegrationTest.java
- Rename `BlockInStreamSource` to be `PROCESS_LOCAL` and `NODE_LOCAL`
- Remove `BlockWorker.closeBlockReader` (newly added) and make the cleanup logic into `BlockReader.close`
- Rename  `BlockWorker. submitAsyncCacheRequest` (newly added) to `BlockWorker.asyncCache` for simplicity
- Share the same `fsContext` among `FuseManager` and `AsyncCacheRequestManager`
- Remove `BlockWorker.unlockBlock(sessionId, blockId)` -- no more necessary
- Combine `BlockWorker.openUfsBlock` to `BlockWorker.createUfsBlockReader` and put cleanup logic into this block reader's `close` method.
- Put `unlock` logic to the `close` method of `LocalBlockReader`
> Improve Worker Interface and implementation

- integration/fuse/bin/alluxio-fuse
StackMain required fuse mount options to be passed in "-obig_writes -okernel_cache" format.
Modify the alluxio-fuse script to match the requirement
> Fix StackFS mount options in alluxio-fuse script

- core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- tests/src/test/java/alluxio/client/fs/io/FileOutStreamIntegrationTest.java
Fixes https://github.com/Alluxio/alluxio/issues/13128
When this guard is added the issue does not happen anymore.
The trade-off is, when we `getFileInfo` on a file that is currently being written, the number of `BlockId` and `FileBlockInfo` we get will mismatch. I don't think that is a problem.
> Update FileInfo when the file is committed

- docs/cn/compute/Hive.md
When I followed the steps in the documentation to create the U_USER table, I found that I cannot read the U_USER table in Hive. But, I could see the table when I set the format of the U_USER table to textfile.
> [DOCFIX] Add Hive file storage format as textfile

- docs/cn/deploy/Running-Alluxio-On-Kubernetes.md
There is a problem in Kubernetes documents, and the title cannot be displayed normally.
This is normal in English documents：
> [DOCFIX] Fix Kubernetes cn document formatting issues

- core/server/common/src/main/java/alluxio/master/journal/AbstractJournalProgressLogger.java
- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalProgressLogger.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointThread.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalProgressLogger.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalReader.java
This change adds some new logging messages to the master while
replaying the  journal. Specifically, it will now log the rate of
journal entries applied to the state machine during the startup process.
The number of entries in a particular interval are logged along with the
current commit index and the expected entries remaining and estimated
time left.
In the embedded journal Instead, we use the Ratis "Commit Index"
which represents batches of journal entries applied to the raft log. We are
able to get the last commit index as well as track the most recently
applied index which gives us the ability to provide the estimated time
remaining. The last SN is more readily available in the UFSJournal
since we control that implementation.
A new function for the UfsJournalReader needed to be …
> Add replay statistics for journal startup

- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java
When doing a quick restart of an alluxio master process with RocksDB, the previous RocksDB may not have been fully cleared yet if the previous process didn't terminate gracefully. Add a timeout around connection so the previous connection lock times out before.
> Add RocksDB.open retry logic

- docs/en/ufs/HDFS.md
Added the `alluxio.master.mount.table.root` prefix for clarity and a relative link to HDFS version mounting.
> [DOCFIX] Adjust Alluxio properties for HDFS

- integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl
`alluxio.logserver.secretVolumeMounts` in `_helpers.tpl` has wrong space Indent. If use hadoop config, it will report this error:
```
Error: YAML parse error on alluxio/templates/logserver/deployment.yaml: error converting YAML to JSON: yaml: line 69: did not find expected key
```
Now, try to fix this.
> Fix helm-chart logserver secretVolumeMounts space Indent

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
- core/server/master/src/test/java/alluxio/master/ControllablePrimarySelector.java
- docs/en/operation/Journal.md
The code changes here are relatively simple. When the
FaultTolerantAlluxioMasterProcess changes state from primary to
secondary, then instead of switching states and continuing operation, we
should trigger the JVM to exit instead.
The reasoning behind this change is that the implementation to clean up
between state changes is not sound and leaves additional resources
hanging around which accumulate if enough state changes occur.
Defaulting to this behavior places the restart responsibility elsewhere,
but guarantees a clean slate and no resource leaks upon startup.
This is implemented with little change by simply placing a call to
stop() once the primary selector changes to the SECONDARY state
within the FTAMP. A simple new test is added to verify this behavior
The behavior by default is …
> Add configuration to stop master process on demotion

- core/server/worker/src/main/java/alluxio/worker/block/BlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/meta/DefaultStorageDir.java
- add info logging for each storage dir on init, which will be very useful for debugging worker tiered storage
- prevent duplicated error info in worker.log as seen in the following. The same error caused two logging messages, one in tiered block store and on in blockwritehandler. This is because previous code catches an exception from allocator, log it and returns null, then in its caller, based on null, another exception is created and thrown.  This PR simply keep the original exception from allocator.
- remove `freeSpace`  from `BlockWorker` interface as no external callers depend on this
```
021-03-23 03:39:52,791 ERROR TieredBlockStore - Allocation failure. Options: AllocateOptions{Location=BlockStoreLocation{TierAlias=MEM, DirIndex=0, MediumType=MEM}, Size=335544320, …
```
> Improve tiered storage related logging

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/conf/RemovedKey.java
- core/server/worker/src/main/java/alluxio/worker/grpc/AbstractWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockReaderTest.java
- tests/src/test/java/alluxio/client/fs/io/UfsFallbackFileOutStreamIntegrationTest.java
- tests/src/test/java/alluxio/server/tieredstore/TierPromoteIntegrationTest.java
- tests/src/test/java/alluxio/server/tieredstore/TieredStoreIntegrationTest.java
Fix https://github.com/fluid-cloudnative/fluid/issues/633,
When property `alluxio.worker.file.buffer.size` is set to a large value (e.g., 320MB in that case),
`distributedLoad` or writing large files may fail often due to each block is allocating  such a big space (compared to much smaller block size 16MB really needed in https://github.com/fluid-cloudnative/fluid/issues/633)
On the other hand, the reserved bytes is calculated on block size today accurately and efficiently, 
https://github.com/Alluxio/alluxio/blob/c939e33a5ca3c4decd27fe7b6080a0feb82d3b9d/core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java#L131 
asking users to configure this property serves no purpose. Therefore we don't need to take the risk of misconfiguration by users.
This PR removed this …
> Remove property of server-side buffer size when writing blocks

- integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
If `env` is set for the master, the space indentation of the current helm template is not aligned with the context. So that helm will report error like this:
```
Error: YAML parse error on alluxio/templates/master/statefulset.yaml: error converting YAML to JSON: yaml: line 81: did not find expected key
```
This PR try to fix the space Indent in `master/statefulset.yaml`
> Fix helm-chart master statefulset.yaml env space Indent

- core/common/src/main/java/alluxio/conf/PropertyKey.java
In light of some recent findings with Presto concurrency, updating the pool max can save users some trouble with hitting concurrency bottlenecks with high load clients (e.g. Presto Coordinator split-loading)
> Update default client pool size to accommodate more concurrent computes

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java
Previously, when we only list one level of directory, we still add the children to the workqueue and prefetch children's children from ufs.  That is not necessary. 
This fixes that issue.
> Reduce unnecessary prefetching in metadata sync

- pom.xml
- underfs/s3a/pom.xml
The aws sdk version currently is 1.11.215 which is more than 4 yrs old. This PR upgrades it to 1.11.815 which has enhanced DefaultAWSCredentialsProviderChain. This adds credentials to be received from web-identity-token file.
Refer [aws sdk documentation](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html ) for more details.
> Upgrade aws-sdk version

- core/common/src/main/java/alluxio/util/CommonUtils.java
This changes `System.getCurrentTimeMillis()` to use Java 8 new time implementation for better precision thread safety. Many classes are using `CommonUtils.getCurrentMs` to calculate time elapsed. So we should move to this new implementation for better calculation precision.
Ref: https://stackify.com/heres-how-to-calculate-elapsed-time-in-java/
> Change System.getCurrentTimeMillis to Instant.now().toEpochMilli()

- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
This PR prevents breadcrumbs from being recreated everytime we issue a listStatus request. 
The main idea is to check for breadcrumb's existence before creating it and only create it when a directory is listed not when it is listed as a child of another directory.
> Reduce unnecessary creation of breadcrumbs

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
- integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
In k8s 1.19+ , `hostPathType` needs to be more accurate, otherwise the following error will be reported:
```
MountVolume.SetUp failed for volume "alluxio-fuse-device" : hostPath type check failed: /dev/fuse is not a file
```
In Node use `file` command to check `/dev/fuse` type:
```shell
$ file fuse
fuse: character special (10/229)
```
So that Maybe we should change `hostPathType` from  `File` to `CharDevice`
> Fix helm-chart fuse hostpath type from File to CharDevice

- tests/src/test/java/alluxio/client/cli/fs/AbstractFileSystemShellTest.java
Motivated by test results https://github.com/Alluxio/alluxio/pull/13215/checks?check_run_id=2328363200
```
Error: 6.229 [ERROR] alluxio.client.cli.fs.command.RmCommandIntegrationTest  Time elapsed: 72.654 s  <<< ERROR!
java.lang.NullPointerException
at alluxio.client.cli.fs.AbstractFileSystemShellTest.afterClass(AbstractFileSystemShellTest.java:132)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at …
```
> Prevent NPE for AbstractFileSystemShellTest

- core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
In `InodeTreePersistentState` we return a `Collections.unmodifiableSet` wrapped around the pinned list. Then in `InodeTree` we create a HashSet copy from it yet again. This is redundant.
Eventually the `getPinnedFileIds` call should be changed to a list-watch mechanism where the worker lists all the pinned IDs then just incrementally watch the changes. But that is not trivial and is not done in this PR.
> Remove extra HashSet creation for pinned list

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Previous commit https://github.com/Alluxio/alluxio/commit/8f618358891ca89f753b369316d58221e8fb9b74
enlarges the race condition window in a access pattern of `write()` - `release()` (async unfortunately) - `getAttr()`.
In `getAttr()`, a special logic is added to wait for the writing file to completed before getting file size information.
`getAttr()` can happen in any cases. When it's in `write()` - `getAttr()` - `write()` process, we don't want it to block waiting file completed. When it's written by other threads or it's in `write()` - `release()` - `getAttr()`, we do want it to block waiting file completed.
This PR introducing new concurrent hash maps for the releasing entries to fulfill the `getAttr()` logics and `umount` logics().
> Fix Fuse write then read problem in async release and support umount

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- docs/en/api/POSIX-API.md
- docs/en/deploy/Running-Alluxio-On-Docker.md
Set the default value of worker fuse mount point to reduce user configuration in using worker fuse.
> Enable /mnt/alluxio-fuse as default worker fuse mount

- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
If the Fuse device is busy reading/writing files, we want umount to wait for those operations to happen.
If timeout exceeds, we want umount to be an no-op.
The current implementation is incorrect and doesn't achieve our target.
Add a TODO and change to log error for a workaround.
> Change throw FuseException to log error in jni-fuse umount

- integration/docker/Dockerfile
- integration/docker/Dockerfile.fuse
This change is being made to fix PR #13204 where we switched the Alluxio Docker base image from Alpine to Ubuntu.
Alpine has [tini](https://github.com/krallin/tini) included as a [package](https://pkgs.alpinelinux.org/package/edge/community/x86/tini) that we previously installed via `apk`.
Since our Helm charts rely on `tini` for the `command: ["tini", "--", "/entrypoint.sh"]`  (see [here](https://github.com/Alluxio/alluxio/blob/master/integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml#L91) for an example), the quickest fix for now is to just add `tini` to the Docker image again.
> [SMALLFIX] Add tini to Docker image

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
- integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl
- integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
- integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml
- integration/kubernetes/helm-chart/alluxio/values.yaml
Add hostAliases to master statefulset.yaml and worker daemonset.yaml . Sometimes, Hadoop hosts is not configured in k8s cluster nodes or in DNS, so that we need to add `hostAliases` to let alluxio to identify Hadoop's hostname.
> Add hostAliases in Master and Worker Pods

- README.md
I notice that in file ./dev/scripts/update-versions.sh, here are lines to update the version of README when updating project version. However, the alluxio version in README is still 2.3.0, because the update version script failed to update README since it has the wrong 'old version'. So I update the version of README to latest version of the project, and then the update version script will correctly recognize the old version of README and update it.
```bash
function update_readme() {
perl -pi -e "s/${1}/${2}/g" README.md
}
```
> [DOCFIX] Update README alluxio version

- docs/en/api/POSIX-API.md
Document [libfuse auto_cache option](https://libfuse.github.io/doxygen/structfuse__config.html#a9db154b1f75284dd4fccc0248be71f66) as a viable option in Alluxio-FUSE.
Relevant discussion: https://github.com/Alluxio/alluxio/issues/13207
> Document libfuse auto_cache option

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/wire/JournalDiskInfo.java
- core/common/src/main/java/alluxio/wire/MasterWebUIMetrics.java
- core/common/src/main/java/alluxio/wire/MasterWebUIOverview.java
- core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- core/server/master/src/main/java/alluxio/master/meta/JournalSpaceMonitor.java
- core/server/master/src/main/java/alluxio/master/meta/MetaMaster.java
- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
- core/server/master/src/test/java/alluxio/master/meta/JournalSpaceMonitorTest.java
- table/server/master/src/test/java/alluxio/master/table/TableMasterFactoryTest.java
- webui/README.md
- webui/master/src/constants/types/IJournalDiskInfo.tsx
- webui/master/src/containers/pages/Metrics/Metrics.tsx
- webui/master/src/containers/pages/Metrics/__snapshots__/Metrics.test.tsx.snap
- webui/master/src/containers/pages/Overview/Overview.tsx
- webui/master/src/store/metrics/reducer.tsx
- webui/master/src/store/metrics/types.tsx
- webui/master/src/store/overview/reducer.tsx
- webui/master/src/store/overview/types.tsx
This new monitor tracks utilization of disks when Alluxio is
is configured to use the embedded journal. The monitor logs messages
when available disk space falls below a configurable percentage. The
disk utilization metrics are exposed in the logs when the threshold is
reached, but can also now be found as metrics as well as in the Alluxio
master's web interface.
Implementation details:
The monitor is implemented as a heartbeat thread in the
DefaultMetaMaster. It gets disk utilization by using the `df` command
that is by default included with nearly all linux distributions, including
within bare containers such as alpine, ubuntu, and centos. The command
and arguments used are all POSIX-compatible, so this should be portable
but for now is limited to Linux.
For metrics, the actual disk …
> Add journal space monitor

- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Fixes #13179
With this PR, the following bash command can execute successfully.
```bash
echo hello>mountPoint/file
echo world>mountPoint/file
```
> Support open file for override

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/TimeBoundPageStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStoreOptions.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreOptions.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStoreOptions.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- tests/src/test/java/alluxio/client/fs/LocalCacheManagerIntegrationTest.java
- tests/src/test/java/alluxio/client/fs/io/LocalCacheFileInStreamIntegrationTest.java
This happens when (1) cache is configured with wrong and smaller capacity, (2) for some reason disk capacity allocated to Alluxio was "stolen" by other applications, or (3) alluxio cache is under-counting the real space used on disk (e.g., due to bugs, inode overhead and etc).
This PR aim to
1. add a metrics to monitor and report when `no space left on device` happens
2. force evicting items in a retry in this case
3.  add a new flag `alluxio.user.client.cache.store.overhead` to allow users to set the space overhead when writing data to disk
Fix https://github.com/prestodb/presto/issues/15972
> Handle client cache failure on "no space left on device"

- integration/fuse/bin/alluxio-fuse
Fix `alluxio-fuse stat` which did not pick up the worker process creating the FUSE mount in the new Alluxio-Worker-FUSE integration that can be enabled with `alluxio.worker.fuse.enabled=true`.
I tested this code snipped on 2.5.0-2
> Fix alluxio-fuse stat for Alluxio-Worker-FUSE

- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
Remove unused enum field alluxio.exception.ExceptionMessage#NO_WORKER_AVAILABLE_ON_ADDRESS
Fix Alluxio/new-contributor-tasks#574
> Remove unused enum field from alluxio.exception.ExceptionMessage

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java
- tests/src/test/java/alluxio/client/fs/UfsSyncIntegrationTest.java
Previously, loadMetadata on a single level of directory would load that directory and its children, causing unnecessary delay. 
This prevents that from happening by changing the descendant type when we are loading a non-base path.
> Prevent loading child inode metadata when not required

- core/server/master/pom.xml
- core/server/worker/pom.xml
Before this PR:
I want to run Alluxio in my IDE.But it has such error
and master.log
`org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor aroundWriteTo
MessageBodyWriter not found for media type=application/json, type=class alluxio.wire.MasterWebUIInit, genericType=class alluxio.wire.MasterWebUIInit`
After this PR:
(It has no effect on packaging Alluxio cause it is `provided`)
master:
worker:
> Enable webui ( master,worker) run normally when start Alluxio in IDE

- docs/en/ufs/S3.md
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
When enabling SSE, PUT/GET requests to S3 must use HTTPS or the response will be a 403. Instead of having the user specify the need for HTTPS manually, we should enable it by default whenever SSE is specified.
> Enable HTTPS when SSE is enabled on S3

- core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
- core/client/fs/src/test/java/alluxio/client/block/stream/GrpcBlockingStreamTest.java
- core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java
- core/client/fs/src/test/java/alluxio/client/file/FileSystemCacheTest.java
- core/client/fs/src/test/java/alluxio/client/file/FileSystemFactoryTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/DefaultMetaStoreTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/TimeBoundPageStoreTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreTest.java
- core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemApiTest.java
- core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
- core/common/src/test/java/alluxio/worker/block/io/LocalFileBlockReaderTest.java
`ExpectedException.none()` is deprecated in JUnit 4.13. It's recommended to change it to `Assert.assertThrows`.
```
package org.junit.rules;
public class ExpectedException implements TestRule {
/**
* Returns a {@linkplain TestRule rule} that expects no exception to
* be thrown (identical to behavior without this rule).
*
* @deprecated Since 4.13
* {@link org.junit.Assert#assertThrows(Class, org.junit.function.ThrowingRunnable)
* Assert.assertThrows} can be used to verify that your code throws a specific
* exception.
*/
@Deprecated
public static ExpectedException none() {
return new ExpectedException();
}
```
Considering the number of tests to update, I will do this module by module. This PR takes care of the client package.
> Deprecate ExpectedException.none() in alluxio.client

- underfs/pom.xml
Remove ceph module from underfs pom so that it will be skipped for maven build. Temporary workaround for #13309
> Remove ceph module from underfs temporarily

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
- integration/kubernetes/helm-chart/alluxio/templates/logserver/deployment.yaml
- integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
- integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml
- integration/kubernetes/helm-chart/alluxio/values.yaml
This PR is being made to address git [issue #13203](https://github.com/Alluxio/alluxio/issues/13203).
I tested that the Helm chart rendered using the following in my `config.yaml`
```
tolerations: [ {"key": "test", "operator": "Equal", "value": "test", "effect": "NoSchedule"} ]
```
and that the tolerations worked as intended on k8s nodes I tainted using `kubectl taint nodes <node> test=test:NoSchedule`
**Note:** I tested the Helm chart using all default values; so no FUSE nor logging-server deployments.
> Add Helm chart support for k8s node tolerations

- core/common/src/main/java/alluxio/conf/PropertyKey.java
This property is only used in tests. It also should not be set explicitly by the users. It's confusing to display the property on the doc page.
> [SMALLFIX] Change alluxio.logger.type property to hidden

- core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java
- job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java
- job/server/src/main/java/alluxio/job/util/JobUtils.java
- job/server/src/main/java/alluxio/master/job/plan/PlanCoordinator.java
- job/server/src/test/java/alluxio/job/plan/replicate/ReplicateDefinitionTest.java
Improve efficiency of `distributedLoad` in two fold:
1. calling `BlockInStream.create` to obtain the InputStream without RPC, where the original  `blockStore.getOutStream(blockId,...)`  makes one RPC to master to get blockInfo.
2. removing using `BlockOutStream` and only reads the block data to alluxio job worker without writing it back to the block store on worker. This will further save at least two RPCs and the overhead to transfer data back to worker.
Note that, the original code is not removed to handle the case Pinned Media, because currently reading a block does not support promoting this block to a medium but only a tier. After discussed with @calvinjia , we will leave this once we consolidate medium and tier on worker
> Improve distributedLoad

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/main/java/alluxio/master/file/RpcContext.java
- core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
- core/server/master/src/test/java/alluxio/underfs/UfsStatusCacheTest.java
- tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java
The previous version slowed down the sync because the number of prefetch threads were much smaller than the number of rpc threads that were performing a sync in many cases.
> Cancel sync job in middle of ufs calls if client cancelled

- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockStore.java
RocksDB engineer claims that it is possible for the readOptions to get garbage collected during iteration because RocksIterator doesn't hold a reference to the object but instead a native resource owned by readOptions.
> Attempt to fix RocksDB SegFaulting Occasionally

- core/server/worker/src/main/java/alluxio/worker/grpc/AbstractWriteHandler.java
Previously, unchecked exceptions are swallowed by alluxio workers, leading to client not knowing about the failure.
> Handle unchecked exceptions similarly to checked exceptions

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- underfs/gcs/src/main/java/alluxio/underfs/gcs/v2/GCSV2UnderFileSystem.java
For requests sent to the GCS, especially data transfer requests, we should enable GCS's internal retry mechanism. 
This allows us to do that. 
The delay starts with initial delay, delay is multiplied by the multiplier on subsequent retries, until the delay reaches maximum delay. The retry will last until the maximum number of retries is reached or the maximum duration is reached.
> Add retry options to GCS requests

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
When data locate in other nodes, use the GrpcBlockingStream to read from other nodes instead of reading from the local node and refetching data from UFS.
> Fix process local block in stream

- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
- core/client/fs/src/test/java/alluxio/client/file/cache/store/LocalPageStoreTest.java
Fixed a regression introduced in #12813 , where I was fixing a potential race (benign) on creating/removing local file system directories but leaving an unbounded amount of directories.
> Fix a regression of uncleaned directories

- pom.xml
- underfs/cephfs-hadoop/pom.xml
- underfs/cephfs/pom.xml
Fix #13309
Create two repo
https://github.com/opendataio/cephfs-hadoop
https://github.com/opendataio/libcephfs
And deployed them to 
https://repo1.maven.org/maven2/io/github/opendataio/cephfs-hadoop/0.0.1/
https://repo1.maven.org/maven2/io/github/opendataio/libcephfs/0.0.1/
So that we can use these dependency by 
```xml
<dependency>
<groupId>io.github.opendataio</groupId>
<artifactId>cephfs-hadoop</artifactId>
<version>${cephfs-hadoop.version}</version>
</dependency>
<dependency>
<groupId>io.github.opendataio</groupId>
<artifactId>libcephfs</artifactId>
<version>${libcephfs.version}</version>
</dependency>
```
```bash
mvn clean install -U --no-transfer-progress -T 2C -DskipTests -Dmaven.javadoc.skip -Dcheckstyle.skip -Dlicense.skip -Dfindbugs.skip > build.log
mvn javadoc:aggregate …
```
> Fix libcephfs version error by maintain a public repo

- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- job/server/src/main/java/alluxio/job/util/JobUtils.java
- job/server/src/test/java/alluxio/job/plan/replicate/ReplicateDefinitionTest.java
Fix an bug introduced in https://github.com/Alluxio/alluxio/pull/13146, causing `setReplication` command to fail when data has not been persisted.
> Fix replicate job loading non-persisted files

- docs/en/ufs/GCS.md
navtabs cannot have the same title, otherwise interacting with one can affect others with the same title
> [DOCFIX] Fix GCS doc navtabs title

- docs/en/contributor/Contributor-Getting-Started.md
Add the description so that new contributors know only take one of the new contributor tasks.
> [DOCFIX] Fix contribution task description

- minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java
- tests/src/test/java/alluxio/client/cli/JournalToolTest.java
- tests/src/test/java/alluxio/server/ft/journal/ufs/SecondaryMasterTest.java
- tests/src/test/java/alluxio/testutils/LocalAlluxioClusterResource.java
The goal of this PR is to make tests faster/less flaky.
> Do not include secondary master by default in LocalAlluxioCluster

- shell/src/main/java/alluxio/cli/fsadmin/report/SummaryCommand.java
- shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
When doing command `fsadmin report`, not only the leader master address is showed, all addresses of live masters are now being printed for more complete information.
> Print all live masters addresses to fsadmin report

- docs/en/deploy/Running-Alluxio-On-Docker.md
The original wordings in section 2 Prepare Docker Volume to Persist Data in Deploy Alluxio on Docker (https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Docker.html#prepare-docker-volume-to-persist-data), where they instruct users to "run" the commands to create a host/named volume, may lead users to actually run the command. Instead they should be included in the complete command which is introduced in section 3.
Fix typo where there are two consecutive "be".
The "Therefore" in the later part of the same section can be a little bit strong, considering that both the host directory and the container location are just examples.
> [DOCFIX] Modify wordings in Prepare Docker Volume to Persist Data

- docs/en/deploy/Running-Alluxio-On-a-Cluster.md
Added the following details due to the confusions some new users had:
- Not knowing to put the master host name in conf/masters and worker’s host name in conf/workers
- Needing further information about Amazon S3 when reading the example of setting S3 bucket as the alluxio.master.mount.table.root.ufs.
- Not knowing to set passwordless ssh from the master node to itself
- Not knowing to config the inbound rules and ports for the nodes
> [DOCFIX] Add details to tutorials

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- pom.xml
- underfs/cephfs/src/main/java/alluxio/underfs/cephfs/CephInputStream.java
ufs/cephfs: improve CephInputStream to be thread safe
xstream: update to 1.4.17 to improve safety level
because 1.4.16 of XStream is vulnerable to a Remote Command Execution attack
http://x-stream.github.io/CVE-2021-29505.html
Signed-off-by: Xue Yantao jhonxue@tencent.com
> Improve CephInputStream to be thread safe

- conf/alluxio-env.sh.template
- libexec/alluxio-config.sh
Due to no-login shell does not source `/etc/profile`, we always get `Cannot find 'java'` error when we just set `JAVA_HOME` in `/etc/profile`.
It's better to have a more friendly tip.
> [SMALLFIX] Improve of set java home

- integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemContractTest.java
Provide an option to help debug a specific test when running runUfsTests
For example, we can pass `--test` to focus test only `test` and `test2`
```
alluxio runUfsTests --test test1 --test test2
```
> Add a test option to accept running test name

- pom.xml
because the older version was only available on bintray, and bintray/jcenter is no longer available starting may 1
> Change jnr-fuse version to 0.5.5

- integration/docker/Dockerfile
- integration/docker/Dockerfile.fuse
Fix https://github.com/Alluxio/alluxio/issues/13322
After this PR 
```
$ docker run -it -u root --entrypoint='' <NewAlluxioImageBuilt> cat /etc/fuse.conf
user_allow_other
```
@cheyang  let me know if you see any concerns to turn this on
> Support FUSE opt user_allow_other by default in docker images

- tests/src/test/java/alluxio/client/fs/FileSystemReadonlyIntegrationTest.java
- tests/src/test/java/alluxio/client/fs/concurrent/ConcurrentFileInStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/fs/concurrent/ConcurrentFileSystemIntegrationTest.java
- tests/src/test/java/alluxio/client/fs/concurrent/ConcurrentFileSystemMasterCreateIntegrationTest.java
- tests/src/test/java/alluxio/client/fs/concurrent/ConcurrentFileSystemMasterLoadMetadataIntegrationTest.java
- tests/src/test/java/alluxio/client/fs/concurrent/ConcurrentFileSystemMasterSetTtlIntegrationTest.java
- tests/src/test/java/alluxio/client/fs/concurrent/ConcurrentRecursiveCreateIntegrationTest.java
Integration tests should be named with suffix `IntegrationTest` at least. If it specifies to validate the concurrency correctness, the prefix will be `Concurrent`.
> [SMALLFIX] Update some integration test names

- job/server/src/main/java/alluxio/job/util/JobUtils.java
- job/server/src/test/java/alluxio/job/plan/replicate/ReplicateDefinitionTest.java
The earlier change can potentially cause undesired load balance among workers.
Because it always respects the alluxio configuration instead of LocalFirst.
Also it always loads from the ufs instead of potentially from another worker when
it is already in alluxio memory. (e.g. When replication checker runs load)
> Allow load to read from another worker and force to local worker

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
- integration/kubernetes/helm-chart/alluxio/templates/logserver/deployment.yaml
- integration/kubernetes/helm-chart/alluxio/values.yaml
Addresses https://github.com/Alluxio/alluxio/issues/13422
> Change logserver Deployment update strategy to Recreate

- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/block/allocator/AllocatorTestBase.java
- core/server/worker/src/test/java/alluxio/worker/block/allocator/GreedyAllocatorTest.java
- core/server/worker/src/test/java/alluxio/worker/block/allocator/MaxFreeAllocatorTest.java
- core/server/worker/src/test/java/alluxio/worker/block/allocator/RoundRobinAllocatorTest.java
- core/server/worker/src/test/java/alluxio/worker/block/reviewer/MockReviewer.java
1. Allocator may  allocate null dirView ,`dirView.getAvailableBytes()`  is NPE and dirView has no toString implementation.
2. Add some UT for `Reviewer`
> [SMALLFIX] Fix NPE in Allocator and add some UT for Reviewer

- core/server/master/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- tests/src/test/java/alluxio/client/fs/FreeAndDeleteIntegrationTest.java
- tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
This is a better approach of achieving https://github.com/Alluxio/alluxio/pull/13454
The current implementation copies the `DefaultBlockMaster.mLostBlocks` to whoever is using the set. This change improves the `BlockMaster` interface to avoid the need to copy that collection. The `mLostBlocks` set can be huge when there are workers lost. Also the cost is very high because we just copy on every read.
> Refactor BlockMaster interface to avoid copying the lost block set

- pom.xml
The original spring plugins repo went offline, thus we need to use a new mirror
> Add aliyun mirror of the spring plugins repo

- pom.xml
- shell/pom.xml
- shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
Fixes #12599
If the `alluxio.underfs.hdfs.configuration` mount option start with "kv@", then extract the key value to mount options.
> Convert the configuration files to mount options when Mount

- core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java
- core/server/master/src/test/java/alluxio/master/block/BlockMasterWorkerServiceHandlerTest.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockMasterClientTest.java
- tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
Currently on worker register and heartbeat, the worker will flatten a `Map<BlockStoreLocation, List<Long>>` to a `List<LocationBlockIdListEntry>` and send to the master. `LocationBlockIdListEntry` is a key-value pair `BlockStoreLocationProto:BlockIdList`.  
The problem with this approach is `BlockStoreLocation` is a tuple `<tier,medium,dirIndex>` whereas `BlockStoreLocationProto` is a pair `<tier,medium>`. Basically in map flattening, the `List<LocationBlockIdListEntry>` contains more than one `LocationBlockIdListEntry` with the same `BlockStoreLocationProto:BlockIdList`. When the master receives the list, it will reconstruct the map using `BlockStoreLocationProto` as the key. At this step, there will be key collision because the worker can have more directories with the same `<tier, …
> Move block list merging from master to worker

- core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
- core/server/master/src/test/java/alluxio/master/file/replication/ReplicationCheckerTest.java
In `DefaultBlockMaster` we create extra copies of `BlockLocation` while we can just use the one given.
> Save one copy of BlockLocation

- docs/en/core-services/Catalog.md
- docs/en/operation/User-CLI.md
- table/server/common/src/main/java/alluxio/table/common/udb/PathTranslator.java
- table/server/common/src/main/java/alluxio/table/common/udb/UnderDatabase.java
- table/server/master/src/main/java/alluxio/master/table/CatalogProperty.java
- table/server/master/src/main/java/alluxio/master/table/Database.java
- table/server/master/src/main/java/alluxio/master/table/DbConfig.java
- table/server/master/src/test/java/alluxio/master/table/TestDatabase.java
- table/server/underdb/glue/src/main/java/alluxio/table/under/glue/GlueDatabase.java
- table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java
This PR supply a new option `catalog.db.config.file` to describe detail information or concrete special behavior for the database. Now, i add a json format file which contains `bypassSet`, if tables are in it, they will be bypassed.
Bypass here means return the udb location directly to client, so that client can read data through ufs directly.
This is an example of db config file.
```json
{
"bypassSet" : ["person1", "person2"]
}
```
We can use the db config file when `attachdb` and `sync`.
```
bin/alluxio table attachdb hive thrift://localhost:9083 test -o catalog.db.config.file=/etc/alluxio/conf/db-test.json
bin/alluxio table sync test
```
I create 3 table named `person` `person1` and `person2`, now I bypass `person1` and `person2`, left `person` in Alluxio.
As a test result, I show the …
> Support bypass table when attach and sync db

- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
- minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTest.java
For snapshot replication we have been using initial raft group which will be wrong if the quorum has changed. Updated the logic to always get the latest raft group.
> Fix stale raft journal group

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/common/src/main/java/alluxio/util/ObjectSizeCalculator.java
- core/common/src/test/java/alluxio/util/ObjectSizeCalculatorTest.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
- core/server/master/src/main/java/alluxio/master/metastore/caching/CachingInodeStore.java
- core/server/master/src/main/java/alluxio/master/metastore/heap/HeapBlockStore.java
- core/server/master/src/main/java/alluxio/master/metastore/heap/HeapInodeStore.java
Use reflection to walk through inode and block object to estimate the size of heap usage by inode and block data structures. 
Assumption: constant inode and block structure size to achieve reasonable time estimate
> Add metrics for inode and block heap sizes

- core/common/src/main/java/alluxio/worker/block/io/DelegatingBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
Because we can not rely on the UnderFileSystemBlockReader type
> Fix ufs read metrics

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/worker/block/io/LocalFileBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/block/RemoteBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java
Adds simple Counter metrics for UFS vs. Remote vs. Local block streams.
**W.I.P: Still undergoing testing**
> Add counters for BlockReader streams

- core/server/master/src/main/java/alluxio/master/metastore/heap/HeapInodeStore.java
Uses a conservative estimate rather than walking the object tree, because that can lead to OOM
Object size estimation is traditionally done by walking the object tree using reflection, but it can pull in very large object with references to many other objects, and quickly grow in size. 
We estimate the object size, and particular collection size by assuming each element of a collection has uniform size. therefore, we do not traverse deep into the object.
> Fix OOM for object size calculation

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
I've monitored excessive memory usage incurred by logging these two messages. Below is a test in a test cluster with master heap of 12G (-Xmx=12g -Xms=12g). 
I simulated registerWorker RPCs where all the blocks are not present on the master. This can happen when a worker registers with blocks that have been removed while the worker lost heartbeat. Each batch of test invokes 20 concurrent RPCs and records the average time taken.
Before the change - logging this message per block. RPCs took >150s to finish on average.
```
$ jstat -gcutil 12182 10000
S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT   
52.54   0.00  72.40   1.19  93.46  90.07      4    0.960     0    0.000    0.960
100.00 100.00 100.00   9.09  94.80  92.34     14    3.725     0    0.000    3.725 …
```
> Change logging on unrecognized blocks to DEBUG

- shaded/hadoop/pom.xml
- shaded/ozone/pom.xml
Fix NoClassDefFoundError when dfs.namenode.kerberos.principal.pattern is set #13527
When ufs is kerberosed HDFS and dfs.namenode.kerberos.principal.pattern is set in hdfs-site.xml, the Alluxio couldn't set up IO streams with HDFS. The cause is java.lang.NoClassDefFoundError: alluxio/shaded/hdfs/com/google/re2j/PatternSyntaxException.
Shaded the dependency com.google.re2j in alluxio-shaded-hadoop and alluxio-shaded-ozone modules.
> Fix NoClassDefFoundError #13527

- docs/en/deploy/Running-Alluxio-On-Docker.md
When enabling POSIX API using docker, launching the container in background would be more user friendly, so that they don't have to use a new tab/window.
> [DOCFIX] Improve Docker POSIX doc

- docs/en/operation/Remote-Logging.md
2 changes:
1. Change the port from number to string, as in a K8s configmap the number format will lead to a parsing error, only the string format will work.
2. Add a link to remote logging setup in k8s as that's much different
> [DOCFIX] Improve remote logging doc

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
When we get status for an incomplete file, we should produce a logging message. 
Currently, we do not check if it is a file.
> Log when it is a file

- docs/en/api/POSIX-API.md
- Add in a few colons to make the lines more readable. 
- Fix a few typos.
- For the "available Linux mount options" man page on line #222, the original link returns 404. I found a related man page but not entirely sure this is the correct one. Let me know if the link is wrong.
> [DOCFIX] Improve POSIX API Doc

- bin/alluxio-monitor.sh
Fix the remote debug error info as follows:
resolve #10958
The reason for this issue is that the same remote debug parameters are specified when AlluxioMasterMonitor is started after AlluxioMaster starts.
Similarly, other processes also have the same problem, such as AlluxioWorker, AlluxioJobMaster, and AlluxioJobWorker.
In fact, all monitor processes, such as AlluxioMasterMonitor, AlluxioWorkerMonitor, etc., are run once. So no remote debug parameters are required for them.
Nothing.
> Fix monitor process when passing Java Opts for Remote debugging 

- docs/en/ufs/NFS.md
> [DOCFIX] Fix file name to capital

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Change the estimate of heap size per inode to 2kb
We want to be more conservative in cache size estimate.
No
> Change estimate of heap size per inode from 350 bytes to 2kb

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
Log a warning on unrecognized/orphaned blocks from worker only when the counts are >0
This is a follow-up for https://github.com/Alluxio/alluxio/pull/13520 where the warning message is logged regardless of the count.
> Log warning on orphaned blocks

- docs/en/deploy/Running-Alluxio-On-Kubernetes.md
This PR proposes some additions to the [Alluxio k8s guide](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html) to reflect some of the recent additions to the Alluxio Helm chart:
- `serviceAccount`: #13297 
- `tolerations`: #13214 
- `hostAliases`: #13226 
- `strategy`: #13423 
Doc validation
Yes, the documentation.
> [DOCFIX] Update k8s doc with new Helm additions

- integration/docker/entrypoint.sh
Fix #13601 
Set alluxio ram folder only if tier 0 is not MEM and tier 0 dir is not set explicitly
To enable launching worker with SSD only storage through docker
No
> Fix worker cannot be ssd only tier in docker issue

- shaded/hadoop/pom.xml
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Fix #13532 (Failed to read data from HDFS files when HDFS EC is enabled)
When alluxio use HDFS client to read EC files, the client will use the ContextClassLoader to initialize CodecRegistry which will load RawErasureCoderFactory. The ClassLoader of HDFS Configuration should be the same with CodecRegistry, otherwise we will get the error java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.io.erasurecode.CodecRegistry.
> Fix failures reading data from HDFS files when HDFS EC is enabled

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
The `Precondition` check will generate a string per block and induce extra method invocation. The cost is significant both in execution time and heap allocation.
The change saves heap allocation for registerWorker call by 75%, compared to without this change. However the Precondition check was brought in by https://github.com/Alluxio/alluxio/pull/13461. That means this PR does not improve the performance of `registerWorker` compared to previous Alluxio version, instead it brings the performance back to normal.
NA
> Remove precondition string concat cost

- core/client/fs/src/main/java/alluxio/client/meta/MetaMasterConfigClient.java
- core/client/fs/src/main/java/alluxio/client/meta/RetryHandlingMetaMasterConfigClient.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- core/server/master/src/main/java/alluxio/master/meta/MetaMaster.java
- core/server/master/src/main/java/alluxio/master/meta/MetaMasterConfigurationServiceHandler.java
- core/transport/src/main/proto/grpc/meta_master.proto
- shell/src/main/java/alluxio/cli/fsadmin/command/UpdateConfCommand.java
- tests/src/test/java/alluxio/client/cli/fs/AbstractShellIntegrationTest.java
- tests/src/test/java/alluxio/client/cli/fsadmin/command/UpdateConfIntegrationTest.java
Fix #13513
bin/alluxio fsadmin updateConf alluxio.master.worker.timeout=4min
Now support dynamic update properties have been tested are:
- alluxio.master.unsafe.direct.persist.object.enabled
- alluxio.master.worker.timeout
- alluxio.master.audit.logging.enabled
- alluxio.master.ufs.managed.blocking.enabled
- alluxio.master.metastore.inode.inherit.owner.and.group
pr-link: Alluxio/alluxio#13514
change-id: cid-58e9469b8db6f962adf700067ff4c86d714bcadd
> Support update config

- core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
The previous value can be too short for worker registration in some use cases, bump up the default timeout to 10 minutes for worker start.
Without this change, the worker registration will reach the time out by registering a large number of blocks.
No.
> Bump up worker start timeout

- table/server/common/src/main/java/alluxio/table/common/udb/PathTranslator.java
- table/server/common/src/test/java/alluxio/table/common/udb/PathTranslatorTest.java
Previously, `PathTranslator` erroneously:
1. finds a prefix of `ufsPath` by simply checking with `String.startsWith()`. This fails to handle the case where the boundary falls within a path component. This case is now covered in the `prefixBoundaryWithinPathComponent` test;
2. chooses an arbitary prefix of `ufsPath` (the first returned during map iteration) even if there are multiple eligible choices. This is fixed by choosing the deepest prefix instead.
It's a bug fix.
No.
> Fix PathTranslator to compare path prefixes by path components

- docs/en/core-services/Catalog.md
- docs/en/operation/User-CLI.md
- table/server/common/src/main/java/alluxio/table/common/udb/UdbBypassSpec.java
- table/server/common/src/main/java/alluxio/table/common/udb/UnderDatabase.java
- table/server/common/src/test/java/alluxio/table/common/udb/UdbBypassSpecTest.java
- table/server/master/src/main/java/alluxio/master/table/Database.java
- table/server/master/src/main/java/alluxio/master/table/DbConfig.java
- table/server/master/src/test/java/alluxio/master/table/DbConfigTest.java
- table/server/master/src/test/java/alluxio/master/table/TestDatabase.java
- table/server/underdb/glue/src/main/java/alluxio/table/under/glue/GlueDatabase.java
- table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java
Following PR #13455, this PR allows bypassing by partition names.
To allow partition specification, the syntax of the config file `catalog.db.config.file` has been changed. It now looks like this:
```json
{
"bypass": {
"tables": [
"table1",
{"table": "table2", "partitions": ["table2_part1", "table2_part2"]}
]
}
}
```
More fine-grained control over which partitions to bypass.
Yes. The syntax of the config file is changed.
> Support bypassing by partitions

- core/server/common/src/main/java/alluxio/web/WebServer.java
Fix master cannot open stacks page issue
Now proxy process can access stacks page by `http://<HOSTNAME>:39999/stacks`, but master process cannot be accessed through `http://<HOSTNAME>:19999/stacks` now.
No.
Now, alluxio master and proxy process can get the stacks info from `/stacks`
> Fix master cannot open stacks page issue

- core/server/common/pom.xml
- core/server/common/src/main/java/alluxio/master/journal/MasterJournalContext.java
- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/LocalFirstRaftClient.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/SnapshotDownloader.java
- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalWriterTest.java
- core/server/common/src/test/java/alluxio/master/journal/raft/SnapshotReplicationManagerTest.java
- core/server/master/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java
- pom.xml
- tests/src/test/java/alluxio/client/cli/JournalToolTest.java
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTest.java
Updating the Apache Ratis API from v1.0.0 to v2.0.0
This upgrade will allow Alluxio to use the new TransferLeadership functionality in Ratis 2.0.0. This will allow Alluxio masters to gracefully give up their leadership manually.
No
Fixes #13680
> Update Apache Ratis API to 2.0.0

- core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
Locking an inode path might leave locks when runtime exceptions are thrown.
This fix ensures there won't be a lock leak for all exceptions.
> Close lock while traversing for all exceptions

- dev/jenkins/Dockerfile-jdk11
using a different keyserver to build java 11 maven image
previous keyserver no longer works
no
> Use working gpg keyserver for java11 maven image

- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
When a user accidentally mounts to a path that exists in Alluxio, the error is like "Mount point <path> already exists". This can be misunderstood as the path is already a mount point. And when they attempt to unmount <path>, they will realize that path is not a mount point and panic.
An example flow looks like below:
```
[hadoop@ip-18-22-4-73 ~]$ alluxio fs mount
hdfs://ip-18-22-4-73.ec2.internal:8020/                 on  /hdfs_comp  (hdfs, capacity=144.43GB, used=16.15MB(0%), not read-only, not shared, properties={})
hdfs://blah:8020/  on  /           (hdfs, capacity=144.43GB, used=37.78GB(26%), not read-only, not shared, properties={alluxio.underfs.version=hadoop-2.8, alluxio.underfs.hdfs.remote=true, alluxio.underfs.hdfs.configuration=/opt/alluxio/conf/core-site.xml:/opt/alluxio/conf/h …
```
> Improve error msg when mount point already exists

- core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
There can be multiple AsyncJournalWriter threads, add a thread name suffix to distinguish them.
Makes jstack debugging easier
NA
> Add a name suffix to distinguish AsyncJournalWriter threads

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Disable interrupting user RPCs when backup is not able to acquire the lock.
Interrupt cycling is n invasive process that has been noticed in many environments to cause disruption for user workflows.
> Disable interrupt-cycle by default to avoid RPC interruption

- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
This change soft disables RPC level safety of RATIS by hard coding relevant configurations to infinity.
Without these overrides, the leader will step down upon detecting a long running GC over 10sec. 
This is not desirable for a single master cluster. Additionally, reduced safety should be provided via standard leader election in clustered mode.
> Disable RATIS's RPC level safety

- conf/log4j.properties
- core/server/common/src/main/java/alluxio/ProcessUtils.java
- core/server/master/src/main/java/alluxio/master/meta/checkconf/ServerConfigurationChecker.java
- core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
Simplify the logging based on user feedback
- Remove excessive logging like “2021-06-01 10:09:25,353 INFO  ServerConfigurationChecker - All server-side configurations are consistent.”
- Add master/worker logging with version
- Remove noisy logging like `WARN  EC2MetadataUtils - Unable to retrieve the requested metadata (/latest/meta-data/product-codes). Failed to connect to service endpoint: `
Clean up logging to ease debugging experience
No
> Improve server-side logging

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/wire/MasterWebUIMetrics.java
- core/common/src/main/java/alluxio/wire/MasterWebUIOverview.java
- core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
- webui/master/src/containers/App/__snapshots__/App.test.tsx.snap
- webui/master/src/containers/pages/Metrics/Metrics.tsx
- webui/master/src/containers/pages/Metrics/__snapshots__/Metrics.test.tsx.snap
- webui/master/src/containers/pages/Overview/Overview.tsx
- webui/master/src/store/metrics/reducer.tsx
- webui/master/src/store/metrics/types.tsx
- webui/master/src/store/overview/reducer.tsx
- webui/master/src/store/overview/types.tsx
Adding warnings to the UI overview page when the journal has not checkpointed in some time after reaching the journal entry checkpoint period. Also, add the two checkpoint metrics (last checkpoint time and entries since checkpoint) to the metrics tab.
New overview page warning:
Metrics page addition:
This is required to help alert users to potential issues with their system if the journal has not checkpointed when it is supposed to. 
- Addition of a hidden property key to change the time period which causes the warning to show up on the overview page. It is marked as hidden because no one _should_ need to configure this value, but it may be desirable. It is also useful for testing.
- Web UI additions (see screenshots). New section on the metrics page and new potential warning in the …
> Add journal checkpoint warnings on UI

- core/common/src/main/java/alluxio/AbstractClient.java
- core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
Fix exception propagation during RPC connection to server.
Sometimes, gRPC throws some unexpected exceptions when target is unavailable. When these go unhandled, they end up failing the RPC.
> Fix exception propagation for RPC connection retries

- shell/src/main/java/alluxio/cli/fsadmin/report/UfsCommand.java
100PB * 100 will overflow a 64 bit integer.
For example:
hdfs, capacity=130.71PB, used=106.79PB(-43%)
> Fix integer overflow in usedPercentage

- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
remove reference to Dockerfile.fuse
Dockerfile.fuse was removed in #13756
no
> Remove Dockerfile.fuse ref from generate-tarball

- core/common/src/main/java/alluxio/wire/MasterWebUIOverview.java
- core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
- webui/master/src/containers/pages/Overview/Overview.tsx
- webui/master/src/containers/pages/Overview/__snapshots__/Overview.test.tsx.snap
- webui/master/src/store/overview/reducer.tsx
- webui/master/src/store/overview/types.tsx
Display cluster Id in the master UI overview page, so that we can make sure the the cluster identify.
Display the cluster id.
Display the cluster id.
> Support display clusterId from master ui

- integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
- integration/kubernetes/helm-chart/alluxio/values.yaml
In Kubernetes helm, replace .Values.fuse.{image, imageTag, imagePullPolicy} with .Values.{image, imageTag, imagePullPolicy}, because alluxio-fuse is using the same docker image as master/worker do and thus has the exact same settings.
> Deprecate .Values.fuse.{image, imageTag, imagePullPolicy} in helm

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java
- core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java
- core/server/master/src/test/java/alluxio/master/metrics/MetricsStoreTest.java
Address #13724
Add a gauge metric in MetricsStore.java, CLUSTER_CACHE_HIT_RATE = 1 - CLUSTER_BYTES_READ_UFS_ALL/(CLUSTER_BYTES_READ_DIRECT + CLUSTER_BYTES_READ_REMOTE + CLUSTER_BYTES_READ_DOMAIN)
We want to add a metric cluster_cache_hit_rate and now we can only calculate by ourselves
Users can get a new metric
> Add cluster_cache_hit_rate metric

- core/client/fs/src/main/java/alluxio/client/file/MetadataCachingBaseFileSystem.java
- core/client/fs/src/test/java/alluxio/client/file/MetadataCachingBaseFileSystemTest.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
If a file or dir is not exist, `getStatus` will throw FileDoesNotExistException, and metadataCache will never cache this result, client will try to call rpc server again next time.
Cache the special URIStatus `NOT_FOUND_STATUS` while met FileDoesNotExistException, when cache hit, re-throw the exception again.
NO.
> Support cache Not exist status

- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
Sending correct argument via reflection to force election upon switching election modes for RATIS nodes.
Without this change, election might not get triggered and test will timeout waiting for seeing the new leader.
Fix https://github.com/Alluxio/alluxio/issues/13746
> Force election after switching leader modes in RaftJournalTest

- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
Switching GRPC and WEB start sequence.
In my tests I found that grpc starts quickly (about 1s) but the web service takes about 15s. Switching the order can make GRPC  accept the request earlier but the impact on the web service is minimal when from follower to leader,
no user facing changes.
> Switch GRPC and WEB start sequence

- core/server/proxy/src/main/java/alluxio/proxy/s3/CopyObjectResult.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/ListAllMyBucketsResult.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketOptions.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketResult.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/test/java/alluxio/proxy/s3/S3RestServiceHandlerTest.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Improve conformance of the S3 API to the specification defined by AWS.
The AWS CLI does not work for many standard operations (e.g. listing buckets, setting max number of return keys, copying between buckets)
This affects some of the values from the S3 API to be in-line with more of the S3 REST API specification. It can potentially break backwards compatibility with previous versions. 
This PR is a a serious of small changes and improvements to the S3
API which improves the conformance to the specification defined
by the AWS Rest API reference at
https://docs.aws.amazon.com/AmazonS3/latest/API/Type_API_Reference.html
A short summary of the changes:
- Implement the CopyObjectResult type for bucket-bucket transfers
- Make the ListAllMyBucketsResult conform to the spec. Added
creationDate …
> Update and improve conformance of S3 API

- core/client/fs/src/main/java/alluxio/client/file/FileSystemUtils.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Add more logging to get timing information about a persist request throughout the system
To understand async persist performance better
No
> Add additional logging to track persist requests

- core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
If container host configured, use it instead of worker host. Otherwise, asyncCache will never successful caused by `Failed to connect to remote block worker`
```
2021-07-20 09:10:08,054 WARN  AsyncCacheRequestManager - Failed to async cache block 60767076352 from remote worker (x.x.x.x/x.x.x.x:29999) on copying the block: java.io.IOException: Failed to connect to remote block worker: GrpcServerAddress{HostName=x.x.x.x, SocketAddress=x.x.x.x/x.x.x.x:29999}
```
The x.x.x.x is node hostname.
No
> Fix async cache error

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java
Utilize the unused SetAttribute builder in the metadat sync code.
I confirmed in a previous incarnation of this code
(https://github.com/Alluxio/alluxio/blame/cc0f1308f4a020cab6099a6622e26a729fe4b755/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java#L3567-L3580)
That the builder was in-fact being used. Seems like it was lost in
translation when migrating the sync code.
Fixes #13796 
Could potentially miss updating the owner on the file.
no
> Fix unused builder for syncing when setting attributes

- shaded/client/pom.xml
Shade plugin is provided fresh jar content always.
Incremental builds (without `clean` lifecycle) are broken due to shade-plugin reshading shaded content.
> Create jar content always from scratch for shading

- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
- core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerWithShadowCacheTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
- core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
- core/common/src/main/java/alluxio/client/file/CacheContext.java
- core/common/src/test/java/alluxio/client/file/CacheContextTest.java
Update the shadow cache metrics in 'get' method
Expose shadow cache metrics by calling the incrementCounts method in CacheContext
Without this change, the shadow cache metrics would be only updated in 'get' method, which might cause the size of working set inaccurate (far below the real value) especially when the working set is lower than the cache capacity.
Our customer can also get table level metrics by overriding the incrementCounts method
> Improve the metric of shadow cache for relatively small working set

- core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java
- core/server/master/src/test/java/alluxio/master/file/replication/ReplicationCheckerTest.java
- core/transport/src/main/proto/grpc/job_master.proto
- job/client/src/main/java/alluxio/client/job/JobMasterClient.java
- job/client/src/main/java/alluxio/client/job/RetryHandlingJobMasterClient.java
- job/client/src/main/java/alluxio/job/plan/replicate/DefaultReplicationHandler.java
- job/client/src/main/java/alluxio/job/plan/replicate/ReplicationHandler.java
- job/server/src/main/java/alluxio/master/job/JobMaster.java
- job/server/src/main/java/alluxio/master/job/JobMasterClientRestServiceHandler.java
- job/server/src/main/java/alluxio/master/job/JobMasterClientServiceHandler.java
- job/server/src/main/java/alluxio/master/job/plan/PlanTracker.java
- job/server/src/main/java/alluxio/master/job/workflow/WorkflowTracker.java
- job/server/src/test/java/alluxio/master/job/JobMasterTest.java
- job/server/src/test/java/alluxio/master/job/plan/PlanTrackerTest.java
- tests/src/test/java/alluxio/client/cli/fs/command/PinCommandMultipleMediaIntegrationTest.java
- tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
- tests/src/test/java/alluxio/client/rest/JobMasterClientRestApiTest.java
Use the existing interface of job master to allow filtering of jobs by name and by job status
Currently, there is no way for client to efficiently look up job status and find incomplete jobs with a specific name/type
This leads to O(n) rpc calls from replicationChecker every heartbeat.
No
> Get job ids with filters

- bin/alluxio-common.sh
- bin/alluxio-start.sh
- bin/alluxio-stop.sh
Add a flag to the `alluxio-start.sh` and `alluxio-stop.sh` scripts to allow for persisting/populating the MEM-type worker caches to/from a local directory.
Allows for durable worker MEM-type cache during host machine restarts.
Changes the `USAGE` output from the `alluxio-start.sh` and `alluxio-stop.sh` scripts.
> Implement durable MEM-type worker cache

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/worker/src/main/java/alluxio/worker/SessionCleaner.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
Introduce a new counter to track the number of active clients talking to a worker
As requested by community user, we want to expose the number of active clients on the worker side,
so user can decide if it is safe to remove a worker.
A new metrics `Worker.ActiveClients`
> Add counter for worker-side clients

- core/client/fs/src/main/java/alluxio/client/file/FileSystemUtils.java
- shell/src/main/java/alluxio/cli/fs/command/PersistCommand.java
Add more debug messages to diagnose persist delays
We do not understand why the client thread stopped polling the file system master. 
More logging
> Add additional debug messages to persist waiting

- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/common/src/test/java/alluxio/util/network/NetworkAddressUtilsTest.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalConfiguration.java
- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalConfigurationTest.java
This pr is to fix issue #13595
If hostname is not one of raft cluster hostname list, add a second round check related ip. 
In some case, we can't change cluster adresss dns name specificed by config file and the node's hostname, so maybe  local hostname is not one of raft cluster hostname list, then the format action will throw error in the validate process.  
No change
> Fix format error when raft cluster hostname different with localhost

- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
Obtain accurate metrics of Master.RpcQueueLength
method of getQueuedTaskCount cannot be collected correctly, so change collection method to getQueuedSubmissionCount.
> Fix metrics of Master.RpcQueueLength

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- core/common/src/main/java/alluxio/client/file/CacheContext.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
Add two metrics for tracking read IO time concerning client cache.
Collect statistics about read IO time in cases of cache hits and misses, to provide insights about local cache performance.
No.
> Add read time metrics for client local cache

- webui/pom.xml
Use `npm ci` instead of `npm install` - helps speeds up installs since it is meant to be used in automated environments such as test platforms, continuous integration, and deployment -- or any situation that requires a clean install of dependencies. 
most people won't be adding/tweaking dependencies.
ref - https://docs.npmjs.com/cli/v6/commands/npm-ci
> Use npm ci for Web UI for installing dependencies

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
This pr resolves the  https://github.com/Alluxio/alluxio/issues/13824 that when the given buffer's length is larger than it read, it will throw IndexOutOfBoundsException.
This occurs when the length of a given buffer minus offset is greater than the actual read data.
It's one bug
No
> Fix the IndexOutOfBoundsException when reading one file

- bin/alluxio
- bin/alluxio-stop.sh
Before:
The behavior of the stop process scripts is: When the execution (**using kill pid**) exceeds the maxWait duration , the process will be forced to kill (**kill -9 pid**).
After this RP: 
We can add option param '-s' . When the execution exceeds the maxWait duration, the process won't be forcibly killed.
for example:
`sh bin/alluxio-stop.sh worker -s`
`sh bin/alluxio-stop.sh all -s`
Make the kill command more gracefully.
Parent PR and context: https://github.com/Alluxio/alluxio/pull/13373.
related PR: https://github.com/Alluxio/alluxio/pull/13876
We need to umount fuse properly instead of kill -9 pid 
Yes. Add one option for` alluxio-stop.sh`
Usage: alluxio-stop.sh  [component] [-c cache] [-s]
> Add soft kill option to all processes

- table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java
- table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/AbstractHiveClientPool.java
- table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/DefaultHiveClientPool.java
- table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveClientPool.java
- table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveClientPoolCache.java
Extract `HiveClientPool` as an abstract class to facilitate testing.
Currently there is no way to inject a mocked `IMetaStoreClient` into `HiveDatabase`. Adding the ability to do so facilitates unit testing.
No.
> Extract HiveClientPool as an abstract class to facilitate testing

- dev/scripts/update-versions.sh
Remove the version replacement for Dockerfile.fuse in the dev/scripts/update-versions.sh
1. the update-versions script is failing because Dockerfile.fuse had been deleted
No
> Remove the version replacement for Dockerfile.fuse

- bin/alluxio-common.sh
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- docs/en/operation/Upgrade.md
- Add section to 'Upgrading' doc about worker ramdisk cache persistence
- Improve descriptions to various `alluxio.worker.tieredstore` configuration options
Update docs to more accurately reflect the state of the application
- Changes the 'Upgrading' doc
- Changes the 'List of Configuration Properties' doc
> [DOCFIX] Improve documentation surrounding worker tiered stores

- webui/common/src/components/HOCs/withFetchDataFromPath/__snapshots__/withFetchDataFromPath.test.tsx.snap
- webui/common/src/components/HOCs/withFetchDataFromPath/withFetchDataFromPath.tsx
- webui/master/src/containers/pages/Browse/Browse.test.tsx
- webui/master/src/containers/pages/Browse/Browse.tsx
While using log web page to open log file, the end button or offset input textbox didn’t work
This is a simple bug, the `updateRequestParameter` was named to `upateRequestParameter` in the browse.tsx and withFetchDataFromPath.tsx, but named to `updateRequestParameter` in the `Logs.tsx`.
So I found error call stack in the browser console
```
Uncaught TypeError: a.props.updateRequestParameter is not a function
at t.<anonymous> (Logs.tsx:128)
at t.n.onClick (Button.js:52)
at Object.<anonymous> (react-dom.production.min.js:49)
at d (react-dom.production.min.js:69)
at react-dom.production.min.js:73
at T (react-dom.production.min.js:140)
at j (react-dom.production.min.js:169)
at k (react-dom.production.min.js:158)
at C (react-dom.production.min.js:232)
at On (react-dom.production.min.js:1718) …
```
> Fix the button of logs tab page cannot work issue

- core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java
- core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerDataReader.java
- core/client/fs/src/main/java/alluxio/client/block/stream/DataReader.java
- core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java
- core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java
- core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataReader.java
- core/client/fs/src/main/java/alluxio/client/block/stream/SharedGrpcDataReader.java
- core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
- core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
- core/client/fs/src/test/java/alluxio/client/block/stream/BlockInStreamTest.java
- core/client/fs/src/test/java/alluxio/client/block/stream/GrpcDataReaderTest.java
- core/client/fs/src/test/java/alluxio/client/block/stream/TestBlockInStream.java
- core/server/worker/src/test/java/alluxio/worker/block/stream/BlockWorkerDataReaderTest.java
Fixes #13766 
Support fuse read from worker through internal method call when cache miss.
Add worker is local check to correct fuse write to process local worker logics.
Add process local read write related metrics
When cache miss, the local worker can still help fetch the data from UFS and provide to the internal client without RPC involved.
Remove the unneeded RPC overhead between Fuse and Worker.
Correct the fuse write to local worker logics
No
> Fix process local read write client side logics and add unit tests

- core/server/common/src/main/java/alluxio/web/WebServer.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
- job/server/src/main/java/alluxio/master/AlluxioJobMasterProcess.java
- job/server/src/main/java/alluxio/worker/AlluxioJobWorkerProcess.java
Support prometheus servlet to all the server, include master, worker, job master, job worker, alluxioProxy.
With this PR, we can easily to get prometheus style metrics from all the servers.
Add `/metrics/json` and `/metrics/prometheus` servlet to all servers of alluxio.
> Move metrics handler to webserver

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
- core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
- core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- core/client/hdfs/src/main/java/alluxio/hadoop/HdfsFileInputStream.java
Reverts Alluxio/alluxio#13733
[StreamCapabilities](https://hadoop.apache.org/docs/r3.0.0/api/org/apache/hadoop/fs/class-use/StreamCapabilities.html) is introduced in hadoop3, which breaks classloading when running Hadoop2 with Alluxio client on classpath
```
err: exit status 1 Failed to finish cmd "/tmp/hadoop/bin/hdfs dfsadmin -safemode wait"
stderr: <OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/hadoop which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
21/08/06 08:53:42 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" …
```
> Revert "Add unbuffer support for impala"

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/common/src/test/java/alluxio/util/network/NetworkAddressUtilsTest.java
- integration/fuse/pom.xml
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
- integration/fuse/src/main/java/alluxio/fuse/FuseWebServer.java
Support FUSE Web server, leverage this, we can get stacks, metrics restfulapi.
We want to monitor FUSE server by prometheus, and get the thread stacks of FUSE in the web browser.
Bring webserver to FUSE server.
If you want open fuse web server, set `alluxio.fuse.web.enabled=true` is necessary.
> Support Web server for fuse process

- core/server/common/src/main/java/alluxio/metrics/sink/MetricsServlet.java
Pretty print the metrics/json web servlet
Easier for users to view all the metrics exposed by master/worker/fuse
Yeah, for web UI  metrics/json/ page, it will show json string as well formatted human readable string instead of the natural json string
> Print web metrics servlet page as human-readable format

- core/server/master/src/main/java/alluxio/master/file/LostFileDetector.java
LostFileDetector accesses journal directly, and should back off from enumeration if the journal becomes unavailable (i.e. closed).
Fixes https://github.com/Alluxio/alluxio/issues/13904
> Stop iterating lost files when journal is not available

- core/client/fs/src/main/java/alluxio/client/block/stream/SharedGrpcDataReader.java
Fix issue https://github.com/Alluxio/alluxio/issues/13125
With shared.caching.reader is enabled, alluxio may generate `java.lang.ArrayIndexOutOfBoundsException` when accessing `BLOCK_LOCKS`.
This problem is caused by `core/client/fs/src/main/java/alluxio/client/block/stream/SharedGrpcDataReader.java`
```java
private static ReentrantReadWriteLock getLock(long blockId) {
return BLOCK_LOCKS[HASH_FUNC.hashLong(blockId).asInt() % BLOCK_LOCKS.length];
}
```
`HASH_FUNC` is murmur3_32, it may generate negative number (depend on input blockId, see https://github.com/google/guava/blob/master/guava-tests/test/com/google/common/hash/Murmur3Hash32Test.java#L36 ). Thus it will finally get a negative index while accessing `BLOCK_LOCKS`. We need  a `abs` before mod or just `floorMod` instead of `%`. 
No.
> Fix ArrayIndexOutOfBoundsException when using shared.caching.reader

- stress/common/src/main/java/alluxio/stress/fuse/FuseIOParameters.java
- stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java
The number of files must be a multiple of number of directories, so each directory has same amount of files.
The number of files must be a multiple of number of threads, so each thread processes same amount of files.
@LuQQiu PTAL. Much cleaner than last time. Thanks!
> Add number of directories to FuseIOBench

- job/server/pom.xml
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystemFactory.java
Fix the job server or job worker starts failed and typo
The job server or job worker depend on `JobMasterWebServer` and `JobWorkWebServer`. When the job server or job worker starts failed with not using `bin` shell. so the pom must add dependencies.
NO
> Fix the job server or job worker starts failed and typo

- integration/docker/Dockerfile
Changes the url to download arthas 3.4.6 to one hosted by github
The original url, hosted by maven.aliyun.com, is sometimes unavailable, causing errors when building the docker image. 
Nope
> Change download url for arthas in Dockerfile

- stress/shell/src/main/java/alluxio/stress/cli/GetPinnedFileIdsBench.java
- stress/shell/src/main/java/alluxio/stress/cli/RegisterWorkerBench.java
- stress/shell/src/main/java/alluxio/stress/cli/UfsIOBench.java
- stress/shell/src/main/java/alluxio/stress/cli/WorkerHeartbeatBench.java
This change implements the missing description for `UfsIOBench` command and improves descriptions in `RpcBench` children, conforming to the same format.
Below is an example from `WorkerHeartbeatBench`. The rough structure is description -> example -> options -> parse exception.
```
$ bin/alluxio runClass alluxio.stress.cli.WorkerHeartbeatBench foofoofoo
A benchmarking tool for the WorkerHeartbeat RPC.
The test will generate a specified number of blocks in the master (without associated files). The test will also register the simulated workers with the master. Then it will keep generating heartbeats with the specified load and sending heartbeats to the master nonstop, until the specified time has elapsed.
Example:
$ bin/alluxio runClass alluxio.stress.cli.WorkerHeartbeatBench --concurrency …
```
> Improve UfsIOBench and RpcBench command descriptions

- shell/src/main/java/alluxio/cli/fs/command/AbstractDistributedJobCommand.java
- shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
For distributedjobcommand, now it just prints the information to the console, this change can intuitively obtain statistical information.
We want to visually obtain the number of successful and failed jobs for each distributedLoad operation.
No
> Count the number of successful and failed job

- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/metrics/sink/PrometheusMetricsServlet.java
- core/server/common/src/main/java/alluxio/metrics/sink/RatisDropwizardExports.java
- core/server/common/src/main/java/alluxio/metrics/sink/RatisNameRewriteSampleBuilder.java
Export ratis related metrics
There are lots of useful Ratis metrics, but not exported from alluxio, now just export it.
The following is the main point of this PR, I add two Consumer to ratis `MetricRegistries`
```java
MetricRegistries.global().addReporterRegistration(
r1 -> registerDropwizard(r1, ratisMetricsMap),
r2 -> deregisterDropwizard(r2, ratisMetricsMap));
```
The implementation of `addReporterRegistration` is 
```java
public void addReporterRegistration(Consumer<RatisMetricRegistry> reporterRegistration,
Consumer<RatisMetricRegistry> stopReporter) {
this.reporterRegistrations.add(reporterRegistration);
this.stopReporters.add(stopReporter);
}
```
And there are two hook point as following
```java
@Override
public RatisMetricRegistry create(MetricRegistryInfo info) {
return …
```
> Support export ratis metrics

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
Add metric of jvm pause monitor.
We want to use the data in jvmPauseMonitor to monitor the pause situation when the alluxio cluster provides services
> Add metric of jvm pause monitor

- core/client/fs/src/main/java/alluxio/client/journal/JournalMasterClient.java
- core/client/fs/src/main/java/alluxio/client/journal/RetryHandlingJournalMasterClient.java
- core/server/common/src/main/java/alluxio/master/journal/DefaultJournalMaster.java
- core/server/common/src/main/java/alluxio/master/journal/JournalMaster.java
- core/server/common/src/main/java/alluxio/master/journal/JournalMasterClientServiceHandler.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/transport/src/main/proto/grpc/journal_master.proto
- shell/src/main/java/alluxio/cli/fsadmin/journal/QuorumElectCommand.java
- tests/src/test/java/alluxio/client/cli/fsadmin/command/QuorumCommandIntegrationTest.java
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTest.java
To avoid the `quorum elect` command from hanging indefinitely
> Make the call to transferLeadership asynchronous

- stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java
Fix a race condition in StressMasterBench. The current code does not atomically get, compare and increment a concurrent counter, and causes the number of runs to be incorrect.
I was using the stress master benchmark tool to create test files on the master, when I found the number of created files does not match what I specified in the arguments:
```console
bin/alluxio runClass alluxio.stress.cli.StressMasterBench --fixed-count 10000 --stop-count 10000  
--operation CreateFile --warmup 0s --cluster --cluster-limit 3 
--base 'alluxio://AlluxioSandbox-bowen-fix-masters-1:19998/stress-master-base'
```
This command uses three job workers to create 10000 files each on the master, and stops the job as soon as the `--stop-count` has been reached. Therefore, the expected total number of files is …
> Fix race condition in StressMasterBench

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
This PR is made as a follow-up to the additions added in PR #13945, which added the functionality to override `livenessProbe` and `readinessProbe` in our Helm chart.
This PR just updates `Chart.yaml` and `CHANGELOG.md` to reflect these changes.
> Update Helm chart metadata for recent changes

- pom.xml
Revert netty version change to use a netty version with better compatibility
> Revert "Bump internal netty version to 4.1.55.Final"

- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
Fixes #13932
Fix the last snapshot related metrics 
When delegation backup is implemented, the leader master will download the snapshot from standby master and use it as its own snapshot, but in this process, we didn't update the last snapshot related metrics of the leader master.
Fix last snapshot metrics
> Fix last snapshot index in delegated backup

- stress/shell/src/main/java/alluxio/stress/cli/GetPinnedFileIdsBench.java
Fix extra preparations and cleanups in GetPinnedFileIdsBench.
`GetPinnedFileIdsBench` does not properly handle cases where the benchmark is running in a local process or in a job worker, causing unwanted extra runs of `prepare()` and `cleanup()`. This may cause the expected number of test files to be incorrect and fail the benchmark.
No.
> Fix extra preparations and cleanups in GetPinnedFileIdsBench

- stress/common/src/main/java/alluxio/stress/master/MasterBenchParameters.java
- stress/shell/src/main/java/alluxio/stress/cli/suite/MaxThroughput.java
We'll do a same maxThroughput test many time, so we don't want to change basedir or create&delete a lots of file before test.
Add a parameter to supply a way to skip prepare step.
Add a new parameter `--skip-prepare`
> Add a skip-prepare parameter for MaxThroughput

- core/common/src/main/java/alluxio/client/file/CacheContext.java
- core/common/src/main/java/alluxio/client/hive/HiveCacheContext.java
- core/common/src/test/java/alluxio/client/file/CacheContextTest.java
This PR add HiveCacheContext into CacheContext
HiveCacheContext contains the hive-related information like schema, table, partition, this information later will be used to identify whether the corresponding file needs to be cached and its caching TTL.
N/A
> Add HiveCacheContext into the CacheContext

- core/server/common/src/main/java/alluxio/master/journal/AbstractJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSystem.java
We need the sequence number information of log to monitor the cluster status. The corresponding metrickey is provided in the source code, but it is not registered to the metric system.
Register the metric key related to the sequence number to the metric system
No
> Register journal sequence number metric

- integration/docker/Dockerfile
Use alpine instead of ubuntu1604-customize to reduce docker image size from 2.8G to 2.41G. Add and modify commands to make everything works in alpine.
> Improve docker image to decrease size

- stress/common/src/main/java/alluxio/stress/BaseParameters.java
- stress/shell/src/main/java/alluxio/stress/cli/Benchmark.java
- stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java
- stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
- stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java
- stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
Make distributed tasks delay time configurable.
When the number of nodes in the cluster is large, the delay time of 10s may cause incomplete task scheduling. The delay time should be flexibly configured as required
No
> Make distributed tasks delay time configurable

- docs/en/deploy/Running-Alluxio-On-Kubernetes.md
This PR is a docfix to update the [Alluxio Kubernetes documentation](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html) to include the troubleshooting information surrounding Alluxio worker Pods getting `OOMKilled` by the Kuberentes scheduler.
See #13022 and #13976 for related issues.
> [DOCFIX] Update Alluxio on k8s doc about worker pod OOMKilled

- core/common/src/main/java/alluxio/conf/PropertyKey.java
IMO, "/job_election" and "/job_leader" should not be created in the root directory. So I updated default ZK path for jobmaster, and added prefix "/alluxio".
> Update default ZK path for jobmaster

- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
Add dockerfile-common.sh to pathsToCopy for autobots to successfully build tarball.
@Xenorith Thanks!
> Add dockerfile-common.sh to pathsToCopy for autobots

- docs/cn/core-services/Caching.md
Fix #14053
Typo:  alluxio.worker.memory.size -> alluxio.worker.ramdisk.size
fix docs
documents in Chinese
> [DOCFIX] Fix typo in cn/core-services/Caching.html #14053

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
- underfs/local/src/test/java/alluxio/underfs/local/LocalUnderFileSystemTest.java
Add a property to skip broken symlinks when calling listStatus with the LocalUnderFileSystem
When a broken symlink appears when using a local UFS, all listings will fail because of the additional call to `#readProperties` in `LocalUndeFileSystem#listStatus`. This behavior can help alert users to broken symlinks, but also breaks functionality until the symlink is removed, which may be undesirable.
A new option that can be used with a local UFS mount.
> Add property to skip listing broken symlinks on local UFS

- core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
- shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
Fix load command printout bug, keep the behavior the same as before(print out directory level information instead of file-level)
Also, add wait option to cache request manager when waiting for the request to be complete.
Keep the load command the same behavior as before, print out directory level information instead of file level
> Fix printout bug for load command

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
Update evictor(LRU) reference by calling getPageInfo when get a page in LocalCacheManager
1. The LRU evictor won't work properly without this change, because read(get) a page won't update the LRU reference which might cause the active pages got evicted earlier.
N/A
> Update evictor(LRU) reference when get a page in LocalCacheManager

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
Make the stopwatch in readInternal as a local var to avoid potential race condition
1. The current usage stopwatch in readInternal might cause race condition
2. readInternal is called by positionedRead which should be thread-safe
N/A
> Make the stopwatch thread-safe in readInternal

- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- job/server/src/main/java/alluxio/master/AlluxioJobMasterProcess.java
Fix the job server service hangs on when  set alluxio.master.journal.folder a no privileged path.
Fix the job server service hangs on when  set alluxio.master.journal.folder a no privileged path.
Because of ratis's bug. See this pr `https://github.com/apache/ratis/pull/477`.
No
> Fix the job server service hangs on when set a no privileged path

- job/server/src/main/java/alluxio/master/job/plan/PlanCoordinator.java
Add more information and break the taskId check loop when a task failed.   
Not enough information for us to know which task failed , no need to check other taskId in the loop, just break.  
Get more information when task failed, skip useless loop.
No
No
> Add some information and break loop when a task failed incomplete

- integration/docker/Dockerfile
Fixes https://github.com/Alluxio/alluxio/issues/14079
change to install tini-static which includes all its dependencies
alphine doesn't have tini dependencies
It supports tini -- entrypoint.sh to continue working in kube scripts
> Use tini-static in Dockerfile for new alphine docker image

- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
Add Dockerfile-dev to the generated alluxio tarball so that we can build docker image from that tarball directly
Otherwise we cannot build the alluxio-dev docker image
NA
> Add Dockerfile-dev to the alluxio tarball

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
The AWS Java client uses this content type in its requests. Also, the
body content type is only consumed in a single method anyways, and is
treated the same regardless of its type.
Add `application/octet-stream` to the default mime types which are allowed
Some S3 clients (e.g. Java AWS SDK) use the `application/octet-stream` by default for the request content type. We only ever consume a byte stream in the handlers anyways, so adding `application/octet-stream` to the types should be harmless and increase support.
No
> Add application/octet-stream to consumed content types in S3 Handler

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
Shuffle the master rpc addresses to balance the request to each master to supply a consistent performance.
In a three-node(master-0, master-1, master-2) ha cluster, `getPrimaryRpcAddress` will be slowest when master-2 is leader, it will be fastest while master-0 is leader.
So I add some time calculate code in to `PollingMasterInquireClient#getAddress`, I found the following result while master-2 is leader, each time `getPrimaryRpcAddress` called will cost io exception extra time caused by non-leader ping.
```
io exception, localhost:19978, cost=358814316
io exception, localhost:19998, cost=6818567
Successful. localhost:19988, cost=40248883
```
Add a new PropertyKey `alluxio.user.rpc.shuffle.masters.enabled`, set default value is `false` to keep consistent behavior to original.
> Support shuffle master addresses for rpc client

- core/server/common/src/main/java/alluxio/metrics/sink/PrometheusMetricsServlet.java
* favor MetricsSystem.startSinksFromConfig to get the constructor by
reflection with parameters (Properties, MetricRegistry)
Fixes https://github.com/Alluxio/alluxio/issues/13165, be able to load PrometheusMetricsServlet when configured by metrics.properties
BUGFIX, MetricsSystem.startSinksFromConfig requires the constructor of the Sink with two parameters (Properties, MetricRegistry), PrometheusMetricsServlet doesn't provide such constructor.
None
> Add a second constructor in PrometheusMetricsServlet #13165

- core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
We cannot run job service related command line tools when we start 3 job master in same machine with different port while the leader is not the default job master rpc port.
After fix this, we can use the following command to start 3 job master and execute job service related command line tools successfully while the leader it not the default job master rpc port
```bash
ALLUXIO_JOB_MASTER_JAVA_OPTS="-Dalluxio.job.master.rpc.port=20001 -Dalluxio.job.master.web.port=20002 -Dalluxio.job.master.embedded.journal.port=20003 -Dalluxio.work.dir=/tmp/alluxio-tmp/alluxio-0 -Xbootclasspath/a:/Users/mbl/projects/github/alluxio-2/conf  -Dalluxio.logger.type=Console" bin/alluxio-start.sh -N job_master
ALLUXIO_JOB_MASTER_JAVA_OPTS="-Dalluxio.job.master.rpc.port=20011 -Dalluxio.job.master.web.port=20012 …
```
> Use jobMasterRpcAddresses to judge ServiceType

- stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java
fix FuseIOBench help command output typo
In the command ". /bin/alluxio runClass alluxio.stress.cli.fuse.FuseIOBench --help" output example, the class name is lowercase (xxx runClass alluxio.stress.cli.fuse.fuseIOBench xxx). Use it cloud not load class FuseIOBench, so it needs to be modified 
no
> Fix runClass FuseIOBench help command typo

- docs/en/api/POSIX-API.md
Remove the last few of the references to alluxio/alluxio-fuse image.
@LuQQiu
> [DOCFIX] Remove alluxio-fuse image reference

- core/common/src/main/java/alluxio/conf/PropertyKey.java
This will avoid clients being stuck on target RPC servers under various network faults.
> Introduce client-side keep-alive monitoring for channels of RPC network

- core/server/worker/src/main/java/alluxio/worker/block/UfsInputStreamCache.java
- core/server/worker/src/main/java/alluxio/worker/block/meta/UnderFileSystemBlockMeta.java
It's been verified that this explicit `cleanUp` call causes assertions from guava cache.
> Catch errors during explicit cache cleanup

- shell/src/main/java/alluxio/cli/fs/command/LoadMetadataCommand.java
Resolve issue #14183.
Provide users with an option to synchronize metadata of subfiles of a directory.
The force option is added to the `loadMetadata` command in the CLI：
> Fix the semantic ambiguity of LoadMetadataCommand

- docs/en/core-services/Caching.md
Add distribtuedLoad command to the caching docs
Otherwise people don't know distributedLoad command can be used to accelerate the data loading speed
change docs
> [DOCFIX] Add distributedLoad command to the caching docs

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/grpc/GrpcServerBuilder.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
This setting controls tolerance of gRPC servers against clients' keep-alive frequency.
Earlier change to enable client-side keep-alive to 30secs required a server-side change to tolerate such frequency beyond what's default (5mins)
> Enable additional keep-alive configuration on gRPC servers

- integration/kubernetes/CSI_README.md
- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/values.yaml
CSI docker-related files are moved to the Docker dir and the original CSI dir only contains a README.md. Since CSI depends on Kubernetes, now move the readme into the Kubernetes dir. Update information and values accordingly.
> Update CSI-related usage

- core/common/src/main/java/alluxio/AbstractClient.java
- core/common/src/main/java/alluxio/util/CommonUtils.java
- core/common/src/test/java/alluxio/util/CommonUtilsTest.java
- core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
Instead of showing 
```
2021-09-28 05:03:00,999 WARN  FileSystemMasterClient - GetPinList() returned [12884901887, 10737418239, 15032385535, ... 4000 others ]] in 2312 ms (>=1000 ms)
```
printing in logs
```
2021-09-28 05:03:00,999 WARN  FileSystemMasterClient - GetPinList() returned in 2312 ms (>=1000 ms)
```
- Worker logs can be spammed by the warning log printing all blocks
- Can be slow down
No
> Avoid printing too many blocks on logging

- stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java
In FuseIOStressBench, num-dirs is not needed for running ListFile operation, but the logic compares number of threads and number of directories, and throw error if the number of threads is larger than number of directories. This constraint should not apply to ListFile operation. This PR fixes this problem.
> Remove one constraint for listfile in FuseIOStressBench

- minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
Adding a delay between launching each master in `MultiProcessCluster` significantly decreases the flakiness at startup. When all the masters are launched at the same time, Ratis can have some difficulties selecting a leading master
> Add deplay when launching multiple masters in `MultiProcessCluster`

- tests/src/test/java/alluxio/client/fs/FreeAndDeleteIntegrationTest.java
Fix flaky test
```
Error: 6.142 [ERROR] alluxio.client.fs.FreeAndDeleteIntegrationTest.deleteDir  Time elapsed: 5.849 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 3000 milliseconds
at java.base@11.0.10/jdk.internal.misc.Unsafe.park(Native Method)
at java.base@11.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
at app//io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:731)
at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:149)
at app//alluxio.grpc.FileSystemMasterClientServiceGrpc$FileSystemMasterClientServiceBlockingStub.completeFile(FileSystemMasterClientServiceGrpc.java:1672)
at app//alluxio.client.file.RetryHandlingFileSystemMasterClient.lambda$completeFile$4(RetryHandlingFileSystemMaste …
```
> Increase timeout for FreeAndDeleteIntegrationTest.deleteDir test

- core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
- core/server/master/src/main/java/alluxio/master/file/meta/SimpleInodeLockList.java
These changes are being made to address the following leak message:
```
2021-10-23 18:17:29,940 ERROR AlluxioResourceLeakDetector - LEAK: LockResource.close() was not called before resource is garbage-collected. See https://docs.alluxio.io/os/user/stable/en/operation/Troubleshooting.html#resource-leak-detection for more information about this message.
Recent access records: 
Created at:
alluxio.resource.LockResource.<init>(LockResource.java:46)
alluxio.resource.LockResource.<init>(LockResource.java:70)
alluxio.resource.RWLockResource.<init>(RWLockResource.java:39)
alluxio.resource.RefCountLockResource.<init>(RefCountLockResource.java:54)
alluxio.collections.LockPool.get(LockPool.java:210)
alluxio.master.file.meta.InodeLockManager.lockInode(InodeLockManager.java:169) …
```
> Resolve lock leak during recursive delete

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- hub/server/src/main/java/alluxio/hub/agent/rpc/service/AgentManagerService.java
- hub/server/src/main/java/alluxio/hub/manager/process/ManagerProcessContext.java
- hub/server/src/main/java/alluxio/hub/manager/rpc/interceptor/HubAuthenticationInterceptor.java
- hub/server/src/main/java/alluxio/hub/manager/rpc/observer/RequestStreamObserver.java
- hub/transport/src/main/proto/grpc/agent.proto
- hub/transport/src/main/proto/grpc/rest.proto
- Hub Manager is required to send authentication keys (API and secret keys) for all gRPC calls.
- Keys must be set via new properties in `alluxio-site.properties`
- If a Hub Manager is unauthenticated, it will attempt to shutdown all Hub Agents and itself, logging an error stating that it was unauthenticated.
This change allows the Hub Manager to use API and secret keys to prove its authentication.
New property keys
`alluxio.hub.authentication.apiKey`
`alluxio.hub.authentication.secretKey`
> Add authentication logic for Hub Manager

- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
`FaultTolerantAlluxioMasterProcess` calls `startMasters` when gaining
primacy, which can throw a `NotLeaderException` if the master has
already lost the leadership, crashing the master. This PR handles this
error
pr-link: Alluxio/alluxio#14353
change-id: cid-0f9987448f0cbd7bda9a7af5ee401497db84d8b4
3. webui
> Fix `startMasters()` from receiving unchecked exceptions

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
This test fails when worker registers with a stream, due to how the operation are rearranged for the streaming registration.
Although this is on the same codepath for unary RPC register, this does not affect the correctness.
> Fix BlockMasterIntegrityIntegrationTest for worker stream register

- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
Worker cannot report worker related cluster aggregated metrics
With this fix, worker can report both client and worker related cluster aggregated metrics to master side.
No
> Fix worker cannot report worker cluster aggregated metrics issue

- dev/scripts/generate-tarballs
- pom.xml
1. Add missing license header in `generate-tarballs`.
2. Update license check exclusion rules to exclude more irrelevant files:
* after this PR #14206 , the go mod files should be ignored for checks instead.
*  `logs` folder  contains a subfolder `user` which contains logs from running commands.
*  `metastore` is generated at runtime.
* `templates` contains templates.
They are causing warnings in the build.
No.
> Update license check rules and add missing license

- docs/en/deploy/Running-Alluxio-On-Docker.md
Tested on CentOS7.
The docker group is not automatically created after installing docker via yum, so create it manually.
Other than log out and log back in, the docker service has to restart to pick up the group change, otherwise there's permission denied error. Move the command after done with adding user to group so no need to restart docker service.
> [DOCFIX] Fix docker doc

- stress/shell/src/main/java/alluxio/stress/cli/GetPinnedFileIdsBench.java
- stress/shell/src/main/java/alluxio/stress/cli/RegisterWorkerBench.java
- stress/shell/src/main/java/alluxio/stress/cli/RpcBenchPreparationUtils.java
- stress/shell/src/main/java/alluxio/stress/cli/StreamRegisterWorkerBench.java
- stress/shell/src/main/java/alluxio/stress/cli/WorkerHeartbeatBench.java
Fix extra preparations in `RegisterWorkerBench` and `WorkerHeartbeatBench`.
Increase concurrency for both benchmarks, to accelerate benchmarking.
> Fix RPC benchmarks extra preparation and low concurrency

- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Previously, the test wasn't actually getting the real status and
comparing it to the result, so the test relied on millisecond-level
timing in order to run successfully. On constrained CI environments
this led to many failures.
Using the real status should alleviate the issue.
alleviate flaky unit test
no
> Fix flakiness of ListAllMyBuckets test

- docs/cn/compute/Flink.md
- docs/en/compute/Flink.md
In the english version of the flink doc, in the prerequisite section it says `Flink has been set up and is running.` which sounds like there should be a running cluster started by the Flink's `bin/start-cluster.sh` command. However, after the changes are made to the configuration of hadoop and flink, running the example in the doc won't work unless the running flink cluster is stopped.
> [DOCFIX] Update Flink documentation

- integration/fuse/bin/alluxio-fuse
* explicitly set required field by '-o' option to eliminate ambiguous
output column order
explicit set '-o' option to eliminate different version of ps command ambiguous output format
ps command in alpine image is from busybox, which pid is the first column by default.
No
Fixes https://github.com/Alluxio/alluxio/issues/14379
> Fix alluxio-fuse inaccurate parse ps output

- core/common/src/main/java/alluxio/metrics/TimeSeries.java
- core/common/src/main/java/alluxio/wire/MasterWebUIMetrics.java
- core/server/master/src/test/java/alluxio/master/metrics/TimeSeriesStoreTest.java
Fix metric web ui will block when data points number too large to process
This is a bug. metric web ui can't show pages, when there are too many data points. 
No
webui
> Fix metric web ui can't resolve large number datapoints

- core/common/src/main/java/alluxio/util/JvmPauseMonitor.java
Make jvm pause monitor to display gc info correctly.
I found that the jvm pause monitor could not display gc info correctly and always print `No GCs detected` even after gc. This PR fixes this issue.
> Make jvm pause monitor display gc info correctly

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
Minor tweaks to metric descriptions to the metric `FUSE_CACHED_PATH_COUNT`.
> [DOCFIX] Tweak FUSE metric and property descriptions

- docs/en/compute/Tensorflow.md
Provide a new example in tensorflow documentation. 
MNIST dataset is another well-known image recognition dataset that classifies hand-writing digits. 
The python script is slightly modified from https://www.tensorflow.org/tutorials/quickstart/advanced.
The original second example uses `tf_cnn_benchmarsk.py`, which is more suitable for tensorflow1 whereas the new example is using tensorflow2, and is no longer under maintained. Therefore remove it.
> [DOCFIX] Update tensorflow doc example

- docs/en/api/POSIX-API.md
To check standalone Fuse metrics, `alluxio.fuse.web.enabled` needs to be set to `true` in `alluxio-site.properties`. Add this to the Posix-api doc.
> [DOCFIX] Add additional requirement for fuse metrics

- docs/cn/Overview.md
- docs/en/Overview.md
remove broken link to google group mirror
> [DOCFIX] Remove broken mirror link in Overview page

- integration/kubernetes/helm-chart/alluxio/templates/worker/domain-socket-pvc.yaml
Whiteout this change, the resulting Helm template would be:
```
#
#
#
#apiVersion: v1
```
Now it will be
```
#
#
#
apiVersion: v1
```
> Remove erroneous whitespace deletion in Helm Chart

- stress/shell/src/main/java/alluxio/stress/cli/RegisterWorkerBench.java
- stress/shell/src/main/java/alluxio/stress/cli/StreamRegisterWorkerBench.java
These two bench tests did not respect register lease relevant configurations.
> Add lease support to stressbench tests

- core/server/worker/src/main/java/alluxio/worker/block/meta/DefaultStorageDir.java
- core/server/worker/src/test/java/alluxio/worker/block/meta/DefaultStorageDirTest.java
Fix incorrect available bytes when change space in StorageDir.
Otherwise the value of available bytes will greater than real available bytes And also make it thread-safe.
> Fix incorrect available bytes when change space in StorageDir

- shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
When distributingload the file, if the file status is incompleted, skip this file
When distributeload files, if the file status is incompleted, the command will get stuck.
No
> Fix the stuck situation when distributedLoad incompleted file

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/MultipartUploadCleaner.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ErrorCode.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
#14257
Add these PropertyKey:
1. `alluxio.proxy.s3.multipart.upload.timeout` 
2. `alluxio.proxy.s3.multipart.upload.cleaner.retry.count`
3. `alluxio.proxy.s3.multipart.upload.cleaner.retry.delay`
4. `alluxio.proxy.s3.multipart.upload.cleaner.pool.size`
> Support auto abort multiupload after timeout

- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- job/server/src/main/java/alluxio/master/AlluxioJobMasterProcess.java
Before this change, journal-system was still active, during shut-down, after masters were closed.
This causes `NullPointerException`s for `BlockMaster` as the block-store was closed but the journal system was still pushing entries.
> Stop journal before masters during shut-down

- shell/src/main/java/alluxio/cli/fs/command/FreeCommand.java
When the file in Alluxio percentage  is zero or the path is a directory, the logic in  waitFor will free again.    
The logic may cause  redundant free call to master.
No
> Fix redundant free when inAlluxio percentage is 0

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/templates/csi/controller-rbac.yaml
- integration/kubernetes/helm-chart/alluxio/templates/csi/pvc-static.yaml
- integration/kubernetes/helm-chart/alluxio/values.yaml
1. The versions of csi node driver registrar and csi provisioner are old and not supported any more. Bump them up to a newer version. 
2. Fix a typo in the controller-rbac template.
3. Improve static pvc so it won't look for any existing storageClass.
> Improve /fix/upgrade CSI template

- dev/scripts/.gitignore
running the generate-tarball and check-docs commands builds an intermediate go binary
these binaries are usually invoked and then removed as part of successfully completing the script execution
when the script terminates unexpectedly and does not reach the cleanup step, the intermediate binaries are leftover and pollutes the git workspace
adding the intermediate binaries to gitignore to keep a more pristine workspace in the failure scenario for these scripts
> Add gitignore for intermediate go binaries

- core/common/src/main/java/alluxio/master/ZkMasterInquireClient.java
Both `PrimarySelectorClient` and `ZKMasterInquireClient` communicate with ZK servers, but only `PrimarySelectorClient` has the ZK 3.4 compatibility flag enabled. This brings both in line with each other.
> Enable Zookeeper 3.4 compatibility mode for `ZKMasterInquireClient`

- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
This change fixes the failing tests in `AlluxioMasterProcessTest`. See [this SO post](https://stackoverflow.com/questions/7442875/generating-hmacsha256-signature-in-junit) for details about the solution.
> Use Powermock annotation to support javax.crypto

- core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketResult.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
S3 doesn't have dir concept so it will return size 0 for all non-object content with delimiter /.
make return value correct, tested as follows:
```
aws s3api list-objects-v2 --bucket shouwei-test
{
"Contents": [
{
"LastModified": "2021-11-04T01:33:07.000Z", 
"ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"", 
"StorageClass": "STANDARD", 
"Key": "alluxio/", 
"Size": 0
}, 
{
"LastModified": "2021-11-04T01:33:08.000Z", 
"ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"", 
"StorageClass": "STANDARD", 
"Key": "alluxio/special_backups/", 
"Size": 0
}, 
{
"LastModified": "2021-11-04T01:33:08.000Z", 
"ETag": "\"4a6b70de44d18dffbd94860a7d60f9e2\"", 
"StorageClass": "STANDARD", 
"Key": "alluxio/special_backups/alluxio-backup-2021-11-04-1635989588831.gz", 
"Size": 190
}
]
}
aws s3api list-objects-v2 …
```
> Fix S3 API ListStatus return value

- core/server/master/src/main/java/alluxio/master/block/RegisterStreamObserver.java
During a worker registration stream, we identify stale stream and `DefaultBlockMaster$WorkerRegisterStreamGCExecutor` recycles them based on the last-message-received timestamp. This change updates the timestamp more often.
There will be fewer false positives for stale streams. The false positives are expensive.
NA
> Update register stream timestamp more often

- core/common/src/main/java/alluxio/master/ZkMasterInquireClient.java
Prevents using container parents as it breaks compatibility with zk 3.4.x servers. This logic is ported from `PrimarySelectorClient`.
> Add another call to ensure compatibility with zk 3.4

- docs/en/reference/Metrics-List.md
Fix missing placeholders in some metric names in docs, e.g. https://docs.alluxio.io/os/user/edge/en/reference/Metrics-List.html#master-metrics , by changing the placeholders to use curly braces rather than triangle parentheses. 
These dynamically generated metrics have placeholders in the name, but they are not rendered properly:
That is because the markdown parser interprets the placeholders warped inside `< >` as HTML tags:
> [DOCFIX] Fix missing placeholder in metric names

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalConfiguration.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java
Redo of PR #14553 by @lilyzhoupeijie. 
Change the thread pool used by `CompletableFuture.runAsync` from the common pool to a separate `ForkJoinPool`. This is because of the concerns raised in [this article](https://dzone.com/articles/be-aware-of-forkjoinpoolcommonpool) about the common pool.
> Change the thread pool for `CompletableFuture.runAsync`

- core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
Display unescape the ufs URI.
Display unescape the ufs URI
original:
now:
> Display unescape the ufs URI

- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AInputStream.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3ALowLevelOutputStream.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AOutputStream.java
Use virtual functions instead of AmazonS3 for temp token refresh.
> Use virtual functions instead of AmazonS3 for temp token refresh

- core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataReader.java
LocalFileDataReader should check the path from the local worker,
if the path can not be found, so falling back to the network transfer.
The case may happen on the K8S, such as, client and worker in two diffrent containers
core/client:LocalFileDataReader Factory check the path from the local worker
LocalFileDataReader should check the path from the local worker,
if the path can not be found, so can falling back to the network transfer.
The case may happen on the K8S, such as, client and worker in two diffrent containers，
client can not see the  worker data path.
2. addition …
> Make short-cirtcuit can fall back to grpc when path notfound

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
Add metric to monitor checkpoint
Refer to the implementation of AlluxioMasterRestServiceHandler#getWebUIOverview. Although there will be an alert on the web page when the checkpoint is abnormal, we want to use a third-party operation and maintenance system to monitor this situation, so we hope to expose this metric. When it is 1, the monitoring system is triggered to send an alarm message .
No
> Add metric to monitor checkpoint

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
- integration/kubernetes/helm-chart/alluxio/templates/config/alluxio-conf.yaml
Fixes a typo in alluxio helm charts.
The typo prevents us from passing custom mount options (e.g, `allow_other`) to alluxio's helm charts.
None.
> [SMALLFIX] Correct the property name in the helm charts

- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
Switch the `ExecutorService` that `JournalStateMachine` uses from `ThreadPoolExecutor` to `ForkJoinPool`.
This PR is an update after #14559. Combined, these two PRs remove the `JournalStateMachine`'s reliance on the `ForkJoinPool.commonPool()`. This reliance is undesirable as explained in [this article](https://dzone.com/articles/be-aware-of-forkjoinpoolcommonpool).
No.
> Change `JournalStateMachine`'s executor service

- integration/docker/entrypoint.sh
- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/templates/config/alluxio-conf.yaml
- integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
- integration/kubernetes/helm-chart/alluxio/values.yaml
Previously using helm chart we can only mount the whole Alluxio storage. Now by specifying `FUSE_ALLUXIO_PATH` in the helm chart, we are able to mount one specific directory in Alluxio, both for standalone Fuse and workerFuse.
> Enable mount specific dir in Alluxio in helm chart

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/common/src/main/java/alluxio/ExecutorServiceBuilder.java
- core/server/common/src/main/java/alluxio/executor/ExecutorServiceBuilder.java
- core/server/common/src/test/java/alluxio/master/ExecutorServiceBuilderTest.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
This PR refactors `alluxio.master.ExecutorServiceBuilder` to the top level package `alluxio.ExecutorServiceBuilder`, and adds it as the executor for the Worker's `GrpcServer`.
Without specifying an executor for `GrpcServer`, it will be assigned a [default executor](https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerBuilder.html#executor-java.util.concurrent.Executor-). In our case this would be the `DEFAULT_WORKER_EVENT_LOOP_GROUP_POOL` from [NettyServerBuilder](https://github.com/grpc/grpc-java/blob/ee581bfdfa03e7b0f96fd99e287f5a326648bc42/netty/src/main/java/io/grpc/netty/NettyServerBuilder.java#L85-L86).
This is an unbounded pool which results in unbounded memory consumption by gRPC worker threads. In highly concurrent workloads this can lead to memory exhaustion.
1. …
> Refactor ExecutorServiceBuilder and add to Worker gRPC server

- underfs/cephfs/src/main/java/alluxio/underfs/cephfs/CephFSUnderFileSystem.java
- underfs/cephfs/src/main/java/alluxio/underfs/cephfs/CephSeekableInputStream.java
The input stream of CEPHFS as under filesystem. This input stream supports seeking and can be
cached for reuse.
Signed-off-by: Xue Yantao <xueyantao2114@163.com>
3. webui
> Make ufs cephfs seekable

- core/common/src/main/java/alluxio/conf/RemovedKey.java
Fix Alluxio/new-contributor-tasks#610
alluxio.user.hostname is not deprecated and is still used. 
So remove it from REMOVED_KEYS of alluxio.conf.RemovedKey.
> [SMALLFIX] Remove alluxio.user.hostname from REMOVED_KEYS

- core/common/pom.xml
- pom.xml
This reverts commit 71f76a1803bc57f196601578b5d16862faf47875.
For backwards compatibility reasons.
> Revert "Upgrade zookeeper from 3.5.5 to 3.5.8"

- webui/master/src/containers/pages/Workers/Workers.test.tsx
- webui/master/src/containers/pages/Workers/Workers.tsx
- webui/master/src/containers/pages/Workers/__snapshots__/Workers.test.tsx.snap
Add the header information of the worker page in the kubernetes environment.
When Alluxio is used in the k8s environment, two ips will be displayed on the worker page, namely hostip (podip), but the header is marked as Node Name, which is now modified to display as Node Name (Container Host) 
yes
> Add webui information in kubernetes environment

- integration/docker/entrypoint.sh
- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/templates/config/alluxio-conf.yaml
- integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
- integration/kubernetes/helm-chart/alluxio/values.yaml
Previously using helm chart we can only mount the whole Alluxio storage.
Now by specifying `FUSE_ALLUXIO_PATH` in the helm chart, we are able to
mount one specific directory in Alluxio, both for standalone Fuse and
workerFuse.
pr-link: #14599
change-id: cid-89a283a3246d855f2d00f9fa516f4855f082911a
> Merge mount Alluxio path in k8s & resolve conflict

- core/common/src/main/java/alluxio/cli/Command.java
- shell/src/main/java/alluxio/cli/bundler/command/CollectConfigCommand.java
- shell/src/main/java/alluxio/cli/bundler/command/CollectEnvCommand.java
- shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java
- shell/src/main/java/alluxio/cli/bundler/command/CollectMetricsCommand.java
- shell/src/main/java/alluxio/cli/fsadmin/command/JournalCommand.java
- shell/src/main/java/alluxio/cli/fsadmin/command/MetricsCommand.java
- shell/src/main/java/alluxio/cli/fsadmin/command/PathConfCommand.java
- shell/src/main/java/alluxio/cli/fsadmin/journal/QuorumCommand.java
Add a default hasSubCommand in Command to simplify the command implementations. 
- Add a default hasSubCommand in Command
- Remove useless implementations from all class implemented from command.
No
> Add a default hasSubCommand in Command

- pom.xml
Upgrade log4j to 2.15.0
Address security vulnerability
> Upgrade log4j to 2.15.0 to address CVE-2021-44228

- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Avoid creating the empty object for root
To avoid some customized S3 object storage error.
> Avoid creating the empty object for S3 root

- core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java
Now the `alluxio.master.worker.register.lease.enabled` is read once the `BlockMasterWorkerServiceHandler` object init instance, but cannot be updated after that.
Read the propertykey from `ServerConfiguration` each time for worker register, never mind the performance down, since the register request for each worker have only one time, and get a value from `ServerConfiguration` have no io operation.
NO
> Support register.lease.enabled can be updated

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/templates/config/alluxio-conf.yaml
Fixes a typo in the helm charts. I haven't tried, but I believe it should be `printf` otherwise the `alluxioPath` will be rendered as `%v/` which shouldn't work.
1. change in user-facing APIs: None
2. addition or removal of property keys: None
3. webui: None
> [SMALLFIX] Correct the configuration rendering for alluxioPath

- pom.xml
2.16.0 resolves more security legacy issues from 2.15.0
Ref: https://www.zdnet.com/article/second-log4j-vulnerability-found-apache-log4j-2-16-0-released/
> Upgrade log4j to 2.16.0

- core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
Change a ConcurrentHashSet to HashSet to reduce cost in metadata sync.
The collection is only locally used for reading and can be changed to HashSet for lower cost.
NA
> Change a collection from ConcurrentHashSet to HashSet in sync

- pom.xml
Ref https://logging.apache.org/log4j/2.x/security.html#CVE-2021-45105
> Upgrade log4j 2.17.0

- build/checkstyle/alluxio_checks.xml
- build/checkstyle/suppressions.xml
- core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
- core/common/src/main/java/alluxio/master/MasterInquireClient.java
- core/server/master/src/main/java/alluxio/master/file/meta/UfsAbsentPathCache.java
- core/server/master/src/main/java/alluxio/master/file/meta/UfsBlockLocationCache.java
- core/server/master/src/main/java/alluxio/master/metastore/BlockStore.java
- integration/fuse/src/main/java/alluxio/cli/command/AbstractFuseShellCommand.java
- integration/fuse/src/main/java/alluxio/cli/command/metadatacache/AbstractMetadataCacheSubCommand.java
- integration/fuse/src/main/java/alluxio/cli/command/metadatacache/DropAllCommand.java
- integration/fuse/src/main/java/alluxio/cli/command/metadatacache/DropCommand.java
- integration/fuse/src/main/java/alluxio/cli/command/metadatacache/SizeCommand.java
The issue is that the Checkstyle Javadoc rules previously (before #14537) checked both the existence and the format of Javadocs. When they were updated, the Javadoc rules only regarded the format of Javadocs, no longer their existence. This rectifies this oversight.
> Include missing Javadoc comments on public methods and classes

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
Create the HashSet with the correct total size to avoid resizing of million blocks.
> Use HashSet sized contructor in worker register

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- hub/server/src/main/java/alluxio/hub/manager/process/ManagerProcessContext.java
Previously we were using the Alluxio cluster id to unique identify a Hub cluster. This PR introduces a new property key that users must set to uniquely identify. their Hub cluster. This allows the Hub Manager to register with the Hosted Hub immediately, instead of depending on retrieving the Alluxio cluster id from the Meta Master before registering.
This change is Hub-related and allows users to uniquely identify their Hub clusters.
Added property key `alluxio.hub.cluster.id` - a 4-character, alphanumeric string
> Use user-defined Hub cluster ID

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Explicitly catch 0x8001 open for write cases. 
Don't use (flags & 0b11) != 0 to detect overwrite since 0X8002， 0xc002 open for read is included.
To avoid detect 0xc002 open for read as open for overwriting
To support 0x8002 for open for read or open for write
Fix read failures
> Fix Fuse open flags 0b11

- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Fix incorrect result in linux vim ：wq
modify file.
vim modify file will have many same write requests
it will write(offset=0,size=4096)
and then write(offset=0,size=4096) again.
The changes are validated.
correct the vim modify file results.
> Fix Fuse write

- stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java
We create a new dir `fuseIOStressBench` inside `localPath` and all files will be written and read inside this new directory. We can then avoid the case that the test files interfere with other files in Alluxio space.
> Put all Fuse Stressbench operations in a new dir

- shell/src/main/java/alluxio/cli/fs/command/ChgrpCommand.java
- shell/src/main/java/alluxio/cli/fs/command/ChmodCommand.java
- shell/src/main/java/alluxio/cli/fs/command/ChownCommand.java
- shell/src/main/java/alluxio/cli/fs/command/CpCommand.java
- shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
- shell/src/main/java/alluxio/cli/fs/command/RmCommand.java
- tests/src/test/java/alluxio/client/cli/fs/command/RmCommandIntegrationTest.java
Fix #8498 
In this patch, I tried to use a method similar to Option.alias(), but
org.apache.commons.cli.Option does not provide a similar function, so I chose to add an ANOTHER_RECURSIVE_OPTION. If there is a better implementation, please suggest it and I will change the code.
make the option consistent with fs shell
No
> Make recursive options consistent in the filesystem shell

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- tests/src/test/java/alluxio/client/cli/fs/command/CheckConsistencyCommandIntegrationTest.java
- tests/src/test/java/alluxio/client/fs/CheckConsistencyIntegrationTest.java
Check consistency should check case that exist in UFS but not exist in alluxio
Now if a file exists in UFS but not in alluxio, then the `checkConsistency` command will not return any consistency information. This PR fixes this issue.
> Make the checkConsistency command check more cases

- integration/metrics/docker-compose-master.yaml
- integration/metrics/docker-compose-worker.yaml
update otel/opentelemetry-collector-dev:latest to otel/opentelemetry-collector-dev:b24db545eb56e2ee7dcf6a8f3740ce49bb80608b
Files under alluxio/integration/metrics use "otel/opentelemetry-collector-dev:latest" which is not backward compatible.
Changed to "otel/opentelemetry-collector-dev:b24db545eb56e2ee7dcf6a8f3740ce49bb80608b".
> Fix Alluxio/new-contributor-tasks#613

- docs/en/compute/Tensorflow.md
The original download will download the whole html instead of the script. 
Add `?raw=true` to make it download the python script.
> [DOCFIX] Fix tensorflow training script download

- pom.xml
address vulnerability described by https://logging.apache.org/log4j/2.x/security.html#CVE-2021-44832
> Upgrade log4j to 2.17.1

- core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
The existing log is 
```
2021-12-31 17:15:20,810 DEBUG ShortCircuitBlockReadHandler - Enter(stream): OpenBlock: Session=0, Request=null
```
Because the `mRequest` is set only in the lambda.
> [SMALLFIX] Fix logging for OpenLocalBlock RPC

- core/common/src/main/java/alluxio/grpc/GrpcUtils.java
- core/common/src/main/java/alluxio/security/authorization/AccessControlList.java
- core/common/src/main/java/alluxio/util/proto/ProtoUtils.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/master/src/main/java/alluxio/master/file/meta/MutableInode.java
- core/server/master/src/main/java/alluxio/master/file/meta/MutableInodeDirectory.java
- core/server/master/src/main/java/alluxio/master/file/meta/MutableInodeFile.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/acl/SupportedHdfsAclProvider.java
Use `intern()` on frequent strings like user/group names. This should change the string memory allocation from the heap into the internal string pool by an extent so we allocate fewer objects (and subsequently friendly to GC).
In a heap analysis I see many duplicate Strings. For example when I run a cluster on AWS with `ec2-user` as both user and group, I see many duplicate "ec2-user" strings from a heap analysis:
My heap size is 15G and 1.7G are allocated  to user/group name strings. I have around 25 million files. Note that the 50K String objects are the live objects. There should have been many more and GC-ed from the heap.
If I'm reading correctly, each string retains 56 bytes in heap.
Using `intern()` should avoid many new String allocations. …
> Add string interning to user and group names

- core/common/src/main/java/alluxio/util/FormatUtils.java
add EB in FormatUtils.getSizeFromBytes.
While ufs is very very large, it can display as xxxxEB.
> Fix FormatUtils.getSizeFromBytes should supports EB

- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
Changed the default command when generating tarball.
The default command to generate a tarball is `mvn -T 1 -am .....` the first parameter `-T 1` means only a thread to be used when compiling. If you want to increase the number of compiled threads, you can pass in the -T parameter through `-mvn-args` for example `-mvn-args "-T,1C" ` which can increase the speed of compilation.
After testing, if the mvn command has multiple -T given, only the first one will take effect, for example, `mvn -T 1 -T 1C` which is equivalent to `mvn -T 1 `, to ensure that the "-T" parameter passed from "-mvn_args" can take effect, need to put the default `-T 1` parameter after the `-T X` parameter given by `-mvn-args`
Tested on my Linux (16 cores), if the -mvn-args "-T,1C" parameter is given, the generate a …
> Change generate tarball command

- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/test/java/alluxio/fuse/AlluxioJniFuseFileSystemTest.java
Fix alluxio fuse don't display atime problem
When exec stat file command in alluxio fuse mount point, the result can't show atime.
No
> Fix alluxio fuse atime unable to display problem

- docs/en/deploy/Running-Alluxio-On-Kubernetes.md
Fix wrong file name in docs, e.g. [https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html#posix-api](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html#posix-api). The file name in command should be alluxio-nginx-pod.yaml.template.
> [DOCFIX] Fix wrong file name in k8s doc

- conf/log4j.properties
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
Change the log format to improve performance. This impacts job master/worker log and audit log.
`%F` is the file that log event is from (java file)
`%M` is the method
Example log looks like this
```
2021-12-14 17:26:32,763 INFO master.AbstractMaster (AbstractMaster.java:stop) - JobMaster: Stopping primary master.
2021-12-14 17:26:32,764 INFO master.AbstractMaster (AbstractMaster.java:stop) - JobMaster: Stopped primary master.
```
As log4j document specifies, using `%F` and `%M` will hurt performance. We have `%c{1}` which outputs the class name anyways so these info are not necessary.
https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternFile in sections for `%F` and `%M`
The log will look different. I don't think anyone is parsing those anyways so the impact should be small …
> Update log4j configuration for performance

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- table/shell/pom.xml
- table/shell/src/main/java/alluxio/cli/table/command/LoadTableCommand.java
Add LoadTableCommand to make it more friendly for SDS users. Users can execute `alluxio table load <database> <table>` to load data under the table.
This command is designed almost as the same as distributedLoad. The only difference is that users won't care about specific files in `table  load` command. There will be more options in future to pick up specific data in table semantics, like specific partitions.
> Add LoadTableCommand

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
Remove permission check from Sync in InodeSyncStream. Sync is the server behavior, should not be checked permission against the client user.
> Remove permission check from Sync in InodeSyncStream

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseOpenUtils.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/test/java/alluxio/jnifuse/struct/FuseFileInfoTest.java
Fixes https://github.com/Alluxio/alluxio/issues/14740
Fuse open with different flags has different interpretations.
Fuse can open file for read/write/read and write/ append .....
we need to handle them correspondingly.
Fuse open() behaviors
> Handle Fuse open flags

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Without this MediaType, hadoop s3a cannot works with alluxio s3 proxy.
The aws-java-sdk-s3 which hadoop s3a dependent add a `Content-Type` `application/x-www-form-urlencoded` default, 
And if Alluxio s3 proxy don't add the `APPLICATION_FORM_URLENCODED` consumer, Alluxio proxy will throw an `NotSupportedException`.
```Console
bin/hdfs dfs -ls s3a://test/
21/12/23 00:53:19 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/12/23 00:53:19 INFO security.UserGroupInformation: Hadoop UGI authentication : SIMPLE
21/12/23 01:03:40 WARN s3a.S3AFileSystem: Client: Amazon S3 error 415: 415 Unsupported Media Type; Unsupported Media Type (retryable)
com.amazonaws.services.s3.model.AmazonS3Exception: Unsupported Media …
```
> Add APPLICATION_FORM_URLENCODED to S3RestServiceHandler

- stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
Mark the byte buffer after creation and reset it after read is done.
If it is not reset after read, the position of the byte buffer is at its limit, and following read will always write 0 bytes into the buffer.
Reference: https://docs.oracle.com/javase/8/docs/api/java/nio/Buffer.html#reset--
> Fix byte buffer not reset after read in client IO bench

- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
when type bin/alluxio fsadmin report metrics, the ufs url excaped.
1.Unescape all names.
2.The  unescape function  is `return uri.replace("%2F", "/").replace("%2E", ".").replace("%25", "%");`. We have not any metrics name is  %2F,%2E or %25, so it is will be safe.
no
> Fix unescape the ufs url of alluxio fsadmin report metrics result

- docs/_data/table/cn/WriteType.yml
- docs/_data/table/en/WriteType.yml
Update FS-API document regarding default write type.
commit 35ea6fc6aa066a40d732430f948b452caff78a5b updated the default write type value from MUST_CACHE to ASYNC_THROUGH. 
FS-API did not update accrodingly. This PR fixes this issue  both in English and Chinese version.
No.
> [DOCFIX] Update obsolete default WriteType value

- underfs/ozone/src/main/java/alluxio/underfs/ozone/OzoneUnderFileSystemFactory.java
Fix ozone `supportsPath` function bug
PropertyKey `UNDERFS_VERSION` has a default value of `3.3` which makes `conf.isSet(PropertyKey.UNDERFS_VERSION)` always `true`, This causes  to ozone `supportsPath` function return the wrong value (The default value of `3.3` is not equal to the version of ozone. So the result of `conf.get(PropertyKey.UNDERFS_VERSION).equals(getVersion())` is false)
No
> Fix ozone supportspath

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Fix typo in code to show correct error message
2021-12-19 22:52:13,523 ERROR AlluxioJniFuseFileSystem - Failed closing /animals_12101333.h5
alluxio.exception.status.AlreadyExistsException: File FileSystemMaster has already been completed.
at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:138)
at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:224)
at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:408)
at alluxio.AbstractClient.retryRPC(AbstractClient.java:372)
at alluxio.AbstractClient.retryRPC(AbstractClient.java:361)
at alluxio.client.file.RetryHandlingFileSystemMasterClient.completeFile(RetryHandlingFileSystemMasterClient.java:171)
at …
> [SMALLFIX] Fix complete file error message

- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
Fix #10365
Before:
After:
And I find that staging path also didn't exist with writing directly to hdfs.
See #10365 
No
> Fix warning on failed dir deletion after running a Spark job

- tests/src/test/java/alluxio/client/cli/job/DistributedCommandsCancelStatsTest.java
- tests/src/test/java/alluxio/job/util/JobTestUtils.java
Add timeout for waitForJobStatus in DistributedCommandsCancelStatsTest
Add adjustable timeout for the test, some test jobs need to have longer timeouts.
> Add timeout for waitForJobStatus in DistributedCommandsCancelStatsTest

- core/server/master/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java
fix journal dumper not work.
when use command `./bin/alluxio readJournal` will face error like:
```
java.lang.RuntimeException: java.lang.IllegalStateException: Raft journal entries should never set multiple fields in addition to sequence number, but found sequence_number: 6
update_inode {
id: 0
last_modification_time_ms: 1641571923648
last_access_time_ms: 1641571923648
}
operationId {
mostSignificantBits: 3407999256801922785
leastSignificantBits: -4799816901488576434
}
at alluxio.master.journal.tool.RaftJournalDumper.lambda$readRatisLogFromDir$0(RaftJournalDumper.java:99)
at org.apache.ratis.server.raftlog.segmented.LogSegment.readSegmentFile(LogSegment.java:141)
at org.apache.ratis.server.raftlog.segmented.LogSegment.readSegmentFile(LogSegment.java:125)
at …
```
> Fix journal dumper not work

- pom.xml
Try updating protobuf to resolve some CVEs.
Some CVEs are caused by protobuf version. This PR updates protobuf to a fixed version.
No
> Update protobuf version

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
A workaround for https://github.com/Alluxio/alluxio/issues/14715 and https://github.com/Alluxio/alluxio/issues/14838
Otherwise Alluxio fuse by default will do the wrong permission check
Permission check will be performed by kernel when using Alluxio-Fuse
> Add default_permissions fuse mount option

- core/common/src/main/java/alluxio/conf/PropertyKey.java
The default value of `alluxio.master.metastore.inode.cache.max.size` is computed at runtime based on the max memory of master JVM. However, the doc for that prop entry is statically generated at build time, thus reflecting the default value on the build machine.
This PR fixes the description, so that the doc correctly shows the formula used to compute the runtime default value, instead of a build time constant.
This is mostly doc fix.
> Fix default value and description for inode cache property key

- docs/en/ufs/HDFS.md
The default port of HDFS web UI is 9870 in the version over 3.0.0
1. If not, the User will think that he configured the HDFS incorrectly.
no
> [DOCFIX] Fix the HDFS document

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseOpenUtils.java
Filebench will use 0xc002 open flag to open the file for reading.
Support using 0xc002 to open file for reading
NA
> Add another open for read flag

- core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStoreOptions.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockStore.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksUtils.java
- core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksStoreTest.java
Fixes https://github.com/facebook/rocksdb/issues/9378
The `orgs.rocksdb.RocksObject` extends `AutoCloseable` so they should be closed properly to avoid leaks. 
According to the [RocksDB documentation](https://github.com/facebook/rocksdb/wiki/RocksJava-Basics#memory-management) and a sample [PR discussion](https://github.com/facebook/rocksdb/pull/7608#discussion_r515159270), the objects need to be closed or wrapped in a try-with-resource block.
NA
> Close RocksDB objects that are AutoCloseable

- tests/src/test/java/alluxio/client/cli/job/DistributedCommandsCancelStatsTest.java
Added Sleeping UFS in DistributedCommandsCancelStatsTest 
Use Sleeping UFS to make sure the operations on UFS would sleep and CANCEL operations would happen while the UFS operations are in progress.
> Use Sleeping UFS for DistributedCommandsCancelStatsTest

- core/transport/pom.xml
- core/transport/src/main/proto/proto.lock
- pom.xml
Protolock prevents incompatible protobuf changes such as removing a field from a proto , but we are not using it correctly so far. 
https://github.com/salesforce/proto-backwards-compat-maven-plugin
Better backwards compatibility
> Update protolock plugin

- core/common/src/test/java/alluxio/AlluxioTestDirectory.java
- tests/src/test/java/alluxio/master/table/TableIntegrationTest.java
Change temp dir creation to be unique and delete upon jvm exit. 
When github runs test with multiple jvms, the two jvms can try to create temp dir at the same time and cause the following error. 
```
Error: 5.534 [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.85 s <<< FAILURE! - in alluxio.client.cli.fsadmin.BackupCommandIntegrationTest
Error: 5.542 [ERROR] alluxio.client.cli.fsadmin.BackupCommandIntegrationTest  Time elapsed: 0.762 s  <<< ERROR!
java.lang.ExceptionInInitializerError
at alluxio.master.AbstractLocalAlluxioCluster.setAlluxioWorkDirectory(AbstractLocalAlluxioCluster.java:362)
at alluxio.master.LocalAlluxioCluster.initConfiguration(LocalAlluxioCluster.java:128)
at alluxio.testutils.LocalAlluxioClusterResource.start(LocalAlluxioClusterResource.java:15 …
```
> Handle temp directories correctly for multiple test jvm

- stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java
We create a directory `fuseIOStressBench` in `mParameters.mLocalPath` for the stressbench. The whole process should be, first `getattr()`, find out it doesn't exist, then `create()`.
In cluster mode, job worker 1 may `getattr()` first and find out it doesn't exist. Before job worker 1 calls `create()`, job worker 2 calls `create()` first, and thus now the path `/fuseIOStressBench` exists, which makes worker1 `create()` fail.
With this fix, the node that issues the stressbench command will create `/fuseIOStressBench` before job service sends the distributed job to job workers, so that by the time the job worker starts the stressbench, the path already exists and they won't race on creating this path.
This requires that the node starting the stressbench command also needs the fuse process …
> Create the test dir earlier in Fuse stressbench cluster mode

- integration/fuse/src/main/java/alluxio/fuse/auth/CustomAuthPolicy.java
- integration/fuse/src/main/java/alluxio/fuse/auth/SystemUserGroupAuthPolicy.java
1. Use the correct method to get the username for cache.
2. Correct assignment to Group and Owner.
1. Currently, using the getGroupName method to get the username, the getUserName method should be used.
2. The option parameter assignment is reversed.
no
> Fix wrong method call to get username and wrong parameter assignment

- core/server/common/src/main/java/alluxio/ProcessUtils.java
Currently when ProcessUtils.fatalError() is called without a Throwable object no stack trace is printed.
In this change, a new Throwable object is created which is used to print the stack trace.
Fixes #10432
No
> Print stack trace from ProcessUtils.fatalError()

- integration/fuse/bin/alluxio-fuse
Previously
integration/fuse/bin/alluxio-fuse unmount /path/to/mount/point
will work, but
integration/fuse/bin/alluxio-fuse unmount /path/to/mount/point/
will give error "/path/to/mount/point/ not mounted". Strip the trailing
slash so both would work.
Fixes #11203
> Fix argument in alluxio-fuse unmount when argument has trailing slash

- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
Fix metrics Worker.ActiveClients counter error
When executing end-to-end test: allxuio runTest --readType NO_CACHE --writeType THROUGH. the counter metric Worker.ActiveClients.xxx will change to 2 instead of 0.
No
> Fix metrics Worker.ActiveClients counter error

- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
If `alluxio.fuse.debug.enabled` is set to true, set the log level of class `alluxio.fuse.AlluxioJniFuseFileSystem` to `DEBUG`
> Set AlluxioJniFS log level to DEBUG if fuse debug on

- integration/docker/entrypoint.sh
- integration/kubernetes/helm-chart/alluxio/templates/config/alluxio-conf.yaml
- integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
- integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml
- copy over `log4j.properties` in `docker/entrypoint.sh` in order for Alluxio cluster + Hub in k8s env to properly start
- fix formatting issues in (hub) helm chart yaml files
These changes are required for the Hub to be properly launched via kubernetes.
no
> Fix Hub + k8s issues due to bad formatting and missing log4j.properties

- shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java
`CollectLog` cli command doesn't collect fuse-related logs. Include them in the included logs.
> Add fuse log to collectLog command

- integration/docker/entrypoint.sh
Populate both log4 and site-properties files if the environment variables are set (due to making changes via Hub). Previous [PR](https://github.com/Alluxio/alluxio/pull/14913) was only populating log4j properties, so config changes were lost on Hub Manager pod restarts 
This change allows the following logic to work properly:
- The Hub manager persists changes to the K8s API server, communicating using the fabric8.io library. This is the same library used by Spark on K8s and is considerably less verbose than the official K8s java binding.
-  Hub manager writes env, site, and log4j properties to the K8s configMap as environment variables 
- The docker entrypoint populates these files if the environment variables are set
Explained above
no
> Preserve config changes made by Hub on pod restarts

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
Fix the bug which load metadata failed when the path is special.
For example, there are some files whose names are like `tmp\flinkxdata\.data\2c64b72a51458ea04db1b9e25c1cd834_0_0`. Alluxio will transfer the file names into a path like `tmp/flinkxdata/.data/2c64b72a51458ea04db1b9e25c1cd834_0_0`. When loading metadata from ufs will failed every times, leaded to unable to refresh some new metadata which is at the back of special files.
Before:
After:
None
> Fix the bug which load metadata failed when the path is special

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
Add worker registry timeout property key to make the timeout adjustable.
As a temporary plan to serve https://github.com/Alluxio/alluxio/issues/14503
1. addition of property key `alluxio.worker.startup.timeout`
> Add worker startup timeout property key

- core/server/common/src/main/java/alluxio/master/PrimarySelectorClient.java
Tracking lifecycle state of `PrimarySelectorClient` properly propagates errors if it is started after being closed. Close before start is a noop.
> Track lifecycle state of PrimarySelectorClient

- webui/master/src/containers/pages/Workers/Workers.test.tsx
- webui/master/src/containers/pages/Workers/Workers.tsx
- webui/master/src/containers/pages/Workers/__snapshots__/Workers.test.tsx.snap
Fixed an issue where `Node Name` header in Worker page was rendering per worker
Note: Replacing https://github.com/Alluxio/alluxio/pull/14898 with proper fix
See above
Yes, web UI Worker page table is fixed to prevent repeat `Node Name` headers from rendering.
> Fix UI Worker page table header issue

- integration/docker/csi/README.md
The CSI driver directory is lacking a README. We are trying to add Alluxio CSI driver into kuberbetes csi drivers list documentation, and the hyperlink to Alluxio CSI driver directory will be included. However currently there is no explanation of anything in that directory. This PR adds a README that points to our CSI documentation.
> [DOCFIX] Add readme to csi driver

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
Some of the local cache read metrics like bytes read, hit rate ect
are registered only when a LocalCacheFileInStream object is created.
In client systems where there are coordinators and workers, file read
might only happen on workers, while metrics are only exposed from
coordinators (e.g. Presto), resulting the metrics not being registered.
Always register the metrics when initializing LocalCacheFileSystem.
Fixes https://github.com/Alluxio/alluxio/issues/14200
> Register local cache read metrics

- tests/src/test/java/alluxio/client/fs/io/FileOutStreamIntegrationTest.java
Fix an integration test of FileOutStreamIntegrationTest#cancelWrite
Original test setup intended to customize worker-master heartbeat interval to speed up the test.
However,  a bug was introduced in https://github.com/Alluxio/alluxio/pull/10588/
which customized the wrong property key.
As a result, the grace period is only 0.5s as supposed to be 2s, introducing flakiness due to lack of time 
for block information to be propagated from worker to master.
No
> Fix flaky FileOutStreamIntegrationTest#cancelWrite

- tests/src/test/java/alluxio/job/master/JobMasterIntegrationTest.java
- tests/src/test/java/alluxio/job/util/JobTestUtils.java
**What changes are proposed in this pull request?**
Fix flaky JobMasterIntegrationTest, add more log info to guard future test flaky
**Why are the changes needed?**
This integration test uses small `JOB_MASTER_WORKER_HEARTBEAT_INTERVAL`, `JOB_MASTER_WORKER_TIMEOUT`, and `JOB_MASTER_LOST_WORKER_INTERVAL` to accelerate the integration test. This setting is totally fine when we do tests at a local machine or Jenkins. However, the `JOB_MASTER_WORKER_HEARTBEAT_INTERVAL` can take a much longer time in GitHub action, which results in a list of flaky tests. The error message is as follows:
```
Error: 3.474 [ERROR] alluxio.job.master.JobMasterIntegrationTest.throttleJobWorkerTasks  Time elapsed: 32.855 s  <<< ERROR!
java.util.concurrent.TimeoutException: Timed out waiting for job 1643913746839 to …
```
> Fix flaky JobMasterIntegrationTest

- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Modify for https://github.com/Alluxio/alluxio/issues/14895
Fix open bugs
support open(WRONLY or RDWR) then truncate(0) then write() fuse case.
For Linux, it requires open(WRONLY or RDWR) on existing file with O_TRUNC to delete existing file.
But in libfuse, the workload can be open() then truncate(0).
OPEN(RDWR) will open for read-only first, if truncate(0) then write(), it will become write-only.
Yeah, support open then truncate(0)
> Support open(WRONLY|RDWR) then truncate(0) in fuse

- core/common/src/main/java/alluxio/conf/AlluxioProperties.java
- core/common/src/test/java/alluxio/conf/AlluxioPropertiesTest.java
isSetByUser() returns inaccurate results
[isSetByUser() returns inaccurate results](https://github.com/Alluxio/alluxio/issues/14879)
NO
3. webui
> Fix isSetByUser reports incorrect config source

- tests/src/test/java/alluxio/client/fuse/AbstractFuseIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/JNIFuseIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/JNRFuseIntegrationTest.java
- tests/src/test/java/alluxio/server/worker/WorkerFuseIntegrationTest.java
Fix the `stop()` logic in FuseIntegrationTest so umounting will work for JNI, JNR and WorkerFuseIntegrationTest.
- For JNI and JNR, umount will happen before cluster stops
- For WorkFuseIntegrationTest, umount will happen after cluster stops
This PR fixes the following bug: 
The `stop()` in FuseIntegrationTest currently umounts fuse mountpoint after cluster stops. This works for WorkerIntegrationTest, but for JNI and JNR, umounting will fail with `Input/output error`, since the cluster has already stopped. In JNI and JNR's situations, umount should run before cluster stops.
No
> Fix stop logic in FuseIntegrationTest

- job/server/src/main/java/alluxio/master/job/plan/PlanCoordinator.java
Make job service output correct error message when set job status to failure
Before this change we would always get `Job set to failed without given an error type or message` because we set error message after we set job status to failure.
NA
> Fix job service error message

- hub/transport/src/main/proto/grpc/hosted.proto
- hub/transport/src/main/proto/grpc/rest.proto
Add Elasticsearch specific grpc messages to hosted.proto
These changes are needed for the Hub UI to retrieve elasticsearch env variables and dashboard id's and embed Kibana dashboards. 
3. webui
> Add ElasticsearchInfo to Hub rest.proto

- bin/alluxio
- bin/alluxio-monitor.sh
- bin/launch-process
- conf/alluxio-env.sh.template
- docs/en/operation/Troubleshooting.md
Attaching a debugger to an Alluxio process was broken. This was due to the fact that the `-agentlib` parameter was passed alongside the `ALLUXIO_JAVA_OPTS`.
For example, when trying the attach to an Alluxio master process using `suspend=y`, the `-agentlib` argument would be passed to `alluxio.cli.GetConf` and would hang until a debugger is attached to it, preventing the master from launching. 
When setting `suspend=n` but assigning a port through the `address` parameter, both `alluxio.cli.GetConf` and `alluxio.master.AlluxioMaster` would both try to set up debug servers using the same port.
This PR decouples the `-agentlib` parameter into its own configurable parameter to prevent this issue.
> Fix how to attach to Alluxio process using remote debugger

- job/server/src/main/java/alluxio/master/job/plan/PlanCoordinator.java
Correct complete metrics counter to only update when all tasks are completed.
Refactor setJobAsFailed to update failure count when setting failure status, change failure counter to update when PlanDefinitionRegistry fails to load job definition.
> Fix and refactor distributed cmd metrics

- bin/alluxio-start.sh
fix https://github.com/Alluxio/alluxio/issues/14994
Remove redundent JVM options for worker.
See https://github.com/Alluxio/alluxio/blob/master/bin/launch-process#L77
When running launch-process script, it had initialized the config. It is unnecessary to pass the worker JVM opts in alluxio-start.sh
No
> Remove unnecessary jvm opts when starting worker

- tests/src/test/java/alluxio/client/cli/job/DistributedCommandsCancelStatsTest.java
Increate sleeping ms for all the SleepingUFS ops; add sleeping time to two more AsyncPersist operations
For DistributedCommandsCancelStatsTest, there are recent failures for testAsyncPersistCancelStats test. Increate sleeping ms; add sleeping time to two more AsyncPersist operations
> Increase SleepMs and add sleeping to two more AsyncPersist operations

- conf/alluxio-env.sh.template
Follow-up to https://github.com/Alluxio/alluxio/pull/14991. Adding env examples for Hub Manager/Agent.
Adding missing examples for Hub manager and agent.
No
> Add examples for Hub Manager/Agent to alluxio-env.sh

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java
- shell/src/main/java/alluxio/cli/fs/command/RmCommand.java
When the deletion is alluxio-only, the sync is skipped.
When the deletion is alluxio-only, there should be no need to sync with the UFS. This should make large alluxio-only deletion requests much faster.
NA
> Make alluxioOnly delete not sync with UFS

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStoreOptions.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreOptions.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStoreOptions.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/store/LocalPageStoreTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreTest.java
- tests/src/test/java/alluxio/client/fs/LocalCacheManagerIntegrationTest.java
In some of our scenarios, we have to use multi-disk to be our cache storage.
- There are no enough space if we just store cache data into one disk
- There are no enough bandwidth if we just store cache data into one disk.
Store the cache data into multi-disk by hash & mod
User can config `alluxio.user.client.cache.dir=rootdir1,rootdir2,rootdir3`.
Meanwhile, this change support keep consistent to the original usage `alluxio.user.client.cache.dir=rootdir1`
> Support store client cache to multidisk

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Change https://github.com/Alluxio/alluxio/blob/b9c66ca164d363bed9bcefb776a0b0f438d96441/core/common/src/main/java/alluxio/conf/PropertyKey.java#L4193
from
.setAlias(new String[] {"alluxio.user.block.master.client.threads"})
to
.setAlias("alluxio.user.block.master.client.threads")
Fix Alluxio/new-contributor-tasks#638
> Fix Alluxio/new-contributor-tasks#638

- core/common/src/main/java/alluxio/resource/LockResource.java
- core/common/src/main/java/alluxio/resource/RWLockResource.java
- core/common/src/main/java/alluxio/resource/RefCountLockResource.java
The `RefCountLockResource#mTracker` field is removed.
`RefCountLockResource` extends `LockResource`, so `RefCountLockResource` is already leak tracked. 
In the current implementation, `RefCountLockResource` has two `mTracker` fields, one declared in its own class, the other from `LockResource`. This doubles the memory footprint for leak detection. Each `DefaultResourceLeak` object retains 1.4KB heap, which is a big cost.
NA
> Remove extra leak detector in RefCountLockResource

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
- integration/kubernetes/helm-chart/alluxio/templates/config/alluxio-conf.yaml
- integration/kubernetes/operator/alluxio/charts/alluxio-repo/alluxio/templates/config/alluxio-conf.yaml
- integration/kubernetes/operator/alluxio/charts/alluxio-repo/alluxio/templates/config/alluxio-fuse-conf.yaml
- integration/kubernetes/operator/alluxio/charts/alluxio-repo/alluxio/templates/format/master.yaml
Removal of the Helm hook annotations in our Helm chart.
The usage of Helm hooks for `ConfigMap` resources means that they cannot be `helm upgrade`-ed. We _could_ add the `"helm.sh/hook": "pre-upgrade"` annotation to address that, but I actually think these resources should not be hooks in the first place.
From the [Helm hooks documentation](https://helm.sh/docs/topics/charts_hooks/):
> **Hook resources are not managed with corresponding releases**
>
> The resources that a hook creates are currently not tracked or managed as part of the release. Once Helm verifies that the hook has reached its ready state, it will leave the hook resource alone. Garbage collection of hook resources when the corresponding release is deleted may be added to Helm 3 in the future, so any hook resources that …
> Remove usage of Helm hooks in Helm chart

- core/server/master/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/file/BlockDeletionContext.java
- core/server/master/src/main/java/alluxio/master/file/DefaultBlockDeletionContext.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
One copy over the block list is avoided in `DefaultBlockDeletionContext`.
The copy in `DefaultBlockDeletionContext.close()` guards two things:
1. A copy creates a view over the `mBlocks`, so the listeners all see the same list of blocks.
2. A copy attempts to provide better thread-safety (although it's not a reliable guarantee)
Point 1 is actually not so meaningful. On `close()`, the context really should have all block IDs ready and no one is updating the list.
Point 2 has been addressed by https://github.com/Alluxio/alluxio/pull/12715
AFAIS the copy is unnecessary now.
No.
> Remove one extra copy in block deletion

- core/client/fs/src/main/java/alluxio/client/file/cache/TimeBoundPageStore.java
Handle the interrupted exception in local cache's time bounded manager.  This change will make the higher level exit when the task got cancelled by the task owner or other threads.
Now we wrapped the interrupted exception as an IO exception.  The IO exception will be logged and swallowed in local cache's code which means the higher level caller will continue running.  We should make the higher level interrupted and exit as soon as possible  
No
> Handle the interrupted exception to make the higher level exit

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/SnapshotReplicationManager.java
- core/server/common/src/main/java/alluxio/master/journal/raft/SnapshotUploader.java
- core/server/common/src/test/java/alluxio/master/journal/raft/SnapshotReplicationManagerTest.java
- tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
Modifies the behavior of the `SnapshotReplicationManager` to allow the leading master to request a snapshot from all followers sequentially, from most recent to least recent snapshot. It also importantly recreates a new `RaftJournalServiceClient` for each new communication between leader and follower.
This addresses the issue where the leader would repeatedly request a snapshot from one flaky follower, and therefore the leader would never receive a snapshot.
The `SnapshotReplicationManager` state machine has been modified as follows:
old:
new:
`STREAM_DATA` now goes back to `REQUEST_DATA` instead of `IDLE` to request data from other followers.
`REQUEST_DATA` only goes back to `IDLE` after requesting snapshots from all followers that have a more recent snapshot than the leader's.
> Request all followers for snapshot instead of a single follower

- job/server/src/main/java/alluxio/master/job/metrics/DistributedCmdMetrics.java
- tests/src/test/java/alluxio/client/cli/job/DistributedCmdTest.java
- tests/src/test/java/alluxio/client/cli/job/DistributedCommandsStatsTest.java
1. Use increment-by-counts instead of iteration for fail and cancel stat counters
2. Refactor DistributedMetrics to skip for other non-supported job types.
1. Previously there is a performance drop, which may be caused by the PR https://github.com/Alluxio/alluxio/pull/14989. Inspecting the PR, code changes for incrementing failure counters are added. 
When the code runs for batch config, if the folder has lots of files and the batch size is huge,  incrementing failure counters in the iteration will be slow. 
Changing the iteration to adding the increment values directly will avoid the long-running loop, and thus speed up the code to run.
2. Refactored the code to skip unsupported job types, so that the code looks cleaner and …
> Use increment-by-count instead of iteration for fail & cancel counters

- core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
As @jiacheliu3 suggested in https://github.com/Alluxio/alluxio/pull/14918, it would be better to remove "callables.size() * " in the worker startup timeout caluculation.  
Make the timeout config more straight forward and easy to read.
N/A
> Simplify the worker start-up timeout logic

- core/server/common/src/main/java/alluxio/RpcUtils.java
Log linkage errors in GRPC calls
These errors get masked otherwise. This surfaces them.
> Add additional logging to log linkage errors

- core/server/worker/src/main/java/alluxio/worker/block/meta/DefaultTempBlockMeta.java
Current the block temp file name is generated with %x, while it is with %d in DefaultBlockMeta
> Modify block file temp path generation way

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Considering other timeouts that are related to this one, 5mins is a better value. Other timeouts that could potentially be counted against this one are:
- stream read/write timeout (1min)
- authentication timeout (30sec)
- RPC timeout (3min)
> Increase block-read timeout duration to 5mins

- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
- tests/src/test/java/alluxio/server/health/ProxyHealthCheckClientIntegrationTest.java
- tests/src/test/java/alluxio/testutils/LocalAlluxioClusterResource.java
In some case, we don't want to start a LocalAlluxioCluster with an alluxio proxy.
Add a includeProxy option to localAlluxioMaster
Add a includeProxy parameter to the builder of LocalAlluxioCluster for developer of Alluxio while test.
> Add includeProxy to LocalAlluxioCluster

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/metastore/BlockStore.java
- core/server/master/src/main/java/alluxio/master/metastore/heap/HeapBlockStore.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockStore.java
- core/server/master/src/test/java/alluxio/master/BackupManagerTest.java
- core/server/master/src/test/java/alluxio/master/metastore/BlockStoreTest.java
For all callers of BlockStore iterators, force them to get a CloseableIterator and use try-with-resource pattern.
Even after https://github.com/Alluxio/alluxio/pull/14964/files, there are still operation that directly iterate the BlockStore without using the CloseableIterator and try-with-resource pattern. This change is to address newly found ones.
The root cause is `BlockStore extends Iterable` which gives `Iterator` to callers. Callers are not aware that the iterators are essentially `CloseableIterator` and do not close them. It's not easy to close either, the caller must first do a checked cast to `CloseableIterator`, and the whole process just does not support try-with-resource pattern.
So this change totally removed interface of `Iterator<Block> iterator()` and provides a …
> Make all BlockStore iterations use CloseableIterator

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Earlier default (1hour) is an abnormal value for streaming timeout for a single chunk.
Let's make it more saner and watch if it causes any issues.
> Restore stream in/out timeouts to a sane value

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
RM should throw early before traversing children paths. The traversal is costly.
See above
NA
> [SMALLFIX] Make rm throw early

- integration/jnifuse/fs/src/main/java/alluxio/jnifuse/AbstractFuseFileSystem.java
Fix FUSE umount logic under Linux by falling back to `umount` if `fusermount` returns non-zero code.
Tested under Debian 11 using libfuse2 and libfuse3. CI tests umount logic on alpine:3.10.2. Need more tests on other distros.
Previously under Linux, alluxio-fuse uses `fusermount` to umount FUSE mountpoint, and if the call to `fusermount` process throws exception, use `umount` to umount instead. 
However, in some distros (like Debian 11), `fusermount` requires root privileges to umount, and **returns code 1** (not throwing exception) if not. The error message of running `fusermount -u` without root is `fusermount: failed to open /etc/mtab: No such file or directory`. But in Debian 11, `umount` can run without root privilege.
The requirement of root privileges differs in different distros. …
> Fix FUSE umount logic under Linux

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
This change trims the deletions message for large deletion failures
When many inodes fail to be deleted, the error msg will be too long for the log message and generate too many side product strings.
The error msg users see will be different. Although the message itself is trimmed, I don't think the user will need the full list of all failure messages in one go. My estimation is the first batch of error messages will be representative enough and if not, after fixing the first batch, the next try will reveal the left batch of failures and eventually all failures can be fixed.
> Improve deletion error message

- core/server/master/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/WorkerRegisterContext.java
- tests/src/test/java/alluxio/client/fs/BlockMasterRegisterStreamIntegrationTest.java
The `WorkerRegisterContext` should have the same clock from the BlockMaster. 
This change fixes the flaky test `BlockMasterRegisterStreamIntegrationTest.hangingWorkerSessionRecycled()`.
The only change in behavior is now in the tests, the `WorkerRegisterContext` will have the same manually controlled clock as other tests, so the behavior is correctly validated by tests. Before this change, `WorkerRegisterContext` relies on the system clock, which defeats all clock-based test logics.
In real use cases all classes use the JVM internal system clock so there's no behavior change at all.
NA
> Fix BlockMasterRegisterStreamIntegrationTest

- hub/transport/src/main/proto/grpc/rest.proto
- integration/hub-elastic/README.md
- integration/hub-elastic/logstash/logstash-start.sh
- integration/hub-elastic/logstash/logstash.conf
- integration/hub-elastic/metricbeat/metricbeat-start.sh
- integration/hub-elastic/metricbeat/metricbeat.yml
- Renamed proto message fields introduced in https://github.com/Alluxio/alluxio/pull/14951
- **NOTE:** renaming fields break back-compat but OK in this case since the fields (and Hub in general) aren't being used yet
- keep naming convention consistent with other related fields
- added `host` field to `ElasticsearchInfo` proto def
- added `-d` dev flag for metricbeat/logstash scripts to allow for connecting to a locally launched Elasticsearch cluster (for dev purposes)
see section above
no
> Update Hub elasticsearch field names and add dev flag for scripts

- conf/alluxio-env.sh.template
- integration/fuse/bin/alluxio-fuse
The pull request https://github.com/Alluxio/alluxio/pull/14991 added environment variables that allow attaching a debugger to various Alluxio processes. This pull request expands on those to allow attaching to the Alluxio fuse process.
Needed in order to easily debug Alluxio Fuse.
No
> Add Alluxio Fuse debug attach environment variable

- core/server/proxy/src/main/java/alluxio/proxy/s3/ListAllMyBucketsResult.java
Fix wrong format of s3 bucket creationDate.
When I use the AWS S3Client JAVA SDK to call listBuckets on AlluxioProxy, the request fails as it is unable to parse the time. The exception information is as follows:
```Exception in thread "main" software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (Text '2022-03-04T10:10:44' could not be parsed at index 19)```
no
> Fix wrong format of s3 bucket creationDate

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
This change makes the UFS fetch operation timeout configurable.
Also a minor change which uses the sized constructor for HashMap.
Some UFSes can be bad in worst response time so the fetch operation can timeout easily when the timeout is just 100ms. This might be most useful in the development stage, where the user is accessing a remote UFS like S3 from a random location, so the response time can be randomly bad.
This adds a new property key for the user to configure if really needs to.
> Add a configuration to set ufs fetch timeout

- core/server/master/src/main/java/alluxio/master/backup/BackupLeaderRole.java
- core/transport/src/main/proto/grpc/meta_master.proto
- core/transport/src/main/proto/proto.lock
- docs/en/operation/Journal.md
- shell/src/main/java/alluxio/cli/fsadmin/command/BackupCommand.java
Introducing a new flag `--bypass-delegation` to backup command for safely by-passing backup delegation.
Passing this flag will revert leading master to taking backups locally.
This new flag provides a fail-safe switch for backup delegation problems.
1- fsadmin backup command is given an additional flag.
> Support bypassing backup delegation via shell switch

- pom.xml
- shell/pom.xml
- shell/src/test/java/alluxio/cli/LogLevelTest.java
Replace PowerMock with Mockito in LogLevelTest.
Part of #15003. 
This PR intentionally limits the scope of change to a single low-impact test, so that we can first add needed dependencies and see if it works, then proceed to replace more PowerMock in other tests.
No.
`powermock` is still used in other child projects. If the `mockito-inline` dependency is enabled for all child projects in root pom, because of https://github.com/powermock/powermock/issues/992, there will be conflicts between powermock and mockito-inline.
The plan is to progressively replace powermock module-by-module, then remove powermock from root pom and enable mockito-inline there.
> Replace PowerMock with Mockito in LogLevelTest

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- tests/src/test/java/alluxio/client/cli/fsadmin/BackupCommandStateLockingIntegrationTest.java
With these changes, the default behavior for backup clients changes as below:
For daily backup:
- There will be an 1 hour long grace-cycle of (2mins of tryLock and 5 mins of sleep)
- After an hour of unsuccessful lock acquisition, daily backup will simply back off.
For shell backup:
- Shell backup will not run grace-cycle. It'll immediately try to acquire exclusive lock.
> Improve state-lock acquisition defaults

- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- The `AlluxioMaster` starts the `RaftJournalSystem` using `RaftJournalSystem#startInternal`. It now holds a `synchronized` lock on `RaftJournalSystem`.
https://github.com/Alluxio/alluxio/blob/dea6a46d67640f54d133744a9b318849fad9ae5c/core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java#L748
- `startInternal` gets to
https://github.com/Alluxio/alluxio/blob/dea6a46d67640f54d133744a9b318849fad9ae5c/core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java#L768
This action fails, for whatever reason, causing `System.exit(int)` --> `Runtime.getRuntime().exit(int)` internally in [Ratis](https://github.com/apache/ratis/blob/96db7f6801738c1c1036f205d925be02e219426c/ratis-common/src/main/java/org/apache/ratis/util/ExitUtils.java#L138). 
- …
> Fix RaftJournalSystem / AlluxioMaster shutdown hook deadlock

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Remove default_permission mount option.
Alluxio fuse needs comprehensive security story. Before that story come out, it does not make sense to enable default_permissions
NA
> Remove fuse default_permission

- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSystem.java
When master process is paused (via sigkill) for a long time, the internal hdfs-client can get confused about the data-node states and throw runtime exception. In an FT cluster, this currently means if a master encounters this during losePrimacy time, it'll never come back up. 
Overall, it's OK to ignore internal streaming errors during `close()`. Because the next time it'll either be a read stream or a new write stream.
> Ignore errors while closing the UFS journal log writer's internal stream

- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/common/src/test/java/alluxio/util/network/NetworkAddressUtilsTest.java
- core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
In some scenarios `cacheBlock` is Unable to correctly determine that the request is a local data source when running the `load command` if `alluxio.network.ip.address.used=true`
Describe the bug
```properties
alluxio.network.ip.address.used=true
```
running `load` command
```bash
bin/allxuio fs load /
```
cacheBlock will always execute the `cacheBlockFromRemoteWorker` branch
---
Reason:
the `mLocalWorkerHostname` always hostname
https://github.com/Alluxio/alluxio/blob/f4ace8f14c1f96a85d1c441fb2acc4f6259c4403/core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java#L76-L84
but  the `request.getSourceHost()` maybe IP address, Because if `alluxio.network.ip.address.used` is true, worker will use IP as workerAddress instead of hostname, So `isSourceLocal ` will always be …
> Fix Load command

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
- integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
Add `MOUNT_POINT` env for fuse daemonset.
```
env:
...
- name: MOUNT_POINT
value: {{ .Values.fuse.mountPath }}
...
```
`MOUNT_POINT` env is required in `entrypoint.sh` for fuse argument:
```
MOUNT_POINT="${MOUNT_POINT:-/mnt/alluxio-fuse}"
...
function mountAlluxioRootFSWithFuseOption {
...
exec integration/fuse/bin/alluxio-fuse mount -n ${fuseOptions} ${MOUNT_POINT} ${ALLUXIO_PATH}
}
```
But `MOUNT_POINT` is not set in fuse daemonset through env. So if the `.Values.fuse.mountPath` is set other than default `/mnt/alluxio-fuse`, the entrypoint will fuse to a wrong mount point.
Fix wrong mount point path if user set their own `Values.fuse.mountPath` in helm chart.
> Fix helm add env for fuse daemonset

- stress/common/src/main/java/alluxio/stress/fuse/FuseIOParameters.java
- stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java
When generating data in fuse stressbench, user can choose the directory names to start from a certain index. 
With this change, user is able to generate all test data in different batches. For example, for the first batch we set `--num-dirs 10` and `--dir-start-index 0`, and for the second batch we set `--num-dirs 10` and `--dir-start-index 10`, we are able to generate 20-dirs test files that is recognizable by reading stress bench.
> Add dir-start-index fuseStressBench

- shell/src/main/java/alluxio/cli/fs/command/AbstractDistributedJobCommand.java
- shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
- shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
- shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
- shell/src/main/java/alluxio/cli/fs/command/job/JobAttempt.java
- tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java
Fix the CLI output of distributedLoad command 
With batch, the output of distributedLoad command output is having wrong file count. And there's no way for user to parse the output and get failures. S
1. change in user-facing CLI
If there's failure in the execution, there would be additional output as the following:
Here are recent failed files:
/a/b/c,
/a/b/d,
Check out logs/user/distributedLoad_`PATH`_failures.csv for full list of failed files 
(PATH here would be the underscore separated path of distributedLoad command, for example if path is /a/b/c, then the failure file would be in logs/user/distributedLoad_a_b_c_failures.csv)
Output file format would be one failure file name per line without header:
/a/b/c
/c/b/a
> Fix DistribtuedLoad CLI Output and dump failed files to local csv

- docs/en/deploy/Running-Alluxio-On-Kubernetes.md
A minor update to add `--` in the `kubectl` command in the doc.
We can still run the command as expected if we don't put the `--` before the command, but we would get a warning `kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead. `
> [DOCFIX] Update k8s doc

- core/server/worker/src/main/java/alluxio/worker/block/meta/DefaultTempBlockMeta.java
fix temp block file name, use %x for session id, it could be a negative number.
Without this change, the following temp file may be generated, it is a little confusing.
/mnt/ramdisk/alluxioworker/.tmp_blocks/-7/-7-17817403392
> Fix temp blockfile name

- .github/workflows/java11_integration_tests.yml
- .github/workflows/java11_integration_tests_webui.yml
- .github/workflows/java11_unit_tests.yml
- dev/github/run_docker.sh
- dev/jenkins/run_docker.sh
Applies the change introduced by https://github.com/Alluxio/alluxio/pull/15150 by building the docker image and updating its references to the newly tagged version
> Bump alluxio-maven img to 0.07

- core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
Remove a log message on UfsStatusCache creation.
https://github.com/Alluxio/alluxio/pull/15065 added a log message in `UfsStatusCache`. At that moment I didn't realize this `UfsStatusCache` is created on every sync request. Having a log message on every sync request will be too noisy and may even hurt performance.
NA
> [SMALLFIX] Remove noisy log in UfsStatusCache

- stress/shell/src/main/java/alluxio/stress/cli/StressJobServiceBench.java
Fix count number in stressbench since we now use file count in distributedLoad command instead of operation count.
we now use file count in distributedLoad command instead of operation count after #https://github.com/Alluxio/alluxio/pull/15106
na
> Fix success count in job service stressbench

- conf/log4j.properties
fixes #15173
Correctly set `FollowerInfo` and `RaftServer$Division` logger to WARN level
Avoid overwhelm leader and follower logs
No
> Disable noisy info log from ratis

- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystemFactory.java
Fix Hdfs supportsPath function bug
Only when the user manually sets PropertyKey `UNDERFS_VERSION`, the value of `UNDERFS_VERSION`  should be compared with `getVersion()`, so we should use `IsSetByUser()`  instead of `isSet()`.
This is similar to [Fix ozone supportspath #14833](https://github.com/Alluxio/alluxio/pull/14833)
3. webui
> Fix UFS version check in hdfs supportsPath

- integration/docker/Dockerfile-dev
We install java11 in dev image but didn't disable jvm dns cache for it. This PR fixes this.
> Disable jvm dns cache in java11 in dockerfile-dev

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
- integration/kubernetes/helm-chart/alluxio/templates/csi/controller-rbac.yaml
- integration/kubernetes/helm-chart/alluxio/templates/csi/driver.yaml
Correct CSI Driver apiVersion and rbac namespace.
* CSI controller rbac is currently only created under the default namespace.
* `storage.k8s.io/v1beta1/CSIDriver` is replaced by `storage.k8s.io/v1/CSIDriver` in kubernetes 18+ version.
> Correct CSI Driver apiVersion and rbac namespace

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
MASTER_JOURNAL_UFS_OPTION is not a template, so moving it to normal PropertyKey.
Also fixing a test that's supposed to test when PropertyKey is null but is no
longer true because "fs.obs.endpoint" is a valid PropertyKey now.
> Remove PropertyKey.Template.MASTER_JOURNAL_UFS_OPTION

- core/common/src/main/java/alluxio/collections/UnmodifiableArrayList.java
- core/common/src/test/java/alluxio/collections/UnmodifiableArrayListTest.java
This PR adds an unmodifiable List interface over an underlying array, so we no longer need to use `Collections.unmodifiableList(Arrays.asList())`
In some JDKs. `Arrays.asList()` is internally `new ArrayList<>(array)`, which incurs a copy. And getting that array back from the List will create another copy with `list.toArray(new T[])`. We add this class to simplify interface conversion and reduce unnecessary copies created just merely for that conversion.
Ideally all existing `Arrays.asList()` and `list.toArray()` can be eliminated with this utility.
NA
> Simplify array-list conversion

- integration/docker/Dockerfile-dev
there's a line in the dockerfiles to disable jvm dns cache by appending to this file within the java installation directory
`/usr/lib/jvm/java-1.8-openjdk/jre/lib/security/java.security`. sometime between the morning of 3/23 and 3/24, something changed such that this path doesn't exist. maybe due to an upgrade in either the java version or the way the OS creates the symlinks, but now the path appends `.0` to the end of `java-1.8` -> `/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/security/java.security`.
note this only affects java 8 on the centos base image; java 11 on the same image and java 8 on the alpine image are not affected
> Fix java installation directory in Dockerfile-dev

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Fix can't remove data in alluxio when under fs is readonly
I think this is a problem. When underfs is readonly, it should not restrict us to remove data from alluxio.
3. webui
> Fix can't remove data in alluxio when under fs is readonly

- core/common/src/main/java/alluxio/conf/PropertyKey.java
parseTimeSize throws NPE for null input. Since it returns primitive
long, it's unclear what null should default to. Thus making parseValue
to handle null uniformly.
> Handle null in PropertyKey.parseValue

- core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
See title.
Fixing issue where null values are considered resolvable, so calling `InstanceConfiguration.get` throws a runtime exception for all unset property keys.
No
> Handle null in InstanceConfiguration.isResolvable

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Init the ArrayList with size to avoid internal resizing.
If no size is given on ArrayList construction, internally I believe ArrayList init with 0 size and on adding the 1st element, it allocates a 10 element array. So when the average block count in Alluxio is significantly less than 10, we can save some space on ArrayList init. And when the average block count in Alluxio is significantly over 10, we half the overall mem allocation of ArrayList by avoiding resizing.
However, the save is mostly mem allocations in the Young Gen and Young GC, so it's not going to be that observable.
NA
> Avoid ArrayList resizing in getFileBlockInfoListInternal

- underfs/gcs/src/main/java/alluxio/underfs/gcs/v2/GCSV2UnderFileSystem.java
For duration type property keys, AlluxioConfiguration.getMs should
be used, rather than getInt.
> Use correct AlluxioConfiguration API to get PropertyKey value

- integration/docker/csi/alluxio/nodeserver.go
Unmount corrupted folder is case csi-nodeserver restarted
Related to issue #14917
This change just mitigate the issue. If node-server restated, it will try to remount the folder. But user job still can not access data during restarting period. 
Just notice these is another solution for this issue https://github.com/Alluxio/alluxio/pull/15165. Believe this solution is more robustness and better for critical job. But this solution need more efforts to be mutual for production workload. Maybe at this stage, we can keep the both.
**Notice: this change requires k8s version above 1.18**
This change not tested yet, we need to kill the nodeserver. After it restarted, check if the mount path is remounted
> Unmount corrupted folder is case nodeserver restarted

- docs/en/deploy/Running-Alluxio-On-Kubernetes.md
- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
- integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
- integration/kubernetes/helm-chart/alluxio/values.yaml
This PR simply adds the `alluxio-config` ConfigMap to the `initContainer` which is launched to format the master journal. Furthermore, it also uses the value set in `.Values.journal.folder` as the mount directory for journal PVs.
Without these changes, the PV intended as the Alluxio master journal would always be mounted under `/journal`. This would be completely ignored if the user changed `.Values.journal.folder` to anything other than `/journal`.
Furthermore, attempting to use the `initContainer` to run the journal format job would cause the journal to be mounted to the [Alluxio default value](https://docs.alluxio.io/os/user/stable/en/reference/Properties-List.html?q=alluxio.master.journal.folder) `alluxio.master.journal.folder=${alluxio.work.dir}/journal`.
For example with the …
> Fix incorrect directory when mounting & formatting master journal volume

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
1. Refactor the rm to avoid one list copy
2. Better init sizing to avoid some copy from ArrayList auto-sizing
3. Setting unused positions to `null` will help GC
See above
NA
If there are `n` inodes to process, the save will be:
1. An `ArrayList` of size `n`, so `8 byte * n`
2. One `Pair<>` per inode, so `32 byte * n`
3. Some `ArrayList` resizing internally by initializing with the final size. So the save is bounded by `8 byte * n`.
The total save is `<(8+32+8) byte * n`. But these are temporary variables so the cost can be less significant than long-held ones. The CPU save could be a more significant benefit, subject to our observation from micro benchmark.
> Save one list copy in rm

- integration/docker/Dockerfile-dev
- integration/docker/README.md
User is able to build dev image running Alluxio with Java11 by using build-arg to specify java version.
Java11 solves a jvm bug in Java8 (See https://github.com/Alluxio/alluxio/issues/15015). If users want to use java11, they have to modify the Dockerfile code then build the image. With this change they can input the java version (for example, 11) to build the image without modifying code.
> Make java version configuable in dev image

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/Inode.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeView.java
- core/server/master/src/main/java/alluxio/master/file/meta/MutableInode.java
- core/server/master/src/main/java/alluxio/master/file/meta/MutableInodeDirectory.java
- core/server/master/src/main/java/alluxio/master/file/meta/MutableInodeFile.java
The `MutableInode` uses a Set to store mediums that the file/dir is pinned in. By default this is an empty HashSet. This PR changes empty sets to `Collection.emptySet()` which is a singleton, in order to avoid creation of empty HashSets.
The main intention is to reduce memory waste on empty collections. 
Before: 
54.5MB total
342B in a `MutableInodeFile.mMediumTypes` where we have a pin medium specified
After
46.6MB total
82B in a `MutableInodeFile.mMediumTypes` where we have a pin medium specified
When there's no value, the save is one empty `HashSet` per MutableInode, < 100B.
When there's value, the save is 342B -> 82B per MutableInode.
NA
> Avoid creating new empty sets in MutableInode

- core/common/src/main/java/alluxio/cli/ValidationToolRegistry.java
- core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/extensions/ExtensionFactoryRegistry.java
- core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
- core/common/src/test/java/alluxio/underfs/UnderFileSystemConfigurationTest.java
- core/server/master/src/main/java/alluxio/web/MasterWebServer.java
- core/server/master/src/test/java/alluxio/master/journal/ufs/UfsJournalConfTest.java
- core/server/worker/src/main/java/alluxio/web/WorkerWebServer.java
- integration/tools/validation/src/main/java/alluxio/cli/ClusterConfConsistencyValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/SshValidationTask.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Allow setting property key with string values but log a warning on
invalid values and let people know that this will be disallowed later.
Some external systems might directly use this internal API to set
Alluxio properties. Give people some warning and time to fix the issues
before directly breaking them.
It removes a potentially user facing change.
> Allow string values when setting AlluxioConfiguration

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/worker/block/io/TimeBoundBlockReader.java
- core/common/src/main/java/alluxio/worker/block/io/TimeBoundBlockWriter.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
One of the fix for https://github.com/Alluxio/alluxio/issues/15019
When read/write from/to local block, timeout when taking too long.
Sometimes read/write to disk will hang and cannot be recovered.
When read/write takes too long, a timeout exception is thrown
> Add timeout logic to local block reading/writing

- docs/cn/operation/Security.md
The Chinese document describes that the master side needs to be modified to configure impersonation, but it does not specify the worker.
Referring to the original document may cause incomplete configuration.
no
> [DOCFIX] Fix ambiguous description for impersonation in CN doc

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
Making `RaftServerConfigKeys.Log.setPurgeUptoSnapshotIndex` to `true` by default. This enables each master in the quorum to look only at the local snapshots it possesses in order to determine which log files to prune. 
Before, masters would only prune based on the quorum consensus of committed log index. 
Community members have noticed that Ratis logs grow unbounded in the presence of a slow master, which can crash certain masters when the UFS runs out of space in extreme cases. 
Adds a `PropertyKey` to enable or disable this new feature.
> Make log compaction local in embedded journal

- core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
- tests/src/test/java/alluxio/client/cli/fs/GetConfTest.java
for `bin/alluxio getConf` backward compatibility, store duration and data size
properties as string for now.
Backward compatibility requirement for 2.8
> Store ms byte as string

- docs/en/operation/StressBench.md
- stress/common/src/main/java/alluxio/stress/common/FileSystemParameters.java
- stress/common/src/main/java/alluxio/stress/master/MasterBenchBaseParameters.java
- stress/common/src/main/java/alluxio/stress/master/MasterBenchParameters.java
- stress/shell/src/main/java/alluxio/stress/cli/MaxFileBench.java
- stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java
This PR introduces a new stressbench test called MaxFileBench.
MaxFileBench creates 0-byte files until the master becomes unresponsive. To ensure we are pushing the master to its limits, we pause between a failure and another attempt at creating a file. This pause doubles in length on successive failure, and gets reset when a new success occurs. If the pause gets too large the test ends. This ensures that the master has actually become unavailable rather than flaky.
> Create MaxFile stressbench

- shell/src/main/java/alluxio/cli/bundler/command/AbstractCollectInfoCommand.java
change
LOG.debug("Command %s works in %s", this.getCommandName(), workingDirPath);
to
LOG.debug("Command {} works in {}", this.getCommandName(), workingDirPath);
since this is logging format, so it support {} grammer.
2. If you fix a bug, describe the bug.  3. 
4. webui
> [SMALLFIX]Fix logging message AbstractCollectInfoCommand.java

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
In our tests, a performance issue of `getFileInfoInternal` was found.
Optimize getFileInfoInternal, the getFileInfoInternal will call getBlockInfoList mutli times
`getFileInfoInternal` will call `getBlockInfoList` 3 times, `getBlockInfoList` is an expensive operation because it reads data from rockdb, which affects the performance of `getFileInfoInternal`.
This PR combines 3 times of `getBlockInfoList` calls into 1 time
After optimization, `getFileInfoInternal` will only be called once `getBlockInfoList`
Using vdbench (128k, read) tests, we found that this doubled the read performance of small files
No
> Optimize getFileInfoInternal

- core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java
- core/server/master/src/main/java/alluxio/master/file/contexts/CreateDirectoryContext.java
- core/server/master/src/main/java/alluxio/master/file/contexts/CreateFileContext.java
- core/server/master/src/main/java/alluxio/master/file/contexts/DeleteContext.java
- core/server/master/src/main/java/alluxio/master/file/contexts/RenameContext.java
For file-system option defaults, gives support for skipping operation-ID generation by argument.
Then makes use of it from internal operations to avoid generating UUIDs.
Internal operations are not retried against the new master. Hence, generating an operation-Id doesn't make sense.
Fixes https://github.com/Alluxio/alluxio/issues/15261
> Stop generating operationID (UUID) for internal operations

- core/server/common/src/main/java/alluxio/metrics/sink/MetricsServlet.java
- tests/src/test/java/alluxio/client/rest/AlluxioMasterRestApiTest.java
- tests/src/test/java/alluxio/client/rest/AlluxioWorkerRestApiTest.java
- tests/src/test/java/alluxio/client/rest/JobMasterClientRestApiTest.java
- tests/src/test/java/alluxio/client/rest/JobMasterRestApiTest.java
- tests/src/test/java/alluxio/client/rest/RestApiTest.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
- tests/src/test/java/alluxio/client/rest/TestCase.java
- tests/src/test/java/alluxio/client/rest/TestCaseOptions.java
- tests/src/test/java/alluxio/web/WebServerIntegrationTest.java
This PR refactors the classes related to `RestApiTest` to remove confusing code such as redundant methods or general Java anti-patterns.
Improving development clarity & ease-of-use.
No user-facing changes.
> Refactor RestApiTest and related classes for clarity

- core/client/fs/src/main/java/alluxio/client/file/cache/filter/CacheFilter.java
- core/client/fs/src/main/java/alluxio/client/file/cache/filter/DefaultCacheFilter.java
- core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
Add a cache filter to local cache. took over from the inactive PR https://github.com/Alluxio/alluxio/pull/13844
This feature might help to prevent the cache flushing on large tables.
add two new property keys to config the cache filter
> Add a default implementation of cache filter to local cache

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
Init list/map with size when we merge journal entries
Avoid List/Map resizing as much as possible
NA
> [SMALLFIX] Avoid list/map resizing in journal entry merging

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Alluxio deprecated property key doesn't work well with new property key with alias.
Remove the deprecated property key as a workaround and will fix the general problem in a later PR.
When setting the value for deprecated property key,
the new property key with the alias name as the deprecated property key name does not take the value.
Supporting alluxio.worker.fuse.mount.point, alluxio.worker.fuse.mount.alluxio.path, and alluxio.worker.fuse.mount.options.
> Fix FUSE deprecated property key

- core/server/common/src/main/java/alluxio/master/journal/raft/SnapshotReplicationManager.java
- core/server/common/src/main/java/alluxio/master/journal/raft/SnapshotUploader.java
- core/server/common/src/test/java/alluxio/master/journal/raft/SnapshotReplicationManagerTest.java
- minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTestFaultTolerance.java
Currently, the `JournalServiceClient` used in `SnapshotReplicationManager` is closed using try-resource blocks. This causes the async calls within said blocks to fail sometimes as the client is closed when the call is launched.
This PR ensures that the clients are closed asynchronously after the call is finished using `whenComplete` blocks. 
A test accompanies this to ensure proper snapshot propagation.
> Close JournalServiceClient asynchronously to account for async calls

- shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
Add the missing options to distributed load cli.
Options like `--excluded-hosts` etc., are missing in `alluxio fs distributedLoad` command. The functionalities controlled by the options are introduced in #13506, but not accessible from the command line interface. Attempting to run the command with this option results in an unrecognized option error:
```console
$ bin/alluxio fs distributedLoad --excluded-hosts host1,host2 /tmp
Failed to parse args for distributedLoad: Unrecognized option: --excluded-hosts
Usage: distributedLoad [--replication <num>] [--active-jobs <num>] [--batch-size <num>] [--index] [--hosts <host1>,<host2>,...,<hostN>] [--host-file <hostFilePath>] [--excluded-hosts <host1>,<host2>,...,<hostN>] [--excluded-host-file <hostFilePath>] [--locality …
```
> Add missing options in DistributedLoad command

- core/server/common/src/main/java/alluxio/master/journal/raft/SnapshotReplicationManager.java
Client is being close inside `if` block incorrectly. Moving the `close` statement outside the `if` block.
> Close client outside if statement

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/worker/src/main/java/alluxio/worker/block/FuseManager.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/test/java/alluxio/fuse/AlluxioJniFuseFileSystemTest.java
- tests/src/test/java/alluxio/client/fuse/AbstractFuseIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/JNIFuseIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/JNRFuseIntegrationTest.java
- tests/src/test/java/alluxio/server/worker/WorkerFuseIntegrationTest.java
Fixes #15295
Cache the capacity info for Fuse.statfs on Fuse side to reduce the master RPC calls.
Improve the Fuse.statfs() to avoid create client context and copyProperties for each call.
NA
> Improve Fuse.statfs to avoid copyProperties and cache on client side

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Make the template setting the type with the default property creator instead of String type.
The current template doesn't respect the new property type.
N/A
> Fix property key template type

- core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java
- core/client/fs/src/main/java/alluxio/client/file/MetadataCachingBaseFileSystem.java
- core/client/fs/src/test/java/alluxio/client/file/MetadataCachingBaseFileSystemTest.java
- integration/fuse/src/main/java/alluxio/cli/command/metadatacache/DropCommand.java
Fixes the fuse shell drop metadata cache
Supports drop metadata cache of a directory with all its parents and all its children
Improve the Fuse shell
> Fix fuse shell drop metadata cache

- integration/docker/Dockerfile
- integration/docker/Dockerfile-dev
The owner of files in `opt/alluxio` is the owner of the tarball. If the user builds the tarball locally as non-alluxio user, the user alluxio (uid 1000) inside the docker container may not have the permission to write into `alluxio-env.sh`, which is a required step in `entrypoint.sh`, and thus the cluster is not able to start.
solves #15309
> Fix alluxio tarball owner in docker

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
The force umount doesn't work in k8s, because after the force kill process, the pod immediately terminated without cleaning up the mount point.
> Revert k8s fuse force umount

- core/common/src/main/java/alluxio/AlluxioURI.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockReaderTest.java
Reduce the overhead of metric tracking in UnderFileSystemBlockReader by not creating the metric name for every reader created. Also some coding style clean up in UnderFileSystemBlockStore and UnderFileSystemBlockReader.
> Reduce metric tracking overhead in UnderFileSystemBlockReader

- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemCommonOperations.java
This ensures when using an object store as the UFS, the root directory will be listed when doing a sync operation.
The check for the root directory was on the wrong line, meaning that the function would always return null for the root directory.
No
> Fix root object store UFS directory not being listed

- job/common/src/main/java/alluxio/job/util/SerializationUtils.java
- stress/shell/src/main/java/alluxio/stress/cli/Benchmark.java
#14819 introduced a header to the JSON output of Stressbench, which break backwards compatibility. This PR removes the header to restore backwards compatibility.
@jja725 @yabola please take a look.
> Remove backcompat breaking stressbench header

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
The metrics INODE_SYNC_STREAM_ACTIVE_PATHS_TOTAL, INODE_SYNC_STREAM_PENDING_PATHS_TOTAL keep track of active elements in queues during sync operations. They were not being decremented after a sync failed or was cancelled leading to them having incorrect values. This PR decrements them in this case.
No
> Fix metric not being decremented in case of cancelled sync operation

- core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java
- core/server/master/src/test/java/alluxio/master/file/meta/AsyncUfsAbsentPathCacheTest.java
Fix the absent cache stats which are always zero.
From the doc on `Cache::stats()`:
> Returns a current **snapshot** of this cache's cumulative statistics, or a set of default values if the cache is not recording statistics. All statistics begin at zero and never decrease over the lifetime of the cache.
**Warning**: this cache may not be recording statistical data. For example, a cache created using CacheBuilder only does so if the CacheBuilder.recordStats method was called. If statistics are not being recorded, a CacheStats instance with zero for all values is returned.
This fix
1. enables stats collection on the cache
2. retrieves a new snapshot every time the gauge is polled, instead of the stale value captured by the lambda.
Yes, the metrics are fixed.
> Fix absent cache stats are always zero

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Slightly improve the rm failure msg
```
alluxio.exception.status.FailedPreconditionException: Failed to delete 2 paths:  from the under file system/nested/test (Permission denied: user=userA, access=-w-, path=/nested/test/file: failed at file, inode owner=test, inode group=, inode mode=rwx------), /nested/test (Directory not empty)
alluxio.exception.status.FailedPreconditionException: Failed to delete 2 paths from the under file system: /nested/test (Permission denied: user=userA, access=-w-, path=/nested/test/file: failed at file, inode owner=test, inode group=, inode mode=rwx------), /nested/test (Directory not empty)
```
NA
> [SMALLFIX] Improve rm failure msg

- job/server/src/main/java/alluxio/worker/job/RetryHandlingJobMasterClient.java
Remove one full collection log
Shorter log and avoid printing the whole collection. The current log is multiple lines like below. I don't think we need to see all the contents.
```
2022-04-07 04:59:47,890 WARN  JobMasterClient - Heartbeat(jobWorkerHealth=JobWorkerHealth{workerId=1649306176300, loadAverage=[1.82, 1.93, 1.68], lastUpdated=1649307369406, hostname=OperationHdfsrm-worker-0, taskPoolSize=10, numActiveTasks=0},taskInfoList=[id: 0
errorMessage: ""
status: COMPLETED
lastUpdated: 1649307368755
type: TASK
parentId: 1649306390187
workerHost: "OperationHdfsrm-worker-0"
description: ""
errorType: ""
, id: 0
errorMessage: ""
status: COMPLETED
lastUpdated: 1649307368799
type: TASK
parentId: 1649306390286
workerHost: "OperationHdfsrm-worker-0"
description: ""
errorType: ""
, id: 0 …
```
> [SMALLFIX] Improve log in job worker heartbeat

- bin/alluxio-start.sh
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalConfiguration.java
Removing a `PropertyKey` mentioned in the doc that is no longer in use (the doc will update dynamically from the removal of this `PropertyKey`.
Also made `bin/alluxio-start.sh secondary_master` always async, as there is no monitor process available to launch it synchronously. Currently try to launch it synchronously produces an error message.
> Validate `Journal.md`

- integration/docker/csi/alluxio/nodeserver.go
- integration/docker/entrypoint.sh
The bash script entrypoint.sh  can not use FUSE_ALLUXIO_PATH and MOUNT_POINT env.
Alluxio csi can not mount in fuse pod. 
no
> Replace invalid env with args in nodeserver

- core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
- core/server/master/src/test/java/alluxio/underfs/UfsStatusCacheTest.java
Don't increment the counter if the path is already in cache, don't decrease it if it isn't.
> Fix metric for ufs status cache can be negative

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
Due to https://github.com/Alluxio/alluxio/issues/14243#issuecomment-941441855, Netty is not able to to get the correct number of processors in certain container environments. Thus set a higher default value. The default value is debatable.
> Add fall back for availableProcessor()

- docs/en/overview/Getting-Started.md
update the list of integrations in the quick start guide. i am proposing to trim these lists to the ones that Alluxio has a stable integration with as opposed to an integration that is not thoroughly explored. also note that if the list is supposed to be thorough and comprehensive, then it will become quickly out of date as more integrations are added and these seem to be less important.
> [DOCFIX] Update quickstart doc

- docs/_data/table/en/env_vars.yml
- docs/en/operation/Basic-Logging.md
- docs/en/operation/Configuration.md
update configuration doc with new env vars
also check for references to `alluxio.logs.dir` to ensure no one tries to set it as a property key, since it can only be set as an env var as discussed in https://github.com/Alluxio/alluxio/pull/14980
> [DOCFIX] Update configuration doc

- core/client/fs/src/main/java/alluxio/client/block/BlockMasterClientPool.java
- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClientPool.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClientPool.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
- core/common/src/test/java/alluxio/resource/DynamicResourcePoolTest.java
- table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/DefaultHiveClientPool.java
Fixes #14766
This change replaces two client side gauges with counters.
On the bottom right corner, it can be seen that the references of EpollGroup are from the metric Gauge lambda in `DynamicResourcePool`. Using `() -> size()` in lambda will implicitly leak the `this` reference or the `mResources` reference used in `size()`(Not sure if JVM just inlined that `size()`).
In my environment, the HMS can spend 40% heap on metrics due to this gauge.
In one user environment, the HMS can spend 50G on such metrics.
The metric to monitor will change
> Fix client side leak caused by Gauge

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/master/pom.xml
- core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java
- core/server/master/src/test/java/alluxio/master/file/meta/AsyncUfsAbsentPathCacheTest.java
Remove duplicate metric `Master.UfsAbsentPathCacheSize`. 
Rename `UfsAbsentPathCacheQueueSize` to `AbsentPathCacheQueueSize` to be consistent with already existing metric name.
Also make other similar metrics cached.
> Remove duplicate metric for absent cache

- stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
Fix an integer overflow in client IO bench that prevents the correct execution of the `ReadFully` operation. To reproduce, test with a file size greater than or equal to 2GB.
Also make the error reporting more useful for some exception types which have no messages. In this case, reading with a negative length throws a`IndexOutOfBoundsException`.
```
java.lang.IndexOutOfBoundsException
at java.io.DataInputStream.readFully(DataInputStream.java:192)
at alluxio.stress.cli.client.StressClientIOBench$AlluxioHDFSBenchThread.applyOperation(StressClientIOBench.java:499)
at alluxio.stress.cli.client.StressClientIOBench$BenchThread.runInternal(StressClientIOBench.java:425)
```
This results in a `null` error in the final JSON output.
> Fix client io bench integer overflow

- docs/en/operation/User-CLI.md
This adds the recent perf evaluation results of `rm/unmount` command and sync to the doc.
This adds how to make a good memory estimation, and the recommended command to perform the operation.
Users should look at the updated doc to use the memory most efficiently.
> [DOCFIX] Add the memory overhead of rm/unmount/sync in the doc

- core/server/common/src/main/java/alluxio/web/JmxServlet.java
- core/server/common/src/main/java/alluxio/web/WebServer.java
This servlet will be accessed by query `http://<address>:<port>/metrics/jmx`, leverage this servlet, alluxio can be monitored by some metrics monitor system can get jmx mxbean metrics. 
If you want to sink alluxio metric to mxbean, you should config the `metrics.properties` like the following
```properties
sink.jmx.class=alluxio.metrics.sink.JmxSink
```
AI on Alluxio
Some hadoop ecosystem monitor system can monitor alluxio without any effort.
Add a new http page `/metrics/jmx`
> Add jmx servlet

- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/LocalBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
- core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
Remove getBlockMeta from BlockWorker and LocalBlockStore.
There are getBlockMeta and getVolatileBlockMeta. The difference is
getBlockMeta requires a sessionId and blockId, and validates the lock.
This is more like a debugging feature. Since the caller has already acquired
the lock, calling getVolatileBlockMeta is always safe in this situation, and
avoids the overhead of validating the lock.
> Remove getBlockMeta from BlockWorker and LocalBlockStore

- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/LocalBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
The moveBlock and removeBlock API with location are only used in test. The
actual API always uses BlockStoreLocation.anyTier() as location. So removing
the APIs and the usage in tests.
> Remove unused API in LocalBlockStore

- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockLockManager.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/LocalBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockLockManagerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
- core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockReaderTest.java
- core/server/worker/src/test/java/alluxio/worker/grpc/BlockReadHandlerTest.java
1) APIs like accessBlock lockBlock, unlockBlock in BlockWorker are just
wrappers on the corresponding LocalBlockStore APIs that are specific to
LocalBlockStore. Using the LocalBlockStore APIs directly and removing the
wrapper APIs in BlockWorker.
2) Rename LocalBlockStore.lockBlock to pinBlock. The API is supposed to
be indicating future block read access and is intended to avoid eviction.
Currently the underlying implementation in TieredBlockStore is still using
locking and the API still returns lockId. But changing the API to indicate
that such strong guarantee is not necessary for all implementations. In the
future this function should just return void.
3) Rename LocalBlockStore.unlockBlock to unpinBlock and remove Exceptions not thrown.
4) Remove BlockWorker.INVALID_LOCK_ID. Using …
> Improve BlockWorker and LocalBlockStore APIs

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
- integration/kubernetes/helm-chart/alluxio/templates/csi/pvc-static.yaml
If using helm chart to deploy CSI directly (not using `kubectl`), the PVCs for static and dynamic provisioning have the same name and cause the deploy to fail.
Although we don't recommend user to use helm chart deploy CSI directly, if anyone gives it a try, the error returned by helm would be `Error: persistentvolumeclaims "alluxio-pvc" already exists`, which is not informative at all.
> Rename static pvc in CSI

- stress/shell/src/main/java/alluxio/stress/cli/StressJobServiceBench.java
Enable files larger than 2GB for distributed load stress bench. 
Using `int` for file size would cause an integer overflow when the file is larger than 2GB.
Cross reference: #15442
> Enable files larger than 2GB for distributed load bench

- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
Allows a `Plugin` process type to be launched w/ an associated metric registry name.
ref https://github.com/Alluxio/alluxio/pull/15314
See above.
No
> Add MetricsSystem case for Plugin type

- core/common/src/main/java/alluxio/grpc/GrpcChannel.java
- core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
- core/common/src/main/java/alluxio/grpc/GrpcChannelKey.java
- core/common/src/main/java/alluxio/security/authentication/AuthenticatedChannelClientDriver.java
- core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java
The `IdentityField` annotation is unnecessary and makes `hashCode` and `equals` expensive.
The `toStringShort` method is longer than `toString`, which also seems to be unnecessary.
> Remove unnecessary code in GrpcChannelKey

- integration/docker/Dockerfile-dev
Solely install `fuse3-libs` can't start alluxio fuse process successfully. It would return error something like "fusermount3 not found"
> Fix fuse3 packages in dev image

- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/common/src/main/java/alluxio/worker/block/meta/StorageDir.java
- core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataEvictorView.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManager.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/LocalBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/evictor/AbstractEvictor.java
- core/server/worker/src/main/java/alluxio/worker/block/management/tier/AlignTask.java
- core/server/worker/src/main/java/alluxio/worker/block/management/tier/PromoteTask.java
- core/server/worker/src/main/java/alluxio/worker/block/management/tier/SwapRestoreTask.java
- core/server/worker/src/main/java/alluxio/worker/block/meta/DefaultStorageDir.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/DelegationWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockMetadataManagerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockMetadataViewTest.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
- core/server/worker/src/test/java/alluxio/worker/block/annotator/AbstractBlockAnnotatorTest.java
- core/server/worker/src/test/java/alluxio/worker/block/meta/DefaultStorageDirTest.java
- core/server/worker/src/test/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandlerTest.java
Return Optional instead of throwing BlockDoesNotExistException.
Using exception to handle special case is expensive, using Optional.empty()
instead.
Also remove the block meta related APIs in BlockWorker.
> Change LocalBlockStore.getVolatileBlockMeta to return Optional

- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
The moveBlock APIs are very light wrappers on top of the API for LocalBlockStore. They don't really need to exist.
> Remove BlockWorker.moveBlock APIs

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
Add a reading buffer to local cache for tiny read
1. we're seeing performance degradation when presto keep reading tiny pieces (1~10 bytes) from local cache on some encrypted parquet format.
no
> Add a reading buffer to local cache for tiny read

- dev/jenkins/Dockerfile-jdk11
- dev/jenkins/Dockerfile-jdk8
The jenkins image didn't install libfuse3 packages, which means in github actions the Fuse integration tests never ran with libfuse3. 
Tested on https://github.com/ssz1997/alluxio/pull/2 and the Fuse integration tests passed: https://github.com/ssz1997/alluxio/runs/6293974135?check_suite_focus=true
> Install libfuse3 in jenkins images

- dev/scripts/watch-metrics.sh
I fixed the bug that the previous `watch-metrics.sh`, when running, cannot correctly recognize the `metrics_dir` parameter; I also add two command checks, checking whether `nslookup` and `jq` commands are existed before running the actual command.
1. Bug: `watch-metrics.sh` cannot recognize the `-d` parameter and will popup `ERROR: Unknown argument`
2. The error message is misleading in some circumstance: If the `nslookup` command is not installed, the error message will be `ERROR: Unknown host` even if the provided hostname can be recognized.
No.
> Fix parameter loading issues and add more checks in the watch-metrics.sh

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockStore.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
- docs/en/operation/Metastore.md
Fix #15466 
Exposing all RocksDB metrics listed [here](https://github.com/facebook/rocksdb/blob/2b5c29f9f3a5c622031368bf3bf4566f5c590ce5/include/rocksdb/db.h#L1104-L1136) except for `rocksdb.estimate-oldest-key-time` as preliminary testing showed it was not working. 
Metics names follow the convention `num-immutable-mem-table` --> `Master.Rocks<Block | Inode>ImmutableMemTable` (depending on whether one wants to study the Inode RocksDB store or the Block RocksDB store).
> Expose RockDB metrics as Alluxio metrics

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/InstrumentedExecutorService.java
- core/common/src/main/java/alluxio/metrics/MaxReservoir.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
- core/transport/src/main/proto/grpc/common.proto
- core/transport/src/main/proto/proto.lock
This allows better monitoring of thread pool executors using the InstrumentedThreadPool executor from https://github.com/dropwizard/metrics. It adds instrumentation for the thread pool executors in DefaultFileSystemMaster for the meta data sync executors.
This helps monitor the queues and executors in case of high load and memory usage.
New metrics for the thread pool executors in DefaultFileSystemMaster for the meta data sync executors, by default this is disabled by property key {alluxio.master.metadata.sync.instrument.executor}. A warning log is printed every {alluxio.metrics.executor.task.warn.frequency} seconds with the number of active tasks (running or queued) if the number is above {alluxio.metrics.executor.task.warn.size}.
> Add InstrumentedExecutorService for monitoring executor services

- core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingTransport.java
- core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncer.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Collection.toArray() is widely used throughout the project, but inappropriate use can waste memory. Find out where is wrong and fix it
Collection.toArray() does a copy. Using Array can reduce one copy to save memory and time if we know very well how many elements there are. 
NA
> Reduce the use of Collection.toArray() in project

- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
Implement get page ids by the given file id
The local cache callers are able to get a list of pages for a particular file, and then they can delete the pages for GDPR or invalidation purpose
Add a new api for local cache
> Implement get page ids by the given file id

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
Use unpooled wrapped buffer in remote block read
Using the unpooled buffer might be more efficient for mmap buffer and heap buffer
see the discussion https://github.com/Alluxio/alluxio/pull/14644 
We need more data to support this, so involved a property key to switch between pooled and unpooled buffer
Add a property key to switch between pooled or unpooled buffer
> Use unpooled wrapped buffer in remote block read

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
Retry the eviction when the deletion of the victim page file failed (it has been deleted by others)
As FB team shared with us, we might see a spike of page put failures if we delete all the page files on the disk.  I think this one might also occur when there is a race on delete the same page file.   So add a retry might help the put operation get through in case the victim file has been deleted by some one else.
No
> Retry the eviction on delete page file failures

- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
Fix the deadlock caused by remove block.  There might be a race in the remove block method, i.e the block meta could be removed by other thread.  No matter the block meta is present or not, we have to release the lock acquired in the remove block method.
fix the deadlock issue found by the microbench
no
> Fix the deadlock caused by remove block

- core/server/worker/src/main/java/alluxio/worker/page/PagedLocalBlockStore.java
Enable heartbeat actions for paged local block store. Make sure heartbeats won't cause exceptions because the new block store is not completed yet.
> Add paged local block store heartbeat actions

- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
Added `toString` method to RaftJournalSystem
RaftJournalSystem does not have a `toString` method, which can result in insufficient information for debugging when RaftJournalSystem exceptions are thrown.
```java
AlluxioMasterProcess(JournalSystem journalSystem) {
//....
if (!mJournalSystem.isFormatted()) {
throw new RuntimeException(
String.format("Journal %s has not been formatted!", mJournalSystem));
}
//...
```
This is a raft journal log
```
bin/launch-process master -c
2022-04-27 09:21:54,626 ERROR AlluxioMaster - Fatal error: Failed to create master process
java.lang.RuntimeException: java.lang.RuntimeException: Journal alluxio.master.journal.raft.RaftJournalSystem@5c7fa833 has not been formatted!
at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:125)
at …
```
> Add RaftJournalSystem toString

- dev/intellij/runConfigurations/AlluxioMaster.xml
`AlluxioMaster.xml` is the only IntelliJ config file that is lacking the `-Xbootclasspath/a:$PROJECT_DIR$/conf` JVM parameter. Adding it ensures that the master logs to the console when launched.
> [SMALLFIX] Add JVM argument to enable console logging on master

- core/server/worker/src/main/java/alluxio/worker/block/meta/DefaultStorageTier.java
- core/server/worker/src/test/java/alluxio/worker/block/meta/DefaultStorageTierTest.java
Check if the directory to remove actually belong to the tier.
> Check if dir belongs to tier before removing it

- shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
Add worker to output information while cache failed.
From the following output, I cannot identify the failed worker.
```
Failed to complete cache request for block 2484118487040 of file /test: io.grpc.StatusRuntimeException: UNKNOWN: java.io.IOException: Failed to read from UFS, sessionId=-8, blockId=2484118487040, offset=0, positionShort=false, options=ufs_path: "hdfs://ns1/test"
offset_in_file: 0
block_size: 161266153
maxUfsReadConcurrency: 2147483647
mountId: 1381858014512144475
no_cache: false
: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: java.net.UnknownHostException: ns1
/ns1/test loaded
```
No
> Print worker for loadCommand while cache failed

- build/checkstyle/alluxio_checks.xml
- core/client/fs/src/main/java/alluxio/client/block/policy/LocalFirstAvoidEvictionPolicy.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStore.java
- core/server/master/src/test/java/alluxio/master/block/SignalBlockMaster.java
- core/server/master/src/test/java/alluxio/master/file/meta/TtlBucketTest.java
- core/server/master/src/test/java/alluxio/master/journal/ufs/UfsJournalLogWriterTest.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketResult.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
- integration/fuse/src/main/java/alluxio/cli/command/metadatacache/DropAllCommand.java
- integration/fuse/src/main/java/alluxio/cli/command/metadatacache/DropCommand.java
- integration/fuse/src/main/java/alluxio/cli/command/metadatacache/SizeCommand.java
- job/server/src/test/java/alluxio/master/job/JobMasterTest.java
- shell/src/main/java/alluxio/cli/fsadmin/report/UfsCommand.java
- tests/src/test/java/alluxio/client/fs/BlockWorkerRegisterStreamIntegrationTest.java
- tests/src/test/java/alluxio/server/ft/journal/TableMasterJournalIntegrationTest.java
- underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemFactoryTest.java
Fix local variables whose names start with a "m", easy to be confused as a class field.
Update checkstyle rules to enforce this.
> Fix local variable names starting with "m"

- integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl
- integration/kubernetes/helm-chart/alluxio/templates/master/service.yaml
- integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
- integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml
- integration/kubernetes/helm-chart/alluxio/values.yaml
This PRs introduces support for extra containers, volume mounts, and volumes for master/worker pods. This flexibility allows for extra customizations without having to directly change the Alluxio helm charts. The structure of the new fields are similarly structured to their respective k8s objects. See example below to get an idea of how the structure looks like.
See above.
See [change](https://github.com/tieujason330/alluxio/blob/c5e1fbf70ab25bbd1b7b67e91788c79b78ccdb26/integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl) for detailed explanations on each new parameter
Extra Helm template values:
- master
- shareProcessNamespace: boolean
- extraContainers: list
- extraVolumeMounts: list
- extraVolumes: list
- extraServicePorts: list
- worker
- shareProcessNamespace: boolean
- …
> Support extra resources for master/worker pods

- core/server/worker/src/main/java/alluxio/worker/block/AbstractBlockStoreEventListener.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockHeartbeatReporter.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMetricsReporter.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockStoreEventListener.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/annotator/DefaultBlockIterator.java
- core/server/worker/src/main/java/alluxio/worker/block/evictor/LRUEvictor.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedLocalBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockHeartbeatReporterTest.java
- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTestUtils.java
- core/server/worker/src/test/java/alluxio/worker/block/annotator/AbstractBlockAnnotatorTest.java
- core/server/worker/src/test/java/alluxio/worker/block/annotator/EmulatingBlockIteratorTest.java
Remove session IDs from the `BlockStoreEventListener` interface as the session ID is unused.
> Remove session ID from block store event listener

- core/common/src/main/java/alluxio/util/io/PathUtils.java
- core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
According to the implementation of `getMountPoint`, it receives an alluxio uri as the parameter, gets the `path` from this uri by calling `uri.getPath()`, iterates the whole mount table's key-value pairs to find the key that is the nearest parent directory of `path`, which in other words is the longest prefix of `path`.
To make sure that the longest prefix can be recorded in `lastMount`, the condition is as follow:
```java
// ...
for (Map.Entry<String, MountInfo> entry : mState.getMountTable().entrySet()) {
String mount = entry.getKey();
if (!mount.equals(ROOT) && PathUtils.hasPrefix(path, mount)
&& PathUtils.hasPrefix(mount, lastMount)) {
lastMount = mount;
}
}
return lastMount;
```
`mount` is the current looped entry's key. The first two && condition check if the `mount` is the prefix …
> Optimize the checks of the loop in getMountPoint

- job/client/src/main/java/alluxio/client/job/JobContext.java
- job/client/src/main/java/alluxio/client/job/JobGrpcClientUtils.java
- job/common/src/main/java/alluxio/job/util/TimeSeries.java
- job/server/src/main/java/alluxio/job/plan/PlanDefinitionRegistry.java
- job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java
- job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java
- job/server/src/main/java/alluxio/job/plan/transform/format/csv/CsvReader.java
- job/server/src/main/java/alluxio/job/plan/transform/format/csv/CsvRow.java
- job/server/src/main/java/alluxio/job/plan/transform/format/parquet/ParquetReader.java
- job/server/src/main/java/alluxio/master/job/JobMaster.java
- job/server/src/main/java/alluxio/master/job/plan/PlanCoordinator.java
change the Java doc for private functions into comment if they are still useful. removed if information is trivil. 
We shouldn't write javadoc for private methods. End users don't have access to private fields or methods so there really isn't a point in providing javadoc for them. Private fields and methods are only meant for the developer. So leaving them as comments if seem useful.
No
> Remove Java doc for private functions

- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Fixes the bug that introduced by https://github.com/LuQQiu/alluxio/commit/36a4d5c93c2756bcaae5c76cc295a5442d6abad8
avoid creating two exactly same S3 clients
> Fix S3 UFS threads bug

- pom.xml
fix https://x-stream.github.io/CVE-2021-43859.html
see https://github.com/x-stream/xstream/security/advisories/GHSA-rmr5-cpv2-vgjf
The vulnerability may allow a remote attacker to allocate 100% CPU time on the target system depending on CPU type or parallel execution of such a payload resulting in a denial of service only by manipulating the processed input stream.
no
> Fix the vulnerability caused by xstream

- core/common/src/main/java/alluxio/metrics/MaxReservoir.java
The max reservoir metric is now initialized to 0.
Previously the max reservoir metric was initialized to Long.MIN_VALUE which is a negative value, but the max reservoir is used to track the max size of something that should be initialized to 0.
Any metric that uses the max reservoir (currently the thread pool executor monitoring the metadata queues) will now be initialized to 0.
> Fix max reservoir metric initialization

- core/server/master/src/main/java/alluxio/master/backup/BackupLeaderRole.java
- core/transport/src/main/proto/grpc/meta_master.proto
- core/transport/src/main/proto/proto.lock
- docs/en/operation/Journal.md
- shell/src/main/java/alluxio/cli/fsadmin/command/BackupCommand.java
Introducing a new flag `--bypass-delegation` to backup command for safely by-passing backup delegation.
Passing this flag will revert leading master to taking backups locally.
This new flag provides a fail-safe switch for backup delegation problems.
1- fsadmin backup command is given an additional flag.
[This is manually generated PR to cherry-pick committed PR Alluxio/alluxio#15110 into target branch branch-2.7]
> Port changes of [#15110] to branch-2.6

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/fuse/auth/AuthPolicy.java
- integration/fuse/src/main/java/alluxio/fuse/auth/CustomAuthPolicy.java
- integration/fuse/src/main/java/alluxio/fuse/auth/NoopAuthPolicy.java
- integration/fuse/src/main/java/alluxio/fuse/auth/SystemUserGroupAuthPolicy.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileEntry.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
- tests/src/test/java/alluxio/client/fuse/JNIFuseIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/file/AbstractFuseFileStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/file/FuseFileInOrOutStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/file/FuseFileInStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/file/FuseFileOutStreamIntegrationTest.java
Refactor the Fuse in out streamS logic. 
Alluxio Fuse can open/create files in read/write/read_and_write mode, while Alluxio only supports read only or sequential write only workloads.
Added FuseInStream, FuseOutStream, FuseInOrOutStream to transfer Fuse stream logic into Alluxio stream logic.
The original code is hard to understand, maintain, and extend.
In the new approach, different streams are isolated, it's easier to troubleshoot or add a new stream (e.g. InAndOutStream)
NA
> Refactor Fuse in out stream

- core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadResult.java
- pom.xml
fix https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518
jackson-databind before 2.13.0 allows a Java StackOverflow exception and denial of service via a large depth of nested objects.
no
> Fix the security vulnerability from jackcon databind

- core/common/src/main/java/alluxio/retry/ExponentialBackoffRetry.java
Fix wrong abs method in `ExponentialBackoffRetry`.
In the current implementation, the value of the `sleepMs` variable is
almost impossible to be `Integer.MIN_VALUE`, because the value of
`mBaseSleepTimeMs` is 50 or 100, neither is a power of 2.
As can be seen from the name of this method (`"abs"`), its function
is mainly to prevent negative numbers from appearing during overflow,
so it is OK to use `Math.abs()` directly.
No
> Fix wrong abs method in ExponentialBackoffRetry

- pom.xml
Fix https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-34429
see: https://github.com/eclipse/jetty.project/security/advisories/GHSA-vjv5-gp2w-65vm
The default compliance mode allows requests with URIs that contain a %u002e segment to access protected resources within the WEB-INF directory. For example, a request to /%u002e/WEB-INF/web.xml can retrieve the web.xml file. This can reveal sensitive information regarding the implementation of a web application. Similarly, an encoded null character can prevent correct normalization so that /.%00/WEB-INF/web.xml cal also retrieve the web.xml file.
no
> Fix the vulnerbility caused by jetty-webapp

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
Fix AlluxioFuseUtils.getUserName bug
Currently alluxio-fuse chown always set the user to the user that mounts the path.
```
alluxio# touch test_chown
alluxio# ll test_chown
-rw-r--r-- 1 alluxio alluxio 0 Jun  8 14:53 test_chown
alluxio# chown test test_chown
alluxio# ll test_chown
-rw-r--r-- 1 alluxio alluxio 0 Jun  8 14:39 test_chown
```
The cause is here https://github.com/Alluxio/alluxio/blob/master/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java#L208
As the below test demonstrated
```
$ id -nu 1008
test
$ bash -c id -nu 1008
uid=1071(alluxio) gid=1071(alluxio) groups=1071(alluxio)
$ bash -c "id -nu 1008"
test
```
No
> Fix AlluxioFuseUtils getUserName

- core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
Add getCachedPageIdsByFileId to NoExceptionCacheManager
The caller should be able to call getCachedPageIdsByFileId via NoExceptionCacheManager
No
> Add getCachedPageIdsByFileId to NoExceptionCacheManager

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
Fix the getCachedPageIdsByFileId for small or empty files
The existing impl is missing the ceiling round when calculate the num of pages for a file, so it will exclude the last the page for the files whose length is not divisible by the page length.
No
> Fix the getCachedPageIdsByFileId for small or empty files

- dev/scripts/watch-metrics.sh
Refactor the `watch-metrics.sh` script to be more useable, and to increase its flexibility.
The previous script required knowledge about the format of the JSON returned by the Alluxio metrics JSON sink. This version of the script only requires the metrics keys.
Developers using the script will see changed flags & functionality.
> Refactor watch-metrics.sh script

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/fuse/StackFS.java
Change uid and gid from octal format to decimal format in log
Generally uid/gid is decimal format, logging them in octal format causes confusing.
For example, the uid in log is `uid=1760` but `id` gives `uid=1008`
```
$ id test
uid=1008(test) gid=1008(test) groups=...
$ chown test test_file
$ grep Chown .../fuse.log
2022-06-11 12:27:47,031 DEBUG AlluxioJniFuseFileSystem - Enter: Fuse.Chown(path=/sidecar/test,uid=1760,gid=...)
```
No
> Change uid and gid from octal to decimal format

- core/server/common/src/main/java/alluxio/master/journal/JournalUtils.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointThread.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
The `UfsJournalCheckpointThread` calls `System.exit(-1)` when encountering journal corruption. This causes a deadlock between the `UfsJournalCheckpointThread` and the shutdown hook calling `AlluxioMasterProcess.stop()`.
This PR removes the `System.exit()` calls in favor of propagating exceptions when the thread completes. 
The net effect is that the master process completely releases its resources when shutting down and terminates without having to be issued `kill -9`.
For clean master process termination on errors.
No.
> Remove System.exit() calls in ufs journal catchup and propagate errors

- core/server/common/src/main/java/alluxio/master/journal/JournalUtils.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointThread.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
The `UfsJournalCheckpointThread` calls `System.exit(-1)` when encountering journal corruption. This causes a deadlock between the `UfsJournalCheckpointThread` and the shutdown hook calling `AlluxioMasterProcess.stop()`.
This PR removes the `System.exit()` calls in favor of propagating exceptions when the thread completes. 
The net effect is that the master process completely releases its resources when shutting down and terminates without having to be issued `kill -9`.
For clean master process termination on errors.
No.
[This is an manually generated PR to cherry-pick committed PR Alluxio/alluxio#15699 into target branch branch-2.7]
> Port changes of [#15699] to branch-2.6

- core/server/master/src/main/java/alluxio/master/CoreMasterContext.java
- core/server/master/src/main/java/alluxio/master/MasterUtils.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/metastore/BlockMetaStore.java
- core/server/master/src/main/java/alluxio/master/metastore/heap/HeapBlockMetaStore.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockMetaStore.java
- core/server/master/src/test/java/alluxio/master/BackupManagerTest.java
- core/server/master/src/test/java/alluxio/master/MasterTestUtils.java
- core/server/master/src/test/java/alluxio/master/metastore/BlockMetaStoreTest.java
- table/server/master/src/test/java/alluxio/master/table/TableMasterFactoryTest.java
Rename BlockStore interface to BlockMetaStore
The blockStore interface actually is a store for the metadata of blocks rather than the data of blocks, so New name may reduce confusion.
Also I would like to use the name of BlockStore for the abstraction of pagedBlockStore and tieredBlockStore.
N/A
> Rename BlockStore interface to BlockMetaStore

- core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/conf/path/PrefixPathConfiguration.java
- core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
- core/common/src/main/java/alluxio/underfs/UnderFileSystemConfiguration.java
- core/common/src/main/java/alluxio/underfs/UnderFileSystemFactoryRegistry.java
- core/common/src/test/java/alluxio/conf/PropertyKeyTest.java
- core/common/src/test/java/alluxio/underfs/UnderFileSystemConfigurationTest.java
- core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/test/java/alluxio/master/file/meta/AsyncUfsAbsentPathCacheTest.java
- core/server/master/src/test/java/alluxio/master/file/meta/LazyUfsBlockLocationCacheTest.java
- core/server/worker/src/main/java/alluxio/underfs/WorkerUfsManager.java
- integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemContractTest.java
- job/server/src/main/java/alluxio/underfs/JobUfsManager.java
- shell/src/main/java/alluxio/cli/ValidateHdfsMount.java
- stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
- tests/src/test/java/alluxio/server/ft/journal/ufs/UfsConfigurationJournalTest.java
- tests/src/test/java/alluxio/testutils/underfs/sleeping/SleepingUnderFileSystemFactory.java
- underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
1) Implements AlluxioConfiguration instead of extends InstancedConfiguration
This will remove set capabilities of UnderFileSystemConfiguration, thus removing
the need of copying when constructing. When set is needed, a new InstancedConfiguration
is explicitly created with copyProperties.
2) Remove mShared / isShared / setShared. This is only used in unit test.
> Refactor UnderFileSystemConfiguration

- core/common/src/test/java/alluxio/ConfigurationRule.java
- core/common/src/test/java/alluxio/ConfigurationRuleTest.java
- docs/cn/contributor/Unit-Testing.md
- docs/en/contributor/Code-Conventions.md
I propose to add a `set` method in `ConfigurationRule` to let unit-tests change configurations in the scope of a single method.
Fix #15683 
No
> Support method-level set for ConfigurationRule

- shell/src/main/java/alluxio/cli/LogLevel.java
Sometimes, both workers and masters are use the same web port, so it cannot infer role from port atomically, so we should supply a way to specify the role for the targets.
```console
$ bin/alluxio logLevel --logName alluxio.worker.block.TieredBlockStore --level DEBUG --target localhost:30000:worker
```
> Support specify role for a target when execute logLevel command

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
This PR changes the variable 'toRead' from Integer to Long.
```
When we increase the size of a put to 2GB, we the get the following error that I see on the proxy side:
2022-05-17 20:55:00,782 WARN S3RestUtils - Unexpected error invoking REST endpoint: For input string: “2147483648”
/Users/t_bisson/Documents/scripts$aws --profile test-aiml-dp-dsc-admin --endpoint http://wiccan-lab.g.apple.com:39999/api/v1/s3/ s3api put-object --bucket=testbucket --key=2gfile_wiccan.txt --body=~/Documents/scripts/2g.img
An error occurred (InternalError) when calling the PutObject operation (reached max retries: 4): For input string: "2147483648"
```
our S3 REST API parses the Content-Length header as a signed Java Integer so it caps at ~2 GB.
If the file is larger than 2GB, some errors will occure.
> Fix the bug of 2GB File Size Limitation with S3 Rest API

- shaded/client/pom.xml
Shade aarch64 netty epoll lib
Make sure aarch64 netty epoll lib is shaded and add a prefix `liballuxio_shaded_client_`.
No
> Shade aarch64 netty epoll lib

- pom.xml
fix https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15250
see [GHSA-269g-pwp5-87pp](https://github.com/junit-team/junit4/security/advisories/GHSA-269g-pwp5-87pp)
The JUnit4 test rule [TemporaryFolder](https://junit.org/junit4/javadoc/4.13/org/junit/rules/TemporaryFolder.html) contains a local information disclosure vulnerability.
no
> Bump junit version again to fix the security vulerability

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalReader.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
- docs/en/operation/Journal.md
- minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
- tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java
This PR adds the option of triggering a backup automatically when an Alluxio master shuts down.
This helps trigger backups automatically when the master encounters unexpected journal corruption. 
It adds a new `PropertyKey` to enable the feature (it is disabled by default).
> Create automatic backup when shutting down Alluxio master

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalReader.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
- docs/en/operation/Journal.md
- minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
- tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java
This PR adds the option of triggering a backup automatically when an Alluxio master shuts down.
This helps trigger backups automatically when the master encounters unexpected journal corruption. 
It adds a new `PropertyKey` to disable the feature (it is enabled by default).
[This is an manually generated PR to cherry-pick committed PR Alluxio/alluxio#15698 into target branch branch-2.6]
> Port changes of [#15698] to branch-2.6

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- docs/en/api/POSIX-API.md
- docs/en/deploy/Running-Alluxio-On-Docker.md
- docs/en/deploy/Running-Alluxio-On-Kubernetes.md
- integration/kubernetes/helm-chart/alluxio/values.yaml
Fixes https://github.com/Alluxio/alluxio/issues/14485
Change from kernel_cache to direct_io fuse mount mode by default for JNI-FUSE.
Yeah, read performance may be impacted but Fuse pod stability will be improved in kubernetes environment
> Set direct_io as the default fuse mount option for JNIFuse

- core/server/common/src/main/java/alluxio/master/BackupManager.java
This closes the thread pools used during backup and restore from backup.
Since the thread pools were not being closed, the threads were being leaked and not garbage collected.
No
> Fix leaking threads in backup

- docs/en/operation/Admin-CLI.md
- docs/en/operation/Journal.md
- shell/src/main/java/alluxio/cli/fsadmin/command/BackupCommand.java
Some of the documentation on the website and in the CLI is missing information about `--bypass-delegation`.
Followup to #15110.
> Fix documentation surrounding `backup` command
