Alluxio/alluxio

- core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
add missing thread name
add missing thread name
https://github.com/Alluxio/alluxio/blob/f2825833fbf5d473fe7265aae749e8b3d52df143/core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java#L147-L149
missing thread name
https://github.com/Alluxio/alluxio/blob/f2825833fbf5d473fe7265aae749e8b3d52df143/core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java#L256-L265
No
> Add missing thread name

- core/server/worker/src/main/java/alluxio/worker/block/io/StoreBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/block/io/StoreBlockWriter.java
The variables are not accessed in other classes so they should be private
> Change member variable in mBlockMeta to private

- tests/src/test/java/alluxio/client/fuse/AbstractFuseIntegrationTest.java
Improve code style\
StandardCharsets.UTF_8 can be used instead of "UTF_8" String
NO
> Improve code style

- integration/docker/entrypoint.sh
Remove an extra space in the script
> [SMALLFIX] Fix entrypoint.sh typo

- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockLockManager.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManager.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/annotator/LRFUAnnotator.java
- core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
- core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockReaderTest.java
- core/server/worker/src/test/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandlerTest.java
Removing some unnecessary APIs in BlockStore.
> Cleanup BlockStore

- dev/intellij/runConfigurations/AlluxioMaster_0.xml
> [DOCFIX] Fix incorrect -D args in IntelliJ config

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Refactor property key template constructor.
N/A
N/A
> Refactor property key template constructor

- docs/en/operation/StressBench.md
Add docs on new stress bench improvements.
Related PRs: #14842, #14925
> [DOCFIX] Update stress bench doc

- core/common/src/main/java/alluxio/util/CommonUtils.java
See title.
Can be used to label Alluxio-related processes that do not fit the existing process types.
No
> Add Plugin ProcessType

- docs/en/api/POSIX-API.md
Improve the POSIX API docs to be easier to follow.
Add some performance tuning recommendation
> [DOCFIX] Improve POSIX API docs

- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/common/src/test/java/alluxio/util/network/NetworkAddressUtilsTest.java
See title.
Allows us to have some flexibility with using `NetworkAddressUtils` functions.
No
> Create interface for NetworkAddressUtils ServiceType

- integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
Fix typo in Fuse daemonset yaml
> [SMALLFIX] Fix typo

- docs/en/compute/Tensorflow.md
> [DOCFIX] Validate `Tensorflow.md`

- docs/en/compute/Hive.md
> [DOCFIX] Improve Hive doc

- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
> Remove BlockWriter from UnderFileSystemBlockStore.BlockInfo

- docs/en/ufs/HDFS.md
> [DOCFIX] Update HDFS doc

- docs/en/operation/Scalability-Tuning.md
Added a few improvements to the scalability doc
> [DOCFIX] Update scalability doc

- core/client/fs/src/main/java/alluxio/client/block/policy/LocalFirstAvoidEvictionPolicy.java
- core/client/fs/src/main/java/alluxio/client/block/policy/LocalFirstPolicy.java
- docs/en/api/FS-API.md
* Fix javadoc and documentation related to `LocalFirstPolicy` and `LocalFirstAvoidEvictionPolicy`.
* Update link to configuration property `alluxio.user.file.write.tier.default`.
* Update example python code.
> [DOCFIX] Fix File System API documentation

- docs/en/core-services/Caching.md
Fix the inaccurate statement in the caching doc
doc
> [DOCFIX] Fix the inaccurate statement in the caching doc

- docs/en/ufs/S3.md
> [DOCFIX] Update UFS S3 webpage doc

- docs/en/api/POSIX-API.md
> [DOCFIX] Fix POSIX API doc

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerDataReader.java
- core/common/src/main/java/alluxio/wire/BlockReadRequest.java
- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockStoreEventListener.java
- core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/LocalBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/evictor/Evictor.java
- core/server/worker/src/main/java/alluxio/worker/block/management/AbstractBlockManagementTask.java
- core/server/worker/src/main/java/alluxio/worker/block/management/BlockTransferExecutor.java
- core/server/worker/src/main/java/alluxio/worker/block/management/ManagementTaskCoordinator.java
- core/server/worker/src/main/java/alluxio/worker/block/management/tier/AlignTask.java
- core/server/worker/src/main/java/alluxio/worker/block/management/tier/PromoteTask.java
- core/server/worker/src/main/java/alluxio/worker/block/management/tier/SwapRestoreTask.java
- core/server/worker/src/main/java/alluxio/worker/block/management/tier/TierManagementTaskProvider.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadRequestContext.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTestUtils.java
- core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockReaderTest.java
- core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockStoreTest.java
- core/server/worker/src/test/java/alluxio/worker/grpc/BlockReadHandlerTest.java
- core/server/worker/src/test/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandlerTest.java
* Change createBlockReader to remove dependency on BlockReadRequest
* Remove createUfsBlockReader
> Refactor BlockWorker API

- docs/en/contributor/Building-Alluxio-From-Source.md
- docs/en/core-services/Unified-Namespace.md
- docs/en/ufs/HDFS.md
Update HDFS documents with build information for active sync
> [DOCFIX] Update HDFS build information for active sync

- docs/en/compute/Spark.md
Update outdated commands in spark document
> [DOCFIX] Update commands in spark doc

- docs/en/operation/Admin-CLI.md
> [DOCFIX] Validate fsadmin doc

- docs/en/operation/Metastore.md
Minor update to metastore document.
> [DOCFIX] Update metastore document

- docs/en/contributor/Building-Alluxio-From-Source.md
Validate Building from source doc
> [DOCFIX] Validate Building from source doc

- docs/en/operation/Metrics-System.md
- docs/en/operation/Web-Interface.md
Add docs for https://github.com/Alluxio/alluxio/pull/14259
NA
NA
> [DOCFIX] Add how to enable web/metrics on standby masters

- integration/docker/csi/alluxio/nodeserver.go
- integration/kubernetes/helm-chart/alluxio/templates/csi/nodeplugin.yaml
- integration/kubernetes/helm-chart/alluxio/values.yaml
1. If `nodeStageVolume` doesn't return succeed, CSI will recall this method, which means we don't need to implement retry ourselves.
2. `mount` command sometimes doesn't work in Alpine image. Look at `proc/mounts` instead. Fix https://github.com/Alluxio/alluxio/issues/15394
> Improve CSI

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/FileSystemMasterView.java
> Optimize the getLostFile to avoid one copy

- docs/cn/operation/Troubleshooting.md
Update operation/troubleshooting Doc
The Chinese contributor/Building-Alluxio-From-Source document is not updated with the latest changes, this PR synchronizes these updates
In the updated content, some document links point to English documents, because there is no Chinese version of these documents at present.
no
> [DOCFIX] Update operation/troubleshooting chinese doc

- docs/cn/contributor/Building-Alluxio-From-Source.md
Update contributor/Building-Alluxio-From-Source Doc
The Chinese contributor/Building-Alluxio-From-Source document is not updated with the latest changes, this PR synchronizes these updates
> [DOCFIX] Update contributor/Building-Alluxio-From-Source Doc

- docs/cn/ufs/Ozone.md
- docs/en/ufs/Ozone.md
Improve UFS ozone doc, Added:
- the mount about HA Ozone mode 
- the mount of the specified Ozone version
Improve UFS ozone doc
NO
> [DOCFIX] Improve UFS ozone doc

- core/common/src/main/java/alluxio/AbstractClient.java
- core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
- core/common/src/main/java/alluxio/master/ZkMasterInquireClient.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/server/common/src/main/java/alluxio/master/journal/raft/BufferedJournalApplier.java
- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/SnapshotReplicationManager.java
- core/server/common/src/test/java/alluxio/master/RegistryTest.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java
- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
- stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java
Miscellaneous tech debt cleanup.
> Refactor tech debt

- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/LocalBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java
- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
- core/server/worker/src/test/java/alluxio/worker/block/management/tier/BaseTierManagementTaskTest.java
- core/server/worker/src/test/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandlerTest.java
Rename getBlockWriter to createBlockWriter
createBlockWriter is a more appropriate name because it's creating a new writer
none
> Rename getBlockWriter to createBlockWriter

- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
Fixes [Alluxio/new-contributor-tasks/issues#621](https://github.com/Alluxio/new-contributor-tasks/issues/621)
at 
[alluxio/core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java](https://github.com/singer-bin/alluxio/blob/fbae051d7f2c25df83a298c1d33490a095d015f5/core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java#L723)
> Fix typo at AbstractFileSystem

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockStore.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
- docs/en/operation/Metastore.md
Cherry picking changes from #15484 to branch-2.7.
> Expose RockDB metrics as Alluxio metrics

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/InstrumentedExecutorService.java
- core/common/src/main/java/alluxio/metrics/MaxReservoir.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/transport/src/main/proto/grpc/common.proto
- core/transport/src/main/proto/proto.lock
Cherry pick changes from #15515 to `branch-2.7`.
> Port changes of [#15515] to branch-2.7

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java
- core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
Port changes of [#15204] to `branch-2.7`.
> Port changes of [#15204] to branch-2.7

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java
- core/server/master/src/test/java/alluxio/master/file/meta/AsyncUfsAbsentPathCacheTest.java
Port changes of [#15357] to `branch-2.7`.
> Port changes of [#15357] to branch-2.7

- core/client/fs/src/main/java/alluxio/client/file/cache/DefaultMetaStore.java
Add precondition check on page ids to ensure they match.
> [SMALLFIX] Ensure page IDs match

- integration/fuse/bin/alluxio-fuse
Please backport to v2.7.3
close #15451
> Remove extra colon in java classpath for FUSE

- core/client/fs/src/main/java/alluxio/client/file/FileSystemUtils.java
Remove the uncessary InterruptedException in the signature
Remove the uncessary InterruptedException in the signature
no
> Remove the uncessary InterruptedException in the signature

- core/client/fs/src/main/java/alluxio/client/file/options/InStreamOptions.java
Refactor building ufs block options
Make the code more clean and concise
N/A
> Refactor building ufs block options

- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/worker/block/BlockStoreType.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/LocalBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockMetaStore.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedLocalBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
- core/server/worker/src/test/java/alluxio/worker/block/management/tier/BaseTierManagementTaskTest.java
- core/server/worker/src/test/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandlerTest.java
- tests/src/test/java/alluxio/client/fs/LocalCacheManagerIntegrationTest.java
Implement the read path of pagedd local block store
Improve the stability of worker
Prevent read amplification
Added new properties to enable the paged local block store
> Implement the read path of paged local block store

- assembly/client/pom.xml
- assembly/server/pom.xml
- microbench/build/checkstyle/suppressions.xml
- microbench/build/findbugs/findbugs-exclude.xml
- microbench/pom.xml
- microbench/readme.md
- microbench/src/main/java/alluxio/RpcUtilsBench.java
- pom.xml
- shaded/client/pom.xml
Add a skeleton for the microbenchmarks module. Plus a simple benchmark.
> Add microbench module skeleton

- integration/tools/benchmark/README.md
- integration/tools/benchmark/pytorch/Dockerfile
- integration/tools/benchmark/pytorch/README.md
- integration/tools/benchmark/pytorch/load.py
- integration/tools/benchmark/pytorch/run-test.sh
Add PyTorch benchmarking scripts to benchmarking data loading performance from Alluxio POSIX API or local filesystem.
Add benchmarking script
Yeah, about how they benchmarking Alluxio performance
> Add pytorch benchmarking scripts

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/WorkerRegisterContext.java
Refactor WorkerRegisterContext
No
> Refactor WorkerRegisterContext

- core/server/worker/src/main/java/alluxio/worker/block/annotator/DefaultBlockIterator.java
Refactor DefaultBlockIterator's constructor
make fields to be final
add requireNonNull in the constructor
> Refactor DefaultBlockIterator's constructor

- core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java
Remove the catch of throwable
Throwable might be a jvm fatal error which we should not catch
no
> Remove the catch of throwable

- core/server/worker/src/main/java/alluxio/web/WorkerWebServer.java
- core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
Remove the unused parameters in WorkerWebServers's constructor
Remove the unused parameters in WorkerWebServers's constructor
no
> Remove the unused parameters in WorkerWebServers's constructor

- core/client/fs/src/main/java/alluxio/client/file/cache/DefaultMetaStore.java
- core/client/fs/src/test/java/alluxio/client/file/cache/DefaultMetaStoreTest.java
As Baolong and I discussed in https://github.com/Alluxio/alluxio/pull/14585, I propose the changes below to improve the accuracy of the metrics.
Using the actual map size instead of the inc/dec for the metrics of num of pages
Remove the unnecessary field mPages 
This change would improve the accuracy of the metrics.  Because the exceptions might skip some of the inc/dec which might make the value of the metrics diverged greatly.
None
> Improve accuracy of the metrics on num of pages

- core/client/fs/src/test/java/alluxio/client/file/cache/DefaultMetaStoreTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/QuotaMetaStoreTest.java
Fix junit test failure in QuotaMetaStoreTest
fix the build
no
> Fix junit test failure in QuotaMetaStoreTest

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Fix the issue that chgrp caused ufs lose the file's owner attribute.
Fix https://github.com/Alluxio/alluxio/issues/15583
No
> Fix chgrp lose owner issue

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerDataWriter.java
- core/common/src/main/java/alluxio/exception/BlockAlreadyExistsException.java
- core/common/src/main/java/alluxio/exception/BlockDoesNotExistException.java
- core/common/src/main/java/alluxio/exception/InvalidWorkerStateException.java
- core/common/src/main/java/alluxio/exception/status/AlluxioStatusException.java
- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/common/src/main/java/alluxio/worker/block/meta/StorageDir.java
- core/server/worker/src/main/java/alluxio/worker/block/AsyncBlockRemover.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManager.java
- core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/LocalBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/block/meta/DefaultStorageDir.java
- core/server/worker/src/main/java/alluxio/worker/block/meta/DefaultStorageTier.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedLocalBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockMetadataManagerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
- core/server/worker/src/test/java/alluxio/worker/block/meta/DefaultStorageDirTest.java
- core/server/worker/src/test/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandlerTest.java
This change removes a lot of unnecessary Exceptions in block worker and underlying block store APIs.
> Simplify exception handling in block worker

- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
Change `Get` into `Gets` in code comments.
Fix Alluxio/new-contributor-tasks#618
No.
> [SMALLFIX] Improve javadoc in ObjectUnderFileSystem.java

- core/server/common/src/main/java/alluxio/master/AbstractMaster.java
Remove extra prep `of` in code comments.
Fix Alluxio/new-contributor-tasks#622
No.
> [SMALLFIX] Fix grammar error in AbstractMaster.java

- shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
- shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
- stress/shell/src/main/java/alluxio/stress/cli/StressJobServiceBench.java
- table/shell/src/main/java/alluxio/cli/table/command/LoadTableCommand.java
Repackaging distributed load code into DistributedLoadUtils to enable file semantics and structured data semantics to share distributed load code.
https://github.com/Alluxio/alluxio/issues/13287
Nope.
> Enable both file and table semantics to share distLoad code

- shell/src/main/java/alluxio/cli/GetConf.java
- shell/src/main/java/alluxio/cli/LogLevel.java
- shell/src/main/java/alluxio/cli/RunOperation.java
- shell/src/main/java/alluxio/cli/TestRunner.java
- shell/src/main/java/alluxio/cli/Version.java
Clean up some warnings in Alluxio shell
> Clean Alluxio shell warnings

- core/common/src/main/java/alluxio/AbstractClient.java
Rectifies the behavior change that was introduced [here](https://github.com/Alluxio/alluxio/pull/15494/files#r882961521).
> Fix behavior change

- core/client/fs/src/main/java/alluxio/client/block/BlockStoreClient.java
- core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataReader.java
Clean some warnings reported by Intellij
> Clean up code

- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockReader.java
Add counters `WORKER_BLOCKS_READ_LOCAL` and `WORKER_BLOCKS_READ_UFS` in paged block reader.
The implementation assumes the counters are not exclusive. In cases where a block has some pages cached and some pages uncached, and a read accesses both cached and uncached pages, then both counters will be incremented, as if this block has been read twice from both local file and UFS.
The metrics were missing.
No.
> Add missing metrics to paged local block store

- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
The access to `mBlock` is not protected by `mLock` in `isNoCache`.
Fix potential race condition.
No.
> Fix potential race condition in UnderFileSystemBlockStore

- integration/jnifuse/fs/src/main/java/alluxio/jnifuse/AbstractFuseFileSystem.java
Modify the code style to align with the coding convention in `AbstractFuseFileSystem.java`
> Fix codestyle in AbstractFuseFileSystem

- integration/jnifuse/fs/src/main/java/alluxio/jnifuse/utils/NativeLibraryLoader.java
Fix coding styles of `NativeLibraryLoader.java` in jnifuse
> Fix coding style in jnifuse

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
- core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/transport/src/main/proto/grpc/block_worker.proto
- core/transport/src/main/proto/proto.lock
add batch load API to worker
more efficient distributedload
> Add batch Load Api

- core/common/src/main/java/alluxio/cli/AbstractShell.java
- shell/src/main/java/alluxio/cli/fs/command/CheckConsistencyCommand.java
- shell/src/main/java/alluxio/cli/fs/command/CopyFromLocalCommand.java
- shell/src/main/java/alluxio/cli/fs/command/CopyToLocalCommand.java
- shell/src/main/java/alluxio/cli/fs/command/CpCommand.java
- shell/src/main/java/alluxio/cli/fs/command/DistributedMvCommand.java
- shell/src/main/java/alluxio/cli/fs/command/MasterInfoCommand.java
- shell/src/main/java/alluxio/cli/fs/command/PinCommand.java
- shell/src/main/java/alluxio/cli/fs/command/StatCommand.java
Cleans up IDE warnings in fs cli.
> Cleanup fs cli warnings

- core/client/fs/src/main/java/alluxio/client/block/BlockStoreClient.java
- core/server/master/src/main/java/alluxio/master/file/AccessTimeUpdater.java
- core/server/master/src/main/java/alluxio/master/file/DefaultPermissionChecker.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterAuditContext.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterJobServiceHandler.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterWorkerServiceHandler.java
- core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java
- core/server/master/src/main/java/alluxio/master/file/ListStatusResultStream.java
- core/server/master/src/main/java/alluxio/master/file/NoopBlockDeletionContext.java
- core/server/master/src/main/java/alluxio/master/file/PermissionChecker.java
- core/server/master/src/main/java/alluxio/master/file/RpcContext.java
- core/server/master/src/main/java/alluxio/master/file/UfsSyncChecker.java
- core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java
- core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java
- core/server/master/src/main/java/alluxio/master/file/meta/FileSystemMasterView.java
Clean up alluxio.master.file package code
> Clean up alluxio.master.file package code

- core/server/common/src/main/java/alluxio/master/journal/JournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSystem.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/AlluxioSecondaryMaster.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- job/server/src/main/java/alluxio/master/AlluxioJobMasterProcess.java
- job/server/src/main/java/alluxio/master/FaultTolerantAlluxioJobMasterProcess.java
Refactor general warnings around master process and RaftJournal and UfsJournal
> Fix general warnings with master process and journals

- stress/common/src/main/java/alluxio/stress/Parameters.java
- stress/common/src/main/java/alluxio/stress/client/ClientIOParameters.java
- stress/common/src/main/java/alluxio/stress/client/ClientIOTaskResult.java
- stress/common/src/main/java/alluxio/stress/common/FileSystemParameters.java
- stress/common/src/main/java/alluxio/stress/fuse/FuseIOOperation.java
- stress/common/src/main/java/alluxio/stress/fuse/FuseIOParameters.java
- stress/common/src/main/java/alluxio/stress/jobservice/JobServiceBenchSummary.java
- stress/common/src/main/java/alluxio/stress/jobservice/JobServiceBenchTaskResult.java
- stress/common/src/main/java/alluxio/stress/master/MasterBenchSummary.java
- stress/common/src/main/java/alluxio/stress/master/MasterBenchTaskResult.java
- stress/shell/src/main/java/alluxio/stress/cli/Benchmark.java
- stress/shell/src/main/java/alluxio/stress/cli/MasterBatchTask.java
- stress/shell/src/main/java/alluxio/stress/cli/RegisterWorkerBench.java
- stress/shell/src/main/java/alluxio/stress/cli/RpcBench.java
- stress/shell/src/main/java/alluxio/stress/cli/RpcBenchPreparationUtils.java
- stress/shell/src/main/java/alluxio/stress/cli/StreamRegisterWorkerBench.java
- stress/shell/src/main/java/alluxio/stress/cli/StressJobServiceBench.java
- stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java
- stress/shell/src/main/java/alluxio/stress/cli/UfsIOBench.java
- stress/shell/src/main/java/alluxio/stress/cli/WorkerHeartbeatBench.java
- stress/shell/src/main/java/alluxio/stress/cli/client/ClientIOWritePolicy.java
- stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
- stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java
- stress/shell/src/main/java/alluxio/stress/cli/report/GenerateReport.java
- stress/shell/src/main/java/alluxio/stress/cli/suite/AbstractMaxThroughput.java
- stress/shell/src/main/java/alluxio/stress/cli/suite/MasterMaxThroughput.java
- stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
Clean up stress code
Clean up stress code
na
> Clean up stress code

- core/client/fs/src/main/java/alluxio/client/file/cache/cuckoofilter/SegmentedLock.java
Refactor the locks of cuckoo filter
make is more concise and readable
no
> Refactor the locks of cuckoo filter

- pom.xml
fix https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15250
see https://github.com/junit-team/junit4/security/advisories/GHSA-269g-pwp5-87pp
The JUnit4 test rule [TemporaryFolder](https://junit.org/junit4/javadoc/4.13/org/junit/rules/TemporaryFolder.html) contains a local information disclosure vulnerability.
no
> Fix the security vulernability caused by junit's temp folder

- shell/src/main/java/alluxio/cli/fs/command/StatCommand.java
> Support Stat command output fileid by formatted argument

- tests/src/test/java/alluxio/client/cli/job/DistributedCommandsStatsTest.java
Increase timeouts for sleepingUFS
> Fix async-persist cancel test timeout

- core/server/worker/src/main/java/alluxio/worker/block/RegisterStreamer.java
- core/server/worker/src/test/java/alluxio/worker/block/RegisterStreamerTest.java
Created a unit test class for `RegisterStreamer` to test expected interaction and stream operations.
- Improve unit test coverage(0% ->92%)
- Exposed some under-clarified behavior in the class
No
> Add unit tests for RegisterStreamer

- core/common/src/main/java/alluxio/grpc/GrpcConnectionPool.java
Remove duplicate mod operation in `GrpcConnectionPool`.
The mod operation is currently performed twice, which is duplicate.
No.
> Remove duplicate mod operation in GrpcConnectionPool

- core/server/worker/pom.xml
- core/server/worker/src/test/java/alluxio/worker/block/BlockMasterClientTest.java
add more unit tests in BlockMasterClientTest that tests for expected grpc behaviors.
improve unit-test coverage of BlockMasterClient (20% -> 90%)
No
> Add unit tests for BlockMasterClient

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerDataWriter.java
- core/common/src/main/java/alluxio/worker/block/BlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/DelegationWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/block/CacheRequestManagerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/grpc/BlockWriteHandlerTest.java
- tests/src/test/java/alluxio/client/fs/BlockWorkerRegisterStreamIntegrationTest.java
This reverts commit 39ccec884a186d8ee9621039e692eeb19d4c5bd0.
> Revert "Refine grpc handler to use the new block store api"

- docs/en/operation/Admin-CLI.md
- docs/en/operation/Journal.md
- shell/src/main/java/alluxio/cli/fsadmin/command/BackupCommand.java
Some of the documentation on the website and in the CLI is missing information about `--bypass-delegation`.
Followup to #15110.
[This is an manually generated PR to cherry-pick committed PR Alluxio/alluxio#15749 into target branch branch-2.6]
> Port changes of [#15749] to branch-2.6

- core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- core/common/src/main/java/alluxio/AbstractClient.java
- core/common/src/main/java/alluxio/conf/Configuration.java
- core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
- core/common/src/main/java/alluxio/grpc/GrpcChannelKey.java
- core/common/src/main/java/alluxio/grpc/GrpcConnectionKey.java
- core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/common/src/test/java/alluxio/grpc/GrpcConnectionPoolTest.java
- core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingClient.java
> Simplify GrpcChannelBuilder and GrpcChannelKey

- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
- core/transport/src/main/proto/grpc/block_worker.proto
- core/transport/src/main/proto/proto.lock
update load API since block size might be different for every block, even for the same file. So change the structure of protobuf and pass in offset in ufs file and block size to better represent the block concept.
na
na
> Update load api

- core/common/src/main/java/alluxio/exception/AlluxioRuntimeException.java
- core/common/src/main/java/alluxio/exception/BlockDoesNotExistRuntimeException.java
- core/common/src/main/java/alluxio/exception/JobDoesNotExistRuntimeException.java
- core/transport/src/main/proto/grpc/common.proto
- core/transport/src/main/proto/proto.lock
- underfs/s3a/src/main/java/alluxio/underfs/s3a/AlluxioS3Exception.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
- underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
> Add alluxio S3 exception

- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
Improve Fuse read/write core logics
> Improve Fuse read/write core logics

- tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
Related PR is https://github.com/Alluxio/alluxio/pull/15615
> Revert o.sync in FileSystemRenameIntegrationTest

- core/server/worker/src/test/java/alluxio/worker/block/PinListSyncTest.java
I added unit tests for `PinListSync`
It improves unit-test coverage of the class (0% -> 100%)
No
> Add unit tests for PinListSync

- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/activesync/SupportedHdfsActiveSyncProvider.java
> Fix build warning for using keySet()

- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/AlluxioHdfsException.java
Add hdfs exception
Better exception handling
na
> Add hdfs exception

- core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java
> Use wakeupEvictThread call while cache is full

- core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockStoreTest.java
I added some tests for `UnderFileSystemBlockStore`
To test the correctness of `UnderFileSystemBlockStore#createBlockReader` and some edge cases.
Improve test coverage for the class(30% -> 80%)
No
> Add unit tests for UnderFileSystemBlockStore

- core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java
> Improve eviction on cache retrieval if cache is full

- core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockStoreTest.java
- tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
Revert mistakenly comment out code
also fix a compile problem because two concurrent PR get merged: #15709 and #15765
na
na
> Fix mistake and compile failure casued by concurrent commits

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadResult.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/CopyPartResult.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/ListPartsResult.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ErrorCode.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/TaggingData.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/signature/AuthorizationV4Validator.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
- tests/src/test/java/alluxio/client/rest/TestCase.java
Based on top of #15796 
---
- Add entity tags to xAttr
- Add UploadPartCopy result XML
- Use Content-Type header in InitiateMultipartUpload
- Add toggleability to tags & bucket restrictions
- [TODO] Update docs
Improve Alluxio S3 API functionality & conformity with AWS S3
New property keys:
- `alluxio.proxy.s3.bucket.naming.restrictions.enabled`
- `alluxio.proxy.s3.tagging.restrictions.enabled`
> [WIP] Add S3 API functionality and handle edge cases

- core/common/src/test/java/alluxio/AlluxioMockUtil.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
- core/server/worker/src/test/java/alluxio/worker/grpc/ShortCircuitBlockReadHandlerTest.java
Created unit tests cases for `ShortCircuitReadHandler`
Improve coverage for the class(0% -> 85%)
No
> Add unit tests for ShortCircuitReadHandler

- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
- tests/src/test/java/alluxio/client/fuse/file/FuseFileInStreamIntegrationTest.java
Fixes #15840
match ext4 behavior
allows open(O_RDONLY|O_TRUNC)
> Allow Fuse open with O_RDONLY|O_TRUNC

- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
Fix Fuse file out stream truncate log
> Fix Fuse truncate log

- dev/jenkins/Dockerfile-jdk11
- dev/jenkins/Dockerfile-jdk8
update java 8 to newer version in jdk11 image
update golang from 1.12 to 1.18
update terraform from 0.12 to 1.0.1
> Update versions in alluxio-maven image

- shell/src/main/java/alluxio/cli/fs/command/DuCommand.java
Modify the meaning of variables more clearly
Modify the meaning of variables more clearly
no
> Modify the meaning of variables more clearly

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
Use Optional type for executors to avoid null
avoid null value handling
n/a
> Use Optional type for executors to avoid null

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Add header parameter 'Authorization' for postBucket method.
Need to check username.
no.
> Add header parameter 'Authorization' for postBucket method

- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/DefaultPageMetaStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/PageMetaStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/QuotaPageMetaStore.java
- core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/DefaultMetaStoreTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerWithMemPageStoreTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/QuotaPageMetaStoreTest.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockMetaStore.java
- tests/src/test/java/alluxio/client/fs/LocalCacheManagerIntegrationTest.java
Rename MetaStore to PageMetaStore
in order to distinguish it from the block metastore
no
> Rename MetaStore to PageMetaStore

- .github/workflows/java11_integration_tests.yml
- .github/workflows/java11_integration_tests_webui.yml
- .github/workflows/java11_unit_tests.yml
- dev/github/run_docker.sh
- dev/jenkins/run_docker.sh
Apply the changes introduced in #15876 and #15881. Update the corresponding image version
> Bump alluxio-maven image to 0.0.8

- microbench/pom.xml
- microbench/src/main/java/alluxio/BaseFileStructure.java
- microbench/src/main/java/alluxio/BaseThreadState.java
- microbench/src/main/java/alluxio/fsmaster/FileSystemMasterBase.java
- microbench/src/main/java/alluxio/fsmaster/FileSystemMasterBench.java
- microbench/src/main/java/alluxio/inode/InodeBenchRead.java
- microbench/src/main/java/alluxio/inode/InodeBenchWrite.java
- microbench/src/main/java/alluxio/inode/RocksBenchRead.java
- microbench/src/main/java/alluxio/inode/RocksBenchReadWrite.java
Create microbench for `FileSystemMaster` and refactor some other common microbench parameters such as number of files, depth of files, and file access patterns.
Redo of #15821.
> Create JMH microbench for `FileSystemMaster`

- stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java
Fix a bug in StressMasterBnecch AlluxioNative client. The AlluxioNative client can only create files of 0KB size.The parameter --create-file-size doesn't work.
The parameter --create-file-size doesn't work in AlluxioNative Client, because the file created by AlluxioNative client is not populated with data.
None
> Fix empty file created by Alluxio native client in StressMasterBench

- core/server/worker/src/test/java/alluxio/worker/grpc/ShortCircuitBlockWriteHandlerTest.java
Added unit tests for `ShortCircuitBlockWriteHandler`
Improved unit test coverage(0% -> 81%)
No
> Add ShortCircuitBlockWriteHandlerTest

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStoreDir.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStoreDir.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreDir.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStoreDir.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreDirTest.java
Use Optional type for getPageId
Use Optional type for getPageId for better null value handling
no
> Use Optional type for getPageId

- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
- core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerWithShadowCacheTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
Implement append for local cache manager
for the write path of paged block store
no
> Implement append for local cache manager

- core/server/master/src/main/java/alluxio/master/file/loadmanager/LoadJob.java
- core/server/master/src/main/java/alluxio/master/file/loadmanager/LoadManager.java
- core/server/master/src/test/java/alluxio/master/file/loadmanager/LoadManagerTest.java
- core/server/master/src/test/java/alluxio/master/file/loadmanager/LoadTestUtils.java
* Support job verification in LoadManager
* remove SUBMITTED job status
* simplify loadManager.processJob
> Support job verification in LoadManager

- core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStoreDir.java
- core/common/pom.xml
- core/common/src/main/java/alluxio/master/metastore/rocks/RocksUtils.java
Fix rockdb iterator leak for local cache by using the new rocksdb iterator pattern in RocksUtil
As @dbw9580 suggested, it might cause the segment fault to use the raw rocksdb iterator
no
> Fix rockdb iterator leak for local cache

- core/common/src/main/java/alluxio/worker/block/BlockStore.java
> Fix an indentation problem

- core/server/common/pom.xml
- core/server/common/src/test/java/alluxio/master/journal/raft/SnapshotReplicationManagerTest.java
- core/server/master/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java
- tests/src/test/java/alluxio/client/cli/JournalToolTest.java
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTestFaultTolerance.java
Upgrade Apache Ratis dependency from 2.0.0 to 2.3.0
2.3.0 brings increased stability, especially around the snapshotting mechanism.
No
> Upgrade Apache Ratis from 2.0.0 to 2.3.0

- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
Fixes #15842
Support Fuse open with O_WRONLY|O_RDWR flags
> Fix Fuse open with O_WRONLY|O_RDWR

- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
> Support dynamic update propertykey for unpooled buffer

- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockWriter.java
- core/server/worker/src/test/java/alluxio/worker/page/PagedBlockWriterTest.java
Implement paged block writer
Implement paged block writer for paged block store
no
> Implement paged block writer

- job/server/src/main/java/alluxio/master/job/common/CmdInfo.java
Fixes [Alluxio/new-contributor-tasks#641](https://github.com/Alluxio/new-contributor-tasks/issues/641)
> [DOCFIX] Remove redundant method names

- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
Add timeout in raft journal test
Make sure this tests fails if it takes too long.
No
> Add timeout in raft journal test

- microbench/pom.xml
- microbench/src/main/java/alluxio/worker/BlockWorkerBase.java
- microbench/src/main/java/alluxio/worker/WorkerBenchLoad.java
Add boilerplate for BlockWorker and add benchmark for load API
na
na
> Add benchmark for BlockWorker

- microbench/pom.xml
- microbench/src/main/java/alluxio/fsmaster/BenchStandaloneGrpcServer.java
- microbench/src/main/java/alluxio/fsmaster/FileSystemBase.java
- microbench/src/main/java/alluxio/fsmaster/FileSystemBench.java
Creates microbenchmarks for the `FileSystem` client-side calls.
Redo of #15919.
> Create microbenchmark for FileSystem class

- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
- microbench/pom.xml
Include JMH microbenchmarks into nightly tarball.
> Include `benchmarks.jar` into tarball

- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
- microbench/pom.xml
This reverts commit b7ef17e5d8a3cecfa205e482d34d57fa9a2b9d38.
> Revert "Include `benchmarks.jar` into tarball"

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
- docs/en/api/S3-API.md
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Manual "cherry-pick" of https://github.com/Alluxio/alluxio/pull/15952 to branch-2.8.
> Port changes of [#15952] to branch-2.8

- core/common/src/main/java/alluxio/worker/block/BlockStore.java
- core/common/src/main/java/alluxio/worker/block/io/BlockWriter.java
- core/common/src/main/java/alluxio/worker/block/io/LocalFileBlockWriter.java
- core/common/src/test/java/alluxio/worker/block/io/LocalFileBlockWriterTest.java
- core/common/src/test/java/alluxio/worker/block/io/MockBlockWriter.java
- core/server/worker/src/main/java/alluxio/worker/block/LocalBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockWriter.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
Use chain of future to further improve the load performance.
Hardening worker exception to use AlluxioRuntimeException
performance and code quality
na
> Update load api with chain of future

- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileInputStream.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Add retry back to keep the behavior the same as before. Would remove the retry in 3.0 version.
na
na
> Revert retry in hdfs

- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockReader.java
- core/server/worker/src/test/java/alluxio/worker/page/ByteArrayCacheManager.java
- core/server/worker/src/test/java/alluxio/worker/page/PagedBlockReaderTest.java
> Fix out of bound read in PagedBlockReader

- job/server/src/main/java/alluxio/job/util/JobUtils.java
- job/server/src/test/java/alluxio/job/plan/replicate/SetReplicaDefinitionReplicateTest.java
Disable passive cache for pinned files.
Fix #15912
No
> Disable passive cache for pinned files

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Fix https://github.com/Alluxio/alluxio/issues/15936
> Avoid checking file permissions in getFileInfo method

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
Allow writing to read-only file when creating
Fix https://github.com/Alluxio/alluxio/issues/15808
No
> Allow writing to read-only file when creating

- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- core/common/src/main/java/alluxio/client/file/CacheContext.java
Add a stats unit for presto's runtime stats
This one will improve the runtime stats on presto side
No
> Add a stats unit for presto's runtime stats

- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/ozone/pom.xml
fix the bug mentioned in the issue [#15960](https://github.com/Alluxio/alluxio/issues/15960)
> Fix ozone mount failure

- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Removes accidentally added Hbase library import from https://github.com/Alluxio/alluxio/pull/15796
> Replace hbase Strings library with Google Guava

- core/client/fs/src/main/java/alluxio/client/file/FileSystemContextReinitializer.java
fix typo in FileSystemContextReinitializer.java
Typos are easy to make people misunderstand.
No, it doesn't.
> Fix typo in FileSystemContextReinitializer.java

- core/common/src/main/java/alluxio/cli/AbstractValidationTask.java
- core/common/src/main/java/alluxio/cli/ValidationUtils.java
- core/common/src/main/java/alluxio/util/ExceptionUtils.java
- integration/tools/hms/src/main/java/alluxio/cli/hms/CreateHmsClientValidationTask.java
- integration/tools/hms/src/main/java/alluxio/cli/hms/DatabaseValidationTask.java
- integration/tools/hms/src/main/java/alluxio/cli/hms/TableValidationTask.java
- integration/tools/hms/src/main/java/alluxio/cli/hms/UriCheckTask.java
- integration/tools/validation/src/main/java/alluxio/cli/RamDiskMountPrivilegeValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/StorageSpaceValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/UfsDirectoryValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/UfsSuperUserValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemContractTest.java
- integration/tools/validation/src/main/java/alluxio/cli/UserLimitValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/hdfs/HdfsConfParityValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/hdfs/HdfsConfValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/hdfs/HdfsProxyUserValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/hdfs/HdfsVersionValidationTask.java
- integration/tools/validation/src/main/java/alluxio/cli/hdfs/SecureHdfsValidationTask.java
- stress/shell/src/main/java/alluxio/stress/cli/UfsIOBench.java
Move an existing utility from `ValidationUtils` to `ExceptionUtils` where it may make more sense.
NA
NA
> Refactor Exception to String conversion util

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Manual "cherry-pick" of https://github.com/Alluxio/alluxio/pull/16074 to branch-2.8.
> Port changes of [#16074] to branch-2.8

- core/server/common/src/main/java/alluxio/RpcUtils.java
> Catch runtime exception in rpc

- integration/docker/Dockerfile
Alpine has been unstable and is blocking other upgrades from taking place. This PR returns the Dockerfile to using CentOS.
> Change Dockerfile to use CentOS instead of Alpine

- core/server/worker/src/main/java/alluxio/worker/block/allocator/MaxFreeAllocator.java
- core/server/worker/src/test/java/alluxio/worker/block/allocator/MaxFreeAllocatorTest.java
- core/server/worker/src/test/java/alluxio/worker/grpc/ShortCircuitBlockReadHandlerTest.java
Fix the return value of `MaxFreeAllocator.allocateBlock`.
Fix https://github.com/Alluxio/alluxio/issues/16106
No
> Fix MaxFreeAllocator.allocateBlock

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
> Fix fuse check file name length method name

- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
Fix potential deadlock in tier store and refine the code
the current impl might cause deadlock
> Fix potential deadlock in tier store and refine the code

- microbench/src/main/java/alluxio/worker/BlockStoreBase.java
- microbench/src/main/java/alluxio/worker/BlockStoreRandomReadBench.java
- microbench/src/main/java/alluxio/worker/BlockStoreReadBench.java
- microbench/src/main/java/alluxio/worker/BlockStoreSequentialReadBench.java
Added a benchmark suite to compare the performance between `MonoBlockStore` and `PagedBlockStore`
Provide insights on the micro performance characteristic for the `PagedBlockStore` that is under development.
No
> Add microbenchmarks for multiple implementations of BlockStore

- stress/common/src/main/java/alluxio/stress/common/FileSystemClientType.java
- stress/common/src/main/java/alluxio/stress/common/FileSystemParameters.java
- stress/common/src/main/java/alluxio/stress/master/MasterBenchBaseParameters.java
- stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java
Add Alluxio POSIX API support for Master Stressbench and MaxThroughput tests.
To have apple to apple comparison between Alluxio POSIX API / Native API / HDFS API interns of metadata read/write performance.
Users can run MasterStressbench and MaxThroughput tests.
> Implement Alluxio POSIX API master stressbench test

- core/client/fs/src/main/java/alluxio/client/block/policy/SpecificHostPolicy.java
> Fix typo at SpecificHostPolicy

- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStoreMeta.java
> Fix paged block store tier name

- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
Some trivial refactoring on AlluxioMasterProcess.
Because we want to make some extensions to AlluxioMasterProcess in the future. Refactoring is put up as a individual PR for the ease of reviewing. 
N/A
> Rename some methods in AlluxioMasterProcess

- core/common/src/main/java/alluxio/AbstractClient.java
Add new connect function
For ee
na
> Add new connect function

- core/common/src/main/java/alluxio/worker/block/BlockStore.java
- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/UfsIOManager.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerExceptionTest.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/block/UfsIoManagerTest.java
- core/transport/src/main/proto/grpc/block_worker.proto
- core/transport/src/main/proto/proto.lock
- microbench/src/main/java/alluxio/worker/WorkerBenchLoad.java
Update load request protobuf
na
na
> Update load request protobuf

- core/common/src/main/java/alluxio/collections/IndexDefinition.java
- core/common/src/test/java/alluxio/collections/IndexedSetConcurrencyTest.java
- core/common/src/test/java/alluxio/collections/IndexedSetTest.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJnrFuseFileSystem.java
- job/server/src/main/java/alluxio/job/util/JobUtils.java
- job/server/src/main/java/alluxio/master/job/JobMaster.java
Add `ofUnique` and `ofNonUnique` factory methods for `IndexDefinition`.
Improve readability and reduce boilerplate code.
No.
> Add factory methods for IndexDefinition

- integration/docker/Dockerfile-dev
Fix the ARG syntax in Dockerfile-dev
> Fix Dockerfile-dev syntax

- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
Use a new client in the thread to avoid closing the client when the method ends.
Fix #16164.
No.
> Fix RaftClient closed error

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Follow-up to https://github.com/Alluxio/alluxio/pull/16162
> Update ListMultipartUploads to prevent leaking other users' upload IDs

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/MultipartUploadCleaner.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ErrorCode.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
- core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
- core/server/proxy/src/test/java/alluxio/proxy/s3/S3RestServiceHandlerTest.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
- tests/src/test/java/alluxio/client/rest/TestCaseOptions.java
- tests/src/test/java/alluxio/client/rest/TestCaseOptionsTest.java
This is a manual cherry-pick of #16162 to `branch-2.8`
> Port changes from [#16162] to branch-2.8

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/test/java/alluxio/proxy/s3/S3RestServiceHandlerTest.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Manual cherry-pick of https://github.com/Alluxio/alluxio/pull/16174
> Port changes of [#16174] to branch-2.8

- stress/common/src/main/java/alluxio/stress/client/ClientIOSummary.java
- stress/common/src/main/java/alluxio/stress/client/ClientIOTaskResult.java
- stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
- tests/src/test/java/alluxio/stress/StressClientIOBenchIntegrationTest.java
1. Lift the check that `--cluster-limit` cannot exceed 1.
2. Put all taskResults from each node into `ClientIOSummary`
> Make clientIO a multi-node test

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Manual cherry-pick for https://github.com/Alluxio/alluxio/pull/16180
> Port changes of [#16180] to branch-2.8

- core/common/src/main/java/alluxio/Constants.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/exception/BusyException.java
- core/common/src/main/java/alluxio/exception/status/AlluxioStatusException.java
- core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java
Add some monitoring indicators for the master status
Add some monitoring indicators for the master status, collecting information for further system throttling.
NA
> Add extra monitoring indicators part1

- shell/src/main/java/alluxio/cli/docgen/MetricsDocGenerator.java
Missing "proxy" in the defined categories to generate metrics csv/yaml
bin/alluxio docGen will not dump NPE
N/A
> Add missing category in metrics docs generation

- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/page/PagedBlockReaderTest.java
Fix incorrect initial offset in paged block reader.
> Fix paged block reader transfer offset

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/common/src/main/java/alluxio/master/AlluxioExecutorService.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
- core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
- docs/_data/table/en/master-metrics.yml
- docs/_data/table/en/worker-metrics.yml
- docs/_data/table/master-metrics.csv
- docs/_data/table/worker-metrics.csv
Add some metrics  of master RPC, worker RPC/block serialized threads and add metrics docs of worker CacheManager threads
Metrics for monitor system
no
> Add some metrics of threads and docs of worker CacheManager threads

- docs/en/contributor/Contributor-Tools.md
Removes bad example that doesn't exist.
Yes, tweaks `Contributor-Tools.md`
> [DOCFIX] Remove invalid example from Contributor-Tools

- core/server/worker/src/main/java/alluxio/worker/block/BlockLock.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockLockManager.java
- core/server/worker/src/main/java/alluxio/worker/block/LocalBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockLockManagerTest.java
Use try-resource lock for block
Reduce the risks of lock leaking
no
> Use try-resource lock for block

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterFsOptsTest.java
Add permission check for exists method.
Fix #16195
NA
> Add permission check for exists method

- docs/en/operation/User-CLI.md
add newline to end of recently modified doc page
> [DOCFIX] Add missing newline in User-CLI doc

- integration/fuse/src/test/java/alluxio/fuse/AlluxioJniFuseFileSystemTest.java
Fix AlluxioJniFuseFileSystemTest chown related cases
- chown
- chownWithoutValidGid
- chownWithoutValidUid
These test cases failed after merging #16177 and #16146, as the CI of them were running without the changes of each other.
No
> Fix AlluxioJniFuseFileSystemTest chown related cases

- core/common/src/main/java/alluxio/extensions/ExtensionFactoryRegistry.java
Fixes https://github.com/Alluxio/alluxio/issues/16001
Save the registered factories and look up from this collection first.
Reduce the memory consumption of metaspace and avoid master crash due to OutOfMemory of metaspace.
No.
> Save the registered factories and look up from this collection first

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Fix the compile error
Build on master is failing
no
> Fix the compile error in S3RestServiceHandler

- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- core/common/src/test/java/alluxio/underfs/MockObjectUnderFileSystem.java
- core/common/src/test/java/alluxio/underfs/ObjectUnderFileSystemTest.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AInputStream.java
> Filter exception that need to be retried in ObjectUnderFileSystem

- docs/en/operation/Admin-CLI.md
Make the description more precise for `updateConf` command.
Limited the support scope of `updateConf`.
N/A
> [DOCFIX] Update updateConf description in Admin-CLI.md

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/main/java/alluxio/master/file/MetadataSyncLockManager.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataConcurrentTest.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataMetricsTest.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTestBase.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- core/server/master/src/test/java/alluxio/master/file/MetadataSyncLockManagerTest.java
- core/transport/src/main/proto/proto.lock
- tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java
Cherry-pick #16241 to branch-2.8
> Merge #16241 to branch-2.8

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Cherry-pick https://github.com/Alluxio/alluxio/pull/16256 to branch-2.8
> Make cherry-pick #16256 to branch-2.8

- core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStore.java
Fix failures in mem page store when zero copy enabled
Worker crash when using mem page store
no
> Fix failures in mem page store when zero copy enabled

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
orig-pr: #16293
orig-commit: 7eba438
orig-commit-author: lucyge2022 <111789461+lucyge2022@users.noreply.github.com>
pr-link: Alluxio/alluxio#16293
change-id: cid-8937a75d2302429274c63df99f0d7e3995893615
> Port changes of [#16293] to branch-2.8

- core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
- core/server/common/src/main/java/alluxio/underfs/UfsManager.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
- core/server/master/src/main/java/alluxio/underfs/MasterUfsManager.java
In place of https://github.com/Alluxio/alluxio/pull/16013
Avoid reusing an used mount point ID
NA
> Avoid duplicated mount point ID

- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncTest.java
Revert an accidental change to a test.
> Revert change to FileSystemMasterSyncTest

- core/client/fs/src/main/java/alluxio/client/block/options/GetWorkerReportOptions.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
- core/server/master/src/test/java/alluxio/master/block/meta/MasterWorkerInfoTest.java
Add missing lock in https://github.com/Alluxio/alluxio/pull/14126#discussion_r718334076 and refactored some locking logic for `MasterWorkerInfo`.
Add the missing read lock to ensure the data consistency.
NA
> Add missing lock in DefaultBlockMaster.extractWorkerInfo

- bin/alluxio-monitor.sh
- bin/alluxio-start.sh
- bin/alluxio-stop.sh
- bin/launch-process
Split strings in scripts so that conflicts with EE version are easier to avoid
> Split strings in scripts to make them easier to modify

- core/common/src/main/java/alluxio/conf/path/TrieNode.java
- core/common/src/test/java/alluxio/conf/path/TrieNodeTest.java
Add additional trie node functionality.
- Store a typed value with each node
- A function to search an exact path
- A function to get the children of a path
Additional functionality for new features.
No
> Add additional trie node functionality

- core/common/src/main/java/alluxio/grpc/GrpcUtils.java
- core/common/src/main/java/alluxio/util/ConfigurationUtils.java
- core/common/src/main/java/alluxio/util/io/PathUtils.java
- core/common/src/test/java/alluxio/grpc/GrpcUtilsTest.java
- core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
- core/server/master/src/main/java/alluxio/master/file/meta/options/MountInfo.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncTest.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTestBase.java
- core/server/master/src/test/java/alluxio/master/file/meta/options/MountInfoTest.java
- minicluster/src/main/java/alluxio/multi/process/ExternalProcess.java
Adds basic utils functionality.
> Update test utils

- core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystemCache.java
- core/client/fs/src/main/java/alluxio/client/file/MetadataCachingFileSystem.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioFileStatus.java
- integration/fuse/src/test/java/alluxio/fuse/auth/AbstractAuthPolicyTest.java
optimize getFileBlockLocations performance.
reduce a useless getStatus RPC when get the file block locations.
> Optimize getFileBlockLocations performance

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJnrFuseFileSystem.java
PR 3 of Alluxio FUSE SDK https://github.com/Alluxio/alluxio/pull/16284
Fix passing the FUSE mount options and refactor path cache loader.
Fix the FUSE mount option issues.
NA
> Fix fuse mount options and refactor path cache loader

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Fix typo for the newly added property key of paging store
no
> Fix typo for the property key of paging store

- tests/src/test/java/alluxio/client/fs/io/FileInStreamIntegrationTest.java
Addresses https://github.com/Alluxio/alluxio/pull/16322#issuecomment-1280404485
> Make async cache check stable

- core/common/src/main/java/alluxio/util/URIUtils.java
- docs/en/api/FS-API.md
- docs/en/api/POSIX-API.md
- docs/en/api/S3-API.md
- docs/en/operation/Troubleshooting.md
orig-pr: Alluxio/alluxio#16335
orig-commit: Alluxio/alluxio@1ea5a840ac8f45d7b593882744dc148481b9ddce
> Fix cherry pick of s3-specia-char to branch-2.8

- integration/docker/entrypoint.sh
PR 7 of Alluxio FUSE SDK https://github.com/Alluxio/alluxio/pull/16284
This PR contains the logic to create a Alluxio Fuse SDK docker image
This PR relies on https://github.com/Alluxio/alluxio/pull/16346
Support creating a Alluxio Fuse docker image
NA
> Support creating Alluxio FUSE SDK docker image

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
> Refactor for easier format

- docs/en/core-services/Caching.md
Add docs for paging store
Add docs for paging store
no
> [DOCFIX] Add docs for paging store

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/server/master/src/main/java/alluxio/master/throttle/MetricsMonitorUtils.java
- docs/en/reference/Metrics-List.md
Modify metrics name to avoid docGen failure
Modify metrics name to avoid docGen failure
NA
> Modify metrics name to avoid docGen failure

- bin/alluxio
- core/common/src/main/java/alluxio/conf/PropertyKey.java
Remove Configuration and CLI of Alluxio table
> Remove Configuration and CLI of Alluxio table

- core/server/common/src/main/java/alluxio/util/FeatureUtils.java
- core/server/master/src/main/java/alluxio/master/meta/UpdateCheck.java
- core/server/master/src/main/java/alluxio/master/meta/UpdateChecker.java
- core/server/master/src/test/java/alluxio/master/meta/UpdateCheckTest.java
> Update Update Check

- core/common/src/main/java/alluxio/util/io/BufferUtils.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/MultipartUploadCleaner.java
fixed double checked locking
missing `volatile`
about Double Check
https://codeql.github.com/codeql-query-help/java/java-unsafe-double-checked-locking/
NO
> Fix double checked locking in S3 uploader

- docs/_data/table/cn/user-configuration.yml
> [DOCFIX] Fix wrong property name reference load to load.type

- docs/en/api/POSIX-API.md
Update the POSIX API doc cache tuning section
make doc easy to understand by end-user
doc
> [DOCFIX] Update the posix api doc cache tuning

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
- integration/kubernetes/helm-chart/alluxio/templates/master/service.yaml
- integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml
1. Improve the indentation in worker daemonset template
2. Make the port numbers in master service follow respective parameters in values.yaml
> Improve Helm chart

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ErrorCode.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Implement HeadBucket call
Users using probing which shoots headbucket gets incorrectly routed to getbucket, it needs to have correct headbucket implentation.
User will get correct headbucket behavior with correct responding time
> Implement S3 headbucket API

- core/common/src/main/java/alluxio/exception/runtime/AlreadyExistsRuntimeException.java
- core/common/src/main/java/alluxio/exception/runtime/CancelledRuntimeException.java
- core/common/src/main/java/alluxio/exception/runtime/FailedPreconditionRuntimeException.java
- core/common/src/main/java/alluxio/exception/runtime/InvalidArgumentRuntimeException.java
- core/common/src/main/java/alluxio/exception/runtime/UnavailableRuntimeException.java
- core/common/src/main/java/alluxio/exception/runtime/UnimplementedRuntimeException.java
- integration/fuse/src/main/java/alluxio/cli/FuseShell.java
- integration/fuse/src/main/java/alluxio/cli/command/metadatacache/AbstractMetadataCacheSubCommand.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/fuse/FuseSignalHandler.java
- integration/fuse/src/main/java/alluxio/fuse/FuseUmountable.java
- integration/fuse/src/main/java/alluxio/fuse/auth/AuthPolicyFactory.java
- integration/fuse/src/main/java/alluxio/fuse/auth/CustomAuthPolicy.java
- integration/fuse/src/main/java/alluxio/fuse/auth/LaunchUserGroupAuthPolicy.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
- integration/fuse/src/test/java/alluxio/fuse/cli/FuseShellTest.java
- tests/src/test/java/alluxio/client/fuse/file/FuseFileInOrOutStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/file/FuseFileInStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/file/FuseFileOutStreamIntegrationTest.java
Refactor Fuse to use AlluxioRuntimeException.
Code cleanness
NA
> Refactor Fuse to use AlluxioRuntimeException

- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerOptions.java
Fix client prop key being used in worker page store.
> [SMALLFIX] Fix worker page store property key

- core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStore.java
- core/client/fs/src/test/java/alluxio/client/file/cache/store/MemoryPageStoreTest.java
Implemtn byte array pool for mem local cache
Prevent GC and oom issue
> Implement Byte array pool

- core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
> Update comments in InodeTreePersistentState

- docs/_data/table/en/user-configuration.yml
- docs/_data/table/en/worker-configuration.yml
> [SMALLFIX] Fix typos in worker-configuration.yml

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Tiny refactor to make code merge easier.
> Refactor single line position

- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
Change update config non-dynamic property to warn level to warn user.
Without this PR, user cannot get warn and reason of update failure.
No
> Change update config failure log to warn level

- job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java
Resolve #16405 
It replaces the list with set for finding worker without block function which is being called in for loop.
It improves the search time from O(N) to O(1).
No
> Improve search for finding worker without block

- docs/en/deploy/Running-Alluxio-On-Docker.md
- docs/en/kubernetes/Running-Alluxio-On-Kubernetes.md
Solves https://github.com/Alluxio/alluxio/issues/13137
pr-link: Alluxio/alluxio#16366
change-id: cid-9ba3367ee9eef15001965f73697110049cc83e27
> [DOCFIX] Port changes of [#3849] to enterprise-2.9

- docs/en/deploy/Running-Alluxio-On-Docker.md
- docs/en/kubernetes/Running-Alluxio-On-Kubernetes.md
Solves https://github.com/Alluxio/alluxio/issues/13137
pr-link: Alluxio/alluxio#16366
change-id: cid-9ba3367ee9eef15001965f73697110049cc83e27
> [DOCFIX] Port changes of [#16366] to branch-2.9

- job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java
Resolve https://github.com/Alluxio/alluxio/issues/16405
It replaces the list with set for finding worker without block function which is being called in for loop.
It improves the search time from O(N) to O(1).
No
> Improve search of finding worker without block

- docs/en/operation/Metrics-System.md
Add job service metrics to doc
na
na
> [DOCFIX] Add job service metrics to doc

- stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
Set write type when creating files in stress worker bench
> Support specify write type for StressWorkerBench

- docs/en/api/POSIX-API.md
Add the POSIX user group policy doc
Clear instruction of Alluxio POSIX API user group policy
NA
> [DOCFIX] Add the POSIX user group policy doc

- underfs/ozone/pom.xml
Tested in [ozone-1.2.1](https://github.com/apache/ozone/releases/tag/ozone-1.2.1) and ozone master branch(1.3.0-SNAPSHOT)
Mount ozone with the following exception. 
```
java.lang.IllegalArgumentException: Unable to create an UnderFileSystem instance for path: o3fs://testbuk.testvol/
at alluxio.underfs.UnderFileSystem$Factory.create(UnderFileSystem.java:120)
at alluxio.underfs.AbstractUfsManager.getOrAdd(AbstractUfsManager.java:136)
at alluxio.underfs.AbstractUfsManager.lambda$addMount$2(AbstractUfsManager.java:203)
at alluxio.underfs.UfsManager$UfsClient.acquireUfsResource(UfsManager.java:61)
at alluxio.master.file.DefaultFileSystemMaster.prepareForMount(DefaultFileSystemMaster.java:3164)
at alluxio.master.file.DefaultFileSystemMaster.mountInternal(DefaultFileSystemMaster.java:3327)
at …
```
> Add hadoop dependencies into ozone ufs connector

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataMetricsTest.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTestBase.java
Add UTs on metadata sync related metrics:
1. MASTER_METADATA_SYNC_UFS_MOUNT
2. MASTER_METADATA_SYNC_EXECUTOR
3. MASTER_METADATA_SYNC_PREFETCH_EXECUTOR
> Add UT on metadata sync

- docs/en/operation/Journal.md
Add note in doc about automatic backup upon journal corruption.
> [DOCFIX] Add note in doc about automatic backup upon journal corruption

- docs/en/operation/Journal.md
- docs/en/operation/User-CLI.md
- docs/en/ufs/HDFS.md
Add missing doc updates from the PRs below:
https://github.com/Alluxio/alluxio/pull/15645
https://github.com/Alluxio/alluxio/pull/15733
https://github.com/Alluxio/alluxio/pull/16018
https://github.com/Alluxio/alluxio/pull/16151
https://github.com/Alluxio/alluxio/pull/16389
This should go to branch-2.9 as well because those commits are in 2.9
> [DOCFIX] Add missing doc changes

- docs/en/administration/StressBench.md
Add posix api option to clientIO stressbench doc
> [DOCFIX] Add fuse to clientIO stressbench doc

- docs/en/deploy/Running-Alluxio-On-Docker.md
Add doc about `alluxio/alluxio-jdk11` image.
> [DOCFIX] Add java11 image doc

- docs/en/administration/Troubleshooting.md
- docs/en/deploy/Running-Alluxio-On-Docker.md
> [DOCFIX] Update Troubleshooting and Running on Docker pages

- docs/en/kubernetes/Running-Alluxio-On-Kubernetes.md
Rename the dropdown name of kubernetes doc.
> [DOCFIX] Rename k8s doc

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
Add macFUSE check for MacOS.
The method isFuseInstalled can not check macFUSE.
no.
> Add macFUSE check for MacOS

- core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
Merge the upload part files in the requested order.
The checksum of the file uploaded by multipart is different from that of the original file.
No.
> Sort part files for uploading

- core/common/src/main/java/alluxio/check/UpdateCheck.java
- core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
- core/common/src/test/java/alluxio/check/UpdateCheckTest.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/fuse/FuseConstants.java
- integration/fuse/src/main/java/alluxio/fuse/StackMain.java
- integration/fuse/src/main/java/alluxio/fuse/meta/UpdateChecker.java
- integration/fuse/src/main/java/alluxio/fuse/options/FuseOptions.java
- integration/fuse/src/test/java/alluxio/fuse/meta/UpdateCheckerTest.java
- integration/fuse/src/test/java/alluxio/fuse/ufs/AbstractFuseFileSystemTest.java
- integration/jnifuse/fs/src/main/java/alluxio/jnifuse/AbstractFuseFileSystem.java
- tests/src/test/java/alluxio/client/fuse/JNIFuseIntegrationTest.java
> Add FUSE SDK update check

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RangeSpec.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Add Content-Range header for getObject.
Fix #16331.
No.
> Add Content-Range header for getObject

- core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
Remove the restriction of UFS for SDK.
To meet the business requirements.
No, it doesn't.
> Remove the restriction of UFS for SDK

- core/common/src/main/java/alluxio/conf/PropertyKey.java
> Fix code style

- core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
Fix FUSE update check error
Exception in thread "main" java.lang.NullPointerException
at alluxio.util.CommonUtils.createNewClassInstance(CommonUtils.java:286)
at alluxio.heartbeat.HeartbeatThread.<init>(HeartbeatThread.java:77)
at alluxio.heartbeat.HeartbeatThread.<init>(HeartbeatThread.java:97)
at alluxio.fuse.AlluxioFuse.main(AlluxioFuse.java:182)
NA
> Fix FUSE update check

- docs/_data/table/s3-api-supported-actions.csv
- docs/en/api/S3-API.md
Add headBucket for S3 API documentation.
> [DOCFIX] Add headBucket for S3 API documentation

- core/server/master/src/main/resources/META-INF/services/alluxio.master.MasterFactory
Fix the master service order
Fix the master service order
NA
> Fix the master service order

- dev/scripts/src/alluxio.org/build-distribution/cmd/common.go
- underfs/cosn/pom.xml
- underfs/cosn/src/main/java-templates/alluxio/CosNUfsConstants.java
- underfs/cosn/src/main/java-templates/alluxio/CosnUfsConstants.java
- underfs/cosn/src/main/java/alluxio/underfs/cosn/CosNUnderFileSystemFactory.java
- underfs/cosn/src/test/java/alluxio/underfs/cosn/CosNUnderFileSystemFactoryTest.java
Based on this pull request, we can support the existence of multiple versions of cosn jar in the tarball.
We want to support multiple versions of cosn in the Alluxio tarball, which requires different lib jars
No
> Support multiple versions of cosn lib jars in alluxio tarball

- integration/docker/entrypoint.sh
Fix FUSE SDK entrypoint.sh
fuse-sdk is an internal term, not easy to understand by users
Yeah. docker run ...alluxio/alluxio-fuse:2.9.1 fuse-sdk <ufs_address> <mount_point> to alluxio/alluxio-fuse:2.9.1 mount <ufs_address> <mount_point>
> Fix FUSE SDK entrypoint.sh

- docs/en/operation/Admin-CLI.md
Add documentation for a new feature that recursively removes path-specific configurations.
The new feature was implemented in #16280.
Doc fix.
> [DOCFIX] Add doc for recursively remove path config

- shell/src/main/java/alluxio/cli/fs/command/AbstractDistributedJobCommand.java
- shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
- shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
Fix nullpointerException in distributed cmd
bug fix
na
> Fix nullpointerException in distributed cmd

- docs/en/kubernetes/Metrics-On-Kubernetes.md
- docs/en/operation/Metrics-System.md
Add how to get JSON metrics and Prometheus metrics on k8s.
> [DOCFIX] Add metrics doc on k8s

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Add property key to enable dora client read location polic
enable dora client read location polic
addition  of property keys
> Add property key to enable dora client read location policy

- docs/cn/overview/FAQ.md
The purpose of this pr is to try to fix some comments that were out of place in FAQ.md and make it more complete.
This needs to be modified, otherwise it will affect the user's use.
The purpose of this pr is to make it easier for users to use alluxio.
> [DOCFIX]Modify some inappropriate descriptions in FAQ.md

- core/server/common/src/main/java/alluxio/master/MasterProcess.java
The purpose of this pr is to make MasterProcess look easier to understand, adding some @links.
Our goal is to make MasterProcess look easier to understand.
3. webui
> [DOCFIX] Improve annotations in MasterProcess and add some @links

- core/common/src/main/java/alluxio/worker/DoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockWorkerFactory.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedFileReader.java
- core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/FileReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
Implement the skeleton of dora work
no
> Implement the skeleton of dora worker

- core/common/src/main/java/alluxio/collections/Pair.java
- stress/common/src/main/java/alluxio/stress/master/MultiOperationMasterBenchSummary.java
- stress/common/src/main/java/alluxio/stress/master/MultiOperationMasterBenchTaskResult.java
- stress/shell/src/main/java/alluxio/stress/cli/MultiOperationStressMasterBench.java
Figured out some issues during tests so fixed them.
> Fix MultiOperation Stress Master Bench

- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsFileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/ufs/UfsFileInStreamTest.java
- core/common/src/main/java/alluxio/exception/runtime/UnknownRuntimeException.java
- integration/fuse/src/test/java/alluxio/fuse/ufs/stream/InStreamTest.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AInputStream.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
This reverts commit 8552b5846c45a296c09c440c3fbb0f63a8a12aba.
3. webui
> Revert "Support FUSE UFS seek"

- core/server/worker/src/test/java/alluxio/worker/block/UfsIoManagerTest.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileOutputStream.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
> Fix and improve dora test

- job/server/src/main/java/alluxio/master/job/JobMaster.java
Fix ip is null in JobMaster audit log.
> Fix ip is null in audit log

- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
Remove useless field in AbstractFileSystem.
Remove useless field in AbstractFileSystem.
> [SMALLFIX] Remove useless field in AbstractFileSystem

- conf/alluxio-env.sh.template
- docs/_data/table/en/env_vars.yml
Add missing parameter to env: ALLUXIO_SECONDARY_MASTER_ATTACH_OPTS.
Complete documentation.
No.
> Add missing parameter to env: ALLUXIO_SECONDARY_MASTER_ATTACH_OPTS

- core/server/common/pom.xml
> Bump ratis version to 2.4.1

- pom.xml
Upgrade to resolve a resource consumption problem in
https://cwe.mitre.org/data/definitions/400.html
> Upgrade protobuf to 3.19.6

- core/server/common/src/main/java/alluxio/RpcUtils.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/journal/DefaultJournalMaster.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java
- table/server/master/src/main/java/alluxio/master/table/DefaultTableMaster.java
In the debug log, client IP will be logged
> Support log source ip to rpc debug log

- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
In the implementation classes associated with BlockStore, some comments are missing. The purpose of this pr is to complement them.
Details: https://github.com/Alluxio/alluxio/issues/16648
Because some important comments are missing.
For the user, there is no impact.
> [DOCFIX] Add some missing comments related to BlockStore

- dev/intellij/runConfigurations/AlluxioFuse.xml
> Fix fuse intellij wrong option

- microbench/src/main/java/alluxio/inode/RocksBenchBase.java
The original checking is wrong.
There was a bug. This condition checking just wrong.
> Correct checking the mIsDirectory condition

- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/master/src/test/java/alluxio/master/journal/raft/RaftJournalSystemMetricsTest.java
Fix Master.JournalSequenceNumber metrics and add RaftJournalSystemMetricsTest.
Fix Master.JournalSequenceNumber metrics.
Test Metrics registered in `RaftJournalSystem#initServer()`.
No.
> Fix Master.JournalSequenceNumber metrics in RaftJournalSystem

- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
Fix typo in TieredBlockStore comment.
> [SMALLFIX] Fix typo in TieredBlockStore comment

- core/common/src/main/java/alluxio/util/io/FileUtils.java
> Remove dead code in FileUtils

- core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSyncHelper.java
- stress/shell/src/main/java/alluxio/stress/cli/RegisterWorkerBench.java
- stress/shell/src/main/java/alluxio/stress/cli/StreamRegisterWorkerBench.java
Refactor and extract an abstract class AbstractBlockMasterSync from the current BlockMasterSync.
In the future, we might want to let the worker heartbeat to standby masters. This refactor makes it easier to extend the base BlockMasterSync.
N/A
> Refactor block master sync

- core/common/src/main/java/alluxio/wire/AlluxioMasterInfo.java
- core/common/src/main/java/alluxio/wire/AlluxioWorkerInfo.java
- core/common/src/main/java/alluxio/wire/MasterWebUIOverview.java
- core/common/src/main/java/alluxio/wire/WorkerWebUIOverview.java
- core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
- webui/master/src/containers/pages/Overview/Overview.tsx
- webui/master/src/containers/pages/Overview/__snapshots__/Overview.test.tsx.snap
- webui/master/src/store/overview/reducer.tsx
- webui/master/src/store/overview/types.tsx
- webui/worker/src/containers/pages/Overview/Overview.tsx
- webui/worker/src/containers/pages/Overview/__snapshots__/Overview.test.tsx.snap
- webui/worker/src/store/overview/reducer.tsx
- webui/worker/src/store/overview/types.tsx
Support display revision in webui.
> Support display revision in webui

- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/common/src/main/java/alluxio/concurrent/jsr/ForkJoinTask.java
- core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- core/common/src/main/java/alluxio/util/CommonUtils.java
- core/common/src/main/java/alluxio/util/ObjectSizeCalculator.java
- core/server/common/src/main/java/alluxio/master/transport/Listeners.java
- core/server/master/src/main/java/alluxio/master/file/UfsSyncChecker.java
- integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemCommonOperations.java
- shell/src/main/java/alluxio/cli/bundler/CollectInfo.java
- stress/shell/src/main/java/alluxio/stress/cli/MasterBatchTask.java
- tests/src/test/java/alluxio/client/fs/concurrent/ConcurrentFileSystemMasterLoadMetadataIntegrationTest.java
- underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
- underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Replace pre-sized array.
pre-sized array is not recommended in HotSpot based JVMs.
https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_new_reflective_array
> Replace pre-sized array

- core/transport/src/main/proto/proto.lock
Add mission proto lock content.
#16578 Modified the proto file but not the `proto.lock` file.
> Add missing proto lock content

- docs/cn/compute/Trino.md
Update cn version of Trino doc.
There is no corresponding Chinese documentation for Trino.
More Chinese users can access Alluxio documentation more easily.
> [DOCFIX] Update cn version of Trino doc

- core/common/pom.xml
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/grpc/GrpcServerBuilder.java
- pom.xml
Add grpc reflection to make the grpc tools such as grpcui and grpcurl send request to alluxio server easier.
N/A
> Add grpc reflection

- docs/cn/compute/Presto-Iceberg.md
Update cn version of Presto-Iceberg doc.
There is no corresponding Chinese documentation for Presto-Iceberg.
More Chinese users can access Alluxio documentation more easily.
> [DOCFIX] Update cn version of Presto-Iceberg doc

- underfs/abfs/src/main/java/alluxio/underfs/abfs/AbfsUnderFileSystem.java
when use managed identity, it has a typo error
if not correct, managed identity will auth failed
no
> Fix managed identity typo error

- docs/cn/ufs/Azure-Data-Lake.md
[DOCFIX] Update cn version of Azure-Data-Lake doc
The Chinese ufs/Azure-Data-Lake doc has been created.
> [DOCFIX] Update cn version of Azure-Data-Lake doc

- docs/cn/overview/Use-Cases.md
[DOCFIX] Update cn version of Use-Cases doc
The Chinese overview/Use-Cases doc is not updated with the latest changes,
> [DOCFIX] Translate use cases

- core/server/worker/src/main/java/alluxio/worker/block/BlockHeartbeatReporter.java
In BlockHeartbeatReporter, there are some incorrect comments. The purpose of this pr is to fix them.
Fix them will make the document look cleaner.
For user, there is no impact.
> Fix some incorrect comments in BlockHeartbeatReporter

- table/server/master/src/main/java/alluxio/master/table/DefaultTableMaster.java
The TableMaster does not have anything that needs to depend on the FileSystemMaster, therefore remove the depdency definition
No.
> Remove TableMaster dependency on FileSystemMaster

- bin/alluxio-monitor.sh
- conf/alluxio-env.sh.template
1. Remove master/worker java opts from monitor java opts;
2. Add default value for monitor java opts.
https://github.com/Alluxio/alluxio/issues/16657
https://github.com/Alluxio/alluxio/issues/10958
https://github.com/Alluxio/alluxio/issues/15168
no
> Remove master/worker java opts from monitor java opts

- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
a improvement may help or may not help
https://github.com/Alluxio/alluxio/issues/16703
> Improve LocalCacheManagerTest

- core/server/master/src/test/java/alluxio/master/journal/JournalContextTest.java
- core/server/master/src/test/java/alluxio/master/journal/JournalTestUtils.java
- core/server/master/src/test/java/alluxio/master/journal/raft/RaftJournalSystemMetricsTest.java
Fixes https://github.com/Alluxio/alluxio/issues/16722
This is done by assigning at open port for the journal for each test instead of using static ports.
> Fix journal ports in use for unit tests

- docs/cn/overview/JobService.md
Update cn version of Job Service doc.
The Chinese overview/Job Service document is not updated with the latest changes,
> [DOCFIX] Update cn version of Job Service doc

- integration/kubernetes/helm-chart/monitor/README.md
Trivial housekeeping change to add missing newline to README file
Add missing newline to end of README file
Housekeeping
No
3. webui
> [DOCFIX] Add missing newline to README file

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
- core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
- core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheFileInStream.java
- core/client/fs/src/main/java/alluxio/client/file/dora/WorkerLocationPolicy.java
- core/client/fs/src/main/java/alluxio/client/file/options/FileSystemOptions.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/worker/src/main/resources/META-INF/services/alluxio.worker.WorkerFactory
- tests/src/test/java/alluxio/client/fs/io/DoraReadIntegrationTest.java
- tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
Dora client side affinity
skip grpc call of the get block location from master
new configruations
> Implement Dora client side affinity

- docs/cn/overview/JobService.md
Trivial housekeeping change to add missing newline to doc file
Add missing newline to end of doc file
Housekeeping
No
3. webui
> [DOCFIX] Add newline to end of doc file

- docs/en/operation/User-CLI.md
> [DOCFIX] Add doc for load v2

- shell/src/main/java/alluxio/cli/fs/command/FreeWorkerCommand.java
Formatted output
Better output readability
NA.
> Fix typo issue of FreeWorkerCommand

- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
Remove duplicate `getPort()` call.
The result of `getPort()` has been recorded and can be used directly
without calling this function again.
No.
> [SMALLFIX] Remove duplicate function call

- bin/alluxio
- core/common/src/main/java/alluxio/conf/PropertyKey.java
Restore table command with deprecated status
Revert of https://github.com/Alluxio/alluxio/pull/16348
N/A
N/A
> Restore table command with deprecated status

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
A temporary solution for metadata caching on worker
reduce the api call to ufs
add properties
> Implement Worker metadata caching

- core/server/master/src/main/java/alluxio/master/service/rpc/RpcServerService.java
- core/server/master/src/test/java/alluxio/master/service/rpc/RpcServerServiceTest.java
- core/server/master/src/test/java/alluxio/master/service/rpc/RpcServerServiceTestBase.java
Did some refactoring to improve the code extensibility
We want to create more grpc service in the future and this refactoring is a intermediate step. 
N/A
> Refactor rpc server service

- microbench/src/main/java/alluxio/BaseFileStructure.java
- microbench/src/main/java/alluxio/fsmaster/FileSystemMasterBench.java
- microbench/src/main/java/alluxio/inode/InodeBenchRead.java
- microbench/src/main/java/alluxio/inode/InodeBenchWrite.java
- microbench/src/main/java/alluxio/inode/RocksBenchRead.java
- microbench/src/main/java/alluxio/inode/RocksBenchReadWrite.java
- microbench/src/main/java/alluxio/inode/RocksBenchWrite.java
- microbench/src/main/java/alluxio/invalidation/cache/InvalidationSyncCacheBench.java
Refactor Microbenchmark `@Param` options to focus only on the most relevant benchmarks.
> Refactor Microbench options

- core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- integration/fuse/src/test/java/alluxio/fuse/auth/AbstractAuthPolicyTest.java
Import class type before code class
4. webui
No
> [SMALLFIX] Import class type before code class

- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTestBase.java
Refactor block worker and its test
so that this class can be inherited more easily 
N/A
> Refactor DefaultBlockWorker and test

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- job/server/src/main/java/alluxio/master/job/tracker/CmdJobTracker.java
- job/server/src/main/java/alluxio/master/job/tracker/CmdRunAttempt.java
port job service related fixes from master
> Job service fixes

- core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java
- core/client/fs/src/test/java/alluxio/client/file/FileSystemTestBase.java
Refactor BaseFileSystemMaster and its test, a test base is extracted out
So that the class can be inherited easily
N/A
> Refactor BaseFileSystemMaster

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/master/selectionpolicy/MasterSelectionPolicy.java
- core/common/src/main/java/alluxio/master/selectionpolicy/SelectionPolicyAnyMaster.java
- core/common/src/main/java/alluxio/master/selectionpolicy/SelectionPolicyAnyStandbyMaster.java
- core/common/src/main/java/alluxio/master/selectionpolicy/SelectionPolicyPrimaryMaster.java
- core/common/src/main/java/alluxio/master/selectionpolicy/SelectionPolicySpecifiedMaster.java
- core/common/src/main/java/alluxio/resource/NoopCloseable.java
- core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
- core/server/common/src/main/java/alluxio/master/AbstractMaster.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalServiceHandler.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/master/src/main/java/alluxio/master/CoreMaster.java
- core/server/master/src/main/java/alluxio/master/CoreMasterContext.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeLockManager.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
- core/server/master/src/main/java/alluxio/master/file/meta/UfsSyncPathCache.java
- core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
- core/server/master/src/test/java/alluxio/master/journal/NoopRaftJournalSystem.java
- core/server/master/src/test/java/alluxio/master/journal/raft/SnapshotReplicationManagerTest.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockHeartbeatReporter.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSyncHelper.java
- shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
- shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
Functional:
1. Make capacity command load configurations before execution
Non functional:
1. Add MasterSelectionPolicy.Type
2. Add NoopCloseable
3. Add LOG to some classes, update private to protected to some class member variables so that the class can be overrode 
4. Update RaftJournalServiceHandler constructor to take an additional RaftJournalSystem as an input 
5. Add primary selectory to master context 
6. Extract updateAccessTime in FileSystemMaster
7. Let notifySyncedPath return SyncState
N/A
> Add some small refactoring changes

- core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
- core/common/src/test/java/alluxio/resource/DynamicResourcePoolTest.java
make fifo/lifo a enum type so that we can suport more strategies 
N/A
> Refactor dynamic resource pool selection type

- core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
If cache already exists in Alluxio, when try to cache the same block, don't increase the metric worker.cacheBlockSize.
The metric Worker.CacheBlocksSize is not correct. If data already exists in Alluxio, caching the same block again will increate metric Worker.cacheBlockSize.
no
> Fix metric worker.cacheBlockSize increases when cache already existed

- docs/en/contributor/Contributor-Getting-Started.md
Point to new contributor tasks since old one is abandoned.
3. webui
> [DOCFIX] Update new contributor doc

- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3ALowLevelOutputStream.java
> Fix s3 client

- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3ALowLevelOutputStream.java
> Make s3 client not final

- core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
Fix debug log in FileSystemContext#reinit().
The argument is wrong.
No.
> Fix debug log in FileSystemContext#reinit()

- docs/_data/table/cn/client-metrics.yml
Some wording in cn client-metric table
Clarified some metric descriptions.
No
> [DOCFIX] Fix some cn client-metric table wording

- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/PageInfo.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStoreDir.java
Implement local cache invalidate method 
support ttl
no
> Implement local cache invalidate method

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/rocks/RocksStore.java
- core/server/common/src/test/java/alluxio/rocks/RocksStoreTest.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockMetaStore.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaStore.java
- core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
- core/server/worker/src/test/java/alluxio/worker/dora/RocksDBDoraMetaStoreTest.java
- core/transport/src/main/proto/proto.lock
- core/transport/src/main/proto/proto/meta/dora_meta.proto
Signed-off-by: Huang Hua <huanghua78@msn.com>
Basic framework of metadata store for Dora
Dora needs to persist some file/dir metadata
A new PropertyKey "alluxio.dora.worker.meta.store.rocksdb.dir" is added.
> Add RocksDB metadata store for Dora

- dev/jenkins/Dockerfile-jdk17
Add dockerfile with java 17 base and java 8 added for compilation, mirroring the java 11 one
> Add maven build dockerfile with jdk17

- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- minicluster/src/main/java/alluxio/master/MultiMasterEmbeddedJournalLocalAlluxioCluster.java
Add embedded journal support for LocalAlluxioCluster in integration tests
To test some features that only works with embedded journals
N/A
> Add embedded journal support for LocalAlluxioCluster

- docs/cn/kubernetes/Spark-On-Kubernetes.md
Update cn version of Spark on Kubernetes doc.
There is no corresponding Chinese documentation for upgrade.
More Chinese users can access Alluxio documentation more easily.
> [DOCFIX] Update cn version of Spark on Kubernetes doc

- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Store File Metadata in persistent DoraMetaStore which is stored in RocksDB.
We want to have File Metadata cache in memory and on persistent storage.
This is to enable the persistent cache.
N/A
> Enable Dora metastore cache

- core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
> [SMALLFIX] Fix a few typos in comment

- core/client/fs/src/main/java/alluxio/client/block/BlockStoreClient.java
Fixes Alluxio/new-contributor-tasks#624
https://github.com/Alluxio/new-contributor-tasks/issues/624
> [SMALLFIX] Fix Alluxio/new-contributor-tasks#624

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
> Fix typo in S3Exception

- core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Cache directory status as well
only get directory status but no list directory
> Cache directory status in distributed cache

- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStoreDir.java
Support removeBlock for pagestore.
To remove metadata and data of blocks and pages on worker when free or delete a file.
N/A
> Support remove blocks on worker for pagestore when free/delete file

- docs/en/administration/StressBench.md
Fix the wrong option in stress bench doc
3. webui
> [DOCFIX] Fix the wrong option in stress bench doc

- core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
> Remove the restriction of UFS for local cache

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Change the default value of alluxio.worker.network.netty.file.transfer from MAPPED to TRANSFER as it has better performance.
> Change the netty default value for better performance

- docs/_config.yml
- docs/en/dora/Deploy-Alluxio-Cluster.md
- docs/en/dora/FUSE-SDK.md
- docs/en/dora/Overview.md
- docs/en/dora/PRESTO-SDK.md
> [DOCFIX] Add dora doc structure

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Support connecting FUSE SDK with original Alluxio cluster for testing.
integration/fuse/bin/alluxio-fuse mount ufs_path mount_point
ufs_path can be s3://bucket/path, or alluxio:///path
> Support FUSE SDK + Alluxio cluster for testing

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Many people do not use file access time. This PR provides an option to disable it.
To improve the performance 
N/A
> Add a property to disable file access time

- core/client/fs/src/main/java/alluxio/client/block/AllMastersWorkerInfo.java
- core/client/fs/src/main/java/alluxio/client/block/util/WorkerInfoUtil.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
- shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
- tests/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
> Enhance the capacity report to show worker registration info

- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- docs/cn/deploy/Running-Alluxio-On-a-HA-Cluster.md
- docs/en/deploy/Running-Alluxio-On-a-HA-Cluster.md
Correct docs about Ratis.
Embedded journal is introduced in #8219,
then Copycat is replaced by Ratis in #12181.
Some docs are not updated.
No.
> [DOCFIX] Correct docs about Ratis

- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
Update the Change Log and Chart for this change: https://github.com/Alluxio/alluxio/pull/16973
> Update helm chart ChangeLog and Chart

- underfs/web/pom.xml
> Fix jsoup CVE-2021-37714

- integration/kubernetes/operator/alluxio/README.md
> Update operator for README.md

- docs/cn/overview/Getting-Started.md
- docs/en/overview/Getting-Started.md
Some documentation has been modified to suggest better use of alluxio.
If JAVA_HOME is not set properly, you will encounter some errors when formatting.
Details: https://github.com/Alluxio/alluxio/issues/16949
3. webui
> [DOCFIX] Fix some errors occurred when formatting alluxio

- README.md
> [DOCFIX] Add OpenSSF Scorecard for README.md

- integration/kubernetes/operator/alluxio/Dockerfile
- integration/kubernetes/operator/alluxio/examples/demo-1/docker/Dockerfile
- integration/kubernetes/operator/alluxio/go.mod
> Bump go from 1.13 to 1.18

- docs/en/dora/PRESTO-SDK.md
Add doc about Presto SDK for Dora
> Add doc about Presto SDK for Dora

- pom.xml
> Fix jackson CVE-2022-42003

- tests/src/test/java/alluxio/server/block/RegisterStreamTestUtils.java
> [SMALLFIX] Add a missing mediumType in test mocking worker register

- core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
Add a metric to capture how many times Dora falls back to UFS when opening files.
N/A
N/A
> Add a metric to capture how many times Dora falls back to UFS

- underfs/cosn/pom.xml
Remove HdfsUnderFileSystemFactory from service loading in COSN UFS jar.
Avoid loading HdfsUnderFileSystemFactory from alluxio-underfs-cosn-*.jar.
No.
> Remove HdfsUnderFileSystemFactory from service loading in COSN UFS jar

- docs/en/compute/Tensorflow.md
- docs/resources/mnist_classification.py
Move the tensorflow script from personal github account to Alluxio.
> [DOCFIX] Update tensorflow script link

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Like https://github.com/Alluxio/alluxio/pull/16893 and https://github.com/Alluxio/alluxio/pull/16944,
Before blockinfo will use mountInfo, so it should not use mountInfo after set excludeMountInfo to true.
This purpose is also to improve rpc performance with HDFS client.
> Support getBlockInfo excluding mount-related info

- conf/log4j.properties
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
1. add multipart upload tests for correct part ordering
2. add log4j configs to show details such as filename/linenumber/threadid for better tracking
improve test coverage on large multipart upload corruption 
No
> Add test coverage on multipart upload

- core/server/proxy/src/main/java/alluxio/proxy/s3/signature/StringToSignProducer.java
Remove System.out.println.
This looks like the debug code forgot to delete.
> Remove System.out.println

- core/common/src/main/java/alluxio/job/CopyJobRequest.java
- core/server/common/src/main/java/alluxio/master/journal/JournalEntryAssociation.java
- core/server/common/src/test/java/alluxio/master/journal/JournalEntryAssociationTest.java
- core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
- core/server/master/src/main/java/alluxio/master/job/JobFactoryProducer.java
- core/server/master/src/main/java/alluxio/master/job/JournalCopyJobFactory.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- core/transport/src/main/proto/proto.lock
- core/transport/src/main/proto/proto/journal/job.proto
- core/transport/src/main/proto/proto/journal/journal.proto
Initial commit to add proto to support copy job. Please ignore CopyJob.java since it's incomplete.
So we can work on user-facing command and backbone in parallel
na
> Add request proto to add copy job

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Cache ListStatus() results on Worker. 
- Only caches a SINGLE list result for now.
- Cache will automatically expire after pre-defined timeout.
This cache will improve performance.
N/A
> Implement Dora list status cache

- core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
The purpose of the pr is removed in AlluxioMasterRestServiceHandler some unused code.
In some of AlluxioMasterRestServiceHandler unused code, should remove them.
1.   change in user-facing APIs
2.   addition or removal of property keys
3.   webui
> Remove some unused code in AlluxioMasterRestServiceHandler

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/util/proto/BlockLocationUtils.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
Finish the todo task after https://github.com/Alluxio/alluxio/pull/16953
> Add metric for cached block location

- job/server/src/main/java/alluxio/master/job/tracker/CmdJobTracker.java
Cherry pick of https://github.com/Alluxio/alluxio/pull/16780
https://github.com/Alluxio/new-contributor-tasks/issues/643 Fix logging to capture jobControlId
this will help in getting jobControlId in the logs, and will help in getting status information about the job
its just log level changes
pr-link: Alluxio/alluxio#16780
change-id: cid-551cf01210bb24d39239199adeb398201f67c184
> Fix logging to capture jobControlId

- docs/en/ufs/Azure-Data-Lake-Gen2.md
See Title
Needed to make broken link clickable.
Yes, will update docs page
> [DOCFIX] Fix Azure Data Lake Gen2 doc broken link

- core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
If an exception returned from Worker is known, client handles this
exception in an appropriate way.
For example, if NOT_FOUND exception is returned from Worker,
client will return empty list for ListStatus(), and will not send
ListStatus() to UFS again.
This will avoid doing unnecessary UFS operations and improve performance.
N/A
> Handle known exceptions on client

- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Starts RocksDBMetaStore in Worker constructor and check the result.
If exception happens, worker continues working without persistent MetaStore.
We cannot do RocksDB init in register() because when heartbeat timeouts, Worker
will do register again. 
N/A
> Start RocksDBMetaStore in Worker constructor

- integration/kubernetes/helm-chart/alluxio/values.yaml
> Add UseContainerSupport flag to default value.yaml of k8s helm chart

- core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
- tests/src/test/java/alluxio/server/ft/FileSystemMasterMergeJournalContextIntegrationTest.java
- tests/src/test/java/alluxio/server/ft/ZookeeperFailureIntegrationTest.java
- tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java
- tests/src/test/java/alluxio/server/ft/journal/MultiProcessCheckpointTest.java
- tests/src/test/java/alluxio/server/ft/journal/TriggeredCheckpointTest.java
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTestFaultTolerance.java
Implements exists() and setAttribute().
Ignore some journal/master related UTs which are not applicable in Dora.
Master/Journal services are not used in Dora.
N/A
> Enable Dora in UT

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/util/ThreadUtils.java
- core/server/common/src/main/java/alluxio/ProcessUtils.java
- core/server/common/src/main/java/alluxio/metrics/sink/MetricsServlet.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java
orig-pr: Alluxio/alluxio#17081
orig-commit: Alluxio/alluxio@7f335463bb1ef07186cbc302895fdb6631889e05
orig-commit-author: Jiacheng Liu <jiacheliu3@gmail.com>
pr-link: Alluxio/alluxio#17152
change-id: cid-5c9dcd5abb5c9731d3c20fe734d3f8d07f8fd167
3. webui
> Port changes of [#17081] to branch-2.7

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/util/ThreadUtils.java
- core/server/common/src/main/java/alluxio/ProcessUtils.java
- core/server/common/src/main/java/alluxio/metrics/sink/MetricsServlet.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java
orig-pr: Alluxio/alluxio#17152
orig-commit: Alluxio/alluxio@632c1c5c7854416b2e11e2212b41dcc7a59ae17a
orig-commit-author: Jiacheng Liu <jiacheliu3@gmail.com>
pr-link: Alluxio/alluxio#17166
change-id: cid-5c9dcd5abb5c9731d3c20fe734d3f8d07f8fd167
3. webui
> Port changes of [#17081] to branch-2.6

- core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
> Check filesystem for mount point

- shell/src/main/java/alluxio/cli/TestRunner.java
Fix the issue that TestRunner related parameters have no effect.
Fix the issue that TestRunner related parameters have no effect. #17066
no
> Fix the issue where runTest ignores arguments

- docs/en/operation/User-CLI.md
- shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
Add usage info for omit-mount-info.
Show usage for omit-mount-info parameter.
> Add usage info for omit-mount-info

- core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
Delete duplicate words.
3. webui
> [SMALLFIX] Delete duplicate words

- docs/cn/core-services/Caching.md
- docs/en/core-services/Caching.md
The purpose of this PR is to fix some bugs related to Caching.md
Fixing these errors will make Caching.md look cleaner.
3. webui
> [DOCFIX]Fix some bugs related to Caching.md

- docs/en/dora/Deploy-Alluxio-Cluster.md
- docs/en/dora/Deploy-Alluxio-Kubernetes.md
As we have (about to have) a proper helm chart for dora, update the doc to a more detailed page.
> [DOCFIX] Update deploy dora on k8s doc

- core/server/master/src/main/java/alluxio/master/meta/MetaMasterClientServiceHandler.java
- core/transport/src/main/proto/grpc/meta_master.proto
- core/transport/src/main/proto/proto.lock
- shell/src/main/java/alluxio/cli/fsadmin/report/SummaryCommand.java
- shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
./alluxio fsadmin report summary
edit: updated screenshot
> Show master versions in fsadmin report command

- core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
Fix the bug that PagedDoraWorker is created twice.
> Fix the bug that PagedDoraWorker is created twice

- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
- core/server/worker/src/test/java/alluxio/worker/dora/RocksDBDoraMetaStoreTest.java
- core/transport/src/main/proto/proto/meta/dora_meta.proto
Use Nano time for timestamp. This will be more accurate for metadata invalidation.
Fix issue of cache invalidation of metadata stored.
For better cache invalidation control and correctness.
N/A
> Fix of updating and invalidating metadata cache

- core/transport/pom.xml
Tentatively disable backwards-compatibility-check on proto
We are in the preparation of 300 release, backwards compatibility breaks may be introduced
No
> Disable backwards-compatibility-check on proto

- build/findbugs/findbugs-exclude.xml
- core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- integration/pom.xml
- pom.xml
- tests/src/test/java/alluxio/client/cli/fs/ConfigurationDocGeneratorTest.java
Remove YARN-related integration
YARN integration has been removed previously.
We are further removing the leftover
No
> Remove YARN related integration

- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java
- tests/src/test/java/alluxio/server/worker/WorkerAllMasterRegistrationTest.java
Remove one log entry which was accidentally brought in from testing
> [SMALLFIX] Remove unintended trace

- docs/en/dora/Deploy-Alluxio-Kubernetes.md
> [DOCFIX] Fix k8s doc in Dora

- core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
- core/server/common/src/main/java/alluxio/RpcUtils.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
- core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
- core/transport/src/main/proto/grpc/block_worker.proto
- core/transport/src/main/proto/proto.lock
Implement Load api in Dora
for load in dora
na
> Implement Load api in Dora

- docs/en/dora/Metadata.md
Added a document to explain metadata invalidation in Dora
Such a doc is needed for users/admins/developers.
N/A
> [DOCFIX] Add Docs for dora metadata invalidation

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/underfs/ObjectLowLevelOutputStream.java
- core/transport/src/main/proto/proto.lock
- underfs/obs/pom.xml
- underfs/obs/src/main/java/alluxio/underfs/obs/OBSLowLevelOutputStream.java
- underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
- underfs/obs/src/test/java/alluxio/underfs/obs/OBSLowLevelOutputStreamTest.java
- underfs/oss/pom.xml
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSLowLevelOutputStream.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystemFactory.java
- underfs/oss/src/main/java/alluxio/underfs/oss/StsOssClientProvider.java
- underfs/oss/src/test/java/alluxio/underfs/oss/OSSLowLevelOutputStreamTest.java
- underfs/oss/src/test/java/alluxio/underfs/oss/StsOssClientProviderTest.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3ALowLevelOutputStream.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
This is a PR to cherry-pick committed PR https://github.com/Alluxio/alluxio/pull/16481 and https://github.com/Alluxio/alluxio/pull/16122 into target branch dora.
> Support STS for OSS UFS and refactor Low Level Output Stream

- integration/docker/entrypoint.sh
CSI has been moved to k8s repo.
Logserver module has been deleted in 1806d92aef9fd612e70fb70b2f4b95736d1cf206
> Remove csi and logserver from entrypoint.sh

- core/client/fs/src/main/java/alluxio/client/block/options/GetWorkerReportOptions.java
- core/common/src/main/java/alluxio/grpc/GrpcUtils.java
- core/common/src/main/java/alluxio/util/webui/NodeInfo.java
- core/common/src/main/java/alluxio/wire/WorkerInfo.java
- core/common/src/test/java/alluxio/wire/WorkerInfoTest.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
- core/server/worker/src/main/java/alluxio/worker/block/RegisterStreamer.java
- core/transport/src/main/proto/grpc/block_master.proto
- core/transport/src/main/proto/proto.lock
- shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
- shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
- tests/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
- webui/master/src/constants/types/INodeInfo.tsx
- webui/master/src/containers/pages/Workers/Workers.tsx
- webui/master/src/containers/pages/Workers/__snapshots__/Workers.test.tsx.snap
Manual cherry pick of https://github.com/Alluxio/alluxio/pull/16521
> Port changes of [#16521] to branch-2.8

- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
- core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
- core/common/src/main/java/alluxio/underfs/options/GetFileStatusOptions.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- core/transport/src/main/proto/proto.lock
- tests/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java
- tests/src/test/java/alluxio/testutils/underfs/sleeping/SleepingUnderFileSystem.java
- underfs/cephfs/src/main/java/alluxio/underfs/cephfs/CephFSUnderFileSystem.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
- underfs/web/src/main/java/alluxio/underfs/web/WebUnderFileSystem.java
Support getting real content hash from hdfs
for data integrity while moving data between object store & HDFS
na
> Support getting real content hash from hdfs when using getFileStatus

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
- core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/job/AbstractJob.java
- core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
- core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
- core/server/master/src/main/java/alluxio/master/job/LoadJob.java
- core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
- core/server/master/src/main/java/alluxio/master/job/WorkerAssignPolicy.java
- core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
- core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
- job/common/src/main/java/alluxio/scheduler/job/Job.java
- job/common/src/main/java/alluxio/scheduler/job/Task.java
- shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
- tests/src/test/java/alluxio/client/cli/fs/command/LoadCommandIntegrationTest.java
new scheduler design, changed some logic of treating each job as statemachine, and make it extensible for developer to write their own logic to resume the statemachine.
enable an extensible scheduler framework to be able to work under dora architecture.
No.
> Add new scheduler

- core/common/src/main/java/alluxio/master/WorkerState.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
- core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
- core/server/master/src/test/java/alluxio/master/block/meta/MasterWorkerInfoTest.java
- shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
- shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
- tests/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
```
bin/alluxio fsadmin report capacity
Capacity information for all workers:
Total Capacity: 10.67GB
Tier: MEM  Size: 10.67GB
Used Capacity: 0B
Tier: MEM  Size: 0B
Used Percentage: 0%
Free Percentage: 100%
Format is short: true
Format is %-16s %-15s %-16s %-13s %s %-16s %-40s
Worker Name      State           Last Heartbeat   Storage       MEM              Version          Revision
192.168.3.8      ACTIVE           166              capacity      10.67GB          2.10.0-SNAPSHOT  ffcb706497bf47e43d5b2efc90f664c7a3e7014e
used          0B (0%)
```
Please list the user-facing …
> Port changes of [#17325] to branch-2.8

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
the same modification as  #16655
> Reduce redundant calls in getObject of S3 API

- core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Convert the Eof error to a standard error code when parse the Complete MPU
> Fix the Eof error when parse the Complete MPU

- dora/core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/security/authentication/AuthType.java
Make some changes for extension.
Make extending PropertyKeys doable
NA
> Update for splitting PropertyKey

- dora/core/common/src/main/java/alluxio/security/authentication/DefaultAuthenticationServer.java
- dora/core/common/src/main/java/alluxio/util/CommonUtils.java
- dora/core/common/src/main/java/alluxio/util/ConfigurationUtils.java
- dora/core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
Create interface for security
Create interface for security
NA
> Create interface for security Part1

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- dora/core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/security/authentication/AuthType.java
- dora/core/common/src/main/java/alluxio/security/authentication/DefaultAuthenticationServer.java
- dora/core/common/src/main/java/alluxio/util/CommonUtils.java
- dora/core/common/src/main/java/alluxio/util/ConfigurationUtils.java
- dora/core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
- pom.xml
> Merge Dora to Dora_0504

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
> Support range copy in copyObject and copyPart

- docs/en/administration/Upgrade.md
- docs/en/operation/Admin-CLI.md
This is the doc update from a few recent commits:
1. https://github.com/Alluxio/alluxio/commit/aee3c5cb960b2e472f4fcdb86e731ca3b91d2f8c
2. https://github.com/Alluxio/alluxio/commit/9a4e154e7293667572fec25c63136462fb58a345
3. https://github.com/Alluxio/alluxio/commit/dbac084c1e1d89c1e9253da036746e2df9e1ef14
4. https://github.com/Alluxio/alluxio/commit/8da59539201cff376c33256846bd565d976a148e
5. https://github.com/Alluxio/alluxio/commit/141ee0e567a4c6c60907f85ea66b828704bd761d
6. https://github.com/Alluxio/alluxio/commit/26257e6f35c57d937f6f5bdee831facc2fcf7e1a
In short, a few improvements have been added that the admin can now see the version/revision of the running Alluxio components in the cluster. A few commands were also added to help with gracefully decommissioning/restarting workers …
> Port changes of [#17381] to branch-2.10

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Port changes of [#17390] to branch-2.8.
Support range copy in copyObject and copyPart
> Port changes of [#17390] to branch-2.8

- dora/core/common/src/main/java/alluxio/extensions/ExtensionsClassLoader.java
Add a new function in ExtensionsClassLoader
Adds a path where the class loader can load resource from.
NA
> Add a new function in ExtensionsClassLoader

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RequestServlet.java
- core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
Remove s3 handler map in s3 proxy.
https://github.com/Alluxio/alluxio/issues/17403
1. change in user-facing APIs NO
2. addition or removal of property keys NO
3. webui NO
> Remove s3 handler map in s3 proxy

- dev/scripts/update-versions.sh
refers to `master` branch, update to `main` branch
> Update branch name in update-versions.sh

- dev/scripts/.gitignore
- dev/scripts/src/alluxio.org/README.md
- dev/scripts/src/alluxio.org/command/command.go
- dev/scripts/src/alluxio.org/go.mod
- dev/scripts/src/alluxio.org/go.sum
adds command/command.go to be used for future golang development
> Add command lib in golang workspace

- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Fix the path style 
Path style was not respected for aws s3 async client previously
N/A
> Fix s3 force path style

- core/common/src/main/java/alluxio/wire/FileInfo.java
Support print xattr for stat command.
Needs to show the xattr for user.
User can see the xattr leverage this PR.
> Support print xattr for stat command

- underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
- underfs/obs/src/main/java/alluxio/underfs/obs/ObsClientExt.java
Support config obs configuration from mount option
For now, we cannot specify other obs client configurations through any way.
After this PR, we can config any obs configuration.
> Support config obs configuration from mount option

- dora/core/common/src/main/java/alluxio/metrics/MetricsSystem.java
Add security metrics
Add security metrics
NA
> Add security metrics

- dora/core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
This PR cherry-picks changes from #17333 on `master-2.x` branch to `main` branch.
> Port changes of [#17333] to main

- dora/shell/src/main/java/alluxio/cli/fsadmin/command/Context.java
Modify Context for extension
Other extra logic can be extended based on Context.
NA
> Modify the interface of Context for extension

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
Modify for DoraCacheFileSystem extensibility
Enable create Doraclient outside of DoraCacheFileSystem.
NA
> Modify for DoraCacheFileSystem extensibility

- dora/core/common/src/main/java/alluxio/grpc/GrpcChannelPool.java
Align the rule to use whether a self signed or official ca
Align the rule to use whether a self signed or official ca.
NA
> Align the rule to use whether a self signed or official ca

- dora/core/common/src/main/java/alluxio/grpc/GrpcChannel.java
- dora/core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
Add a new function to enable the caller create sasl client handler.
Add a new function to enable the caller create sasl client so that the authenticate method can be extended.
NA
> Add a new function to enable the caller create sasl client

- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Load metadata as well as data when running Load on Dora
User still need to know the metadata(ex. length) when openFile
na
> Load metadata when running Load on Dora

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/underfs/ChecksumType.java
- dora/underfs/gcs/src/main/java/alluxio/underfs/gcs/v2/GCSV2UnderFileSystem.java
- dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Support new contentHash for GCS
new contenthash so we can compare HDFS checksum with GCS object checksum
new property
> Support CRC32C Checksum for GCS

- bin/launch-process
Regarding https://github.com/Alluxio/alluxio/pull/16940#discussion_r1198367841. Add the substring "Xmx" that's supposed to be checked on.
> Fix Xmx check

- core/common/src/main/java/alluxio/heartbeat/CronExpressionIntervalSupplier.java
- core/common/src/main/java/alluxio/heartbeat/FixedIntervalSupplier.java
- core/common/src/main/java/alluxio/heartbeat/SleepingTimer.java
Check sleep timer interval change when update conf
We currently generate these logs every time we execute the updateConf command, even if the value has not been modified.
```
2023-04-24 11:37:27,445 INFO  [config-hash-master-heartbeat-0](SleepingTimer.java:88) - update Master Cluster Metrics Updater interval supplier.
2023-04-24 11:37:27,445 INFO  [config-hash-master-heartbeat-0](SleepingTimer.java:88) - update Master Lost Worker Detection interval supplier.
2023-04-24 11:37:27,445 INFO  [config-hash-master-heartbeat-0](SleepingTimer.java:88) - update Worker register stream session cleaner interval supplier.
2023-04-24 11:37:27,445 INFO  [config-hash-master-heartbeat-0](SleepingTimer.java:88) - update Master Block Integrity Check interval supplier.
2023-04-24 11:37:27,445 INFO …
```
> Avoid unnecessary config update checks

- dora/core/client/fs/src/main/java/alluxio/client/block/AllMastersWorkerInfo.java
- dora/core/client/fs/src/main/java/alluxio/client/block/util/WorkerInfoUtil.java
- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
- dora/core/common/src/main/java/alluxio/util/CommonUtils.java
- dora/core/common/src/main/java/alluxio/util/WaitForOptions.java
- dora/core/common/src/main/java/alluxio/util/proto/BlockLocationUtils.java
- dora/core/common/src/test/java/alluxio/util/proto/BlockLocationUtilsTest.java
- dora/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- dora/core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
- dora/core/server/worker/src/main/java/alluxio/worker/block/BlockSyncMasterGroup.java
- dora/shell/src/main/java/alluxio/cli/fs/command/FreeCommand.java
- dora/shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
- dora/shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
- dora/stress/shell/src/main/java/alluxio/stress/cli/RpcBenchPreparationUtils.java
- dora/tests/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
During the master-2.x -> main attempt, some commits were left in the below PRs because we missed #16849 
https://github.com/Alluxio/alluxio/pull/17435
https://github.com/Alluxio/alluxio/pull/17445
https://github.com/Alluxio/alluxio/pull/17449
Now that 16849 is ported by https://github.com/Alluxio/alluxio/pull/17462, these children commits should all go in.
> Merge commits depending on #16849 to main

- .gitignore
- dev/intellij/runConfigurations/AlluxioDoraWorker_0.xml
- dev/intellij/runConfigurations/AlluxioDoraWorker_1.xml
Update gitignore file and IDE run configurations.
> Update git ignore and add Dora worker IDE run configurations

- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
> Fix copy UFS

- dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadJob.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/task/CopyHandler.java
- dora/job/common/src/main/java/alluxio/scheduler/job/Job.java
Mark job as failure if there's failed files instead of mark job as succeeded
Resolve confusion progress report
na
> Mark job as failure if there's failed files

- dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
Add permission exception in dora client exception list.
This exception can be thrown to the user.
NA
> Add permission exception in dora client exception list

- dora/shaded/client-hadoop3/pom.xml
need to fix the directory paths in cherry picked PR since it is under `dora/`
> Fix build path in shaded/client-hadoop3 pom

- common/transport/src/main/proto/grpc/block_worker.proto
- common/transport/src/main/proto/proto/journal/job.proto
- common/transport/src/main/proto/proto/journal/journal.proto
- dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
- dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
- dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
- dora/core/server/common/src/main/java/alluxio/master/journal/JournalEntryAssociation.java
- dora/core/server/common/src/test/java/alluxio/master/journal/JournalEntryAssociationTest.java
- dora/core/server/master/src/main/java/alluxio/master/job/JobFactoryProducer.java
- dora/core/server/master/src/main/java/alluxio/master/job/JournalMoveJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/task/DeleteHandler.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Adding the move job to the EE main branch.
The move job is essential for the PPDM hardening.
Pls see the docs: https://docs.google.com/document/d/1RsDr_378Oc7VoXwDIE-7pM4uYOY2iikK2KEYaipIjq8/edit?usp=sharing
No
> Add move job

- dora/integration/fuse/bin/alluxio-fuse
> Fix FUSE mount issue

- dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/AbstractReadHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/BlockReadRequestContext.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/FileReadHandler.java
Modify the visibility and inheritance of some interfaces
Supports better scalability
> Modify the visibility and inheritance of some dora interfaces

- dora/core/common/src/main/java/alluxio/security/authorization/AclAction.java
Add toModeBits for extension
Add toModeBits for extension
NA
> Add toModeBits for extension

- common/transport/src/main/proto/grpc/block_worker.proto
- dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
- dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- dora/core/server/master/src/main/java/alluxio/master/job/AbstractJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/HashBasedWorkerAssignPolicy.java
- dora/core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/RoundRobinWorkerAssignPolicy.java
- dora/core/server/master/src/main/java/alluxio/master/job/WorkerAssignPolicy.java
- dora/core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
- dora/job/common/src/main/java/alluxio/scheduler/job/Job.java
- dora/job/common/src/main/java/alluxio/scheduler/job/Task.java
make scheduler universally work for copyjob + doraloadjob
resolve conflict of copyjob to use the new scheduler
N/A
> Update scheduler to work with copy

- integration/tools/pom.xml
- tests/pom.xml
- tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
- underfs/hdfs/pom.xml
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileOutputStream.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
As some people are confused about why we encountered some build error while running alluxio tests.
I will suggest them to remove the HADOOP1 related code to pass the build.
> Cleanup HADOOP1 support

- dev/scripts/src/alluxio.org/build/cmd/tarball.go
- dev/scripts/src/alluxio.org/build/profiles.yml
- dora/integration/fuse/bin/alluxio-fuse
When generate a tarball for standalone fuse, the tarball script is not work.
Fix standalone fuse tarball error
No
4. webui
> Fix standalone fuse tarball error

- dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
Fix async submit task. When we have async submit job with different thread, we could have the following issue
1. submit task
2. task not submitted to mJobToRunningTasks yet
3. job pass the check `if (mJobToRunningTasks.getOrDefault(job, new ConcurrentHashSet<>()).isEmpty()
&& job.isCurrentPassDone())`
4. job is marked as succeeded.
Fix bug
na
> Fix async submit task

- common/transport/src/main/proto/proto/journal/job.proto
Fix proto format
Fix proto format
NA
> [SMALLFIX] Fix proto format

- integration/docker/.dockerignore
- integration/docker/Dockerfile
- integration/docker/Dockerfile-base
- integration/docker/Dockerfile-dev
- integration/docker/conf/alluxio-env.sh.template
- integration/docker/conf/alluxio-site.properties.template
This is the updated one of https://github.com/Alluxio/alluxio/pull/17444. The `ln -s` wouldn't work in the Dockerfile because we are already user `alluxio` and thus no proper permission in the `/opt` dir. Still need to leverage the docker `COPY`.
> Extensible Dockerfile

- common/transport/src/main/proto/grpc/policy_master.proto
- common/transport/src/main/proto/proto/journal/journal.proto
- common/transport/src/main/proto/proto/journal/policy.proto
- dora/core/common/src/main/java/alluxio/Constants.java
- dora/core/server/common/src/main/java/alluxio/master/journal/JournalEntryAssociation.java
- dora/core/server/common/src/test/java/alluxio/master/journal/JournalEntryAssociationTest.java
Migrate policy related proto to main so journal entry change can be picked up.
Journal entry
na
> Migrate policy related proto to dora

- dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
Fix copy progress to show the correct setting
na
na
> Fix copy progress

- docs/en/Overview.md
- docs/en/overview/Getting-Started.md
clarify the improvement comparsion and update download links to alluxio.io/downloads
> [DOCFIX] Update overview doc and download links

- dora/core/common/src/main/java/alluxio/Constants.java
- dora/core/common/src/main/java/alluxio/grpc/ServiceVersionClientServiceHandler.java
Fix policy service version otherwise client won't be able to connect to service
bug fix
na
> Fix policy service version

- common/transport/src/main/proto/grpc/raft_journal.proto
- common/transport/src/main/proto/proto.lock
> Port [#17358] to main

- common/transport/src/main/proto/grpc/file_system_master.proto
- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
- dora/core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
- dora/core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
- dora/core/server/master/src/main/java/alluxio/master/job/JournalMoveJobFactory.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/integration/fuse/src/test/java/alluxio/fuse/cli/MockFuseFileSystemMasterClient.java
- dora/tests/src/test/java/alluxio/client/cli/job/DistributedCommandsStatsTest.java
1. refactor move API for ee
2. add get mount Id API so we can use this API to get correct ufs in ee
na
na
> Add mount table support for move

- docs/_data/table/cn/master-metrics.yml
[DOCFIX]Update cn version of docs/_data/table/cn/master-metrics.yml
The Chinese docs/_data/table/cn/master-metrics.yml doc is problematic: the description of Master.CreateDirectoryOps is wrong. 
This PR synchronizes these updates.
> [DOCFIX]Update cn version of docs/_data/table/cn/master-metrics.yml

- docs/cn/ufs/OSS.md
[DOCFIX] Update cn version of OSS doc
The Chinese ufs/OSS doc is not updated with the latest changes,
> [DOCFIX] Update cn version of OSS doc

- docs/cn/ufs/Azure-Data-Lake-Gen2.md
- docs/cn/ufs/Azure-Data-Lake.md
[DOCFIX] Update cn version of Azure-Data-Lake-Gen2 doc
The Chinese ufs/Azure-Data-Lake-Gen2 doc is not updated with the latest changes,
> [DOCFIX] Update cn version of Azure-Data-Lake-Gen2 doc

- docs/cn/solutions/Deep-Learning.md
[DOCFIX] Update cn version of Deep-Leaning doc
The Chinese solutions/Deep-Leaning doc is not updated with the latest changes,
> [DOCFIX] Update cn version of Deep-Leaning doc

- core/common/src/main/java/alluxio/wire/WorkerWebUILogs.java
The purpose of this pr is to fix some incorrect code in WorkerWebUILogs.
There is some incorrect code in WorkerWebUILogs, we should fix them.
1.   change in user-facing APIs
2.   addition or removal of property keys
3.   webui
> Fix some incorrect code in WorkerWebUILogs

- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
The purpose of this pr is to improve the comments related to DefaultMetaMaster and add some @links.
In DefaultMetaMaster, some of the documentation descriptions are not clear enough, and we should fix them as much as possible.
3. webui
> [DOCFIX]Improve annotations in DefaultMetaMaster add some @links

- dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
- dora/core/client/fs/src/main/java/alluxio/client/file/dora/netty/NettyDataWriter.java
- dora/core/client/fs/src/main/java/alluxio/client/file/options/OutStreamOptions.java
- dora/core/client/fs/src/main/java/alluxio/client/file/ufs/DoraOutStream.java
- dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/BlockWriteRequestContext.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/FileWriteHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/WriteRequest.java
> Adjust the details of the dora writing process for extension

- core/server/common/pom.xml
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalUtils.java
- core/server/master/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java
- core/server/master/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTestFaultTolerance.java
Bump ratis version to 2.5.1 and fix API changes.
Ratis 2.5.1 is released and brings several improvements and bug fixes.
No.
> Bump ratis version to 2.5.1

- dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Modify interface for extension
In some situation, eg. permission check, it is requiring to inherit the function to add extra check.
NA
> Modify interface for extension

- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
orig-pr: Alluxio/alluxio#17497
orig-commit: Alluxio/alluxio@812855fe5040ae94bcdfb2ebd7fed233632fcf70
orig-commit-author: Bin Fan <fanbin103@gmail.com>
> Fix a bug that creates 0 byte block file mistakenly

- core/common/src/main/java/alluxio/exception/runtime/BlockDoesNotExistRuntimeException.java
- core/common/src/main/java/alluxio/util/io/FileUtils.java
- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
- tests/src/test/java/alluxio/server/tieredstore/TieredStoreBlockCorruptionIntegrationTest.java
- tests/src/test/java/alluxio/server/tieredstore/TieredStoreIntegrationTest.java
Manual cherry-pick of #17564.
pr-link: https://github.com/Alluxio/alluxio/pull/17564
change-id: cid-2758ff97e5016c1aae7ededb244e919233ae6d3b
> Fix corrupted block causing reads to fail; Port [#17564] to branch-2.9

- dora/shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
Make mount command work in dora
na
na
> Make mount command work in dora

- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
Fix move job tasks didn't picking up active workers.
Fix move job bugs
na
> Fix move job picking workers

- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
change task exceptions to catch throwable 
otherwise when throwable happens it would report task success
na
> Update job tasks

- dora/tests/src/test/java/alluxio/client/fs/UnderStorageReadIntegrationTest.java
Fixed an error in `UnderStorageReadIntegrationTest. java`.
Added some mReadNoCache cases in the test cases.
Fix a test bug and add more cases.
na
> Fix a test bug & Add no-cache cases

- dora/core/common/src/main/java/alluxio/security/group/GroupMappingService.java
Modify for GroupMappingService extension
Modify for GroupMappingService extension
NA
> Modify for GroupMappingService extension

- bin/alluxio-start.sh
Remove mount check when starting alluxio if users do not intend to mount
When the user does not want to mount and starts alluxio directly, the user can enter `./bin/alluxio-start.sh local` or `./bin/alluxio-start.sh all`. The old code will not be able to start alluxio successfully, it will refuse to start or the AlluxioWorker will fail to start. This PR fixes the issue.
The reason for deleting the mount check part of the code is:
We found that the mount check is only started when the user enters `./bin/alluxio-start.sh worker` or `./bin/alluxio-start.sh local`. However, if the user intends to use alluxio after mounting, the user will use `alluxio-mount.sh` for the mount operation. If the mount fails, an error will be reported, and `alluxio-start.sh` will not be executed. If alluxio is …
> Remove mount check when starting alluxio if users do not intend to mount

- dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Hookup permission checks in dora worker for scheduler job related endpoints
To handle permission checking correctly 
N/A
> Hookup permission check for scheduler jobs

- dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Add getOpenFileHandleContainer method
Add getOpenFileHandleContainer method
> Add getOpenFileHandleContainer method

- dev/github/run_checks.sh
- dev/scripts/src/alluxio.org/check-docs/main.go
remove the doc check in pr build since the config.yml file changes its structure.
> Remove the doc check in pr build

- common/transport/src/main/proto/grpc/file_system_master.proto
- dora/core/server/master/src/main/java/alluxio/master/file/FileSystemMasterWorkerServiceHandler.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/file/FileSystemMasterClient.java
Add get mount id to worker master rpc
support get mount id from worker
na
> Add get mount id to worker master rpc

- dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
Expose the getJobState API to scheduler.
This is needed for EE updates policy status.
na
> Expose get job state to scheduler

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
The purpose of this pr is to fix some descriptions related to the FileSystemMaster module.
In the FileSystemMaster module, there are some inappropriate descriptions or comments, and we should fix them as much as possible.
3. webui
> [DOCFIX] Fix some descriptions related to the FileSystemMaster module

- core/common/src/main/java/alluxio/heartbeat/CronExpressionIntervalSupplier.java
- core/common/src/main/java/alluxio/heartbeat/FixedIntervalSupplier.java
- core/common/src/main/java/alluxio/heartbeat/SleepIntervalSupplier.java
- core/common/src/main/java/alluxio/heartbeat/SleepingTimer.java
- core/common/src/main/java/alluxio/time/LightThreadSleeper.java
- core/common/src/main/java/alluxio/time/Sleeper.java
- core/common/src/main/java/alluxio/time/SteppingThreadSleeper.java
- core/common/src/test/java/alluxio/heartbeat/SleepingTimerForCronExpressionIntervalSupplierTest.java
- core/common/src/test/java/alluxio/heartbeat/SleepingTimerTest.java
Implements light thread sleeper to support invoke a sleeping sleeper to determine whether need continue to sleep. 
Without this feature, when we need to refresh the interval of Heartbeat thread, it cannot take effect.
No
> Support SteppingThreadSleeper

- docs/_config.yml
- docs/_data/menu-en.yml
- docs/_includes/sitemap.html
- docs/_layouts/global.html
This pr is recreated pr for https://github.com/Alluxio/alluxio/pull/17495
> Enable tiered category hierarchy/dropdowns for docs

- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
Fix move job process response.
bug
na
> Fix move job process response

- docs/_data/menu-en.yml
update the docs menu based on current layout of md files in docs/en/
> [DOCFIX] Fix EN docs menu

- docs/_data/menu-en.yml
> [DOCFIX] Update menu-en for docs

- dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
If the file is a single file, don't use listing.
> Add support of loading a single file in DoraLoadCommand

- docs/_includes/sitemap.html
- docs/en/api/S3-API.md
Fix link problem in the docs to pass the `checkLinks` test
> [DOCFIX] Fix link problem in the docs 

- dora/minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
Fix integration tests for Dora.
> Set page store dir and empty UFS before tests

- dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Add a parameter to decide whether initializing the loadFS cache.
it is possible that the child class would implement a new cache.
NA
> Modify hdfs ufs interface for extension

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServer.java
Fix the bug that dora worker is blocked by http server
> Fix the bug that dora worker is blocked by http server

- dev/scripts/src/alluxio.org/check-docs/main.go
Check menu.yml URLs should match exactly with the list of all markdown doc files.
> Add check url with actual path functionality to check-docs

- dora/shell/src/main/java/alluxio/cli/DocGenerator.java
Extract the logic from main to other function.
Refactor docGen for extension
NA
> Refactor docGen for extension

- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
Include job id into progress report
better track errors.
na
> Include job id into progress report

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
- dora/core/common/src/main/java/alluxio/Constants.java
Remove the switch flag for dora write. It is not needed any more.
It is not needed any more. The write in dora is now enabled and tested. 
No
> Remove the switch flag for dora write

- dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
> Fix getInStream worker net address

- dora/core/server/worker/src/main/java/alluxio/worker/task/CopyHandler.java
Throw exception if overwrite
Better behavior 
na
> Throw exception if overwrite

- dora/shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
> Fix MountCommand

- dev/scripts/src/alluxio.org/build/cmd/build.go
- dev/scripts/src/alluxio.org/build/cmd/profile.go
- dev/scripts/src/alluxio.org/build/cmd/tarball.go
- dev/scripts/src/alluxio.org/build/profiles.yml
specify client jar name in tarball profile
> Add client jar customization to generate tarball script

- dev/scripts/src/alluxio.org/build/cmd/docker.go
- dev/scripts/src/alluxio.org/build/docker.yml
adding `-docker` suffix to docker tarball names
integrate w/ our internal automation
docker tarball name changes
> Update docker artifact names

- dora/shell/src/main/java/alluxio/cli/fs/command/UnmountCommand.java
- dora/shell/src/main/java/alluxio/cli/fs/command/UpdateMountCommand.java
Followup change to https://github.com/Alluxio/alluxio/pull/17694 and https://github.com/Alluxio/alluxio/pull/17697.
> Make UpdateMountCommand and UnmountCommand behave like MountCommand

- dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
Determine whether it is a file or directory based on the path to obtain the correct file status
No
> Fix the issue of not being able to display third level files

- common/transport/src/main/proto/grpc/file_system_master.proto
- dora/core/common/src/main/java/alluxio/job/MoveJobRequest.java
- dora/core/server/master/src/main/java/alluxio/master/job/JobFactoryProducer.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJobFactory.java
Add move job request
Need for distMv command.
na
> Add move request to job factory

- dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/JournalCopyJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/JournalMoveJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/UfsFileIterable.java
- dora/core/server/worker/src/main/java/alluxio/worker/task/CopyHandler.java
Use ufs iterable for copy and move
save memory
na
Test with distCp & s3
> Use ufs iterable for copy and move

- core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
Fix local cache identifier
If not including `modification time`, it may have consistency issues.
NO
> Fix local cache identifier to solve the local cache consistent issue

- dora/core/common/src/main/java/alluxio/metrics/MetricsSystem.java
> [SMALLFIX] Fix typo in MetricsSystem

- dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSPositionReader.java
- dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
Support position reader of OBS.
Alluxio couldn't read data in OBS. I have implemented OBSPositionReader and now it can `cat` files in OBS.
Here is the screenshot about OBS's position reader.
No
> Support position reader of OBS

- dora/core/common/pom.xml
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/ListStatusResult.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
- pom.xml
1. Move metastore into dora meta manager
2. Handles listing cache invalidation
3. Add unit tests
4. Introduced caffeinine cache
Dora metadata management has a lot of consistency issue between metadata/listing/page cahces. To address these issues, the first step is to introduce a centralized management place and put these logic together.
N/A
> Refactor dora meta manager

- docs/_data/menu-en.yml
- docs/en/ufs/COS.md
- docs/en/ufs/OBS.md
- docs/en/ufs/OSS.md
- docs/en/ufs/S3.md
[DOCFIX] Add multipart-upload method
1. Add multipart upload method in S3, OSS, COS and OBS.
2. Add configure COS and OBS with Alluxio.
No
> [DOCFIX] Add multipart-upload method

- dev/scripts/src/alluxio.org/build/cmd/flags.go
- dev/scripts/src/alluxio.org/build/cmd/profile.go
- dev/scripts/src/alluxio.org/build/profiles.yml
- dora/core/common/src/main/java-templates/alluxio/ProjectConstants.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- pom.xml
and remove the --disableTelemetry flag
readded the enabled config to set the default value
follow up to https://github.com/Alluxio/alluxio/pull/17738
> Define default-release and default-testing tarball profiles

- docs/en/fuse-sdk/Local-Cache.md
> [DOCFIX] Fix fuse doc picture

- docs/cn/cloud/Tencent-Cloud-EMR.md
- docs/en/cloud/Tencent-Cloud-EMR.md
Tencent Cloud EMR has updated some version information and needs to be synchronized to community documents
3. webui
> [DOCFIX]  Fix doc errors for Tencent Cloud EMR

- dora/shaded/client/pom.xml
Shade protobuf
Avoid dependency conflict
No
> Shade protobuf to prevent dependency confliction

- dora/core/common/src/main/java/alluxio/AbstractClient.java
Add createChannel API for extension
The child class can create channel according to its extension.
NA
> Add createChannel API for extension

- integration/docker/Dockerfile
- integration/docker/Dockerfile-dev
1. The version number has been wrong. Fix them to comply with the alluxio version.
2. Update the version of async profiler to a newer version.
> Fix Dockerfiles

- docs/_layouts/global.html
- docs/css/main.css
layout right now:
example after change without format:
with format:
> [DOCFIX] Change docs width from 1200px to entire page

- common/transport/src/main/proto/proto/journal/job.proto
- dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/JournalCopyJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJobFactory.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
Add filter to copy jobs.
To add copy job to policy engine.
na
> Add filter to copy jobs

- dora/core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
This change adds a flag to local cache input stream, to allow forcing a FS open to external storage. The flag is default disabled so no impact.
Local cache stream works in the way that, if all the bytes are found in local cache, there will be no open call to remote storage. However, making a call to remote storage may be desired, for example, to trigger the remote FS data ACL check. 
Note that remote FS open is bypassed only when ALL bytes are read local, as long as there is any bytes needed from remote FS, an open call to remote FS will be triggered.
Make a constructor for LocalCacheFileInStream and FSDataInputStream that access the new flag. Current constructor interface will still work and set the flag to false (disabled) so no change.
> Allow forcing open call to fallback storage in local cache read

- dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Fix the wrong recursive listing logic where the listing result is cached.
N/A
> Fix recursive listing cache

- docs/en/compute/Hive.md
- docs/en/fuse-sdk/FUSE-SDK-Dora-Quick-Start.md
- docs/en/ufs/Azure-Blob-Store.md
- docs/en/ufs/Azure-Data-Lake-Gen2.md
- docs/en/ufs/Azure-Data-Lake.md
- docs/en/ufs/COS.md
- docs/en/ufs/COSN.md
- docs/en/ufs/CephFS.md
- docs/en/ufs/CephObjectStorage.md
- docs/en/ufs/GCS.md
- docs/en/ufs/Minio.md
- docs/en/ufs/NFS.md
- docs/en/ufs/OBS.md
- docs/en/ufs/OSS.md
- docs/en/ufs/Ozone.md
- docs/en/ufs/Qiniu-KODO.md
- docs/en/ufs/S3.md
- docs/en/ufs/Swift.md
the step to deploy Alluxio can be assumed for docs related to integrations with Alluxio
> [DOCFIX] Remove install Alluxio step in integration docs

- core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreDir.java
> Remove rocks page store log

- docs/_data/menu-en.yml
- docs/en/Overview.md
- docs/en/core-services/Data-Caching.md
- docs/en/introduction/Glossary.md
- docs/en/presto-sdk/presto-sdk.md
- docs/en/ufs/Azure-Data-Lake.md
- docs/en/ufs/COS.md
- docs/en/ufs/COSN.md
- docs/en/ufs/GCS.md
- docs/en/ufs/OBS.md
Added more terms to glossary page
update terms list & definitions
yes
> [DOCFIX] Update Glossary Page & minor changes

- core/server/master/src/main/java/alluxio/master/meta/MetaMasterSync.java
> Close client when heartbeat executor closed

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreDir.java
This PR aim to fix bug related to a wrong named logger.
Correct the logger name.
> Remove rocks page store log from PageStoreDir

- dora/core/common/src/main/java/alluxio/conf/Configuration.java
- dora/core/common/src/main/java/alluxio/conf/Source.java
- dora/core/common/src/main/java/alluxio/conf/reference/DemoProperty.java
- dora/core/common/src/main/java/alluxio/conf/reference/ReferenceProperty.java
- dora/core/common/src/main/resources/META-INF/services/alluxio.conf.reference.ReferenceProperty
- dora/core/common/src/test/java/alluxio/conf/SourceTest.java
Add reference property support
Add reference property support
Add reference property support
> Add reference property support

- dora/core/common/src/main/java/alluxio/ClientContext.java
- dora/core/common/src/main/java/alluxio/conf/Configuration.java
- dora/core/common/src/main/java/alluxio/grpc/GrpcServerBuilder.java
- dora/core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- dora/core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClientPool.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/shell/src/main/java/alluxio/common/RpcPortHealthCheckClient.java
Change for extension
Change for extension
NA
> Change for extension

- dev/github/Dockerfile-jdk11
- dev/github/Dockerfile-jdk17
- dev/github/Dockerfile-jdk8
in preparation to use testcontainers in junit tests
> Install docker in alluxio-maven images

- dev/github/run_docker.sh
upgrades to the image containing docker
> Update alluxio-maven to 0.1.3

- dora/core/client/fs/src/main/java/alluxio/client/file/ConfigHashSync.java
- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContextReinitializer.java
- dora/core/server/worker/src/main/java/alluxio/web/WorkerWebServer.java
- dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
Add a new constructor in FileSystemContextReinitializer
Add a new constructor in FileSystemContextReinitializer, the ConfigHashSync can be created by the caller.
NA
> Add a new constructor in FileSystemContextReinitializer

- dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Add get functions in S3 underfs
Add get functions in S3 underfs
> Add get functions in S3 underfs

- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
> Solve FUSE flush issue

- docs/en/fuse-sdk/Local-Cache.md
> Fix fuse docs

- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Change for future extension
Change for future extension
NA
> Change for future extension

- dora/core/common/src/test/java/alluxio/ConfigurationTestUtils.java
- dora/core/server/worker/src/main/java/alluxio/worker/WorkerProcess.java
Add interfaces to allow using custom modules to inject in worker
The `LocalAlluxioCluster` can be reused outside the repo with custom worker implemenetation.
no
> Add interfaces to allow using custom modules to inject in worker

- dora/core/common/pom.xml
- dora/core/server/common/pom.xml
- dora/integration/tools/hms/pom.xml
- dora/tests/pom.xml
- dora/underfs/cephfs/pom.xml
- dora/underfs/cos/pom.xml
- dora/underfs/cosn/pom.xml
- dora/underfs/gcs/pom.xml
- dora/underfs/kodo/pom.xml
- dora/underfs/ozone/pom.xml
- dora/underfs/s3a/pom.xml
- dora/underfs/web/pom.xml
- pom.xml
Cleanup top level POM dependencies
- Move dependency version definition to <dependencyManagement> section
- Remove unused properties
- Sort properties and dependencies alphabetically
- Remove unused profile
No
> Cleanup top level POM dependencies

- dora/shaded/hadoop/pom.xml
- dora/underfs/hdfs/pom.xml
- dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/HdfsUnderFileSystemIntegrationTest.java
Add HDFS UFS integration test using HDFS mini cluster
To test HDFS UFS related features better in alluxio
N/A
> Add HDFS UFS  integration test

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileSystem.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- dora/core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
Rollback to use localcacheInStream for presto local cache
Fix the oom and out of bound issue in prestodb's local cache
no
> Rollback to use localcacheInStream for presto local cache

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Add metrics for num of client position read fallback
counting the number of fallback
no
> Add metrics for num of client position read fallback

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Add metrics counter for the page invalidated by TTL
no
> Add metrics counter for the page invalidated by TTL

- pom.xml
> Skip tests for release 302

- pom.xml
This reverts commit 37ae3552b1a34f2fe12449d08c5d7a7b9f3e0dfc.
3. webui
> Revert "Skip tests for release 302"

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
> Add metrics for exteranl storage call from alluxio worker

- docs/en/operation/User-CLI.md
Fix load cli doc and remove job service doc
doc quality
na
> [DOCFIX] Fix load doc

- dora/underfs/hdfs/pom.xml
There are some other packages need to reference the test file in HDFS UFS package so we create a test jar here.
N/A
> Generate test-jar for HDFS UFS

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
- dora/core/server/common/src/main/java/alluxio/master/journal/MergeJournalContext.java
- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- dora/core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileWriter.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/PacketReadTaskStateMachine.java
Improve debug logging, avoid constructing strings online
Fix anti patterns. 
No
> Improve debug logging

- docs/en/reference/Metrics-List.md
update plain text tables to table formatting
better user interface
webui
> [DOCFIX] Update List of Metrics table formatting

- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Remove the dependency to the master during the registration
Not necessary to connect to the master during registration
NA
> Remove the dependency to the master during the registration

- dora/minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- dora/tests/pom.xml
- dora/tests/src/test/java/alluxio/client/fuse/dora/FuseEndToEndTest.java
- dora/tests/src/test/java/alluxio/client/fuse/dora/FuseUtils.java
- dora/tests/src/test/java/alluxio/client/fuse/dora/hdfs3/AbstractFuseHdfsIntegrationTest.java
- dora/tests/src/test/java/alluxio/client/fuse/dora/hdfs3/FuseHdfsIntegrationTest.java
> Dora Fuse HDFS integration test

- docs/en/Overview.md
- docs/en/contributor/Contribution-Guide.md
- docs/en/core-services/Data-Caching.md
- docs/en/introduction/Introduction.md
- docs/en/kubernetes/Install-Alluxio-On-Kubernetes.md
remove embedded videos, replace with link
better ui
webui
> [DOCFIX] Remove embedded videos

- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
- dora/core/common/src/main/java/alluxio/membership/MembershipManager.java
- dora/core/common/src/main/java/alluxio/membership/StaticMembershipManager.java
- dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/DefaultWorkerProvider.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/MembershipManagerWorkerProvider.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/WorkerProvider.java
- dora/core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
Support ETCD worker management for scheduler
na
na
> Support ETCD worker management for scheduler

- docs/en/overview/Release-Notes.md
Add release notes 
bring release notes to doc
n/a
> [DOCFIX] Add release notes 2.9.3

- docs/en/overview/Release-Notes.md
> [DOCFIX] Add Release Notes 2.8.1

- docs/en/overview/Release-Notes.md
> [DOCFIX] Add Release Notes 2.7.3

- docs/en/overview/Release-Notes.md
> [DOCFIX] Add Release Notes 2.7.2

- dora/tests/src/test/java/alluxio/client/fuse/dora/hdfs3/AbstractFuseHdfsIntegrationTest.java
- dora/tests/src/test/java/alluxio/client/fuse/dora/hdfs3/FuseHdfsIntegrationTest.java
> Update fuse hdfs integration tests

- bin/alluxio
Remove the table command
Remove the table command
NA
> [SMALLFIX] Remove the table command

- docs/en/Overview.md
> [DOCFIX] Update Overview

- docs/en/Get-Started.md
- docs/en/Overview.md
- docs/en/contributor/Contribution-Guide.md
- docs/en/core-services/Data-Caching.md
- docs/en/introduction/Introduction.md
update get started section with locally, cluster, or k8s
added play icons for videos
better overview page flow
play icons to differentiate between links & videos
webui
> [DOCFIX] Update Overview Page

- docs/en/overview/Release-Notes.md
add release notes 
bring release notes to docs 
n/a
> [DOCFIX] Release Notes 2.7.1

- docs/en/overview/Release-Notes.md
> [DOCFIX] Release Notes 2.6.0

- docs/en/overview/Release-Notes.md
> [DOCFIX] Release Notes 2.6.2

- bin/alluxio
- bin/alluxio-start.sh
- bin/launch-process
Remove the several redundant run commands.
Remove the several redundant run commands.
NA
> [SMALLFIX] Remove the several redundant run commands

- bin/alluxio
Remove the bootstrap config and killAll.
Remove the bootstrap config and killAll.
NA
> [SMALLFIX] Remove the bootstrap config and killAll

- dev/scripts/src/alluxio.org/build/cmd/version.go
after rearranging the pom.xml in sorted order, version parsing in build script returns the wrong value for version
fix by parsing the single version tag that is directly under the root project xml node
> Fix version parsing in build script

- bin/alluxio
`killAll` is needed for stop commands
> Add back killAll command

- dora/shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShellUtils.java
Fix the membership check in fsadmin
Fix the membership check
NA
> Fix the membership check in fsadmin

- dev/scripts/src/alluxio.org/build/profiles.yml
Follow-up to https://github.com/Alluxio/alluxio/pull/17960
Fix tarball builds
No
> Update list of tarball copied bin scripts

- dora/shaded/client/pom.xml
Fix the duplicated class issues when compile presto with alluxio
3. webui
> Fix the duplicated class issues when compile presto with alluxio

- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
- dora/core/client/fs/src/main/java/alluxio/client/metrics/ClientMasterSync.java
- dora/core/common/src/main/java/alluxio/ClientContext.java
- dora/shell/src/main/java/alluxio/cli/fsadmin/command/ReportCommand.java
- dora/tests/src/test/java/alluxio/client/fs/FileSystemContextReinitIntegrationTest.java
- dora/tests/src/test/java/alluxio/client/fs/FileSystemReadonlyIntegrationTest.java
- dora/tests/src/test/java/alluxio/client/fs/PathConfigurationIntegrationTest.java
Remove unused parameters pathConf.
Remove unused parameters pathConf.
NA
> Remove unused parameters pathConf

- dev/scripts/src/alluxio.org/check-docs/main.go
> [DOCFIX] Update checkstyle pr build check

- build/cli/build-cli.sh
`declare -A` is only available starting bash 4+ as pointed out by @twalluxio and @Kai-Zhang
change os/arch mappings in `bin/alluxio` into a list of tuples
> Avoid using associative arrays in bin/alluxio script

- cli/src/alluxio.org/cli/processes/master.go
parity with the bash side change in https://github.com/Alluxio/alluxio/pull/17933
> Remove journal backup flag from start master

- docs/_data/menu-en.yml
- docs/en/compute/Tensorflow.md
[DOCFIX] Add Doc of running alluxio with Tensorflow
Now dora branch is lack of docs about how to run alluxio with Tensorflow. This PR provides a doc about running Alluxio with Tensorflow
No
> [DOCFIX] Add Doc of running Alluxio with Tensorflow

- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileEntry.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReadOrOutStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReader.java
> Refactor Fuse interfaces

- dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
> Fix broken UT by remove TieredIdentity in 

- docs/en/api/S3-API.md
Update headers so that once it's clicked in the right side menu, it redirects to its section, instead of external aws link
menu should redirect to section
n/a
> [DOCFIX] Update headers in right menu to redirect to section

- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3BucketTask.java
- dora/tests/integration/src/test/java/alluxio/client/rest/MultipartUploadTest.java
add S3 list-parts UTs.
test for s3 list parts
none
> Add S3 list-parts UTs

- dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Fix the copy handler's ufs manager creation and
refactor some progress report.
Found a bug during e2e tests for GCS.
na
> Fix copy ufs manager creation

- cli/src/alluxio.org/cli/env/command.go
Add a new function in golang CLI to support reformatting the json output to yaml and so on.
For `info` commands, it'll provide a easier way to change the format.
nope
> Add format function in CLI

- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
- dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Chooses a preferred worker from worker list to fetch files
> Choose preferred worker from worker list

- dora/core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
Enable dora meta store WAL
Otherwise data will lose after worker restarts
N/A
> Enable dora meta store WAL

- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileEntry.java
- dora/integration/jnifuse/fs/src/main/java/alluxio/jnifuse/AbstractFuseFileSystem.java
- dora/tests/integration/src/test/java/alluxio/client/fuse/dora/hdfs3/AbstractFuseHdfsIntegrationTest.java
> Refactor Fuse

- dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
fix the skip error handling
Previously we consider the skip as a failure, which is not correct.
Consider skip only as skip.
na
> Fix delta copy error report

- docs/en/ufs/Aliyun-OSS.md
- docs/en/ufs/CephFS.md
- docs/en/ufs/Huawei-OBS.md
- docs/en/ufs/Ozone.md
- docs/en/ufs/Storage-Overview.md
- docs/en/ufs/Tencent-COS.md
label ufs contributed/maintained by community and update github links
bring more awareness of os community
n/a
> [DOCFIX] Label UFS contributed by community

- docs/en/compute/Tensorflow.md
- remove redundant info, add redirect link to section on local cache quick start doc
- update external links to open in new tab
better user journey
n/a
> [DOCFIX] Update Tensorflow Doc

- cli/src/alluxio.org/cli/cmd/info/collect.go
- dora/shell/src/main/java/alluxio/cli/bundler/CollectInfo.java
- dora/shell/src/main/java/alluxio/cli/bundler/command/AbstractCollectInfoCommand.java
- dora/shell/src/main/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommand.java
- dora/shell/src/test/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommandTest.java
- dora/shell/src/test/java/alluxio/cli/bundler/command/CollectConfCommandTest.java
- dora/shell/src/test/java/alluxio/cli/bundler/command/CollectEnvCommandTest.java
- dora/shell/src/test/java/alluxio/cli/bundler/command/CollectLogCommandTest.java
New cli for collectInfo does not seem to work, fix the bug to keep the arguments in line with the Java code.
> Fix info collect not working bug

- dora/tests/integration/pom.xml
- dora/tests/testcontainers/pom.xml
> Improve pom module name

- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
Add the alluxio hadoop3 jar client to the artifacts
Some users may want to use hadoop3
no
> Add hadoop3 jar to the artifacts

- docs/_includes/sitemap.html
remove the indentation in sitemap and manage indentation in css
> [DOCFIX] Remove indentation for sitemap

- docs/en/deploy/Install-Alluxio-Cluster-with-HA.md
> [DOCFIX] Remove zookeeper doc

- docs/en/operation/User-CLI.md
> [DOCFIX] Update journal command doc

- integration/docker/entrypoint.sh
Script `launch-process` was renamed to `launch-process-bash`. Update the name of the script in `entrypoint.sh`
> Run launch-process-bash script

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
One more place to count the cache hit requests
> Add dora worker metrics at http requests

- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Count the hit and miss of ListStatus and GetFileInfo in worker
> Add dora worker metadata metrics

- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/membership/MasterMembershipManager.java
- dora/core/common/src/main/java/alluxio/membership/MembershipManager.java
- dora/core/common/src/main/java/alluxio/membership/MembershipType.java
- dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
Change name of NoopMembershipManager to MasterMembershipManager.
N/A
N/A
> Change name of NoopMembershipManager

- core/common/src/main/java/alluxio/conf/Reconfigurable.java
- core/common/src/main/java/alluxio/conf/ReconfigurableRegistry.java
- core/common/src/main/java/alluxio/heartbeat/HeartbeatThread.java
- core/common/src/main/java/alluxio/heartbeat/HeartbeatTimer.java
- core/common/src/main/java/alluxio/heartbeat/SleepingTimer.java
- core/common/src/test/java/alluxio/heartbeat/SleepingTimerTest.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
> Provide a way to support listening only for modified PropertyKey

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Reverts Alluxio/alluxio#18070
revert per request on backward compatibility
> Revert "Change metric type of LocalCacheState from counter to gauge"

- dora/core/server/worker/src/main/java/alluxio/worker/netty/AbstractReadHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/BlockReadRequest.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/ReadRequest.java
Refactor Netty read handler to allow subclassing.
> Refactor Netty read handler

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/context/CachePerThreadContext.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
Implement per-thread cache context
Enable the fine-grained cache admission 
no
> Implement per-thread cache context

- build/cli/build-cli.sh
- dev/scripts/src/alluxio.org/build/profiles.yml
> Fix cli binary name for arm

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
Better error handling when a stream is closed. Log more and don't swallow errors
N/A
> Improve dora stream error handling

- docs/_data/menu-en.yml
- docs/en/Overview.md
- docs/en/deploy/Install-Alluxio-Cluster-with-Docker.md
> [DOCFIX] Update docker documentation

- dora/core/server/master/src/main/java/alluxio/master/predicate/DatePredicate.java
- dora/core/server/master/src/test/java/alluxio/master/predicate/DatePredicateTest.java
Fix datePredicate so it would respect the interval specified in the policy.
Polish tests
bug fix
na
> Fix datePredicate

- dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
> Fix typo in ServiceDiscoveryRecipe

- cli/src/alluxio.org/cli/cmd/info/collect.go
- dora/shell/src/main/java/alluxio/cli/bundler/CollectInfo.java
Refactor some of the code in java and go to make the CLI more flexible for the future
There might be more commands added in the future
nope
> Refactor the collectInfo main for future use

- cli/src/alluxio.org/cli/cmd/initiate/validate.go
- dora/core/server/common/src/main/java/alluxio/master/journal/checkpoint/TarballCheckpointFormat.java
- dora/core/server/common/src/main/java/alluxio/master/journal/checkpoint/ZipCheckpointFormat.java
- dora/core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- dora/integration/tools/validation/src/main/java/alluxio/cli/ClusterConfConsistencyValidationTask.java
- dora/integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemContractTest.java
- dora/integration/tools/validation/src/main/java/alluxio/cli/ValidateEnv.java
- dora/shell/src/main/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommand.java
collectAlluxioInfo calls bin/alluxio commands and collects their output. fix the commands after the golang CLI refactor
> Update collectAlluxioInfo and other bin/alluxio cmd strings

- dev/scripts/src/alluxio.org/build/cmd/assembly.go
- dev/scripts/src/alluxio.org/build/cmd/build.go
- dev/scripts/src/alluxio.org/build/cmd/docker.go
- dev/scripts/src/alluxio.org/build/cmd/flags.go
- dev/scripts/src/alluxio.org/build/cmd/module.go
- dev/scripts/src/alluxio.org/build/cmd/preset.go
- dev/scripts/src/alluxio.org/build/cmd/profile.go
- dev/scripts/src/alluxio.org/build/cmd/tarball.go
- dev/scripts/src/alluxio.org/build/cmd/ufs.go
- dev/scripts/src/alluxio.org/build/cmd/version.go
- made some funcs/consts public
- tarball artifacts list lib/plugin modules in `metadata` field
no
> Refactor build logic for usability

- dora/core/server/master/src/main/java/alluxio/master/job/UfsFileIterable.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/UfsFileIterableTest.java
Fix last modified time is 0 in UfsFileIterable
bug fix
na
> Fix last modified time is 0 in UfsFileIterable

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
Add cache rejected metrics.
Add cache rejected metrics.
Add metrics `Worker_CacheRejectedBlocks`.
> Add worker rejected cache block request metrics

- cli/src/alluxio.org/cli/cmd/info/report.go
- cli/src/alluxio.org/cli/cmd/util/format.go
move code into separate package
> Move json formatting in info as util SKIPCI

- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
> Remove log

- dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorker.java
remove master host check
master host should not be a hard requirement right now.
na
> Remove master host check

- dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
Make copy & move return list of tasks
make worker busy
na
> Make copy & move return list of tasks

- cli/src/alluxio.org/cli/cmd/fs/check_cached.go
> Fix check-cached

- core/client/fs/src/main/java/alluxio/client/block/options/GetWorkerReportOptions.java
- core/common/src/main/java/alluxio/grpc/GrpcUtils.java
- core/common/src/main/java/alluxio/wire/WorkerInfo.java
- core/common/src/test/java/alluxio/wire/WorkerInfoTest.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
- core/server/worker/src/main/java/alluxio/worker/block/RegisterStreamer.java
- core/transport/src/main/proto/grpc/block_master.proto
- core/transport/src/main/proto/proto.lock
- shell/src/main/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommand.java
- shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
- shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
- tests/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
provide more information about worker state
> Add worker vCPU info to fsadmin report capacity command

- dora/core/common/src/main/java/alluxio/util/EnvironmentUtils.java
Fail directly if sudo needs password.
Fix #18194
NO
> Fail directly if sudo needs password

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/ResponseFileInfo.java
- dora/tests/integration/src/test/java/alluxio/server/worker/WorkerHttpServerIntegrationTest.java
Improve list files RESTful API providing more useful info. This PR add the following info to the response JSON:
1. Formatted file size
2. Alluxio path
3. UFS path
4. Last modification timestamp
> Improve list files RESTful API providing more useful info

- dora/core/client/fs/src/test/java/alluxio/client/file/ufs/UfsBaseFileSystemTest.java
The old UfsBaseFileSystem cannot run, this pr fix it.
no.
> Fix the UfsBaseFileSystemTest

- dora/tests/integration/src/test/java/alluxio/client/fuse/AbstractFuseIntegrationTest.java
- dora/tests/integration/src/test/java/alluxio/server/worker/WorkerMetadataSyncIntegrationTest.java
Remove the @Ignore annotations. It works now.
improve code quality.
no.
> [SMALLFIX] Enable WorkerMetadataSyncIntegrationTest

- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/DoraLoadJobTest.java
- dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
Fix load command ufs string
bug fix
na
> Fix load command ufs string

- dora/tests/integration/src/test/java/alluxio/client/cli/fs/FileSystemShellUtilsTest.java
The loadCommands of FileSystemShellUtilsTest now works.
No.
> Fix FileSystemShellUtilsTest

- dev/scripts/src/alluxio.org/build/cmd/docker.go
add name to metadata
Needed to identify docker artifacts
no
> Add name to artifacts metadata

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadOptions.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadService.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Add RESTful API for distributed load.
**SUBMIT:**
description: submit a load job
example:
`http://localhost:28080/v1/load?path=s3a://jiamingmai-test/&opType=submit&partialListing=false&&verify=true&bandwidth=1000&loadMetadataOnly=false&verbose=true&skipIfExists=true`
**STOP:**
description: stop the load job
example:
`http://localhost:28080/v1/load?path=s3a://jiamingmai-test/&opType=stop`
**PROGRESS:**
description: get the progress of the load job
example:
`http://localhost:28080/v1/load?path=/&opType=progress&progressFormat=text&verbose=true`
> Add RESTful API for distributed load

- .gitignore
- dora/core/common/pom.xml
- dora/core/common/src/main/java/alluxio/metrics/MultiDimensionalMetricsSystem.java
- dora/core/server/common/src/main/java/alluxio/web/WebServer.java
- dora/core/server/master/src/main/java/alluxio/master/AlluxioMaster.java
- dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorker.java
- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
- pom.xml
Introduce a new tool to add multi-dimensional metrics more easily. The new class holds all the metrics and exposes them in Prometheus type.
Add following metrics:
- alluxio_data_access
- alluxio_ufs_data_access
- alluxio_cached_data_read
- alluxio_meta_operation
- alluxio_cached_storage
- alluxio_cached_capacity
- alluxio_cached_evicted_data
- alluxio_cached_readable_storage
No. The new metrics will expose on a new URL which the webui is not currently using.
> Add multi-dimensional metrics system

- dora/core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
PR https://github.com/Alluxio/alluxio/pull/18182 was merged with changes conflicting to https://github.com/Alluxio/alluxio/pull/18285 which CI was not able to catch. So `main` is not able to compile after merging `18182`. This small change fixes that, by adapting new code in 18285 to interface changes in 18182.
> Use new UfsManager.get() avoid creating conf instances every time

- common/transport/src/main/proto/grpc/block_worker.proto
- dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
- dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- dora/core/client/fs/src/main/java/alluxio/client/file/PositionReadFileInStream.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
- dora/core/client/fs/src/test/java/alluxio/client/file/PositionReadFileInStreamTest.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
In the position reader, preloading pages on workers to improve the cold read performance.
To improve the cold read performance.
N/A
> Improve cold read performance by prefetching data on workers

- dora/integration/fuse/src/test/java/alluxio/fuse/meta/UpdateCheckerTest.java
Delete invalid UnderFileSystemAlluxioTest for changed codebase.
No.
> Delete useless UnderFileSystemAlluxioTest

- dev/github/Dockerfile-jdk11
- dev/github/Dockerfile-jdk17
- dev/github/Dockerfile-jdk8
- native/rust/archetype/pom.xml
Add Rust toolchain to the Docker image used for CI.
Allow CI to compile and run Rust code.
No.
> Add Rust toolchain to CI

- common/transport/src/main/proto/grpc/block_worker.proto
- dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashPolicy.java
- dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/HashBasedWorkerAssignPolicy.java
- dora/core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadDataSubTask.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadMetadataSubTask.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadSubTask.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/RoundRobinWorkerAssignPolicy.java
- dora/core/server/master/src/main/java/alluxio/master/job/WorkerAssignPolicy.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/DoraLoadJobTest.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
- dora/job/common/src/main/java/alluxio/scheduler/job/Job.java
Update load job to adopt multi replicas
part of PR to support loading multi replicas
new load option `replicas`
> Update Load replica job

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/common/src/main/java/alluxio/metrics/MultiDimensionalMetricsSystem.java
Add some metrics and change the registry to expose the metrics more accurately.
And add the call point of the capacity-related metrics.
Use default registry will expose all the metrics and some of them are not meaningful for all components.
no
> Change the metrics registry and some metrics

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
> Move job related operations to DoraCacheFileSystem

- cli/src/alluxio.org/cli/cmd/job/load.go
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Fix the bug that command line doesn't support regx file filter
> Fix the bug that command line doesn't support regx file filter

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- shell/src/main/java/alluxio/cli/fsadmin/command/UnsetConfCommand.java
- shell/src/main/java/alluxio/cli/fsadmin/command/UpdateConfCommand.java
- tests/src/test/java/alluxio/client/cli/fsadmin/command/UpdateConfIntegrationTest.java
Support dynamic unset value
3. webui
> Support dynamic unset value

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3Handler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
The v1 and v2 versions of proxy use uniform judgment conditions.
> Use correct audit log configuration in proxy

- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
XATTR config added to PagedDoraWorkerTest
LocalUFS does not support xattr
no
> Disable xatter in PagedDoraWorker test

- dora/core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
- dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
- dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
> Fix COS/OSS/OBS iterative listing

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
Fix page store TTL metrics
We should not count the age of page which has been just deleted
no
> Fix page store TTL metrics

- dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/ChmodCommandIntegrationTest.java
The old one is ignored, now bring it back.
No.
> [SMALLFIX] Fix broken ChmodCommandIntegrationTest

- docs/cn/introduction/introduction.md
Introduction Chapter translation
> Translate Introduction

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Respond with unsupported message when GetBucketLocation
Alluxio proxy doesn't support GetBucketLocation request, so we need to return 'Not Implemented' error code.
3. webui
> Respond with unsupported message when GetBucketLocation

- dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUfsStatusIterator.java
Fix the bug that HDFS iterator doesn't work.
> Fix the bug that HDFS iterator doesn't work

- underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/oss/src/test/java/alluxio/underfs/oss/OSSUnderFileSystemTest.java
Fix the NPE in COSUnderFileSystem as PR #18403
Replace the FOLDER_SUFFIX from "_$folder$" to "/" in OSS UFS as PR #18408
3. webui
> Fix COS and OSS UFS 

- core/server/proxy/src/main/java/alluxio/proxy/s3/signature/StringToSignProducer.java
> Parse the URI if needed when creating the signature

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/PagedService.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/vo/WritePageResponseVO.java
Support write page with RESTful API
```
HTTP Method: POST
Request URL: http://localhost:28080/v1/file/<fileId>/page/<pageIndex>
HTTP Body: <page bytes>
```
> Support write page with RESTful API

- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
```
$ df -h /mnt/fuse/
Filesystem      Size  Used Avail Use% Mounted on
alluxio-fuse    910T     0  910T   0% /mnt/fuse
```
Add fake numbers for statfs
Some application checks the available space in a file system before continuing to do file operations.
A fake number (1 Petabytes) is provided to statfs. This number does not reflect real available storage space.
> Add fake numbers for statfs

- integration/docker/entrypoint.sh
`format` commands don't exist in cli anymore, so as job services. Delete some entrypoint code.
Solves https://github.com/Alluxio/alluxio/issues/18466
> Fix entrypoint

- dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashPolicyTest.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
2000 is too much
2000 is too much
na
> Change default value of virtual node count per worker

- core/common/src/main/java/alluxio/util/CommonUtils.java
- core/common/src/main/java/alluxio/util/ShellUtils.java
- core/common/src/test/java/alluxio/util/CommonUtilsTest.java
- core/common/src/test/java/alluxio/util/ShellUtilsTest.java
Port changes from  [@LetianYuan](https://github.com/LetianYuan) in PR : https://github.com/Alluxio/alluxio/pull/17256
in urgency for resolving injection vulnerability.
Resolve issue:  https://nvd.nist.gov/vuln/detail/CVE-2023-38889
No.
> Fix code injection admin

- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioFileSystem.java
Fix #18479
Fix the memory leak issue when the client accesses Alluxio through Hadoop FileContext API.
No.
> Fix AlluxioFileSystem memory leak

- docs/en/deploy/Requirements.md
clarify supportability of arm architecture
> [DOCFIX] Update Requirements.md

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
Using name threads is generally a good practice and helps system administrators understand what's going on with the system. Without explicit naming, the JDK-provided pools jave threads named `pool-N-thread-T`.
> Name threads used by LocalCacheManager

- integration/docker/Dockerfile-base
Install netcat in Dockerfile as needed.
> Install netcat in Dockerfile

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Add a path to the worker http server to enable an easy health check.
> Add http server health check

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpRequestUri.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Add health check RESTful API in Worker HTTP Server.
> Add health check RESTful API

- common/transport/src/main/proto/grpc/common.proto
- dora/core/common/src/main/java/alluxio/uri/UfsUrl.java
- dora/core/common/src/test/java/alluxio/UfsUrlTest.java
Add UfsUrl and its unit test into feature branch.
> Add UfsUrl and its UT

- docs/cn/ufs/TOS.md
- docs/en/ufs/TOS.md
Added the doc for TOS.
Because some configuration is added.
No.
> Support Tos doc for Alluxio

- dev/github/Dockerfile-jdk11
- dev/github/Dockerfile-jdk17
- dev/github/Dockerfile-jdk8
Install UCX on dockerfile jdk 8 for github PR test
> Install ucx on dockerfile jdk8

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
- core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- core/common/src/main/java/alluxio/Constants.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/network/protocol/databuffer/NioHeapBufferPool.java
- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- core/common/src/main/java/alluxio/util/CRC64.java
- core/common/src/main/java/alluxio/wire/FileInfo.java
- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/transport/src/main/proto/grpc/block_worker.proto
- core/transport/src/main/proto/grpc/file_system_master.proto
- core/transport/src/main/proto/proto.lock
- pom.xml
- shell/src/main/java/alluxio/cli/fs/command/CRC64CheckCommand.java
- shell/src/main/java/alluxio/cli/fs/command/CRC64CheckCommandUtils.java
- underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
To check the file integrity
Add a crc64 check cli
pr-link: Alluxio/alluxio#18682
change-id: cid-4eb62e603591f3235b92e4191c5b511b534f6fc3
3. webui
> Add CRC64 checksum check

- shell/src/main/java/alluxio/cli/fs/command/CRC64CheckCommandUtils.java
> Fix wording

- .github/workflows/checkstyle.yml
- .github/workflows/fuse_integration_tests.yml
- .github/workflows/java8_integration_tests.yml
- .github/workflows/java8_integration_tests_ft.yml
- .github/workflows/java8_integration_tests_webui.yml
- .github/workflows/java8_unit_tests.yml
pr-link: Alluxio/alluxio#18702
change-id: cid-b4b1fb88de0b1a2cca107fe252f62b0fc6463fcb
> Update github action version to v4
