- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockMasterClientTest.java
Modify `NetworkAddressUtils#parseInetSocketAddress` to handle resolved address strings correctly.
As mentioned in https://github.com/Alluxio/alluxio/pull/15670#discussion_r891870760 A resolved `InetSocketAddress` has the following `toString()` representation: "<hostname>/<resolved_address>:<port>". It is handy that `NetworkAddressUtils#parseInetSocketAddress` can process such strings correctly, so that we can pass an `InetSocketAddress` directly to the configuration.
No
> Support parsing resolved InetSocketAddress string

- core/server/common/src/test/java/alluxio/DefaultStorageTierAssocTest.java
Remove `checkStorageTierAssoc` method in `DefaultStorageTierAssocTest`. 
This method is no longer used after the commit `18f73f28fe4d`.
No.
> Remove unused method in DefaultStorageTierAssocTest

- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
- tests/src/test/java/alluxio/client/fuse/JNIFuseIntegrationTest.java
Fixes #15569
Support FIO sequential write test
fio --name=sequential-write --directory=/mnt/alluxio-fuse --rw=write --refill_buffers --bs=4M --size=4G --end_fsync=1
The sequential write workload failed with 
```
Fuse.Create(path=/sequential-write.0.0,mode=100644)
Fuse.Flush(path=/sequential-write.0.0,fd=1)
Fuse.Release(path=/sequential-write.0.0,fd=1)
Fuse.Open(path=/sequential-write.0.0,flags=0x8002(READ_WRITE))
Fuse.Write(path=/sequential-write.0.0,fd=2,size=131056,offset=0)
Cannot overwrite existing file /sequential-write.0.0 without O_TRUNC flag or fuse.truncate(size=0), flag 0x8002
```
and Alluxio do not support create empty file then open for write
Support create empty file and open for write or open for readOrWrite
> Support create empty file and open for write/RW workloads

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
To optimize the access speed of the inAlluxioData UI page
When there are many files in alluxio, if we open the inAlluxio web ui of the Alluxio master, it will take a long time and cause the Alluxio master to freeze. We may specify a certain number of file information to be displayed on the inAlluxio web through configuration items to avoid the above situation.
No
> Optimize the access speed of the inAlluxioData UI page

- core/client/fs/src/main/java/alluxio/client/block/policy/CapacityBaseRandomPolicy.java
- core/client/fs/src/test/java/alluxio/client/block/policy/CapacityBaseRandomPolicyTest.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
in scenary of presto+alluxio, presto break file to splits (a pice of file) and then read splits  concurrently.
This may result one block loaded by many workers concurrently. This result two problem:
1)  result too much replica in alluxio, and evict some important data
2)  ufs system (eg. hdfs datanode ) may result high workload
> Add cache for CapacityBaseRandomPolicy

- core/server/worker/src/main/java/alluxio/worker/block/BlockWorkerFactory.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/block/CacheRequestManagerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/stream/BlockWorkerDataReaderTest.java
- tests/src/test/java/alluxio/client/fs/BlockWorkerRegisterStreamIntegrationTest.java
Remove the unused parameter in DefaultBlockWorker
ufsManager is no longer used in blockworker
no
> Remove the unused parameter in DefaultBlockWorker

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
- tests/src/test/java/alluxio/client/fuse/JNIFuseIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/file/FuseFileOutStreamIntegrationTest.java
Fixes #15569
Support Fuse.truncate() to set the file to a bigger size before writing to it.
Support running FIO sequential read test.
Support Fuse.truncate() to change file to a file size bigger than the current bytes written.
Support user Fuse.truncate() to actual file size - sequential write to actual file size use case.
> Support truncate to extend file length

- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
helm-generate.sh has been moved into the helm-chart. Fix the related tarball generation process.
> Fix helm-chart-related tarball generation

- docs/en/operation/Basic-Logging.md
- docs/en/operation/User-CLI.md
Represent the `logLevel` command capabilities accurately.
> [DOCFIX] Fix `logLevel` command doc

- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointThread.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
The `UfsJournalCheckpointThread` calls `System.exit(-1)` when encountering journal corruption. This causes a deadlock between the `UfsJournalCheckpointThread` and the shutdown hook calling `AlluxioMasterProcess.stop()`.
This PR removes the `System.exit()` calls in favor of propagating exceptions when the thread completes. 
The net effect is that the master process completely releases its resources when shutting down and terminates without having to be issued `kill -9`.
For clean master process termination on errors.
No.
[This is an manually generated PR to cherry-pick committed PR Alluxio/alluxio#15699 into target branch branch-2.6]
> Port changes of [#15699] to branch-2.8

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalReader.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
- docs/en/operation/Journal.md
- minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
- tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java
This PR adds the option of triggering a backup automatically when an Alluxio master shuts down.
This helps trigger backups automatically when the master encounters unexpected journal corruption. 
It adds a new `PropertyKey` to disable the feature (it is enabled by default).
[This is an manually generated PR to cherry-pick committed PR Alluxio/alluxio#15698 into target branch branch-2.6]
> Port changes of [#15698] to branch-2.8

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
Remove directory return correct error code when failed to delete directory because directory not empty
Pjdfstest
expect 0 mkdir ${n0} 0755
create_file ${type} ${n0}/${n1}
expect "EEXIST|ENOTEMPTY" rmdir ${n0}
Clear error message
> Fix Fuse remove dir not empty error code

- core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
Fix `IllegalArgumentException` when releasing a block worker client because it was released to the wrong pool.
Fix #15556.
On the creation of the block worker and its release, the key used to retrieve the pool from the map are computed separately, and its ingredients could have changed in between. Therefore, when releasing the client, the wrong pool may be retrieved. This can be due to a number of reasons, for example the Alluxio configuration has changed during this time, and the client picks up new conf via client master config sync.
The fix is to embed the key inside the closable resource to avoid computing it a second time.
No.
> Fix wrong pool when releasing BWC

- dev/jenkins/Dockerfile-jdk11
- dev/jenkins/Dockerfile-jdk8
The current JNIFuseIntegrationTest is always running fuse2 even it claims it runs with fuse3. The PR https://github.com/Alluxio/alluxio/pull/15863 fixes this by replacing the existing incorrect loading libfuse process for the test with a correct one, but the jenkins image doesn't have fuse3, so the test hangs. 
This PR is to install Fuse3 on the jenkins image. On Ubuntu used by the jenkins image, package `fuse3` installs `fuse2` as well, which is why only `fuse3` is installed.
> Install fuse3 in jenkins image for github action

- core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
Remove unneeded auto-boxing in `AsyncJournalWriter`.
The `mWriteCounter` member only needs to be a primitive `long` type.
No.
> Remove unneeded auto-boxing in AsyncJournalWriter

- dev/jenkins/Dockerfile-jdk11
- dev/jenkins/Dockerfile-jdk8
Deleted package libfuse-dev in PR https://github.com/Alluxio/alluxio/pull/15876. Turns out it is required. Add it back in along with the corresponding libfuse3-dev for fuse3.
> Install libfuse-dev and libfuse3-dev in alluxio-maven image

- core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java
- tests/src/test/java/alluxio/server/worker/WorkerMetadataSyncIntegrationTest.java
Created an integration test class to test the heartbeat syncing mechanism mainly implemented in `BlockMasterSync`
Verify that the heartbeat between `BlockWorker` and `BlockMaster` is functioning properly. Give a 80% coverage for `BlockMasterSync` class
No
> Add integration test for BlockMasterSync

- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
- tests/src/test/java/alluxio/client/fuse/file/FuseFileInOrOutStreamIntegrationTest.java
Fixes #15852 support create empty file -> open(rdwr) -> truncate() workload
> Fix Fuse open read_write then truncate to extend file length

- docs/_data/table/en/cluster-metrics.yml
Fix incorrect description of 'Cluster.BytesReadDirectThroughput' in docs.
Description of metric 'Cluster.BytesReadDirectThroughput' in docs is incorrect.
No.
> Fix metric description of 'Cluster.BytesReadDirectThroughput'

- core/server/proxy/pom.xml
- job/server/pom.xml
Fix #15414
https://github.com/kongchen/swagger-maven-plugin says that each item of "location" must have a tag, such as
```
<locations>
<location>com.github.kongchen.swagger.sample.wordnik.resource</location>. 
<location>com.github.kongchen.swagger.sample.wordnik.resource2</location>
</locations>
```
I tested the PR and it works for the api docs.
No
> Fix api docs

- .github/workflows/checkstyle.yml
- .github/workflows/fuse_integration_tests.yml
- .github/workflows/java11_integration_tests.yml
- .github/workflows/java11_integration_tests_webui.yml
- .github/workflows/java11_unit_tests.yml
- .github/workflows/java8_integration_tests.yml
- .github/workflows/java8_integration_tests_webui.yml
- .github/workflows/java8_unit_tests.yml
Add caching under github runners to reduce the need for go module downloads for every build
Go downloads occasionally fail to download due to external factors. Caching reduces the need to download and thus reduce frequency of build failures.
No
> Add go dependency caching to github actions workflow

- core/common/src/main/java/alluxio/worker/block/io/LocalFileBlockWriter.java
- core/common/src/test/java/alluxio/worker/block/io/LocalFileBlockWriterTest.java
Remove the unnecessary buf duplicate call
we already call duplicated on the caller side.  https://github.com/Alluxio/alluxio/blob/70b6e77438ad22b876890e635a43d1520e83498b/core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java#L193
no
> Remove the unnecessary buf duplicate call

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
Move jvm pause metrics names so that it can be used.
This is for the jvm pause metrics name string reuse
NA
> Move jvm pause metrics names

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/SnapshotReplicationManager.java
- core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
- core/server/common/src/test/java/alluxio/master/journal/raft/SnapshotReplicationManagerTest.java
- core/transport/src/main/proto/grpc/raft_journal.proto
- core/transport/src/main/proto/proto.lock
When using Ratis, the primary master does not take a snapshot itself, instead it requests a snapshot from a follower. This pull request fixes two issues with the current implementation of this.
1. Currently when a snapshot needs to be taken as given by `alluxio.master.journal.checkpoint.period.entries`, Ratis will call `takeSnapshot()` in the JournalStateMachine each time a journal entry is committed until a new snapshot is installed. On the primary master `takeSnapshot()` runs asynchronously by first requesting snapshot information from each follower, then downloading a snapshot form one of them if a valid snapshot is available. If no valid snapshot is available (which is likely since all nodes take snapshots at the same log index and it takes time to generate a snapshot) the request …
> Fix snapshot from follower thread leak

- integration/docker/Dockerfile
- integration/docker/Dockerfile-dev
- integration/docker/README.md
- integration/docker/entrypoint.sh
Rrefactor the Dockerfile's entrypoint script so that we can set permissions on a provided env/argument instead.
Currently in the Alluxio Dockerfile the USER, UID and GID are all hard-coded. Thus only way to change the file permissions is to recompile a Docker image with new values for the arguments.
This creates a problem for users of the Helm chart who try to modify the user / UID used to run the Docker container in k8s. The corresponding file permissions do not get updated to the new UID.
I suggest we should consider refactoring the Dockerfile's entrypoint script so that we can set permissions on a provided env/argument instead.
No, it doesn't.
> Allow Docker image file permissions to be modified at runtime

- core/server/master/src/main/java/alluxio/master/file/loadmanager/LoadManager.java
- core/server/master/src/test/java/alluxio/master/file/loadmanager/LoadManagerTest.java
Add a test for 1000 worker with 100 jobs. Change the processJob task to run more
frequently to shorten test wall time. The CPU for each run is small except for
the first run when a job is submitted so the overhead is negligible.
> Add test for LoadManager

- integration/fuse/bin/alluxio-fuse
Fix alluxio-fuse unmount to get the right pid to kill.
Currently even the "-f" option cannot kill the AlluxioFuse process, below is a demo
```
$ jps -m
42757 AlluxioFuse -m /mnt/projects -a /projects -o allow_other
$ integration/fuse/bin/alluxio-fuse unmount -f /mnt/projects
Successfully unmount fuse at /mnt/projects
$ jps -m
42757 AlluxioFuse -m /mnt/projects -a /projects -o allow_other
```
The cause is:
- https://github.com/Alluxio/alluxio/blob/master/integration/fuse/bin/alluxio-fuse#L101
```
alluxio.fuse.AlluxioFuse \
-m ${mount_point} -a ${mount_alluxio_path} ${mount_options}"
```
- https://github.com/Alluxio/alluxio/blob/master/integration/fuse/bin/alluxio-fuse#L205, `fuse_stat` outputs the `mount_alluxio_path` instead of `mount_point` here
No
> Fix alluxio-fuse unmount to get the right pid

- core/client/fs/src/main/java/alluxio/client/file/cache/cuckoofilter/SegmentedLock.java
Fix a typo in `SegmentedLock` that probably caused the deadlock described in https://github.com/Alluxio/alluxio/issues/15935
Fix https://github.com/Alluxio/alluxio/issues/15935
No
> Fix typo in SegmentedLock

- core/common/src/main/java/alluxio/retry/RetryUtils.java
- core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java
https://github.com/Alluxio/alluxio/pull/15765 changed the ActiveSync retry mechanism to use reuse a single RetryPolicy object for every call. This caused the ActiveSync calls to not work correctly as the timer object in this single object was always expired after every call. This reverts the change, but keeps the cleanup restructuring from that PR.
This fixes ActiveSync calls timing out unnecessarily.
No
> Fix ActiveSync timeout retry

- docs/en/deploy/Running-Alluxio-On-a-Cluster.md
Fix the typo: from `conf/worers` to `conf/workers`
To make our doc more accurate
Nope
> [DOCFIX] Fix typo in deployment of Alluxio Cluster

- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
Added more unit tests for DefaultBlockWorker that:
- tested for various failure scenarios
- tested the behavior of ufs fallback block reader
- tested cache behavior
- tested DefaultBlockWorker's heartbeat tasks are executing properly
Give more confidence on the correctness of `DefaultBlockWorker`, improve unit-test coverage(60% -> 83%)
No
> Add more unit tests for DefaultBlockWorker

- core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
- core/common/src/main/java/alluxio/AbstractClient.java
- core/common/src/main/java/alluxio/AbstractJobMasterClient.java
- core/common/src/main/java/alluxio/AbstractMasterClient.java
- core/common/src/main/java/alluxio/Client.java
- core/common/src/test/java/alluxio/AbstractClientTest.java
- core/server/common/src/main/java/alluxio/master/journal/raft/SnapshotReplicationManager.java
- integration/fuse/src/test/java/alluxio/fuse/cli/MockFuseFileSystemMasterClient.java
- shell/src/main/java/alluxio/cli/LogLevel.java
- shell/src/main/java/alluxio/cli/fs/command/LeaderCommand.java
- shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShellUtils.java
- shell/src/test/java/alluxio/cli/LogLevelTest.java
Refactor the `Client` API to:
- replace the original `InetSocketAddress getAddress` method with `SocketAddress getRemoteSockAddress` and `String getRemoteHostName`
Refactor the `AbstractClient`:
- Work with a `GrpcServerAddress` instead of a raw `InetSocketAddress` to be compatible with `BlockWorkerClient`, which might not have an IP-remote. 
- Clarify the semantics of the methods: `getRemoteSockAddress` and `getRemoteHostName` inherited from `Client` are supposed to be idempotent getters, i.e., they should not perform network queries each time they are called. Provide a new abstract method `queryGrpcServerAddress` that queries the address each time it's called. Child classes now override this method to implement whatever address query logic they need, and `connect` uses this method to …
> Refactor the address API of alluxio client

- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
Fix NPE in `DefaultBlockWorkerTest` because `OpenUfsBlockOptions` cannot be `null` with the paged block reader.
> Fix NPE in DefaultBlockWorkerTest

- dev/github/run_checks.sh
- dev/jenkins/build.sh
- dev/scripts/src/alluxio.org/build-distribution/cmd/check-ufs-versions.go
- dev/scripts/src/alluxio.org/build-distribution/main.go
For new HDFS UFS versions, a new enum describing the version needs to be added to HdfsVersion.java as well as adding a new ufs module to compile the jar when building the tarball. It is easy to check for the UFS modules in a tarball by inspecting the lib directory of a tarball, but it is not easy to check that the corresponding version enum is defined. This check ensures that each HDFS UFS module has a corresponding HdfsVersion by checking that the compilation version matches version enum regex.
> Add consistency check for ufs versions against their compiled modules

- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/test/java/alluxio/fuse/AlluxioJniFuseFileSystemTest.java
Fix AlluxioJniFuseFileSystemTest and enable it.
Fixed test cases
- read
- write
- create
- flush
- rename
- renameNewExist
- renameOldNotExist
- statfs
- incompleteFileCannotOpen
- openWithDelay (deleted as alluxio does not wait the file to complete now)
- chown
- chownWithoutValidGid
Currently AlluxioJniFuseFileSystemTest is ignored and there are a lot of cases failed if testing them.
AlluxioJniFuseFileSystemTest is still keep evolving, so it is better to have AlluxioJniFuseFileSystemTest to check some details.
No
> Fix AlluxioJniFuseFileSystemTest and enable it

- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
Change `OpenUfsOptions` in `DefaultBlockWorkerTest#cacheBlock` to disable fall back behavior.
Once the cache succeeded, we should find the block locally without falling back. This ensures correct test expectations.
No
> Use no fallback options for cache test in DefaultBlockWorkerTest

- integration/docker/Dockerfile
- integration/docker/Dockerfile-dev
- integration/docker/README.md
- integration/docker/entrypoint.sh
This reverts commit 0cc44736fd533b2b1d452f36dd23ba92eabf3088.
We need to further discuss on whether we should/want to let root be the default user because of security concerns. It is also breaking k8s, so reverting it
> Revert "Allow Docker image file permissions to be modified at runtime"

- core/common/src/main/java/alluxio/worker/block/BlockStore.java
- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/UfsIOManager.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerUfsExceptionTest.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/server/worker/src/test/java/alluxio/worker/block/UfsIoManagerTest.java
- core/transport/src/main/proto/grpc/block_worker.proto
- core/transport/src/main/proto/proto.lock
- microbench/src/main/java/alluxio/worker/WorkerBenchLoad.java
Use bytes instead of MB as the unit for bandwidth
> Change block worker load api's bandwidth to int64

- core/common/src/main/java/alluxio/util/FormatUtils.java
- docs/en/deploy/Running-Alluxio-On-Kubernetes.md
- integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
- integration/kubernetes/helm-chart/alluxio/Chart.yaml
- integration/kubernetes/helm-chart/alluxio/values.yaml
Make Alluxio able to recognize KiB, MiB,... that are used by Kubernetes configs. Making use of the "i" format default in helm chart.
Addresses https://github.com/Alluxio/alluxio/issues/12277. This solution is mentioned at https://github.com/Alluxio/alluxio/issues/12277#issuecomment-1058572008 and I also think it has the minimal impact.
No.
> Make Alluxio parse KiB and more

- core/server/common/src/test/java/alluxio/master/journal/raft/SnapshotReplicationManagerTest.java
Fixes snapshot replication test which could block sometimes by adding a timeout when GetInfo requests are disabled by mocking (as would happen they were not being mocked).
No
> Fix snpashot replication test

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
- docs/en/api/S3-API.md
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
- Rename a property key to align with prior naming scheme.
- Update S3 API docs to include `CompleteMultipartUpload` XML body.
- Update scope & consistency enforcement of S3 API `PropertyKey`s
- Remove requirement for objects to have prior ETags in `GetObject(Attributes)`
- Improved log messages for HTTP requests received
Clarity/accuracy.
For the ETag requirement removal, this is to make the S3 API behaviour in line with before that ETag `xAttr` field existed. We unintentionally made it so that the S3 API was incompatible with files in Alluxio's FS which were not created via the S3 API. 
Renamed `alluxio.proxy.s3.multipart.upload.min.part.size` to `alluxio.proxy.s3.complete.multipart.upload.min.part.size`
> Remove S3 API ETag requirement & misc. cleanups

- core/common/src/test/java/alluxio/util/JvmPauseMonitorTest.java
JVM pause monitor test can fail sometimes due to data races.
The thread sleep isnt always accurate, so it uses the more precise timer (the same that the actual pause monitor uses) and it increases the wait time by one, because the check in the monitor class is exactly for 250, which would fail if the time was exactly that.
It also ensures the logs are flushed on write.
No.
> Fix JVM pause monitor test

- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
Fix master down when master change to leader but last time failed because of startMasters
Fix master down when master change to leader but last time failed because of startMasters
The master change leader failed because of startMasters, but it is not set mRaftJournalWriter = null; The next time the master change to leader , it will check `Preconditions.checkState(mRaftJournalWriter == null);`, so the master will exit.
no
> Fix master down when master change to leader

- integration/fuse/src/test/java/alluxio/fuse/AlluxioJniFuseFileSystemTest.java
Ignore AlluxioJniFuseFileSystemTest
AlluxioJniFuseFileSystemTest is enabled in https://github.com/Alluxio/alluxio/pull/15983.
Before merging, it had rebased on the latest `master` branch at that time and passed all tests.
But now there are test cases failing in  https://github.com/Alluxio/alluxio/runs/7668865525?check_suite_focus=true
No
> Ignore AlluxioJniFuseFileSystemTest

- tests/src/test/java/alluxio/client/fs/FileSystemMasterRestartIntegrationTest.java
In FileSystemMasterRestartIntegrationTest.unavailableUfsRecursiveCreate,
when we call stopFS, the authenticated client user might be cleared, in
which case the following listStatus can fail. Always set the user before
calling listStatus explicitly.
> Fix Integration test

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java
Remove dead code (permission check). The usage of the perm checker was removed in #14698.
Remove unused code
NA
> Remove dead code on perm checking from InodeSyncStream

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Support record the audit log for getMounttable operation.
Just add auditlog context.
No.
```
2022-08-03 22:53:40,239 INFO  AUDIT_LOG - succeeded=true	allowed=true	ugi=mbl,staff (AUTH=SIMPLE)	ip=/127.0.0.1:65311	cmd=getMountPointInfo(invokeUfs)	src=null	dst=null	perm=null	executionTimeUs=436
2022-08-03 22:53:51,628 INFO  AUDIT_LOG - succeeded=true	allowed=true	ugi=mbl,staff (AUTH=SIMPLE)	ip=/127.0.0.1:65332	cmd=getMountPointInfo(invokeUfs)	src=null	dst=null	perm=null	executionTimeUs=940
2022-08-03 22:54:00,779 INFO  AUDIT_LOG - succeeded=true	allowed=true	ugi=mbl,staff (AUTH=SIMPLE)	ip=/127.0.0.1:65348	cmd=getMountPointInfo(invokeUfs)	src=null	dst=null	perm=null	executionTimeUs=617
2022-08-03 22:54:14,247 INFO  AUDIT_LOG - succeeded=true	allowed=true	ugi=mbl,staff (AUTH=SIMPLE) …
```
> Support record audit log for getMountTable op

- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
TakeSnapshot in JournalStateMachine calls a Ratis function that needs to acquire a lock in the RaftServerProxy.
When the raft server is shutting down it takes the lock in RaftServerProxy then waits for the state machine thread thread to finish while holding this lock. This causes a deadlock.
This PR fixes this by ensuring takeSnapshot will not take this lock once shutdown has started.
No
> Fix journal shutdown deadlock

- underfs/obs/src/main/java/alluxio/underfs/obs/OBSOutputStream.java
delete temporary files when uploading files to OBS fails.
Currently does not delete temporary files when obs delete fails.
> Delete temporary files when uploading files to OBS fails

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Disable FileSystemMaster block integrity check by default.
This operation is very expensive. It causes failovers to take much too long in HA mode.
No.
> Disable block integrity check by default

- core/server/common/src/main/java/alluxio/master/PrimarySelector.java
- core/server/common/src/main/java/alluxio/master/PrimarySelectorClient.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftPrimarySelector.java
- core/server/common/src/test/java/alluxio/master/AbstractPrimarySelectorTest.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- core/server/master/src/test/java/alluxio/master/AlwaysStandbyPrimarySelector.java
- core/server/master/src/test/java/alluxio/master/ControllablePrimarySelector.java
- job/server/src/main/java/alluxio/master/FaultTolerantAlluxioJobMasterProcess.java
`PrimarySelector` and its implementations never throw in `start` or `stop`. I removed the Exception from the method signatures.
> Remove unnecessary exception from `PrimarySelector`

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Resolves https://github.com/Alluxio/alluxio/issues/15844
There was an outdated `catch (FileNotFoundException e)` which returned a `BucketNotFound` S3 Error code (HTTP 404). It was outdated because a check that the bucket path exists was added since that code had been written. Furthermore, we needed to return an empty list for the `children` to `ListBucketResults`.
> Fix S3 API writing objects yields BucketNotFound 404

- dev/jenkins/Dockerfile-jdk11
- dev/jenkins/Dockerfile-jdk8
to address the following error
ERROR:  Error installing jekyll:
The last version of public_suffix (< 6.0, >= 2.0.2) to support your Ruby & RubyGems was 4.0.7. Try installing it with `gem install public_suffix -v 4.0.7` and then running the current command again
public_suffix requires Ruby version >= 2.6. The current ruby version is 2.5.0
3. webui
> Fix jekyll installation in alluxio-maven dockerfiles

- webui/pom.xml
Bump up maven frontend plugin to fix the "cannot download node.js" issues on osx m1.  See the discussion here https://github.com/eirslett/frontend-maven-plugin/issues/952
Enable the development on macbook m1
no
> Bump up maven frontend plugin for m1 arm support

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Add configuration for Kerberos: 1) Allow user to specify Kerberos authentication Ufs HDFS. 2) Allow user to specify the location of krb5.conf file ; 3) allow user to enable autorenewal auth with keytab 
Tested out with Kerberos auth for Ufs HDFS. It failed without the change. 
no
> Add configuration for kerberos authentication for Ufs HDFS

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/FileSystemMergeJournalContext.java
- core/server/common/src/main/java/alluxio/master/journal/JournalContext.java
- core/server/common/src/main/java/alluxio/master/journal/JournalEntryMerger.java
- core/server/common/src/main/java/alluxio/master/journal/MasterJournalContext.java
- core/server/common/src/main/java/alluxio/master/journal/MergeJournalContext.java
- core/server/common/src/main/java/alluxio/master/journal/NoopJournalContext.java
- core/server/common/src/main/java/alluxio/master/journal/StateChangeJournalContext.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemJournalEntryMerger.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java
- core/server/master/src/main/java/alluxio/master/file/LostFileDetector.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
- core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java
- core/server/master/src/test/java/alluxio/master/file/AccessTimeUpdaterTest.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemJournalEntryMergerTest.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- core/server/master/src/test/java/alluxio/master/file/PermissionCheckerTest.java
- core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
- core/server/master/src/test/java/alluxio/master/file/meta/LockedInodePathTest.java
- core/server/master/src/test/java/alluxio/master/file/replication/ReplicationCheckerTest.java
- core/server/master/src/test/java/alluxio/master/journal/JournalContextTest.java
- microbench/src/main/java/alluxio/inode/InodeBenchBase.java
- tests/src/test/java/alluxio/server/ft/FileSystemMasterFaultToleranceIntegrationTest.java
- tests/src/test/java/alluxio/server/ft/FileSystemMasterMergeJournalContextIntegrationTest.java
- tests/src/test/java/alluxio/server/health/BlockMasterIntegrityIntegrationTest.java
1. Created a new FileSystemMergeJournalContext to merge journals on a single inode object together before they get flushed.
2. Force flush journals before the locked inode path is closed.
Today our current journal are applied different between primary and standby and this creates inconsistencies. The goal of this PR is to mitigate it.
Change 1 reduces the change on a standby master to see partial changes & intermediate metadata. 
Change 2 slightly reduces the race condition and ensures the ordering of journals after FileSystemMergeJournalContext is introduced. 
There will be a following PR to add locks on the standby master side.
3. addition or removal of property keys
4. webui
> Merge journals & flush journals before lock release

- core/common/src/main/java/alluxio/AbstractMasterClient.java
- core/common/src/main/java/alluxio/master/selectionpolicy/AbstractMasterSelectionPolicy.java
- core/common/src/main/java/alluxio/master/selectionpolicy/MasterSelectionPolicy.java
- core/common/src/main/java/alluxio/master/selectionpolicy/SelectionPolicyAnyMaster.java
- core/common/src/main/java/alluxio/master/selectionpolicy/SelectionPolicyAnyStandbyMaster.java
- core/common/src/main/java/alluxio/master/selectionpolicy/SelectionPolicyPrimaryMaster.java
- core/common/src/main/java/alluxio/master/selectionpolicy/SelectionPolicySpecifiedMaster.java
- core/common/src/test/java/alluxio/AbstractMasterClientTest.java
Enhance the abstract master client with the master selection policy that allows a client to connect to primary master / standby master or a specific master. This refactoring is a prerequisite for the following master side works. 
Introduced different types of MasterSelectionPolicy(/ies)
N/A
> Refactor abstract master client with master selection policy

- templates/strapdown.html.hbs
[Hosting](https://docs.alluxio.io/scripts/strapdown.min.js) strapdown script ourselves since the link we were originally relying on is not available anymore. This script is used to help create styled doc pages in Markdown. 
https://strapdownjs.com/v/0.2/strapdown.js is no longer available.
REST docs
> [DOCFIX] Use our own hosted strapdown script for REST docs

- core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
- core/common/src/test/java/alluxio/master/PollingMasterInquireClientTest.java
- core/server/common/src/main/java/alluxio/master/AbstractPrimarySelector.java
- core/server/common/src/main/java/alluxio/master/PrimarySelector.java
- core/server/common/src/main/java/alluxio/master/journal/DefaultJournalMaster.java
- core/server/common/src/main/java/alluxio/master/journal/JournalMaster.java
- core/server/common/src/main/java/alluxio/master/journal/JournalMasterClientServiceHandler.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftPrimarySelector.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalMultiMasterPrimarySelector.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSingleMasterPrimarySelector.java
- core/server/common/src/test/java/alluxio/master/AbstractPrimarySelectorTest.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
- core/server/master/src/test/java/alluxio/master/AlwaysStandbyPrimarySelector.java
- core/transport/src/main/proto/grpc/journal_master.proto
- core/transport/src/main/proto/proto.lock
- job/server/src/main/java/alluxio/master/AlluxioJobMasterProcess.java
1. In PollingMasterInquireClient, replace the current version service call with a new introduced GetNodeState grpc endpoint which returns if the node is primary or standby directly, which internally gets the node state from the PrimarySelector.  
2. Replace the PrimarySelector.State with a protobuf model NodeState.
Currently PollingMasterInquireClient determines which master is the primary master by polling each client to see which one responds. This is a bit hacky and based on the assumption that standby masters don't have a gRPC server. So we replace the current call with a new call to GetNodeState endpoint that tells if the node is primary or not directly. 
N/A
> Determine the primary master address by calling GetNodeState endpoint

- integration/docker/csi/alluxio/nodeserver.go
Both `nodeID` and `volumeID` are needed for the fuse pod because:
1. If different volumes are used on the same node, we need to create different fuse pod, so volume ID is needed.
2. If same volume is used across different nodes, we need to create fuse pods on every node, so node ID is needed.
> Fix CSI nodeserver

- core/common/src/main/java/alluxio/Constants.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/util/io/PathUtils.java
- core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Add a configurable temp ufs dir.
Add a configurable temp ufs dir. So far the dir is a fixed one under "/", some users may have concerns about that.
The configurable dir config item:
alluxio.underfs.persistence.async.temp.dir
eg:
alluxio.underfs.persistence.async.temp.dir=.ufs_persistence_temp_dir
> Add a configurable temp ufs dir

- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
Introduced in https://github.com/Alluxio/alluxio/pull/16067/, the timeout for the master in `AbstractLocalAlluxioCluster` is set to 20s. This brings about >75% failure rate of the test `updateConfIntegrationTest` in github actions. 
Tested on different machines, running same tests the slower machine can be 5x slower than the faster machine. Since Github actions machines are not considered powerful, set the timeout to 30s.
> Set longer timeout for localAlluxioCluster to get ready

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
When we have a large cluster, we found that is very slowly to register all workers to master. Because of default 25 workers  register a time and the lease lasts for 1 minute since the worker have finished the register. And I found when not use stream register, it will release lease. So I think it should be the same as before.
Greatly increase the worker registration speed when you have a large scale cluster.
no
> Fix worker stream register forget release lease

- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
dockerfile-common.sh is removed by #16101. Remove it from generate tarball script.
> Remove dockerfile-common.sh from generating tarball

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- core/server/master/src/test/java/alluxio/master/file/meta/AsyncUfsAbsentPathCacheTest.java
- core/server/master/src/test/java/alluxio/master/file/meta/LazyUfsBlockLocationCacheTest.java
- libexec/alluxio-config.sh
1. Add method `validateMount` in `MountTable` 
2. When doing mount in `DefaultFileSystemMaster`, load the directory metadata first, then modify the `MountTable` 
One major challenge we face in #15578 is that when the mount point is added to `MountTable`, the corresponding inodes don't exist yet. That makes our proposed change in #15578 hard because by using a `Trie<Inode>` data structure the inode must exist first. 
In this change we propose creating the inode before updating the MountTable, so when we update the MountTable, we can just update the `MountTableTrie` with the correct Inode.
Nope
> Create inode before updating the MountTable

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
When we have a large cluster, we found that is very slowly to register
all workers to master. Because of default 25 workers register a time and
the lease lasts for 1 minute since the worker have finished the
register. And I found when not use stream register, it will release
lease. So I think it should be the same as before.
Greatly increase the worker registration speed when you have a large
scale cluster.
no
pr-link: Alluxio/alluxio#16137
change-id: cid-20fd21e04cb74c5861cd692764a4b5f3db896178
> Port changes of [#16137] to branch-2.8

- core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
- core/common/src/test/java/alluxio/resource/DynamicResourcePoolTest.java
Allow dynamic resource pool returning resources in the queue in a FIFO manner.
Currently, the resource pool always returns the last returned resource on acquire(). This creates some imbalance and might cause some issues if the resource is a client. This changes mitigates the issue. 
N/A
> Allow dynamic resource pool returning resources using fifo strategy

- conf/log4j.properties
Set the log4j.additivity of the audit log to false.
Audit logs do not need to be appended to service logs.
no.
> Set log4j.additivity of the audit log to false

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/MultipartUploadCleaner.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
- core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
- core/server/proxy/src/test/java/alluxio/proxy/s3/S3RestServiceHandlerTest.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
- tests/src/test/java/alluxio/client/rest/TestCaseOptions.java
- tests/src/test/java/alluxio/client/rest/TestCaseOptionsTest.java
This PR is the successor of https://github.com/Alluxio/alluxio/pull/16135
---
Introduced on top of that PR is the following:
- Fixes how the S3 API sets ACL permissions and mode bits on files so that buckets and their objects are owned by a user corresponding to the "Authorization" header
- Disables requirement for "Authorization" header when `alluxio.security.authentication.type=NOSASL`
> Require valid "Authorization" header in S3 API Proxy

- core/common/src/main/java/alluxio/exception/runtime/OutOfRangeRuntimeException.java
- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/UfsIOManager.java
- core/server/worker/src/test/java/alluxio/worker/block/UfsIoManagerTest.java
- core/transport/src/main/proto/grpc/block_worker.proto
- core/transport/src/main/proto/proto.lock
make ufsiomanager take byterbuffer as input so we can allocate bytebuffer from buffer pool later on
better memory usage
na
> Allocate buffer in load api

- core/server/common/src/main/java/alluxio/master/journal/AbstractJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/JournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalWriter.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSystem.java
- tests/src/test/java/alluxio/testutils/master/FsMasterResource.java
Some key journal method have exceptions in their method signatures where it is not necessary, and in most cases where the method does not even throw said exception.
This PR removes those.
> Remove exception from journal method signatures

- stress/common/src/main/java/alluxio/stress/client/ClientIOTaskResult.java
Divide 1000 to get megabytes per second instead of megabytes per millisecond.
> Fix clientIO stressbench throughput calculation

- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioFileSystem.java
- core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
Fix #14648.
Followup to #14649.
Currently, the `alluxio.hadoop.AlluxioFileSystem` (that offers compatibility with Hadoop 2.x) reports its default port as 19998 through its method `#getUriDefaultPort`. This contrasts with the `alluxio.hadoop.AbstractFileSystem` and `alluxio.hadoop.FileSystem`  who have default port 0 (as they do not override the `#getDefaultPort` method).
This mismatch causes yarn jobs to fail when using Alluxio logical URIs.
We can see [here](https://github.com/apache/hadoop/blob/a3b9c37a397ad4188041dd80621bdeefc46885f2/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/DelegateToFileSystem.java#L170) that `org.apache.hadoop.fs.DelegateToFileSystem#getUriDefaultPort` calls `org.apache.hadoop.fs.FileSystem#getDefaultPort` by default. 
This PR therefore …
> Ensure the HadoopFS default port is the same across all hadoop fs

- core/server/common/src/main/java/alluxio/master/journal/JournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/noop/NoopJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSystem.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- core/server/master/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
- minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTestFaultTolerance.java
Currently, when calling `bin/alluxio fsadmin journal checkpoint` on a cluster with a single embedded journal master, the information about the new snapshot does not get propagated back to Ratis. This in turn means that logs are not pruned and the snapshot is ignored on master restart. 
This fix makes sure the new snapshot is taken through Ratis so that all appropriate functions may be executed. 
Removed `mIsSnapshotAllowed` from `RaftJournalSystem` as it is functionally a duplicate of `mIsLeader` in `JournalStateMachine`.
Redo of #16117.
> Fix single master embedded journal checkpoint

- core/common/src/main/java/alluxio/Sessions.java
- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
use Constant for session id of load API. In this case, we can pick up the temporary block when the master wants to retry failed blocks. This is a temporary fix only and would be replaced after we implement the new session design in the worker.
Also add some error logging.
bug fix
na
> Fix load sessionId

- integration/fuse/src/main/java/alluxio/fuse/auth/LaunchUserGroupAuthPolicy.java
- integration/fuse/src/test/java/alluxio/fuse/auth/AbstractAuthPolicyTest.java
Avoid chown if the file already has correct owner and group
- The client may send a request to change owner&group even the file already has correct values
- The request may be rejected because "chown" needs supergroup privilege
No
> Avoid chown if the file already has correct owner and group

- stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
Add POSIX API to clientIO stressbench. Doc will be updated in the next pr.
To use the posix api, set `--base` to the alluxio fuse mount point.
> Add posix api to StressClientIOBench

- integration/fuse/bin/alluxio-fuse
Add a parameter "-t" to set the sleep time before checking the AlluxioFuse process.
Sometimes `alluxio-fuse mount` outputs `Successfully mounted` and returns `0` even failed, for example
```
$ integration/fuse/bin/alluxio-fuse mount /mnt/not_exist/projects /projects
Path /mnt/not_exist/projects is not mounted
Starting AlluxioFuse process: mounting alluxio path "/projects" to local mount point "/mnt/not_exist/projects"
Successfully mounted Alluxio to /mnt/not_exist/projects.
See /opt/alluxio-2.7.1-sdi-016/logs/fuse.log for logging messages
$ echo $?
0
$ jps -m |grep -i fuse
$
```
With the added option `-t`, the issue can be solved by setting a bigger value as below
```
$ integration/fuse/bin/alluxio-fuse mount -t 5 /mnt/not_exist/projects /projects
Path /mnt/not_exist/projects is not …
```
> Support setting sleep time for alluxio-fuse mount

- integration/fuse/bin/alluxio-fuse
Fix alluxio-fuse unmount to get the right pid when no options provided during mounting. 
I submitted a PR [Fix alluxio-fuse unmount to get the right pid](https://github.com/Alluxio/alluxio/pull/15897) about two months ago. For that PR, I was always testing with setting mount options. For example, `-o default_permissions`. 
Now I found that (with options)/(without options) made the matching pattern have different indexes, and the solution is to make the pattern has consistent indexes.
No
> Fix alluxio-fuse unmount to get the right pid when no options

- core/server/common/src/main/java/alluxio/master/AbstractPrimarySelector.java
- core/server/common/src/main/java/alluxio/master/PrimarySelector.java
- core/server/common/src/test/java/alluxio/master/AbstractPrimarySelectorTest.java
- core/server/master/src/test/java/alluxio/master/AlwaysStandbyPrimarySelector.java
Replace the lock with volatile for the state variable in PrimarySelector because the state assignment is atomic and doesn't depend on any previous values.
Provide a getUnsafe() method to read the variable without adding a lock.
Improve the read performance of the primary selector.  
N/A
> Add getUnsafe() interface for PrimarySelector

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
Initialize AuditLog writer in WebServer for proxy.
It is obviously unreasonable to create an AsyncUserAccessAuditLogWriter for every request. This may cause OutOfMemoryError as follows.
```
java.lang.OutOfMemoryError : unable to create new native Thread
```
No.
> Initialize AuditLog writer in WebServer for proxy

- core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketResult.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
Add empty string check for delimiter.
For MinIO clients, commands such as' ls - r' will set the delimiter to an empty string.
No.
> Add empty string check for delimiter

- shell/src/main/java/alluxio/cli/fs/command/ChownCommand.java
- shell/src/test/java/alluxio/cli/fs/command/ChownCommandTest.java
Allow dot in chown username or groupname.
Reasons
1. "chown" in hdfs supports a user/group with a dot
2. alluxio internal also supports it, such as "alluxio fs ls"
3. Dot is also allowed in gmail's account, which is registered as usernames in many cases
Otherwise the following behaviour is strange
No
> Allow dot in chown username or group

- core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
- tests/src/test/java/alluxio/client/rest/TestCaseOptions.java
This PR explicitly sets the mode bits for all S3 API gRPC writes instead of relying on implicit parent directory perms.
- Theoretically writes were supposed to inherit the parent folder's (bucket's) mode bits of `770` but in reality they were committed as `755` for directories and `644` for files.
> Fix S3 API file mode bits to prevent unauthorized reads

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
Add direct mem used metrics
Sometimes the direct mem used is helpful for troubleshooting.
The metrics would look like:
"Master.pool.direct.mem.used" : {
"value" : 1138778
},
NA
> Add direct mem used metrics

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
This PR will run the async write in call's thread when the queue is full.
Prevent the rejection of the async write during busy time
no
> Run async write in caller thread when queue is full for local cache

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/main/java/alluxio/master/file/MetadataSyncLockManager.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataConcurrentTest.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataMetricsTest.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTestBase.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- core/server/master/src/test/java/alluxio/master/file/MetadataSyncLockManagerTest.java
- tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java
Update the metadata sync logic to avoid concurrent metadata sync on the same path #16241
If multiple requests attempt to sync the same directory, the metadata sync might happen over and over and bring huge load to UFS.
1. Larger lock scope -> previously the Inode Path Lock will be RELEASED of the metadata sync of the sync uri root is done and the children are processed by worker threads which they will acquire locks separately. This means that once the root sync is done, another request can come in and trigger another sync. With this patch, this won't be available any more. If you do a sync /, the whole alluxio inode tree will be blocked from another sync until it's done. Though this doesn't block other threads read the directory (e.g. getFileInfo or ListStatus, because they don't use the …
> Avoid and dedup concurrent metadata sync

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
respect prefix param to avoid recursive ls on root dir
when s3 client issues list-objects with --prefix flag on a particular subfolder  ( /bucket/folder1/) but without no --delimiter flag, this should be a recursive listing on  /bucket/folder1/   but instead s3 proxy is ignoring this flag and end up shooting recursive listing on /bucket, with ramification of generating unnecessary metadata sync in the backend. 
N/A
> Respect prefix param to avoid recursive ls on root dir

- core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStore.java
Remove unnecessary log in memory page store
The log of the cache eviction is polluting the log on presto side 
no
> Remove unnecessary log in memory page store

- core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
> Change synchronized on FileSystemContext to avoid deadlock

- core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataMetricsTest.java
- core/server/master/src/test/java/alluxio/underfs/UfsStatusCacheTest.java
During a recursive meta data sync, when a child directory is set to be fetched from the UFS it will be done in a separate thread. Another thread will then use this perfected data to sync the path. Currently if this thread starts running before the prefetch is complete, it will cancel the prefetch and relaunch it. This PR changes this so it will instead wait for the thread to complete.
> Avoid canceling duplicate metadata sync prefetch job

- integration/docker/Dockerfile
By adding an argument to specify the java version, users will be able to launch Alluxio with java 11 in containers.
Only java 8 and java 11 are supported. If users try build with other versions, the build would fail with error `failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed`. It is not intuitive at all but there is no way to print an custom error message because the error happens when it's trying to load the metadata for all images used in the dockerfile, before any script runs, where we can put our custom error message.
This is the first step of a series of updates of the images. The documentation will be updated later.
> Enable java 11 in alluxio base image

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
1) Fixed the issue of unable to do aws s3 cp when the source objects has special characters in it. The source object are specified in the header x-amz-copy-source which is url encoded, it should be decoded to give the correct source object name.
2) Add access log to display req http verb / path / query / http body content length / time for processing the request. As well in the debug mode the request and response headers will be displayed.
3) Fixed when the uploadId is not found in multipart upload, it should return NoSuchUpload error code instead of NoSuchKey.
To fix incorrect behavior in aws cp and multipart upload APIs.
No.
> Fix aws s3 cp with source object having special characters in it

- core/common/src/main/java/alluxio/util/io/PathUtils.java
An ArrayList that will eventually be converted to an Array is used to hold the common components in `PathUtils.findLowestCommonAncestor()` .  It is better to use Array because the length of ArrayList is fixed in the method.
`ArrayList.toArray()` dose a copy. Using Array can reduce one copy if we know very well how many elements there are.
NA
> Avoid one copy in PathUtils.findLowestCommonAncestor

- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
In the comment `TieredBlockStore` is stated to be thread safe. Therefore I'm updating the tag assuming the comment is more up-to-date.
> [SMALLFIX] Add ThreadSafe tag to TieredBlockStore

- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
LocalPageStore delete pageId cloud ignore parent path NoSuchFileException when parent path is deleted by other thread in a benign race
[fix  #16250]
None.
> Ignore parent path NoSuchFileException when localPageStore delete pageId

- core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
- core/common/src/main/java/alluxio/master/MasterInquireClient.java
Add an rpc call that keeps the client resource and refactor FileSystemContext to allow specifying the master addresses.
Additional functionality needed for new rpc calls that must keep the connection open and specify master addresses.
No
> Refactor FileSystem and RPC client calls

- job/server/src/main/java/alluxio/master/job/tracker/CmdJobTracker.java
- job/server/src/main/java/alluxio/master/job/tracker/DistLoadCliRunner.java
- shell/src/main/java/alluxio/cli/fs/command/AbstractDistributedJobCommand.java
- shell/src/main/java/alluxio/cli/job/command/GetCmdStatusCommand.java
- shell/src/main/java/alluxio/cli/util/DistributedCommandUtil.java
- tests/src/test/java/alluxio/client/cli/job/GetCmdStatusCommandTest.java
If no actual load happens on the server side, then the command just outputs "Job is completed successfully." as its default 
success state.
An example is below:
**Example 1:**
➜  alluxio git:(patch-fix) bin/alluxio fs distributedLoad /dir3
Please wait for command submission to finish..
Submitted successfully, jobControlId = 1665695558406
Waiting for the command to finish ...
Get command status information below:
Total completed file count is 0, failed file count is 0
Finished running the command, jobControlId = 1665695558406
➜  alluxio git:(patch-fix) bin/alluxio job getCmdStatus  1665695558406
Get command status information below:
Total completed file count is 0, failed file count is 0
**Example 2:**
Create an empty dir and check the output.
➜  alluxio git:(patch-fix) ✗ bin/alluxio fs …
> Fix unwanted message for empty job of distributedLoad

- core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
- core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
- core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
- core/server/master/src/main/java/alluxio/master/file/meta/SyncCheck.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- core/transport/src/main/proto/proto.lock
- integration/fuse/src/test/java/alluxio/fuse/cli/MockFuseFileSystemMasterClient.java
Add the client interface to mark a path as needing synchronization with the UFS.
`void invalidateSyncPath(AlluxioURI path) throws AlluxioStatusException`
> Add invalidation client interface

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
- core/server/master/src/main/java/alluxio/master/file/meta/SyncCheck.java
- core/server/master/src/test/java/alluxio/master/file/meta/MountTableTest.java
Refactor mount table so that resolution are static classes, and internal state is not static.
Refactor create directory, to include boolean indicating if is was created by a metadata load.
> Refactor mount table and directory create

- core/server/master/src/main/java/alluxio/master/file/meta/UfsSyncPathCache.java
Cleaning a path is expensive operation and needs to be performed only once on the initial string, instead of every time getParent is called.
> Reduce calls to clean path

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
GetInfo does not need to load descendants, so its sync check for descendants should be set to NONE.
> Set metadata load type to none for getinfo

- core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
- shell/src/main/java/alluxio/cli/fs/command/CopyFromLocalCommand.java
When calling precondition or debug logs, avoid creating strings that are not used.
Also the precondition check on line 503 of JournalStateMachine is put behind a debug flag, as that operation is extremely expensive (it causes the most memory allocation of all operations on the standby master).
> Reduce creation of unused strings

- core/server/master/src/main/java/alluxio/master/throttle/SystemMonitor.java
Fix the time used to calculate the gap between two heartbeats
The time unit should be mini seconds, it was using nano seconds.
NA
> Fix the time used to calculate the gap between two heartbeats

- core/common/src/main/java/alluxio/resource/CloseableIterator.java
- core/server/master/src/main/java/alluxio/master/metastore/ReadOnlyInodeStore.java
- core/server/master/src/main/java/alluxio/master/metastore/heap/HeapInodeStore.java
- core/server/master/src/test/java/alluxio/master/metastore/InodeStoreTest.java
- core/server/master/src/test/java/alluxio/master/metastore/caching/CachingInodeStoreMockedBackingStoreTest.java
Fix how `CloseableIterator` is closed to avoid false leak alarms.
For places where an iterator is associated with some resources that need to be closed, we use `CloseableIterator` which requires explicit closing. Additionally we use the leak detector to catch unclosed ones (if they are enabled).
This change fixes below leak detection complaints:
```
2022-10-10 14:15:30,225 ERROR AlluxioResourceLeakDetector - LEAK: CloseableResource.close() was not called before resource is garbage-collected. See https://docs.alluxio.io/os/user/stable/en/operation/Troubleshooting.html#resource-leak-detection for more information about this message.
Recent access records: 
Created at:
alluxio.resource.CloseableResource.<init>(CloseableResource.java:35) …
```
> Avoid CloseableIterator leak false alarms

- core/server/common/src/main/java/alluxio/util/TarUtils.java
- core/server/common/src/test/java/alluxio/util/TarUtilsTest.java
To store and distribute RocksDB snapshot files, we compress them into a `.tar.gz` file. This file fails to be written if the group id or user id being operated under is too large: `group id '__' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit` or `user id '__' is too big ( > 2097151 ).`
This PR resolves this issue.
> Fix error in snapshot-taking when using large group ids

- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
When master gain/regain primacy they create a new RPC server and executor related metrics along with it. These metrics do not get reregistered when a master is promoted to leader for a second time. This PR fixes this problem.
> Fix gauges when creating a new rpc server

- core/server/common/src/main/java/alluxio/util/TarUtils.java
- core/server/common/src/test/java/alluxio/util/TarUtilsTest.java
To store and distribute RocksDB snapshot files, we compress them into a `.tar.gz` file. This file fails to be written if the group id or user id being operated under is too large: `group id '__' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit` or `user id '__' is too big ( > 2097151 ).`
This PR resolves this issue.
[This is an manually-generated PR to cherry-pick committed PR Alluxio/alluxio#16365 into target branch branch-2.8]
> Port changes of [#16365] to branch-2.8

- core/server/common/src/main/java/alluxio/master/journal/FileSystemMergeJournalContext.java
- core/server/common/src/main/java/alluxio/master/journal/MasterJournalContext.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemJournalEntryMerger.java
- core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
Make journal context thread safe to address potential data race issues. During metadata sync, the journal context is shared across multiple metadata sync inode threads.
To address potential data race issues.
N/A
> Make journal context thread safe

- dev/github/run_docker.sh
- dev/github/run_tests.sh
Adds a fork count environment variable so that the number of concurrent forks to run during a test can be set in the GitHub tests yml file.
> Add fork count option to alluxio github test scripts

- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
When implementing `org.apache.hadoop.fs.FileSystem` we are provided with a default implementation for `#canonicalizeUri(URI)` (found [here](https://github.com/apache/hadoop/blob/454157a3844cdd6c92ef650af6c3b323cbec88af/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L400)). This default implementation leaves the URI unaltered if the implementation has default port of 0. 
#16207 changed the default port from 0 to 1998. This PR overrides `#canonicalizeUri(URI)` so that it can continue to be unaltered as it was before #16207.
> Fix AbstractFileSystem URI parsing

- core/client/fs/src/main/java/alluxio/client/block/BlockStoreClient.java
- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
Failover to an available worker while the current reading worker goes down
Fix #16295
No
> Support failover worker while reading

- core/server/worker/src/main/java/alluxio/worker/block/UfsInputStreamCache.java
Fix string format specifier `%d` in `Preconditions.checkArgument` error message template.
any other format specifiers like `%d` are not recognized at the method of `Preconditions.checkArgument`, only `%s` is accepted.
none
Fixed https://github.com/Alluxio/alluxio/pull/642 https://github.com/Alluxio/new-contributor-tasks/issues/642
> [SMALLFIX] Fix incorrect error message template in UfsInputStreamCache

- core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
- core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
- core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
- core/server/master/src/main/java/alluxio/master/file/meta/UfsSyncPathCache.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncTest.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- core/transport/src/main/proto/proto.lock
- docs/en/operation/User-CLI.md
- integration/fuse/src/test/java/alluxio/fuse/auth/AbstractAuthPolicyTest.java
- integration/fuse/src/test/java/alluxio/fuse/cli/MockFuseFileSystemMasterClient.java
- shell/src/main/java/alluxio/cli/fs/command/NeedsSyncCommand.java
- tests/src/test/java/alluxio/client/cli/fs/command/NeedsSyncCommandIntegrationTest.java
Adds cli for marking a path as needing sync with the UFS.
New cli as follows
`bin/alluxio fs needsSync {path}`
> Add cli for marking a path as needing sync with UFS

- tests/src/test/java/alluxio/client/cli/fs/command/DistributedCpCancelTest.java
- tests/src/test/java/alluxio/client/cli/job/DistributedCommandsStatsTest.java
1. For DistributedCommandsStats, increase file size to persist to allow enough time for the cancel to happen.
2. For DistributedCpCancel, increase test timeout to exceed (90s) local cluster start timeout (1 min).
> Fix timeouts for DistributedCpCancel and DistributedCommandsStats tests

- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
Throw Error when there's an Error so the worker could crash and let K8s restart the worker.
Without this, Worker would still pretend to be functional if there's OOM.
na
> Fix worker swallow OOM

- pom.xml
- shaded/client/pom.xml
Fix shaded client dependencies for prestodb's alluxio connector
There is some code in prestodb are still using the alluxio-table-client
no
> Fix shaded client dependencies for prestodb's alluxio connector

- core/client/fs/src/main/java/alluxio/client/block/stream/GrpcBlockingStream.java
Fix the problem of exception being swallowed
When an OOM exception occurs on the client side, currently LOG is
`Received error io.grpc.StatusRuntimeException: UNKNOWN for stream (Zero Copy GrpcDataReader)`
The actual LOG that is helpful for troubleshooting is as follows, but it was swallowed:
```
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:645)
...
```
No
> Print stack on stream error

- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
This PR can fix the OOM Error no longer reply to client issue.
```
2022-10-19 11:41:38,397 WARN  GrpcBlockingStream - Client did not receive message from stream, will wait again. totalWaitMs: 60006 clientClosed: false clientCancelled: false serverClosed: false description: Zero Copy GrpcDataReader
2022-10-19 11:42:38,404 WARN  GrpcBlockingStream - Client did not receive message from stream, will wait again. totalWaitMs: 120013 clientClosed: false clientCancelled: false serverClosed: false description: Zero Copy GrpcDataReader
2022-10-19 11:43:38,409 WARN  GrpcBlockingStream - Client did not receive message from stream, will wait again. totalWaitMs: 180018 clientClosed: false clientCancelled: false serverClosed: false description: Zero Copy GrpcDataReader
2022-10-19 11:44:38,415 WARN …
```
> Make worker error propagate to client

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Backup delegation in HA should be the preferred default because it doesn't lock the primary master
> Enable backup delegation by default

- core/client/fs/src/main/java/alluxio/client/block/policy/CapacityBaseRandomPolicy.java
- core/client/fs/src/test/java/alluxio/client/block/policy/CapacityBaseRandomPolicyTest.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
This effectively reverts  #15423 (https://github.com/Alluxio/alluxio/commit/3b1bdb3b80e56d3528bc6f41a923da6e28e808ee)
For the problem that #15423 was trying to solve, a new policy is proposed in #16237.
1. local cache is useless because BlockLocationPolicy will be created every time, because it is not a singleton
2. local cache can only be useful to limit replica in each client, but useless for a cluster with many client (eg. presto workers ) because each client has different cache result.
3. additionally, in general, block location policies should not be concerned about block replication, as master will take care of that.
Two property keys are deprecated: `alluxio.user.ufs.block.read.location.policy.cache.size` and `alluxio.user.ufs.block.read.location.policy.cache.expiration.time`, as …
> Remove caching for CapacityBaseRandomPolicy

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
- core/server/proxy/src/test/java/alluxio/proxy/s3/S3RestServiceHandlerTest.java
fix out of bound error in parsing s3 Authorization header
if the authorization header have not the "/", the out of bound error will happen, and then Alluxio proxy will return an `500 Internal Error` to client.
> Fix out of bound error in parsing s3 Authorization header

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
Add metrics for direct memory
monitoring and debugging
new metrics
"Master.pool.direct.mem.used" : {
"value" : 1228802
},
"Worker.pool.direct.mem.used.10_0_0_206" : {
"value" : 8193
},
> Add direct mem metrics

- tests/src/test/java/alluxio/client/fs/io/FileInStreamIntegrationTest.java
Currently the test asyncCacheFirstBlock is flaky, when the test is running extremely slow, and after the worker reports the newly cached blocks to master, the test will fail. The original time interval is 1000ms and may be small. Increasing the worker heartbeat in the test to 2000ms may allow the test to pass before worker reporting to master.
> Increase worker heartbeat time for asyncCache tests

- core/common/src/main/java/alluxio/util/CommonUtils.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
Throw Error after reply error to client so worker would crash because of Error and k8s can restart unhealthy worker
na
na
> Throw Error after reply error to client

- stress/shell/src/main/java/alluxio/stress/cli/suite/AbstractMaxThroughput.java
Fix use of a wrong variable in `AbstractMaxThroughput.computeMaxThroughput`.
Introduced in #14819, the number of test files prepared by the benchmark is controlled by `perWorkerThroughput`
https://github.com/Alluxio/alluxio/blob/4b43e50eb294542ab64687ab48e748feb2ad0b6f/stress/shell/src/main/java/alluxio/stress/cli/suite/AbstractMaxThroughput.java#L131
while it should have been `cluster-wide all-workers throughput`. Before the change:
https://github.com/Alluxio/alluxio/blob/bec0c356d0a4f3ecf9fcc7b504c55df06d353e4c/stress/shell/src/main/java/alluxio/stress/cli/suite/MaxThroughput.java#L100-L102
where `next` is the current throughput for all workers:
https://github.com/Alluxio/alluxio/blob/bec0c356d0a4f3ecf9fcc7b504c55df06d353e4c/stress/shell/src/main/java/alluxio/stress/cli/suite/MaxThroughp …
> Fix misuse of variable in computeMaxThroughput

- core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
fix usage for acquireMasterClientResource() in AlluxioFileInStream with try-with-resource
resource leak
none
> Use try-with-resource on FSMClient to avoid leak

- core/server/master/pom.xml
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
- core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
- pom.xml
Introduce the HashSet from fastutil (https://fastutil.di.unimi.it/) to replace the current java HashSet in MasterWorkerInfo
MasterWorkerInfo persisted in heap, has become a bottleneck for persisting more metadata in alluxio masters. This is mainly because it contains a block id set. If there are too many workers and too many blocks, this set will exhaust the memory.
A Long object in a java HashSet will take about 64 bytes memory. However, there are some third party collection libraries for primitive types. By getting rid of the boxing and unboxing, tons of memories can be saved and we can also achieve some performance boost. 
By using the LongOpenHashSet, we cut down the size of the hash map to a quarter and save 75% memory.     
Fastutil is one of the most used java alternatives .
There …
> Optimize MasterWorkerInfo memory usage by introducing fastutil Set

- tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java
- tests/src/test/java/alluxio/server/ft/journal/JournalMigrationIntegrationTest.java
After we changed delegated backup to enabled by default, a few UTs are automatically running on delegated backup and that affected the stability (in some tests the cluster is not fully mocked so delegated backup might not even work). This change disables delegated backup in UTs that are irrelevant.
A few tests are updated and the numbers are from my local runs:
JournalBackupIntegrationTest#backupRestoreZk
enabled - 1 out of 10 success
disabled - 10 out of 10 success
JournalBackupIntegrationTest#backupRestoreEmbedded
enabled - 0 out of 10 success
disabled - 0 out of 10 success
// The flakiness in this test is irrelevant to backup but to election
JournalMigrationIntegrationTest#migrate
enabled - 0 out of 10 success
disabled - 10 out of 10 success
> Disable delegated backup in irrelevant UTs

- tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java
- tests/src/test/java/alluxio/server/ft/journal/JournalMigrationIntegrationTest.java
After we changed delegated backup to enabled by default, a few UTs are automatically running on delegated backup and that affected the stability (in some tests the cluster is not fully mocked so delegated backup might not even work). This change disables delegated backup in UTs that are irrelevant.
A few tests are updated and the numbers are from my local runs:
JournalBackupIntegrationTest#backupRestoreZk
enabled - 1 out of 10 success
disabled - 10 out of 10 success
JournalBackupIntegrationTest#backupRestoreEmbedded enabled - 0 out of 10 success
disabled - 0 out of 10 success
// The flakiness in this test is irrelevant to backup but to election
JournalMigrationIntegrationTest#migrate
enabled - 0 out of 10 success
disabled - 10 out of 10 success
pr-link: Alluxio/alluxio#16482
change-id: …
> Port changes of [#16482] to branch-2.9

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java
Add flag to control whether to trigger metadata sync on UFS root after a backup restore or not.
> Add flag sync root

- core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
Allow metadata cache used in process other than alluxio client, e.g. alluxio fuse inside alluxio worker
Worker fuse performance with metadata cache option enabled has worse performance because no actual metadata cache happening
Performance
> Fix worker fuse metadata cache

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/wire/HeartBeatResponseMessage.java
- core/server/master/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
- core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
- core/server/master/src/test/java/alluxio/master/block/ConcurrentBlockMasterTest.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockMasterClientTest.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- core/transport/src/main/proto/grpc/block_master.proto
- core/transport/src/main/proto/proto.lock
- stress/shell/src/main/java/alluxio/stress/cli/WorkerHeartbeatBench.java
- tests/src/test/java/alluxio/client/fs/BlockMasterRegisterStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/fs/BlockWorkerRegisterStreamIntegrationTest.java
- tests/src/test/java/alluxio/server/ft/MasterFaultToleranceIntegrationTest.java
The information of the number of replications of blocks in the clusters can help us optimize the evictor algorithm. For example, we can first delete the block with more replications in other workers to decrease the times to download data.
This PR has finished these things:
1. Original heartbeat just send a command to worker. We changed into a new class 'HeartbeatResponseMessage' to contain more messages. 
2. When heartbeat, the worker tells the master which blocks are added or removed, and the master tells the worker the how each block replication number have been changed from last heartbeat.  And the master send these messages to the worker.
> Add the replica number feature through heartbeat

- core/common/src/main/java/alluxio/concurrent/ClientRWLock.java
- core/common/src/test/java/alluxio/concurrent/ClientRWLockTest.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockLockManager.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
- integration/fuse/src/main/java/alluxio/fuse/lock/FuseReadWriteLockManager.java
- tests/src/test/java/alluxio/client/fuse/file/AbstractFuseFileStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/file/FuseFileInOrOutStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/file/FuseFileInStreamIntegrationTest.java
Fix the bug introduced by https://github.com/Alluxio/alluxio/pull/16377.
Change thread based lock to session based lock to avoid IllegalMonitorException when a thread tries to unlock a lock locked by another thread.
Fuse stream operations can be called by different threads. stream creation (lock the path) can be called by one thread while stream close (unlock the path) may be called by another thread. Use the previous ReadWriteLock, unlock will throw IllegalMonitorException.
NA
> Change FUSE readwriteLock to session based lock

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/master/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
Without this PR, we have to modify alluxio code to support a new coming ratis config key.
The way to config ratis related configures something like the following:
```
alluxio.master.embedded.journal.ratis.config.raft.server.rpc.slowness.timeout=1000
alluxio.master.embedded.journal.ratis.config.raft.server.snapshot.auto.trigger.threshold=1000
```
Without this PR, we have to modify alluxio code to support a new coming ratis config key.
Add alluxio config prefix 
`alluxio.master.embedded.journal.ratis.config`
> Support config ratis configurations through alluxio config

- core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
- core/common/src/test/java/alluxio/master/PollingMasterInquireClientTest.java
Revert the PollingMasterInquireClient change in https://github.com/Alluxio/alluxio/pull/16065
Command to revert:
git checkout 50a282e5f48aa00b6d3e83dd1b3d60079162dcea -- core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
git checkout 50a282e5f48aa00b6d3e83dd1b3d60079162dcea -- core/common/src/test/java/alluxio/master/PollingMasterInquireClientTest.java 
The previous PR introduced a new endpoint for polling primary master address, which introduces a backward compatibility issue.  If a 2.9 client tries to connect to a 2.8 master, then it will get an error because the endpoint it's calling isn't on 2.8.
Revert the change for now to solve the backward compatibility issue.  
N/A
> Revert PollingMasterInquireClient change and use MetaService again

- core/common/src/main/java/alluxio/util/ThreadUtils.java
- core/server/common/src/main/java/alluxio/web/WebServer.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketOptions.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketResult.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
1. respect encoding-type flag in list-objects ( list-objects-v2 equivalent) and url-encoding the following return fields:
Prefix, Key, and StartAfter
2. add util to print stacktrace of throwable in existing print thread stack trace util func
3. add service name in the webservice serving threads when starting for better tracing purpose
4. add access log in CompleteMultipartUploadHandler as well
5. add logging in CompleteMultipartUploadTask for better exception tracking.
1. to fix the bug where  + in object names is shown as space when using aws s3 clit -> respect encoding-type flag fixed this
2. track completemultipartupload exception for better debugging purpose.
N/A
> Add encoding-type support for S3 ListObjects and more logging

- core/client/fs/src/main/java/alluxio/client/block/options/GetWorkerReportOptions.java
- core/transport/src/main/proto/grpc/block_master.proto
- core/transport/src/main/proto/proto.lock
Enum variant `BLOCK_COUNT` of `WorkerInfoField` in `GetWorkerReportOptions.java` was introduced in  #14126, but its gRPC counterpart was not updated accordingly.
This PR adds the missing variant, and reorders the fields of the java enum. 
The field cannot be retrieved via RPC, only via internal function call, because gRPC will fail to serialize that java enum variant.
No.
> Add BLOCK_COUNT in gRPC WorkerInfoField

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
With this PR, we can configure block store and inode store into different disk, so that the performance can be improved leverage this PR.
Add a new propertykey `alluxio.master.metastore.block.store.dir` which default to be same with `alluxio.master.metastore.dir`
> Support RocksDB inode/block store to different disk paths

- .github/workflows/checkstyle.yml
- .github/workflows/java8_integration_tests.yml
- .github/workflows/java8_integration_tests_webui.yml
- .github/workflows/java8_unit_tests.yml
none of the workflows should be scheduled via cron. this also wastes github action minutes on individual forks of the repo
> Fix github actions from running cron

- core/server/common/pom.xml
- core/server/master/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java
- core/server/master/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
- core/server/master/src/test/java/alluxio/master/journal/raft/SnapshotReplicationManagerTest.java
- tests/src/test/java/alluxio/client/cli/JournalToolTest.java
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTestFaultTolerance.java
1. Upgrade Apache Ratis to 2.4.0.
2. Fix issues caused by API change.  (Please double check the `RaftStorage.StartupOption` I used) 
Verified with CI: https://github.com/kaijchen/alluxio/pull/1/checks
Apache Ratis has released 2.4.0 in Oct 18th and includes some bug fixes.
https://ratis.apache.org/post/2.4.0.html
Do note Apache Ratis 2.4.1 release is under discussion,
but we can just bump the dependency version when it's released.
https://lists.apache.org/thread/9yw80p20ds533wwn7jfcg1f76q56zogh
No.
> Upgrade Apache Ratis from 2.3.0 to 2.4.0

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- integration/fuse/src/main/java/alluxio/fuse/options/FuseOptions.java
- tests/src/test/java/alluxio/client/fuse/JNRFuseIntegrationTest.java
Remove direct_io mount option when using libfuse 3.
Add -o max_idle_threads=64 when using FUSE with libfuse 3.
Change default mount option to "attr_timeout=600,entry_timeout=600"
Fix and optimize mount options.
Improve performance when using libfuse 3 and remove not working default mount options.
> Optimize FUSE mount options

- core/client/fs/src/main/java/alluxio/client/file/ConfigHashSync.java
- core/common/src/main/java/alluxio/ClientContext.java
- tests/src/test/java/alluxio/client/fs/FileSystemContextReinitIntegrationTest.java
Revert "Remove ClientContext.mClusterConfHash"
Use the clusterConfHash calculated by the master as the hash version of all the clients.
fix #16491
The master uses Configuration.hash() to calculate the hash, while client uses clusterConf to calculate the hash version, which will cause the client to judge that the master and its own clusterConfHash are always unequal, thus updating the client configuration all the time.
> Fix client side config using wrong hash

- core/client/fs/src/main/java/alluxio/client/block/policy/LocalFirstPolicy.java
- docs/en/api/Java-API.md
Fix outdated doc and comments about `LocalFirstPolicy`.
Add undocumented configuration item `alluxio.user.ufs.block.read.location.policy`.
`LocalFirstPolicy` only looks at the capacity of the workers, not availability. The comments about availability dates back to https://github.com/Alluxio/alluxio/pull/2284/commits/2ba4c2deddb5085e613c822d489dec5c1656a20f but was soon removed in https://github.com/Alluxio/alluxio/pull/2284/commits/924562829b3fb46e92995ea33a40b4f77c57aa1a  during review of #2284.
Doc fix.
> [DOCFIX] Fix outdated doc of LocalFirstPolicy

- stress/common/src/main/java/alluxio/stress/master/MasterBenchSummary.java
- stress/common/src/main/java/alluxio/stress/master/MasterBenchTaskResult.java
- stress/common/src/main/java/alluxio/stress/master/MasterBenchTaskResultBase.java
- stress/common/src/main/java/alluxio/stress/master/MasterBenchTaskResultStatistics.java
- stress/shell/src/main/java/alluxio/stress/cli/AbstractStressBench.java
- stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java
- stress/shell/src/main/java/alluxio/stress/cli/StressMasterBenchBase.java
Extract some variables/functions from MasterBenchParameters into a new created MasterStressBenchBaseParameters class
Extract some variables/functions from MasterBenchTaskResult into a new created MasterBenchTaskResultBase class
Extract some variables/functions from StressMasterBench into a new created StressMasterBenchBase class
We are going to introduce a new type of MasterStressBench which allows running more than one operations (e.g. ListDir + CreateFile) at a certain ratio (e.g. 70% Read + 30% Write). To DRY the code, we refactor stress master bench related code first so that some code can be reused by the upcoming MultiOperationStressMasterBench.
N/A
> Refactor Stress Master Bench

- shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
Ignore no_cache setting for "load" command.
Currently the "load" command behaviours strangely if the corresponding node/client has the setting
```
alluxio.user.file.readtype.default=NO_CACHE
```
It reports "loaded" every time repeatedly
```
$ ./bin/alluxio fs load /test/file.01
/test/file.01 loaded
$ ./bin/alluxio fs load /test/file.01
/test/file.01 loaded
```
After applying this PR, the behaviour changes to
```
$ ./bin/alluxio fs load /test/file.01
/test/file.01 loaded
$ ./bin/alluxio fs load /test/file.01
/test/file.01 already in Alluxio fully
```
No
> Ignore no_cache setting for "load" command

- .github/workflows/java8_integration_tests_ft.yml
- tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java
This should improve test reliability for the fault tolerant tests as it runs a single test at a time (see ALLUXIO_DOCKER_FORK_COUNT=1). These tests are costly as they are starting and stopping Alluxio processes frequently, which may cause the tests to timeout.
It also adds a wait command to the JournalBackupIntegrationTest to ensure the cluster is ready after being restarted.
> Run fault tolerant tests as single fork

- core/client/fs/src/main/java/alluxio/client/block/stream/UnderFileSystemFileOutStream.java
- core/client/fs/src/main/java/alluxio/client/file/AlluxioFileOutStream.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Make CompleteMultipartUpload call idempotent
Support Overwrite now only for createobject from s3client thru multipart upload 
When use  Spark + hadoop s3a to write to Alluxio, spark will retry if CompleteMultipartUpload took too long, since alluxio doesnt allow overwrite, s3 proxy does a delete and create in an non-atomic way which causes race condition, rendering the retry fail, and as a result failing the entire spark write.
1) New timer (with uniformTimer call)using UniformReservoir is introduced in the MetricsSystem
2) the uniformTimer is added to measure different parts of CompleteMultipartUpload call, as well as common places such as UFS and AlluxioOutstream close call.
> Eliminate race condition in completempupload and support overwrite

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- docs/en/administration/Performance-Tuning.md
This adds the option to allow journal entries to be committed without waiting for them to be flushed to disk. It can improve performance greatly in the case of slow or busy disks with the risk of metadata loss. It also adds performance tuning discussions on how to improve journal write performance.
This adds the property key alluxio.master.embedded.journal.unsafe.flush.enabled
> Add unsafe flush option to embedded journal

- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
Currently when using the embedded journal, on every journal entry committed, a task is submitted to the common thread pool to check if the journal group has changed. In certain experiments I have seen this resulting int up to a thousand threads being created to process these requests. I believe the group should only change when the configuration changes, so I have moved this operation to only be called on configuration changes.
> Update raft group only on config change

- core/server/common/src/main/java/alluxio/master/MasterProcess.java
In Alluxio, AlluxioMaster, AlluxioJobMaster, AlluxioWorker, AlluxioJobWorker, and AlluxioProxy are equal. They all use mStartTimeMs to record the time when the service starts. But the way they initialize mStartTimeMs is different. MasterProcess does not directly initialize mStartTimeMs through the constructor:
MasterProcess :
`
final long mStartTimeMs = System.currentTimeMillis();
`
But AlluxioProxyProcess, AlluxioWorkerProcess, AlluxioJobWorkerProcess are initialized in the constructor. Details:
`
AlluxioProxyProcess() { mStartTimeMs = System. currentTimeMillis(); … }
`
`
AlluxioWorkerProcess(TieredIdentity tieredIdentity) { mStartTimeMs = System. currentTimeMillis(); … }
`
`
AlluxioJobWorkerProcess() { mStartTimeMs = System. currentTimeMillis(); … }
`
The goal of this PR is to keep them …
> Improve MasterProcess#mStartTimeMs initialization

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Remove the file from UfsAbsentPathCache after async persisting.
To fix #16621
No
> Remove file from UfsAbsentPathCache after persisting

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
Clear worker.buildVersion when it's not set in proto.
Note: Since we are using protobuf3 to compile proto2, it's OK to omit `hasField` check.
If the field is not set, the default instance will be returned.
Steps to reproduce:
1. Start a new cluster (master and worker).
2. Stop the new worker.
3. Start a old worker (prior to 7d8ad9b12ab366ef85c05a7cedfa3a60a562de12) using the same config.
4. Check workers in web UI.
Previously, if we downgrade a worker to a versions prior to 7d8ad9b12ab366ef85c05a7cedfa3a60a562de12,
the buildVersion is stale.
It fixes a bug in which the buildVersion could be stale.
> Fix stale buildVersion when downgrade workers

- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsFileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/ufs/UfsFileInStreamTest.java
- core/common/src/main/java/alluxio/exception/runtime/UnknownRuntimeException.java
- integration/fuse/src/test/java/alluxio/fuse/ufs/stream/InStreamTest.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AInputStream.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Support seek in S3AInputStream. Support Seek in UfsFileInStream.
Fuse is seek() heavy. Every read will first seek() and then read(). 
Fuse.seek() can seek to any position and is a real random read.
Supports FUSE UFS random read operations. e.g. FIO random read
> Support FUSE UFS seek

- integration/fuse/pom.xml
- integration/fuse/src/test/java/alluxio/fuse/ufs/AbstractTest.java
- integration/fuse/src/test/java/alluxio/fuse/ufs/FuseFileSystemDataTest.java
- integration/fuse/src/test/java/alluxio/fuse/ufs/FuseFileSystemMetadataTest.java
Support fuse test to test against S3 by passing maven parameter `-Dalluxio.test.s3a.path=s3://alluxio-test-fuse/`.
> Support fuse test to test against S3

- core/common/src/main/java/alluxio/master/MasterInquireClient.java
- core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
- core/common/src/test/java/alluxio/master/PollingMasterInquireClientTest.java
- minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
- shell/src/main/java/alluxio/cli/fs/command/LeaderCommand.java
- shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShellUtils.java
Previously the service type in polling master inquire client was deduced by looking up the master ip address. This is an unnecessary step because when the client is initialized, the caller knows what exact type of master it talks too. So we add this as a constructor param and let every caller to pass it in, to improve the code readability. 
To improve the code readability.
N/A
> Improve the PollingMasterInquireClient logic

- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsFileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/ufs/UfsFileInStreamTest.java
- core/common/src/main/java/alluxio/exception/runtime/UnknownRuntimeException.java
- integration/fuse/src/test/java/alluxio/fuse/ufs/stream/InStreamTest.java
Support seek in UfsFileInStream
Fuse is seek() heavy. Every read will first seek() and then read().
Fuse.seek() can seek to any position and is a real random read.
Supports FUSE UFS random read operations. e.g. FIO random read
> Support fuse sdk seek

- docs/en/contributor/Contributor-Tools.md
Small doc fix. be able see -> be able to see
> Fix fuse small doc

- core/common/src/main/java/alluxio/conf/PropertyKey.java
In the PropertyKey file, Name#MASTER_EMBEDDED_JOURNAL_PROXY_HOST is not used anywhere and should be removed.
Details: https://github.com/Alluxio/alluxio/issues/16624
For users, there is no impact.
> Remove unused Name#MASTER_EMBEDDED_JOURNAL_PROXY_HOST

- core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/util/ParallelZipUtils.java
- core/server/common/src/main/java/alluxio/util/TarUtils.java
- core/server/common/src/test/java/alluxio/util/ParallelZipUtilsTest.java
- core/server/common/src/test/java/alluxio/util/TarUtilsTest.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java
- tests/src/test/java/alluxio/server/ft/journal/MultiProcessCheckpointTest.java
Allows the user to specify the compression level of the RocksDB checkpoint for both single and multithreaded compression.
Fixes an issue where the compression level for the multithreaded compression was not being used.
Adds the property key `alluxio.master.metastore.rocks.checkpoint.compression.level`.
Removes the property key `alluxio.master.metastore.rocks.parallel.backup.compression.level` as its value was not being used.
> Add compression level option for RocksDB checkpoint

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
I replace` FileInStream is = userFs.openFile(objectUri); ` with `FileInStream is = userFs.openFile(status, OpenFilePOptions.getDefaultInstance());`  around 1242th line in S3RestServiceHandler.java
When I detected alluxio proxy, I found that `S3RestServiceHandler.GetObject` calls `FileSystem.getStatus()` twice.
I found that the 1241th line and 1242th line in S3RestServiceHandler.java caused this problem:
```
URIStatus status = userFs.getStatus(objectUri);
FileInStream is = userFs.openFile(objectUri); 
```
`userFs.openFile(objectUri) `calls `openFile(getStatus(objectUri), OpenFilePOptions.getDefaultInstance())`, which  leads to double time consuming.
To reduce redundant calls,  I replace` FileInStream is = userFs.openFile(objectUri); ` with `FileInStream is = userFs.openFile(status, …
> Reduce redundant calls in getObject of S3 API

- job/server/src/main/java/alluxio/master/job/JobMaster.java
- job/server/src/main/java/alluxio/master/job/JobMasterAuditContext.java
Add jobName into audit log for run command.
The audit log of the run command has no jobName record.
```
2022-11-02 18:20:47,690 INFO  JOB_MASTER_AUDIT_LOG (AsyncUserAccessAuditLogWriter.java:run) - succeeded=true    allowed=true    ugi=alluxio,alluxio (AUTH=RPC)  ip=null cmd=run mJobId=1666765197501    mJobName=null   perm=null       executionTimeUs=2700
```
> Add jobName into audit log for run command

- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
Use mdtest to get file status of 1000 files, by removing the isFile call, the get status performance can double.
> Remove unneeded isFile call in UfsBaseFileSystem.getStatus

- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInStream.java
- integration/fuse/src/main/java/alluxio/fuse/options/FuseOptions.java
- integration/fuse/src/test/java/alluxio/fuse/AlluxioJniFuseFileSystemTest.java
Remove extra get status call in fuse.open()
Reduce one unneeded get metadata call
NA
> Remove redundant get file status call in fuse.open()

- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsFileInStream.java
Remove some overhead in big file read (cache hit/ cache miss) in fuse sdk.
Improve overall read performance
NA
> Remove some overhead in big file read

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
In DefaultBlockMaster, there are some redundant SuppressFBWarnings. The purpose of this pr is to remove them.
Details: https://github.com/Alluxio/alluxio/issues/16660
For user, there is no impact.
> Remove the redundant DefaultBlockMaster#SuppressFBWarnings

- core/client/fs/src/main/java/alluxio/client/file/FileSystemUtils.java
- core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java
- core/client/fs/src/main/java/alluxio/client/file/MetadataCachingFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/options/FileSystemOptions.java
- core/client/fs/src/test/java/alluxio/client/file/MetadataCachingFileSystemTest.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- integration/fuse/bin/alluxio-fuse-sdk
- integration/fuse/src/main/java/alluxio/cli/command/metadatacache/AbstractMetadataCacheSubCommand.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
- integration/fuse/src/test/java/alluxio/fuse/AlluxioJniFuseFileSystemTest.java
- integration/fuse/src/test/java/alluxio/fuse/AlluxioJnrFuseFileSystemTest.java
- integration/fuse/src/test/java/alluxio/fuse/cli/FuseShellTest.java
- integration/fuse/src/test/java/alluxio/fuse/ufs/AbstractTest.java
- tests/src/test/java/alluxio/client/fuse/AbstractFuseIntegrationTest.java
- tests/src/test/java/alluxio/client/fuse/file/AbstractFuseFileStreamIntegrationTest.java
Enable default client-side metadata cache (20,000 entries with 40MB memory).
Each fuse.open() has two extra get file status calls which cannot be provided via kernel metadata cache but can via user space metadata cache. Enable user space metadata cache can largely improve the overall fuse FIO small file read performance. S3FS-FUSE has similar settings of enable user space metadata cache (100,000 entries with 40MB memory) by default.
FIO benchmarking FUSE SDK against s3-fuse in terms of small file read:
fio --name=sequentialread --rw=read --bs=100k --numjobs=1 --filesize=100k --direct=1 --group_reporting --nrfiles 1000
<google-sheets-html-origin><style type="text/css"></style>
  | S3 FUSE | ALLUXIO FUSE
-- | -- | --
Original | 9000 KiB/s | 1500 KiB/s
Kernal metadata cache …
> Enable default metadata cache for FUSE SDK

- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
- shaded/client/pom.xml
- change the build destination of the shaded client jar from `client/alluxio-VERSION-client.jar` to `client/build/alluxio-VERSION-client.jar`
- add a new step to create a symlink at the previous `client/alluxio-VERSION-client.jar` pointing to the new destination. also mimic this step in the tarball generation script
with the client jar being a symlink, this will allow the addition of a hadoop3 compatible shaded client jar via
- adding new modules in core/client/ and shaded/ to define the new client jar
- building the new shaded client jar also within `client/build/`
- exposing a new flag/profile to replace the current symlink with a new symlink pointing to the hadoop3 client jar + also doing the same within the tarball generation script
this change was tested by building the release …
> Build and symlink to shaded client jar within client/build/

- core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/util/TarUtils.java
- core/server/common/src/test/java/alluxio/util/FileUtil.java
- core/server/common/src/test/java/alluxio/util/TarUtilsTest.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java
- tests/src/test/java/alluxio/server/ft/journal/MultiProcessCheckpointTest.java
Allows the user to specify the compression level of the RocksDB checkpoint for both single and multithreaded compression.
Fixes an issue where the compression level for the multithreaded compression was not being used.
Adds the property key `alluxio.master.metastore.rocks.checkpoint.compression.level`.
Removes the property key `alluxio.master.metastore.rocks.parallel.backup.compression.level` as its value was not being used.
[This is manually generated PR to cherry-pick committed PR Alluxio/alluxio#16620 into target branch branch-2.8]
> Port changes of [#16620] to branch-2.8

- core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/util/ParallelZipUtils.java
- core/server/common/src/main/java/alluxio/util/TarUtils.java
- core/server/common/src/test/java/alluxio/util/ParallelZipUtilsTest.java
- core/server/common/src/test/java/alluxio/util/TarUtilsTest.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java
- tests/src/test/java/alluxio/server/ft/journal/MultiProcessCheckpointTest.java
Allows the user to specify the compression level of the RocksDB checkpoint for both single and multithreaded compression.
Fixes an issue where the compression level for the multithreaded compression was not being used.
Adds the property key `alluxio.master.metastore.rocks.checkpoint.compression.level`.
Removes the property key `alluxio.master.metastore.rocks.parallel.backup.compression.level` as its value was not being used.
[This is manually generated PR to cherry-pick committed PR Alluxio/alluxio#16620 into target branch branch-2.9]
> Port changes of [#16620] to branch-2.9

- core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
- core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- core/server/master/src/test/java/alluxio/master/journal/raft/RaftJournalSystemMetricsTest.java
Clear metrics when closing JournalStateMachine,
so when a new instance of JournalStateMachine is created, those metrics can be refreshed.
https://github.com/Alluxio/alluxio/blob/bd30e25d7b0103e30dd8de611da250ced85cdf27/core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java#L293-L297
Fix #16704.
Fix a bug that after a primacy change, metrics of JournalStateMachine will get stuck.
No.
> Clear metrics when closing JournalStateMachine

- integration/kubernetes/helm-chart/alluxio/README.md
The guidance in integration/kubernetes/helm-chart/alluxio/README.md doesn't  work.
User can't install an alluxio with helm  in kubernetes cluster.
No
> Fix error in helm install guidance

- bin/alluxio-monitor.sh
- conf/alluxio-env.sh.template
This reverts commit bd3ab80ba462a6863787d325c93c796dce3e18de.
This commit solve the related issues but require us to set the same configuration twice especially in Kubernetes environment which all configuration including address information are set through java opts
> Revert "Remove master/worker java opts from monitor java opts"

- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java
- core/server/master/src/main/java/alluxio/master/block/BlockContainerIdGenerator.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryIdGenerator.java
- core/server/master/src/main/java/alluxio/master/file/meta/SimpleInodeLockList.java
- core/server/master/src/main/java/alluxio/master/metastore/InodeStore.java
- core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java
- core/server/master/src/main/java/alluxio/master/metastore/caching/CachingInodeStore.java
- core/server/master/src/main/java/alluxio/master/metastore/heap/HeapInodeStore.java
Add more logs to detect inode tree corruption
Some users reported a issue that expecting to lock inode A but inode B is locked. After the investigation, we figured that this might be due to inode tree corruption caused by journal loss. So we add more logs to help users debug the issue better. 
N/A
> Add more observability on inode tree corruption

- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java
- core/server/master/src/main/java/alluxio/master/block/BlockContainerIdGenerator.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryIdGenerator.java
- core/server/master/src/main/java/alluxio/master/file/meta/SimpleInodeLockList.java
- core/server/master/src/main/java/alluxio/master/metastore/InodeStore.java
- core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java
- core/server/master/src/main/java/alluxio/master/metastore/caching/CachingInodeStore.java
- core/server/master/src/main/java/alluxio/master/metastore/heap/HeapInodeStore.java
Add more logs to detect inode tree corruption
Some users reported a issue that expecting to lock inode A but inode B is locked. After the investigation, we figured that this might be due to inode tree corruption caused by journal loss. So we add more logs to help users debug the issue better.
N/A
pr-link: Alluxio/alluxio#16710
change-id: cid-b90490c7122465ccaaf83c660e8e5dfcfc0f692a
3. webui
> Port changes of [#16710] to branch-2.6

- core/common/src/main/java/alluxio/conf/ReconfigurableRegistry.java
The update method is called safely
When the update call unregister, will throw ConcurrentModificationException
NA.
> Make ReconfigurableRegistry thread-safe

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- underfs/oss/pom.xml
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystemFactory.java
- underfs/oss/src/main/java/alluxio/underfs/oss/StsOssClientProvider.java
- underfs/oss/src/test/java/alluxio/underfs/oss/StsOssClientProviderTest.java
Support STS for OSS ufs
1. Plaintext AccessKey/AccessSecret is not safe and not Recommended for Aliyun
2. STS(Security Token Service) for OSS is more safe. For details, see https://help.aliyun.com/document_detail/32016.html
addition property keys
1. UNDERFS_OSS_STS_ENABLED
2. UNDERFS_OSS_RETRY_MAX
3. UNDERFS_OSS_ECS_RAM_ROLE
#16510
> Support STS for OSS ufs through RAMRole

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/main/java/alluxio/master/file/meta/LockingScheme.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataConcurrentTest.java
The concurrent sync feature will throw exception if the locking scheme uses the constructor that takes a shouldSync boolean. This PR fixes it.
N/A
> Fix concurrent sync dedup

- core/common/src/main/java/alluxio/RuntimeConstants.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/grpc/ClientVersionClientInjector.java
- core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
- core/common/src/main/java/alluxio/security/authentication/ClientContextServerInjector.java
- core/server/common/src/main/java/alluxio/RpcUtils.java
- core/server/common/src/main/java/alluxio/master/journal/raft/SnapshotReplicationManager.java
- core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingServer.java
- core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingServiceClientHandler.java
- core/server/master/src/main/java/alluxio/master/backup/BackupLeaderRole.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterAuditContext.java
- core/server/master/src/main/java/alluxio/master/journal/DefaultJournalMaster.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java
- job/server/src/main/java/alluxio/master/job/JobMaster.java
- job/server/src/main/java/alluxio/master/job/JobMasterAuditContext.java
- table/server/master/src/main/java/alluxio/master/table/DefaultTableMaster.java
1. The client will use an injector to send version and revision to the server
2. Displaying client version in audit log
This allows us to know the version of the client connected to alluxio.
Display client version information in the audit log like
```
2022-11-30 18:08:57,038 INFO AUDIT_LOG: succeeded=true	allowed=true	ugi=xxx,xxx(AUTH=SIMPLE)	ip=/xxx:52912	cmd=mkdirs	src=xxx	dst=null	perm=xxx:xxx:rwxrwxrwx	executionTimeUs=160770	clientVersion=xxx	proto=rpc
```
> Make client send version to server and audit log contain version

- core/server/common/src/main/java/alluxio/Registry.java
- core/server/master/src/test/java/alluxio/master/file/PermissionCheckTest.java
Fix an NPE in PermissionCheckTest.
The `mMetricsMaster` was initialized to `null` and the setup was adding a null pointer to the registry. A null pointer should have been rejected by the registry but it was not the case until refactoring was done in #16644.
No.
> Fix NPE in PermissionCheckTest

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- integration/fuse/bin/alluxio-fuse-sdk
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
- integration/fuse/src/test/java/alluxio/fuse/meta/UpdateCheckerTest.java
- integration/fuse/src/test/java/alluxio/jnifuse/struct/FuseFileInfoTest.java
Set default fuse version to 3 because of easy to use and better performance.
One can sudo yum install fuse3 and then alluxio-fuse to be able to enjoy the 
better performance brought by MAX_IDLE_THREADS=64 (64 threads instead 10 idle threads to execute fuse operations for better performance).
> Set default fuse version to 3 and support setting via command line

- integration/fuse/src/main/java/alluxio/fuse/StackMain.java
All properties have already copied from `args` to set `fuseOpts` in line 45-47. Arraycopy would error out.
> Remove incorrect copy in StackFS

- .github/workflows/stale.yaml
change to run at 7AM US west time, 11PM China time, 3PM UTC
run more operations per run (from 30 to 100)
From old issues/PRs to new ones
> Fix stale github action

- core/server/master/src/main/java/alluxio/master/journal/tool/UfsJournalDumper.java
- tests/src/test/java/alluxio/client/cli/JournalToolTest.java
Fix `UfsJournalDumper.dumpJournal()`, which shouldn't call `Files.createDirectories(dir)`.
bug: when using UfsJournal, if you use JournalTool to dump the ufs journal of a regular checkpoint(like BlockMaster), it will throws FileNotFoundException: /path-to-output/checkpoints-106 (Is a directory).
like this: 
Because in `AbstractJournalDumper.readCheckpoint(checkpoint, path)`, path is a file or dir. For regular checkpoint, it is a file; and for compound checkpoint, it is a dir. But `UfsJournalDumper` calls `Files.createDirectories(dir)`, which should be called in `AbstractJournalDumper.readCompoundCheckpoint`.
None
> Fix bug for ufs journal dumper when read regular checkpoint

- core/common/src/main/java/alluxio/worker/block/io/BlockReadableChannel.java
- core/common/src/test/java/alluxio/worker/block/io/BlockReadableChannelTest.java
- core/common/src/test/java/alluxio/worker/block/io/MockBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedFileReader.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockReader.java
- core/server/worker/src/test/java/alluxio/worker/page/PagedBlockReaderTest.java
Implement `getChannel`. The implementation does not yet enable zero-copy transfer with netty.
> Implement getChannel for PagedBlockReader

- core/server/master/src/main/java/alluxio/master/block/RegisterStreamObserver.java
The locked section is here
https://github.com/Alluxio/alluxio/blob/c3dcda455e081ef99345f2d906e7899652b3a2e6/core/server/master/src/main/java/alluxio/master/block/RegisterStreamObserver.java#L78
The object is locked to init the context. This change only adds the missing tag. The locking logic has been in for a long time.
> Add missing GuardedBy and volatile for worker stream register

- pom.xml
This should address [CVE-2022-40151](https://nvd.nist.gov/vuln/detail/CVE-2022-40151)
No
> Bump xstream version to 1.4.20

- tests/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
Change matcher in CapacityCommandIntegrationTest.
1. Match the output line by line, deprecate `assertThat()`.
2. Use regexp to match the table header.
1. `Assert.assertThat()` is deprecated.
2. We got following errors in our internal CI, because the worker name is too long.
```
[ERROR] Failures: 
[ERROR] alluxio.client.cli.fsadmin.command.CapacityCommandIntegrationTest.allCapacity
[ERROR]   Run 1: CapacityCommandIntegrationTest.allCapacity:40 
Expected: a string containing "Worker Name      Last Heartbeat   Storage       MEM              Version          Revision"
but: was "Capacity information for all workers: 
Total Capacity: 16.00MB
Tier: MEM  Size: 16.00MB
Used Capacity: 0B
Tier: MEM  Size: 0B
Used Percentage: 0%
Free Percentage: 100%
Worker Name …
```
> Change matcher in CapacityCommandIntegrationTest

- core/client/hdfs3/pom.xml
- core/client/pom.xml
- shaded/client-hadoop3/pom.xml
- shaded/pom.xml
the new client/hdfs3 and shaded/client-hadoop3  modules are currently a copy of the existing client/hdfs and shaded/client modules
the addition of this will allow for changes that are available only in hadoop3, such as https://github.com/Alluxio/alluxio/pull/16017#discussion_r1039377694
both client jars will be built by default, but the symlink at client/alluxio-VERSION-client.jar will point to the hadoop-2 one to maintain backcompat. if the hadoop-3 profile is activated by adding `-Phadoop-3`, then the symlink will be overridden to point to the new hadoop3 shaded client jar
> Add client-hadoop3 module

- job/server/src/main/java/alluxio/master/job/tracker/CmdJobTracker.java
https://github.com/Alluxio/new-contributor-tasks/issues/643
Fix logging to capture jobControlId 
this will help in getting jobControlId in the logs, and will help in getting status information about the job
its just log level changes
> Fix logging to capture jobControlId

- integration/kubernetes/helm-chart/monitor/README.md
The old Grafana dashboard link in the Readme returns 404. Replace it with the correct link.
Solves https://github.com/Alluxio/alluxio/issues/16796
> [DOCFIX] Fix monitor helm chart Grafana dashboard link

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/test/java/alluxio/client/file/cache/HangingPageStore.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
In the async page store, when worker threads run out, the caller thread
should perform the action.
The test had a race condition where all the threads could block,
including the calling thread.
pr-link: https://github.com/Alluxio/alluxio/pull/16731
change-id: cid-81d809c343968d68b57988978575d8b9e4ace63a
Original commit https://github.com/Alluxio/alluxio/commit/7a4e0a53a3ea89630c0cd9bca77bb7fdea254873
> Fix hanging page store test

- job/server/src/main/java/alluxio/master/job/tracker/CmdRunAttempt.java
Whenever the job command status is being asked for the job command id, it is mostly being asked by alluxio cli client in synchronous mode, it should return the status immediately in case of plan info has one of the finished status like failed, completed or cancelled instead of checking its children tasks' status and deriving the final status.
As per #16708, the distributed cli commands like distcp and distload hang; same behaviour observed consistently whenever any job worker is declared disconnected by job master.
Currently, the job master derives the status for job command id by calling its children job control id which internally, derives its status from its children's status. In normal circumstances, all the children of job control id have expected status but in circumstance like any …
> Fix cli distributed command hang issue

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Set job service batch size default to 1 to avoid using batched jobs. Batched job is no longer helpful for job service since we move the scheduling logic from client to job master. Eventually, we would deprecate batched job.
Reduce code complexity
na
> [SMALLFIX]Update job service batch size default value

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Change the default value for a property key.
After some internal testing, we saw that a compression level of 1 compressed 98% as much as a compression level of -1 (system default) but reduced compression time by 23%. In light of this, we believe that 1 is the better default value.
No
> Change default value for checkpoint compression level

- core/server/master/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java
- core/server/master/src/main/java/alluxio/master/file/meta/UfsSyncPathCache.java
Currently when metadata is created during metadata sync, when creating journal entries for block ids, they will be journaled synchronously. All other metadata updates are journaled asynchronously then flushed as a group.
This PR makes the block id journal entries also be flushed asynchronously using the same journal context.
Additionally it add higher concurrency defaults on some of the caches used by metadata sync which reduces the locking overhead.
No
> Use async journals for block id journal entries in metadata sync

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
Clean up `mTempWorkers` when a worker is deemed lost
> [SMALLFIX] Remove unregistered worker metadata on timeout

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/loadmanager/LoadJob.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- core/transport/src/main/proto/proto.lock
This adds a property to the list status call to disable the are descendants loaded check.
Currently before a recursive listing happens, the entire enclosed set of files are traversed to see if they all have the descendants loaded flag set in order to check if a metadata sync is needed. This can be costly especially if doing batch or partial listings. By setting this property the check can be avoided. This is, for example, recommended to set to true on the calls following the first call of a batch listing.
Note that this is recommended as more of a temporary fix for internal libraries, until a new logic design for the metadata sync is completed.
New property in the list status options proto.
> Add disable are descendants loaded property

- integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemContractTest.java
The UnderFileSystemContractTest was outputting a successful output code even though some of the tests were failing.
> Fix ufs contract test not outputting error code on failure

- .github/workflows/stale.yaml
About 1 page of issues were labeled stale per week. At this rate we need 30 weeks to label all of old issues, which is too slow.
> Make stale labeling faster

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/TtlBucket.java
- core/server/master/src/main/java/alluxio/master/file/meta/TtlBucketList.java
As mentioned in https://github.com/Alluxio/alluxio/issues/8991, some data structures about state of index in the master are stored in memory, which could cause memory issues.
To know if this is happening, some metrics are added to compute the size of these structures.
These already existed:
Master.FilesPinned
Master.FilesToBePersisted
And these are added:
Master.TTLBuckets
Master.TTLInodes
Master.ReplicationLimitedFiles
For an example of how these new metrics work, can try something like:
In Alluxio-site.properties set ```alluxio.master.ttl.checker.interval.ms=60000```
Then run
``` ./bin/alluxio runTests -Dalluxio.user.file.create.ttl=1m  -Dalluxio.user.file.create.ttl.action=DELETE -Dalluxio.user.file.replication.max=1```
And watch
```watch -n 1 "curl 127.0.0.1:19999/metrics/json/ | grep …
```
> Add metrics for in memory data structures

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/underfs/ObjectLowLevelOutputStream.java
- underfs/obs/src/main/java/alluxio/underfs/obs/OBSLowLevelOutputStream.java
- underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
- underfs/obs/src/test/java/alluxio/underfs/obs/OBSLowLevelOutputStreamTest.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSLowLevelOutputStream.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/oss/src/test/java/alluxio/underfs/oss/OSSLowLevelOutputStreamTest.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3ALowLevelOutputStream.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
- underfs/s3a/src/test/java/alluxio/underfs/s3a/S3ALowLevelOutputStreamTest.java
Refactor s3 low level output stream and support OSS and OBS.
1. extract the generic logic to `ObjectLowLevelOutputStream` to make it easy to support new object storage.
2. Support streaming uploads for OBS and OSS.
3. fix the bug that empty files cannot be persisted to UFS.
4. specify MD5 when upload parts.
`alluxio.underfs.oss.intermediate.upload.clean.age`: clean incomplete multi abort age for OSS.
`alluxio.underfs.oss.streaming.upload.enabled`: Whether to enable stream upload for OSS.
`alluxio.underfs.oss.streaming.upload.partition.size`: straming upload partition size for OSS.
`alluxio.underfs.oss.streaming.upload.threads`: thread pool size for OSS streaming upload.
`alluxio.underfs.obs.intermediate.upload.clean.age`: clean incomplete multi abort age for obs. …
> Refactor s3 low level output stream and support OSS and OBS

- docs/en/api/Java-API.md
relative links within the codebase do not render to usable links when publishing to our documentation website.
`[description](/path/to/file)` will render as `https://docs.alluxio.io/path/to/file`
replace with the full github url to the corresponding file in master branch instead
> [DOCFIX] Fix links to java file examples in Java-API.md

- core/client/fs/src/main/java/alluxio/client/file/cache/evictor/TwoChoiceRandomEvictor.java
- core/client/fs/src/test/java/alluxio/client/file/cache/TwoChoiceRandomEvictorTest.java
The PR adds the two-choice random cache eviction policy. The algorithm selects two random page IDs and evicts the one least recently used.
From some evaluation (https://danluu.com/2choices-eviction/), the two-choice random policy has competitive performance compared with LRU.
Users can configure the new cache eviction policy.
> Add the two-choice random cache eviction policy

- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/client/fs/src/main/java/alluxio/client/file/cache/PageInfo.java
- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStoreDir.java
The PR cherry-picks @beinan's implementation of local cache invalidation to the master branch.
> Merge local cache invalidation

- core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerOptions.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
Co-Author-By: Chen Liang <chliang@uber.com>
This change adds a scheduled thread in LocalCacheManager, to periodically check the page create time, and delete pages that have passed the configurable time threshold.
Certain use cases require the cached data to be removed beyond certain longevity. This is mainly for compliance considerations.
No
> Add cache TTL enforcement

- core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Fix caching not working in dora worker.
Two bugs are fixed:
1. Page store in Dora worker was not created with the worker specific property keys. Keys for client local cache was used, so the settings like cache dir location and sizes did not have effect.
2. `DoraCacheFileSystem.open` did not honor client side read default options, and was using hard-coded defaults from gRPC definition, which is `NO_CACHE`.
No.
> Fix data not being cached by dora worker

- core/client/fs/src/test/java/alluxio/client/file/cache/TwoChoiceRandomEvictorTest.java
Fix the flaky test in the two-choice random cache eviction policy
As the test is flaky, it will influence other PRs.
No.
> Fix the flaky test in the two-choice random cache eviction policy

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
Page Not Found is reported on the first time to access such page, or when the page cache is evicted. This is normal and not an error.
Signed-off-by: Huang Hua <huanghua78@msn.com>
Change the log level from error to debug.
When client reads some file for the first time, worker has the following error messages:
```
2023-02-08 15:07:43,839 ERROR LocalCacheManager - Failed to get existing page PageId{FileId=1478269e1f194060bc522a21dce77eeee147367afad6d4011ae65543e9b0256b, PageIndex=0} from pageStore
alluxio.exception.PageNotFoundException: /Volumes/ramdisk/LOCAL/1048576/221/1478269e1f194060bc522a21dce77eeee147367afad6d4011ae65543e9b0256b/0
at alluxio.client.file.cache.store.LocalPageStore.get(LocalPageStore.java:118)
at alluxio.client.file.cache.LocalCacheManager.getPage(LocalCacheManager.java …
```
> Reduce log level to debug for Page Not Found

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- core/transport/src/main/proto/proto.lock
- shell/src/main/java/alluxio/cli/fs/command/RmCommand.java
- tests/src/test/java/alluxio/client/cli/fs/AbstractFileSystemShellTest.java
- tests/src/test/java/alluxio/client/cli/fs/command/RmCommandIntegrationTest.java
Support delete file from alluxio only and reset its directChildrenLoadedState of parent.
```Console
$ bin/alluxio fs rm -R --alluxioOnly --syncParentNextTime=true /test/bb
$ bin/alluxio fs ls /test/
drwxr-xr-x  mbl            staff                        0       PERSISTED 05-30-2022 14:45:24:142  DIR /test/bb
$ bin/alluxio fs rm -R --alluxioOnly --syncParentNextTime=false /test/bb
$ bin/alluxio fs ls /test/
```
> Support rm directory and reset DirectChildrenLoadedState

- core/common/src/main/java/alluxio/grpc/GrpcServerBuilder.java
- core/common/src/main/java/alluxio/grpc/ServiceVersionClientServiceHandler.java
- core/server/master/src/main/java/alluxio/master/MasterProcess.java
- core/server/master/src/main/java/alluxio/master/service/rpc/RpcServerService.java
Make version service return unavailable on standby masters
In this https://github.com/Alluxio/alluxio/pull/16839 PR, we adds the capability to run grpc services on standby masters. However, if one uses an old alluxio client and connects to the new master with standby master enabled, it will get some errors. This PR is used to address the issue to make the change backward compatible.  
N/A
> Make version service return unavailable on standby masters

- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- dev/jenkins/run_docker.sh
Replace ManagementFactoryHelper with ManagementFactory for java11
Java 11 doesn't support to directly call ManagementFactoryHelper, so it is necessary to find an alternative one in java11.
NA
> Replace ManagementFactoryHelper with ManagementFactory for java11

- pom.xml
See title.
Adds https://github.com/git-commit-id/git-commit-id-maven-plugin v.4.0.5 as a dependency. Latest version (5.0.0) requires Java 11.
Updating `pom.xml` to support reproducible Maven builds. See https://maven.apache.org/guides/mini/guide-reproducible-builds.html.
Adds a `git.properties` file to output directories containing commit into (can be configurable).
ex:
```
#Generated by Git-Commit-Id-Plugin
git.build.version=2.10.0-SNAPSHOT
git.commit.id.abbrev=622dfb4
git.commit.id.full=622dfb4ca246020efaeb169b18012bd394170e9a
git.commit.time=2023-02-13T21\:47\:53Z
```
> Support Maven reproducible builds

- core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
reduce useless async cache request when read from remote worker
It is useless to trigger async cache when the remote worker has already cached block.
> Reduce useless async cache request when read from remote worker

- examples/pom.xml
Fix the security issue introduced by following link. The newest version of hadoop fix this issue. 
- http://horus.oa.com/advisory/HOSA-pzst-tfwm6u4cy 
- http://horus.oa.com/advisory/HOSA-n612-2d07um3px
- http://horus.oa.com/advisory/HOSA-yn2x-x9qulrobf
- http://horus.oa.com/advisory/HOSA-jatn-nizpv9w2u
I remove the hadoop.version property to keep consistent with parent module.
> Remove hardcoded version dependency in examples module

- docs/cn/administration/Upgrade.md
Update cn version of Upgrade doc.
There is no corresponding Chinese documentation for upgrade.
More Chinese users can access Alluxio documentation more easily.
> [DOCFIX] Update cn version of Upgrade doc

- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
Fix Worker.ActiveClients is negative when load from ufs
createUfsBlockReader will invoke closeUfsBlock then invoke commitBlock then this metric decrease.
But forget to increase firstly . So it need to increase firstly.
no.
> Fix Worker.ActiveClients is negative when load from ufs

- core/common/src/main/java/alluxio/resource/Pool.java
- core/common/src/main/java/alluxio/resource/PooledResource.java
- core/common/src/test/java/alluxio/resource/PooledResourceTest.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Since we do not have a standalone worker discovery mechanism, clients still need to pull the worker list from master. If workers do not send heartbeats then master will mark a worker as lost after a timeout.
This PR temporarily enables heartbeats until we implement a worker discovery mechanism independent of the masters.
> Enable heartbeat for Dora workers temporarily

- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java
**What changes are proposed in this pull request?**
Fix the bug that cannot cache file with block store when using Netty data transmission.
**Why are the changes needed?**
`UnderFileSystemBlockReader#getChannel` is not supported, but it throws exception (as shown below) when we check the state using `reader.getChannel() instanceOf FileChannel` in `BlockReadHandler`. We are sure that `UnderFileSystemBlockReader#getChannel` will never be called actually, so we can just return null to avoid this exception here.
```
Caused by: alluxio.exception.status.InternalException: Channel to node3/xxx.xxx.xxx.xxx:59999: UFSFileBlockReader#getChannel not supported
at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:159)
at …
```
> Fix the bug that cannot cache file with block store when using netty

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/retry/SleepingRetry.java
- core/common/src/test/java/alluxio/underfs/ObjectUnderFileSystemTest.java
Modern object stores ensure strong consistency as follows:
Alibaba oss: https://www.alibabacloud.com/help/en/object-storage-service/latest/what-is-oss
Amazon S3: https://aws.amazon.com/s3/consistency/
GCP Cloud Storage: https://cloud.google.com/storage/docs/consistency
Huawei OBS: https://support.huaweicloud.com/intl/en-us/api-obs/obs_04_0118.html
When this is non-zero and the UFS is strongly consistent, and Alluxio is out of sync, some operations may retry over and over even though nothing will change, slowing down the system for long periods of time. This value should be 0 by default with strong consistency as Alluxio will see the most up to date version the first time it accesses the object.
> Update retry policy for object stores

- core/common/src/main/java/alluxio/AbstractClient.java
- core/common/src/main/java/alluxio/grpc/ServiceVersionClientServiceHandler.java
- core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
- core/transport/src/main/proto/grpc/version.proto
- core/transport/src/main/proto/proto.lock
Add a rejectOnStandbyMasters on version grpc endpoint 
We added a PR to make standby master return unavailable on this version service endpoint
https://github.com/Alluxio/alluxio/pull/16854
However, in addition to the polling master inquire client, the AbstractMasterClient also needs this endpoint. 
https://github.com/Alluxio/alluxio/blob/master/core/common/src/main/java/alluxio/AbstractClient.java#L172
When a client makes a request to standby master, such check will constantly fail and resulted in failures. 
So we want the logic done in #16854 only applies to PollingMasterInquireClient and hence we added this boolean field to bypass the check. 
N/A
> Add allowOnStandbyMasters option for version grpc endpoint

- core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
add a missing javadoc `@param`
> [SMALLFIX] Add a missing javadoc param

- core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- core/client/fs/src/test/java/alluxio/client/file/ufs/UfsBaseFileSystemTest.java
- core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- integration/fuse/src/test/java/alluxio/fuse/AlluxioJniFuseFileSystemTest.java
- tests/src/test/java/alluxio/client/fuse/dora/readonly/stream/InStreamTest.java
- tests/src/test/java/alluxio/client/fuse/dora/stream/InOrOutStreamOutTest.java
- tests/src/test/java/alluxio/client/fuse/dora/stream/OutStreamTest.java
Signed-off-by: Huang Hua <huanghua78@msn.com>
In Dora client, we need to join the UFS root with the Alluxio file path before calling UfsBaseFileSystem operations.
All input FilePath strings from client are Alluxio based file path. So, the root path of the UFS should be added before the Alluxio file path and be passed to UfsBaseFileSystem on client side. The file path returned from UfsBaseFileSystem.getStatus() and UfsBaseFileSystem.listStatus() also need to be stripped with its UFS root.
When the FileStatus is sent back from DoraWorker, the file path in FileInfo needs similar transformation.
No
> Add UFS root before the Alluxio file path

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RequestServlet.java
Rename PROXY_S3_OPTIMIZED_VERSION_ENABLED to PROXY_S3_V2_VERSION_ENABLED in comment.
Using a error property about how to enable the s3 v2 api in `alluxio.proxy.s3.S3RequestServlet`.
> [SMALLFIX] Correct version name in comment

- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterFsOptsTest.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- core/transport/src/main/proto/proto.lock
- tests/src/test/java/alluxio/client/cli/fs/command/CopyFromLocalCommandIntegrationTest.java
- tests/src/test/java/alluxio/client/cli/fs/command/CpCommandIntegrationTest.java
Support overwrite option in createFile
before this change, if we have the same name file existing in Alluxio, we will try `getStatus`, `deleteFile`, and then create the new one. now we just need to call `createFile` with overwrite option. no matter in hdfs api or s3 api. Excessive RPCs are saved.
add a new option in CreateFileOption for overwriting.
> Support overwrite option in createFile

- microbench/src/main/java/alluxio/worker/BlockStoreBase.java
- microbench/src/main/java/alluxio/worker/BlockStoreRandomReadBench.java
- microbench/src/main/java/alluxio/worker/BlockStoreSequentialReadBench.java
Added benchmarks for `PagedBlockStore` that read from local storage rather than UFS. 
This piece is missing as `PagedBlockStore` didn't support creating local blocks then.
No.
> Add local read benchmarks for PagedBlockStore

- job/server/src/main/java/alluxio/master/job/JobMaster.java
Adding metrics sink to job master.
Fix the issue that the job master is unable to sink metrics. 
Yes, this change will enable users to sink metrics from the job master.
> Add metrics sink to job master

- core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
- core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
- core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
- core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheFileInStream.java
- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/server/worker/src/main/java/alluxio/worker/grpc/FileReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/AbstractReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/FileReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/PipelineHandler.java
Support netty data transmission in dora to further improve reading performance. 
Experimental result shows that replacing gRPC with netty to transfer data can improve the reading performant by 30%-50%. Based on this context, dora can also benefit from netty data transmission. Therefore, it is meaningful to support netty data transmission in dora.
To enable netty, just add the following configurations to `alluxio-site.properties`. Notice that we can enable `epoll` if we are using Linux. As Windows and MacOS don't support `epoll`, we use `nio` instead.
```
alluxio.user.netty.data.transmission.enabled=true
#alluxio.worker.network.netty.channel=epoll
alluxio.worker.network.netty.channel=nio
#alluxio.worker.network.netty.file.transfer=MAPPED
alluxio.worker.network.netty.file.transfer=TRANSFER …
```
> Support netty data transmission in dora

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/RateLimitInputStream.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
- core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
- core/server/proxy/src/test/java/alluxio/proxy/s3/RateLimitInputStreamTest.java
Add read limit for s3 proxy when getObject return files.
We use NVME to speed up reading algorithm model, but we find that the reading speed of alluxio is too fast and k8s container will consume a lot of network card resources, and then affect other containers of the same host, so we need to limit the reading speed.
Add two properties:
1. `alluxio.proxy.s3.global.read.rate.limit.mb` to limit all connections rate;
2. `alluxio.proxy.s3.single.connection.read.rate.limit.mb` to limit single connection rate.
> Add rate limit for s3 proxy

- core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
- tests/src/test/java/alluxio/client/fuse/dora/readonly/stream/InStreamTest.java
So Dora client can access Alluxio relative path and full ufs path.
Prepare a full UFS path for client APIs and then pass it to worker.
We want Dora client to accept Alluxio path, and as well as full UFS path.
Now the client APIs accept Alluxio path relative to UFS root, and also the full
UFS path.
> Pass full UFS path from client to worker

- shell/src/main/java/alluxio/cli/fs/command/HeadCommand.java
- shell/src/main/java/alluxio/cli/fs/command/TailCommand.java
Fix a bug where `fs head` and `fs tail` output less data than it is expected to.
The code is buggy: it only calls `read` once, and does not check if the returned number of bytes read is equal to the total number of bytes to read as specified by the cli option.
Compare with the `cat` command: 
https://github.com/Alluxio/alluxio/blob/73f3ce83c8a3ef77ac3eebb4579bb7d412784ec9/shell/src/main/java/alluxio/cli/fs/command/CatCommand.java#L57-L63
No.
> Fix head and tail commands read less than expected

- core/client/fs/src/main/java/alluxio/client/CanUnbuffer.java
- core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
- core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
- core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- core/client/fs/src/test/java/alluxio/client/block/stream/TestBlockInStream.java
- core/client/fs/src/test/java/alluxio/client/block/stream/TestDataReader.java
- core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java
- core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioHdfsInputStream.java
- core/client/hdfs/src/main/java/alluxio/hadoop/BaseHdfsFileInputStream.java
- core/client/hdfs3/src/main/java/alluxio/hadoop/HdfsFileInputStream.java
Implement unbuffer interface for HdfsFileInputStream. Fix #16016.
If the unbuffer method is not implemented, then impala will not be able to use the file handle cache.
Implement CanUnbuffer and StreamCapabilities for HdfsFileInputStream.
> Implement unbuffer interface for HdfsFileInputStream

- core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
Keep the MountTable on the standby master up-to-date before switching to primary.
No
> Make standby master keep MountTable up-to-date

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Incorrect usage of flag in atomic rename for the final step of completing the target multipart-upload file.
if write type is cache_thru or thru, the atomic rename ( delete target and rename src to target ) will incorrectly delete
alluxio-only instead of deleting UFS, hence making the renaming op in UFS fail.
N/A
> Fix incorrect flag passing into delete op

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java
- tests/src/test/java/alluxio/client/fs/UfsSyncIntegrationTest.java
When the metadata sync descendant type is NONE, stop loading the children of the sync root.  
If a metadata sync is trigged by a GetStatus() call on a directory 
Previous behavior: The directory itself, as well as all its sub directories in the inode store will be synced.
New behavior: ONLY the directory itself will be loaded. 
This PR addresses https://github.com/Alluxio/alluxio/issues/16922.
The incorrect metadata sync behavior on GetStatus for a directory loads more children of the directory than expected and put a lot of pressure on UFS side. 
Yes. The metadata sync behavior has been changed. See the comment above. The previous behavior was actually wrong and we added a hidden feature flag to allow customers to fallback.
> Fix metadata sync behavior when descendant type is NONE

- stress/shell/src/main/java/alluxio/stress/cli/client/ClientIOWritePolicy.java
Fix client stressbench concurrency problem.
Reproduce:
Cluster:  
1 master and 2 workers
Command:
`bin/alluxio runClass alluxio.stress.cli.client.StressClientIOBench --operation Write --base alluxio:///stress-client-io-base --write-num-workers 2 --file-size 1m --threads 8`
Result: user_root.log
3. webui
> Fix the client stressbench concurrency problem

- core/common/src/main/java/alluxio/RuntimeConstants.java
Support new version string e.g. 291-alpha.
Fix RUNTIME ArrayIndexOutOfBoundException issues when starting master/worker process.
Split the version string with dot and want to get second element, which throws ArrayIndexOutOfBoundException
> Support new version string as XXX-XXX

- core/common/src/main/java/alluxio/RuntimeConstants.java
It will through ArrayOutOfBoundException if we build alluxio in a node which have no git installed, and the `VERSION` would be shorter than 8, even empty string, so substring(8) cannot work anymore.
This PR check there are more than 8 chars in the `VERSION` first, otherwise, do not cut the `VERSION` string.
> Fix build error when revision is shorter than 8 chars

- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
Improve listStatus 5X performance in some scenarios.
For instance,
Under the scenario:
1. Use Hadoop compatible system to access Alluxio(listStatus)
2. There are many mount point such as more than 500.
3. There are more than 2000 files in a directory.
The PathUtils.hasPrefix (comes from MountTable.getMountPoint)method will be called at least 10w (500 * 2000) times.
But actually we don't need the information of mount point.
The test can be reduced from about 400ms to 70ms under the master branch.
The test can be reduced from about 700ms to about 100ms under 2.7.1 branch.
no
> Improve LS by allowing to omit UFS and mount info

- bin/launch-process
Currently if user specifies `MaxRamPercentage` without specifying `Xmx`, Alluxio still gives a defualt `Xmx` which will override the `MaxRamPercentage` because of priority. Fix this by if user specifies `MaxRamPercentage` we don't give a default `Xmx`. 
First step of solving https://github.com/Alluxio/alluxio/issues/10083
Replace https://github.com/Alluxio/alluxio/pull/15819
> Respect MaxRamPercentage in container

- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- integration/fuse/bin/alluxio-fuse
- integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Fix issues when running against file:///local/path.
When using ` file:///local/path/file`, uri.getPath returns `/local/path/file`. UfsStatus.getName is `/local/path/file`, when we transform the ufs status to alluxio status, the status is `file:///local/path/local/path/file` which is wrong.
Using uri.toString to always passing in full URL together with scheme
> Fix Local UFS path

- integration/kubernetes/helm-chart/alluxio/values.yaml
The old registry k8s.gcr.io will be frozen early April 2023. The new registry registry.k8s.io will replace the old one. Thus updating the registry for csi images.
Source: https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
> Update registry for CSI images

- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Remove the ".worker + workerId" from the DBdir
Workers should be running from different dirs. They should have different DBdir configured.
N/A
> Create RocksDBDoraMetaStore in specified dir without workerID

- .github/workflows/checkstyle.yml
- .github/workflows/fuse_integration_tests.yml
- .github/workflows/java8_integration_tests.yml
- .github/workflows/java8_integration_tests_ft.yml
- .github/workflows/java8_integration_tests_webui.yml
- .github/workflows/java8_unit_tests.yml
- .github/workflows/stale.yaml
https://github.com/Alluxio/alluxio/issues/16963
3. webui
> Update ci version

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/StateLockManager.java
- core/server/common/src/test/java/alluxio/master/StateLockManagerTest.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
1. Change tracking threads to keeping thread read lock holder count
2. Log jstack on state lock error so we can further check who are holding the state lock
Make debugging state lock issues slightly easier.
A chunky jstack output will appear in the master.log, which may look intimidating at first glance. This is good because I want people to notice and send the output to us.
> Improve state lock tracking and report on error

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
- core/server/worker/src/test/java/alluxio/worker/dora/RocksDBDoraMetaStoreTest.java
Add a configurable TTL to Dora RocksDBMetaStore, and check if the retrieved metadata has expired or not.
We need a way to invalidate the cached Metadata in RocksDBMetaStore.
A configurable TTL is the easiest way to do so.
A new property key "alluxio.dora.worker.metastore.rocksdb.ttl" is added for this TTL.
> Add configurable TTL for Dora Worker RocksDBMetaStore

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
Enable v2 s3 proxy by default.
s3 api will go thru v2 proxy service now.
> Enable v2 s3 proxy by default

- core/common/src/main/java/alluxio/util/proto/BlockLocationUtils.java
- core/common/src/test/java/alluxio/util/proto/BlockLocationUtilsTest.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- stress/shell/src/main/java/alluxio/stress/cli/RpcBenchPreparationUtils.java
Cache block location object to reduce memory consumption
Number of possible Block location value is limited, up to 9 * number of workers. By caching it, memory consumption can be saved.
N/A
> Cache Block Location to save memory

- core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Pass GetStatusPOption from client to dora Worker.
Invalidate in-memory and persistent metadata based on the GetStatusPOption.CommonOptions.SyncIntervalMs
If the "alluxio.user.file.metadata.sync.interval" is set to a valid number, Alluxio should do metadata invalidation
based this configuration.
N/A
> Implement the metadata invalidation based on user configured interval

- core/client/fs/src/test/java/alluxio/client/file/options/OutStreamOptionsTest.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java
- tests/src/test/java/alluxio/client/fs/TtlIntegrationTest.java
Set the ttlAction back to free to fix the backward compatibility issue from our daily sanity test.
Fix the backward compatibility proto issue from a previous PR
https://github.com/Alluxio/alluxio/pull/16823.
No.
> Set ttlaction back to free

- core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
- integration/fuse/src/main/java/alluxio/cli/command/metadatacache/AbstractMetadataCacheSubCommand.java
1. Add a method `getUnderlyingFileSystem()` in DelegatingFileSystem to get underlying FileSystem;
2. Add judgment logic to the fileSystem in AbstractMetadataCacheSubCommand.
https://github.com/Alluxio/alluxio/issues/17029
1. change in user-facing APIs? false
3. addition or removal of property keys? false
4. webui? false
> Fix fuse metadata command ClassCastException

- core/server/master/src/main/java/alluxio/master/file/LostFileDetector.java
`LostFileDetector` checks all files that are possibly LOST in Alluxio, meaning the data only resides in Alluxio (not PERSISTED) and now cannot be found(no block found).
We used to create one JournalContext when updating each file's status. In this PR we change that to batching, to avoid too many synchronous flushing. This is consistent with https://github.com/Alluxio/alluxio/pull/16529
It is fine to batch because:
1. It's relatively low impact if we lose entries marking inodes as LOST. Losing a file is HIGH impact, while not identifying a lost file is LOW impact. That identification is asynchronous and can be turned off anyways.
2. Even if an inode is marked LOST, we don't have any special handling... The client will just try to read it the same way and results in IOException. That means …
> Merge journal context in LostFileDetector

- core/server/common/src/main/java/alluxio/master/journal/MasterJournalContext.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
`PersistenceChecker` and `PersistenceScheduler` will regularly check all files that need persistence. Some fields in the inode is used to track the persistence status. So PersistenceChecker and PersistentSchedule will constantly update inodes, which creates journal entries. 
Currently one JournalContext is created on processing each file, and closed after this file is processed. This means the journal entries are flushed once per file. In this change, we merge those flushes to:
1. Reduce frequent JournalContext usage, which acquires the state lock
2. Reduce the number of synchronous journal flushes
The idea is also consistent with https://github.com/Alluxio/alluxio/pull/16529
The correctness is guaranteed by:
1. It is fine to lose those journal entries on async persist on failover. If an …
> Merge JournalContext for persistence

- core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java
- core/server/master/src/main/java/alluxio/master/file/meta/TtlBucket.java
- core/server/master/src/main/java/alluxio/master/file/meta/TtlBucketList.java
- core/server/master/src/test/java/alluxio/master/file/meta/TtlBucketListTest.java
- core/server/master/src/test/java/alluxio/master/file/meta/TtlBucketTest.java
- shell/src/main/java/alluxio/cli/fs/command/FileSystemCommandUtils.java
- tests/src/test/java/alluxio/client/fs/TtlIntegrationTest.java
- tests/src/test/java/alluxio/client/fs/concurrent/ConcurrentFileSystemMasterSetTtlIntegrationTest.java
- tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
1)setttl cmd on a big directory unnecessary setattr recursively, while dir ttl already supercedes children ttl. there's absolutely no reason to save ttl on children node individually.
2)ttlbucket unnecessarily saves Inode obj on heap unboundedly, where it could and should only save inodeid and load inode from inodestore to double check expiry during inodettlchecker processing.
3)fix race condition on ttlbucketlists from ttlchecker and insertion from foreground.
4)fix case where any expiration of inodes failed during ttlchecker it will never be retried again.
Reduce heavy GC when setttl on a huge folder / bug fixes as indicated above for ttl 
yes. So now setTtl command on a dir will not set ttl attributes for all its children.
> Fix setTtl workflow and ttlbucket bugs

- docs/en/dora/Deploy-Alluxio-Cluster.md
1. Deploy Dora on K8s can reuse the existing helm chart. The existing helm chart has extra configurations that do not apply to Dora, but also won't error out.
2. Fuse can't be launched with the existing helm chart because the CLI command is not the same.
> [DOCFIX] Add dora deployment on k8s doc

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/util/executor/ExecutorServiceUtils.java
- core/server/common/src/main/java/alluxio/master/journal/checkpoint/CheckpointType.java
- core/server/common/src/main/java/alluxio/master/journal/checkpoint/ZipCheckpointFormat.java
- core/server/common/src/main/java/alluxio/util/ParallelZipUtils.java
- core/server/common/src/test/java/alluxio/util/ParallelZipUtilsTest.java
- core/server/common/src/test/java/alluxio/util/TarUtilsTest.java
- core/server/master/src/main/java/alluxio/master/journal/tool/AbstractJournalDumper.java
- core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java
- tests/src/test/java/alluxio/server/ft/journal/TriggeredCheckpointTest.java
Cherry pick of https://github.com/Alluxio/alluxio/pull/16151
Parallel zip compression and decompression can be used for RocksInodeStore.
Checkpoint is too slow for RocksIndoeStore with more than 1 billion data
It can be enabled by alluxio.master.parallel.backup.rocksdb, and the degree of parallelism can be determined by alluxio.master.parallel.backup.rocksdb.thread.pool.size
> Support multithread checkpointing with compression/decompression

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
- core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
- core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
- core/transport/src/main/proto/grpc/block_worker.proto
- core/transport/src/main/proto/grpc/table/layout/hive/hive.proto
- core/transport/src/main/proto/proto.lock
This first version of ListStatus from client to Dora worker.
More items are needed:
divide big directory contents into batch limited by max batch size.
Dora client sends ListStatus() request to Dora Worker, and Worker sends ListStatus()
to UFS, and then the results are propagated back.
This is the first step to do worker side ListStatus() cache.
N/A
> Implement ListStatus RPC from client to Worker in Dora

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
- tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
- tests/src/test/java/alluxio/server/ft/FileSystemMasterFaultToleranceIntegrationTest.java
- tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTestFaultTolerance.java
This fixes an issue caused by https://github.com/Alluxio/alluxio/pull/16529
That PR reduced the number of journal flushes during metadata sync using embedded journal, but was not compatible with ufs journal as in ufs journal each master has a different journal file.
This PR disables that change when using ufs journal.
> Fix metadata sync journalling when using UFS journal

- core/common/src/main/java/alluxio/util/ThreadUtils.java
In Alluxio, each component's WebUI `host:port/stacks` shows all thread stacks in the current component. This change makes the output format align with `jstack` command, so analyzer tools like https://fastthread.io/ can parse it.
See above
Now can use [FastThread ](https://fastthread.io/) to analyze the `stacks` output result  of threaddump
> Improve thread dump format to match jstack

- core/common/src/main/java/alluxio/retry/RetryUtils.java
- core/common/src/main/java/alluxio/underfs/ObjectLowLevelOutputStream.java
This fixes the retry utils function so it throws an IOException when the retires run out. Currently it throws a null pointer exception as it tries to throw a null exception.
It also fixes the retires in the low level object output stream.
> Fix retry function and S3 abort upload

- underfs/gcs/src/main/java/alluxio/underfs/gcs/v2/GCSV2OutputStream.java
The content hash for the fingerprint was being calculated using the wrong value for the GCS v2 stream. This fixes it.
> Fix content hash for GCS v2 stream

- core/common/src/main/java/alluxio/conf/PropertyKey.java
Fix a typo in the property. the matcher pattern is not aligned with the expected content. 
Fix a typo in the property. the matcher pattern is not aligned with the expected content.
> Fix property identity typo error

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/util/ThreadUtils.java
- core/server/common/src/main/java/alluxio/ProcessUtils.java
- core/server/common/src/main/java/alluxio/Registry.java
- core/server/common/src/main/java/alluxio/master/StateLockManager.java
- core/server/common/src/main/java/alluxio/metrics/sink/MetricsServlet.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java
The master/worker processes will dump jstack/metrics when:
1. Process exits normally, from an error, or SIGTERM from `alluxio-stop.sh`. (Note that segfault is abrupt and the process doesn't have a chance to output these information.)
2. Primary master fails over to standby.
The major changes in the code are:
1. Dumping those information into files
2. CollectInfo and CollectLog commands will capture those output files
3. Change the jstack dumping to async (https://github.com/Alluxio/alluxio/commit/9ae71902499b005852563055ae5135e97833e274 changed that to sync), so we don't block the process. The trade off is the output is not totally consistent. That should be acceptable in troubleshooting.
This change depends on https://github.com/Alluxio/alluxio/commit/9ae71902499b005852563055ae5135e97833e …
> Dump metrics + stacks on failover/crash

- core/server/common/src/main/java/alluxio/master/journal/FileSystemMergeJournalContext.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
1. do not use the FileSystemMergeJournalContext in list status operation as well as other operations that calls the FileSystemMaster public createJournalContext() method, because some of these callers does not expect journals to be held in the context until it gets closed.
2. force flushing journals if too many journals in the FileSystemMergeJournalContext
3. better observerability 
A PR that addressed inode operation consistency issue 
https://github.com/Alluxio/alluxio/pull/17071/files caused issues on master side and made fuse unable to connect to it. https://github.com/Alluxio/alluxio/issues/17041
That PR introduced a FileSystemMergeJouralContext that keeps inode operation journals in memory and merges these journal entries on the fly. When the journal context closes, all of the …
> Fix file system merge journal context

- core/server/proxy/src/main/java/alluxio/proxy/s3/signature/AwsSignatureProcessor.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/signature/StringToSignProducer.java
Fix NPE for S3 Porxy.
When we enable s3 v2 and authentication, the NullPointException will occur:
```
alluxio.s3.rest.authentication.enabled=true
alluxio.proxy.s3.v2.version.enabled=true
```
like: 
```
2023-03-14 22:54:51,738 ERROR S3Handler - Exception during create s3handler:alluxio.proxy.s3.S3Exception
at alluxio.proxy.s3.signature.AwsSignatureProcessor.getAuthInfo(AwsSignatureProcessor.java:138)
at alluxio.proxy.s3.S3RestUtils.getUserFromSignature(S3RestUtils.java:576)
at alluxio.proxy.s3.S3RestUtils.getUser(S3RestUtils.java:562)
at alluxio.proxy.s3.S3Handler.doAuthentication(S3Handler.java:458)
at alluxio.proxy.s3.S3Handler.init(S3Handler.java:230)
at alluxio.proxy.s3.S3Handler.createHandler(S3Handler.java:147)
at alluxio.proxy.s3.S3RequestServlet.service(S3RequestServlet.java:73)
at …
```
> Fix NPE for s3 proxy v2

- shell/src/main/java/alluxio/cli/bundler/command/CollectMetricsCommand.java
1. We added more information to the response JSON string. Make the whole thing a JSON string for easier parsing.
2. Refactor the get metrics part for reusing.
> Refactor collectMetrics command

- integration/docker/Dockerfile
- integration/docker/csi/go.mod
- integration/docker/csi/go.sum
Bump go version and some package version in Alluxio CSI module to fix some security alert brought up by Github Dependabot some time ago.
> Bump CSI package version to fix security alert

- core/server/master/pom.xml
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterS3UfsTest.java
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- pom.xml
- tests/pom.xml
- tests/src/test/java/alluxio/client/fs/FileSystemS3UfsIntegrationTest.java
- underfs/pom.xml
- underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemMockServerTest.java
Introduce a s3 mock server and used it in unit testing
When we doing the new metadata sync redesign project, we need a reliable way to test the interactions with s3 UFS and help us deal with corner cases. 
N/A
> Introduce S3 mock server to enhance unit testing

- core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Dora Worker service should try to check the types of the exceptions.
If they are known, Dora worker should convert them to known gRPC exceptions and return them back.
If the exception types are known, we can handle the exceptions better, e.g. retry the operation or try alternatives.
N/A
> Return specific exception in Worker handler if it is known

- shell/src/main/java/alluxio/cli/bundler/command/CollectMetricsCommand.java
In container env worker address is stored in the field `mContainerHost`, not in `mHost`. `getHost()` will get the host machine hostname, which is not what we want.
> Fix collectMetrics command in k8s

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
Add properties to config s3 proxy v2 thread pool.
for light pool:
1. `alluxio.proxy.s3.v2.async.light.pool.core.thread.number`  ;
2. `alluxio.proxy.s3.v2.async.light.pool.maximum.thread.number`;
3. `alluxio.proxy.s3.v2.async.light.pool.queue.size`.
for heavy pool:
1. `alluxio.proxy.s3.v2.async.heavy.pool.core.thread.number` ;
2. `alluxio.proxy.s3.v2.async.heavy.pool.maximum.thread.number`;
3. `alluxio.proxy.s3.v2.async.heavy.pool.queue.size`.
We config `alluxio.web.threads` as 1000, because our OPS has reached 2000. The default value of thread number is not big enough.
> Make light and heavy thread pool configurable for s3 proxy v2

- shaded/client/pom.xml
**PR Background - Bug description:**
[PrestoDB](https://prestodb.io/) and [TrinoDB](https://trino.io/) use our shaded JAR in their `pom.xml`. When upgrading the version of `alluxio-shaded-client` from `2.8.1` to `2.9.1`, we fail to compile the codes of presto/trino. This is because there is dependency conflict.
**Solution:**
Relocate the dependencies in `shaded/client/pom.xml` to avoid deplicate classes and files.
**TIPS:** You can execute `cd ${ALLUXIO_HOME}/shaded && mvn clean install -Prelease -DskipTests -T 4C` to package the shaded JAR.
> Fix dependencies conflicts thrown by trino

- conf/log4j.properties
Add filename:linenumber:threadid details into default log4j settings so logs could be more informative when doing debugging.
During debugging, it is hard to trace events for one particular file/event/thread with current default log4j settings
N/A
> Add more details in Log4j default settings

- job/server/src/main/java/alluxio/master/job/plan/PlanCoordinator.java
Fixing a typo by removing duplicate word in comments.
> Remove duplicate word in comments

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/util/ThreadUtils.java
- core/server/common/src/main/java/alluxio/ProcessUtils.java
- core/server/common/src/main/java/alluxio/metrics/sink/MetricsServlet.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
- core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
- shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java
The master/worker processes will dump jstack/metrics when:
1. Process exits normally, from an error, or SIGTERM from `alluxio-stop.sh`. (Note that segfault is abrupt and the process doesn't have a chance to output these information.)
2. Primary master fails over to standby.
The major changes in the code are:
1. Dumping those information into files
2. CollectInfo and CollectLog commands will capture those output files
3. Change the jstack dumping to async (https://github.com/Alluxio/alluxio/commit/9ae71902499b005852563055ae5135e97833e274 changed that to sync), so we don't block the process. The trade off is the output is not totally consistent. That should be acceptable in troubleshooting.
This change depends on
https://github.com/Alluxio/alluxio/commit/9ae71902499b005852563055ae5135e97833e …
> Port changes of [#17081] to branch-2.8

- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
Avoid getting meta sync lock if no need.
After backporting #16241, "ls /" encountered the following exception 
```
2023-03-30 14:00:51,657 ERROR FileSystemMasterClientServiceHandler - Exit (Error): ListStatus: request=path: "/"
options {
loadMetadataType: ONCE
commonOptions {
syncIntervalMs: 86400000
ttl: -1
ttlAction: DELETE
}
recursive: false
loadMetadataOnly: false
}
java.lang.RuntimeException: Call cancelled by trackers: GRPC_CLIENT_TRACKER
at alluxio.master.file.RpcContext.throwIfCancelled(RpcContext.java:107)
at alluxio.master.file.InodeSyncStream.sync(InodeSyncStream.java:322)
at alluxio.master.file.DefaultFileSystemMaster.syncMetadata(DefaultFileSystemMaster.java:3816)
at alluxio.master.file.DefaultFileSystemMaster.listStatus(DefaultFileSystemMaster.java:1042)
...
```
We found …
> Avoid getting meta sync lock if no need

- core/server/master/src/main/java/alluxio/master/job/AbstractJob.java
- core/server/master/src/main/java/alluxio/master/job/LoadJob.java
- core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
- job/common/src/main/java/alluxio/scheduler/job/Job.java
When we restore a job from the journal we would call setJobStatus and would double count job that already finished successfully
fix bug
na
> Fix double counting job success when restore job from journal

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
Print exception stack for s3 proxy.
Sometimes, the message of exception is null, and we need print stack to find where the exception occurred.
Before add exception stack:
```
2023-03-24 14:47:50,164 INFO  ProxyWebServer - [ACCESSLOG] ListObjects Request:Request[GET //localhost:39999/api/v1/s3/s3/?prefix=user%2Fhumengyu%2Fword1&encoding-type=url]@54efde7a - Status:500 - ContentLength:None - Elapsed(ms):561
2023-03-24 14:47:50,325 WARN  S3RestUtils - Error invoking REST endpoint for s3:
null
2023-03-24 14:47:50,328 INFO  ProxyWebServer - [ACCESSLOG] ListObjects Request:Request[GET //localhost:39999/api/v1/s3/s3/?prefix=user%2Fhumengyu%2Fword1&encoding-type=url]@54efde7a - Status:500 - ContentLength:None - Elapsed(ms):18
2023-03-24 14:47:50,469 WARN  S3RestUtils - Error invoking REST …
```
> Print exception stack in s3 proxy

- shell/src/main/java/alluxio/cli/TestRunner.java
both https://github.com/Alluxio/alluxio/pull/17170/files#diff-c80fd5152cf94b0cc483c26efb94f3946af189626fc4f10c0232bf968432078e and https://github.com/Alluxio/alluxio/pull/17068/files introduced the same change but in different lines so the merge was clean, but resulted in parsing args twice
caught by running `bin/alluxio runTests --directory /path/to/dir` with error msg:
```
error: Exception in thread "main" com.beust.jcommander.ParameterException: Can only specify option --directory once.
at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:240)
at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:913)
at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:894)
at com.beust.jcommander.JCommander.parseValues(JCommander.java:724)
at …
```
> Fix double arg parsing in runTests

- core/server/worker/src/main/java/alluxio/worker/netty/FileReadHandler.java
Use URI hash as PageId for netty FileReader
We use  URI hash as PageId everywhere else.
N/A
> Use URI hash as PageId for netty FileReader

- dev/github/Dockerfile-jdk11
fixes a deadlock issue in parallel builds that we are encountering when building the repo
https://maven.apache.org/docs/3.8.6/release-notes.html
> Bump alluxio-maven maven version to 3.8.6

- .github/workflows/fuse_integration_tests.yml
- .github/workflows/java11_integration_tests.yml
- .github/workflows/java11_integration_tests_ft.yml
- .github/workflows/java11_integration_tests_webui.yml
- .github/workflows/java11_unit_tests.yml
- dev/github/run_checks.sh
- dev/github/run_docker.sh
- dev/github/run_tests.sh
update default alluxio-maven docker image used to the `0.1.0-jdk11` tag. this changes the default jdk from 8 to 11 and upgrades maven from 3.6.3 to 3.8.5
rename github action workflows from jdk8 -> jdk11
> Use java11 for builds

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
1. when s3 write type is CACHE_THRU, initiateMultipartUpload creates MultipartMetaFile without closing the outstream, causing leak in BlockWorkerClient resource.
2. createFilePOption in CopyObject didn't set any write type (which should respect alluxio.proxy.s3.writetype), causing all objects copied are in the MUST_CACHE write type.
To fix the above 2 problems.
No.
> Fix CopyObject writetype and unclosed outstream in InitiateMPUpload

- shaded/client/pom.xml
This PR is the same as [PR#17129](https://github.com/Alluxio/alluxio/pull/17129) except that it is for dora
PR Background - Bug description:
[PrestoDB](https://prestodb.io/) and [TrinoDB](https://trino.io/) use our shaded JAR in their pom.xml. When upgrading the version of alluxio-shaded-client from 2.8.1 to 2.9.1, we fail to compile the codes of presto/trino. This is because there is dependency conflict.
Solution:
Relocate the dependencies in shaded/client/pom.xml to avoid duplicate classes and files.
TIPS: You can execute `cd ${ALLUXIO_HOME}/shaded && mvn clean install -Prelease -DskipTests -T 4C` to package the shaded JAR.
> Fix dependencies conflicts thrown by trino and prestodb

- bin/alluxio-common.sh
- bin/alluxio-masters.sh
- bin/alluxio-workers.sh
Skip ssh connection while running locally.
I was trying to setup a one-node cluster with the latest version to do some simple tests. However, I encountered the following exception while executing `/bin/alluxio format`
```
$ ./bin/alluxio format
Executing the following command on all worker nodes and logging to /home/test/deploy/alluxio/logs/task.log: /home/test/deploy/alluxio/bin/alluxio formatWorker
Waiting for tasks to finish...
test@localhost's password:
test@localhost's password:
test@localhost's password:
Task on 'localhost' fails, exit code: 255
There are task failures, look at /home/test/deploy/alluxio/logs/task.log for details.
```
In the log, it has
```
[2023-03-24 17:12:20][localhost] Failed to add the host to the list of known hosts (/home/test/.ssh/known_hosts).
[2023-03-24 …
```
> Skip ssh for localhost

- core/common/src/main/java/alluxio/conf/PropertyKey.java
There is a property key brought into 2.8 during cherry pick by accident. This change removes it.
> [SMALLFIX] Remove unrelated property key

- core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
Add a path SEPARATOR to the end of the path for root
Because when concat the ufs root with "/", the ending "/" will be trimmed.
We need it for HDFS UFS.
This bug only exists for HDFS UFS.
N/A
> Fix ufs root issue when HDFS is used as UFS

- core/common/src/main/java/alluxio/conf/PropertyKey.java
If we develop a new Propertykey and give the inappropriate default value, the master will not start successfully, and we cannot find which Propertykey is bad.
So I improve the prompt and show the related Propertykey
Show the related Propertykey of inappropriate default value
NO
> Show the invalid default value and key name

- core/common/src/main/java/alluxio/extensions/ExtensionFactoryRegistry.java
**Background:**
For each connector (e.g. hive-hadoop2), Presto uses an independent `PluginClassLoader` to load its classes. However, in our dora's client, it also use an `ExtensionsClassloader` to load the classes for each UFS implementation. Moreover, it breaks the parent delegation and uses `ClassLoader.getSystemClassLoader()`
as its parent's class loader. So only when the new class loader cannot load the classes, it calls its parent's class loader (`ClassLoader.getSystemClassLoader()`) to load the classes. However, the classes in `${PRESTO_HOME}/plugin/hive-hadoop2/alluxio-shaded-client-2.10.0-SNAPSHOT.jar` is loaded by the PluginClassLoader, but not the `ClassLoaders$AppClassLoader.` Therefore, Presto throws No under file system factory found exception during the time we are querying …
> Use thread context class loader instead to avoid presto exception

- core/common/src/main/java/alluxio/util/io/PathUtils.java
- core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
- core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
Improve the performance of MountTable.getMountPoint
Currently the implementation of `MountTable.getMountPoint` needs to iterate through all mount points. In one of our Alluxio clusters, there are more than 300 mount points. The leader alluxio master had very high load and we found `MountTable.getMountPoint` cost most of the cpu time.
This PR can improve the performance a lot especially for clusters with lots of mount points.
Below is the time cost of calling `MountTable.getMountPoint` 1000 times when there are 300 mount points
| version | time cost (ms) |
| --- | --- |
| master | 142 |
| PR | 6 |
NO
> Improve the performance of MountTable.getMountPoint

- shaded/client/pom.xml
Both Presto and Alluxio use guice for dependency injection, and the versions of guice may be different in Presto and Alluxio. Therefore, we add relocation for guice avoiding dependency conflict with Presto.
> Add relocation for guice avoiding dependency conflict with Presto

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
Add a metric to measure the number of running scheduler job commands.
To measure the number of running scheduler commands, which can be used in the distributed copy or load.
No.
> Add a metric for the number of running scheduler job commands

- dev/scripts/src/alluxio.org/build-distribution/cmd/common.go
- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-fuse-tarball.go
- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-release-tarballs.go
- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
Remove k8s-related code from build tarball script. It breaks the build process.
> Remove k8s from build tarball script in Dora

- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- core/client/fs/src/test/java/alluxio/client/file/ufs/UfsBaseFileSystemTest.java
- core/client/hdfs/src/main/java/alluxio/hadoop/FileSystem.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Construct correct path for URIStatus from UFSStatus.
When user issues listStatus(path), the returned result from UFS is relative path from the requested path.
We need to concat the result path after the requested path.
N/A
> Fix path for URIStatus from UFSStatus

- core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Invalidate cached File when its metadata cache expires
Because we don't know if the data has changed.
TODO: we need a better way to determine if the data is still valid.
N/A
> Invalidate Cached File

- stress/common/src/main/java/alluxio/stress/worker/IOTaskSummary.java
- stress/common/src/test/java/alluxio/stress/worker/IOTaskSummaryTest.java
Fix the aggregate result problem in UfsIOBench.
The  UfsIOBench result summary calculates the total duration by summing each  points' result, and   compute the average speed based on total duration, actually the average can't  represent the system performance. 
For examples: 
An alluxio cluster with 1 job master and 3 job worker,  Run the UfsIOBench with 16 threads:
```
./bin/alluxio runUfsIOTest --path hdfs://hdfsCluster/tmp/ufsIoBanch --io-size 2G--threads 16 --cluster
```
the mTotalDurationSeconds is 16 * 3 *(points duration), but actually the 16 points read and write concurrently  and finished almostly at same time.
No
> Fix the aggregate result problem in UfsIOBench

- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- core/client/fs/src/test/java/alluxio/client/file/ufs/UfsBaseFileSystemTest.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Set the URIStatus.path to a relative path against  `alluxio.master.mount.table.root.ufs`
The returned URIStatus from listStatus() and getStatus() needs to be relative to `alluxio.master.mount.table.root.ufs`.
In the original code, we set the relative path to the top level root. That is not the right one if mounted like   `s3://<BUCKET>/<DIR>`
N/A
> Fix relative path if mounted like s3://<BUCKET>/<DIR>

- core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
If listStatus() return empty result, maybe the request path is a file, not a dir.
So try getStatus() for this file.
listStatus() should work for both directory and file. This is the default behavior for most of the UFS, such as HDFS and S3.
N/A
> Handle FileNotFound exception and retry getStatus() instead

- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/server/worker/src/main/java/alluxio/worker/block/UfsIOManager.java
The exponential moving average used for meter can produce inaccurate rate when computing transfer rate.
The reason is that we call mark(number of bytes) when a transfer is finished to indicate how many bytes have been transfered, but that is inaccurate in calculating an average rate which is really what we want in a Bytes/Sec calculation.
SlidingTimewindow produces a moving average that is more correct especially when a short window is used
https://www.javadoc.io/static/io.dropwizard.metrics/metrics-core/4.1.1/com/codahale/metrics/SlidingTimeWindowMovingAverages.html
no
> Use SlidingTimeWindow Moving Average for meter computation

- core/server/master/src/main/java/alluxio/master/file/FileSystemJournalEntryMerger.java
- core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemJournalEntryMergerTest.java
- core/server/master/src/test/java/alluxio/master/file/meta/LockedInodePathTest.java
1. Only force flushing journals when a locked inode path is closed for FileSystemMergeJournalContext
2. Fix the journal merger broken logic where updating the fingerprint for a directry will be ignored.
We used to fix the merge journal context in https://github.com/Alluxio/alluxio/pull/17071, where a regular non-merging journal context is used when listStatus() is called. 
However, if a listStatus triggers a metadata sync and MASTER_FILE_SYSTEM_MERGE_INODE_JOURNALS is set to true, journals will be flushed on every lockedInodePath close during the metadata sync. This behavior leads to journals being flushed too many times and impairs the metadata sync performance. 
Also we found a minor issue that when inode directory journals are merged, the fingerprint will be ignored. This is becuase …
> Fix FileSystemMergeJournalContext related

- core/client/fs/src/main/java/alluxio/util/FileSystemOptionsUtils.java
Before this PR, if we did not config `alluxio.user.file.metadata.sync.interval` in client side, and config it in master side while we disable the `alluxio.user.conf.cluster.default.enabled` meanwhile, the metadata sync interval will always set to `-1`. 
After this PR, when `alluxio.user.conf.cluster.default.enabled=false`, master side `alluxio.user.file.metadata.sync.interval` will be accepted if user didn't set it.
No
> Do not pass sync interval by default

- core/common/src/main/java/alluxio/conf/PropertyKey.java
This will result in longer cache life for metadata. It increases metadata operation performance. This is suitable for read-only use case.
Increase TTL values for metadata cache. Increase to 48 hours. If the metadata is not used in 48 hours, they can be considered not needed in near future.
For better performance.
N/A
> Set Metadata cache TTL to 48 hours

- core/common/src/main/java/alluxio/network/protocol/databuffer/RefCountedNioByteBuf.java
- core/common/src/test/java/alluxio/network/protocol/databuffer/RefCountedNioByteBufTest.java
Fix an infinite recursion with `RefCountedNioByteBuf.setBytes` which causes stack overflow error.
The current implementation of `RefCountedNioByteBuf.setBytes(int index, ByteBuf src, int srcIndex, int length)` delegates the copying of bytes to the `getBytes(int index, ByteBuf dst, int dstIndex, int length)` method of the source buffer.
In some implementations of a direct `ByteBuf`, e.g. [`io.netty.buffer.UnpooledUnsafeDirectByteBuf`](https://github.com/netty/netty/blob/d773f37e3422b8bc38429bbde94583173c3b7e4a/buffer/src/main/java/io/netty/buffer/UnpooledUnsafeDirectByteBuf.java), the `getBytes(int index, ByteBuf src, int srcIndex, int length)` method in turn delegates the call back to the `setBytes` method of the destination buffer …
> Fix infinite recursion with RefCountedNioByteBuf.setBytes

- core/client/fs/src/main/java/alluxio/client/file/PositionReadFileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/PositionReadFileInStreamTest.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/test/java/alluxio/ByteArrayPositionReader.java
Use dynamic buffering for sequential read.
It's hard to assume the consumer of a seekable, positioned readable input stream will be doing sequential reads. If the consumer randomly reads from different positions, then it would be pointless to do aggressive buffering since it would only cause read amplification and wastes time and bandwith.
Otherwise, if the read sequence is consecutive, then it can benefit from prefetching and buffering.
The idea of this PR is to first observe the read sequence, calculate the length of consecutive reads, and based on that, tries to prefetch data from the underlying reader. It keeps a sliding window of recent read calls, and use the sum of the consecutive read lengths in the window as the size of the prefetch.
With dynamic buffering, the prefetch size will …
> Use dynamic buffering for sequential read in PositionReadFileInStream

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
Manual cherry pick of https://github.com/Alluxio/alluxio/pull/16618
Clear worker.buildVersion when it's not set in proto.
Note: Since we are using protobuf3 to compile proto2, it's OK to omit hasField check.
If the field is not set, the default instance will be returned.
Steps to reproduce:
Start a new cluster (master and worker).
Stop the new worker.
Start a old worker (prior to https://github.com/Alluxio/alluxio/commit/7d8ad9b12ab366ef85c05a7cedfa3a60a562de12) using the same config.
Check workers in web UI.
Previously, if we downgrade a worker to a versions prior to https://github.com/Alluxio/alluxio/commit/7d8ad9b12ab366ef85c05a7cedfa3a60a562de12,
the buildVersion is stale.
Does this PR introduce any user …
> Port changes of [#16618] to branch-2.8

- core/client/fs/src/main/java/alluxio/client/block/policy/SpecificHostPolicy.java
- core/client/fs/src/main/java/alluxio/client/file/options/InStreamOptions.java
- core/client/fs/src/main/java/alluxio/client/file/options/OutStreamOptions.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- core/transport/src/main/proto/proto.lock
- shell/src/main/java/alluxio/cli/BasicNonByteBufferOperations.java
- shell/src/main/java/alluxio/cli/BasicOperations.java
- shell/src/main/java/alluxio/cli/TestRunner.java
Support executing the runTests command on specific workers.
e.g. 
./alluxio runTests --workers worker1:29998,worker2:29998
If the workers are specified, runTests will be executed for each worker with writes and reads to go a dedicated worker.
So that we can verify if workers are up 
N/A
> Port changes of [#17170] to branch-2.8

- core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
Avoid using mBlockMasterClientPool directly.
Using mBlockMasterClientPool during reinit may throw an exception.
> Avoid null when using BlockMasterClientPool

- core/common/src/main/java/alluxio/job/CopyJobRequest.java
- core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
- core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
- core/server/master/src/main/java/alluxio/master/job/JobFactoryProducer.java
- core/server/master/src/main/java/alluxio/master/job/JournalCopyJobFactory.java
- core/server/master/src/main/java/alluxio/master/job/LoadJob.java
- core/server/master/src/main/java/alluxio/master/job/UfsFileIterable.java
- core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
- core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
- core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- core/server/worker/src/main/java/alluxio/worker/task/CopyHandler.java
- core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
- core/transport/src/main/proto/grpc/block_worker.proto
- core/transport/src/main/proto/proto/journal/job.proto
Fix the issue that when Copy job using ufsIterable, the listStatus doesn't apply to the file. So add an API to fetch file information as well.
Also, use the full ufs path through the whole copy process.
na
na
> Fix listStatus from ufs

- core/common/src/main/java/alluxio/master/WorkerState.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
- core/server/master/src/main/java/alluxio/master/block/meta/WorkerState.java
- core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
- core/server/master/src/test/java/alluxio/master/block/meta/MasterWorkerInfoTest.java
- shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java
- shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
- tests/src/test/java/alluxio/client/cli/fsadmin/command/CapacityCommandIntegrationTest.java
```
bin/alluxio fsadmin report capacity
Capacity information for all workers:
Total Capacity: 10.67GB
Tier: MEM  Size: 10.67GB
Used Capacity: 0B
Tier: MEM  Size: 0B
Used Percentage: 0%
Free Percentage: 100%
Format is short: true
Format is %-16s %-15s %-16s %-13s %s %-16s %-40s
Worker Name      State           Last Heartbeat   Storage       MEM              Version          Revision
192.168.3.8      ACTIVE           166              capacity      10.67GB          2.10.0-SNAPSHOT  ffcb706497bf47e43d5b2efc90f664c7a3e7014e
used          0B (0%)
```
Please list the user-facing …
> Make capacity command show worker state

- core/common/src/main/java/alluxio/util/io/PathUtils.java
- core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
- core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
This reverts commit f7e811c384e8049eb32a66721834cacf03f1dd30.
this causes a 20% performance degradation for the list directory metadata operation
> Revert "Improve the performance of MountTable.getMountPoint"

- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
Fix a bug where when a decommissioned worker registers after restart, it is not recognized and allocated a new ID.
This bug only emerges in 2.8 and was caused by cherry picking.
Verified the fix locally
```
➜  bin/alluxio fsadmin report capacity
Capacity information for all workers:
Total Capacity: 3072.00MB
Tier: MEM  Size: 3072.00MB
Used Capacity: 0B
Tier: MEM  Size: 0B
Used Percentage: 0%
Free Percentage: 100%
Worker Name      State           Last Heartbeat   Storage       MEM              Version          Revision
192.168.3.5      Decommissioned  163              capacity      3072.00MB        2.8.0-SNAPSHOT   36e7d4784ee084f0ea76d513a69436c62180ab8f
used          0B (0%)
➜ bin/alluxio-start.sh worker
Assuming NoMount by default.
Successfully Killed 1 process(es) successfully on …
```
> Fix decommissioned worker recorded twice after restart

- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- core/server/master/src/main/java/alluxio/master/meta/RetryHandlingMetaMasterMasterClient.java
- core/transport/src/main/proto/grpc/meta_master.proto
- core/transport/src/main/proto/proto.lock
Fix a bug where standby masters don't send the version info to primary.
This bug only emerges in 2.8 and was caused by cherry picking.
> Fix standby master version not shown

- pom.xml
the dockerfile at dev/github/Dockerfile-jdk11 defines the build environment with maven 3.8.6. update the `maven.version` property in pom.xml to match
> Update maven.version in pom.xml to match Dockerfile

- pom.xml
not sure how this `java.version` property in the pom.xml affects the build after changing everything else to java 11. referenced as a configuration value for the `maven-compiler-plugin` and `maven-enforcer-plugin`
> Update java.version in pom.xml to 1.11

- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
mentioned in #16629 
The `Cluster.ActiveRpcReadCount` metric could get an impossible value like a negative number. The main reason is that the request handling doesn't cover all situations.
Nope
> Fix the active rpc metrics

- docs/en/administration/Upgrade.md
- docs/en/operation/Admin-CLI.md
This is the doc update from a few recent commits:
1. https://github.com/Alluxio/alluxio/commit/aee3c5cb960b2e472f4fcdb86e731ca3b91d2f8c
2. https://github.com/Alluxio/alluxio/commit/9a4e154e7293667572fec25c63136462fb58a345
3. https://github.com/Alluxio/alluxio/commit/dbac084c1e1d89c1e9253da036746e2df9e1ef14
4. https://github.com/Alluxio/alluxio/commit/8da59539201cff376c33256846bd565d976a148e
5. https://github.com/Alluxio/alluxio/commit/141ee0e567a4c6c60907f85ea66b828704bd761d
6. https://github.com/Alluxio/alluxio/commit/26257e6f35c57d937f6f5bdee831facc2fcf7e1a
In short, a few improvements have been added that the admin can now see the version/revision of the running Alluxio components in the cluster. A few commands were also added to help with gracefully decommissioning/restarting workers …
> [DOCFIX] Add docs for rolling upgrade and decommission worker

- common/transport/pom.xml
- dora/core/client/fs/pom.xml
- dora/microbench/pom.xml
- dora/pom.xml
- pom.xml
Fix the following warnings
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.alluxio:alluxio-core-transport:jar:295-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for com.salesforce.servicelibs:proto-backwards-compatibility is missing. @ line 137, column 15
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.alluxio:alluxio-core-client-fs:jar:295-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.alluxio:alluxio-underfs-local:jar -> duplicate declaration of version ${project.version} @ line 109, column 17
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.alluxio:alluxio-microbench:jar:295-SNAPSHOT …
```
> Fix building warnings due to POM issues

- core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
Don't print a warning in log if the deprecated config is not set by the user explicitly.
Even if a deprecated config is not set, when a client or a worker loads cluster default config from master, the config is considered to be `CLUSTER_DEFUALT` level, and triggers a deprecation warning.
This PR changes the condition for a deprecation message to be logged to be that the level is higher than `CLUSTER_DEFAULT`, which is the same condition used by `isSetByUser`.
After this change, if a deprecated config does get set in `alluxio-site.properties`, the config source level would be `SITE_PROPERTIES` and get logged at the master's log.
No.
> Fix verbose config deprecation warning

- dora/core/common/pom.xml
- dora/core/common/src/main/java/alluxio/grpc/GrpcSerializationUtils.java
- pom.xml
Bump grpc & netty version
1. We want to try netty io_uring feature 
2. The new aws client we are going to introduce relies on newer version of netty 
3. Current grpc & netty versions do not match. (https://github.com/grpc/grpc-java/blob/master/SECURITY.md)
N/A
> Bump grpc & netty version

- core/common/src/main/java/alluxio/conf/AlluxioProperties.java
- core/common/src/main/java/alluxio/conf/Configuration.java
- core/common/src/main/java/alluxio/conf/Hash.java
- core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- core/common/src/main/java/alluxio/wire/ConfigHash.java
- core/common/src/main/java/alluxio/wire/Configuration.java
- core/common/src/main/java/alluxio/wire/MasterWebUIConfiguration.java
- core/common/src/main/java/alluxio/wire/WorkerWebUIConfiguration.java
- core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- core/server/master/src/main/java/alluxio/master/meta/PathProperties.java
- core/server/master/src/main/java/alluxio/master/meta/PathPropertiesView.java
- core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/transport/src/main/proto/grpc/meta_master.proto
- core/transport/src/main/proto/proto.lock
- microbench/src/main/java/alluxio/fsmaster/BenchStandaloneGrpcServer.java
Display the config hash and config updated time
3. webui
> Support display config hash and timestamp in web page

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
- core/common/src/main/java/alluxio/network/RejectingServer.java
- core/common/src/test/java/alluxio/conf/ConfigurationBuilder.java
- core/common/src/test/java/alluxio/master/PollingMasterInquireClientTest.java
Make the client poll the master concurrently.
Currently, we find the active master node by polling each node in series. If a node did not respond due to network or other issues, this may take a lot of time and affect service availability. Make the client poll the master concurrently can alleviate this problem.
> Make the client poll the master concurrently

- dev/scripts/src/alluxio.org/build/modules.yml
module paths need to be renamed after moving module directories under `dora/`
> Fix pl path for modules

- dora/integration/pom.xml
- dora/microbench/pom.xml
- pom.xml
- webui/pom.xml
- Fix maven building warnings like "[warning] parameter 'legacyConfigExcludes' (user property 'license.excludes') is deprecated: use {@link licenseset#excludes}". The previous way to config `license-maven-plugin` is deprecated.
Code hygiene
No
> Fix legacy config in licence checking

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
When the filesystem establishes a connection with the master, the configuration of the filesystem will be overridden by the master's configuration, resulting in changes. Therefore, we should not use the configuration of the filesystem anymore, but instead use the configuration of the local client.
It is very common for the master configuration and client configuration to be different. We should avoid the newly created filesystem from being influenced by the server.
3. webui
> Use local conf to create filesystem for s3proxy

- common/transport/src/main/proto/grpc/file_system_master.proto
- common/transport/src/main/proto/proto/journal/job.proto
- dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- dora/core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
- dora/core/common/src/main/java/alluxio/underfs/AtomicFileOutputStream.java
- dora/core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- dora/core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
- dora/core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
- dora/core/common/src/main/java/alluxio/underfs/options/GetStatusOptions.java
- dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/JournalCopyJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/UfsFileIterable.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
- dora/core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java
- dora/core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTestBase.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/CopyJobTest.java
- dora/core/server/worker/src/main/java/alluxio/worker/task/CopyHandler.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
- dora/tests/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java
- dora/tests/src/test/java/alluxio/testutils/underfs/sleeping/SleepingUnderFileSystem.java
- dora/underfs/abfs/src/main/java/alluxio/underfs/abfs/AbfsUnderFileSystem.java
- dora/underfs/adl/src/main/java/alluxio/underfs/adl/AdlUnderFileSystem.java
- dora/underfs/cephfs/src/main/java/alluxio/underfs/cephfs/CephFSUnderFileSystem.java
- dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
- dora/underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
- dora/underfs/wasb/src/main/java/alluxio/underfs/wasb/WasbUnderFileSystem.java
- dora/underfs/web/src/main/java/alluxio/underfs/web/WebUnderFileSystem.java
Couple fixes for copy on dora
1. support passing check content option from cli
2. support passing ufs full path from cli
3. delete temp file only when exceptional case
4. skip if file is already in dst instead of throw exception
5. cleanup getStatus method in ufs and fix bugs that we don't pass options down to some ufs
6. add real content hash to local ufs and test
improvement
new `checkContent`option for copy job
> Update copy job

- .gitignore
- build/version/write_version.sh
- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
- dev/scripts/src/alluxio.org/build/profiles.yml
- dev/scripts/update-versions.sh
- libexec/alluxio-config.sh
- pom.xml
previously the VERSION env variable was defined in libexec/alluxio-config.sh. the variable exists to properly locate various files bundled as part of the compiled alluxio package, such as when bundling as a tarball, because the pom.xml file is not included. however this led to having two sources of defining the version string, one in pom.xml and the other in alluxio-config.sh. they happened to be usually in sync because update-versions.sh will replace the version string in both of them simultaneously.
after this change, the version string is printed out when compiling the repo, written to a generated version.sh file. this file is sourced by alluxio-config.sh to maintain backcompat and is included in the tarball packaging. this results in the single source of truth:
- within the repo, the …
> Remove hardcoded VERSION in libexec/alluxio-config.sh

- bin/launch-process
Regarding https://github.com/Alluxio/alluxio/pull/16940#discussion_r1198367841. Make the line actually checks whether `Xmx` is contained.
> Fix Xmx check

- dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- dora/core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
- dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- dora/core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/JobFactoryProducer.java
- dora/core/server/master/src/main/java/alluxio/master/job/JournalCopyJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
This PR resolves the UFS leak problem in copy job. By making the method public in UfsManager.
Since we don't have mountID in Dora, so we need a new way to identify which UFS to use. Currently, I'm following the original design which uses Scheme, Authority & Properties as the key. Later on, we should also use the token given by the client to identify the UFS.
na
> Resolve the UFS leak in copy job

- core/server/common/src/main/java/alluxio/master/AlluxioExecutorService.java
Fix CCE for metric system
Without this fix, start a single master will encountered the following CCE.
```
2023-05-21 21:41:27,422 INFO  [main](WebServer.java:211) - Alluxio Master Web service started @ /0.0.0.0:19999
2023-05-21 21:41:27,422 INFO  [main](PrimaryOnlyMetricsService.java:27) - Promoting PrimaryOnlyMetricsService
2023-05-21 21:41:27,422 INFO  [main](MetricsService.java:29) - Start metric sinks.
2023-05-21 21:41:27,425 INFO  [main](AlluxioMasterProcess.java:294) - Primary started
2023-05-21 21:41:28,244 ERROR [Master Throttle](HeartbeatThread.java:157) - Uncaught exception in heartbeat executor, Heartbeat Thread shutting down
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
at alluxio.master.throttle.ServerIndicator.createFromMetrics(ServerIndicat …
```
> Fix CCE for metric system

- integration/fuse/pom.xml
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseRestServiceHandler.java
- integration/fuse/src/main/java/alluxio/fuse/FuseWebServer.java
- shell/src/main/java/alluxio/cli/LogLevel.java
Support changing log level at runtime for alluxio-fuse.
Now with the configuration "alluxio.fuse.web.enabled=true", the user can change the logLevel  for alluxio-fuse with the following ways
1. With `logLevel` command
```
$ ./bin/alluxio logLevel --logName=alluxio.fuse.AlluxioJniFuseFileSystem --target=localhost:49999 --level=INFO
Role inferred from port: localhost:49999[fuse]
localhost:49999[fuse]LogInfo{INFO, alluxio.fuse.AlluxioJniFuseFileSystem, Setting Level to INFO}
```
2. With `curl`
```
$ curl -X POST "http://localhost:49999/api/v1/fuse/logLevel?logName=alluxio.fuse.AlluxioJniFuseFileSystem&level=DEBUG"
{"logName":"alluxio.fuse.AlluxioJniFuseFileSystem","message":"Setting Level to DEBUG","level":"DEBUG"}
```
Please refer #17174 
NO
> Support changing log level at runtime for alluxio-fuse

- dora/core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java
- dora/core/common/src/main/java/alluxio/underfs/AsyncUfsClient.java
- dora/core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
- dora/core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- dora/core/common/src/main/java/alluxio/underfs/UfsLoadResult.java
- dora/core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
- dora/core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
- dora/core/common/src/main/java/alluxio/util/RateLimiter.java
- dora/core/common/src/main/java/alluxio/util/SimpleRateLimiter.java
- dora/core/common/src/test/java/alluxio/underfs/ObjectUnderFileSystemTest.java
- dora/core/common/src/test/java/alluxio/underfs/UnderFileSystemTestUtil.java
- dora/core/server/master/pom.xml
- dora/core/server/master/src/test/java/alluxio/master/file/FileSystemMasterS3UfsTest.java
- dora/minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- dora/tests/pom.xml
- dora/tests/src/test/java/alluxio/client/fs/FileSystemS3UfsIntegrationTest.java
- dora/tests/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java
- dora/underfs/local/pom.xml
- dora/underfs/local/src/test/java/alluxio/underfs/local/LocalUnderFileSystemTest.java
- dora/underfs/pom.xml
- dora/underfs/s3a/pom.xml
- dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
- dora/underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemMockServerTest.java
- dora/underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
- pom.xml
Partially cherry picked changes from 
https://github.com/Alluxio/alluxio/pull/17102 and
https://github.com/Alluxio/alluxio/pull/17242
1. Introduced s3 mock for unit tests & corresponding unit tests for s3
2. UFS ListStatus iterator interface
3.  Async S3 listing & get interfaces & integration with the new s3 client 
Better performance & memory control for s3
N/A
> Merge cherry-picked s3 ufs changes from 2.x branch

- integration/docker/.dockerignore
- integration/docker/Dockerfile
- integration/docker/Dockerfile-base
- integration/docker/Dockerfile-dev
- integration/docker/conf/alluxio-env.sh.template
- integration/docker/conf/alluxio-site.properties.template
1. Move env setup to a base image for better extendability
2. Remove the copy configuration during build time. If users need the files they can (and should because it's more flexible) use `--volume` to mount the files into containers at runtime.
> Make dockerfile extendable

- bin/alluxio-monitor.sh
Given that the startup time is unpredictable and there is always chance that the process is simply not serving and may just start to serve eventually, mention that a double check is needed when the monitor shows the master/worker start "[FAILED]".
> Improve monitor script printout

- dev/scripts/src/alluxio.org/build/cmd/build.go
- generate `libexec/version.sh` for using `--dryRun` 
For using dry run flag for dev purposes
> Create `libexec/version.sh` for tarball dry run

- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Fix a bug that may create 0-byte block file on worker, when there is issue to read a file from UFS.
Also fix the logging as it is too spammy when HDFSUnderFileSystem fails to read a UFS file
When we are caching a file (async),  and somehow the file does not exist on UFS any more (perhaps modified out of band).
An exception will be thrown from `UnderFileSystemBlockStore.createBlockReader`.
In its exception handling part, we treated this case the same as a normal close and commit the temp block.
This commit fixes this by abort the temp block instead on error cases.
Besides, the exception message in `createUfsBlockReader` is constructed wrong by also attaching the stacktrace into errorMessage. This is also fixed.
In addition, surpressing the warn log on HDFS UFS when attempting to read a …
> Fix a bug that creates 0 byte block file mistakenly

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
Fix a deadlock in `LocalCacheManager.getAndLoad`.
To reproduce the deadlock: https://github.com/dbw9580/alluxio/commit/ff87c7334e2576d3bd936dd3a1c2ced4803da5b6
Deadlock detected by jstack:
<details>
<summary>jstack output</summary>
```
Found one Java-level deadlock:
=============================
"pool-4-thread-1":
waiting for ownable synchronizer 0x000000070eb3b9f0, (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync),
which is held by "pool-4-thread-6"
"pool-4-thread-6":
waiting for ownable synchronizer 0x000000070eb25728, (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync),
which is held by "pool-4-thread-3"
"pool-4-thread-3":
waiting for ownable synchronizer 0x000000070eb3b9f0, (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync),
which is held by …
```
> Fix deadlock in LocalCacheManager

- dora/core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
fixed directory deletion failure when ufs is cos
1. cos bucket name is bucket-appid
2. COSUnderFileSystem.deleteObjects request is not bucket-appid case  `Failed to delete 1 paths from the under file system: /xxx (UFS delete dir failed)`
3. ObjectUnderFileSystem.submitBatch exception should print
1. when ufs is cos can normal exec alluxio rm -r xxx
> fixed directory deletion failure when ufs is cos

- core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileSystem.java
Check if the `uri` needs cache in `alluxio.client.file.cache.LocalCacheFileSystem`
`needsCache` is checked in `alluxio.hadoop.LocalCacheFileSystem` but not `alluxio.client.file.cache.LocalCacheFileSystem`. However, it is `alluxio.client.file.cache.LocalCacheFileSystem` used by local cache.
I also checked the code and cannot find a place is using `alluxio.hadoop.LocalCacheFileSystem` in Alluxio. Should it be deleted from code or it may be used by some clients?
NO
> Call needsCache in LocalCacheFileSystem

- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Fix a bug that may create 0-byte block file on worker, when there is issue to read a file from UFS.
Also fix the logging as it is too spammy when HDFSUnderFileSystem fails to read a UFS file
When we are caching a file (async),  and somehow the file does not exist on UFS any more (perhaps modified out of band).
An exception will be thrown from `UnderFileSystemBlockStore.createBlockReader`.
In its exception handling part, we treated this case the same as a normal close and commit the temp block.
This commit fixes this by abort the temp block instead on error cases.
Besides, the exception message in `createUfsBlockReader` is constructed wrong by also attaching the stacktrace into errorMessage. This is also fixed.
In addition, surpressing the warn log on HDFS UFS when attempting to read a …
> Fix a bug that creates 0 byte block file mistakenly; Port [#179497] to branch-2.9

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
This PR fixes https://github.com/Alluxio/alluxio/issues/17083
This PR moved the inode completion check from scheduleAsyncPersistenceInternal() method to scheduleAsyncPersistence()  . So we no longer unintentionally check `file.isComplete()` in `completeFile()` and throw and exception.
The inode model fetched from RockDB might become stale because the model is in memory and won't reflect the recent rocksDB change. Such stale in-memory model might fail some checks unexpectedly.  
N/A
> Remove unnecessary inode.isComplete() check from completeFile()

- core/transport/src/main/proto/grpc/raft_journal.proto
- core/transport/src/main/proto/proto.lock
Following #16998, some messages, fields, and RPCs are no longer in use. This PR marks them as deprecated.
> Deprecate some Raft journal RPCs

- dev/scripts/src/alluxio.org/build/artifact/artifact.go
- dev/scripts/src/alluxio.org/build/cmd/docker.go
- dev/scripts/src/alluxio.org/build/cmd/flags.go
- dev/scripts/src/alluxio.org/build/docker.yml
- dev/scripts/src/alluxio.org/build/main.go
Add command to build docker images via artifact generation script. Docker images will be built and saved to tarballs (via `docker save`).
ex:
```
./build-artifact.sh docker --image alluxio <add same args as tarball cmd>
./build-artifact.sh docker --image alluxio --tarballPath ../../alluxio-296-SNAPSHOT-bin.tar.gz
```
Enable generating docker 'artifacts' (tarballs)
3. webui
> Add command to build docker images

- cli/README.md
dev docs for defining conventions for the new alluxio cli in golang
see https://github.com/Alluxio/alluxio/issues/17522
> [DOCFIX] Define CLI conventions in README

- core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
Fix LocalPageStore NPE.
I encountered the following exception while using local cache
```
2023-05-31T17:25:13.453+0800    ERROR   20230531_092513_00010_uqx2a.1.0.0-7-153 alluxio.client.file.cache.NoExceptionCacheManager       Failed to put page PageId{FileId=76f9c79d5d43c725de31295c263291e0, PageIndex=534}, cacheContext CacheContext{cacheIdentifier=null, cacheQuota=alluxio.client.quota.CacheQuota$1@1f, cacheScope=CacheScope{id=.}, hiveCacheContext=null, isTemporary=false}
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "java.lang.Exception.getMessage()" is null
at alluxio.client.file.cache.store.LocalPageStore.put(LocalPageStore.java:80)
at alluxio.client.file.cache.LocalCacheManager.putAttempt(LocalCacheManager.java:345) …
```
> Fix LocalPageStore NPE

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/dora/netty/PartialReadException.java
Slient expected errors
e.g. Worker cold read not find file
```
2023-06-02 22:58:50,374 ERROR [BlockPacketReaderExecutor-2](NoExceptionCacheManager.java:149) - Failed to getDataFileChannel of page PageId{FileId=0d446ae33f21e86ce68b6982b22553f833a1e19a78eb121463329e7054cb93ba, PageIndex=0}
alluxio.exception.PageNotFoundException: Page PageId{FileId=0d446ae33f21e86ce68b6982b22553f833a1e19a78eb121463329e7054cb93ba, PageIndex=0} could not be found
at alluxio.client.file.cache.DefaultPageMetaStore.getPageInfo(DefaultPageMetaStore.java:148)
at alluxio.client.file.cache.LocalCacheManager.getDataFileChannel(LocalCacheManager.java:199)
at alluxio.client.file.cache.NoExceptionCacheManager.getDataFileChannel(NoExceptionCacheManager.java:147)
at …
```
> Remove some noisy expected page not find log

- dora/core/server/master/src/main/java/alluxio/master/job/CopyJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/JournalMoveJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
- dora/core/server/master/src/main/java/alluxio/master/predicate/FilePredicate.java
- dora/core/server/master/src/main/java/alluxio/master/predicate/FilePredicateFactory.java
- dora/core/server/master/src/main/java/alluxio/master/predicate/TimePredicate.java
- dora/core/server/master/src/main/java/alluxio/master/predicate/interval/Interval.java
- dora/core/server/master/src/main/java/alluxio/master/predicate/interval/IntervalSet.java
- dora/core/server/master/src/main/java/alluxio/master/predicate/interval/IntervalUtils.java
- dora/core/server/master/src/main/resources/META-INF/services/alluxio.master.predicate.FilePredicateFactory
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/MoveJobTest.java
- dora/core/server/master/src/test/java/alluxio/master/predicate/TimePredicateTest.java
- dora/core/server/master/src/test/java/alluxio/master/predicate/interval/IntervalSetTest.java
- dora/core/server/master/src/test/java/alluxio/master/predicate/interval/IntervalTest.java
- dora/core/server/master/src/test/java/alluxio/master/predicate/interval/IntervalUtilsTest.java
Adding the predicates for move jobs in order to be triggered by the policy engine.
Adding two predicates:
1. unmodifiedFor
2. dateFromFileNameOlderThan
NA
> Add FilePredicates for jobs

- cli/src/alluxio.org/cli/cmd/journal/backup.go
- cli/src/alluxio.org/cli/cmd/journal/checkpoint.go
- cli/src/alluxio.org/cli/cmd/journal/format.go
- cli/src/alluxio.org/cli/cmd/journal/journal.go
- cli/src/alluxio.org/cli/cmd/journal/read.go
- cli/src/alluxio.org/cli/env/command.go
Add journal commands to CLI as part of https://github.com/Alluxio/alluxio/issues/17522
> Add journal commands to CLI

- cli/src/alluxio.org/cli/cmd/quorum/elect.go
- cli/src/alluxio.org/cli/cmd/quorum/info.go
- cli/src/alluxio.org/cli/cmd/quorum/quorum.go
- cli/src/alluxio.org/cli/cmd/quorum/remove.go
- cli/src/alluxio.org/cli/main.go
Add quorum/HA related commands as part of https://github.com/Alluxio/alluxio/issues/17522
> Add quorum commands to CLI

- core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- core/server/master/src/main/java/alluxio/master/meta/MetaMasterSync.java
When the standby master send a heartbeat request to the leader master, many times there is no trace. When necessary, we should record their correspondence.
Adding some logs is necessary, here are some reasons:
1. When the master node fails, logs can help troubleshoot the cause.
2. It can make the communication between the standby master and the leader master clearer.
3. webui
> Add some logs when the standby master send a heartbeat request

- core/server/master/src/main/java/alluxio/master/file/FileSystemJournalEntryMerger.java
- core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemJournalEntryMergerTest.java
- core/server/master/src/test/java/alluxio/master/file/meta/LockedInodePathTest.java
1. Only force flushing journals when a locked inode path is closed for FileSystemMergeJournalContext
2. Fix the journal merger broken logic where updating the fingerprint for a directry will be ignored.
We used to fix the merge journal context in https://github.com/Alluxio/alluxio/pull/17071, where a regular non-merging journal context is used when listStatus() is called. 
However, if a listStatus triggers a metadata sync and MASTER_FILE_SYSTEM_MERGE_INODE_JOURNALS is set to true, journals will be flushed on every lockedInodePath close during the metadata sync. This behavior leads to journals being flushed too many times and impairs the metadata sync performance. 
Also we found a minor issue that when inode directory journals are merged, the fingerprint will be ignored. This is becuase …
> Port [#17251] to branch-2.10

- core/common/src/main/java/alluxio/exception/runtime/BlockDoesNotExistRuntimeException.java
- core/common/src/main/java/alluxio/util/io/FileUtils.java
- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java
- tests/src/test/java/alluxio/server/tieredstore/TieredStoreBlockCorruptionIntegrationTest.java
- tests/src/test/java/alluxio/server/tieredstore/TieredStoreIntegrationTest.java
Fix read failure when a mismatch occurs between the block size recorded in memory by `BlockMeta` and the length of the actual physical block file. When such a mismatch is detected, the block is removed from worker storage, and worker falls back to reading from UFS.
This causes reading the block to fail.
No.
> Fix corrupted block causing reads to fail

- bin/alluxio-common.sh
Update shell of mount ramdisk
Alluxio's original tier path is set by `alluxio.worker.tieredstore.level0.dirs.path`. However, in branch main, this property is removed. So I modify `bin/alluxio-common.sh` and let the value of `tier_path` be equal to `worker.page.store.dirs`.
No.
> Update shell of mount ramdisk

- dev/scripts/src/alluxio.org/build/cmd/build.go
Redirect the err output to stderr, just like how we redirect to stdout
> Improve build-artifact to print mvn error to stderr

- cli/src/alluxio.org/cli/cmd/fs/cat.go
- cli/src/alluxio.org/cli/cmd/fs/checksum.go
- cli/src/alluxio.org/cli/cmd/fs/count.go
- cli/src/alluxio.org/cli/cmd/fs/cp.go
- cli/src/alluxio.org/cli/cmd/fs/du.go
- cli/src/alluxio.org/cli/cmd/fs/fs.go
- cli/src/alluxio.org/cli/cmd/fs/head.go
- cli/src/alluxio.org/cli/cmd/fs/location.go
- cli/src/alluxio.org/cli/cmd/fs/ls.go
- cli/src/alluxio.org/cli/cmd/fs/mkdir.go
- cli/src/alluxio.org/cli/cmd/fs/mv.go
- cli/src/alluxio.org/cli/cmd/fs/rm.go
- cli/src/alluxio.org/cli/cmd/fs/stat.go
- cli/src/alluxio.org/cli/cmd/fs/tail.go
- cli/src/alluxio.org/cli/cmd/fs/test.go
- cli/src/alluxio.org/cli/cmd/fs/touch.go
- cli/src/alluxio.org/cli/env/command.go
- cli/src/alluxio.org/cli/launch/launch.go
- cli/src/alluxio.org/cli/main.go
Add fs commands to golang CLI as part of https://github.com/Alluxio/alluxio/issues/17522
unlike other CLI commands, utilize arguments to maintain the existing structure of filesystem commands (ex. cp, du, ls, mv, rm, etc)
> Add fs subcommand to CLI

- docs/en/overview/Architecture.md
In Section 6.4 Write to UFS Only (THROUGH), write completion and persistence are described in the wrong order. In the case of using UFS only, write should be completed after persistence to ensure that the written data will not be lost.
Suggest to update the sentence
”This write type ensures that data will be persisted after the write completes“
to
”This write type ensures that data will be persisted before the write completes“
> [DOCFIX] Improve desc on write type THROUGH

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/DefaultPageMetaStore.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/PageMetaStore.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerWithShadowCacheTest.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/page/PagedBlockMetaStore.java
- dora/core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
- dora/core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStoreDir.java
- dora/core/server/worker/src/test/java/alluxio/worker/page/ByteArrayCacheManager.java
Add and implement functions to invalidate all cached pages by fileId.
When we know that some file is to be removed, or renamed, or overwritten, we need to invalidate the cached pages in PagingStore.
Please note, at this moment, it is possible that the target file is already removed from UFS. So, getStatus() of this file will fail with exception. But we still need to invalidate all the cached pages.
N/A
> Invalidate cached pages from PagingStore by fileId

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
- dora/core/common/src/main/java/alluxio/file/NettyBufTargetBuffer.java
- dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServer.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerInitializer.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/PagedService.java
- dora/core/server/worker/src/main/java/alluxio/worker/modules/BlockWorkerModule.java
- dora/core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
- dora/tests/src/test/java/alluxio/client/cli/JournalToolTest.java
Implement http server for providing the get page RESTful API. Now we can get the page by sending a HTTP request:
`http://<HOST>:<PORT>/page?fileId=<FILE_ID>&pageIndex=<PAGE_INDEX>`
An example snapshot is shown as follows:
It can provide a more convenient API for AI scenarios and improve reading performance.
No, it doesn't.
> Implement HTTP server for providing the get page RESTful API

- dora/core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
- dora/core/server/master/src/main/java/alluxio/master/journal/DefaultJournalMaster.java
- dora/core/server/master/src/main/java/alluxio/master/journal/JournalMaster.java
- dora/core/server/master/src/main/java/alluxio/master/journal/JournalMasterClientServiceHandler.java
- dora/shell/src/main/java/alluxio/cli/fsadmin/journal/QuorumElectCommand.java
- dora/tests/src/test/java/alluxio/client/cli/fsadmin/command/QuorumCommandIntegrationTest.java
- dora/tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTestTransferLeadership.java
After upgrading Apache Ratis to version 2.5.1 (#17571), it is possible to transfer leadership between two masters of equal priority. This PR removes the need to update priorities twice when using the `elect` command.
In addition, this PR reworks the inner working of the command to make them thread safe: the new logic ensures that the transfer id is selected and reserved atomically. Moreover, it ensures that the transfer id is returned to the client before initiating the transfer of leadership. This is important because the leader receiving this RPC will be demoted and close its RPC server, potentially propagating an error to the client erroneously.
> Simplify `elect` command

- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Calls shutdown on the executor service in the S3 UFS class.
If shutdown is not called the threads will not be garbage collected.
No
> Fix S3 UFS executor service thread leak

- dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Throw an exception when there's an error deleting the file. Limit to S3 first and see if is there any object from the user about the semantic change. And from the `Filesystem` interface, we are dropping the returned value so we would never know there's an exception even though we are not able to delete ufs objects and this PR fixes this.
We probably need to update other ufs as well.
otherwise, exception would be swallowed.
throwing exception when there's delete error
This would break SafeUfsDeleter but we don't care about that
> Throw exception when there's error deleting file

- dora/core/common/src/main/java/alluxio/exception/ExceptionMessage.java
- dora/core/common/src/test/java/alluxio/AlluxioURITest.java
- dora/shell/src/main/java/alluxio/cli/fs/command/CpCommand.java
- dora/tests/src/test/java/alluxio/client/cli/fs/command/CopyFromLocalCommandIntegrationTest.java
Fix copyFromLocal while dest path is endsWith a `/`.
Fix #10191
Now the behaviour likes below
```
$ ./bin/alluxio fs mkdir /230610
Successfully created directory /230610
$ ./bin/alluxio fs copyFromLocal LICENSE /230610/dir.01/
/230610/dir.01 is a directory and should be created first.
./bin/alluxio fs copyFromLocal LICENSE /230610/file.01
Copied file:///.../LICENSE to /230610/file.01
$ ./bin/alluxio fs copyFromLocal LICENSE /230610/file.01/
/230610/file.01 exists but it's not a directory.
```
NO
> Fix copyFromLocal while dest path is endsWith a `/`

- dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReader.java
- dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsPositionedUnderFileInputStream.java
The position read will return -1 when position >= filesize, then the fuse will throw an error.
/tmp/alluxio-fuse/f1 is a 1mb file.
Fix the fuse position read bug.
3. webui
> Fix fuse position read bug

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Set `alluxio.dora.client.ufs.root` to `${alluxio.work.dir}/underFSStorage`.
The previous default was `/tmp`, which happens to clash with the default worker cache directory. Additionally, during integration tests we want to empty the UFS after each test, but `/tmp` is a shared system directory that cannot be emptied.
The new default is also consistent with the convention in 2.x.
Yes, the default Dora UFS root is changed.
> Set dora ufs root to local underFSStorage directory

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
- dora/core/client/fs/src/main/java/alluxio/client/file/options/FileSystemOptions.java
- dora/core/client/fs/src/test/java/alluxio/client/file/ufs/AbstractUfsStreamTest.java
- dora/core/client/fs/src/test/java/alluxio/client/file/ufs/UfsBaseFileSystemTest.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
- dora/integration/fuse/src/main/java/alluxio/fuse/options/FuseOptions.java
- dora/integration/fuse/src/test/java/alluxio/fuse/meta/UpdateCheckerTest.java
- dora/integration/fuse/src/test/java/alluxio/fuse/ufs/AbstractFuseFileSystemTest.java
- dora/minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
- dora/shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
- dora/tests/src/test/java/alluxio/client/cli/job/CancelCommandTest.java
- dora/tests/src/test/java/alluxio/client/cli/job/LeaderCommandTest.java
- dora/tests/src/test/java/alluxio/client/cli/job/StatCommandTest.java
- dora/tests/src/test/java/alluxio/client/fuse/dora/AbstractFuseFileSystemTest.java
- dora/tests/src/test/java/alluxio/client/fuse/dora/FuseEndToEndTest.java
- dora/tests/src/test/java/alluxio/client/fuse/dora/readonly/AbstractFuseFileSystemTest.java
Add a switch for client UFS fallback.
Allow a user to optionally enable or disable this feature. UFS fallback may be undesirable in cases where the clients run in an untrusted environment, so the UFS credentials cannot be exposed to the client.
Added a new config property `alluxio.dora.client.ufs.fallback.enabled` which defaults to `false`.
> Add switch for client UFS fallback

- dora/core/server/master/src/main/java/alluxio/master/job/AbstractJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
- dora/job/common/src/main/java/alluxio/scheduler/job/Job.java
- dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
Fix 2 concurrent submit job issue:
1. when we concurrently submit 2 jobs, both jobs could successfully submitted job although there's only one job would exist.
2. Avoid someone trying to submit a new job while the old job is still in the cleaning state(scheduler line 471~485). Ideally we would like we do the post processing first and then mark job as succeed/Failed. But the check is still valuable.
Also get rid of update job parameter since it's not very useful
bug fix
na
> Fix concurrent submit job

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
Fix local cache metrics in log.
When there are multiple cache directories, the metrics of LocalCacheManager log are incorrect. For example
```
2023-06-22 16:04:38,437 INFO  LocalCacheManager - Restoring PageStoreDir (/mnt/disk/1/alluxio.local.cache/LOCAL)
2023-06-22 16:04:38,443 INFO  LocalCacheManager - PageStore (/mnt/disk/1/alluxio.local.cache/LOCAL) restored with 7 pages (6895353 bytes), discarded 0 pages (com.codahale.metrics.Counter@347d2634 bytes)
2023-06-22 16:04:38,443 INFO  LocalCacheManager - Restoring PageStoreDir (/mnt/disk/2/alluxio.local.cache/LOCAL)
2023-06-22 16:04:38,443 INFO  LocalCacheManager - PageStore (/mnt/disk/2/alluxio.local.cache/LOCAL) restored with 7 pages (6895353 bytes), discarded 0 pages (com.codahale.metrics.Counter@347d2634 bytes)
```
The second directory …
> Fix local cache metrics in log

- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Add extra explicit loaded class for filesystem
In some situation, it is expected to load a class explicit, so that the extended logic can be appended.
NA
> Add extra explicit loaded class for filesystem

- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
- dora/core/client/fs/src/main/java/alluxio/client/file/options/FileSystemOptions.java
- dora/tests/src/test/java/alluxio/client/cli/fs/FileSystemShellUtilsTest.java
- dora/tests/src/test/java/alluxio/client/cli/fs/JobServiceFaultToleranceShellTest.java
- dora/tests/src/test/java/alluxio/client/cli/fs/command/DoraLoadCommandIntegrationTest.java
- dora/tests/src/test/java/alluxio/client/cli/fs/command/HelpCommandIntegrationTest.java
- dora/tests/src/test/java/alluxio/client/cli/fs/command/TestCommandIntegrationTest.java
- dora/tests/src/test/java/alluxio/client/cli/job/GetCmdStatusCommandTest.java
UFS root path is still required even though UFS fall back is disable. Otherwise, the `mDelegatedFileSystem` in `DoraCacheFileSystem` would be an instance of `BaseFileSystem`, and this leads to command failure. Therefore, we still need the UFS root address temporarily.
> Fix the bug that most commands fail after disable UFS fall back

- dora/core/server/master/src/main/java/alluxio/master/scheduler/Scheduler.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
Clean up scheduler job information when stop.
And when it start, we use jobMetaStore as the source of truth.
This avoids the job metadata is not consistent when transfer master.
bug fix
na
> Clean up scheduler job informations when stop

- pom.xml
Change mvn compiler plugin to use javac to expose internal errors better.
Ref: https://stackoverflow.com/a/52536499/4933827
When using `javac`, the compile time error stack trace can be shown when `mvn` fails in some cases.
Before
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:24 min (Wall Clock)
[INFO] Finished at: 2023-06-21T18:48:37+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] AssertionError -> [Help 1]
[ERROR] java.lang.AssertionError
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable …
```
> Show stacktrace on maven error

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStoreDir.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/exception/ExceptionMessage.java
- dora/core/common/src/main/java/alluxio/master/metastore/rocks/RocksExclusiveLockHandle.java
- dora/core/common/src/main/java/alluxio/master/metastore/rocks/RocksSharedLockHandle.java
- dora/core/common/src/main/java/alluxio/master/metastore/rocks/RocksUtils.java
- dora/core/common/src/main/java/alluxio/resource/CloseableIterator.java
- dora/core/server/common/src/main/java/alluxio/rocks/RocksCheckpointed.java
- dora/core/server/common/src/main/java/alluxio/rocks/RocksStore.java
- dora/core/server/common/src/test/java/alluxio/rocks/RocksStoreTest.java
- dora/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- dora/core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockMetaStore.java
- dora/core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
- dora/core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksBlockMetaStoreTest.java
- dora/core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksInodeStoreTest.java
- dora/core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksStoreTestUtils.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
- dora/microbench/src/main/java/alluxio/inode/RocksBenchBase.java
- dora/tests/src/test/java/alluxio/server/worker/WorkerAllMasterRegistrationTest.java
We fixed some `RocksStore` thread safety issues where concurrent operations and RocksDB stopping may crash the master process. Those changes are only in `master-2.x` and therefore missing in the `main` branch. Therefore those changes are manually brought in, with fixes on conflicts. Those missing commits are:
https://github.com/Alluxio/alluxio/commit/9f152c554b737b7014a3c8ac1555d0a2d1e2e936
https://github.com/Alluxio/alluxio/commit/bf60aefc247f57708fd39dce1c440515712a54c1
Also in the Dora architecture the worker has its new `RocksDBDoraMetaStore`, which is missing the same thread safety control. Those are implemented in this PR too.
Honestly this change isn't as important on the Dora worker as it previously was in Alluxio 2.x master, because crashing a Dora worker while shutting down is …
> Apply RocksDB thread safety changes to Dora

- dora/core/server/master/src/main/java/alluxio/master/job/CopyJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/MoveJob.java
log after job status change
fix bug
na
> Fix job log

- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3BucketTask.java
- dora/tests/src/test/java/alluxio/client/rest/ListStatusTest.java
- dora/tests/src/test/java/alluxio/client/rest/TestCase.java
A new file `ListStatusTest.java` was created to do UTs about  S3 proxy's listing-objects functions.
The formely UTs of S3 proxy 'S3ClientRestApiTest'  is redundant and unreadable. 
Most of UTs of S3 proxy is not suitable for alluxio-dora version. 
So I rebuild UTs of S3 proxy to make UTs concise and correct.
no.
> Create UTs to listing objects of S3 proxy

- core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryIdGenerator.java
Fix deadlock issue when master process exit
```
stackTrace:
java.lang.Thread.State: BLOCKED (on object monitor)
at java.lang.Shutdown.exit(java.base@11.0.12-ga/Shutdown.java:173)
- **waiting to lock <0x00007f55e98d1920> (a java.lang.Class for java.lang.Shutdown)**
at java.lang.Runtime.exit(java.base@11.0.12-ga/Runtime.java:116)
at java.lang.System.exit(java.base@11.0.12-ga/System.java:1752)
at alluxio.ProcessUtils.fatalError(ProcessUtils.java:83)
at alluxio.ProcessUtils.fatalError(ProcessUtils.java:63)
at alluxio.master.journal.MasterJournalContext.waitForJournalFlush(MasterJournalContext.java:99)
at alluxio.master.journal.MasterJournalContext.close(MasterJournalContext.java:109)
- locked <0x00007f5602000010> (a alluxio.master.journal.MasterJournalContext)
at …
```
> Fix deadlock issue when master process exit

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/QuotaManagedPageStoreDir.java
- dora/core/client/fs/src/main/java/alluxio/client/file/dora/netty/NettyDataWriter.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerWithShadowCacheTest.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- dora/core/common/src/main/java/alluxio/worker/block/io/BlockWriter.java
- dora/core/common/src/main/java/alluxio/worker/block/io/LocalFileBlockWriter.java
- dora/core/common/src/test/java/alluxio/worker/block/io/MockBlockWriter.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileWriter.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/AbstractWriteHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/FileWriteHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/page/PagedBlockWriter.java
- dora/core/server/worker/src/test/java/alluxio/worker/page/ByteArrayCacheManager.java
We found that there is a bug that worker doesn't check the size when writing temp pages. This leads the fact that the pages' size stored in Alluxio Worker exceeds the capacity limitation, as shown in the following snapshot. This makes worker easy to crash.
This PR fixes this bug by checking the temp page size to write.
> Fix the bug that worker doesn't check size when writing temp pages

- dora/core/server/worker/src/main/java/alluxio/worker/task/CopyHandler.java
address corner case when rerunning the copy operation of a directory
results in worker log error:
```
2023-07-02 04:28:45,565 ERROR PagedDoraWorker - Failed to move s3://jul02-vvrz-1/Compatibility-TestTool-1.1-alpha/lib to s3://jul02-vvrz-0/TEST1/lib
alluxio.exception.runtime.FailedPreconditionRuntimeException: File s3://jul02-vvrz-0/TEST1/lib is already in UFS
at alluxio.worker.task.CopyHandler.copy(CopyHandler.java:85)
at alluxio.worker.dora.PagedDoraWorker.lambda$move$11(PagedDoraWorker.java:631)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
at …
```
> Return if dst folder exists in distCp

- dora/integration/tools/hms/pom.xml
- dora/integration/tools/validation/pom.xml
- dora/table/server/underdb/glue/pom.xml
- dora/table/server/underdb/hive/pom.xml
- dora/underfs/abfs/pom.xml
- dora/underfs/adl/pom.xml
- dora/underfs/cephfs-hadoop/pom.xml
- dora/underfs/cephfs/pom.xml
- dora/underfs/cos/pom.xml
- dora/underfs/cosn/pom.xml
- dora/underfs/gcs/pom.xml
- dora/underfs/hdfs/pom.xml
- dora/underfs/kodo/pom.xml
- dora/underfs/local/pom.xml
- dora/underfs/obs/pom.xml
- dora/underfs/oss/pom.xml
- dora/underfs/ozone/pom.xml
- dora/underfs/s3a/pom.xml
- dora/underfs/swift/pom.xml
- dora/underfs/wasb/pom.xml
- dora/underfs/web/pom.xml
less ambiguous to define the dst path from project root rather than from module root. the lib/ directory is more simple to define as `build.path/../lib/`, rather than `module.root/../<some variable number of parent directories>/lib/`
> Fix lib jar copy dst path

- common/transport/src/main/proto/grpc/file_system_master.proto
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/grpc/GrpcUtils.java
- dora/core/common/src/main/java/alluxio/wire/FileInfo.java
- dora/core/common/src/test/java/alluxio/wire/FileInfoTest.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Instead of comparing the fingerprint, we compare the fields in the file info object directly, to make it more efficient.
In https://github.com/Alluxio/alluxio/pull/17458, we introduced a mechanism that populates fingerprint and persists that into metastore so that we can skip invalidating unnecessary page caches when the metadata is updated. 
Such mechanism is protected under a property key as it does not perform good. Now after the discussion with @dbw9580 , we came up with a more efficient way where we just leverage the fields in the file info object and we believe we are able to get rid of such switch. 
N/A
> Use a more efficient way to store content hash

- dora/core/common/src/main/java/alluxio/RuntimeConstants.java
Fix to support alluxio version other than xxx.yyy
Without these changes, users from alluxio open source community who want to build a package with their version name under their community version name rule, but it doesn't contains any `.` within version name, it wouldn't start alluxio cluster successfully.
No
> Fix to support alluxio version other than xxx.yyy

- dora/core/common/src/main/java-templates/alluxio/ProjectConstants.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
- pom.xml
define new property for configurability of update checker, to be used in conjunction with the update checker enabled property. previously the enabled property has its default value set as a build time constant, but the value could be overridden if set in configuration. now the configurability value, which is set at build time, determines if the enabled property can be configured, and if it is, uses its corresponding value. this pattern allows us to lock the enabled value at build time such that a published jar cannot override this enabled property.
> Define configurability of update checker

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
Using the content hash of the file to be the ETag in the s3 api. Add a property key to decide whether to get real content hash when loading file meta from ufs.
Now we no longer use Xattr to store the etag of the file. And alluxio adds a new option to get real content hash.
No
> Change to use the new way to get the ETag of the file

- dora/core/common/src/main/java/alluxio/underfs/options/DeleteOptions.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
The delete/create options are currently not passed to the UFS. By passing them to the UFS correctly, we should be able to achieve recursive create/delete.
However, note that under Dora structure, when we delete `/a/`, we can't also remove all `/a/*` cache from all workers immediately. https://github.com/Alluxio/alluxio/issues/17741
> Add recursive create/delete

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/ResponseFileInfo.java
- dora/core/server/worker/src/test/java/alluxio/worker/http/TestHttpServerHandler.java
Support list files through RESTful API
Usage example:
HTTP GET request http://localhost:28080/files?path=/test 
`ls` files of the path `/test` and response a JSON string
> Support list files through RESTful API

- job/server/src/main/java/alluxio/master/job/tracker/DistLoadCliRunner.java
- job/server/src/main/java/alluxio/master/job/tracker/MigrateCliRunner.java
Use field property 'mActiveJobs' for 'AbstractCmdRunner' instead of the default value DEFAULT_ACTIVE_JOBS which is hardcoded with 3000.
Currently, the number of active jobs are limited at 3000 which is not enough when we have lots of loading tasks on huge cluster. We will add command line args to allow user pass the limit of active jobs (set the value of 'mActiveJobs') the  in the future.
N/A
> [SMALLFIX] Use field property for 'AbstractCmdRunner'

- docs/_includes/sitemap.html
make a differentiation between a title w/ subfiles vs a title with a single file. if it's only a single file, then create the button link instead of the dropdown style.  This pr is related change based on https://github.com/Alluxio/alluxio/pull/17737 
example without format:
with format:
> [DOCFIX] Update the style of nav list

- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
Release buffer when an exception occurs.
Fix memory leaking.
> Fix memory leaking when loading data

- dora/core/client/fs/src/main/java/alluxio/client/file/dora/WorkerLocationPolicy.java
- dora/core/client/fs/src/test/java/alluxio/client/file/dora/WorkerLocationPolicyTest.java
Fix a race condition between refreshing the map and retrieving worker info from the map.
This cause a NPE where the requested entry can be `null`.
No.
> Fix worker policy race condition

- dev/github/Dockerfile-jdk11
- dev/github/Dockerfile-jdk17
- dev/github/Dockerfile-jdk8
reintroduce jdk8 version of alluxio-maven image
for non-jdk8 images, install jdk8 to be used for compilation
follow up to https://github.com/Alluxio/alluxio/pull/17751
> Add back jdk8 to images used for PR builds

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpResponseContext.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServer.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerInitializer.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/PagedService.java
1. Remove compression encoder for faster data transmission.
2. Use bigger thread pool to serve the HTTP clients.
3. Use Netty's zero-copy feature to avoid data copying in Alluxio Worker.
> Improve HTTP RESTful API performance

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Fix the bug that list files RESTful API doesn't work caused by the code doesn't handle `FullHttpResponse`.
> Fix list files RESTful API

- build/checkstyle/suppressions.xml
- dora/tests/pom.xml
- dora/underfs/hdfs/pom.xml
- pom.xml
Cleanup maven build process by removing "com.igormaznitsa:jcp", which is used to create generated-source and generated-test-source due to **incompatible** APIs of Hadoop-1 and Hadoop-2 client source code.
1. jcp is no longer used after 300. Still running jcp for generate-sources during compilation is meaningless and time-wasting.
2. maintaining generated-test-source and generated-source for dev really complicates the IDE environment: most of the classes in generated source or test source will be identified as duplicates by IDE. 
3. In general, having duplicated classes complicates build process too. For certain plugin, the compiler is also confused by which class to use.
N/A
> Remove dependency on com.igormaznitsa:jcp

- integration/fuse/bin/alluxio-fuse
Fix  mount fuse do not report error on macosx
> Fix to support mount fuse do not report error on macosx

- pom.xml
Fix Maven warnings on plugin declaration:
```
[WARNING] Some problems were encountered while building the effective model for org.alluxio:alluxio-assembly-client:jar:302-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for pl.project13.maven:git-commit-id-plugin is missing. @ org.alluxio:alluxio-parent:302-SNAPSHOT, /Users/binfan/projects/alluxio/alluxio/pom.xml, line 1174, column 15
[WARNING] Some problems were encountered while building the effective model for org.alluxio:alluxio-assembly:pom:302-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.codehaus.mojo:exec-maven-plugin @ org.alluxio:alluxio-parent:302-SNAPSHOT, /Users/binfan/projects/alluxio/alluxio/pom.xml, line 1371, column 15
[WARNING] …
```
> Fix Maven warnings on plugin declaration

- dev/github/run_tests.sh
- pom.xml
Upgrade maven-surefire-plugin to 3.0.0 to eliminate the following warning message: 
```
[WARNING] Parameter 'localRepository' is deprecated core expression; 
Avoid use of ArtifactRepository type. 
If you need access to local repository, switch to '${repositorySystemSession}' expression and get LRM from it instead.
```
Codebase hygiene
This warning is because maven deprecated parameter `localRepository` MNG-7706 in maven 3.9.1;
But there are a set of maven plugins still using it and upgrade is needed to adopt the change on maven.
Upgrade surefire [SUREFIRE-2154] to remove this message
No
> Upgrade maven surefire plugin to remove build warnings

- dev/github/Dockerfile-jdk17
no maven openjdk image for 17 according to https://hub.docker.com/_/maven/tags?page=1&name=3.8.6-open but the default 3.8.6 is available as an eclipse-temurin flavor of java17: [3.8.6-eclipse-temurin-17](https://hub.docker.com/layers/library/maven/3.8.6-eclipse-temurin-17/images/sha256-d9035c93956cda1f067a6fe5d120c6c3575830dd651802e72c8e9376b78563b9?context=explore)
> Fix base docker image for alluxio-maven jdk17

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/underfs/ObjectMultipartUploadOutputStream.java
- dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSMultipartUploadOutputStream.java
- dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
- dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSMultipartUploadOutputStream.java
- dora/underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
- dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSMultipartUploadOutputStream.java
- dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AMultipartUploadOutputStream.java
- dora/underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
- dora/underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemMockServerTest.java
- dora/underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
Support multipart upload of S3, OSS, COS and OBS.
1. support multipart upload mode of s3. Simple upload refers to [this](https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html). Multipart upload refer to [this](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html)
2. Multipart upload improve streaming upload mode. Multipart upload remove temp file, that optimizes three read and write disk operations into one. Upload each time the input data reaches the `partition size`, and use Netty zero-copy technology for splicing.
3. OSS, COS and OBS are similar as described to the above.
**There are some experiments conducted on Mac Laptop and AWS instance. Simple upload (default) and streaming upload are two original upload methods of alluxio.**
File Size: 4.8GB …
> Support multipart upload of S3, OSS, COS and OBS

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
- dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/worker/dora/OpenFileHandle.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileWriter.java
- dora/tests/src/test/java/alluxio/client/fs/DoraFileSystemIntegrationTest.java
- dora/tests/src/test/java/alluxio/client/fs/UnderStorageReadIntegrationTest.java
- Clients write data to worker and worker write data to local paging cache and UFS. 
Added a switch to control this. The default way is client writing directly to UFS.
- WriteType.THROUGH is handled.
- InAlluxioPercentage and inMemoryPercentage is set to 100 when file length is zero.
So Alluxio workers can do some control, e.g. security, flow, quota, on worker. This also avoid managing UFS access tokens on clients, minimize performance bottles on client.
TODO: worker decides writing data to local paging cache or remote UFS based on different write types.
For example, for CACHE_THROUGH, data is going to local paging store and UFS.
For THROUGH, data is ONLY going to UFS.
N/A
> Enable Dora write through worker to UFS

- docs/css/main.css
the table exceeds its own div on current the page:
fixed example without format:
with format:
> [DOCFIX] Fix table format issue for Properties-List page

- dev/scripts/src/alluxio.org/build/assembly.yml
- dev/scripts/src/alluxio.org/build/cmd/assembly.go
- dev/scripts/src/alluxio.org/build/cmd/build.go
- dev/scripts/src/alluxio.org/build/cmd/flags.go
- dev/scripts/src/alluxio.org/build/cmd/tarball.go
define how to manipulate the assembly jars inside a tarball via configuration file instead of hardcoding the map
> Refactor assembly jar defs in tarball gen

- docs/en/Get-Started.md
- docs/en/Overview.md
- docs/en/compute/Hadoop-MapReduce.md
- docs/en/compute/Presto.md
- docs/en/compute/Spark.md
- docs/en/compute/Trino.md
- docs/en/contributor/Contribution-Guide.md
- docs/en/introduction/Glossary.md
- docs/en/introduction/Introduction.md
- docs/en/kubernetes/Install-Alluxio-On-Kubernetes.md
- docs/en/operation/Journal.md
- docs/en/ufs/Azure-Blob-Store.md
- docs/en/ufs/Azure-Data-Lake-Gen2.md
- docs/en/ufs/Azure-Data-Lake.md
- docs/en/ufs/COS.md
- docs/en/ufs/COSN.md
- docs/en/ufs/CephObjectStorage.md
- docs/en/ufs/GCS.md
- docs/en/ufs/HDFS.md
- docs/en/ufs/Minio.md
- docs/en/ufs/NFS.md
- docs/en/ufs/OBS.md
- docs/en/ufs/OSS.md
- docs/en/ufs/Ozone.md
- docs/en/ufs/Qiniu-KODO.md
- docs/en/ufs/S3.md
- docs/en/ufs/Swift.md
Deleted mount command links because they redirected to main page
Added more resources to Get Started page
Added more relevant terms to glossary
Mount command links are not useful. 
More resources in the Get Started for next steps after running locally
More relevant terms to glossary
Web UI
> [DOCFIX] Delete mount command links, Add resources to Get Started

- dora/integration/tools/validation/src/main/java/alluxio/cli/S3ASpecificOperations.java
- dora/integration/tools/validation/src/main/java/alluxio/cli/UnderFileSystemCommonOperations.java
- dora/tests/pom.xml
Stop shading alluxio-test.
Shading a module is slow and error-prone. The shading of the `alluxio-test` module was previously introduced in https://github.com/Alluxio/alluxio/pull/7765 for journal-related tests. There is no longer a need to shade this module.
As part of this PR, `listStatusRootTest` (introduced in https://github.com/Alluxio/alluxio/pull/15361/) has been moved to the S3 specific tests. This move was made because the test failed after the shading was removed on my local MacOS (although it passes CI on Linux), likely due to an unusual setting of the root directory on MacOS. I am unsure why removing shading on `alluxio-test` also impacts `alluxio-integration-tools-validation`. However, based on the description of https://github.com/Alluxio/alluxio/pull/15361, it does seem to …
> Remove shading for alluxio-test module

- core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java
Delegate `getFileBlockLocation` to external file system in `LocalCacheFileSystem`.
Otherwise, `LocalCacheFileSystem` inherits the default behavior of `org.apache.hadoop.fs.FileSystem` which returns `localhost` only. 
No.
> Support getFileBlockLocation in LocalCacheFileSystem

- docs/en/kubernetes/Metrics-On-Kubernetes.md
remove the accordion , so the `toc` navbar on right side can jump to metric content correctly
> [DOCFIX] Remove accordion in Metrics-On-Kubernetes.md

- cli/src/alluxio.org/cli/cmd/generate/docs.go
- cli/src/alluxio.org/cli/cmd/generate/generate.go
- cli/src/alluxio.org/cli/cmd/generate/template.go
- cli/src/alluxio.org/cli/env/env.go
- cli/src/alluxio.org/cli/env/env_vars.go
- cli/src/alluxio.org/cli/main.go
Add generate commands to golang CLI as part of #17522 
bin/alluxio docGen -> bin/cli generate docs
bin/alluxio bootstrapConf -> bin/cli generate template
to read ALLUXIO_CONF_DIR, also conducted a minor change on env variables.
> Add generate subcommand to CLI

- .github/workflows/java8_unit_tests.yml
this build is failing the compilation step, claiming it can't find dora/tests jar when building dora/microbench. strange that it wasn't happening when validating https://github.com/Alluxio/alluxio/pull/17811
> Fix compilation for unit tests build

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Add metrics for num of request to external storage when cache miss
For cost saving
no
> Add metrics for num of request to external storage when cache miss

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
- job/server/src/main/java/alluxio/master/job/JobMaster.java
Support dynamic enable/disable audit log
Now, if we disable auditlog before master startup, we cannot support enable it dynamically, but it can be disable if it is enabled at startup time, it is tricky.
And it is not expensive to start an object.
No
> Support dynamic enable/disable audit log

- job/server/src/main/java/alluxio/job/plan/replicate/SetReplicaDefinition.java
Now we unpin and set min replication to 0 if we failed due to IO related reasons. (such as UFS not available, file does not exist etc).
Previously if a replication job fails, it would be rescheduled again and again, causing Denial of Service.
Yes, the user would expect certain files unpinned or adjusted if it becomes unavailable.
> Set min replicate to 0 and unpin file if we fail to replicate a file

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- dora/core/common/src/main/java/alluxio/client/file/URIStatus.java
With this flag, client read will fall back to UFS when previous getStatus() falls back to UFS.
If a URIStatus is retrieved from UFS in stead of worker by falling back to UFS, set the flag.
So, subsequent openFile(status, path) can fall back UFS immediately. So client read will
continue without error in shorter time interval.
To reduce the client fall back time.
3. webui
> Set FromUFSFallBack flag in URIStatus to reduce client fall back time

- dora/integration/fuse/bin/alluxio-fuse
e.g. removing trailing "/" at the end or in the middle.
checking existance of parent dir and mount point
If the mount point is not processed, it may contains excessive "/" at the end or in the middle.
But the 'mount' command will output mount point without those excessive "/".
So, the script cannot determine if the mount is succeeded or not.
N/A
> Process the mount point from user input

- docs/en/overview/Release-Notes.md
> [DOCFIX] Add Release Notes 2.8.0

- docs/en/overview/Release-Notes.md
> [DOCFIX] Release Notes 2.6.1

- dev/github/run_tests.sh
- pom.xml
1. Skip validating if the poms are sorted when running UT/integration tests in GitHub CI.
2. Skip sorting the pom files in-place during build. 
1. Avoid failing tests just because a developer forgets to sort the pom files. The `Checkstyle, findbugs, etc.` checks will still catch it.
2. This is undesirable during CI as it silently modifies the pom file without giving a warning. However, the auto sort is still accessible by directly running `mvn sortpom:sort@manual-sort` from the command line. This can be handy for a developer that needs to incorporate large chunks of pom changes.
No.
> Skip sortpom when running tests and during build

- cli/src/alluxio.org/cli/env/env.go
- cli/src/alluxio.org/cli/env/env_vars.go
- cli/src/alluxio.org/cli/env/process_start.go
- cli/src/alluxio.org/cli/env/process_stop.go
- cli/src/alluxio.org/cli/main.go
- cli/src/alluxio.org/cli/processes/all.go
- cli/src/alluxio.org/cli/processes/common.go
- cli/src/alluxio.org/cli/processes/job_masters.go
- cli/src/alluxio.org/cli/processes/job_workers.go
- cli/src/alluxio.org/cli/processes/local.go
- cli/src/alluxio.org/cli/processes/masters.go
- cli/src/alluxio.org/cli/processes/proxies.go
- cli/src/alluxio.org/cli/processes/workers.go
- cli/src/alluxio.org/go.mod
- cli/src/alluxio.org/go.sum
Add `process` commands with multiple nodes to golang CLI as part of https://github.com/Alluxio/alluxio/issues/17522
`bin/alluxio-start.sh masters` -> `bin/cli.sh process start masters`
`bin/alluxio-start.sh job_masters` -> `bin/cli.sh process start job_masters`
`bin/alluxio-start.sh workers` -> `bin/cli.sh process start workers`
`bin/alluxio-start.sh job_workers` -> `bin/cli.sh process start job_workers`
`bin/alluxio-start.sh proxies` -> `bin/cli.sh process start proxies`
`bin/alluxio-start.sh all` -> `bin/cli.sh process start all`
`bin/alluxio-start.sh local` -> `bin/cli.sh process start local`
`bin/alluxio-stop.sh masters` -> `bin/cli.sh process stop masters`
`bin/alluxio-stop.sh job_masters` -> `bin/cli.sh process stop job_masters`
`bin/alluxio-stop.sh workers` -> `bin/cli.sh process …
> Add process subcommands for multiple nodes

- cli/src/alluxio.org/cli/cmd/job/cancel.go
- cli/src/alluxio.org/cli/cmd/job/cmd_status.go
- cli/src/alluxio.org/cli/cmd/job/job.go
- cli/src/alluxio.org/cli/cmd/job/job_status.go
- cli/src/alluxio.org/cli/cmd/job/leader.go
- cli/src/alluxio.org/cli/cmd/job/list.go
- cli/src/alluxio.org/cli/cmd/job/load.go
- cli/src/alluxio.org/cli/cmd/job/submit.go
- cli/src/alluxio.org/cli/cmd/names.go
- cli/src/alluxio.org/cli/main.go
Add job commands to golang CLI as part of https://github.com/Alluxio/alluxio/issues/17522
`bin/alluxio-bash job cancel id` -> `bin/alluxio job cancel --id`
`bin/alluxio-bash job leader` -> `bin/alluxio job leader`
`bin/alluxio-bash job ls` -> `bin/alluxio job list`
`bin/alluxio-bash job getCmdStatus jobControlId` -> `bin/alluxio job cmdStatus --id`
`bin/alluxio-bash job stat [-v] id` -> `bin/alluxio job jobStatus [-v] --id`
`bin/alluxio-bash fs distributedCp src dst` -> `bin/alluxio job submit --type cp --src --dst`
`bin/alluxio-bash fs distributedMv src dst` -> `bin/alluxio job submit --type mv --src --dst`
`bin/alluxio-bash fs load path --submit` -> `bin/alluxio job load --path`
> Add job subcommand to CLI

- dora/shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShellUtils.java
- dora/shell/src/main/java/alluxio/cli/fsadmin/command/ReportCommand.java
Remove check to the master if etcd membership.
Remove check to the master if etcd membership.
Otherwise, it will fail the following command with etcd membership
> ./bin/alluxio fsadmin report nodestatus
NA
> Remove check to the master if etcd membership

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Turn off client side metrics sink since the master will be removed.
Turn off client side metrics sink by default since the master will be removed.
NA
> Turn off client side metrics sink since the master will be removed

- cli/src/alluxio.org/cli/cmd/info/info.go
- cli/src/alluxio.org/cli/cmd/info/version.go
Add an `info version` subcommand to golang CLI as part of https://github.com/Alluxio/alluxio/issues/17522
`bin/alluxio-bash version` -> `bin/alluxio info version`
> Add subcommand bin/cli info version

- cli/src/alluxio.org/cli/cmd/cache/cache.go
- cli/src/alluxio.org/cli/cmd/cache/format.go
- cli/src/alluxio.org/cli/cmd/cache/free.go
- cli/src/alluxio.org/cli/cmd/cache/persist.go
- cli/src/alluxio.org/cli/cmd/cache/ttl.go
- cli/src/alluxio.org/cli/main.go
Add `cache` commands to golang CLI as part of https://github.com/Alluxio/alluxio/issues/17522
`bin/alluxio-bash formatWorker` -> `bin/cli cache format`
`bin/alluxio-bash fs freeWorker` -> `bin/cli cache free --worker`
`bin/alluxio-bash fs free` -> `bin/cli cache free [-f] --path`
`bin/alluxio-bash fs persist` -> `bin/cli cache persist --path`
`bin/alluxio-bash fs setTtl` -> `bin/cli cache ttl --set --duration --action`
`bin/alluxio-bash fs unsetTtl` -> `bin/cli cache ttl --unset`
> Add cache subcommand to CLI

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
Remove the duplicated metrics counting
We count CLIENT_CACHE_BYTES_READ_CACHE twice
3. webui
> Fix the duplicated metrics counting

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/conf/RemovedKey.java
- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/grpc/AbstractWriteHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/grpc/FileReadHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/NettyExecutors.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/PipelineHandler.java
- dora/core/server/worker/src/test/java/alluxio/worker/grpc/GrpcExecutorsTest.java
1. Removed two unused thread pools in the worker:
a. GRPC async cache manager
b. Netty async cache thread pool
2. Removed property keys and metrics related to those thread pools.
3. Renamed many property keys and variables to remove the "block" keyword 
Reduce the number of threads on worker and remove obsolete logic
Some property keys are removed.
> Remove unused thread pools and rename netty/grpc pools

- dev/scripts/src/alluxio.org/check-docs/main.go
- docs/_includes/sitemap.html
with following example in the `menu-en.yml`
``` 
- title: example level 1
buttonTitle: example_level_1
subfiles:
- title: Introduction
url: /en/introduction/Introduction.html
- title: Glossary
url: /en/introduction/Glossary.html
- subfiles: 
- title: example level 2
buttonTitle: example_level_2
subfiles:
- title: example level2 doc
url: /en/introduction/Introduction.html
- subfiles:
- title: example level 3
buttonTitle: example_level_3
subfiles:
- title: example level3 doc
url: /en/introduction/Introduction.html
- title: Glossary
url: /en/introduction/Glossary.html
- title: What is Alluxioxx
buttonTitle: What_is_Alluxioxx
subfiles:
- title: Introduction
url: /en/introduction/Introduction.html
```
The output with format will looks like 
also update the checks-doc script
> [DOCFIX] Update sitemap logic and relate checks

- pom.xml
After this PR, when building the source with Java 11, following error will be raised
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.3.0:enforce (enforce-versions) on project alluxio-parent: 
[ERROR] Rule 1: org.apache.maven.enforcer.rules.version.RequireJavaVersion failed with message:
[ERROR] Detected JDK version 11.0.19 (JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home) is not in the allowed range [1.8,1.8].
```
The previous Java version requirement in enforce plugin is "soft recommendation".
Change it to a hard requirement following version range syntax:
https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
No
> Require Java version 1.8

- dora/shaded/client/pom.xml
- dora/underfs/abfs/pom.xml
- dora/underfs/adl/pom.xml
- dora/underfs/cephfs-hadoop/pom.xml
- dora/underfs/cosn/pom.xml
- dora/underfs/ozone/pom.xml
- dora/underfs/pom.xml
- dora/underfs/wasb/pom.xml
1. Improve filter setting in `dora/shaded/client/pom.xml` to eliminate some warnings in the shading process.
2. Remove duplicated code of filter setting in UFS. The shading filter in each UFS will inherit the shading plugin settings from `dora/underfs/pom.xml`, enabling us to reduce duplication by moving the common settings to `dora/underfs/pom.xml`.
Code hygiene and readability
No
> Improve filter exclusion setting for shade plugin

- dora/core/server/worker/src/main/java/alluxio/worker/netty/FileWriteHandler.java
Fix non-existent property `WORKER_TIERED_STORE_LEVEL_ALIAS` preventing worker from starting.
The property key was removed in #17948. 
See error stack
```
2023-08-15 12:04:46,377 WARN  [data-server-tcp-socket-worker-0](ChannelInitializer.java:97) - Failed to initialize a channel. Closing: [id: 0xe69bb935, L:/192.168.31.18:29997 - R:/192.168.31.18:52896]
java.lang.RuntimeException: No value set for configuration key alluxio.worker.tieredstore.level0.alias
at alluxio.conf.InstancedConfiguration.get(InstancedConfiguration.java:108)
at alluxio.conf.InstancedConfiguration.get(InstancedConfiguration.java:100)
at alluxio.conf.InstancedConfiguration.getString(InstancedConfiguration.java:259)
at alluxio.conf.Configuration.getString(Configuration.java:221)
at …
```
> Fix non-existent tiered store property preventing worker from starting

- dora/core/server/worker/src/main/java/alluxio/worker/netty/FileWriteHandler.java
Remove unused class which causing problem.
```
2023-08-15 21:40:36,663 WARN  ChannelInitializer - Failed to initialize a channel. Closing: [id: 0xa460dfda, L:/172.31.93.123:29997 - R:/172.31.80.106:34390]
java.lang.RuntimeException: No value set for configuration key alluxio.worker.tieredstore.level0.alias
at alluxio.conf.InstancedConfiguration.get(InstancedConfiguration.java:108)
at alluxio.conf.InstancedConfiguration.get(InstancedConfiguration.java:100)
at alluxio.conf.InstancedConfiguration.getString(InstancedConfiguration.java:259)
at alluxio.conf.Configuration.getString(Configuration.java:221)
at alluxio.DefaultStorageTierAssoc.<init>(DefaultStorageTierAssoc.java:71)
at alluxio.worker.netty.FileWriteHandler.<init>(FileWriteHandler.java:49)
at …
```
> Remove unused class

- dev/github/run_checks.sh
add check to ensure the go code in `cli/` compiles as part of the checks build
> Add golang cli compilation to github check

- dev/github/run_checks.sh
- dev/scripts/src/alluxio.org/build/cmd/build.go
running `build/cli/build-cli.sh -a` from tarball dry runs
needed to fix dry runs
no
> Build all golang cli executables for tarball dry run

- cli/src/alluxio.org/cli/cmd/fs/cp.go
directly call `fs cp` instead of the deleted `copyToLocal` and `copyFromLocal`
> Fix cp command to avoid copyToLocal and copyFromLocal

- bin/alluxio-monitor-bash.sh
- bin/alluxio-start-bash.sh
- cli/src/alluxio.org/cli/env/process_start.go
- cli/src/alluxio.org/cli/env/process_stop.go
- cli/src/alluxio.org/cli/processes/all.go
- cli/src/alluxio.org/cli/processes/local.go
Disable proxy and job services to start by default
Proxy (standalone), job services are deprecated in 3.0
When launching Alluxio, by default no job service or proxy processes will be started
> Disable starting proxy/job processes in all/local

- bin/alluxio-start-bash.sh
- bin/alluxio-stop-bash.sh
follow up to https://github.com/Alluxio/alluxio/pull/17993 on the stop process bash script side. golang code doesn't have an issue because it has a single source of truth
> Disable stopping proxy/job processes in all/local

- build/cli/build-cli.sh
- docs/en/contributor/Building-Alluxio-From-Source.md
in the golang cli build script, check that
- `go` is accessible
- go version is 1.18+
- run `go mod tidy` which should be a no-op command normally, but if it's the first time building, it will download some native packages
also update the compile requirements in docs
> Check env preconditions before building go cli

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Add metrics for the ages of the pages in page cache store
To make sure we're not keep the data in cache too long
no
> Add metrics for the ages of the pages in page cache store

- dora/shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
The LsCommand displays DataInAlluxioPercentage, but it always shows 0% which is misleading.
This change changes the DataInAlluxioPercentage column to a fix string FILE in the Lscommand.
As mentioned above, it fixes the bug that LsCommand always shows 0% for DataInAlluxio.
Yes, it will change the display of LsCommand.
It will change the output of LsCommand for files but not directories. For files, it will be the follow format
```
./alluxio fs ls /file_path
FileSize     PeristenceState    Timestamp    FILE     FilePath 
```
It changes the percentage of data in Alluxio to a fix string FILE as shown above.
> [SMALLFIX] Fix DataPercentageinAlluxio always shows 0%

- dora/core/common/src/main/java/alluxio/membership/AlluxioEtcdClient.java
- dora/core/common/src/main/java/alluxio/membership/DefaultServiceEntity.java
- dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
- dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
- dora/core/common/src/main/java/alluxio/membership/WorkerServiceEntity.java
- dora/core/common/src/test/java/alluxio/membership/ServiceEntityTest.java
- Change the serialize/deserialize interface for future use(#17959)
- Expose the TTL and timeout of the lease used in `ServiceDiscoveryRecipe`
- Expose the path prefix of the `ServiceDiscoveryRecipe` for future use
etcd will be used in the near future for more areas than worker service discovery. so expose more information for future use.
nope
> Change the interface of etcd-related class

- cli/src/alluxio.org/cli/cmd/initiate/copy_dir.go
- cli/src/alluxio.org/cli/cmd/initiate/format.go
- cli/src/alluxio.org/cli/cmd/initiate/initiate.go
- cli/src/alluxio.org/cli/env/env.go
- cli/src/alluxio.org/cli/env/env_vars.go
- cli/src/alluxio.org/cli/processes/common.go
- cli/src/alluxio.org/cli/processes/multi.go
Additional `init` commands to golang CLI as part of https://github.com/Alluxio/alluxio/issues/17522
`bin/alluxio-bash format` -> `bin/alluxio init format`
`bin/alluxio-bash copyDir` -> `bin/alluxio init copyDir`
> Add init/format, copyDir subcommands to CLI

- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadHandler.java
- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadRequest.java
- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/ListMultipartUploadsResult.java
- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
- dora/tests/integration/src/test/java/alluxio/client/rest/MultipartUploadTest.java
- dora/tests/integration/src/test/java/alluxio/client/rest/RestApiTest.java
- dora/tests/integration/src/test/java/alluxio/client/rest/TestCase.java
1. fix bugs in `alluxio.proxy.s3.S3ObjectTask.CompleteMultipartUploadTask#validateParts`
2. `CompleteMultipartUpload` executes the specified parts  with the specified upload ID rather than all parts. 
3. add `initiate / complete / abort MPU and upload part` unit tests.
4. remove `XAttr`
5. show all upload-parts to user while listing parts
there are problems in validateParts() of complete MPU
1. can’t recognize S3 Error: MalformedXML
3. throw unexpected error: InvalidPartOrder
we need to fix validateParts() of complete MPU to keep s3 proxy behaviors as consistent with aws as possible.
- can't get the bucket name and object name of the part while executing  ListMultipartUploads
- now complete MPU's response is like
|part list|response(before)|response(now)|
|-|-|-|
|  [] |   500 …
> Fix S3 multipart upload and add related UTs

- cli/src/alluxio.org/cli/env/command.go
Add a `RunWithWriters` interface apart from `Run` for future use.
In the future, we might need to parse the output of java in golang CLI. In this way we can reuse more code.
nope
> Add a new Run interface in CLI for future use

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Original-author: humengyu <hellohumengyu@gmail.com>
Support hdfs trash in hdfs ufs.
https://github.com/Alluxio/alluxio/issues/17723
HDFS trash is a very useful feature, and we should support it. It allows users to recover deleted files from the trash after accidental deletion.
add config in `alluxio-site.properties`:
```
alluxio.underfs.hdfs.trash.enable=true
```
add config in hdfs `core-site.xml`:
```
<property>
<name>fs.trash.interval</name>
<value>1440</value>
</property>
```
1. change in user-facing APIs YES
2. addition or removal of property keys YES
3. webui NO
> Support HDFS UFS trash

- dora/integration/jnifuse/fs/pom.xml
- dora/integration/jnifuse/fs/src/main/java/alluxio/jnifuse/AbstractFuseFileSystem.java
fix the bug where fuse has the bug of "java.lang.NoClassDefFoundError: Could not initialize class io.vertx.core.dns.AddressResolverOptions" after jetcd dependency was introduced
classes from native side, if not explicitly loaded, it will spew "NoClassDefFoundError" at runtime when the relevant classes was invoked.
No.
> Fix bug of classnotfound at Fuse runtime

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
This is a very small change which allows children of `DoraFileSystem` to have a ref to its `FileSystemContext`.
> [SMALLFIX] Allow FileSystem to have FSContext by inheritance

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/PacketReadTaskStateMachine.java
Reduce CPU overhead by replacing while loop with await. The previous version waits for finishing sending data by using a **while loop**. In that way, cpu overhead would be pretty high. Thus, instead of waiting for finishing sending data with a **while loop**, we use a **BlockingQueue** to notice it when all data have been sent out successfully.
> Reduce CPU overhead by replacing while loop with await

- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Worker checks UFS rename operation result and throws expcetion if failed
The rename operation result is omitted before. If operation fails, Alluxio client does not know the result.
N/A
> Check UFS rename operation result and throw exception if failed

- dora/integration/fuse/bin/alluxio-fuse
Fix alluxio-fuse bug with `/tmp` symlink on macOS
On macOS, the directory `/tmp/` is a symbolic link to `/private/tmp/`. 
This caused the `fuse_mounted` function to fail when attempting to 
mount a UFS to `/tmp/mnt`, as the `mount` command outputs the path 
as `/private/tmp/mnt`. 
This commit corrects this issue by resolving the symlink before checking the mount status.
Fix this bug which fails to detect if alluxio-fuse successfully mounts a remote UFS
NA
> Fix alluxio-fuse when mounting to /tmp

- dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
should use interface factory for membership mgr module for scheduler at time of master startup, otherwise setting STATIC membership mgr will not start master.
if alluxio.worker.membership.manager.type is set to STATIC, master won't be able to start as it needs etcd related info.
N/A
> Fix issue when starting master with STATIC membership type

- dora/examples/pom.xml
This PR fixed the shaded client version problem in dora example pom.
Current version in dora/example/pom.xml written as `<version>2.9.0</version>`. As a result, all updates on the shaded client after 2.9.0 won't work (e.g. removal of swift ufs). Now it is written as `<version>${project.version}</version>`
> Fix static shaded client version in dora example pom

- cli/src/alluxio.org/cli/env/env.go
Run `bash -c java -version` might be not work on remote machines, reporting the following bug.
```
java.lang.RuntimeException: Failed to successfully complete the job: Task execution failed: Error: error defining alluxio environment
--- at /cli/src/alluxio.org/cli/launch/launch.go:49 (Run.func1) ---
Caused by: error checking java version compatibility
--- at /cli/src/alluxio.org/cli/env/env.go:132 (InitAlluxioEnv) ---
Caused by: error finding java version from `/usr/lib/jvm/java/bin/java -version`
--- at /cli/src/alluxio.org/cli/env/env.go:246 (checkJavaVersion) ---
Caused by: exec: "bash": executable file not found in $PATH
```
Run `java -version` directly can solve this problem.
> Avoid using bash -c in checking Java version in Golang CLI

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
The reverse resolution should follow the same pattern as defined in `DoraCacheFileSystem.convertAlluxioPathToUfsPath()` and be made public. This further allows inheritance and overriding.
> [SMALLFIX] Make DoraCacheFileSystem.convertUfsPathToAlluxioPath public

- core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
Fix a deadlock.
On the Alluxio client, there is a monitor lock of `FileSystemContext` to sync individual client-to-master operations.
One application thread can successfully hold the monitor lock (`alluxio.client.file.FileSystemContext`)  in order to get worker list, but blocked by another “lock” `FileSystemContextReinitializer`  (waiting for latch on on-going RPCs down to zero) for acquiring the block master client to really connect to master process  (waiting for other callers involving `FileSystemContextReinitializer` to finish). 
On the other hand, another heartbeat thread "config-hash-master-heartbeat-0" is awaking periodically to sync with the master process to fetch the latest configuration. This thread detected the conf update and thus entered `FileSystemContextReinitializer` …
> Fix a deadlock in FileSystemContext

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Handle the reserved character ':' for HTTP server.
> Handle the reserved character ':' for HTTP server

- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Return FileNotFound when a file is being create/write. No need to refresh its metadata.
Metadata will be refreshed when file is closed.
If a file is being written to, and another getStatus() comes for such file, 
this file probably has not been created in UFS. At that time,
the getStatus() thinks that this file does not exists. So the worker tries to remove its metadata and its data from cache.
ERROR logs were generated in such case.
This patch is to handle this correctly and remove such ERROR logs:
```
2023-09-05 17:16:32,802 ERROR LocalCacheManager - Failed to delete page PageId{FileId=f4b0d1f405d7419069129a1262eae9329e9c19ed2584fc3fe27656a698344047, PageIndex=0} (isTemporary: false) from pageStore.
alluxio.exception.PageNotFoundException: …
```
> Return FileNotFound when a file is being create/write

- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReadOrOutStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReader.java
Add isReadOnly() for FuseFileStream and implement this interface in various Streams.
This interface is used to determine if the Stream is only. This is needed to determine if a real data flush is needed.
N/A
> Add isReadOnly() for FuseFileStream

- shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
ref https://github.com/Alluxio/alluxio/commit/8cbc4908da1985b5b0ebec3bb807ce9bd3764f4e
Fix potentially failing test for different versions
no
> Handle any version string for summarycommandtest

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Add a config to turn on/off the sdk cache fallback
the read fallback should be turn off by default to avoid retry storm to UFS
Addition  of property keys
> Add a config to turn on/off the sdk cache fallback

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
Fix the array out of bound exception in presto
Because we saw earlier that the LocalCacheManager swallows all exceptions, if there is an error accessing one of the cached files, the exception will be ignored. However, the offset may have changed during the failed read attempt in LocalCacheManager. When LocalCacheManager returns -1 on error and tries to reread from the lower layer storage, the offset could be out of bounds.
Regarding why this issue only appears in versions 2.9.3 and later, it's because the offset became a member variable of our target buffer starting from 2.9.3. In earlier versions it was always a local variable, so there was no compounding of offset errors.
no
> Fix the array out of bound exception in presto

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
Change metric type of LocalCacheState from counter to gauge.
The type of LocalCacheState metric is not reasonable since the value of this metric is a enum type not an increasable value
No
> Change metric type of LocalCacheState from counter to gauge

- core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioHdfsInputStream.java
Support read bytebuffer for non ByteBufferReadable input stream
Without this changes, a non ByteBufferReadable input stream can throw exception when the bytebuffer apis are called.
No
> Support read bytebuffer for non ByteBufferReadable input stream

- docs/en/deploy/Get-Started.md
Fuse is supported on K8s. Remove the outdated limitation.
> [DOCFIX] Remove outdated limitation in QuickStart doc

- dora/job/server/src/main/java/alluxio/job/plan/stress/StressBenchDefinition.java
- dora/stress/shell/src/main/java/alluxio/stress/cli/Benchmark.java
Change `runClass` in Benchmark to `exec class`
Since new alluxio cli change from `runClass` to `exec class`, related benchmark code should be change as well to keep it work
no
> Change Benchmark's `runClass` to `exec class` 

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- dora/core/common/src/test/java/alluxio/metrics/MetricsSystemTest.java
Remove hostname from metrics key
For easy aggregation on prometheus and grafana side
Add a flag to disable this for compatibility
> Remove hostname from metrics key

- cli/src/alluxio.org/cli/launch/launch.go
- docs/en/api/REST-API.md
- docs/en/contributor/Contributor-Tools.md
- docs/en/deploy/Get-Started.md
- docs/en/deploy/Install-Alluxio-Cluster-with-HA.md
- docs/en/operation/Configuration.md
- docs/en/operation/Logging.md
- docs/en/reference/Troubleshooting.md
besides the User-CLI.md doc, update other doc files that refer to `bin/alluxio` commands
- remove docs on path config
- remove starting/stopping job master/worker from contributor docs
> [DOCFIX] Update bin/alluxio usage format

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/integration/fuse/src/main/java/alluxio/fuse/lock/FuseReadWriteLockManager.java
Make fuse max reader concurrency configurable. The default value was 64 and it was unchangeable.
> Make fuse max reader concurrency configurable

- docs/en/compute/Hadoop-MapReduce.md
- docs/en/compute/Hive.md
- docs/en/compute/Presto.md
- docs/en/compute/Spark.md
- docs/en/compute/Tensorflow.md
- docs/en/compute/Trino.md
- docs/en/ufs/CephFS.md
- docs/en/ufs/Storage-Overview.md
update usages of bin/alluxio, bin/alluxio-start.sh and bin/alluxio-stop.sh to their new counterparts
simplify section of CephFS.md and remove sections related to mounting. the ufs must be configured as the root mount via alluxio-site.properties.
> [DOCFIX] Update bin/alluxio usage in ufs/compute

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Support accessing OSS through proxy by configuring alluxio properties or system properties.
When accessing OSS through a proxy, the OSS client cannot recognize the proxy configuration in system property and environment variables. So it has to proactively set proxy-related configurations in the configuration.
3. webui
> Support accessing OSS with proxy

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
If don't set oss.proxy.host, the default value should be NULL
If don't set oss.proxy.host, the default value should be NULL
3. webui
> Fix default value of proxy host

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- dora/core/server/worker/src/main/java/alluxio/worker/s3/S3NettyHandler.java
In this change the path conversion logic is extracted to static utility methods for code reuse (because other classes may use the same path resolution logic). 
The method names are slightly improved, to distinguish the member methods in `DoraCacheFileSystem` (may be inherited) from the static utility methods.
> Extract path resolution in DoraCacheFS into static utility

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- dora/core/common/src/main/java/alluxio/util/io/PathUtils.java
1. Move the path resolution logic from `DoraCacheFileSystem` to `PathUtils` where it makes more sense
2. Fix the alluxioPathToUfsPath resolution by handling the case where the ufs path may have no matching alluxio path, making the util method more generic
> Move path resolution logic and fix a bug

- core/server/master/src/main/java/alluxio/master/job/FileIterable.java
- core/server/master/src/test/java/alluxio/master/file/scheduler/LoadJobTest.java
- core/server/master/src/test/java/alluxio/master/file/scheduler/LoadTestUtils.java
Check for more results when the filtered result is null when loading data.
Fix #18043.
> Check for more results when the filtered result is empty

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
1. Use `addSuppressed` instead of creating a new exception to throw the original exception.
2. Go ahead to write data to UFS when it encountered exception during the time writing data to Alluxio Worker.
> Write to UFS when failed to write to Alluxio Worker

- cli/src/alluxio.org/cli/cmd/job/load.go
- common/transport/src/main/proto/grpc/block_worker.proto
- common/transport/src/main/proto/grpc/file_system_master.proto
- common/transport/src/main/proto/proto/journal/job.proto
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/worker/dora/DoraWorker.java
- dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/JournalLoadJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadJobFactory.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/JournaledJobMetaStore.java
- dora/core/server/master/src/test/java/alluxio/master/file/scheduler/SchedulerTest.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
- dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
Improve distributed load
1. Configurable job failure criteria 
2. Configuration to determine if the load job should be restored from journal or not
3. Add an option to skip existing fully loaded file 
4. Add retry count for failed files 
5. Bug fixing
To enhance the distributed load tool
Yes. The skip-if-exists option is added to the distributed load cli.
> Improve distributed load

- dora/core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- dora/core/client/hdfs/src/main/java/alluxio/hadoop/FileSystem.java
- dora/core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemApiTest.java
- dora/tests/integration/src/test/java/alluxio/client/fs/DoraS3PathIntegrationTest.java
Recover the ufs uri support
Ufs uri should be the first class citizen in dora
No
> Recover the ufs uri support

- dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashProviderTest.java
Add a test so we can monitor the vnode distribution is not too uneven. 
This test calculates the standard deviation over mean on the collection of virtual nodes assigned to physical nodes. It arbitrarily bounds it at 0.25, but ideally this number should get smaller over time as we improve hashing algorithm
and use better ways to assign virtual nodes to physical nodes.
We may change hashing algorithm and virtual node assignment in the future, this will provide guidance and catch errors. 
No.
> Add a test to monitor the distribution of vnode to physical node

- cli/src/alluxio.org/cli/cmd/info/report.go
- cli/src/alluxio.org/cli/env/command.go
Update the Golang side commands to be able to use this output:
1. Return either the yaml or json (default) output to the console.
2. Users can define the format they want with `--format` flag, like `bin/alluxio info report --format yaml`
3. In JSON format, print properties in a fixed, easy-to-read order
4. In YAML format, print properties alphabetically (since YAML specification regards property order non-significant)
Before:
```
{"safeMode":false,"masterVersions":[{"version":"304-SNAPSHOT","host":"localhost","port":19998,"state":"PRIMARY"}],"masterAddress":"localhost:19998","zookeeperAddress":[],"useZookeeper":false,"raftJournalAddress":["localhost:19200"],"useRaftJournal":true,"liveWorkers":1,"lostWorkers":0,"freeCapacity":"1024.00MB","totalCapacityOnTiers":{"MEM":"1024.00MB"},"usedCapac …
```
> Parse JSON-style reports in golang side

- dora/core/server/master/src/main/java/alluxio/master/predicate/DatePredicate.java
- dora/core/server/master/src/main/resources/META-INF/services/alluxio.master.predicate.FilePredicateFactory
- dora/core/server/master/src/test/java/alluxio/master/predicate/DatePredicateTest.java
Add datePredicate, i.e.:
lastModifiedDate(2000/01/01, 2023/09/01)
Customer requirement.
na
> Add datePredicate

- dora/job/server/src/main/java/alluxio/job/plan/stress/StressBenchDefinition.java
- dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchCoarseDataPoint.java
- dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchCoarseDataPointDeserializer.java
- dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchDataPoint.java
- dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchDataPointDeserializer.java
- dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchParameters.java
- dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchSummary.java
- dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchTaskResult.java
- dora/stress/shell/src/main/java/alluxio/stress/cli/Benchmark.java
- dora/stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
- dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
For random reads, bytes read per file is not a constant any more. In spite of existing duration distribution, need a throughput distribution for better understanding of reading performance.
Also, when duration too long, grpc will receive huge size of output data. Should aggregate data points to transfer more datapoints with limited output size.
Group datapoints by threads and time slices:
Example:
```
nodeResults: {
worker-0: {
dataPoints: [
data: [
{ // worker 0, thread 0, slice 0
count: 1,
iobytes: 33554432,
}, { // worker 0, thread 0, other slices
…
}
], [ // worker 0, other workers
…
]
]
throughputPercentiles: […]
},
worker-1: { // other workers
…
}
}
```
Slice time with `--slice-size` flag, e.g. `--slice-size 1s`.
> Add throughput distribution and coarse datapoints for StressWorkerBench

- dora/core/common/src/main/java/alluxio/extensions/ExtensionFactoryRegistry.java
Fix UFS not loaded in some cases.
Fix the following error when loading `UnderFileSystemFactory`:
```
java.lang.NoClassDefFoundError: alluxio/underfs/UnderFileSystemFactory
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at alluxio.extensions.ExtensionsClassLoader.findClass(ExtensionsClassLoader …
```
> Fix `NoClassDefFoundError` UnderFileSystemFactory not loaded

- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Alluxio does not have a valid Block Info at this moment.
return an all zero block info for fsstat
No valid block info is managed by Alluxio at this moment.
Alluxio does not have 'master' node, and no block info is stored/managed by other components.
This may change in future, e.g. statfs() can gather the block info from all worker nodes.
N/A
> return an all zero fsstat

- dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashPolicy.java
- dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashProvider.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
The configuration `alluxio.user.consistent.hash.virtual.node.count` is for total virtual nodes of all workers. We need to adjust the configuration according to the number of worker nodes. However, it is difficult to determine how many virtual nodes are enough to avoid the data skew issue.
Based on this background, a better way to solve the data skew issue is to allow user to set the virtual nodes number for a worker node, but not the total virtual nodes of all worker nodes. This is what this PR does.
> Enable config the virtual nodes num per node

- dora/underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystemFactory.java
Fix GCSV2UnderFileSystem initialization
not able to create ufs instance if not set access key, which should not be a requirement for gcs v2
na
> Fix GCSV2UnderFileSystem initialization

- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
And refactor fuse start code into startCommon() and stopCommon()
Stop Fuse web server when exit.
Fuse web server must be stopped, otherwise the main thread is waiting for it forever.
N/A
> Stop fuse web server

- cli/src/alluxio.org/cli/env/process.go
Only stop processes belong to the current user while running `./bin/alluxio process start` or `./bin/alluxio process stop`
Without this PR, it will try to stop all processes match the class name even they are not started by the current user. Like the below case
```
$ ./bin/alluxio process stop local
WARN[2023-09-21T14:57:31+08:00] No process to stop because could not find running process matching alluxio.worker.AlluxioWorker
INFO[2023-09-21T14:57:31+08:00] Found 1 running process(es) matching alluxio.master.AlluxioMaster
INFO[2023-09-21T14:57:31+08:00] Successfully killed 0 process(es)
ERRO[2023-09-21T14:57:31+08:00] Failed to kill 1 process(es):
ERRO[2023-09-21T14:57:31+08:00] Failed to kill process: error sending TERM signal to process for alluxio.master.AlluxioMaster with pid 17055
--- …
```
> Only stop processes belong to the current user

- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileReader.java
Don't call the ufs.close() in PageFileReader.close()
1. we should not close the ufs instance, because we always try to reuse it for the same ufs mount point. unless we don't reuse the instance of the ufs instance.
2. S3UnderFileSystem.close() will just shut down the executor held by the instance. when other threads reuse the executor, it will cause issues.
no
> Fix the bug of using a terminated executor in S3 UFS

- dora/core/common/src/main/java/alluxio/resource/CloseableResource.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInOrOutStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileInStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileOutStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FuseFileStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReadOrOutStream.java
- dora/integration/fuse/src/main/java/alluxio/fuse/file/FusePositionReader.java
Split the fuse stream close() method into two individual methods:
1. Close the fuse stream
2. Release the lock
Currently no behavior changes on the close function as the function will call these two functions to achieve the same functionality as before. 
When we handle some fuse operations, we sometimes want to close the stream only but want to keep the lock there, to avoid inconsistency.  
3. addition or removal of property keys
4. webui
> Split the fuse stream close() method

- cli/src/alluxio.org/cli/cmd/info/report.go
- cli/src/alluxio.org/cli/env/command.go
- cli/src/alluxio.org/go.mod
- cli/src/alluxio.org/go.sum
- dora/shell/src/main/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommand.java
- dora/shell/src/main/java/alluxio/cli/fsadmin/report/JobServiceOutput.java
- dora/shell/src/main/java/alluxio/cli/fsadmin/report/SummaryCommand.java
- dora/shell/src/main/java/alluxio/cli/fsadmin/report/SummaryOutput.java
- dora/shell/src/test/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommandTest.java
- dora/shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
For now, Java is in charge of formatting the output of reports, e.g. file size in bytes to readable values; date formats.
This PR moves the format job to the golang CLI side. When checking reports, data transferred to golang CLI, and CLI deal with the formatting.
Current date format: `2006-01-02T15:04:05Z07:00`
Current duration format: `0d 12h34m56s`
Current file size format: `1024.00MB` (scale up when number > 5120)
Format on dates:
- `summary` object -> `started` object
- `job_service` object -> `masterStatus` array -> `startTime` object
- `job_service` object -> `recentModifiedJobs` array -> `timestamp` object
- `job_service` object -> `recentFailedJobs` array -> `timestamp` object
- `job_service` object -> `longestRunningJobs` array -> `timestamp` object
Format on duration:
- …
> Format reports on Golang CLI

- dora/core/client/fs/src/test/java/alluxio/client/file/ufs/AbstractUfsStreamTest.java
- dora/core/client/fs/src/test/java/alluxio/client/file/ufs/UfsFileInStreamTest.java
- dora/core/client/fs/src/test/java/alluxio/client/file/ufs/UfsFileOutStreamTest.java
UfsFileIn/OutStream Test runnable now
Need UfsFileIn/OutStream Test
No
> Fix and re-enable UfsFileIn/OutStreamTest

- core/common/src/main/java/alluxio/Constants.java
- core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
- core/server/master/src/test/java/alluxio/master/meta/AlluxioMasterRestServiceHandlerTest.java
- core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
Before: Web UI displays only files ending with ".log" in name.
After: Web UI displays logs files like `.log.XXX`, which are rolled over log files. Also the displayed files include `.out` and captured `txt` and `json` files like metrics and jstack.
Better observability for admin.
3. webui
> Support display all log files on web UI

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/transport/src/main/proto/grpc/file_system_master.proto
- core/transport/src/main/proto/proto.lock
- shell/src/main/java/alluxio/cli/fs/command/MountCommand.java
Support unmount and mount to another mount point within the same lock
Support replace ufs for a mount point. The operation is atomic so no user operations should fail due to observing the middle state.
A new rpc field and cmd options are added.
> Support unmount and remount in one atomic operation

- common/transport/src/main/proto/grpc/block_master.proto
- dora/core/client/fs/src/main/java/alluxio/client/block/BlockMasterClient.java
- dora/core/client/fs/src/main/java/alluxio/client/block/BlockWorkerInfo.java
- dora/core/client/fs/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java
- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
- dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/server/master/src/main/java/alluxio/master/block/BlockMasterClientServiceHandler.java
- dora/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- dora/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- dora/core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/DefaultWorkerProvider.java
- dora/core/server/master/src/main/java/alluxio/master/scheduler/WorkerProvider.java
By default, we build a dynamic consistent hash with the live worker list that comes from master or ETCD. Sometimes we want to build a static consistent hash ring to make sure we won't write data to other worker node when a worker node is offline temporarily (especially when other worker nodes are running out of disk space).
This PR provides allows us to build a static consistent hash ring by setting `alluxio.user.dynamic.consistent.hash.ring.enabled=false`. In this case, client will read from UFS if the worker where the specified file locate is down.
> Enable static consistent hash ring

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
- dora/core/client/fs/src/main/java/alluxio/client/file/dora/netty/NettyDataReader.java
- dora/core/client/fs/src/main/java/alluxio/client/file/ufs/UfsFileInStream.java
- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
Add client read metrics
These metrics are helpful.
N/A
> Add Read Metrics

- dora/core/common/src/main/java/alluxio/membership/AlluxioEtcdClient.java
- dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
- dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
1. Since EtcdClient is a singleton, close it in the jvm shutdownHook
2. Close related resources within EtcdClient
> Close Etcd client when process exits

- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileReader.java
1. The length of the read is incorrectly calculated. Should not have anything to do with the position of the reader.
2. `mPos` should not be updated for the `read` method, as it's a positioned read operation (has an `offset` argument).
bug fix
No.
> Fix read position in PagedDoraWorker

- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
This improves resource deallocation in two ways:
1. Close FileSystemContext
2. Close an optional thread pool on normal exit (before it is only destroy on error)
Resource deallocation
> Improve resource deallocation in FUSE

- dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchDataPoint.java
- dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
For now StressWorkerBench uses milliseconds as the smallest unit of recording. In random read, if file is very small, it is possible to have a duration <1ms. Since instant throughput = bytes read / duration, it will lead to a divide by zero error.
This PR replace millisecond-level record of a file read with a nanosecond-level approach. It also makes the following updates on StressWorkerBench:
- record file read time within `applyOperation()` function, instead of before entering or after exiting it
- wrap metrics about the `applyOperation()` function to a private class, instead of returning bytes read only
- remove getter and setters for WorkerBenchDataPoint, since all elements inside is public
- standardize the unit of output throughput, now unit is MB/s
> Modify StressWorkerBench: calculate elapsed time in nanoseconds

- dora/integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Added a manual double-safety `System.exit()` at the end of FUSE lifecycle, to be absolutely sure we exit the JVM and terminate all non-daemon & daemon threads.
Before this change, after we `alluxio-fuse umount` or `kill (not -9)`, the FUSE process may fail to quit. One reason is a non-daemon thread dangling around:
```
"vert.x-eventloop-thread-0" #21 prio=5 os_prio=31 cpu=482.23ms elapsed=722.11s tid=0x00007fde79251800 nid=0x8c03 runnable  [0x00007000102ae000]
java.lang.Thread.State: RUNNABLE
at sun.nio.ch.KQueue.poll(java.base@11.0.11/Native Method)
at sun.nio.ch.KQueueSelectorImpl.doSelect(java.base@11.0.11/KQueueSelectorImpl.java:122)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.11/SelectorImpl.java:124)
- locked <0x00000007c0603938> (a …
```
> Add manual exit at the end of FUSE life cycle

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/membership/AlluxioEtcdClient.java
- dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Allow AlluxioEtcdClient to use username/password to talk to etcd if target etcd server has authentication enabled.
as above.
N/A
> Add user/password support for etcd

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/DefaultPageMetaStore.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/DefaultPageMetaStoreTest.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/QuotaPageMetaStoreTest.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/QuotaPagePageMetaStoreTest.java
Add unit test for DefaultPageMetaStore.commitFile() method, and rename some variables to more accurate names. 
Improve the test coverage.
No.
> Add UT to DefaultPageMetaStore.commitFile

- dora/tests/integration/src/test/java/alluxio/client/fs/DoraFileSystemIntegrationTest.java
Set PropertyKey.DORA_CLIENT_UFS_FALLBACK_ENABLED to false.
As we mentioned in [here](https://github.com/Alluxio/alluxio/pull/18213).
When we want to test the DoraFileSystem, we have to disable the Ufs Fallback, otherwise the methods like `createFile`  `getStatus` will fall back to Ufs, while we want to test DoraFileSystem.
**This is a important change, so it is necessary to open a new PR for it.**
No.
> Disable UFS fallback in DoraFileSystemIntegrationTest

- dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
when etcd lease keepalive client returned with onCompleted or onError, the lease might not directly get expired at the time, therefore we always new a lease to resume keepalive without explicitly checking isleaseexpired
when etcd got induced network unstableness such as pkg loss, there's race condition in our reconnection logic from ServiceDiscoveryRecipe, where we directly check isLeaseExpired when we got terminal callback from keepalive client, but at the time the lease isn't expired yet. Hence we stop trying to create new lease to keepalive.
No
> Fix reconnect logic of servicediscoveryrecipe

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerInitializer.java
- dora/core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
Avoid creating `FileSystem` instance many times in `HttpServerHandler`, and call the `close()` method when the handler is removed.
> Avoid creating FileSystem instance many times in HttpServerHandler

- dora/tests/integration/src/test/java/alluxio/client/hadoop/FileSystemBlockLocationIntegrationTest.java
Fixed one test case in FileSystemBlockLocationIntegrationTest
Logic of getBlockLocation in DoraCacheFileSystem has chagned, so related IntegrationTest need be change as well
no
> Fix FileSystemBlockLocationIntegrationTest

- dora/core/client/fs/src/main/java/alluxio/client/file/dora/WorkerLocationPolicy.java
- dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchMode.java
- dora/stress/common/src/main/java/alluxio/stress/worker/WorkerBenchParameters.java
- dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
This PR adds a `--mode` option for StressWorkerBench. This option allows user to choose from a range of file read policies. Possible option values are `hash`(default) and `local-only`.
If use `hash`, the config `alluxio.client.file.dora.ConsistentHashPolicy` is set to `alluxio.client.file.dora.ConsistentHashPolicy`.
If use `local-only`, that config is set to `alluxio.client.file.dora.LocalWorkerPolicy`.
The benchmark will parse this option, and choose the right policy. Also, it will print a log about the policy the user is using in both the benchmark and the policy factory.
In previous versions, the default policy is `local-only`.
However, in Alluxio, the default policy is `hash`, using `alluxio.client.file.dora.ConsistentHashPolicy`.
If user wants to use the `local-only` policy, add …
> Support StressWorkerBench using consistent hash policy

- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
- tests/src/test/java/alluxio/client/hadoop/FileSystemAclIntegrationTest.java
Support creating directories and files with default permissions based on configuration propertykey in HDFS API.
Alluxio Hdfs api hasn't the corresponding implementation of Mkdir without permission parameter. If it does not carry permission, the umask property in the configuration item shall prevail.
> Support Mkdir/CreateFile with configured default umask in HDFS API

- dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashProvider.java
- dora/core/client/fs/src/test/java/alluxio/client/file/dora/ConsistentHashPolicyTest.java
Use linked hash set to keep sequence when picking multiple worker
When loading multiple replica into Alluxio, we want deterministic sequence so we can decide which worker to load data and which worker the client can talk to.
na
> Use linked hash set to keep sequence when picking multiple worker

- dora/core/common/src/main/java/alluxio/wire/WorkerIdentity.java
- dora/core/common/src/test/java/alluxio/wire/WorkerIdentityTest.java
Allow `WorkerIdentity` to be de/serialized to JSON and Java serialization format.
To be able to be embedded in `WorkerInfo` and other data objects that need to be de/serialized to JSON.
No.
> Add ser/de support for JSON or WorkerIdentity

- cli/src/alluxio.org/cli/cmd/cache/format.go
- cli/src/alluxio.org/cli/cmd/conf/get.go
- cli/src/alluxio.org/cli/cmd/exec/test_basic_io.go
- cli/src/alluxio.org/cli/cmd/exec/test_hdfs_mount.go
- cli/src/alluxio.org/cli/cmd/exec/test_worker.go
- cli/src/alluxio.org/cli/cmd/generate/doc_tables.go
- cli/src/alluxio.org/cli/cmd/initiate/validate.go
- cli/src/alluxio.org/cli/cmd/journal/format.go
- cli/src/alluxio.org/cli/cmd/journal/read.go
- cli/src/alluxio.org/cli/env/command.go
- cli/src/alluxio.org/cli/env/env.go
- cli/src/alluxio.org/cli/env/env_vars.go
- cli/src/alluxio.org/cli/env/process.go
- cli/src/alluxio.org/cli/processes/common.go
- cli/src/alluxio.org/cli/processes/job_master.go
- cli/src/alluxio.org/cli/processes/job_worker.go
- cli/src/alluxio.org/cli/processes/master.go
- cli/src/alluxio.org/cli/processes/proxy.go
- cli/src/alluxio.org/cli/processes/worker.go
- cli/src/alluxio.org/cli/processes/worker_test.go
address https://github.com/Alluxio/alluxio/issues/18249
refactor how java opt env vars are handled. previously they were treating as strings and then using a split operation to separate the single string into cmd line arguments. now they are handled as `[]string` immediately after parsing from env to properly handle any leading or trailing whitespaces.
> Refactor handling of java opts env vars in cli

- core/common/src/main/java/alluxio/conf/Configuration.java
Check cluster ufs version in getClusterConf.
Fix #18221.
> Check cluster ufs version in getClusterConf

- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Check the `-f, --load-metadata` option at the worker side.
The [doc](https://docs.alluxio.io/os/user/edge/en/operation/User-CLI.html#fs-ls) has
and the "fs ls" command has the following option
```
-f, --load-metadata       Force load metadata for immediate children in a directory
```
But this option is only set at the client side and is not checked at the worker side. So setting it has no use. Please check the following example
```
$ ./bin/alluxio fs ls /
-rw-rw-r--  test test              1366                 10-02-2023 17:39:54:284 FILE /file.01
-rw-rw-r--  test test              1366                 10-02-2023 17:41:37:496 FILE /file.02
-rw-rw-r--  test test              1366                 10-03-2023 11:04:18:177 FILE /file.03
$ ./bin/alluxio fs ls -f /
-rw-rw-r--   test test …
```
> Check load meta option at worker

- dora/integration/fuse/src/test/java/alluxio/fuse/ufs/stream/OutStreamTest.java
A comment in OutStreamTest is useless and need to be removed.
No.
> [SMALLFIX] Enable one UT case in OutStreamTest

- underfs/cosn/src/main/java/alluxio/underfs/cosn/CosNUnderFileSystemFactory.java
- Don't have to inherit the HdfsUnderFileSystemFactory CosNUnderFileSystemFactory directly implement UnderFileSystemFactory interface
- Possibly to resolve package conflicts, #17024 removed HdfsUnderFileSystemFactory from COSN UFS jar, resulting in inability to use COSN interface
- However, CosNUnderFileSystemFactory inherits from HdfsUnderFileSystemFactory,the ServiceLoader.load method loads CosNUnderFileSystemFactory and first searches for its parent class, so removing HdfsUnderFileSystemFactory directly will result in an error.
```
failed to load jar alluxio-underfs-hadoop-cosn-3.1.0-5.8.5-2.9.3.jar NoClassdDefFoundError :alluxio/underfs/hdfs/HdfsUnderFileSystemFactory
```
> Change CosNUnderFileSystemFactory implementation UnderFileSystemFactory

- dora/core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
- dora/core/common/src/main/java/alluxio/underfs/UfsFileStatusIterator.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadOptions.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadService.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
Add RESTful API for distributed load.
**SUBMIT:**
description: submit a load job
example:
`http://localhost:28080/v1/load?path=/&opType=submit&partialListing=false&&verify=true&bandwidth=1000&loadMetadataOnly=false&verbose=true&skipIfExists=true`
**STOP:**
description: stop the load job
example:
http://localhost:28080/v1/load?path=/&opType=stop
**PROGRESS:**
description: get the progress of the load job
example:
`http://localhost:28080/v1/load?path=/&opType=progress&progressFormat=text&verbose=true`
> Add RESTful API for distributed load

- dora/shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
- dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLoadCommandIntegrationTest.java
- dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLoadCommandWithVirtualBlockIntegrationTest.java
Load ufs path directly
Previously we concatenate root with relative path, now we directly pass ufs path So we can have multiple ufs support
load have to input full ufs path
> Load ufs path directly

- dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUfsStatusIterator.java
- dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
- dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/hdfs3/HdfsUnderFileSystemIntegrationTest.java
- dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/hdfs3/HdfsUnderFileSystemIntegrationTestBase.java
When there are a lot of files in HDFS, it takes a large amount of time and memory to complete a `listStatus` request. Moreover, sometimes OOM occurs. This PR provides an iterator for the HDFS under file system to list files.
> Implement HDFS list status iterator

- dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
- dora/core/client/fs/src/main/java/alluxio/client/file/PositionReadFileInStream.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Halve the prefetch size when cache miss, instead of resetting it to zero.
Slower shrinking of buffer size can improve performance in case of sequential read.
No.
> Make size of dynamic buffering shrink slower

- dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Now with worker id can be assumed from a different worker instance whether on a different pod in k8s or a different host machine for baremetal. The creation onto the persisted ring path : /DHT/DefaultAlluxioCluster/AUTHORIZED/ should not bail if a different value is seen.
to enable rejoin of a worker bearing same worker id but with different host or other WorkerInfo fileds.
No
> Remove restriction in overwriting worker info within join logic

- dora/core/client/fs/src/main/java/alluxio/client/file/AdaptivePrefetchCachePolicy.java
- dora/core/client/fs/src/main/java/alluxio/client/file/BasePrefetchCachePolicy.java
- dora/core/client/fs/src/main/java/alluxio/client/file/PositionReadFileInStream.java
- dora/core/client/fs/src/main/java/alluxio/client/file/PrefetchCachePolicy.java
- dora/core/client/fs/src/test/java/alluxio/client/file/PositionReadFileInStreamTest.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
Origin @dbw9580 
Add an prefetch cache policy that does not reset the sliding window when a cache read misses. Fuse sometimes create read requests that are out of the order and this helps the prefetch keep stable.
> Add prefetch cache policy

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
- dora/tests/integration/src/test/java/alluxio/server/worker/WorkerHttpServerIntegrationTest.java
Add getStatus RESTful API.
**Example:**
Get the specified directory/file information by the following request:
`curl -X GET http://localhost:28080/v1/info?path=/tpcds-data`
The response JSON looks like:
`[
{
"mType": "directory",
"mName": "tpcds-data",
"mPath": "/tpcds-data",
"mUfsPath": "s3a://jiamingmai-test/tpcds-data",
"mLastModificationTimeMs": 0,
"mLength": 0,
"mHumanReadableFileSize": "0B"
}
]`
> Add getStatus RESTful API

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStore.java
This change mainly adds two fixes to the `MemoryPageStore`:
1. Add a noop implementation to commit() so it does nothing instead of throwing `UnsupportedOperationException`
2. Clears the cache on close explicitly
> Fix MemoryPageStore error on commit() and clear cache on close()

- common/transport/src/main/proto/grpc/block_worker.proto
- common/transport/src/main/proto/grpc/file_system_master.proto
- common/transport/src/main/proto/proto/journal/job.proto
- dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadDataSubTask.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadMetadataSubTask.java
- dora/core/server/master/src/main/java/alluxio/master/job/LoadSubTask.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Update worker api support for load multi replicas
part of PR to support load multi replicas
na
> Update worker api support for load multi replicas

- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
Extract the logic to create `UfsBaseFileSystem` into `FileSystemContext`, for possible extension. This change is functionally a refactor that changes nothing.
> [SMALLFIX] Extract create UfsBaseFileSystem for extension

- dora/core/server/worker/src/main/java/alluxio/worker/netty/AbstractReadHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/FileReadHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/NettyReadHandlerStateMachine.java
resolves https://github.com/Alluxio/alluxio/issues/18324
Disclaimer: I might have monkey-typed this fix but I still do not know anything about buffer ref counting. This fix does NOT make me the owner of this state machine.
> Fix a buffer memory leak in NettyReadHandlerStateMachine

- underfs/cosn/pom.xml
Fix bug involved by https://github.com/Alluxio/alluxio/pull/17024
After https://github.com/Alluxio/alluxio/pull/18143, `HdfsUnderFileSystemFactory` is no longer included in COSN jar therefore no need to exclude.
> Fix cosn ufs cannot find class

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- dev/scripts/src/alluxio.org/build-distribution/cmd/common.go
- dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
- docs/cn/contributor/Building-Alluxio-From-Source.md
- docs/cn/ufs/HDFS.md
- docs/en/contributor/Building-Alluxio-From-Source.md
- docs/en/ufs/COSN.md
- docs/en/ufs/HDFS.md
- integration/tools/pom.xml
- pom.xml
- shaded/hadoop/pom.xml
- underfs/abfs/pom.xml
- underfs/adl/pom.xml
- underfs/hdfs/pom.xml
- underfs/wasb/pom.xml
Bump Hadoop version from `3.3.1` to `3.3.4`.
Fix hadoop CVE-2021-37404.
Hadoop version bump.
> Bump hadoop version to 3.3.4

- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Fix a bug when file size < 1 page, alluxio considers all pages are cached no matter if it really caches it or not.
Bug fixing 
N/A
> Fix isAllPageCached

- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
https://github.com/Alluxio/alluxio/issues/18357
mtime display error when ufs is hdfs
after this commit:
1. change in user-facing APIs. no
2. addition or removal of property keys. no
3. webui. no
> Fix file mtime display when ufs mtime is not null

- bin/alluxio-masters.sh
- bin/alluxio-monitor.sh
As issue https://github.com/Alluxio/alluxio/issues/15795 mentioned. When output any warnings, the cli of judging HA_ENABLED will be invalid. This PR fixs it.
Bug fix.
No.
> Fix getConf bugs when it comes across warning

- dora/core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
Change the method visibility to `protected` to allow overriding this method.
I can override this method to a noop so the `UfsManager` does not connect to the real UFS instance.
> [SMALLFIX] Allow extension on `UfsManager.tryUfsFileSystem()`

- dora/core/common/src/main/java/alluxio/worker/dora/OpenFileHandle.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraOpenFileHandleContainer.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
Checking all open handles periodically. 
if some handle is stale (inactive for more than 24 hours), please warning messages.
Every time an open handle is used, its last access time is updated.
In future, we may need to handle this case instead of printing warning messages.
If an open handle is inactive for a long time, it may be caused by stuck, or by disconnected client.
So a warning message is generated. Originally the open handle was closed in such case.
But if a write is really slow or paused there, we are not going to close this handle.
N/A.
> Print warning messages for stale open handle instead of removing it

- dora/core/common/src/main/java/alluxio/network/netty/NettyChannelPool.java
Reduce unnecessary logging to help debugging
Noisy logging like `2023-09-11 20:02:30,750 INFO  NettyChannelPool - Channel closed`
N/A
> Change logging level in NettyChannelPool

- dora/core/client/fs/src/main/java/alluxio/client/file/AdaptivePrefetchCachePolicy.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/server/master/src/main/java/alluxio/master/job/DoraLoadJob.java
1. Add a property to limit the DLQ capacity in distributed load
2. Fix a position reader bug where the prefetch size will converge at 2 * read length - 1
> Add a configurable DLQ capacity of avoid OOM

- dora/core/server/worker/src/main/java/alluxio/worker/dora/DoraMetaManager.java
- dora/underfs/cos/src/main/java/alluxio/underfs/cos/AlluxioCosException.java
- dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
- dora/underfs/cos/src/test/java/alluxio/underfs/cos/COSUnderFileSystemTest.java
- dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Add exception handling for OSS and COS ufs in getting object tags and other apis.
When handling exceptions, we need to identify exceptions that can be allowed, and other errors need to be converted to an Alluxio exception.
3. webui
> Fix the issue to get a tag of a non-existed in OSS/COS

- cli/src/alluxio.org/cli/env/command.go
When debugging load command, it is found that `./bin/alluxio` CLI can't process Chinese characters correctly. There must be something wrong with the CLI encoding or decoding. It seems that the Chinese characters are encoded incorrectly.
This happens because the construction of CLI commands does not initialize environmental variables correctly. OS-level environmental variables are ignored, so the program uses a false encoder.
This pull request fixes this problem.
> Fix chaotic chinese characters with golang cli commands

- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3BucketTask.java
- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/s3/S3NettyBucketTask.java
`objects` is initialized by empty array but we never used this default value.
1. change in user-facing APIs. no
2. addition or removal of property keys. no
3. webui. no
> [SMALLFIX] Remove unused objects initialize

- dora/core/client/fs/src/main/java/alluxio/client/file/dora/RemoteWorkerList.java
- dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
This pull request fixes a bug on stress worker bench.
1. When using the remote worker policy, running `findNextWorker()`, multiple threads increment `mNextIndex`, leading to possible array out of bounds errors when getting worker info.
2. If use remote worker policy and the cluster size is 1, no workers can be found in `findNextWorker()`, resulting in errors.
This fix turns `findNextWorker()` into a synchronized function, which can avoid data corruption. In addition, this policy can only be used when cluster size > 1.
> Fix StressWorkerBench with remote worker policy

- .github/workflows/java8_integration_tests.yml
- .github/workflows/java8_integration_tests_ft.yml
- .github/workflows/java8_integration_tests_webui.yml
- dev/github/run_tests.sh
a previous PR https://github.com/Alluxio/alluxio/pull/18313 restored the integration tests but caused the unit tests to also run with the integration tests.
the issue was correctly identified as an issue with the maven project list but the underlying problem was that the project name was not correctly set; `dora/tests` is not a module. it was previously a module until `dora/tests/testcontainers` was introduced, thus separating testcontainer tests vs integration tests.
this fix updates the previous project list with the correct module name
> Fix integration tests again

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraCacheFileSystem.java
- dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
Also print file path in getStatus() exception on client side
Use generic Exception to catch all exceptions in getStatus(), just like that in all other handlers.
File path will be included in log message for getStatus().
Sometimes, exceptions are thrown in under file system and/or other third-party libraries.
We don't know the exact type of the specific exceptions. If they are not caught, client will
report unknown exceptions in logs. This is misleading. 
Client will show logs with detailed exception information if there is any.
For getStatus(), file path will also be shown in log.
> Use generic Exception to catch all exceptions in getStatus()

- dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
meta.getLastModified() could be null, and should avoid the NPE. the parameter is nullable, so give it a null in this case.
meta.getLastModified() could be null, and should avoid the NPE. the parameter is nullable, so give it a null in this case.
3. webui
> Fix the NPE in COSUnderFileSystem

- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
Fix a bug caused by empty block location strings. The worker sends block locations which contain empty medium type strings and block master sync is therefore broken.
```
2023-11-06 10:18:26,714 ERROR BlockMasterSync - Failed to receive master heartbeat command. worker id 1812723380431920939
alluxio.exception.status.InternalException: MediumType must be one of {MEM, HDD and SSD} but got
at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:159)
at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:215)
at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:486)
at alluxio.AbstractClient.retryRPC(AbstractClient.java:450)
at alluxio.AbstractClient.retryRPC(AbstractClient.java:439)
at …
```
> Fix empty block location

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileReader.java
Remove empty pages when they are accessed by the get page methods. Empty pages except for the vert first page of a file are most likely malformed and are a result of a failed put attempt.
Reading empty pages causes 0 bytes to be read, and in some cases causing an infinite loop in the caller. When used with `getDataFileChannel`, it results in the channel to be created multiple times for a given empty page, because the channels are always 0 sized.
No.
> Remove malformed empty page files on access

- dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- dora/underfs/oss/src/test/java/alluxio/underfs/oss/OSSUnderFileSystemTest.java
Replace the FOLDER_SUFFIX from "_$folder$" to "/" in OSS UFS
We don't want to use '_$ Folder $" to represent the directory. We want to use a more general "/" instead to avoid some issues
No
> Replace the FOLDER_SUFFIX from "_$folder$" to "/" in OSS UFS

- dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
PR #18377 removes setting property `alluxio.user.worker.selection.policy` by mistake.
This will cause remote only policy not working.
This PR fixes this problem.
> Fix stress worker bench remote only policy not working

- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraMkdirCommandIntegrationTest.java
The `RuntimeException(FileAlreadyExistException)` changed to `AlreadyExistException()` in `PagedDoraWorker`
`RuntimeException(FileAlreadyExistException)` seems won't be caught in `DoraWorkerClientServiceHandler` when convertin it to `AlluxioRuntimeException`, which willl cause the loss status code
no
> Change file exist exception to runtime exception in PagedDoraWorker

- dora/core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
- dora/core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- dora/core/client/fs/src/main/java/alluxio/client/file/PositionReadFileInStream.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
- dora/core/client/fs/src/main/java/alluxio/client/file/dora/DoraCacheClient.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
Improve page loading performance by loading the page form UFS directly, instead of creating a reader.
To improve the data loading performance & reduce the memory consumption 
N/A
> Improve page loading performance

- dora/core/client/fs/src/main/java/alluxio/client/file/DoraFileOutStream.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCachePositionReader.java
- dora/core/common/src/main/java/alluxio/metrics/MultiDimensionalMetricsSystem.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedFileWriter.java
- dora/core/server/worker/src/main/java/alluxio/worker/grpc/DoraWorkerClientServiceHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/modules/DoraWorkerModule.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/AbstractWriteHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/FileWriteHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/NettyReadHandlerStateMachine.java
- dora/core/server/worker/src/main/java/alluxio/worker/netty/WriteRequestContext.java
Add call points of the new metrics
The new metrics are already defined in the previous pr, and need to be called in this pr.
no
> Add call points of the new metrics

- dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
> Fix the issue when mount an empty oss bucket

- dora/core/server/master/src/main/java/alluxio/master/job/UfsStatusIterable.java
- dora/underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUfsStatusIterator.java
- dora/underfs/hdfs/src/test/java/alluxio/underfs/hdfs/hdfs3/HdfsUnderFileSystemIntegrationTest.java
Fix the bug that `HdfsUfsStatusIterator` returns wrong path (the getName() method of `UfsStatus` should return a relative path, but not just the file name).
> Fix the bug that HdfsUfsStatusIterator returns wrong path

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java
When unmounting the mount point, make the deletion of syncPoint be applied to the standby master through journal.
If use `NOOP` journal, standby master will not remove the syncPoint, then if the standby become leader, if will crash and throw exception
```
2023-11-07 20:48:30,700 ERROR [main](ProcessUtils.java:76) - Uncaught exception while running Alluxio master @xx.xxx.xxx.xxx:xxxx, stopping it and exiting. Exception "java.lang.UnsupportedOperationException: Active Sync is not supported on this UFS type: local", Root Cause "java.lang.UnsupportedOperationException: Active Sync is not supported on this UFS type: local"
java.lang.UnsupportedOperationException: Active Sync is not supported on this UFS type: local
at alluxio.master.file.activesync.ActiveSyncManager.start(ActiveSyncManager.java …
```
> Fix standby master don't remove syncPoint correctly issue

- underfs/cos/src/main/java/alluxio/underfs/cos/AlluxioCosException.java
- underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
Fix the issue to get a tag of a non-existed in COS as PR #18388
3. webui
> Fix the issue in COSUnderFileSystem

- dora/core/client/fs/src/main/java/alluxio/client/file/dora/ConsistentHashProvider.java
- dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLsCommandIntegrationTest.java
Fix consistent hash policy returns stale worker addresses
Consistent hash policy only considers worker identities when building the hash ring. When a worker changes its network address but its ID stays the same, the update is ignored by the policy, so clients will try to connect with stale worker address.
No.
> Fix consistent hash policy returns stale worker addresses

- core/client/fs/src/main/java/alluxio/client/file/ufs/UfsBaseFileSystem.java
- core/common/src/main/java/alluxio/Constants.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
- core/server/master/src/main/java/alluxio/master/file/mdsync/DefaultSyncProcess.java
Recode the content hash into XAttr as the ETag when the UFS is S3. When the file is newly created or loaded from UFS, Alluxio will record the ContentHash into metastore so the user can see the ETag attribute.
When the UFS is Object storage, The user can see the ETag of the file persisted in UFS by this way.
No
> Load content hash as the etag of the object when the UFS is S3

- core/common/pom.xml
- core/common/src/main/java/alluxio/util/LogUtils.java
- core/server/master/src/test/java/alluxio/master/metastore/InodeStoreBench.java
- integration/tools/hms/pom.xml
- logserver/pom.xml
- pom.xml
- table/server/underdb/glue/pom.xml
- table/server/underdb/hive/pom.xml
- underfs/cephfs-hadoop/pom.xml
This PR fixes `log4j 1.x` [CVE-2019-17571](https://nvd.nist.gov/vuln/detail/CVE-2019-17571) critical vulnerability, by excluding all the `log4j 1.x` dependencies and replacing them with [reload4j](https://reload4j.qos.ch).
Fixing the `log4j 1.x CVE-2019-17571` critical vulnerability is imperative due to its potential for remote code execution, posing a significant security breach risk. Addressing this vulnerability is essential for maintaining compliance and adhering to best security practices.
Being a `“binary compatible, drop-in replacement for log4j version 1.2.17”`, the `reload4j` library used in this fix should not introduce any user-facing changes.
Migrating to `log4j 2.x`, or using the `adapter technique`, would have implied more implementation effort and considerable user-facing …
> [Security] Fix log4j 1.x CVE-2019-17571 critical vulnerability

- dora/shaded/client/pom.xml
- dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLsCommandIntegrationTest.java
Shade all the class under javax
We need this change to fix the maven build error in presto
no
> Fix duplicated class and resources in presto mvn build

- dora/shaded/client/pom.xml
Fix the shading issue for javax security
you might see class not found in javax's security module
no
> Fix the shading issue for javax security

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3Handler.java
Make the buffer size in s3 proxy configurable, which is currently 8KB and unchangeable.
> Make proxy transfer buffer size configurable

- dora/core/common/src/main/java/alluxio/grpc/GrpcUtils.java
- dora/core/common/src/main/java/alluxio/util/webui/NodeInfo.java
- dora/core/common/src/main/java/alluxio/wire/WorkerInfo.java
- dora/core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
- dora/core/common/src/main/java/alluxio/wire/WorkerState.java
- dora/core/common/src/test/java/alluxio/wire/WorkerInfoTest.java
- dora/core/common/src/test/java/alluxio/wire/WorkerNetAddressTest.java
- dora/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- dora/core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
- dora/core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
- dora/core/server/master/src/test/java/alluxio/master/block/meta/MasterWorkerInfoTest.java
- dora/job/common/src/main/java/alluxio/job/MasterWorkerInfo.java
1. Move `WorkerState` enum from master package to the wire package.
2. Add a new worker state `UNRECOGNIZED` and use it as the default state.
3. Make worker state in `WorkerInfo` an enum.
4. Add copy constructors to `WorkerInfo` and `WorkerNetAddress`.
1. Make sure the state of worker can be enumerated.
2. Allow safely copying mutable `WorkerInfo` and `WorkerNetAddress` objects.
No.
> Make WorkerInfo enum (and some small refactors)

- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
- dora/core/server/worker/src/main/java/alluxio/worker/dora/PagedDoraWorker.java
- dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Put back the restriction of reuse worker identity for non-k8s env deployment.
Worker identity gets reused by wrong deployment behaviors such as copy conf/ over for new worker setup, as opposed to k8s deployment is thru operator / automation, bare metal deployment has no way of prevention, thus putting back the restriction for non-k8s deployment.
No.
> Fix to disable worker identity reuse for registration unless in k8s

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpLoadService.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/vo/LoadJobProgressResponseVO.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/vo/LoadJobStopResponseVO.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/vo/LoadJobSubmitResponseVO.java
This PR improves RESTful load api, use JSON format as the response content.
```
// 20231211174310
// http://localhost:28080/v1/load?path=hdfs://node01:8020/testRoot/testDirectory2&opType=submit&verbose=true
{
"success": true,
"jobId": "0dbc0f47-580b-420f-b50e-d08a170746c8",
"path": "hdfs://node01:8020/testRoot/testDirectory2",
"message": "Load 'hdfs://node01:8020/testRoot/testDirectory2' is successfully submitted. JobId: 0dbc0f47-580b-420f-b50e-d08a170746c8\n"
}
```
```
// 20231211180110
// http://localhost:28080/v1/load?path=hdfs://node01:8020/testRoot/testDirectory2&opType=progress&verbose=true
{
"jobState": "RUNNING",
"path": "hdfs://node01:8020/testRoot/testDirectory2",
"message": "Progress for loading path 'hdfs://node01:8020/testRoot/testDirectory2':\n\tSettings:\tbandwidth: …
```
> Improve rest load api response JSON

- dora/integration/fuse/bin/alluxio-fuse
Remove additional white space in alluxio-fuse script
alluxio-fuse unmount <mnt_point> is unable to find the pid of AlluxioFuse process because the grep content isn't correct.
No
> Fix alluxio-fuse script for finding fuse pid

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/PagedService.java
Support get page with RESTful API by specifying offset and length.
PAGE_URL_FORMAT = (
"[http://{worker_host}:{http_port}/v1/file/{path_id}/page/{page_index}?offset=100&length=1024](http://{worker_host}:%7Bhttp_port%7D/v1/file/%7Bpath_id%7D/page/%7Bpage_index%7D?offset=100&length=1024)"
)
> Support get page with RESTful API by specifying offset and length

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/server/master/src/main/java/alluxio/master/throttle/MetricsMonitorUtils.java
- core/server/master/src/main/java/alluxio/master/throttle/ServerIndicator.java
- core/server/master/src/main/java/alluxio/master/throttle/SystemMonitor.java
- core/server/master/src/test/java/alluxio/master/throttle/IndicatorsTests.java
- docs/_data/table/cn/process-metrics.yml
- docs/_data/table/en/process-metrics.yml
Add a metric to record the direct memory usage of Netty.
when high business pressure, there may be OOM issues when using Netty direct memory to transfer data. Adding this metric to monitor the usage of direct memory.
No
> Add the metrics to record the direct memory used by Netty

- docs/en/ufs/HDFS.md
Update the correct kerberos configuration 'alluxio.hadoop.kerberos.keytab.login.autorenewal' in HDFS docs to avoid user confusion.
Fix #18486
> [DOCFIX] Update kerberos configuration 'alluxio.hadoop.kerberos.keytab.login.autorenewal' in HDFS docs

- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3Handler.java
- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- dora/core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
Create metadata directory in initiateMultipartUpload method.
Each request calls the initialization method of the handler and sends an `exists` request to the master, which is unnecessary.
> Create metadata directory in initiateMultipartUpload method

- core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
Reduce talk to master to improve the performance for small file scenario.
I guess this is introduced by  https://github.com/Alluxio/alluxio/commit/ed53d541d16ef1212936d8226b1df64c4478a707
The block info can be get from file status, so we should not ask it from master every time.
No
> Avoid get block info when positioned read for first retry

- dora/core/server/worker/src/main/java/alluxio/worker/s3/S3NettyObjectTask.java
fix the issue of S3 range read. 
there is a bug when setting  S3 range offset.
user can try the following cmd to validate S3 range read.
`aws --endpoint http://localhost:39999/api/v1/s3 s3api get-object --range bytes=10-20 --bucket [bucket-name] --key=[key-name] [output-file]`
> Fix the issue of S3 range read

- dora/stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java
Change to use long type store file size.
Without this PR, we cannot specified a filesize lagger than Integer.MAX_VALUE.
No
> Fix negative size if specified filesize over Integer.MAX_VALUE for stressWorkerBench

- dora/core/common/src/main/java/alluxio/membership/MembershipManager.java
- dora/core/common/src/main/java/alluxio/membership/MembershipType.java
- dora/core/common/src/main/java/alluxio/membership/ServiceRegistryMembershipManager.java
- dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Add etcd membership manager only include active workers
For python client it would need to only look at active worker list 
We only need active workers list in big tech env. If the worker is down, we don't care and just reshard small portion of data to other workers.
na
> Add ServiceRegistry membership manager which only include active workers

- core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java
Current TTL frees a file but the file can be brought back in due to min replication being set. 
This changes that behavior and ensures the file is freed. 
TTL and minreplication can conflict each other, this fixes that and allow TTL to take precedence.
TTL free behavior change
> Set min replication when TTL expires to free a file

- dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
- dora/core/common/src/main/java/alluxio/membership/StaticMembershipManager.java
- dora/core/common/src/main/java/alluxio/membership/WorkerServiceEntity.java
- dora/core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
- dora/core/common/src/test/java/alluxio/membership/ServiceEntityTest.java
- dora/core/common/src/test/java/alluxio/wire/WorkerNetAddressTest.java
- dora/core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
- dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
This PR enables registering the worker's HTTP server's port in the etcd. This helps to find worker's restful APIs from the Python client.
Alluxio Python client (e.g. in ML use cases) needs to connect to the worker's REST APIs. But as the http server port isn't included in the worker's information in the etcd, the client fails to find the API endpoint.
No.
> Add http server port in the worker net address

- dora/tests/integration/src/test/java/alluxio/client/cli/fs/command/DoraLoadCommandIntegrationTest.java
Fix DoraLoadCommandIntegrationTest.
Without this PR, DoraLoadCommandIntegrationTest may fail with the following exception
```
[ERROR] alluxio.client.cli.fs.command.DoraLoadCommandIntegrationTest.testCommand  Time elapsed: 7.995 s  <<< FAILURE!
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at alluxio.client.cli.fs.command.DoraLoadCommandIntegrationTest.testCommand(DoraLoadCommandIntegrationTest.java:107)
```
The cause is that
- The second job is using the same path as the first job
- While submitting the second job, the second job is still in "cleaning" state. As the following log shows
```
2024-01-31 09:52:33,057 [master-rpc-executor-TPE-thread-494] WARN  scheduler.Scheduler …
```
> Fix DoraLoadCommandIntegrationTest

- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpRequestUri.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/PagedService.java
- dora/core/server/worker/src/test/java/alluxio/worker/http/TestHttpRequestUtil.java
Fix the bug that the get page RESTful API doesn't support nullable offset and length.
> Support nullable offset and length in get page RESTful API

- core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- tests/src/test/java/alluxio/client/fs/DirectAccessIntegrationTest.java
Previously direct access is a list of paths, and makes it very difficult to specify. 
Ease of use
alluxio.user.file.direct.access is now a regex indicating the paths that should be direct access
> Add Regex support to direct access

- docs/en/compute/Presto-Iceberg.md
Fix broken link in Presto-Iceberg.md due to link being split by a newline
> [DOCFIX] Fix link in Presto-Iceberg

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java
- dora/core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStore.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/store/LocalPageStoreTest.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/store/MemoryPageStoreTest.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreTest.java
- dora/core/common/src/main/java/alluxio/exception/PageCorruptedException.java
Throw a PageCorruptedException when the length of page inconsistent with the metadata
Do our best efforts to delete the corrupted page file
Reset the offset of buffer when we found the data has been corrupted to avoid ArrayOutOfBound exception. 
We found the cache make presto keep failing when some of the page file got corrupted
No
> Improve the local cache fallback behavior for corrupted pages

- cli/src/alluxio.org/cli/cmd/process/process.go
- cli/src/alluxio.org/cli/cmd/process/remove_worker.go
- dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
- dora/core/common/src/main/java/alluxio/wire/WorkerIdentity.java
- dora/core/common/src/test/java/alluxio/wire/WorkerIdentityTest.java
- dora/shell/src/main/java/alluxio/cli/fsadmin/command/NodesCommand.java
- dora/shell/src/main/java/alluxio/cli/fsadmin/nodes/RemoveWorkerCommand.java
- dora/tests/integration/src/test/java/alluxio/client/cli/fsadmin/command/NodesCommandIntegrationTest.java
- dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
Add decommission capability for worker and removenode cli cmd to remove node from etcd registration
to add decommission capability for worker
New cli added for remove worker node
> Add decommission capability and removenode cmd

- core/server/worker/src/main/java/alluxio/worker/block/CacheRequestManager.java
- core/server/worker/src/main/java/alluxio/worker/block/MonoBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
- tests/src/test/java/alluxio/client/fs/TtlIntegrationTest.java
This fix a bug in corrupted data files.
Previously, https://github.com/Alluxio/alluxio/pull/17497 attempt to solve this issue but only covers the case when creating a UFS reader
Notice we only handle block reader. So this may not fix paged Block Reader in 2.x
If you propose a new API, clarify the use case for a new API.
If you fix a bug, describe the bug.
change in user-facing APIs
addition or removal of property keys
[This is an auto-generated PR to cherry-pick committed PR https://github.com/Alluxio/alluxio/pull/18525 into branch …
> Fix data corruption, Port [#18525] to branch-2.10

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RequestServlet.java
- core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
Support the global rate limiter in Proxy V2, and add the configuration for async context timeout.
Support the configuration of async context timeout, which can avoid frequent timeouts of asynchronous requests caused by too short timeouts.
No
> Add global ratelimiter and make async timeout configurable in Proxy V2

- dora/core/common/src/main/java/alluxio/util/CommonUtils.java
Alluxio doesn't work with early-access (EA) JDKs which makes it hard to do some forward-testing before new JDK is released.
3. webui
> Support running on early-access JDK

- dora/core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
- dora/core/common/src/main/java/alluxio/conf/PropertyKey.java
- dora/core/common/src/main/java/alluxio/membership/AlluxioEtcdClient.java
- dora/core/common/src/main/java/alluxio/membership/EtcdMembershipManager.java
- dora/core/common/src/main/java/alluxio/membership/ServiceDiscoveryRecipe.java
- dora/core/common/src/main/java/alluxio/membership/ServiceRegistryMembershipManager.java
- dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
1. catch all exception thrown by fetch worker cluster view from etcd …when refresh the workers view instead of propagate throwing all the way to the caller
2. make worker failure detection timeout (the timeout to determine if a worker is in FAILED state) configurable thru setting the service discovery entity's lease ttl
3. make newLeaseInternal always overwrite the key with the newly created lease
To resolve:
1) currently worker is considered down only 2sec after its disconnection with etcd, its too small, make the failure detection timeout configurable for registered service discovery services.
2) etcd unavaible runtime exception will be propagated to caller which is non-ideal, currently capture at FileSystemContext.getCachedWorkers layer to prevent propagating to IO layer, causing an …
> Fix etcd calls exception handling and adjust failure detection timeout

- dora/core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
When a old worker is down for couple days and up again with old data, the metrics Client.CachePagesAges would show high page age which exceed the ttl. And this violates the regulation.
This is caused by: 
1. we are not deleting old files when restoring local cache, and old data may still be able to serve users. 
2. when we are not able to run invalidate scheduled tasks when we are in restore state(initialDelay = 0).
In the meanwhile, fix a metrics calculation: CLIENT_CACHE_PAGES_INVALIDATED
bug fix
na
> Fix local cache ttl

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3Handler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ObjectTask.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
When requesting a smaller range from the S3 proxy, support the S3 proxy in using the position read API to request data from the worker.
add a new property:
```
alluxio.proxy.s3.use.position.read.range.size
```
Using position read can effectively solve the issue of reading amplification.
1. If you propose a new API, clarify the use case for a new API. no
2. If you fix a bug, describe the bug. no
1. change in user-facing APIs no
2. addition or removal of property keys yes
3. webui no
> Add position read supports for s3 proxy

- core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
Cherry pick https://github.com/Alluxio/alluxio/pull/17234 to branch-2.10
mentioned in #16629 
The `Cluster.ActiveRpcReadCount` metric could get an impossible value like a negative number. The main reason is that the request handling doesn't cover all situations.
Nope
> Fix the active rpc metrics; Port [#17234] to branch-2.10

- conf/log4j.properties
Removes log entries such as `2024-02-13 17:07:02,337 WARN  InstanceMetadataServiceResourceFetcher - Fail to retrieve token` in a similar fashion as https://github.com/Alluxio/alluxio/pull/13736
> Remove noisy logging in InstanceMetadataServiceResourceFetcher

- dora/core/server/worker/src/main/java/alluxio/worker/dora/RocksDBDoraMetaStore.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/RocksDBDoraMetaStoreTest.java
Modified the logic of Alluxio clearing expired metadata.
The expiration time of RocksDB is set so that expired metadata can be cleared in time every time RocksDB performs a compaction operation.
Alluxio has a problem that expired metadata cannot be cleared in time, which may lead to insufficient disk space in the long run.
We have modified the logic for clearing expired metadata to ensure that if the user sets an appropriate metadata expiration time, the disk will not continue to accumulate metadata that cannot be cleared.
None
> Update the logic of Alluxio clearing expired metadata

- core/common/src/main/java/alluxio/metrics/MetricKey.java
- core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
- core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSyncHelper.java
- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/io/MetricAccountingBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/page/PagedUfsBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/page/UfsBlockReadOptions.java
- core/server/worker/src/test/java/alluxio/worker/page/PagedBlockReaderTest.java
Please outline the changes and how this PR fixes the issue. modify the calculation method for cacheMissPercentage metric, ensuring it comprehensively accounts for the influence of job worker read operations. #16945
Because of the incorrect calculation results of this metric, it may produce exception value.
No
pr-link: Alluxio/alluxio#18208
change-id: cid-d24a6f324f7148cab4a30fbbf819510a1a314ebc
> Fix cacheMissPercentage metric; Port [#18208] to branch-2.10 

- core/server/worker/src/main/java/alluxio/worker/block/io/MetricAccountingBlockReader.java
generalize the constructor input of MetricAccountingBlockReader to count metrics for any implementation of BlockReader
> Allow MetricAccountingBlockReader to accept any BlockReader

- dora/core/common/src/main/java/alluxio/metrics/MetricKey.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/HttpServerHandler.java
- dora/core/server/worker/src/main/java/alluxio/worker/http/PagedService.java
Add HTTP getPage cache hit ratio. This is used for mimicing how much data read from alluxio cache and how much data possibly fallback to UFS given that no that much user get metrics from alluxiofs client.
To get cache hit ratio of worker http server get page
Yes, add some metrics
> Add http getPage cache hit ratio

- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
if the request ends with "/" and the object is a file, return 404
if the user want to get the metadata of a file, it should not end with "/". if the user wants to get the metadata of a dir, then it should end with "/".
no
> Return 404 when head the file end with slash

- docs/en/operation/User-CLI.md
There are known limitations in using the `fs distributedCp` command; explicitly call them out in the docs, ex. https://docs.alluxio.io/ee-da/user/stable/en/operation/User-CLI.html#distributedcp
> [DOCFIX] Add warning for distributedCp limitations

- core/common/src/main/java/alluxio/retry/CountingRetry.java
- core/common/src/main/java/alluxio/retry/ExponentialBackoffRetry.java
- core/common/src/main/java/alluxio/retry/ExponentialTimeBoundedRetry.java
- core/common/src/main/java/alluxio/retry/RetryPolicy.java
- core/common/src/main/java/alluxio/retry/SleepingRetry.java
- core/common/src/main/java/alluxio/retry/TimeBoundedRetry.java
- core/common/src/main/java/alluxio/retry/TimeoutRetry.java
- underfs/cos/src/main/java/alluxio/underfs/cos/COSInputStream.java
- underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoInputStream.java
- underfs/obs/src/main/java/alluxio/underfs/obs/OBSInputStream.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSInputStream.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftInputStream.java
Add the copy() for RetryPolicy, so it can be used in some situations where the RetryPolicy needs to be reused.
For OSSInputStream or other stream, it needs to call createStream() more than once in some cases, it should not use the same RetryPolicy instance in multiple different calls of createStream().
None
> Fix read exception when the range size is smaller than Block size

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/common/src/test/java/alluxio/metrics/MetricsSystemTest.java
> Update metric system with cherry-pick `Remove hostname from metrics key`

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/underfs/ObjectLowLevelOutputStream.java
- underfs/tos/src/main/java/alluxio/underfs/tos/TOSLowLevelOutputStream.java
- underfs/tos/src/main/java/alluxio/underfs/tos/TOSUnderFileSystem.java
I have completed the task of implementing multipart upload in TOS (Tachyon Object Storage). Users can now choose whether to enable multipart upload through the configuration file.
1、Users need to choose multipart upload for large files exceeding 5GB.
2、Users can customize whether to use multipart upload for smaller files and also define the size of each part for multipart upload.
Several new property keys have been added, which require users to specify the TOS configuration.
> Support MultiPartUpload in Tos

- core/common/src/main/java/alluxio/util/CommonUtils.java
- core/common/src/test/java/alluxio/util/CommonUtilsTest.java
Right now Alluxio 2.x is not starting correctly on early access/beta JDKs. It's required to do a proper forward testing of new JDK releases.
3. webui
> Allow running on early access and beta JDKs

- pom.xml
Downgrade the version of AWS SDK to 2.15.79
The current AWS SDK version 2.16.104 depends on Netty 4.1.63-Final, and Alluxio depends on Netty 4.1.52-Final. There is a conflict between the two versions that causes Netty's native epoll library to fail to be loaded. Consequently, the data server on a worker cannot be started on a domain socket which requires epoll, and thus short circuit read cannot be enabled in a Kubernetes deployment.
No.
> Downgrade AWS SDK to 2.15.79

- core/server/master/src/main/java/alluxio/master/file/meta/UfsSyncPathCache.java
- core/server/master/src/test/java/alluxio/master/file/meta/InvalidationSyncCacheTest.java
Disable the onCacheEviction Handler.
To fix a potential cache eviction recursion issue.
No.
> Disable invalidation time

- dora/tests/testcontainers/src/test/java/alluxio/membership/MembershipManagerTest.java
- pom.xml
add back netty dependency within grpc
previously we exclude netty dependency since we already have netty-all outside https://github.com/Alluxio/alluxio/pull/9942
But due to https://github.com/grpc/grpc-java/issues/11284, we sometimes have incompatibility between grpc and netty, and it's better to use shaded netty within grpc so we can be sure that they are compatible.
na
> Add back shaded netty within grpc

- integration/docker/Dockerfile
Using Rocky8 as base image
Centos7 EOL on June 30, 2024 so mirrorlist.centos.org no longer exists for yum installs
no
> Update Dockerfile to use Rocky8 as base image 

- underfs/tos/src/test/java/alluxio/underfs/tos/TOSInputStreamTest.java
- underfs/tos/src/test/java/alluxio/underfs/tos/TOSLowLevelOutputStreamTest.java
- underfs/tos/src/test/java/alluxio/underfs/tos/TOSOutputStreamTest.java
- underfs/tos/src/test/java/alluxio/underfs/tos/TOSUnderFileSystemFactoryTest.java
- underfs/tos/src/test/java/alluxio/underfs/tos/TOSUnderFileSystemTest.java
I have created some unit tests for TOS.
1、Because it can help us check our code.
No.
> Support Unit Tests for TOS

- core/common/src/main/java/alluxio/conf/PropertyKey.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Rename property key alluxio.underfs.s3.threads.max to alluxio.underfs.s3.connections.max and bump the default number to 1024
The property `alluxio.underfs.s3.threads.max` has a misleading name, as it actually represents the size of a connection pool rather than the max number of threads. Consequently, the value of this property is typically much larger (e.g., Trino uses 256 for the equivalent property to ensure sufficient bandwidth when reading from S3).
However, including "threads" in the name causes some users to worry, as they believe it should be calculated based on the number of vCores (as we found in one PoC that users were unwilling to set this value large) .
This commit changes the name but retains the original property name as an alias to maintain backward compatibility.
Yes but …
> Rename property key alluxio.underfs.s3.threads.max

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
- core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
- core/common/src/main/java/alluxio/Constants.java
- core/common/src/main/java/alluxio/conf/PropertyKey.java
- core/common/src/main/java/alluxio/network/protocol/databuffer/NioHeapBufferPool.java
- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- core/common/src/main/java/alluxio/util/CRC64.java
- core/common/src/main/java/alluxio/wire/FileInfo.java
- core/common/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/master/src/main/java/alluxio/master/AlluxioMaster.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java
- core/transport/src/main/proto/grpc/block_worker.proto
- core/transport/src/main/proto/grpc/file_system_master.proto
- core/transport/src/main/proto/proto.lock
- pom.xml
- shell/src/main/java/alluxio/cli/fs/command/CRC64CheckCommand.java
- shell/src/main/java/alluxio/cli/fs/command/CRC64CheckCommandUtils.java
- underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
To check the file integrity
Add a crc64 check cli
> Add CRC64 checksum check

- core/common/src/main/java/alluxio/Sessions.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
> Release BlockReader in CRC check

- dora/core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
- dora/core/server/worker/src/test/java/alluxio/worker/dora/PagedDoraWorkerTest.java
> Update cache manager prefix search test
