Alluxio/alluxio

- shell/src/main/java/tachyon/shell/TfsShellUtils.java
- shell/src/main/java/tachyon/shell/command/AbstractLsCommand.java
- shell/src/main/java/tachyon/shell/command/AbstractTfsShellCommand.java
- shell/src/main/java/tachyon/shell/command/CommandUtils.java
- shell/src/main/java/tachyon/shell/command/CopyFromLocalCommand.java
- shell/src/main/java/tachyon/shell/command/CopyToLocalCommand.java
- shell/src/main/java/tachyon/shell/command/DuCommand.java
- shell/src/main/java/tachyon/shell/command/GetCapacityBytesCommand.java
- shell/src/main/java/tachyon/shell/command/GetUsedBytesCommand.java
- shell/src/main/java/tachyon/shell/command/LoadCommand.java
- shell/src/main/java/tachyon/shell/command/PersistCommand.java
- shell/src/main/java/tachyon/shell/command/TfsShellCommand.java
> [TACHYON-935] Added the usage of links in the documentation for the tachyon-shell module

- servers/src/main/java/tachyon/worker/block/BlockDataManager.java
- servers/src/main/java/tachyon/worker/block/BlockLockManager.java
- servers/src/main/java/tachyon/worker/block/BlockMasterSync.java
- servers/src/main/java/tachyon/worker/block/BlockMetadataManager.java
- servers/src/main/java/tachyon/worker/block/BlockMetadataManagerView.java
- servers/src/main/java/tachyon/worker/block/BlockStore.java
- servers/src/main/java/tachyon/worker/block/BlockStoreLocation.java
- servers/src/main/java/tachyon/worker/block/BlockWorker.java
- servers/src/main/java/tachyon/worker/block/PinListSync.java
- servers/src/main/java/tachyon/worker/block/TieredBlockStore.java
> [TACHYON-935] Added the usage of links in the documentation in the tachyon.worker.block package

- integration/yarn/pom.xml
- integration/yarn/src/main/java/tachyon/yarn/ApplicationMaster.java
- integration/yarn/src/test/java/tachyon/yarn/ApplicationMasterTest.java
https://tachyon.atlassian.net/browse/TACHYON-1403
> [TACHYON-1403] Add unit tests for ApplicationMaster

- underfs/glusterfs/src/test/java/tachyon/underfs/glusterfs/GlusterFSUnderFileSystemFactoryTest.java
- underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystemFactory.java
- underfs/local/src/main/java/tachyon/underfs/local/LocalUnderFileSystem.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3InputStream.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3OutputStream.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3UnderFileSystem.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3UnderFileSystemFactory.java
- underfs/s3/src/test/java/tachyon/underfs/s3/S3UnderFileSystemTest.java
- underfs/swift/src/main/java/tachyon/underfs/swift/SwiftUnderFileSystem.java
> [TACHYON-935] Added the usage of links in the documentation for the tachyon-unserfs module

- servers/src/main/java/tachyon/master/TachyonMaster.java
https://tachyon.atlassian.net/browse/TACHYON-1292
> [TACHYON-1292] Private constructor for the Factory class.

- servers/src/main/java/tachyon/MasterStorageTierAssoc.java
- servers/src/main/java/tachyon/StorageTierAssoc.java
- servers/src/main/java/tachyon/ValidateConf.java
- servers/src/main/java/tachyon/WorkerStorageTierAssoc.java
- servers/src/main/java/tachyon/worker/WorkerContext.java
- servers/src/main/java/tachyon/worker/netty/DataServerHandler.java
> [TACHYON-935] Added the usage of links in the documentation for the remaining classes of the tachyon-servers module

- docs/Command-Line-Interface.md
- shell/src/main/java/tachyon/shell/TfsShell.java
https://tachyon.atlassian.net/browse/TACHYON-1407
> [TACHYON-1407] Remove old shell command request

- docs/Contributing-to-Tachyon.md
> [DOCFIX] Add description of DOCFIX PRs

- servers/src/main/java/tachyon/metrics/MetricsConfig.java
- servers/src/main/java/tachyon/metrics/MetricsSystem.java
- servers/src/main/java/tachyon/metrics/sink/ConsoleSink.java
- servers/src/main/java/tachyon/metrics/sink/CsvSink.java
- servers/src/main/java/tachyon/metrics/sink/GraphiteSink.java
- servers/src/main/java/tachyon/metrics/sink/JmxSink.java
- servers/src/main/java/tachyon/metrics/sink/MetricsServlet.java
- servers/src/main/java/tachyon/metrics/source/Source.java
- servers/src/main/java/tachyon/web/WebInterfaceBrowseLogsServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceBrowseServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceConfigurationServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceDownloadLocalServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceDownloadServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceGeneralServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceHeaderServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceMemoryServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceWorkerBlockInfoServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceWorkerGeneralServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceWorkersServlet.java
> [TACHYON-935] Added the usage of links in the documentation in the tachyon.metrics and tachyon.web packages

- common/src/main/java/tachyon/exception/ExceptionMessage.java
- integration/yarn/src/main/java/tachyon/yarn/ApplicationMaster.java
- integration/yarn/src/main/java/tachyon/yarn/Client.java
- integration/yarn/src/main/java/tachyon/yarn/YarnUtils.java
- integration/yarn/src/test/java/tachyon/yarn/ApplicationMasterTest.java
https://tachyon.atlassian.net/browse/TACHYON-1406
> [TACHYON-1406] Avoid allocating multiple workers on the same host

- servers/src/main/java/tachyon/web/WebInterfaceWorkerBlockInfoServlet.java
https://tachyon.atlassian.net/browse/TACHYON-1431
"orderedTierAliases" needs to be set even when the offset and limit aren't specified.
> [TACHYON-1431] Fix NPE in BlockInfo tab

- docs/Developer-Tips.md
https://tachyon.atlassian.net/browse/TACHYON-1433
> [TACHYON-1433] Add docs for generating thrift and protobuf Java code

- clients/unshaded/src/main/java/tachyon/client/file/FileInStream.java
https://tachyon.atlassian.net/browse/TACHYON-1434
> [TACHYON-1434] Changed FileInStream to be not final

- integration-tests/src/test/java/tachyon/client/TachyonFileSystemIntegrationTest.java
https://tachyon.atlassian.net/browse/TACHYON-1435
> [TACHYON-1435] Fix build - UNDERFS_ADDRESS is a URI, not a Path

- shell/src/main/resources/tfs.man
https://tachyon.atlassian.net/browse/TACHYON-1396
> [TACHYON-1396] Added a man file for the TFS shell

- integration-tests/src/test/java/tachyon/underfs/UnderStorageSystemInterfaceIntegrationTest.java
- underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystem.java
https://tachyon.atlassian.net/browse/TACHYON-1436
> [TACHYON-1436] Fix listRecursive to work with hdfs

- clients/unshaded/src/test/java/tachyon/client/lineage/options/GetLineageInfoListOptionsTest.java
[TACHYON-1359] Add unit tests for GetLineageInfoListOptions
> [TACHYON-1359] Add unit tests for GetLineageInfoListOptions

- build/checkstyle/tachyon_checks.xml
- common/src/main/java/tachyon/collections/DirectedAcyclicGraph.java
- common/src/main/java/tachyon/collections/DirectedAcyclicGraphNode.java
- common/src/main/java/tachyon/collections/IndexedSet.java
- common/src/main/java/tachyon/collections/PrefixList.java
I already added the rule, but left it commented out to not break the build. Will add the appropriate documentation before bringing it in.
> [TACHYON-1428] Started to document the tachyon.collections package in preparation for the checkstyle rule

- clients/unshaded/src/main/java/tachyon/client/ClientContext.java
- clients/unshaded/src/main/java/tachyon/client/Utils.java
- clients/unshaded/src/main/java/tachyon/client/block/BlockStoreContext.java
- clients/unshaded/src/main/java/tachyon/client/block/BlockWorkerClientPool.java
- clients/unshaded/src/main/java/tachyon/client/file/FileOutStream.java
https://tachyon.atlassian.net/browse/TACHYON-1446
> [TACHYON-1446] Make a client Utils class

- common/src/main/java/tachyon/conf/TachyonConf.java
- common/src/main/java/tachyon/exception/BlockAlreadyExistsException.java
- common/src/main/java/tachyon/exception/BlockDoesNotExistException.java
- common/src/main/java/tachyon/exception/BlockInfoException.java
- common/src/main/java/tachyon/exception/ConnectionFailedException.java
- common/src/main/java/tachyon/exception/DependencyDoesNotExistException.java
- common/src/main/java/tachyon/exception/DirectoryNotEmptyException.java
- common/src/main/java/tachyon/exception/ExceptionMessage.java
- common/src/main/java/tachyon/exception/FailedToCheckpointException.java
- common/src/main/java/tachyon/exception/FileAlreadyCompletedException.java
> [TACHYON-1428] Started to document the tachyon.conf and tachyon.exception packages in preparation for the checkstyle rule

- common/src/main/java/tachyon/exception/FileAlreadyExistsException.java
- common/src/main/java/tachyon/exception/FileDoesNotExistException.java
- common/src/main/java/tachyon/exception/InvalidFileSizeException.java
- common/src/main/java/tachyon/exception/InvalidPathException.java
- common/src/main/java/tachyon/exception/InvalidWorkerStateException.java
- common/src/main/java/tachyon/exception/LineageDeletionException.java
- common/src/main/java/tachyon/exception/LineageDoesNotExistException.java
- common/src/main/java/tachyon/exception/NoWorkerException.java
- common/src/main/java/tachyon/exception/TableColumnException.java
- common/src/main/java/tachyon/exception/TableDoesNotExistException.java
> [TACHYON-1428] Started to document the tachyon.exception package in preparation for the checkstyle rule

- integration/bin/tachyon-application-master.sh
- integration/yarn/src/main/java/tachyon/yarn/Client.java
https://tachyon.atlassian.net/browse/TACHYON-1441
> [TACHYON-1441] Run ApplicationMaster from a script

- common/src/main/java/tachyon/LeaderInquireClient.java
- common/src/main/java/tachyon/LeaderSelectorClient.java
- common/src/main/java/tachyon/exception/TableMetadataException.java
- common/src/main/java/tachyon/exception/TachyonException.java
- common/src/main/java/tachyon/exception/TachyonExceptionType.java
- common/src/main/java/tachyon/exception/WorkerOutOfSpaceException.java
- common/src/main/java/tachyon/job/CommandLineJob.java
- common/src/main/java/tachyon/job/JobConf.java
- common/src/main/java/tachyon/network/protocol/EncodedMessage.java
- common/src/main/java/tachyon/network/protocol/databuffer/DataNettyBuffer.java
> [TACHYON-1428] Started to document the tachyon packages in preparation for the checkstyle rule

- docs/Configuration-Settings.md
Now we have five categories of configuration properties (add 'Cluster Management').
> [SMALLFIX] Fix the inconsistent description in Configuration-Settings.md

- bin/tachyon-start.sh
- integration/bin/tachyon-mesos.sh
this is useful when running under cluster managers etc.
This PR superceeds #2159
> [TACHYON-1346] optionally wait for process to finish/die

- common/src/main/java/tachyon/network/protocol/RPCBlockReadRequest.java
- common/src/main/java/tachyon/network/protocol/RPCBlockReadResponse.java
- common/src/main/java/tachyon/network/protocol/RPCBlockWriteRequest.java
- common/src/main/java/tachyon/network/protocol/RPCBlockWriteResponse.java
- common/src/main/java/tachyon/network/protocol/RPCErrorResponse.java
- common/src/main/java/tachyon/network/protocol/RPCMessage.java
- common/src/main/java/tachyon/network/protocol/RPCRequest.java
- common/src/main/java/tachyon/network/protocol/RPCResponse.java
> [TACHYON-1428] Documented the tachyon.network.protocol package in preparation for the checkstyle rule

- common/src/main/java/tachyon/replay/ReplayCache.java
- common/src/main/java/tachyon/retry/ExponentialBackoffRetry.java
- common/src/main/java/tachyon/security/authentication/AuthenticationProvider.java
- common/src/main/java/tachyon/security/authentication/AuthenticationUtils.java
- common/src/main/java/tachyon/security/authentication/CustomAuthenticationProviderImpl.java
- common/src/main/java/tachyon/security/authentication/PlainSaslServer.java
- common/src/main/java/tachyon/security/authentication/PlainSaslServerProvider.java
- common/src/main/java/tachyon/security/authentication/PlainSaslUtils.java
- common/src/main/java/tachyon/security/authorization/FileSystemPermission.java
- common/src/main/java/tachyon/security/authorization/PermissionStatus.java
> [TACHYON-1428] Documented the tachyon.replay, tachyon.retry and tachyon.security packages in preparation for the checkstyle rule

- common/src/main/java/tachyon/heartbeat/HeartbeatContext.java
- common/src/test/java/tachyon/heartbeat/HeartbeatContextTest.java
- servers/src/main/java/tachyon/worker/block/BlockWorker.java
- servers/src/main/java/tachyon/worker/block/PinListSync.java
Please reivew:
https://tachyon.atlassian.net/browse/TACHYON-1412
> [TACHYON-1412] Refactor PinListSync to implement HeartbeatExecutor

- common/src/main/java/tachyon/TachyonURI.java
- common/src/main/java/tachyon/security/User.java
- common/src/main/java/tachyon/security/login/AppLoginModule.java
- common/src/main/java/tachyon/security/login/TachyonLoginModule.java
- common/src/main/java/tachyon/underfs/UnderFileSystem.java
- common/src/main/java/tachyon/underfs/UnderFileSystemFactory.java
- common/src/main/java/tachyon/underfs/UnderFileSystemRegistry.java
- common/src/main/java/tachyon/util/CommonUtils.java
- common/src/main/java/tachyon/util/FormatUtils.java
- common/src/main/java/tachyon/util/IdUtils.java
> [TACHYON-1428] Documented the tachyon.security, tachyon.underfs and tachyon.util packages in preparation for the checkstyle rule

- common/src/test/java/tachyon/TachyonURITest.java
- common/src/test/java/tachyon/underfs/UnderFileSystemTest.java
- common/src/test/java/tachyon/util/CommonUtilsTest.java
- common/src/test/java/tachyon/util/FormatUtilsTest.java
- common/src/test/java/tachyon/util/io/BufferUtilsTest.java
- common/src/test/java/tachyon/util/io/FileUtilsTest.java
- common/src/test/java/tachyon/util/io/PathUtilsTest.java
- common/src/test/java/tachyon/util/network/GetMasterWorkerAddressTest.java
- common/src/test/java/tachyon/util/network/NetworkAddressUtilsTest.java
> [TACHYON-1428] Documented the tests in the tachyon package in preparation for the checkstyle rule

- common/src/main/java/tachyon/Version.java
- common/src/main/java/tachyon/network/protocol/RPCBlockReadRequest.java
- common/src/main/java/tachyon/util/LineageUtils.java
- common/src/main/java/tachyon/util/ThreadFactoryUtils.java
- common/src/main/java/tachyon/util/io/BufferUtils.java
- common/src/main/java/tachyon/util/io/PathUtils.java
- common/src/main/java/tachyon/util/network/NettyUtils.java
- common/src/main/java/tachyon/util/network/NetworkAddressUtils.java
- common/src/main/java/tachyon/worker/ClientMetrics.java
- common/src/main/java/tachyon/worker/DataServerMessage.java
> [TACHYON-1428] Documented the tachyon package in preparation for the checkstyle rule

- clients/unshaded/src/test/java/tachyon/hadoop/TFSTest.java
https://tachyon.atlassian.net/browse/TACHYON-1384
http://stackoverflow.com/questions/32660836/java-lang-linkageerror-loader-constraint-violation-in-interface-itable-initiali
> [TACHYON-1384] fix TFS test with CDH

- common/src/main/java/tachyon/Constants.java
- common/src/main/resources/tachyon-default.properties
- servers/src/main/java/tachyon/master/file/meta/InodeTree.java
- servers/src/main/java/tachyon/master/permission/FileSystemPermissionChecker.java
- servers/src/test/java/tachyon/master/file/meta/InodeTreeTest.java
- servers/src/test/java/tachyon/master/permission/FileSystemPermissionCheckerTest.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-1415
Add configuration properties and an almost empty class `FileSystemPermissionChecker` to use it. The check method impl will be in TACHYON-1416.
@apc999 , @sundapeng
> [TACHYON-1415] Check - Add configuration properties for permission check usage

- common/src/test/java/tachyon/security/LoginUserTest.java
- common/src/test/java/tachyon/security/authentication/AuthenticationUtilsTest.java
- common/src/test/java/tachyon/security/authentication/CustomAuthenticationProviderImplTest.java
- common/src/test/java/tachyon/security/authentication/PlainClientCallbackHandlerTest.java
- common/src/test/java/tachyon/security/authentication/PlainSaslServerProviderTest.java
- common/src/test/java/tachyon/security/authentication/PlainSaslServerTest.java
- common/src/test/java/tachyon/security/authentication/PlainServerCallbackHandlerTest.java
- common/src/test/java/tachyon/security/authentication/SimpleAuthenticationProviderImplTest.java
- common/src/test/java/tachyon/security/authorization/FileSystemActionTest.java
- common/src/test/java/tachyon/security/authorization/FileSystemPermissionTest.java
- common/src/test/java/tachyon/security/authorization/PermissionStatusTest.java
- common/src/test/java/tachyon/security/login/LoginModuleTest.java
> [TACHYON-1428] Documented the tests in the tachyon.security package in preparation for the checkstyle rule

- integration/yarn/src/main/java/tachyon/yarn/Client.java
- integration/yarn/src/test/java/tachyon/yarn/ApplicationMasterTest.java
This fixes the developer build
> [SMALLFIX] Fix ApplicationMasterTest style

- common/src/test/java/tachyon/util/ShellUtilsTest.java
https://tachyon.atlassian.net/browse/TACHYON-1468
> [TACHYON-1468] Fix shell utils test on OSX

- deploy/vagrant/conf/tachyon.yml
> [SMALLFIX] Update the deploy module release versions to the latest releases.

- deploy/vagrant/core/EnvSetup.rb
https://tachyon.atlassian.net/browse/TACHYON-1467
> [TACHYON-1467] Support cdh5 in deploy module

- underfs/swift/src/main/java/tachyon/underfs/swift/SwiftUnderFileSystem.java
- underfs/swift/src/main/java/tachyon/underfs/swift/SwiftUnderFileSystemFactory.java
- underfs/swift/src/main/java/tachyon/underfs/swift/SwiftUnderFileSystemUtils.java
- underfs/swift/src/test/java/tachyon/underfs/swift/SwiftUnderFileSystemTest.java
> [TACHYON-1428] Documented the Swift Under FS package in preparation for the checkstyle rule

- common/src/test/java/tachyon/master/block/BlockIdTest.java
- underfs/glusterfs/src/main/java/tachyon/underfs/glusterfs/GlusterFSUnderFileSystem.java
- underfs/glusterfs/src/main/java/tachyon/underfs/glusterfs/GlusterFSUnderFileSystemFactory.java
- underfs/glusterfs/src/test/java/tachyon/underfs/glusterfs/GlusterFSUnderFileSystemFactoryTest.java
- underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystemUtils.java
- underfs/hdfs/src/test/java/tachyon/underfs/hdfs/HdfsUnderFileSystemFactoryTest.java
- underfs/hdfs/src/test/java/tachyon/underfs/hdfs/HdfsUnderFileSystemUtilsTest.java
- underfs/local/src/main/java/tachyon/underfs/local/LocalUnderFileSystem.java
- underfs/local/src/test/java/tachyon/underfs/local/LocalUnderFileSystemFactoryTest.java
> [TACHYON-1428] Documented some of the Under FS packages in preparation for the checkstyle rule

- build/checkstyle/tachyon_checks.xml
- underfs/s3/src/main/java/tachyon/underfs/s3/S3OutputStream.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3UnderFileSystem.java
- underfs/s3/src/test/java/tachyon/underfs/s3/S3UnderFileSystemFactoryTest.java
- underfs/s3/src/test/java/tachyon/underfs/s3/S3UnderFileSystemTest.java
> [TACHYON-1428] Documented the S3 under FS package in preparation for the checkstyle rule

- build/checkstyle/tachyon_checks.xml
- clients/unshaded/src/main/java/tachyon/client/BoundedStream.java
- clients/unshaded/src/main/java/tachyon/client/ClientContext.java
- clients/unshaded/src/main/java/tachyon/client/block/BufferedBlockOutStream.java
- clients/unshaded/src/main/java/tachyon/client/block/LocalBlockInStream.java
- clients/unshaded/src/main/java/tachyon/client/block/TachyonBlockStore.java
- clients/unshaded/src/main/java/tachyon/client/file/FileSystemMasterClient.java
- clients/unshaded/src/main/java/tachyon/client/file/options/CompleteFileOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/CreateOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/DeleteOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/FreeOptions.java
> [TACHYON-1428] Documented parts of the tachyon-client package in preparation for the checkstyle rule

- clients/unshaded/src/main/java/tachyon/client/file/options/GetInfoOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/InStreamOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/ListStatusOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/LoadMetadataOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/MkdirOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/MountOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/OpenOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/OptionsBuilder.java
- clients/unshaded/src/main/java/tachyon/client/file/options/OutStreamOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/RenameOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/SetStateOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/UnmountOptions.java
> [TACHYON-1428] Documented parts of the tachyon.client.file.options package in preparation for the checkstyle rule

- clients/unshaded/src/test/java/tachyon/client/file/options/InStreamOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/ListStatusOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/LoadMetadataOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/MkdirOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/MountOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/OpenOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/OutStreamOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/RenameOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/SetStateOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/UnmountOptionsTest.java
> [TACHYON-1428] Documented parts of the tests of the tachyon.client.file.options package in preparation for the checkstyle

- servers/src/test/java/tachyon/master/lineage/checkpoint/CheckpointLatestPlannerTest.java
https://tachyon.atlassian.net/browse/TACHYON-1471
> [TACHYON-1471] Fix flaky schduleTest

- clients/unshaded/src/test/java/tachyon/client/lineage/LineageContextTest.java
- clients/unshaded/src/test/java/tachyon/client/lineage/LineageMasterClientTest.java
- clients/unshaded/src/test/java/tachyon/client/lineage/options/GetLineageInfoListOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/netty/ClientHandlerTest.java
- clients/unshaded/src/test/java/tachyon/client/table/RawTableContextTest.java
- clients/unshaded/src/test/java/tachyon/client/table/RawTableMasterClientTest.java
- clients/unshaded/src/test/java/tachyon/client/util/ClientMockUtils.java
- clients/unshaded/src/test/java/tachyon/client/util/ClientTestUtils.java
- clients/unshaded/src/test/java/tachyon/hadoop/ConfUtilsTest.java
- clients/unshaded/src/test/java/tachyon/hadoop/TFSTest.java
- clients/unshaded/src/test/java/tachyon/hadoop/UtilsTest.java
> [TACHYON-1428] Documented parts of the tests of the tachyon.client package in preparation for the checkstyle rule

- clients/unshaded/src/test/java/tachyon/client/file/AbstractTachyonFileSystemTest.java
- clients/unshaded/src/test/java/tachyon/client/file/FileInStreamTest.java
- clients/unshaded/src/test/java/tachyon/client/file/FileOutStreamTest.java
- clients/unshaded/src/test/java/tachyon/client/file/FileSystemMasterClientTest.java
- clients/unshaded/src/test/java/tachyon/client/file/TachyonFileTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/CompleteFileOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/CreateOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/DeleteOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/FreeOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/GetInfoOptionsTest.java
> [TACHYON-1428] Documented parts of the tests of the tachyon.client.file package in preparation for the checkstyle rule

- integration/yarn/src/main/java/tachyon/yarn/ApplicationMaster.java
- integration/yarn/src/test/java/tachyon/yarn/ApplicationMasterTest.java
Followup to https://github.com/amplab/tachyon/pull/2334
> [SMALLFIX] Fix ApplicationMasterTest

- underfs/oss/README.md
Add the documents for the OSS UnderFileSystem
README.md in underfs/oss/
> [TACHYON-1461] Provide documents for the OSS UnderFileSystem

- common/src/main/java/tachyon/exception/AccessControlException.java
- common/src/main/java/tachyon/exception/ExceptionMessage.java
- common/src/main/java/tachyon/exception/PreconditionMessage.java
- common/src/main/java/tachyon/exception/TachyonExceptionType.java
- common/src/main/java/tachyon/security/authorization/FileSystemPermission.java
- servers/src/main/java/tachyon/master/file/meta/InodeTree.java
- servers/src/main/java/tachyon/master/permission/FileSystemPermissionChecker.java
- servers/src/test/java/tachyon/master/permission/FileSystemPermissionCheckerTest.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-1416
Base class of permission checking logic in `FileSystemPermissionChecker`
The usage of this in `FileSystemMaster` would look like below, for example, at the entry of `getFileInfo()` method, invoke `FileSystemPermissionChecker.checkSelfPermission(...)`, keep going if checking succeeds, and throw exception if fails.
@jsimsa , @yupeng9 , @apc999 , @sundapeng , would you like to take a look? Thanks.
> [TACHYON-1416] Check - Add a basic class for permission check logic

- common/src/main/java/tachyon/security/authorization/PermissionStatus.java
- common/src/main/java/tachyon/util/CommonUtils.java
- common/src/test/java/tachyon/security/authorization/PermissionStatusTest.java
- common/src/test/java/tachyon/util/CommonUtilsTest.java
Please review:
https://tachyon.atlassian.net/browse/TACHYON-1413
> [TACHYON-1413] Groups - Bind group info to INode

- clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystem.java
- clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystemCore.java
- clients/unshaded/src/main/java/tachyon/client/file/options/OptionsBuilder.java
- clients/unshaded/src/main/java/tachyon/client/lineage/AbstractLineageClient.java
- clients/unshaded/src/main/java/tachyon/client/lineage/DummyFileOutputStream.java
- clients/unshaded/src/main/java/tachyon/client/lineage/LineageFileOutStream.java
- clients/unshaded/src/main/java/tachyon/client/lineage/LineageMasterClient.java
- clients/unshaded/src/main/java/tachyon/client/lineage/options/CreateLineageOptions.java
- common/src/test/java/tachyon/security/authorization/PermissionStatusTest.java
- common/src/test/java/tachyon/util/CommonUtilsTest.java
> [TACHYON-1428] Documented parts of the tachyon.client package in preparation for the checkstyle rule

- integration-tests/src/test/java/tachyon/underfs/s3/S3UnderStorageCluster.java
> [TACHYON-1469] Fix configuration settings for S3UnderStorageCluster

- integration/bin/tachyon-yarn.sh
https://tachyon.atlassian.net/browse/TACHYON-1483
> [TACHYON-1483] Fix tachyon-yarn.sh to respect tachyon master address

- minicluster/src/main/java/tachyon/master/AbstractLocalTachyonCluster.java
Addresses the issue seen in #2354
> [SMALLFIX] Increase cluster ready timeout to accomadate for slower under storage.

- minicluster/src/main/java/tachyon/master/AbstractLocalTachyonCluster.java
https://tachyon.atlassian.net/browse/TACHYON-1484
> [TACHYON-1484] Enable S3 Under Storage Tests to write data to S3

- integration/yarn/src/main/java/tachyon/yarn/ApplicationMaster.java
- integration/yarn/src/test/java/tachyon/yarn/ApplicationMasterTest.java
https://tachyon.atlassian.net/browse/TACHYON-1486
> [TACHYON-1486] Fix issue with yarn container sizes overflowing

- common/src/main/java/tachyon/Constants.java
- integration-tests/src/test/java/tachyon/shell/TfsShellTest.java
- servers/src/main/webapp/browse-body.jsp
- servers/src/main/webapp/memory.jsp
- shell/src/main/java/tachyon/shell/command/AbstractLsCommand.java
Please review:
https://tachyon.atlassian.net/browse/TACHYON-1414
> [TACHYON-1414] Group - Show group info in UI and CLI

- shell/src/main/java/tachyon/shell/command/FreeCommand.java
- shell/src/main/java/tachyon/shell/command/GetCapacityBytesCommand.java
- shell/src/main/java/tachyon/shell/command/GetUsedBytesCommand.java
- shell/src/main/java/tachyon/shell/command/ListLineagesCommand.java
- shell/src/main/java/tachyon/shell/command/LoadCommand.java
- shell/src/main/java/tachyon/shell/command/LoadMetadataCommand.java
- shell/src/main/java/tachyon/shell/command/LocationCommand.java
- shell/src/main/java/tachyon/shell/command/LsCommand.java
- shell/src/main/java/tachyon/shell/command/LsrCommand.java
- shell/src/main/java/tachyon/shell/command/MkdirCommand.java
> [TACHYON-1428] Documented parts of the tachyon.shell.command package in preparation for the checkstyle rule

- common/src/main/java/tachyon/retry/CountingRetry.java
- common/src/test/java/tachyon/retry/CountingRetryTest.java
- underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystem.java
https://tachyon.atlassian.net/browse/TACHYON-1451
Added a simple change to use SleepingRetry with no sleep time. 
If this change is accepted will go ahead and add it to other usage of retries in the same class.
> [TACHYON-1451] minor change of using SleepingRetry for Hdfs path create

- shell/src/main/java/tachyon/shell/command/FreeCommand.java
- shell/src/main/java/tachyon/shell/command/GetCapacityBytesCommand.java
- shell/src/main/java/tachyon/shell/command/GetUsedBytesCommand.java
- shell/src/main/java/tachyon/shell/command/ListLineagesCommand.java
- shell/src/main/java/tachyon/shell/command/LoadCommand.java
- shell/src/main/java/tachyon/shell/command/LoadMetadataCommand.java
- shell/src/main/java/tachyon/shell/command/LocationCommand.java
- shell/src/main/java/tachyon/shell/command/LsCommand.java
- shell/src/main/java/tachyon/shell/command/LsrCommand.java
- shell/src/main/java/tachyon/shell/command/MkdirCommand.java
> [TACHYON-1428] Changed the comments of the constructors for the shell commands

- integration/bin/tachyon-master-yarn.sh
- integration/bin/tachyon-worker-yarn.sh
https://tachyon.atlassian.net/browse/TACHYON-1504
> [TACHYON-1504] Log to application logs when running Tachyon on Yarn

- common/src/main/java/tachyon/LeaderInquireClient.java
- integration-tests/src/test/java/tachyon/master/MasterFaultToleranceIntegrationTest.java
- minicluster/src/main/java/tachyon/master/LocalTachyonCluster.java
- minicluster/src/main/java/tachyon/master/LocalTachyonClusterMultiMaster.java
- minicluster/src/main/java/tachyon/master/LocalTachyonMaster.java
- servers/src/main/java/tachyon/master/TachyonMaster.java
https://tachyon.atlassian.net/browse/TACHYON-987
Here is another attempt to enable fault tolerant tests. stop() does not work well in fault tolerant mode, so kill() is used.
> [TACHYON-987] Enable fault tolerant tests

- bin/tachyon
I introduced a new checking of the input parameters, so if program execute without parameters or having three or more input parameters, it will execute printUsage function and exit with error code 1. Also, I changed the IF-ELSIF-ELSE statements for a CASE which turns to be more clean and have a better readability.
> [SMALLFIX] Tachyon code update

- common/src/main/java/tachyon/Constants.java
- common/src/main/java/tachyon/conf/TachyonConf.java
- common/src/main/resources/tachyon-default.properties
- docs/Configuration-Settings.md
- integration/yarn/src/main/java/tachyon/yarn/ApplicationMaster.java
- integration/yarn/src/main/java/tachyon/yarn/Client.java
- integration/yarn/src/test/java/tachyon/yarn/ApplicationMasterTest.java
https://tachyon.atlassian.net/browse/TACHYON-1495
> [TACHYON-1495] Allow users to configure maximum workers per host

- clients/unshaded/src/main/java/tachyon/client/file/BaseFileSystem.java
- clients/unshaded/src/main/java/tachyon/client/file/FileSystem.java
- clients/unshaded/src/main/java/tachyon/client/file/FileSystemMasterClient.java
> [TACHYON-167] Change create directory and load metadata to return void.

- deploy/vagrant/README.md
- Remove trailing whitespaces
- Fix wording/grammar
> [SMALLFIX] Vagrant README cleanup

- underfs/oss/src/main/java/tachyon/underfs/oss/OSSUnderFileSystem.java
fix the same problem as S3 integration test in UnderStorageSystemInterfaceIntegrationTest.testListRecursive
The jira link is here: https://tachyon.atlassian.net/browse/TACHYON-1518
> [TACHYON-1518] Fix UnderStorageSystemInterfaceIntegrationTest.testListRecursive for OSS

- common/src/main/java/tachyon/security/authentication/AuthenticationProvider.java
- common/src/test/java/tachyon/retry/CountingRetryTest.java
- common/src/test/java/tachyon/worker/block/io/LocalFileBlockReaderTest.java
- common/src/test/java/tachyon/worker/block/io/LocalFileBlockWriterTest.java
- underfs/oss/src/main/java/tachyon/underfs/oss/OSSOutputStream.java
- underfs/oss/src/main/java/tachyon/underfs/oss/OSSUnderFileSystemFactory.java
- underfs/oss/src/test/java/tachyon/underfs/oss/OSSUnderFileSystemFactoryTest.java
- underfs/oss/src/test/java/tachyon/underfs/oss/OSSUnderFileSystemTest.java
- underfs/swift/src/main/java/tachyon/underfs/swift/SwiftUnderFileSystem.java
> [TACHYON-1428] Documented parts of the tachyon-common and tachyon-underfs modules in preparation for the checkstyle rule

- common/src/main/java/tachyon/security/group/provider/ShellBasedUnixGroupsMapping.java
- common/src/main/java/tachyon/util/CommonUtils.java
- fuse/src/main/java/tachyon/fuse/OpenFileEntry.java
- integration-tests/src/test/java/tachyon/client/RemoteBlockInStreamIntegrationTest.java
https://tachyon.atlassian.net/browse/TACHYON-1323
> [TACHYON-1323] Changed code in Javadoc in different modules

- clients/unshaded/src/main/java/tachyon/client/TachyonFSTestUtils.java
- clients/unshaded/src/main/java/tachyon/client/block/BlockWorkerInfo.java
- clients/unshaded/src/main/java/tachyon/client/file/FileSystemMasterClient.java
- clients/unshaded/src/main/java/tachyon/client/file/policy/RoundRobinPolicy.java
- clients/unshaded/src/main/java/tachyon/client/file/policy/SpecificHostPolicy.java
- clients/unshaded/src/main/java/tachyon/client/worker/BlockWorkerClient.java
- clients/unshaded/src/main/java/tachyon/hadoop/HdfsFileInputStream.java
- clients/unshaded/src/main/java/tachyon/hadoop/Utils.java
- common/src/main/java/tachyon/worker/NetAddress.java
- underfs/swift/src/main/java/tachyon/underfs/swift/SwiftUnderFileSystem.java
> [TACHYON-1428] Documented parts of the different modules in preparation for the checkstyle rule

- servers/src/test/java/tachyon/worker/block/BlockMetadataManagerTest.java
- servers/src/test/java/tachyon/worker/block/BlockMetadataManagerViewTest.java
- servers/src/test/java/tachyon/worker/block/BlockStoreMetaTest.java
- servers/src/test/java/tachyon/worker/block/SpaceReserverTest.java
- servers/src/test/java/tachyon/worker/block/TieredBlockStoreTest.java
- servers/src/test/java/tachyon/worker/block/TieredBlockStoreTestUtils.java
- servers/src/test/java/tachyon/worker/block/allocator/AllocatorFactoryTest.java
- servers/src/test/java/tachyon/worker/block/allocator/BaseAllocatorTest.java
- servers/src/test/java/tachyon/worker/block/evictor/EvictorContractTestBase.java
- servers/src/test/java/tachyon/worker/block/evictor/LRUEvictorTest.java
- servers/src/test/java/tachyon/worker/block/evictor/PartialLRUEvictorTest.java
- servers/src/test/java/tachyon/worker/block/meta/BlockMetaBaseTest.java
- servers/src/test/java/tachyon/worker/block/meta/BlockMetaTest.java
- servers/src/test/java/tachyon/worker/block/meta/StorageDirTest.java
- servers/src/test/java/tachyon/worker/block/meta/StorageDirViewTest.java
- servers/src/test/java/tachyon/worker/block/meta/StorageTierTest.java
- servers/src/test/java/tachyon/worker/block/meta/StorageTierViewTest.java
- servers/src/test/java/tachyon/worker/block/meta/TempBlockMetaTest.java
https://tachyon.atlassian.net/browse/TACHYON-1516
> [TACHYON-1516] Clean up WorkerContext config after tests

- clients/unshaded/src/test/java/tachyon/client/file/FileInStreamTest.java
- clients/unshaded/src/test/java/tachyon/client/file/FileOutStreamTest.java
- clients/unshaded/src/test/java/tachyon/client/file/policy/LocalFirstPolicyTest.java
- clients/unshaded/src/test/java/tachyon/client/file/policy/MostAvailableFirstPolicyTest.java
- clients/unshaded/src/test/java/tachyon/client/file/policy/RoundRobinPolicyTest.java
- clients/unshaded/src/test/java/tachyon/client/file/policy/SpecificHostPolicyTest.java
- clients/unshaded/src/test/java/tachyon/client/lineage/LineageFileOutStreamTest.java
- clients/unshaded/src/test/java/tachyon/client/lineage/TachyonLineageFileSystemTest.java
- underfs/swift/src/main/java/tachyon/underfs/swift/SwiftUnderFileSystem.java
> [TACHYON-1428] Documented parts of the swift and client modules in preparation for the checkstyle rule

- servers/src/test/java/tachyon/worker/block/SpaceReserverTest.java
- servers/src/test/java/tachyon/worker/block/TieredBlockStoreTest.java
- servers/src/test/java/tachyon/worker/block/meta/BlockMetaTest.java
- servers/src/test/java/tachyon/worker/block/meta/StorageDirTest.java
- servers/src/test/java/tachyon/worker/block/meta/StorageDirViewTest.java
- servers/src/test/java/tachyon/worker/block/meta/StorageTierTest.java
- servers/src/test/java/tachyon/worker/block/meta/StorageTierViewTest.java
- servers/src/test/java/tachyon/worker/block/meta/TempBlockMetaTest.java
- servers/src/test/java/tachyon/worker/file/FileDataManagerTest.java
- servers/src/test/java/tachyon/worker/file/FileSystemMasterClientTest.java
> [TACHYON-1428] Documented parts of the tachyon-servers module in preparation for the checkstyle rule

- clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystem.java
- clients/unshaded/src/main/java/tachyon/client/file/options/CreateOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/OutStreamOptions.java
- clients/unshaded/src/main/java/tachyon/client/file/options/SetStateOptions.java
- clients/unshaded/src/main/java/tachyon/client/lineage/LineageFileOutStream.java
- clients/unshaded/src/main/java/tachyon/client/lineage/TachyonLineageFileSystem.java
- clients/unshaded/src/test/java/tachyon/client/file/options/CreateOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/OutStreamOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/file/options/SetStateOptionsTest.java
- clients/unshaded/src/test/java/tachyon/client/lineage/TachyonLineageFileSystemTest.java
- docs/Command-Line-Interface.md
- integration-tests/src/test/java/tachyon/master/file/FileSystemMasterIntegrationTest.java
- integration-tests/src/test/java/tachyon/shell/TfsShellTest.java
- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
- servers/src/main/java/tachyon/master/file/meta/InodeFile.java
- servers/src/main/java/tachyon/master/file/meta/InodeTree.java
- servers/src/main/java/tachyon/master/file/meta/TtlBucket.java
- servers/src/main/java/tachyon/master/file/meta/TtlBucketList.java
- servers/src/main/java/tachyon/master/file/meta/options/CreatePathOptions.java
- servers/src/main/java/tachyon/master/file/options/CreateOptions.java
- servers/src/test/java/tachyon/master/file/FileSystemMasterTest.java
- servers/src/test/java/tachyon/master/file/meta/TtlBucketListTest.java
- servers/src/test/java/tachyon/master/file/meta/TtlBucketPrivateAccess.java
- servers/src/test/java/tachyon/master/file/meta/TtlBucketTest.java
- servers/src/test/java/tachyon/master/file/meta/options/CreatePathOptionsTest.java
- servers/src/test/java/tachyon/master/file/options/CreateOptionsTest.java
- shell/src/main/java/tachyon/shell/command/CommandUtils.java
- shell/src/main/java/tachyon/shell/command/SetTtlCommand.java
- shell/src/main/java/tachyon/shell/command/UnsetTtlCommand.java
- shell/src/main/resources/tfs.man
https://tachyon.atlassian.net/browse/TACHYON-1387
> [TACHYON-1387] Use Ttl instead of TTL for naming

- servers/src/main/webapp/footer.jsp
https://tachyon.atlassian.net/browse/TACHYON-1529
Sample image:
> [TACHYON-1529] Add link to the mailing list in the web ui.

- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
- servers/src/main/java/tachyon/master/file/FileSystemMasterWorkerServiceHandler.java
- servers/src/main/java/tachyon/master/lineage/recompute/RecomputeExecutor.java
- servers/src/main/java/tachyon/master/permission/FileSystemPermissionChecker.java
- servers/src/test/java/tachyon/master/file/FileSystemMasterPermissionCheckTest.java
- servers/src/test/java/tachyon/master/file/FileSystemMasterTest.java
https://tachyon.atlassian.net/browse/TACHYON-1420
This pull request is adding permission check for setState, completeFile, free, loadMetadata, mount, unmount.
@apc999 , @jsimsa , @yupeng9, @dongche
> [TACHYON-1420] Check - Check Tachyon specfic operations in Master side

- servers/src/main/java/tachyon/worker/block/SpaceReserver.java
Added the link to the class in its documentation.
> [DOCFIX] Added link in documentation of SpaceReserver

- integration-tests/src/test/java/tachyon/IntegrationTestUtils.java
- integration-tests/src/test/java/tachyon/client/FileOutStreamAsyncWriteIntegrationTest.java
- integration-tests/src/test/java/tachyon/master/lineage/LineageMasterIntegrationTest.java
https://tachyon.atlassian.net/browse/TACHYON-1408
> [TACHYON-1408] Fix flaky lineage integration test

- shell/src/main/java/tachyon/shell/command/RmrCommand.java
https://tachyon.atlassian.net/browse/TACHYON-1215
> [TACHYON-1215] rmr doesn't show error message

- deploy/vagrant/conf/spark.yml
- deploy/vagrant/provision/roles/tachyon/files/down_release.sh
The Spark comment directed to somewhere which didn't have the tarball names, and the Tachyon site has changed.
> [SMALLFIX] Update download sites

- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
https://tachyon.atlassian.net/browse/TACHYON-1361
I create a new PR for issue TACHYON-1361.make it more clear.
I made a lot of mistakes before,sorry! ! !
> [TACHYON-1361]adda javadoc for mTtlBuckets

- integration-tests/src/test/java/tachyon/master/MasterFaultToleranceIntegrationTest.java
- integration-tests/src/test/java/tachyon/shell/TfsShellTest.java
- servers/src/test/java/tachyon/master/file/FileSystemMasterTest.java
Make sure that unit tests which modify MasterContext's TachyonConf reset the config afterwards.
Jira address: https://tachyon.atlassian.net/browse/TACHYON-1514
> [TACHYON-1514] Audit misuse of MasterContext in tests.

- docs/Building-Tachyon-Master-Branch.md
small fix to add oss underfs support in Building-Tachyon-Master-Branch.md
> [SMALLFIX] Add oss underfs support in Building-Tachyon-Master-Branch.md

- underfs/glusterfs/src/main/java/tachyon/underfs/glusterfs/GlusterFSUnderFileSystem.java
- underfs/glusterfs/src/main/java/tachyon/underfs/glusterfs/GlusterFSUnderFileSystemFactory.java
- underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystemFactory.java
- underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystemUtils.java
- underfs/local/src/main/java/tachyon/underfs/local/LocalUnderFileSystem.java
- underfs/local/src/main/java/tachyon/underfs/local/LocalUnderFileSystemFactory.java
- underfs/oss/src/main/java/tachyon/underfs/oss/OSSInputStream.java
- underfs/oss/src/main/java/tachyon/underfs/oss/OSSOutputStream.java
- underfs/oss/src/main/java/tachyon/underfs/oss/OSSUnderFileSystem.java
- underfs/oss/src/main/java/tachyon/underfs/oss/OSSUnderFileSystemFactory.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3InputStream.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3OutputStream.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3UnderFileSystem.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3UnderFileSystemFactory.java
- underfs/swift/src/main/java/tachyon/underfs/swift/SwiftOutputStream.java
- underfs/swift/src/main/java/tachyon/underfs/swift/SwiftUnderFileSystem.java
- underfs/swift/src/main/java/tachyon/underfs/swift/SwiftUnderFileSystemFactory.java
- underfs/swift/src/main/java/tachyon/underfs/swift/http/SwiftDirectClient.java
Addresses: https://tachyon.atlassian.net/browse/TACHYON-1475
> [TACHYON-1475] Cleanup of UFS source code

- underfs/glusterfs/src/test/java/tachyon/underfs/glusterfs/GlusterFSUnderFileSystemFactoryTest.java
- underfs/hdfs/src/test/java/tachyon/underfs/hdfs/HdfsUnderFileSystemFactoryTest.java
- underfs/local/src/test/java/tachyon/underfs/local/LocalUnderFileSystemFactoryTest.java
- underfs/oss/src/test/java/tachyon/underfs/oss/OSSUnderFileSystemFactoryTest.java
- underfs/oss/src/test/java/tachyon/underfs/oss/OSSUnderFileSystemTest.java
- underfs/s3/src/test/java/tachyon/underfs/s3/S3UnderFileSystemFactoryTest.java
- underfs/swift/src/test/java/tachyon/underfs/swift/SwiftUnderFileSystemFactoryTest.java
- underfs/swift/src/test/java/tachyon/underfs/swift/SwiftUnderFileSystemTest.java
Addresses: https://tachyon.atlassian.net/browse/TACHYON-1478
> [TACHYON-1478] Cleaning up UFS test code.

- servers/src/test/java/tachyon/master/block/meta/BlockContainerIdGeneratorTest.java
https://tachyon.atlassian.net/browse/TACHYON-1489
> [TACHYON-1489] Add unittests for BlockContainerIdGenerator

- integration-tests/src/test/java/tachyon/IntegrationTestUtils.java
- servers/src/test/java/tachyon/worker/TachyonWorkerPrivateAccess.java
- servers/src/test/java/tachyon/worker/file/FileSystemWorkerPrivateAccess.java
Followup to https://github.com/amplab/tachyon/pull/2451
> [SMALLFIX] Use Private Access pattern in IntegrationTestUtils

- clients/unshaded/src/test/java/tachyon/client/block/BlockStoreContextTest.java
- servers/src/main/java/tachyon/worker/DataServer.java
- servers/src/main/java/tachyon/worker/TachyonWorker.java
- servers/src/main/java/tachyon/worker/WorkerContext.java
- servers/src/main/java/tachyon/worker/block/meta/StorageDir.java
- servers/src/main/java/tachyon/worker/file/FileDataManager.java
- servers/src/main/java/tachyon/worker/netty/PipelineHandler.java
- servers/src/test/java/tachyon/master/block/BlockMasterTest.java
- servers/src/test/java/tachyon/master/block/meta/BlockContainerIdGeneratorTest.java
- servers/src/test/java/tachyon/master/block/meta/MasterBlockInfoTest.java
> [TACHYON-1428] Documented parts of the tachyon-servers and tachyon-client modules in preparation for the checkstyle rule

- underfs/s3/pom.xml
> [SMALLFIX] Adding missing jets3t dependencies into the S3 UFS jar.

- underfs/s3/pom.xml
> [SMALLFIX] Adding a TODO for the S3 pom file.

- shell/src/main/java/tachyon/shell/TfsShell.java
Remove mCloser from tachyon.shell.TfsShell
> [TACHYON-1550] Remove mCloser from tachyon.shell.TfsShell

- servers/src/test/java/tachyon/metrics/MetricsConfigTest.java
- servers/src/test/java/tachyon/metrics/MetricsSystemTest.java
- servers/src/test/java/tachyon/network/protocol/databuffer/DataByteBufferTest.java
- servers/src/test/java/tachyon/network/protocol/databuffer/DataFileChannelTest.java
- shell/src/main/java/tachyon/shell/TfsShell.java
- shell/src/main/java/tachyon/shell/command/CommandUtils.java
> [TACHYON-1428] Documented parts of the tachyon-servers and tachyon-shell modules in preparation for the checkstyle rule

- clients/unshaded/src/main/java/tachyon/client/file/FileInStream.java
Hi admins, please take a look if that is what you want.
Regards.
> [TACHYON-744] Clean up log message in FileInStream

- bin/tachyon
- clients/unshaded/src/main/java/tachyon/client/WriteType.java
- examples/src/main/java/tachyon/examples/BasicOperations.java
https://tachyon.atlassian.net/browse/TACHYON-1248
> [TACHYON-1248] Undeprecated ASYNC_THROUGH write type and added examples

- integration-tests/src/test/java/tachyon/shell/command/PinCommandTest.java
added two more tests cases for commands getUsedBytes and getCapacityBytes
> [TACHYON-1376] Pin Command in separate class. 

- integration-tests/src/test/java/tachyon/LocalTachyonClusterResource.java
https://tachyon.atlassian.net/browse/TACHYON-1563
> [TACHYON-1563] Clean up LocalTachyonCluster on exception

- servers/src/main/webapp/footer.jsp
https://tachyon.atlassian.net/browse/TACHYON-1529
Example page:
> [TACHYON-1529] Add the project survey link to the UI.

- common/src/test/java/tachyon/heartbeat/HeartbeatThreadTest.java
- integration-tests/src/test/java/tachyon/master/JournalIntegrationTest.java
- integration-tests/src/test/java/tachyon/master/JournalShutdownIntegrationTest.java
- integration-tests/src/test/java/tachyon/master/file/FileSystemMasterIntegrationTest.java
- integration-tests/src/test/java/tachyon/security/BlockWorkerClientAuthenticationIntegrationTest.java
- servers/src/main/java/tachyon/master/lineage/recompute/RecomputeExecutor.java
- servers/src/main/java/tachyon/worker/block/BlockMasterSync.java
- servers/src/main/java/tachyon/worker/file/FileWorkerMasterSyncExecutor.java
- Give names to threads used in production
- Shutdown executors used in tests
> [SMALLFIX] Thread cleanup

- integration-tests/src/test/java/tachyon/master/file/FileSystemMasterIntegrationTest.java
The test which modifies shared state is responsible for restoring it.
> [SMALLFIX] File system master test cleanup

- common/src/main/java/tachyon/TachyonURI.java
- common/src/main/java/tachyon/conf/TachyonConf.java
- common/src/main/java/tachyon/util/io/PathUtils.java
- common/src/test/java/tachyon/TachyonURITest.java
- underfs/local/src/main/java/tachyon/underfs/local/LocalUnderFileSystemFactory.java
- underfs/local/src/test/java/tachyon/underfs/local/LocalUnderFileSystemFactoryTest.java
[TACHYON-1532] is high priority fix which also affect other platforms.
Others are minor fixes.
> A bunch of bug fixes mainly focus running on Windows platform

- clients/unshaded/src/main/java/tachyon/client/worker/WorkerClientHeartbeatExecutor.java
- common/src/main/java/tachyon/heartbeat/HeartbeatExecutor.java
- common/src/main/java/tachyon/heartbeat/HeartbeatThread.java
- common/src/test/java/tachyon/heartbeat/HeartbeatThreadTest.java
- servers/src/main/java/tachyon/master/block/BlockMaster.java
- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
- servers/src/main/java/tachyon/master/lineage/checkpoint/CheckpointSchedulingExcecutor.java
- servers/src/main/java/tachyon/master/lineage/recompute/RecomputeExecutor.java
- servers/src/main/java/tachyon/worker/block/BlockMasterSync.java
- servers/src/main/java/tachyon/worker/block/PinListSync.java
- servers/src/main/java/tachyon/worker/file/FileWorkerMasterSyncExecutor.java
- servers/src/test/java/tachyon/master/lineage/recompute/TestRecomputeExecutor.java
https://tachyon.atlassian.net/browse/TACHYON-1577
> [TACHYON-1577] Clean up HeartbeatExecutor threadpools

- clients/unshaded/src/main/java/tachyon/hadoop/AbstractTFS.java
- integration-tests/src/test/java/tachyon/hadoop/TFSAclIntegrationTest.java
Jira: https://tachyon.atlassian.net/browse/TACHYON-1427
The pull request is adding support for Hadoop based TFS, change owner, group and permission.
@apc999 , @jsimsa , @yupeng9 , @dongche 
**Since https://github.com/amplab/tachyon/pull/2394 is not merged to branch, I apply my commit TACHYON-1427 based on it. You may need to change to commit view to review my patch. Thanks!**
> [TACHYON-1427] Support setting permission model in Hadoop based TFS

- common/src/main/java/tachyon/exception/ExceptionMessage.java
- common/src/main/java/tachyon/exception/PreconditionMessage.java
- integration-tests/src/test/java/tachyon/client/keyvalue/KeyValueStoresIntegrationTest.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/BaseKeyValuePartitionWriter.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/BaseKeyValueStoreWriter.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/KeyValuePartitionWriter.java
- keyvalue/clients/src/test/java/tachyon/client/keyvalue/BaseKeyValuePartitionWriterTest.java
https://tachyon.atlassian.net/browse/TACHYON-1576
> [TACHYON-1576] Force each key-value partition no larger than the max size set in Conf

- fuse/src/main/java/tachyon/fuse/TachyonFuse.java
- fuse/src/main/java/tachyon/fuse/TachyonFuseFs.java
- fuse/src/test/java/tachyon/fuse/TachyonFuseFsTest.java
Updates the fuse code to match #2523
> [TACHYON-167] Update fuse code.

- fuse/src/main/java/tachyon/fuse/TachyonFuse.java
- minicluster/src/main/java/tachyon/master/AbstractLocalTachyonCluster.java
- minicluster/src/main/java/tachyon/master/LocalTachyonCluster.java
- minicluster/src/main/java/tachyon/master/LocalTachyonClusterMultiMaster.java
- minicluster/src/main/java/tachyon/master/LocalTachyonMaster.java
- minicluster/src/main/java/tachyon/underfs/LocalFilesystemCluster.java
- minicluster/src/main/java/tachyon/underfs/UnderFileSystemCluster.java
> [TACHYON-1428] Documented parts of the tachyon-minicluster and tachyon-fuse modules in preparation for the checkstyle rule

- clients/unshaded/src/main/java/tachyon/client/worker/BlockWorkerClient.java
- common/src/main/java/tachyon/exception/TachyonException.java
- examples/src/main/java/tachyon/examples/JournalCrashTest.java
- integration-tests/src/test/java/tachyon/client/FileSystemIntegrationTest.java
https://tachyon.atlassian.net/projects/TACHYON/issues/TACHYON-1602
> [TACHYON-1602] Remove TachyonException#getType

- clients/unshaded/src/main/java/tachyon/client/file/BaseFileSystem.java
- clients/unshaded/src/main/java/tachyon/client/file/FileSystem.java
- clients/unshaded/src/main/java/tachyon/client/file/options/SetAclOptions.java
- clients/unshaded/src/main/java/tachyon/client/lineage/options/DeleteLineageOptions.java
- common/src/main/java/tachyon/exception/AccessControlException.java
- common/src/main/java/tachyon/security/login/AppCallbackHandler.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/Index.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/hadoop/KeyValueInputFormat.java
> [TACHYON-1428] Documented parts of the several modules in preparation for the checkstyle rule

- clients/unshaded/src/test/java/tachyon/client/ClientUtilsTest.java
https://tachyon.atlassian.net/projects/TACHYON/issues/TACHYON-1559
> [TACHYON-1559] Add unit test for tachyon.client.ClientUtils.getRandomNonNegativeLong()

- fuse/src/main/java/tachyon/fuse/OpenFileEntry.java
- fuse/src/main/java/tachyon/fuse/TachyonFuse.java
- fuse/src/main/java/tachyon/fuse/TachyonFuseFs.java
- fuse/src/main/java/tachyon/fuse/TachyonFuseOptions.java
- fuse/src/main/java/tachyon/fuse/TachyonFuseUtils.java
Addresses: https://tachyon.atlassian.net/browse/TACHYON-1611
@yupeng9
> [TACHYON-1611] Adding thread safety annotations for tachyon.fuse in fuse module.

- clients/unshaded/src/main/java/tachyon/client/lineage/TachyonLineage.java
- clients/unshaded/src/main/java/tachyon/client/netty/ClientHandler.java
@apc999 follow up to https://github.com/amplab/tachyon/pull/2541
> [SMALLFIX] Minor fixes.

- integration/mesos/src/main/java/tachyon/mesos/TachyonFramework.java
- integration/mesos/src/main/java/tachyon/mesos/TachyonMasterExecutor.java
- integration/mesos/src/main/java/tachyon/mesos/TachyonWorkerExecutor.java
- integration/yarn/src/main/java/tachyon/yarn/ApplicationMaster.java
- integration/yarn/src/main/java/tachyon/yarn/Client.java
- integration/yarn/src/main/java/tachyon/yarn/CommandBuilder.java
- integration/yarn/src/main/java/tachyon/yarn/YarnUtils.java
Addresses: https://tachyon.atlassian.net/browse/TACHYON-1612
@apc999 @aaudiber
> [TACHYON-1612] Use thread safety annotations in the integration module

- keyvalue/clients/src/main/java/tachyon/client/keyvalue/BaseKeyValueStores.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/KeyValuePair.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/hadoop/KeyValueInputFormat.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/hadoop/KeyValueInputSplit.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/hadoop/KeyValueOutputCommitter.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/hadoop/KeyValueOutputFormat.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/hadoop/KeyValueRecordReader.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/hadoop/KeyValueRecordWriter.java
- keyvalue/servers/src/main/java/tachyon/master/keyvalue/KeyValueMasterFactory.java
- keyvalue/servers/src/main/java/tachyon/worker/keyvalue/KeyValueWorkerFactory.java
Addresses: https://tachyon.atlassian.net/browse/TACHYON-1617
> [TACHYON-1617] Use thread safety annotations in the keyvalue module

- build/checkstyle/suppressions.xml
- build/checkstyle/tachyon_checks.xml
- pom.xml
> [TACHYON-1428] Added checkstyle rule for documentation of public methods and classes

- integration/mesos/src/main/java/tachyon/mesos/TachyonFramework.java
- integration/mesos/src/main/java/tachyon/mesos/TachyonMasterExecutor.java
- integration/mesos/src/main/java/tachyon/mesos/TachyonWorkerExecutor.java
> [SMALLFIX] Adding missing javadoc

- servers/src/main/java/tachyon/worker/netty/NettyDataServer.java
This is needed to fix the build
> [SMALLFIX] Update param javadoc

- integration/yarn/src/main/java/tachyon/yarn/ApplicationMaster.java
- integration/yarn/src/main/java/tachyon/yarn/Client.java
- integration/yarn/src/main/java/tachyon/yarn/CommandBuilder.java
- integration/yarn/src/main/java/tachyon/yarn/YarnUtils.java
This is needed to fix the developer build
> [SMALLFIX] Add missing javadoc relating to Yarn

- integration/fuse/pom.xml
> [SMALLFIX] Fixing the FUSE pom file.

- servers/src/main/java/tachyon/worker/block/SessionCleaner.java
- servers/src/main/java/tachyon/worker/block/SpaceReserver.java
1. currently space reserver doesn't update last check time.
2. last check time in session cleaner doesn't record the duration of clean operation
> [TACHYON-1507] Fix last check time in space reserver and session cleaner

- deploy/vagrant/core/EnvSetup.rb
Followup to https://github.com/amplab/tachyon/pull/2566
> [SMALLFIX] Fix deploy script syntax

- servers/src/main/java/tachyon/web/UIFileInfo.java
- servers/src/main/java/tachyon/web/WebInterfaceBrowseLogsServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceBrowseServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceGeneralServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceWorkerGeneralServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceWorkersServlet.java
- servers/src/main/java/tachyon/web/WebUtils.java
- servers/src/test/java/tachyon/web/UtilsTest.java
- servers/src/test/java/tachyon/web/WebUtilsTest.java
tachyon.web.WebUtils is better for readability since there are multiple Utils class.
https://tachyon.atlassian.net/browse/TACHYON-1560
> [TACHYON-1560] Rename tachyon.web.Utils to tachyon.web.WebUtils

- bin/tachyon
https://tachyon.atlassian.net/browse/TACHYON-1625
> [TACHYON-1625] Add oss option in TACHYON_UNDERFS_ADDRESS in "bin/tachyon format"

- core/common/src/main/java/tachyon/exception/ExceptionMessage.java
- core/common/src/main/java/tachyon/security/authentication/PlainSaslServer.java
- core/common/src/main/java/tachyon/security/authorization/PermissionStatus.java
- core/server/src/main/java/tachyon/master/file/FileSystemMaster.java
- core/server/src/main/java/tachyon/web/WebInterfaceBrowseServlet.java
- core/server/src/main/java/tachyon/web/WebInterfaceDownloadServlet.java
- core/server/src/main/java/tachyon/web/WebInterfaceMemoryServlet.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-1668
Bug fixed. Check whether security is enabled at first. If not, which is the default conf in Tachyon, the if branch should be bypassed.
@apc999 , @yupeng9 , @sundapeng
> [TACHYON-1668] Tachyon UI is broken because of security checking

- docs/_includes/Running-Tachyon-on-EC2/access-key.md
- docs/_includes/Running-Tachyon-on-EC2/copy-ec2.md
- docs/_includes/Running-Tachyon-on-EC2/destroy.md
- docs/_includes/Running-Tachyon-on-EC2/download-tachyon.md
- docs/_includes/Running-Tachyon-on-EC2/generate-key-pair.md
- docs/_includes/Running-Tachyon-on-EC2/install-aws-vagrant-plugin.md
- docs/_includes/Running-Tachyon-on-EC2/install-pip.md
- docs/_includes/Running-Tachyon-on-EC2/install-vagrant.md
- docs/_includes/Running-Tachyon-on-EC2/launch-cluster.md
- docs/_includes/Running-Tachyon-on-EC2/runTests.md
- docs/_includes/Running-Tachyon-on-EC2/shell-output.md
- docs/_includes/Running-Tachyon-on-EC2/ssh-TachyonMaster.md
- docs/_includes/Running-Tachyon-on-EC2/ssh-other-node.md
- docs/_includes/Running-Tachyon-on-EC2/ssh.md
- docs/cn/Running-Tachyon-on-EC2.md
- docs/en/Running-Tachyon-on-EC2.md
https://tachyon.atlassian.net/browse/TACHYON-1655
Add the Chinese version of documentation page 'Running-Tachyon-on-EC2'
> [TACHYON-1655] Add the Chinese version of documentation page 'Running-Tachyon-on-EC2'

- docs/en/File-System-API.md
Updates the doc to be consistent.
> [DOCFIX] FileSystem doc update

- docs/_includes/Building-Tachyon-Master-Branch/Apache.md
- docs/_includes/Building-Tachyon-Master-Branch/Cloudera.md
- docs/_includes/Building-Tachyon-Master-Branch/Hortonworks.md
- docs/_includes/Building-Tachyon-Master-Branch/MapR.md
- docs/_includes/Building-Tachyon-Master-Branch/OutOfMemoryError.md
- docs/_includes/Building-Tachyon-Master-Branch/Pivotal.md
- docs/_includes/Building-Tachyon-Master-Branch/STDOUT.md
- docs/_includes/Building-Tachyon-Master-Branch/checkout.md
- docs/_includes/Building-Tachyon-Master-Branch/increase-number.md
- docs/_includes/Building-Tachyon-Master-Branch/supported-values.md
- docs/_includes/Building-Tachyon-Master-Branch/tachyon-runTests.md
- docs/_includes/Building-Tachyon-Master-Branch/tachyon-start.md
- docs/_includes/Building-Tachyon-Master-Branch/tachyon-stop.md
- docs/_includes/Building-Tachyon-Master-Branch/test-result.md
- docs/_includes/Building-Tachyon-Master-Branch/under-storage.md
- docs/_includes/Building-Tachyon-Master-Branch/unit-tests.md
- docs/cn/Building-Tachyon-Master-Branch.md
- docs/en/Building-Tachyon-Master-Branch.md
https://tachyon.atlassian.net/browse/TACHYON-1629
Add the Chinese version of documentation page 'Building-Tachyon-Master-Branch'
> [TACHYON-1629] Add the Chinese version of documentation page 'Building-Tachyon-Master-Branch'

- docs/_includes/Running-Tachyon-on-EC2-Mesos/access-key.md
- docs/_includes/Running-Tachyon-on-EC2-Mesos/destroy.md
- docs/_includes/Running-Tachyon-on-EC2-Mesos/download-tachyon.md
- docs/_includes/Running-Tachyon-on-EC2-Mesos/generate-key-pair.md
- docs/_includes/Running-Tachyon-on-EC2-Mesos/install-aws-vagrant-plugin.md
- docs/_includes/Running-Tachyon-on-EC2-Mesos/install-pip.md
- docs/_includes/Running-Tachyon-on-EC2-Mesos/install-vagrant.md
- docs/_includes/Running-Tachyon-on-EC2-Mesos/launch-cluster.md
- docs/_includes/Running-Tachyon-on-EC2-Mesos/runTests.md
- docs/_includes/Running-Tachyon-on-EC2-Mesos/shell-output.md
- docs/_includes/Running-Tachyon-on-EC2-Mesos/ssh-TachyonMaster.md
- docs/_includes/Running-Tachyon-on-EC2-Mesos/ssh.md
- docs/cn/Running-Tachyon-on-EC2-Mesos.md
- docs/en/Running-Tachyon-on-EC2-Mesos.md
https://tachyon.atlassian.net/browse/TACHYON-1653
Add the Chinese version of documentation page 'Running-Tachyon-on-EC2-Mesos'
> [TACHYON-1653] Add the Chinese version of documentation page 'Running-Tachyon-on-EC2-Mesos'

- core/server/src/test/java/tachyon/worker/block/SpaceReserverTest.java
https://tachyon.atlassian.net/browse/TACHYON-1680
> [TACHYON-1680] Avoid network binding in space reserver unit test

- core/client-internal/src/main/java/tachyon/client/block/BlockStoreContext.java
The whole section should be locked, because the AtomicBoolean only locks the condition itself.
> [SMALLFIX] Fixed a concurrency bug in BlockStoreContext

- core/client-internal/pom.xml
- core/common/pom.xml
- core/server/pom.xml
- integration/fuse/pom.xml
- integration/yarn/pom.xml
- keyvalue/client-internal/pom.xml
- keyvalue/common/pom.xml
- keyvalue/server/pom.xml
- pom.xml
- tests/pom.xml
- underfs/glusterfs/pom.xml
- underfs/hdfs/pom.xml
- underfs/local/pom.xml
- underfs/oss/pom.xml
- underfs/s3/pom.xml
- underfs/swift/pom.xml
https://tachyon.atlassian.net/browse/TACHYON-1679
> [TACHYON-1679] Move test dependencies to parent pom

- docs/en/File-System-API.md
Correct the discription of ReadType.  Below is the link issue:
https://tachyon.atlassian.net/browse/TACHYON-1682
> [TACHYON-1682]Correct the discription of ReadType

- docs/cn/index.md
https://tachyon.atlassian.net/browse/TACHYON-1663
> [TACHYON-1663]Add the Chinese version of documentation page 'HomePage'(index)

- docs/cn/Web-Interface.md
- docs/en/Web-Interface.md
https://tachyon.atlassian.net/browse/TACHYON-1661
> [TACHYON-1661]Add the Chinese version of documentation page 'Web-Interface'

- docs/_data/table/versions-of-Spark-and-Tachyon.csv
- docs/_includes/Running-Spark-on-Tachyon/Hadoop-1.x-configuration.md
- docs/_includes/Running-Spark-on-Tachyon/Tachyon-In-Out-Scala.md
- docs/_includes/Running-Spark-on-Tachyon/any-Tachyon-master.md
- docs/_includes/Running-Spark-on-Tachyon/earlier-spark-version-bash.md
- docs/_includes/Running-Spark-on-Tachyon/fault-tolerant-mode-with-zookeeper-bash.md
- docs/_includes/Running-Spark-on-Tachyon/fault-tolerant-mode-with-zookeeper-xml.md
- docs/_includes/Running-Spark-on-Tachyon/foo.md
- docs/_includes/Running-Spark-on-Tachyon/off-heap-Spark-shell.md
- docs/_includes/Running-Spark-on-Tachyon/slave-hostname-example.md
- docs/_includes/Running-Spark-on-Tachyon/slave-hostname.md
- docs/_includes/Running-Spark-on-Tachyon/spark-local-hostname-example.md
- docs/_includes/Running-Spark-on-Tachyon/your_tachyon_version.md
- docs/cn/Running-Spark-on-Tachyon.md
- docs/en/Running-Spark-on-Tachyon.md
https://tachyon.atlassian.net/browse/TACHYON-1649
> [TACHYON-1649]Add the Chinese version of documentation page 'Running-Spark-on-Tachyon'

- docs/_includes/Running-Flink-on-Tachyon/core-site-configuration.md
- docs/_includes/Running-Flink-on-Tachyon/create-core-site.md
- docs/_includes/Running-Flink-on-Tachyon/hadoop-classpath.md
- docs/cn/Running-Flink-on-Tachyon.md
- docs/cn/Running-Spark-on-Tachyon.md
- docs/cn/index.md
- docs/en/Running-Flink-on-Tachyon.md
https://tachyon.atlassian.net/browse/TACHYON-1647
also fix some problem in the former translations.
> [TACHYON-1647]Add the Chinese version of documentation page 'Running-Flink-on-Tachyon'

- docs/_data/table/cn/java-options-for-fault-tolerance.yml
- docs/_data/table/en/java-options-for-fault-tolerance.yml
- docs/_data/table/java-options-for-fault-tolerance.csv
- docs/cn/Running-Spark-on-Tachyon.md
- docs/cn/Running-Tachyon-Fault-Tolerant.md
- docs/cn/index.md
- docs/en/Running-Spark-on-Tachyon.md
- docs/en/Running-Tachyon-Fault-Tolerant.md
https://tachyon.atlassian.net/browse/TACHYON-1651
also fix some problems in the former translation,
revise a word in The English Version  'Running-Tachyon-Fault-Tolerant'
> [TACHYON-1651]Add the Chinese version of documentation page 'Running-Tachyon-Fault-Tolerant'

- minicluster/src/main/java/tachyon/master/AbstractLocalTachyonCluster.java
https://tachyon.atlassian.net/browse/TACHYON-1685
> [TACHYON-1685] Delete temporary directories created in integration tests

- docs/cn/Powered-By-Tachyon.md
https://tachyon.atlassian.net/browse/TACHYON-1662
Add the Chinese version of documentation page 'Powered-By-Tachyon'
> [TACHYON-1662] Add the Chinese version of documentation page 'Powered-By-Tachyon'

- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/access-keys.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/copy-ec2-yml.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/destroy.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/download-tachyon.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/generate-key-pairs.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/install-aws-vagrant-plugin.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/install-pip.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/install-vagrant.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/jps.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/kill-leader.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/launch-cluster.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/runTests.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/see-leader.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/shell-output.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/ssh-TachyonMaster.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/ssh-other-node.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/ssh.md
- docs/_includes/Running-Tachyon-Fault-Tolerant-on-EC2/zookeeper-client.md
- docs/cn/Running-Tachyon-Fault-Tolerant-on-EC2.md
- docs/en/Running-Tachyon-Fault-Tolerant-on-EC2.md
https://tachyon.atlassian.net/browse/TACHYON-1650
Add the Chinese version of documentation page 'Running-Tachyon-Fault-Tolerant-on-EC2'
> [TACHYON-1650] Add the Chinese version of documentation page 'Running-Tachyon-Fault-Tolerant-on-EC2'

- docs/_includes/Configuring-Tachyon-with-S3/aws.md
- docs/_includes/Configuring-Tachyon-with-S3/copy-tachyon-env.md
- docs/_includes/Configuring-Tachyon-with-S3/dependency.md
- docs/_includes/Configuring-Tachyon-with-S3/hadoop-s3-dependency.md
- docs/_includes/Configuring-Tachyon-with-S3/java-bash.md
- docs/_includes/Configuring-Tachyon-with-S3/jets3t-dependency.md
- docs/_includes/Configuring-Tachyon-with-S3/proxy.md
- docs/_includes/Configuring-Tachyon-with-S3/runTests.md
- docs/_includes/Configuring-Tachyon-with-S3/s3-file.md
- docs/_includes/Configuring-Tachyon-with-S3/start-tachyon.md
- docs/_includes/Configuring-Tachyon-with-S3/stop-tachyon.md
- docs/_includes/Configuring-Tachyon-with-S3/underfs-address.md
- docs/cn/Configuring-Tachyon-with-S3.md
- docs/en/Configuring-Tachyon-with-S3.md
https://tachyon.atlassian.net/browse/TACHYON-1635
> [TACHYON-1635] Add the Chinese version of documentation page 'Configuring-Tachyon-with-S3'

- docs/cn/Maven.md
- docs/en/Maven.md
https://tachyon.atlassian.net/browse/TACHYON-1644
> [TACHYON-1644] Add the Chinese version of documentation page 'Maven'

- docs/_includes/Running-Tachyon-Locally/Tachyon-format-start.md
- docs/_includes/Running-Tachyon-Locally/copy-template.md
- docs/_includes/Running-Tachyon-Locally/download-Tachyon-binary.md
- docs/_includes/Running-Tachyon-Locally/first-sample-output.md
- docs/_includes/Running-Tachyon-Locally/run-sample.md
- docs/_includes/Running-Tachyon-Locally/run-tests.md
- docs/_includes/Running-Tachyon-Locally/tachyon-stop.md
- docs/cn/Running-Tachyon-Fault-Tolerant.md
- docs/cn/Running-Tachyon-Locally.md
- docs/en/Running-Tachyon-Locally.md
https://tachyon.atlassian.net/browse/TACHYON-1652
> [TACHYON-1652]Add the Chinese version of documentation page 'Running-Tachyon-Locally'

- docs/_includes/Contributing-to-Tachyon/M2_REPO.md
- docs/_includes/Contributing-to-Tachyon/checkstyle.md
- docs/_includes/Contributing-to-Tachyon/eclipse-configuration.md
- docs/_includes/Contributing-to-Tachyon/findbugs.md
- docs/_includes/Contributing-to-Tachyon/slf4j.md
- docs/cn/Contributing-to-Tachyon.md
- docs/en/Contributing-to-Tachyon.md
https://tachyon.atlassian.net/browse/TACHYON-1637
> [TACHYON-1637] Add the Chinese version of documentation page 'Contributing-to-Tachyon'

- docs/_includes/Configuring-Tachyon-with-HDFS/copy-tachyon-env.md
- docs/_includes/Configuring-Tachyon-with-HDFS/mvn-Dhadoop-package.md
- docs/_includes/Configuring-Tachyon-with-HDFS/mvn-package.md
- docs/_includes/Configuring-Tachyon-with-HDFS/runTests.md
- docs/_includes/Configuring-Tachyon-with-HDFS/start-tachyon.md
- docs/_includes/Configuring-Tachyon-with-HDFS/stop-tachyon.md
- docs/_includes/Configuring-Tachyon-with-HDFS/underfs-address.md
- docs/cn/Configuring-Tachyon-with-HDFS.md
- docs/en/Configuring-Tachyon-with-HDFS.md
https://tachyon.atlassian.net/browse/TACHYON-1633
> [TACHYON-1633] Add the Chinese version of documentation page 'Configuring-Tachyon-with-HDFS'

- docs/_includes/Configuring-Tachyon-with-GlusterFS/copy-tachyon-env.md
- docs/_includes/Configuring-Tachyon-with-GlusterFS/glusterfs-file.md
- docs/_includes/Configuring-Tachyon-with-GlusterFS/runTests.md
- docs/_includes/Configuring-Tachyon-with-GlusterFS/start-tachyon.md
- docs/_includes/Configuring-Tachyon-with-GlusterFS/stop-tachyon.md
- docs/_includes/Configuring-Tachyon-with-GlusterFS/underfs-address.md
- docs/cn/Configuring-Tachyon-with-GlusterFS.md
- docs/en/Configuring-Tachyon-with-GlusterFS.md
https://tachyon.atlassian.net/browse/TACHYON-1632
> [TACHYON-1632] Add the Chinese version of documentation page 'Configuring-Tachyon-with-GlusterFS'

- core/server/src/main/java/tachyon/Format.java
- core/server/src/main/java/tachyon/master/MasterFactory.java
- core/server/src/main/java/tachyon/master/TachyonMaster.java
- keyvalue/server/src/main/java/tachyon/master/keyvalue/KeyValueMasterFactory.java
- minicluster/src/main/java/tachyon/master/AbstractLocalTachyonCluster.java
https://tachyon.atlassian.net/browse/TACHYON-1686
> [TACHYON-1686] Centralize logic for finding different master names

- core/client-internal/src/main/java/tachyon/hadoop/AbstractTFS.java
- core/client-internal/src/main/java/tachyon/hadoop/HadoopUtils.java
- core/client-internal/src/test/java/tachyon/hadoop/HadoopUtilsTest.java
https://tachyon.atlassian.net/browse/TACHYON-1558
> [TACHYON-1558] rename tachyon.hadoop.Utils to tachyon.hadoop.HadoopUtils

- docs/cn/Running-Tachyon-on-EC2.md
- docs/en/Running-Tachyon-on-EC2.md
> [SMALLFIX] Update doc to use S3 as default ufs on EC2

- core/client-internal/src/main/java/tachyon/client/block/BlockWorkerClient.java
- core/common/src/main/java/tachyon/Constants.java
- core/server/src/main/java/tachyon/worker/block/BlockWorkerClientServiceHandler.java
> [SMALLFIX} Using consistent naming for service version constant names

- core/common/src/main/java/tachyon/Constants.java
- core/common/src/main/java/tachyon/security/login/AppLoginModule.java
- core/common/src/main/resources/tachyon-default.properties
- docs/en/Configuration-Settings.md
- docs/en/Security.md
JIRA: https://tachyon.atlassian.net/browse/TACHYON-1462
https://tachyon.atlassian.net/browse/TACHYON-1677
Doc security related properties in Configuration-Settings.md.
Doc security features in Security.md.
@apc999 , @yupeng9 , @jsimsa , @sundapeng , would you like to take a look? Your feedbacks are appreciated to improve the doc quality. Thanks!
BTW, I will install Jekyll to generate the doc html and verify the links could navigate well tomorrow.
> [TACHYON-1462] Document security related properties in Configuration-Settings.md

- core/client-internal/src/main/java/tachyon/client/file/BaseFileSystem.java
- core/client-internal/src/main/java/tachyon/client/file/FileInStream.java
- core/client-internal/src/main/java/tachyon/client/file/URIStatus.java
- core/client-internal/src/test/java/tachyon/client/file/FileInStreamTest.java
- core/server/src/main/java/tachyon/web/UIFileInfo.java
- core/server/src/main/java/tachyon/web/WebInterfaceWorkerBlockInfoServlet.java
Removes the temporary getInfo method from URIStatus.
> [SMALLFIX] Remove getInfo from URIStatus

- core/common/src/test/java/tachyon/security/LoginUserTest.java
- core/common/src/test/java/tachyon/security/UserTest.java
https://tachyon.atlassian.net/browse/TACHYON-1700
> [SMALLFIX] [TACHYON-1700] Add unit tests in tachyon.securty.{UserTest, LoginUserTest}

- docs/_includes/Running-Tachyon-on-a-Cluster/bootstrap-conf.md
- docs/_includes/Running-Tachyon-on-a-Cluster/download-extract-Tachyon-tar.md
- docs/_includes/Running-Tachyon-on-a-Cluster/run-tests.md
- docs/_includes/Running-Tachyon-on-a-Cluster/start-Tachyon.md
- docs/_includes/Running-Tachyon-on-a-Cluster/sync-info.md
- docs/cn/Running-Tachyon-on-a-Cluster.md
- docs/en/Running-Tachyon-on-a-Cluster.md
https://tachyon.atlassian.net/browse/TACHYON-1657
> [TACHYON-1657]Add the Chinese version of documentation page 'Running-Tachyon-on-a-Cluster'

- docs/cn/Metrics-System.md
Add the Chinese version of documentation page 'Metrics-System'. See https://tachyon.atlassian.net/browse/TACHYON-1645
The Screencast of the html page is http://www.tachyon-project.org/documentation/master/en/Metrics-System.html. Then choose Chinese version.
> [TACHYON-1645]Add the Chinese version of documentation page 'Metrics-System'

- docs/_data/table/cn/tiered-storage-configuration-parameters.yml
- docs/_data/table/en/tiered-storage-configuration-parameters.yml
- docs/_data/table/tiered-storage-configuration-parameters.csv
- docs/_includes/Tiered-Storage-on-Tachyon/configuration-parameters.md
- docs/_includes/Tiered-Storage-on-Tachyon/evictor-allocator.md
- docs/_includes/Tiered-Storage-on-Tachyon/pin-file.md
- docs/_includes/Tiered-Storage-on-Tachyon/two-tiers.md
- docs/_includes/Tiered-Storage-on-Tachyon/unpin-file.md
- docs/cn/Tiered-Storage-on-Tachyon.md
- docs/en/Tiered-Storage-on-Tachyon.md
https://tachyon.atlassian.net/browse/TACHYON-1659
> [TACHYON-1659]Add the Chinese version of documentation page 'Tiered-Storage-on-Tachyon'

- docs/_includes/Thrift/build-Thrift-port.md
- docs/_includes/Thrift/build-Thrift-ubuntu.md
- docs/_includes/Thrift/download-install-Thrift.md
- docs/_includes/Thrift/install-Boost-brew.md
- docs/_includes/Thrift/install-Boost-port.md
- docs/_includes/Thrift/install-Homebrew.md
- docs/_includes/Thrift/install-Thrift-brew.md
- docs/_includes/Thrift/install-Thrift-port.md
- docs/_includes/Thrift/install-dependency-apt.md
- docs/_includes/Thrift/install-dependency-brew.md
- docs/_includes/Thrift/install-dependency-centos.md
- docs/_includes/Thrift/install-dependency-port.md
- docs/_includes/Thrift/install-dependency-yum.md
- docs/_includes/Thrift/install-lenny-backports.md
- docs/_includes/Thrift/regenerate.md
- docs/_includes/Thrift/update-autoconf.md
- docs/_includes/Thrift/update-port.md
- docs/cn/Thrift.md
- docs/en/Thrift.md
Add the Chinese version of documentation page 'Thrift'. See https://tachyon.atlassian.net/browse/TACHYON-1658
> [TACHYON-1658]Add the Chinese version of documentation page 'Thrift'

- docs/_data/table/LineageParameter.csv
- docs/_data/table/cn/LineageParameter.yml
- docs/_data/table/en/LineageParameter.yml
- docs/_includes/Lineage-API/config-lineage.md
- docs/_includes/Lineage-API/delete-cascade.md
- docs/_includes/Lineage-API/delete-lineage.md
- docs/_includes/Lineage-API/get-lineage-client.md
- docs/cn/Lineage-API.md
- docs/en/Lineage-API.md
Add the Chinese version of documentation page 'Lineage API'. See https://tachyon.atlassian.net/browse/TACHYON-1643
> [TACHYON-1643]Add the Chinese version of documentation page 'Lineage API'

- docs/_includes/Java-Setup/install-jdk-linux.md
- docs/cn/Java-Setup.md
- docs/en/Java-Setup.md
Add the Chinese verion of documentation page 'Java Setup'. See https://tachyon.atlassian.net/browse/TACHYON-1642
> [TACHYON-1642]Add the Chinese verion of documentation page 'Java Setup'

- docs/cn/Integrating-Under-Storage-Systems.md
Add the Chinese version of documentation page 'Integrating Under Storage Systems'. See https://tachyon.atlassian.net/browse/TACHYON-1641
> [TACHYON-1641]Add the Chinese version of doc page 'Integrating Under Storage Systems'

- docs/_includes/Getting-Started/config-application.md
- docs/cn/Getting-Started.md
- docs/en/Getting-Started.md
Add the Chinese version of documentation page 'Getting Started'. See https://tachyon.atlassian.net/browse/TACHYON-1640
> [TACHYON-1640]Add the Chinese version of documentation page 'Getting Started'

- docs/_data/table/Developer-Tips.csv
- docs/_data/table/cn/Developer-Tips.yml
- docs/_data/table/en/Developer-Tips.yml
- docs/_includes/Developer-Tips/install-protobuf.md
- docs/_includes/Developer-Tips/install-thrift.md
- docs/_includes/Developer-Tips/protoGen.md
- docs/_includes/Developer-Tips/thriftGen.md
- docs/cn/Developer-Tips.md
- docs/en/Developer-Tips.md
Add the Chinese version of documentation page of 'Developer Tips'. See https://tachyon.atlassian.net/browse/TACHYON-1638
> [TACHYON-1638]Add the Chinese version of documentation page of 'Developer Tips'

- docs/cn/Architecture.md
Add the Chinese version of documentation page 'Architecture'. See https://tachyon.atlassian.net/browse/TACHYON-1628
> [TACHYON-1628-cn]Add the Chinese version of documentation page 'Architecture'

- docs/_includes/Configuring-Tachyon-with-NFS/copy-tachyon-env.md
- docs/_includes/Configuring-Tachyon-with-NFS/nfs-file.md
- docs/_includes/Configuring-Tachyon-with-NFS/runTests.md
- docs/_includes/Configuring-Tachyon-with-NFS/start-tachyon.md
- docs/_includes/Configuring-Tachyon-with-NFS/stop-tachyon.md
- docs/_includes/Configuring-Tachyon-with-NFS/underfs-address.md
- docs/cn/Configuring-Tachyon-with-NFS.md
- docs/en/Configuring-Tachyon-with-NFS.md
https://tachyon.atlassian.net/browse/TACHYON-1712
> [TACHYON-1712] Added the docs for setting up Tachyon with NFS

- docs/cn/index.md
Improve the index page of the Chinese document.
> [SMALLFIX]Improve the index page of the Chinese doc

- docs/cn/Running-Tachyon-Locally.md
Improve the Running-Tachyon-Locally page of the Chinese document.
> [SMALLFIX]Improve the Running-Tachyon-Locally page of the Chinese doc

- docs/_includes/Running-Hadoop-MapReduce-on-Tachyon/add-jar-libjars.md
- docs/_includes/Running-Hadoop-MapReduce-on-Tachyon/cat-result.md
- docs/_includes/Running-Hadoop-MapReduce-on-Tachyon/compile-Tachyon-Hadoop-test.md
- docs/_includes/Running-Hadoop-MapReduce-on-Tachyon/compile-Tachyon-Hadoop.md
- docs/_includes/Running-Hadoop-MapReduce-on-Tachyon/config-Tachyon.md
- docs/_includes/Running-Hadoop-MapReduce-on-Tachyon/config-core-site.md
- docs/_includes/Running-Hadoop-MapReduce-on-Tachyon/config-hadoop.md
- docs/_includes/Running-Hadoop-MapReduce-on-Tachyon/copy-from-local.md
- docs/_includes/Running-Hadoop-MapReduce-on-Tachyon/run-wordcount.md
- docs/_includes/Running-Hadoop-MapReduce-on-Tachyon/start-Tachyon.md
- docs/_includes/Running-Hadoop-MapReduce-on-Tachyon/start-cluster.md
- docs/cn/Running-Hadoop-MapReduce-on-Tachyon.md
- docs/en/Running-Hadoop-MapReduce-on-Tachyon.md
Add the Chinese version of documentation page 'Hadoop MapReduce'. See https://tachyon.atlassian.net/browse/TACHYON-1648
> [TACHYON-1648]Add the Chinese version of documentation page 'Hadoop MapReduce'

- bin/tachyon-workers.sh
Changed the start/stop from bin/tachyon-workers.sh to be performed asynchronously.
> [TACHYON-1510] Start and stop Tachyon asynchronously

- docs/_includes/Key-Value-Store-API/get-key-value-system.md
Read KVStore code and find a small mismatch between code and the javadoc
> [SMALLFIX] small mismatch between code and doc in KeyValueSystem

- core/server/src/main/java/alluxio/web/WebInterfaceMasterMetricsServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceWorkerMetricsServlet.java
- core/server/src/main/webapp/metrics.jsp
- core/server/src/main/webapp/worker/metrics.jsp
Fix some comments in code to meet the rename of the project.
> [SMALLFIX] Fix some comments in code to meet the rename of the project.

- integration/fuse/pom.xml
- integration/mesos/pom.xml
- integration/yarn/pom.xml
> Update pom parent version on integration module.

- docs/_includes/Running-Spark-on-Alluxio/spark-profile-build.md
- docs/en/Running-Spark-on-Alluxio.md
> [DOCFIX] Improve Framework docs in master

- docs/en/Running-Spark-on-Alluxio.md
> [DOCFIX] Code format alluxio dir.

- docs/_data/table/cn/security-configuration.yml
- docs/_data/table/en/security-configuration.yml
- docs/_data/table/security-configuration.csv
- docs/_includes/Security/lsr.md
- docs/cn/Configuration-Settings.md
- docs/cn/Security.md
- docs/en/Configuration-Settings.md
- docs/en/Security.md
https://tachyon.atlassian.net/browse/ALLUXIO-1719
> [ALLUXIO-1719] translate documentations about Security into Chinese

- docs/cn/Contributing-to-Alluxio.md
Improve chinese documentation of how to contribute to Alluxio. Correct some inconsistent content with the English part.
> [DOCFIX] Improve chinese documentation of how to contribute to Alluxio

- docs/cn/Building-Alluxio-Master-Branch.md
Improve the Building-Alluxio-Master-Branch page of the Chinese doc
> [SMALLFIX]Improve the Building-Alluxio-Master-Branch page of the Chinese doc

- docs/cn/Architecture.md
Improve the Architecture page of the Chinese doc.
> [SMALLFIX]Improve the Architecture page of the Chinese doc

- docs/cn/Lineage-API.md
- docs/cn/Metrics-System.md
Lineage-API.md
Metrics-System.md
>  [DOCFIX] Improve Chinese documentation of a few pages(Lineage-API, Metrics-System) 

- docs/cn/File-System-API.md
- docs/cn/Key-Value-System-API.md
File-System-API
Key-Value-System-API
> [DOCFIX] Improve Chinese documentation of a few pages(File-System-API, Key-Value-System-API)

- docs/cn/Maven.md
- docs/cn/Thrift.md
- docs/cn/Web-Interface.md
Maven.md
Thrift.md
Web-Interface.md
> [DOCFIX] Improve Chinese documentation of a few pages(Maven, Thrift, WebInterface)

- docs/cn/Mounting-Alluxio-FS-with-FUSE.md
- docs/cn/Security.md
- docs/cn/Tiered-Storage-on-Alluxio.md
- docs/cn/Unified-and-Transparent-Namespace.md
Mounting-Alluxio-FS-with-FUSE.md
Security.md
Tiered-Storage-on-Alluxio.md
Unified-and-Transparent-Namespace.md
> [DOCFIX] Improve Chinese documentation of a few pages(FUSE, Security,Tiered-Storage,Transparent-Namespace) 

- docs/cn/Developer-Tips.md
- docs/cn/Getting-Started.md
- docs/cn/Integrating-Under-Storage-Systems.md
Developer-Tips.md
Getting-Started.md
Integrating-Under-Storage-Systems.md
> [DOCFIX] Improve Chinese documentation of a few pages

- docs/cn/Configuring-Alluxio-with-secure-HDFS.md
https://tachyon.atlassian.net/browse/ALLUXIO-1722
> [ALLUXIO-1722] Translate the page Configuring-Alluxio-with-secure-HDFS.md into Chinese

- docs/cn/Accessing-Alluxio-from-Zeppelin.md
- docs/en/Accessing-Alluxio-from-Zeppelin.md
https://tachyon.atlassian.net/browse/ALLUXIO-1721
Also fix the links in the english page
> [ALLUXIO-1721] Translate the page "Accessing-Alluxio-from-Zeppelin.md" into Chinese

- docs/cn/Web-Interface.md
Add the "Master Metric" and "Worker Metric" part in the Chinese Web-Interface page, to make it consistent with the English version.
> [DOCFIX] Improve Chinese documentation of Web-Interface page

- core/common/src/main/java/alluxio/job/CommandLineJob.java
- core/common/src/main/java/alluxio/network/protocol/RPCBlockReadRequest.java
- core/common/src/main/java/alluxio/network/protocol/RPCBlockReadResponse.java
- core/common/src/main/java/alluxio/network/protocol/RPCBlockWriteRequest.java
- core/common/src/main/java/alluxio/network/protocol/RPCBlockWriteResponse.java
- core/common/src/main/java/alluxio/network/protocol/RPCErrorResponse.java
- core/common/src/main/java/alluxio/util/ShellUtils.java
- core/server/src/main/java/alluxio/SessionInfo.java
- core/server/src/main/java/alluxio/master/block/meta/MasterBlockInfo.java
- core/server/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
- core/server/src/main/java/alluxio/master/lineage/checkpoint/CheckpointPlan.java
- core/server/src/main/java/alluxio/master/lineage/meta/Lineage.java
- core/server/src/main/java/alluxio/master/lineage/recompute/RecomputePlan.java
- core/server/src/main/java/alluxio/worker/block/evictor/BlockTransferInfo.java
- core/server/src/main/java/alluxio/worker/block/evictor/EvictionPlan.java
- core/server/src/test/java/alluxio/SessionInfoTest.java
> [SMALLFIX] Using Objects.toStringHelper() as the default toString() mechanism.

- docs/_data/table/cn/LineageParameter.yml
- docs/cn/Architecture.md
- docs/cn/Key-Value-System-API.md
- docs/cn/index.md
LineageParameter.yml
Architecture.md
Key-Value-System-API.md
index.md
> [DOCFIX] Improve Chinese documentation of a few pages(LineageParameter, Architecture,Key-Value,index) 

- docs/_config.yml
Added Portuguese language option to support future translation of docs to Portuguese.
> [ALLUXIO-1727] Added Portuguese language option to site.

- tests/src/test/java/alluxio/shell/command/PinCommandTest.java
Ticket at https://tachyon.atlassian.net/browse/ALLUXIO-1729
> [SMALLFIX] Ignore flaky pin test

- docs/cn/Powered-By-Alluxio.md
- docs/en/Powered-By-Alluxio.md
Added Ultra Tendency to the 'Powered By' page.
> [DOCFIX] Added Ultra Tendency to' Powered By' page

- docs/pt/Architecture.md
Added the Portuguese version of documentation page 'Architecture.md'
> [ALLUXIO-1725] Added the Portuguese version of documentation page 'Architecture.md'

- core/client-internal/src/test/java/alluxio/client/file/FileInStreamTest.java
- core/client-internal/src/test/java/alluxio/client/netty/ClientHandlerTest.java
Removed mockito.times(1) - It is the default
> [ALLUXIO-1710] Remove mockito.times(1)

- core/client-internal/src/test/java/alluxio/client/block/BlockWorkerClientHeartbeatExecutorTest.java
added test coverage described in ALLUXIO-1588
> [ALLUXIO-1588] Add test coverage for WorkerClientHeartbeatExecutor

- core/client-internal/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
This is needed to fix the hadoop-1,hdfsTest build
> [SMALLFIX] Fix test for hadoop-1 environment

- underfs/swift/src/test/java/alluxio/underfs/swift/SwiftOutputStreamTest.java
Added unit tests for SwiftOutputStream
> [ALLUXIO-1591] Added unit test coverage for SwiftOutputStream

- core/client-internal/src/main/java/alluxio/client/lineage/LineageClient.java
Delete the access modifiers 'public' from interface function.
> [SMALLFIX]Delete the access modifiers 'public' from interface function.

- core/server/src/main/java/alluxio/ValidateConf.java
https://tachyon.atlassian.net/browse/ALLUXIO-1747
> [ALLUXIO-1747] Fix bug in validateConf for master side storage alias

- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
> [SMALLFIX] making sure file object creation fails when the object already exists

- core/server/src/main/java/alluxio/web/UIFileInfo.java
https://tachyon.atlassian.net/browse/ALLUXIO-1748
> [ALLUXIO-1748] Fix incompatible type compilation error on Java 8

- tests/src/test/java/alluxio/LocalAlluxioClusterResource.java
- tests/src/test/java/alluxio/shell/AbstractAlluxioShellTest.java
- tests/src/test/java/alluxio/shell/command/CopyFromLocalCommandTest.java
- tests/src/test/java/alluxio/shell/command/MvCommandTest.java
- tests/src/test/java/alluxio/shell/command/PinCommandTest.java
- tests/src/test/java/alluxio/shell/command/RmCommandTest.java
- tests/src/test/java/alluxio/shell/command/RmrCommandTest.java
https://tachyon.atlassian.net/browse/ALLUXIO-1729
> [ALLUXIO-1729] Unflake PincommandTest

- docs/cn/index.md
Update the index page of Chinese documentation with the English version.
> [DOCFIX] Update the index page of Chinese documentation 

- core/server/src/main/java/alluxio/worker/netty/BlockDataServerHandler.java
- core/server/src/main/java/alluxio/worker/netty/DataServerHandler.java
https://alluxio.atlassian.net/projects/ALLUXIO/issues/ALLUXIO-1739
> [ALLUXIO-1739] Move block specific logic to BlockDataServerHandler

- deploy/vagrant/ansible.cfg
https://github.com/Alluxio/alluxio/pull/2823
> [ALLUXIO-1761] Port to master branch for PR 2823

- keyvalue/client/src/main/java/alluxio/client/keyvalue/BaseKeyValueSystem.java
Add "final" keyword for jira #1808 new contributor task.
> [ALLUXIO-1808] Make BaseKeyValueSystem final

- core/client/pom.xml
- keyvalue/client/pom.xml
- pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-1813
> [ALLUXIO-1813] Only apply spark profile for client artifacts

- core/client-internal/src/main/java/alluxio/client/block/AlluxioBlockStore.java
- core/client-internal/src/main/java/alluxio/client/block/RemoteBlockInStream.java
- core/client-internal/src/main/java/alluxio/client/file/FileInStream.java
- core/client-internal/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
- tests/src/test/java/alluxio/client/RemoteBlockInStreamIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1814
> [ALLUXIO-1814] Don't cache to a worker which already has the block

- core/client/src/main/java/alluxio/client/file/FileInStream.java
- core/client/src/main/java/alluxio/client/file/FileOutStream.java
- core/client/src/main/java/alluxio/client/file/FileSystemContext.java
- core/client/src/test/java/alluxio/client/file/FileInStreamTest.java
- core/client/src/test/java/alluxio/client/file/FileOutStreamTest.java
> [SMALLFIX] Fix a typo in FileSystemContext.

- core/client/src/main/java/alluxio/client/netty/ClientHandler.java
1. Remove not used in parameter ctx in handleResponse.
> [ALLUXIO-1788] Remove the unused parameter from handleResponse

- deploy/vagrant/README.md
update the link to Getting-Started page.
> [ALLUXIO-1800] update the link to Getting Start Page

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
add private constructor to class AlluxioFuse
> [Alluxio 1789] Add a private constructor to class AlluxioFuse

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
* A small test PR for new contributor. https://alluxio.atlassian.net/browse/ALLUXIO-1794
* Added newlines to make the javadoc align with the rest of code base
> [ALLUXIO-1794] Improve javadoc in AlluxioFuseFileSystem

- core/server/src/test/java/alluxio/master/file/options/CompleteFileOptionsTest.java
PTAL.
Modified CompleteFileOptionsTest.java, updated the spelling mistake.
> [ALLUXIO-1778] Rename filedsTest() for master CompleteFileOptionsTest

- core/common/src/main/java/alluxio/exception/BlockDoesNotExistException.java
> [ALLUXIO-1793] Improve javadoc in BlockDoesNotExistException

- core/server/src/main/java/alluxio/worker/block/BlockWorkerClientRestServiceHandler.java
Grabbed a ticket from JIRA and removed an obsolete TODO comment.
> [ALLUXIO-1769] Remove completed TODO from BlockWorkerRestServiceHandler

- core/common/src/test/java/alluxio/resource/DummyCloseableResource.java
modify DummyCloseableResource to a final class
> [ALLUXIO-1787] Mark alluxio.resource.DummyCloseableResource final

- core/client-internal/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client-internal/src/main/java/alluxio/hadoop/HdfsFileInputStream.java
- tests/src/test/java/alluxio/hadoop/HdfsFileInputStreamIntegrationTest.java
> [SMALLFIX] Port #2821 to branch-1.0.

- docs/pt/Contributing-to-Alluxio.md
- docs/pt/Running-Alluxio-on-a-Cluster.md
Add the Portuguese version of documentation page "Contributing-to-Alluxio.md" and other nested pages from it.
> [ALLUXIO-1820] Add the Portuguese version of documentation page "Contributing-to-Alluxio.md"

- conf/alluxio-site.properties.template
- docs/en/Configuration-Settings.md
Sample alluxio properties template in conf/ to help easily
use and tune for the user
> [ALLUXIO-1803] Add alluxio-site.properties.template

- core/common/src/test/java/alluxio/util/IdUtilsTest.java
Add two unit tests for IdUtils.
mvn test passed.
> [ALLUXIO-1776] Add unit tests for IdUtils

- minicluster/src/main/java/alluxio/master/LocalAlluxioMaster.java
Update comment in alluxio.master.LocalAlluxioMaster#kill
> Update comment in alluxio.master.LocalAlluxioMaster#kill

- docs/cn/index.md
Update the index page of Chinese documentation with the English version.
> [DOCFIX] Update the index page of Chinese documentation

- docs/cn/File-System-API.md
Update the File-System-API page of Chinese documentation with the English version.
> [DOCFIX] Update the File-System-API page of Chinese documentation

- core/client/src/main/java/alluxio/client/block/BlockWorkerClient.java
- core/client/src/main/java/alluxio/client/block/RemoteBlockInStream.java
- core/client/src/main/java/alluxio/client/block/RemoteBlockOutStream.java
Also delete an error logic which is to increment metrics in RemoteBlockInStream because the increment logic is already exist in BufferedBlockInStream.
> [ALLUXIO-1821][ALLUXIO-1822]Fix a bug in which the metric of RemoteBlockXXXStream is incorrect 

- core/common/src/main/java/alluxio/Constants.java
- core/common/src/main/java/alluxio/security/authentication/AuthenticationUtils.java
- core/common/src/main/resources/alluxio-default.properties
- core/common/src/test/java/alluxio/ConfigurationTest.java
- docs/_data/table/cn/common-configuration.yml
- docs/_data/table/common-configuration.csv
- docs/_data/table/en/common-configuration.yml
Cherry-pick https://github.com/Alluxio/alluxio/pull/2830 to branch-1.0
> Revert "[ALLUXIO-1749] Make thrift largest frame size adjustable"

- core/client-internal/src/main/java/alluxio/client/file/FileInStream.java
This leads to confusing output when stack traces are printed but there actually isn't a problem. Only adding this for `BlockAlreadyExists` for now.
> [SMALLFIX] Do not show exception on acceptable warning.

- core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-1785
> [ALLUXIO-1785] Improve exception handling in AbstractFileSystem

- docs/_includes/Running-Spark-on-Alluxio/alluxio-hdfs-in-out-scala.md
- docs/_includes/Running-Spark-on-Alluxio/alluxio-local-in-out-scala.md
- docs/_includes/Running-Spark-on-Alluxio/alluxio-one-partition.md
- docs/_includes/Running-Spark-on-Alluxio/any-Alluxio-master.md
- docs/_includes/Running-Spark-on-Alluxio/fault-tolerant-mode-with-zookeeper-bash.md
- docs/_includes/Running-Spark-on-Alluxio/foo.md
- docs/_includes/Running-Spark-on-Alluxio/license-hdfs.md
- docs/_includes/Running-Spark-on-Alluxio/license-local.md
- docs/cn/Running-Spark-on-Alluxio.md
- docs/en/Running-Spark-on-Alluxio.md
Clarifies certain behaviors and removes unnecessary lines.
> [DOCFIX] Clarify Spark and Alluxio docs

- docs/_includes/Running-Hadoop-MapReduce-on-Alluxio/run-wordcount.md
- docs/en/Running-Hadoop-MapReduce-on-Alluxio.md
Adds where to get the map reduce examples.
> [DOCFIX] Update Map-Reduce Docs

- docs/en/Running-Alluxio-Locally.md
Clarify the steps to set up passwordless ssh.
> [SMALLFIX] Add a link to a passwordless ssh tutorial.

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
I've opened https://alluxio.atlassian.net/browse/ALLUXIO-1830 which should clean up this logic when implemented.
> [SMALLFIX] Enforce Mount does not exist in Alluxio

- core/client/pom.xml
- docs/_includes/Running-Flink-on-Alluxio/flink-profile-build.md
- docs/_includes/Running-Flink-on-Alluxio/license.md
- docs/_includes/Running-Flink-on-Alluxio/wordcount.md
- docs/en/Running-Flink-on-Alluxio.md
- keyvalue/client/pom.xml
- pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-1832
> [ALLUXIO-1832] Update Flink Profile and Documentation

- tests/pom.xml
Fixing the failing integration tests
> [SMALLFIX] Fix failing test BufferedBlockInStreamIntegrationTest

- core/server/src/main/java/alluxio/master/lineage/LineageMasterClientRestServiceHandler.java
r.t. Trivial update as NewContributer.
> [ALLUXIO-1770] Remove completed TODO from LineageMasterRestServiceHandler

- core/client-internal/src/main/java/alluxio/client/UfsUtils.java
- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
- tests/src/test/java/alluxio/client/UfsUtilsIntegrationTest.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
Updates the load ufs script to use load metadata and changes some implementation in s3 client to handle load metadata.
> [ALLUXIO-1760] Load Ufs Fix

- core/client/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
[ALLUXIO-1771] Made corrections of TFS to Alluxio FS in AbstractFileSystemTest
> [ALLUXIO-1771] Corrected TFS to Alluxio FS in AbstractFileSystemTest

- core/common/src/main/java/alluxio/security/authorization/PermissionStatus.java
https://alluxio.atlassian.net/browse/ALLUXIO-1828
> [ALLUXIO-1828] [SMALLFIX] Use SecurityUtils.isAuthenticationEnabled everywhere.

- core/client-internal/src/main/java/alluxio/client/block/LocalBlockOutStream.java
- core/server/src/main/java/alluxio/worker/block/BlockWorker.java
https://alluxio.atlassian.net/browse/ALLUXIO-1836
> [ALLUXIO-1836] Worker creates tiered storage files

- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
- keyvalue/client/src/main/java/alluxio/client/keyvalue/BaseKeyValueStoreWriter.java
- keyvalue/client/src/main/java/alluxio/client/keyvalue/KeyValuePartitionWriter.java
- tests/src/test/java/alluxio/client/keyvalue/KeyValueSystemIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1556
Modify the BaseKeyValueStoreWriter to prevent adding same key multiple times. A test method is also added.
> [ALLUXIO-1556] Prevent adding same key multiple times

- core/common/src/main/java/alluxio/util/io/PathUtils.java
- core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-1833
> [ALLUXIO-1833] Consolidate normalizePath method in S3UnderFileSystem

- keyvalue/client/src/main/java/alluxio/client/keyvalue/BaseKeyValuePartitionReader.java
https://alluxio.atlassian.net/browse/ALLUXIO-1786  Use .isEmpty to check the collection is empty or not in BaseKeyValuePartitionReader.java
> [ALLUXIO-1786] update function to isEmpty()

- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
- shell/src/main/java/alluxio/shell/command/CopyFromLocalCommand.java
- tests/src/test/java/alluxio/shell/command/CopyFromLocalCommandTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1753
> [ALLUXIO-1753] Extend the copyFromLocal command and add the support of folder copy

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1830
> [ALLUXIO-1830] Provide boolean methods in InodeTree to check if an inode exists.

- examples/src/main/java/alluxio/examples/Performance.java
https://alluxio.atlassian.net/browse/ALLUXIO-1838
> [ALLUXIO-1838] Fix a few issues in alluxio.examples.Performance

- docs/cn/Powered-By-Alluxio.md
Update the Powered-By-Alluxio page of Chinese documentation
> [DOCFIX] Update the Powered-By-Alluxio page of Chinese documentation

- docs/cn/Configuration-Settings.md
Sync the Configuration-Settting page of Chinese documentation with the English version.
> [DOCFIX] Update the Configuration-Settting page of Chinese documentation

- docs/cn/Accessing-Alluxio-from-Zeppelin.md
Sync the Accessging-Alluxio-from-Zeppelin page of Chinese documentation with the English version.
> [DOCFIX] Update the Accessging-Alluxio-from-Zeppelin page of Chinese documentat

- docs/en/Debugging-Guide.md
https://alluxio.atlassian.net/browse/ALLUXIO-1839
> [ALLUXIO-1839] Add a Debugging-Guide doc

- tests/src/test/java/alluxio/shell/command/LsCommandTest.java
> [SMALLFIX] Fix failing tests

- core/server/src/main/webapp/browse-body.jsp
- core/server/src/main/webapp/browse-pagination-header.jsp
- core/server/src/main/webapp/browse.jsp
- core/server/src/main/webapp/configuration.jsp
- core/server/src/main/webapp/dependency.jsp
- core/server/src/main/webapp/footer-scripts.jsp
- core/server/src/main/webapp/footer.jsp
- core/server/src/main/webapp/general.jsp
- core/server/src/main/webapp/header-scripts.jsp
- core/server/src/main/webapp/header.jsp
- core/server/src/main/webapp/memory-pagination-header.jsp
- core/server/src/main/webapp/memory.jsp
- core/server/src/main/webapp/metrics-summary.jsp
- core/server/src/main/webapp/metrics.jsp
- core/server/src/main/webapp/pagination-component.jsp
- core/server/src/main/webapp/pagination-control.jsp
- core/server/src/main/webapp/viewFile-body.jsp
- core/server/src/main/webapp/viewFile.jsp
- core/server/src/main/webapp/worker/blockInfo-pagination-header.jsp
- core/server/src/main/webapp/worker/blockInfo.jsp
- core/server/src/main/webapp/worker/browse.jsp
- core/server/src/main/webapp/worker/general.jsp
- core/server/src/main/webapp/worker/metrics-summary.jsp
- core/server/src/main/webapp/worker/metrics.jsp
- core/server/src/main/webapp/worker/viewFile.jsp
- core/server/src/main/webapp/worker/viewFileBlocks.jsp
- core/server/src/main/webapp/workers.jsp
https://alluxio.atlassian.net/browse/ALLUXIO-1841
The WebUI now displays normally.
> [ALLUXIO-1841] Change the comment symbols in licenses of the jsp files

- tests/src/test/java/alluxio/client/keyvalue/KeyValueSystemIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1843
> [ALLUXIO-1843] Remove codes using createStoreOfMultiplePartitions in KeyValueSystemIntegrationTest#createMultiPartitionsTest

- core/server/src/main/java/alluxio/web/WebInterfaceBrowseServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceDownloadServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceWorkerBlockInfoServlet.java
https://tachyon.atlassian.net/browse/ALLUXIO-1600
> [ALLUXIO-1600] update docs for the exceptions

- bin/alluxio-fuse.sh
- bin/alluxio-mount.sh
- bin/alluxio-start.sh
- bin/alluxio-stop.sh
- bin/alluxio-workers.sh
> [SMALLFIX] Improve shell code style in bin.

- keyvalue/client/src/main/java/alluxio/client/keyvalue/BaseKeyValueStoreReader.java
https://alluxio.atlassian.net/browse/ALLUXIO-1842
Improve the inefficient for-loop to binary search in BaseKeyValueStoreReader#get()
> [ALLUXIO-1842] Improve the inefficient for-loop to binary search in BaseKeyValueStoreReader#get()

- core/server/src/main/java/alluxio/worker/block/BlockLockManager.java
- core/server/src/main/java/alluxio/worker/block/BlockMetadataManagerView.java
- core/server/src/test/java/alluxio/worker/block/BlockLockManagerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1846
> [ALLUXIO-1846] Switch from block worker lock striping to lock pool

- docs/pt/Configuring-Alluxio-with-Swift.md
- docs/pt/Getting-Started.md
- docs/pt/Running-Alluxio-on-EC2.md
- docs/pt/Running-Flink-on-Alluxio.md
- docs/pt/Running-Spark-on-Alluxio.md
- docs/pt/index.md
Add the Portuguese version of documentation page "index.md" and other nested pages
> [ALLUXIO-1860] Add the Portuguese version of documentation page "index.md" 

- keyvalue/server/src/main/java/alluxio/worker/keyvalue/KeyValueWorkerClientServiceHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-1847
here  is the screenshot of the bug I encounter:
> [SMALLFIX] Fix "Too many open files " exception in KeyValueWorkerClientServiceHandler#getReader

- deploy/vagrant/provision/roles/alluxio/tasks/compile.yml
https://alluxio.atlassian.net/browse/ALLUXIO-1861
> [ALLUXIO-1861] [SMALLFIX] Extend compile alluxio timeout to 30min, due to slow vb downloading

- tests/src/test/java/alluxio/client/IsolatedFileSystemIntegrationTest.java
- tests/src/test/java/alluxio/client/RemoteBlockInStreamIntegrationTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
- tests/src/test/java/alluxio/shell/command/PinCommandTest.java
- tests/src/test/java/alluxio/worker/DataServerIntegrationTest.java
- tests/src/test/java/alluxio/worker/block/meta/TieredStoreIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1863
https://alluxio.atlassian.net/browse/ALLUXIO-1729
> [ALLUXIO-1863][ALLUXIO-1729] Deflake tests with time based periodical heartbeats

- core/common/src/main/java/alluxio/security/authorization/PermissionStatus.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/file/FileSystemMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
- core/server/src/main/java/alluxio/master/file/PermissionChecker.java
- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/src/main/java/alluxio/master/lineage/LineageMaster.java
- core/server/src/main/java/alluxio/web/WebInterfaceBrowseServlet.java
- core/server/src/test/java/alluxio/master/MasterSourceTest.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- core/server/src/test/java/alluxio/master/file/PermissionCheckTest.java
- core/server/src/test/java/alluxio/master/file/PermissionCheckerTest.java
- core/server/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
- keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMaster.java
- tests/src/test/java/alluxio/client/FileSystemIntegrationTest.java
- tests/src/test/java/alluxio/master/JournalIntegrationTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterClientRestApiTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
- tests/src/test/java/alluxio/shell/command/LsCommandTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1762
> [ALLUXIO-1762] Refactor FileSystemMaster to better organize security related parts

- perf/bin/alluxio-perf
- perf/src/main/java/alluxio/perf/benchmark/metadata/MetadataThread.java
- perf/src/main/java/alluxio/perf/benchmark/simpleread/SimpleReadThread.java
- perf/src/main/java/alluxio/perf/benchmark/simplewrite/SimpleWriteThread.java
https://alluxio.atlassian.net/browse/ALLUXIO-1865
This is an additional PR for https://github.com/Alluxio/alluxio/pull/2992
The first commit fixes the ssh connect (for remote launch).
The second commit fixes the getFileSystem (get the correct fs and now it can test HDFS).
> [ALLUXIO-1865] [Alluxio-Perf] Fix perf branch

- core/server/src/main/java/alluxio/worker/block/BlockLockManager.java
- core/server/src/main/java/alluxio/worker/block/ClientRWLock.java
This PR fixes the race conditions mentioned in the ticket by adding reference counting to the ClientRWLock.
https://alluxio.atlassian.net/browse/ALLUXIO-1867
> [ALLUXIO-1867] Fix race conditions in block lock manager

- core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
- core/common/src/test/java/alluxio/heartbeat/HeartbeatContextTest.java
- core/common/src/test/java/alluxio/heartbeat/HeartbeatThreadTest.java
- core/common/src/test/java/alluxio/heartbeat/ManuallyScheduleHeartbeat.java
- core/server/pom.xml
- core/server/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/src/test/java/alluxio/master/MasterSourceTest.java
- core/server/src/test/java/alluxio/master/block/BlockMasterTest.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- tests/src/test/java/alluxio/client/FileOutStreamAsyncWriteIntegrationTest.java
- tests/src/test/java/alluxio/client/FreeAndDeleteIntegrationTest.java
- tests/src/test/java/alluxio/client/IsolatedFileSystemIntegrationTest.java
- tests/src/test/java/alluxio/client/RemoteBlockInStreamIntegrationTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
- tests/src/test/java/alluxio/master/lineage/LineageMasterIntegrationTest.java
- tests/src/test/java/alluxio/shell/command/FreeCommandTest.java
- tests/src/test/java/alluxio/shell/command/PinCommandTest.java
- tests/src/test/java/alluxio/worker/BlockServiceHandlerIntegrationTest.java
- tests/src/test/java/alluxio/worker/DataServerIntegrationTest.java
- tests/src/test/java/alluxio/worker/block/meta/TieredStoreIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1870
This PR fixes the ALLUXIO-1870 bug by resetting back to automatic scheduling at the end of each test.
> [ALLUXIO-1870] Add rule for manual heartbeat scheduling

- core/common/src/main/java/alluxio/collections/DirectedAcyclicGraph.java
- core/common/src/test/java/alluxio/collections/DirectedAcyclicGraphTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1799
Add unit test for alluxio.collections.DirectedAcyclicGraph
> [ALLUXIO-1799] Add unit test for alluxio.collections.DirectedAcyclicGraph

- tests/pom.xml
- tests/src/test/java/alluxio/underfs/gcs/GCSUnderStorageCluster.java
https://alluxio.atlassian.net/browse/ALLUXIO-1824
> [ALLUXIO-1824] Add integration tests for GCS as UnderFileSystem

- deploy/vagrant/Vagrantfile
- deploy/vagrant/conf/ufs.yml
- deploy/vagrant/core/EnvSetup.rb
- deploy/vagrant/core/config_google.rb
- deploy/vagrant/provision/roles/alluxio/tasks/config.yml
- deploy/vagrant/provision/roles/spark/files/remove_gcs_exclusion.sh
- deploy/vagrant/provision/roles/spark/tasks/compile.yml
- deploy/vagrant/provision/roles/ufs_gcs/files/compile_alluxio.sh
- deploy/vagrant/provision/roles/ufs_gcs/files/compile_spark.sh
- deploy/vagrant/provision/roles/ufs_gcs/files/config_alluxio.sh
- deploy/vagrant/provision/roles/ufs_gcs/tasks/config.yml
- deploy/vagrant/provision/roles/ufs_gcs/tasks/download_release.yml
- deploy/vagrant/provision/roles/ufs_gcs/tasks/rsync_dist.yml
- deploy/vagrant/provision/roles/ufs_gcs/tasks/start.yml
- deploy/vagrant/provision/roles/ufs_hadoop1/files/config_alluxio.sh
- deploy/vagrant/provision/roles/ufs_hadoop2/files/config_alluxio.sh
- deploy/vagrant/provision/roles/ufs_s3/files/config_alluxio.sh
- docs/_includes/Running-Alluxio-on-GCE/access-key.md
- docs/en/Running-Alluxio-on-GCE.md
https://alluxio.atlassian.net/browse/ALLUXIO-1824
This PR:
- makes the default underfs for gce deployement to be Google Cloud Storage. 
- updates the GCE doc with GCS environment setup requirements.
- is tested with a deployment on GCE.
> [ALLUXIO-1824] Make GCE deployment use GCS as default underfs

- bin/alluxio-start.sh
Mostly to address Jiri's comment to follow Google bash style guide or Alluxio's bash convection.
> [ALLUXIO-1871] Change alluxio-start.sh to follow Google bash style guide

- core/common/src/main/java/alluxio/util/io/BufferUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-1877
> [ALLUXIO-1877] Making BufferUtils thread safe.

- deploy/vagrant/provision/roles/alluxio/files/alluxio_jar.sh
- deploy/vagrant/provision/roles/lib/files/maven.sh
These commits cherry-picked from master are needed to successfully run the deploy module.
> [SMALLFIX] Fix deploy module

- core/client/src/main/java/alluxio/client/block/UnderStoreBlockInStream.java
- core/client/src/test/java/alluxio/client/block/UnderStoreBlockInStreamTest.java
- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
https://alluxio.atlassian.net/browse/ALLUXIO-1864
> [ALLUXIO-1864] UnderStoreBlockInStream tests and fixes

- core/client/src/main/java/alluxio/client/file/BaseFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-1780
> [ALLUXIO-1780] Add logging to the loadMetadata command in BaseFileSystem

- core/client/src/main/java/alluxio/client/file/BaseFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-1782
> [ALLUXIO-1782] Add logging to the set attribute command in BaseFileSystem

- minicluster/pom.xml
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- minicluster/src/main/java/alluxio/master/LocalAlluxioMaster.java
- pom.xml
- tests/src/test/java/alluxio/master/block/BlockMasterClientRestApiTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterClientRestApiTest.java
- tests/src/test/java/alluxio/master/lineage/LineageMasterClientRestApiTest.java
- tests/src/test/java/alluxio/worker/block/BlockWorkerClientRestApiTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1717
> [ALLUXIO-1717] Fix REST API tests

- core/server/src/main/java/alluxio/master/block/BlockMaster.java
Followup to a comment unaddressed in https://github.com/Alluxio/alluxio/pull/3000.
> [SMALLFIX] Improve error message

- core/common/src/main/java/alluxio/AlluxioURI.java
- core/common/src/main/java/alluxio/MultiPartSchemeURI.java
- core/common/src/main/java/alluxio/StandardURI.java
- core/common/src/main/java/alluxio/URI.java
- core/common/src/main/java/alluxio/util/URIUtils.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/common/src/test/java/alluxio/AlluxioURITest.java
- core/server/src/main/java/alluxio/master/file/meta/MountTable.java
- shell/src/main/java/alluxio/shell/AlluxioShellUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-1879
> [ALLUXIO-1879] Improve AlluxioURI with additional functionality

- perf/src/main/java/alluxio/perf/benchmark/iterate/IterateThread.java
- perf/src/main/java/alluxio/perf/benchmark/massive/MassiveThread.java
- perf/src/main/java/alluxio/perf/benchmark/mixture/MixtureThread.java
https://alluxio.atlassian.net/browse/ALLUXIO-1880
The Iterate, Massive and Mixture workloads in alluxio-perf currently use the default block size, read/write type, but not the configured ones.
This PR adds mBlockSize, mReadType and mWriteType to these workloads and make them work.
> [ALLUXIO-1880] [Alluxio-Perf] Use the configured block size, read type and write type

- core/client/src/main/java/alluxio/client/file/BaseFileSystem.java
> [ALLUXIO-1779] Add logging to the free command in BaseFileSystem

- docs/_config.yml
- docs/pt/index.md
Two minor modifications, one to fit the site categories correctly and the other one is to fix 'Current Features' frame.
> [DOCFIX] Portuguese site modification

- tests/src/test/java/alluxio/master/block/BlockMasterClientRestApiTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterClientRestApiTest.java
- tests/src/test/java/alluxio/master/lineage/LineageMasterClientRestApiTest.java
- tests/src/test/java/alluxio/worker/block/BlockWorkerClientRestApiTest.java
These tests break the hdfs builds, see https://alluxio.atlassian.net/browse/ALLUXIO-1888
> [SMALLFIX] Ignore broken tests

- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
- underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-1872
> [ALLUXIO-1854] Update UFS block size bytes calls

- docs/cn/Running-Alluxio-Locally.md
- docs/pt/Running-Alluxio-Locally.md
Followup to https://github.com/Alluxio/alluxio/pull/3003 to fix `jekyll build`
> [DOCFIX] Fix jekyll includes

- bin/alluxio
- deploy/vagrant/Vagrantfile
- deploy/vagrant/conf/alluxio.yml
- deploy/vagrant/core/EnvSetup.rb
- deploy/vagrant/provision/roles/alluxio/files/set_master_address.sh
- deploy/vagrant/provision/roles/alluxio/files/set_master_address_old.sh
- deploy/vagrant/provision/roles/alluxio/tasks/config.yml
Since bootstrap conf was not working in the older version of Alluxio, this changes the deploy script to use the old logic for older releases.
> [SMALLFIX] Backward compatibility for deploy script

- core/common/src/main/java/alluxio/util/FormatUtils.java
- core/common/src/test/java/alluxio/util/FormatUtilsTest.java
- core/server/src/main/java/alluxio/RestUtils.java
- core/server/src/main/java/alluxio/RpcUtils.java
- core/server/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
- core/server/src/main/java/alluxio/master/block/BlockMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/master/file/FileSystemMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/master/lineage/LineageMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
- core/server/src/main/java/alluxio/worker/block/BlockWorkerClientRestServiceHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-1889
`/` should not be escaped, which is fixed by this PR
> [ALLUXIO-1889] Fixing JSON encoding.

- core/common/src/main/java/alluxio/collections/ConcurrentHashSet.java
- core/common/src/main/java/alluxio/collections/IndexedSet.java
- core/common/src/test/java/alluxio/collections/IndexedSetTest.java
- core/server/src/main/java/alluxio/master/file/meta/InodeDirectory.java
- tests/src/test/java/alluxio/collections/IndexedSetConcurrencyTest.java
- tests/src/test/java/alluxio/collections/IndexedSetIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1885
> [ALLUXIO-1885] Improve concurrency of IndexedSet

- docs/en/Configuring-Alluxio-with-S3.md
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystemFactory.java
[ALLUXIO-1882](https://alluxio.atlassian.net/browse/ALLUXIO-1882)
> [ALLUXIO-1882] Enable using EC2 Instance profile for S3 Access

- core/common/src/main/java/alluxio/network/protocol/RPCFileReadRequest.java
- core/common/src/main/java/alluxio/network/protocol/RPCFileReadResponse.java
- core/common/src/main/java/alluxio/network/protocol/RPCFileWriteRequest.java
- core/common/src/main/java/alluxio/network/protocol/RPCFileWriteResponse.java
- core/common/src/main/java/alluxio/network/protocol/RPCMessage.java
- core/server/src/main/java/alluxio/worker/AlluxioWorker.java
- core/server/src/main/java/alluxio/worker/DataServer.java
- core/server/src/main/java/alluxio/worker/netty/DataServerHandler.java
- core/server/src/main/java/alluxio/worker/netty/FileDataServerHandler.java
- core/server/src/main/java/alluxio/worker/netty/NettyDataServer.java
- core/server/src/test/java/alluxio/network/protocol/RPCFileReadRequestTest.java
- core/server/src/test/java/alluxio/network/protocol/RPCFileReadResponseTest.java
- core/server/src/test/java/alluxio/network/protocol/RPCFileWriteRequestTest.java
- core/server/src/test/java/alluxio/network/protocol/RPCFileWriteResponseTest.java
- core/server/src/test/java/alluxio/worker/block/SpaceReserverTest.java
Creates 4 new RPC messages, File (Read/Write) (Request/Response). They are currently unused and will be used in later PRs.
> [ALLUXIO-1739] Add Dataserver messages for ufs operations

- bin/alluxio
> [SMALLFIX] Fix format error in bin/alluxio

- core/client/pom.xml
- core/client/src/test/java/alluxio/client/file/options/CompleteFileOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/CreateDirectoryOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/CreateFileOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/DeleteOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/FreeOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/InStreamOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/LoadMetadataOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/MountOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/OpenFileOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/OutStreamOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/SetAttributeOptionsTest.java
- core/common/pom.xml
- core/common/src/main/java/alluxio/security/authorization/PermissionStatus.java
- core/common/src/test/java/alluxio/CommonTestUtils.java
- core/common/src/test/java/alluxio/CommonTestUtilsTest.java
- core/server/pom.xml
- core/server/src/test/java/alluxio/master/file/options/CompleteFileOptionsTest.java
- core/server/src/test/java/alluxio/master/file/options/CreateDirectoryOptionsTest.java
- core/server/src/test/java/alluxio/master/file/options/CreateFileOptionsTest.java
- core/server/src/test/java/alluxio/master/file/options/MountOptionsTest.java
- core/server/src/test/java/alluxio/master/file/options/SetAttributeOptionsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1896
> [ALLUXIO-1896] test equals and hashCode for options

- core/client/src/main/java/alluxio/client/block/RemoteBlockInStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-1900
> [ALLUXIO-1900] Verify something was read when closing RemoteBlockInStream

- docs/_config.yml
To fit the site, I've change again Portuguese Categories. And to set a standard, the English and Portugues Categories were all modified to plural.
> [DOCFIX] Changed Portuguese and English Categories

- tests/src/test/java/alluxio/client/FreeAndDeleteIntegrationTest.java
- tests/src/test/java/alluxio/shell/command/FreeCommandTest.java
See https://alluxio.atlassian.net/browse/ALLUXIO-1907
> [SMALLFIX] Ignore flaky tests

- docs/cn/Running-Alluxio-on-GCE.md
Update the Running-Alluxio-on-GCE page of Chinese Doc with the English version.
> [DOCFIX] Update the Running-Alluxio-on-GCE page of Chinese Doc.

- docs/cn/Running-Alluxio-Locally.md
- docs/cn/Unified-and-Transparent-Namespace.md
Update the Running-Alluxio-Locally and Unified-and-Transparent-Namespace page of Chinese Doc.
> [DOCFIX] Update the Running-Loally and Unified-Namespace page of Chinese Doc.

- core/client/pom.xml
- core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client/src/main/java/alluxio/hadoop/ConfUtils.java
- core/client/src/main/java/alluxio/hadoop/HadoopUtils.java
- underfs/swift/pom.xml
Would like to add Swift to the Alluxio client. Otherwise Swift underfs is not working with Spark.
> [ALLUXIO-1852] Adding Swift to the alluxio client

- core/common/src/main/java/alluxio/collections/DirectedAcyclicGraph.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/file/async/DefaultAsyncPersistHandler.java
- core/server/src/main/java/alluxio/master/lineage/meta/LineageStore.java
- core/server/src/main/java/alluxio/worker/block/BlockLockManager.java
- core/server/src/main/java/alluxio/worker/block/BlockStoreMeta.java
- core/server/src/main/java/alluxio/worker/block/allocator/RoundRobinAllocator.java
- core/server/src/main/java/alluxio/worker/file/FileDataManager.java
- examples/src/main/java/alluxio/examples/keyvalue/KeyValueStoreOperations.java
- tests/src/test/java/alluxio/worker/block/BlockWorkerClientRestApiTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1819
This is JIRA is still work in progress and needs more PRs.
> [ALLUXIO-1819] Used diamond operator instead of Guava's shorthand

- core/client/src/test/java/alluxio/client/file/MockFileInStream.java
- core/client/src/test/java/alluxio/client/file/MockFileOutStream.java
Handy for testing classes which use FileInStream/FileOutStream
> [SMALLFIX] Add mock file in and out streams

- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
This ticket tracks fixing this test: https://alluxio.atlassian.net/browse/ALLUXIO-1914
> [SMALLFIX] Ignore flaky test

- core/client/src/main/java/alluxio/client/block/UnderStoreBlockInStream.java
- core/client/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/client/src/main/java/alluxio/client/file/FileInStream.java
- core/client/src/main/java/alluxio/client/file/UnknownFileInStream.java
- core/client/src/main/java/alluxio/client/file/UnknownLengthFileInStream.java
- core/client/src/test/java/alluxio/client/block/UnderStoreBlockInStreamTest.java
- core/common/src/main/java/alluxio/Constants.java
- core/server/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/src/main/java/alluxio/master/block/meta/MasterBlockInfo.java
- core/server/src/main/java/alluxio/master/file/meta/InodeFile.java
- core/server/src/test/java/alluxio/master/file/meta/InodeFileTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1915
> [ALLUXIO-1915] Enable support for reading UFS files of unknown length

- core/common/src/main/java/alluxio/util/io/PathUtils.java
- core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
This will be applied in later PRs.
> [SMALLFIX] Add path subtraction utility

- tests/src/test/java/alluxio/master/AlluxioMasterRestApiTest.java
- tests/src/test/java/alluxio/master/block/BlockMasterClientRestApiTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterClientRestApiTest.java
- tests/src/test/java/alluxio/master/lineage/LineageMasterClientRestApiTest.java
- tests/src/test/java/alluxio/worker/block/BlockWorkerClientRestApiTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1888
> [ALLUXIO-1888] Fix rest API tests

- core/common/src/main/java/alluxio/collections/IndexedSet.java
- core/common/src/test/java/alluxio/collections/IndexedSetTest.java
- core/server/src/main/java/alluxio/master/block/BlockMaster.java
This makes it easier to use IndexedSet in conjunction with standard library functions.
> [SMALLFIX] Implement Set with IndexedSet

- tests/src/test/java/alluxio/IntegrationTestUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-1916
We'll see if increasing this timeout prevents flakiness
> [ALLUXIO-1916] Increase waitForPersist timeout

- examples/src/main/java/alluxio/examples/JournalCrashTest.java
[SMALLFIX]https://alluxio.atlassian.net/browse/ALLUXIO-1773 : Update comment in alluxio.examples.JournalCrashTest
> [ALLUXIO-1773] Update comment in alluxio.examples.JournalCrashTest

- core/server/src/main/java/alluxio/worker/block/BlockMasterSync.java
https://alluxio.atlassian.net/browse/ALLUXIO-1899
> [ALLUXIO-1899] Avoid generate multiple BlockRemover threads for deleting locked blocks

- tests/src/test/java/alluxio/master/lineage/LineageMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1916
> [ALLUXIO-1916] fix flaky lineageCompleteAndAsyncPersistTest

- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1831
> [ALLUXIO-1831] Add Unit Tests for mount logic in FileSystemMaster

- underfs/s3/src/main/java/alluxio/underfs/s3/S3OutputStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-1897
Upload large file to S3 using Multipart: https://aws.amazon.com/blogs/aws/amazon-s3-multipart-upload/. The threshold can probably be configurable..
> [ALLUXIO-1897] use Multipart to upload large file to S3

- docs/cn/Powered-By-Alluxio.md
- docs/en/Powered-By-Alluxio.md
- docs/pt/Powered-By-Alluxio.md
Hi everyone,
this PR is for adding my company Radicalbit to the 'PoweredBy' list.
We are using Alluxio as a storage layer in our fast data distribution.
More information can be found at http://radicalbit.io/
Best,
Saverio
> [DOCFIX] add radicalbit to the powered-by companies list

- core/client/src/test/java/alluxio/client/file/BaseFileSystemTest.java
- core/common/src/main/java/alluxio/Constants.java
- core/server/src/main/java/alluxio/master/AlluxioMaster.java
- core/server/src/main/java/alluxio/web/MasterUIWebServer.java
- core/server/src/main/java/alluxio/web/WorkerUIWebServer.java
- core/server/src/main/java/alluxio/worker/AlluxioWorker.java
- adding a unit test for listStatus
- cleaning up master and worker comments and messages
> [SMALLFIX] adding a unit test and cleaning up messages and comments

- docs/_includes/Building-Alluxio-Master-Branch/checkout.md
Skipping tests when building alluxio for the first time.
> [DOCFIX] Skip tests in building alluxio instructions

- core/client/src/main/java/alluxio/client/block/BlockMasterClient.java
Removed an explicit type argument in the *BlockMasterClient* class.
> [SMALLFIX] Removed explicit type argument in BlockMasterClient

- core/server/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/lineage/LineageMaster.java
- core/server/src/main/java/alluxio/web/MasterUIWebServer.java
- core/server/src/main/java/alluxio/web/WebInterfaceAbstractMetricsServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceBrowseServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceConfigurationServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceDependencyServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceDownloadLocalServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceDownloadServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceGeneralServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceWorkerBlockInfoServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceWorkerGeneralServlet.java
- core/server/src/main/java/alluxio/web/WorkerUIWebServer.java
- core/server/src/main/java/alluxio/worker/block/BlockWorker.java
- core/server/src/main/java/alluxio/worker/block/TieredBlockStore.java
- core/server/src/main/webapp/worker/general.jsp
- this PR cleans up minor nits in the web UI
- this PR makes uses of <> more efficient
> [SMALLFIX] Web UI and <> cleanup

- docs/cn/Configuring-Alluxio-with-S3.md
Update the Configuring-Alluxio-with-S3 page of Chinese Doc.
> [DOCFIX] Update the Configuring-Alluxio-with-S3 page of Chinese Doc.

- core/common/src/main/java/alluxio/underfs/UnderFileSystemRegistry.java
* Replaced all instances of <UnderFileSystemFactory> with <> for conciseness. 
https://alluxio.atlassian.net/browse/ALLUXIO-1934
> [ALLUXIO-1934] Replaced <UnderFileSystemFactory> with <>

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-1924
> [ALLUXIO-1924] Fix typo in javadoc of alluxio.master.file.FileSystemMaster#getFileInfoInternal

- core/common/src/main/java/alluxio/security/authentication/AuthenticatedClientUser.java
https://alluxio.atlassian.net/browse/ALLUXIO-1931
> [ALLUXIO-1931] replace verbose instantiation

- core/common/src/main/java/alluxio/security/group/provider/ShellBasedUnixGroupsMapping.java
https://alluxio.atlassian.net/browse/ALLUXIO-1932
> [ALLUXIO-1932] succinct diamond operator

- core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-1933
> [ALLUXIO-1933] use <> operator

- tests/src/test/java/alluxio/client/StreamOptionUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-1920
> [ALLUXIO-1920] Improve javadoc in alluxio.client.StreamOptionUtils

- core/common/src/main/java/alluxio/collections/PrefixList.java
https://alluxio.atlassian.net/browse/ALLUXIO-1926
> [ALLUXIO-1926] use <> operator

- docs/README.md
Hi there! Wanted to submit a small PR to get the feel for it. Thanks!
> [DOCFIX] Updated docs/README syntax

- core/server/src/main/java/alluxio/worker/block/BlockWorker.java
https://alluxio.atlassian.net/browse/ALLUXIO-1922
collapsed identical catches to multi-catch
> [ALLUXIO-1922] collapsed identical catches to multi-catch

- core/server/src/main/java/alluxio/master/block/BlockMaster.java
(Trivial fix) Alluxio-1930. Use message defined in ExceptionMessage for the exception
> Alluxio-1930. Use message defined in ExceptionMessage for the exception

- core/client/src/test/java/alluxio/client/file/URIStatusTest.java
[Alluxio-1938] Add unit tests for URIStatus
https://alluxio.atlassian.net/browse/ALLUXIO-1938
> [Alluxio-1938] Add unit tests for URIStatus

- core/client/src/main/java/alluxio/client/file/FileSystemUtils.java
Removed a redundant initializer in the *FileSystemUtils* class.
> [SMALLFIX] Removed redundant initializer in FileSystemUtils

- core/client/src/test/java/alluxio/client/block/UnderStoreBlockInStreamTest.java
Fixed documentation and removed unnecessary additions in the *UnderStoreBlockInStreamTest* class.
> [SMALLFIX] Fixed docs and removed unnecessary additions

- core/client/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
Removed the unnecessary boxing and converted fields to local variables in the *AlluxioBlockStoreTest* class.
> [SMALLFIX] Removed unnecessary boxing and converted fields to local variables in AlluxioBlockStoreTest

- shell/src/main/java/alluxio/shell/command/TailCommand.java
- tests/src/test/java/alluxio/shell/command/TailCommandTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1919
Alluxio-1919. Add -c option to alluxio.shell.command.TailCommand
> [ALLUXIO-1919] Add -c option to alluxio.shell.command.TailCommand

- underfs/swift/pom.xml
JOSS version is updated to 0.9.10
>  [SMALLFIX] Update JOSS version number

- core/common/src/main/java/alluxio/security/login/AlluxioLoginModule.java
- core/common/src/main/java/alluxio/security/login/AppLoginModule.java
- core/server/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
- core/server/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/src/main/java/alluxio/master/file/async/AsyncPersistHandler.java
- core/server/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
- core/server/src/main/java/alluxio/worker/block/BlockLockManager.java
- core/server/src/main/java/alluxio/worker/block/allocator/Allocator.java
- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
- keyvalue/client/src/main/java/alluxio/client/keyvalue/BaseKeyValueSystem.java
- shell/src/main/java/alluxio/shell/AlluxioShellUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-1322
Prepared some classes for the upcoming MissingCtor rule in Checkstyle. It checks that classes (except abstract ones) define a constructor and don't rely on the default one. The rule will look like the following
<module name="MissingCtor"/>
This ticket is WIP and needs some additional PRs.
> [ALLUXIO-1322][WIP] Prepared classes for MissingCtor rule in Checkstyle

- core/common/src/main/java/alluxio/wire/FileInfo.java
> [SMALLFIX] Fix the FileInfo construction to be 1.0.1 compatible

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftOutputStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-1945
> [ALLUXIO-1945] Log an error when Swift output stream does not successfully close.

- core/common/src/main/java/alluxio/security/login/AlluxioLoginModule.java
Removed a redundant initializer in the *AlluxioLoginModule* class.
> [SMALLFIX] Removed redundant initializer in AlluxioLoginModule

- core/common/src/main/java/alluxio/collections/DirectedAcyclicGraph.java
After the while loop,the "toVisit" set must be empty, we should check the "input".
> [SMALLFIX] Use the wrong set which should be "input"

- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/test/java/alluxio/master/MasterSourceTest.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1947
> [ALLUXIO-1947] Throw an exception when delete fails

- core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
- core/common/src/main/java/alluxio/util/io/FileUtils.java
- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-1952
> [ALLUXIO-1952] Add SetOwner in UFS

- core/common/src/main/java/alluxio/exception/AlluxioException.java
> [SMALLFIX] Added exception type back for compatibility with 1.0.x

- core/server/pom.xml
This fixes runtime exception when generating REST API documentation.
> [SMALLFIX] bumping up version of REST API generation

- core/common/src/main/java/alluxio/heartbeat/HeartbeatScheduler.java
First commit to update little code to follow the java code style. Thanks
> [ALLUXIO-1927] Use <> operator efficiently in HeartBeatScheduler.java

- core/server/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
- core/server/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
- tests/pom.xml
- tests/src/test/java/alluxio/master/AlluxioMasterRestApiTest.java
- tests/src/test/java/alluxio/master/block/BlockMasterClientRestApiTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterClientRestApiTest.java
- tests/src/test/java/alluxio/master/lineage/LineageMasterClientRestApiTest.java
- tests/src/test/java/alluxio/worker/AlluxioWorkerRestApiTest.java
- tests/src/test/java/alluxio/worker/block/BlockWorkerClientRestApiTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1888
Cannot reproduce this problem. But fix another issue (RestServiceHandlers should have non-private constructors)
> [ALLUXIO-1888] Re-enable Restful API tests

- core/common/src/main/java/alluxio/Constants.java
- core/common/src/main/resources/alluxio-default.properties
- core/server/src/main/java/alluxio/master/AbstractMaster.java
- core/server/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/src/main/java/alluxio/master/block/meta/MasterBlockInfo.java
- core/server/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
- core/server/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
https://alluxio.atlassian.net/browse/ALLUXIO-1913
> [ALLUXIO-1913] Improve scalability of the BlockMaster

- core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
Removed some explicit parameter types in the *UnderFileSystem* class.
> [SMALLFIX] Removed explicit parameter types in UnderFileSystem

- core/client/src/test/java/alluxio/client/lineage/LineageFileSystemTest.java
Converted some fields to local variables in the *LineageFileSystemTest* class.
> [SMALLFIX] Converted fields to local variables

- core/server/src/main/java/alluxio/worker/block/meta/StorageDir.java
Removed some explicit type arguments in the *StorageDir* class.
> [SMALLFIX] Removed explicit type arguments in StorageDir

- core/server/src/main/java/alluxio/worker/block/TieredBlockStore.java
Removed an explicit type argument in the *TieredBlockStore* class.
> [SMALLFIX] Removed explicit type argument in TieredBlockStore

- bin/alluxio-start.sh
- integration/bin/alluxio-yarn-setup.sh
To convert "=" to "==" in bash scripts.
> [Alluxio-1940][SMALLFIX]Consistent equals in bash scripts

- core/server/src/main/java/alluxio/worker/block/meta/StorageDirView.java
Removed some explicit type arguments in the *StorageDirView* class.
> [SMALLFIX] Removed explicit type arguments in StorageDirView

- core/client/src/test/java/alluxio/client/file/options/ExistsOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/GetStatusOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/ListStatusOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/RenameOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/UnmountOptionsTest.java
- core/client/src/test/java/alluxio/client/file/policy/LocalFirstPolicyTest.java
- core/client/src/test/java/alluxio/client/file/policy/MostAvailableFirstPolicyTest.java
- core/client/src/test/java/alluxio/client/file/policy/RoundRobinPolicyTest.java
- core/client/src/test/java/alluxio/client/file/policy/SpecificHostPolicyTest.java
Added several test cases for the client file package.
> [ALLUXIO-872] Added test cases for the client file package

- core/server/src/main/java/alluxio/Sessions.java
Removed some explicit type arguments in the *Sessions* class.
> [SMALLFIX] Removed explicit type arguments in Sessions

- core/server/src/test/java/alluxio/worker/block/evictor/EvictorTestUtils.java
Removed some explicit type arguments in the *EvictorTestUtils* class.
> [SMALLFIX] Removed explicit type arguments in EvictorTestUtils

- core/server/src/test/java/alluxio/worker/block/meta/AbstractBlockMetaTest.java
Made a field a local variable in the *AbstractBlockMetaTest* class.
> [SMALLFIX] Made field a local variable in AbstractBlockMetaTest

- core/server/src/test/java/alluxio/worker/block/meta/BlockMetaTest.java
Made a field a local variable in the *BlockMetaTest* class.
> [SMALLFIX] Made field a local variable in BlockMetaTest

- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- minicluster/src/main/java/alluxio/underfs/UnderFileSystemCluster.java
https://alluxio.atlassian.net/browse/ALLUXIO-1950
> [ALLUXIO-1950] Clean up temporary testing directories

- core/common/src/main/java/alluxio/heartbeat/HeartbeatScheduler.java
- core/common/src/main/java/alluxio/heartbeat/ScheduledTimer.java
- core/common/src/main/java/alluxio/resource/LockResource.java
- core/common/src/main/java/alluxio/resource/ResourcePool.java
- core/common/src/test/java/alluxio/resource/LockResourceTest.java
- core/server/src/main/java/alluxio/master/file/meta/InodeLockList.java
- core/server/src/main/java/alluxio/master/file/meta/MountTable.java
- core/server/src/main/java/alluxio/worker/block/TieredBlockStore.java
This PR create LockResource, which makes it possible to acquire and release locks using the try-with-resources idiom.
> [SMALLFIX] creating LockResource

- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- minicluster/src/main/java/alluxio/underfs/UnderFileSystemCluster.java
Reverts Alluxio/alluxio#3229
This caused build breakage - will revert while fixing
> Revert "[ALLUXIO-1950] Clean up temporary testing directories"

- core/common/src/main/java/alluxio/Constants.java
- docs/_includes/Configuring-Alluxio-with-S3/server-side-encryption.md
- docs/en/Configuring-Alluxio-with-S3.md
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
Addresses https://alluxio.atlassian.net/browse/ALLUXIO-1959
> [ALLUXIO-1959] Add S3 server-side-encryption support.

- conf/alluxio-site.properties.template
Add the new option to the template file.
> [SMALLFIX] Update properties template for ufs ops delegation.

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/src/main/java/alluxio/master/file/meta/MountTable.java
This method fixes an issue with journal compaction, that would cause mount points disappear across multiple restarts.
> [SMALLFIX] Adding mount table journal compaction.

- core/server/src/test/java/alluxio/worker/block/meta/StorageDirViewTest.java
Made a field a local variable in the *StorageDirViewTest* class.
> [SMALLFIX] Made field a local variable in StorageDirViewTest

- core/common/src/main/java/alluxio/AbstractClient.java
based on https://github.com/Alluxio/alluxio/pull/3329 by fixing the update of `mConnected`
> [SMALLFIX] fixing a possible resource leak in AbstractClient

- docs/_includes/Running-Spark-on-Alluxio/license-hdfs.md
- docs/en/Running-Spark-on-Alluxio.md
Add under storage address fixes
> [DOCFIX] Update Spark docs

- core/client/src/main/java/alluxio/client/netty/NettyUnderFileSystemFileReader.java
- core/common/src/main/java/alluxio/network/protocol/RPCFileReadRequest.java
- core/common/src/main/java/alluxio/network/protocol/RPCFileReadResponse.java
- core/server/src/main/java/alluxio/worker/netty/UnderFileSystemDataServerHandler.java
- core/server/src/test/java/alluxio/network/protocol/RPCFileReadRequestTest.java
Buffers on the server side before sending to the client.
> [SMALLFIX] Optimize UFS Dataserver Read

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
Do not load metadata if the file exists.
> [SMALL FIX] Fix load metadata bugs

- core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
> Properly initialize hadoop client fields

- core/server/src/main/java/alluxio/master/file/async/AsyncPersistHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-1921
> [ALLUXIO-1921] Move logging to the correct scope

- shell/src/main/java/alluxio/cli/AlluxioShell.java
Removed an explicit argument type in the *AlluxioShell* class.
> [SMALLFIX] Removed explicit argument type in AlluxioShell

- core/server/src/main/java/alluxio/worker/block/meta/StorageTier.java
moved from https://github.com/Alluxio/alluxio/pull/3378
> [SMALLFIX] Fix spurious delete failure message

- core/server/src/main/java/alluxio/master/block/BlockMaster.java
- tests/src/test/java/alluxio/client/FreeAndDeleteIntegrationTest.java
- tests/src/test/java/alluxio/shell/AlluxioShellUtilsTest.java
- tests/src/test/java/alluxio/shell/command/FreeCommandTest.java
The BlockRemover in BlockWorker is executed asynchronously, so in test we need to wait for all of the involved blocks being removed.
> [ALLUXIO-1907] fix and unignore free tests

- tests/src/test/java/alluxio/hadoop/HdfsFileInputStreamIntegrationTest.java
Converted a field to a local variable in the *HdfsFileInputStreamIntegrationTest* class.
> [SMALLFIX] Converted field to local variable in HdfsFileInputStreamIntegrationTest

- shell/src/main/java/alluxio/shell/AlluxioShellUtils.java
Removed some explicit argument types and a redundant initializer in the *AlluxioShellUtils* class.
> [SMALLFIX] Removed explicit argument types and redundant initializer in AlluxioShellUtils

- core/server/src/test/java/alluxio/StorageTierAssocTest.java
- core/server/src/test/java/alluxio/worker/block/BlockMetadataManagerTest.java
- core/server/src/test/java/alluxio/worker/block/BlockStoreMetaTest.java
- core/server/src/test/java/alluxio/worker/block/BlockWorkerTest.java
- core/server/src/test/java/alluxio/worker/block/evictor/LRFUEvictorTest.java
- core/server/src/test/java/alluxio/worker/file/FileWorkerMasterSyncExecutorTest.java
- core/server/src/test/java/com/google/common/util/concurrent/MockRateLimiter.java
- examples/src/main/java/alluxio/cli/JournalCrashTest.java
- shell/src/main/java/alluxio/shell/command/TailCommand.java
- tests/src/test/java/alluxio/hadoop/fs/DFSIOIntegrationTest.java
Small clean up of some classes in the *core*, *tests*, *shell* and *examples* package.
> [SMALLFIX] Clean up in core, tests, shell and examples module

- core/common/src/main/java/alluxio/AbstractMasterClient.java
- docs/_data/table/cn/operation-command.yml
- docs/_data/table/en/operation-command.yml
- docs/_data/table/operation-command.csv
- docs/_includes/Command-Line-Interface/leader.md
- docs/cn/Command-Line-Interface.md
- docs/en/Command-Line-Interface.md
- shell/src/main/java/alluxio/shell/command/LeaderCommand.java
- tests/src/test/java/alluxio/shell/command/LeaderCommandTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1490
> [ALLUXIO-1490] Add a command to output current leader master

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
- core/server/src/main/java/alluxio/master/file/meta/TtlBucketList.java
- core/server/src/main/java/alluxio/master/journal/JournalTool.java
- core/server/src/main/java/alluxio/master/lineage/LineageMasterClientServiceHandler.java
- core/server/src/main/java/alluxio/master/lineage/meta/LineageStore.java
- core/server/src/main/java/alluxio/metrics/MetricsConfig.java
- core/server/src/main/java/alluxio/metrics/MetricsSystem.java
- core/server/src/main/java/alluxio/web/UIFileBlockInfo.java
- core/server/src/main/java/alluxio/web/UIFileInfo.java
- core/server/src/main/java/alluxio/web/WebInterfaceBrowseLogsServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceConfigurationServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceGeneralServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceMasterMetricsServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceMemoryServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceWorkerGeneralServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceWorkerMetricsServlet.java
- core/server/src/main/java/alluxio/worker/block/evictor/AbstractEvictor.java
- core/server/src/main/java/alluxio/worker/block/evictor/EvictionDirCandidates.java
- core/server/src/main/java/alluxio/worker/block/evictor/GreedyEvictor.java
Small clean up of some classes in the *core* module.
> [SMALLFIX] Clean up in core module

- core/server/src/main/java/alluxio/master/lineage/recompute/RecomputePlan.java
remove the extra "in" before "in parallel" in RecomputePlan Line 28:
https://alluxio.atlassian.net/browse/ALLUXIO-1988
> [ALLUXIO-1988]remove the extra  words

- core/common/src/main/java/alluxio/LeaderInquireClient.java
[ALLUXIO-1989]Remove useless parentheses in LeaderInquireClient#getMasterAddress
https://alluxio.atlassian.net/browse/ALLUXIO-1989
> [ALLUXIO-1989]Remove useless parentheses in LeaderInquireClient#getMasterAddress

- core/server/src/main/java/alluxio/worker/WorkerSource.java
[ALLUXIO-1992] remotelly->remotely in WorkerSource
https://alluxio.atlassian.net/browse/ALLUXIO-1992?jql=labels%20%3D%20NewContributor
> [ALLUXIO-1992] remotelly->remotely in WorkerSource

- docs/en/Running-Alluxio-Fault-Tolerant-on-EC2.md
https://alluxio.atlassian.net/browse/ALLUXIO-2003
Update "Browse File System" to "Browse" in docs/en/Running-Alluxio-Fault-Tolerant-on-EC2.md
> [DOCFIX] browse file system to browse

- docs/cn/Web-Interface.md
This PR fixes issue with JIRA ticket ALLUXIO-2002
i update "Browse File System" to "Browse" in docs/cn/Web-Interface.md to be consistent with the Web UI navigation bar
> [DOCFIX] Update "Browse File System" to "Browse" in docs/cn/Web-Interface.md to be consistent with the Web UI navigation bar

- docs/cn/Running-Alluxio-on-EC2.md
ALLUXIO-2000
https://alluxio.atlassian.net/browse/ALLUXIO-2000?jql=labels%20%3D%20NewContributor
> [DOCFIX] Update "Browse File System" to "Browse" in docs/cn/Running-Alluxio-on-EC2.md to be consistent with the Web UI navigation bar

- docs/cn/Running-Alluxio-Locally.md
https://alluxio.atlassian.net/browse/ALLUXIO-2004
> [DOCFIX]Update "Browse File System" to "Browse" in docs/en/Running-Alluxio-Locally.md to be consistent with the Web UI navigation bar

- docs/cn/Running-Alluxio-Locally.md
Update "Browse File System" to "Browse" in docs/cn/Running-Alluxio-Fault-Tolerant-on-EC2.md to be consistent with the navigation bar.
> update brower file system to brower

- docs/cn/Running-Alluxio-Fault-Tolerant-on-EC2.md
https://alluxio.atlassian.net/browse/ALLUXIO-1996
Update "Browse File System" to "Browse" in docs/cn/Running-Alluxio-Fault-Tolerant-on-EC2.md to be consistent with the navigation bar
> [DOCFIX] Update "Browse File System" to "Browse" in docs/cn/Running-Alluxio-Fault-Tolerant-on-EC2.md to be consistent with the navigation bar

- docs/en/Web-Interface.md
https://alluxio.atlassian.net/browse/ALLUXIO-2006
Update "Browse File System" to "Browse" in docs/en/Web-Interface.md to be consistent with the Web UI navigation bar
> [DOCFIX] Update "Browse File System" to "Browse"

- docs/en/Web-Interface.md
https://alluxio.atlassian.net/browse/ALLUXIO-2006
ALLUXIO-2006
Update "Browse File System" to "Browse" in docs/en/Web-Interface.md to be consistent with the Web UI navigation bar
> [DOCFIX]Update "Browse File System" to "Browse"

- docs/cn/Configuring-Alluxio-with-GlusterFS.md
NanJing University Hackathon
https://alluxio.atlassian.net/browse/ALLUXIO-1978
> [DOCFIX] add one command in cn docs

- docs/cn/Web-Interface.md
change "system configuration" to "configuration"
https://alluxio.atlassian.net/browse/ALLUXIO-2009?filter=-4
> [DOXFIX] delete System 

- docs/en/Web-Interface.md
This PR fixes issue with JIRA ticket ALLUXIO-2002
https://alluxio.atlassian.net/browse/ALLUXIO-2002
Update "Browse File System" to "Browse" in docs/cn/Web-Interface.md to be consistent with the Web UI navigation bar
> [DOCFIX] [ALLUXIO-2002]Update "Browse File System" to "Browse" in docs/cn/Web-Interface.md to be consistent with the Web UI navigation bar

- docs/cn/Running-Alluxio-on-Virtual-Box.md
Update "Browse File System" to "Browse" in docs/cn/Running-Alluxio-on-Virtual-Box.md to be consistent with the Web UI navigation bar
The links is: https://alluxio.atlassian.net/browse/ALLUXIO-2001
> [DOCFIX]Update "Browse File System" to "Browse" in docs/cn/Running-Alluxio-on-Virtual-Box.md to be consistent with the Web UI navigation bar

- docs/cn/Running-Alluxio-on-EC2.md
https://alluxio.atlassian.net/browse/ALLUXIO-1999
> [DOCFIX] Change "System Configuration" to "Configuration"

- docs/cn/Running-Hadoop-MapReduce-on-Alluxio.md
[This jira ticket is for Nanjing Hackathon.](https://alluxio.atlassian.net/browse/ALLUXIO-1984?filter=-4)
In the section of Running Hadoop wordcount with Alluxio Locally in docs/en/Running-Hadoop-MapReduce-on-Alluxio.md, there's a statement saying "depends on the hadoop version, you might need to replace ./bin with ./sbin". Update it in the corresponding page of the Chinese version.
> [DOCFIX] [ALLUXIO-1984] Modify cn-doc in docs/cn/Running-Hadoop-Mapreduce-on-Alluxio

- integration/bin/alluxio-mesos.sh
- integration/bin/alluxio-yarn-setup.sh
- integration/bin/alluxio-yarn.sh
- libexec/alluxio-config.sh
Found some more instances of writing error messages to stdout instead of stderr.
> [SMALLFIX] Write error messages to stderr

- core/common/src/test/java/alluxio/ConfigurationTest.java
Updates the unit test value to be the new one.
> [SMALLFIX] Config test update

- underfs/oss/src/test/java/alluxio/underfs/oss/OSSOutputStreamTest.java
The junit test case for OSSOutputSteam. Thanks
> [ALLUXIO-1586] Add test coverage for OSSOutputStream.java

- conf/alluxio-site.properties.template
As https://github.com/Alluxio/alluxio/pull/3451 discussed, we should disable the delegation. In addition, I got a timeout issue when running MapReduce with the use of delegation.
```Java
INFO mapreduce.Job: Task Id : attempt_1465596856169_0003_m_000147_0, Status : FAILED
Error: java.io.IOException: java.util.concurrent.TimeoutException: Timeout waiting for task.
at alluxio.client.netty.NettyUnderFileSystemFileWriter.write(NettyUnderFileSystemFileWriter.java:103)
at alluxio.client.file.UnderFileSystemFileOutStream.writeToWorker(UnderFileSystemFileOutStream.java:161)
at alluxio.client.file.UnderFileSystemFileOutStream.flush(UnderFileSystemFileOutStream.java:85)
at alluxio.client.file.UnderFileSystemFileOutStream.close(UnderFileSystemFileOutStream.java:75)
at …
```
> [SMALLFIX] Disable delegation on alluxio-site.properties.template

- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2014
> [ALLUXIO-2014] Reduce log severity in S3 UFS

- tests/src/test/java/alluxio/IntegrationTestUtils.java
- tests/src/test/java/alluxio/client/FileInStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/LocalBlockInStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/RemoteBlockInStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/concurrent/ConcurrencyTestUtils.java
Minor fixes in the **test** module.
*IntegrationTestUtils*: Fixed link in documentation and introduced automatic resource management in try statement.
*FileInStreamIntegrationTest*: Introduced automatic resource management in try statement.
*LocalBlockInStreamIntegrationTest*: Introduced automatic resource management in try statement.
*RemoteBlockInStreamIntegrationTest*: Introduced automatic resource management in try statement.
*ConcurrencyTestUtils*: Fixed documentation.
> [SMALLFIX] Clean up in the test module

- keyvalue/client/src/main/java/alluxio/client/keyvalue/BaseKeyValueStoreReader.java
- keyvalue/client/src/main/java/alluxio/hadoop/mapreduce/KeyValueOutputCommitter.java
Minor fixes in the **keyvalue** module.
*BaseKeyValueStoreReader*: Introduced automatic resource management in try statement
*KeyValueOutputCommitter*: Fixed deprecation
> [SMALLFIX] Clean up in the keyvalue module

- underfs/glusterfs/src/main/java/alluxio/underfs/glusterfs/GlusterFSUnderFileSystemFactory.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystemFactory.java
- underfs/swift/src/main/java/alluxio/underfs/swift/http/SwiftDirectClient.java
Minor fixes in the **test** module.
*GlusterFSUnderFileSystemFactory*: Simplified return statement.
*HdfsUnderFileSystem*: Converted field into local variable.
*HdfsUnderFileSystemFactory*: Simplified return statement.
*SwiftDirectClient*: Simplified exception handling.
> [SMALLFIX] Clean up in the underfs module

- core/client/src/test/java/alluxio/client/RemoteBlockWriterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1597
Implemented test for RemoteBlockWriter.Factory
> [ALLUXIO-1597] Test for RemoteBlockWriter.Factory

- core/server/src/main/java/alluxio/master/MasterContext.java
https://alluxio.atlassian.net/browse/ALLUXIO-1553
> [ALLUXIO-1553] remove redundant documentation with @return

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
Addresses https://alluxio.atlassian.net/browse/ALLUXIO-2017
> [ALLUXIO-2017] Reduce log severity in Swift UFS

- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
Addresses https://alluxio.atlassian.net/browse/ALLUXIO-2018
> [ALLUXIO-2018] Reduce log severity in GCS UFS

- docs/cn/Configuring-Alluxio-with-S3.md
> [DOCFIX] fix caps issue with directory name

- core/common/src/main/java/alluxio/util/FormatUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-2029
> [ALLUXIO-2029] Use StringBuilder instead of StringBuffer to avoid unnecessary synchronization

- tests/src/test/java/alluxio/worker/AlluxioWorkerRestApiTest.java
A follow-up PR for https://github.com/Alluxio/alluxio/pull/3570
> [SMALLFIX] Add a test case for the REST API to get worker configuration

- core/common/src/main/java/alluxio/network/protocol/databuffer/DataByteBuffer.java
- core/server/src/main/java/alluxio/worker/netty/BlockDataServerHandler.java
- core/server/src/main/java/alluxio/worker/netty/ReleasableResourceChannelListener.java
https://alluxio.atlassian.net/browse/ALLUXIO-2022
> [ALLUXIO-2022] Fix potential memory leak in remote read 

- core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
- core/common/src/main/java/alluxio/wire/MountPointInfo.java
- core/common/src/test/java/alluxio/wire/MountPointInfoTest.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/file/FileSystemMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/master/file/meta/MountTable.java
- core/server/src/main/java/alluxio/master/file/meta/options/MountInfo.java
- core/server/src/test/java/alluxio/master/file/meta/MountTableTest.java
- core/server/src/test/java/alluxio/master/file/meta/options/MountInfoTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2030
Information about Alluxio mount points includes ufs url, ufs storage usage, ufs type, and mount point configurations.
> [ALLUXIO-2030] Add a new REST endpoint for getting mount points

- docs/en/Powered-By-Alluxio.md
Updated text to allow for quick editing link
> [DOCFIX] Update edit link

- docs/cn/index.md
Update the index page of Chinese docs with the English version
> [DOCFIX]Update the index page of Chinese docs with the English version

- docs/cn/Running-Alluxio-Fault-Tolerant-on-EC2.md
- docs/cn/Running-Alluxio-on-EC2-Yarn.md
Update EC2 related Chinese docs with the English version
> [DOCFIX]Update EC2 related Chinese docs with the English version

- docs/cn/Getting-Started.md
- docs/cn/Powered-By-Alluxio.md
Update the Get-Started and Powered-By Chinese docs with the English version
> [DOCFIX]Update the Get-Started and Powered-By Chinese docs with the English version

- core/common/src/main/resources/alluxio-default.properties
- docs/_data/table/cluster-management.csv
- integration/mesos/src/main/java/alluxio/mesos/AlluxioFramework.java
https://alluxio.atlassian.net/browse/ALLUXIO-2040
> [ALLUXIO-2040] Make the Mesos principal property optional

- core/server/src/main/java/alluxio/Sessions.java
- core/server/src/test/java/alluxio/worker/block/BlockWorkerTest.java
Fix the issue: https://alluxio.atlassian.net/browse/ALLUXIO-2037. I have tested with : mvn test  &&  mvn checkstyle:checkstyle && mvn checkstyle:checkstyle
> [ALLUXIO-2037] Mark alluxio.Sessions class final

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
Addresses: https://alluxio.atlassian.net/browse/ALLUXIO-2039
> [ALLUXIO-2039] Fixing mounting of Swift directories.

- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Addresses: https://alluxio.atlassian.net/browse/ALLUXIO-2042
> [ALLUXIO-2042] Fix mounting for OSS

- docs/cn/Web-Interface.md
https://alluxio.atlassian.net/browse/ALLUXIO-2009
Update "System Configuration" to "Configuration" in docs/cn/Web-Interface.md to be consistent with the Web UI navigation bar
> [DOCFIX] [ALLUXIO-2009] Update "System Configuration" to "Configuration"

- core/client/src/main/java/alluxio/hadoop/HdfsFileInputStream.java
- tests/src/test/java/alluxio/hadoop/HdfsFileInputStreamIntegrationTest.java
Addresses: https://groups.google.com/forum/#!topic/alluxio-users/7nbVt7aF8no
> [SMALLFIX] adding support for HdfsFileInputStream.available()

- integration/yarn/src/test/java/alluxio/yarn/ApplicationMasterTest.java
I'm currently working on fixing this test. This is to unblock other PRs.
> [SMALLFIX] Ignore broken ApplicationMaster test

- integration/yarn/pom.xml
- integration/yarn/src/test/java/alluxio/yarn/ApplicationMasterTest.java
Simple change to reset the configuration after tests modify it
> [SMALLFIX] Clean up configuration changes after ApplicationMasterTests

- integration/bin/alluxio-mesos.sh
- integration/mesos/src/main/java/alluxio/mesos/AlluxioFramework.java
- integration/mesos/src/main/java/alluxio/mesos/AlluxioMasterExecutor.java
- integration/mesos/src/main/java/alluxio/mesos/AlluxioWorkerExecutor.java
- integration/mesos/src/main/java/alluxio/mesos/OfferUtils.java
Make use of logger in the Mesos framework
> [SMALLFIX] Improved Mesos framework logging

- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2049
> [ALLUXIO-2049] Fix lock upgrade when locking a pair of paths

- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
- underfs/gcs/src/test/java/alluxio/underfs/gcs/GCSUnderFileSystemTest.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
- underfs/s3/src/test/java/alluxio/underfs/s3/S3UnderFileSystemTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2035
This is a continuation of PR #3615
> [ALLUXIO-2047] Surfacing non-Alluxio directories from object storage

- docs/en/Web-Interface.md
https://alluxio.atlassian.net/browse/ALLUXIO-2008
> [ALLUXIO-2008][DOCFIX] Update 'System Configuration' to 'Configuration'

- core/common/src/main/java/alluxio/security/authentication/NoSaslTransportProvider.java
https://alluxio.atlassian.net/browse/ALLUXIO-2055
> [ALLUXIO-2055] Fixed javadoc for NoSaslTransportProvider

- core/common/src/main/java/alluxio/resource/CloseableResource.java
https://alluxio.atlassian.net/browse/ALLUXIO-2054
> [ALLUXIO-2054] Fixed CloseableResource javadoc syntax

- docs/en/Running-Flink-on-Alluxio.md
Addresses: https://alluxio.atlassian.net/browse/ALLUXIO-2060
> [ALLUXIO-2060] [DOCFIX] Improve flink docs.

- core/client/src/main/java/alluxio/client/file/FileSystemUtils.java
Fixed javadoc.
see: https://alluxio.atlassian.net/browse/ALLUXIO-2056?filter=13700
> [DOCFIX] Fix javadoc for FileSystemUtils.waitCompleted

- core/client/src/main/java/alluxio/client/ClientContext.java
- core/client/src/main/java/alluxio/client/file/FileSystemUtils.java
- core/common/src/main/java/alluxio/util/CommonUtils.java
- core/server/src/main/java/alluxio/master/FaultTolerantAlluxioMaster.java
- core/server/src/main/java/alluxio/worker/file/FileSystemWorker.java
- tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2067
Before this change, running the integration tests built up around 1000 threads. After the change, it is closer to 500.
> [ALLUXIO-2067] Clean up leaked threads

- tests/src/test/java/alluxio/master/JournalIntegrationTest.java
- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2072
> [ALLUXIO-2072] Support group/owner in object stores

- core/client/src/main/java/alluxio/hadoop/ConfUtils.java
- core/client/src/main/java/alluxio/hadoop/HadoopUtils.java
- core/client/src/test/java/alluxio/hadoop/ConfUtilsTest.java
- core/common/src/main/java/alluxio/Constants.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystemUtils.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystemFactory.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2082
> [ALLUXIO-2082] Allow s3a credentials to be stored in site properties

- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
- underfs/gcs/src/test/java/alluxio/underfs/gcs/GCSUnderFileSystemTest.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/oss/src/test/java/alluxio/underfs/oss/OSSUnderFileSystemTest.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
- underfs/s3/src/test/java/alluxio/underfs/s3/S3UnderFileSystemTest.java
[ALLUIXO-2073] Consolidate stripFolderSuffixIfPresent mothed into Util
https://alluxio.atlassian.net/browse/ALLUXIO-2073
> [ALLUXIO-2073] Consolidate stripFolderSuffixIfPresent methed into Util

- tests/src/test/java/alluxio/collections/IndexedSetConcurrencyTest.java
I added two concurrent unit tests for indexedSet. Namely tested the correctness of non-unique index.
> [SMALLFIX] Add two concurrent unit tests for indexedSet

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
A more efficient listRecursive call is also added.
JIRA ticket: https://alluxio.atlassian.net/browse/ALLUXIO-2089
> [ALLUXIO-2089] Pagination support for large directories in Swift

- core/server/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/src/main/java/alluxio/master/file/meta/InodeDirectory.java
- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/src/main/java/alluxio/worker/file/UnderFileSystemManager.java
- core/server/src/test/java/alluxio/master/block/BlockMasterPrivateAccess.java
- core/server/src/test/java/alluxio/master/block/BlockMasterTest.java
There is no need to new an index definition every time. Make them static can save some memory.
> [SMALLFIX] Make index definition static

- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2075
> [ALLUXIO-2075] Consolidate stripPrefixIfPresent mothed into Util

- docs/en/Configuring-Alluxio-with-S3.md
- docs/en/Running-Hadoop-MapReduce-on-Alluxio.md
Document where ufs delegation is helpful.
> [DOCFIX] Client Dependency Docs

- core/common/src/main/java/alluxio/underfs/UnderFileSystemRegistry.java
https://alluxio.atlassian.net/browse/ALLUXIO-2069
Removes capitalization from param descriptions in UnderFileSystemRegistry.java.
> [ALLUXIO-2069]correct @param descriptions in UnderFileSystemRegistry.java

- tests/src/test/java/alluxio/client/FileSystemIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2071
Changing FileSystemIntegrationTest class to be final
> [ALLUXIO-2071] Define FileSystemIntegrationTest as final

- tests/src/test/java/alluxio/collections/IndexedSetConcurrencyTest.java
Reverts Alluxio/alluxio#3674
It seems like this test has been causing a lot of build failures lately, probably due to leaked resources. In the last 10 default builds, 5 ran this test first, while 5 ran it after most other integration tests. Every build which ran this first went very slowly and timed out, while the builds which ran this toward the end succeeded. I will revert this and see if things start passing again.
> Revert "[SMALLFIX] Add two concurrent unit tests for indexedSet"

- tests/src/test/java/alluxio/underfs/UnderStorageSystemInterfaceIntegrationTest.java
Tests if list and delete work correctly for directories large enough to require pagination.
https://alluxio.atlassian.net/browse/ALLUXIO-2090
> [ALLUXIO-2090] New UFS integration tests for pagination

- core/server/pom.xml
- core/server/src/main/java/alluxio/web/UIWebServer.java
- pom.xml
Reverts Alluxio/alluxio#3546
This has been breaking the last few hdfs1 builds, which use the profile `-Phadoop-1 -PhdfsTest`. The failures are below. This may be some sort of dependency conflict with hadoop-1 jetty.
```
serverUpTest(alluxio.web.WebServerIntegrationTest)  Time elapsed: 3.361 sec  <<< FAILURE!
java.lang.AssertionError: expected:<200> but was:<500>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at alluxio.web.WebServerIntegrationTest.verifyWebService(WebServerIntegrationTest.java:62)
at alluxio.web.WebServerIntegrationTest.serverUpTest(WebServerIntegrationTest.java:94)
listenSameAddressTest(alluxio.master.ServiceSocketBindIntegration …
```
> Revert "[ALLUXIO-1956] Upgrade Jetty to fix jdk regression."

- core/client/src/main/java/alluxio/hadoop/ConfUtils.java
- core/client/src/main/java/alluxio/hadoop/HadoopUtils.java
- core/common/src/main/java/alluxio/Constants.java
- tests/pom.xml
- tests/src/test/java/alluxio/underfs/swift/SwiftUnderStorageCluster.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftMockOutputStream.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystemFactory.java
- underfs/swift/src/main/java/alluxio/underfs/swift/http/SwiftDirectClient.java
Client-side Swift API simulation to aid testing.
https://alluxio.atlassian.net/browse/ALLUXIO-2080
> [ALLUXIO-2080] A mock Swift backend using JOSS simulation mode

- core/client/src/main/java/alluxio/client/file/FileSystemUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-2094
> [ALLUXIO-2094] Fix persist command to UFS

- core/server/src/main/java/alluxio/worker/block/BlockWorkerClientServiceHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-2061
> [ALLUXIO-2061] Fix typo in BlockWorkerClientServiceHandler javadoc

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2093
> [ALLUXIO-2093] Quick fix for persist to Swift UFS

- docs/cn/Architecture.md
- docs/cn/Getting-Started.md
improve the translation in doc/cn!
> [DOCFIX]improve some translation in cn

- libexec/alluxio-config.sh
Apply the next version on `libexec/alluxio-config.sh` as well.
> [SMALLFIX] Update Alluxio version for next development iteration

- tests/src/test/java/alluxio/master/lineage/LineageMasterIntegrationTest.java
This fixes a race condition in lineageRecoveryTest.
reportLostFile only works when called between when a file is created and when the file is asynchronously persisted. Previously there was a race condition where the file created in lineageRecoveryTest would be persisted before reportLostFile was called. This change increases the checkpoint interval to 100 seconds so that the file persistence is guaranteed to not happen before reportLostFile is called.
> [SMALLFIX] Fix flakiness in LineageMasterIntegrationTest

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2076
> [ALLUXIO-2076]Making function args final for isRoot and addFolderSuffixIfNotPresent

- tests/src/test/java/alluxio/hadoop/FileSystemStatisticsTest.java
Use constants in FileSystemStatisticsTest
https://alluxio.atlassian.net/browse/ALLUXIO-2065
> [ALLUXIO-2065] Use constants in FileSystemStatisticsTest

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
[ALLUXIO-2102](https://alluxio.atlassian.net/browse/ALLUXIO-2102)
Guys, please help review the PR, thanks!
> [ALLUXIO-2102] Fix raw type in FileSystemMaster.java

- core/common/src/main/java/alluxio/collections/ConcurrentHashSet.java
[ALLUXIO-2096](https://alluxio.atlassian.net/browse/ALLUXIO-2096)
Just renamed the template parameter name as described, please help review it, thanks a lot.
> [ALLUXIO-2096] Fix type shadowing in ConcurrentHashSet

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- tests/src/test/java/alluxio/master/JournalIntegrationTest.java
- tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java
- tests/src/test/java/alluxio/master/MasterTestUtils.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
- tests/src/test/java/alluxio/security/ClusterInitializationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2111
> [ALLUXIO-2111] Fix standby master replay of checkpoint mount entry

- core/client/src/main/java/alluxio/hadoop/HadoopUtils.java
[ALLUXIO-2112](https://alluxio.atlassian.net/browse/ALLUXIO-2112)
Guys, refactored according to my knowledge, please help review it, any issue notice me, thanks.
> [ALLUXIO-2112] Refactor property setting in HadoopUtils.java

- tests/src/test/java/alluxio/master/lineage/LineageMasterIntegrationTest.java
> [SMALLFIX] Make private in LineageMasterIntegrationTest protected

- core/server/src/test/java/alluxio/worker/file/UnderFileSystemManagerTest.java
> [ALLUXIO-2119] Remove use of whitebox in UnderFileSystemManagerTest

- deploy/vagrant/conf/alluxio.yml
- deploy/vagrant/conf/spark.yml
https://alluxio.atlassian.net/browse/ALLUXIO-2123
https://alluxio.atlassian.net/browse/ALLUXIO-2124
> [ALLUXIO-2123] [ALLUXIO-2124] Update default deploy versions

- deploy/vagrant/provision/roles/spark/files/spark_env.sh
https://alluxio.atlassian.net/browse/ALLUXIO-2121
https://alluxio.atlassian.net/browse/ALLUXIO-2122
> [ALLUXIO-2121] [ALLUXIO-2122] Deploy module updates

- core/server/src/test/java/alluxio/worker/file/UnderFileSystemManagerTest.java
[ALLUXIO-2098](https://alluxio.atlassian.net/browse/ALLUXIO-2098)
> [ALLUXIO-2098] Add missing type parameter in UnderFileSystemManagerTest

- core/client/src/main/java/alluxio/client/file/FileInStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-2131
> [ALLUXIO-2131] ZSD New Contributor

- tests/src/test/java/alluxio/client/block/BlockStoreContextIntegrationTest.java
Previously the test had to use a lot of powermock and whitebox to test what it wanted to test. Moving to integration tests makes the test much simpler.
> [ALLUXIO-2119] Make BlockStoreContextTest an integration test

- docs/_data/table/en/operation-command.yml
- docs/_data/table/operation-command.csv
- docs/_includes/Command-Line-Interface/checksum.md
- docs/_includes/Command-Line-Interface/cp.md
- docs/_includes/Command-Line-Interface/ls.md
- docs/en/Command-Line-Interface.md
- shell/src/main/resources/fs.man
[Updated_Commmand_Line_Documentation.pdf](https://github.com/Alluxio/alluxio/files/389695/Updated_Commmand_Line_Documentation.pdf)
> [DOCFIX] Checksum and cp command, and a typo

- core/client/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/client/src/main/java/alluxio/client/file/FileInStream.java
- core/client/src/main/java/alluxio/client/file/UnknownLengthFileInStream.java
- core/client/src/test/java/alluxio/client/file/FileInStreamTest.java
- core/client/src/test/java/alluxio/client/file/MockFileInStream.java
> [ALLUXIO-2119] Remove use of whitebox in FileInStreamTest

- core/server/src/test/java/alluxio/master/file/PermissionCheckTest.java
> [ALLUXIO-2119] Avoid use of whitebox in PermissionCheckTest

- tests/src/test/java/alluxio/client/FileInStreamIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2070
> [ALLUXIO-2070] Define class FileInStreamIntegrationTest as final

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
Add a debug message in SwiftUnderFileSystem.java::listRecursive,detail:
https://alluxio.atlassian.net/browse/ALLUXIO-2166
> [ALLUXIO-2166]Add a debug message in SwiftUnderFileSystem

- core/client/src/main/java/alluxio/client/netty/NettyUnderFileSystemFileReader.java
https://alluxio.atlassian.net/browse/ALLUXIO-2159
> [ALLUXIO-2159]Remove redundant initialization in NettyUnderFileSystemFileReader.java

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
> [ALLUXIO-2119] Avoid use of whitebox in FileSystemMasterTest

- core/client/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
> [ALLUXIO-2119] Reduce use of whitebox in AbstractFileSystemTest

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2167
> [ALLUXIO-2167] Add a debug message in SwiftUnderFileSystem.java::list

- core/server/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
- core/server/src/test/java/alluxio/worker/WorkerTestUtils.java
- core/server/src/test/java/alluxio/worker/block/BlockWorkerTest.java
> [ALLUXIO-2119] Avoid use of whitebox in BlockWorker

- docs/en/Unit-Testing.md
https://alluxio.atlassian.net/browse/ALLUXIO-2174
> [ALLUXIO-2174] Add unit testing guide

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftInputStream.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
Skipping data from an InputStream used to fetch data from remote storage. Now instead, a new stream is opened starting at the desired position.
https://alluxio.atlassian.net/browse/ALLUXIO-2178
> [ALLUXIO-2178] Efficient skip with Swift InputStream

- deploy/vagrant/Vagrantfile
- deploy/vagrant/conf/ufs.yml
- deploy/vagrant/core/EnvSetup.rb
- deploy/vagrant/provision/roles/alluxio/tasks/config.yml
- deploy/vagrant/provision/roles/ufs_swift/files/compile_alluxio.sh
- deploy/vagrant/provision/roles/ufs_swift/files/compile_spark.sh
- deploy/vagrant/provision/roles/ufs_swift/files/config_alluxio.sh
- deploy/vagrant/provision/roles/ufs_swift/tasks/config.yml
- deploy/vagrant/provision/roles/ufs_swift/tasks/download_release.yml
- deploy/vagrant/provision/roles/ufs_swift/tasks/rsync_dist.yml
- deploy/vagrant/provision/roles/ufs_swift/tasks/start.yml
Modifications to vagrant scripts with Swift UFS configuration.
https://alluxio.atlassian.net/browse/ALLUXIO-2175
> [ALLUXIO-2175] Deployment scripts for Alluxio with a Swift UFS

- core/server/src/main/java/alluxio/worker/file/UnderFileSystemManager.java
- core/server/src/test/java/alluxio/worker/file/UnderFileSystemManagerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2179
> [ALLUXIO-2179] Use openAtPosition API for s3a.

- core/server/src/main/java/alluxio/worker/WorkerSource.java
- pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-2182
> [ALLUXIO-2182] Add hostname to worker metrics name

- pom.xml
Pick up the fix reported here https://github.com/dropwizard/metrics/issues/694
> [ALLUXIO-2182] Update metrics lib version to 3.1.2 from 3.1.0

- tests/src/test/java/alluxio/worker/AlluxioWorkerRestApiTest.java
Followup to https://github.com/Alluxio/alluxio/pull/3813
@peisun1115
> [SMALLFIX] Fix metrics test

- core/server/src/main/java/alluxio/worker/block/SpaceReserver.java
https://alluxio.atlassian.net/browse/ALLUXIO-2148
> [ALLUXIO-2148] Simplify exception handling in SpaceReserver

- core/client/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2157
Followup of https://github.com/Alluxio/alluxio/pull/3792
> [ALLUXIO-2157] Remove redundant initialization in RetryHandlingBlockMasterClient.java

- integration/yarn/src/main/java/alluxio/yarn/Client.java
After #3535 [SMALLFIX] Yarn improvements ,  yarn client will exit after launching the application master. It's better to wait until the app is running to show the tracking url.
> [SMALLFIX] Wait until the app is running when submitting alluxio to Yarn

- bin/alluxio-fuse.sh
https://alluxio.atlassian.net/browse/ALLUXIO-2191
> [ALLUXIO-2191] Set the java opts correctly when starting fuse

- docs/_includes/Configuring-Alluxio-with-secure-HDFS/alluxio-opts.md
- docs/_includes/Configuring-Alluxio-with-secure-HDFS/alluxio-properties-for-secure-hdfs-kerberos.md
- docs/_includes/Configuring-Alluxio-with-secure-HDFS/hadoop-opts.md
- docs/_includes/Configuring-Alluxio-with-secure-HDFS/spark-opts.md
- docs/en/Configuring-Alluxio-with-secure-HDFS.md
Kerberos configurations should be system properties, not in Alluxio site-properties.
> [DOCFIX] Fix a issue in secure HDFS doc. 

- core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2068
Apart from fixing words like "The",  I also change those words like "UFS" to "ufs".
Besides, I also add some "the" to precede the noun.
Hope it's right.
>  [ALLUXIO-2068] Fix Javadoc style for {{@param}} in UnderFileSystem.java

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2163
It's a hot Summer, right?
>  [ALLUXIO-2163] Add a debug message in SwiftUnderFileSystem.java::getModificationTimeMs

- core/client/src/main/java/alluxio/client/block/RemoteBlockInStream.java
- core/client/src/test/java/alluxio/client/block/UnderStoreBlockInStreamTest.java
- core/common/src/main/java/alluxio/collections/IndexedSet.java
- core/common/src/main/java/alluxio/exception/AlluxioException.java
- core/common/src/main/java/alluxio/network/protocol/databuffer/DataNettyBuffer.java
- Used automatic resource management in RemoteBlockInStream
- Fixed link in Javadoc in UnderStoreBlockInStreamTest
- Used <> generics in IndexedSet
- Removed standalone Javadoc snippet in AlluxioException
- Simplified check in DataNettyBuffer
> [SMALLFIX] Minor changes in several files

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2161
> [ALLUXIO-2161] Add a debug message in SwiftUnderFileSystem.java::exists

- core/server/src/test/java/alluxio/AbstractClientTest.java
- core/server/src/test/java/alluxio/worker/block/allocator/AllocatorTestBase.java
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- tests/src/test/java/alluxio/master/AlluxioMasterRestApiTest.java
- tests/src/test/java/alluxio/worker/AlluxioWorkerRestApiTest.java
- Removed not needed import in AbstractClientTest
- Added documentation of exception in AbstractLocalAlluxioCluster
- Simplified if statements in AllocatorTestBase
- Removed not needed cast in AlluxioMasterRestApiTest
- Removed not needed casts in AlluxioWorkerRestApiTest
> [SMALLFIX] Small fixes in several classes

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2162
> [ALLUXIO-2162] Add a debug message in SwiftUnderFileSystem.java::getBlockSizeByte

- docs/en/Configuring-Alluxio-with-OSS.md
update three http links for the oss documents update
> [DOCFIX] Update the OSS UnderFileSystem Configuration Document

- deploy/vagrant/create
> [SMALLFIX] Tracking usage of vagrant deploy module

- build/style/check_no_windows_line_endings.sh
- pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-2210
> [ALLUXIO-2210] Add check for unix line endings

- core/common/src/main/java/alluxio/collections/UniqueFieldIndex.java
https://alluxio.atlassian.net/browse/ALLUXIO-2140
> [ALLUXIO-2140] Improve the exception message

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftInputStream.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftRange.java
This addresses JIRA https://alluxio.atlassian.net/browse/ALLUXIO-2207.
> [ALLUXIO-2207] Use a range query to limit data fetched by Swift InputStream

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2168
> [ALLUXIO-2168] Add a debug message in SwiftUnderFileSystem.java::mkdirs

- docs/en/Unit-Testing.md
> [DOCFIX] Add global state section to unit testing guide

- core/client/src/main/java/alluxio/client/block/BlockWorkerClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2214
> [ALLUXIO-2214] Send a heartbeat before we do any worker ops.

- core/client/src/main/java/alluxio/client/block/AlluxioBlockStore.java
- core/client/src/main/java/alluxio/client/block/BlockStoreContext.java
- core/client/src/main/java/alluxio/client/block/BufferedBlockOutStream.java
- core/client/src/main/java/alluxio/client/block/LocalBlockOutStream.java
- core/client/src/main/java/alluxio/client/block/RemoteBlockOutStream.java
- core/client/src/main/java/alluxio/client/file/FileInStream.java
- core/client/src/main/java/alluxio/client/file/FileSystemContext.java
- core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client/src/test/java/alluxio/client/block/BufferedBlockOutStreamTest.java
- core/client/src/test/java/alluxio/client/block/TestBufferedBlockOutStream.java
- core/client/src/test/java/alluxio/client/file/FileInStreamTest.java
- core/client/src/test/java/alluxio/client/file/FileOutStreamTest.java
- core/client/src/test/java/alluxio/client/util/ClientTestUtils.java
- core/client/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
- keyvalue/client/src/main/java/alluxio/client/keyvalue/BaseKeyValuePartitionReader.java
- keyvalue/client/src/main/java/alluxio/hadoop/mapreduce/KeyValueInputSplit.java
- shell/src/main/java/alluxio/shell/command/FileInfoCommand.java
- shell/src/main/java/alluxio/shell/command/GetCapacityBytesCommand.java
- shell/src/main/java/alluxio/shell/command/GetUsedBytesCommand.java
- shell/src/main/java/alluxio/shell/command/LocationCommand.java
- tests/src/test/java/alluxio/client/RemoteBlockInStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/block/BlockStoreContextIntegrationTest.java
- tests/src/test/java/alluxio/master/MasterFaultToleranceIntegrationTest.java
- tests/src/test/java/alluxio/master/ServiceSocketBindIntegrationTest.java
- tests/src/test/java/alluxio/worker/DataServerIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2154
> [ALLUXIO-2154] Break up the BlockStoreContext singleton

- core/common/src/main/java/alluxio/Configuration.java
- core/common/src/main/java/alluxio/PropertyKey.java
- core/common/src/test/java/alluxio/ConfigurationTest.java
- core/common/src/test/java/alluxio/SetAndRestoreSystemProperty.java
- examples/src/main/java/alluxio/cli/JournalCrashTest.java
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java
- minicluster/src/main/java/alluxio/master/LocalAlluxioMaster.java
- minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java
- underfs/hdfs/src/test/java/alluxio/underfs/hdfs/HdfsUnderFileSystemUtilsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2217
> [ALLUXIO-2217] Split up the responsibilities of alluxio.home

- core/common/src/main/java/alluxio/security/login/AppLoginModule.java
https://alluxio.atlassian.net/browse/ALLUXIO-2153
- Collapsed two catch blocks into one in AppLoginModule
> [ALLUXIO-2153] Improved exception handling in AppLoginModule

- core/server/src/main/java/alluxio/web/WebInterfaceWorkerBlockInfoServlet.java
https://alluxio.atlassian.net/browse/ALLUXIO-2221
> [ALLUXIO-2221] Avoid crashing worker UI in case of missing files

- core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
- underfs/glusterfs/src/main/java/alluxio/underfs/glusterfs/GlusterFSUnderFileSystem.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/hdfs/src/test/java/alluxio/underfs/hdfs/HdfsUnderFileSystemTest.java
- underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2222
> [ALLUXIO-2222] Change underFsType to be a String

- core/common/src/main/java/alluxio/heartbeat/SleepingTimer.java
- core/common/src/main/java/alluxio/util/FormatUtils.java
- core/common/src/test/java/alluxio/util/FormatUtilsTest.java
- do not sleep before invoking a heartbeat for the first time
- add a generalized utility for printing hex strings
> [SMALLFIX] a couple of small nits

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- tests/src/test/java/alluxio/hadoop/FileSystemAclIntegrationTest.java
> [SMALLFIX] Allow setOwn/setMode on Alluxio but not propagating to object

- core/server/src/test/java/alluxio/worker/block/BlockLockManagerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2139
> [ALLUXIO-2139] Mark BlockLockManagerTest as final class 

- core/common/src/main/java/alluxio/job/CommandLineJob.java
https://alluxio.atlassian.net/browse/ALLUXIO-2152
> [ALLUXIO-2152] Improve exception handling in CommandLineJob

- docs/_includes/Building-Alluxio-Master-Branch/supported-values.md
Adds the swift and gcs profiles.
> [DOCFIX] Update docs for test profiles

- core/common/src/test/java/alluxio/CommonTestUtils.java
- core/common/src/test/java/alluxio/CommonTestUtilsTest.java
Break up monolithic test into its parts
> [SMALLFIX] Clean up common test utils test

- docs/en/Getting-Started.md
Made a few small changes to the Getting Started documentation page to improve readability.
> [DOCFIX] Small changes to improve readability

- core/common/src/main/java/alluxio/collections/NonUniqueFieldIndex.java
https://alluxio.atlassian.net/browse/ALLUXIO-2143
I just update the Iterator to iterator
> [ALLUXIO-2143] Improve comment for NonUniqueFieldIndexIterator mIndexIterator

- core/server/src/main/java/alluxio/RpcUtils.java
Logs additional info on the server side which would otherwise be lost.
> [SMALLFIX] Add additional logging for RPC errors.

- integration/bin/alluxio-mesos.sh
- integration/mesos/pom.xml
- integration/mesos/src/main/java/alluxio/mesos/AlluxioFramework.java
- integration/mesos/src/main/java/alluxio/mesos/AlluxioScheduler.java
https://alluxio.atlassian.net/browse/ALLUXIO-2230
This change also moves `AlluxioScheduler` to its own file. The only changes to the scheduler are those involving `mRequiredMasterHostname`.
> [ALLUXIO-2230] Make Alluxio master in Mesos configurable

- core/server/src/test/java/alluxio/master/lineage/LineageMasterTest.java
@jsimsa The mocking issue has returned despite switching to `doReturn.when()`. This PR moves all mocking to before the master is started so that we aren't mocking an object while it is in use by other threads.
> [SMALLFIX] Finish all mocking before starting lineage master

- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2233
Previously it defaulted to 100MB.
> [ALLUXIO-2233] Update S3A min copy part size.

- docs/cn/Security.md
- docs/en/Security.md
This PR addresses https://alluxio.atlassian.net/browse/ALLUXIO-2239
The PR is blocked by https://github.com/Alluxio/alluxio/pull/3913
> [ALLUXIO-2239] Update Alluxio security document for simple mode is enabled by default

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
> [MERGE] Merge branch-1.2 to master

- integration/bin/alluxio-env-mesos.sh
- integration/mesos/src/main/java/alluxio/mesos/AlluxioScheduler.java
https://alluxio.atlassian.net/browse/ALLUXIO-2248
@jsimsa
> [ALLUXIO-2248] Propagate configuration to Mesos executors

- core/common/src/main/java/alluxio/collections/FieldIndex.java
- core/common/src/main/java/alluxio/collections/NonUniqueFieldIndex.java
- core/common/src/main/java/alluxio/collections/UniqueFieldIndex.java
- core/server/src/main/java/alluxio/master/file/meta/InodeDirectory.java
Make `add()` return `boolean` like `remove()`
> [SMALLFIX] Allows add() to return boolean

- docs/cn/Configuring-Alluxio-with-Swift.md
- docs/en/Configuring-Alluxio-with-Swift.md
https://alluxio.atlassian.net/browse/ALLUXIO-2242
thanks your review
> [DOCFIX] update docs/cn/Configuring-Alluxio-with-Swift.md

- core/client/src/main/java/alluxio/client/block/AlluxioBlockStore.java
- core/client/src/main/java/alluxio/client/netty/ClientHandler.java
- core/client/src/main/java/alluxio/client/netty/NettyRemoteBlockReader.java
- core/client/src/main/java/alluxio/client/netty/NettyRemoteBlockWriter.java
- core/client/src/main/java/alluxio/client/netty/NettyUnderFileSystemFileReader.java
- core/client/src/main/java/alluxio/client/netty/NettyUnderFileSystemFileWriter.java
- core/client/src/test/java/alluxio/client/netty/ClientHandlerTest.java
A channel can be closed asynchronously in netty. we should avoid doing that.
> [ALLUXIO-2236] Fix a bug related channel close

- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/common-configuration.csv
- docs/_data/table/en/common-configuration.yml
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2249
> [ALLUXIO-2249] Use ensure exists for S3A rename.

- core/client/src/test/java/alluxio/client/block/BlockStoreContextTestUtils.java
> [SMALLFIX] Add BlockStoreContextTestUtils to clear pool.

- docs/cn/Contributing-Getting-Started.md
https://alluxio.atlassian.net/browse/ALLUXIO-2246
> [ALLUXIO-2246] DOCFIX

- pom.xml
> [SMALLFIX] Exclude protobuf dependency from mesos

- docs/_config.yml
@aaudiber This is a fix to display the correct version for the docs on alluxio.org.
> [DOCFIX] Update to correct short version

- docs/_config.yml
To better reflect convention of `ALLUXIO_MASTER_VERSION_SHORT`
> [DOCFIX] Update comment for ALLUXIO_MASTER_VERSION_SHORT

- core/common/src/main/java/alluxio/heartbeat/HeartbeatScheduler.java
- core/common/src/test/java/alluxio/heartbeat/HeartbeatThreadTest.java
- core/server/src/test/java/alluxio/master/block/BlockMasterTest.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- core/server/src/test/java/alluxio/worker/block/SpaceReserverTest.java
- tests/src/test/java/alluxio/IntegrationTestUtils.java
- tests/src/test/java/alluxio/client/FreeAndDeleteIntegrationTest.java
- tests/src/test/java/alluxio/client/IsolatedFileSystemIntegrationTest.java
- tests/src/test/java/alluxio/client/RemoteBlockInStreamIntegrationTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
- tests/src/test/java/alluxio/shell/command/PinCommandTest.java
- tests/src/test/java/alluxio/worker/BlockServiceHandlerIntegrationTest.java
- tests/src/test/java/alluxio/worker/DataServerIntegrationTest.java
- tests/src/test/java/alluxio/worker/block/meta/TieredStoreIntegrationTest.java
This simplifies how we execute manually scheduled heartbeats during tests. @jsimsa
> [SMALLFIX] Heartbeat cleanup

- bin/alluxio
Under file system address should be set in site-properties in most cases.
> [SMALLFIX] Do not set ufs address in bootstrap conf

- conf/alluxio-site.properties.template
Makes it easier to maintain and read.
> [SMALLFIX] Site Properties Update

- docs/en/Running-HBase-on-Alluxio.md
some bugs in the en/Running HBase on Alluxio.md
> [DOCFIX] en/Running HBase on Alluxio.md

- docs/cn/Running-HBase-on-Alluxio.md
https://alluxio.atlassian.net/browse/ALLUXIO-2245
> [DOCFIX]  Add Running-HBase-on-Alluxio.md of the Chinese version

- docs/_data/table/cn/user-configuration.yml
https://alluxio.atlassian.net/browse/ALLUXIO-2247
> [DOCFIX]docs/_data/table/cn/user-configuration.yml

- deploy/vagrant/create
> [SMALLFIX] Track vagrant usage asynchronously

- tests/src/test/java/alluxio/underfs/UnderStorageSystemInterfaceIntegrationTest.java
consistency for S3/GCS list operation.
> [SMALLFIX] Add retry in large dir list test to tolerate eventual

- docs/cn/Debugging-Guide.md
https://alluxio.atlassian.net/browse/ALLUXIO-2244
> [DOCFIX]Update Debugging-Guide.md of the Chinese version

- core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
- core/common/src/main/java/alluxio/resource/ResourcePool.java
> [SMALLFIX] Rervert the fairness lock change

- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
https://alluxio.atlassian.net/browse/ALLUXIO-2151
Removed period from error message
> [ALLUXIO-2151] - Removed period from error message

- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
https://alluxio.atlassian.net/browse/ALLUXIO-2149
Updated ExceptionMessage.java to change the current message for NO_LOCAL_WORKER from "Local" to "Local address".
> [ALLUXIO-2149] - Updated NO_LOCAL_WORKER error message

- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
Tested locally: restarting a cluster by enabling security from `NOSASL` to `SIMPLE`, without formatting the journal.
Without this change, the journal generated with security off would not be replayed correctly into a new version with security on.
> [SMALLFIX] Fix a compatibility issue for journal replay with security mode change.

- docs/en/Configuring-Alluxio-with-secure-HDFS.md
important configurations setup
> [DOCFIX] Improve some sub-header in secure HDFS doc to highlight

- core/common/src/main/java/alluxio/collections/NonUniqueFieldIndex.java
- core/common/src/main/java/alluxio/collections/UniqueFieldIndex.java
- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
- core/common/src/main/java/alluxio/heartbeat/HeartbeatScheduler.java
- core/common/src/test/java/alluxio/heartbeat/HeartbeatThreadTest.java
- core/server/src/test/java/alluxio/master/block/BlockMasterTest.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- core/server/src/test/java/alluxio/worker/block/SpaceReserverTest.java
- docs/_config.yml
- docs/_data/table/cn/user-configuration.yml
- docs/cn/Debugging-Guide.md
- docs/cn/Running-HBase-on-Alluxio.md
- docs/en/Running-HBase-on-Alluxio.md
- tests/src/test/java/alluxio/IntegrationTestUtils.java
- tests/src/test/java/alluxio/client/FreeAndDeleteIntegrationTest.java
- tests/src/test/java/alluxio/client/IsolatedFileSystemIntegrationTest.java
- tests/src/test/java/alluxio/client/RemoteBlockInStreamIntegrationTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
- tests/src/test/java/alluxio/shell/command/PinCommandTest.java
- tests/src/test/java/alluxio/worker/BlockServiceHandlerIntegrationTest.java
- tests/src/test/java/alluxio/worker/DataServerIntegrationTest.java
- tests/src/test/java/alluxio/worker/block/meta/TieredStoreIntegrationTest.java
@jsimsa @calvinjia 
after this PR, master and branch-1.3 are only different in version related strings.
> [SMALLFIX] Sync code change in master into 1.3

- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AInputStream.java
In very rare cases we may try to read a 0 length file.
> [SMALLFIX] S3A inputstream fix

- docs/_includes/Running-Alluxio-on-EC2-Yarn/stop-install-yarn.md
- docs/en/Running-Alluxio-on-EC2-Yarn.md
- pom.xml
These changes should make following the Running-Alluxio-on-EC2-Yarn instructions a bit easier to follow.
> [DOCFIX] Yarn integration docfix

- core/common/src/main/java/alluxio/security/LoginUser.java
- docs/_includes/Running-Hadoop-MapReduce-on-Alluxio/add-jar-libjars.md
The original code creates log message has the real cause very minimal 
Also update the command using `-libjar` in doc
> [SMALLFIX] [branch-1.3] Throw IOException directly on login failure, rather than creating LoginException first

- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- docs/_includes/Running-Spark-on-Alluxio/earlier-spark-version-bash.md
- docs/_includes/Running-Spark-on-Alluxio/fault-tolerant-mode-with-zookeeper-bash.md
- docs/en/Running-Spark-on-Alluxio.md
> [DOCFIX] Update the spark+alluxio doc

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
Ceph and OpenStack Swift return different error codes when a checking existence or deleting an object. Openstack Swift returns 404 which JOSS handles as NotFoundException. Ceph, on the other hand, returns 500 Unknown error.
> [SMALLFIX] Make Swift UFS tolerant to variance in error codes from backend

- core/common/src/main/java/alluxio/util/executor/ExecutorServiceFactories.java
- core/common/src/main/java/alluxio/util/executor/ExecutorServiceFactory.java
- core/server/src/main/java/alluxio/master/AbstractMaster.java
- core/server/src/main/java/alluxio/master/AlluxioMaster.java
- core/server/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/lineage/LineageMaster.java
- core/server/src/test/java/alluxio/master/block/BlockMasterTest.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- core/server/src/test/java/alluxio/master/lineage/LineageMasterTest.java
- keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMaster.java
- tests/src/test/java/alluxio/master/MasterFaultToleranceIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2252
> [ALLUXIO-2252] Fix master fault tolerance integration test

- core/client/src/test/java/alluxio/client/file/FileSystemWorkerClientTestUtils.java
> [SMALLFIX] Use correct variable names

- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
before fixing the root cause in https://github.com/Alluxio/alluxio/pull/4024
@peisun1115 @calvinjia
> [SMALLFIX] [branch-1.3] Disable flaky FileSystemMasterIntegrationTest

- core/common/src/main/java/alluxio/security/LoginUser.java
- docs/en/Running-Hadoop-MapReduce-on-Alluxio.md
for adding alluxio client jar in HADOOP classpath.
> [SMALLFIX] [branch-1.3] Improve error message and docs

- docs/en/Getting-Started.md
> [DOCFIX] Add MapRFS to the list of supported under storages.

- README.md
- assembly/pom.xml
- core/client/pom.xml
- core/common/pom.xml
- core/pom.xml
- core/server/pom.xml
- docs/_config.yml
- examples/pom.xml
- integration/fuse/pom.xml
- integration/mesos/pom.xml
- integration/pom.xml
- integration/yarn/pom.xml
- keyvalue/client/pom.xml
- keyvalue/common/pom.xml
- keyvalue/pom.xml
- keyvalue/server/pom.xml
- libexec/alluxio-config.sh
- minicluster/pom.xml
- pom.xml
- shell/pom.xml
- tests/pom.xml
- underfs/gcs/pom.xml
- underfs/glusterfs/pom.xml
- underfs/hdfs/pom.xml
- underfs/local/pom.xml
- underfs/oss/pom.xml
- underfs/pom.xml
- underfs/s3/pom.xml
- underfs/s3a/pom.xml
- underfs/swift/pom.xml
Since 1.3.0 has been released.
> [SMALLFIX] Upgrade to 1.4.0-SNAPSHOT.

- core/common/src/test/java/alluxio/ConfigurationRule.java
https://alluxio.atlassian.net/browse/ALLUXIO-2263
> [ALLUXIO-2263] Mark class ConfigurationRule in ConfigurationRule.java final

- docs/cn/Unit-Testing.md
https://alluxio.atlassian.net/browse/ALLUXIO-2243
> [DOCFIX] Add Unit-Testing.md of the Chinese version

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
[ALLUXIO-2074]https://alluxio.atlassian.net/browse/ALLUXIO-2074
modified by DZ1633008
> [ALLUXIO-2074]Reword comment in the file SwiftUnderFileSystem:rename 

- core/client/src/main/java/alluxio/client/block/RetryHandlingBlockWorkerClient.java
[https://alluxio.atlassian.net/browse/ALLUXIO-2271](https://alluxio.atlassian.net/browse/ALLUXIO-2271)
> [ALLUXIO-2271] Remove a comment in RetryHandlingBlockWorkerClient

- core/common/src/main/java/alluxio/PropertyKey.java
https://alluxio.atlassian.net/browse/ALLUXIO-2261
> [ALLUXIO-2261] Mark enum PropertyKey with annotation "@ThreadSafe"

- core/client/src/main/java/alluxio/client/file/FileSystemWorkerClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2269
> [ALLUXIO-2269] Remove a comment in FileSystemWorkerClient

- core/server/src/test/java/com/google/common/util/concurrent/MockRateLimiter.java
https://alluxio.atlassian.net/browse/ALLUXIO-2256
Improve the description of the class.At line 26 in "C:\Users\remote\Documents\GitHub\alluxio\keyvalue\common\src\main\java\alluxio\thrift\KeyValueWorkerClientService.java",change the "version" to "versions".
> [ALLUXIO-2256]Improve docs in MockRateLimiter

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-2258
Update the comment in loadMetadataIfNotExistAndJournal from exisits to exists.
> [ALLUXIO-2258] Improve docs in FileSystemMaster

- core/server/src/main/java/alluxio/worker/block/BlockStore.java
https://alluxio.atlassian.net/browse/ALLUXIO-2276
modified by MG1633034
Correct "meta data" in this file to "metadata".
> [ALLUXIO-2276] Fix javadoc in BlockStore.java

- core/common/src/test/java/alluxio/metrics/MetricsSystemTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2137
Mark class MetricsSystemTest as final
> [ALLUXIO-2137]  Mark class MetricsSystemTest as final

- core/client/src/main/java/alluxio/client/block/BlockWorkerClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2288
Update "Id" to "ID" in the javadoc
> [ALLUXIO-2288] Fix javadoc in BlockWorkerClient.java

- core/server/src/test/java/alluxio/worker/file/FileWorkerMasterSyncExecutorTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2254
> [ALLUXIO-2254] Improve style in FileWorkerMasterSyncExecutorTest

- core/common/src/main/java/alluxio/collections/ConcurrentHashSet.java
MG1633044 https://alluxio.atlassian.net/browse/ALLUXIO-2279
add final to concurrenthashset.java
> [ALLUXIO-2279]add final to concurrenthashset.java

- core/server/src/test/java/alluxio/master/file/meta/TtlBucketListTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2133
Mark class TtlBucketListTest as final in TtlBucketListTest.java
> [ALLUXIO-2133] Mark class TtlBucketListTest as final in TtlBucketListTest.java

- core/server/src/main/java/alluxio/master/file/meta/Inode.java
https://alluxio.atlassian.net/browse/ALLUXIO-2296
> change varible mId to final long

- .gitignore
- core/server/src/test/java/alluxio/AbstractClientTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2255
> [Alluxio 2255] Improve style in AbstractClientTest

- core/client/src/main/java/alluxio/client/block/RetryHandlingBlockWorkerClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2289
Update "Id" to "ID" in RetryHandlingBlockWorkerClient.java
> [ALLUXIO-2289]Fix javadoc in RetryHandlingBlockWorkerClient.java

- docs/cn/Security.md
- docs/en/Security.md
> [DOCFIX] Remove alpha annotation for Security

- docs/_includes/Configuring-Alluxio-with-GlusterFS/underfs-address.md
- docs/en/Configuring-Alluxio-with-GlusterFS.md
Updated how to set the underfs address.
> [SMALLFIX] Updated the docs for GlusterFS configuration

- core/server/src/main/java/alluxio/master/block/BlockMasterClientServiceHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-2332
> [ALLUXIO-2332]mark class BlockMasterClientServiceHandler final

- core/common/src/test/java/alluxio/AlluxioURITest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2287
Update "an URI" to "a URI" 
Fix javadoc in AlluxioURITest.java
> [ALLUXIO-2287]Update "an URI" to "a URI"

- core/common/src/main/java/alluxio/LeaderInquireClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2305
I haved changed the 'create' to 'Creating'
> [ALLUXIO-2305] Improve logging in LeaderInquireClient

- core/common/src/main/java/alluxio/LeaderSelectorClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2312
Make the logging style consistent by changing all the log statements to start with a capital letter.
> [ALLUXIO-2312]Improve logging in LeaderSelectorClient

- core/server/src/main/java/alluxio/worker/block/meta/StorageDirView.java
https://alluxio.atlassian.net/browse/ALLUXIO-2295
Update "Id" to "ID" in the javadoc
> [ALLUXIO-2295] Fix javadoc in StorageDirView.jav

- core/common/src/thrift/file_system_master.thrift
https://alluxio.atlassian.net/browse/ALLUXIO-2272
> [ALLUXIO-2272] modify a word in file_system_master.thrift from "meta data" to "metadata"

- core/server/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2253
Update lines with `which not exists` to `which doesn't exist`
> [ALLUXIO-2253]Improve docs in TieredBlockStoreTest

- core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
https://alluxio.atlassian.net/browse/ALLUXIO-2291
Update "Id" to "ID" in the javadoc of DynamicResourcePool.java
> [ALLUXIO-2291] Update "Id" to "ID" in the javadoc of DynamicResourcePool.java

- core/server/src/main/java/alluxio/RestUtils.java
@jsimsa @ifcharming 
https://alluxio.atlassian.net/browse/ALLUXIO-2353
> [ALLUXIO-2353] Use super user permission in REST service

- core/common/src/main/java/alluxio/collections/UniqueFieldIndex.java
- readme.txt
https://alluxio.atlassian.net/browse/ALLUXIO-2141
delete a line in UniqueFieldIndex containsObject
> [ALLUXIO-2141] Remove extra line in UniqueFieldIndex containsObject()

- core/server/src/main/java/alluxio/master/AlluxioMaster.java
- pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-2340
> [ALLUXIO-2340]Improve error handling in AlluxioMaster constructor

- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
Add javadoc for getFileIdTest
https://alluxio.atlassian.net/browse/ALLUXIO-2146
> [ALLUXIO-2146] Add javadoc for getFileIdTest

- core/server/src/test/java/alluxio/worker/block/BlockHeartbeatReporterTest.java
[https://alluxio.atlassian.net/browse/ALLUXIO-2138](url)
> [ALLUXIO-2138]Mark class BlockHeartbeatReporterTest as final

- core/server/src/main/java/alluxio/master/file/meta/InodeDirectory.java
https://alluxio.atlassian.net/browse/ALLUXIO-2298
> [ALLUXIO-2298]Mark member variable mChildren in InodeDirectory.java final

- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
https://alluxio.atlassian.net/browse/ALLUXIO-2292
> [ALLUXIO-2292]Fix javadoc in InodeTree.java

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
[https://alluxio.atlassian.net/browse/ALLUXIO-2315](url)
Fix wrong link in javadoc of alluxio.underfs.swift.SwiftUnderFileSystem#rename
> [ALLUXIO-2315] Change "* @inheritDoc" to  "* {@inheritDoc}" in alluxio.underfs.swift.SwiftUnderFileSystem

- core/common/src/main/java/alluxio/PropertyKey.java
- core/common/src/test/java/alluxio/ConfigurationRule.java
https://alluxio.atlassian.net/browse/ALLUXIO-2262
> [ALLUXIO-2262] Mark nested class Name in PropertyKey with annotation "@ThreadSafe"

- core/common/src/main/java/alluxio/LeaderSelectorClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2306
> [ALLUXIO-2306]Improved javadoc in LeaderSelectorClient (member variables) 

- core/server/src/test/java/alluxio/master/file/meta/MountTableTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2286
I fixed a javadoc named MountTableTest.java.I updated "an URI" to "a RUI".
> [ALLUXIO-2286]Fix javadoc in MountTableTest

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
> [SMALLFIX] Do not set permission in Alluxio if propogation to UFS failed.

- core/common/src/main/java/alluxio/LeaderSelectorClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2307
> [ALLUXIO-2307]Update LeaderSelectorClient.java

- core/common/src/main/java/alluxio/PropertyKeyFormat.java
https://alluxio.atlassian.net/browse/ALLUXIO-2260
Mark member variable mFormat as final in PropertyKeyFormat.java
ALLUXIO-2260
> [ALLUXIO-2260] Mark member variable mFormat as final in PropertyKeyFormat.java

- core/server/src/main/java/alluxio/cli/Format.java
https://alluxio.atlassian.net/browse/ALLUXIO-2328
Fix javadoc on Format.java. Added word 'the' in the file.
> [ALLUXIO-2328] Fix javadoc on Format.java

- core/server/src/test/java/alluxio/master/file/meta/options/MountInfoTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2132
> [ALLUXIO-2132] Mark class MountInfoTest as final

- keyvalue/server/pom.xml
- keyvalue/server/src/main/java/alluxio/worker/keyvalue/KeyValueWorker.java
https://alluxio.atlassian.net/browse/ALLUXIO-2354
> [ALLUXIO-2354]Improve javadoc for KeyValueWorker#mBlockWorker

- core/server/src/main/java/alluxio/worker/block/BlockMasterSync.java
https://alluxio.atlassian.net/browse/ALLUXIO-2293
Update "Id" to "ID" in the javadoc
> [ALLUXIO-2293] Fix javadoc in BlockMasterSync.java

- core/server/src/main/java/alluxio/worker/block/BlockStoreMeta.java
https://alluxio.atlassian.net/browse/ALLUXIO-2281
Modified by MG1633046
> [ALLUXIO-2281]Fix javadoc in BlockStoreMeta.java:'meta data'to 'matadata'

- core/common/src/main/java/alluxio/collections/IndexedSet.java
https://alluxio.atlassian.net/browse/ALLUXIO-2097
> [ALLUXIO-2097] Fix formatting for IndexedSet constructor definition

- core/server/src/main/java/alluxio/master/file/options/SetAttributeOptions.java
https://alluxio.atlassian.net/browse/ALLUXIO-2331
Add final for SetAttributeOptions class.
> [ALLUXIO-2331]Add final for SetAttributeOptions class.

- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2145
> [ALLUXIO-2145]add javadoc for FileSyestemMasterTest.java

- core/client/src/main/java/alluxio/client/file/BaseFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2330
> [ALLUXIO-2330]Simplify code in BaseFileSystem#exists
