Alluxio/alluxio

docs/en/Contributing-Getting-Started.md
docs/en/Contributing-to-Alluxio.md

Apologies in advance for deleting trailing whitespace, but I don't think we want trailing whitespace in our markdown files, and many editors remove trailing whitespace by default.

[DOCFIX] Update docs with new component labeling guidelines

---

core/common/src/main/java/alluxio/Configuration.java

This method doesn't make sense any more in the new configuration world

[SMALLFIX] Remove unused method

---

core/common/src/main/java/alluxio/underfs/UnderFileSystemRegistry.java

https://alluxio.atlassian.net/browse/ALLUXIO-2079
The UnderFileSystemRegistry object created by create method. The Constructor should be private.

[ALLUXIO-2079] Set Constructor of alluxio.underfs.UnderFileSystemRegistry  to be private

---

core/common/src/main/java/alluxio/exception/ExceptionMessage.java
core/common/src/main/java/alluxio/exception/PreconditionMessage.java
core/common/src/main/java/alluxio/security/authorization/Permission.java
core/common/src/main/java/alluxio/underfs/UnderFileSystem.java

avoid expensive calls to Configuration.get
`UnderFileSystem.get` calls `Configuration.get` every time. `Configuration.get` is expensive. Since mOwner/mGroup are not actually used for now, we can remove them.

[SMALLFIX] Remove user/group in UnderFileSystem object and cache to

---

docs/resources/alluxio-code-formatter-eclipse.xml

Should not add white space before a postfix operator.

[SMALLFIX] correct a small bug in formatter xml

---

docs/en/Contributing-Getting-Started.md
docs/en/Contributing-to-Alluxio.md

Reverts Alluxio/alluxio#3662
Github permissions prevent people without write permissions from modifying labels, so we can't ask people to specify component via label.

Revert "[DOCFIX] Update docs with new component labeling guidelines"

---

tests/src/test/java/alluxio/hadoop/FileSystemAclIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2064
Replaced an integer literal with Constants.GB when creating the LocalAlluxioClusterResource object in FileSystemAclIntegrationTest.

[ALLUXIO-2064] Replacing integer literal with predefined sizes in Constants

---

bin/alluxio-workers.sh

On centos7 when try to start alluxio in cluster model will get error :
Pseudo-terminal will not be allocated because stdin is not a terminal.
sudo: sorry, you must have a tty to run sudo
Mount failed, not starting worker.
For detail please see:https://alluxio.atlassian.net/browse/ALLUXIO-2031

[ALLUXIO-2031] fix Pseudo-terminal error when use alluxio on centos7

---

tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java

ttlExpiredCreateFileTest has been flaky lately, probably because we weren't setting the TTL interval.
note that the only real change is https://github.com/Alluxio/alluxio/pull/3724/files#diff-1be4c7950bd806f9ec493a2ebe267c61R80, the rest is moving inner classes down

[SMALLFIX] Fix expired ttl test flake

---

tests/src/test/java/alluxio/client/AbstractFileOutStreamIntegrationTest.java

InputStream should expect a return value -1 and not 0 for an empty stream.
https://alluxio.atlassian.net/browse/ALLUXIO-2092

[ALLUXIO-2092] Fix expected value in test for  Swift UFS InputStream

---

tests/src/test/java/alluxio/collections/IndexedSetConcurrencyTest.java

Reverts Alluxio/alluxio#3721
Lei has ensured that resources aren't leaked here. There was a confounding variable where IndexedSetConcurrencyTest would happen to run first on the amplab build node (amplab-worker-06) which tends to run slower.

Revert "Revert "[SMALLFIX] Add two concurrent unit tests for indexedSet""

---

tests/src/test/java/alluxio/master/ServiceSocketBindIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-1738
This test fails when run on a system which maps 0.0.0.0
in /etc/hosts, and this is done by some adblocks

[ALLUXIO-1738] Remove listenWildcardTest

---

core/common/src/test/java/alluxio/util/io/FileUtilsTest.java

Reset all modes should make the test work for various default modes, such as ubuntu has default mode '0664'

[SMALLFIX] Fix a get local file mode test under different OS.

---

pom.xml
shell/src/main/java/alluxio/shell/command/ChecksumCommand.java
tests/src/test/java/alluxio/shell/command/ChecksumCommandTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2114
This uses md5 from DigestUtils to calculate the checksum, but we can also use a sha*.

[ALLUXIO-2114] Add checksum shell command

---

core/common/src/main/java/alluxio/collections/ConcurrentHashSet.java
core/common/src/main/java/alluxio/collections/NonUniqueFieldIndex.java
core/common/src/main/java/alluxio/collections/UniqueFieldIndex.java
core/server/src/main/java/alluxio/master/block/BlockMaster.java
core/server/src/main/java/alluxio/worker/block/BlockLockManager.java
core/server/src/main/java/alluxio/worker/block/evictor/LRFUEvictor.java

CHM v8 performs better than V7 in both speed and memory footprint. We can change the ConcurrentHashMap to CHMV8 to utilize those improvements.
The jira link is: https://alluxio.atlassian.net/browse/ALLUXIO-2113

[ALLUXIO-2113] Update CHM to netty ConcurrentHashMapV8

---

core/client/src/test/java/alluxio/client/file/options/CompleteUfsFileOptionsTest.java
core/client/src/test/java/alluxio/client/file/options/CreateUfsFileOptionsTest.java
core/common/src/main/java/alluxio/Constants.java
core/common/src/main/java/alluxio/security/group/CachedGroupMapping.java
core/common/src/main/java/alluxio/security/group/GroupMapping.java
core/common/src/main/java/alluxio/security/group/GroupMappingService.java
core/common/src/main/java/alluxio/util/CommonUtils.java
core/common/src/main/resources/alluxio-default.properties
core/common/src/test/java/alluxio/security/GroupMappingServiceTestUtils.java
core/common/src/test/java/alluxio/security/authorization/PermissionTest.java
core/common/src/test/java/alluxio/security/group/GroupMappingServiceTest.java
core/common/src/test/java/alluxio/underfs/options/CreateOptionsTest.java
core/common/src/test/java/alluxio/underfs/options/MkdirsOptionsTest.java
core/common/src/test/java/alluxio/util/CommonUtilsTest.java
core/server/src/main/java/alluxio/master/file/PermissionChecker.java
core/server/src/test/java/alluxio/master/file/PermissionCheckTest.java
core/server/src/test/java/alluxio/master/file/PermissionCheckerTest.java
minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
tests/src/test/java/alluxio/master/JournalIntegrationTest.java
tests/src/test/java/alluxio/shell/command/LsCommandTest.java

This PR implements the 1) solution in https://alluxio.atlassian.net/browse/ALLUXIO-2117
Implement a cache for user to groups mapping, which is refreshed every time interval (by default 1 min). Once the system admin updates user to groups mapping, it needs 1 min to propagate to take effect in Alluxio namespace.

[ALLUXIO-2117] Add caching in user to groups mapping.

---

pom.xml

This makes it much easier to reproduce issues caused by interference between tests.

[SMALLFIX] Run tests in a deterministic order

---

core/client/src/main/java/alluxio/client/file/BaseFileSystem.java
core/client/src/main/java/alluxio/client/lineage/LineageFileSystem.java
core/client/src/test/java/alluxio/client/file/BaseFileSystemTest.java

Using dependency injection to make dependencies explicit instead of using whitebox.

[ALLUXIO-2119] Remove use of whitebox in BaseFileSystem

---

core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
core/common/src/test/java/alluxio/heartbeat/HeartbeatContextTest.java

1. Checking that constants are not null is a waste of space.
2. `checkInstanceOfTest` is generalized to check that all heartbeat threads use `SleepingTimer` by default.
3. `addNewTimerClassesTest` is changed to use `ManuallyScheduleHeartbeat` to test a more realistic scenario.

[ALLUXIO-2119] Heartbeat context test cleanup

---

core/server/src/main/java/alluxio/worker/file/DefaultFileSystemWorker.java
core/server/src/main/java/alluxio/worker/file/FileDataManager.java
core/server/src/test/java/alluxio/worker/file/FileDataManagerTest.java

1. Inject `UnderFileSystem` and `RateLimiter` into `FileDataManagerTest` instead of modifying them via Whitebox. 
2. Changes the implementation of `clearPersistFilesTest` to work without Whitebox
3. Move the construction of the mocks and `FileDataManger` to `@Before` since this is shared between almost every test

[ALLUXIO-2119] Avoid use of whitebox in FileDataManagerTest

---

core/server/src/main/java/alluxio/master/file/meta/Inode.java
core/server/src/main/java/alluxio/master/file/meta/InodeDirectory.java
core/server/src/main/java/alluxio/master/file/meta/InodeFile.java
core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/src/test/java/alluxio/master/file/meta/AbstractInodeTest.java
core/server/src/test/java/alluxio/master/file/meta/TtlBucketListTest.java
core/server/src/test/java/alluxio/master/file/meta/TtlBucketTest.java

@gpang was it intentional that we don't restore `creationTimeMs` from the journal? Do you think it would make sense to journal Inode's `lastModificationTime`?

[ALLUXIO-2119] Remove use of whitebox in TtlBucketListTest

---

core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2173
We added the logic to skip loading metadata for non-persisted directory because Alluxio loads metadata for directories that is not present in ufs everytime. Too many exceptions were thrown. 
But this can be problematic if the user creates a directory in Alluxio first and then creates files in that directory in ufs. "alluxio fs ls -f" won't be able to load metadata for that directory because it is non-persisted.  (see the unittest for an example).

[ALLUXIO-2173] Load metadata for non-persisted directory 

---

core/client/src/main/java/alluxio/client/file/FileInStream.java

Instead of having constants for log messages (BLOCK_ID_NOT_CACHED, BLOCK_ID_EXISTS_SO_NOT_CACHED) in the class, we can inline the String where it appears to be consistent with the rest of the codebase.
https://alluxio.atlassian.net/browse/ALLUXIO-1826

[ALLUXIO-1826] Remove error message constants in FileInStream

---

underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
underfs/s3/src/main/java/alluxio/underfs/s3/S3Utils.java
underfs/s3/src/test/java/alluxio/underfs/s3/S3UtilsTest.java
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUtils.java
underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUtilsTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2180
This PR adds the support to inherited S3 bucket ACL to Alluxio permission, limited to owner only. 
- S3 bucket ACL entry has 5 types of permission: `READ`, `WRITE`, `READ_ACP`, `WRITE_ACP`, `FULL_CONTROL`.
- Map READ to 0500 (which should be the only `READ_ONLY` mode to the owner), and the 
`WRITE`/`FULL_CONTROL` to be 0700 (read/write/exec to the owner).
- The object-level ACL is not used here because there's typically only object READ permission by the owner. WRITE permission is not applicable to S3 objects.
- chown/chgrp/chmod are still not propagated to S3 UFS.
Future work:
- Add similar translation in GCS and Swift.
- Currently `group` and `others` mode bits are only 0. We could add an option in Mount to support sharing the mounted …

[ALLUXIO-2180] Translate S3/S3A bucket owner and ACL to Alluxio permission.

---

integration/yarn/src/main/java/alluxio/yarn/Client.java
integration/yarn/src/main/java/alluxio/yarn/YarnUtils.java

In yarn RM HA mode, there will be multi resource manager addresses with one is active and others are standby. So we need to get RM delegation token for all of them.

[SMALLFIX] Support yarn RM HA during getting RM delegation token

---

libexec/alluxio-config.sh

After #3095, empty java.security.krb5.realm/kdc options will be added to ALLUXIO_JAVA_OPTS in all os platforms, which conflicts with the option: java.security.krb5.conf in secure hadoop env.
A simple solution is to remove the empty options and let user export krb5 options if needed.

[SMALLFIX] Remove empty java.security.krb5.realm/kdc options

---

core/client/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java

ALLUXIO-2157 Remove redundant initialization in RetryHandlingBlockMasterClient.java
Refer to https://alluxio.atlassian.net/browse/ALLUXIO-2157 for detail.

[ALLUXIO-2157]Remove redundant initialization in RetryHandlingBlockMasterClient.java

---

core/common/src/main/java/alluxio/AbstractClient.java
core/common/src/main/java/alluxio/RuntimeConstants.java

https://alluxio.atlassian.net/browse/ALLUXIO-2189
before:
```bash
$ hadoop fs -libjars core/client/target/alluxio-core-client-1.3.0-SNAPSHOT-jar-with-dependencies.jar  -ls alluxio://localhost:19998/
16/08/15 15:38:25 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/08/15 15:38:25 INFO logger.type: initialize(alluxio://localhost:19998/, Configuration: core-default.xml, core-site.xml, mapred-default.xml, mapred-site.xml, yarn-default.xml, yarn-site.xml, hdfs-default.xml, hdfs-site.xml). Connecting to Alluxio: alluxio://localhost:19998/
16/08/15 15:38:25 INFO logger.type: alluxio://localhost:19998 alluxio://localhost:19998
16/08/15 15:38:25 INFO logger.type: Loading Alluxio properties from Hadoop …
```

[ALLUXIO-2189] Reference webdoc when seeing transport framesize wrong in error message

---

core/server/src/main/java/alluxio/master/file/FileSystemMaster.java

Alluxio file is not completed yet.
https://alluxio.atlassian.net/browse/ALLUXIO-2198
When Alluxio creates a file persisted in UFS, it first creates a temporary UFS file and then renames to final destination when the Alluxio file is completed. Alluxio chown/chgrp/chown propagation to UFS file would fail before the Alluxio file is completed, because the mapped UFS file does not exist yet.
Furthermore, we should flush the latest metadata to UFS final file when the Alluxio file is completed. However that would introduce an extra RPC to UFS for each completeFile metadata op, so it's not included in this PR yet. For now, we claim that `Alluxio does not propagate chown/chgrp/chmod to UFS for incomplete files`.

[ALLUXIO-2198] [SMALLFIX] Skip permission change to UFS file if the

---

tests/src/test/java/alluxio/hadoop/fs/DFSIOIntegrationTest.java

Sometimes Jenkins is having a bad day and times out on some of these tests.

[SMALLFIX] Increase DFSIOTest timeouts

---

core/common/src/test/java/alluxio/ConfigurationTest.java
core/server/src/main/java/alluxio/master/file/FileSystemMasterWorkerServiceHandler.java
core/server/src/main/java/alluxio/worker/file/FileDataManager.java
shell/src/main/java/alluxio/shell/command/CopyFromLocalCommand.java
tests/src/test/java/alluxio/hadoop/fs/DFSIOIntegrationTest.java

- Removed not needed static declaration of inner enum in
ConfigurationTest
- Introduced automatic resource management in CopyFromLocalCommand
- Removed not needed accessor and static declarations and not needed
casts in DFSIOIntegrationTest
- Collapsed multiple catch statements into one in FileDataManager
- Collapsed multiple catch statements into one in
FileSystemMasterWorkerServiceHandler

[SMALLFIX] Small fixes in several classes

---

shell/src/main/java/alluxio/shell/command/CopyFromLocalCommand.java
tests/src/test/java/alluxio/shell/command/CopyFromLocalCommandTest.java
underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java

This PR is for a few potentials NPEs in alluxio shell when using copyFromLocal. 
The case a dir is not readable is rare though.
./bin/alluxio fs copyFromLocal nonReadableDir /destDir
```
Exception in thread "main" java.lang.NullPointerException
at alluxio.shell.command.CopyFromLocalCommand.copyFromLocalDir(CopyFromLocalCommand.java:95)
at alluxio.shell.command.CopyFromLocalCommand.copyFromLocal(CopyFromLocalCommand.java:189)
at alluxio.shell.command.CopyFromLocalCommand.run(CopyFromLocalCommand.java:75)
at alluxio.cli.AlluxioShell.run(AlluxioShell.java:177)
at alluxio.cli.AlluxioShell.main(AlluxioShell.java:65)
```

[SMALLFIX] Fix a few potential null pointers in shell

---

core/server/src/main/java/alluxio/worker/DefaultAlluxioWorker.java
core/server/src/main/java/alluxio/worker/netty/NettyDataServer.java
tests/src/test/java/alluxio/master/lineage/LineageMasterIntegrationTest.java

This PR makes fixes various minor issues:
- removes duplicate call to stop the worker metrics system
- uses the proper API (as opposed to sleeping in a loop) to wait for the data server executor groups to shutdown; this speeds up integration tests from 4:50 to 4:30 on my machine
- replaces unnecessary `protected`qualifiers  with `private`

[SMALLFIX] Various improvements.

---

core/common/src/main/java/alluxio/wire/BlockInfo.java
core/common/src/main/java/alluxio/wire/BlockLocation.java
core/common/src/main/java/alluxio/wire/CommandLineJobInfo.java
core/common/src/main/java/alluxio/wire/FileBlockInfo.java
core/common/src/main/java/alluxio/wire/FileInfo.java
core/common/src/main/java/alluxio/wire/JobConfInfo.java
core/common/src/main/java/alluxio/wire/LineageInfo.java
core/common/src/main/java/alluxio/wire/LockBlockResult.java
core/common/src/main/java/alluxio/wire/MountPointInfo.java
core/common/src/main/java/alluxio/wire/WorkerInfo.java
core/common/src/main/java/alluxio/wire/WorkerNetAddress.java

Explicitly use `HashMap` and `ArrayList` since they are `Serializable` but `Map` and `List` are not.

[SMALLFIX] Ensure that wire types are Serializable

---

tests/src/test/java/alluxio/underfs/UnderStorageSystemInterfaceIntegrationTest.java
underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java

This addresses https://alluxio.atlassian.net/browse/ALLUXIO-2211.
The core problem is that FileSystemMaster:loadMetadataAndJournal calls list as follows:
String[] files = ufs.list(ufsUri.getPath());
getPath eliminates the 'swift://container/' scheme from the uri. The Swift UFS and some others I presume expect that the scheme is present. Although others are more robust to an absence. This PR makes Swift more robust.
I will address correct loadMetadataAndJournal to pass the fully qualified path to a UFS in a later PR which establishes a contract with all UFSs.

[ALLUXIO-2211] Fix recursive loadMetadata of a Swift directory

---

core/common/src/main/java/alluxio/Configuration.java
core/common/src/main/java/alluxio/exception/ExceptionMessage.java

"Invalid configuration key" makes it sound like the key is mis-typed or unsupported, but it actually just means that no value was set for that key.

[SMALLFIX] Improve error message when configuration is undefined

---

core/client/src/main/java/alluxio/client/file/policy/LocalFirstPolicy.java

Remove redundant initialization in LocalFirstPolicy.java
private String mLocalHostName = null; can be simplified to private String mLocalHostName;
jira ticket: https://alluxio.atlassian.net/browse/ALLUXIO-2158

[ALLUXIO-2158] Remove redundant initialization in LocalFirstPolicy.java

---

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java

Two reasons:
1. Alluxio uses hostname when returning cached block locations. 
2. Keep it consistent with Spark.  https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/rdd/ReliableCheckpointRDD.scala & line = 89
https://github.com/apache/spark/blob/master/streaming/src/main/scala/org/apache/spark/streaming/util/HdfsUtils.scala & line = 72

[SMALLFIX] Use hostname instead of ip:port as the ufs block location

---

build/style/check_no_windows_line_endings.sh

no need to show the output of git status during the build

[SMALLFIX] Quiet down line ending check

---

docs/_data/table/en/common-configuration.yml

yml gets confused when lines end with ":"

[DOCFIX] Fix jekyll compilation

---

underfs/swift/src/main/java/alluxio/underfs/swift/MidPartLongRange.java
underfs/swift/src/main/java/alluxio/underfs/swift/SwiftInputStream.java
underfs/swift/src/main/java/alluxio/underfs/swift/SwiftRange.java

Even though the JOSS AbstractRange parameter is named 'length', it actually expects 'end position' to be passed.
Ref: RANGE_HEADER_VALUE_PREFIX in https://github.com/javaswift/joss/blob/bf0b8e411a1022e167e034ba4c3482670d46b6fe/src/main/java/org/javaswift/joss/headers/object/range/AbstractRange.java
Ref: http://developer.openstack.org/api-ref/object-storage/index.html?expanded=get-object-content-and-metadata-detail

[SMALLFIX] JOSS range parameters fix

---

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
underfs/hdfs/src/test/java/alluxio/underfs/hdfs/HdfsUnderFileSystemTest.java

Disables the HDFS client cache when constructing the HDFS under storage file system, so that the configuration passed in will be effective. 
Otherwise an application may create an HDFS client directly or indirectly, and that will shadow the configurations during the under storage file system construction.

[SMALLFIX] Disable the HDFS cache in HDFS under storage file system

---

shell/src/main/java/alluxio/shell/AlluxioShellUtils.java

Same as previous PR for CopyFromLocalCommand.java, in AlluxioShellUtils.java, File.listFiles() could return null. 
http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/solaris/native/java/io/UnixFileSystem_md.c

[SMALLFIX] handle NPE in shell utils

---

core/server/src/test/java/alluxio/worker/netty/NettyDataServerTest.java

Before we would have to wait a few seconds after each test for the quiet period to elapse.

[SMALLFIX] Fix slowness in Netty data server test

---

core/common/src/main/java/alluxio/exception/ExceptionMessage.java
core/server/src/test/java/alluxio/master/file/meta/InodeTreeTest.java

So the exception message will be changed from 
```Block 123,456,789 is not available on local machine```
to 
```Block 123456789 is not available on local machine```

[SMALLFIX] In ExceptionMessage, correctly format those fields of long (e.g. IDs)

---

core/client/src/main/java/alluxio/client/UnderFileSystemFileReader.java
core/client/src/main/java/alluxio/client/UnderFileSystemFileWriter.java
core/client/src/main/java/alluxio/client/file/DelegatedUnderStoreStreamFactory.java
core/client/src/main/java/alluxio/client/file/UnderFileSystemFileInStream.java
core/client/src/main/java/alluxio/client/file/UnderFileSystemFileOutStream.java
core/client/src/main/java/alluxio/client/netty/NettyUnderFileSystemFileReader.java
core/client/src/main/java/alluxio/client/netty/NettyUnderFileSystemFileWriter.java
core/common/src/main/java/alluxio/PropertyKey.java
docs/_data/table/en/user-configuration.yml
docs/_data/table/user-configuration.csv

To make code structure consistent with `RemoteBlockReader` and `RemoteBlockWriter`.

[SMALLFIX] Refactor netty UnderFileSystemFile reader and writer.

---

core/server/pom.xml

https://alluxio.atlassian.net/browse/ALLUXIO-1956
Excludes the older servlet-api which is brought in by hadoop client. The artifact ID was changed so we cannot rely on dependency management to resolve this.

[ALLUXIO-1956] Java 8 fix for Hadoop 2.6

---

underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java

Makes the log severity consistent between the ufses.

[SMALLFIX] Decrease log severity of S3A unsupported warnings to debug.

---

docs/cn/Running-Alluxio-Fault-Tolerant.md

I update the chinese version docs to the latest. Add the extra instructions about setting "worker heartbeat timeout value" to a larger value to avoid exceptions when master failover.
The problem is mentioned in [Alluxio User Group](https://groups.google.com/forum/#!topic/alluxio-users/W9Ryj4HCcxI)

[DOCFIX] Fix cn docs ported from master branch

---

core/server/src/main/java/alluxio/master/file/FileSystemMaster.java

For filesystem master `delete`/`rename`, we don't propagate the operations when replaying the journals. This should be the same case for `setAttribute`.

[SMALLFIX] Donot set attribute to UFS when replaying journals

---

core/client/src/main/java/alluxio/client/file/FileOutStream.java

This is unnecessary since we will not be able to recover the new path if a rename operation has occurred.

[SMALLFIX] Remove update ufs path on client side.

---

pom.xml

We rely on 2.2+, but hadoop-client uses 2.1

[SMALLFIX] Exclude jsp from hadoop client dependency

---

tests/src/test/java/alluxio/master/AlluxioMasterRestApiTest.java

UFSes can return -1 when it is unknown how much capacity is available (ie. object storage).

[SMALLFIX] Update rest integration test

---

core/server/pom.xml
underfs/gcs/pom.xml
underfs/s3/pom.xml

Addressing issues reported here on our mailing list:
https://groups.google.com/forum/#!topic/alluxio-users/3VTRH6kXz0g
in parent `pom.xml`, there is one entry in `dependencyManagement` section:
```xml
<dependency>
<groupId>commons-codec</groupId>
<artifactId>commons-codec</artifactId>
<version>1.10</version>
</dependency>
```

[SMALLFIX] Remove conflicting commons-codec version, which has been dependency-managed

---

core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
docs/_data/table/common-configuration.csv
docs/_data/table/en/common-configuration.yml
tests/pom.xml
tests/src/test/java/alluxio/underfs/UnderStorageSystemInterfaceIntegrationTest.java
underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java

Large directory list and delete test pagination in the UFS. To speed up testing the parameter "alluxio.underfs.listing.length" can be set to a small number, allowing testing pagination for smaller directories.
S3 returns a maximum of 1000 list items. Didn't find similar documentation for other UFSs.

[SMALLFIX] Configuration parameter for UFS listing length

---

docs/_includes/Configuring-Alluxio-with-S3/bootstrapConf.md

We don't need to specify the ufs anymore.

[DOCFIX] S3 docs fix

---

core/client/src/main/java/alluxio/client/ClientContext.java
core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
core/common/src/main/java/alluxio/metrics/MetricsConfig.java
examples/src/main/java/alluxio/cli/TestRunner.java
examples/src/main/java/alluxio/examples/BasicNonByteBufferOperations.java
examples/src/main/java/alluxio/examples/BasicOperations.java

When doing `alluxio runTests`, it outputs to console messages unnecessary. This PR removes these logs.
Especially, the metrics config file is optional
```bash
2016-09-30 11:00:41,442 ERROR type (MetricsConfig.java:loadConfigFile) - Error loading metrics configuration file.
2016-09-30 11:00:41,442 WARN  type (MetricsSystem.java:startSinksFromConfig) - Sinks have already been started.
```
@peisun1115

[SMALLFIX] [branch-1.3] Remove excessive logging messages w.r.t. metrics system

---

core/common/src/main/java/alluxio/collections/NonUniqueFieldIndex.java
core/common/src/main/java/alluxio/collections/UniqueFieldIndex.java

https://alluxio.atlassian.net/browse/ALLUXIO-2142
Removed newline before last return statement from containsObject() in NonUniqueFieldIndex.java and UniqueFieldIndex.java

[ALLUXIO-2142] - Removed newline from containsObject method

---

core/server/src/main/java/alluxio/worker/file/UnderFileSystemManager.java
core/server/src/test/java/alluxio/worker/file/UnderFileSystemManagerTest.java

Removes an unnecessary exists check, the logic consistent with the case when delegation is disabled.
The exists check should not pass in normal operation since the URI is a temporary path. Only on client retries could this be a problem, and in that case it is better to allow the client to continue with a new file (since it has not written any data) instead of throwing an exception.

[SMALLFIX] Delegation create optimization

---

core/common/src/main/java/alluxio/AbstractClient.java
core/common/src/main/java/alluxio/network/connection/ThriftClientPool.java

@calvinjia @peisun1115 
This should be the right way to fix the hanging client issue when a SIPMLE client tries to connect with a NOSASL server, as opposed to https://github.com/Alluxio/alluxio/pull/4008
Also, `alluxio.security.authentication.socket.timeout.ms` default to 10min seems a bit too long, is it mainly for remote object storage which can be pretty slow?

[SMALLFIX] Do not retry if socket times out in transport.open

---

core/server/pom.xml
tests/pom.xml

When a library is directly referenced in the source code, putting it directly in the corresponding pom file is considered as a good practice. This PR does some tuning in pom files regarding the conflict between `com.sun.jersey`(1.x) and `org.glassfish.jersey` (2.x):
1. make use of `org.glassfish.jersey.core:jersey-server` explicit (also `javax.ws.rs:javax.ws.rs-api`)
2. better exclude classes of `com.sun.jersey` from module `tests`.

[SMALLFIX] [branch-1.3] Improve server related dependency

---

underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java

`getObjectDetails` will try to find a folder, but `getFileSize` only applies to files.

[SMALLFIX] Skip folder check on get file size

---

core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/main/java/alluxio/network/connection/NettyChannelPool.java
docs/_data/table/cn/user-configuration.yml
docs/_data/table/en/user-configuration.yml

This is to provide an option to make >=1.3.0 client backward compatible with <=1.2.0 server

[SMALLFIX] Add an option to disable netty channel pool

---

underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java

Reverts Alluxio/alluxio#3928
This causes significant performance overhead for renaming large (~GBs) files in S3. We should make this either tunable or set automatically based on a heuristic in the future.

[Revert] [ALLUXIO-2233] Update S3A min copy part size.

---

core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
core/server/src/main/java/alluxio/worker/file/FileSystemMasterClient.java
core/server/src/main/java/alluxio/worker/file/FileWorkerMasterSyncExecutor.java

https://alluxio.atlassian.net/browse/ALLUXIO-2215
When the file being async persisted is deleted from master, the worker heartbeat after the persist will crash due to the file not exist failure. This PR addresses the issue by logging the issues on master, but not returning exception to the heartbeat request.

[ALLUXIO-2215] Fixed the heartbeat thread crashing during the async persist

---

deploy/vagrant/provision/start_alluxio_on_standalone.yml

We no longer use export for alluxio-env.sh

[SMALLFIX] Fix vagrant script setting master hostname

---

deploy/vagrant/provision/roles/alluxio/tasks/config.yml
deploy/vagrant/provision/roles/ufs_gcs/files/config_alluxio.sh
deploy/vagrant/provision/roles/ufs_hadoop1/files/config_alluxio.sh
deploy/vagrant/provision/roles/ufs_hadoop2/files/config_alluxio.sh
deploy/vagrant/provision/roles/ufs_s3/files/config_alluxio.sh
deploy/vagrant/provision/roles/ufs_swift/files/config_alluxio.sh

Layout of alluxio-env.sh is updated after release 1.1, and in branch-1.3, the layout of alluxio-env.sh generated by `alluxio bootstrapConf` is updated again, this PR updates the deploy module to respect these new layouts, and keep backward compatibility for older layouts as well.

[SMALLFIX] Update the deploy module to respect the new alluxio-env.sh layout

---

core/client/src/main/java/alluxio/client/file/FileInStream.java

Add a newline between the description and the `@throws` tags in the javadoc of `readCurrentBlockToEnd` method.
[https://alluxio.atlassian.net/browse/ALLUXIO-2127](https://alluxio.atlassian.net/browse/ALLUXIO-2127)

[ALLUXIO-2127] Improve Javadoc spacing in FileInStream

---

core/client/src/main/java/alluxio/client/file/FileInStream.java

https://alluxio.atlassian.net/browse/ALLUXIO-2126
I Merged the javadoc in FileInStream.java for the variable mPos into one line.

[ALLUXIO-2126] The javadoc in FileInStream.java for the variable mPos can be one line

---

core/common/src/main/java/alluxio/collections/FieldIndex.java

https://alluxio.atlassian.net/browse/ALLUXIO-2103
The javadoc for FieldIndex.java size() says: "in this indexed set". Instead, it should say "in this index".

[ALLUXIO-2103]Update javadoc for FieldIndex#size()

---

core/common/src/main/java/alluxio/security/authentication/AuthenticatedClientUser.java

AuthenticatedClientUser uses `ThreadLocal` user, so there's no need to use synchronized for setter and getter.

[SMALLFIX] Remove unnecessary synchronized

---

core/server/src/main/java/alluxio/master/file/meta/Inode.java

https://alluxio.atlassian.net/browse/ALLUXIO-2297
In Inode.java (alluxio.master.file.meta.Inode),
change
protected boolean mDirectory;
to
protected final boolean mDirectory;
as this member variable is not changed after init

[ALLUXIO-2297] Mark member variable mDirectory final in class Inode

---

core/server/src/main/java/alluxio/master/file/meta/InodeTree.java

https://alluxio.atlassian.net/browse/ALLUXIO-2324
Removed unused method getNonexistentPathIndex and member variable mNonexistentIndex in InodeTree, and also adjust the related method

[ALLUXIO-2324]Removed unused method getNonexistentPathIndex in InodeTree

---

core/server/src/main/java/alluxio/worker/block/BlockWorker.java

This file refers to metadata as "meta data". We should correct this to "metadata".

[SMALLFIX] Fix javadoc in BlockWorker.java

---

core/server/src/main/java/alluxio/worker/block/evictor/EvictionDirCandidates.java

[https://alluxio.atlassian.net/browse/ALLUXIO-2283](url)
Fix javadoc in EvictionDirCandidates.java
This file refers to metadata as "meta data". We should correct this to "metadata".
modified by MG1633049

[ALLUXIO-2283]Fix javadoc in EvictionDirCandidates.java

---

core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java

https://alluxio.atlassian.net/browse/ALLUXIO-2338
Right now we handle an exception by both logging and rethrowing the exception. This isn't great because the code which catches the thrown exception will also log it, so we will log the same exception multiple times.
We should remove the log statement.

[ALLUXIO-2338] Improve error handling in NetworkAddressUtils#getLocalHostName

---

core/common/src/main/java/alluxio/AbstractClient.java

Only keep the @return since it is a getter function.
Issue: https://alluxio.atlassian.net/browse/ALLUXIO-2301
Author: Zixuan Wang, MG1633082, Nanjing University.

[ALLUXIO-2301][DOCFIX]Remove the description of isConnected function in AbstractClient.java

---

core/server/src/main/java/alluxio/worker/block/TieredBlockStore.java

https://alluxio.atlassian.net/browse/ALLUXIO-2129
In TieredBlockStore.java, the javadoc for the writelock should say mMetadataLock instead of mMetadataReadLock

[DOCFIX] Updata the javadoc for the writelock in TieredBlockStore.java

---

underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
underfs/swift/src/test/java/alluxio/underfs/swift/SwiftUnderFileSystemTest.java

Uri hostname does not permit the underscore character. Using getHost return null for a container name with _ because of validation.
Authority is the combination of any user, host and port.

[SMALLFIX] Permit underscore as Swift container name

---

pom.xml

We don't revision this file so there's no reason it needs to be license-checked

[SMALLFIX] Exclude alluxio-site.properties from license check

---

core/common/src/main/java/alluxio/LeaderInquireClient.java

https://alluxio.atlassian.net/browse/ALLUXIO-2304
Remove the unnecessary description for getMasterAddress, only the @returns clause is necessary.

[ALLUXIO-2304] Remove the unnecessary description for getMasterAddress

---

core/server/src/main/java/alluxio/master/file/meta/InodeTree.java

https://alluxio.atlassian.net/browse/ALLUXIO-2323
Annotation @SuppressWarnings("unchecked") is not needed for variable mInodes

[ALLUXIO-2323] Remove unnecessary suppresswarning annotation in InodeTree

---

bin/alluxio-start.sh

https://alluxio.atlassian.net/browse/ALLUXIO-2392
I configured 50 slaves and use the HDFS UnderFS to the alluxio cluster. After I configured and start the master using:
```
bin/alluxio format 
bin/alluxio-start master
```
everything goes fine. And then when I try to start all the workers using: 
```
bin/alluxio-start.sh workers SudoMount
```
no slave started correctly.
After debuged the start script, I found that it is because a bug in the start script as below:
```bash
259   case "${ACTION}" in
......
287     workers)
288       ${LAUNCHER} "${BIN}/alluxio-workers.sh" "${BIN}/alluxio-start.sh" "worker" "${MOPT}" \
289        "${ALLUXIO_MASTER_HOSTNAME}"
290       ;;
```
It added the `${ALLUXIO_MASTER_HOSTNAME}`  in the tail of the bash command which will launched at every slaves to start …

[ALLUXIO-2392] Bug in alluxio-start.sh when batch start workers

---

tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java

https://github.com/Alluxio/alluxio/pull/4157 should fix the leak. This PR is to make sure the resource is reset in the JournalShutdownIntegrationTest so that JournalShutdownIntegrationTest can fail instead of the one runs after it.

[SMALLFIX] Clear client pool  in JournalShutdownIntegrationTest

---

core/server/src/main/java/alluxio/master/file/meta/InodeTree.java

https://alluxio.atlassian.net/browse/ALLUXIO-2318
For method computePathForInode() in InodeTree.java, the javadoc param for "inode" should link to Inode.

[ALLUXIO-2318]  javadoc param for "inode" should link to Inode

---

core/common/src/main/java/alluxio/collections/FieldIndex.java

https://alluxio.atlassian.net/browse/ALLUXIO-2101
In the javadoc class comments for FieldIndex.java, there are several places where it says "this IndexedSet". These should be updated to just say "IndexedSet".

[ALLUXIO-2101] Update javadoc for FieldIndex class comments

---

core/server/src/main/java/alluxio/worker/block/meta/StorageDir.java

https://alluxio.atlassian.net/browse/ALLUXIO-2277
This file often refers to metadata as "meta data". I correct this to "metadata".

[ALLUXIO-2277] Fix javadoc in StorageDir.java by "@lyzGithub"

---

underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystemFactory.java

https://alluxio.atlassian.net/browse/ALLUXIO-2349
Right now we handle an exception by both logging and rethrowing the exception. This isn't great because the code which catches the thrown exception will also log it, so we will log the same exception multiple times.
We should remove the log statement.

[ALLUXIO-2349]Improve error handling in GCSUnderFileSystemFactory#create

---

core/server/src/test/java/alluxio/worker/block/evictor/EvictorTestUtils.java

Accoding the requirement of ALLUXIO-2278 on JIRA , i just fix the javadoc in EvictorTestUtils.java .I correct the word 'meta data' to word 'metadata' 
The link of JIPA ticket is https://alluxio.atlassian.net/browse/ALLUXIO-2278

 [ALLUXIO-2278] correct 'meta data' to 'metadata'

---

core/common/src/main/java/alluxio/LeaderSelectorClient.java

Remove the unnecessary javadoc description for getName, only the @returns clause is necessary.

[ALLUXIO-2310]improve javadoc for LeaderSelectorClient (getName)

---

core/server/src/main/java/alluxio/master/file/meta/InodeTree.java

https://alluxio.atlassian.net/browse/ALLUXIO-2325
Removed unused method getInode() and member variable mInode in InodeTree, and adjust related method TraversalResult().
modified by dg1533502

[ALLUXIO-2325] Remove unused method getInode in InodeTree

---

core/common/src/main/java/alluxio/underfs/UnderFileSystemRegistry.java

Makes it more clear to the user that there may be something wrong with the path.

[SMALLFIX] Better error message when ufs fails to find a suitable factory.

---

core/common/src/main/java/alluxio/resource/DynamicResourcePool.java

https://alluxio.atlassian.net/browse/ALLUXIO-2236
Use linked list (similar as LRU cache) to store the resources to reduce lock contention.

[ALLUXIO-2236] Improve DynamicResourcePool

---

shell/src/main/java/alluxio/cli/AlluxioShell.java
tests/src/test/java/alluxio/shell/command/SetTtlCommandTest.java

We should print error messages to the user, not propagate runtime exceptions

[SMALLFIX] Improve shell error handling of RuntimeExceptions

---

core/common/src/main/java/alluxio/network/connection/NettyChannelPool.java

https://alluxio.atlassian.net/browse/ALLUXIO-2275
replaced 'channel with 'channels' at '//be newly created channel' in NettyChannelPool.java

[ALLUXIO-2275]replaced 'channel' with 'channels' at '//be newly created channel' in NettyChannelPool.java

---

core/common/src/main/java/alluxio/metrics/sink/JmxSink.java

https://alluxio.atlassian.net/browse/ALLUXIO-2284
public class JmxSink implements Sink {
should be
public final class JmxSink implements Sink {
as this class is not expected to have subclasses

[ALLUXIO-2284]Mark class JmxSink as final in JmxSink.java

---

core/client/src/main/java/alluxio/client/block/BlockStoreContext.java
core/client/src/main/java/alluxio/client/block/LocalBlockInStream.java
core/client/src/main/java/alluxio/client/block/LocalBlockOutStream.java
core/client/src/main/java/alluxio/client/block/RemoteBlockInStream.java
core/client/src/main/java/alluxio/client/block/RemoteBlockOutStream.java
core/client/src/main/java/alluxio/client/block/RetryHandlingBlockWorkerClient.java
core/client/src/main/java/alluxio/client/file/FileOutStream.java
core/client/src/main/java/alluxio/client/file/FileSystemWorkerClient.java
core/client/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
tests/src/test/java/alluxio/master/ServiceSocketBindIntegrationTest.java
tests/src/test/java/alluxio/worker/DataServerIntegrationTest.java

Patterns to be avoided (esp in Constructor and close):
1. 
```
CloseableResource r = new CloseableResource();
doSomeWorkAndThrowException();
r.close();  // leak
```
2.
```
CloseableResource r1, r2 
try {
doSomeWorkAndThrowException();
} finally {
r1.close();  // throw exception 
r2.close(); // leak
}
```
3.
```
CloseableResource r1
ReleaseableResource r2
try {
doSomeWorkAndThrowException();
} finally {
r1.close();  // throw exception 
release(r2); // leak
}
```

[SMALLFIX] Close resources to avoid resource leaks

---

core/client/src/main/java/alluxio/client/block/RetryHandlingBlockWorkerClient.java
core/client/src/main/java/alluxio/client/file/FileSystemWorkerClient.java

Its unnecessary to have a hundred+ threads for heartbeats.

[SMALLFIX] Reduce the size of the worker heartbeat threadpools to save on threads.

---

core/common/src/main/java/alluxio/collections/NonUniqueFieldIndex.java

https://alluxio.atlassian.net/browse/ALLUXIO-2106
Update the javadoc class comments for NonUniqueFieldIndex. It says: "in this {@link IndexedSet}", but it should say "in this index".

[ALLUXIO-2106]Update the javadoc class comments for NonUniqueFieldIndex. It says: "in this {@link IndexedSet}", but it should say "in this index". 

---

underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java

Prevents failing unnecessarily on concurrent folder create.

[SMALLFIX] Check isFile instead of exists in s3a mkdirs to avoid race conditions.

---

core/server/src/main/java/alluxio/master/file/meta/MountTable.java

[https://alluxio.atlassian.net/browse/ALLUXIO-2299](https://alluxio.atlassian.net/browse/ALLUXIO-2299)
In MountTable.java, 
change
`private Map<String, MountInfo> mMountTable;`
to be
`private final Map<String, MountInfo> mMountTable;`
as this member variable is no more changed after init

[ALLUXIO-2299] Mark member variable mMountTable "final" in class MountTable

---

core/common/src/main/java/alluxio/network/connection/ThriftClientPool.java
core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
core/server/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
underfs/oss/src/test/java/alluxio/underfs/oss/OSSOutputStreamTest.java

- Removed two not needed variables in FileSystemMasterIntegrationTest
- Removed two not needed variables in InodeTreeTest
- Removed not needed variable in OSSOutputStreamTest
- Moved variable into try-statement and removed not needed return statement in ThriftClientPool
- Inlined variable in UnderFileSystem

[SMALLFIX] Minor fixes of variables in different classes

---

core/client/src/test/java/alluxio/client/file/BaseFileSystemTest.java
core/common/src/test/java/alluxio/AlluxioURITest.java
core/server/src/test/java/alluxio/worker/block/BlockWorkerTest.java
core/server/src/test/java/alluxio/worker/block/allocator/AllocatorTestBase.java
tests/src/test/java/alluxio/underfs/gcs/GCSUnderStorageCluster.java
tests/src/test/java/alluxio/underfs/s3/S3UnderStorageCluster.java

- Introduced equals check in AllocatorTestBase
- Removed two not needed variables in AlluxioURITest
- Removed variable in BaseFileSystemTest
- Removed variable in BlockWorkerTest
- Introduced equals check in GCSUnderStorageCluster
- Introduced equals check in S3UnderStorageCluster

[SMALLFIX] Removed variables and removed equals check in some classes

---

core/server/src/main/java/alluxio/web/UIFileInfo.java
shell/src/main/java/alluxio/shell/command/LsCommand.java
tests/src/test/java/alluxio/shell/command/LsCommandTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2336
- Specifier characters used by String.format cause an error in the ls
shell command
- Fixed this and the ls shell command can now handle specifier
characters in a file name
- Added test for this behavior

[ALLUXIO-2336] Fixed specifier character handling in LsCommand

---

core/server/src/main/java/alluxio/master/AlluxioMaster.java

https://alluxio.atlassian.net/browse/ALLUXIO-2342
We should remove the log statement to avoid logging the same exception multiple times.

[ALLUXIO-2342]Improve error handling in AlluxioMaster#stopMasters

---

core/server/src/main/java/alluxio/cli/Format.java

Prevents format from hanging in rare situations.

[SMALLFIX] Exit at the end of format

---

core/server/src/main/java/alluxio/master/FaultTolerantAlluxioMaster.java

https://alluxio.atlassian.net/browse/ALLUXIO-2337
Right now the constructor does
} catch (Exception e) {
LOG.error(e.getMessage(), e);
throw Throwables.propagate(e);
}
}
Both logging and throwing at the same time is superfluous since the place which catches the thrown exception will also log, so we will log the same exception multiple times. We should remove the
LOG.error(e.getMessage(), e);
statement

[ALLUXIO-2337] Improve error handling in FaultTolerantAlluxioMaster constructor

---

core/server/src/main/java/alluxio/master/file/FileSystemMaster.java

The internal representation is a set, so we do not need to worry about duplicates.

[SMALLFIX] Fixes ttl propagation on checkpointing.

---

core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
core/common/src/test/java/alluxio/underfs/UnderFileSystemTest.java
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystemFactory.java

Remove unnecessary parse function and move isHadoopUnderFS to Hdfs factory.

[SMALLFIX] Cleanup UFS API

---

pom.xml

This allows us to run our tests with multiple forked JVMs, giving a very significant speedup.
Running with `-DforkCount=8`, my integration test time went from 6:42 to 2:02.
@apc999 @calvinjia

[SMALLFIX] Update surefire version

---

integration/mesos/src/main/java/alluxio/mesos/AlluxioScheduler.java

Previously we assumed that Alluxio distribution tarballs have a root directory named `alluxio-version`. This change still works for that case, but now also works when the root directory is named just `alluxio`.

[SMALLFIX] Fix Mesos when root tarball directory is "alluxio"

---

conf/metrics.properties.template
core/common/pom.xml
core/common/src/main/java/alluxio/metrics/sink/GangliaSink.java
docs/cn/Metrics-System.md
docs/en/Metrics-System.md
pom.xml

https://alluxio.atlassian.net/browse/ALLUXIO-2395
In my company, bigdata clusters environments, we use ganglia heavily to monitoring and debugging, and I noticed that alluxio doesn't support ganglia metrics sink currently.
There are somebody(like me) really needs this support.So it might be a choice to provide ganglia metrics sinker in alluxio.

[ALLUXIO-2395] add ganglia metrics sink support in alluxio

---

minicluster/src/main/java/alluxio/master/LocalAlluxioMaster.java
tests/src/test/java/alluxio/master/AlluxioMasterRestApiTest.java
tests/src/test/java/alluxio/master/ServiceSocketBindIntegrationTest.java
tests/src/test/java/alluxio/master/block/BlockMasterClientRestApiTest.java
tests/src/test/java/alluxio/master/file/FileSystemMasterClientRestApiTest.java
tests/src/test/java/alluxio/master/lineage/LineageMasterClientRestApiTest.java
tests/src/test/java/alluxio/web/WebServerIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-1621
- Removed methods marked as test-only from LocalAlluxioMaster
- Changed usage of the removed getWebLocalPort in tests to the internal master

[ALLUXIO-1621] Removed test-only methods from LocalAlluxioMaster

---

core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java

Clean up some messages in Alluxio log that are either redundant or not very helpful.

[SMALLFIX] Log message cleanup in Hadoop API

---

core/server/src/main/java/alluxio/master/file/PermissionChecker.java

This helps debugging unit/integration tests flakiness.

[SMALLFIX] Dump inode permission fields in permission check exception message.

---

core/common/src/main/java/alluxio/PropertyKey.java
core/server/src/main/java/alluxio/worker/block/ClientRWLock.java
docs/_data/table/cn/worker-configuration.yml
docs/_data/table/en/worker-configuration.yml
docs/_data/table/worker-configuration.csv

https://alluxio.atlassian.net/browse/ALLUXIO-2402
Make MAX_AVAILABLE in ClientRWLock configurable.
There is a exist property key as:
```
WORKER_TIERED_STORE_BLOCK_LOCKS = "alluxio.worker.tieredstore.block.locks";
```
As the code shows, this key is used to set how much block locks a Worker can have. And the MAX_AVAILABLE in ClientRWLock is to control a block lock's permit. These two config keys seems not exactly the same. So I add another key.
Please confirm if the new key's below name is acceptable:
```
WORKER_TIERED_STORE_BLOCK_PARALLEL = "alluxio.worker.tieredstore.block.parallel"
```

[ALLUXIO-2402] Make MAX_AVAILABLE in ClientRWLock configurable.

---

pom.xml

1. Set `reuseForks` to false so that a new JVM is used for each test class. This improves test isolation.
2. Set `forkCount` to 2. This will run two tests at a time in separate JVMs, offsetting the speed cost of setting `reuseForks` to false
3. Set `runOrder` to alphabetical. Now that test classes are run in separate JVMs, it doesn't matter what order they run in, so we might as well use a simple deterministic order.

[SMALLFIX] Change default test forking strategy

---

core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
core/common/src/main/java/alluxio/util/UnderFileSystemUtils.java
core/server/src/main/java/alluxio/master/AbstractMaster.java
core/server/src/main/java/alluxio/master/journal/CheckpointManager.java
core/server/src/main/java/alluxio/master/journal/JournalWriter.java
tests/src/test/java/alluxio/UnderFileSystemSpy.java
tests/src/test/java/alluxio/master/JournalIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2408

[ALLUXIO-2408] Fix potential journal checkpoint failure

---

tests/src/test/java/alluxio/UnderFileSystemSpy.java
tests/src/test/java/alluxio/master/JournalIntegrationTest.java

This is required to fix the build for the hadoop profiles. Previously, the local under filesystem would be mocked even when testing the hadoop under filesystem. This changes the tests to mock whatever UFS the journal is stored in.

[SMALLFIX] Hadoop journal integration fix

---

core/client/src/main/java/alluxio/client/file/FileSystemUtils.java
core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
tests/src/test/java/alluxio/shell/command/PersistCommandTest.java

We should never call mkdirs with `createParent=true` because UFS does not know about the ancestor inode permission in Alluxio namespace. Instead, all the missing ancestor directories in UFS should be created from top to the bottom, with the corresponding permission in inode.
Currently there are two places where we set `createParent` to true, one is persist command, the other one is rename with creating missing dst partent directories in UFS.

[SMALLFIX] Fix the recursive UFS mkdirs with permission

---

libexec/alluxio-config.sh

Before this change, the line 
```bash
JAVA_HOME=${JAVA_HOME:-"$(dirname $(which java))/.."}
```
would complain that `dirname` requires an operand when `which java` turned up empty
```bash
dirname: missing operand
Try 'dirname --help' for more information.
```

[SMALLFIX] Improve error message when java is not installed

---

tests/src/test/java/alluxio/hadoop/FileSystemAclIntegrationTest.java

Otherwise the test file might not show up immediately after `create`.

[SMALLFIX] Fix test by closing after create file.

---

bin/alluxio-start.sh

Looks like this was accidentally introduced in https://github.com/Alluxio/alluxio/pull/3702

[SMALLFIX] Remove unnecessary print from start script

---

core/common/src/main/java/alluxio/Configuration.java
core/common/src/test/java/alluxio/ConfigurationTest.java
pom.xml

Avoid properties set in `alluxio-site.properties` affecting test results.

[SMALLFIX] Do not load site properties when running tests

---

tests/src/test/java/alluxio/hadoop/FileSystemAclIntegrationTest.java

The set mode semantics in hadoop-1 is different. Ignoring the load metadata mode test for hadoop-1 to fix master build with `-Phadoop-1 -PhdfsTest`

[SMALLFIX] Ignore hadoop-1 for set mode test.

---

core/server/src/main/java/alluxio/master/file/PermissionChecker.java
core/server/src/test/java/alluxio/master/file/PermissionCheckTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2426 is created.
Also make the mode output more readable when permission check failed.

[SMALLFIX] Ignore flaky PermissionCheckTest

---

deploy/vagrant/Vagrantfile
deploy/vagrant/core/EnvSetup.rb
deploy/vagrant/provision/roles/alluxio/files/zookeeper.sh
deploy/vagrant/provision/roles/alluxio/tasks/config.yml

In latest master branch, a precondition is added, where unknown configuration properties cause error. This PR updates the deploy module to only set known properties for the specific version of alluxio.

[SMALLFIX] Only set appropriate property for enabling zookeeper for different alluxio versions

---

core/common/src/main/java/alluxio/PropertyKey.java
core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
core/server/src/main/java/alluxio/web/WebInterfaceGeneralServlet.java
core/server/src/main/webapp/general.jsp
docs/_data/table/en/master-configuration.yml
docs/_data/table/master-configuration.csv
minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
tests/src/test/java/alluxio/master/StartupConsistencyCheckTest.java

Allows the consistency check to propagate more info to the user and be disabled (enabled by default).
https://alluxio.atlassian.net/browse/ALLUXIO-2410

[ALLUXIO-2410] Check consistency flag

---

dev/scripts/generate-tarball.sh

${TARGET} is already an absolute path

[SMALLFIX] Fix path printed by generate-tarball.sh

---

core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
core/common/src/main/java/alluxio/underfs/options/CreateOptions.java
core/server/src/main/java/alluxio/master/journal/JournalWriter.java
core/server/src/test/java/alluxio/master/journal/JournalWriterTest.java
minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java
minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java
tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java

Current journal entry log may not be closed before a crash. Make sure that the log is readable before a close by using CreateOptions.ensureAtomic = false.

[SMALLFIX] Do not write to temporary file for active journal log

---

tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java

mExecutorsForClient.shutdown() did not shutdown the creator client thread which lead to a concurrency bug.

[SMALLFIX] Fix concurrency bug in journal test

---

core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java

- Fix a bug in `listStatus` that Alluxio Hadoop API does not return correct mode/user/group
- some cleanup
To test,   run `bin/hadoop fs -ls alluxio://localhost:19998/aaa`
before
```bash
-rw-rw-rw-   3          0 2016-11-19 17:13 alluxio://localhost:19998/aaa/bbb
-rw-rw-rw-   3          0 2016-11-19 17:13 alluxio://localhost:19998/aaa/ccc
```
after
```bash
-rw-r--r--   3 binfan staff          0 2016-11-19 17:13 alluxio://localhost:19998/aaa/bbb
-rw-r--r--   3 binfan staff          0 2016-11-19 17:13 alluxio://localhost:19998/aaa/ccc
```

[SMALLFIX] Fix Permission when listStatus in AbstractFileSystem

---

core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java

`FileSystemMasterTest` is flaky with root permission being `0755`, because the server admin user not guaranteed to be TEST_USER. Since `FileSystemMasterTest` is not specialized in permission tests, changing the UMASK here to be 000 should work around the flakiness.

[SMALLFIX] Deflake FileSystemMasterTest with permission

---

core/common/src/main/java/alluxio/underfs/AtomicFileOutputStream.java
core/common/src/main/java/alluxio/underfs/AtomicFileOutputStreamCallback.java
core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
core/common/src/main/java/alluxio/underfs/UnderFileStatus.java
core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
core/common/src/main/java/alluxio/underfs/options/ListOptions.java
core/common/src/main/java/alluxio/underfs/options/OpenOptions.java
core/common/src/test/java/alluxio/underfs/options/ListOptionsTest.java
core/common/src/test/java/alluxio/underfs/options/OpenOptionsTest.java
core/server/src/main/java/alluxio/cli/Format.java
core/server/src/main/java/alluxio/master/AlluxioMaster.java
core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
core/server/src/main/java/alluxio/worker/file/UnderFileSystemManager.java
core/server/src/test/java/alluxio/worker/file/UnderFileSystemManagerTest.java
minicluster/src/main/java/alluxio/underfs/UnderFileSystemCluster.java
tests/src/test/java/alluxio/master/JournalIntegrationTest.java
tests/src/test/java/alluxio/underfs/UnderStorageSystemInterfaceIntegrationTest.java
underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
underfs/oss/src/main/java/alluxio/underfs/oss/OSSInputStream.java
underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
underfs/oss/src/test/java/alluxio/underfs/oss/OSSInputStreamTest.java
underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
underfs/swift/src/main/java/alluxio/underfs/swift/SwiftInputStream.java
underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java

This PR addresses the following:
- listRecursive is now an option to list. All variants of list now return a status object instead of just a name. This has the additional information identifying the name as a file or a directory, used to remove the extra RPC on a follow up call.
- openAtPosition is merged into open options. Swift and OSS implementations are added to open stream at given position instead of using skip. LocalUFS and HDFS get implementations using skip internally.
- createDirect is removed from the main UFS API and moved to a callback interface used when employing AtomicFileOutStream.
- UFSs extending ObjectUnderFileSystem consistently work on a 'key' instead of a 'path', where key=stripPrefixIfPresent(path).
JIRA: https://alluxio.atlassian.net/browse/ALLUXIO-2416

[ALLUXIO-2416] Consistent use of options idiom

---

tests/src/test/java/alluxio/worker/AlluxioWorkerRestApiTest.java

NetworkAddressUtils reads from Configuration, where the worker port is set to 0 during integration tests.

[SMALLFIX] Fix unit test

---

shell/src/main/java/alluxio/shell/command/AbstractShellCommand.java
shell/src/main/java/alluxio/shell/command/CatCommand.java
shell/src/main/java/alluxio/shell/command/CheckConsistencyCommand.java
shell/src/main/java/alluxio/shell/command/DuCommand.java
shell/src/main/java/alluxio/shell/command/FileInfoCommand.java
shell/src/main/java/alluxio/shell/command/FreeCommand.java
shell/src/main/java/alluxio/shell/command/LoadCommand.java
shell/src/main/java/alluxio/shell/command/LocationCommand.java
shell/src/main/java/alluxio/shell/command/PinCommand.java
shell/src/main/java/alluxio/shell/command/ReportCommand.java
shell/src/main/java/alluxio/shell/command/RmCommand.java
shell/src/main/java/alluxio/shell/command/TailCommand.java
shell/src/main/java/alluxio/shell/command/UnpinCommand.java
shell/src/main/java/alluxio/shell/command/WithWildCardPathCommand.java

We use protected everywhere else, no reason for just a few to be package-private

[SMALLFIX] Make shell method visibilities consistent

---

integration/bin/alluxio-yarn.sh

Adding the ability to override the location Yarn by setting the environment variable $YARN_HOME. On AWS EMR, Hadoop and Yarn reside in separate locations; this fixes that issue.

[SMALLFIX] Fix Yarn home for EMR users

---

bin/alluxio-start.sh
bin/alluxio-stop.sh
bin/alluxio-workers.sh

This PR makes the following improvements to shell scripts:
- `bin/alluxio-start.sh proxies` is now supported
- `bin/alluxio-stop.sh local` is now supported
- `bin/alluxio-stop.sh proxies` is now supported
- `bin/alluxio-start.sh all` now correctly starts proxies
- `bin/alluxio-stop.sh *` stops services in the reverse order the corresponding `start` action started them
- removes brittle action type detection from `task.log`
- the `task.log` output lines of remote ssh execution are now tagged with hostname

[SMALLFIX] Improvements to shell scripts.

---

core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
core/client/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
core/common/src/main/java/alluxio/exception/ExceptionMessage.java

https://alluxio.atlassian.net/browse/ALLUXIO-2021
Currently, the first master address user provided will be used to initialize the global client context, but if the address is wrong, the user has to restart the client JVM to reset a master address.
This PR validates the master address when initializing the hadoop compatible file system API by trying to connect to master RPC port, connection failure causes client initialization failure, so that a new master address can be set. Once a valid master address is set, further initialization with a different master address will fail.

[ALLUXIO-2021] Validate master address during initializing hadoop client.

---

core/common/src/main/java/alluxio/MasterInquireClient.java

https://alluxio.atlassian.net/browse/ALLUXIO-2448
I found that the previous approach would always take over one second for the first `exists` RPC, while the low-level api would take less than 50 milliseconds. 
Docs on Zookeeper clients: http://curator.apache.org/curator-client/index.html

[ALLUXIO-2448] Use faster low-level Zookeeper API for inquire client

---

core/client/pom.xml
core/common/pom.xml
core/server/pom.xml

Upgrade netty from 4.0 to 4.1
New features in 4.1:
http://netty.io/wiki/new-and-noteworthy-in-4.1.html
The ones that are very relevant to us:
1. Easier and more precise buffer leak tracking
2. PooledByteBufAllocator as the default allocator
3. Globally unique channel ID

[SMALLFIX] Netty version upgrade

---

core/client/src/main/java/alluxio/client/file/FileSystemUtils.java
core/client/src/main/java/alluxio/client/file/options/SetAttributeOptions.java
core/client/src/test/java/alluxio/client/file/options/SetAttributeOptionsTest.java
core/common/src/main/java/alluxio/util/CommonUtils.java
core/common/src/test/java/alluxio/CommonTestUtils.java
core/server/src/main/java/alluxio/worker/file/FileDataManager.java
core/server/src/main/java/alluxio/worker/file/FileWorkerMasterSyncExecutor.java
shell/src/main/java/alluxio/shell/command/PersistCommand.java

Leverage `AsyncPersist` to remove the UFS dependency of persist shell command.
This PR fixes the ancestor permission propagation in AsyncPersist.
It also enables deprecation the Persist bit in `SetAttributeOptions`.

[SMALLFIX] Make persist shell command go though Alluxio worker

---

dev/scripts/generate-tarball.sh

Previously the tarball would end up with an empty alluxio-env.sh file.

[SMALLFIX] Clean up temp alluxio-env.sh during tarball generation

---

tests/src/test/java/alluxio/client/AbstractFileOutStreamIntegrationTest.java
tests/src/test/java/alluxio/master/lineage/LineageMasterIntegrationTest.java

`WORKER_DATA_SERVER_CLASS` by default is already set to `NETTY_DATA_SERVER`

[SMALLFIX] Integration test cleanup

---

integration/docker/bin/alluxio-master.sh
integration/docker/bin/alluxio-proxy.sh
integration/docker/bin/alluxio-worker.sh

These paths broke during the `integration/bin` refactor

[SMALLFIX] Fix relative paths

---

shell/src/main/java/alluxio/shell/command/AbstractShellCommand.java
shell/src/main/java/alluxio/shell/command/LsCommand.java
tests/src/test/java/alluxio/shell/command/LsCommandTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2461
This makes it possible to `ls` the metadata for root dir `"/"`:
`./bin/alluxio fs ls -d / `

[ALLUXIO-2461] Add -d option in ls command to list dir as plain file

---

core/common/src/main/java/alluxio/underfs/ObjectUnderFileInputStream.java

Do not re-open stream when seek pos = current pos

[SMALLFIX] Fix read performance regression for due to ObjectStore seek

---

core/client/src/main/java/alluxio/client/file/FileSystemContext.java
core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
core/client/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
core/common/src/main/java/alluxio/exception/ExceptionMessage.java

https://alluxio.atlassian.net/browse/ALLUXIO-2021
Remove a check added in https://github.com/Alluxio/alluxio/pull/4422 
When running hibench, i saw the following error.
java.io.IOException: Master address hibench-spark-Rl-peis-masters-1:19998 is different from that in client context hibench-spark-Rl-peis-masters-1/172.xx.xx.xx:19998
Failing this attempt. Failing the application.
16/12/24 06:35:14 INFO mapreduce.Job: Counters: 0
Exception in thread "main" java.io.IOException: Job failed!
at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:865)
at HiBench.BayesData.createBayesData(BayesData.java:137)
at HiBench.BayesData.generate(BayesData.java:158)
at HiBench.DataGen.run(DataGen.java:29)
at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
at …

[ALLUXIO-2021] Remove the hostname check

---

core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
core/client/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2471
We should use `ugi.getShortUserName` to get the user's login name, rather than the full principal name.

[ALLUXIO-2471] [branch-1.4] User UGI getShortUserName to get login user

---

core/common/src/main/java/alluxio/PropertyKey.java
docs/_data/table/common-configuration.csv
docs/_data/table/en/common-configuration.yml
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java

Setting the request timeout can prevent stragglers from causing significant slowdowns.

[SMALLFIX] S3A request timeout

---

conf/alluxio-env.sh.template

Clarify that `alluxio-env.sh` is now optional and recommend to use `alluxio-site.properties`

[SMALLFIX] Update comment in alluxio-env.sh

---

core/server/src/main/java/alluxio/cli/Format.java
examples/src/main/java/alluxio/cli/AlluxioFrameworkIntegrationTest.java
integration/mesos/src/main/java/alluxio/mesos/AlluxioMasterExecutor.java
integration/mesos/src/main/java/alluxio/mesos/AlluxioWorkerExecutor.java

Fixes regression introduced by #4250. We were calling `Format.main`, which would call `System.exit` even on success.

[SMALLFIX] Fix mesos executors

---

docs/cn/Debugging-Guide.md

在google论坛Alluxio Developers中，我提出了名为“Just Debug it ! Debug it ! Remote Debug with alluxio (eclipse or Idea and others)”的主题，给出了远程调试alluxio的方法，开发者Bin Fan给予了回复，建议我把方法写在调试向导中，这样很多初学者会受益于此。

[DOCFIX]在调试向导中增加Alluxio远程调试章节

---

core/server/pom.xml

(https://alluxio.atlassian.net/browse/ALLUXIO-2513)
This is a simple bug, the baseUrl have a minor mistake, but user cannot use RESTful API correctly.

[ALLUXIO-2513]The baseUrl have a minor mistake.

---

tests/src/test/java/alluxio/master/AlluxioMasterRestApiTest.java

It's expected to get invalid ufs capability for object storage.

[SMALLFIX] [branch-1.4] Fix ufs capability test with object storage

---

docs/_config.yml

In order for the docs to be rendered properly on alluxio.org, the `ALLUXIO_MASTER_VERSION_SHORT` must be set to the name of the branch (e.g., `master`, `branch-1.3`, etc.). 
This PR updates the variable to `master` on the master branch.

[DOCFIX] Update ALLUXIO_MASTER_VERSION_SHORT in _config.yml

---

conf/alluxio-site.properties.template

It becomes recommended in v1.4 to define `alluxio.master.hostname` in `alluxio-site.properties`. However, it is not in the template file.

[SMALLFIX] Add alluxio.master.hostname to alluxio-site.properties.template

---

docs/_includes/Configuring-Alluxio-with-GlusterFS/bootstrapConf.md

The ufs parameter is no longer necessary.

[DOCFIX] Glusterfs docfix

---

tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java

We've seen some flakiness which could be caused by the test time
being too short, causing the cluster to shut down before any files
are written. This bumps the time to minimize the source of flakiness.

[SMALLFIX] Deflake journal shutdown integration test

---

core/common/src/main/java/alluxio/Configuration.java

It is reasonable to set both alluxio.master.hostname and
zk fault tolerance properties when configuring the Alluixo master

[SMALLFIX] Remove warning when using alluxio.master.hostname with zk

---

docs/en/Running-Alluxio-Fault-Tolerant.md

This updates the doc to recommend setting
alluxio.master.hostname in alluxio-site.properties
instead of ALLUXIO_MASTER_HOSTNAME in alluxio-env.sh.
This reflects our latest configuration story changes.

[SMALLFIX] Update Running-Alluxio-Fault-Tolerant.md

---

core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
core/server/src/main/java/alluxio/master/file/options/LoadMetadataOptions.java
core/server/src/test/java/alluxio/master/file/options/LoadMetadataOptionsTest.java

When loading a directory from the UFS, the previous implementation makes many exists/isFile calls to the UFS. With the new UFS API these calls are unnecessary as the first listStatus on the parent directory now returns UnderFileStatus[] which contains the isFile/isDirectory bit.
This PR will majorly impact loadMetadata performance, potentially (3 x number of entries in directory) times fewer calls to UFS.

[SMALLFIX] Fix loadMetadata performance

---

docs/cn/Metrics-System.md

Consider context, it better to translate to "注册".

[DOCFIX]Wrong translation of the word "Register"

---

docs/en/Running-Alluxio-on-EC2-Yarn.md

- A couple wording changes
- The master hostname is set deterministically, so we no longer need to search for it in the "Test Alluxio" section.

[DOCFIX] Tweak yarn ec2 docs

---

docs/_data/table/user-configuration.csv

(https://alluxio.atlassian.net/browse/ALLUXIO-2510)
alluxio.user.network.netty.timeout.ms's default value is 30000

[ALLUXIO-2510]alluxio.user.network.netty.timeout.ms's default value is 30000

---

docs/en/Running-Alluxio-on-EC2-Yarn.md
integration/yarn/src/main/java/alluxio/yarn/ApplicationMaster.java
integration/yarn/src/main/java/alluxio/yarn/Client.java

Adding support for starting a Master node outside of Yarn while keeping Worker nodes in Yarn. This update allows the ApplicationMaster to detect if a Master node is running on the given Alluxio Master Hostname and then skips provisioning one in Yarn if one is running.
This is useful for EMR users as it allows them to run Alluxio Master on the EMR Master Instance and then utilize all the Core Instances for Worker nodes.
JIRA Link: https://alluxio.atlassian.net/browse/ALLUXIO-2452

[ALLUXIO-2452] Added support for starting a Master node outside of Yarn

---

tests/src/test/java/alluxio/client/RemoteBlockInStreamIntegrationTest.java

Add javadoc for RemoteBlockInStreamIntegrationTest#RemoteBlockInStreamIntegrationTest.
The third parameter reader is never used

[SMALLFIX] Add javadoc for RemoteBlockInStreamIntegrationTest#RemoteBlockInStreamIntegrationTest

---

core/client/src/main/java/alluxio/client/file/options/CreateDirectoryOptions.java
core/client/src/main/java/alluxio/client/file/options/CreateFileOptions.java
core/client/src/main/java/alluxio/client/file/options/DeleteOptions.java
core/client/src/main/java/alluxio/client/file/options/ExistsOptions.java
core/client/src/main/java/alluxio/client/file/options/FreeOptions.java
core/client/src/main/java/alluxio/client/file/options/GetStatusOptions.java
core/client/src/main/java/alluxio/client/file/options/ListStatusOptions.java
core/client/src/main/java/alluxio/client/file/options/MountOptions.java
core/client/src/main/java/alluxio/client/file/options/OpenFileOptions.java
core/client/src/main/java/alluxio/client/file/options/RenameOptions.java
core/client/src/main/java/alluxio/client/file/options/SetAttributeOptions.java
core/client/src/main/java/alluxio/client/file/options/UnmountOptions.java
core/common/src/main/java/alluxio/security/authorization/Mode.java
tests/src/test/java/alluxio/proxy/FileSystemClientRestApiTest.java
tests/src/test/java/alluxio/rest/TestCase.java

This PR fixes the following issues:
- adds JSON annotation to only serialize option fields that are set (affects tests only)
- provide private default constructor for `Mode`, which is needed for successful JSON deserialization
- improves the `SetAttribute` REST API test

[SMALLFIX] REST API improvements

---

tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java

Jenkins has been failing with timeout exceptions on this test. Increases the timeout to see if failures are just due to performance flakiness.

[SMALLFIX] Increase the timeout for waiting for a new master.

---

bin/alluxio-mount.sh
bin/alluxio-start.sh
core/common/src/main/java/alluxio/Configuration.java
core/common/src/main/java/alluxio/util/OSUtils.java
libexec/alluxio-config.sh

https://alluxio.atlassian.net/browse/ALLUXIO-2542
This PR aims to add support to customize the top tier dir freely in `alluxio-site.properties` or using `ALLUXIO_RAM_FOLDER`. In addition, it simplifies the logic 
Specifically:
- Calculating the default ram folder based on OS in Java land rather than in Bash
- Calculating the default worker memory size based on total physical memory in Java land rather than in Bash
- If top tier is not MEM, allows `NoMount`
- Don't hardcode default ram folder to system properties --- this permits setting the folder in site properties.

[ALLUXIO-2542] Enable customize top tier

---

docs/_data/table/cn/ReadType.yml
docs/_data/table/en/ReadType.yml

(https://alluxio.atlassian.net/browse/ALLUXIO-2533)
The ` for each completely read data block` portion of CACHE description in the File System API documentation should be removed as it is no longer accurate.

[ALLUXIO-2533]Update documentation of CACHE

---

core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
core/client/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
docs/en/Running-Alluxio-Fault-Tolerant.md

https://alluxio.atlassian.net/browse/ALLUXIO-2546

[ALLUXIO-2546] Improve fault tolerance + HDFS API quality of life

---

core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
core/server/src/main/java/alluxio/master/file/meta/InodeDirectory.java
core/server/src/main/java/alluxio/master/file/meta/InodeFile.java
core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/src/main/java/alluxio/master/file/options/CreateDirectoryOptions.java
core/server/src/main/java/alluxio/master/file/options/CreateFileOptions.java
core/server/src/main/java/alluxio/master/file/options/CreatePathOptions.java
core/server/src/test/java/alluxio/master/file/PermissionCheckTest.java
core/server/src/test/java/alluxio/master/file/meta/AbstractInodeTest.java
core/server/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
core/server/src/test/java/alluxio/master/file/options/CreateDirectoryOptionsTest.java
core/server/src/test/java/alluxio/master/file/options/CreateFileOptionsTest.java

This PR is a follow up to #4717, removing the `mDefaultMode` field which is now no longer needed.

[SMALLFIX] Follow up to #4717

---

docs/cn/Running-HBase-on-Alluxio.md

In Running-HBase-on-Alluxio.md, L25, changed "/base" to "/hbase".

[DOCFIX] Update Running-HBase-on-Alluxio.md

---

core/common/src/main/java/alluxio/exception/ExceptionMessage.java
core/common/src/main/java/alluxio/security/authorization/ModeParser.java
core/common/src/test/java/alluxio/security/authorization/ModeParserTest.java
shell/src/main/java/alluxio/shell/command/ChmodCommand.java
tests/src/test/java/alluxio/shell/command/ChmodCommandTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2552
This provides the initial support for specifying permissions in symbolic form when using the `chmod` command. This allows for specifying them more explicitly without users having to know how to convert them into the octal numeric form e.g.
> alluxio fs chmod u=rw,go=r /example
Syntax is based upon the standard *nix symbolic syntax with some limitations, namely:
- The permissions `X`, `s`, and `t` are not supported since they make no sense in Alluxio
- Permissions cannot be specified in mutative form i.e. `g+w` or `u-x`
Supporting mutative permissions would require more substantial changes because permissions are always applied declaratively currently. The associated JIRA contains a description of a possible future enhancement to support …

[ALLUXIO-2552] Support symbolic permissions in chmod command

---

core/common/src/main/java/alluxio/underfs/UnderFileSystemRegistry.java

The current thrown exception doesn't include a stack trace, which can
be extremely helpful for determining the root cause.

[SMALLFIX] Log warning when ufs creation fails

---

core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
core/common/src/main/java/alluxio/security/LoginUser.java

https://alluxio.atlassian.net/browse/ALLUXIO-2556
This PR fixes a problem when a user is using Alluxio with `hadoop jar -libjars` without setting `HADOOP_CLASSPATH`. In this case, user may see login error like "Failed to login: no Alluxio user is found`. The root cause is two classloaders are introduced by hadoop jar
```java
if(libjars!=null && libjars.length>0) {
conf.setClassLoader(new URLClassLoader(libjars, conf.getClassLoader()));
Thread.currentThread().setContextClassLoader(
new URLClassLoader(libjars, 
Thread.currentThread().getContextClassLoader()));
```
When Hadoop creates Alluxio FS, the first one is used to load Alluxio FS and related classes; while when entering Alluxio world, the second is used as context one. Having two classes causes confusion as a class is actually …

[ALLUXIO-2556] Set classloader when entering Alluxio land from Hadoop Cli

---

integration/docker/entrypoint.sh

When not mounting the ram folder from the host, it makes sense to use `/dev/shm` because Docker sets it up automatically and lets you configure it via `--shm-size`

[SMALLFIX] Default to using /dev/shm for dockerized Alluxio worker

---

bin/alluxio-mount.sh

https://alluxio.atlassian.net/browse/ALLUXIO-2548
In case some one set limited sudo NOPASS access to mount/umount/chmod for OS user that starts Alluxio like the following  in `/etc/sudoers`
```
alluxio    ALL=(ALL) NOPASSWD: /bin/mount * ramfs /mnt/ramdisk, /bin/umount * /mnt/ramdisk, /bin/chmod * /mnt/ramdisk
```
This PR will remove the previous requirement of sudo privileges which is too broad.
Tested on linux.

[ALLUXIO-2548] Narrow down the use of sudo privileges

---

core/common/src/main/java/alluxio/PropertyKey.java
core/server/master/src/main/java/alluxio/master/DefaultAlluxioMaster.java
docs/_data/table/cn/master-configuration.yml
docs/_data/table/en/master-configuration.yml
docs/_data/table/master-configuration.csv

https://alluxio.atlassian.net/browse/ALLUXIO-2555
To solve the problem of network connection is not closed, when I use the Presto cluster connection, as a result of multi work open/load file, resulting in a lot of connection objects can not be released, increase configuration: `alluxio.master.connection.timeout.ms`
``` java
new TServerSocket(NetworkAddressUtils.getBindAddress(ServiceType.MASTER_RPC),
connectionTimeout);
```

[ALLUXIO-2555] support thrift add timeout time

---

core/server/worker/src/main/java/alluxio/worker/file/DefaultFileSystemWorker.java
core/server/worker/src/main/java/alluxio/worker/file/FileDataManager.java
core/server/worker/src/main/java/alluxio/worker/file/UnderFileSystemManager.java
core/server/worker/src/test/java/alluxio/worker/file/FileDataManagerTest.java
tests/src/test/java/alluxio/client/PersistMultipleMountsIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2558
Since 1.4.0  moved persistence logic to the worker it is fundamentally broken when users Mount more than one under file system. This is because it takes a single instance of and under file system created from the default under file system Setting in the configuration. When multiple under file systems are mounted attempts to persist to non-default under filesystems will fail because they attempt to use the wrong under file system instance. This is one possible fix though I am not sure it is necessarily the correct one.
Have `FileDataManager` obtain `UnderFileSystem` instances as needed so it selects the
correct UFS to persist files to depending on the mount point under which
a file is located.

[ALLUXIO-2558] Proposed fix for ALLUXIO-2558

---

bin/alluxio-mount.sh

Using the `-l` flag for `umount` on Linux is a solution for the `umount: /mnt/ramdisk: device is busy.` issue (see http://unix.stackexchange.com/questions/19918/umount-device-is-busy)

[SMALLFIX] Use lazy unmount for Linux.

---

underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java

Fail if container does not exist

[SMALLFIX] Swift UFS should not try to create container if absent

---

core/client/src/main/java/alluxio/client/block/RetryHandlingBlockWorkerClient.java
core/common/src/main/java/alluxio/retry/CountingRetry.java
core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java

1. Add logging on worker side when a temp block is deleted because of expired session.
2. Reenables worker session heartbeat which was disabled accidentally in (PR#4800) 
3. Improve exception handling in sessionHeartbeat

[SMALLFIX] Fix a  session heartbeat bug

---

core/common/src/main/java/alluxio/AlluxioURI.java
core/common/src/main/java/alluxio/URI.java
core/common/src/test/java/alluxio/AlluxioURITest.java

it turns out a URL like "scheme:part2://host:123/path" is supported (and you can omit the ":" after "part2" like "scheme:part2//host:123/path" if this looks better. Adding a unit test to verify this.

[SMALLFIX] Add unit tests for multi-parts AlluxioUri

---

docs/en/Contributing-to-Alluxio.md

[DOCFIX] Updated Google java style guide link

---

core/client/src/main/java/alluxio/client/file/FileInStream.java

Especially with delegation enabled, it's confusing to receive exceptions complaining that the client can't talk directly to the UFS. With this change we will log the UFS exception for debugging purposes, and propagate the exception that caused us to attempt the direct UFS read in the first place.

[SMALLFIX] Propagate original exception when falling back to UFS read

---

core/server/common/src/main/java/alluxio/worker/AbstractWorker.java

before `class_def` should have a blank line.

[SMALLFIX]Fix javadoc checkstyle bug

---

core/server/master/src/main/java/alluxio/master/block/BlockMaster.java

Return type has changed from `Set` to `List`, but javadoc still `Set`

[SMALLFIX]Correct the javadoc of getLostWorkersInfoList

---

core/server/proxy/src/main/java/alluxio/StreamCache.java
core/server/proxy/src/test/java/alluxio/StreamCacheTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2587
Adds concurrent test to StreamCache and mark it as @ThreadSafe.
Although the cached FileInStream and FileOutStream are not thread safe, but the StreamCache is thread safe, which means concurrent put, get, invalidate operations won't cause damage to StreamCache.

[ALLUXIO-2587] Mark StreamCache as ThreadSafe and add concurrent test.

---

core/client/src/main/java/alluxio/client/block/AlluxioBlockStore.java

https://alluxio.atlassian.net/browse/ALLUXIO-2590
Replaced
LOG.warn("Failed to open local stream for block " + blockId + ". " + e.getMessage());
with
LOG.warn("Failed to open local stream for block {}: {}", blockId, e.getMessage());

ALLUXIO­2590] Fix logging style in AlluxioBlockStore

---

core/common/src/main/java/alluxio/MasterInquireClient.java

This lookup can happen very often, and the logs are only useful for debugging
purposes. The logged information can also be found by running the masterInfo
shell command or using the Zookeeper CLI.

[SMALLFIX] Reduce log level of Zookeeper master lookup

---

core/server/common/src/main/webapp/workers.jsp
core/server/master/src/main/java/alluxio/web/WebInterfaceWorkersServlet.java

Without worker id, we don't konw the workerid in the `master.log` means which worker.
Now we can find worker hostname from worker id in the workers page.

[SMALLFIX]Added a `worker Id` table column to the workers page.

---

tests/src/test/java/alluxio/client/keyvalue/KeyValuePartitionIntegrationTest.java

JIRA ticket:https://alluxio.atlassian.net/browse/ALLUXIO-2481
In alluxio/client/keyvalue/KeyValuePartitionIntegrationTest.java:
from
.setProperty(PropertyKey.KEY_VALUE_ENABLED, "true")
to
.setProperty(PropertyKey.KEY_VALUE_ENABLED, true)

[ALLUXIO-2481]Remove unnecessary toString() in setProperty in KeyValuePartitionIntegrationTest.java

---

docs/_data/table/en/operation-command.yml

Fix the grammar of setTtl documentation in `docs/_data/table/en/operation-command.yml`.
https://alluxio.atlassian.net/browse/ALLUXIO-2527

[ALLUXIO-2527] Update setTtl documentation grammar

---

bin/alluxio

This will prevent setting ALLUXIO_SHELL_JAVA_OPTS in shell to take effect

[SMALLFIX] Remove unnecessary initialization of ALLUXIO_SHELL_JAVA_OPTS in bin/alluxio

---

core/server/common/src/main/java/alluxio/cli/Format.java
core/server/common/src/main/java/alluxio/master/journal/ufs/UfsMutableJournal.java
underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java

- Print complete when format is done. otherwise it is hard to tell error or fine
- mkdir should not set owner /group when owner/group are empty string (default value for create dir Option. This is surfaced by running `alluxio format`. Previously you will see format error message like this:
```
$ bin/alluxio format
Executing the following command on all worker nodes and logging to /Users/binfan/tmp/alluxio/bin/../logs/task.log: /Users/binfan/tmp/alluxio/bin/alluxio formatWorker
Waiting for tasks to finish...
All tasks finished
Formatting Alluxio Master @ apc999
2017-03-22 11:11:43,624 INFO  Format - Formatting JOURNAL_FOLDER:/Users/binfan/tmp/alluxio/journal
2017-03-22 11:11:43,629 INFO  Format - Formatting BlockMaster_JOURNAL_FOLDER:/Users/binfan/tmp/alluxio/journal/BlockMaster
2017-03-22 …
```

[SMALLFIX] Alluxio format improvement

---

tests/src/test/java/alluxio/collections/IndexedSetConcurrencyTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2493
According to the Alluxio unit test style guide, test names should not contain the "Test" suffix.
Consequently, the IndexedSetConcurrencyTest#concurrentAddTest() should be renamed to concurrentAdd().

[ALLUXIO-2493] Remote one unnecessary 'Test' suffix

---

core/client/pom.xml
pom.xml

Guice from Hadoop dependency conflicts with Presto.
Checked with the latest presto 0.170

[SMALLFIX] Shade guice in presto profile

---

bin/alluxio
bin/alluxio-start.sh
integration/fuse/bin/alluxio-fuse.sh

https://alluxio.atlassian.net/browse/ALLUXIO-2649
If there is a space in JAVA_HOME, bin/alluxio and bin/alluxio-start.sh will not work.
For example, many Mac users' JAVA_HOME is:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
This is usually caused by running Oracle's official upgrade patch, for example from 1.6 to 1.8. Then your JAVA_HOME will be set like that.
This is not a unusually problem.For example, elasticsearch has this issue as well:
elastic/elasticsearch#6942
changed ${JAVA} to "${JAVA}" in some scripts to correctly dereference the variable

[ALLUXIO-2649] add double quote. Correctly dereference JAVA and JAVA_HOME

---

assembly/pom.xml

Currently it is being implicitly included by the client dependency.

[SMALLFIX] Add s3a dependency to assembly jar.

---

core/client/src/main/java/alluxio/client/RetryHandlingMetaMasterClient.java

https://alluxio.atlassian.net/browse/ALLUXIO-2608
Deprecate Throwables.propagate with RuntimeException in RetryHandlingMetaMasterClient.java

[ALLUXIO-2608] Deprecate Throwables.propagate with RuntimeException in RetryHandlingMetaMasterClient.java

---

core/common/src/main/java/alluxio/exception/ExceptionMessage.java
core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalWriter.java
docs/en/Debugging-Guide.md

https://alluxio.atlassian.net/browse/ALLUXIO-2672
This is not a fix to ALLUXIO-2672 but just a slightly improvement in error messages users see.
Instead of showing error like this on client side (e.g., in Spark logs) which is not clear where is wrong, at least point out it is journal problem and likely due to insufficient space on the space to write journals.
```
2017-03-20 02:33:00,219 ERROR logger.type (RpcUtils.java:call) - Unexpected error running rpc
java.lang.RuntimeException: alluxio.exception.UnexpectedAlluxioException: java.lang.RuntimeException: java.io.IOException: Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try. (Nodes: current=[10.116.50.230:50010, 10.116.78.14:50010], original=[10.116.50.230:50010, …
```

[ALLUXIO-2672] Better error message when journal write failed

---

core/server/worker/src/test/java/alluxio/network/protocol/databuffer/DataNettyBufferTest.java

This one is different, because there was a private method in DataNettyBufferTest.java named releaseBuffer(), so I first changed the private method name into releaseBufferHelper, then changes all fields which called this method, finally, I changed releaseBufferTest() to releaseBuffer().

[SMALLFIX]Change the Unit test method name follows the standard

---

core/server/common/src/main/java/alluxio/master/MasterRegistry.java
core/server/master/src/main/java/alluxio/master/DefaultAlluxioMaster.java
core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java
tests/src/test/java/alluxio/master/MasterTestUtils.java
tests/src/test/java/alluxio/master/StartupConsistencyCheckTest.java
tests/src/test/java/alluxio/master/UfsJournalIntegrationTest.java
tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
tests/src/test/java/alluxio/security/ClusterInitializationTest.java

We would often start `BlockMaster` and `FileSystemMaster`, but then only stop `FileSystemMaster`. This PR addresses this by moving masters start/stop logic to `MasterRegistry`

[SMALLFIX] Fix leaked masters

---

docs/en/Running-Hive-with-Alluxio.md

@TeddyBear1314  I think to set Alluxio properties, we need to config the hadoop `core-site.xml`. That's because Hive only hosts the metadata, the actual querying is done through MapReduce, which will use Hadoop config. For example, `fs.alluxio.impl` is set in Hadoop config, but not Hive.

[DOCFIX] Update hive docs

---

core/client/src/main/java/alluxio/client/file/RetryHandlingFileSystemWorkerClient.java

[https://alluxio.atlassian.net/browse/ALLUXIO-2616](https://alluxio.atlassian.net/browse/ALLUXIO-2616)
Modify core/client/src/main/java/alluxio/client/file/RetryHandlingFileSystemWorkerClient.java to replace
```java
throw Throwables.propagate(e);
```
with
```java
Throwables.propagateIfPossible(e);
throw new RuntimeException(e);
```

[ALLUXIO-2616] Deprecate Throwables.propagate with RuntimeException in RetryHandlingFileSystemWorkerClient.java

---

core/common/src/test/java/alluxio/exception/AlluxioExceptionTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2658
To avoid accidental subclass extension.

[ALLUXIO-2658]Make AlluxioExceptionTest final

---

core/common/src/test/java/alluxio/retry/TimeoutRetryTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2665
To avoid accidental subclass extension.

[ALLUXIO-2665] Make TimeoutRetryTest final.

---

core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java

[https://alluxio.atlassian.net/browse/ALLUXIO-2684](url)
The class javadoc for ServiceType should end with a period.

[ALLUXIO-2684] Improve javadoc in NetworkAddressUtils

---

core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java

https://alluxio.atlassian.net/browse/ALLUXIO-2592
Replace all occurrences of
LOG.error("delete failed: {}", e.getMessage());
LOG.error("Failed to rename {} to {}", src, dst);
with
LOG.warn("delete failed: {}", e.getMessage());
LOG.warn("rename failed: {}", e.getMessage());

[ALLUXIO-2592]Fix logging style in AbstractFileSystem

---

core/client/src/main/java/alluxio/client/netty/ClientHandler.java

https://alluxio.atlassian.net/browse/ALLUXIO-2694
Currently we use
mAddress = Preconditions.checkNotNull(address);
If this precondition fails, it will throw a NullPointerException with no message. We should add a second argument so that the exception will include the name of the variable that is null:
mAddress = Preconditions.checkNotNull(address, "address");

[ALLUXIO-2694] Specify null variable in ClientHandler.java precondition check

---

shell/src/main/java/alluxio/shell/command/StatCommand.java
tests/src/test/java/alluxio/shell/command/StatCommandTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2573
The stat shell command displays information about the file.
For “bin/alluxio fs stat -f <format> <path>”: prints the formatted stat info. e.g
Supported format symbol:
"%N": name of the file
"%z": size of file in bytes
"%u": owner
"%g": group name of owner
"%y" or "%Y": modification time. %y shows “yyyy-MM-dd HH:mm:ss” (the UTC date), for %Y it shows milliseconds since January 1, 1970 UTC
"%b": Number of blocks allocated for file

[ALLUXIO-2573] Add "-f" (format) option for Shell Command "bin/alluxio fs stat"

---

core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
core/client/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java

JIRA ticket:https://alluxio.atlassian.net/browse/ALLUXIO-2470
In the listStatus method, we create a filesystem with
FileSystem alluxioHadoopFs = new FileSystem(alluxioFs);
add
alluxioHadoopFs.close();
at the end of the method

[ALLUXIO-2470]Fix leaking resource in AbstractFileSystemTest

---

core/client/src/main/java/alluxio/client/file/BaseFileSystem.java

https://alluxio.atlassian.net/browse/ALLUXIO-2591
All the replacements is done,**EXCEPT** 
`LOG.info("Mount " + ufsPath.toString() + " to " + alluxioPath.getPath());`
TO
`¨LOG.debug("Mounted {} to {}, options: {}", ufsPath.toString(), alluxioPath.getPath(), options);¨`
There is a problem with this replacement that  it may lead to a mistake reported by maven described as
> error: Line is longer than 100 characters (found 101)
please check the correctness of the code for this replacement.

[ALLUXIO-2591] Fix logging style in BaseFileSystem

---

docs/_data/img.yml
docs/cn/Running-Presto-with-Alluxio.md
docs/en/Running-Presto-with-Alluxio.md

I made some improvements to the doc, including fixing the broken screenshot links and clarifying the Alluxio properties configuration. 
@gjhkael @maobaolong  Please take a look.
Also, what else did you else to show Alluxio logs in presto server log?
What I've seen is
`Found binding in [jar:file:/tmp/presto/data/plugin/hive-hadoop2/alluxio-core-client-1.5.0-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]` and some exception messages when exception happens.
Presto works with Alluxio fine though.

[DOCFIX] Presto doc improvement

---

bin/alluxio

example:
if you append append the `ALLUXIO_SHELL_DEBUG_JAVA_OPTS` in `alluxio-env.sh` as following:
```bash
ALLUXIO_SHELL_DEBUG_JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5603"
```
then you can execute your shell command with -debug between the alluxio COMMAND and GENERIC_COMMAND_OPTIONS
```bash
$ alluxio fs -debug ls /
debug mode!
Listening for transport dt_socket at address: 5603
```

[SMALLFIX] Support enter debug mode use `-debug`

---

core/server/worker/src/main/java/alluxio/worker/block/ClientRWLock.java

If a thread read, then it hold the read lock and don't unlock, then another thread want to write lock, as we all know, this thread will never get the lock, but a third thread want to get the read lock, it also never get the lock if we set the semaphore to `fair`. So i set it to `unfair` to let other read thread get read lock.
(https://alluxio.atlassian.net/projects/ALLUXIO/issues/ALLUXIO-2636)

[ALLUXIO-2636]Convert semaphore to unfair

---

shell/src/main/java/alluxio/cli/AlluxioShell.java
shell/src/main/java/alluxio/shell/AlluxioShellUtils.java
shell/src/main/java/alluxio/shell/command/HelpCommand.java
tests/src/test/java/alluxio/shell/AlluxioShellUtilsTest.java
tests/src/test/java/alluxio/shell/command/HelpCommandTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2569
Alluxio shell command "bin/alluxio fs" should provide a sub-command called "help", which works like the following:
For “bin/alluxio fs help <command>”, this will print help message for the given command.
For “bin/alluxio fs help”, this will print help messages for all supported commands.
To implement this feature, this "help" command should be a class "alluxio.shell.command.HelpCommand.java", inheriting "alluxio.shell.command.AbstractShellCommand".

[ALLUXIO-2569]Add Shell Command 'bin/alluxio fs help'

---

core/client/src/main/java/alluxio/client/file/FileSystemUtils.java

[https://alluxio.atlassian.net/browse/ALLUXIO-2615](https://alluxio.atlassian.net/browse/ALLUXIO-2615)
This JIRA modifies core/client/src/main/java/alluxio/client/file/FileSystemUtils.java to replace
```java
throw Throwables.propagate(e);
```
with
```java
Throwables.propagateIfPossible(e);
throw new RuntimeException(e);
```

[ALLUXIO-2615] modify the deprecated Throwables

---

shell/src/main/java/alluxio/shell/command/AbstractShellCommand.java
shell/src/main/java/alluxio/shell/command/LsCommand.java
tests/src/test/java/alluxio/shell/command/LsCommandTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2571
Currently "bin/alluxio fs ls <path>" command works like normal "ls" command on Linux shell, it shows the information of files or directories, including the size of a file.
This JIRA aims to add a “-h” option like linux "ls" command by which user can specify the format of file sizes in a human-readable fashion (eg 1K instead of 1024). To be more specific 
when used with the -l option, the size part of ls output use unit suffixes: Byte, Kilobyte, Megabyte, Gigabyte, Terabyte and Petabyte, like "204B", "35K", "1M", "23G" depends on the actual file size. Right now, this is enabled by default and you have to use -raw option to show the raw size. This JIRA aims to switch this by displaying the size in raw bytes by default, and only shows …

[ALLUXIO-2571]Add "-h" (HumanReadable) option for Shell Command “bin/alluxio fs ls”

---

core/common/src/main/java/alluxio/wire/CommandLineJobInfo.java

https://alluxio.atlassian.net/browse/ALLUXIO-2708
Currently we use
Preconditions.checkNotNull(command); 
If this precondition fails, it will throw a NullPointerException with no message. We should add a second argument so that the exception will include the name of the variable that is null:
Preconditions.checkNotNull(command, "command");

[ALLUXIO-2708] Specify null variable in CommandLineJobInfo.java precondition check

---

core/server/common/src/main/java/alluxio/cli/Format.java

Previously an `IllegalArgumentException` thrown by `format` would result in an incorrect message. This would happen if the UFS type is unrecognized

[SMALLFIX] Fix exception handling in Format.java

---

core/client/src/test/java/alluxio/client/util/ClientTestUtils.java

[ALLUXIO-2720]Deprecate Throwables.propagate with RuntimeException in ClientTestUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-2720

[ALLUXIO-2720] Deprecate Throwables.propagate with RuntimeException in ClientTestUtils.java

---

bin/alluxio-mount.sh

hot_files_size=$((5 * n_kb))
metadata_size=$((alloc_bitmap_size + ext_overflow_file_size + journal_file_size + \
catalog_file_size + hot_files_size + quota_users_file_size + quota_groups_file_size))
change the origin hot_file_size to hot_files_size

[SMALLFIX] fix a missing s in variable name in alluxio-mount.sh

---

core/common/src/main/java/alluxio/network/protocol/databuffer/DataByteArrayChannel.java

[https://alluxio.atlassian.net/browse/ALLUXIO-2700](url)
Currently we use
mByteArray = Preconditions.checkNotNull(byteArray);
If this precondition fails, it will throw a NullPointerException with no message. We should add a second argument so that the exception will include the name of the variable that is null:
mByteArray = Preconditions.checkNotNull(byteArray, "byteArray");

[ALLUXIO-2700] Specify null variable in DataByteArrayChannel.java precondition check

---

integration/fuse/bin/alluxio-fuse.sh
integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java

Infer MASTER_ADDRESS from MASTER_HOSTNAME and MASTER_RPC_PORT.

[SMALLFIX] Set Alluxio CLASSPATH correctly when starting Fuse connection

---

bin/alluxio
shell/src/main/java/alluxio/shell/command/AbstractShellCommand.java
shell/src/main/java/alluxio/shell/command/MountCommand.java
tests/src/test/java/alluxio/shell/command/MountCommandTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2743
This PR includes:
- Add support in mount command to take `--option` and remove `-P` since we have `--option` supported
- Fix the issue that args with space could not be passed to alluxio shell
- Add integration tests of mount command

[ALLUXIO-2743] Support specifying Mount Options for each Mount Point (part2)

---

core/common/src/main/java/alluxio/security/authentication/PlainSaslServerCallbackHandler.java

https://alluxio.atlassian.net/browse/ALLUXIO-2704
Add a second argument so that the exception will include the name of the variable that is null.

[ALLUXIO-2704] Specify null variable in PlainSaslServerCallbackHandler.java precondition check

---

minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java

It slows down the tests. Disable for now.

[SMALLFIX] Disable secondary master in the integration tests 

---

core/common/src/main/java/alluxio/util/CommonUtils.java
core/common/src/test/java/alluxio/util/CommonUtilsTest.java
shell/src/main/java/alluxio/cli/AlluxioShell.java
shell/src/main/java/alluxio/shell/AlluxioShellUtils.java
shell/src/main/java/alluxio/shell/command/AbstractShellCommand.java
shell/src/main/java/alluxio/shell/command/CheckConsistencyCommand.java
shell/src/main/java/alluxio/shell/command/ChgrpCommand.java
shell/src/main/java/alluxio/shell/command/ChmodCommand.java
shell/src/main/java/alluxio/shell/command/ChownCommand.java
shell/src/main/java/alluxio/shell/command/CpCommand.java
shell/src/main/java/alluxio/shell/command/FreeCommand.java
shell/src/main/java/alluxio/shell/command/HeadCommand.java
shell/src/main/java/alluxio/shell/command/HelpCommand.java
shell/src/main/java/alluxio/shell/command/LsCommand.java
shell/src/main/java/alluxio/shell/command/MountCommand.java
shell/src/main/java/alluxio/shell/command/RmCommand.java
shell/src/main/java/alluxio/shell/command/SetTtlCommand.java
shell/src/main/java/alluxio/shell/command/ShellCommand.java
shell/src/main/java/alluxio/shell/command/StatCommand.java
shell/src/main/java/alluxio/shell/command/TailCommand.java
shell/src/main/java/alluxio/shell/command/TestCommand.java
tests/src/test/java/alluxio/shell/AlluxioShellUtilsTest.java
tests/src/test/java/alluxio/shell/command/HelpCommandTest.java
tests/src/test/java/alluxio/shell/command/SetTtlCommandTest.java

Various change on shell side to improve its output. This PR is motivated when I was working on https://github.com/Alluxio/alluxio/pull/5166 to add a new opt in mount cmd where I found various issues with current shell command.
- Fix the issue that unknown options was treated as an arg, rather than throwing error about unrecognized option. @ifcharming , I saw you change in https://github.com/Alluxio/alluxio/pull/2604, do you have particular reason to set `stopAtNonOption` in this PR, will my PR here break anything you fixed?
This is the output after this PR. Previously it will treat `--wrongOpt` a path to ls.
```bash
$ bin/alluxio fs ls --wrongOpt
ls: Unrecognized option: --wrongOpt
Usage: ls [-d|-f|-p|-R|-h] <path>
```
- Fix the output of `bin/alluxio fs` to be cleaner. Previously we also …

[SMALLFIX] Improve shell command output

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java

`AlluxioURI` can be constructed using the relative file path, and therefore fetching the deprecated `MASTER_ADDRESS` is not needed.

[SMALLFIX] Updated Fuse to support Alluxio HA

---

core/common/src/main/java/alluxio/PropertyKey.java

The documentation is using the correct `alluxio.user.short.circuit.enabled`

[SMALLFIX] Fix a typo for a property key name.

---

examples/src/main/java/alluxio/cli/MiniBenchmark.java

Count runtime more accurately.
Separate results from different iterations as the runtime can vary from iteration to iteration.

[SMALLFIX] Some improvements to mini benchmark 

---

tests/src/test/java/alluxio/master/MasterFaultToleranceIntegrationTest.java

This has been failing a lot of builds and pull request builds lately. Lets ignore it until we have it fixed

[SMALLFIX] Temporarily ignore flaky MasterFaultToleranceIntegrationTest

---

bin/alluxio-mount.sh

Fix the typo 
@LuQQiu  it should be `${BIN}` rather than `${bin}` in your previous PR, as a lot of shell (e.g., BASH)  are case sensitive

[SMALLFIX] Fix typo in alluxio-mount.sh

---

core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
core/server/proxy/src/main/java/alluxio/proxy/AlluxioProxyProcess.java
core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java

Prevents integration tests from waiting indefinitely when a cluster resource is being created.

[SMALLFIX] Add 10s timeout for the wait for ready method.

---

core/server/worker/src/test/java/alluxio/SessionInfoTest.java

Unnecessarily uses configuration.

[SMALLFIX] Clean up session info test.

---

core/client/fs/src/main/java/alluxio/client/block/stream/BlockOutStream.java
core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java
core/client/fs/src/main/java/alluxio/client/block/stream/PacketOutStream.java
core/client/fs/src/main/java/alluxio/client/block/stream/UnderFileSystemFileOutStream.java
core/client/fs/src/test/java/alluxio/client/block/stream/NettyPacketWriterTest.java
core/protobuf/src/main/java/alluxio/proto/dataserver/Protocol.java
core/protobuf/src/proto/dataserver/protocol.proto
core/server/worker/src/main/java/alluxio/worker/block/BlockWorker.java
core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
core/server/worker/src/main/java/alluxio/worker/netty/DataServerBlockReadHandler.java
core/server/worker/src/main/java/alluxio/worker/netty/DataServerBlockWriteHandler.java
core/server/worker/src/main/java/alluxio/worker/netty/DataServerReadHandler.java
core/server/worker/src/main/java/alluxio/worker/netty/DataServerUfsBlockReadHandler.java
core/server/worker/src/main/java/alluxio/worker/netty/DataServerUfsFileWriteHandler.java
core/server/worker/src/main/java/alluxio/worker/netty/DataServerWriteHandler.java
core/server/worker/src/test/java/alluxio/worker/netty/DataServerBlockWriteHandlerTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2813
Changes the session heartbeat logic to use netty instead of thrift. Now we assume the entirety of read or write operations (including any metadata operations) are concluded before `InternalRequest#close` is called. `InternalRequest#close` will clean up any lingering temporary state.
This currently won't work for reads w/ caching since the cache logic is outside of the netty data path.

[ALLUXIO-2813] Move session logic to netty

---

core/client/fs/src/main/java/alluxio/client/block/stream/PacketOutStream.java
tests/src/test/java/alluxio/client/AbstractFileOutStreamIntegrationTest.java
tests/src/test/java/alluxio/client/FileOutStreamIntegrationTest.java

Since the control path is tied to the channel, we cannot close the channel (commit blocks) until the entire file is ready.

[SMALLFIX] Correctly clean up aborted writes

---

core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
core/client/fs/src/main/java/alluxio/client/block/stream/LocalFilePacketReader.java
core/client/fs/src/main/java/alluxio/client/block/stream/PacketInStream.java
core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
core/client/fs/src/test/java/alluxio/client/file/FileInStreamTest.java
core/protobuf/src/main/java/alluxio/proto/dataserver/Protocol.java
core/protobuf/src/proto/dataserver/protocol.proto
core/server/worker/src/main/java/alluxio/worker/netty/DataServerBlockReadHandler.java
core/server/worker/src/main/java/alluxio/worker/netty/DataServerShortCircuitReadHandler.java
core/server/worker/src/main/java/alluxio/worker/netty/NettyExecutors.java
core/server/worker/src/main/java/alluxio/worker/netty/PipelineHandler.java
tests/src/test/java/alluxio/worker/block/meta/TierPromoteIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2813
A few things which I think are suboptimal atm
1. Passing a boolean instead of ReadType. If we go with read type we may be able to save more metadata fields, but I think it should be part of a separate refactor.
2. Worker side lock logic. The worker side logic currently assumes locks are held by possibly remote clients which makes locking awkward when we move things to netty (in the same JVM).
3. Threadpool/runnable in short circuit reader. As a developer the code there seems unintuitive.

[ALLUXIO-2813] Move promote logic to data path

---

core/server/common/pom.xml
core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java
core/server/common/src/main/java/alluxio/master/journalv0/ufs/UfsJournalWriter.java
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileInputStream.java
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileOutputStream.java
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java

We only use the dependency to call a special output stream API which can be isolated to the ufs module.

[SMALLFIX] Remove hadoop-client dependency in servers

---

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java

- `ObjectUnderFileSystem:getDirectoryStatus` updated to work correctly for pseudo-directory with no breadcrumb
- JOSS Swift library does not return size and last modified for pseudo-directory objects => populating `ObjectStatus` with invalid values

[SMALLFIX] Minor issues w/ Object UFS

---

core/common/src/main/java/alluxio/PropertyKey.java
docs/_data/table/common-configuration.csv
docs/_data/table/en/common-configuration.yml
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java

Update the suffix for pseudo-directories in S3A to path separator.
Caveats when migrating from older versions:
- 1.4.0 directory breadcrumbs will show up as files
- `isDirectory` will not recognize 1.4.0 empty directories
- `deleteDirectory` will not delete 1.4.0 empty directories. Also performance could be impacted as `UfsSyncChecker` may falsely detect nested directory breadcrumbs as un-synced files

[SMALLFIX] Update S3A directory suffix

---

dev/scripts/generate-tarball.sh

The semi-colon should be removed, otherwise the `BUILD_OPTS` is not passed to the script in the next statement.

[SMALLFIX] Fix the example in generate-tarball script

---

core/common/src/main/java/alluxio/security/authorization/ModeParser.java
core/common/src/main/java/alluxio/util/CommonUtils.java
core/common/src/main/java/alluxio/util/FormatUtils.java
core/common/src/main/java/alluxio/util/ShellUtils.java
core/common/src/main/java/alluxio/util/UnixMountInfo.java
core/common/src/test/java/alluxio/util/CommonUtilsTest.java
core/common/src/test/java/alluxio/util/FormatUtilsTest.java
core/common/src/test/java/alluxio/util/ShellUtilsTest.java
core/server/master/src/main/java/alluxio/master/MasterUtils.java
core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTier.java

https://alluxio.atlassian.net/browse/ALLUXIO-2559
This PR adds best-effort checking for the case where the ramfs/tmpfs is smaller than the memory it is configured as. If the size of the ramfs/tmpfs can't be determined, no checking is done.
Example output:
```
[ec2-user@ip-172-31-74-144 alluxio]$ cat logs/worker.out
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: tmpfs is smaller than the configured size: tmpfs size: 512MB, configured size: 3GB
at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:147)
at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:35)
at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:54)
Caused by: java.lang.IllegalStateException: tmpfs is smaller than the configured size: tmpfs size: …
```

[ALLUXIO-2559] Check that ramfs/tmpfs is big enough

---

core/client/runtime/pom.xml

To fix the incompatibility issue when using client jar compiled with hadoop 2.7.3 (default hadoop-2.7 profile), while the hadoop deployment is 2.7.2

[SMALLFIX] Make hadoop-client dependency provided by default for client runtime jar

---

docs/_includes/Common-Commands/stop-alluxio.md
docs/_includes/Configuring-Alluxio-with-NFS/stop-alluxio.md
docs/_includes/Running-Alluxio-Locally/Alluxio-stop.md
docs/_includes/Running-Hadoop-MapReduce-on-Alluxio/start-Alluxio.md
docs/cn/Configuring-Alluxio-with-Azure-Blob-Store.md
docs/cn/Getting-Started.md
docs/en/Configuring-Alluxio-with-Azure-Blob-Store.md
docs/en/Getting-Started.md

`bin/alluxio-start.sh local` should be coupled with `bin/alluxio-stop.sh local` not `bin/alluxio-stop.sh all`

[SMALLFIX] Use the correct command for stopping local cluster in documentation.

---

integration/docker/bin/alluxio-master.sh
integration/docker/bin/alluxio-proxy.sh
integration/docker/bin/alluxio-worker.sh
integration/mesos/bin/alluxio-master-mesos.sh
integration/mesos/bin/alluxio-mesos-start.sh
integration/mesos/bin/alluxio-worker-mesos.sh
integration/yarn/bin/alluxio-application-master.sh
integration/yarn/bin/alluxio-master-yarn.sh
integration/yarn/bin/alluxio-worker-yarn.sh

alluxio-config.sh no longer sets CLASSPATH. Instead, it sets ALLUXIO_SERVER_CLASSPATH and ALLUXIO_CLIENT_CLASSPATH.

[SMALLFIX] Update usages of libexec CLASSPATH

---

integration/mesos/pom.xml

The mesos integration doesn't use these dependencies. We can remove them.

[SMALLFIX] Remove unused mesos dependencies

---

dev/scripts/generate-release-tarballs.sh
dev/scripts/generate-tarball.sh

md5 is not available everywhere, also I tacked on `-bin` on the tarred file name but not the untarred folder to be consistent with how previous distributions were generated.

[SMALLFIX] Update Generate tarball script

---

core/client/fs/src/main/java/alluxio/client/file/policy/LocalFirstPolicy.java

Since LocalFirstPolicy is the default policy, the current implementation will always pick the same worker for multiple threads, i.e. Performance.java

[SMALLFIX] Randomly pick a worker correctly

---

core/client/fs/src/main/java/alluxio/client/block/stream/LocalFilePacketReader.java
core/client/fs/src/main/java/alluxio/client/block/stream/LocalFilePacketWriter.java
core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketReader.java
core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java
core/client/fs/src/main/java/alluxio/client/file/FileSystemUtils.java
core/common/src/main/java/alluxio/AbstractClient.java
core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/main/java/alluxio/security/authentication/NoSaslTransportProvider.java
core/common/src/main/java/alluxio/security/authentication/PlainSaslTransportProvider.java
core/common/src/main/java/alluxio/security/group/CachedGroupMapping.java
core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
core/server/worker/src/main/java/alluxio/Sessions.java
core/server/worker/src/main/java/alluxio/worker/SessionCleaner.java
core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java
core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
core/server/worker/src/main/java/alluxio/worker/file/DefaultFileSystemWorker.java
tests/src/test/java/alluxio/client/FileOutStreamIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2738
allow Configuration.getMs to accept input with different unit
This is the third pull request
I fixed the following 14 property keys.
WORKER_BLOCK_HEARTBEAT_INTERVAL_MS
WORKER_BLOCK_HEARTBEAT_TIMEOUT_MS
WORKER_FILESYSTEM_HEARTBEAT_INTERVAL_MS
WORKER_SESSION_TIMEOUT_MS
WORKER_TIERED_STORE_RESERVER_INTERVAL_MS
WORKER_UFS_BLOCK_OPEN_TIMEOUT_MS
PROXY_STREAM_CACHE_TIMEOUT_MS
USER_FILE_WAITCOMPLETED_POLL_MS
USER_HEARTBEAT_INTERVAL_MS
USER_NETWORK_NETTY_TIMEOUT_MS
USER_NETWORK_NETTY_WRITER_CLOSE_TIMEOUT_MS
USER_RPC_RETRY_MAX_SLEEP_MS
SECURITY_AUTHENTICATION_SOCKET_TIMEOUT_MS
SECURITY_GROUP_MAPPING_CACHE_TIMEOUT_MS

[SMALLFIX] third pull request, change time-related property-key value from getLong, getInt to getMs

---

tests/src/test/java/alluxio/shell/command/FreeCommandTest.java

The test assumed that the wildcard match would discover /foo/foobar1 before
/foo/foobar2. If it matched /foo/foobar2 first, /foo/foobar2 would be freed
before noticing that /foo/foobar1 is pinned.

[SMALLFIX] Fix flaky freeWildcardPinnedFile test

---

docs/_config.yml
docs/_includes/Running-Spark-on-Alluxio/earlier-spark-version-bash.md
docs/_includes/Running-Spark-on-Alluxio/spark-profile-build.md
docs/cn/Running-Spark-on-Alluxio.md
docs/en/Running-Spark-on-Alluxio.md
docs/pt/Running-Spark-on-Alluxio.md

Since we already precompile Spark client and bundle it within the distribution, there is no need to recompile Alluxio with the Spark profile in the instruction.

[DOCFIX] Update Spark docs not to recompile Alluxio

---

core/server/proxy/src/main/java/alluxio/proxy/StreamsRestServiceHandler.java

During stress testing of python clients, I encountered the following error, this PR fixes this.
```
2017-06-15 18:04:47,864 ERROR StreamCache - Failed to close stream: 
java.util.ConcurrentModificationException
at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
at java.util.LinkedList$ListItr.next(LinkedList.java:888)
at alluxio.client.file.FileOutStream.close(FileOutStream.java:143)
at alluxio.StreamCache$1.onRemoval(StreamCache.java:45)
at com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:2016)
at com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3521)
at com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3497)
at com.google.common.cache.LocalCache$Segment.remove(LocalCache.java:316 …
```

[SMALLFIX] Close is already called by removal listener when calling invalidate.

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/StartupConsistencyCheck.java
core/server/master/src/test/java/alluxio/master/file/StartupConsistencyCheckTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2851
The changes to StartupConsistencyCheck.java guarantee that getInconsistentUris() can never return null.
The change to DefaultFileSystemMaster.java fixes a race condition where we start the web server before initializing mStartupConsistencyCheck, causing queries to getStartupConsistencyCheck() to hit NPE

[ALLUXIO-2851] NPE fixes for StartupConsistencyCheck

---

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java
core/client/fs/src/main/java/alluxio/client/block/policy/BlockLocationPolicy.java
core/client/fs/src/main/java/alluxio/client/block/policy/DeterministicHashPolicy.java
core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java
core/client/fs/src/main/java/alluxio/client/file/policy/FileWriteLocationPolicy.java
core/client/fs/src/main/java/alluxio/client/file/policy/LocalFirstAvoidEvictionPolicy.java
core/client/fs/src/main/java/alluxio/client/file/policy/LocalFirstPolicy.java
core/client/fs/src/main/java/alluxio/client/file/policy/MostAvailableFirstPolicy.java
core/client/fs/src/main/java/alluxio/client/file/policy/RoundRobinPolicy.java
core/client/fs/src/main/java/alluxio/client/file/policy/SpecificHostPolicy.java
core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
core/client/fs/src/test/java/alluxio/client/block/policy/DeterministicHashPolicyTest.java
core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java
core/client/fs/src/test/java/alluxio/client/file/policy/LocalFirstAvoidEvictionPolicyTest.java
core/client/fs/src/test/java/alluxio/client/file/policy/LocalFirstPolicyTest.java
core/client/fs/src/test/java/alluxio/client/file/policy/MostAvailableFirstPolicyTest.java
core/client/fs/src/test/java/alluxio/client/file/policy/RoundRobinPolicyTest.java
core/client/fs/src/test/java/alluxio/client/file/policy/SpecificHostPolicyTest.java

GetWorker should not be communicating with any other components so IOExceptions do not make as much sense as `null`. @apc999 will consider null annotation after we decide how to enforce.

[SMALLFIX] Handle null value for Get Worker

---

core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java

Avoid a small time window where REST server requests could be served before the worker is ready

[SMALLFIX] Start web server after initializing worker state

---

tests/src/test/java/alluxio/client/FileSystemIntegrationTest.java

This test fails with a high chance on hadoop profiles without this fix.

[SMALLFIX] Deflake FileSystemIntegrationTest.

---

core/common/src/test/java/alluxio/worker/block/io/LocalFileBlockWriterTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2764
Make class LocalFileBlockWriterTest final to avoid unexpected subclassing.

[ALLUXIO-2764] Make class LocalFileBlockWriterTest final

---

core/common/src/main/java/alluxio/MasterInquireClient.java

Otherwise this can cause the `stopWorkers` call to hang making some tests timeout.

[SMALLFIX] Reset the interrupt flag when MasterInquireClient is interrupted.

---

core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java

This test fails deterministically for hadoop-1

[SMALlFIX] Fix AbstractFileSystemTest for Hadoop-1.

---

core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/main/java/alluxio/retry/ExponentialBackoffRetry.java
docs/_data/table/user-configuration.csv

Lower the max time from 5min to 30sec to make clients more responsive while still waiting a significant amount of time between max-wait periods.
Choose a random sleep time between `n` and `n/2` so that the backoff times increase monotonically.

[SMALLFIX] Alter retry times

---

core/server/common/src/main/java/alluxio/RestUtils.java

With status code, clients for different languages based on the REST API can have more fine-grained exceptions.

[ALLUXIO-2952] Show both status code and error message for error responses from REST calls

---

core/server/master/src/test/java/alluxio/master/file/PermissionCheckTest.java

Previously we were using the default /opt/alluxio/underFSStorage
for the UFS. Some tests would fail if this path actually existed.

[SMALLFIX] Fix UFS usage in PermissionCheckTest

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMasterWorkerServiceHandler.java
shell/src/main/java/alluxio/shell/command/ChownCommand.java
shell/src/test/java/alluxio/shell/command/ChownCommandTest.java
tests/src/test/java/alluxio/hadoop/FileSystemAclIntegrationTest.java
tests/src/test/java/alluxio/shell/AbstractAlluxioShellTest.java
tests/src/test/java/alluxio/shell/command/ChownCommandIntegrationTest.java
tests/src/test/java/alluxio/shell/command/ChownCommandTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2901
1. On the client side, use simple regular expressions to parse user:group or user option string and extract corresponding information. Not fully compatible with UNIX/Linux chown syntax yet
2. On the server side, check whether user belongs to the group. If the check fails, throw a FailedPreconditionException. Note that this check is enforced on non-persistent files as well as persistent UFS files. For this reason, I need to modify the FileSystemAclIntegration test.

[ALLUXIO-2901] Support change owner and group of a file or directory with one chown

---

core/server/master/src/test/java/alluxio/master/file/PermissionCheckTest.java

Avoid manual configuration modification by using `AlluxioTestDirectory` instead of `mTestFolder`

[SMALLFIX] Clean up test configuration usage in PermissionCheckTest

---

core/common/src/main/java/alluxio/PropertyKey.java

https://alluxio.atlassian.net/browse/ALLUXIO-2909
The purpose of this change is to enable more attributes of `PropertyKey` in the future, e.g., source (default, site-properties, system properties and etc), whether runtime determined, deprecated, without losing readability of the code (e.g., keep extending the factory method with more args will be messy)

[ALLUXIO-2909] use Builder Pattern to replace factory method of PropertyKey

---

bin/alluxio-masters.sh
bin/alluxio-workers.sh

https://alluxio.atlassian.net/browse/ALLUXIO-2974
In alluxio-masters.sh and alluxio-workers.sh, we should not use
$ALLUXIO_LOG_DIR since we already have an enviroment variable called
$ALLUXIO_LOGS_DIR that we should always respect.

[ALLUXIO-2974] Replace $ALLUXIO_LOG_DIR with $ALLUXIO_LOGS_DIR.

---

core/common/src/main/java/alluxio/Configuration.java

Since we no longer use the default properties file.

[SMALLFIX] Clean up configuration javadoc

---

underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystemFactory.java
underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystemFactory.java
underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystemFactory.java

https://alluxio.atlassian.net/browse/ALLUXIO-2900
this will fix the problem to use `--option` to mount GCS and OSS and etc

[ALLUXIO-2900][branch-1.5] Check credentials from under ufs conf

---

docs/_data/table/en/worker-configuration.yml

The yaml won't compile with \` and : tokens
Replaced \` with ' and removed : since they weren't really needed anyway

[DOCFIX] Avoid use of : and ` in yaml file

---

conf/log4j.properties
libexec/alluxio-config.sh

The getConf function in alluxio-config.sh relies on the output to
stdout, therefore we do not want any logging message to mess up with
stdout.
@aaudiber @apc999

[SMALLFIX] Use Null Appender for getConf during start.

---

build/checkstyle/alluxio_checks.xml

This requirement is burdensome when implementing 1-method subclasses like `Comparator`. It's also controversial whether or not empty constructors are even a good thing - PMD [has a rule](http://pmd.sourceforge.net/pmd-4.3.0/rules/controversial.html) for checking that empty constructors are *not* used. I think it makes more sense to use empty constructors when we think they make sense (e.g. an external dependency/tool relies on having an empty constructor), and not use them when they don't (e.g. when writing a `Comparator`)

[SMALLFIX] Remove explicit constructor check

---

core/server/common/src/main/java/alluxio/cli/ValidateEnv.java
core/server/common/src/main/java/alluxio/cli/validation/UserLimitValidationTask.java
docs/_includes/Building-Alluxio-Master-Branch/increase-number.md

https://alluxio.atlassian.net/browse/ALLUXIO-2989
https://alluxio.atlassian.net/browse/ALLUXIO-2990
Added extensions for validateEnv command to check user limits for number of open files and number of processes.

[ALLUXIO-2989] [ALLUXIO-2990] Extend the validateEnv command to check max user processes

---

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileOutputStream.java

The filteroutputstream write(byte[], int, int) api is inefficient.

[SMALLFIX] Do not use filteroutputstream.

---

core/server/proxy/src/main/java/alluxio/proxy/s3/S3ErrorCode.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
tests/src/test/java/alluxio/proxy/s3/S3ClientRestApiTest.java
tests/src/test/java/alluxio/rest/TestCase.java

A valid object is either an existing Alluxio file or an empty Alluxio directory.
Also added tests.
How this PR is tested:
Along with the other [PR](https://github.com/Alluxio/alluxio/pull/5927) is merged, the following script works (assuming `/bucket1/key1` is a file exists in Alluxio) :
```import boto
access_key = 'put your access key here!'
secret_key = 'put your secret key here!'
conn = boto.connect_s3(
aws_access_key_id = access_key,
aws_secret_access_key = secret_key,
host = 'localhost',
port = 39999,
path = '/api/v1/s3',
is_secure=False,
calling_format = boto.s3.connection.OrdinaryCallingFormat(),
)
bucket = conn.get_bucket('bucket1')
print bucket
for key in bucket.list():
print …
```

[ALLUXIO-2997] [s3] Implement S3 DELETE object API

---

core/common/src/main/java/alluxio/AbstractClient.java

Reverts the accidental movement of `mAddress = getAddress()` in https://github.com/Alluxio/alluxio/pull/5886/files#diff-d7dc60da6f1005850b481cc5792912c5R167
The address needs to be fetched inside the loop so that we detect primary master changes. Otherwise we keep retrying with a stale master address

[SMALLFIX] Re-query for the address during each connection attempt

---

docs/css/main.css

This fixes the documentation generated by Jekyll.
Before: 
After:

[SMALLFIX] Fix documentation header style

---

docs/_data/table/en/common-configuration.yml
docs/_data/table/en/key-value-configuration.yml
docs/_data/table/en/master-configuration.yml
docs/_data/table/en/security-configuration.yml
docs/_data/table/en/user-configuration.yml
docs/_data/table/en/worker-configuration.yml
docs/_data/table/master-configuration.csv
shell/src/main/java/alluxio/cli/ConfigurationDocGenerator.java
tests/src/test/java/alluxio/cli/ConfigurationDocGeneratorTest.java

We recently added colon marks in yml file which broke the syntax. Put them in quotes fixed it.

[DOCFIX] Fix colon in yml files

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/meta/Inode.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeLockList.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
tests/src/test/java/alluxio/master/file/ConcurrentFileSystemMasterCreateTest.java
tests/src/test/java/alluxio/master/file/ConcurrentFileSystemMasterUtils.java

https://alluxio.atlassian.net/browse/ALLUXIO-3002
The use of downgradeLast in inode.createFile is risky and could lead to race conditions.
The downgrade to read lock in create file was based on the assumption that file node creation is an atomic operation that after the inode is created it would not be modified and therefore it's safe for other threads to read, in order to improve the throughput.
However, such assumption is not necessarily true as in the case that a getFileInfo discovers a file in UFS and creates an inode in Alluxio. The creation consists of two steps: (1) create the inode in the inodetree (2) complete the file with the block IDs generation. If the lock is downgraded, it's possible that a concurrent getFileInfo request of the same file accesses the partial state before …

[ALLUXIO-3002] Remove lock downgrade of the last node in inodetree

---

core/server/proxy/src/main/java/alluxio/proxy/s3/S3ErrorCode.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
tests/src/test/java/alluxio/proxy/s3/S3ClientRestApiTest.java
tests/src/test/java/alluxio/rest/TestCase.java
tests/src/test/java/alluxio/rest/TestCaseOptions.java
tests/src/test/java/alluxio/rest/TestCaseOptionsTest.java

Implements 
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html.
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html.
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html.
Options in GET object are not considered in this PR.
The following Python script works under this implementation.
```python
import boto
conn = boto.connect_s3(
aws_access_key_id = '',
aws_secret_access_key = '',
host = 'localhost',
port = 39999,
path = '/api/v1/s3',
is_secure=False,
calling_format = boto.s3.connection.OrdinaryCallingFormat(),
)
bucketName = 'bucket'
bucket = conn.create_bucket(bucketName)
smallObjectKey = 'small.txt'
smallObjectContent = 'Hello World!'
key = …
```

[ALLUXIO-2997] [s3] Implement HEAD, GET and PUT object in S3 API

---

core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketOptions.java
core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketResult.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3Error.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3ErrorCode.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
tests/src/test/java/alluxio/proxy/s3/S3ClientRestApiTest.java
tests/src/test/java/alluxio/rest/TestCase.java
tests/src/test/java/alluxio/rest/TestCaseOptions.java

This PR
- implements the GET bucket operation: recursively listing all the files and empty-directories as objects
- adds integration tests for the GET bucket
- Add Xml support in `rest/TestCase`
The API is compatible as the AWS S3 doc here: http://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html
How to test:
Assuming `/default_tests_files` is a valid directory pre-existing in Alluxio namespace and there are some dirs and files under it.
```
import boto
access_key = 'put your access key here!'
secret_key = 'put your secret key here!'
conn = boto.connect_s3(
aws_access_key_id = access_key,
aws_secret_access_key = secret_key,
host = 'localhost',
port = 39999,
path = '/api/v1/s3',
is_secure=False, …
```

[ALLUXIO-2997] [s3] Implement S3 GET bucket API

---

core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
tests/src/test/java/alluxio/proxy/s3/S3ClientRestApiTest.java

Follow-up for object PUT/GET/HEAD api.
Addressed major comments in https://github.com/Alluxio/alluxio/pull/5949
- Use `DigestOutputStream`
- Add `Content-Length` in GET/HEAD response.
- Allow `Content-MD5` unspecified.

[ALLUXIO-2997] [s3] Improve S3 object APIs

---

core/common/src/main/java/alluxio/Constants.java
core/common/src/main/java/alluxio/PropertyKey.java
core/server/common/src/main/java/alluxio/RestUtils.java
core/server/proxy/pom.xml
core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketOptions.java
core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketResult.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3Error.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3ErrorCode.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3Exception.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java
pom.xml
tests/src/test/java/alluxio/proxy/s3/S3ClientRestApiTest.java
tests/src/test/java/alluxio/rest/TestCase.java
tests/src/test/java/alluxio/rest/TestCaseOptions.java
tests/src/test/java/alluxio/rest/TestCaseOptionsTest.java

This `s3` feature branch adds northbound S3 API to Alluxio, via Alluxio proxy.
It includes:
- PUT/GET/DELETE bucket which maps to directory in Alluxio
- PUT/GET/HEAD/DELETE object which maps to file/empty-dir in Alluxio
- Integration tests covered for all new ops.
No support yet:
- POST object, Multi-part upload/download are not supported yet.
- Options for ETag, security/ACL, Delimiter/CommonPrefixes are not supported yet.
How to use/test:
Option1: via REST API
```
```
Option2: use a sample S3 client script:
```
import boto
conn = boto.connect_s3(
aws_access_key_id = '',
aws_secret_access_key = '',
host = 'localhost',
port = 39999,
path = '/api/v1/s3',
is_secure=False,
calling_format = boto.s3.connection.OrdinaryCallingFormat(),
)
bucketName = …
```

[MERGE] Merge s3 feature branch to master

---

core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
core/client/fs/src/test/java/alluxio/client/block/stream/TestBlockInStream.java
core/client/fs/src/test/java/alluxio/client/file/FileInStreamTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-2995
This PR addresses the issue that when the file is read from UFS, the client still needs to drive the partial caching but should not create a cache stream, as the worker will perform the caching.

[ALLUXIO-2995] More fixes on partial caching

---

core/common/src/test/java/alluxio/underfs/AbstractUnderFileSystemContractTest.java

We don't expect the InputStream returned to implement Seekable anymore.

[SMALLFIX] Remove seek tests from UFS Contract Test

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

https://alluxio.atlassian.net/browse/ALLUXIO-3014
I tested locally deleting 100k files, and this change brought the time down from around 40 seconds to less than 2 seconds

[ALLUXIO-3014] Fix runtime complexity of recursive delete

---

core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java
core/common/src/main/java/alluxio/Configuration.java
core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
core/common/src/test/java/alluxio/heartbeat/HeartbeatThreadTest.java
core/common/src/test/java/alluxio/util/CommonUtilsTest.java
core/common/src/test/java/alluxio/util/FormatUtilsTest.java
core/common/src/test/java/alluxio/util/io/BufferUtilsTest.java
core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
core/server/common/src/main/java/alluxio/cli/extensions/command/InstallCommand.java
core/server/common/src/main/java/alluxio/cli/extensions/command/UninstallCommand.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/UfsSyncChecker.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockStoreMeta.java
shell/src/main/java/alluxio/cli/fs/FileSystemShellUtils.java
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java

ArrayList uses less space overhead and has better lookup time: O(1) vs O(n)
LinkedList is only better when we need to add or remove items
from somewhere besides the end of the list. This never happens
in our code base in practice. Uses of LinkedList should be viewed
with suspicion since it's easy to create performance bottlenecks through
use of #get(int index) on a long linked list, as was fixed in
https://github.com/Alluxio/alluxio/pull/6004
This PR changes all but one usage of LinkedList to ArrayList.
All usages for the lists were inspected to make sure we weren't
using any features of the list that would make LinkedList more
appropriate than ArrayList.

[SMALLFIX] Prefer ArrayList over LinkedList

---

core/common/src/test/java/alluxio/underfs/AbstractUnderFileSystemContractTest.java

@aaudiber This fixes the failed contract test for the tutorial extension base on local ufs.
@calvinjia

[SMALLFIX] Fix createAtomic ufs contract test

---

core/common/src/main/java/alluxio/Constants.java
core/common/src/main/java/alluxio/PropertyKey.java
core/server/proxy/src/main/java/alluxio/proxy/s3/CompleteMultipartUploadResult.java
core/server/proxy/src/main/java/alluxio/proxy/s3/InitiateMultipartUploadResult.java
core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketResult.java
core/server/proxy/src/main/java/alluxio/proxy/s3/ListPartsResult.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3ErrorCode.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
tests/src/test/java/alluxio/proxy/s3/S3ClientRestApiTest.java
tests/src/test/java/alluxio/rest/TestCase.java

This PR implements
[DONE] [multipart upload initialization](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadInitiate.html)
[DONE] [upload part](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPart.html)
[DONE] [abort upload](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadAbort.html)
[DONE] [complete upload](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html)
[DONE] [list parts](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListParts.html)
The following Python script initiates a multipart upload, uploads the parts, and completes the upload.
```python
import math, os
import boto
from filechunkio import FileChunkIO
c = boto.connect_s3(
aws_access_key_id = '', …
```

[ALLUXIO-2997] [S3] S3 multipart upload

---

core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java

Before we would execute one executor task per block. Now we will perform at most one task per heartbeat. This could be relevant if hundreds of blocks are freed during a single heartbeat.

[SMALLFIX] Reduce thread usage in BlockMasterSync

---

core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
core/client/fs/src/test/java/alluxio/client/file/FileInStreamTest.java

Partial caching should not be enabled when no local worker is available unless the block is from UFS.

[SMALLFIX] No partial caching when no local worker

---

bin/alluxio-start.sh
bin/alluxio-stop.sh
core/common/src/main/java/alluxio/Configuration.java
core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/test/java/alluxio/ConfigurationTest.java
core/common/src/test/java/alluxio/PropertyKeyTest.java
docs/_data/table/common-configuration.csv
docs/_data/table/en/common-configuration.yml
docs/_data/table/en/master-configuration.yml
libexec/alluxio-config.sh
shell/src/main/java/alluxio/cli/ConfigurationDocGenerator.java

@apc999 @aaudiber 
With this PR, Alluxio will ignore the user-specified values for certain properties in the alluxio-site.properties file. Instead user should use system or JVM properties for them.
Could you take a look and give some feedback? Thanks!
I will clean up unused code later if we decide to take the current approach proposed in this PR.

[SMALLFIX] Ignore several site properties set by user

---

core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java

This logging happens every time the client opens a
stream. For random-read workloads especially, this can
cause excessive amounts of info-level logging.

[SMALLFIX] Move stream type logging to debug level

---

core/client/fs/src/main/java/alluxio/client/block/stream/LocalFilePacketReader.java
tests/src/test/java/alluxio/client/FileInStreamIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3017
Limit the end of the local file reader to be the file length, otherwise the reader may read outside the file.

[SMALLFIX] LocalFilePacketReader fix

---

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java
core/client/fs/src/main/java/alluxio/client/block/policy/BlockLocationPolicy.java
tests/src/test/java/alluxio/client/FileInStreamIntegrationTest.java

It's possible that the block location policy cannot find any available worker.

[SMALLFIX] Null check on worker address

---

core/common/src/main/java/alluxio/Constants.java
core/common/src/main/java/alluxio/util/FormatUtils.java
core/common/src/test/java/alluxio/util/FormatUtilsTest.java
shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
tests/src/test/java/alluxio/cli/fs/command/LsCommandIntegrationTest.java

1. instead of "In Memory" and "Not In Memory", show the percentage In Alluxio to be consistent with the webUI
2. add the persistence state to output
3. with "-h" flag, when displaying size in bytes, not use float but directly use integers
4. with "-h" flag, dir size is always the number of child inodes
5. make fields right aligned except the last field of filename
output before:
```bash
-rw-r--r--     binfan         staff          2947.00B       09-19-2017 00:27:44:512  Not In Memory  /README.md
```
output after
```bash
-rw-r--r--     binfan     staff           2947           PERSISTED  09-19-2017 00:27:44:512   0% /README.md
```

[SMALLFIX] [branch-1.6] Improvement over ls command:

---

core/server/master/src/main/java/alluxio/master/file/LostFileDetector.java

Given the lost file detector is only used by lineage module, change it to debug so it won't flush the log.

[SMALLFIX] Downgraded log level to debug when a lost file does not exist

---

core/server/common/src/main/java/alluxio/Registry.java

5 seconds is sometimes too short because we may attempt DNS resolutions while constructing servers. The purpose of the timeout is to prevent hanging forever, so 60 seconds is a reasonable value.

[SMALLFIX] Increase registry wait time

---

core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
core/client/fs/src/test/java/alluxio/client/block/stream/TestBlockInStream.java
core/client/fs/src/test/java/alluxio/client/block/stream/TestPacketReader.java
core/client/fs/src/test/java/alluxio/client/file/FileInStreamTest.java
core/common/src/main/java/alluxio/exception/PreconditionMessage.java

This fix the case when underlying BlockInStream is actually shorter than expected. E.g., the files are out of sync. In this case, this PR improves the client to throw an exception indicating the inconsistency. Otherwise, the client is returning meaningless data.

[SMALLFIX] [branch-1.6] Throw exception when underlying BlockInStream is inconsistent

---

core/common/src/main/java/alluxio/Constants.java
core/server/common/src/main/java/alluxio/Registry.java
core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java

In my testing of release 1.6.0 RC0, the worker always fails to be started due to timeout when creating the worker servers, the error is in logs/worker.out like
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Timed out waiting for server alluxio.worker.block.BlockWorker to be created
at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:148)
at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:35)
at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:54)
Caused by: java.lang.RuntimeException: Timed out waiting for server alluxio.worker.block.BlockWorker to be created
at alluxio.util.CommonUtils.waitFor(CommonUtils.java:264)
at alluxio.Registry.get(Registry.java:83)
at alluxio.Registry.get(Registry.java:69)
at …
```

[SMALLFIX] Increase timeout for waiting for worker factories.

---

core/common/src/main/java/alluxio/AbstractClient.java

This PR fixes the issue that 1.6 start local cluster failure with NOSASL mode.
Without this PR:
```
2017-09-26 19:08:20,336 ERROR ProcessUtils - Uncaught exception while running Alluxio worker, stopping it and exiting.
java.lang.RuntimeException: Failed to get a worker id from block master: org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:202)
at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:75)
at alluxio.Registry.start(Registry.java:128)
at alluxio.worker.AlluxioWorkerProcess.startWorkers(AlluxioWorkerProcess.java:242)
at alluxio.worker.AlluxioWorkerProcess.start(AlluxioWorkerProcess.java:217)
at alluxio.ProcessUtils.run(ProcessUtils.java:31)
at …
```

[SMALLFIX] [branch-1.6] Retry IOException for AbstractClient connect

---

core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
core/client/fs/src/test/java/alluxio/client/file/FileInStreamTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3039
With partial caching on, when a block is not fully read, closing the file in stream will read the rest of the block, even when the block is not necessary to cache, such as when the block is already in local worker, or when the block is read from a remote worker but there is no local worker available.

[ALLUXIO-3039] Unnecessary read when closing a file with partial caching on

---

core/server/common/src/main/java/alluxio/web/UIFileInfo.java
core/server/common/src/main/webapp/browse-body.jsp
core/server/common/src/main/webapp/memory-pagination-header.jsp
core/server/master/src/main/java/alluxio/web/WebInterfaceMemoryServlet.java

We already updated API to return in-Alluxio status instead of in-Memory. The UI label is also updated to In-Alluxio data. This change updated the UI to actually display files in Alluxio as opposed to files only in memory.

[SMALLFIX] Update master UI to show in-Alluxio files

---

underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java

Otherwise, the duplicate warns show every 1.5s.

[SMALLFIX] [branch-1.6] Make a spammy GCS warn to debug level

---

core/common/src/main/java/alluxio/util/io/FileUtils.java
core/server/worker/src/main/java/alluxio/worker/block/meta/StorageDir.java

https://alluxio.atlassian.net/browse/ALLUXIO-3037
Moved log out of the util function.

[ALLUXIO-3037] moved log statement out of util function

---

core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java

This setting will allow core threads to expire so that when we aren't under heavy load, we don't have 64 idle threads.

[SMALLFIX] Allow path absent cache threadpool size to decrease

---

docs/_data/table/cn/user-configuration.yml
docs/_data/table/en/user-configuration.yml

We want the user easier to know if `alluxio.user.file.passive.cache.enabled` option turn on, client which have a local worker can cache the file's blocks when reading from remote workers, this can reduce the remote worker reading, because of the local worker have owned this file's block. But, it have to increase the usage of the Alluxio tiered store.

[DOCFIX] Make passive.cache more concrete and easier to understand.

---

core/common/src/main/java/alluxio/PropertyKey.java

`In PropertyKey.java, update
public static final PropertyKey UNDERFS_HDFS_PREFIXES =
new Builder(Name.UNDERFS_HDFS_PREFIXES)
.setDefaultValue("hdfs://,glusterfs:///,maprfs:///")
.setDescription("Optionally, specify which prefixes should run through the Apache "
+ "Hadoop implementation of UnderFileSystem. The delimiter is any whitespace "
+ "and/or ','.")
to
public static final PropertyKey UNDERFS_HDFS_PREFIXES =
new Builder(Name.UNDERFS_HDFS_PREFIXES)
.setDefaultValue("hdfs://,glusterfs:///,maprfs:///")
.setDescription("Optionally, specify which prefixes should run through the HDFS "
+ "implementation of UnderFileSystem. The delimiter is any whitespace "
+ "and/or ','.")`

[SMALLFIX] In PropertyKey.java, update the value of UNDERFS_HDFS_PREFIXES using given tip

---

core/server/worker/src/test/java/alluxio/network/protocol/databuffer/DataByteBufferTest.java

[SMALLFIX]Use static imports for standard test utilities for DataByteBufferTest.java

[SMALLFIX]Use static imports for standard test utilities for DataByteBufferTest.java

---

core/server/worker/src/test/java/alluxio/network/protocol/databuffer/DataNettyBufferTest.java

Use static imports for standard test utilities for DataNettyBufferTest.java

[SMALLFIX]Use static imports for standard test utilities for DataNettyBufferTest.java

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java,
we have the signature
private FileSystemMasterAuditContext createAuditContext(String command,
AlluxioURI srcPath,
@Nullable  AlluxioURI dstPath, @Nullable  Inode srcInode) throws
AccessControlException {
There are two spaces after each @Nullable annotation, but there should
be only one

[SMALLFIX] Fix formatting after Nullable in DefaultFileSystemMaster #27

---

core/common/src/main/java/alluxio/wire/CommandLineJobInfo.java

Supply the variable name to Preconditions.checkNotNull for CommandLineJobInfo.java

[SMALLFIX]Supply the variable name to Preconditions.checkNotNull for CommandLineJobInfo.java

---

core/server/worker/src/test/java/alluxio/network/protocol/databuffer/DataFileChannelTest.java

Use static imports for standard test utilities in
core/server/worker/src/test/java/alluxio/network/protocol/databuffer/DataFileChannelTest.java

[SMALLFIX] Use static imports for standard test utilities in DataFileChannelTest.java

---

core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java

change the attribute of mBufferNotFullOrFailed to final

[SMALLFIX]In NettyPacketWriter.java,add final attribute to mBufferNotFullOrFailed

---

core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java

Improve core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java as mBufferNotFullOrFailed can be marked as final.
Change
private Condition mBufferNotFullOrFailed = mLock.newCondition();
to
private final Condition mBufferNotFullOrFailed = mLock.newCondition();

[ALLUXIO-6249]change the attribute of mBufferNotFullOrFailed to final

---

core/common/src/test/java/alluxio/security/group/GroupMappingServiceTest.java

Use static imports for standard test utilities in GroupMappingServiceTest.java

[SMALLFIX]Use static imports for standard test utilities in GroupMappingServiceTest.java

---

docs/_data/table/en/operation-command.yml

The description in docs/_data/table/en/operation-command.yml says "Set the TTL (time to live) in milliseconds to a file" change to "Set the TTL (time to live) in milliseconds for a file".

[DOCFIX]Fix description for setTtl command

---

core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java

https://alluxio.atlassian.net/browse/ALLUXIO-6291
Improve core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java as mBufferEmptyOrFailed can be marked as final.
Change
private Condition mBufferEmptyOrFailed = mLock.newCondition();
to
private final Condition mBufferEmptyOrFailed = mLock.newCondition();

[ALLUXIO-6291]  Improve Something

---

docs/_plugins/copy_javadoc_to_docs.rb

This is useful when developing documentation since building javadoc
takes a while.

[SMALLFIX] Allow docs to build without javadoc

---

integration/docker/entrypoint.sh

This fix adds a map to entrypoint.sh where offending environment variables can be listed along with the correct way they should be transformed from environment variable name to configuration property name.
https://alluxio.atlassian.net/browse/ALLUXIO-3042

[ALLUXIO-3042] Fix to Docker's entrypoint.sh for environment variables violating the dash-to-dot rule

---

core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java

replace throw Throwables.propagate() with throw new RuntimeException()

[SMALLFIX]Deprecate Throwables.propagate with RuntimeException in NetworkAddressUtils.java

---

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
core/common/src/main/java/alluxio/master/MasterInquireClient.java
core/common/src/main/java/alluxio/master/SingleMasterInquireClient.java
core/common/src/main/java/alluxio/master/ZkMasterInquireClient.java
core/common/src/test/java/alluxio/ConfigurationTestUtils.java
integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java
minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
tests/src/test/java/alluxio/master/AlluxioMasterRestApiTest.java
tests/src/test/java/alluxio/worker/AlluxioWorkerRestApiTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3045
Default configuration that should be shared between all integration tests is moved to ConfigurationTestUtils. Configuration specific to AbstractLocalMiniCluster is left there.
FileSystemContext is updated to allow callers to inject a MasterInquireClient of their choice. No functionality should be changed.
MasterInquireClient no longer implements `AutoCloseable` because `ZkMasterInquireClients` are cached, so it is usually incorrect to close them.

[ALLUXIO-3045] Refactor to prepare for external process test cluster

---

underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java

Checking the existence of a non-existent file should not generate a warning in the logs.

[SMALLFIX] Reduce log level of common s3a exception

---

core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java

Improve core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java as mPreviousBlockOutStreams can be marked as final.
Change
private List<BlockOutStream> mPreviousBlockOutStreams;
to
private final List<BlockOutStream> mPreviousBlockOutStreams;

[SMALLFIX]Change private List<BlockOutStream> mPreviousBlockOutStreams to private final List<BlockOutStream> mPreviousBlockOutStreams

---

core/client/fs/src/main/java/alluxio/client/file/FileInStream.java

Improve core/client/fs/src/main/java/alluxio/client/file/FileInStream.java as mSeekBuffer can be marked as final.
Change
private byte[] mSeekBuffer;
to
private final byte[] mSeekBuffer;

[SMALLFIX]Change mSeekBuffer to final mSeekBuffer

---

core/server/worker/src/test/java/alluxio/network/protocol/RPCBlockReadResponseTest.java

Use static imports for standard test utilities in
core/server/worker/src/test/java/alluxio/network/protocol/RPCBlockReadResponseTest.java

[SMALLFIX]Use static imports for standard test utilities in RPCBlockReadResponseTest.java

---

core/server/worker/src/test/java/alluxio/network/protocol/RPCFileWriteResponseTest.java

[SMALLFIX]Use static imports for standard test utilities for class RPCFileWriteResponseTest

[SMALLFIX]Use static imports for standard test utilities for class RPCFileWriteResponseTest

---

core/client/fs/src/test/java/alluxio/client/file/options/OutStreamOptionsTest.java

[SMALLFIX]Use static imports for standard test utilities for class OutStreamOptionsTest

[SMALLFIX]Use static imports for standard test utilities for class OutStreamOptionsTest

---

core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java

[SMALLFIX]Use static imports for standard test utilities for class AlluxioBlockStoreTest

[SMALLFIX]Use static imports for standard test utilities for class AlluxioBlockStoreTest

---

core/server/worker/src/test/java/alluxio/worker/netty/AbstractWriteHandlerTest.java

Use static imports for standard test utilities in
core/server/worker/src/test/java/alluxio/worker/netty/AbstractWriteHandlerTest.java

[SMALLFIX] Use static imports for standard test utilities in AbstractWriteHandlerTest.java

---

core/common/src/test/java/alluxio/underfs/options/MkdirsOptionsTest.java

Use static imports for standard test utilities in core/common/src/test/java/alluxio/underfs/options/MkdirsOptionsTest.java

[SMALLFIX] Use static imports for standard test utilities in MkdirsOptionsTest.java

---

tests/src/test/java/alluxio/master/MasterFaultToleranceIntegrationTest.java

Use static imports for standard test utilities in MasterFaultToleranceIntegrationTest.java

[SMALLFIX]Use static imports for standard test utilities in MasterFaultToleranceIntegrationTest.java

---

README.md

Changes the ordering so it is more intuitive for readers (example comes after the paragraph describing it)

[DOCFIX] Clean up readme.

---

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java

Changes the `getObjectStatus` call to throw an IOException if we get anything other than a 404 for S3A. Also removes the unnecessary null check which was mistakenly causing a test to incorrectly pass. Also removes the noisy logging since the 404 errors were expected when an exists call returned false.

[SMALLFIX] S3 Get Fix

---

minicluster/src/main/java/alluxio/multi/process/ExternalProcess.java
minicluster/src/main/java/alluxio/multi/process/Master.java
minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
minicluster/src/main/java/alluxio/multi/process/Worker.java
minicluster/src/test/java/alluxio/multi/process/MultiProcessClusterTest.java
tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java

- Track within the cluster whether the test has succeeded or failed, and decide during `destroy` whether to save state for debugging.
- Use `Map<PropertyKey, String>` consistently
- Pass per-master properties into `Master` and `Worker` from `MultiProcessCluster`. This way, `MultiProcessCluster` is the source of truth for all configuration.
- Fix issue where restarting would append new masters to the masters list instead of replacing. Now we differentiate between create (populate the masters list) and start/stop (operate on specific masters without modifying the list).

[SMALLFIX] MultiProcessCluster improvements

---

core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/test/java/alluxio/ConfigurationTestUtils.java
core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
docs/_data/table/common-configuration.csv
docs/_data/table/en/cluster-management-configuration.yml
docs/_data/table/en/common-configuration.yml
docs/_data/table/en/master-configuration.yml
docs/_data/table/en/user-configuration.yml
docs/_data/table/en/worker-configuration.yml
minicluster/pom.xml
minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
minicluster/src/main/java/alluxio/zookeeper/RestartableTestingServer.java
tests/src/test/java/alluxio/AlluxioOperationThread.java
tests/src/test/java/alluxio/zookeeper/ZookeeperFailureIntegrationTest.java

This test ensures that the Alluxio primary stops serving when it loses access to Zookeeper.
Other changes:
- The master thrift shutdown timeout is made configurable so that the external cluster can shut down quickly. This reduces the test time from ~ 1.1 minutes to 0.4 minutes
- Curator's wrapper around Zookeeper's test cluster doesn't expose the restart method. This PR adds a `RestartableTestingServer` class which extends Curator's test cluster to expose restart functionality needed for the integration test.
- This PR adds an `AlluxioOperationThread` class that may be shared by future integration tests.

[SMALLFIX] Add Zookeeper failure test

---

.gitignore

This PR
* removes the `alluxio` directory which might be unintentionally included into the repo
* ignore `lib` directory which will be generated during compilation and contain different under storage connectors
* ignore everything (intermediate compilation results, generated release tarballs, etc) in `dev/scripts` except for the shell scripts that should be contained in the repo

[SMALLFIX] Update .gitignore

---

core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java

Various small improvement on `NettyPacketWriter`
- Update callbacks for `sendEOF` and `sendCancel` rather than using `CLOSE_ON_FAILURE`, so that if failures happens on sending the packet to channel, the states (e.g., `mDoneOrFailed` will be updated rather than ignored).
- Better handle exceptions: if there are already exceptions seen by this channel, add them to suppressed.
- Improve Exception message

[SMALLFIX] Improve NettyPacketWriter 

---

keyvalue/client/src/main/java/alluxio/client/keyvalue/BaseKeyValueStoreWriter.java

```java
KeyValueSystem kvs = KeyValueSystem.Factory.create();
KeyValueStoreWriter writer = kvs.createStore(new AlluxioURI("alluxio://192.168.1.200:19998/path/my-kvstore"));
```
The above code block want Alluxio master `192.168.1.200:19998` to create a keyValueStoreWriter. If we do nothing more, this program will use the default config, so that it think the master is localhost, but we can use `System.setProperty("alluxio.master.hostname", "192.168.1.200");` to special Alluxio master.
But i think the user gave the host and port mean that he want to special the master address through the uri, so i make this change.

[SMALLFIX] Through URI to special master address.

---

bin/alluxio-fuse.sh
integration/fuse/bin/alluxio-fuse.sh
integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java

This PR changes the fuse command to:
- Mount: ` mount mount_point [alluxio_path]`. Mount an Alluxio path to a given mount point. When `alluxio_path` is not given, default to `/`
- Unmount: `unmount mount_point`. Unmount the fuse from the given mount point
- Status: `stat`. Displays the `pid,mount_point,alluxio_path` of each fuse

[ALLUXIO-3052] Allow multiple fuse mount points per machine

---

integration/pom.xml
pom.xml

- Remove profiles that require JDK 1.8 which is now by default
- Remove unused profiles

[SMALLFIX] Cleanup profiles in POM not used

---

core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
core/common/src/main/java/alluxio/exception/ExceptionMessage.java
core/common/src/main/java/alluxio/exception/PreconditionMessage.java

The internal statistics cache maintains a mapping from scheme to statistics object, if the scheme mismatches, the key of the statistics cache will be wrong, although other functionality is not affected.

[SMALLFIX] Assure correctness of URI scheme.

---

core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java

Change
retryRPC(new RpcCallable<Void>() {
@Override
public Void call() throws TException {
mClient.unmount(alluxioPath.toString(), new UnmountTOptions());
return null;
}
});
to
retryRPC(() -> { 
mClient.unmount(alluxioPath.toString(), new UnmountTOptions());
return null;
});
2nd attempt, done by DZ1733015
The previous attempt is failed because of one extra space.

[SMALLFIX]Java 8 Improvement: replace anonymous type with lambda in alluxio.client.file.RetryHandlingFileSystemMasterClient#unmount

---

underfs/gcs/pom.xml
underfs/hdfs/pom.xml
underfs/local/pom.xml
underfs/oss/pom.xml
underfs/pom.xml
underfs/s3a/pom.xml
underfs/swift/pom.xml
underfs/wasb/pom.xml

Set the convention for shaded jar name:
- In target dir, shaded uber jar will be suffixed with `-jar-with-dependencies.jar`
- In the `${ALLUXIO_HOME}/lib` dir, jars will not be suffixed with `-jar-with-dependencies.jar`

[SMALLFIX] Cleanup the name of lib jars

---

docs/_data/table/en/operation-command.yml

Update
"Prints information regarding master fault tolerance such as leader address, list of master addresses, and the configured Zookeeper address."
to
"Print information regarding master fault tolerance such as leader address, list of master addresses, and configured Zookeeper address."

[SMALLFIX]Update wording for masterInfo command in docs/_data/table/en/operation-command.yml

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

Deprecate Throwables.propagate with RuntimeException in DefaultFileSystemMaster.java

[SMALLFIX]Issue117:Deprecate Throwables.propagate with RuntimeException in DefaultFileSystemMaster.java

---

tests/src/test/java/alluxio/cli/fs/command/UnsetTtlTest.java

tests/src/test/java/alluxio/cli/fs/command/UnsetTtlTest.java

[SMALLFIX] Use static imports for standard test utilities

---

tests/src/test/java/alluxio/cli/ConfigurationDocGeneratorTest.java

[SMALLFIX]Use static imports for standard test utilities for class ConfigurationDocGeneratorTest

[SMALLFIX]Use static imports for standard test utilities for class ConfigurationDocGeneratorTest

---

tests/src/test/java/alluxio/master/block/BlockMasterClientRestApiTest.java

[SMALLFIX]Use static imports for standard test utilities for class BlockMasterClientRestApiTest

[SMALLFIX]Use static imports for standard test utilities for class BlockMasterClientRestApiTest

---

minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java

The global timeout rule applied to each integration test is
inadequate here because when it fails a test, the
test cleanup is skipped, so there is no way to collect
cluster logs for debugging.

[SMALLFIX] Add timeout in journal shutdown tests

---

core/server/worker/src/test/java/alluxio/network/protocol/RPCBlockReadRequestTest.java

core/server/worker/src/test/java/alluxio/network/protocol/RPCBlockReadRequestTest.java

[SMALLFIX] Use static imports for standard test utilities RPCBlockReadRequestTest.java

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
integration/fuse/src/main/java/alluxio/fuse/OpenFileEntry.java
integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java

I have observed that on Mac writing sequentially in the application layer into `FileInputStream` will end up with the multiple writes of the same offset in the Fuse layer. This suggests from unexpected behavior with OSXFUSE (I used 3.7.1).
For example, when I write a file of 10MB sequentially, the `write` method in `AlluxioFuseFileSystem` is invoked to write 64kb at offsets 0, 64KB, 12  ...., 8MB, and then it starts again at 0, 64KB, ...10MB. It's unclear why it writes to 8MB and then starts over from 0 again. However, without this PR, writing 10MB file would end up with a file much larger than 10MB because of the repeat write of the same offsets.
But such issues are not encountered in Linux with libfuse. This might be related to the [issue](https://github.com/osxfuse/osxfuse/issues/244) …

[ALLUXIO-3052] Track write positions to work around issues in OSXFUSE

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java

https://alluxio.atlassian.net/browse/ALLUXIO-3052
Add a `utimens` implementation placeholder to suppress the errors on local file system operations. This method is invoked when the file is accessed and the kernel will try to update the access time, which is not supported by Alluxio.

[ALLUXIO-3052] Add utimens placeholder

---

tests/src/test/java/alluxio/proxy/FileSystemClientRestApiTest.java

Use static imports for standard test utilities for FileSystemClientRestApiTest.java

[SMALLFIX]Use static imports for standard test utilities for FileSystemClientRestApiTest.java

---

core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java

Exception does not allow self-suppression, so when netty packet writer handles the same exception,   it throws runtime exception:
```
java.lang.IllegalArgumentException: Self-suppression not permitted
at java.lang.Throwable.addSuppressed(Throwable.java:1043)
at alluxio.client.block.stream.NettyPacketWriter.updateException(NettyPacketWriter.java:363)
at alluxio.client.block.stream.NettyPacketWriter.access$600(NettyPacketWriter.java:69)
at alluxio.client.block.stream.NettyPacketWriter$WriteListener.operationComplete(NettyPacketWriter.java:459)
at alluxio.client.block.stream.NettyPacketWriter$WriteListener.operationComplete(NettyPacketWriter.java:436)
```

[SMALLFIX] Better exception handling

---

docs/en/Configuring-Alluxio-with-GCS.md

In docs/en/Configuring-Alluxio-with-GCS.md, in "Initial Setup" section, in the last sentence, change "documentations" to "documentation". So, the sentence should be:
If you are new to GCS, please read its documentation.

[SMALLFIX]Improve grammar in docs/en/Configuring-Alluxio-with-GCS.md 

---

docs/_data/table/en/operation-command.yml

Update wording for copyToLocal command in docs/_data/table/en/operation-command.yml 
Update
"Copy the specified file from the path specified by "remote path" to a local destination."
to
"Copy the file specified by "remote path" to a local destination."

[DOCFIX]Update wording for copyToLocal command in docs/_data/table/en/operation-command.yml

---

core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java

A more scalable internal data structure for `MountTable` can be:
```
Trie<String, Long> mMountPathToMountId;
Trie<String, Long> mUfsPathToMountId;
Map<Long, MountInfo> mMountTable;
```
Then finding the mount point prefix is more efficient due to the Trie and `getMountInfo(long id)` is O(1) instead of O(n). 
But I think there will be just a few mount points, so the current implementation is ok.

[SMALLFIX] Reduce string comparison operations in getMountPoint.

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java
core/server/master/src/main/java/alluxio/master/file/meta/NoopUfsAbsentPathCache.java
core/server/master/src/main/java/alluxio/master/file/meta/UfsAbsentPathCache.java
core/server/master/src/test/java/alluxio/master/file/meta/AsyncUfsAbsentPathCacheTest.java

For a path like `/mnt/task/level/file` where `/` is the only mount point,  if `/mnt/task/level` is persisted, but `file` is not persisted, then every time `listStatus` is called, the `AsyncUfsAbsentPathCache#process` will call `ufs.exists` on `/`, `/mnt`, `/mnt/task`, `/mnt/task/level`, and `/mnt/task/level/file`. 
This PR changes this behavior by starting `process` from the first component that is not yet persisted.

[SMALLFIX] Do not process persisted paths during updating absent paths.

---

underfs/gcs/pom.xml
underfs/hdfs/pom.xml
underfs/local/pom.xml
underfs/oss/pom.xml
underfs/pom.xml
underfs/s3a/pom.xml
underfs/swift/pom.xml
underfs/wasb/pom.xml

Remove the error message like the following when starting Alluxio
```
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by
log4j:ERROR [alluxio.extensions.ExtensionsClassLoader@71dac704] whereas object of type
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [sun.misc.Launcher$AppClassLoader@55f96302].
log4j:ERROR Could not instantiate appender named "Console".
log4j:ERROR A "org.apache.log4j.varia.NullAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by
log4j:ERROR [alluxio.extensions.ExtensionsClassLoader@71dac704] whereas object of type
log4j:ERROR …
```

[SMALLFIX] Remove warning message due to logger class loading

---

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java

This PR saves a `getFileInfo` RPC call to HDFS when getting HDFS block locations.

[SMALLFIX] Save one RPC call to HDFS.

---

core/common/src/main/java/alluxio/util/UnderFileSystemUtils.java

Deprecate Throwables.propagate with RuntimeException in UnderFileSystemUtils.java

[SMALLFIX]Deprecate Throwables.propagate in UnderFileSystemUtils.java

---

core/client/runtime/pom.xml
core/common/src/test/java/alluxio/EmbeddedChannels.java
pom.xml

Requires the changes to remove usages of chmv8. Version >= 4.0.50 is required to support shading without needing to specify system properties.

[SMALLFIX] Update Netty minor version

---

integration/docker/entrypoint.sh
integration/kubernetes/README.md
integration/kubernetes/alluxio-master.yaml.template
integration/kubernetes/alluxio-pv-volume.yaml.template

- The template can be used for requesting NFS volumes for journal
- Docker entrypoint has added commands, e.g, for starting master without format

[SMALLFIX][k8s] Add template for persistent volume

---

docs/_data/table/en/operation-command.yml

Update
"Copy the specified file specified by "source path" to the path specified by "remote path". This command will fail if "remote path" already exists."
to
"Copy the file specified by "source path" to the path specified by "remote path". This command will fail if "remote path" already exists.

[DOCFIX]modify the operation-command.yml in docs/_data/table/en/operation-command.yml

---

keyvalue/client/src/main/java/alluxio/client/keyvalue/BaseKeyValueStoreReader.java

Supply the variable name to Preconditions.checkNotNull in BaseKeyValueStoreReader.java

[SMALLFIX] Supply the variable name to Preconditions.checkNotNull in BaseKeyValueStoreReader.java

---

core/server/master/src/main/java/alluxio/master/file/meta/TtlBucket.java

In alluxio/master/file/meta/TtlBucket.java, change the definition and reference of sTtlIntervalMs as it is used as a constant.

[SMALLFIX] Mark alluxio.master.file.meta.TtlBucket#sTtlIntervalMs final

---

core/server/common/src/test/java/alluxio/master/journal/AsyncJournalWriterTest.java

[SMALLFIX]Use static imports for standard test utilities for class AsyncJournalWriterTest

[SMALLFIX]Use static imports for standard test utilities for class AsyncJournalWriterTest

---

core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java

Change
return retryRPC(new RpcCallable<URIStatus>() {
@Override
public URIStatus call() throws TException {
return new URIStatus(ThriftUtils
.fromThrift(mClient.getStatus(path.getPath(), options.toThrift()).getFileInfo()));
}
});
to
return retryRPC(() -> new URIStatus(ThriftUtils
.fromThrift(mClient.getStatus(path.getPath(), options.toThrift()).getFileInfo())));

[SMALLFIX]replace anonymous type with lambda in alluxio.client.file.RetryHandlingFileSystemMasterClient#getStatus

---

integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java

So developers won't see test failures on mac if they do not have osxfuse installed.

[SMALLFIX] Ignore the fuse tests if the libfuse library is missing

---

docs/en/Configuring-Alluxio-with-Azure-Blob-Store.md

In docs/en/Configuring-Alluxio-with-Azure-Blob-Store.md, for the last sentence in the "Configuring Alluxio" section, remove the "try" aspect. So, the sentence should be like:
After these changes, Alluxio should be configured to work with Azure Blob Store as its under storage system, and you can run Alluxio locally with it.

[DOCFIX] remove 'try to'

---

core/common/src/test/java/alluxio/security/authentication/PlainSaslClientCallbackHandlerTest.java

Use static imports for standard test utilities in PlainSaslClientCallbackHandlerTest.java

[SMALLFIX] Use static imports for standard test utilities in PlainSaslClientCallbackHandlerTest.java

---

core/common/src/main/java/alluxio/PropertyKey.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/meta/LazyUfsBlockLocationCache.java
core/server/master/src/main/java/alluxio/master/file/meta/UfsBlockLocationCache.java
core/server/master/src/test/java/alluxio/master/file/meta/LazyUfsBlockLocationCacheTest.java

When listing status of a file, if the file is persisted and has no block cached in Alluxio, and the ufs is not remote, then Alluxio will ask UFS for the block locations of the file so that computation framework can leverage data locality.
This PR caches the ufs locations so that further requests for the ufs locations do not need to send RPCs to UFS again.

[SMALLFIX] Cache ufs block locations.

---

core/client/fs/src/test/java/alluxio/client/block/options/LockBlockOptionsTest.java

[SMALLFIX]Use static imports for standard test utilities for class LockBlockOptionsTest

[SMALLFIX]Use static imports for standard test utilities for class LockBlockOptionsTest

---

core/server/master/src/test/java/alluxio/master/file/async/DefaultAsyncPersistHandlerTest.java

[SMALLFIX]Use static imports for standard test utilities for class DefaultAsyncPersistHandlerTest

[SMALLFIX]Use static imports for standard test utilities for class DefaultAsyncPersistHandlerTest

---

core/server/worker/src/main/java/alluxio/worker/netty/NettyDataServer.java

We block on the thrift server for exiting the worker. Otherwise, we can run into cases where the data server threads prevent the worker from exiting, for example if the data server fails to bind.

[SMALLFIX] Use daemon threads for data server.

---

core/server/worker/src/test/java/alluxio/worker/file/FileWorkerMasterSyncExecutorTest.java

[SMALLFIX] Use static imports for standard test utilities in class FileWorkerMasterSyncExecutorTest

---

docs/_data/table/en/operation-command.yml

[DOCFIX] Update wording for cat command 

---

docs/_data/table/en/operation-command.yml

Update
"Displays info for the specified path both file and directory."
to
"Display info for the specified file or directory."

[SMALLFIX]Update wording for stat command in docs/_data/table/en/operation-command.yml

---

core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
core/server/master/src/test/java/alluxio/master/file/meta/MountTableTest.java

When the path is omitted such as in `hdfs://localhost`, the `getPath` method returns emtpy string, which in turn would fail the `PathUtils.hasPrefix` check with `Path  is invalid` exception.

[SMALLFIX] Fix mount table resolution when the root path is omitted

---

integration/docker/entrypoint.sh

`./bin/alluxio format` tries to ssh to workers and `formatWorker`

[SMALLFIX] Format master in docker should never attempt to ssh to workers

---

tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java

This test has been failing a lot of builds, ignoring it for now until we have a chance to deflake it

[SMALLFIX] Ignore flaky test

---

conf/alluxio-env.sh.template

- `ALLUXIO_HOME` is not really respected
- `ALLUXIO_MASTER_HOSTNAME`, `ALLUXIO_MASTER_ADDRESS`, `ALLUXIO_RAM_FOLDER`, `ALLUXIO_UNDERFS_ADDRESS`, `ALLUXIO_WORKER_MEMORY_SIZE` should be set by their corresponding Alluxio properties

[SMALLFIX] Remove env vars in alluxio-env.sh.template that have corresponding site properties

---

docs/en/Configuring-Alluxio-with-Ceph.md
docs/en/Configuring-Alluxio-with-GCS.md
docs/en/Configuring-Alluxio-with-S3.md
docs/en/Configuring-Alluxio-with-secure-HDFS.md
docs/en/Debugging-Guide.md
docs/en/Remote-Logging.md
docs/en/Running-Alluxio-Fault-Tolerant.md
docs/en/Running-Spark-on-Alluxio.md

To reduce confusion, we recommend to use `alluxio-site.properties` rather than `alluxio-env.sh` to set properties.

[SMALLFIX] Remove reference of alluxio-env.sh as we recommend alluxio-site.properties

---

pom.xml

Max perm size is no longer supported.

[SMALLFIX] Remove deprecated java property.

---

pom.xml

Though in dependency management, we already specify the version of maven-enforcer-plugin to be 1.4, we still see the following warning messages with the wrong maven-enforcer-plugin version (1.0 rather than 1.4). This PR avoids warning message by hardcoding the version.
```
[INFO] ------------------------------------------------------------------------
[INFO] Building Alluxio Parent 1.7.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * …
```

[SMALLFIX] Eliminate maven build warning

---

core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectory.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeFile.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java

We lost the mode after a reset if owner/group was empty. To reproduce: when using s3a, with inherit_acl = false.
```
./bin/alluxio format
./bin/alluxio-start.sh
./bin/alluxio fs ls / # discovered objects have mode 0700
./bin/alluxio chmod 600 /file
./bin/alluxio-start.sh
./bin/alluxio fs ls / # objects have mode 0777 since user and group is empty
```
Case where it matters: Initial load from s3 has empty user/group, chmod, restart (chmod lost), chown (now the original chmod matters) #

[SMALLFIX] Set inode mode if journal entry has mode set

---

core/client/hdfs/src/main/java/alluxio/hadoop/HadoopConfigurationUtils.java
core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
core/common/src/main/java/alluxio/Configuration.java
core/common/src/main/java/alluxio/util/ConfigurationUtils.java
core/common/src/test/java/alluxio/ConfigurationTest.java
core/server/common/src/main/webapp/configuration.jsp
core/server/master/src/main/java/alluxio/web/WebInterfaceConfigurationServlet.java
shell/src/main/java/alluxio/cli/GetConf.java

https://alluxio.atlassian.net/browse/ALLUXIO-3077
- Change in `getConf` CLI, a new `--source` option is added to show the source of a configuration in the following two cases:
```bash
$ bin/alluxio getConf --source
alluxio.conf.dir=/Users/binfan/Dropbox/Work/alluxio/alluxio/conf (SYSTEM_PROPERTY)
alluxio.debug=true (SITE_PROPERTY: /Users/binfan/Dropbox/Work/alluxio/alluxio/conf/alluxio-site.properties)
alluxio.extensions.dir=${alluxio.home}/extensions (DEFAULT)
...
$ bin/alluxio getConf --source alluxio.debug
SITE_PROPERTY: /Users/binfan/Dropbox/Work/alluxio/alluxio/conf/alluxio-site.properties
```
- Change in Configuration tab of WebUI: add a new column to show the source of each configuration property.

[ALLUXIO-3077] Add source of different configuration properties to track

---

core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketReader.java
core/client/fs/src/test/java/alluxio/client/block/stream/NettyPacketReaderTest.java
core/server/worker/src/main/java/alluxio/worker/block/RemoteBlockReader.java

https://alluxio.atlassian.net/browse/ALLUXIO-3069
Some uncleanliness:
* We don't use `InStreamOptions` when doing remote reads and it is not passed to the worker for async caching, so I removed the parameter altogether. This could need to be reverted if for some reason we needed more information from `InStreamOptions` which we could not bundle into the `ReadRequest`
* `RemoteBlockReader` only supports the `transferTo` API and cannot seek/read at arbitrary offsets, that is not necessary for async caching.
* Added a new public constructor to `BlockInStream` because the worker side information is lossy compared to the client side (which reads blocks as part of a file, instead of for the sake of reading a block).
* `WorkerNetAddress` is not a proto object so we only sent the important parts …

[ALLUXIO-3069] Implement RemoteBlockReader for the worker

---

bin/alluxio
core/server/common/src/main/java/alluxio/ProcessUtils.java
core/server/master/src/main/java/alluxio/master/AlluxioMaster.java

@aaudiber Could you take a look? Thanks!
When master process receives SIGTERM, the hook will execute to cleanly
close the resources used by the process, e.g. open files.
Without this feature, master will not close the journal files, nor will
it release the lease (lock) held on the journals. Consequently, if HDFS
restarts afterwards, HDFS will not be able to access the journals.

[SMALLFIX] Allow Alluxio master to shutdown cleanly upon SIGTERM

---

core/common/src/main/java/alluxio/util/io/BufferUtils.java
core/common/src/test/java/alluxio/ConfigurationTestUtils.java
tests/src/test/java/alluxio/client/FileInStreamIntegrationTest.java
tests/src/test/java/alluxio/client/RemoteReadIntegrationTest.java

If we keep it at 64KB, read requests end up reading 64KB * 16 max packets in flight = 1 MB of data. This leads to weird behavior when checking for Alluxio caching, since even reading 1 byte will lead to 1MB being read, which could potentially be the entire block. It does make some tests slower so we will need to make sure to increase the packet size when necessary.

[SMALLFIX] Decrease netty packet size in tests.

---

core/common/src/main/java/alluxio/Configuration.java

We stopped searching the classpath for alluxio-site.properties files in `https://github.com/Alluxio/alluxio/pull/6614`. When the `searchPropertiesFile` method was refactored, we lost the call to `loadPropertiesFromResource`. https://github.com/Alluxio/alluxio/pull/6614/files#diff-5a808cf82f4c0b96b3fe034f313c8b78L103
This PR restores the original behavior

[SMALLFIX] Allow site properties to be loaded from classpath

---

core/common/src/test/java/alluxio/resource/ResourcePoolTest.java

[SMALLFIX]Use static imports for standard test utilities for class ResourcePoolTest

[SMALLFIX]Use static imports for standard test utilities for class ResourcePoolTest

---

core/common/src/test/java/alluxio/security/group/ShellBasedUnixGroupsMappingTest.java

[SMALLFIX]Use static imports for standard test utilities for class ShellBasedUnixGroupsMappingTest

[SMALLFIX]Use static imports for standard test utilities for class ShellBasedUnixGroupsMappingTest

---

core/server/common/src/main/java/alluxio/master/AbstractMaster.java
core/server/common/src/main/java/alluxio/master/MasterContext.java
core/server/master/src/main/java/alluxio/master/block/BlockMasterFactory.java
core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMasterFactory.java
core/server/master/src/main/java/alluxio/master/lineage/DefaultLineageMaster.java
core/server/master/src/main/java/alluxio/master/lineage/LineageMasterFactory.java
core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
core/server/master/src/test/java/alluxio/master/lineage/LineageMasterTest.java
keyvalue/server/src/main/java/alluxio/master/keyvalue/DefaultKeyValueMaster.java
keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMasterFactory.java

This PR moves safe mode manager to MasterContext which can be used by all masters.

[SMALLFIX] Add safe mode manager to file system master

---

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java

Hadoop 1 does not have `isFile` or `isDirectory` so we need to use the deprecated `isDir`.

[SMALLFIX] Hadoop 1 compatibility.

---

docs/cn/Clients-Go.md
docs/cn/Clients-Hadoop.md
docs/cn/Clients-Python.md
docs/cn/Clients-S3.md
docs/cn/Lineage-API.md
docs/cn/Running-Alluxio-On-Docker.md
docs/cn/Running-Alluxio-Yarn-Standalone.md
docs/cn/Running-Hadoop-MapReduce-on-Alluxio.md
docs/cn/Running-Spark-on-Alluxio.md
docs/cn/Tiered-Locality.md
docs/en/Clients-Go.md
docs/en/Clients-Python.md
docs/en/Clients-S3.md
docs/en/Lineage-API.md
docs/en/Running-Alluxio-On-Docker.md
docs/en/Running-Alluxio-Yarn-Standalone.md
docs/en/Running-Hadoop-MapReduce-on-Alluxio.md

1. Add blank after hash key and remove redundant label
2. Add Table of Contents and little fix
3. Fix the python example to markdown style
4. Highlight the commands like the en version
5. ALLUXIO_CLIENT_JAR_PATH_BUILD should be ALLUXIO_CLIENT_JAR_PATH

[DOCFIX] Some doc fixes

---

.gitignore

These directories are for tarball generation.

[SMALLFIX] Add tarball and work directories to gitignore.

---

core/server/common/src/main/java/alluxio/RpcUtils.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java

getStatus is the standard way to check for existence. Before this PR, checking for the existence of a non-existent file would log a warning in the master log. This causes the master log to become unnecessarily full under normal operations. With this change, users will only get RPC tracing for getStatus when they set the log level to debug.

[SMALLFIX] Avoid filling logs with getstatus warnings

---

core/server/common/src/main/java/alluxio/cli/ValidateEnv.java

This change added a new option `-l` to `validateEnv` command for user to list validation tasks to run for a given target and prefix. For example `alluxio validateEnv all -l` will list all tasks available to run for each master node and worker node.

[SMALLFIX] Allow user to list available validation tasks

---

core/server/common/src/main/java/alluxio/cli/validation/RamDiskMountPrivilegeValidationTask.java
core/server/common/src/main/java/alluxio/cli/validation/StorageSpaceValidationTask.java
core/server/common/src/main/java/alluxio/cli/validation/Utils.java

Currently running validateEnv command on linux with mounted ramfs for worker storage will fail because ramfs does not report correct space information. I am adding a check so we skip checking available space for ramfs.

[SMALLFIX] Fix storage space validation for ramfs

---

core/server/common/src/main/java/alluxio/master/SafeModeManager.java
core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
core/server/master/src/main/java/alluxio/master/DefaultSafeModeManager.java
core/server/master/src/test/java/alluxio/master/SafeModeManagerTest.java
core/server/master/src/test/java/alluxio/master/TestSafeModeManager.java

Currently Alluxio master only reenters safe mode when RPC server starts, leaving safe mode off during the period between a server becomes primary and the RPC server starts. This change adds notification to the safe mode manager so the safe mode will be turned on even when master is starting, preventing services from doing worker dependent tasks.

[SMALLFIX] Reenter safe mode after master become primary again

---

underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSOutputStream.java
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AOutputStream.java

Currently for S3 and GCS put request we are setting content type value to content encoding. While it works for S3 and GCS, some compatible storage providers will reject it as bad request.
This is same PR as https://github.com/Alluxio/alluxio/pull/6706 retargeted to branch 1.7 .

[SMALLFIX] Fix invalid content-encoding for object stores.

---

core/server/worker/src/test/java/alluxio/worker/block/UfsInputStreamManagerTest.java

The purpose of test `testConcurrencyWithExpiration` is to ensure the test can finish without deadlock. So we just check one of the input stream can expire and close, but not an exact amount given that the cache eviction is asynchronous.

[SMALLFIX] check at least one in stream is expired and closed

---

core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
core/common/src/main/java/alluxio/underfs/Fingerprint.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
core/server/master/src/main/java/alluxio/master/file/options/DescendantType.java
core/server/master/src/main/java/alluxio/master/file/options/LoadMetadataOptions.java
core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
core/server/master/src/test/java/alluxio/master/file/options/LoadMetadataOptionsTest.java
tests/src/test/java/alluxio/master/file/UfsSyncIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3063

[ALLUXIO-3063] Support recursive ufs sync

---

core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
core/common/src/main/java/alluxio/network/netty/NettyRPC.java
core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java
core/server/worker/src/main/java/alluxio/worker/netty/AsyncCacheHandler.java

Aim to:
- Save one roundtrip when client wants to async cache a block on a worker and isolate the result of this async cache on critical path on client
- Catch and ignore the exceptions on worker on submitting async cache --- it is best effort
- the netty service handler of async cache return no response

[SMALLFIX] Ignore exceptions on submitting async cache request on worker and make client call nonblocking

---

core/server/common/src/main/java/alluxio/master/AbstractMaster.java
core/server/common/src/main/java/alluxio/master/journal/Journal.java
core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
core/server/master/src/main/java/alluxio/master/block/BlockMaster.java
core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java
core/server/master/src/main/java/alluxio/master/block/ContainerIdGenerable.java
core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
core/server/master/src/main/java/alluxio/master/file/async/AsyncPersistHandler.java
core/server/master/src/main/java/alluxio/master/file/async/DefaultAsyncPersistHandler.java
core/server/master/src/main/java/alluxio/master/file/meta/FileSystemMasterView.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryIdGenerator.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/main/java/alluxio/master/lineage/DefaultLineageMaster.java
core/server/master/src/main/java/alluxio/master/lineage/LineageMaster.java
core/server/master/src/main/java/alluxio/master/lineage/LineageMasterClientServiceHandler.java
core/server/master/src/main/java/alluxio/master/lineage/recompute/RecomputeExecutor.java
keyvalue/server/src/main/java/alluxio/master/keyvalue/DefaultKeyValueMaster.java
keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMaster.java
keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMasterClientServiceHandler.java
tests/src/test/java/alluxio/master/journal/ufs/UfsJournalIntegrationTest.java
tests/src/test/java/alluxio/master/journal/ufs/UfsJournalTest.java

This PR fixes an issue where acked metadata changes could be lost if they happen immediately after the journal is closed. This issue was possible but extremely unlikely in previous versions. It only became a real problem after https://github.com/Alluxio/alluxio/pull/6628 merged two weeks ago.
1. RPC begins
2. Journal is closed, usually by the shutdown hook when stopping the Alluxio master, but possibly because the master loses connection to Zookeeper and steps down as primary.
3. RPC creates a journal context. The context is a NoopContext because the journal is closed.
4. RPC completes without writing a journal entry.
5. RPC is successful, but when master restarts the change is forgotten
To fix this, we should throw UnavailableException instead of returning a NoopContext when the journal …

[SMALLFIX] Fix ft failure window

---

docs/en/Running-Alluxio-Fault-Tolerant.md

- Removed S3 as suggested journal location option.
- Removed suggestion for extending heartbeat timeout since we already bump up the default value.

[DOCFIX] Update instructions for running Alluxio in fault tolerant mode

---

tests/src/test/java/alluxio/client/FileInStreamIntegrationTest.java

Positioned read closes the block in stream after reading, which triggers async caching.

[SMALLFIX] Update positioned read test.

---

tests/src/test/java/alluxio/master/journal/ufs/UfsJournalIntegrationTest.java

There's no need to downcast when the only method used is already in the `FileSystemMaster` interface

[SMALLFIX] Clean up test

---

core/client/fs/src/test/java/alluxio/client/block/stream/NettyPacketReaderTest.java

[SMALLFIX]Use static imports for standard test utilities for class NettyPacketReaderTest

[SMALLFIX]Use static imports for standard test utilities for class NettyPacketReaderTest

---

core/client/fs/src/test/java/alluxio/client/block/BlockMasterClientPoolTest.java

[SMALLFIX]Use static imports for standard test utilities for class BlockMasterClientPoolTest

[SMALLFIX]Use static imports for standard test utilities for class BlockMasterClientPoolTest

---

integration/yarn/bin/alluxio-yarn.sh

The lib directory is required to have access to the core UFS implementations.

[SMALLFIX] Fix YARN integration

---

core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java

When uploading image, audio, or video, the "Content-Type" is not necessarily "application/octet-stream".

[SMALLFIX] Support more MIME types when uploading objects in S3 API.

---

docs/en/Running-Alluxio-Fault-Tolerant-on-EC2.md

Per script the valid Type has to be either `hadoop1` or `hadoop2`.

[DOCFIX] Fix Running-Alluxio-Fault-Tolerant-on-EC2.md

---

core/server/worker/src/test/java/alluxio/worker/block/UfsInputStreamManagerTest.java

In case the test runs too slowly.

[SMALLFIX] Increase timeout for UfsInputStreamManagerTest.testConcurrency

---

core/server/common/src/main/java/alluxio/cli/ValidateEnv.java
core/server/common/src/main/java/alluxio/cli/validation/AbstractValidationTask.java
core/server/common/src/main/java/alluxio/cli/validation/HdfsValidationTask.java
core/server/common/src/main/java/alluxio/cli/validation/PortAvailabilityValidationTask.java
core/server/common/src/main/java/alluxio/cli/validation/RamDiskMountPrivilegeValidationTask.java
core/server/common/src/main/java/alluxio/cli/validation/SecureHdfsValidationTask.java
core/server/common/src/main/java/alluxio/cli/validation/SshValidationTask.java
core/server/common/src/main/java/alluxio/cli/validation/StorageSpaceValidationTask.java
core/server/common/src/main/java/alluxio/cli/validation/UfsDirectoryValidationTask.java
core/server/common/src/main/java/alluxio/cli/validation/UserLimitValidationTask.java
core/server/common/src/main/java/alluxio/cli/validation/ValidationTask.java

Some validateEnv tasks report problems that are not fatal. This change adds a new return type for validation tasks to indicate task result to be one of the 4 options: ok, warning, failed and skipped.
Bonus: the task results now have colors!

[SMALLFIX] Add warnings to validateEnv command

---

core/client/fs/src/main/java/alluxio/client/file/FileSystem.java

example output for user log:
```
2018-01-11 16:19:01,229 DEBUG NetworkAddressUtils - address: localhost/127.0.0.1 isLoopbackAddress: true, with host 127.0.0.1 localhost
2018-01-11 16:19:01,247 DEBUG FileSystem$Factory - alluxio.conf.dir=/Users/binfan/Dropbox/Work/alluxio/alluxio/conf (SYSTEM_PROPERTY)
2018-01-11 16:19:01,247 DEBUG FileSystem$Factory - alluxio.debug=true (SITE_PROPERTY: /Users/binfan/Dropbox/Work/alluxio/alluxio/conf/alluxio-site.properties)
2018-01-11 16:19:01,247 DEBUG FileSystem$Factory - alluxio.extensions.dir=${alluxio.home}/extensions (DEFAULT)
2018-01-11 16:19:01,247 DEBUG FileSystem$Factory - alluxio.fuse.cached.paths.max=500 (DEFAULT)
2018-01-11 16:19:01,247 DEBUG FileSystem$Factory - alluxio.fuse.debug.enabled=false (DEFAULT)
```

[SMALLFIX] Add logging message on Client creation to debug-log conf properties and their sources

---

underfs/wasb/pom.xml

As a result, Wasb will consider itself eligible for HDFS mount. Fix this by eliminating the HDFS UFS factory from Wasb UFS jar

[SMALLFIX] Fix The issue where Wasb UFS Jar also contains HDFS UFS factory class.

---

docs/en/Clients-Go.md

Now users can copy/paste the code example and run it
as long as a proxy is running locally.

[DOCFIX] Make Go client example runnable

---

tests/src/test/java/alluxio/client/FileInStreamIntegrationTest.java

Packets in flight and packet size is not sufficient to limit the amount of data transfer. I also increased the packet size for the read tests to speed them up since the data size is larger now.

[SMALLFIX] Update FileInStreamIntegrationTest.

---

integration/docker/Dockerfile

Now that 1.7.0 is our the Dockerfile can be updated to get the latest release.

[DOCFIX] Upgrade docker integration example to 1.7.0

---

underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java

[https://alluxio.atlassian.net/browse/ALLUXIO-2933](https://alluxio.atlassian.net/browse/ALLUXIO-2933)
New Contributor task, modify detail:
In line 109,
replace
// We do not need access credentials in simulation mode
with
// We do not need access credentials in simulation mode.

[ALLUXIO-2933] Improve comment style in SwiftUnderFileSystem

---

shell/src/main/java/alluxio/cli/fs/command/StatCommand.java

For empty files, fs stat now shows
`This file does not contain any blocks.`
instead of
`Containing the following blocks:`

[SMALLFIX] Improve stat command message

---

minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java

Instead of copying the work directory to "."
to tar it up, we now change the tar command's
working directory to the parent of the work
directory. This saves a directory copy and
avoids polluting the java working directory.
It is important to not pollute the java working
directory because if the files there are not
cleaned up, the license check will fail on them.
This has been causing PR build failures in 
https://github.com/Alluxio/alluxio/pull/6795

[SMALLFIX] Create test failure artifact in-place

---

core/common/src/test/java/alluxio/AlluxioTestDirectory.java

Without this, an exception will be thrown if there are files left under the test directory.

[SMALLFIX] Clean up test files as well as directories

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

This PR makes journal replay logging consistent with our practice of using stack traces for errors and toString/getMessage for warnings.

[SMALLFIX] Log improvements

---

core/common/src/main/java/alluxio/Configuration.java

This changes the message from
"%s=%dms is smaller than %s=%dms. Workers might not have enough time to register. Consider either increasing %s or decreasing %s"
to something like
"alluxio.master.worker.connect.wait.time=0ms is smaller than alluxio.user.rpc.retry.max.sleep=500ms. Workers might not have enough time to register. Consider either increasing alluxio.master.worker.connect.wait.time or decreasing alluxio.user.rpc.retry.max.sleep"

[SMALLFIX] Fix log message

---

docs/en/Running-Spark-on-Alluxio.md

I tested the Running spark cluster on Alluxio, but the spark job did not work.
I found the reason is I only place the client jar in Spark master, but do not put them in Spark slaves so that Spark executors cannot find local Alluxio client jar.

[DOCFIX] update docs/en/Running-Spark-on-Alluxio.md

---

minicluster/src/main/java/alluxio/multi/process/Master.java
minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
tests/src/test/java/alluxio/BaseIntegrationTest.java
tests/src/test/java/alluxio/LocalAlluxioClusterResource.java
tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java

This PR uses a RuleChain to enforce an order on rules, allowing us to put a log handling rule at the outermost level and have it capture logs generated by other rules like LocalAlluxioClusterResource.
@calvinjia @apc999 PTAL. If you're on board with the idea, I'll update all integration tests to pass their rules through the `rules()` method

[SMALLFIX] Improve test logging

---

core/server/common/src/main/java/alluxio/master/PrimarySelectorClient.java

https://alluxio.atlassian.net/browse/ALLUXIO-3099
Otherwise the message gets logged at error level when
we stop the server normally with alluxio-stop.sh

[ALLUXIO-3099] Avoid spurious log messages from PrimarySelectorClient

---

core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/main/java/alluxio/util/ThreadUtils.java
core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java

The serving thread is supposed to be responsive to interrupts such that this will never happen, but in case the thread doesn't die after 5 minutes, we should stop the process and log the stack of the serving thread.
The PropertyKey is added with `isHidden=true` since users should never need to see this configuration, but it could be useful for developer debugging purposes, or to avoid the `System.exit` in case it causes issues.

[SMALLFIX] Improve handling for the serving thread hanging

---

underfs/wasb/pom.xml

Remove the warning by avoiding having `META-INF/services/alluxio.underfs.UnderFileSystemFactory` to pollute service loading in Wasb UFS
```
2018-01-17 10:03:55,327 INFO  ExtensionsClassLoader - Created ExtensionsClassLoader with jars=file:/Users/binfan/Dropbox/Work/alluxio/alluxio/lib/alluxio-underfs-wasb-1.7.1-SNAPSHOT.jar
**2018-01-17 10:03:55,349 WARN  UnderFileSystemFactoryRegistry - Failed to load jar /Users/binfan/Dropbox/Work/alluxio/alluxio/lib/alluxio-underfs-wasb-1.7.1-SNAPSHOT.jar: alluxio.underfs.UnderFileSystemFactory: Provider alluxio.underfs.hdfs.HdfsUnderFileSystemFactory not found**
```

[SMALLFIX] Remove HdfsUnderFileSystemFactory from service loading in WASB UFS jar

---

core/server/worker/src/main/java/alluxio/worker/block/BlockStore.java
core/server/worker/src/main/java/alluxio/worker/block/BlockWorker.java
core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
core/server/worker/src/main/java/alluxio/worker/block/evictor/AbstractEvictor.java
core/server/worker/src/main/java/alluxio/worker/block/evictor/Evictor.java
core/server/worker/src/main/java/alluxio/worker/block/evictor/GreedyEvictor.java
core/server/worker/src/main/java/alluxio/worker/block/evictor/LRFUEvictor.java
core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3105
The space reserver is invoked asynchronously every heartbeat to free space in a worker. Currently the eviction policy is all-or-nothing, so if there is not enough space to free for a given amount, for example, when too many files are pinned to make space, then the evictor just fails and throws exception.
In this PR, the space reserver is improved to make space in a best-effort way, and lower the watermark as much as possible

[ALLUXIO-3105] Update evictor to take a best-effort mode to evict blocks

---

core/server/master/src/main/java/alluxio/web/WebInterfaceGeneralServlet.java

Before: when UFS is lost, a tracestack is shown on the webUI
```
HTTP ERROR 500
Problem accessing /home. Reason:
Server Error
Caused by:
java.net.ConnectException: Call From localhost/127.0.0.1 to localhost:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:783)
at …
```

[SMALLFIX] Fix WebUI when UFS is lost

---

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalReader.java

Otherwise we will retry in a tight loop, filling the logs
with the same warning.
The exception will be propagated to the top-level handler, and cause the system to exit

[SMALLFIX] Missing journal log improvement

---

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java

This could happen due to the context being closed (ie. from application code), not catastrophic so we can just log a warning instead of crashing.

[SMALLFIX] Log warning instead of throwing exception on channel close.

---

core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3114
Applications like Impala requires block locations to be non-empty for data load to work. Currently Impala could not read from Alluxio Hadoop client when data is not preloaded:
1. For files in HDFS under file system, Alluxio returns HDFS block location hostnames for `BlockLocation::getNames()`, but Impala requires two part `name:port` format which is indicated in javadoc of the method.
2. For files in non-HDFS or remote HDFS under file system, Alluxio returns no `BlockLocation`, this is making Impala skip reading of the file all together.
This change updated the client to return full two-part locations for UFS locations if there is an Alluxio worker co-located. If no worker is colocated with the UFS block location, it will fallback to …

[ALLUXIO-3114] Better attempt to return block locations for blocks not in Alluxio workers

---

core/server/worker/src/main/java/alluxio/worker/netty/AsyncCacheHandler.java
core/server/worker/src/main/java/alluxio/worker/netty/PipelineHandler.java

`AsyncCacheRequestManager` instance should be shared for different handlers across channels.

[SMALLFIX] Fix async cache manager: shared among different handlers

---

core/server/worker/src/main/java/alluxio/worker/netty/AbstractWriteHandler.java

- Packet writing failure is bad, so it should be error but not warning. And the stacktrace is necessary to show in the log
- To prevent too much logging from the write request validation on misbehaving client, we only validate the write request when the context does not have error.

[SMALLFIX] Improve the error handling of packet writing failure

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/worker/src/main/java/alluxio/worker/block/SpaceReserver.java

Logging messages from `LOG.warn(e.getMessage());` will not be able to locate.

[SMALLFIX] Fix LOG.warn without context

---

docs/en/Running-Presto-with-Alluxio.md

Enable `hive.force-local-scheduling` for data locality

[DOCFIX] Enable data locality for presto

---

core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java

We need to remove the entry from pending requests on failures, or the entry will never be removed (since we only try once).

[SMALLFIX] Remove from pending requests on failures.

---

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java

We usually retry all journal operations in case of temporary journal unavailability, but the journal reads in `catchUp` slipped through the cracks, allowing the master to crash if the journal is unavailable during startup or failover.

[SMALLFIX] Perform retries during catchUp

---

core/common/src/main/java/alluxio/PropertyKey.java

For object stores, close can take a long time with slow connections and/or large files.

[SMALLFIX] Increase netty close timeout

---

core/common/src/main/java/alluxio/util/io/PathUtils.java
core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3127

[ALLUXIO-3127] Creating/loading an Inode does not load ufs metadata for ancestors when recursive is set to true

---

core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java

Fix infinite retries when a directory cannot be created in UFS due to permission issue.

[SMALLFIX] Fix broken sync directory retry

---

core/server/worker/src/main/java/alluxio/worker/block/SpaceReserver.java
core/server/worker/src/test/java/alluxio/worker/block/SpaceReserverTest.java

before this fix, async evict will not trigger when low watermark + high watermark < 100%.
Is this intended? I view watermarks [10%, 80%] a valid pair.

[SMALLFIX] Fix async evictor with small high/low watermarks

---

core/client/fs/src/test/java/alluxio/client/file/FileSystemTestUtils.java
core/server/master/src/main/java/alluxio/master/file/BlockDeletionContext.java
core/server/master/src/main/java/alluxio/master/file/DefaultBlockDeletionContext.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
core/server/master/src/main/java/alluxio/master/file/NoopBlockDeletionContext.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
tests/src/test/java/alluxio/master/file/UfsSyncIntegrationTest.java
tests/src/test/java/alluxio/underfs/FlakyUfsIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3134
This PR introduces a context to track which blocks need to be deleted so that we can use try-with-resources to guarantee that they will be removed, even if an RPC throws an exception.
We now have quite a few context-like objects that must be used in a certain order: BlockDeletionContext, LockedInodePath, JournalContext, and AuditContext. In a followup PR to master, I will merge these contexts into a single context that will ensure that the correct order is used, and save us from passing too many arguments to every RPC handler.

[ALLUXIO-3134] Use context to delete block ids for deleted files

---

core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

- Avoid use `LOG.error(e.getMessage());` --- no way to locate the exception
- on `LOG.error`, avoid using `e.toString()` but `e` directly to have more exception info 
- Fix
```
2018-03-19 10:09:18,126 ERROR DefaultBlockMaster - The worker MasterWorkerInfo{id=5811404141286572521, workerAddress=WorkerNetAddress{host=xxxx, rpcPort=29998, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=gdc-worker03-uspresto.i.nease.net, rack=null)}, capacityBytes=869730877440, usedBytes=5040223851, lastUpdatedTimeMs=1521425057100, blocks=[101300830208, 1210979450880, 1208328650752, 1208261541888, 1214821433344, 1214452334592, 128664469504, 1235625181184, 1233024712704, 185052692480, 193390968832, 203675402240, 205034356736, 207332835328, 217969590272, 218774896640, …
```

[SMALLFIX] Improve error logging in masters

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

Otherwise we can run into unnecessary problems where we can't open/close a journal context due to the journal being closed or unavailable. This also reduces journal locking

[SMALLFIX] Skip empty block delete

---

shell/src/main/java/alluxio/cli/fs/command/HeadCommand.java
shell/src/main/java/alluxio/cli/fs/command/HelpCommand.java
shell/src/main/java/alluxio/cli/fs/command/PersistCommand.java
shell/src/main/java/alluxio/cli/fs/command/RmCommand.java
shell/src/main/java/alluxio/cli/fs/command/SetTtlCommand.java
shell/src/main/java/alluxio/cli/fs/command/TailCommand.java

https://alluxio.atlassian.net/browse/ALLUXIO-3139
- Use `--foo` for long opts of fs shell command consistently
- Clean up wrong opt description
- Clean up command usage description

[ALLUXIO-3139] Fix opts and descriptions of various shell commands

---

core/common/src/main/java/alluxio/underfs/Fingerprint.java
core/common/src/test/java/alluxio/underfs/FingerprintTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3150
Added the notion of Content vs Metadata based tags and some methods to compare fingerprint strictly based on metadata and content.

[ALLUXIO-3150] Enable UfsFingerprint to partition between content-related vs metadata-related info

---

core/server/master/src/test/java/alluxio/master/file/PermissionCheckerTest.java

Use static imports for standard test utilities in alluxio.master.file.PermissionCheckerTest.

[SMALLFIX] Use static imports for standard test utilities in alluxio.master.file.PermissionCheckerTest

---

core/server/worker/src/test/java/alluxio/worker/block/BlockMetadataManagerViewTest.java

Change
import org.mockito.Mockito;
to
import static org.mockito.Mockito;
And put import it before all other non-static import in a separate section.

[SMALLFIX]Use static imports for standard test utilities in alluxio.worker.block.BlockMetadataManagerViewTest 

---

shell/src/main/java/alluxio/cli/fs/command/FreeCommand.java
tests/src/test/java/alluxio/cli/fs/command/FreeCommandIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3155
Instead of making the messages include the asynchronous nature of the command, I thought it would be easier to use if the shell commands were just synchronous.

[ALLUXIO-3155] Make the free command synchronous.

---

core/client/fs/src/test/java/alluxio/client/block/stream/NettyPacketWriterTest.java

#177: Use static imports for standard test utilities in alluxio.client.block.stream.NettyPacketWriterTest and resolve some errors.

[SMALLFIX]Use static imports for standard test utilities

---

core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java

change
return RestUtils.call(new RestUtils.RestCallable<Map<String, Long>>() {
@Override
public Map<String, Long> call() throws Exception {
return getMetricsInternal();
}
});
to
return RestUtils.call(() -> getMetricsInternal());

[SMALLFIX]change RestUtils.call()

---

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
core/common/src/main/java/alluxio/underfs/UfsDirectoryStatus.java
core/common/src/main/java/alluxio/underfs/UfsFileStatus.java
core/common/src/main/java/alluxio/underfs/UfsStatus.java
core/common/src/main/java/alluxio/util/io/PathUtils.java
core/common/src/test/java/alluxio/underfs/AbstractUnderFileSystemContractTest.java
core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java

For getStatus, we always set the `UfsStatus` name to the full path, but never seem to use it anywhere.
For listStatus, we always set the `UfsStatus` name to the basename, and do sometimes use it.
It would be nice if we could be consistent with what type of path we store in `UfsStatus`. Given that we currently rely on listStatus using basenames, I propose using basename consistently.

[SMALLFIX] Consistently use basenames for UfsStatus names

---

core/common/src/main/java/alluxio/PropertyKey.java
docs/_data/table/en/master-configuration.yml

reason to have this PR is to clarify that `alluxio.master.startup.block.integrity.check.enabled` not available in 1.7.0, which users reported confusion.

[SMALLFIX] Clarify alluxio.master.startup.block.integrity.check.enabled

---

core/server/worker/src/main/java/alluxio/worker/block/SpaceReserver.java

Precondition takes only `%s` as the placeholder in the error message template.

[SMALLFIX] Fix placeholder in precondition error message template

---

core/server/master/src/main/java/alluxio/master/DefaultSafeModeManager.java

This addresses a few minor issues in the log messages surrounding startup safe mode
- It isn't clear to users what we mean by safe mode. It's clearer to say what it means, i.e. that we're waiting to give workers a chance to register.
- Because we exit safe mode lazily, we might log "Expect leaving safe mode after 5000ms", but then wait much more than 5000ms before logging "Exiting safe mode".

[SMALLFIX] Update safe mode logging

---

core/common/src/main/java/alluxio/underfs/Fingerprint.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/meta/UfsSyncUtils.java
tests/src/test/java/alluxio/master/file/UfsSyncIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3159
If non-content related attributes have changed in the UFS file, the corresponding Alluxio file should just be updated with that info, and not be deleted if not necessary.

[ALLUXIO-3159] Sync plan change so that only content change causes delete and reload

---

bin/alluxio
shell/src/main/java/alluxio/cli/GetConf.java

https://alluxio.atlassian.net/browse/ALLUXIO-3163
-Xmx=8g was ending up after the classname when
calling the JVM. This made it an argument to the
CLI instead of a JVM arg.

[ALLUXIO-3163] Pass -X args to the JVM instead of the shell

---

core/server/master/src/main/java/alluxio/master/file/DefaultInodePermissionChecker.java
core/server/master/src/main/java/alluxio/master/file/InodePermissionChecker.java
core/server/master/src/main/java/alluxio/master/file/PermissionChecker.java
core/server/master/src/test/java/alluxio/master/file/PermissionCheckerTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3162
The default permission checking logic is not POSIX standard. There should be no "fall through" in standard POSIX permission checking.
For example, if a file has permission `r-xrwx---`, and the owning user belongs to the owning group, then the owning user should have no WRITE permission. But in current codebase, since the owning user belongs to the owning group, and the owning group has WRITE permission, the owning user is finally granted the WRITE permission. This is WRONG.

[ALLUXIO-3162] Fix default inode permission checking logic.

---

tests/src/test/java/alluxio/hadoop/FileSystemAclIntegrationTest.java

In the test gcsGetPermission, rename the file /objectFileA to /gcsGetPermissionFile

[SMALLFIX]Improve Naming for FileSystemAclIntegrationTest #10

---

core/common/src/main/java/alluxio/security/authorization/AccessControlList.java
core/common/src/main/java/alluxio/security/authorization/AclAction.java
core/common/src/main/java/alluxio/security/authorization/AclActions.java
core/common/src/main/java/alluxio/security/authorization/AclEntry.java
core/common/src/main/java/alluxio/security/authorization/AclEntryParser.java
core/common/src/main/java/alluxio/security/authorization/AclEntryType.java
core/common/src/main/java/alluxio/security/authorization/Mode.java
core/common/src/test/java/alluxio/security/authorization/AccessControlListTest.java
core/common/src/test/java/alluxio/security/authorization/AclActionsTest.java
core/common/src/test/java/alluxio/security/authorization/ModeBitsTest.java
core/protobuf/src/main/java/alluxio/proto/journal/File.java
core/protobuf/src/proto/journal/file.proto
core/server/master/src/main/java/alluxio/master/file/meta/Inode.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectory.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeFile.java

This PR:
1. adds data structures to represent access control list
2. replaces owner, group, and mode in Inode with AccessControlList
3. updates journal entries for InodeFile and InodeDirectory to include AccessControlList
4. adds unit tests to test the newly added data structures

[ALLUXIO-3164] Add ACL data structures to Inode

---

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
core/common/src/main/java/alluxio/underfs/UfsDirectoryStatus.java
core/common/src/main/java/alluxio/underfs/UfsFileStatus.java
core/common/src/main/java/alluxio/underfs/UfsStatus.java
core/common/src/main/java/alluxio/util/io/PathUtils.java
core/common/src/test/java/alluxio/underfs/AbstractUnderFileSystemContractTest.java
core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java

This reverts commit c8de9a7de11aaea4d66c0faa1287a3212bae2df7.
This is necessary because recursive listStatus requires that status
names be relative to the listed path, and for nested directories
this means the names can't always be base names.

[SMALLFIX] Revert basename change

---

tests/src/test/java/alluxio/testutils/BaseIntegrationTest.java

Otherwise it is possible that the log file is not created and we will fail when trying to get the `FileWriter`.

[SMALLFIX] Add logger to base integration test to avoid edge case.

---

logserver/src/main/java/alluxio/logserver/AlluxioLogServerProcess.java

Otherwise if closing one socket fails, we will exit with exit code `-1` instead without gracefully closing other sockets. With this change, we will try to close all sockets, and only log warning messages if some of the closes fail.

[SMALLFIX] Catch IOException on socket close

---

core/client/fs/src/test/java/alluxio/client/lineage/LineageFileOutStreamTest.java

Use static imports for standard test utilities in alluxio.client.lineage.LineageFileOutStreamTest #169

[SMALLFIX]#169: use static imports for standard test utilities in LineageFileOutputStreamTest

---

tests/src/test/java/alluxio/client/hadoop/FileSystemAclIntegrationTest.java

In the test swiftGetPermission, rename the file /objectfileA to /swiftGetPermissionFile

[SMALLFIX]Improve Naming for FileSystemAclIntegrationTest 

---

core/common/src/main/java/alluxio/wire/TieredIdentity.java

add "@Nullable" before the function
“public static TieredIdentity fromThrift(alluxio.thrift.TieredIdentity tieredIdentity)”

[SMALLFIX] Add nullable annotation for function fromThrift

---

core/client/hdfs/src/test/java/alluxio/hadoop/HadoopConfigurationUtilsTest.java
core/common/src/main/java/alluxio/Configuration.java
core/common/src/test/java/alluxio/ConfigurationTest.java
core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
core/server/master/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
shell/src/main/java/alluxio/cli/fsadmin/report/ConfigurationCommand.java
shell/src/test/java/alluxio/cli/fsadmin/command/ConfigurationCommandTest.java
tests/src/test/java/alluxio/client/cli/fsadmin/command/ReportCommandIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3168
- Web UI and CLI can only get a small set of configurations from Alluxio leader master in 1.8.0-SNAPSHOT.
- Web UI should be able to show all alluxio-related configurations and fsadmin report configuration should be able to show all configurations.
- In the ```Configuration.java```, we use a ```ConcurrentHashMap<String, String> PROPERTIES``` to record property keys and values.
- We have a merge function to merge ```defaultProperties/systemProperties/siteProperties``` to our ```PROPERTIES``` map.
- However, ```PROPERTIES``` map actually do not need to store default property key value pairs, so someone delete the codes to merge ```defaultProperties``` to ```PROPERTIES``` map. The ```Configuration.get(PropertyKey key)``` can use …

[ALLUXIO-3168] Web UI and CLI master configuration broken

---

core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/main/java/alluxio/security/authentication/NoSaslTransportProvider.java

it does not help as we are not using non-blocking server.
this will hopefully get rid of errors like "Frame size (67108864) larger than max length (16777216)" when `NO_SASL` security is on

[SMALLFIX] Removing the use of TFramedTransport

---

core/common/src/main/java/alluxio/PropertyKey.java

This is a port of the fix #7238 to branch-1.7

[SMALLFIX] Set default mesos JDK url to local (branch-1.7)

---

core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

Only show the first 100 invalid blocks in logs

[SMALLFIX] Avoid spamming logs when there are a lot of orphan blocks

---

pom.xml

https://alluxio.atlassian.net/browse/ALLUXIO-3203
Usage: `mvn compile -PgenerateDocs`
Note that this adds about 40 seconds to build on my local machine and requires jekyll to be installed as `jekyll`

[ALLUXIO-3203] Add profile for building docs.

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/DefaultPermissionChecker.java
core/server/master/src/main/java/alluxio/master/file/PermissionChecker.java
core/server/master/src/test/java/alluxio/master/file/PermissionCheckTest.java
core/server/master/src/test/java/alluxio/master/file/PermissionCheckerTest.java

This change extracts interface from the default permission checker to make it extendable.

[SMALLFIX] make permission checker extendable

---

tests/src/test/java/alluxio/client/hadoop/FileSystemAclIntegrationTest.java

Improve Naming in FileSystemAclIntegrationTest,in the test s3GetPermission, rename the file /objectFileA to /s3GetPermissionFile.

 [SMALLFIX]Improve Naming in FileSystemAclIntegrationTest

---

core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java

Sometimes the exception type is vital to understanding
the meaning of the exception, e.g. NPE

[SMALLFIX] Improve error message

---

core/common/src/main/java/alluxio/extensions/ExtensionFactory.java
core/common/src/main/java/alluxio/extensions/ExtensionFactoryRegistry.java
core/common/src/main/java/alluxio/underfs/UnderFileSystemFactory.java
core/common/src/main/java/alluxio/underfs/UnderFileSystemFactoryRegistry.java

Extract extension loading logic from UnderFileSystemFactoryRegistry and put it in a reusable generic class.

[SMALLFIX] generalize extension factory registry

---

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
core/client/fs/src/main/java/alluxio/client/metrics/MetricsMasterClient.java
core/common/src/main/java/alluxio/AbstractClient.java
core/common/src/main/java/alluxio/AbstractMasterClient.java
core/common/src/main/java/alluxio/heartbeat/HeartbeatThread.java
core/common/src/main/java/alluxio/retry/CountingRetry.java

https://alluxio.atlassian.net/browse/ALLUXIO-3210
Issues with testing w/ Metrics Heartbeat
* When initially starting up, port is 0, there is no point to try and heartbeat (fixed)
* Retrying metrics is not good because the heartbeat automatically does so, also it makes the shutdown hook hang if the master is not available (fixed)
* When stopping the LocalAlluxioCluster, we actually reset the client instead of stopping it, this leads to a heartbeat failure on each test because we stop the master (not fixed)

[ALLUXIO-3211] Make metrics heartbeat retry-less on individual heartbeats.

---

tests/src/test/java/alluxio/server/ft/journal/JournalShutdownIntegrationTest.java

Since it times out after 2 hours

[SMALLFIX] ignore JournalShutdownIntegerationTest for now

---

core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
core/common/src/main/java/alluxio/resource/ResourcePool.java
core/common/src/test/java/alluxio/resource/DynamicResourcePoolTest.java
core/common/src/test/java/alluxio/resource/ResourcePoolTest.java

Some comparisons with timestamp values are not safe. This comparisons can trigger errors that were found in some other projects, e.g. apache kafka with the issue id KAFKA-4290.
I changed those comparisons according to what the Java documentation recommends to help preventing such errors.

[SMALLFIX] Timestamps comparison can overflow

---

core/server/common/src/main/webapp/general.jsp

Nice to show fixed-size summary info before potentially lengthy warnings sections

[SMALLFIX] Show storage usage summary before warnings in web UI

---

build/checkstyle/alluxio_checks.xml
core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
core/client/hdfs/src/main/java/alluxio/hadoop/HadoopConfigurationUtils.java
core/client/hdfs/src/test/java/alluxio/hadoop/HadoopConfigurationUtilsTest.java
core/common/src/main/java/alluxio/AlluxioConfiguration.java
core/common/src/main/java/alluxio/Configuration.java
core/common/src/main/java/alluxio/InstancedConfiguration.java
core/common/src/main/java/alluxio/conf/AlluxioProperties.java
core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
core/common/src/main/java/alluxio/conf/Source.java
core/common/src/main/java/alluxio/master/MasterInquireClient.java
core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
core/common/src/test/java/alluxio/ConfigurationTest.java
core/common/src/test/java/alluxio/conf/AlluxioPropertiesTest.java
core/common/src/test/java/alluxio/conf/SourceTest.java
core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
integration/mesos/src/main/java/alluxio/mesos/AlluxioScheduler.java
shell/src/main/java/alluxio/cli/GetConf.java

https://alluxio.atlassian.net/browse/ALLUXIO-3216
This moves most functionality of `Configuration` to `InstancedConfiguration`, then has `Configuration` delegate to an internal instance of `InstancedConfiguration`. The only logic left in `Configuration` is the logic for setting/clearing values, and the logic for initializing itself in `reset`.
`Configuration.global()` returns an instance object that acts the same as `Configuration`.
The methods needed by `AbstractFileSystem` were updated to accept both instanced and non-instanced configuration. In the long term they will probably take only instanced configuration, but in the short and medium terms we can make incremental progress by keeping both versions.
The only functionality change in the move from `Configuration` to …

[ALLUXIO-3216] Instanced config

---

core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
core/common/src/test/java/alluxio/ConfigurationTest.java

Adding null check back to keep the non-nullable contract of configuration getter.

[SMALLFIX] add null check to configuration value getter

---

core/common/src/main/java/alluxio/conf/AlluxioProperties.java
core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
core/common/src/test/java/alluxio/conf/AlluxioPropertiesTest.java

to keep the method name consistent with `Configuration` interface

[SMALLFIX] Rename hasValueSet to isSet in AlluxioProperties.java

---

core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
core/server/master/src/main/java/alluxio/master/meta/checkconf/ServerConfigurationChecker.java

This PR addresses https://alluxio.atlassian.net/browse/ALLUXIO-3221 and includes a few more small fixes around the configuration checker.
The root cause for the deadlock was
```java
mMasterStore.registerChangeListener(this::regenerateReport);
mWorkerStore.registerChangeListener(this::regenerateReport);
```
`regenerateReport` makes calls into `mMasterStore`, and `mWorkerStore`, but `mWorkerStore` and `mMasterStore` both call `regenerateReport` synchronously while holding `ConfigurationStore`-level locks. This leads to an issue where `mMasterStore` and `mWorkerStore` each try to grab a lock on the other.

[SMALLFIX] Config checker improvements

---

core/server/master/src/main/java/alluxio/master/meta/MetaMasterMasterServiceHandler.java

Simple bug, causes 
2018-06-15 13:20:36,902 WARN  alluxio.AbstractClient (AbstractClient.java:connect) - Failed to connect (1) with MetaMasterMaster @ 192.168.1.34/192.168.1.34:53018: MetaMasterMaster client version 1 is not compatible with server version 2
in the logs

[SMALLFIX] Fix meta master master service version

---

tests/src/test/java/alluxio/testutils/BaseIntegrationTest.java

Otherwise we end up with unnecessary test log files for every skipped test

[SMALLFIX] Skipped log file cleanup

---

core/common/src/main/java/alluxio/AbstractClient.java
core/server/master/src/main/java/alluxio/master/meta/checkconf/ServerConfigurationChecker.java

Test setup: Set a master-only property on master1 but not on master2
Expected: Configuration checker reports the inconsistency
Actual:
1. Secondary master gets ID from primary master, triggering handshake
2. Handshake sends the primary master's version of the property to secondary master, and overrides the secondary master's configuration
3. Secondary master reports its configuration, but it's actually reporting the configuration that the primary master sent it
4. The test fails.
There's actually a 50% chance that the test passes because the handshake doesn't propagate unset values, so if the master which left the property unset becomes primary, the handshake won't break the test.

[SMALLFIX] Fix unset test

---

minicluster/src/main/java/alluxio/master/TestUtils.java
tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterCreateTest.java

When the testing system is under a high load, some tests
start failing due to overly strict time requirements.

[SMALLFIX] Relax time requirements to prevent flakiness under stress

---

bin/alluxio

https://alluxio.atlassian.net/browse/ALLUXIO-3229
It formats all masters, so formatMasters seems
like a better name.
Also includes a smallfix to pass -agentlib to the jvm instead of shell commands like format. Otherwise running format with the -agentlib java arg will fail because it thinks -agentlib is an argument to format

[ALLUXIO-3229] Rename formatMaster to formatMasters

---

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
integration/checker/pom.xml

Checker couldn't build with the hadoop-1 profile because its `hadoop-yarn-client` dependency does not exist until hadoop 2.
Now we can build in these ways:
`mvn install` - build alluxio and checker with the default hadoop version (2.2.0)
`mvn install -Phadoop-2.7` - build alluxio and checker with hadoop 2.7
`mvn install -Phadoop-1 -Dchecker.hadoop.version=2.2.0` - build alluxio with hadoop 1.0.4, build the checker with hadoop 2.2.0

[SMALLFIX] Fix build for hadoop 1

---

dev/scripts/src/alluxio.org/build-distribution/cmd/common.go
dev/scripts/src/alluxio.org/build-distribution/cmd/generate-release-tarballs.go
dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go

We traditionally distribute a tarball named `alluxio-${VERSION}-bin.tar.gz` which is built with the default hadoop version, and untars to a directory named `alluxio-${VERSION}`. This PR adds support for generating this tarball automatically by specifying the "default" hadoop-distribution

[SMALLFIX] Add support for generating default tarballs

---

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go

Some docs expect it to exist, and it's good to distribute the license anyway

[SMALLFIX] Include license in tarball

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

before this change, listStatusInternal was locking from the root to the child node, now we lock from the parent node to the child node.

[SMALLFIX] more efficient locking for listStatus

---

core/common/src/main/java/alluxio/network/thrift/SocketTrackingTServerSocket.java

Fixes this happening when the superclass fails to bind the socket and tries to call `close()` before finishing the constructor.
```
java.lang.RuntimeException: java.lang.NullPointerException
at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:172)
at alluxio.master.MasterProcess$Factory.create(MasterProcess.java:45)
at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:45)
at alluxio.multi.process.LimitedLifeMasterProcess.main(LimitedLifeMasterProcess.java:26)
Caused by: java.lang.NullPointerException
at alluxio.network.thrift.SocketTrackingTServerSocket.closeClientSockets(SocketTrackingTServerSocket.java:98)
at alluxio.network.thrift.SocketTrackingTServerSocket.close(SocketTrackingTServerSocket.java:68)
at org.apache.thrift.transport.TServerSocket.<init>(TServerSocke …
```

[SMALLFIX] Fix NPE

---

docs/en/Running-Alluxio-On-Docker.md

Master address is required by config sync checker even in non-HA mode

[DOCFIX] Update docker doc now that master address is required

---

docs/en/Clients-Go.md

Needs to be uppercase since our organization name is uppercase.
@Xenorith fysa

[DOCFIX] Fix case for Alluxio/alluxio-go import

---

docs/en/Configuring-Alluxio-with-NFS.md

It looks strange to say ```properties``` should be added to ```conf/alluxio-site.properties``` file for me. People that are not familiar with Alluxio or not have much coding experience before may think the word ```properties``` should be directly added to conf files.
The fix is to make the docs easier to follow.

[DOCFIX] improve NFS docs

---

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java

In object stores, successful return from `createFile()` doesn't imply that `exists()` will return true, so we need to remove this precondition check.
Tested locally, before this change master can't start up with journal pointed to an S3 folder. After the change runTests passes.

[SMALLFIX] Fix using object storage for UFS journal

---

tests/src/test/java/alluxio/server/tieredstore/TieredStoreIntegrationTest.java

If the file size is too large, there is a chance the async evictor will kick it out before we read it.

[SMALLFIX] Deflake TieredStoreIntegration Test

---

docs/en/Running-Alluxio-Fault-Tolerant-on-EC2.md

Fix Vagrant installation instruction regarding getting the deployment script.

[DOCFIX] Update EC2 HA doc

---

core/common/src/main/java/alluxio/extensions/ExtensionFactoryRegistry.java

Mostly style changes, the only functional change is changing from
```java
LOG.debug("factory implementation {} is eligible for path {}", factory.getClass(), path);
```
to
```java
LOG.debug("Factory implementation {} is eligible for path {}", factory, path)
```
This is because `factory` shows the specific reference for the ufs factory (e.g. `alluxio.underfs.hdfs.HdfsUnderFileSystemFactory@4dfcb41e`) instead of just the class name (`alluxio.underfs.hdfs.HdfsUnderFileSystemFactory`)
This helps with identifying which specific jar was used to instantiate a UFS

[SMALLFIX] Improve extension factory logging

---

core/common/src/main/java/alluxio/Configuration.java
core/common/src/main/java/alluxio/conf/Source.java
core/common/src/main/java/alluxio/util/ConfigurationUtils.java
core/common/src/test/java/alluxio/ConfigurationTest.java

Otherwise the site properties source will show up as `null` when it's loaded from the classpath

[SMALLFIX] Track source for alluxio-site.properties loaded from classpath

---

core/server/common/src/main/java/alluxio/master/AbstractMaster.java
core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java

- Replace individual members in `AbstractMaster` in favor of storing and using `MasterContext` directly.
- Add getPrimaryIndex in MultiProcessCluster for determining primary master.

[SMALLFIX] make a couple things more reusable

---

core/common/src/main/java/alluxio/Configuration.java
core/common/src/main/java/alluxio/util/ConfigurationUtils.java
core/common/src/test/java/alluxio/ConfigurationTest.java

The NPE is triggered if no alluxio-site.properties file can be found anywhere

[SMALLFIX] Check for null when searching classpath for alluxio-site.properties

---

core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java
core/server/master/src/test/java/alluxio/master/metrics/MetricsMasterTest.java

Calling `MultiValueMetricsUpdate` incurs some costs, such as querying ufs for available space. Also, this gets call on each heartbeat which can be very frequent. Instead, do this on a best effort basis periodically.

[SMALLFIX] Use a heartbeat thread to update metrics.

---

core/common/src/main/java/alluxio/metrics/Metric.java
core/common/src/main/java/alluxio/metrics/MetricsSystem.java
core/common/src/main/java/alluxio/security/authentication/AuthenticatedClientUser.java
core/server/common/src/main/java/alluxio/RpcUtils.java

Since metrics will often be reported multiple times, we reduce the overhead of string construction by caching the metric names.
Also change the user name call to be much more lightweight as accessing the configuration is relatively expensive.

[SMALLFIX] Optimize metric name construction

---

core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/main/java/alluxio/util/ConfigurationUtils.java
core/server/master/src/main/java/alluxio/master/meta/checkconf/ServerConfigurationStore.java
core/server/master/src/test/java/alluxio/master/meta/checkconf/ServerConfigurationStoreTest.java

Previously, sending an unknown property to master
would cause an exception which prevents the worker
from joining. Now, the worker will filter out
invalid properties before sending its configuration
to master, and the master will also tolerate unknown
properties for the purpose of configuration checking.

[SMALLFIX] Fix exception when sending unknown conf to master

---

shell/src/main/java/alluxio/cli/fsadmin/report/MetricsCommand.java
shell/src/test/java/alluxio/cli/fsadmin/report/MetricsCommandTest.java
tests/src/test/java/alluxio/client/cli/fsadmin/command/MetricsCommandIntegrationTest.java

The issue occurs because the metrics name has changed from "master.FilesPinned" to "Master.FilesPinned". Remove this case sensitive info from "Alluxio logical operations:" to "other metrics information: Master.FilesPinned  (0)" .
In the future, we can see how to improve the report metrics to make it sync with the web UI.

[SMALLFIX] fix report metrics null issue

---

docs/en/Running-Alluxio-on-EC2.md

We updated all the other vagrant docs to recommend cloning instead of download, this is the last one

[DOCFIX] Update doc for cloning Alluxio to get deploy module

---

core/client/fs/src/main/java/alluxio/client/metrics/MetricsMasterClient.java
core/common/src/main/java/alluxio/AbstractClient.java
core/common/src/main/java/alluxio/Configuration.java
core/common/src/main/java/alluxio/retry/RetryUtils.java
core/common/src/main/java/alluxio/util/CommonUtils.java
core/server/worker/src/main/java/alluxio/worker/AlluxioWorker.java
core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java

- Move `loadClusterDefault` to `Configuration`.
- Refactor a bunch of retry policies.

[SMALLFIX] Enforce loading cluster-default conf on worker process starting up

---

tests/src/test/java/alluxio/server/ft/ZookeeperFailureIntegrationTest.java

This prevents the logs from getting spammed by NPEs when we shut down the cluster without stopping the operation thread.

[SMALLFIX] Test improvement in zk failure test

---

tests/src/test/java/alluxio/client/fs/ConcurrentDeleteIntegrationTest.java
tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterSetTtlTest.java
tests/src/test/java/alluxio/client/fs/ConcurrentRenameIntegrationTest.java

This helps to prevent flaky failures.
The bounds are still tight enough that if the
operations are executed sequentially instead
of concurrently, they will time out.

[SMALLFIX] Increase time bounds on concurrency test

---

tests/src/test/java/alluxio/client/fs/ConcurrentDeleteIntegrationTest.java
tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterSetTtlTest.java
tests/src/test/java/alluxio/client/fs/ConcurrentRenameIntegrationTest.java

This helps to prevent flaky failures.
The bounds are still tight enough that if the
operations are executed sequentially instead
of concurrently, they will time out.
(cherry-pick)

[SMALLFIX] Increase time bounds on concurrency test (#7599)

---

core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java

This also fixes a race condition which could happen if
initialize is called multiple times concurrently.
Finally, this PR adds logging so that we can see which
connect details are used for initializing the filesystem
context.

[SMALLFIX] Simplify context resetting in AbstractFileSystem

---

core/common/src/main/java/alluxio/network/netty/NettyRPC.java

The test was getting stuck trying to `Thread.join` the operation thread after interrupting it. Turns out that our Netty client was wrapping `InterruptedException` without resetting the interrupted flag. Haven't been able to get the test to fail since fixing this.

[SMALLFIX] Fix flakiness in zk failure test

---

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
core/common/src/main/java/alluxio/heartbeat/HeartbeatThread.java
core/common/src/main/java/alluxio/resource/ResourcePool.java
core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
core/common/src/main/java/alluxio/util/CommonUtils.java
core/common/src/main/java/alluxio/util/ThreadUtils.java
core/server/common/src/main/java/alluxio/cli/validation/Utils.java
core/server/common/src/main/java/alluxio/master/AbstractMaster.java
core/server/common/src/main/java/alluxio/master/audit/AsyncUserAccessAuditLogWriter.java
core/server/worker/src/main/java/alluxio/worker/block/ClientRWLock.java
core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
core/server/worker/src/main/java/alluxio/worker/file/DefaultFileSystemWorker.java
core/server/worker/src/main/java/alluxio/worker/netty/NettyDataServer.java

Update code to follow a general practice of
immediately resetting the interrupt status
if the handling of an InterruptedException
is not going to exit the thread or propagate
the exception as an InterruptedException.

[SMALLFIX] Audit interrupted exception handling

---

tests/src/test/java/alluxio/client/cli/fs/command/CpCommandIntegrationTest.java

The test is flaky, and the functionality is already
covered by CopyToLocalCommandIntegrationTest.

[SMALLFIX] Remove CpCommandIntegrationTest#copyToLocalLarge

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryIdGenerator.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/test/java/alluxio/master/file/PermissionCheckerTest.java
core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java

Otherwise the following could happen:
1. Start master
2. Take snapshot (snapshotted next inode id = 0)
3. Create root inode with id 0, next inode id should be 1
4. Restart master, loading snapshot which thinks next inode id is 0
5. Create directory /x, it gets assigned id 0
6. Try to delete /x, fails because it thinks it's the root inode

[SMALLFIX] Journal the creation of the root directory

---

core/common/src/main/java/alluxio/client/file/URIStatus.java
core/common/src/main/java/alluxio/security/authorization/AccessControlList.java
core/common/src/main/java/alluxio/security/authorization/AclActions.java
core/common/src/main/java/alluxio/security/authorization/AclEntry.java
core/common/src/main/java/alluxio/security/authorization/DefaultAccessControlList.java
core/common/src/main/java/alluxio/wire/FileInfo.java
core/common/src/test/java/alluxio/wire/FileInfoTest.java
core/server/common/src/main/java/alluxio/web/UIFileInfo.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectory.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeFile.java
core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
shell/src/main/java/alluxio/cli/fs/command/GetFaclCommand.java
shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
tests/src/test/java/alluxio/client/cli/fs/command/LsCommandIntegrationTest.java

Instead of keeping a list of string entries in the file info, we keep acl object in the `FileInfo` object. This results in fewer conversions to/ from object when we convert to Thrift

[ALLUXIO-3164] Improve facl serialization/deserialization perf

---

shell/src/main/java/alluxio/cli/fsadmin/report/MetricsCommand.java
shell/src/test/java/alluxio/cli/fsadmin/report/MetricsCommandTest.java
tests/src/test/java/alluxio/client/cli/fsadmin/command/MetricsCommandIntegrationTest.java

There's probably a better way to do this so that we don't need to manually remember to update this whenever we add a new metric. Will leave this to a future PR. @calvinjia does anything similar need to be done for the web UI metrics?

[SMALLFIX] Update metrics command to include set_acl_ops

---

core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java
core/common/src/main/java/alluxio/exception/ExceptionMessage.java
core/server/worker/src/main/java/alluxio/worker/block/SpaceReserver.java
core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java

- Set cancel mark in FileOutStream to true if exception caught on write failures
- Improve exception messages

[SMALLFIX] Set cancel mark in FileOutStream to true if exception caught on write failures

---

core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java
core/common/src/main/java/alluxio/exception/ExceptionMessage.java
core/server/worker/src/main/java/alluxio/worker/block/SpaceReserver.java
core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java

Cherry-pick #7656 from 1.9-snapshot to 1.8
* Set cancel mark in FileOutStream to true if exception caught on write failures
* Improve exception messages

[SMALLFIX] Set cancel mark in FileOutStream to true if exception caught on write failures (#7656)

---

core/client/runtime/pom.xml

Before this fix:
- When building Alluxio from the root dir of the source tree, the protobuf still shows as a dependency of alluxio-core-protobuf, which introduces unshaded protobuf in the final uber client jar.
- When building Alluxio from `core/client/runtime`, the output is correct
This fix corrects the output by enforcing the output having no thrift and protobuf classes in filters.

[ALLUXIO-3278] Enforce no unshaded protobuf and thrift classes in the output

---

shell/src/main/java/alluxio/cli/fsadmin/report/UfsCommand.java

[https://alluxio.atlassian.net/browse/ALLUXIO-3279](https://alluxio.atlassian.net/browse/ALLUXIO-3279)
Format mounted info according to the longest mount point/under storage path.

[ALLUXIO-3279] Format mount command with no arguments

---

pom.xml
shell/src/main/java/alluxio/cli/fs/command/HelpCommand.java

Fix the following issue that may happen on certain terminals:
```bash
$ bin/alluxio fs help ls
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:580)
at java.lang.Integer.valueOf(Integer.java:766)
at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
at jline.UnixTerminal.<init>(UnixTerminal.java:65)
at jline.UnixTerminal.<init>(UnixTerminal.java:50)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at …
```

[SMALLFIX] Avoid potential exception when terminal type can not be decided

---

core/common/src/main/java/alluxio/collections/FieldIndex.java
core/common/src/main/java/alluxio/collections/IndexDefinition.java
core/common/src/main/java/alluxio/collections/IndexedSet.java
core/common/src/main/java/alluxio/collections/NonUniqueFieldIndex.java
core/common/src/main/java/alluxio/collections/UniqueFieldIndex.java
core/common/src/test/java/alluxio/collections/IndexedSetConcurrencyTest.java
core/common/src/test/java/alluxio/collections/IndexedSetTest.java
core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectory.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java

This PR improves type safety by specifying the type of values returned by indices. Previously we just called everything `Object`. Now usages like
```java
int x = indexedSet.getFirst(ID_INDEX, "notAnId");
```
will be caught at compile time instead of at runtime.

[SMALLFIX] Improve type safety for indexed set

---

core/server/master/src/test/java/alluxio/master/MasterTestUtils.java

https://alluxio.atlassian.net/browse/ALLUXIO-3269
change Mockito.mock(...) to mock(...) for all function of class alluxio.master.MasterTestUtils and change import org.mockito.Mockito; to import static org.mockito.Mockito.mock;

[ALLUXIO-3269] Use static imports for standard test utilities for class MasterTestUtilster test utils

---

minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
minicluster/src/test/java/alluxio/multi/process/MultiProcessClusterTest.java
tests/src/test/java/alluxio/server/configuration/ConfigCheckerIntegrationTest.java
tests/src/test/java/alluxio/server/ft/ZookeeperFailureIntegrationTest.java
tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java
tests/src/test/java/alluxio/server/ft/journal/JournalShutdownIntegrationTest.java

This PR adds support for running tests with fixed ports. Previously, we would choose a random currently-available ephemeral port. The problem with ephemeral ports is that multiple processes may choose to run with the same ephemeral port, causing the second test to fail if the first is still using the port. There can be a long delay between when the port is chosen and when it gets bound. Secondary master doesn't bind its RPC port until it is promoted to primary, so it could be many seconds during a failover test between when we select the RPC port and when it finally gets bound. During this time another test could choose to use the port and have a conflict.
With fixed ports, every test will use different ports from every other tests. A central `PortCoordination` class enforces this, and …

[SMALLFIX] Coordinate test ports

---

core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java

Not sure what this Set was doing other than trying to run our test processes out of memory. Replacing with `sleep` to get a similar effect

[SMALLFIX] Remove unnecessary Set

---

core/server/common/src/test/java/alluxio/master/AbstractPrimarySelectorTest.java

This can fail sometimes if the system is under heavy load.

[SMALLFIX] Deflake AbstractPrimarySelectorTest

---

integration/checker/pom.xml

Remove the dependency on jamon-runtime package.

[SMALLFIX] exclude one package in Hive checker

---

tests/src/test/java/alluxio/server/health/WorkerHealthCheckClientIntegrationTest.java

Otherwise this fails/does not test correctly if you have a process running on port 29998.

[SMALLFIX] Use an ephemeral worker port for test.

---

underfs/gcs/src/test/java/alluxio/underfs/gcs/GCSUnderFileSystemTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3268
change Mockito.mock(...) to mock(...) for all function of class alluxio.underfs.gcs.GCSUnderFileSystemTest and change import org.mockito.Mockito; to import static org.mockito.Mockito.mock;
Mockito.when(...) is the same.

[ALLUXIO-3268] Use static imports for standard test utilities for class GCSUnderFileSystemTest 

---

core/common/src/main/java/alluxio/security/authorization/AccessControlList.java
core/common/src/main/java/alluxio/security/authorization/AclActions.java
core/common/src/main/java/alluxio/security/authorization/ExtendedACLEntries.java
core/common/src/test/java/alluxio/security/authorization/AccessControlListTest.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/meta/Inode.java
core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
tests/src/test/java/alluxio/client/cli/fs/command/SetFaclCommandIntegrationTest.java

Before this change, we were ignoring ACL masks. After this change, we will take ACL masks into consideration when we do permission checking. Also we automatically sets masks when updating other relevant entries.

[SMALLFIX] make masks auto update, and make permission checking respect ACL mask

---

bin/alluxio
core/common/src/main/java/alluxio/Constants.java
core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
tests/src/test/java/alluxio/client/cli/fs/GetConfTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3288
If I set `alluxio.zookeeper.enabled=true` alone in `alluxio-site.properties` without setting `alluxio.zookeeper.address`, this error shows before this patch:
```
$ bin/alluxio getConf alluxio.zookeeper.enabled
Exception in thread "main" java.lang.ExceptionInInitializerError
at alluxio.cli.GetConf.getConfImpl(GetConf.java:176)
at alluxio.cli.GetConf.getConf(GetConf.java:141)
at alluxio.cli.GetConf.main(GetConf.java:261)
Caused by: java.lang.IllegalStateException: Inconsistent Zookeeper configuration; alluxio.zookeeper.address should be set if and only if alluxio.zookeeper.enabled is true
at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
at alluxio.conf.InstancedConfiguration.checkZkConfiguration(InstancedConfiguratio …
```

[ALLUXIO-3288] skip conf validation for getConf

---

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go

cherry-pick from 1.9-SNAPSHOT to 1.8 branch

[SMALLFIX] The release package is missing bin/alluxio-monitor.sh (#7752)

---

core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTier.java
core/server/worker/src/test/java/alluxio/worker/block/meta/StorageTierTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3291
Currently Alluxio worker will fail to start if one of the storage disk is failing. This change makes Alluxio worker disregard the failed location and start normally with an error message logged.

[ALLUXIO-3291] Make worker not crash if a storage location cannot be accessed

---

core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTier.java
core/server/worker/src/test/java/alluxio/worker/block/meta/StorageTierTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3291
Cherry-pick https://github.com/Alluxio/alluxio/pull/7751 for `branch-1.8`

[ALLUXIO-3291] make worker not crush if a storage location cannot be accessed (#7751)

---

core/common/src/test/java/alluxio/heartbeat/SleepingTimerTest.java

[https://alluxio.atlassian.net/browse/ALLUXIO-3265](url)
change Mockito.verify(...) to verify(...) for all function of class alluxio.heartbeat.SleepingTimerTest and change import org.mockito.Matchers; to import static org.mockito.Matchers.verify;
Mockito.mock(...), Mockito.times(...) ,Mockito.any(...) and Mockito.anyString() are the same.

[ALLUXIO-3265] Use static imports for standard test utilities for class SleepingTimerTest

---

core/server/worker/src/test/java/alluxio/worker/file/UnderFileSystemUtilsTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3264
change Mockito.verify(...) to verify(...) for all function of class alluxio.worker.file.UnderFileSystemUtilsTest and change import org.mockito.Mockito; to import static org.mockito.Mockito.verify;
Mockito.mock(...),Mockito.when(...), Mockito.times(...) ,Mockito.any(...) and Mockito.anyString() are the same.

[ALLUXIO-3264]Use static imports for standard test utilities for class UnderFileSystemUtilsTest

---

bin/alluxio-start.sh

Right now alluxio-start.sh will check ramdisk if the action is one of local, worker, workers, all. It should only happen if a local worker will be started.

[SMALLFIX] Fix mount check for alluxio-start.sh

---

core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/test/java/alluxio/ConfigurationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3259
Cherry-pick from 1.9-SNAPSHOT
* Fix NPE when passing an option to UFS root from extension
* Fix failing test

[ALLUXIO-3259] Fix NPE when passing an option to UFS root from extension (#7784)

---

core/client/fs/src/main/java/alluxio/client/metrics/ClientMasterSync.java
core/common/src/main/java/alluxio/AbstractClient.java

https://alluxio.atlassian.net/browse/ALLUXIO-3298
- `TransportProvider.Factory.create()` is using `Configuration.get` inside, which should be after `beforeConnect`
- I will cherry-pick this to branch-1.8

[ALLUXIO-3298] Avoid creating transport of metrics client before cluster conf loaded

---

core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
core/common/src/main/java/alluxio/uri/Authority.java
core/common/src/test/java/alluxio/AlluxioURITest.java
core/common/src/test/java/alluxio/uri/AuthorityTest.java
tests/src/test/java/alluxio/client/hadoop/FileSystemUriIntegrationTest.java

Change the SingleMasterAuthority and ZookeeperAuthority to be more concrete check.
add integration tests for using Alluxio on Zookeeper Uri in HDFS API to connect to Alluxio on Zookeeper cluster.

[SMALLFIX] improve Authority regrex and add tests

---

core/client/fs/src/main/java/alluxio/client/metrics/ClientMasterSync.java
core/common/src/main/java/alluxio/AbstractClient.java

https://alluxio.atlassian.net/browse/ALLUXIO-3298
Cherry-pick from 1.9 snapshot to 1.8 branch

[ALLUXIO-3298] Avoid setting transport of metrics client earlier than cluster conf loaded (#7795) 

---

docs/en/Building-Alluxio-From-Source.md
docs/en/Getting-Started.md

- There were a set of variables which were escaped because I believe jekyll thought they were HTML tags. I fixed that by adding preformatting outside of the angled brackets.
- The build from source instructions indicated java 8 or higher. I found that I could only build with java 8. Not 9 or 10.
- I also updated the steps to run the local version to match the same setup as what is in the quick start guide. The original steps did not work for me. However, the quick start instructions did.

[DOCFIX] - accidentally escaped angled brackets and fixing compile from source instructions

---

core/common/src/main/java/alluxio/exception/ExceptionMessage.java
core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
tests/src/test/java/alluxio/client/cli/fs/command/CatCommandIntegrationTest.java

This will make cases of exceptions on empty strings clearer without detracting from the original message.
@aaudiber

[SMALLFIX] - Quote formatted paths in path exceptions

---

core/common/src/main/java/alluxio/exception/ExceptionMessage.java
core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
tests/src/test/java/alluxio/client/cli/fs/command/CatCommandIntegrationTest.java

* quote formatted paths in path exceptions
* Fix unit and integration test

[SMALLFIX] - Quote formatted paths in path exceptions (#7833)

---

core/common/src/main/java/alluxio/security/authorization/DefaultAccessControlList.java
core/common/src/main/java/alluxio/security/authorization/Mode.java
core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
core/common/src/main/java/alluxio/underfs/UnderFileSystem.java
core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/meta/Inode.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectory.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeFile.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/main/java/alluxio/master/file/options/CreateDirectoryOptions.java
core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
tests/src/test/java/alluxio/client/cli/fs/command/SetFaclCommandIntegrationTest.java
tests/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsAclProvider.java
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/NoopHdfsAclProvider.java
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/acl/SupportedHdfsAclProvider.java

https://alluxio.atlassian.net/browse/ALLUXIO-3305
This PR fixes issues uncovered during testing. 
1. ls failed to load files when acl profile is turned on (due to a masked exception) 
2. ACL inheritance should also respect the umask. Basically the inherited acl should not violate any umask and be an AND result with the umask.

[ALLUXIO-3305] Fix loadMetadata bug related to ACL  

---

core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java
core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemApiTest.java
core/common/src/test/java/alluxio/TestLoggerRule.java
core/common/src/test/java/alluxio/TestLoggerRuleTest.java

This will change will warn users if they pass an invalid authority to the client, and then continue to use default configuration values as it currently does as to not break backwards compatibility.
The warning should be upgraded to an exception in a later Alluxio version.
@aaudiber

[SMALLFIX] - Warn users if an unkown authority is passed to the hadoop client

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

This fixes a potential NPE in listStatus when the returned children array is null.

[SMALLFIX] Check for null in ListStatus

---

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java
core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3293
Cherry-pick from master branch 
* Fix retry policy being invalid when reading local block from a crashed local worker
* move updatestream to try

[ALLUXIO-3293] Fix retry policy being invalid when reading local block from a crashed local worker (#7828)

---

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java

https://alluxio.atlassian.net/browse/ALLUXIO-3304
* Limit metrics heartbeat shutdown hook time
* Explicitly set thread to be daemon
* Move warning to finally

[ALLUXIO-3304] Limit metrics heartbeat shutdown hook time (#7796)

---

core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemApiTest.java
core/common/src/main/java/alluxio/uri/Authority.java
core/common/src/test/java/alluxio/uri/AuthorityTest.java

I tried running hibench-spark with both `alluxio://zkHost1:2181,zkHost2:2181` and `alluxio://zkHost1:2181;zkHost2`. Neither worked because the prepare phases uses hadoop, while the run phase uses spark. Using a comma breaks Spark because it tries to split on the comma. Using a semicolon breaks hadoop because it splits on semicolon. They both seem happy with `+` though, so it's nice if we could support it as a third option.
If everyone is on board with supporting `+`, I'll update the docs in a followup PR

[SMALLFIX] Allow + as a uri authority address delimiter

---

core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java
core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemApiTest.java
core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/main/java/alluxio/master/MasterInquireClient.java
core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
core/common/src/main/java/alluxio/master/SingleMasterInquireClient.java
core/common/src/main/java/alluxio/master/ZkMasterInquireClient.java
core/common/src/main/java/alluxio/uri/Authority.java
core/common/src/main/java/alluxio/uri/ZookeeperAuthority.java
core/common/src/main/java/alluxio/util/ThreadUtils.java
core/common/src/test/java/alluxio/AlluxioURITest.java
core/common/src/test/java/alluxio/TestLoggerRule.java
core/common/src/test/java/alluxio/master/MasterInquireClientTest.java
core/common/src/test/java/alluxio/uri/AuthorityTest.java

This adds support for Zookeeper authorities, e.g. `zk@host1:2181,host2:2181,host3:2181`. If the user has Zookeeper configured, and they use the configured connect details in the authority string, we shouldn't throw an exception.
To get the currently configured `Authority` this PR leverages the existing code to create a `ConnectDetails` object based on configuration. Each type of `ConnectDetails` now implements a `toAuthority` method which gives the authority represented by the connect details.
@ZacBlanco

[SMALLFIX] Handle Zookeeper authorities in uri check

---

core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java

Moving to debug level since the situation is expected and not a problem. I saw this get logged reasonably often while running tpcds tests.

[SMALLFIX] Improve logging when failing to add concurrently created inode

---

integration/docker/Dockerfile

https://alluxio.atlassian.net/browse/ALLUXIO-3311
Cherry-pick from https://github.com/Alluxio/alluxio/pull/7817

[ALLUXIO-3311] Use symlink instead of rename for docker build (#7817)

---

core/common/src/main/java/alluxio/util/CommonUtils.java
core/common/src/test/java/alluxio/util/CommonUtilsTest.java
core/server/master/src/main/java/alluxio/master/MasterUtils.java
core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java

Main improvement is to exit early if one of the tasks fails. This also improves the exception types - ExecutionException is needed to differentiate `TimeoutExceptions` thrown by callables vs `TimeoutExceptions` thrown by `invokeAll`
I noticed this issue when my worker failed to start due to an incorrect ramdisk size, but it took over 10 seconds for the error to appear because the process was stuck in `invokeAll`.

[SMALLFIX] Improvements to invokeAll

---

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
core/common/src/main/java/alluxio/util/executor/ExecutorServiceFactories.java
core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java
core/server/worker/src/main/java/alluxio/worker/block/UfsInputStreamManager.java
keyvalue/server/src/main/java/alluxio/master/keyvalue/DefaultKeyValueMaster.java
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java

Our master threads live forever, so there isn't
any functional difference between fixed vs cached
when things are working properly. But it's easy
to add a new thread without remembering to update
the fixed threadpool size, which results in a
difficult to debug situation where the thread
never gets run.

[SMALLFIX] Use cached threadpools for masters

---

core/protobuf/src/main/java/alluxio/proto/dataserver/Protocol.java

replace anonymous type with method reference in alluxio.proto.dataserver.alluxio.proto.dataserver#internalValueMap #316

[SMALLFIX] Java 8 migration: replace anonymous type with method reference in alluxio.proto.dataserver.alluxio.proto.dataserver#internalValueMap #316

---

core/server/master/src/main/java/alluxio/master/file/meta/TtlBucketList.java

[Issue #203] Use @Nullable annotation for method(s) which may return null in alluxio.master.file.meta.getBucketContaining.

[SMALLFIX] Use @nullable annotation in getBucketContaining

---

core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java

Replace
retryRPC(new RpcCallable<Void>() {
@Override
public Void call() throws TException {
mClient.commitBlock(workerId, usedBytesOnTier, tierAlias, blockId, length,
new CommitBlockTOptions());
return null;
}
});
with
retryRPC((RpcCallable<Void>) () -> {
mClient.commitBlock(workerId, usedBytesOnTier, tierAlias, blockId, length,
new CommitBlockTOptions());
return null;
});

[DOCFIX] Java 8 Improvement: replace anonymous type with lambda in alluxio.worker.block.BlockMasterClient#commitBlock

---

shell/src/main/java/alluxio/cli/fs/command/CheckConsistencyCommand.java

[SMALLFIX] Java 5 migrartion: replace for with foreach in alluxio.cli.fs.command.CheckConsistencyCommand#checkConsistency

[SMALLFIX] Java 8 migrartion: replace for with foreach in alluxio.cli.fs.command.CheckConsistencyCommand#checkConsistency

---

pom.xml

2.6.6 has a security vulnerability
https://www.cvedetails.com/cve/CVE-2018-7489/

[SMALLFIX] Bump jackson version to 2.9.7

---

docs/cn/Clients-Hadoop.md

I have updated Chinese document docs/cn/Clients-Hadoop.md to make it more native. In detail, I changed 'Hadoop文件操作会被翻译为文件系统操作。' to 'Hadoop 文件操作会被转换为文件系统操作。'.

[DOCFIX] update Chinese document

---

tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java

Java 8 Improvement: replace lambda with method reference in alluxio.server.ft.journal.JournalBackupIntegrationTest#backupRestoreTest

[SMALLFIX] Java 8 Improvement: replace lambda with method reference

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
tests/src/test/java/alluxio/server/ft/journal/JournalReplayIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3352
Looks like this was accidentally introduced in 
https://github.com/Alluxio/alluxio/commit/1e5d189311ea1061866d91f8ba2e49fea662e92c#diff-493c8b8cf4598e4841f56aa902c7d388, not noticing that the `unmountInternal` was being added inside a `!replayed` block

[ALLUXIO-3352] Replay mount table updates during recursive delete

---

tests/src/test/java/alluxio/server/ft/journal/JournalReplayIntegrationTest.java

This was broken in previous versions but already
fixed in master. Adding this test to keep it fixed.
Related to https://alluxio.atlassian.net/browse/ALLUXIO-3352

[SMALLFIX] Add mount-delete-mount journal replay test

---

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSystem.java

https://alluxio.atlassian.net/browse/ALLUXIO-3342
Journals can be replayed independently, so we
can greatly improve master startup time by replaying
the journals in parallel instead of one after another.
Running locally with a new journal and default
configuration, this change reduces master startup time
from 26 seconds to 11 seconds.

[ALLUXIO-3342] Replay journals in parallel

---

core/server/worker/src/test/java/alluxio/worker/netty/AbstractWriteHandlerTest.java

Java 8 Improvement: replace lambda with method reference in alluxio.worker.netty.AbstractWriteHandlerTest#waitForResponse #376

[SMALLFIX] Java 8 Improvement: replace lambda with method reference #376

---

minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
minicluster/src/test/java/alluxio/multi/process/MultiProcessClusterTest.java
tests/src/test/java/alluxio/server/configuration/ConfigCheckerIntegrationTest.java
tests/src/test/java/alluxio/server/ft/ZookeeperFailureIntegrationTest.java
tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java
tests/src/test/java/alluxio/server/ft/journal/JournalShutdownIntegrationTest.java

Cherry-pick from https://github.com/Alluxio/alluxio/pull/7716
This should prevent the test flakiness we are seeing where ports cannot be bound.

[SMALLFIX] Coordinate test ports (#7716)

---

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java

Please check it.
There is no file named "GlusterFSUnderFileSystem" or "GlusterFSUnderFileSystem.java" in alluxio
and the comment
// workers, short circuit without querying the locations
can only be found in "underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java" by "grep -r '// workers, short circuit without querying the locations'"

[SMALLFIX] Improve comment style in GlusterFSUnderFileSystem

---

core/common/src/main/java/alluxio/exception/ExceptionMessage.java
core/common/src/test/java/alluxio/TestLoggerRule.java
core/common/src/test/java/alluxio/TestLoggerRuleTest.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java
job/server/src/main/java/alluxio/master/job/JobMaster.java
job/server/src/test/java/alluxio/master/job/JobMasterTest.java
tests/src/test/java/alluxio/job/replicate/ReplicateIntegrationTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3355
- Previously when the job master needed to schedule hundreds or thousands of jobs at once, we would send all of the RPCs for each job. Depending on the system this caused a ton of logging messages and would clog the logs when a large number operations ran and could not all be completed at once.
These changes use the same backoff strategy used when we get a `JobDoesNotExist` exception in the replication checker. The `PersistenceChecker` already uses this strategy for `ResourceExhaustedException` as well.

[ALLUXIO-3355] Improvements for behavior for when job master is at full capacity

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java

https://alluxio.atlassian.net/browse/ALLUXIO-3365
`setAcl()` should only be performed by owner of the target.

[ALLUXIO-3365] Fix setAcl permission

---

pom.xml

Surefire's `rerunFailingTests` option allows us to rerun tests which fail at build time for a specified number of retries.
Failures may be due to a variety of errors. Some deterministic, and others not. By adding in this flag we will be allowing some non-deterministically failing tests to fly under the radar for a short period of time until we have proper tracking on jenkins.
For the time being, this should improve the build pass rate due to tests like the `journalFencingFailoverTest` (and a few others) which have been failing at seemingly random times which causes  some inefficiency in getting code merged.
I've set the rerun count to 1, which allows a single test rerun upon one failure (single test may be run a maximum of 2 times). If we see a build fail due to a flake, the test should …

[SMALLFIX] Improve builds by using rerunFailingTests

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java
core/server/master/src/main/java/alluxio/master/file/LostFileDetector.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeLockList.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
core/server/master/src/main/java/alluxio/master/file/meta/LockingScheme.java
core/server/master/src/main/java/alluxio/master/file/meta/MutableLockedInodePath.java
core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java
core/server/master/src/test/java/alluxio/master/file/PermissionCheckTest.java
core/server/master/src/test/java/alluxio/master/file/PermissionCheckerTest.java
core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
core/server/master/src/test/java/alluxio/master/file/replication/ReplicationCheckerTest.java
tests/src/test/java/alluxio/server/health/BlockMasterIntegrityIntegrationTest.java

- Split `LockMode` into `LockPattern` and `LockMode`
- Remove the `WRITE_PARENT` lock pattern. We can get the same effect using `WRITE_LAST` on the parent.
- Remove concept of lock hints. They are no longer needed for anything.
- Shorten `InodeTree.LockPattern` references to just `LockPattern`

[SMALLFIX] Locking cleanups

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

https://alluxio.atlassian.net/browse/ALLUXIO-3372
The order needs to be swapped otherwise unmounting won't stop the sync point.

[ALLUXIO-3372] Swap the order of unmounting and stopSync

---

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
core/client/fs/src/main/java/alluxio/client/metrics/ClientMasterSync.java
core/client/fs/src/main/java/alluxio/client/metrics/MetricsMasterClient.java
core/common/src/main/java/alluxio/metrics/MetricsSystem.java
core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java

https://alluxio.atlassian.net/browse/ALLUXIO-3370
This fixes 2 issues
**Master synchronization**
We update client metrics by removing the old client metrics and adding the new ones. This needs to be synchronized against the code which aggregates client metrics. Otherwise, metrics that should only go up could be seen to go down. (1) clear metrics for client A, (2) aggregate the metrics and report to web UI (doesn't include client A), (3) add metrics for client A.
Previously we synchronized the remove/add on the `mWorkerMetrics` field, but synchronized the lookup (`getMetricsByInstanceTypeAndName`) on the `MetricsStore` instance. This PR changes the synchronization so that all public methods of `MetricsStore` are synchronized on the `MetricsStore` instance. Nothing should synchronize on …

[ALLUXIO-3370] Client metrics fixes

---

pom.xml

Maven 3.6.0 compile alluxio reported the following error
```
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.2:findbugs (findbugs) on project alluxio-parent: Unable to parse configuration of mojo org.codehaus.mojo:findbugs-maven-plugin:3.0.2:findbugs for parameter pluginArtifacts: Cannot assign configuration entry 'pluginArtifacts' with value '${plugin.artifacts}' of type java.util.Collections.UnmodifiableRandomAccessList to property of type java.util.ArrayList -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] …
```

[SMALLFIX]Fix compiling error when using maven 3.6.0

---

core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java

Instead of locking on the instance, we lock on individual indexed sets. This can't lead to deadlock because the synchronized blocks don't contain any code that acquires locks.

[SMALLFIX] Reduce scope of MetricsStore locking to avoid deadlock

---

shell/src/main/java/alluxio/cli/fs/command/CatCommand.java

Increase the cat buffer size to 1MB. 512 is unreasonably small for larger files.

[SMALLFIX] Use 1 MB buffer size for cat.

---

README.md

Fix some link errors in alluxio documentation:
- Alluxio Latest Release Document: 
http://www.alluxio.org/documentation/.  =>  https://www.alluxio.org/download/releases/
- Master Branch Document:
http://alluxio.org/documentation/master/ => https://www.alluxio.org/docs/master/en/

[ALLUXIO-3387] Fix some link errors in alluxio documentation

---

core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java
tests/src/test/java/alluxio/client/cli/fs/command/DistributedMvCommandTest.java
tests/src/test/java/alluxio/client/cli/fs/command/SetReplicationCommandTest.java

This also fixes an issue with recursive setReplication, where we create a WRITE_EDGE locked inode path instead of a WRITE_INODE locked inode path

[SMALLFIX] Add job tests

---

core/protobuf/src/main/java/alluxio/proto/meta/InodeMeta.java
core/protobuf/src/proto/meta/inode_meta.proto
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectory.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryView.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeLockManager.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
core/server/master/src/main/java/alluxio/master/file/meta/MutableInodeDirectory.java

With off-heap metadata, it is no longer cheap to
query the number of children of a directory. This
causes performance issues when the ls command needs
to show directory sizes. This commit addresses the
issue by keeping track of directory size in inode
directory metadata.

[SMALLFIX] Track inode directory sizes

---

dev/jenkins/build.sh
dev/jenkins/run_docker.sh

- Make script interruptible with Ctrl-C
- Construct args list incrementally to improve comment style
- Run inside a main function
- Set HOME=/home/jenkins
- Support mvn arguments passed to run_docker.sh
- Make fork count configurable

Build script improvements

---

core/common/src/main/java/alluxio/PropertyKey.java
core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
core/common/src/test/java/alluxio/ConfigurationTestUtils.java
core/common/src/test/java/alluxio/util/network/NetworkAddressUtilsTest.java
core/server/common/src/main/java/alluxio/cli/ValidateEnv.java
core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
core/server/worker/src/main/java/alluxio/worker/DataServer.java
core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
core/server/worker/src/test/java/alluxio/worker/block/BlockWorkerTest.java
integration/mesos/src/main/java/alluxio/mesos/AlluxioScheduler.java
integration/mesos/src/main/java/alluxio/mesos/OfferUtils.java
minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
tests/src/test/java/alluxio/client/fs/LocalFirstPolicyIntegrationTest.java
tests/src/test/java/alluxio/client/keyvalue/KeyValuePartitionIntegrationTest.java

Removed unused worker RPC server from worker process.
Removed property definition for `WORKER_DATA_PORT`. `GrpcDataServer` now uses `WORKER_RPC_PORT`. For backward compatibility, the default value for `WORKER_RPC_PORT` is now `29999` and `alluxio.worker.data.port` becomes an alias for `WORKER_RPC_PORT`.

Refactor gRPC worker ports

---

core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
tests/src/test/java/alluxio/testutils/BaseIntegrationTest.java

Most of the tests in FileSystemMasterTest take 100-200ms when run individually. But when running all 100 tests in a suite, they take longer and longer, with the last tests taking ~600ms. The slowdown happens because it takes longer and longer for the MetricsMaster to stop. It takes longer and longer to stop because it is stuck in `ClusterMetricsUpdater#heartbeat`: https://github.com/Alluxio/alluxio/blob/master/core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java#L227. This method keeps taking longer and longer because we don't reset metrics across test runs, so the number of metrics to aggregate keeps increasing.
With this change, the test duration drops from 24 seconds to 10 seconds when running in my local intellij.
@ggezer This might fix the test slowdown …

Improve FileSystemMasterTest performance

---

core/client/fs/src/main/java/alluxio/client/block/stream/GrpcBlockingStream.java
core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java
core/server/worker/src/main/java/alluxio/worker/grpc/AbstractReadHandler.java

When we were using netty the data buffer is release by netty when it sends the data. With gRPC however, it is assumed to be immutable so the lifecycle management is on us. For now, switching to pass on heap buffer to gRPC so it can be garbage collected.

properly release buffer for gRPC data path

---

job/client/src/main/java/alluxio/client/job/RetryHandlingJobMasterClient.java

ByteBuffer being left out of retry code was causing ByteBuffer to be read to completion in the first attempt and was returning empty byte array on next attempts.

Fix job master client sending empty config on retries

---

core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java
core/server/worker/src/main/java/alluxio/worker/grpc/AbstractReadHandler.java
core/server/worker/src/test/java/alluxio/worker/grpc/BlockReadHandlerTest.java
core/server/worker/src/test/java/alluxio/worker/grpc/ReadHandlerTest.java

Pass in direct buffer for gRPC streams instead of on-heap copy. This should be safe given gRPC serializes the message on the same thread as the caller. No errors so far in the initial concurrent IO tests.

remove extra copy of data buffer for gRPC streaming

---

core/common/src/main/java/alluxio/PropertyKey.java

Bumping up the chunk size to 1MB and flow control window to 2MB by default for better throughput.

Improve gRPC data streaming throughput
