Alluxio/alluxio

- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
https://alluxio.atlassian.net/browse/ALLUXIO-2322
Change raw type of Inode in InodeTree.traverseToInodeInternal to Inode<?>
> [ALLUXIO-2322]Raw type of Inode in InodeTree.traverseToInodeInternal

- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2285
Fix javadoc into simple present tense
> [ALLUXIO-2285] Fix javadoc for OSSUnderFileSystem#toURIPath

- keyvalue/client/src/main/java/alluxio/client/keyvalue/BaseKeyValueStoreReader.java
https://alluxio.atlassian.net/browse/ALLUXIO-2356
Change "kv store" to "key-value store" in the comments
> [ALLUXIO-2356] Improve comments for BaseKeyValueStoreReader#get

- core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
https://alluxio.atlassian.net/browse/ALLUXIO-2313
Add descriptions for member variables and fix comments in DynamicResourcePool.java
> [ALLUXIO-2313]Improve javadoc for DynamicResourcePool (member variables)

- core/common/src/main/java/alluxio/LeaderSelectorClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2311
> [ALLUXIO-2311]Improve javadoc for LeaderSelectorClient (setCurrentMasterThread)

- core/server/src/main/java/alluxio/master/file/async/DefaultAsyncPersistHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-2334
Mark class DefaultAsyncPersistHandler with keyword "final"
> [ALLUXIO-2334] Mark class DefaultAsyncPersistHandler with keyword "final"

- core/common/src/main/java/alluxio/collections/UniqueFieldIndex.java
https://alluxio.atlassian.net/browse/ALLUXIO-2104
> [ALLUXIO-2104]Update javadoc UniqueFieldIndex class comments #4129

- core/server/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-2333
public final class BlockMasterWorkerServiceHandler implements
BlockMasterWorkerService.Iface {
> [ALLUXIO-2333]Mark class BlockMasterWorkerServiceHandler final

- core/common/src/main/java/alluxio/Constants.java
https://alluxio.atlassian.net/browse/ALLUXIO-2259
> [ALLUXIO-2259]remove alluxio.Constants.DEFAULT_HOST_RESOLUTION_TIMEOUT_MS from Constants.java

- underfs/s3/src/test/java/alluxio/underfs/s3/S3InputStreamTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1583
> [ALLUXIO-1583] Add test coverage for S3InputStream.java

- core/common/src/main/java/alluxio/master/block/BlockId.java
https://alluxio.atlassian.net/browse/ALLUXIO-2290
> [ALLUXIO-2290]Fix javadoc in BlockId.java

- core/server/src/main/java/alluxio/worker/block/BlockStoreEventListener.java
https://alluxio.atlassian.net/browse/ALLUXIO-2282
This file refers to metadata as "meta data". I correct this to "metadata".
> [ALLUXIO] Fix javadoc in BlockStoreEventListener.java  by "zhuzhuxia1"

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2321
MF1533074 张雅淋
> [ALLUXIO-2321] Remove unused variable in AlluxioFuseFileSystem

- core/common/src/main/java/alluxio/AbstractMasterClient.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/server/src/main/java/alluxio/web/WebInterfaceHeaderServlet.java
Generalize the utility to take the leader path as an argument
> [SMALLFIX] Refactor zookeeper code to inject leader path

- core/server/src/main/java/alluxio/worker/DefaultAlluxioWorker.java
https://alluxio.atlassian.net/browse/ALLUXIO-2343
Remove the log statement
> [ALLUXIO-2343] Improve error handling in DefaultAlluxioWorker#createThriftServerSocket

- underfs/oss/src/test/java/alluxio/underfs/oss/OSSInputStreamTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1585
> [ALLUXIO-1585] Add test coverage for OSSInputStream.java

- core/common/src/main/java/alluxio/AbstractClient.java
- core/common/src/main/java/alluxio/AbstractMasterClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2302
MG1633087
> [SMALLFIX]remove the description

- core/server/src/test/java/alluxio/master/file/meta/MountTableTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2134
> [ALLUXIO-2134]Mark class MountTableTest final 

- bin/alluxio-workers.sh
https://alluxio.atlassian.net/browse/ALLUXIO-2391
> [ALLUXIO-2391] Fix initial run of alluxio format fails because there is no logs dir

- core/server/src/test/java/alluxio/master/file/meta/TtlIntervalRule.java
https://alluxio.atlassian.net/browse/ALLUXIO-2135
> [ALLUXIO-2135]mark TtlIntervalRule final

- core/common/src/main/java/alluxio/LeaderInquireClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2303
Add a javadoc describing the function of sCreatedClients.
> [ALLUXIO-2303] Improve javadoc for LeaderInquireClient

- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
https://alluxio.atlassian.net/browse/ALLUXIO-2316
[ALLUXIO-2316] modified by MG1633035
> [ALLUXIO-2316] Improve javadoc for CreatePathResult constructor in InodeTree.java

- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
https://alluxio.atlassian.net/browse/ALLUXIO-2319
> [ALLUXIO-2319] Improve lockFullInodePath() in InodeTree.java

- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystemFactory.java
https://alluxio.atlassian.net/browse/ALLUXIO-2346
Remove the log statement.
> [ALLUXIO-2346]Improve error handling in S3AUnderFileSystemFactory#create

- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2147
mf1633045
> [ALLUXIO-2147]Add javadoc for getFileInfoTest

- core/client/src/main/java/alluxio/client/file/FileInStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-2130
>   [ALLUXIO-2130]  Ends a comment with period

- core/common/src/test/java/alluxio/resource/DynamicResourcePoolTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2257
> [ALLUXIO-2257] Improve naming in DynamicResourcePoolTest

- core/common/src/test/java/alluxio/metrics/MetricsConfigTest.java
ALLUXIO-2266
Reference static method through the class in MetricsConfi…
https://alluxio.atlassian.net/browse/ALLUXIO-2266
> [ALLUXIO-2266]Reference static method through the class in MetricsConfigTest

- core/server/src/test/java/alluxio/master/AlluxioMasterRestServiceHandlerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2160
> [ALLUXIO-2160] Write unit tests for AlluxioMasterRestServiceHandler

- core/server/src/main/java/alluxio/worker/block/BlockStore.java
https://alluxio.atlassian.net/browse/ALLUXIO-2270
> [ALLUXIO-2270] delete all 'the' in the line. #4154

- core/client/src/main/java/alluxio/hadoop/HadoopUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-2374
> [ALLUXIO-2374]improve javadoc in hadooputils

- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-2339
remove the redundant log statement
> [ALLUXIO-2339]Improve error handling in NetworkAddressUtils#getLocalIpAddress

- core/common/src/main/java/alluxio/LeaderSelectorClient.java
[ALLUXIO-2309]https://alluxio.atlassian.net/browse/ALLUXIO-2309
modified by MG1633097
description:Remove the unnecessary description in getParticipants.
> [ALLUXIO-2309] Improve javadoc for LeaderSelectorClient (getParticipants)

- core/server/src/main/java/alluxio/master/file/options/SetAttributeOptions.java
https://alluxio.atlassian.net/browse/ALLUXIO-2300
MG1633025 谷雨
> [SMALLFIX]correct the typo

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftOutputStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-2388
Reword comment in SwiftOutputStream
> [ALLUXIO-2388]Reword comment in SwiftOutputStream

- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystemFactory.java
https://alluxio.atlassian.net/browse/ALLUXIO-2347
remove log statement
> [ALLUXIO-2347] Improve error handling in S3UnderFileSystemFactory#create

- core/common/src/test/java/alluxio/metrics/MetricsConfigTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2136
To prevent accidental extension.
> [ALLUXIO-2136] Mark class MetricsConfigTest as final

- core/common/src/main/java/alluxio/RuntimeConstants.java
https://alluxio.atlassian.net/browse/ALLUXIO-2265
I have marked RuntimeConstants class name in RuntimeConstants.java with annotation "@ThreadSafe".
> [ALLUXIO-2265]Mark RuntimeConstants class name in RuntimeConstants.java with annotation "@ThreadSafe"

- underfs/swift/src/main/java/alluxio/underfs/swift/http/SwiftDirectClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2387
> [ALLUXIO-2387] Reword Comment in SwiftDirectClient

- core/server/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
https://alluxio.atlassian.net/browse/ALLUXIO-2386
> [ALLUXIO-2386] Improve precondition check in AsyncJournalWriter.java

- core/common/src/main/java/alluxio/LeaderSelectorClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2308
> [ALLUXIO-2308]Remove the unnecessary description of the isLeader method. Only the @returns clause is necessary.

- keyvalue/client/src/main/java/alluxio/client/keyvalue/KeyValuePartitionReader.java
https://alluxio.atlassian.net/browse/ALLUXIO-2355
> [ALLUXIO-2355] Modify "should only contains" to "should only contain"

- core/common/src/main/java/alluxio/collections/ConcurrentHashSet.java
https://alluxio.atlassian.net/browse/ALLUXIO-2274
MG1633024
Improve equals method in ConcurrentHashSet.java
> [ALLUXIO-2274] Improve equals method in ConcurrentHashSet.java

- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystemFactory.java
https://alluxio.atlassian.net/browse/ALLUXIO-2348
Remove the log statement in file OSSUnderFileSystemFactory.java.
> [ALLUXIO-2348]Improve error handling in OSSUnderFileSystemFactory#create

- core/common/src/main/java/alluxio/PropertyKey.java
- core/server/src/main/java/alluxio/worker/block/TieredBlockStore.java
- docs/_data/table/cn/worker-configuration.yml
- docs/_data/table/en/worker-configuration.yml
- docs/_data/table/worker-configuration.csv
https://alluxio.atlassian.net/browse/ALLUXIO-2400
In TieredBlockStore, the MAX_RETRIES is a hard code, it might be a good choice to make it configurable.
> [ALLUXIO-2400] Make MAX_RETRIES in TieredBlockStore configurable

- core/common/src/main/java/alluxio/PropertyKeyFormat.java
https://alluxio.atlassian.net/browse/ALLUXIO-2264
> [ALLUXIO-2264] Mark enum PropertyKeyFormat with annotation @ThreadSafe

- docs/en/Architecture.md
https://alluxio.atlassian.net/browse/ALLUXIO-2357
> [ALLUXIO-2357] Remove extra space in Architecture.md

- core/server/src/main/java/alluxio/worker/block/BlockMetadataManager.java
https://alluxio.atlassian.net/browse/ALLUXIO-2273
> [ALLUXIO-2273]Change meta data to metadata in BlockMetadataManager

- .gitignore
- core/common/src/test/java/alluxio/wire/ThriftUtilsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1775
> [ALLUXIO-1775] Add unit tests for alluxio.wire.ThriftUtils

- shell/src/main/java/alluxio/cli/AlluxioShell.java
https://alluxio.atlassian.net/browse/ALLUXIO-2327
This is a new PR, the previous PR is closed because I can't fix the problem which I meet
> [ALLUXIO-2327]update javadoc with active voice

- core/server/src/main/java/alluxio/worker/netty/DataServerHandler.java
- docs/en/Command-Line-Interface.md
https://alluxio.atlassian.net/browse/ALLUXIO-2384
> [ALLUXIO-2384] Improve precondition check in DataServerHandler.java

- core/server/src/main/java/alluxio/master/file/meta/options/MountInfo.java
https://alluxio.atlassian.net/browse/ALLUXIO-2329
> [ALLUXIO-2329] Fix javadoc in MountInfo#getUfsUri

- core/server/src/main/java/alluxio/master/file/meta/MutableLockedInodePath.java
https://alluxio.atlassian.net/browse/ALLUXIO-2363
i changed Inode getAncestorInode()  to Inode<?> getAncestorInode()
>  [ALLUXIO-2363]Parameterize the returned type Inode in MutableLockedInodePath.getAncestorInode

- core/server/src/main/java/alluxio/worker/file/FileSystemWorkerClientServiceHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-2383
> [ALLUXIO-2383]add error message

- core/common/src/main/java/alluxio/heartbeat/HeartbeatThread.java
https://alluxio.atlassian.net/browse/ALLUXIO-2382
> [ALLUXIO-2382] Improve precondition check in HeartbeatThread.java

- tests/src/test/java/alluxio/client/keyvalue/KeyValuePartitionIntegrationTest.java
- tests/src/test/java/alluxio/client/keyvalue/KeyValueSystemIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1589
- Added tests for the factory of KeyValuePartitionWriter
- Added tests for the factory of KeyValuePartitionReader
- Added tests for the factory of KeyValueSystem
> [ALLUXIO-1589] Added test coverage for KeyValueStore factories

- core/client/src/main/java/alluxio/client/block/LocalBlockInStream.java
- core/client/src/main/java/alluxio/client/block/LocalBlockOutStream.java
- core/client/src/main/java/alluxio/client/block/RemoteBlockInStream.java
- core/client/src/main/java/alluxio/client/block/RemoteBlockOutStream.java
- core/client/src/main/java/alluxio/client/file/FileOutStream.java
- core/client/src/main/java/alluxio/client/file/FileSystemContext.java
- core/client/src/main/java/alluxio/client/file/UnderFileSystemFileOutStream.java
- core/client/src/test/java/alluxio/client/file/FileOutStreamTest.java
- core/client/src/test/java/alluxio/client/lineage/LineageFileOutStreamTest.java
@peisun1115 , could you take a look?
> [SMALLFIX] Use Closer pattern to improve closing logic

- docs/en/Configuring-Alluxio-with-secure-HDFS.md
> [DOCFIX] Add the periodical kinit documentation in secure HDFS docs.

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- tests/src/test/java/alluxio/hadoop/FileSystemAclIntegrationTest.java
Also added integration tests, which failed before this change and passes after this fix.
> [SMALLFIX] Do not apply umask for loaded file/dir from UFS

- docs/en/Web-Interface.md
removed extraneous carriage returns to better display list elements consistent with documentation styleguide.
> [DOCFIX] Better display list items

- core/client/src/main/java/alluxio/client/block/BlockWorkerInfo.java
https://alluxio.atlassian.net/browse/ALLUXIO-2375
> [ALLUXIO-2375] Improve precondition check in BlockWorkerInfo.java

- docs/_data/table/en/operation-command.yml
- docs/_data/table/operation-command.csv
- docs/_includes/Command-Line-Interface/checkConsistency.md
- docs/en/Command-Line-Interface.md
https://alluxio.atlassian.net/browse/ALLUXIO-2401
> [ALLUXIO-2401] Documentation for check consistency command

- underfs/local/src/test/java/alluxio/underfs/local/LocalUnderFileSystemTest.java
Currently this class is only covered by integration tests, unit tests are needed.
Jira: https://alluxio.atlassian.net/browse/ALLUXIO-1593
> [ALLUXIO-1593] Add unit test coverage for LocalUnderFileSystem

- core/common/src/main/java/alluxio/AbstractMasterClient.java
- core/common/src/main/java/alluxio/MasterInquireClient.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/server/src/main/java/alluxio/web/WebInterfaceHeaderServlet.java
- shell/src/main/java/alluxio/shell/command/MasterInfoCommand.java
https://alluxio.atlassian.net/browse/ALLUXIO-1976
> [ALLUXIO-1976] Add a command to print out the relative master information

- core/server/src/main/java/alluxio/master/journal/JournalReader.java
- core/server/src/main/java/alluxio/worker/file/FileSystemWorkerClientServiceHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-2385
> [ALLUXIO-2385]Improve precondition check in JournalReader.java

- docs/cn/Debugging-Guide.md
see https://alluxio.atlassian.net/browse/ALLUXIO-2418
> [ALLUXIO-2418]Update Debugging-Guide.md of the Chinese version

- core/client/src/main/java/alluxio/client/UnderStorageType.java
https://alluxio.atlassian.net/browse/ALLUXIO-2370
@calvinjia
> [ALLUXIO-2370] rename 'Under Storage' to 'the under storage' in docs

- core/common/src/main/java/alluxio/Configuration.java
- core/common/src/main/java/alluxio/util/ConfigurationUtils.java
- core/server/src/main/java/alluxio/master/AlluxioMaster.java
- core/server/src/main/java/alluxio/worker/AlluxioWorker.java
- shell/src/main/java/alluxio/cli/AlluxioShell.java
- shell/src/main/java/alluxio/cli/ValidateConf.java
So configuration is forced to be checked.
> [SMALLFIX] Consolidate conf validation from different entry point to its init process

- docs/_config.yml
- docs/_includes/Running-Hadoop-MapReduce-on-Alluxio/add-jar-libjars.md
- docs/_includes/Running-Hadoop-MapReduce-on-Alluxio/config-hadoop.md
- docs/_includes/Running-Hadoop-MapReduce-on-Alluxio/run-wordcount.md
- docs/cn/Running-HBase-on-Alluxio.md
- docs/cn/Running-Hadoop-MapReduce-on-Alluxio.md
- docs/en/Debugging-Guide.md
- docs/en/Running-HBase-on-Alluxio.md
- docs/en/Running-Hadoop-MapReduce-on-Alluxio.md
- docs/en/Running-Hive-with-Alluxio.md
https://alluxio.atlassian.net/browse/ALLUXIO-2403
> [ALLUXIO-2403] Introduced ALLUXIO_CLIENT_JAR_PATH variable in docs

- core/client/src/main/java/alluxio/client/block/RemoteBlockInStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-1904
> [ALLUXIO-1904] Changed creation behavior of RemoteBlockReader in RemoteBlockInStream

- core/client/src/main/java/alluxio/client/file/FileSystemUtils.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
This fixes the -PhdfsTest failure for "PersistCommandTest"
> [SMALLFIX] Make recursive UFS mkdirs stop at Alluxio root

- core/client/src/main/java/alluxio/client/file/FileSystemUtils.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
To pick up a fix for `PersistCommandTest` with `-PhdfsTest`.
> [SMALLFIX] Merge branch-1.3 to master

- core/server/src/main/java/alluxio/master/AlluxioMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-2341
Improve error handling in AlluxioMaster
> [ALLUXIO-2341]Improve error handling in AlluxioMaster#startMasters

- docs/_includes/Building-Alluxio-Master-Branch/supported-values.md
https://alluxio.atlassian.net/browse/ALLUXIO-2360
> [ALLUXIO-2360] Fixing documentation in Building-Alluxio-Master-Branch/supported-values.md

- docs/en/Command-Line-Interface.md
https://alluxio.atlassian.net/browse/ALLUXIO-2366
> [Alluxio-2366] Fix documentation in Command-Line-Interface.md

- core/common/src/main/java/alluxio/heartbeat/HeartbeatScheduler.java
https://alluxio.atlassian.net/browse/ALLUXIO-2381
> [ALLUXIO-2381] Fix for error message

- core/common/src/main/java/alluxio/collections/IndexedSet.java
https://alluxio.atlassian.net/browse/ALLUXIO-2380
> [ALLUXIO-2380] Improve precondition check

- docs/en/Command-Line-Interface.md
https://alluxio.atlassian.net/browse/ALLUXIO-2367
> [ALLUXIO-2367] Fixing documentation in Command-Line-Interface.md

- docs/_includes/Building-Alluxio-Master-Branch/supported-values.md
- docs/en/Command-Line-Interface.md
https://alluxio.atlassian.net/browse/ALLUXIO-2359
> [ALLUXIO-2359] Fixing documentation in supported-values.md

- core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
https://alluxio.atlassian.net/browse/ALLUXIO-2379
> [ALLUXIO-2379] Improve precondition check

- core/client/src/main/java/alluxio/client/block/RetryHandlingBlockWorkerClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2376
> [ALLUXIO-2376] Improve precondition check

- core/server/src/main/java/alluxio/master/file/meta/LockedInodePath.java
https://alluxio.atlassian.net/browse/ALLUXIO-2361
> [ALLUXIO-2361] Parameterize the returned type

- tests/src/test/java/alluxio/master/JournalIntegrationTest.java
Journal recovery also comes with consistency checking which may take longer.
> [SMALLFIX] Resolve test flakiness.

- docs/en/Configuring-Alluxio-with-MapR-FS.md
> [SMALLFIX] Minor update of MapR-FS docs

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-2433
> [ALLUXIO-2433] Permissive startup check consistency

- core/server/src/main/java/alluxio/RunUtils.java
- core/server/src/main/java/alluxio/cli/Format.java
- core/server/src/main/java/alluxio/master/AlluxioMaster.java
- core/server/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
- core/server/src/main/java/alluxio/master/AlluxioMasterService.java
- core/server/src/main/java/alluxio/master/DefaultAlluxioMaster.java
- core/server/src/main/java/alluxio/master/FaultTolerantAlluxioMaster.java
- core/server/src/main/java/alluxio/master/block/BlockMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/master/file/FileSystemMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/master/lineage/LineageMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/web/MasterWebServer.java
- core/server/src/main/java/alluxio/web/WebInterfaceBrowseServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceDependencyServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceGeneralServlet.java
- core/server/src/main/java/alluxio/web/WebInterfaceMemoryServlet.java
- core/server/src/main/java/alluxio/worker/AlluxioWorker.java
- core/server/src/main/java/alluxio/worker/DefaultAlluxioWorker.java
- core/server/src/test/java/alluxio/master/AlluxioMasterRestServiceHandlerTest.java
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java
- minicluster/src/main/java/alluxio/master/LocalAlluxioMaster.java
- minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java
- tests/src/test/java/alluxio/master/ServiceSocketBindIntegrationTest.java
- tests/src/test/java/alluxio/master/lineage/LineageMasterClientRestApiTest.java
This PR:
- mirrors the Alluxio worker class hierarchy (AlluxioWorker, AlluxioWorkerService, DefaultAlluxioWorker) for Alluxio master
- removes System.exit() from DefaultAlluxioWorker constructor (which among other things will prevent hard to debug test failures)
> [SMALLFIX] refactoring master and worker

- tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java
The client cleanup has timed out in Jenkins a couple times, lets increase it.
> [SMALLFIX] Increase timeout journal shutdown test

- core/server/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
- tests/src/test/java/alluxio/master/AlluxioMasterRestApiTest.java
This PR adds a parameter raw to /master/configuration REST API for controlling whether the property values should be resolved or not.
https://alluxio.atlassian.net/browse/ALLUXIO-2406
It reopens https://github.com/Alluxio/alluxio/pull/4294.
> [ALLUXIO-2406] Be able to resolve configuration property values in REST service

- core/server/pom.xml
- core/server/src/main/java/alluxio/proxy/FileSystemClientRestServiceHandler.java
- docs/en/File-System-API.md
Provides documentation for: https://alluxio.atlassian.net/browse/ALLUXIO-2232
Detailed API-level documentation is generating using MireDot during Alluxio build. This is how it looks like:
> [ALLUXIO-2232] File System REST API documentation.

- core/server/src/main/java/alluxio/master/file/meta/LockedInodePath.java
https://alluxio.atlassian.net/browse/ALLUXIO-2362
> [ALLUXIO-2362] Parameterized raw type declaration of Inode in LockedInodePath class

- docs/cn/index.md
For consistency with the English docs.
> [DOCFIX] Update Chinese index.md.

- core/client/src/main/java/alluxio/client/MetaMasterClient.java
- core/client/src/main/java/alluxio/client/RetryHandlingMetaMasterClient.java
- core/common/src/main/java/alluxio/wire/MasterInfo.java
- core/server/src/main/java/alluxio/master/MetaMasterClientServiceHandler.java
Followup to small style errors introduced in https://github.com/Alluxio/alluxio/pull/4383
> [SMALLFIX] Minor cleanups

- docs/pt/index.md
@calvinjia Updated the contributor numbers in the Portuguese documentation.
> [DOCFIX] Updated contributor numbers

- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
Use listStatus.isDir instead of isDirectory to make hadoop-1 happy
> [SMALLFIX] Fix build

- docs/en/Configuration-Settings.md
https://alluxio.atlassian.net/browse/ALLUXIO-2369
> [ALLUXIO-2369]Clarify intro in Configuration-Settings.md

- core/server/src/main/java/alluxio/master/file/PermissionChecker.java
https://alluxio.atlassian.net/browse/ALLUXIO-2364
> [ALLUXIO-2364]Change the type of the argument Inode

- docs/en/Configuring-Alluxio-with-secure-HDFS.md
Doc fix for Configuring Alluxio with secure HDFS
> [SMALLFIX] Doc fix

- core/server/src/test/java/alluxio/worker/block/BlockLockManagerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2445
> [ALLUXIO-2445] Fix concurrenct data structure in BlockLockManagerTest.

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-2449
> [ALLUXIO-2449] Improve concurrency for getFileInfo

- bin/alluxio
- examples/src/main/java/alluxio/cli/MiniBenchmark.java
https://alluxio.atlassian.net/browse/ALLUXIO-2441
A simple tool to run a read/write benchmark. I am not sure whether you guys are ok with checking in this.
> [ALLUXIO-2441 ] MiniBenchmark

- core/common/src/main/java/alluxio/wire/AlluxioMasterInfo.java
- core/common/src/main/java/alluxio/wire/StartupConsistencyCheck.java
- core/common/src/main/java/alluxio/wire/StartupConsistencyCheckStatus.java
- core/common/src/test/java/alluxio/wire/AlluxioMasterInfoTest.java
- core/server/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/web/WebInterfaceGeneralServlet.java
- tests/src/test/java/alluxio/master/AlluxioMasterRestApiTest.java
- tests/src/test/java/alluxio/master/MasterTestUtils.java
- tests/src/test/java/alluxio/master/StartupConsistencyCheckTest.java
- tests/src/test/java/alluxio/rest/RestApiTest.java
> [SMALLFIX] Surface startup consistency check result in master info.

- bin/alluxio
- shell/src/main/java/alluxio/cli/GetConf.java
https://alluxio.atlassian.net/browse/ALLUXIO-2456
> [ALLUXIO-2456] Add utility for printing configuration

- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/common-configuration.csv
- docs/_data/table/en/common-configuration.yml
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2460
> [ALLUXIO-2460] Remote hdfs hint

- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/file/meta/Inode.java
- core/server/src/main/java/alluxio/master/file/meta/InodeDirectory.java
- core/server/src/main/java/alluxio/master/file/meta/InodeFile.java
- core/server/src/main/java/alluxio/master/file/meta/InodeLockList.java
- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- core/server/src/test/java/alluxio/master/file/meta/InodeDirectoryTest.java
- core/server/src/test/java/alluxio/master/file/meta/InodeFileTest.java
- core/server/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2453
> [ALLUXIO-2453] Concurrent rename

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-2453
> [ALLUXIO-2453] Follow up to concurrent rename changes.

- core/server/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
This is the same changes applied to worker as those applied to master.
> [SMALLFIX] Add parameter "raw_configuration" to the worker/info endpoint.

- core/common/src/main/java/alluxio/collections/IndexedSet.java
- core/common/src/main/java/alluxio/util/IdUtils.java
- core/server/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/src/test/java/alluxio/master/AlluxioMasterRestServiceHandlerTest.java
- minicluster/src/main/java/alluxio/master/LocalAlluxioMaster.java
- minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java
- tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java
- tests/src/test/java/alluxio/master/MasterFaultToleranceIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2439
> [ALLUXIO-2439] Randomly generate worker ids to avoid collisions

- core/client/pom.xml
- core/client/src/main/java/alluxio/client/block/StreamFactory.java
- core/client/src/main/java/alluxio/client/block/stream/BlockOutStream.java
- core/common/pom.xml
- core/common/src/main/java/alluxio/network/protocol/Status.java
- core/server/pom.xml
- pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-2441
> [SMALLFIX] Some style fixes

- core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2464
> [ALLUXIO-2464]raise the log level in AbstractFileSystem

- core/client/src/main/java/alluxio/hadoop/HdfsFileInputStream.java
- core/client/src/test/java/alluxio/hadoop/HdfsFileInputStreamTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2466
> [ALLUXIO-2466]add a skip method in HdfsFileInputStream.java

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
Sets the parent id correctly and adds a test to catch this.
> [SMALLFIX] Fix bug in rename recovery

- tests/src/test/java/alluxio/hadoop/FileSystemAclIntegrationTest.java
User `CreateOptions` and `MkdirsOptions` to make the UFS operation atomic. Otherwise, the metadata might be loaded (with default `rwxr-xr-x`) before it's chmod'ed.
> [SMALLFIX] [branch-1.4] Deflake FileSystemAclIntegrationTest

- integration/mesos/src/main/java/alluxio/mesos/AlluxioScheduler.java
> [SMALLFIX] Handle when the root directory is named just "alluxio"

- docs/_config.yml
Fix variable "ALLUXIO_CLIENT_JAR_PATH"
> [Branch-1.4][SMALLFIX] Fix the client jar path site variable

- tests/src/test/java/alluxio/client/FreeAndDeleteIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2485
> [ALLUXIO-2485] remove toString()

- docs/en/Configuring-Alluxio-with-HDFS.md
https://alluxio.atlassian.net/browse/ALLUXIO-2472
> [ALLUXIO-2472] docs/en/Configuring-Alluxio-with-HDFS.md Doc Fix

- core/common/src/main/java/alluxio/thrift/BlockWorkerClientService.java
- core/common/src/thrift/block_worker.thrift
The exceptions thrown are removed by
https://github.com/Alluxio/alluxio/pull/4259/
> [SMALLFIX] Fix the thrift def of requestBlockLocation

- tests/src/test/java/alluxio/hadoop/fs/AccumulatingReducer.java
Add javadoc for AccumulatingReducer#AccumulatingReducer
> [SMALLFIX] Add javadoc for AccumulatingReducer#AccumulatingReducer

- docs/en/Getting-Started.md
> [DOCFIX] Link to Java setup page in Quick Start.

- tests/src/test/java/alluxio/hadoop/fs/AccumulatingReducer.java
Add javadoc for AccumulatingReducer#reduce
> [SMALLFIX] Add javadoc for AccumulatingReducer#reduce

- tests/src/test/java/alluxio/rest/TestCase.java
Add javadoc for the function of creatURL in class TestCase
> [SMALLFIX]Add javadoc for the function of creatURL in class TestCase

- tests/src/test/java/alluxio/rest/TestCase.java
Add javadoc for the function of getResponse() in class TestCase
> [SMALLFIX]Add javadoc for the function of getResponse() in class TestCase

- tests/src/test/java/alluxio/hadoop/FileSystemAclIntegrationTest.java
[SMALLFIX] Add javadoc for  FileSystemAclIntegrationTest#cleanup
> [SMALLFIX] Add javadoc for  FileSystemAclIntegrationTest#cleanup

- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- tests/src/test/java/alluxio/underfs/UnderStorageSystemInterfaceIntegrationTest.java
- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSInputStream.java
- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3InputStream.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
When reading an empty file, opening an existing file at pos = 0 would through an Exception.
> [SMALLFIX] Fix reading an empty file for some UFSs

- docs/en/Debugging-Guide.md
By Bin Fan request, i modified this, insert a chapter about java remote debug
> [DOCFIX]insert a chapter about java remote debug

- tests/src/test/java/alluxio/network/protocol/MessageSavingHandler.java
[SMALLFIX] Add javadoc for MessageSavingHandler#getMessage, MessageSavingHandler#reset
> [SMALLFIX] Add javadoc for MessageSavingHandler#getMessage, MessageSavingHandler#reset

- core/server/pom.xml
Clone of #4552 to 1.4
https://alluxio.atlassian.net/browse/ALLUXIO-2513
> [ALLUXIO-2513] Fix baseURL for rest api

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
Reverting some changes made in PR #4322.
> [SMALLFIX] Fix loadmetadata regression for a file that does not exist

- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
Our tests rely on being able to mock under file systems.
> [SMALLFIX] Make S3UnderFileSystem mockable.

- docs/en/Getting-Started.md
> [DOCFIX] Add a note to the quick start guide

- tests/pom.xml
Changes some of the default config to make object storage test profiles run more smoothly.
> [SMALLFIX] Object storage test fixes

- core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2465
> [ALLUXIO-2465]change call sequence for create and rename method

- docs/en/Getting-Started.md
A follow-up PR to https://github.com/Alluxio/alluxio/pull/4566#issuecomment-270758071 to update the style.
> [DOCFIX] Wrap the paragraph of 

- core/server/pom.xml
> [REVERT] Revert "[SMALLFIX] Reorder common and client in alluxio-core-server"

- integration/mesos/src/main/java/alluxio/mesos/AlluxioWorkerExecutor.java
Addressing comment in https://github.com/Alluxio/alluxio/pull/4524
> [SMALLFIX] Improve error handling in mesos worker executor

- assembly/pom.xml
- core/client/pom.xml
- core/common/pom.xml
- core/pom.xml
- core/server/pom.xml
- docs/_config.yml
- examples/pom.xml
- integration/fuse/pom.xml
- integration/mesos/pom.xml
- integration/pom.xml
- integration/yarn/pom.xml
- keyvalue/client/pom.xml
- keyvalue/common/pom.xml
- keyvalue/pom.xml
- keyvalue/server/pom.xml
- libexec/alluxio-config.sh
- minicluster/pom.xml
- pom.xml
- shell/pom.xml
- tests/pom.xml
- underfs/gcs/pom.xml
- underfs/glusterfs/pom.xml
- underfs/hdfs/pom.xml
- underfs/local/pom.xml
- underfs/oss/pom.xml
- underfs/pom.xml
- underfs/s3/pom.xml
- underfs/s3a/pom.xml
- underfs/swift/pom.xml
Update version to 1.4.0-RC3-PS
> [MERGE] Branch 1.4 to 1.4-ps

- tests/src/test/java/alluxio/worker/block/meta/SpecificTierWriteIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2404
> [ALLUXIO-2404] Add specific tier write integration tests

- core/client/src/test/java/alluxio/client/file/options/InStreamOptionsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2486
> [ALLUXIO-2486] Rename InStreamOptionsTest#defaultsTest()

- docs/cn/File-System-API.md
Update doc: docs/en/File-System-API.md of the Chinese version
> [DOCFIX] Update doc: docs/en/File-System-API.md of the Chinese version

- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2496
> [ALLUXIO-2496] Removing test suffix

- docs/cn/index.md
Update index.md of the Chinese version
> [DOCFIX] Update index.md of the Chinese version

- docs/_data/table/cn/user-configuration.yml
Update user-configuration.yml of the Chinese version
> [DOCFIX] Update user-configuration.yml of the Chinese version 

- docs/_data/table/cn/common-configuration.yml
The corresponding en doc counterpart:
> [DOCFIX]update docs/_data/table/cn/common-configuration.yml

- core/common/src/main/java/alluxio/Configuration.java
- core/common/src/main/java/alluxio/exception/PreconditionMessage.java
- core/common/src/main/java/alluxio/util/ConfigurationUtils.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/server/src/main/java/alluxio/proxy/AlluxioProxy.java
- core/server/src/main/java/alluxio/worker/AlluxioWorker.java
- shell/src/main/java/alluxio/cli/AlluxioShell.java
@calvinjia we probably want this in the release
> [SMALLFIX] Don't require master hostname when zookeeper is configured

- tests/src/test/java/alluxio/master/MasterTestUtils.java
Add javadoc for MasterTestUtils#createLeaderFileSystemMasterFromJournal
> [SMALLFIX] Add javadoc for MasterTestUtils#createLeaderFileSystemMasterFromJournal

- libexec/alluxio-config.sh
Reverts runtime breaking changes introduced by https://github.com/Alluxio/alluxio/pull/4591
> [SMALLFIX] Revert breaking changes.

- core/common/src/main/java/alluxio/underfs/options/FileLocationOptions.java
https://alluxio.atlassian.net/browse/ALLUXIO-2509
> [ALLUXIO-2509] Improve comment in FileLocationOptions

- core/server/src/main/java/alluxio/web/WebInterfaceGeneralServlet.java
- core/server/src/main/webapp/general.jsp
#Show inconsistent path list on WebUI
https://alluxio.atlassian.net/browse/ALLUXIO-2515
Normal
Error(inconsistent files)
> [ALLUXIO-2515]Show inconsistent path list on WebUI 

- README.md
- assembly/pom.xml
- core/client/pom.xml
- core/common/pom.xml
- core/pom.xml
- core/server/pom.xml
- docs/_config.yml
- examples/pom.xml
- integration/fuse/pom.xml
- integration/mesos/pom.xml
- integration/pom.xml
- integration/yarn/pom.xml
- keyvalue/client/pom.xml
- keyvalue/common/pom.xml
- keyvalue/pom.xml
- keyvalue/server/pom.xml
- libexec/alluxio-config.sh
- minicluster/pom.xml
- pom.xml
- shell/pom.xml
- tests/pom.xml
- underfs/gcs/pom.xml
- underfs/glusterfs/pom.xml
- underfs/hdfs/pom.xml
- underfs/local/pom.xml
- underfs/oss/pom.xml
- underfs/pom.xml
- underfs/s3/pom.xml
- underfs/s3a/pom.xml
- underfs/swift/pom.xml
Merges branch-1.4 and updates the version to 1.5.0-SNAPSHOT
> [MERGE] Update to 1.5.0-SNAPSHOT

- core/common/src/main/java/alluxio/underfs/UnderFileStatus.java
(https://alluxio.atlassian.net/browse/ALLUXIO-2508)
> [ALLUXIO-2508]Improve javadoc in UnderFileStatus

- core/server/src/main/java/alluxio/master/block/BlockMaster.java
(https://alluxio.atlassian.net/browse/ALLUXIO-2503)
Improve javadoc for getLostBlocks() in BlockMaster.java
> [ALLUXIO-2503]Improve javadoc for getLostBlocks() in BlockMaster.java

- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
(https://alluxio.atlassian.net/browse/ALLUXIO-2507)
Improve javadoc for ObjectUnderFileSystem
> [ALLUXIO-2507]modify javadoc ObjectUnderFileSystem

- docs/cn/Running-Spark-on-Alluxio.md
Fixed markdown format of a section header in the doc.
> [DOCFIX] minor format change of section header

- core/common/src/main/java/alluxio/wire/AlluxioProxyInfo.java
- core/common/src/test/java/alluxio/wire/AlluxioProxyInfoTest.java
- core/server/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
- core/server/src/main/java/alluxio/master/DefaultAlluxioMaster.java
- core/server/src/main/java/alluxio/proxy/AlluxioProxy.java
- core/server/src/main/java/alluxio/proxy/AlluxioProxyRestServiceHandler.java
- core/server/src/main/java/alluxio/proxy/AlluxioProxyService.java
- core/server/src/main/java/alluxio/proxy/DefaultAlluxioProxy.java
- core/server/src/main/java/alluxio/web/ProxyWebServer.java
- core/server/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
- core/server/src/main/java/alluxio/worker/AlluxioWorkerService.java
- core/server/src/main/java/alluxio/worker/DefaultAlluxioWorker.java
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
https://alluxio.atlassian.net/browse/ALLUXIO-2518
> [ALLUXIO-2518] Adding REST service for fetching proxy information

- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
Add javadoc for the function in class FileSystemMasterIntegrationTest.
> [SMALLFIX]Add javadoc for the functions in class FileSystemMasterIntegrationTest

- core/client/src/main/java/alluxio/client/lineage/AbstractLineageClient.java
changed my email for github account
> [SMALLFIX]correct a spell

- core/server/src/main/java/alluxio/master/AbstractMaster.java
- core/server/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
- core/server/src/main/java/alluxio/master/journal/JournalWriter.java
- tests/src/test/java/alluxio/master/JournalIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2526
Clone of #4679 to 1.4
> [ALLUXIO-2526] Do not expose EntryOutputStream

- core/common/src/main/java/alluxio/PropertyKey.java
- core/common/src/main/java/alluxio/retry/TimeoutRetry.java
- core/common/src/test/java/alluxio/retry/TimeoutRetryTest.java
- core/server/src/main/java/alluxio/master/AbstractMaster.java
- core/server/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
- core/server/src/test/java/alluxio/master/journal/AsyncJournalWriterTest.java
- docs/_data/table/en/master-configuration.yml
- docs/_data/table/master-configuration.csv
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
https://alluxio.atlassian.net/browse/ALLUXIO-2525
> [ALLUXIO-2525] Retry journal flushes

- keyvalue/client/src/main/java/alluxio/client/keyvalue/KeyValueMasterClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2523
> [SMALLFIX]fix a typo

- core/common/src/test/java/alluxio/wire/BlockInfoTest.java
Add javadoc for the functions in class BlockInfoTest
> [SMALLFIX]Add javadoc for the functions in class BlockInfoTest

- core/client/src/test/java/alluxio/hadoop/HadoopClientTestUtils.java
- tests/src/test/java/alluxio/hadoop/fs/DFSIOIntegrationTest.java
Add javadoc for HadoopClientTestUtils and DFSIOIntegrationTest
> [SMALLFIX] Add javadoc for HadoopClientTestUtils and DFSIOIntegrationTest

- core/client/src/main/java/alluxio/client/file/UnderFileSystemFileOutStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-2524
I have changed the email for my own github account!
> [SMALLFIX]fix a spell in UnderFileSystemFileOutStreamline 79

- core/client/src/main/java/alluxio/client/block/AlluxioBlockStore.java
https://alluxio.atlassian.net/browse/ALLUXIO-2536
> [ALLUXIO-2536] Choose random replica for nonlocal reads

- core/client/src/main/java/alluxio/client/file/UnderFileSystemFileOutStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-2524
> [ALLUXIO-2524] fixed typo in ALLUXIO-2524

- tests/src/test/java/alluxio/shell/command/SetTtlCommandTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2498
> [ALLUXIO-2498] Follow unit test naming convention for SetTtlCommandTest#setTtlNegativeTest()

- tests/src/test/java/alluxio/worker/block/meta/SpecificTierWriteIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2537
> [ALLUXIO-2537] Wait for files to be deleted for SpecificTierWriteIntegrationTest

- core/client/src/main/java/alluxio/client/block/AlluxioBlockStore.java
- core/client/src/main/java/alluxio/client/file/options/CreateDirectoryOptions.java
- core/client/src/main/java/alluxio/client/file/options/CreateFileOptions.java
- core/client/src/main/java/alluxio/client/file/options/DeleteOptions.java
- core/client/src/main/java/alluxio/client/file/options/ExistsOptions.java
- core/client/src/main/java/alluxio/client/file/options/FreeOptions.java
- core/client/src/main/java/alluxio/client/file/options/GetStatusOptions.java
- core/client/src/main/java/alluxio/client/file/options/ListStatusOptions.java
- core/client/src/main/java/alluxio/client/file/options/MountOptions.java
- core/client/src/main/java/alluxio/client/file/options/OpenFileOptions.java
- core/client/src/main/java/alluxio/client/file/options/RenameOptions.java
- core/client/src/main/java/alluxio/client/file/options/SetAttributeOptions.java
- core/client/src/main/java/alluxio/client/file/options/UnmountOptions.java
- core/common/src/main/java/alluxio/PropertyKey.java
- core/common/src/main/java/alluxio/retry/TimeoutRetry.java
- core/common/src/main/java/alluxio/security/authorization/Mode.java
- core/common/src/test/java/alluxio/retry/TimeoutRetryTest.java
- core/server/src/main/java/alluxio/master/AbstractMaster.java
- core/server/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
- core/server/src/main/java/alluxio/master/journal/JournalWriter.java
- core/server/src/test/java/alluxio/master/journal/AsyncJournalWriterTest.java
- docs/_data/table/en/master-configuration.yml
- docs/_data/table/master-configuration.csv
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- tests/src/test/java/alluxio/master/JournalIntegrationTest.java
- tests/src/test/java/alluxio/proxy/FileSystemClientRestApiTest.java
- tests/src/test/java/alluxio/rest/TestCase.java
> [MERGE] Merge branch-1.4 to master

- core/server/src/main/webapp/browse-body.jsp
- underfs/oss/pom.xml
add an input field to input the file path in browse page
> [SMALLFIX]add an input field in browse page

- core/common/src/main/java/alluxio/Configuration.java
https://alluxio.atlassian.net/browse/ALLUXIO-2539
> [ALLUXIO-2539] Fix incorrect warning message

- docs/en/Configuring-Alluxio-with-HDFS.md
Update doc about HDFS superuser requirement.
> [DOCFIX] Explain HDFS superuser is required to run Alluxio

- tests/src/test/java/alluxio/master/file/ConcurrentFileSystemMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2544
> [ALLUXIO-2544] Reduce timing requirement in ConcurrentFileSystemMasterTest

- bin/alluxio-mount.sh
- bin/alluxio-start.sh
- core/common/src/main/java/alluxio/Configuration.java
- core/common/src/main/java/alluxio/util/OSUtils.java
- libexec/alluxio-config.sh
> Revert "[ALLUXIO-2542] Enable customize top tier"

- bin/alluxio
- bin/alluxio-workers.sh
- Send format logs to stdout so that it won't silently fail
- Improve logging for what's happening on workers
> [SMALLFIX] Format usability improvements

- bin/alluxio-mount.sh
- shell/src/main/java/alluxio/cli/GetConf.java
- tests/src/test/java/alluxio/cli/GetConfTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2542
> [ALLUXIO-2542]  Fix failing mount

- tests/src/test/java/alluxio/master/MasterFaultToleranceIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2549
> [ALLUXIO-2549] Do not rely on timing for MasterFaultTolerance Test

- bin/alluxio
- examples/src/main/java/alluxio/cli/TestRunner.java
https://alluxio.atlassian.net/browse/ALLUXIO-2547
> [ALLUXIO-2547] Fix runTests to work in fault-tolerant mode

- docs/en/Running-Alluxio-On-Docker.md
- integration/docker/Dockerfile
- integration/docker/README.md
- integration/docker/entrypoint.sh
https://alluxio.atlassian.net/browse/ALLUXIO-2541
> [ALLUXIO-2541] Add Dockerfile

- core/common/src/test/java/alluxio/heartbeat/HeartbeatThreadTest.java
Add javadoc for HeartBeatThreadTest
> [SMALLFIX] Add javadoc for HeartBeatThreadTest

- assembly/pom.xml
This PR is needed to correctly build the assembly jar after the https://github.com/Alluxio/alluxio/pull/4726 refactoring
> [SMALLFIX] Fix assembly jar build.

- minicluster/pom.xml
- tests/pom.xml
> [SMALLFIX] Fixed the POM of mini-cluster

- integration/mesos/pom.xml
- integration/yarn/pom.xml
> [SMALLFIX] Fix pom in mesos and yarn integration

- docs/en/Integrating-Under-Storage-Systems.md
Of adding a new under file system
> [DOCFIX] Fix the broken links in docs

- core/common/src/test/java/alluxio/heartbeat/ManuallyScheduleHeartbeat.java
Add javadoc for ManuallyScheduleHeartbeat#Resource
> [SMALLFIX] Add javadoc for ManuallyScheduleHeartbeat#Resource

- docs/_data/table/en/ReadType.yml
https://alluxio.atlassian.net/browse/ALLUXIO-2531
> [ALLUXIO-2531] Update NO_CACHE description in file system API documentation

- tests/src/test/java/alluxio/security/MasterClientAuthenticationIntegrationTest.java
Add javadoc for MasterClientAuthenticationIntegrationTest#NameMatchAuthenticationProvider
> [SMALLFIX] Add javadoc for MasterClientAuthenticationIntegrationTest#NameMatchAuthenticationProvider

- core/common/src/main/java/alluxio/security/authentication/AuthenticatedClientUser.java
- core/server/master/src/test/java/alluxio/master/file/PermissionCheckTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2426
> [ALLUXIO-2426] Re-enable PermissionCheckerTest

- tests/src/test/java/alluxio/client/FileSystemIntegrationTest.java
- tests/src/test/java/alluxio/client/FileSystemUtilsIntegrationTest.java
- tests/src/test/java/alluxio/client/IsolatedFileSystemIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2484
> [ALLUXIO-2484] Remove unnecessary toString()

- docs/_data/table/en/worker-configuration.yml
https://alluxio.atlassian.net/browse/ALLUXIO-2529
> [ALLUXIO-2529] Update documentation of alluxio.worker.tieredstore.retry

- docs/_includes/File-System-API/read-file.md
https://alluxio.atlassian.net/browse/ALLUXIO-2530
> [ALLUXIO-2530] Update File System API example

- core/client/src/main/java/alluxio/client/block/AlluxioBlockStore.java
- core/client/src/main/java/alluxio/client/block/LocalBlockOutStream.java
- core/client/src/main/java/alluxio/client/block/stream/BlockInStream.java
- core/client/src/main/java/alluxio/client/block/stream/PacketOutStream.java
- core/client/src/main/java/alluxio/client/file/FileSystemContext.java
- core/client/src/main/java/alluxio/client/file/policy/LocalFirstAvoidEvictionPolicy.java
- core/client/src/main/java/alluxio/client/file/policy/LocalFirstPolicy.java
- core/client/src/main/java/alluxio/client/lineage/LineageContext.java
- core/common/src/main/java/alluxio/PropertyKey.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/common/src/test/java/alluxio/util/network/NetworkAddressUtilsTest.java
- docs/_data/table/en/user-configuration.yml
- docs/_data/table/user-configuration.csv
https://alluxio.atlassian.net/browse/ALLUXIO-2554
> [ALLUXIO-2554] Make client hostname configurable

- core/server/common/src/test/java/alluxio/master/journal/AsyncJournalWriterTest.java
Add javadoc for AsyncJournalWriterTest
> [SMALLFIX] Add javadoc for AsyncJournalWriterTest

- core/common/src/main/java/alluxio/Constants.java
Cleans up some unused constants.
> [SMALLFIX] Remove unused constants.

- docs/_data/table/cn/ReadType.yml
Update doc: docs/_data/table/en/ReadType.yml of the Chinese version
> [DOCFIX] Update doc: docs/_data/table/en/ReadType.yml of the Chinese version

- bin/alluxio-mount.sh
- docs/en/Running-Alluxio-Locally.md
https://alluxio.atlassian.net/browse/ALLUXIO-2548
> [ALLUXIO-2548] Mkdir also need sudo in alluxio-mount.sh

- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockWorkerClientServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/file/FileSystemWorkerClientServiceHandler.java
In the future, we can look into ways of refactoring this to have less boilerplate.
> [ALLUXIO-2564] Add entry/exit point debug info for important thrift interfaces

- core/client/src/main/java/alluxio/client/block/BlockMasterClient.java
- core/client/src/main/java/alluxio/client/block/BlockMasterClientPool.java
- core/client/src/main/java/alluxio/client/block/BlockWorkerClient.java
- core/client/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java
- core/client/src/main/java/alluxio/client/block/RetryHandlingBlockWorkerClient.java
- core/client/src/main/java/alluxio/client/file/FileInStream.java
- core/client/src/main/java/alluxio/client/file/FileSystemContext.java
- core/client/src/main/java/alluxio/client/file/FileSystemMasterClient.java
- core/client/src/main/java/alluxio/client/file/FileSystemMasterClientPool.java
- core/client/src/main/java/alluxio/client/file/FileSystemWorkerClient.java
- core/client/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
- core/client/src/main/java/alluxio/client/file/RetryHandlingFileSystemWorkerClient.java
- core/client/src/test/java/alluxio/client/block/BlockWorkerClientTestUtils.java
- core/client/src/test/java/alluxio/client/file/FileSystemWorkerClientTestUtils.java
- core/client/src/test/java/alluxio/client/lineage/LineageFileOutStreamTest.java
- core/client/src/test/java/alluxio/client/lineage/LineageFileSystemTest.java
- core/common/src/main/java/alluxio/AbstractClient.java
- core/common/src/main/java/alluxio/AbstractMasterClient.java
- core/common/src/main/java/alluxio/Client.java
- core/common/src/main/java/alluxio/MasterClient.java
- examples/src/main/java/alluxio/cli/AlluxioFrameworkIntegrationTest.java
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- tests/src/test/java/alluxio/IntegrationTestUtils.java
- tests/src/test/java/alluxio/master/FileSystemMasterClientIntegrationTest.java
- tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java
- tests/src/test/java/alluxio/master/ServiceSocketBindIntegrationTest.java
- tests/src/test/java/alluxio/master/lineage/LineageMasterIntegrationTest.java
- tests/src/test/java/alluxio/security/MasterClientAuthenticationIntegrationTest.java
- tests/src/test/java/alluxio/worker/BlockServiceHandlerIntegrationTest.java
- tests/src/test/java/alluxio/worker/DataServerIntegrationTest.java
- adds interfaces for file system master and worker client and moves the implementation to `RetryHandlingFileSystem{Master|Worker}Client`.
- adds factories for the interfaces
- removes exceptions from constructors of retry handling clients
> [SMALLFIX] Improving style of client code

- core/client/src/test/java/alluxio/client/file/options/OutStreamOptionsTest.java
- core/common/src/test/java/alluxio/ConfigurationRule.java
- core/common/src/test/java/alluxio/SetAndRestoreConfiguration.java
- core/common/src/test/java/alluxio/security/LoginUserTestUtils.java
- core/server/master/src/test/java/alluxio/master/file/PermissionCheckTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2426
filesystemmaster and blockmaster are started for each testcase, but not stopped. This may or may not be the root cause of ALLUXIO-2426, but still a good fix to have.
> [ALLUXIO-2426] Attempt to deflake PermissionCheckTest

- core/server/common/src/main/java/alluxio/RpcUtils.java
- core/server/master/src/main/java/alluxio/master/block/BlockMasterClientServiceHandler.java
- core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterWorkerServiceHandler.java
- core/server/master/src/main/java/alluxio/master/lineage/LineageMasterClientServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockWorkerClientServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/file/FileSystemWorkerClientServiceHandler.java
- keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMasterClientServiceHandler.java
- keyvalue/server/src/main/java/alluxio/worker/keyvalue/KeyValueWorkerClientServiceHandler.java
Follow up to #4798 which makes the logging more failure resilient.
> [ALLUXIO-2564] Improve entry/exit debug logging

- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
- core/server/worker/src/main/java/alluxio/worker/file/FileSystemWorkerClientServiceHandler.java
> [ALLUXIO-2564] Clean up service handler logging.

- core/client/src/main/java/alluxio/client/file/FileInStream.java
> [SMALLFIX] Minor fix.

- core/server/common/src/main/java/alluxio/master/AbstractMaster.java
Add javadoc for AbstractMaster#appendJournalEntry
> [SMALLFIX] Add javadoc for AbstractMaster#appendJournalEntry

- core/server/worker/src/main/java/alluxio/worker/netty/DataServerHandler.java
> [ALLUXIO-2564] Add enter/exit logging for Data Server Handlers

- core/common/src/main/java/alluxio/underfs/UnderFileSystemRegistry.java
- core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
> [ALLUXIO-2564] Add entry/exit point logging for UFS operations

- core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
- core/server/common/src/main/java/alluxio/RpcUtils.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-2574
> [ALLUXIO-2574] Decouple Control Flow from Exception Logging

- docs/en/Logging-Conventions.md
https://alluxio.atlassian.net/browse/ALLUXIO-2578
> [ALLUXIO-2578] Add documentation for logging conventions.

- integration/docker/.dockerignore
- integration/docker/Dockerfile
- integration/docker/README.md
- integration/docker/conf/.gitignore
https://alluxio.atlassian.net/browse/ALLUXIO-2575
> [ALLUXIO-2575] Add support for including conf files in docker build

- tests/src/test/java/alluxio/IntegrationTestUtils.java
- tests/src/test/java/alluxio/IntegrationTestUtilsTest.java
- tests/src/test/java/alluxio/client/PersistMultipleMountsIntegrationTest.java
- tests/src/test/java/alluxio/client/PersistPermissionIntegrationTest.java
- tests/src/test/java/alluxio/hadoop/FileSystemAclIntegrationTest.java
- tests/src/test/java/alluxio/shell/command/PersistCommandTest.java
- tests/src/test/java/alluxio/underfs/UnderStorageSystemInterfaceIntegrationTest.java
Using instanceof is no longer valid due to the Ufs w/ Logging decorator
> [SMALLFIX] Fix ufs instance of

- tests/src/test/java/alluxio/IntegrationTestUtilsTest.java
> [SMALLFIX] Fix checkstyle.

- core/common/src/main/java/alluxio/util/UnderFileSystemUtils.java
- tests/src/test/java/alluxio/IntegrationTestUtils.java
- tests/src/test/java/alluxio/client/PersistMultipleMountsIntegrationTest.java
- tests/src/test/java/alluxio/client/PersistPermissionIntegrationTest.java
- tests/src/test/java/alluxio/hadoop/FileSystemAclIntegrationTest.java
- tests/src/test/java/alluxio/shell/command/PersistCommandTest.java
- tests/src/test/java/alluxio/underfs/UnderStorageSystemInterfaceIntegrationTest.java
- tests/src/test/java/alluxio/util/UnderFileSystemUtilsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2580
> [ALLUXIO-2580] Migrate Is*UFS methods to UnderFileSystemUtils

- docs/en/FAQ.md
> [DOCFIX] Updating the FAQ.md of the English Version

- core/server/common/src/test/java/alluxio/master/journal/AbstractJournalFormatterTest.java
Add javadoc for AbstractJournalFormatterTest
> [SMALLFIX] Add javadoc for AbstractJournalFormatterTest

- docs/cn/Contributing-to-Alluxio.md
Update Google java style guide link
> [DOCFIX] Update doc: docs/en/Contributing-to-Alluxio.md of the Chinese version

- core/common/src/main/java/alluxio/security/authentication/TransportProviderUtils.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
> [SMALLFIX] Use specified hostname instead of FQDN

- core/client/src/main/java/alluxio/client/block/RetryHandlingBlockWorkerClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2609
> [ALLUXIO-2609] Deprecate Throwables.propagate with RuntimeException in RetryHandlingBlockWorkerClient.java

- tests/src/test/java/alluxio/shell/AbstractAlluxioShellTest.java
Add javadoc for AbstractAlluxioShellTest
> [SMALLFIX] Add javadoc for AbstractAlluxioShellTest

- core/common/src/test/java/alluxio/security/authentication/PlainSaslServerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2630
> [ALLUXIO-2630] Make PlainSaslServerTest final

- core/common/src/test/java/alluxio/util/SecurityUtilsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2625
P.S. really sry for the trouble i made
> [ALLUXIO-2625]Make SecurityUtilsTest final

- tests/src/test/java/alluxio/hadoop/fs/DFSIOIntegrationTest.java
Add javadoc for DFSIOIntegrationTest#ByteMultiple
> [SMALLFIX] Add javadoc for DFSIOIntegrationTest#ByteMultiple

- tests/src/test/java/alluxio/collections/IndexedSetConcurrencyTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2494?filter=-1
> [ALLUXIO-2494] remove Test in nonUniqueConcurrentUpdateTest

- tests/src/test/java/alluxio/master/JournalIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2497
Renamed JournalIntegrationTest#mountEntryCheckpointTest() to JournalIntegrationTest#mountEntryCheckpoint()
> [ALLUXIO-2497] Renamed JournalIntegrationTest#mountEntryCheckpointTest()

- docs/en/Configuring-Alluxio-with-NFS.md
https://alluxio.atlassian.net/browse/ALLUXIO-2474?jql=project%20%3D%20ALLUXIO%20AND%20status%20%3D%20Open%20AND%20labels%20%3D%20NewContributor%20AND%20assignee%20in%20(EMPTY)
Change
"""This guide describes how to configure Alluxio with NFS as the under storage system."""
to be
"""This guide describes the instructions to configure NFS as Alluxio's under storage system."""
> [ALLUXIO-2474] Configuring-Alluxio-with-NFS.md doc improvement

- core/client/src/test/java/alluxio/client/file/options/CreateDirectoryOptionsTest.java
- core/server/master/src/test/java/alluxio/master/file/options/CreateDirectoryOptionsTest.java
[https://alluxio.atlassian.net/browse/ALLUXIO-2596](url)
> [ALLUXIO-2596]Make CreateDirectoryOptionsTest final

- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2495
> [ALLUXIO-2495] Delete Test suffix in test name

- docs/pt/Running-Spark-on-Alluxio.md
https://alluxio.atlassian.net/browse/ALLUXIO-2378
Ticket 2378
> [ALLUXIO-2378] replace spark/conf/spark-env.sh

- core/client/src/main/java/alluxio/client/block/stream/PacketOutStream.java
JIRA ticket: https://alluxio.atlassian.net/browse/ALLUXIO-2499?jql=project%20%3D%20ALLUXIO%20AND%20status%20%3D%20Open%20AND%20labels%20%3D%20NewContributor%20AND%20assignee%20in%20(EMPTY)
Replaced "Release" with "Releases" in the Javadoc for releaseCurrentPacket() in PacketOutStream.java
> [ALLUXIO-2499] Update Javadoc for releaseCurrentPacket() in PacketOutStream.java

- README.md
- core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
https://alluxio.atlassian.net/browse/ALLUXIO-2618
> [ALLUXIO-2618] Include units in variable name in AsyncJournalWriter

- tests/src/test/java/alluxio/hadoop/fs/DFSIOIntegrationTest.java
Add javadoc for DFSIOIntegrationTest#TestType
> [SMALLFIX] Add javadoc for DFSIOIntegrationTest#TestType

- core/client/src/test/java/alluxio/client/file/options/SetAttributeOptionsTest.java
- core/server/master/src/test/java/alluxio/master/file/options/SetAttributeOptionsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2603
> [ALLUXIO-2603] Make SetAttributeOptionsTest final

- core/client/src/test/java/alluxio/client/file/options/LoadMetadataOptionsTest.java
- core/server/master/src/test/java/alluxio/master/file/options/LoadMetadataOptionsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2600
> [ALLUXIO-2600]Make LoadMetadataOptionsTest final

- docs/en/Debugging-Guide.md
Update the method how to go to debug mode.
> [DOCFIX] update for debugging guide

- docs/en/Running-Alluxio-Locally.md
For users running on MacOS, sudo privileges are not required as mount in MacOS doesn't require sudo
> [DOCFIX] Update Running-Alluxio-Locally.md

- core/common/src/main/java/alluxio/util/URIUtils.java
- core/common/src/test/java/alluxio/AlluxioTestDirectory.java
- core/server/common/src/main/java/alluxio/cli/Format.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
- integration/mesos/src/main/java/alluxio/mesos/AlluxioMasterExecutor.java
- integration/mesos/src/main/java/alluxio/mesos/AlluxioWorkerExecutor.java
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- minicluster/src/main/java/alluxio/underfs/UnderFileSystemCluster.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
Fixes a bug introduced by https://github.com/Alluxio/alluxio/pull/4862/files (`URIUtils#appendPath` would discard the port). This should fix the HDFS build.
This PR also includes minor cleanup of logging (following our logging style guideline).
> [SMALLFIX] Fixing bug in URIUtils and other minor cleanup.

- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalReader.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalTailer.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalWriter.java
- tests/src/test/java/alluxio/master/UfsJournalIntegrationTest.java
Fixes a bug in `UfsJournalReader` introduced by https://github.com/Alluxio/alluxio/pull/4862 and performs minor cleanup.
> [SMALLFIX] Fix a bug in the UFS journal reader.

- core/common/src/test/java/alluxio/security/login/LoginModuleTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2628
add final keyword to LoginModuleTest class
> [ALLUXIO-2628] add final keyword to LoginModuleTest

- core/common/src/test/java/alluxio/security/authentication/PlainSaslServerCallbackHandlerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2629
add final keyword to PlainSaslServerCallbackHandlerTest class
> [ALLUXIO-2629] add final to PlainSaslServerCallbackHandlerTest

- core/common/src/test/java/alluxio/util/WaitForOptionsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2627
add final keyword to WaitForOptionsTest class
> [ALLUXIO-2627] add final keyword to  WaitForOptionsTest class

- core/common/src/test/java/alluxio/security/authentication/SimpleAuthenticationProviderTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2631
add final keyword to SimpleAuthenticationProviderTest class
> [ALLUXIO-2631] add final to SimpleAuthenticationProviderTest

- core/common/src/main/java/alluxio/Configuration.java
https://alluxio.atlassian.net/browse/ALLUXIO-2594
Replace
LOG.error("Unsupported property " + propertyName);
with
LOG.warn("Unsupported property {}", propertyName);
> [ALLUXIO-2594] fix logging style in Configuration

- shell/src/main/java/alluxio/shell/command/LoadCommand.java
https://alluxio.atlassian.net/browse/ALLUXIO-2617
Fix javadoc grammer in LoadCommand.java
> [ALLUXIO-2617] Fix javadoc grammer in LoadCommand.java

- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
[https://alluxio.atlassian.net/browse/ALLUXIO-2585](https://alluxio.atlassian.net/browse/ALLUXIO-2585)
---
To minimize merge conflicts, sort alphabetically in each section.
> [ALLUXIO-2585] Clarify javadoc in ExceptionMessage

- core/client/src/test/java/alluxio/client/file/options/CreateFileOptionsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2597
> [ALLUXIO-2597]Make CreateFileOptionsTest final

- core/client/src/test/java/alluxio/client/file/options/DeleteOptionsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2598
make DeleteOptionsTest final
To avoid accidental subclass extension
>  [ALLUXIO-2598]Make DeleteOptionsTest final

- docs/cn/Running-Alluxio-On-Docker.md
Update doc: docs/en/Running-Alluxio-On-Docker.md of Chinese version
> [DOCFIX] Update doc: docs/en/Running-Alluxio-On-Docker.md of Chinese version

- core/common/src/main/java/alluxio/AbstractClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2604
> [ALLUXIO-2604] Deprecate Throwables.propagate with RuntimeException in AbstractClient.java

- core/common/src/test/java/alluxio/metrics/MetricsSystemTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2489
Update MetricsSystemTest to follow unit test naming convention.
> [ALLUXIO-2489] Update MetricsSystemTest to follow style guide

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystemFactory.java
[getaddress](https://alluxio.atlassian.net/browse/ALLUXIO-2344)
> [ALLUXIO-2344]Improve error handling in SwiftUnderFileFactory#Improvement

- core/common/src/main/java/alluxio/exception/DependencyDoesNotExistException.java
https://alluxio.atlassian.net/browse/ALLUXIO-2584
Fix the typo in the word exception on line 17.
> [ALLUXIO-2584] Fix the typo in the word exception on line 17.

- docs/en/Running-HBase-on-Alluxio.md
https://alluxio.atlassian.net/browse/ALLUXIO-2610
> [ALLUXIO-2610] Fix grammar in Running HBase doc intro

- core/client/src/main/java/alluxio/client/file/FileSystemContext.java
https://alluxio.atlassian.net/browse/ALLUXIO-2614
> [ALLUXIO-2614] Deprecate Throwables.propagate with RuntimeException in FileSystemContext.java

- core/server/common/src/main/java/alluxio/web/WebInterfaceBrowseLogsServlet.java
https://alluxio.atlassian.net/browse/ALLUXIO-2479
> [ALLUXIO-2479] Improve comment style in WebInterfaceBrowseLogsServlet

- core/common/src/test/java/alluxio/resource/ResourcePoolTest.java
add javadoc to ResourcePoolTest#TestResourcePool
> [SMALLFIX]Add javadoc for the class of TestResourcePool in ResourcePoolTest.java

- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2607 
replace "than" with "the"
> [ALLUXIO-2607]Fix error message in MetricsSystem.java

- tests/src/test/java/alluxio/master/file/ConcurrentFileSystemMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2688
> [ALLUXIO-2688] Add a test for concurrent renaming.

- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-2687
Fix log style NetworkAddressUtils
> [ALLUXIO-2687] Fix log style NetworkAddressUtils

- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
- core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/Inode.java
- tests/src/test/java/alluxio/master/file/ConcurrentFileSystemMasterTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2654
> [ALLUXIO-2654] Enable concurrent deletes in the same directory

- core/common/src/main/java/alluxio/util/io/BufferUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-2686
> [ALLUXIO-2686]fix BufferUtils log style

- core/common/src/test/java/alluxio/metrics/MetricsConfigTest.java
Modified the function name in MetricsConfigTest.java to unit test standard
> [SMALLFIX]Change Function name

- core/server/worker/src/main/java/alluxio/worker/block/evictor/LRFUEvictor.java
ALLUXIO-2620
https://alluxio.atlassian.net/browse/ALLUXIO-2620
> [ALLUXIO-2620] Fix comment style LRUEvictor.java

- shell/src/main/java/alluxio/cli/AlluxioShell.java
[https://alluxio.atlassian.net/browse/ALLUXIO-2326]()
Update the javadoc for #printUsage from
*         Method which prints the method to use all the commands.
to
*         Prints usage for all shell commands.
> [ALLUXIO-2326] Fix javadoc in AlluxioShell

- core/server/master/src/main/java/alluxio/master/file/meta/TempInodePathForDescendant.java
https://alluxio.atlassian.net/browse/ALLUXIO-2365
> [ALLUXIO-2365] Parameterize the returned type Inode in TempInodePathForDescendant.getInode

- core/common/src/test/java/alluxio/metrics/MetricsConfigTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2487
> [ALLUXIO-2487] Follow unit test naming convention for MetricsConfigTest#setPropertiesTest()

- tests/src/test/java/alluxio/master/file/ConcurrentFileSystemMasterTest.java
> [SMALLFIX] Fix test errors for profile hadoop*

- core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client/src/main/java/alluxio/hadoop/HdfsFileInputStream.java
- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
- tests/src/test/java/alluxio/hadoop/HdfsFileInputStreamIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2647
> [ALLUXIO-2647] Clean up HdfsFileInputStream

- docs/_data/table/cn/ReadType.yml
the `*` cannot display bold text in web page.
> [DOCFIX]`*` cannot display bold text in web page

- tests/src/test/java/alluxio/hadoop/fs/DFSIOIntegrationTest.java
Add javadoc for DFSIOIntegrationTest#main
> [SMALLFIX] Add javadoc for DFSIOIntegrationTest#main

- core/client/src/main/java/alluxio/client/block/stream/NettyPacketReader.java
- core/client/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java
- core/common/src/main/java/alluxio/network/protocol/RPCProtoMessage.java
- core/common/src/main/java/alluxio/network/protocol/Status.java
- core/common/src/main/java/alluxio/util/network/NettyUtils.java
- core/protobuf/src/main/java/alluxio/proto/dataserver/Protocol.java
- core/protobuf/src/proto/dataserver/protocol.proto
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerBlockReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerBlockWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerUFSFileReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerUFSFileWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerUfsBlockReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerWriteHandler.java
- core/server/worker/src/test/java/alluxio/worker/netty/DataServerBlockWriteHandlerTest.java
- core/server/worker/src/test/java/alluxio/worker/netty/DataServerReadHandlerTest.java
- core/server/worker/src/test/java/alluxio/worker/netty/DataServerUFSFileWriteHandlerTest.java
- core/server/worker/src/test/java/alluxio/worker/netty/DataServerWriteHandlerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2642
1. Add better cancel support in DataServerWriteHandler. 
2. Improve threading models in DataServer{Read/Writer}Handler and NettyPacket{Reader,Writer}. This PR defines the invariants more clearly.
> [ALLUXIO-2642] Support cancel in netty packet writer

- core/server/common/src/main/java/alluxio/master/journalv0/AsyncJournalWriter.java
- core/server/common/src/main/java/alluxio/master/journalv0/Journal.java
- core/server/common/src/main/java/alluxio/master/journalv0/JournalCheckpointStreamable.java
- core/server/common/src/main/java/alluxio/master/journalv0/JournalEntryRepresentable.java
- core/server/common/src/main/java/alluxio/master/journalv0/JournalFactory.java
- core/server/common/src/main/java/alluxio/master/journalv0/JournalFormatter.java
- core/server/common/src/main/java/alluxio/master/journalv0/JournalInputStream.java
- core/server/common/src/main/java/alluxio/master/journalv0/JournalOutputStream.java
- core/server/common/src/main/java/alluxio/master/journalv0/JournalReader.java
- core/server/common/src/main/java/alluxio/master/journalv0/JournalTool.java
- core/server/common/src/main/java/alluxio/master/journalv0/JournalWriter.java
- core/server/common/src/main/java/alluxio/master/journalv0/MutableJournal.java
- core/server/common/src/main/java/alluxio/master/journalv0/ProtoBufJournalFormatter.java
- core/server/common/src/main/java/alluxio/master/journalv0/ufs/UfsCheckpointManager.java
- core/server/common/src/main/java/alluxio/master/journalv0/ufs/UfsJournal.java
- core/server/common/src/main/java/alluxio/master/journalv0/ufs/UfsJournalReader.java
- core/server/common/src/main/java/alluxio/master/journalv0/ufs/UfsJournalWriter.java
- core/server/common/src/main/java/alluxio/master/journalv0/ufs/UfsMutableJournal.java
https://alluxio.atlassian.net/browse/ALLUXIO-2689
Backup the current journal implementation so that we can write tool to convert journal between versions.
> [ALLUXIO-2689] Backup the current journal implementation to journalv0

- docs/cn/index.md
Update doc: docs/en/index.md of Chinese version
> [DOCFIX] Update doc: docs/en/index.md of Chinese version

- core/client/src/test/java/alluxio/client/file/options/CompleteFileOptionsTest.java
- core/server/master/src/test/java/alluxio/master/file/options/CompleteFileOptionsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2595
> [ALLUXIO-2595]To avoid accidental subclass extension

- core/client/src/test/java/alluxio/client/file/options/RenameOptionsTest.java
- core/server/master/src/test/java/alluxio/master/file/options/RenameOptionsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2602
Make RenameOptionsTest final to avoid accidental subclass extension.
> [ALLUXIO-2602]Make RenameOptionsTest final to avoid accidental subclass extension.

- core/common/src/test/java/alluxio/client/file/URIStatusTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2655
Make URIStatusTest final
> [ALLUXIO-2655] Make URIStatusTest final

- core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
https://alluxio.atlassian.net/browse/ALLUXIO-2671
replace T with R.
> [ALLUXIO-2671] Fix type shadowing in DynamicResourcePool -- use a different letter 

- core/client/src/main/java/alluxio/client/block/StreamFactory.java
- core/client/src/main/java/alluxio/client/file/FileInStream.java
- core/client/src/main/java/alluxio/client/file/UnderFileSystemFileOutStream.java
- core/client/src/main/java/alluxio/client/netty/NettyClient.java
- core/client/src/main/java/alluxio/hadoop/HdfsFileInputStream.java
- core/client/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/en/user-configuration.yml
- docs/_data/table/user-configuration.csv
https://alluxio.atlassian.net/browse/ALLUXIO-2744
This PR handles the switches in our code. A follow up PR will be made to clean up unused classes.
> [ALLUXIO-2744] Use Packet Streaming Only

- core/common/src/test/java/alluxio/collections/PairTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2657
> [ALLUXIO-2657] Make PairTest final

- core/server/worker/src/main/java/alluxio/worker/block/PinListSync.java
https://alluxio.atlassian.net/browse/ALLUXIO-2681
Fix logging style
> [ALLUXIO-2681] Fix logging style in PinListSync

- core/server/proxy/src/test/java/alluxio/StreamCacheTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2726
> [ALLUXIO-2726]Make StreamCacheTest final

- core/common/src/test/java/alluxio/security/authentication/CustomAuthenticationProviderTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2662
> [ALLUXIO-2662]Make CustomAuthenticationProviderTest final

- core/server/worker/src/test/java/alluxio/worker/block/allocator/GreedyAllocatorTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2734
Mark class GreedyAllocatorTest as a final class
> [ALLUXIO-2734] Mark class GreedyAllocatorTest as a final class

- core/server/common/src/test/java/alluxio/StorageTierAssocTest.java
[https://alluxio.atlassian.net/browse/ALLUXIO-2723](url)
> [ALLUXIO-2723]Make StorageTierAssocTest final

- core/common/src/main/java/alluxio/worker/DataServerMessage.java
https://alluxio.atlassian.net/browse/ALLUXIO-2714
> [ALLUXIO-2714] Specify null variable in DataServerMessage.java precondition check

- core/client/src/main/java/alluxio/client/block/stream/NettyPacketReader.java
- core/client/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java
- core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerWriteHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-2463
> [ALLUXIO-2463] Replace try-finally with try-with-resource for locks

- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/en/common-configuration.yml
- docs/en/Configuring-Alluxio-with-S3.md
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2805
> [ALLUXIO-2805] Support S3 providers which only support v2 signatures

- core/client/src/main/java/alluxio/client/block/AlluxioBlockStore.java
- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
https://alluxio.atlassian.net/browse/ALLUXIO-2576
@aaudiber  PTAL,  which test will generate this issue?
> [ALLUXIO-2576] Fix misleading error msg

- core/server/worker/src/main/java/alluxio/worker/file/FileDataManager.java
https://alluxio.atlassian.net/browse/ALLUXIO-2682
> [ALLUXIO-2682]Fix logging style in FileDataManager

- core/common/src/main/java/alluxio/AbstractThriftClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2593
Replace all occurrences of
LOG.error("Failed after " + retryPolicy.getRetryCount() + " retries.");
with
LOG.error("Failed after {} retries.", retryPolicy.getRetryCount());
> [ALLUXIO-2593] Fix logging style in AbstractThriftClient 

- core/server/worker/src/main/java/alluxio/worker/block/evictor/LRFUEvictor.java
https://alluxio.atlassian.net/browse/ALLUXIO-2621
> [ALLUXIO-2621]Fix comment style in LRFUEvictor.java (line 53)

- core/common/src/test/java/alluxio/security/authentication/PlainSaslServerCallbackHandlerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2629
make PlainSaslServerCallbackHandlerTest final
> [ALLUXIO-2629]make PlainSaslServerCallbackHandlerTest final

- core/server/worker/src/test/java/alluxio/worker/block/BlockStoreMetaTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2728
To avoid accidental extension.
> [ALLUXIO-2728] Make BlockStoreMetaTest final

- bin/alluxio
- examples/src/main/java/alluxio/cli/MiniBenchmark.java
https://alluxio.atlassian.net/browse/ALLUXIO-2739
> [ALLUXIO-2739] Fix "runMiniBentchmark" command to respect master addr set in Configuration 

- core/common/src/main/java/alluxio/util/ConfigurationUtils.java
JIRA ticket: https://alluxio.atlassian.net/browse/ALLUXIO-2683
Comments which start with capital letters should end with periods.
> [ALLUXIO-2683] Improve comment sytle in ConfigurationUtils

- core/common/src/test/java/alluxio/resource/LockResourceTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2660
make LockResourceTest avoid extend
> [ALLUXIO-2660]make LockResourceTest final

- examples/src/main/java/alluxio/cli/AlluxioFrameworkIntegrationTest.java
Replace the word and Remove the import com.google.common.base.Throwables;.
> [ALLUXIO-­2716] Replace and Remove

- core/server/common/src/test/java/alluxio/master/MasterRegistryTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2722
> [ALLUXIO-2722] Make MasterRegistryTest final

- core/common/src/main/java/alluxio/AbstractClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2695
Specify null variable in AbstractClient.java precondition check
>  [ALLUXIO-2695] Specify null variable in AbstractClient.java precondition check

- docs/cn/Configuring-Alluxio-with-S3.md
update docs/cn/Configuring-Alluxio-with-S3.md, sync with docs/en/Configuring-Alluxio-with-S3.md
> [DOCFIX] update docs/cn/Configuring-Alluxio-with-S3.md

- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTestUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-2731
> [ALLUXIO-2731] Make TieredBlockStoreTestUtils final

- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
Add javadoc for FileSystemMasterIntegrationTest#ConcurrentFreer#exec
> [SMALLFIX] Add javadoc for FileSystemMasterIntegrationTest#ConcurrentFreer#exec

- core/server/worker/src/main/java/alluxio/worker/block/evictor/LRFUEvictor.java
https://alluxio.atlassian.net/browse/ALLUXIO-2623
>  [ALLUXIO-2623]Fix comment style in LRUEvictor.java (line 57) 

- core/common/src/main/java/alluxio/util/ConfigurationUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-2677
> [ALLUXIO-2677] Fix logging style in ConfigurationUtils

- core/common/src/main/java/alluxio/wire/BlockLocation.java
https://alluxio.atlassian.net/browse/ALLUXIO-2707
> [ALLUXIO-2707]Specify null variable in BlockLocation.java precondition check

- LICENSE
Change copyright to 2017 from 2016
> [DOCFIX] Update LICENSE

- core/common/src/test/java/alluxio/wire/CommandLineJobInfoTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2753
Make CommandLineJobInfoTest final
> [ALLUXIO-2753]Make CommandLineJobInfoTest final

- core/common/src/main/java/alluxio/network/protocol/databuffer/DataByteBuffer.java
https://alluxio.atlassian.net/browse/ALLUXIO-2701
Specify null variable in DataByteBuffer.java precondition check
> [ALLUXIO-2701] Specify null variable in DataByteBuffer.java precondition check

- core/server/master/src/test/java/alluxio/master/AlluxioMasterRestServiceHandlerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2724
Make AlluxioMasterRestServiceHandlerTest final
> [ALLUXIO-2724] Make AlluxioMasterRestServiceHandlerTest final

- core/common/src/main/java/alluxio/wire/FileBlockInfo.java
[ALLUXIO-2709](https://alluxio.atlassian.net/browse/ALLUXIO-2709)
Specify null variable in FileBlockInfo.java precondition check(Located at Line 87 and 106)
> [ALLUXIO-2709] Specify null variable in FileBlockInfo.java precondition check

- core/common/src/main/java/alluxio/resource/ResourcePool.java
https://alluxio.atlassian.net/browse/ALLUXIO-2812
> [ALLUXIO-2812] Fix some logical problems in ResourcePool

- core/common/src/test/java/alluxio/heartbeat/HeartbeatContextTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2659
> [ALLUXIO-2659] Make HeartbeatContextTest final

- core/client/src/test/java/alluxio/client/block/policy/options/CreateOptionsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2806
> [ALLUXIO-2806] Add unit tests for block policy CreateOptions.

- docs/en/Running-HBase-on-Alluxio.md
https://alluxio.atlassian.net/browse/ALLUXIO-2613
[ALLUXIO­2613] Fix grammar in Running HBase Prerequisites
>  [ALLUXIO-2613] Fix grammar in Running HBase Prerequisites

- tests/src/test/java/alluxio/master/MockMaster.java
- tests/src/test/java/alluxio/master/journal/options/JournalReaderOptionsTest.java
- tests/src/test/java/alluxio/master/journal/options/JournalWriterOptionsTest.java
- tests/src/test/java/alluxio/master/journal/ufs/JournalCheckpointThreadTest.java
- tests/src/test/java/alluxio/master/journal/ufs/UfsJournalCheckpointWriterTest.java
- tests/src/test/java/alluxio/master/journal/ufs/UfsJournalFileTest.java
- tests/src/test/java/alluxio/master/journal/ufs/UfsJournalIntegrationTest.java
- tests/src/test/java/alluxio/master/journal/ufs/UfsJournalLogWriterTest.java
- tests/src/test/java/alluxio/master/journal/ufs/UfsJournalReaderTest.java
- tests/src/test/java/alluxio/master/journal/ufs/UfsJournalSnapshotTest.java
- tests/src/test/java/alluxio/master/journal/ufs/UfsJournalTest.java
PR2: Unittests, integration tests
Full PR: #5019
> [ALLUXIO-2689] New journal to improve master's availability [PR2]

- core/server/worker/src/main/java/alluxio/worker/block/allocator/Allocator.java
https://alluxio.atlassian.net/browse/ALLUXIO-2715
Deprecate Throwables.propagate with RuntimeException
> [ALLUXIO-2715] Deprecate Throwables.propagate with RuntimeException in Allocator.java

- core/client/src/main/java/alluxio/client/file/FileOutStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-2693
> [ALLUXIO-2693]Specify null variable in FileOutStream.java precondition check

- core/common/src/main/java/alluxio/wire/BlockInfo.java
[ALLUXIO-2793](https://alluxio.atlassian.net/browse/ALLUXIO-2793)
`mLocations = new ArrayList<>(Preconditions.checkNotNull(locations));`
> [ALLUXIO-2793]  Use precondition check chaining in BlockInfo

- docs/_data/table/cn/common-configuration.yml
Add Chinese Doc for alluxio.underfs.s3a.signer.algorithm in common configuration.
> [DOCFIX]Add Chinese Doc of S3SignerType for common-configuration

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
> [SMALLFIX] Remove extra new line.

- core/common/src/main/java/alluxio/wire/LineageInfo.java
https://alluxio.atlassian.net/browse/ALLUXIO-2712
Replace Preconditions.checkNotNull(inputFiles) with Preconditions.checkNotNull(inputFiles,"inputFiles")
> [ALLUXIO-2712] Specify null variable in LineageInfo.java precondition check

- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
javadoc:FileSystemMasterIntegrationTest#ConcurrentCreateDelete#ConcurrentCreateDelete
> [SMALLFIX] Add javadoc to FileSystemMasterIntegrationTest#ConcurrentCreateDelete#ConcurrentCreateDelete

- core/server/worker/src/test/java/alluxio/worker/block/BlockStoreLocationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2727
Make BlockStoreLocationTest final to avoid accidental extension
> [ALLUXIO-2727] Make BlockStoreLocationTest final to avoid accidental extension

- core/client/src/main/java/alluxio/client/file/FileInStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-2692
> [ALLUXIO-2692] Specify null variable in FileInStream.java precondition check 

- docs/en/Configuring-Alluxio-with-Azure-Blob-Store.md
https://alluxio.atlassian.net/browse/ALLUXIO-2811
@gpang PTAL
> [ALLUXIO-2811] Added documentation for running Alluxio on Azure Blob Store as underfs

- core/common/src/main/java/alluxio/util/io/PathUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-2685
> [ALLUXIO-2685] Modified commenting style in PathUtils file

- tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java
Add javadocs for JournalShutdownIntegrationTest#createFsMasterFromJournal
> [SMALLFIX]Add javadoc for createFsMasterFromJournal

- core/common/src/main/java/alluxio/wire/FileInfo.java
https://alluxio.atlassian.net/browse/ALLUXIO-2710
> [ALLUXIO-2710] Specify null variable in FileInfo.java precondition check

- core/common/src/main/java/alluxio/Configuration.java
https://alluxio.atlassian.net/browse/ALLUXIO-2696
> [ALLUXIO-2696]Special null variable in Configuraton.java precondition check

- docs/en/Contributing-to-Alluxio.md
Make the link to show unassigned tasks, rather than all tasks
> [DOCFIX] Update Contributing-to-Alluxio.md

- tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java
Add javadocs for JournalShutdownIntegrationTest#setupMultiMasterCluster and JournalShutdownIntegrationTest#setupSingleMasterCluster
> [SMALLFIX]Add javadocs for setupMasterCluster

- core/server/worker/src/main/java/alluxio/worker/file/UnderFileSystemUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-2676
> [ALLUXIO-2676]Clean up UnderFileSystemUtils javadoc

- core/common/src/main/java/alluxio/collections/DirectedAcyclicGraphNode.java
https://alluxio.atlassian.net/browse/ALLUXIO-2698
> [ALLUXIO-2698]Specify null variable in DirectedAcyclicGraphNode.java precondition check

- core/server/worker/src/test/java/alluxio/worker/block/BlockLockManagerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2718
> [ALLUXIO-2718]Deprecate Throwables.propagate with RuntimeException in BlockLockManagerTest.java

- core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
https://alluxio.atlassian.net/browse/ALLUXIO-2713
> [ALLUXIO-2713]Specify null variable in WorkerNetAddress.java precondition check

- core/server/master/src/main/java/alluxio/master/file/meta/InodeFile.java
- core/server/master/src/test/java/alluxio/master/file/meta/InodeFileTest.java
Include the invalid length to help with debugging
> [SMALLFIX] Improve negative file size message

- core/common/src/test/java/alluxio/util/FormatUtilsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2624
make class FormatUtilsTest final to avoid accidental subclass extension
> [ALLUXIO-2624]Make FormatUtilsTest final

- core/common/src/main/java/alluxio/PropertyKey.java
https://alluxio.atlassian.net/browse/ALLUXIO-2740
My task is Mark MASTER_ADDRESS Depreciated,but it may should be Deprecated. 
I'm ashamed that I don't know how to write the reason why it was deprecated.
> [ALLUXIO-2740]Mark MASTER_ADDRESS Deprecated

- docs/_data/table/cn/common-configuration.yml
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
Add javadoc for ConcurrentFreer in FileSystemMasterIntegrationTest.
> [SMALLFIX]Add javadoc for concurrent freer

- core/common/src/test/java/alluxio/wire/BlockLocationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2751
> [ALLUXIO-2751]Make BlockLocationTest final

- docs/cn/Running-Alluxio-on-GCE.md
Update Chinese doc for Running-Alluxio-on-GCE.
> [DOCFIX]Update Chinese doc for Running-Alluxio-on-GCE

- docs/cn/Key-Value-System-API.md
Update Chinese doc for Key-Value-System-API.
> [DOCFIX]Update Chinese doc for Key-Value-System-API

- docs/cn/index.md
> [DOCFIX] docfix for docs/cn/index.md

- docs/cn/Unit-Testing.md
doc fix for docs/cn/Unit-Testing.md
> [DOCFIX] doc fix for docs/cn/Unit-Testing.md

- integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java
A follow-up PR to https://github.com/Alluxio/alluxio/pull/5235
> [SMALLFIX] Fix fuse test

- docs/en/Configuration-Settings.md
Change "property values" to "configuration setting" as this makes more sense in the context of the previous paragraph
Change "Cluster Manager" to Resource Manager Configurations" as this section is related to configurations for resource managers
> [DOCFIX] Update Configuration-Settings.md

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2654
> [ALLUXIO-2654] De-flake concurrency test

- core/server/worker/src/main/java/alluxio/worker/block/evictor/Evictor.java
JIRA Tickets: 
https://alluxio.atlassian.net/browse/ALLUXIO-2788
> [ALLUXIO­-2788] replace Throwables.propagate with RuntimeException

- core/common/src/test/java/alluxio/CommonTestUtilsTest.java
Add javadoc for CommonTestUtilsTest.
> [SMALLFIX] Add javadoc for CommonTestUtilsTest

- core/common/src/test/java/alluxio/AlluxioURITest.java
Add javadoc for AlluxioURITest#testParentChild.
> [SMALLFIX] Add javadoc for AlluxioURITest#testParentChild

- core/common/src/main/java/alluxio/MasterInquireClient.java
Add javadoc for MasterInquireClient#MasterInquireClient.
> [SMALLFIX] Add javadoc for MasterInquireClient#MasterInquireClient

- core/common/src/test/java/alluxio/wire/LockBlockResultTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2758
> [ALLUXIO-2758] Make LockBlockResultTest final

- bin/alluxio
https://alluxio.atlassian.net/browse/ALLUXIO-2673
> [ALLUXIO-2673]improve the usage for fs in bin/alluxio

- core/common/src/test/java/alluxio/util/ShellUtilsTest.java
[https://alluxio.atlassian.net/browse/ALLUXIO-2626](url)
He Xincheng changed  class ShellUtilsTest. in ./core/common/src/test/java/alluxio/util/ShellUtilsTest.java to final.
> [ALLUXIO-2626]Make ShellUtilsTest final

- core/client/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java
[https://alluxio.atlassian.net/browse/ALLUXIO-2612](url)
> [ALLUXIO-2612] Deprecate Throwables.propagete with RuntimeException in NettyPacketWriter.java

- docs/en/Running-Hive-with-Alluxio.md
- docs/en/Running-Presto-with-Alluxio.md
Update the Hive and Presto docs on the instructions of alluxio properties setting.
> [DOCFIX] Presto doc update

- docs/cn/Configuring-Alluxio-with-GCS.md
- docs/cn/Configuring-Alluxio-with-OSS.md
- docs/cn/Configuring-Alluxio-with-S3.md
- docs/pt/Configuring-Alluxio-with-S3.md
> [DOCFIX] Sync CN/PT docs for doc changes.

- core/client/src/main/java/alluxio/client/block/stream/NettyPacketReader.java
- core/client/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java
- core/client/src/main/java/alluxio/client/netty/NettyRPC.java
- core/client/src/main/java/alluxio/client/netty/NettyRPCContext.java
- core/common/src/main/java/alluxio/network/protocol/RPCProtoMessage.java
- core/common/src/main/java/alluxio/util/CommonUtils.java
This PR implements an RPC client library via netty. A follow up PR will use it in short circuit IO.
> [ALLUXIO-2816] netty rpc client

- core/server/worker/src/main/java/alluxio/worker/block/evictor/GreedyEvictor.java
https://alluxio.atlassian.net/browse/ALLUXIO-2680
> [ALLUXIO-2680] fix logging style in GreedyEvictor.java

- core/common/src/main/java/alluxio/Configuration.java
- core/common/src/main/java/alluxio/PropertyKey.java
- core/common/src/test/java/alluxio/ConfigurationTest.java
- core/common/src/test/java/alluxio/PropertyKeyTest.java
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java
- tests/src/test/java/alluxio/client/MultiUfsMountIntegrationTest.java
- tests/src/test/java/alluxio/client/ReadOnlyMountIntegrationTest.java
- tests/src/test/java/alluxio/shell/command/MountCommandTest.java
- tests/src/test/java/alluxio/underfs/ConfExpectingUnderFileSystemFactory.java
https://alluxio.atlassian.net/browse/ALLUXIO-2743
This PR adds an integration test for the multi-ufs mounting with different configurations per mount point.
> [ALLUXIO-2743] Add integration test for per-mount point UFS mounting

- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- tests/src/test/java/alluxio/client/MultiUfsMountIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2743
This PR aims to fix the build on hadoop-{1/2} profile
> [ALLUXIO-2743] Fix MultiUfsMountIntegrationTest with hadoop profiles

- pom.xml
- underfs/gcs/pom.xml
- underfs/oss/pom.xml
- underfs/s3/pom.xml
- underfs/s3a/pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-2830
> [ALLUXIO-2830] Shade OSS/S3/S3a/GCS UnderFileSystem Modules

- core/common/src/main/java/alluxio/AbstractClient.java
- core/common/src/main/java/alluxio/AbstractMasterClient.java
- core/common/src/main/java/alluxio/network/connection/ThriftClientPool.java
- core/common/src/test/java/alluxio/AbstractClientTest.java
- keyvalue/client/src/main/java/alluxio/client/keyvalue/KeyValueWorkerClient.java
Mode did not provide any additional and useful information.
> [SMALLFIX] Clean up client connect messages

- docs/en/File-System-API.md
Fixed some language as existing language is confusing as does not apply to all cases
> [DOCFIX] Update File-System-API.md

- docs/en/File-System-API.md
> [DOCFIX] Clean up FileSystem API line length

- core/server/worker/src/test/java/alluxio/worker/block/allocator/AllocatorContractTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2732
> [ALLUXIO-2732] Make AllocatorContractTest final

- core/server/proxy/src/main/java/alluxio/proxy/AlluxioProxyProcess.java
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
Aims to address https://alluxio.atlassian.net/browse/ALLUXIO-2831 by adding additional condition to the `waitForReady` proxy process method.
> [ALLUXIO-2831] Fix flaky REST API tests.

- core/client/fs/src/main/java/alluxio/client/netty/IdleWriteHandler.java
- core/client/fs/src/main/java/alluxio/client/netty/NettyClient.java
- core/common/src/main/java/alluxio/PropertyKey.java
- core/common/src/main/java/alluxio/network/protocol/RPCMessage.java
- core/common/src/main/java/alluxio/network/protocol/RPCProtoMessage.java
- core/protobuf/src/main/java/alluxio/proto/dataserver/Protocol.java
- core/protobuf/src/main/java/alluxio/util/proto/ProtoMessage.java
- core/protobuf/src/proto/dataserver/protocol.proto
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerBlockReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerHeartbeatHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/IdleReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/PipelineHandler.java
- docs/_data/table/common-configuration.csv
- docs/_data/table/en/common-configuration.yml
- tests/src/test/java/alluxio/client/RemoteReadIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2813
Adds a heartbeat to the server through any active Netty channels. If the server does not receive a heartbeat within the configured timeout period, the channel will be closed.
> [ALLUXIO-2813] Netty Channel Heartbeat

- bin/alluxio
https://alluxio.atlassian.net/browse/ALLUXIO-2675
In bin/alluxio , we can improve the usage from
Run an Alluxio class with main method.
to
Run the main method of an Alluxio class.
> [ALLUXIO-2675]Improve usage for bin/alluxio runClass

- core/server/worker/src/test/java/alluxio/worker/block/allocator/MaxFreeAllocatorTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2735
Mark class MaxFreeAllocatorTest as a final class
> [ALLUXIO-2735] Mark class MaxFreeAllocatorTest as a final class

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockOutStream.java
- core/client/fs/src/main/java/alluxio/client/block/stream/LocalFilePacketWriter.java
- core/client/fs/src/main/java/alluxio/client/block/stream/PacketOutStream.java
- core/client/fs/src/main/java/alluxio/client/netty/NettyRPC.java
- core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
- core/client/fs/src/test/java/alluxio/client/block/stream/TestBlockOutStream.java
- core/client/fs/src/test/java/alluxio/client/file/FileInStreamTest.java
- core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java
- core/common/src/main/java/alluxio/network/protocol/RPCMessage.java
- core/common/src/main/java/alluxio/network/protocol/RPCProtoMessage.java
- core/protobuf/src/main/java/alluxio/proto/dataserver/Protocol.java
- core/protobuf/src/main/java/alluxio/util/proto/ProtoMessage.java
- core/protobuf/src/proto/dataserver/protocol.proto
- core/server/common/src/main/java/alluxio/RpcUtils.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerBlockWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerShortCircuitReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerShortCircuitWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/PipelineHandler.java
- core/server/worker/src/test/java/alluxio/worker/netty/DataServerBlockWriteHandlerTest.java
Implement short circuit write via netty.
> [ALLUXIO-2813] Short circuit write via netty 

- core/client/hdfs/src/test/java/alluxio/hadoop/HadoopConfigurationUtilsTest.java
- core/common/src/main/java/alluxio/Configuration.java
- core/common/src/main/java/alluxio/exception/PreconditionMessage.java
- core/common/src/test/java/alluxio/ConfigurationTest.java
- core/common/src/test/java/alluxio/ConfigurationTestUtils.java
- core/server/worker/src/test/java/alluxio/worker/block/SpaceReserverTest.java
- core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockReaderTest.java
- shell/src/main/java/alluxio/cli/ValidateConf.java
- tests/src/test/java/alluxio/LocalAlluxioClusterResource.java
- tests/src/test/java/alluxio/master/AlluxioMasterRestApiTest.java
- tests/src/test/java/alluxio/master/journal/ufs/JournalCheckpointThreadTest.java
- tests/src/test/java/alluxio/master/journal/ufs/UfsJournalCheckpointWriterTest.java
- tests/src/test/java/alluxio/master/journal/ufs/UfsJournalLogWriterTest.java
- tests/src/test/java/alluxio/master/journal/ufs/UfsJournalReaderTest.java
- improves configuration initialization
- cleans up configuration validation
- adds configuration validation for test cluster
> [SMALLFIX] Configuration cleanup

- core/common/src/test/java/alluxio/security/authentication/PlainSaslServerTest.java
Add javadoc for PlainSaslServerTest.
> [SMALLFIX] Add javadoc for PlainSaslServerTest

- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
Add doc for UnderFileSystemBlockStore#Key.
> [DOCFIX]Add doc for Key

- core/server/master/src/test/java/alluxio/master/file/PermissionCheckerTest.java
Add doc for PermissionCheckerTest#verifyInodesList.
> [DOCFIX]Add doc for verifyInodesList

- core/server/worker/src/test/java/alluxio/worker/block/meta/StorageDirTest.java
add javadoc for StorageDirTest#newStorageDir and StorageDirTest#newBlockFile
> [SMALLFIX]add javadoc for StorageDirTest

- core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java
Add javadoc for FileOutStreamTest#createTestStream.
> [SMALLFIX] Add javadoc for FileOutStreamTest#createTestStream

- core/server/worker/src/main/java/alluxio/worker/block/evictor/LRFUEvictor.java
https://alluxio.atlassian.net/browse/ALLUXIO-2619)
> [ALLUXIO-2619]i changed the line62 into '/** Logic time count. */'

- core/common/src/main/java/alluxio/network/protocol/databuffer/DataNettyBufferV2.java
Update DataNettyBufferV2.https://alluxio.atlassian.net/browse/ALLUXIO-2703
> [ALLUXIO-2703]Update DataNettyBufferV2.java

- core/server/worker/src/test/java/alluxio/worker/block/meta/StorageDirTest.java
add javadoc for StorageDirTest#assertMetadataEmpty and StorageDirTest#assertStorageDirEmpty
> [SMALLFIX] add javadoc for StorageDirTest's Assert*Empty

- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
> [SMALLFIX] Fix hadoop profile

- core/common/src/test/java/alluxio/client/file/URIStatusTest.java
- core/server/worker/src/test/java/alluxio/worker/block/meta/StorageDirTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2790
> [ALLUXIO-2790] Use assertThat to improve junit error message.

- core/client/fs/src/test/java/alluxio/client/block/policy/options/GetWorkerOptionsTest.java
JIRA: https://alluxio.atlassian.net/browse/ALLUXIO-2807
> [ALLUXIO-2807] add getworkeroptions test

- docs/cn/Contributing-Getting-Started.md
Updates Chinese doc for Contributing-Getting-Start.
> [DOCFIX]update Chinese doc for Contributing

- docs/cn/Configuring-Alluxio-with-S3.md
docfix for Configuring-Alluxio-with-S3.md
> [DOCFIX] docfix for Configuring-Alluxio-with-S3.md

- core/common/src/main/java/alluxio/PropertyKey.java
- core/common/src/test/java/alluxio/PropertyKeyTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2651
> [ALLUXIO-2651] Help!!! Support Deprecated annotation in PropertyKey

- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- core/common/src/main/java/alluxio/underfs/UfsStatus.java
Do not create directory breadcrumbs on listStatus or isDirectory.
JIRA: https://alluxio.atlassian.net/browse/ALLUXIO-2836
> [ALLUXIO-2836] Support read-only object store mount points

- shell/src/main/java/alluxio/shell/command/TestCommand.java
- tests/src/test/java/alluxio/shell/command/TestCommandTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2572
> [ALLUXIO-2572] Fix return value when error

- docs/cn/Running-Spark-on-Alluxio.md
Updates Chinese doc for Running-Spark-on-Alluxio.md and adds the solutions for `Failed to login`.
> [DOCFIX]update doc for Spark-on-Alluxio

- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
> [SMALLFIX] Fix hadoop-1 test for underfs/hdfs

- core/common/src/test/java/alluxio/wire/BlockInfoTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2750
> [ALLUXIO-2750] Make BlockInfoTest final

- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/user-configuration.csv
This should improve performance for write heavy workloads.
> [SMALLFIX] Update write request buffer to 8MB.

- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/user-configuration.csv
Reverts Alluxio/alluxio#5418
Breaks some unit tests which depend on the default config value, will fix and resubmit.
> Revert "[SMALLFIX] Update write request buffer to 8MB."

- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/user-configuration.csv
- tests/src/test/java/alluxio/shell/AbstractAlluxioShellTest.java
> [SMALLFIX] Update user write request buffer size

- core/common/src/main/java/alluxio/Constants.java
- docs/en/Configuring-Alluxio-with-Swift.md
- underfs/swift/src/main/java/alluxio/underfs/swift/KeystoneV3Access.java
- underfs/swift/src/main/java/alluxio/underfs/swift/KeystoneV3AccessProvider.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
Add support for authentication using Keystone V3 credentials.
JIRA: https://alluxio.atlassian.net/browse/ALLUXIO-2455
Reference: OpenStack Keystone V3 Authentication https://developer.openstack.org/api-ref/identity/v3/?expanded=password-authentication-with-scoped-authorization-detail
> [ALLUXIO-2455] Keystone v3 authentication for Swift UFS

- underfs/swift/src/main/java/alluxio/underfs/swift/KeystoneV3AccessProvider.java
> [SMALLFIX] Use HttpClient

- core/common/src/main/java/alluxio/wire/BlockInfo.java
https://alluxio.atlassian.net/browse/ALLUXIO-2706
> [ALLUXIO-2706] Specify null variable in BlockInfo.java precondition check

- core/common/src/test/java/alluxio/retry/ExponentialBackoffRetryTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2664
> [ALLUXIO-2664]Make ExponentialBackoffRetryTest final

- core/server/worker/src/test/java/alluxio/worker/block/allocator/AllocatorFactoryTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2733
> [ALLUXIO-2733]Make AllocatorFactoryTest final

- docs/cn/Configuring-Alluxio-with-Swift.md
Updates Chinese doc for Configuring-Alluxio-with-Swift.
> [DOCFIX]updates Chinese doc for Config-With-Swift

- docs/_data/table/cn/common-configuration.yml
Updates Chinese doc for Common-Configuration.
> [DOCFIX]updates Chinese doc for common config

- docs/_data/table/cn/master-configuration.yml
docfix for docs/_data/table/cn/master-configuration.yml
> [DOCFIX] docfix for docs/_data/table/cn/master-configuration.yml

- dev/scripts/build-docker.sh
- dev/scripts/generate-tarball.sh
https://alluxio.atlassian.net/browse/ALLUXIO-2842
> [ALLUXIO-2842] Docker build script and refactor tarball generation

- core/server/master/src/test/java/alluxio/master/file/PermissionCheckTest.java
Add java doc comments for PermissionCheckTest:
* verifyRead
* verifyGetFileId
> [DOCFIX]Add java doc for PermissionCheckTest

- core/common/src/test/java/alluxio/resource/ResourcePoolTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2661
> [ALLUXIO-2661] Make ResourcePoolTest final

- core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-2789
> [ALLUXIO-2789] Fixed indentation in FilesystemMaster

- core/common/src/main/java/alluxio/job/Job.java
https://alluxio.atlassian.net/browse/ALLUXIO-2699
> [ALLUXIO-­2699]Specify null variable in Job.java precondition check

- docs/_data/table/cn/user-configuration.yml
docfix for docs/_data/table/cn/user-configuration.yml
> [DOCFIX] docfix for docs/_data/table/cn/user-configuration.yml

- core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
[https://alluxio.atlassian.net/browse/ALLUXIO-2668](https://alluxio.atlassian.net/browse/ALLUXIO-2668)
> [ALLUXIO-2668] Make PathUtilsTest final

- dev/scripts/generate-release-tarballs.sh
- dev/scripts/generate-tarball.sh
This PR is ready for review, we shouldn't merge it right away though
> [SMALLFIX] Add script for publishing release tarballs

- docs/_data/table/en/tiered-storage-configuration-parameters.yml
- docs/_data/table/tiered-storage-configuration-parameters.csv
- docs/en/Tiered-Storage-on-Alluxio.md
> [DOCFIX] Clean up Tiered Storage docs

- core/server/master/src/main/java/alluxio/master/lineage/checkpoint/CheckpointPlanner.java
https://alluxio.atlassian.net/browse/ALLUXIO-2719
modifies core/server/master/src/main/java/alluxio/master/lineage/checkpoint/CheckpointPlanner.java
> [ALLUXIO-2719] Deprecate Throwables.propagate with RuntimeException in CheckpointPlanner.java

- core/server/worker/src/main/java/alluxio/worker/netty/NettyExecutors.java
> [REVERT] Revert "[SMALLFIX] Use LinkedBlockingQueue to create the threadpools "

- docs/cn/Tiered-Storage-on-Alluxio.md
updates Chinese doc for Tiered Storage.
> [DOCFIX]updates Chinese doc for Tiered Storage

- core/server/common/src/main/java/alluxio/RestUtils.java
[https://alluxio.atlassian.net/browse/ALLUXIO-2678](url)
> [ALLUXIO-2678]Fix logging style in RestUtils

- core/common/src/test/java/alluxio/wire/FileBlockInfoTest.java
Make FileBlockInfoTest final
https://alluxio.atlassian.net/browse/ALLUXIO-2754
> [ALLUXIO-2754]Make FileBlockInfoTest final

- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/en/common-configuration.yml
- docs/_includes/Configuring-Alluxio-with-Ceph/underfs-s3a.md
- docs/en/Configuring-Alluxio-with-Ceph.md
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
- underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
Older backends implementing S3 interface may implement list object v1 API http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html.
> [SMALLFIX] Support for S3A ListObjects V1

- docs/en/Running-Alluxio-Yarn-Integration.md
- docs/en/Running-Alluxio-Yarn-Standalone.md
These docs describe how to run Alluxio with an existing YARN cluster, either standalone or as a YARN application
> [DOCFIX] Add additional YARN docs

- core/common/src/main/java/alluxio/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java
- core/server/master/src/main/java/alluxio/master/file/meta/UfsAbsentPathCache.java
- docs/_data/table/en/master-configuration.yml
- docs/_data/table/master-configuration.csv
> [SMALLFIX] Improve efficiency of async path cache

- docs/cn/Debugging-Guide.md
- docs/en/Debugging-Guide.md
Update the debug guide to insert the shell debug flag description
> [DOCFIX]insert the shell debug flag description to branch 1.5

- docs/cn/Configuring-Alluxio-with-HDFS.md
Updates Chinese doc for config-with-HDFS
> [DOCFIX]updates Chinese doc for config-with-HDFS

- docs/cn/Running-Alluxio-on-EC2-Yarn.md
Updates Chinese doc for running-on-ec2-yarn.
> [DOCFIX]docfix for running-on-ec2-yarn

- docs/cn/Running-Alluxio-Yarn-Standalone.md
add cn doc: docs/cn/Running-Alluxio-Yarn-Standalone.md
> [DOCFIX] add cn doc: docs/cn/Running-Alluxio-Yarn-Standalone.md

- docs/cn/Configuring-Alluxio-with-OSS.md
docfix for docs/cn/Configuring-Alluxio-with-OSS.md
> [DOCFIX] docfix for docs/cn/Configuring-Alluxio-with-OSS.md

- core/client/fs/src/main/java/alluxio/client/file/policy/LocalFirstPolicy.java
- core/client/fs/src/test/java/alluxio/client/file/policy/LocalFirstPolicyTest.java
> [SMALLFIX] Port #5547 to branch-1.5

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java
- core/server/master/src/main/java/alluxio/master/file/meta/NoopUfsAbsentPathCache.java
- core/server/master/src/main/java/alluxio/master/file/meta/UfsAbsentPathCache.java
- core/server/master/src/test/java/alluxio/master/file/meta/AsyncUfsAbsentPathCacheTest.java
- core/server/master/src/test/java/alluxio/master/file/meta/UfsAbsentPathCacheTest.java
- docs/_data/table/en/master-configuration.yml
> [SMALLFIX] Configuration for disabling ufs path cache

- core/common/src/test/java/alluxio/wire/AlluxioWorkerInfoTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2749
> [ALLUXIO-2749] Make AlluxioWorkerInfoTest final

- docs/_data/table/cn/tiered-storage-configuration-parameters.yml
docfix for docs/_data/table/cn/tiered-storage-configuration-parameters.yml
> [DOCFIX] docfix for docs/_data/table/cn/tiered-storage-configuration-parameters.yml

- core/common/src/test/java/alluxio/util/io/BufferUtilsTest.java
[ALLUXIO-2666](https://alluxio.atlassian.net/browse/ALLUXIO-2666)
> [ALLUXIO-2666] Make BufferUtils Test Final

- core/server/master/src/main/java/alluxio/master/file/UfsSyncChecker.java
- tests/src/test/java/alluxio/client/FileSystemIntegrationTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
> [SMALLFIX] Ufs should not fail deletion of in-progress writes

- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
https://alluxio.atlassian.net/browse/ALLUXIO-2849
> [ALLUXIO-2849] Close TServerSocket when stopping serving

- core/server/worker/src/test/java/alluxio/worker/block/allocator/RoundRobinAllocatorTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2736
> [ALLUXIO-2736]Make RoundRobinAllocatorTest final

- docs/_data/table/cn/master-configuration.yml
Docfix for master-configuration.
> [DOCFIX]docfix for master-configuration

- docs/cn/Metrics-System.md
Updates Chinese doc for metrics system.
> [DOCFIX]update Chinese doc for metrics system

- docs/_data/table/cn/common-configuration.yml
Docfixs for common-configuration.
> [DOCFIX]docfix for common-configuration

- docs/cn/Running-Hive-with-Alluxio.md
Updates Chinese doc for running-hive-with-alluxio.
> [DOCFIX]update Chinese doc for running-hive

- core/common/src/main/java/alluxio/metrics/MetricsSystem.java
- core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
- core/server/common/src/main/java/alluxio/underfs/UfsManager.java
- core/server/master/src/test/java/alluxio/master/file/meta/MountTableTest.java
- core/server/worker/src/main/java/alluxio/underfs/WorkerUfsManager.java
- core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerBlockReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerBlockWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerUfsFileWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/DataServerWriteHandler.java
- core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockReaderTest.java
- core/server/worker/src/test/java/alluxio/worker/file/FileDataManagerTest.java
- core/server/worker/src/test/java/alluxio/worker/netty/DataServerUfsFileWriteHandlerTest.java
Improve consistency and naming in the UfsManager code
> [SMALLFIX] UfsManager cleanup

- core/server/worker/src/main/java/alluxio/worker/netty/DataServerUfsFileWriteHandler.java
This is consistent with the other dataserver readers and writers
> [SMALLFIX] Create ufs file lazily

- tests/src/test/java/alluxio/master/journal/ufs/UfsJournalIntegrationTest.java
Add java doc for test methods in UfsJournalIntegrationTest.
> [DOCFIX] Add javadoc for UfsJournalIntegrationTest

- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
A follow-up fix to PR https://github.com/Alluxio/alluxio/pull/5224/files#diff-d5233a8530cd24552aec12806df5eddaR139
> [SMALLFIX] Fix the getters of S3A timeouts

- conf/alluxio-env.sh.template
- docs/en/Configuration-Settings.md
> [DOCFIX] Document ALLUXIO_CLASSPATH

- core/server/master/src/main/java/alluxio/master/file/options/LoadMetadataOptions.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManagerView.java
- core/server/worker/src/main/java/alluxio/worker/block/evictor/EvictorUtils.java
- core/server/worker/src/main/java/alluxio/worker/block/evictor/LRFUEvictor.java
> [SMALLFIX]adds Nullable for some files

- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2478
> [ALLUXIO-2478] : Improve comment style in FileSystemMasterTest

- core/server/worker/src/main/java/alluxio/worker/block/evictor/GreedyEvictor.java
smallfix for GreedyEvictor.java. Supply the variable name to Preconditions.checkNotnull
> [SMALLFIX] Supply the variable name to Preconditions.checkNotnull for GreedyEvictor.java

- docs/en/Running-Hive-with-Alluxio.md
Fixed typo  + updated language to make it more clear
> [DOCFIX] -Small changes

- docs/_config.yml
- docs/cn/Running-Presto-with-Alluxio.md
- docs/en/Running-Presto-with-Alluxio.md
Since we already precompile presto client and bundle it within the distribution, there is no need to recompile Alluxio with the presto profile in the instruction.
> [DOCFIX] Update docs for presto

- core/common/src/main/java/alluxio/exception/status/AlluxioStatusException.java
- core/server/worker/src/main/java/alluxio/web/WebInterfaceWorkerBlockInfoServlet.java
- core/server/worker/src/test/java/alluxio/worker/netty/DataServerUfsFileWriteHandlerTest.java
- docs/_data/table/cn/common-configuration.yml
- docs/_data/table/cn/master-configuration.yml
- docs/_data/table/worker-configuration.csv
- docs/cn/Metrics-System.md
- docs/cn/Running-Hive-with-Alluxio.md
- docs/en/Running-Hive-with-Alluxio.md
- integration/docker/Dockerfile
- tests/src/test/java/alluxio/client/FileSystemIntegrationTest.java
Picks up select documentation updates.
> [MERGE] Merge branch-1.5 with master

- tests/src/test/java/alluxio/shell/command/TailCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2881
> [ALLUXIO-2881] rename test file from TailCommandTest to TailCommandIntegrationTest

- tests/src/test/java/alluxio/shell/command/StatCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2880
> [ALLUXIO-2880] Rename file StatCommandTest.java to StatCommandIntegrationTest.java

- core/server/master/src/test/java/alluxio/master/block/meta/BlockContainerIdGeneratorTest.java
Static import for BlockContainerIdGeneratorTest.
> [SMALLFIX]static import for BlockContainerIdGeneratorTest

- core/server/master/src/test/java/alluxio/master/block/meta/MasterBlockInfoTest.java
static import for MasterBlockInfoTest.
> [SMALLFIX]static import for MasterBlockInfoTest

- core/server/master/src/test/java/alluxio/master/block/meta/MasterWorkerInfoTest.java
Static import for MasterWorkerInfoTest.
> [SMALLFIX]static import for MasterWorkerInfoTest

- core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManagerView.java
add @Nullable notation for BlockMetadataManagerView.java
> [SMALLFIX] add @Nullable notation for BlockMetadataManagerView.java

- core/server/worker/src/main/java/alluxio/worker/block/evictor/GreedyEvictor.java
- core/server/worker/src/main/java/alluxio/worker/file/DefaultFileSystemWorker.java
- core/server/worker/src/main/java/alluxio/worker/file/FileDataManager.java
- core/server/worker/src/test/java/alluxio/worker/block/evictor/EvictorTestUtils.java
Updates checkNotNull for some files.
> [SMALLFIX]checkNotNull for some files

- core/protobuf/src/main/java/alluxio/proto/journal/Block.java
- core/protobuf/src/main/java/alluxio/proto/journal/Journal.java
- core/protobuf/src/proto/journal/block.proto
- core/protobuf/src/proto/journal/journal.proto
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java
- tests/src/test/java/alluxio/master/block/BlockMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2852
> [ALLUXIO-2852] Journal block deletion

- core/common/src/main/java/alluxio/PropertyKey.java
- core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
- core/server/common/src/test/java/alluxio/master/journal/ufs/UfsJournalTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2887
> [ALLUXIO-2887] UFS Journal Configuration

- core/server/master/src/main/java/alluxio/master/file/StartupConsistencyCheck.java
- core/server/master/src/test/java/alluxio/master/file/StartupConsistencyCheckTest.java
- tests/src/test/java/alluxio/master/MasterTestUtils.java
- tests/src/test/java/alluxio/master/StartupConsistencyCheckIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2851
> [ALLUXIO-2851] Fix null pointer exception in master/info REST endpoint

- tests/src/test/java/alluxio/shell/command/MvCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2874
> [ALLUXIO-2874] Rename file MvCommandTest.java to MvCommandIntegrationTest.java

- tests/src/test/java/alluxio/shell/command/LsCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2871
> [ALLUXIO-2871] Rename file LsCommandTest.java to LsCommandIntegrationTest.java

- tests/src/test/java/alluxio/shell/command/SetTtlCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2879
> [ALLUXIO-2879] Rename SetTtlCommandTest.java

- tests/src/test/java/alluxio/shell/command/FreeCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2865
> [ALLUXIO-2865] Rename file FreeCommandTest.java to FreeCommandIntegrationTest.java

- core/common/src/main/java/alluxio/AbstractClient.java
- core/common/src/main/java/alluxio/PropertyKey.java
- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
change property key
MASTER_CONNECTION_TIMEOUT_MS
MASTER_JOURNAL_FLUSH_BATCH_TIME_MS
to support time unit transformation
> [SMALLFIX] change ms-related propertykey to support time unit transformation

- shell/src/main/java/alluxio/cli/GetConf.java
Cmd must be non-null, no need to check.
> [SMALLFIX]No need to check null

- tests/src/test/java/alluxio/shell/command/CatCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2853
> [ALLUXIO-2853] Rename file CatCommandTest.java to CatCommandIntegrationTest.java

- shell/src/main/java/alluxio/shell/command/CheckConsistencyCommand.java
java doc for CheckConsistencyCommand#checkConsistency
> [SMALLFIX] java doc for CheckConsistencyCommand#checkConsistency

- tests/src/test/java/alluxio/shell/command/HelpCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2867
> [ALLUXIO-2867] rename HelpCommandTest to HelpCommandIntegrationTest

- tests/src/test/java/alluxio/shell/command/CheckConsistencyCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2854
> [ALLUXIO-2854] Rename CheckConsistencyCommandTest to CheckConsistencyCommandIntegrationTest

- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTestUtils.java
add variable name to Preconditions.checkNotNull for TieredBlockStoreTestUtils.java
> [SMALLFIX] add variable name to Preconditions.checkNotNull for TieredBlockStoreTestUtils.java

- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystemFactory.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystemFactory.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystemFactory.java
https://alluxio.atlassian.net/browse/ALLUXIO-2900
> [ALLUXIO-2900] Check credentials from under ufs conf

- core/common/src/test/java/alluxio/PropertyKeyTest.java
static import of PropertyKeyTest.java
> [SMALLFIX] static import of PropertyKeyTest.java

- tests/src/test/java/alluxio/shell/command/HeadCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2866
Rename file HeadCommandTest.java to HeadCommandIntegrationTest.java, and rename class HeadCommandTest to HeadCommandIntegrationTest.
> [ALLUXIO-2866] Rename file HeadCommandTest.java to HeadCommandIntegrationTest.java

- tests/src/test/java/alluxio/shell/command/CpCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2862
> [ALLUXIO-2862] Renamed file CpCommandTest.java to CpCommandIntegrationTest.java

- shell/src/main/java/alluxio/shell/command/AbstractShellCommand.java
- shell/src/main/java/alluxio/shell/command/CheckConsistencyCommand.java
- shell/src/main/java/alluxio/shell/command/ChgrpCommand.java
- shell/src/main/java/alluxio/shell/command/ChmodCommand.java
- shell/src/main/java/alluxio/shell/command/ChownCommand.java
- shell/src/main/java/alluxio/shell/command/CpCommand.java
- shell/src/main/java/alluxio/shell/command/FreeCommand.java
- shell/src/main/java/alluxio/shell/command/LsCommand.java
- shell/src/main/java/alluxio/shell/command/RmCommand.java
[ALLUXIO-2893] Refactor arg options in Alluxio Shell Command Line
> [ALLUXIO-2893] Refactor arg options in Alluxio Shell Command Line

- tests/src/test/java/alluxio/shell/command/DuCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2863
> [ALLUXIO-2863] Rename file DuCommandTest.java

- core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
https://alluxio.atlassian.net/browse/ALLUXIO-2294
> [ALLUXIO-2294]Change Id to id in comment

- bin/alluxio-start.sh
(https://alluxio.atlassian.net/browse/ALLUXIO-2905)
> [ALLUXIO-2905]Use awk to replace cut command

- core/common/src/main/java/alluxio/util/CommonUtils.java
- core/server/common/src/main/java/alluxio/web/UIFileInfo.java
- core/server/common/src/main/java/alluxio/web/WebUtils.java
- core/server/master/src/main/java/alluxio/web/WebInterfaceGeneralServlet.java
- core/server/worker/src/main/java/alluxio/web/WebInterfaceWorkerGeneralServlet.java
- shell/src/main/java/alluxio/shell/command/CommandUtils.java
- shell/src/main/java/alluxio/shell/command/LsCommand.java
- tests/src/test/java/alluxio/shell/command/LsCommandIntegrationTest.java
(https://alluxio.atlassian.net/browse/ALLUXIO-2906)
> [ALLUXIO-2906]Combine convertMsToDate from WebUtils and CommandUtils to CommonUtils

- docs/en/Running-Hive-with-Alluxio.md
I have performed some experiments against Hive with tables stored in HDFS originally and I transferred the data into Alluxio, change the table data location， then I can query data from Alluxio. 
Looking forward to more advice on this!
> [SMALLFIX]update doc Running-Hive-With-Alluxio

- tests/src/test/java/alluxio/shell/command/ChgrpCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2856
> [ALLUXIO-2856] renamed:    ChgrpCommandTest.java -> ChgrpCommandIntegrationTest.java

- core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManagerView.java
add variable name to Preconconditions.checkNotNull for BlockMetadataManagerView.java
> [SMALLFIX] add variable name to Preconconditions.checkNotNull for BlockMetadataManagerView.java

- tests/src/test/java/alluxio/hadoop/fs/DFSIOIntegrationTest.java
add @Nullable for methods of DFSIOIntegrationTest.java
> [SMALLFIX] add @Nullable for methods of DFSIOIntegrationTest.java

- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/cn/user-configuration.yml
- docs/_data/table/en/user-configuration.yml
- docs/_data/table/user-configuration.csv
- docs/cn/Debugging-Guide.md
- docs/en/Debugging-Guide.md
- shell/src/main/java/alluxio/shell/command/CpCommand.java
https://alluxio.atlassian.net/browse/ALLUXIO-2898
Added a configuration to determine the write location policy for copyFromLocal. Made it use round robin by default.
> [ALLUXIO-2898] Make copyFromLocal use round robin by default

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystemFactory.java
https://alluxio.atlassian.net/browse/ALLUXIO-2344
> [ALLUXIO-2344] Improve error handling in SwiftUnderFileSystemFactory

- core/common/src/main/java/alluxio/PropertyKey.java
- core/common/src/test/java/alluxio/PropertyKeyTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2892
> [ALLUXIO-2892] Support alias for Alluxio configuration

- tests/src/test/java/alluxio/shell/command/CopyToLocalCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2860
Rename file tests/src/test/java/alluxio/shell/command/Copy ToLocalCommandTest.java to tests/src/test/java/alluxio/shell/command/CopyToLocalCommandIntegrationTest.java
> [ALLUXIO-2860] Rename file

- docs/en/Configuring-Alluxio-with-S3.md
https://alluxio.atlassian.net/browse/ALLUXIO-2473
Updated Configuring-Alluxio-with-S3.md Doc
> [ALLUXIO-2473] Updated Configuring-Alluxio-with-S3.md Doc

- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2939
> [ALLUXIO-2939] Make acl inheritance best effort for s3a.

- core/common/src/main/java/alluxio/util/io/FileUtils.java
- core/server/worker/src/test/java/alluxio/worker/block/SpaceReserverTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2902
Change all file operation to NIO
> [ALLUXIO-2902]Migrate Java IO Filesystem calls to NIO APIs in FileUtils.java

- pom.xml
- shell/src/main/java/alluxio/shell/command/HelpCommand.java
https://alluxio.atlassian.net/browse/ALLUXIO-2894
> [ALLUXIO-2894] Improve Help Command to adjust the output width according to terminal width

- keyvalue/server/src/main/java/alluxio/master/keyvalue/DefaultKeyValueMaster.java
- keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMaster.java
- keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMasterFactory.java
https://alluxio.atlassian.net/browse/ALLUXIO-2912
> [ALLUXIO-2912] Separate KeyValueMaster.java into an interface class and an implementation class

- docs/en/Configuring-Alluxio-with-OSS.md
Described how to mount OSS using the mount command with options.
> [DOCFIX] Add doc for mounting OSS location at a nested folder

- docs/en/Configuring-Alluxio-with-S3.md
Described how to mount s3 using the mount command with options.
> [DOCFIX] Add doc for mounting s3 location at a nested folder

- core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
- underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
- underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2958
> [ALLUXIO-2958] Make initialization of s3a permissions lazy.

- core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManager.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockStore.java
- core/server/worker/src/main/java/alluxio/worker/block/BlockStoreMeta.java
- core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockStoreMeta.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockStoreMetaTest.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockWorkerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/SpaceReserverTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2908
> [ALLUXIO-2908]Fix Wrong path setup in SpaceReseverTest

- tests/src/test/java/alluxio/master/file/ConcurrentDeleteIntegrationTest.java
rename ConcurrentFileSystemMasterDeleteTest.java to ConcurrentDeleteIntegrationTest.java
> [SMALLFIX] rename ConcurrentFileSystemMasterDeleteTest.java

- tests/src/test/java/alluxio/master/file/ConcurrentSetTtlIntegrationTest.java
Rename ConcurrentFileSystemMasterSetTtlTest.java to Right name
> [SMALLFIX]Rename ConcurrentFileSystemMasterSetTtlTest.java

- core/common/src/test/java/alluxio/security/login/LoginModuleTest.java
static import of LoginModuleTest.java
> [SMALLFIX] static import of LoginModuleTest.java

- core/common/src/test/java/alluxio/security/authorization/ModeBitsTest.java
static import of ModeBitsTest.java
> [SMALLFIX] static import of ModeBitsTest.java

- integration/docker/entrypoint.sh
Also, we should avoid setting `RAM_FOLDER` if tiered storage is already configured.
> [SMALLFIX] Populate alluxio-env.sh in docker entrypoint

- core/client/fs/src/main/java/alluxio/client/RetryHandlingMetaMasterClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2938
> [ALLUXIO-2938] Improve javadoc in RetryHandlingMetaMasterClient 

- tests/src/test/java/alluxio/master/file/CheckConsistencyIntegrationTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
- tests/src/test/java/alluxio/master/lineage/LineageMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2965
> [ALLUXIO-2965] test fix: use AuthenticatedUserRule to simplify tests

- tests/src/test/java/alluxio/shell/command/LoadCommandIntegrationTest.java
static import of LoadCommandIntegrationTest.java
> [SMALLFIX] static import of LoadCommandIntegrationTest.java

- core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- tests/src/test/java/alluxio/shell/command/CopyFromLocalCommandTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2970
@gpang, would it make sense to check for FileAlreadyExists earlier in the create file code path?
> [ALLUXIO-2970] Fix class cast exception on file create

- core/common/src/main/java/alluxio/util/URIUtils.java
add @Nullable for URIUtils.java
> [SMALLFIX] add @Nullable for URIUtils.java

- docs/_config.yml
- docs/_layouts/global.html
- docs/en/Clients-Hadoop.md
- docs/en/Clients-Java-Native.md
- docs/en/Clients-Rest.md
- docs/en/Key-Value-System-API.md
- docs/en/Lineage-API.md
- docs/en/Mounting-Alluxio-FS-with-FUSE.md
> [DOCFIX] Reorganize client doc pages

- bin/alluxio
- core/common/pom.xml
- core/common/src/main/java/alluxio/util/network/HttpUtils.java
- core/common/src/main/java/alluxio/wire/LogInfo.java
- shell/src/main/java/alluxio/cli/LogLevel.java
https://alluxio.atlassian.net/browse/ALLUXIO-2850
> [ALLUXIO-2850]Change a special class log level dynamically through shell command

- tests/src/test/java/alluxio/client/FreeAndDeleteIntegrationTest.java
static import of FreeAndDeleteIntegrationTest.java
> [SMALLFIX] static import of FreeAndDeleteIntegrationTest.java

- underfs/gcs/src/test/java/alluxio/underfs/gcs/GCSUnderFileSystemContractTest.java
Supply the variable name to Preconditions.checkNotNull for GCSUnderFileSystemContractTest.java
> [SMALLFIX] Supply the variable name to Preconditions.checkNotNull for GCSUnderFileSystemContractTest.java

- tests/src/test/java/alluxio/shell/command/PinCommandIntegrationTest.java
use static imports for standard test utilities in PinCommandIntegrationTest.java
> [SMALLFIX]use static imports for standard test utilities

- underfs/oss/src/test/java/alluxio/underfs/oss/OSSUnderFileSystemContractTest.java
supply the variable name to Predictions.checkNotNull in OSSUnderFileSystemContractTest.java
> [SMALLFIX]supply the variable name to Predictions.checkNotNull

- core/common/src/main/java/alluxio/Configuration.java
- core/common/src/main/java/alluxio/PropertyKey.java
- core/common/src/test/java/alluxio/ConfigurationRuleTest.java
- core/common/src/test/java/alluxio/ConfigurationTest.java
- core/common/src/test/java/alluxio/PropertyKeyTest.java
The property was only being used in tests.
> [SMALLFIX] Remove MASTER_ADDRESS config property

- libexec/alluxio-config.sh
Since we no longer use alluxio-layout.sh, therefore I remove it from alluxio-config.sh script.
> [SMALLFIX] Clean up alluxio-config.sh

- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystemFactory.java
supply variable name for GCSUnderFileSystemFactory.java
> [SMALLFIX] supply variable name for GCSUnderFileSystemFactory.java

- core/common/src/main/java/alluxio/wire/WorkerInfo.java
supply variable name for WorkerInfo.java (alluxio.wire)
> [SMALLFIX] supply variable name for WorkerInfo.java (alluxio.wire)

- core/server/worker/src/main/java/alluxio/worker/block/SpaceReserver.java
Not sure why the check style missed this.
> [SMALLFIX] Clean up formatting in SpaceReserver.

- core/common/src/main/java/alluxio/PropertyKey.java
https://alluxio.atlassian.net/browse/ALLUXIO-2889
WORK_DIR
WORKER_TIERED_STORE_LEVEL0_ALIAS
WORKER_TIERED_STORE_LEVEL0_DIRS_PATH
WORKER_TIERED_STORE_LEVEL0_DIRS_QUOTA
WORKER_TIERED_STORE_LEVEL0_HIGH_WATERMARK_RATIO
WORKER_TIERED_STORE_LEVEL0_LOW_WATERMARK_RATIO
> [ALLUXIO-2889] update a few Key's descriptions to PropertyKey.java

- core/common/src/main/java/alluxio/PropertyKey.java
https://alluxio.atlassian.net/browse/ALLUXIO-2982
> [ALLUXIO-2982] Rename .ms suffix from PropertyKey names

- core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client/hdfs/src/main/java/alluxio/hadoop/FaultTolerantFileSystem.java
- core/client/hdfs/src/main/java/alluxio/hadoop/FileSystem.java
- docs/en/Running-Alluxio-Fault-Tolerant.md
- docs/en/Running-Hadoop-MapReduce-on-Alluxio.md
- docs/en/Running-Hive-with-Alluxio.md
- docs/en/Running-Presto-with-Alluxio.md
- docs/en/Running-Spark-on-Alluxio.md
https://alluxio.atlassian.net/browse/ALLUXIO-2983
> [ALLUXIO-2983] Deprecate FaultTolerantAlluxioFileSystem

- core/common/src/main/java/alluxio/PropertyKey.java
- core/common/src/test/java/alluxio/PropertyKeyTest.java
- docs/_data/table/en/common-configuration.yml
- docs/_data/table/en/key-value-configuration.yml
- docs/_data/table/en/master-configuration.yml
- docs/_data/table/en/security-configuration.yml
- docs/_data/table/en/user-configuration.yml
- docs/_data/table/en/worker-configuration.yml
- docs/_data/table/master-configuration.csv
- shell/src/main/java/alluxio/cli/ConfigurationDocGenerator.java
- tests/src/test/java/alluxio/cli/ConfigurationDocGeneratorTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2889
> [ALLUXIO-2889] 2nd task yml file update

- docs/_config.yml
- docs/_layouts/global.html
> [DOCFIX] Define category list

- docs/cn/Configuring-Alluxio-with-Swift.md
docfix for Configuring-Alluxio-with-Swift.md
> [DOCFIX] docfix for Configuring-Alluxio-with-Swift.md

- core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
> [SMALLFIX] Include exception message in WARN

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockOutStream.java
- core/client/fs/src/test/java/alluxio/client/block/stream/BlockOutStreamTest.java
- core/client/fs/src/test/java/alluxio/client/block/stream/FailingTestPacketWriter.java
- core/client/fs/src/test/java/alluxio/client/block/stream/TestFailingPacketWriter.java
https://alluxio.atlassian.net/browse/ALLUXIO-2987
Clone of #5887 to 1.5.
> [ALLUXIO-2987] Prevent illegal reference counts in BlockOutStream

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockOutStream.java
- core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
- core/client/fs/src/test/java/alluxio/client/block/stream/BlockOutStreamTest.java
- core/client/fs/src/test/java/alluxio/client/block/stream/FailingTestPacketWriter.java
- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/en/user-configuration.yml
> [MERGE] Merge branch 1.5

- examples/src/main/java/alluxio/cli/RunOperation.java
This is useful when populating the journal for testing.
> [SMALLFIX] Add tool for running an operation multiple times.

- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/common-configuration.csv
- docs/_data/table/en/common-configuration.yml
https://alluxio.atlassian.net/browse/ALLUXIO-2994
> [ALLUXIO-2994] Search conf dir for conf

- core/common/src/main/java/alluxio/wire/WorkerInfo.java
- core/common/src/test/java/alluxio/wire/WorkerInfoTest.java
- core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
Sort WorkerInfo list by o.LastContactSec prior() to returning lost workers in DefaultBlockMaster.
Sorted list screenshot:
> [ALLUXIO-2996] Sort lost worker list in UI.

- docs/cn/Running-Alluxio-on-a-Cluster.md
docfix for Running-Alluxio-on-a-Cluster.md
> [DOCFIX] docfix for Running-Alluxio-on-a-Cluster.md

- docs/cn/Running-Presto-with-Alluxio.md
docfix for Running-Presto-with-Alluxio.md
> [DOCFIX] docfix for Running-Presto-with-Alluxio.md

- core/common/src/main/java/alluxio/Constants.java
https://alluxio.atlassian.net/browse/ALLUXIO-2993
> [ALLUXIO-2993] Increase padding for file size.

- tests/src/test/java/alluxio/proxy/s3/S3ClientRestApiTest.java
Add integration test for #5914
> [SMALLFIX] [s3] Add integration test for S3 PUT bucket

- core/common/src/main/java/alluxio/Constants.java
- core/common/src/main/java/alluxio/PropertyKey.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3ErrorCode.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
- core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestUtils.java
- tests/src/test/java/alluxio/proxy/s3/S3ClientRestApiTest.java
> [SMALLFIX] [s3] Add S3 DELETE bucket API

- core/common/src/main/java/alluxio/underfs/options/CreateOptions.java
- core/common/src/test/java/alluxio/underfs/options/CreateOptionsTest.java
- underfs/local/src/test/java/alluxio/underfs/local/LocalUnderFileSystemTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2998
> [ALLUXIO-2998] avoid unnecessary ufs rename during create

- bin/alluxio
- bin/alluxio-masters.sh
- bin/alluxio-mount.sh
- bin/alluxio-start.sh
- bin/alluxio-stop.sh
- bin/alluxio-workers.sh
- integration/fuse/bin/alluxio-fuse.sh
- integration/mesos/bin/alluxio-mesos-start.sh
- integration/yarn/bin/alluxio-yarn.sh
https://alluxio.atlassian.net/browse/ALLUXIO-2999
> [ALLUXIO-2999] Follow one level of symlinks

- bin/alluxio
- bin/alluxio-masters.sh
- bin/alluxio-mount.sh
- bin/alluxio-start.sh
- bin/alluxio-stop.sh
- bin/alluxio-workers.sh
- integration/fuse/bin/alluxio-fuse.sh
- integration/mesos/bin/alluxio-mesos-start.sh
- integration/yarn/bin/alluxio-yarn.sh
If readlink fails, fall back to non-readlink
> [SMALLFIX] Fix script location lookup when script is not a link

- examples/src/main/java/alluxio/cli/TestRunner.java
Add an option to test non-root mount points
> [SMALLFIX] Add directory option for runTests

- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/tiered-storage-configuration-parameters.csv
- docs/_data/table/worker-configuration.csv
(https://alluxio.atlassian.net/browse/ALLUXIO-3301)
> [ALLUXIO-3301] change watermark.high.ratio default value to 0.95

- docs/_data/table/Developer-Tips.csv
- docs/_data/table/cn/Developer-Tips.yml
- docs/_data/table/en/Developer-Tips.yml
- docs/cn/Developer-Tips.md
- docs/cn/Getting-Started.md
- docs/en/Developer-Tips.md
- docs/en/Getting-Started.md
- docs/pt/Developer-Tips.md
https://alluxio.atlassian.net/browse/ALLUXIO-3003
> [ALLUXIO-3003] Add document for validateEnv command

- core/server/worker/src/main/java/alluxio/worker/netty/AbstractReadHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/AbstractWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/BlockWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/BlockWriteRequest.java
- core/server/worker/src/main/java/alluxio/worker/netty/BlockWriteRequestContext.java
- core/server/worker/src/main/java/alluxio/worker/netty/UfsFileWriteHandler.java
- core/server/worker/src/main/java/alluxio/worker/netty/WriteRequestContext.java
- core/server/worker/src/test/java/alluxio/worker/netty/ReadHandlerTest.java
- core/server/worker/src/test/java/alluxio/worker/netty/WriteHandlerTest.java
@yupeng9  this PR should fix part of the failing unit test of https://github.com/Alluxio/alluxio/pull/5942
> [SMALLFIX] Handle invalid write request when it is the first request

- assembly/server/pom.xml
- bin/alluxio-start.sh
- bin/alluxio-stop.sh
- conf/log4j.properties
- core/common/src/main/java/alluxio/PropertyKey.java
- core/server/common/src/main/java/alluxio/AlluxioRemoteLogFilter.java
- core/server/common/src/main/java/alluxio/ProcessUtils.java
- libexec/alluxio-config.sh
- logserver/pom.xml
- logserver/src/main/java/alluxio/logserver/AlluxioLog4jSocketNode.java
- logserver/src/main/java/alluxio/logserver/AlluxioLogServer.java
- logserver/src/main/java/alluxio/logserver/AlluxioLogServerProcess.java
- pom.xml
- tests/src/test/java/alluxio/master/file/ConcurrentFileSystemMasterCreateTest.java
> [MERGE] Merge master to 1.6

- docs/en/Configuring-Alluxio-with-S3.md
- docs/en/Debugging-Guide.md
> [SMALLFIX] Update the s3 integration doc.

- docs/_data/table/s3-api-supported-operations.csv
- docs/en/Clients-S3.md
> [DOCFIX] [branch-1.6] Add S3 API docs with examples

- docs/cn/Running-Hadoop-MapReduce-on-Alluxio.md
Update Chinese documents to make them more clearly.
> [DOCFIX] Update Chinese Documents

- core/common/src/main/java/alluxio/PropertyKey.java
> [SMALLFIX] Cleanup unused properties

- docs/en/Running-Alluxio-On-Docker.md
Improved the separation between the tutorial and non-tutorial topics
> [DOCFIX] Improve clarity and organization of Docker docs

- core/server/master/src/test/java/alluxio/master/lineage/recompute/RecomputePlannerTest.java
static import of RecomputePlannerTest
> [SMALLFIX] static import of RecomputePlannerTest

- docs/cn/index.md
> [DOCFIX] docfix for index.md

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- shell/src/main/java/alluxio/cli/fs/command/RmCommand.java
(https://alluxio.atlassian.net/browse/ALLUXIO-2838)
> [ALLUXIO-2838] Add delete shell with alluxioOnly Option

- docs/en/Configuring-Alluxio-with-Ceph.md
- docs/en/Configuring-Alluxio-with-Swift.md
> [DOCFIX][branch-1.6] Fix Ceph + Swift docs

- docs/en/Configuring-Alluxio-with-secure-HDFS.md
@aaudiber Could you take a look and comment? Thanks!
> [DOCFIX] Configure Alluxio with Secure HDFS

- docs/_includes/Running-Spark-on-Alluxio/Hadoop-1.x-configuration.md
- docs/_includes/Running-Spark-on-Alluxio/alluxio-hdfs-in-out-scala.md
- docs/_includes/Running-Spark-on-Alluxio/alluxio-local-in-out-scala.md
- docs/_includes/Running-Spark-on-Alluxio/alluxio-one-partition.md
- docs/_includes/Running-Spark-on-Alluxio/any-Alluxio-master.md
- docs/_includes/Running-Spark-on-Alluxio/earlier-spark-version-bash.md
- docs/_includes/Running-Spark-on-Alluxio/fault-tolerant-mode-with-zookeeper-bash.md
- docs/_includes/Running-Spark-on-Alluxio/fault-tolerant-mode-with-zookeeper-xml.md
- docs/_includes/Running-Spark-on-Alluxio/license-hdfs.md
- docs/_includes/Running-Spark-on-Alluxio/license-local.md
- docs/_includes/Running-Spark-on-Alluxio/off-heap-Spark-shell.md
- docs/_includes/Running-Spark-on-Alluxio/slave-hostname-example.md
- docs/_includes/Running-Spark-on-Alluxio/slave-hostname.md
- docs/_includes/Running-Spark-on-Alluxio/spark-local-hostname-example.md
- docs/_includes/Running-Spark-on-Alluxio/spark-profile-build.md
- docs/cn/Running-Spark-on-Alluxio.md
- docs/en/Running-Spark-on-Alluxio.md
- docs/pt/Running-Spark-on-Alluxio.md
Small improvements:
- removed extra `$` on non bash snippets
- moved code snippets inline
> [DOCFIX] Improve "Running Spark on Alluxio" Doc

- underfs/hdfs/src/test/java/alluxio/underfs/hdfs/HdfsUnderFileSystemContractTest.java
add variable name for Preconditions.checknull of HdfsUnderFileSystemContractTest.java
> [SMALLFIX] add variable name for Preconditions.checknull of HdfsUnderFileSystemContractTest.java

- core/server/master/src/main/java/alluxio/master/lineage/recompute/RecomputePlanner.java
Supply variable name for Precondition.checkNotNull of RecomputePlanner.java
> [SMALLFIX] Supply variable name for Precondition.checkNotNull of RecomputePlanner.java

- core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/FileInStreamTest.java
conflicts resolution is at the last commit
> [MERGE] Merge 1.5 to 1.6

- docs/en/Unit-Testing.md
https://alluxio.atlassian.net/browse/ALLUXIO-2935
> [ALLUXIO-2935]Fix typo in Unit-Testing

- core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockHeartbeatReporterTest.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockLockManagerTest.java
- core/server/worker/src/test/java/alluxio/worker/block/BlockMetadataManagerViewTest.java
- core/server/worker/src/test/java/alluxio/worker/block/ClientRWLockTest.java
Use static imports for standard test utilities
> [SMALLFIX] Use static imports for standard test utilities

- core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockStoreTest.java
static import of UnderFileSystemBlockStoreTest.java
> [SMALLFIX] static import of UnderFileSystemBlockStoreTest.java

- core/server/worker/src/test/java/alluxio/worker/block/BlockStoreLocationTest.java
static import of BlockStoreLocationTest.java
> [SMALLFIX] static import of BlockStoreLocationTest.java

- core/server/master/src/main/java/alluxio/master/lineage/LineageMasterClientServiceHandler.java
Supply variable name for Precondition.checkNotNull of LineageMasterClientServiceHandler.java
> [SMALLFIX] Supply variable name for Precondition.checkNotNull of LineageMasterClientServiceHandler.java

- core/server/master/src/main/java/alluxio/master/lineage/recompute/RecomputePlan.java
add variable name for Preconditions.checkNotNull of RecomputePlan.java
> [SMALLFIX] add variable name for Preconditions.checkNotNull of RecomputePlan.java

- core/server/master/src/main/java/alluxio/master/lineage/recompute/RecomputeExecutor.java
add variable name for Preconditions.checkNotNull of RecomputeExecutor.java
> [SMALLFIX] add variable name for Preconditions.checkNotNull of RecomputeExecutor.java

- core/server/master/src/main/java/alluxio/master/lineage/meta/LineageStoreView.java
add variable name for Preconditions.checkNotNull of LineageStoreView.java
> [SMALLFIX] add variable name for Preconditions.checkNotNull of LineageStoreView.java

- core/server/master/src/main/java/alluxio/master/lineage/meta/Lineage.java
add variable name for Preconditions.checkNotNull of Lineage.java
> [SMALLFIX] add variable name for Preconditions.checkNotNull of Lineage.java

- docs/cn/Configuring-Alluxio-with-secure-HDFS.md
docfix for Configuring-Alluxio-with-secure-HDFS.md
> [DOCFIX] docfix for Configuring-Alluxio-with-secure-HDFS.md

- core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
static import of TieredBlockStoreTest.java
> [SMALLFIX] static import of TieredBlockStoreTest.java

- core/server/worker/src/test/java/alluxio/worker/block/BlockMetadataManagerTest.java
static import of BlockMetadataManagerTest.java
> [SMALLFIX] static import of BlockMetadataManagerTest.java

- core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryIdGenerator.java
- core/server/master/src/main/java/alluxio/master/file/meta/InodeFile.java
- core/server/master/src/main/java/alluxio/master/file/meta/options/MountInfo.java
Supply the variable name to Preconditions.checkNotNull
> [SMALLFIX] Supply the variable name to Preconditions.checkNotNull

- core/client/fs/src/main/java/alluxio/client/file/policy/LocalFirstPolicy.java
add Nullable notation for LocalFirstPolicy.java
> [SMALLFIX] add Nullable notation for LocalFirstPolicy.java

- core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
add Nullable notation for LockedInodePath.java
> [SMALLFIX] add Nullable notation for LockedInodePath.java

- core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
add Nullable notation for AlluxioMasterProcess.java
> [SMALLFIX] add Nullable notation for AlluxioMasterProcess.java

- core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
add Nullable notation for InodeTree.java
> [SMALLFIX] add Nullable notation for InodeTree.java

- core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java
add Nullable notation for MountTable.java
> [SMALLFIX] add Nullable notation for MountTable.java

- docs/_config.yml
> [SMALLFIX] Improve descriptions for variables in _config.yml

- docs/en/Configuration-Settings.md
- docs/en/Remote-Logging.md
@aaudiber @gpang 
Could you take a look? Thanks!
> [DOCFIX] Add documentation for remote logging

- docs/en/Security.md
@aaudiber 
Could you take a look? Thanks!
> [DOCFIX] Fix doc for audit logging.

- underfs/swift/src/test/java/alluxio/underfs/swift/SwiftUnderFileSystemContractTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3021
[ALLUXIO-3021]Supply the variable name to Preconditions.checkNotNull for class SwiftUnderFileSystemContractTest
> [ALLUXIO-3021]Supply the variable name to Preconditions.checkNotNull for class SwiftUnderFileSystemContractTest

- docs/en/Configuration-Settings.md
@aaudiber 
Typo. I came across these while reviewing the page, and thought I may as well fix them. Thanks.
> Fix several typos.

- docs/en/Remote-Logging.md
@aaudiber 
This PR fixes a typo.
> [DOCFIX] Typo fix

- docs/cn/Configuring-Alluxio-with-Swift.md
https://alluxio.atlassian.net/browse/ALLUXIO-3028
update docs/en/Configuring-Alluxio-with-Swift.md of the chinese by the change in https://github.com/Alluxio/alluxio/compare/Alluxio:5569e02...Alluxio:eef0c29
> [DOCFIX]Update the docs/en/Configuring-Alluxio-with-Swift.md of the chinese version

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3033
> [ALLUXIO-3033] Fix partial recursive deletion

- core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3036
> [ALLUXIO-3036] Fix typo in deletion implementation

- keyvalue/client/src/main/java/alluxio/client/keyvalue/BasePayloadReader.java
https://alluxio.atlassian.net/browse/ALLUXIO-3023
> [ALLUXIO-3023] Passing variable name to Preconditions.checkNotNull

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystemFactory.java
https://alluxio.atlassian.net/browse/ALLUXIO-3019
> [SMALLFIX] Update SwiftUnderFileSystemFactory

- keyvalue/client/src/main/java/alluxio/client/keyvalue/BasePayloadWriter.java
https://alluxio.atlassian.net/browse/ALLUXIO-3024
> [ALLUXIO-3024] Passing variable name to Preconditions.checkNotNull

- core/client/fs/src/main/java/alluxio/client/block/stream/BlockOutStream.java
- core/client/fs/src/test/java/alluxio/client/lineage/LineageFileOutStreamTest.java
and disable a deprecated integration test
> [SMALLFIX] Minor code cleanup

- docs/cn/Developer-Tips.md
Update Chinese version of docs/cn/Developer-Tips.md corresponding to modified part of docs/en/Developer-Tips.md
> [DOCFIX] Update Chinese version of docs/cn/Developer-Tips.md

- core/server/worker/src/main/java/alluxio/worker/block/evictor/AbstractEvictor.java
[SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class AbstractEvictor
> [SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class AbstractEvictor

- docs/cn/Security.md
Update Chinese version of docs/cn/Security.md corresponding to modified part of docs/en/Security.md
> [DOCFIX] Update Chinese version of docs/en/Security.md

- docs/cn/Configuration-Settings.md
Update Chinese version of docs/cn/Configuration-Settings.md corresponding to modified part of docs/en/Configuration-Settings.md
> [DOCFIX] Update Chinese version of docs/en/Configuration-Settings.md

- core/common/src/main/java/alluxio/PropertyKey.java
- docs/_data/table/en/cluster-management-configuration.yml
- docs/_data/table/en/user-configuration.yml
- docs/_data/table/en/worker-configuration.yml
Start with capital letter and end with period.
> [SMALLFIX] Clean up doc descriptions

- keyvalue/client/src/main/java/alluxio/client/keyvalue/ByteBufferKeyValuePartitionReader.java
https://alluxio.atlassian.net/browse/ALLUXIO-3022
Change mBuf = Preconditions.checkNotNull(fileBytes); to
mBuf = Preconditions.checkNotNull(fileBytes，“fileBytes”);
> [ALLUXIO-3022] Supply the variable name to Preconditions.checkNotNull for class KeyValuePartitionReader

- docs/cn/Clients-Go.md
[DOCFIX] alluxio\docs\cn\Clients-Go.md
2017-10-04-JiangXiNJU
> [DOCFIX] alluxio\docs\cn\Clients-Go.md

- core/client/fs/src/main/java/alluxio/client/block/policy/DeterministicHashPolicy.java
- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
> [MERGE] Merge branch-1.6 to master

- core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
- core/client/fs/src/test/java/alluxio/client/file/FileInStreamTest.java
Merge the fixes from https://github.com/Alluxio/alluxio/pull/6202
> [MERGE] Merge the partial caching fix

- docs/cn/Clients-S3.md
- docs/cn/Configuring-Alluxio-with-Swift.md
- docs/cn/Security.md
Create docs/cn/Clients-S3.md corresponding to docs/en/Clients-S3.md
> [DOCFIX] Update Chinese version of docs/en/Clients-S3.md 

- docs/cn/Remote-Logging.md
[DOCFIX] alluxio\docs\cn\Remote-Logging.md
2017-10-04-JiangXiNJU
> [DOCFIX] alluxio\docs\cn\Remote-Logging.md

- keyvalue/server/src/main/java/alluxio/worker/keyvalue/KeyValueWorkerClientServiceHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-3020
> [SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class KeyValueWorkerClientServiceHandler

- core/server/common/src/main/java/alluxio/master/journalv0/ufs/UfsJournalWriter.java
[SMALLFIX] UfsJournalWriter.java
2017-10-04-JiangXiNJU
> [SMALLFIX] UfsJournalWriter.java

- core/server/master/src/main/java/alluxio/master/lineage/meta/Lineage.java
Supply the variable name to Preconditions.checkNotNull in
core/server/master/src/main/java/alluxio/master/lineage/meta/Lineage.java
> [SMALLFIX]Supply the variable name to Preconditions.checkNotNull in Lineage.java

- core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java
Improve core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketWriter.java as mLock can be marked as final.
Change
private ReentrantLock mLock = new ReentrantLock();
to
private final ReentrantLock mLock = new ReentrantLock();
> [SMALLFIX]NettyPacketWriter.java changed

- core/server/master/src/main/java/alluxio/master/file/PermissionChecker.java
[SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class PermissionChecker.java
> [SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class PermissionChecker.java

- core/server/common/src/main/java/alluxio/web/WebServer.java
Change
private InetSocketAddress mAddress;
to
private final InetSocketAddress mAddress;
> [SMALLFIX] Mark alluxio.web.WebServer#mAddress final 

- core/server/master/src/test/java/alluxio/master/file/PermissionCheckTest.java
[SMALLFIX] PermissionCheckTest.java
2017-10-08-JiangXiNJU
> [SMALLFIX] PermissionCheckTest.java

- integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java
Use static imports for standard test utilities in AlluxioFuseFileSystemTest.java
> [SMALLFIX]Use static imports for standard test utilities in AlluxioFuseFileSystemTest.java

- docs/en/Web-Interface.md
update /docs/en/Web-Interface.md and replace Files currently in the memory tier with Files currently in Alluxio
> [SMALLFIX]Update Web-Interface.md to reflect the latest change in UI
