Alluxio/alluxio

- core/src/main/java/tachyon/UnderFileSystemHdfs.java
- core/src/main/java/tachyon/hadoop/AbstractTFS.java
- pom.xml
When tachyon is used for MapReduce jobs, under fs may not be properly initialized.
This fix is to set those properties before under fs initialize() is called. If the properties are already set in core-site.xml, then don't overwrite them.
On my glutster setup, a wordcount test was run to validate this patch. Separately, @pfxuan validated part of the fix on his setup using orangefs as under fs.
The core-site.xml in use can be found at http://pastebin.com/SMpP6VXa
The wordcount test output can be found at http://pastebin.com/XXRPQRFt
> fix under fs and glusterfs configuration issues

- core/src/main/java/tachyon/conf/MasterConf.java
- core/src/main/java/tachyon/web/UIWebServer.java
- core/src/test/java/tachyon/master/LocalTachyonCluster.java
- docs/Configuration-Settings.md
On a server with more that 16 cores, the Web server hangs and does not respond because the default tachyon.master.web.threads is set to 9. The setting tachyon.master.web.threads is now actually limit the maximum thread pool size.
When Jetty server starts, it internally creates N acceptor threads and N selector threads by default. Acceptors are threads dedicated to accepting incoming connections, while selectors manage events on connected sockets. N is determined by processor number which equal to (processor number + 3) / 4. So on a server with 48 cores, it by default creates 12 acceptor threads and 12 selector threads. The thread pool max size has to be 25(1+selectors+acceptors) or above, otherwise Jetty does not work with a error message "insufficient threads ...".
For Tachyon Web UI, we …
> Fix Jetty hang issue and set Acceptor thread number

- core/src/test/java/tachyon/master/LocalTachyonCluster.java
- core/src/test/java/tachyon/master/LocalTachyonClusterMultiMaster.java
If we run test via LocalTachyonCluster.run() or LocalTachyonClusterMultiMaster.run(), it will build two tmp dirs, and one is unused.
For example, if we run TachyonFileTest.isInMemoryTest(), it will make two dirs:
-rw-r--r-- 1 root root      0 Jan 20 19:07 Tachyon281998800240761114
drwxrwxrwt 6 root root   4096 Jan 20 19:07 Tachyon281998800240761114U1421752078178
The tmp dir Tachyon281998800240761114 is unused, we don't need to make it.
> TACHYON-264: don't build unused tmp dir when run test

- core/src/test/java/tachyon/client/TachyonFSTest.java
cover the exception case which column count bigger than CommonConf.get().MAX_COLUMNS in TachyonFS#createRawTable
> Add test case for column count bigger than CommonConf.get().MAX_COLUMNS

- core/src/main/java/tachyon/command/TFsShell.java
- core/src/test/java/tachyon/command/TFsShellTest.java
Now tachyon client don't support copying a local file to a tachyon directory.
for example, there is no file under tachyon path {/test/input}
[root@huang1 tachyon]# bin/tachyon tfs lsr /test/input
[root@huang1 tachyon]# 
The following command will success
[root@huang1 tachyon]# bin/tachyon tfs copyFromLocal /home/testdata/input/a.txt /test/input/a.txt
But the following command will failed
[root@huang1 tachyon]# bin/tachyon tfs copyFromLocal /home/testdata/input/a.txt /test/input/
For better customer usage, we should support copying a local file to a tachyon directory.
> TACHYON-268: Enable copying a local file to tachyon directory

- core/src/main/java/tachyon/UnderFileSystemHdfs.java
- core/src/main/java/tachyon/hadoop/AbstractTFS.java
- pom.xml
This is an enhanced fix to #623. Previous fix failed on TestDFSIO test because in that test, the fs.defaultFS property is already set. If so, then avoid overriding this property. This new fix passed the tests.
When tachyon is used for MapReduce jobs, under fs may not be properly initialized.
This fix is to set those properties before under fs initialize() is called. If the properties are already set in core-site.xml, then don't overwrite them.
On my glutster setup, a wordcount test was run to validate this patch. Separately, @pfxuan validated part of the fix on his setup using orangefs as under fs.
The core-site.xml in use can be found at http://pastebin.com/WuR6Xn7v
The wordcount test output can be found at http://pastebin.com/aJJVSBK9
> (2nd round) fix under fs and glusterfs configuration issues

- core/src/main/java/tachyon/UnderFileSystemHdfs.java
- core/src/main/java/tachyon/hadoop/AbstractTFS.java
- pom.xml
> Revert "(2nd round) fix under fs and glusterfs configuration issues"

- core/pom.xml
This is a follow up to https://github.com/amplab/tachyon/pull/631 reduced to only resolve the compiler related warnings since resolving the other warnings has proved to be less than trivial
During compilation several spurious warnings would be seen in the logs
about the use of unchecked/unsafe methods:
```
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ tachyon ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 159 source files to /Users/rvesse/Documents/Work/Code/tachyon/core/target/classes
[WARNING] /Users/rvesse/Documents/Work/Code/tachyon/core/src/main/java/tachyon/thrift/ClientFileInfo.java: Some input files use unchecked or unsafe operations.
[WARNING] /Users/rvesse/Documents/Work/Code/tachyon/core/src/main/java/tachyon/thrift/ClientFileInfo.java: …
```
> Fix maven compiler warnings

- core/src/main/java/tachyon/client/BlockOutStream.java
- core/src/main/java/tachyon/client/TachyonFile.java
- core/src/test/java/tachyon/client/TachyonFileTest.java
1. decoupling cancel and close in BlockOutStream, because cancel and close actually runs different code path. and close method calls appendCurrentBuffer, which means it also write data,  if exception happens during appendCurrentBuffer in close, caller will not be able to cancel the block, it is a bug. for example recache operation in TachyonFile. 
2. fix bug and refactor recache method in TacyonFile .
> Decouple cancel and close in BlockOutStream and fix and refactor recache in TachyonFile

- core/src/main/java/tachyon/client/TachyonFS.java
Currently code following:
public synchronized TachyonFile getFile(int fid, boolean useCachedMetadata) throws IOException {
if (!useCachedMetadata || !mIdToClientFileInfo.containsKey(fid)) {
ClientFileInfo clientFileInfo = getFileStatus(fid, TachyonURI.EMPTY_URI);   ==> (1)
if (clientFileInfo == null) {
return null;
}
mIdToClientFileInfo.put(fid, clientFileInfo);  ==> (2)
==> (3)
}
return new TachyonFile(this, fid);  ==> (4)
}
There are three issues:
1. If useCachedMetadata is false, and fid is valid, (1) will cache mIdToClientFileInfo, but (2) cache duplicated.
2. If we duplicated cache fid in (2), why not cache mPathToClientFileInfo in (3)?
3. If useCachedMetadata is true, and fid is -1 or invalid, then will return new TachyonFile(this, fid), but should return null.
I think we don't need …
> TACHYON-269: simplify logic of 'getFile(int, boolean)'

- core/src/main/java/tachyon/command/TFsShell.java
- core/src/test/java/tachyon/command/TFsShellTest.java
- docs/Command-Line-Interface.md
Currently "tfs rm <path>" will remove a file or a directory.
But many file system separate remove a file and a directory to two commands.
e.g. linux, "rm" will remove a file and can't remove a directory, "rm -r" will remove a directory.
hdfs, "dfs rm" will remove a file and can't remove a directory, "dfs rmr" will remove a directory.
For better customer usage and file system standard, we should change "tfs rm <path>" to remove a file, and add "tfs rmr <path>" to remove a directory.
> TACHYON-270: support 'tfs rmr <directory_path>'

- bin/tachyon
- bin/tachyon-mount.sh
- bin/tachyon-start.sh
- bin/tachyon-stop.sh
- bin/tachyon-workers.sh
This pull request includes a couple of useful improvements to the Bash scripts.
Firstly it modifies the scripts to allow better debugging when using `bash -x` to launch the scripts.  Currently this is not so helpful because many of the scripts actually launch other Tachyon scripts and the debugging mode is not propagated to those sub-shells.  With these changes the debugging mode is now propagated to any sub-shells that the scripts launch (both to local and remote)
Secondly it makes a minor but useful tweak to `tachyon-workers.sh` to echo which user we are SSH'ing as because in some environments and situations this might not be the user who owns the terminal that launches the script e.g. when launching via `sudo`
> Bash script improvements

- bin/tachyon-mount.sh
On OS X a RAM FS is used and each time Tachyon is started the old RAM FS
(if any) is unmounted and then a brand new one is formatted and mounted.
However because of the way in which the RAM FS is unmounted we end up
endlessly incrementing the device ID so after you've run Tachyon a bunch
of times you end up with a device ID like `/dev/disk22` and a huge list
of unused disks if you run `diskutil list`
This commit changes how the old RAM FS is unmounted to instead determine
the actual device ID behind the RAM FS volume and if present detach it
rather than unmounting it.  This causes OS X to unmount and throw away
the disk so it doesn't clutter the list of devices and we simply reuse
the device ID when we create the new disk rather than endlessly
incrementing it.
> Improve how old RAM FS is unmounted on OS X

- core/src/main/java/tachyon/client/BlockOutStream.java
In original code, `if (mBuffer.position() + len >= mUserConf.FILE_BUFFER_BYTES)`, then current buffer to write will always be written to file since
`if (len > 0) {
appendCurrentBuffer(b, off, len);
}` will always hold, otherwise, `IndexOutOfBoundsException` will be thrown earlier.
> write to buffer first as much as possible

- bin/tachyon
use rmr instead of rm  to make sure the path is removed.
> use rmr instead of rm in tachyon script

- assembly/pom.xml
- build/license/HEADER.txt
- client/pom.xml
- core/pom.xml
- core/src/main/java/tachyon/client/RemoteBlockInStream.java
- core/src/main/java/tachyon/util/ThreadFactoryUtils.java
- core/src/test/java/tachyon/hadoop/HdfsFileInputStreamTest.java
- core/src/test/java/tachyon/hadoop/fs/AccumulatingReducer.java
- core/src/test/java/tachyon/hadoop/fs/IOMapperBase.java
- core/src/test/java/tachyon/hadoop/fs/TestDFSIO.java
- core/src/test/java/tachyon/retry/ExponentialBackoffRetryTest.java
- core/src/test/java/tachyon/worker/hierarchy/HierarchyStoreTest.java
- pom.xml
As requested in PR #647 this pull request pulls out the fixes to license headers and adds license header enforcement to the build.
This is improved upon the approach in #647 as it simply defines the plugin and its excludes once in the parent POM.  In order for this to work correctly in the child POMs if you are building individual modules it is necessary to override the property that provides the path to the header file in those child POMs as well.
I have added what seemed like sensible excludes:
- Build, Packing and Deployment
- Configuration scripts, files and resources
- Documentation
- Thrift Generated Code
> License headers enforcement and fixes

- core/src/main/java/tachyon/worker/hierarchy/StorageDir.java
- core/src/test/java/tachyon/worker/hierarchy/StorageDirTest.java
The method cancelBlock gets the allocatedBytes from mTempBlockAllocatedBytes and returns the space. The info should not be removed from mTempBlockAllocatedBytes before calling cancelBlock, otherwise the space is not returend.
> Fix potential capacity leak in StorageDir and add unit tests

- core/src/main/java/tachyon/conf/UserConf.java
there are two different configurations for default block size in UserConf and Constants. make them consistent.
> fix default block size conflict

- core/src/test/java/tachyon/client/TachyonFileTest.java
- core/src/test/java/tachyon/command/TFsShellTest.java
- core/src/test/java/tachyon/worker/DataServerTest.java
- core/src/test/java/tachyon/worker/WorkerServiceHandlerTest.java
- core/src/test/java/tachyon/worker/hierarchy/HierarchyStoreTest.java
There are many tests that rely on an embedded Tachyon cluster running.
Lots of these take some action and then need to wait for the workers to
update the masters state (or vice versa) before checking their assertions.
They do this by sleeping before carrying on with their assertions.  Due to 
the vagaries of JVM thread scheduling tests need to wait longer than the 
heartbeat interval because otherwise the heartbeat may not have yet 
occurred.  Most tests already do this by sleeping for double the heartbeat
interval plus a little bit extra.
However there were a few tests that only waited for a single heartbeat
interval so could intermittently fail with no real cause.  This commit
fixes up the tests that weren't waiting long enough to use the same
longer wait as other tests.
> Address intermittent test failures

- pom.xml
As reported in [TACHYON-276](https://tachyon.atlassian.net/browse/TACHYON-276) when building with Java 8 the build will fail with doclint errors from the javadocs plugin. This commit adds a Java 8 triggered profile which disables the doclint checks thus allowing builds to complete under Java 8
> Disable javadoc doclint under Java 8 (TACHYON-276)

- core/src/main/java/tachyon/hadoop/AbstractTFS.java
The default block size in AbstractTFS is provided by FileSystem, which is 32MB.
Use default block size in Tachyon to replace the default value in FileSystem.
> Set the default block size in AbstractTFS to be the default block size in Tachyon

- core/src/test/java/tachyon/client/TachyonFSTest.java
deleteFileTest can be invoked after other tests. If prior tests have written bytes into worker storage, getUsedBytes() will return non-zero
> getUsedBytes() assert in deleteFileTest 

- core/src/main/java/tachyon/client/TachyonFS.java
- core/src/main/java/tachyon/worker/package-info.java
Patch fixes these recently introduced warnings:
[WARNING] /home/abutala/work/tachyon/source/abhirajbutala/tachyon/core/src/main/java/tachyon/client/TachyonFS.java:631: warning - @param argument "the" is not a parameter name.
[WARNING] /home/abutala/work/tachyon/source/abhirajbutala/tachyon/core/src/main/java/tachyon/client/TachyonFS.java:631: warning - @param argument "the" is not a parameter name.
[WARNING] /home/abutala/work/tachyon/source/abhirajbutala/tachyon/core/src/main/java/tachyon/worker/package-info.java:58: warning - Tag @link: can't find createBlockResponseMessage(boolean, long, long,
[WARNING] long) in tachyon.worker.nio.DataServerMessage
> Fix build warnings in TachyonFS.java and package-info.java .

- core/src/main/java/tachyon/worker/TachyonWorker.java
Terminate worker when exception happens during initialization, or the worker process still exists.
> Terminate worker when exception happens during initialization

- core/pom.xml
- pom.xml
Currently JUnit 4.10 is used which is from Sept 2011 whereas the latest
version is 4.12 from Dec 2014.  The old version is licensed under the
Common Public License 1.0 which is a deprecated license that was
superseded by the Eclipse Public License which makes it problematic from
a licensing perspective.  Newer versions of JUnit are licensed under the
Eclipse Public License.
This commit upgrades JUnit to 4.12 and changes the hard coding of the
JUnit version in the dependency declaration to use a Maven property
to make this easy to change in the future.  Powermock was also upgraded
to the latest version in order to align with the JUnit upgrade
> Upgrade JUnit and PowerMock to the latest versions

- core/src/main/java/tachyon/thrift/MasterService.java
- core/src/main/java/tachyon/thrift/WorkerService.java
- core/src/thrift/tachyon.thrift
Keeps the naming consistent for block info exception in tachyon.thrift.
> Rename block info exception and regenerate thrift files.

- LICENSE
- NOTICE
Respinning this again, per @hsaputra and @haoyuan previous comments I have changed the format to better match Apache style `LICENSE` and `NOTICE` files
Tachyon bundles several third party libraries as-is in its
web-application.  These include all/part of the following:
- Bootstrap 2 (Apache License)
- jQuery (MIT License)
- Cookies.js (Public domain)
- Modernizr (MIT License)
- Pygments (BSD 2-Clause License)
Entries for each of these are added to the `LICENSE` file along with the
relevant licenses
The `NOTICE` is also updated to update the copyright year to 2015 and to
inform users that some portions of Tachyon are under alternative
licenses and they should consult `LICENSE` to see the details of this.
> Add bundled code to LICENSE file

- core/src/main/java/tachyon/StorageLevelAlias.java
- core/src/main/java/tachyon/master/MasterInfo.java
- core/src/main/java/tachyon/worker/WorkerStorage.java
A follow up to #655. Adds a size field to the StorageLevelAlias enum since it is used a few times. Also fills empty lists by using nCopies.
> Tier bytes cleanup

- pom.xml
This is an alternative to PR #681 which fixes the license plugin for the SNAPSHOT builds rather than ripping it out as that PR suggests.
The SNAPSHOT builds insist on using a local maven repository inside of
the working copy which means the license plugin sees the artifacts in
those directories and rejects them as not having a license (see my commentary on #681)
This commit simply adds the relevant path to the excludes list.  I set up
my local environment to create a local maven repository within the
working copy as the SNAPSHOT builds do and verified that mvn validate now passes
> Fix broken SNAPSHOT builds

- bin/tachyon
In the event the command line is very long and the keyword being searched
for runs out of the column width, killAll fails to kill the appropriate
daemon.  This is fixed by simply adding "ww" to the 'ps' command to
force unlimited width.
> Fix corner case with killAll

- pom.xml
Could probably just do a git revert if that seems cleaner.
I don't think the excludes should be there since the maven repo isn't something in the provided/auto-generated by the default Tachyon codebase.
@rvesse what do you think?
> Remove local Maven repo excludes from license plugin. (Reverts #682).

- bin/tachyon
- bin/tachyon-workers.sh
- conf/tachyon-env.sh.template
Several patches to fix bin/tachyon-workers.sh to speed up launching of workers on a cluster.
> Workerslaunchingspeed -   Several patches to fix bin/tachyon-workers.sh to speed up launching of workers on a cluster.

- core/src/main/java/tachyon/master/TachyonMaster.java
- core/src/main/java/tachyon/web/UIWebServer.java
- core/src/test/java/tachyon/master/LocalTachyonMaster.java
After the configuration changes I found that tests were hanging in my
environment and looking at the logs the web server was failing to start
properly because it wasn't respecting the test configuration that
LocalTachyonMaster created.
The problem was that UIWebServer simply creates a new TachyonConf
instance and thus gets the default values rather than it being passed
the TachyonConf object by the TachyonMaster to which it belongs.  This
commit simply changes the behaviour to do that.
It also improves the logging when the web server starts under a test
environment (port = 0) so it actually prints the port chosen for the web
server.
> Fix bug with UIWebServer getting the wrong conf (TACHYON-286)

- core/src/main/java/tachyon/master/MasterInfo.java
- core/src/main/java/tachyon/util/CommonUtils.java
- core/src/main/java/tachyon/worker/WorkerStorage.java
The sleepMs utility catches interrupts, but there are places where we rely on the thread being interrupted to break out of a while loop.
One case is during worker shutdown, currently if the workerStorage checkpoint threads are interrupted, they will not stop and the executor will wait 5 seconds before terminating them. As a side effect, our unit tests which spin up and down tachyon clusters take 5 additional seconds each (partially avoided by using BeforeClass/AfterClass). Unit tests after this change take around 5 minutes to run on my machine (previously 20+).
> SleepMs can optionally propagate interrupts.

- core/src/main/java/tachyon/client/AbstractTachyonFS.java
- core/src/main/java/tachyon/client/TachyonFS.java
- core/src/main/java/tachyon/hadoop/AbstractTFS.java
- core/src/main/java/tachyon/worker/WorkerStorage.java
- core/src/main/java/tachyon/worker/netty/NettyDataServer.java
- core/src/test/java/tachyon/hadoop/fs/TestDFSIO.java
make default block size consistant with TachyonConf
remove mAvailableBytes in TachyonFS which is not used
remove unused getUsedBytess method in WorkerStorage
remove unused import
> make default block size consistant with TachyonConf and code clean

- LICENSE
- NOTICE
The `NOTICE` file of an Apache licensed project is used to propagate legally required notices such as specific copyright statements or additional restrictions to the downstream consumer.  The current Tachyon `NOTICE` file does not do this despite relying on many other Apache licensed projects which do have things present in their `NOTICE` files
This pull request takes all the required notices and adds them to the `NOTICE` or `LICENSE` as appropriate.  Note that in some cases (e.g. Jetty and Netty) the dependencies had more notices than were propagated but I determined by checking `mvn dependency:tree` output that the artifacts to which the notices pertained were not bundled by Tachyon and so did not require propagation.
The notices from Netty are awkward because they look more like they …
> [TACHYON-281] Propagate required notices to NOTICE file

- core/src/main/java/tachyon/worker/hierarchy/StorageDir.java
- core/src/main/java/tachyon/worker/hierarchy/StorageTier.java
- core/src/test/java/tachyon/worker/hierarchy/AllocateStrategyTest.java
- core/src/test/java/tachyon/worker/hierarchy/EvictStrategyTest.java
- core/src/test/java/tachyon/worker/hierarchy/StorageDirTest.java
In method StorageDir.moveBlock, we make sure the block is locked during copying.
> Lock block before copying it

- core/src/main/java/tachyon/util/UfsUtils.java
- docs/Syncing-the-Underlying-Filesystem.md
Update the documentation since users are running into the fail to parse uri issue. Also make local ufs work properly (to an extent, won't work with file:// prefix, but that can go into 0.7).
> [TACHYON-302] loadufs fix

- core/src/main/java/tachyon/client/RemoteBlockInStream.java
Since multiple reads will most likely occur for each block, trying to find a copy of the block in a worker's memory is very expensive each time and unlikely to succeed after the first failure.
The performance improvement is around 240s -> 10s when reading a 1.5 gb file in HDFS on my local machine.
> [TACHYON-295] Only attempt to read from worker memory once per block stream.

- bin/tachyon
Currently if you use `bin/tachyon runTests` and for whatever reason it
starts failing e.g. misconfiguration using Ctrl+C or `kill` to terminate
it only terminates the current test but still proceeds to run the
subsequent tests.
This commit changes the logic of both runTests and runTest so that if
the JVM receives a signal (whether via Ctrl+C, kill or some other means)
that causes further testing to be aborted.
> Tachyon command should abort tests early if they receive a signal

- core/src/main/java/tachyon/client/BlockOutStream.java
- core/src/main/java/tachyon/client/RemoteBlockInStream.java
- core/src/main/java/tachyon/client/TachyonFile.java
We should use TachyonConf.getBytes instead of getInt or getLong for any configuration value like xMB, xGB. Otherwise it fails to parse the value and always use the default value.
> Use getBytes instead of getInt or getLong for bytes config

- core/src/main/java/tachyon/conf/UserConf.java
- docs/Configuration-Settings.md
The configuration "tachyon.user.remote.read.buffer.size.byte" has a big effect on the remote read performance. The default setting is 1MB. For reading 1GB data from a remote worker in 1Gb/sec ethernet, the client need send 1000+ requests. So it takes about 17 seconds. If we set this buffer size higher (i.e. 8MB), we can read 1GB data from a remote worker more quickly (about 10.5 seconds). Let's use 8MB for now since it is mainly large sequential read currently. Previous discussion can be found at #702
> Set user remote read buffer size to 8MB for better performance

- core/src/main/java/tachyon/Constants.java
- core/src/main/java/tachyon/worker/WorkerStorage.java
Way back in commit 5186b2b782be56c34e8b06ea9d3932c5a0af654f I believe
there was a search and replace of 1000 with SECOND_MS.  Which was
fine, except for the setting
getIntProperty("tachyon.worker.per.thread.checkpoint.cap.mb.sec", Constants.SECOND_MS);
which makes it confusing b/c this configuration field is a rate (MB/sec)
and not a time (sec).
Replace with a less confusing constant.
> Fix errant search and replace

- core/src/main/java/tachyon/Constants.java
- core/src/main/java/tachyon/UnderFileSystemSingleLocal.java
- core/src/main/java/tachyon/client/RemoteBlockInStream.java
- core/src/main/java/tachyon/client/TachyonFS.java
- core/src/main/java/tachyon/conf/TachyonConf.java
- core/src/main/java/tachyon/util/NetworkUtils.java
- core/src/main/java/tachyon/worker/TachyonWorker.java
- core/src/main/java/tachyon/worker/WorkerClient.java
- core/src/main/resources/tachyon-default.properties
- core/src/test/java/tachyon/client/TachyonFSTest.java
- core/src/test/java/tachyon/command/TFsShellTest.java
- core/src/test/java/tachyon/conf/TachyonConfTest.java
- core/src/test/java/tachyon/master/LocalTachyonCluster.java
- core/src/test/java/tachyon/master/LocalTachyonClusterMultiMaster.java
- core/src/test/java/tachyon/master/LocalTachyonMaster.java
Under some network configurations it is possible for Tachyon host name
resolution for the local host to select a host that is not actually
reachable or usable, for example a network broadcast address.  When it
does so Tachyon will hang until such time as the timeout and retry
limits are reached which can be an extremely long time.
This commit improves the local host resolution to ensure that the host
selected is actually reachable and to discount any non-reachable addresses
from use as local hosts.
As part of this it was necessary to add a timeout to the host name
resolution so that it doesn't spend too long waiting to determine if a
particular host name is reachable.  This defaults to 5000 milliseconds
currently, the relevant methods were updated to take a timeout and all
relevant calls …
> Fix Tachyon host name resolution (TACHYON-303)

- docs/Configuration-Settings.md
Adds documentation for the new host resolution timeout configuration
option introduced as part of the TACHYON-303 fix
> Add documentation for host resolution timeout (TACHYON-303)

- core/src/main/java/tachyon/Constants.java
- core/src/main/java/tachyon/client/TachyonFS.java
set default user failed space request limit from 0 to 4.
if setting to 0, no request will be actually executed.
> Fix default user failed space request limit

- core/src/main/java/tachyon/client/TachyonFS.java
- core/src/main/java/tachyon/worker/TachyonWorker.java
- core/src/test/java/tachyon/client/TachyonFSTest.java
when start worker or TFsShell, the master hostname is wrong.
> change error master host name

- core/src/main/java/tachyon/worker/TachyonWorker.java
Currently, when worker starts, the hostname of the master is set to be the worker's host name, which makes Tachyon fail to run on a cluster.
> Fix master address during starting TachyonWorker

- core/src/main/java/tachyon/hadoop/AbstractTFS.java
- core/src/test/java/tachyon/hadoop/TFSRenameTest.java
This patch adds unit tests for the rename operation in TFS and attempts to make it comply with Hadoop FileSystem's behaviors. In particular, exceptions are caught instead of propagated and renaming to an existing directory attempts to move the source into the directory.
The current implementation changes the logic only in the TFS interface, if the behavior makes sense for Tachyon, we should change it in the core code (since TFS defers to TachyonFS here).
> [TACHYON-311] TFS Rename improvements

- docs/Contributing-to-Tachyon.md
The default profile, local-test causes DFSMiniCluster to not be downloaded. To avoid having errors showing, the hdfs-test profile should be used.
> Update documentation for users using intelliJ

- core/src/main/java/tachyon/master/BlockInfo.java
- core/src/test/java/tachyon/master/BlockInfoTest.java
- core/src/test/java/tachyon/master/InodeFileTest.java
When a client read a block from remote workers, it gets the block's locations and try to read it from the remote workers. Some workers may have the block in its MEM, while some may have it in its SSD or HDD. For better performace, we'd better return the the block's locations sorted by MEM, SSD, HDD, etc. So the client reads from a remote worker's memory first.
> Optimize remote reading from hierarchy store

- conf/tachyon-env.sh.template
- libexec/tachyon-config.sh
This option may be used to change the ordering of jars in the Java
classpath in the event of jar conflicts.
This option should help solve TACHYON-291
https://tachyon.atlassian.net/browse/TACHYON-291
> Support TACHYON_PREPEND_TACHYON_CLASSES environment option

- bin/tachyon-workers.sh
The debug statement placed in tachyon-workers.ssh to state which user
account is being used to SSH to the remote workers was wrapped inside an
if by a later commit so it only fired when using non-background SSH
which doesn't aid debugging.  Moved the echo outside of the offending if statement
Also made minor white space changes for readability
> Fix debugging in tachyon-workers.sh

- .gitignore
Adds .DS_STORE to gitignore so mac users won't see those untracked files.
> Ignore .DS_STORE files

- core/pom.xml
- core/src/main/java/tachyon/TachyonURI.java
- core/src/main/java/tachyon/util/NetworkUtils.java
- core/src/main/java/tachyon/util/UfsUtils.java
- core/src/test/java/tachyon/TachyonURITest.java
Makes transient dependencies of shaded thrift visible so they can be excluded.
Allow uris without port to support s3.
Fix bugs in loadufs to support s3.
> Provide compatibility for s3/spark

- core/src/main/java/tachyon/TachyonURI.java
- core/src/main/java/tachyon/util/NetworkUtils.java
- core/src/test/java/tachyon/TachyonURITest.java
TachyonURI parses URIs from strings incorrectly in cases where the
authority does not contain a port.  Since the port is an optional
component of the authority (see RFC 3986 Section 3.2) this is incorrect.
This wrong assumption means that Tachyon can treat some URIs as not
having authorities causing them to get mangled and produce odd error
messages as reported in [TACHYON-289](https://tachyon.atlassian.net/browse/TACHYON-289)
This commit corrects the parsing of the authority component and updates
the corresponding tests to cover authorities without ports and correct
existing tests that were using this wrong assumption.
NetworkUtils.replaceHostName() is also appropriately updated to not
include a port if there wasn't one to start with
> Fix TachyonURI authority parsing (TACHYON-289)

- core/src/main/java/tachyon/worker/TachyonWorker.java
- core/src/test/java/tachyon/master/LocalTachyonCluster.java
- core/src/test/java/tachyon/master/LocalTachyonClusterMultiMaster.java
Currently, the TachyonConf is not updated when creating worker.
this change makes Tachyon always create worker through createWorker(TachyonConf conf) API.
> Simplify call hierarchy of createWorker in TachyonWorker

- docs/Contributing-to-Tachyon.md
https://tachyon.atlassian.net/browse/TACHYON-339
The contractTest profile has the most requirements of the profiles so it should be used to avoid import issues in ides.
> [TACHYON-339] Update docs to reflect contract tests.

- core/src/main/java/tachyon/command/TFsShell.java
- core/src/test/java/tachyon/command/TFsShellTest.java
1. Fix the incorrect output for tfs rm on non-exiting files.
2. Modify rmNonexistingFileTest
3. Add rmNonexistingDirTest
> TACHYON-337: fix tfs rm output for non-existing files

- perf/bin/tachyon-perf
- perf/bin/tachyon-perf-collect
- perf/conf/tachyon-perf-env.sh.template
- perf/libexec/tachyon-perf-config.sh
When Tachyon Perf is installed on a shared file system visible to all nodes
there is no need to do an scp to distribute the config nor to do an scp to
collect the results.
This commit adds a new variable to the config that when set will omit these scp
steps in favour of no-ops (for deploy) and local cp for collect
Also corrects the incorrect version in the JAR specified in `tachyon-perf-config.sh`
> Improve support for Tachyon Perf on Shared FS

- perf/conf/test-case.xml
- perf/conf/testsuite/Mixture.xml
- perf/src/main/java/tachyon/perf/benchmark/Operators.java
- perf/src/main/java/tachyon/perf/benchmark/mixture/MixtureTask.java
- perf/src/main/java/tachyon/perf/benchmark/mixture/MixtureTaskContext.java
- perf/src/main/java/tachyon/perf/benchmark/mixture/MixtureThread.java
Add a workload named 'Mixture'.
In this workload, each Perf Slave reads and writes files in a configured ratio. Different from SimpleRead and SimpleWrite workloads, this workload may read and write files at one time.
> [TACHYON-340] Add workload 'Mixture' to Tachyon Perf

- deploy/vagrant/Vagrantfile
- deploy/vagrant/conf/ec2-config.yml
- deploy/vagrant/core/config_aws.rb
https://tachyon.atlassian.net/browse/TACHYON-335
This isn't a complete fix for this issue, but this will allow the user to make larger/more ebs volumes. Without specifying block device mappings, the disk provided will only be 10GB.
> [TACHYON-335] Vagrant block device mapping for AWS

- deploy/vagrant/ufs/hadoop1/init.sh
- deploy/vagrant/ufs/hadoop2/init.sh
https://tachyon.atlassian.net/projects/TACHYON/issues/TACHYON-341
Previously the workers file would be ignored and hdfs would run with only 1 data node (localhost).
> [TACHYON-341] Use slaves file for Vagrant deploys with hadoop

- core/src/main/java/tachyon/worker/eviction/EvictLRU.java
- core/src/main/java/tachyon/worker/eviction/EvictPartialLRU.java
It's possible that a block is deleted just after we think it as a candidate to evict. For a non-exist block, getBlockSize return -1. It doesn't make sense to use -1 as block size and continue other calculations.
> Omit non-exist blocks in the eviction algorithm

- core/src/main/java/tachyon/Format.java
https://tachyon.atlassian.net/projects/TACHYON/issues/TACHYON-345
Previously we would attempt to format all of the folders in the storage directory path. This will cause null pointers if a folder cannot be read due to permissions.
> [TACHYON-345] Format tachyon worker data directory only.

- core/src/main/java/tachyon/UnderFileSystemHdfs.java
we have seen cases where the path gets mapped to another URL, leading to a base dir path that is longer than the file path.  Add this warning message to catch it early.
>  add warning message to UnderFileSystemHdfs list()

- core/pom.xml
https://tachyon.atlassian.net/projects/TACHYON/issues/TACHYON-347
Promote transitive dependencies causes everything to be promoted and not just thrift's dependencies.
> [TACHYON-347] Do not promote transitive dependencies.

- perf/bin/tachyon-perf
- perf/bin/tachyon-perf-start.sh
- perf/conf/log4j.properties
When running Tachyon perf on a shared file system all the slaves log to a single
log file `slaves.log` which means their logging is interleaved and hard to read.
This commit parameterizes the name of the slaves log file to add the slave ID to
the log file name e.g. `slave-1.log`
> Parameterize Perf slave log file names

- core/src/main/java/tachyon/client/BlockOutStream.java
JIRA Issue: https://tachyon.atlassian.net/browse/TACHYON-348
Changing if condition for reducing the buffer copy and write frequency.
For input byte array is consitent and capacity is `userFileBufferBytes/2`, it should be put into Buffer twice for making full use of the Buffer.
For input byte array is consistent and capacity greater than `userFileBufferBytes/2` and less than `userFileBufferBytes`, it should be written to mapped file directly instead of copying to Buffer.
> [TACHYON-348]Modify if condition for reducing buffer copy and write frequency in BlockOutStream

- core/pom.xml
https://tachyon.atlassian.net/browse/TACHYON-350
Removes the ufs for contract test profile (property still required) and fixes the hadoop version to 2.6.0 so it can be run automatically by Jenkins (which will vary the hadoop.version property).
> [TACHYON-350] Clean up contract test profile.

- perf/README.md
- perf/bin/tachyon-perf
- perf/conf/test-case.xml
- perf/conf/testsuite/Iterate.xml
- perf/src/main/java/tachyon/perf/benchmark/iterate/IterateTask.java
- perf/src/main/java/tachyon/perf/benchmark/iterate/IterateTaskContext.java
- perf/src/main/java/tachyon/perf/benchmark/iterate/IterateThread.java
This workload tests in an iterative way - the output of the former iteration is the input of the next one.
Besides, two modes called _Shuffle_ and _Non-Shuffle_ are provided. In the _Shuffle_ mode, it reads files from the whole workspace, which may lead to remote reading across the cluster network. In the _Non-Shuffle_ mode, it only reads the files written by itself, which keeps good locality.
> [TACHYON-357] Add workload 'Iterate' to Tachyon Perf

- core/src/main/java/tachyon/master/MasterInfo.java
https://tachyon.atlassian.net/browse/TACHYON-359
In MasterInfo,  mLostWorkers is initialized to a fixed size queue (size = 32), when we have more than 32 failed workers, it would throw an exception as follows:
2015-04-02 17:30:29,144 ERROR server.TThreadPoolServer (TThreadPoolServer.java:run) - Error occurred during processing of message.
java.lang.IllegalStateException: Queue full
at java.util.AbstractQueue.add(AbstractQueue.java:71)
at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:209)
at tachyon.master.MasterInfo.registerWorker(MasterInfo.java:2065)
at tachyon.master.MasterServiceHandler.worker_register(MasterServiceHandler.java:3
26)        at tachyon.thrift.MasterService$Processor$worker_register.getResult(MasterService.java:2445)
at …
> [TACHYON-359] fix for tachyon 359

- core/src/main/java/tachyon/Format.java
https://tachyon.atlassian.net/browse/TACHYON-346
Otherwise it might try to create a folder instead of a mounted fs.
> [TACHYON-346] Check if the data directory exists before trying to format.

- core/src/main/java/tachyon/client/FileOutStream.java
getBlockIdBasedOnOffset should be avoided when getBlockId(offset) can be used. tOff += tLen statement is redundant.
> Code cleanup. Remove unnessary function calls/operations

- core/src/main/java/tachyon/client/TachyonFile.java
Follow up for 806, since it removed the only usage of this method.
> Remove unused method

- core/pom.xml
It is no longer necessary and causes the dependency tree to become excessively large.
> Remove promote transitive dependencies

- core/src/main/java/tachyon/master/TachyonMaster.java
- core/src/main/java/tachyon/underfs/UnderFileSystem.java
https://tachyon.atlassian.net/browse/TACHYON-349
In this change, we abstract the isFormatted method from TachyonMaster, instead, the Under File Systems should provide a function to check whether a directory is formatted or not.
> [TACHYON-349] Format the underlying FS only if the underlying FS provides storage

- perf/bin/tachyon-perf
- perf/bin/tachyon-perf-collect
In tachyon-perf, you can write multi slaves in conf/slaves and they will have different IDs.
This PR fixes the bug that those slaves are sorted in some scripts and not sorted in others. For example, if you set conf/slaves as below:
slave1
slave2
slave1
It must have the same IDs in all the scripts.
> Fix slaves sort in perf's script

- .gitignore
- perf/conf/tachyon-perf-env.sh.template
- perf/src/main/java/tachyon/perf/PerfConstants.java
- perf/src/main/java/tachyon/perf/SlaveStatus.java
- perf/src/main/java/tachyon/perf/benchmark/Operators.java
- perf/src/main/java/tachyon/perf/benchmark/iterate/IterateThread.java
- perf/src/main/java/tachyon/perf/benchmark/metadata/MetadataThread.java
- perf/src/main/java/tachyon/perf/benchmark/mixture/MixtureThread.java
- perf/src/main/java/tachyon/perf/benchmark/simpleread/SimpleReadTask.java
- perf/src/main/java/tachyon/perf/benchmark/simpleread/SimpleReadThread.java
- perf/src/main/java/tachyon/perf/benchmark/simplewrite/SimpleWriteThread.java
- perf/src/main/java/tachyon/perf/benchmark/skipread/SkipReadTask.java
- perf/src/main/java/tachyon/perf/benchmark/skipread/SkipReadThread.java
- perf/src/main/java/tachyon/perf/fs/HDFSPerfFS.java
- perf/src/main/java/tachyon/perf/fs/PerfFS.java
- perf/src/main/java/tachyon/perf/fs/THCIPerfFS.java
- perf/src/main/java/tachyon/perf/fs/TachyonPerfFS.java
- perf/src/main/java/tachyon/perf/tools/TachyonPerfCleaner.java
Some code I wrote when benchmarking different client implementations in Tachyon Perf (specifically AbstractTFS and Hadoop's File System client).
The overall idea was to extract the current implementation of `PerfFileSystem` and make it into an interface, `PerfFS`. Then implement that interface with various different clients (ie. `TachyonPerfFS`, `THCIPerfFS`). This will allow tests to be made using the common interface and be extended to a variety of client implementations.
The filesystem to be used is specified through the config `TACHYON_PERF_UFS`. Currently it is just a string matching switch in `PerfConstants`, but it can be refactored to be more versatile if needed.
> Perf FileSystem Interface

- bin/tachyon
- bin/tachyon-start.sh
- conf/log4j.properties
- conf/tachyon-env.sh.template
- core/src/main/java/tachyon/Constants.java
- core/src/main/java/tachyon/web/WebInterfaceBrowseLogsServlet.java
- core/src/main/resources/tachyon-default.properties
- docs/Configuration-Settings.md
Enable web UI to support custom log directory. 
To use a custom log directory, a user can export TACHYON_LOGS_DIR in tachyon-env.sh
> Support custom log directory

- perf/bin/configure.xsl
- perf/bin/tachyon-perf-configure
- perf/bin/tachyon-perf-repeat
Test cases as they stand are configured via XML files which while nice
for humans to edit are something of a pain to script against.  This
commit adds a script that levarages the `xsltproc` command line tool to
automatically transform a configuration file.
The intent of the script is to make it easy for end users to script up
their benchmarks so that they can script a set of runs with different
configuration parameters without having to manually edit the XML files
between each run.
> [TACHYON-373] Add a script which helps with the configuration of test cases

- core/src/main/java/tachyon/web/WebInterfaceConfigurationServlet.java
https://tachyon.atlassian.net/browse/TACHYON-380
This just makes the `${value}` parts of the conf resolved to the correct conf values. 
For example: `${tachyon.home}/core/src/main/webapp` will now be `/tachyon/core/src/main/webapp` if `tachyon.home` is set to `/tachyon`
Path resolution is more complicated because there is no indicator of whether or not a config value is a path.
> [TACHYON-380] Resolve Values in ConfUI

- libexec/tachyon-config.sh
Now, path related to tachyon.home in system configuration in web UI is displayed as:
tachyon.home	/tachyon/libexec/..
tachyon.master.journal.folder	/tachyon/libexec/../journal/
the root cause is not in codes of web ui, but in libexec/tachyon-config.sh.
> [TACHYON-380] Resolved path in web UI

- core/src/main/java/tachyon/hadoop/AbstractTFS.java
This reverts commit ddfabdb07b3bf7a62975e5a9cb9c8b0a3232f114.
Method delete is deprecated but should not be removed for now as this is required to be overriden if we want to extend AbstractTFS from org.apache.hadoop.fs.FileSystem.
> Revert "Remove deprecated API method delete from AbstractTFS"

- deploy/vagrant/provision/device.sh
- deploy/vagrant/provision/playbook.yaml
- docs/Running-Tachyon-on-AWS.md
- docs/Running-Tachyon-on-Container.md
- docs/Running-Tachyon-on-OpenStack.md
- docs/Running-Tachyon-on-VirtualBox.md
The purpose and design considerations are explained in vagrant/provision/device.sh in the first commit.
> [TACHYON-335] Automatically mount all block device mappings

- core/src/main/java/tachyon/client/TachyonFS.java
https://tachyon.atlassian.net/browse/TACHYON-397
> [TACHYON-398] add get(String path) as deprecated method in TachyonFS

- core/src/main/webapp/browse-body.jsp
- core/src/main/webapp/browse-pagination-header.jsp
- core/src/main/webapp/configuration.jsp
- core/src/main/webapp/dependency.jsp
- core/src/main/webapp/footer-scripts.jsp
- core/src/main/webapp/footer.jsp
- core/src/main/webapp/general.jsp
- core/src/main/webapp/header-scripts.jsp
- core/src/main/webapp/header.jsp
- core/src/main/webapp/js/autorefresh.js
- core/src/main/webapp/memory-pagination-header.jsp
- core/src/main/webapp/memory.jsp
- core/src/main/webapp/viewFile-body.jsp
- core/src/main/webapp/workers.jsp
This commits adds auto-refresh functionality to the Web UI which is
useful if you are keeping an eye on Tachyon's state and don't want to
have to hit Refresh manually.
Auto-Refresh is off by default and is toggled on via a link in the top
navigation.  Once enabled the page will refresh after 15 seconds and
auto-refresh remains enabled on page reload.
Refresh uses `window.location.replace()` so it does not fill the users
history and the back button will work normally
As part of this commit the JSPs were refactored slightly to pull the
script definitions out into includeable JSPs.  One for scripts that need
to appear at the start of a page and one for scripts that must appear at
the end of the page.
> [TACHYON-390] Add auto-refresh functionality to Web UI

- core/src/main/java/tachyon/command/TFsShell.java
- core/src/test/java/tachyon/command/TFsShellTest.java
https://tachyon.atlassian.net/browse/TACHYON-403
Fix exception when tail an empty file.
Remove the <path> parameter in getUsedBytes, getCapacityBytes.
Add error message when operation mv is failed.
> [TACHYON-403] Fix exception in TFsShell

- core/src/main/java/tachyon/Constants.java
- core/src/main/java/tachyon/client/BlockInStream.java
- core/src/main/java/tachyon/client/RemoteBlockInStream.java
- core/src/main/java/tachyon/client/TachyonFile.java
- core/src/test/java/tachyon/client/BlockInStreamTest.java
allow user to disable local read through tachyon.user.localread.disable, default to false.
tachyon.user.localwrite.disable is also added but not used.
test case added.
JIRA: https://tachyon.atlassian.net/browse/TACHYON-53
see comments in the JIRA for more details.
> [TACHYON-100] Let user disable local read/writes

- core/src/test/java/tachyon/underfs/UnderStorageSystemInterfaceTest.java
https://tachyon.atlassian.net/browse/TACHYON-420
Currently this will test the LocalUnderFileSystem and the HDFSUnderFileSystem implementations when they are run in the core and hdfs modules respectively.
These tests will help define the expected behavior of under file system clients and make it easier to do sanity checks when implementing new clients.
> [TACHYON-420] Add UnderFileSystem interface tests

- client/pom.xml
https://tachyon.atlassian.net/browse/TACHYON-421
If signature files are included in the client jar, they will not be filtered out because it does not match the *:* artifact pattern. Therefore, we should filter out the signature files when we create the client jar to ensure there are no signature files included in the uber jar.
> [TACHYON-421] Filter signature files in shade execution for client module.

- bin/tachyon
After refactoring, it is now under `tachyon.underfs` instead of `tachyon.util`
> [TACHYON-419] Fix loadufs class name.

- docs/Running-Spark-on-Tachyon.md
Documentation for configuring Spark with Tachyon FT mode shows wrong value for fs.tachyon-ft.impl
<property>
<name>fs.tachyon-ft.impl</name>
<value>tachyon.hadoop.TFS</value>
</property>
It should be ..
<property>
<name>fs.tachyon-ft.impl</name>
<value>tachyon.hadoop.TFSFT</value>
</property>
> TACHYON-427 : Running Spark on Tachyon Documentation need correction

- deploy/vagrant/Vagrantfile
- deploy/vagrant/core/EnvSetup.rb
- deploy/vagrant/provision/playbook.yaml
- deploy/vagrant/spark_version.yml
- deploy/vagrant/tachyon_version.yml
- deploy/vagrant/ufs/hadoop1/init.sh
- docs/Running-Specific-Version-Of-Tachyon-Or-Spark-Via-Vagrant.md
https://tachyon.atlassian.net/browse/TACHYON-408
currently, use deploy module forces you to compile tachyon/spark, it's too time consuming
with this PR, you can choose to deploy tachyon/spark releases, the process should be in 10min with ./run_vb.sh
> [TACHYON-408] add option to vagrant deployment to deploy public releases

- core/src/main/java/tachyon/client/TachyonFS.java
https://tachyon.atlassian.net/browse/TACHYON-397
We should support backward compatibility for at least 1 version. For example, spark recently updated to use the TachyonURI API instead of the String API, which makes it incompatible with master branch without this addition.
> [TACHYON-397] Add deprecated method for 0.6.x's TachyonFS.get(TachyonURI).

- client/pom.xml
- common/src/main/java/tachyon/Constants.java
- common/src/main/java/tachyon/underfs/UnderFileSystem.java
- core/src/main/java/tachyon/hadoop/Utils.java
- core/src/test/java/tachyon/client/BlockInStreamTest.java
- core/src/test/java/tachyon/underfs/UnderFileSystemCluster.java
- core/src/test/java/tachyon/underfs/UnderStorageSystemInterfaceTest.java
- docs/Setup-UFS.md
- libexec/tachyon-config.sh
- underfs/hdfs/pom.xml
- underfs/pom.xml
- underfs/s3/pom.xml
- underfs/s3/src/main/java/tachyon/underfs/s3/S3OutputStream.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3UnderFileSystem.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3UnderFileSystemFactory.java
- underfs/s3/src/main/resources/META-INF/services/tachyon.underfs.UnderFileSystemFactory
- underfs/s3/src/test/java/tachyon/underfs/s3/S3UnderFileSystemTest.java
- underfs/s3/src/test/java/tachyon/underfs/s3/S3UnderStorageCluster.java
- underfs/s3/src/test/resources/log4j.properties
Rebased version of #891 
https://tachyon.atlassian.net/projects/TACHYON/issues/TACHYON-424
This PR implements an S3 Client using the jets3t library.
A new s3 submodule under /underfs contains the logic for the client. The user may enable this client as their s3 client by removing the s3n:// prefix from the hadoop prefixes in their configuration.
The implementation conforms to our UnderFileSystem interface and unit tests. It also passes all applicable core tests when using the S3UnderFileSystemCluster. Since the S3UnderFileSystem is implemented as a real S3 backend, the tests are disabled by default.
> [TACHYON-424] S3 client v2

- underfs/glusterfs/pom.xml
- underfs/hdfs/pom.xml
- underfs/hdfs/src/test/resources/test_metrics.properties
- underfs/s3/pom.xml
https://tachyon.atlassian.net/projects/TACHYON/issues/TACHYON-438
Cleans up poms for the underfs modules since they should no longer need to pull in test classes from the core (these are in integration-tests now).
> [TACHYON-438] Clean up poms

- core/src/main/java/tachyon/metrics/MetricsConfig.java
- core/src/main/java/tachyon/metrics/MetricsSystem.java
- core/src/test/java/tachyon/metrics/MetricsConfigTest.java
- core/src/test/java/tachyon/metrics/MetricsSystemTest.java
- core/src/test/resources/test_metrics.properties
https://tachyon.atlassian.net/browse/TACHYON-415
The metrics system tests are not stable because the test_metrics.properties file fails to be loaded randomly. 
This PR removes the file and set the properites in code.
> [TACHYON-415] Make metrics system tests stable

- common/src/main/java/tachyon/Constants.java
- core/src/main/java/tachyon/worker/netty/NettyDataServer.java
- integration-tests/src/test/java/tachyon/master/LocalTachyonCluster.java
https://tachyon.atlassian.net/projects/TACHYON/issues/TACHYON-445
Total test run time goes down by ~50% on my local machine with this change. Two new internal (not documented to users) settings are added which control the nature of the netty data server shutdown. The default values are the same as if `shutdownGracefully` is called without parameters.
> [TACHYON-445] Faster Data Server shutdown in unit tests

- common/src/main/java/tachyon/underfs/UnderFileSystemRegistry.java
I've encountered this error message when testing S3 as ufs. 
A typical error is "java.lang.NoSuchMethodError:  org.jets3t.service.impl.rest.httpclient.RestS3Service"
but e.getMessage() only returns the later part, that's confusing when I first encounter the error, I don't know what's wrong with this class.
> more explicit error message when no suitable ufs is found

- clients/unshaded/pom.xml
- common/pom.xml
- examples/pom.xml
- integration-tests/pom.xml
- pom.xml
- servers/pom.xml
- shell/pom.xml
https://tachyon.atlassian.net/browse/TACHYON-442
Further cleanup the pom files, focusing on maven-surefire-plugin and maven-compiler-plugin.
> [TACHYON-442] Apply PluginManagement to cleanup pom.xml in each module

- clients/unshaded/src/main/java/tachyon/client/RemoteBlockInStream.java
https://tachyon.atlassian.net/browse/TACHYON-467
tachyon.user.remote.read.buffer.size.byte is set to 8MB as a default value. This is set in the tachyon-default.properties. But in RemoteBlockInStream.java, it still uses 1MB as a default value if this property is not set. A client process without the tachyon-default.properties on the class path may still use 1MB as the remote read buffer size.
> [TACHYON-467] Client may still use a small remote read buffer size

- common/src/main/java/tachyon/Constants.java
- docs/Configuration-Settings.md
- servers/src/main/java/tachyon/master/TachyonMaster.java
A config option to set the address the master listens to.
- if unspecified, master just listens on hostname (current behavior)
- if specified to "*", master listens on all addresses
- otherwise, the master listens on the specified hostname
> [TACHYON-368] master listening address configuration option

- core/src/main/java/tachyon/master/TachyonMaster.java
In case of complex network configuration for Tachyon cluster, like when working in AWS with Elastic IP attached to Tachyon master machine, external IP or DNS may not be related to addresses attached to the instance. Moreover, in such case external IP is undiscoverable at the instance itself. Same happen when working behind NATs or load balancers.
> [TACHYON-368] Listen on wildcard address on master

- servers/src/main/java/tachyon/worker/TachyonWorker.java
https://tachyon.atlassian.net/browse/TACHYON-468
The worker will access the under file system when initializing the WorkerStorage. If the under file system is secured HDFS, it will fail as it has not yet logined.
> [TACHYON-468] Tachyon worker fails to start when under file system is secured HDFS

- underfs/s3/src/main/java/tachyon/underfs/s3/S3OutputStream.java
https://tachyon.atlassian.net/browse/TACHYON-424
Instead of using the jets3t convenience method to calculate MD5, we calculate it in the stream. This will give a large performance boost for large files due to the MD5 calculation being the bottleneck in machines with less CPU resource.
On a 5 node cluster of r3.large machines, there is a write performance increase of ~60%.
> [TACHYON-424] Calculate MD5 in S3OutputStream

- servers/src/main/java/tachyon/worker/tiered/StorageTier.java
1. currently when failed to request space, both client side and server(worker) side will retry the request again, but the retry time is configured by  USER_FAILED_SPACE_REQUEST which is a user configuration. 
this patch removes the configuration on the server side, make it configured on client side.
> [TACHYON-475] Simplify the requestSpace logic in StorageTier

- servers/src/test/java/tachyon/worker/tiered/StorageTierTest.java
Remove request space and update temporary block allocated bytes operation in createBlockFile function, because such operations have been done in test cases, or the space will be requested twice.
> [TACHYON-480] Fix test cases in StorageTierTest

- servers/src/main/java/tachyon/worker/netty/NettyDataServer.java
TachyonConf.getInt can't parse "KB",  change  getInt to getBytes
> [Small Fix] Fix tachyon.worker.network.netty.watermark.low/high number

- docs/_plugins/copy_javadoc_to_docs.rb
- pom.xml
Fix TACHYON-490, it requires to run `mvn javadoc:javadoc` and `mvn site:site` first.
https://tachyon.atlassian.net/browse/TACHYON-490
> [TACHYON-490] Fix the Javadoc

- servers/src/main/java/tachyon/worker/eviction/EvictLRU.java
- servers/src/main/java/tachyon/worker/eviction/EvictLRUBase.java
- servers/src/main/java/tachyon/worker/eviction/EvictPartialLRU.java
Add evicting block list to record the blocks that is being evicted, so that blocks that are evicting by another thread will not be chosen by current thread again
> [TACHYON-476] Improve eviction strategy by adding evicting block list

- servers/src/main/java/tachyon/worker/netty/NettyDataServer.java
https://tachyon.atlassian.net/browse/TACHYON-489
this is a cosmetic change: add a space between the type cast and the variable so as to conform with the coding style
> [TACHYON-489] coding style: add a space between type cast and the variable

- servers/src/test/java/tachyon/underfs/UnderFileSystemCluster.java
- underfs/s3/pom.xml
- underfs/s3/src/main/java/tachyon/underfs/s3/S3InputStream.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3UnderFileSystem.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3UnderFileSystemFactory.java
https://tachyon.atlassian.net/browse/TACHYON-424
This patch fixes a few issues with S3 client's read performance related to multiblock reads. The performance gain is linear in the number of blocks of the file, ie 10x for a file with 10 blocks.
1. A faster skip is implemented to avoid reading and discarding bytes. This becomes very costly when skipping a large number of bytes.
2. The jets3t version is changed to 0.8.1. This is because the implementation of the inputstream from s3 does not efficiently close (reads the entire file before closing).
> [TACHYON-424] S3 input stream in S3 client

- deploy/vagrant/provision/roles/spark/files/spark-defaults.sh
- deploy/vagrant/provision/roles/spark/tasks/config.yml
- deploy/vagrant/provision/roles/spark/tasks/start.yml
since deploy/vagrant is mainly used for testing, enabling spark eventlog and history server is needed for monitoring and debugging, this PR enables these two features by default. Did not make them optional because they are common use cases.
> [TACHYON-478] Enable spark eventlog in deploy/vagrant

- perf/README.md
- perf/bin/tachyon-perf-log-collect
This script supports user to get the worker logs from a failed worker to the master instead of ssh to the workers. https://tachyon.atlassian.net/browse/TACHYON-358
The usage is `bin/tachyon-perf-log-collect all` or `bin/tachyon-perf-log-collect node1 node2 ...`
The collected logs will be under ${tachyon.perf.home}/logs/collected-logs, in different node-named directories.
> [TACHYON-358] [Tachyon-Perf] Add a utility to support collecting worker logs from master

- deploy/vagrant/conf/spark_version.yml
- deploy/vagrant/conf/tachyon_version.yml
- docs/Running-Specific-Version-Of-Tachyon-Or-Spark-Via-Vagrant.md
Updated the Tachyon and Spark versions in the Vagrant configuration and documentation
Tachyon version: 0.5.0 => 0.6.4
Spark version: 1.3.1 => 1.4.0
> Updated Tachyon and Spark versions in Vegrant config and doc

- perf/README.md
- perf/bin/tachyon-perf
- perf/conf/test-case.xml
- perf/conf/testsuite/Massive.xml
- perf/src/main/java/tachyon/perf/benchmark/massive/MassiveTask.java
- perf/src/main/java/tachyon/perf/benchmark/massive/MassiveTaskContext.java
- perf/src/main/java/tachyon/perf/benchmark/massive/MassiveThread.java
The related JIRA https://tachyon.atlassian.net/browse/TACHYON-502
This is an addition to https://tachyon.atlassian.net/browse/TACHYON-326
Current there are several workloads in perf with some access patterns. This Massive workload doesn't have a determined access pattern, but to randomly choose read or write for some time concurrently.
This workload does not aim to show the excellent performance of tachyon but to find out the potential issues or bugs.
> [TACHYON-502] [TACHYON-506] Add 'Massive' workload to the perf module and update perf's README

- servers/src/main/java/tachyon/worker/tiered/StorageDir.java
GetLockedBlockSize in StorageDir will iterate on mUserPerLockedBlock in StorageDir, but did not make it synchronized, during the iteration, the mUserPerLockedBlock may be changed in lockBlock/unlockBlock, and ConcurrentModificationException will be thrown.
> [TACHYON-507] Fix ConcurrentModificationException in StorageDir

- clients/unshaded/src/main/java/tachyon/client/FileOutStream.java
Simplify FileOutStream, remove some duplicated variables
mCurrentBlockLeftByte: can be gotten from mCurrentBlockOutStream.getRemainingSpaceByte()
mCurrentBlockId: can be gotten from mCurrentBlockOutStream.getBlockId()
This change makes sure there is only one variable to record the information, which also helps to make the information consistent.
> [TACHYON-508] Simplify FileOutStream

- clients/unshaded/pom.xml
- clients/unshaded/src/main/java/tachyon/client/TachyonFS.java
- clients/unshaded/src/main/java/tachyon/client/netty/ClientHandler.java
- clients/unshaded/src/main/java/tachyon/client/netty/NettyRemoteBlockReader.java
- clients/unshaded/src/main/java/tachyon/client/netty/SingleResponseListener.java
- common/pom.xml
- common/src/main/java/tachyon/Constants.java
- common/src/main/java/tachyon/network/NettyUtils.java
- common/src/main/java/tachyon/network/protocol/RPCBlockResponse.java
- common/src/main/java/tachyon/util/ThreadFactoryUtils.java
- common/src/main/resources/tachyon-default.properties
- integration-tests/src/test/java/tachyon/IntegrationTestConstants.java
- integration-tests/src/test/java/tachyon/client/RemoteBlockInStreamIntegrationTest.java
- integration-tests/src/test/java/tachyon/worker/DataServerIntegrationTest.java
- servers/pom.xml
- servers/src/main/java/tachyon/master/TachyonMaster.java
- servers/src/main/java/tachyon/worker/TachyonWorker.java
- servers/src/main/java/tachyon/worker/WorkerStorage.java
- servers/src/main/java/tachyon/worker/netty/NettyDataServer.java
https://tachyon.atlassian.net/browse/TACHYON-495
This PR introduces a new remote block reader that uses Netty to communicate with the network. The Netty based block reader should eventually replace the existing TCP one, since Netty is far easier to maintain/extend.
> [TACHYON-495] Refactor remote block reader to use Netty

- integration-tests/pom.xml
- servers/pom.xml
- shell/pom.xml
While many of the dependencies were extracted, there are still a few classes that are required by other tests, so the test jars are still necessary.
> [TACHYON-444] Fix test-jar dependencies

- servers/src/main/java/tachyon/worker/block/BlockMetadataManager.java
The storage dir in BlockMeta need to be updated when we move a BlockMeta.
> Update the dir in BlockMeta when moving BlockMeta

- clients/unshaded/src/main/java/tachyon/client/ReadType.java
- clients/unshaded/src/main/java/tachyon/client/WriteType.java
[TACHYON-577] Remove redundant modifier "private" in tachyon.client.ReadType constructor
[TACHYON-576] Remove redundant modifier "private" in tachyon.client.WriteType constructor
> [TACHYON-576] [TACHYON-577] remove redundant modifier private in enum constructor

- servers/src/main/java/tachyon/worker/block/BlockLockManager.java
Original PR to branch 'reabsed_worker_wip' (https://github.com/amplab/tachyon/pull/1029), now directly pull-requesting to master branch because 'reabsed_worker_wip' is merged into master.
The goal of this PR is to improve the mapping from blockId to locks in `BlockLockManager`.
We use `murmur3_32` from Guava as the hashing function, afters apply abs and modulo to make sure `hashValue` falls in [0, NUM_LOCKS-1].
Note #1037 is also closed because of messy commit history.
> [TACHYON-596] Improve hash of blockId so mapping to locks is more evenly distributed

- common/src/main/java/tachyon/util/CommonUtils.java
- common/src/test/java/tachyon/util/CommonUtilsTest.java
https://tachyon.atlassian.net/browse/TACHYON-565
Fix [TACHYON-565] Fix String equals bug in CommonUtils.
Previously proposed solution is trimmedPath.equals(""), but it is not null-safe and with potential performance overhead (see http://howtodoinjava.com/2013/03/31/always-use-length-instead-of-equals-to-check-empty-string-in-java/). A null-safe solution is "".equals(trimmedPath), but it does not fall into "continue" when trimmedPath is NULL. I guess the original intention is to "continue" whenever trimmedPath is NULL or empty, though trimFrom(path) will always return "".
> [TACHYON-565] Fix String equals bug in CommonUtils

- integration-tests/src/test/java/tachyon/client/FileOutStreamIntegrationTest.java
This fixes a bug in an hdfs test that the remote write PR introduced.
> [TACHYON-108] Disable hdfs client cache correctly

- common/src/main/java/tachyon/network/protocol/RPCMessageEncoder.java
[TACHYON-559] Removed variable 'LOG'  in RPCMEssageEncoder.java
https://tachyon.atlassian.net/browse/TACHYON-559
sorry for my terrible git operation
> [TACHYON-559] Removed variable 'LOG'  in RPCMEssageEncoder.java

- integration-tests/src/test/java/tachyon/client/FileOutStreamIntegrationTest.java
- integration-tests/src/test/java/tachyon/client/RemoteBlockInStreamIntegrationTest.java
Two fixes to make the remote tests more stable:
- The remote read test was not clearing settings.
- The remote write test should only use the Netty data server (NIO data server does not support writes).
> [TACHYON-108] Fix flaky remote write integration test

- servers/src/main/java/tachyon/worker/block/BlockMetadataManager.java
- servers/src/main/java/tachyon/worker/block/TieredBlockStore.java
- servers/src/main/java/tachyon/worker/block/meta/StorageDir.java
- servers/src/test/java/tachyon/worker/block/BlockMetadataManagerTest.java
- servers/src/test/java/tachyon/worker/block/meta/StorageDirTest.java
https://tachyon.atlassian.net/browse/TACHYON-617
This deals with the following race condition:
Storage device full, ie. 1 GB user temp data, 9 GB data (10 GB total)
1. Clean up user
2. User metadata is cleaned up, worker thinks it has 1 GB free space, but the device is really full.
3. Space is requested and used before the data on the device is deleted.
This will cause out of space exception on a storage device or overflow the ramdisk possibly causing out of memory errors in other processes or the Tachyon worker.
> [TACHYON-617] Worker cleanup fix

- common/src/main/java/tachyon/Constants.java
- common/src/main/java/tachyon/security/authentication/AuthenticationFactory.java
- common/src/main/resources/tachyon-default.properties
- common/src/test/java/tachyon/security/authentication/AuthenticationFactoryTest.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-614
This patch adds a parameter to switch authentication mode in Tachyon configuration. Build a main entry class for authentication feature. It should provide methods invoked by original code based on different mode.
@calvinjia , @ooq , @apc999 , do you think we should set the default mode to `NOSASL` (security disabled) or `SIMPLE`?
> [TACHYON-614] Add authentication configuration and main entry

- common/src/main/java/tachyon/security/UserInformation.java
- common/src/main/java/tachyon/util/PlatformUtils.java
- common/src/test/java/tachyon/security/LoginModuleTest.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-601
This is the 1st step to implement LOGIN mechanism.
This patch adds a OS_LOGIN_MODULE following JAAS framework. This module leverages JAAS provided different OS LoingModule (such as com.sun.security.auth.module.UnixLoginModule) to import an OS user and associate it with current Subject.
> [TACHYON-601] Login Mechanism: Add OS_LOGIN_MODULE

- deploy/vagrant/core/config_aws.rb
Default environment variables vagrant looks for are different from our settings: `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
> [SMALLFIX] explicitly set aws credentials

- clients/unshaded/src/main/java/tachyon/client/FileOutStream.java
- clients/unshaded/src/main/java/tachyon/client/LocalBlockOutStream.java
- clients/unshaded/src/main/java/tachyon/client/RemoteBlockOutStream.java
- common/src/main/java/tachyon/Constants.java
- common/src/main/java/tachyon/worker/ClientMetrics.java
- servers/src/main/java/tachyon/worker/WorkerSource.java
- servers/src/main/java/tachyon/worker/block/BlockDataManager.java
https://tachyon.atlassian.net/browse/TACHYON-624
This PR adds client metrics for remote writes. They essentially mirror the statistics for "local blocks written" and "local bytes written".
This is a re-opened PR to the 0.7 RC.
> [TACHYON-624] Distinguish between remote and local writes for client metrics

- clients/unshaded/src/main/java/tachyon/hadoop/AbstractTFS.java
The port returned in `getFileBlockLocations` should be the data transfer port and not the RPC port. 
For reference: https://hadoop.apache.org/docs/r2.4.1/api/org/apache/hadoop/fs/BlockLocation.html `getNames` method.
> [SMALLFIX] Use correct port in getFileBlockLocations

- servers/src/main/java/tachyon/master/BlockInfo.java
Since the port logic was fixed in #1117 the corresponding logic in the master should also be updated for locations obtained from the ufs.
> [SMALLFIX] Master side loc port fix

- servers/src/main/java/tachyon/master/BlockInfo.java
#1123 Fixes the issue for when the block is in Tachyon by changing the worker addresses to not use `getCanonicalHostname`. When we retrieve the location from the under storage, we also should not resolve the hostname.
> [TACHYON-670] Fix location on the master side

- integration-tests/src/test/java/tachyon/worker/block/meta/CapacityUsageIntegrationTest.java
- minicluster/src/main/java/tachyon/master/LocalTachyonCluster.java
https://tachyon.atlassian.net/browse/TACHYON-605
This test fails when evicting a block is triggered before a separate command of deleting this block arrives. The cause of this bug is due to the missing creation of dirs in `LocalTachyonCluster`.
Since this test is non-deterministic, I also increased the number of iterations to increase chance to trigger the deletionDuringEviction case.
> [TACHYON-605] Fix bug in DeleteDuringEvictionTest

- servers/src/main/java/tachyon/worker/block/TieredBlockStore.java
mAllocator and mEvictor are not thread-safe, so we should synchronize on
them.
> [TACHYON-627] Synchronized on final objects in TieredBlockStore

- clients/unshaded/src/main/java/tachyon/client/RemoteBlockInStream.java
Since #1117 changed the port to secondary port, we need to update RemoteBlockInStream which was using the port as a flag.
> [SMALLFIX] Remote read port check fix

- servers/src/main/java/tachyon/worker/block/BlockWorker.java
https://tachyon.atlassian.net/browse/TACHYON-670
With an empty Tachyon storage space, run `sc.textFile("tachyon://host:ip/file").count()` for the first time(suppose size of file can fit into Tachyon), the whole file will be loaded into Tachyon, then run the same command for the second time, more space will be consumed. But spark executor should be allocated to read local blocks from Tachyon.  
The problem may be: After getting `BlockInfo` of a block, spark compares its host field to current node's host, spark set the current node's host to raw IP string while Tachyon sets it to canonicalHostName, so no block will be matched to local blocks, then executor will try to read from remote TachyonWorker, and more space will be consumed. 
This is still a **guess**, it's only tested on a EC2 …
> [TACHYON-670] Fix spark locality issue

- servers/src/main/java/tachyon/worker/block/BlockHeartbeatReporter.java
- servers/src/test/java/tachyon/worker/block/BlockHeartbeatReporterTest.java
Changes the worker to master communication to not report a block as removed and then readded when the block is moved. Instead we can just report it as added since the master assumes only one copy of the block is in the worker at a time and will update the metadata instead of appending a new block to it.
> [TACHYON-672] Fix Eviction and Delete Bug

- docs/Configuration-Settings.md
Adds a note to users that the tcp remote reader is deprecated.
> [SMALLFIX] Document tcp remote reader deprecation

- servers/src/main/java/tachyon/worker/block/TieredBlockStore.java
Deletes user folders in a new way after the user times out. This way if the user does not have any lingering blocks, their user folders will still be cleaned up.
> [SMALLFIX] User folder delete fix

- servers/src/main/java/tachyon/worker/block/meta/StorageDir.java
- servers/src/main/java/tachyon/worker/block/meta/StorageTier.java
- servers/src/test/java/tachyon/worker/block/meta/BlockMetaBaseTest.java
- servers/src/test/java/tachyon/worker/block/meta/BlockMetaTest.java
- servers/src/test/java/tachyon/worker/block/meta/StorageDirTest.java
- servers/src/test/java/tachyon/worker/block/meta/StorageTierTest.java
- servers/src/test/java/tachyon/worker/block/meta/TempBlockMetaTest.java
This patch makes the worker create directories if they do not exist and also adds the tachyon worker data folder to the directories, making paths like `/mnt/ramdisk/tachyonworker` like in previous versions of Tachyon.
> [TACHYON-664] Initialize worker storage directories

- servers/src/main/java/tachyon/worker/block/BlockStoreLocation.java
https://tachyon.atlassian.net/browse/TACHYON-682
Remove redundant call of 'equal' method from tachyon.worker.block.BlockStoreLocation#belongTo.
> [TACHYON-682] Remove redundant call of overridden 'equal' method from tachyon.worker.block.BlockStoreLocation#belongTo

- integration-tests/src/test/java/tachyon/underfs/hdfs/LocalMiniDFSCluster.java
In older versions of hadoop the cast may be required.
> [SMALLFIX] Cast filesystem to distributed filesystem

- integration-tests/src/test/java/tachyon/underfs/hdfs/LocalMiniDFSCluster.java
Compiling with some HDFS profiles, IDE will complain the unnecessary cast, which is in fact useful for some other HDFS profiles.
> [SMALLFIX] Add javadoc to explain the unnecessary cast

- docs/_layouts/global.html
If they are absolute it will not resolve to the correct version on the webpage but always go to the current version.
> [SMALLFIX] Update links in docs to be relative.

- clients/unshaded/src/main/java/tachyon/hadoop/AbstractTFS.java
- integration-tests/src/test/java/tachyon/hadoop/TFSBlockLocationIntegrationTest.java
https://tachyon.atlassian.net/browse/TACHYON-692
`AbstractTFS.getFileBlockLocations` is to get which block(s) contain the content from `start` to `start+len`. Each block is from `offset` to `end`. Then the judgement statement should cover the following conditions:
1. start <= offset <= start+len <= end
2. start <= offset <= end <= start+len
3. offset <= start <= start+len <= end
4. offset <= start <= end <= start+len
Current it cannot cover condition 3.
> [TACHYON-692] Fix AbstractTFS.getFileBlockLocations

- common/src/main/java/tachyon/security/PlainSaslHelper.java
- common/src/main/java/tachyon/security/PlainSaslServerProvider.java
- common/src/test/java/tachyon/security/PlainSaslServerProviderTest.java
Because the Java SunSASL provider doesn’t support the server-side PLAIN mechanism. There is a new provider needed to register to support server-side PLAIN mechanism. There are three basic steps in implementing a SASL security provider.
1.Write a class that implements the SaslServer interface (It has been merged into security branch)
2.Write a factory class that implements the SaslServerFactory which creates instances of the SaslServer
3.Write a JCA provider that registers the factory
This PR is the remaining two steps to implement the provider supported the server-side PLAIN mechanism
> [TACHYON-623] Add a new JCA provider which registers the PlainSaslServerFacroty to create instances of PlainSaslServer

- servers/src/main/java/tachyon/worker/block/BlockMetadataManagerView.java
- servers/src/test/java/tachyon/worker/block/BlockMetadataManagerViewTest.java
[TACHYON-703](https://tachyon.atlassian.net/browse/TACHYON-703)(https://tachyon.atlassian.net/browse/TACHYON-703)
In _BlockMetadataManagerView_, need to ensure that `StorageTierView getTierView(int tierAlias)` returns the same _TierView_ as `new StorageTierView(mMetadataManager.getTier(tierAlias), this)`.
Add unit test for both `getTierView` and `getTierViewsBelow`.
> [TACHYON-703] Ensure returning the same TierView

- servers/src/main/java/tachyon/UserInfo.java
Why not override equals and hashCode to use mUserId to identify UserInfo object.
As mUserId is used to identify an UserInfo object.
> [TACHYON-702] Use mUserId as HashCode

- libexec/tachyon-config.sh
0.6 is really in 0.6.5-SNAPSHOT, updating the script.
> [SMALLFIX] Fix wrong version in `tachyon-config.sh` of branch-0.6

- pom.xml
This update can avoid running unit tests on IPv4-mapped IPv6 addresses.
> [TACHYON-717]: Disable IPv6 stack on unit tests

- servers/src/test/java/tachyon/worker/block/evictor/EvictorFactoryTest.java
Follow up commit addressing some of the comments in #1145 . Didn't change the `before` to `beforeClass` since nothing too expensive is done in the `before` and to match the style of `AllocatorFactoryTest`.
> [TACHYON-723] Fix the documentation in EvictorFactoryTest.

- clients/unshaded/src/main/java/tachyon/client/RemoteBlockInStream.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-639
From [TACHYON-639](https://tachyon.atlassian.net/browse/TACHYON-639), we keep a reference of current reader in `RemoteBlockInStream` so that we can call `closeReader` when we close the stream. In `#retrieveByteBufferFromRemoteMachine`, the created reader instance is not assigned to the reference but instead a local variable. This PR fixes it.
In the future, we should add integration tests to make sure underlying buffers from the reader are always released when a stream is closed [(TACHYON-721)](https://tachyon.atlassian.net/browse/TACHYON-721). To further eliminate buffer leakage, we also want to investigate a way to release buffer when threads exit unexpectedly [(TACHYON-722)](https://tachyon.atlassian.net/browse/TACHYON-722).
> [TACHYON-639] Fix bug in `RemoteBlockInStream#retrieveByteBufferFromRemoteMachine`

- clients/unshaded/src/main/java/tachyon/client/TachyonFile.java
JIRA: [TACHYON-639](https://tachyon.atlassian.net/browse/TACHYON-639)
This PR fixes bug reported by Pengfei Xuan on JIRA TACHYON-639. The bug causes basic THROUGH test to fail as no null-check is performed for the buffer returned from reading a dummy stream, before copying the data to another buffer.
> [TACHYON-639] Check buffer returned from reading a dummy stream is null.

- servers/src/main/java/tachyon/worker/block/BlockDataManager.java
- servers/src/main/java/tachyon/worker/block/BlockStoreMeta.java
- servers/src/main/webapp/worker/general.jsp
- servers/src/test/java/tachyon/worker/block/BlockMetadataManagerTest.java
[TACHYON-710] https://tachyon.atlassian.net/browse/TACHYON-710
Master and WebUI treat `CapacityBytesOnTiers` at alias level. But Worker treats it at tier level.
This PR fixes the incompatibility by modifying Worker to treat at alias level.
> [TACHYON-710] Fix 'XBytesOnTiers' to be compatible in Master and Worker

- docs/Running-Spark-on-Tachyon.md
Spark 1.5+ will work out of the box with Tachyon 0.7.x.
> [SMALLFIX] Update the Tachyon - Spark dependency docs

- deploy/vagrant/create
https://tachyon.atlassian.net/browse/TACHYON-725
Honestly I don't know much about bash regexp test, but I found an example here: http://stackoverflow.com/questions/11396740/how-can-i-check-if-a-string-is-in-an-array-without-iterating-over-the-elements and it seems to work here, :wink:
> [TACHYON-725] fix vagrant deploy script string matching regexp

- clients/unshaded/src/main/java/tachyon/client/WriteType.java
- docs/Configuration-Settings.md
Notes async_through as an experimental write type, since the feature will likely be modified in future versions.
> [SMALLFIX] Mark async through as experimental in 0.7.

- deploy/vagrant/provision/roles/common/files/java.sh
- deploy/vagrant/provision/roles/lib/files/maven.sh
Old script point to an outdated maven repo that is not working anymore.
Instead we fetch a specific version of maven that is known to work, and
a java version that is required of that maven version.
> [SMALLFIX] Using a newer java and maven to build Tachyon.

- common/src/main/java/tachyon/security/PlainSaslHelper.java
- common/src/main/java/tachyon/security/PlainSaslServer.java
- common/src/main/java/tachyon/security/authentication/AuthenticationFactory.java
- common/src/test/java/tachyon/security/PlainSaslServerTest.java
- common/src/test/java/tachyon/security/PlainServerCallbackHandlerTest.java
- common/src/test/java/tachyon/security/authentication/AuthenticationFactoryTest.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-726
This patch adds a method in AuthenticationFactory for creating server side TTransportFactory, which is used to build a Thrift TServer.
In original code, `TachyonMaster` build a `TThreadPoolServer` with transport `TFramedTransport.Factory`. This method increase options of transport, so enhance the server.
> [TACHYON-726] Add methods of creating TTransport

- servers/src/main/java/tachyon/worker/block/BlockMasterSync.java
In the master branch, failing to lock now throws NotFoundException, so we should catch that instead.
> [SMALLFIX] Change IOException to NotFoundException

- deploy/vagrant/conf/ec2.yml
Updates the AMI to be compatible with the java and maven upgrade. This is the same AMI used in master.
> [SMALLFIX] Use Amazon Linux AMI

- clients/unshaded/src/main/java/tachyon/hadoop/AbstractTFS.java
- clients/unshaded/src/main/java/tachyon/hadoop/HdfsFileInputStream.java
- integration-tests/src/test/java/tachyon/hadoop/HdfsFileInputStreamIntegrationTest.java
- integration-tests/src/test/java/tachyon/hadoop/TFSStatisticsTest.java
https://tachyon.atlassian.net/browse/TACHYON-754
Also run a simple WordCount on both hdfs:// and tachyon://. (Hadoop-2.6.0, Tachyon-master)
**Run on hdfs://** File System Counters
FILE: Number of bytes read=545224
FILE: Number of bytes written=1060941
FILE: Number of read operations=0
FILE: Number of large read operations=0
FILE: Number of write operations=0
HDFS: Number of bytes read=3428
HDFS: Number of bytes written=1765
HDFS: Number of read operations=13
HDFS: Number of large read operations=0
HDFS: Number of write operations=4
**Run on tachyon://** File System Counters
FILE: Number of bytes read=545258
FILE: Number of bytes written=1060059
FILE: Number of read operations=0
FILE: Number of large read operations=0
FILE: Number of write operations=0
HDFS: Number of bytes read=0
HDFS: …
> [TACHYON-754] Enable MapReduce FileSystem Counter information in AbstractTFS

- deploy/vagrant/provision/roles/spark/files/spark-defaults.sh
Fixes the default spark external block store url to use the correct one.
> [SMALLFIX] Fix external block store hostname

- servers/src/test/java/tachyon/worker/block/allocator/AllocatorContractTest.java
- underfs/s3/src/test/java/tachyon/underfs/s3/S3UnderFileSystemTest.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-585
Change-Id: Id2ae6e7a0f8764ed44b443cdee31206095d3aa1b
This patch is about unit test coding style, I think it's better to use "Before" instead of "BeforeClass" in the following two cases.
> [TACHYON-585] replace beforeclass with before in two cases

- common/src/main/java/tachyon/util/io/FileUtils.java
- common/src/test/java/tachyon/util/io/FileUtilsTest.java
- servers/src/main/java/tachyon/worker/block/TieredBlockStore.java
https://tachyon.atlassian.net/browse/TACHYON-771
Through reviewing the codebase, it appears that 'path' appears more frequently than 'Files' as input parameters of 'FileUtils' 's util methods. Hence we will take the former for standardization.
> [TACHYON-771] Standardize FileUtils functionality

- integration-tests/src/test/java/tachyon/worker/block/meta/CapacityUsageIntegrationTest.java
https://tachyon.atlassian.net/browse/TACHYON-782
This is a temporary bandaid for ticket 782. The long term solution should be to repurpose the test to the new worker delete and eviction logic.
> [TACHYON-782] Disable flakey delete during eviction test.

- deploy/vagrant/bin/init_aws.py
oops, should have run it to sanity check. 
Taking out the check for empty argument changed the code path in other part of the code  exposed the bug.
> [SMALLFIX] fix a bug introduced by PR#1238

- common/src/main/java/tachyon/master/MasterClient.java
- common/src/main/java/tachyon/security/PlainSaslHelper.java
- common/src/main/java/tachyon/security/authentication/AuthenticationFactory.java
- common/src/test/java/tachyon/security/PlainClientCallbackHandlerTest.java
- common/src/test/java/tachyon/security/authentication/AuthenticationFactoryTest.java
Jira: https://tachyon.atlassian.net/browse/TACHYON-621
This patch is about Enable Client PLAIN Authentication, including adding Plain Client Transport and callback handler in client side.
Related jira: [TACHYON-726](https://tachyon.atlassian.net/browse/TACHYON-726) Add methods of creating TTransport
> [TACHYON-621] Enable Client PLAIN Authentication

- common/src/test/java/tachyon/util/io/BufferUtilsTest.java
it's more natural to match the test class name with the source class name
> [SMALLFIX] rename ByteUtilsTest.java to BufferUtilsTest.java

- deploy/vagrant/create
Before the fix ./create will print "usage: start <number of machines> <provider(aws" in bash. 
But ">>> Usage start <number of machines> <provider(aws vb)>" is expected.
> [SMALLFIX] Fix the truncated usage message of vagrant create script

- common/src/test/java/tachyon/util/io/BufferUtilsTest.java
https://tachyon.atlassian.net/browse/TACHYON-787
As suggested by @apc999 , allocate & free 16 MB of memory for 1024 times, make sure there is no OOM
> [TACHYON-787] add test for BufferUtils#cleanDirectBuffer

- servers/src/main/java/tachyon/worker/block/BlockHeartbeatReporter.java
- servers/src/main/java/tachyon/worker/block/meta/StorageDir.java
- servers/src/test/java/tachyon/worker/block/BlockHeartbeatReporterTest.java
https://tachyon.atlassian.net/browse/TACHYON-796
Remove the map entry from `mAddedBlocks` when the block list added under corresponding dir becomes empty. 
Also, compared with the code before, exit the loop directly when already find and remove blockId from `mAddedBlocks`.
> [TACHYON-796] Remove the map entry from `mAddedBlocks` when the block list is empty

- servers/src/main/java/tachyon/worker/block/BlockDataManager.java
- servers/src/main/java/tachyon/worker/block/BlockMasterSync.java
- servers/src/main/java/tachyon/worker/block/BlockWorker.java
- servers/src/main/java/tachyon/worker/block/PinListSync.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-785
Current implementation creates three new MasterClient in BlockDataManager, BlockMasterSync, and PinListSync, which in turn creates three heartbeat threads inside MasterClient. A thread monitor on Worker can observe this behavior.
This PR moves MasterClient into BlockWorker and passes it to BlockManager, BlockMasterSync and PinListSync, avoiding redundant creation so the MasterClient heartbeat thread is limited to one.
> [TACHYON-785] Move MasterClient into BlockWorker

- servers/src/main/java/tachyon/worker/block/meta/StorageDir.java
- servers/src/test/java/tachyon/worker/block/meta/StorageDirTest.java
https://tachyon.atlassian.net/browse/TACHYON-811
If the two conditions happens when `resizeTempBlockMeta`:
- newSize is smaller than oldSize,
- or no more Available bytes in the parent dir.
Exception thrown and the temBlockSize should just keep the same.
Set tempBlock size only when method `reserveSpace` succeeds.
> [TACHYON-811] Set tempBlock size only when method `reserveSpace` succeeds

- servers/src/main/java/tachyon/worker/block/meta/StorageDir.java
- servers/src/test/java/tachyon/worker/block/meta/StorageDirTest.java
Follow up to #1327 to clean up the error message.
> [TACHYON-811] Trim trailing whitespace from exception message.

- clients/unshaded/src/main/java/tachyon/client/TachyonFS.java
Removes the IOExceptions clause in get since IOExceptions are not thrown anymore.
> [SMALLFIX] Remove unnecessary throws IOException

- integration-tests/src/test/java/tachyon/hadoop/fs/DFSIOIntegrationTest.java
All the other tests are at 25000 (25 seconds), but readSkipTest was at 20 seconds. This caused a failure in Jenkins: https://amplab.cs.berkeley.edu/jenkins/job/Tachyon-Master/957/PROFILE=hdfs1Test,label=centos/console
> [SMALLFIX] Increase readSkipTest's timeout

- shell/src/main/java/tachyon/shell/TFsShellUtils.java
- shell/src/test/java/tachyon/shell/TFsShellUtilsTest.java
There are two public methods, 
`getTachyonURIs` and `getFiles`
; the former is for Tachyon files and the latter is for files in the local fs.
Basically, the method takes a input path (could contain wildcards) and return the list of files that matches the input path (if the input path is an absolute path, it returns the path)
> [TACHYON-590] Utility functions for the wildcard support of Tachyon shell commands

- common/src/main/java/tachyon/conf/TachyonConf.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-470
getLong is still taking a default value. This PR aims to remove the default value parameter.
> [TACHYON-470] Update TachyonConf.getLong to eliminate taking default value

- clients/unshaded/src/main/java/tachyon/client/RemoteBlockInStream.java
- integration-tests/src/test/java/tachyon/client/RemoteBlockInStreamIntegrationTest.java
https://tachyon.atlassian.net/browse/TACHYON-813
@gpang Is this what you have in mind? Maybe we could also check the type of mBlockOutStream upon creation at line 247 and reset it to null if it's remote?
> [TACHYON-813] RemoteBlockInstream read should only cache locally

- .gitignore
vbox/shared will not be generated anymore.
> [SMALLFIX] remove vbox/shared directory from .gitignore

- docs/js/scrollspy.js
There was a comparator in the if statement that was using !== instead of != so undefined and null were not resulting in equal values, causing the scrollspy plugin to fail.
> [SMALLFIX] Fix Table of Contents for Project Docs

- integration-tests/src/test/java/tachyon/master/JournalCrashIntegrationTest.java
The JournalCrashIntegrationTest has a crash behavior but cannot totally crash the LocalTachyonCluster. The remaining threads will influence the coming test.
Temporarily ignore these tests and will consider a better way to simulate cluster crashing.
> [SMALLFIX] Temporarily ignore unstable tests

- servers/src/main/java/tachyon/master/next/IndexedSet.java
- servers/src/main/java/tachyon/master/next/block/BlockMaster.java
- servers/src/main/java/tachyon/master/next/filesystem/meta/InodeDirectory.java
- servers/src/test/java/tachyon/master/next/IndexedSetTest.java
The common use case for `all()` in `IndexedSet` is to iterate over all elements, so it is an `Iterable`.
> [SMALLFIX] Let IndexedSet implement Iterable

- servers/src/test/java/tachyon/worker/block/TieredBlockStoreTestUtils.java
https://tachyon.atlassian.net/browse/TACHYON-740
Variable `LOG` is not used in TieredBlockStoreTestUtils. Please remove it.
> [TACHYON-740] Remove 'LOG' in TieredBlockStoreTestUtils

- integration-tests/src/test/java/tachyon/master/JournalShutdownIntegrationTest.java
https://tachyon.atlassian.net/browse/TACHYON-776
It's hard to completely simulate cluster crashing in integration test. The threads of master/worker/client/ufs cannot be totally killed since they are in the same JVM and influence each other.
This PR move the test back to a shutdown test. The crash test will be implemented as a "program" (see: https://tachyon.atlassian.net/browse/TACHYON-833)
> [TACHYON-776] Journal shutdown test

- common/src/main/java/tachyon/Constants.java
- common/src/main/java/tachyon/security/CustomLoginModule.java
- common/src/main/java/tachyon/security/TachyonJaasConfiguration.java
- common/src/test/java/tachyon/security/LoginUserTest.java
JIRA: [TACHYON-786](https://tachyon.atlassian.net/browse/TACHYON-786)
In production use of Tachyon, we want different applications to have separate user identities, even if they are running under same operating system user. We should allow this by letting the application to specify their username, through Java configuration parameter. This JIRA enables that in the SIMPLE login mechanism. If tachyon.security.username is specified by the application and is not empty, the login modules uses tachyon.security.username as the username; otherwise, we fall back to OS_SPECIFIC_LOGIN.
> [TACHYON-786] Login Mechanism: Add CUSTOM_LOGIN (by JAAS framework)

- common/src/main/java/tachyon/conf/TachyonConf.java
- common/src/main/java/tachyon/exception/AbstractTachyonException.java
- common/src/main/java/tachyon/exception/AlreadyExistsException.java
- common/src/main/java/tachyon/exception/ExceptionMessage.java
- common/src/main/java/tachyon/exception/NotFoundException.java
- common/src/main/java/tachyon/exception/OutOfSpaceException.java
- servers/src/main/java/tachyon/ErrorMessage.java
- servers/src/main/java/tachyon/worker/block/BlockLockManager.java
- servers/src/main/java/tachyon/worker/block/BlockMetadataManager.java
- servers/src/main/java/tachyon/worker/block/BlockMetadataManagerView.java
- servers/src/main/java/tachyon/worker/block/TieredBlockStore.java
- servers/src/test/java/tachyon/worker/block/BlockLockManagerTest.java
- servers/src/test/java/tachyon/worker/block/BlockMetadataManagerTest.java
- servers/src/test/java/tachyon/worker/block/BlockMetadataManagerViewTest.java
- servers/src/test/java/tachyon/worker/block/TieredBlockStoreTests.java
https://tachyon.atlassian.net/browse/TACHYON-814
Other than describing exception message as plain strings in an adhoc way, it's better to aggregate them into a central place. The benefits include at least (1) writing unit tests (2) internationalization (3) refactoring, etc.
> [TACHYON-814] Defined the exception messages in an enum and refactored existing exceptions

- common/src/main/java/tachyon/util/io/BufferUtils.java
- common/src/test/java/tachyon/util/io/BufferUtilsTest.java
- integration-tests/src/test/java/tachyon/hadoop/HdfsFileInputStreamIntegrationTest.java
Some utility functions in tachyon.util.io.BufferUtils are missing unit tests; this PR adds more tests (increasing line coverage from 30% to 80%).
> [TACHYON-880] Adding unit tests for tachyon.util.io.BufferUtils.

- common/src/main/java/tachyon/security/LoginUser.java
- common/src/main/java/tachyon/security/authentication/AuthenticationFactory.java
- common/src/main/java/tachyon/security/authentication/PlainSaslHelper.java
- common/src/main/java/tachyon/security/authentication/PlainSaslServer.java
- common/src/main/java/tachyon/security/authentication/PlainSaslServerProvider.java
- common/src/main/java/tachyon/security/login/CustomLoginModule.java
- common/src/main/java/tachyon/security/login/TachyonJaasConfiguration.java
- common/src/main/java/tachyon/security/login/TachyonJaasProperties.java
- common/src/main/java/tachyon/security/login/TachyonLoginModule.java
- common/src/test/java/tachyon/security/authentication/AuthenticationFactoryTest.java
- common/src/test/java/tachyon/security/authentication/PlainClientCallbackHandlerTest.java
- common/src/test/java/tachyon/security/authentication/PlainSaslServerProviderTest.java
- common/src/test/java/tachyon/security/authentication/PlainSaslServerTest.java
- common/src/test/java/tachyon/security/authentication/PlainServerCallbackHandlerTest.java
- common/src/test/java/tachyon/security/login/LoginModuleTest.java
Currently most of classes are under tachyon.security package. In order to organize them based on functionality, let's do below changes:
1. move PlainSaslXXX classes to tachyon.security.authentication
2. create a package tachyon.security.login and move TachyonJaasXXX or TachyonLoginXXX to it. These classes serves for login purpose.
jira: https://tachyon.atlassian.net/browse/TACHYON-799
> [TACHYON-799] Organize the classes into proper packages under tachyon security

- integration-tests/src/test/java/tachyon/master/JournalShutdownIntegrationTest.java
https://tachyon.atlassian.net/browse/TACHYON-776
The previous test sometimes failed. See 
https://amplab.cs.berkeley.edu/jenkins/job/Tachyon-Master/PROFILE=hdfs1Test,label=centos/1014/
https://amplab.cs.berkeley.edu/jenkins/job/Tachyon-Master/PROFILE=hdfs2Test,label=centos/1011/console
https://amplab.cs.berkeley.edu/jenkins/job/Tachyon-Master/PROFILE=contractTest,label=centos/1007/console
This PR fixes the test by:
1. Ensure the clients and local cluster are terminated before status checking.
2. Consider the special case. The following is the workflow to create a file.
i. Client sends request to Master
ii. Master creates the file metadata
iii. Master writes the editlog
iv. Return to the Client
If something crashes between iii and iv (e.g. kill the service server), client will record the …
> [TACHYON-776] Stabilize JournalShutdownTest

- servers/src/main/java/tachyon/worker/block/BlockLockManager.java
LOCK_ACQUIRE_TIMEOUT_MS is no longer used.
> [TACHYON-896]Remove unused field in BlockLockManager

- README.md
- assembly/README.md
- deploy/vagrant/README.md
- docs/Running-Shark-on-Tachyon.md
- pom.xml
This PR fixes HTTP links that were broken after adding the "documentation" component to the URL path for most Tachyon project pages. Also, for consistency this PR changes instances of tachyonproject.org to tachyon-project.org.
> [SMALLFIX] Fixing broken HTTP links

- common/src/main/java/tachyon/security/LoginUser.java
- common/src/main/java/tachyon/security/TachyonJaasConfiguration.java
- common/src/main/java/tachyon/security/login/AppLoginModule.java
- common/src/main/java/tachyon/security/login/TachyonJaasConfiguration.java
- common/src/test/java/tachyon/security/LoginUserTest.java
JIAR: [TACHYON-898](https://tachyon.atlassian.net/browse/TACHYON-898)
In current login framework, the login user can only be fetched in SIMPLE mode. Getting login user will throw UnsupportedOperationException in other mode. In this PR, we enable getting login user in CUSTOM mode.
This issue was found when doing integration test in #1297 . Configured with CUSTOM mode, client side will throw unsupported exception when getting login user for connecting to server. This PR resolve this.
@ooq , @apc999 , could you help to review this? Thanks.
> [TACHYON-898] Enable LoginUser in CUSTOM mode

- common/src/test/java/tachyon/security/LoginUserTest.java
JIRA: [TACHYON-838](https://tachyon.atlassian.net/browse/TACHYON-838)
In #1292 (TACHYON-786), in the test the login user name is verified equality instead of just being checked not null. As discussed there, this Jira is a follow-up to update the original test getSimpleLoginUserTest like that.
> [TACHYON-838] Update getSimpleLoginUserTest in LoginUserTest

- common/src/main/java/tachyon/security/LoginUser.java
- common/src/main/java/tachyon/security/TachyonJaasConfiguration.java
- common/src/test/java/tachyon/security/LoginUserTest.java
- integration-tests/src/test/java/tachyon/master/MasterClientAuthenticationIntegrationTest.java
- servers/src/main/java/tachyon/master/TachyonMaster.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-772.
Enable Master Server PLAIN Authentication. I have written some integration tests for all kinds of authentication mode, such as NOSASL, SIMPLE, CUSTOM and KERBEROS.　There has some code about create a test loginUser for uniting test. I know @ooq has sent a PR about custom loginmodule. I will use his feature when it has been committed. @apc999 @ooq  please help me to review this PR. Thanks.
> [TACHYON-772] Enable Master Server PLAIN Authentication

- common/src/main/java/tachyon/worker/WorkerClient.java
- servers/src/main/java/tachyon/worker/block/BlockWorker.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-798
Similar as the Master, we enable simple authentication on Worker by creating proper TTransport based on conf. 
This patch currently only contains change on code, and will be updated with tests, after #1297 merged (reuse the tests in #1297 and add worker part).
> [TACHYON-798] Enable simple authentication on TachyonWorker and WorkerClient

- docs/css/main.css
On mobile the master documentation was having some styling issues where it was hard to see the navigation links, so I added a few extra styles to respond to mobile devices.
> [SMALLFIX] Fix header for docs on mobile

- clients/unshaded/src/main/java/tachyon/client/AbstractTachyonFS.java
- clients/unshaded/src/main/java/tachyon/client/BlockInStream.java
- clients/unshaded/src/main/java/tachyon/client/BlockOutStream.java
- clients/unshaded/src/main/java/tachyon/client/EmptyBlockInStream.java
- clients/unshaded/src/main/java/tachyon/client/FileInStream.java
- clients/unshaded/src/main/java/tachyon/client/FileOutStream.java
- clients/unshaded/src/main/java/tachyon/client/LocalBlockInStream.java
- clients/unshaded/src/main/java/tachyon/client/LocalBlockOutStream.java
- clients/unshaded/src/main/java/tachyon/client/ReadType.java
- clients/unshaded/src/main/java/tachyon/client/RemoteBlockInStream.java
- clients/unshaded/src/main/java/tachyon/client/RemoteBlockOutStream.java
- clients/unshaded/src/main/java/tachyon/client/RemoteBlockReader.java
- clients/unshaded/src/main/java/tachyon/client/RemoteBlockWriter.java
- clients/unshaded/src/main/java/tachyon/client/TachyonByteBuffer.java
- clients/unshaded/src/main/java/tachyon/client/TachyonFS.java
- clients/unshaded/src/main/java/tachyon/client/TachyonFSCore.java
- clients/unshaded/src/main/java/tachyon/client/TachyonFSTestUtils.java
- clients/unshaded/src/main/java/tachyon/client/TachyonFile.java
- clients/unshaded/src/main/java/tachyon/client/UfsUtils.java
- clients/unshaded/src/main/java/tachyon/client/WriteType.java
- clients/unshaded/src/main/java/tachyon/client/netty/ClientHandler.java
- clients/unshaded/src/main/java/tachyon/client/netty/NettyRemoteBlockReader.java
- clients/unshaded/src/main/java/tachyon/client/netty/NettyRemoteBlockWriter.java
- clients/unshaded/src/main/java/tachyon/client/table/RawColumn.java
- clients/unshaded/src/main/java/tachyon/client/table/RawTable.java
- common/src/main/java/tachyon/master/MasterClient.java
Some public methods in the tachyon.client.* package are not completely documented (e.g. method, @param, @throws descriptions). This PR makes sure that all JavaDoc contain the required @param and @throws description, use a consistent style, and all TODOs are tagged with their author.
> [TACHYON-909] Improve JavaDoc comments for tachyon.client.*

- clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystem.java
- servers/src/main/java/tachyon/master/file/journal/AddCheckpointEntry.java
Should not use `getPath` on ufs `TachyonURI`, use `toString` instead to preserve scheme and host.
> [SMALLFIX] Fix mvn test -Phdfs1Test

- clients/unshaded/src/main/java/tachyon/client/TachyonFS.java
Also, `MasterInfoIntegrationTest` for `-Phdfs1Test` didn't hang.
> [SMALLFIX] Fix UfsUtilsIntegrationTest#loadUnderFsTest for hdfs1Test

- common/src/main/java/tachyon/worker/ClientMetrics.java
This checkin added javadoc to all public methods in ClientMetrics, hence TACHYON 884 through 893 can be considered fixed since they are all about javadocs of the very same class.
https://tachyon.atlassian.net/browse/TACHYON-883
> [TACHYON-883] add javadoc to all public methods of ClientMetrics

- integration-tests/src/test/java/tachyon/master/JournalShutdownIntegrationTest.java
The 'multiMasterJournalCrashIntegrationTest' in 'JournalShutdownIntegrationTest' may fail.
A ticket have been opened for this issue ([TACHYON-929](https://tachyon.atlassian.net/browse/TACHYON-929)).
> [SMALLFIX] Disable failing test in JournalShutdownIntegrationTest

- common/src/test/java/tachyon/util/io/FileUtilsTest.java
Relax the dir permission bits' assert restriction in FileUtilsTest#setLocalDirStickyBitTest.
https://tachyon.atlassian.net/browse/TACHYON-924
> [TACHYON-924] Relax the dir permission bits' assert restriction

- clients/unshaded/src/main/java/tachyon/client/file/FileInStream.java
- integration-tests/src/test/java/tachyon/client/FileInStreamIntegrationTest.java
- integration-tests/src/test/java/tachyon/hadoop/fs/DFSIOIntegrationTest.java
- servers/src/main/java/tachyon/Users.java
Upon reaching the end of the file, we should still allow seek operations. This fixes the bug that was breaking the dfsio tests.
> [SMALLFIX] Handle stream operations when at the end of the file.

- common/src/main/java/tachyon/MasterClientBase.java
- common/src/test/java/tachyon/security/LoginUserTest.java
- integration-tests/src/test/java/tachyon/security/MasterClientAuthenticationIntegrationTest.java
- integration-tests/src/test/java/tachyon/security/WorkerClientAuthenticationIntegrationTest.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-947
Fix the failed test `WorkerClientAuthenticationIntegrationTest` and `MasterClientAuthenticationIntegrationTest` by using `AuthenticationFactory` to create the transport in `MasterClientBase`
@apc999 , @ooq , @shenguoquan , @sundapeng , could you please take a look? Thanks
> [TACHYON-947] Fix failed security integration test after merging master with PR #1464

- deploy/vagrant/core/EnvSetup.rb
Mesos env parsing is missing the None type, the default deploy env setup fail with 'Unknown VersionType'
> [SMALLFIX] correct mesos config parsing, add missing None type

- servers/src/main/java/tachyon/master/journal/JournalReader.java
rename  mLatestCheckpointModifiedTime to mCheckpointLastModifiedTime, so that the name is consistent with its getter function and other variable's naming convention
> [SMALLFIX] rename a variable name for consistency

- clients/unshaded/src/main/java/tachyon/client/AbstractTachyonFS.java
- clients/unshaded/src/main/java/tachyon/client/TachyonFS.java
- clients/unshaded/src/main/java/tachyon/client/TachyonFSCore.java
All the consumers of `createFile` are casting it to a long, and downcasting the long to an int is not safe.
> [SMALLFIX] Change createFile's type signature to long.

- integration-tests/src/test/java/tachyon/master/MasterFaultToleranceIntegrationTest.java
This test fails in hdfs mode, this is a temporary bandaid until the master fault tolerance suite is fixed overall.
> [SMALLFIX] Disable failing test

- assembly/pom.xml
For case insensitive file systems (ie. HFS+ for osx) a collision will occur if the license/notice transformer is not included.
> [SMALLFIX] Handle license collisions in assembly jar

- common/src/main/java/tachyon/exception/ExceptionMessage.java
- servers/src/main/java/tachyon/worker/block/TieredBlockStore.java
- servers/src/test/java/tachyon/worker/block/TieredBlockStoreTests.java
for PR: https://github.com/amplab/tachyon/pull/1498
if user wants to delete some block in certain layer, the old logic doesn't work,
Use belongTo to compare the current location and the location specified.
> [SMALLFIX] Follow up small change for TACHYON-937

- minicluster/pom.xml
This PR changes the minicluster project name from "Mock Tachyon Cluster" to "Tachyon Mock Cluster". This is purely a cosmetic change for consistency with other modules, all of which have names starting with Tachyon.
> [SMALLFIX] Module name rewording.

- assembly/pom.xml
The reason is to avod conflicting filenames in filesytems that are not insensitive for filename case like MacOS filesystem. e.g., using yarn running the assembly jar on MacOS meets this problem
> [SMALLFIX] Exclude LICENSE file in assemly jar. 

- integration-tests/src/test/java/tachyon/master/JournalIntegrationTest.java
- integration-tests/src/test/java/tachyon/master/MasterTestUtils.java
- minicluster/src/main/java/tachyon/master/LocalTachyonMaster.java
- servers/src/main/java/tachyon/master/MasterBase.java
- servers/src/main/java/tachyon/master/MasterInfo.java
- servers/src/main/java/tachyon/master/TachyonMaster.java
- servers/src/main/java/tachyon/master/TachyonMasterFaultTolerant.java
- servers/src/main/java/tachyon/master/block/BlockMaster.java
- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
- servers/src/main/java/tachyon/master/file/FileSystemMasterServiceHandler.java
- servers/src/main/java/tachyon/master/file/meta/Dependency.java
- servers/src/main/java/tachyon/master/journal/Journal.java
- servers/src/main/java/tachyon/master/journal/JournalReader.java
- servers/src/main/java/tachyon/master/journal/JournalTailerThread.java
- servers/src/main/java/tachyon/master/journal/JournalWriter.java
- servers/src/main/java/tachyon/master/journal/ReadOnlyJournal.java
- servers/src/main/java/tachyon/master/rawtable/RawTableMaster.java
- servers/src/main/java/tachyon/web/WebInterfaceDownloadServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceGeneralServlet.java
- servers/src/test/java/tachyon/master/file/FileSystemMasterTest.java
- servers/src/test/java/tachyon/master/file/meta/InodeTreeTest.java
- shell/src/test/java/tachyon/shell/TFsShellTest.java
This PR replaces the use of private members that store the Tachyon configuration in the master code with the use of MasterContext.
> [SMALLFIX] Making use of MasterContext.getConf() in the master code

- deploy/vagrant/provision/roles/tachyon/tasks/clone_local_repo.yml
${TACHYON_HOME}/journal is excluded by rsync when cloning the local source repo. However, a source folder also named as "journal" was skipped too due to this exclusion. Remove the rsync filtering rule for now. Leave a TODO to better address this problem.
> [SMALLFIX] Fix vagrant deployment when cloning local repo to EC2

- clients/unshaded/src/main/java/tachyon/client/block/LocalBlockOutStream.java
https://tachyon.atlassian.net/browse/TACHYON-995
> [TACHYON-995] Fix Log message in LocalBlockOutStream to not include parenthesis

- common/src/main/java/tachyon/exception/ExceptionMessage.java
- servers/src/main/java/tachyon/master/block/BlockMaster.java
- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
- servers/src/main/java/tachyon/master/journal/JournalWriter.java
- servers/src/main/java/tachyon/master/journal/JsonJournalFormatter.java
- servers/src/main/java/tachyon/master/rawtable/RawTableMaster.java
- servers/src/main/java/tachyon/master/rawtable/meta/RawTables.java
We put exception messages that are used in numerous places in the ExceptionMessage class. Other remaining error messages in the master code are not duplicated anywhere, so they didn't need to be put into ExceptionMessage
> [SMALLFIX] Standardized duplicate error messages in master

- servers/src/main/java/tachyon/worker/block/BlockMasterSync.java
- servers/src/main/java/tachyon/worker/block/BlockWorker.java
- servers/src/main/java/tachyon/worker/block/PinListSync.java
PinListSync and BlockMasterSync should use workercontext to get tachyonconf now. Also add a javadoc comment for BlocalMasterSync
> [SMALLFIX] Use workercontext to get conf for PinListSync and BlockMasterSync

- deploy/vagrant/provision/roles/tachyon/tasks/clone_local_repo.yml
when rsyncing files in a local tachyon repo to remote aws servers.
Especially, add back `${TACHYON_HOME}/journal` to the list of excluded files.
> [SMALLFIX] Complete a TODO in deployment script 

- clients/unshaded/src/main/java/tachyon/client/block/BufferedBlockOutStream.java
`allocateBuffer` is only used as a helper method in this class and does not need to be public.
> [SMALLFIX] Make allocateBuffer a private method and add javadoc.

- clients/unshaded/src/main/java/tachyon/client/block/LocalBlockInStream.java
It no longer throws IOException.
> [SMALLFIX] Remove unnecessary throws clause in checkIfClosed

- servers/src/test/java/tachyon/worker/block/allocator/BaseAllocatorTest.java
Use Junit rules to manage temp folders so that they can be deleted automatically after the UT.
> [SMALLFIX] Use junit rules to manage temp folders

- deploy/vagrant/provision/roles/ufs_hadoop2/files/config.sh
by default YARN gives each container 2GB virtual memory (not physical memory). And Tachyon master on initialization requires close to 5 GB virtual memory space (though only 100 MB physical memory used). This PR removes the check on YARN site if YARN is deployed using our vagrant script to avoid YARN killing Tachyon Master unnecessarily.
> [SMALLFIX] Change YARN setting in deployment not to check virtual memory

- integration-tests/src/test/java/tachyon/client/IsolatedTachyonFileSystemIntegrationTest.java
Fix a bug in IsolatedTachyonFileSystemIntegrationTest#unlockBlockTest3 which causes this test flaky
In the test, we should first sleep until eviction propagated to master then get `fileInfo`, while the original 
did it in the wrong order.
> [TACHYON-1043] Fix flakiness in IsolatedTachyonFileSystemIntegrationTest

- common/src/main/java/tachyon/Constants.java
- common/src/main/resources/tachyon-default.properties
- integration/mesos/src/main/java/tachyon/mesos/TachyonFramework.java
https://tachyon.atlassian.net/browse/TACHYON-990
In current version, assuming tachyon binaries and java is installed and are already in mesos slaves but may not be in practice. Executor dependencies provided from distributed file system or some server.
> Providing executor dependencies from URI.

- deploy/vagrant/create
In BSD, `seq 3 1` returns `3 2 1`,
In GNU, it returns nothing.
> [SMALLFIX] More robust for loop in vagrant/create and add an appropriate break in a loop

- clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystemCore.java
- shell/src/main/java/tachyon/shell/TfsShell.java
In `TfsShell`, there are conventions like `mTfs.delete(mTfs.open(path))`, if `path` doesn't exist, `mTfs.open` will return null, then a confusing `NullPointerException` will be thrown. 
https://tachyon.atlassian.net/browse/TACHYON-1094
> [TACHYON-1094] Handle the case when open return null in TfsShell

- deploy/vagrant/create
In practice, when Tachyon is in fault tolerant mode, I find that without waiting for sometime, the leader may not have been selected, so all `curl` to web UI will fail, then user needs to manually try to load web UI of different masters to determine current leader, not user-friendly.
> [SMALLFIX] Wait for leader to be selected in deploy/create 

- clients/unshaded/src/main/java/tachyon/client/lineage/AbstractLineageClient.java
- clients/unshaded/src/main/java/tachyon/client/lineage/LineageMasterClient.java
- clients/unshaded/src/main/java/tachyon/client/lineage/TachyonLineageFileSystem.java
- servers/src/main/java/tachyon/master/file/meta/InodeTree.java
https://tachyon.atlassian.net/browse/TACHYON-1098
- Now AbstractLineageClient passes just the path part to
LineageMasterClient#createLineage, which, in turn, has been updated
accordingly.
- InodeTree#createPath passes the correct path part of the TachyoURI to
PathUtils#getPathComponents
> [TACHYON-1098] Stripping path from TachyonURI

- clients/client/pom.xml
This prevent issues with unjar() when running hadoop with the tachyon client jar.
> [SMALLFIX] Ignore license in client jar

- underfs/s3/src/main/java/tachyon/underfs/s3/S3UnderFileSystem.java
- underfs/s3/src/test/java/tachyon/underfs/s3/S3UnderFileSystemTest.java
This PR fixes https://tachyon.atlassian.net/browse/TACHYON-1097. 
Also, before this PR, consider that we have an instance of `S3UnderFileSystem` `ufs`, then call `ufs.create("s3n://a/b/")`, and then call `ufs.exists("/a/b")`, the last call will return false, I think this behavior is not what we want, since a client of ufs may call `create` with uri containing scheme, it may also call it with just the absolute path.  This PR fixes this misbehavior too.
> [TACHYON-1097] Better logic in S3UnderFileSystem#stripPerfixIfPresent

- servers/src/main/java/tachyon/worker/block/SpaceReserver.java
- servers/src/test/java/tachyon/worker/block/SpaceReserverTest.java
Simplify SpaceReserverTest by removing multiple-threading.
Unit tests are meant to be simple and isolated.
This test used to be flaky.
> [SMALLFIX] Make SpaceReserverTest single thread

- .gitignore
which is the default ufs dir for local fs
> [SMALLFIX] Add back underFSStorage into gitignore,

- deploy/vagrant/bin/spot_request.py
Sometimes, waiting for spot instances fails because it can't find the spot instance id. Sleeping seems to solve that error.
> [SMALLFIX] Sleep before waiting for spot instances

- integration/mesos/src/main/java/tachyon/mesos/TachyonFramework.java
When a task starts RUNNING, new entry is automatically registered to mesos-dns  and format will be “taskname.frameworkname.mesos”. 
In tachyon framework, I set frame name as “tachyon” and our master task name is “masternode”, then our dns entry will be “masternode.tachyon.mesos”. Mesos-DNS installation that configured to Mesos master will be enough to test it.
> [TACHYON-1101] Integrating tachyon mesos framework with Mesos-DNS for service discovery

- common/src/main/java/tachyon/security/authorization/FsPermission.java
- common/src/main/resources/tachyon-default.properties
- common/src/test/java/tachyon/security/authorization/FsPermissionTest.java
- integration-tests/src/test/java/tachyon/master/file/FileSystemMasterIntegrationTest.java
- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
- servers/src/main/java/tachyon/master/file/meta/InodeTree.java
- servers/src/test/java/tachyon/master/file/meta/InodeTreeTest.java
- servers/src/test/java/tachyon/master/journal/JournalFormatterTestBase.java
https://tachyon.atlassian.net/browse/TACHYON-897
Currently Tachyon uses FileSystemMaster to handler client requests. FileSystemMaster is the place to plug the permission status for authorization. FileSystemMaster sets the initialized permission for file or directory, the initialized permission should be masked. For example, default file permission is “0666”, default directory permission is “0777”, and the default umask is “0022”.So the masked file permission is “0644”, and masked directory permission is “0755”. When we create a new file or directory, the permission should be “0644” for a file, and “0755” for a directory.
> [TACHYON-897] Integrate the permission status into MasterInfo When it creates file or directory

- common/src/test/java/tachyon/util/io/FileUtilsTest.java
"resource" is ok to suppress because the constructor is expected to fail
fw needs to be declared so that the @SuppressWarnings can be applied locally
> [SMALLFIX] Suppress warnings in FileUtilsTest

- common/src/test/java/tachyon/security/authentication/AuthenticationUtilsTest.java
In AuthenticationUtilsTest, concurrent test cases may compete for the same port to create listening socket. This PR uses port "0" when creating a server-side socket
> [SMALLFIX] Fix a flaky unit test "AuthenticationUtilsTest"

- common/src/main/java/tachyon/Constants.java
Just remove constants:
DEFAULT_MASTER_MAX_WORKER_THREADS
DEFAULT_WORKER_MAX_WORKER_THREADS
https://tachyon.atlassian.net/browse/TACHYON-1082
> [TACHYON-1082] Remove unused Tachyon parameters definition from Tachyon.Constants

- clients/unshaded/src/main/java/tachyon/client/TachyonFile.java
- clients/unshaded/src/main/java/tachyon/client/file/AbstractTachyonFileSystem.java
- clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystem.java
- clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystemCore.java
- clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystemUtils.java
- integration-tests/src/test/java/tachyon/client/TachyonFileSystemIntegrationTest.java
- integration-tests/src/test/java/tachyon/worker/block/meta/TieredStoreIntegrationTest.java
- servers/src/main/java/tachyon/web/WebInterfaceBrowseServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceWorkerBlockInfoServlet.java
- shell/src/main/java/tachyon/shell/TfsShell.java
- shell/src/main/java/tachyon/shell/TfsShellUtils.java
- shell/src/test/java/tachyon/shell/TfsShellTest.java
- shell/src/test/java/tachyon/shell/TfsShellUtilsTest.java
Most people expect open to throw an exception if the path does not
exist, but currently it would returns null, so that people could use it
as an exists method.
Rather than have an exists method, which introduces atomicity
problems (the file could be deleted in between checking for existence
and opening), we added an openIfExists method, which has the same
behavior as the old open method. The new open method will throw an
exception if the path does not exist.
> [TACHYON-993] Added openIfExists method

- common/src/main/java/tachyon/heartbeat/SleepingTimer.java
This PR gets rid of the spurious "... last execution took XXX ms. Longer than the interval YYY." log messages.
> [SMALLFIX] Fixing interval computation in SleepingTimer

- servers/src/main/java/tachyon/master/lineage/LineageMaster.java
Otherwise the journal records an empty entry of PersistFile
> [SMALLFIX] Do not call persistFiles when the files are empty.

- common/src/main/java/tachyon/Constants.java
- underfs/s3/src/main/java/tachyon/underfs/s3/S3UnderFileSystem.java
Additional configurations for the S3UnderFileSystem which enable to use the proxy while access s3.
This modification makes it possible to adopt some other s3-compatible storage as the underfs.
btw, I append MD5 to put request while creating the dir.
> [SMALLFIX] make s3 underfs available for proxy-based access

- clients/unshaded/src/main/java/tachyon/client/file/FileInStream.java
[TACHYON-1143](https://tachyon.atlassian.net/browse/TACHYON-1143)
When reading files in remote workers with *STORE* `TachyonStorageType`, clients only cache the first block in the files and fail to cache other blocks to local.
> [TACHYON-1143] fix cache remote blocks

- deploy/vagrant/provision/roles/spark/files/dist.sh
- deploy/vagrant/provision/roles/spark/tasks/compile.yml
- deploy/vagrant/provision/roles/ufs_hadoop1/files/compile_spark.sh
- deploy/vagrant/provision/roles/ufs_hadoop2/files/compile_spark.sh
- deploy/vagrant/provision/roles/ufs_s3/files/compile_spark.sh
I find that it is more developer friendly to use `mvn` instead of the wrapper script `make-distribution.sh` where some unnecessary logic happens except compilation. Directly use `mvn` will leave spark source code there, so once the cluster is setup, the user can still recompile spark, recompilation is needed in testing process by developers in our community.
> [SMALLFIX] Replace make-distribution.sh with mvn to build spark

- shell/src/main/java/tachyon/shell/TfsShell.java
- shell/src/test/java/tachyon/shell/TfsShellTest.java
https://tachyon.atlassian.net/browse/TACHYON-926
Currently, Tachyon supports simple authentication and binds the username info into inode. This feature is very useful. It can shows who create these files. The TfsShell commands such as ls or lsr should show these info. This PR depends on #1574
> [TACHYON-926] Show user info in the output when TfsShell commands"ls or lsr" run

- deploy/vagrant/provision/roles/spark/files/remove_s3_exclusion.sh
- deploy/vagrant/provision/roles/spark/tasks/compile.yml
From tachyon 0.8, after removing exclusion of tachyon-underfs-s3 from spark core/pom.xml and recompiling spark against tachyon, spark + tachyon + s3 should work out of box.
> [SMALLFIX] Remove tachyon-underfs-s3 exclusion from spark when ufs is s3

- servers/src/main/java/tachyon/master/file/meta/InodeTree.java
Using getPath strips the scheme/authority which is required.
> [TACHYON-1132] Fix resolved path usage

- servers/src/main/java/tachyon/worker/block/evictor/LRUEvictor.java
[TACHYON-1145](https://tachyon.atlassian.net/browse/TACHYON-1145)
When we run hive SQL (aggregation, join and scan) on Tachyon (2G MEM x 9 nodes + 30GHDD x 9 nodes), write data about 20GB on each Tachyon worker, The **EvictorBase.java** often shows "`java.util.ConcurrentModificationException`" error when access the next entry of *mLRUCache.keyset().iterator()*
> [TACHYON-1145] Fix concurrent modification error in LRUEvictor#mLRUCache.keyset().iterator

- servers/src/main/java/tachyon/master/file/meta/Inode.java
- servers/src/main/java/tachyon/master/file/meta/InodeDirectory.java
- servers/src/main/java/tachyon/master/file/meta/InodeFile.java
Previously all of the (T) casts were considered unsafe by Java, and Builder was a raw type.
Credit for proper abstract fluent builder generics goes to http://stackoverflow.com/questions/5818504/can-i-have-an-abstract-builder-class-in-java-with-method-chaining-without-doing
> [SMALLFIX] Fix generics in Inode.Builder and subclasses

- build/checkstyle/tachyon_checks.xml
- clients/unshaded/src/main/java/tachyon/client/TachyonFS.java
- clients/unshaded/src/main/java/tachyon/client/TachyonFSTestUtils.java
- clients/unshaded/src/main/java/tachyon/client/TachyonFile.java
- clients/unshaded/src/main/java/tachyon/client/block/BlockStoreContext.java
- clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystemUtils.java
- examples/src/main/java/tachyon/examples/BasicCheckpoint.java
- integration-tests/src/test/java/tachyon/master/file/FileSystemMasterIntegrationTest.java
- integration-tests/src/test/java/tachyon/master/rawtable/RawTableMasterIntegrationTest.java
- minicluster/src/main/java/tachyon/master/LocalTachyonCluster.java
- servers/src/main/java/tachyon/master/file/meta/InodeFile.java
- servers/src/main/java/tachyon/web/WebInterfaceMemoryServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceWorkersServlet.java
- servers/src/test/java/tachyon/master/block/BlockMasterTest.java
- shell/src/main/java/tachyon/shell/TfsShellUtils.java
...except unused imports in autogenerated Thrift files until
the fix to THRIFT-2794 happens in the next version of Thrift.
> [SMALLFIX] Remove all unused imports from the Tachyon codebase

- common/src/main/java/tachyon/collections/IndexedSet.java
- common/src/test/java/tachyon/collections/IndexedSetTest.java
- servers/src/main/java/tachyon/master/block/BlockMaster.java
- servers/src/main/java/tachyon/master/rawtable/meta/RawTables.java
Generics can't be safely passed into varargs because varargs creates an array of the generic type, and Java doesn't support generic arrays.
http://www.angelikalanger.com/GenericsFAQ/FAQSections/ProgrammingIdioms.html#FAQ300
> [SMALLFIX] Avoid or suppress vararg generic warnings

- servers/pom.xml
This resolves the warning our builds were giving:
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.tachyonproject:tachyon-servers:jar:0.9.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.sling:maven-jspc-plugin is missing. @ line 134, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```
> [SMALLFIX] Explicitly specify jspc version

- clients/unshaded/src/main/java/tachyon/client/block/TachyonBlockStore.java
- common/src/main/java/tachyon/resource/ResourcePool.java
ClientOptions is completely gone, and FileSystemMasterClientPool is in a separate project from ResourcePool, so it can't be linked by javadoc.
> [SMALLFIX] Remove links to inaccessible files

- clients/unshaded/src/main/java/tachyon/client/UfsUtils.java
- common/src/main/java/tachyon/Constants.java
- common/src/main/java/tachyon/Version.java
- examples/src/main/java/tachyon/examples/BasicCheckpoint.java
- examples/src/main/java/tachyon/examples/BasicNonByteBufferOperations.java
- examples/src/main/java/tachyon/examples/BasicOperations.java
- examples/src/main/java/tachyon/examples/BasicRawTableOperations.java
- examples/src/main/java/tachyon/examples/Performance.java
- servers/src/main/java/tachyon/Format.java
- servers/src/main/java/tachyon/master/TachyonMaster.java
https://tachyon.atlassian.net/browse/TACHYON-1193
`Constants` should be a dependency sink - it should not depend on other classes.
The build was breaking because `Constants` is used by `NetworkAddressUtils` to initialize its logger,
but `Constants` depended statically on `Version` which depended statically on initializing a `TachyonConf`, which used `NetworkAddressUtils` in its construction. This created a circular dependency starting and ending with `NetworkAddressUtils`, as you can see in the stack trace:
```
java.lang.ExceptionInInitializerError: null
at tachyon.util.network.NetworkAddressUtils.getLocalIpAddress(NetworkAddressUtils.java:356)
at tachyon.util.network.NetworkAddressUtils.getLocalHostName(NetworkAddressUtils.java:320)
at …
```
> [TACHYON-1193] Move jar location constant to Version to fix build

- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
Javadoc isn't great at understanding references to inner classes. In this case it needs the fully qualified name.
> [SMALLFIX] Fix broken link in javadoc

- servers/src/main/java/tachyon/worker/block/BlockDataManager.java
Was incorrectly using `TachyonTException` and importing it.
> [SMALLFIX] Fix the exception javadoc in BlockDataManager.

- assembly/pom.xml
- build/findbugs/findbugs-include.xml
- clients/client/pom.xml
- clients/pom.xml
- clients/unshaded/pom.xml
- common/pom.xml
- examples/pom.xml
- integration-tests/pom.xml
- integration/mesos/pom.xml
- integration/pom.xml
- integration/yarn/pom.xml
- minicluster/pom.xml
- pom.xml
- servers/pom.xml
- shell/pom.xml
- underfs/glusterfs/pom.xml
- underfs/hdfs/pom.xml
- underfs/local/pom.xml
- underfs/pom.xml
- underfs/s3/pom.xml
- underfs/swift/pom.xml
https://tachyon.atlassian.net/browse/TACHYON-1196
On my local machine this added around 1.5 minutes to the build, but was able to detect the cyclic dependency issue we had recently (https://tachyon.atlassian.net/browse/TACHYON-1193)
> [TACHYON-1196] Enable FindBugs to prevent static circular dependencies

- integration-tests/src/test/java/tachyon/client/TachyonFileSystemIntegrationTest.java
Hi, 
Removing the unused variables from TachyonFileSystemIntegrationTest (that are listed in the JIRA issue).
Removing other unused variables like sReadCache and mWorkerTachyonConf resulted in tests not passing.
> [TACHYON-1176] Remove unused variables in TachyonFileSystemIntegrationTest

- servers/src/main/java/tachyon/master/lineage/meta/Lineage.java
We only need to document it once.
> [SMALLFIX] Remove duplicated javadoc param in lineage.

- clients/unshaded/src/main/java/tachyon/client/file/FileInStream.java
- clients/unshaded/src/test/java/tachyon/client/block/BufferedBlockInStreamTest.java
- clients/unshaded/src/test/java/tachyon/client/block/TestBufferedBlockInStream.java
- clients/unshaded/src/test/java/tachyon/client/block/TestBufferedBlockOutStream.java
- clients/unshaded/src/test/java/tachyon/client/file/FileInStreamTest.java
- clients/unshaded/src/test/java/tachyon/client/util/ClientMockUtils.java
- clients/unshaded/src/test/java/tachyon/client/util/ClientTestUtils.java
ClientMockUtils are currently only used by FileInStreamTest, but they will soon be used by FileOutStreamTest after this commit merges.
> [TACHYON-1139] Add unit tests for FileInStream

- clients/unshaded/src/test/java/tachyon/client/file/FileInStreamTest.java
When possible it is better to avoid messing with the contents of the
test FileInStream
> [SMALLFIX] Mock FileSystemContext.INSTANCE instead of mContext

- servers/src/test/java/tachyon/master/journal/JsonJournalFormatterTest.java
The test was sometimes failing to find `"/home/jenkins/workspace/Tachyon-Pull-Request-Builder%403/servers/target/test-classes/tachyon/master/journal/JsonJournalEntries.json"`. I suspect that something is going wrong with our handling of a filename with `%` in it, so we will give Jackson the `URL` directly and see if the test continues to flake.
> [SMALLFIX] Simplify flaky JsonJournalFormatterTest

- docs/Command-Line-Interface.md
- docs/Configuration-Settings.md
- docs/File-System-API.md
- docs/Lineage-API.md
- docs/Running-Spark-on-Tachyon.md
- docs/Tiered-Storage-on-Tachyon.md
- docs/css/main.css
In Configuration page:
- Some columns are too thin to read due to previous columns too wide---making them wrappable by using `&#8203;` as line-break indicator.
- Add stripes into tables so they are easy to read.
> [SMALLFIX] Fix format of configuration page in docs for easier read 

- shell/src/main/java/tachyon/shell/TfsShell.java
- shell/src/test/java/tachyon/shell/TfsShellTest.java
https://tachyon.atlassian.net/browse/TACHYON-1212
in TfsShellTest, when calling "TfsShell.run", the array construction is not only verbose but also redundant (if we modify signature of run slightly to take varargs):
We want to change code from
```java
mFsShell.run(new String[] {"load", "/testRoot"});
```
to
```java
mFsShell.run("load", "/testRoot");
```
> [TACHYON-1212] Eliminate unnecessary array construction in TfsShellTest

- servers/src/main/java/tachyon/master/file/meta/InodeFile.java
- servers/src/main/java/tachyon/master/file/meta/options/CreatePathOptions.java
- servers/src/main/java/tachyon/master/file/options/CreateOptions.java
We should also change these methods to include the time unit in the name, e.g. setTtlMs.
@calvinjia Do you think it makes sense to deprecate setTTL() and recommend setTtlMs()?
> [SMALLFIX] Add and fix TTL javadocs

- common/src/main/java/tachyon/LeaderInquireClient.java
- common/src/main/java/tachyon/LeaderSelectorClient.java
- servers/src/main/java/tachyon/master/file/meta/MountTable.java
When a master restarts very quickly and creates a connection to zookeeper, zk still thinks it is the old client, so it thinks the master is the same, instead of a newly started master. This prevents the new master from taking leadership, and therefore, prevents any of the masters to be serving as the leader.
> [SMALLFIX] Fix master fault tolerant restart behavior

- servers/src/test/java/tachyon/master/file/FileSystemMasterTest.java
Trying to prevent flakes like https://amplab.cs.berkeley.edu/jenkins/job/Tachyon-Pull-Request-Builder/org.tachyonproject$tachyon-servers/6495/testReport/junit/tachyon.master.file/FileSystemMasterTest/createFileWithTTLTest/
If the JVM is having a *really* good day, it could run TTL cleanup before the 1ms TTL in the test has expired, causing the test to fail as in the linked example.
> [SMALLFIX] Prevent possible flakiness in createFileWithTTLTest

- common/src/main/java/tachyon/security/authentication/AuthenticationUtils.java
Sometimes, when a master failover happens, a client might try to send RPCs to the old master, but the RPC hangs forever, since the old master is standby now. Clients shouldn't wait forever to get a response from an RPC, so it can try to reconnect to the real leader master.
> [SMALLFIX] Use timeout for thrift RPCs

- clients/unshaded/src/main/java/tachyon/client/TachyonFS.java
- clients/unshaded/src/main/java/tachyon/client/TachyonFile.java
- clients/unshaded/src/main/java/tachyon/client/lineage/TachyonLineageFileSystem.java
- clients/unshaded/src/test/java/tachyon/client/file/options/UnmountOptionsTest.java
- common/src/main/java/tachyon/collections/IndexedSet.java
- common/src/main/java/tachyon/heartbeat/HeartbeatContext.java
- examples/src/main/java/tachyon/examples/BasicRawTableOperations.java
- integration-tests/src/test/java/tachyon/client/BufferedBlockInStreamIntegrationTest.java
- integration-tests/src/test/java/tachyon/client/FileInStreamIntegrationTest.java
- integration-tests/src/test/java/tachyon/client/TachyonFileSystemIntegrationTest.java
- integration-tests/src/test/java/tachyon/master/JournalShutdownIntegrationTest.java
- minicluster/src/main/java/tachyon/master/ClientPool.java
- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
- servers/src/main/java/tachyon/metrics/sink/JmxSink.java
- servers/src/main/java/tachyon/web/WebInterfaceDownloadServlet.java
- servers/src/main/java/tachyon/worker/block/io/LocalFileBlockReader.java
- servers/src/main/java/tachyon/worker/block/io/LocalFileBlockWriter.java
- servers/src/main/java/tachyon/worker/lineage/LineageWorker.java
- servers/src/test/java/tachyon/worker/block/BlockDataManagerTest.java
- shell/src/test/java/tachyon/shell/TfsShellTest.java
After this, 100% of our java warnings will be either from thrift or from deprecations.
> [SMALLFIX] Remove unused variables

- integration/pom.xml
- integration/yarn/pom.xml
- pom.xml
When compiling with developer profile, assembly/ failed due to undefined `${yarn.version}` in `integration/yarn/pom.xml`. Moving this definition into the dependency management session of parent pom.
> [SMALLFIX] Fix broken build of developer profile 

- common/src/main/java/tachyon/Constants.java
- common/src/main/resources/tachyon-default.properties
- minicluster/src/main/java/tachyon/master/LocalTachyonCluster.java
- servers/src/main/java/tachyon/master/TachyonMaster.java
- servers/src/main/java/tachyon/worker/block/BlockWorker.java
https://tachyon.atlassian.net/browse/TACHYON-1167
The default Thrift TThreadPoolServer timeout is 60 seconds. This was causing our
integration tests to wait until all outstanding RPCs were resolved before
completing. As a result, we were spending half of our integration test time
waiting for the Thrift server to stop. This commit fixes this by making the
timeout configurable via TachyonConf, and setting it to 0 for tests.
> [TACHYON-1167] Significantly speed up integration tests

- docs/Configuration-Settings.md
very simple correction (confirmed code says TachyonWorker)
> correct typo in tachyon.integration.mesos.worker.name default

- clients/unshaded/src/main/java/tachyon/client/netty/ClientHandler.java
Changed the type of ClientHandler.mListeners to 'Set' for https://tachyon.atlassian.net/browse/TACHYON-1185.
> [TACHYON-1185] Changed the type of ClientHandler.mListeners to 'Set'

- common/src/main/java/tachyon/TachyonURI.java
- common/src/main/java/tachyon/conf/TachyonConf.java
- common/src/main/java/tachyon/security/User.java
- servers/src/main/java/tachyon/SessionInfo.java
- servers/src/main/java/tachyon/master/block/journal/BlockContainerIdGeneratorEntry.java
- servers/src/main/java/tachyon/master/block/journal/BlockInfoEntry.java
- servers/src/main/java/tachyon/master/file/meta/Inode.java
- servers/src/main/java/tachyon/master/file/meta/InodeTree.java
- servers/src/main/java/tachyon/master/file/meta/TTLBucket.java
- servers/src/main/java/tachyon/worker/block/BlockStoreLocation.java
https://tachyon.atlassian.net/projects/TACHYON/issues/TACHYON-1205
This commit updated all equals() implementations to have same style with following exceptions:
- thrift classes since they are auto-generated;
- TachyonFile class since it has been deprecated
- Pair.java since it is generics
> [TACHYON-1205]: make equals() implementaion consistent

- clients/unshaded/src/main/java/tachyon/client/file/AbstractTachyonFileSystem.java
- clients/unshaded/src/main/java/tachyon/client/lineage/AbstractLineageClient.java
- clients/unshaded/src/main/java/tachyon/client/lineage/TachyonLineageFileSystem.java
- common/src/main/java/tachyon/exception/TachyonException.java
Followup to https://github.com/amplab/tachyon/pull/1787, which changed exception handling so that `TachyonException`s are never wrapped. After https://github.com/amplab/tachyon/pull/1787, any `unwrap(e, type)` followed by `throw e` does nothing at all and is a waste of cycles.
> [SMALLFIX] Remove unwrap

- deploy/vagrant/provision/playbook.yml
- deploy/vagrant/provision/roles/ufs_hadoop1/tasks/distribute_tachyon_client.yml
- deploy/vagrant/provision/roles/ufs_hadoop2/tasks/distribute_tachyon_client.yml
Reverts amplab/tachyon#1914
After this PR, vagrant deploys client jar to `$HADOOP_CLASSPATH` on starting the EC2 instances. However, it also makes `start-yarn.sh` fail to work. Revert this PR for now.
> Revert a80cbb2dcaa4d526287e04929d25f1da1bf61ed9

- clients/client/pom.xml
The reason of this PR is because `tachyon-underfs-glusterfs` depends on some library in hadoop 2.3.0. 
```
[INFO] +- org.tachyonproject:tachyon-underfs-glusterfs:jar:0.9.0-SNAPSHOT:compile
[INFO] |  \- org.gluster:glusterfs-hadoop:jar:2.3.13:compile
[INFO] |     \- org.apache.hadoop:hadoop-yarn-server-nodemanager:jar:2.3.0:compile
```
Once this client jar is in `$HADOOP_PATH` (which is not really required for Tachyon to work but may happen by mistakes), people may see the following error to stop YARN namenode to start if hadoop version > 2.4.0
```
************************************************************/
2015-11-09 10:46:48,382 INFO org.apache.hadoop.yarn.server.nodemanager.NodeManager: registered UNIX signal handlers for [TERM, HUP, INT]
2015-11-09 10:46:48,586 FATAL …
```
> [SMALLFIX] Remove tachyon-underfs-glusterfs from client uber jar

- clients/unshaded/src/main/java/tachyon/hadoop/AbstractTFS.java
Shouldn't link the exception in the throws clause.
> [SMALLFIX] Fix style in AbstractTFS javadoc.

- clients/unshaded/src/main/java/tachyon/hadoop/AbstractTFS.java
Previously if a user created the client with a url like tachyon:///path/to/data or
tachyon://localhost/path/to/data, missing either hostname or port, they would get
a NullPointerException or complaint about port -1 being invalid.
> [SMALLFIX] Improve error when incomplete tachyon uri is specified

- clients/unshaded/src/main/java/tachyon/hadoop/AbstractTFS.java
https://tachyon.atlassian.net/browse/TACHYON-1262
Followup to https://github.com/amplab/tachyon/pull/1970, which changed the behavior of mkdirs when creating a directory which already exists. This change is fine for the tachyon API, but our integration with Hadoop requires that we follow their `FileSystem.mkdirs` spec, which specifies `Existence of the directory hierarchy is not an error`
This is needed to fix this failure: https://amplab.cs.berkeley.edu/jenkins/job/Tachyon-Master/PROFILE=contractTest,label=centos/1415/
> [TACHYON-1262] Make AbstractTFS.mkdirs return true when the folder exists

- clients/unshaded/src/main/java/tachyon/client/block/BufferedBlockInStream.java
- clients/unshaded/src/main/java/tachyon/client/block/LocalBlockInStream.java
- clients/unshaded/src/main/java/tachyon/client/block/RemoteBlockInStream.java
- clients/unshaded/src/main/java/tachyon/client/block/TachyonBlockStore.java
- clients/unshaded/src/test/java/tachyon/client/block/TestBufferedBlockInStream.java
The protected field is never used in the abstract class or any other
subclasses, so we might as well move it to RemoteBlockInStream
> [SMALLFIX] Move mLocation into RemoteBlockInStream

- integration-tests/src/test/java/tachyon/LocalTachyonClusterResource.java
This is a Junit rule, which serves as sort-of a mixin for integration
tests. The goal is that instead of creating and managing your own
LocalTachyonCluster for every integration test, you use a
LocalTachyonClusterResource, with some basic defaults, and can employ
per-class or per-method configuration on it.
The rule can also be created as a static class, which means its only
initialized once per suite, rather than once per method.
> [TACHYON-988] Added LocalTachyonClusterResource

- clients/unshaded/src/main/java/tachyon/client/block/BufferedBlockInStream.java
Just removed the ```location``` parameter from the JavaDoc in the ```BufferedBlockInStream``` constructor, which is not in the parameter list.
> [SMALLFIX] Removed not used 'location' parameter in JavaDoc

- clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystemUtils.java
Fixed link to the right constant in JavaDoc for ```waitCompleted``` method in ```TachyonFileSystemUtils```.
> [SMALLFIX] Fixed documentation in TachyonFileSystemUtils

- clients/unshaded/src/test/java/tachyon/client/block/TachyonBlockStoreTest.java
This is not meant to be comprehensive. This should make it easier to fill out the rest of the unit tests for `TachyonBlockStore` in the future.
> [SMALLFIX] Add unit tests for TachyonBlockStore.getInStream

- servers/src/main/java/tachyon/web/WebInterfaceDownloadLocalServlet.java
`tachyon.logs.dir=${tachyon.home}/logs` is not always true as we could specify `tachyon.logs.dir` separately.
Eliminate this assumption in our codebase
> [TACHYON-1310] Fix possible wrong assumption to derive logs dir

- common/src/main/java/tachyon/security/authentication/AuthenticationUtils.java
- common/src/main/resources/tachyon-default.properties
https://tachyon.atlassian.net/browse/TACHYON-1278
Logging revealed that `createRawTable` is taking the server ~32 seconds, but our socket timeout of 30 seconds ruins everything.
> [TACHYON-1278] Extend socket timeout to fix build

- integration-tests/src/test/java/tachyon/master/file/FileSystemMasterIntegrationTest.java
Temporary fix for errors like
```
getCapacityBytesTest(tachyon.master.file.FileSystemMasterIntegrationTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1000> but was:<0>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at tachyon.master.file.FileSystemMasterIntegrationTest.getCapacityBytesTest(FileSystemMasterIntegrationTest.java:513)
```
Eventually we should improve `LocalTachyonClusterResource` to properly wait for everything to start.
> [SMALLFIX] Prevent flakiness in getCapacityBytesTest()

- integration-tests/src/test/java/tachyon/master/ServiceSocketBindIntegrationTest.java
Sometimes the services are too slow to start and Jenkins fails with something like
```
listenEmptyTest(tachyon.master.ServiceSocketBindIntegrationTest)  Time elapsed: 0.561 sec  <<< ERROR!
java.net.ConnectException: Connection refused
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:579)
at java.net.Socket.connect(Socket.java:528)
at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
at …
```
> [SMALLFIX] Prevent flakiness in ServiceSocketBindIntegrationTest

- conf/core-site.xml.template
This small typo could have people wondering why their settings aren't having effect.
> [SMALLFIX] Fix typo in core-site.xml swift config

- clients/unshaded/src/test/java/tachyon/client/util/ClientMockUtils.java
Fixed problems in JavaDoc references in ```ClientMockUtils```.
> [SMALLFIX] Fixed link in documentation in 'ClientMockUtils'

- bin/tachyon-start.sh
Previously if the master or worker failed to start, it was difficult to figure out why without reading the tachyon-start script.
> [SMALLFIX] Add mention in startup script about where logs are going

- servers/src/main/java/tachyon/worker/block/allocator/GreedyAllocator.java
Fixed problems in JavaDoc references in ```GreedyAllocator```.
> [SMALLFIX] Fixed link in documentation in 'GreedyAllocator'

- common/src/main/java/tachyon/replay/ReplayCache.java
Added a missing closing bracket in the documentation of the ```ReplayCallableThrowsIOException<V>``` interface.
> [SMALLFIX] Added missing bracket in Javadoc in 'ReplayCache'

- integration-tests/src/test/java/tachyon/client/FileInStreamIntegrationTest.java
The thrown exception is ```TachyonException```, not ```TException```.
> [SMALLFIX] Changed thrown exception in Javadoc in 'FileInStreamIntegrationTest'

- servers/src/main/java/tachyon/master/file/meta/InodeFile.java
- servers/src/main/java/tachyon/worker/package-info.java
persistFile is no longer done by the worker, so we can remove the feature
from the worker package javadoc
> [SMALLFIX] Fix javadoc errors

- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
- servers/src/main/java/tachyon/master/file/meta/InodeTree.java
- shell/src/test/java/tachyon/shell/TfsShellTest.java
One case where loadMetadata would fail is when the user calls "ls" on a
directory in the UFS that hasn't been loaded yet, which creates the
inode in the tree, but doesn't mark it as persisted, because the UFS
failed to create the directory (since it already existed). Then when
they call loadMetadata, creating the directory would again try to mark
it as persisted and fail for the same reason, and loadMetadata would
crash because it expected that either a directory was created, or an
exception is thrown.
This modifies InodeTree.createPath to mark a directory as persisted
regardless of whether the ufs directory was actually created or
not (because if it was not, that means it already existed). Now
loadMetadata will throw the proper error message when the directory has
already been loaded …
> [TACHYON-1333] Fixed UFS mkdir persistence

- integration-tests/src/test/java/tachyon/hadoop/TFSRenameIntegrationTest.java
https://tachyon.atlassian.net/browse/TACHYON-1337
This test was unignored in https://github.com/amplab/tachyon/pull/2106, but breaks on the `hdfs1Test` profile.
> [TACHYON-1337] Revert un-ignore of broken test

- servers/src/test/java/tachyon/worker/block/TieredBlockStoreTestUtils.java
```setupTachyonConfWithSingleTier``` is a void method and does not need a ```@return``` statement in the documentation.
> [SMALLFIX] Removed unnecessary return statement in Javadoc in 'TieredBlockStoreTestUtils'

- servers/src/main/java/tachyon/worker/block/allocator/RoundRobinAllocator.java
Removed colon after ```@return``` statement in documentation for ```getNextAvailDirInTier```  method.
> [SMALLFIX] Fixed return tag in documentation in 'RoundRobinAllocator'

- common/src/main/java/tachyon/resource/ResourcePool.java
- common/src/test/java/tachyon/resource/ResourcePoolTest.java
Even with the following configuration, I sometimes got starvation at resource getting.
```
tachyonConf.set(Constants.USER_FILE_MASTER_CLIENT_THREADS, Integer.toString(50000));
tachyonConf.set(Constants.USER_BLOCK_MASTER_CLIENT_THREADS, Integer.toString(50000));
```
By first checking available resource without synchronization, we could mitigate thread contention somewhat.
> [TACHYON-1329] Mitigate thread contention at resource getting

- common/src/main/java/tachyon/exception/ExceptionMessage.java
- common/src/main/java/tachyon/security/authentication/PlainSaslServer.java
- common/src/main/java/tachyon/security/authorization/PermissionStatus.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-1343
Fix the issue and refine exception message.
In hdfs2Test profile, `PLAIN` mechanism is set as `org.apache.hadoop.security.SaslPlainServer`. `tachyon.security.authentication.PlainSaslServer` does not take effect. So the threadlocal user is not set by method `evaluateResponse()`. We move the setting user into callback handler, which can be executed no matter what the underlying `SaslServer` is.
@jsimsa , @apc999
> [TACHYON-1343] Build break for MasterClientAuthenticationIntegrationTest

- integration-tests/src/test/java/tachyon/client/LocalBlockInStreamIntegrationTest.java
The thrown exception is ```TachyonException```, not ```TException```.
> [SMALLFIX] Changed thrown exception in Javadoc in 'LocalBlockInStreamIntegrationTest'

- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
Added the missing documentation for the ```fileId``` parameter of the ```getFileInfoList``` in the ```FileSystemMaster``` class.
> [SMALLFIX] Added documentation for the 'fileId' of the 'getFileInfoList' method in the 'FileSystemMaster' class

- clients/unshaded/src/main/java/tachyon/client/ClientContext.java
- clients/unshaded/src/main/java/tachyon/hadoop/AbstractTFS.java
- clients/unshaded/src/test/java/tachyon/hadoop/TFSTest.java
- common/src/main/java/tachyon/Constants.java
- common/src/main/java/tachyon/conf/TachyonConf.java
- common/src/main/java/tachyon/util/network/NetworkAddressUtils.java
- common/src/test/java/tachyon/conf/TachyonConfTest.java
- common/src/test/java/tachyon/util/network/GetMasterWorkerAddressTest.java
- common/src/test/java/tachyon/util/network/NetworkAddressUtilsTest.java
- examples/src/main/java/tachyon/examples/BasicNonByteBufferOperations.java
- examples/src/main/java/tachyon/examples/BasicOperations.java
- examples/src/main/java/tachyon/examples/Performance.java
- minicluster/src/main/java/tachyon/master/AbstractLocalTachyonCluster.java
- minicluster/src/main/java/tachyon/master/LocalTachyonCluster.java
- minicluster/src/main/java/tachyon/master/LocalTachyonClusterMultiMaster.java
- minicluster/src/main/java/tachyon/master/LocalTachyonMaster.java
- servers/src/main/java/tachyon/master/TachyonMaster.java
- servers/src/main/java/tachyon/worker/block/BlockWorker.java
- shell/src/main/java/tachyon/shell/TfsShellUtils.java
We call the master web port `MASTER_WEB_PORT` and the worker web and data ports `WORKER_WEB_PORT` and `WORKER_DATA_PORT`.
> Rename Master and Worker RPC port Constants for consistency

- integration-tests/src/test/java/tachyon/master/file/FileSystemMasterIntegrationTest.java
This sleep is no longer needed now that test cluster startup blocks on worker registration with master.
> [SMALLFIX] Remove unneeded sleep

- clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystemUtils.java
https://tachyon.atlassian.net/browse/TACHYON-1377
We need to use `toString()` instead of `getPath()` because `getPath()` drops the authority information, making it look like filesystem should be used. Props to @calvinjia for helping with finding this.
> [TACHYON-1377] Fix shell persist command to work with hdfs

- integration-tests/src/test/java/tachyon/master/file/FileSystemMasterIntegrationTest.java
https://tachyon.atlassian.net/browse/TACHYON-1378
The explanation of the problem is in the JIRA ticket, copied here for convenience.
The failing test creates a file with a 1 millisecond time to live(TTL), waits 5000 milliseconds, then asserts that the file does not exist. The TachyonConf is set so that the TTL interval is 1000ms. It should never take more than 2x the TTL interval for an expired file to be cleaned up, so this should be adequate.
When this failure occurs, it is because a TTL interval of MAX_INT ms is used instead of the configured 1000ms. This occurs precisely when the build happens to run TfsShellTest first (integration test ordering is arbitrary). When TfsShellTest runs first, it sets the TachyonConf to use MAX_INT for the TTL interval. When the TTLBucket class loads …
> [TACHYON-1378] Fix flaky ttlExpiredCreateFileTest

- common/src/main/java/tachyon/security/LoginUser.java
- common/src/main/java/tachyon/security/authentication/AuthenticationProvider.java
- common/src/main/java/tachyon/security/authentication/AuthenticationUtils.java
- common/src/main/java/tachyon/security/authentication/CustomAuthenticationProviderImpl.java
- common/src/main/java/tachyon/security/authentication/PlainSaslServer.java
- common/src/main/java/tachyon/security/authentication/PlainSaslServerProvider.java
- common/src/main/java/tachyon/security/authentication/PlainSaslUtils.java
- common/src/main/java/tachyon/security/authorization/PermissionStatus.java
- common/src/main/java/tachyon/security/login/AppLoginModule.java
- common/src/main/java/tachyon/security/login/TachyonJaasConfiguration.java
> [TACHYON-935] Added the usage of links in the documentation in the tachyon.security packages

- underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystemFactory.java
https://tachyon.atlassian.net/browse/TACHYON-1325
This significantly speeds up mkdir, bringing the time for `RawTableIntegrationTest.getColumnsTest` from 70 seconds to 20 seconds on my machine. I noticed that we were explicitly disabling caching (https://github.com/amplab/tachyon/blob/f297b579022ccfed8c55107df04b927ac652e35d/underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystem.java#L107). Is there a known issue with caching besides the call to `FileSystem.close()` in `HdfsUnderFileSystem.close()` (https://github.com/amplab/tachyon/blob/f297b579022ccfed8c55107df04b927ac652e35d/underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystem.java#L118) which I have removed?
> [TACHYON-1325] Cache FileSystems in HdfsUnderFileSystem

- servers/src/main/java/tachyon/metrics/sink/Sink.java
Removed the unnecessary public modifiers in the ```Sink```  interface.
> [SMALLFIX] Removed public modifier in 'Sink' interface

- common/pom.xml
- integration-tests/pom.xml
- servers/pom.xml
- shell/pom.xml
- underfs/glusterfs/pom.xml
- underfs/hdfs/pom.xml
- underfs/local/pom.xml
- underfs/s3/pom.xml
- underfs/swift/pom.xml
The shell module no longer has tests since we moved TfsShellTest to integration-tests, so we don't need test dependencies.
Previously we would often superfluously specify the test scope in child poms even though we've already specified the test scope in the parent pom's `<dependencyManagement>` section. See https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management for info about how this works.
> [SMALLFIX] Pom cleanup

- common/src/test/java/tachyon/security/authentication/AuthenticationUtilsTest.java
This is better, because 'locahost' might not always be resolved to the correct IP address, as in virtual network.
> [SMALLFIX] Use InetAddress.getLocalHost() instead of hardcoded localhost

- docs/Contributing-to-Tachyon.md
- Fix grammar/wording
- Changed `Startup Tasks for New Contributors` to make it sound less mandatory. Almost all new contributor and beginner tickets can be done without doing any of these tasks.
> [SMALLFIX] Update Contributing to Tachyon guide

- docs/Command-Line-Interface.md
The documentation on http://tachyon-project.org/documentation/master/Command-Line-Interface.html uses the ```remote source```  parameter instead of ```remote path```.
> [SMALLFIX] Changed documentation of CLI copyToLocal command from 'remote source' to 'remote path'

- servers/src/main/java/tachyon/Format.java
If `tachyon.master.journal.folder` is set to `/journal`, the original code will not create `_format_xxx` under the `/journal` directory, which will mislead tachyon to believe that master is not formatted.
> [SMALLFIX] Use concatPath for better portability

- common/src/main/java/tachyon/exception/ExceptionMessage.java
- integration-tests/src/test/java/tachyon/client/TachyonFileSystemIntegrationTest.java
- integration-tests/src/test/java/tachyon/shell/TfsShellTest.java
- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
- servers/src/main/java/tachyon/master/file/meta/MountTable.java
- servers/src/test/java/tachyon/master/file/meta/MountTableTest.java
For correctness and simplicity, we place a few restrictions on mounting
paths:
1. You cannot mount a UFS path that is a prefix or a suffix of an
already-mounted UFS path
2. You cannot mount to a Tachyon path that shadows a path in the default
underfs
3. The UFS path you are mounting must exist at mount time
> [Tachyon-1333] Improved mount path checking

- integration-tests/src/test/java/tachyon/security/WorkerClientAuthenticationIntegrationTest.java
This test flaked recently (https://amplab.cs.berkeley.edu/jenkins/view/Tachyon/job/Tachyon-Master/PROFILE=hdfs2Test,label=centos/1562/). This fixes a race condition where a thread comes along and regenerates `sLoginUser` after `clearLoginUser()` but before `System.setProperty(Constants.SECURITY_LOGIN_USERNAME, "no-tachyon")`.
> [SMALLFIX] Clean up WorkerClientAuthenticationIntegrationTest

- common/src/main/java/tachyon/underfs/UnderFileSystem.java
- integration-tests/src/test/java/tachyon/underfs/UnderStorageSystemInterfaceIntegrationTest.java
Turns out the version of Hadoop we support doesn't have any mechanism
for listing recursively, so all underfs's use the default
implementation.
> [TACHYON-1399] Implemented listRecursive

- servers/src/main/java/tachyon/worker/lineage/LineageWorker.java
[TACHYON-1404]
Remove the following line in tachyon/worker/lineage/LineageWorker.java because it is no more meaningful.
"/** Threadpool for the lineage master sync */"
> [TACHYON-1404] Remove one unused comment in tachyon/worker/lineage/LineageWorker.java

- build/checkstyle/tachyon_checks.xml
- clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystem.java
- clients/unshaded/src/main/java/tachyon/client/table/TachyonRawTables.java
- clients/unshaded/src/main/java/tachyon/hadoop/ConfUtils.java
- common/src/main/java/tachyon/exception/PreconditionMessage.java
- integration-tests/src/test/java/tachyon/client/StreamOptionUtils.java
- integration/yarn/src/test/java/tachyon/yarn/ApplicationMasterTest.java
- servers/src/main/java/tachyon/Format.java
- servers/src/main/java/tachyon/ValidateConf.java
- servers/src/main/java/tachyon/master/TachyonMaster.java
- servers/src/main/java/tachyon/master/file/meta/options/CreatePathOptions.java
- servers/src/main/java/tachyon/web/WebInterfaceGeneralServlet.java
- servers/src/main/java/tachyon/web/WebInterfaceWorkersServlet.java
- servers/src/main/java/tachyon/worker/block/BlockMetadataManager.java
- servers/src/main/java/tachyon/worker/block/ClientRWLock.java
- servers/src/test/java/tachyon/worker/block/BlockLockManagerTest.java
[TACHYON-1430] Add the checkstyle rule FinalClass
JIRA link https://tachyon.atlassian.net/browse/TACHYON-1430
Add the FinalClass checkstyle module in build/checkstyle/tachyon_checks.xml to enable style checks that a class which has only private constructors is declared as final. And with this check, find several classes not fit the rule.
There are:
clients/unshaded/src/main/java/tachyon/client/file/TachyonFileSystem.java
clients/unshaded/src/main/java/tachyon/client/table/TachyonRawTables.java
clients/unshaded/src/main/java/tachyon/hadoop/ConfUtils.java
common/src/main/java/tachyon/exception/PreconditionMessage.java
integration-tests/src/test/java/tachyon/client/StreamOptionUtils.java
servers/src/main/java/tachyon/Format.java
servers/src/main/java/tachyon/ValidateConf.java …
> [TACHYON-1430] Add the checkstyle rule FinalClass

- build/findbugs/findbugs-exclude.xml
- minicluster/pom.xml
- minicluster/src/main/java/tachyon/master/LocalTachyonMaster.java
- pom.xml
- servers/pom.xml
- servers/src/main/java/tachyon/master/block/BlockMaster.java
- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
- servers/src/main/java/tachyon/master/lineage/LineageMaster.java
- servers/src/main/java/tachyon/worker/nio/NIODataServer.java
Add findbug rule for unread/unused private variables. The public/protected ones are allowed since they may be used with classes not seen as part of the analysis.
Also, this PR suppresses the found bugs with `@edu.umd.cs.findbugs.annotations.SuppressFBWarnings("URF_UNREAD_FIELD")`
> [TACHYON-1318] Add a findbug rule of finding unused variables

- bin/tachyon-mount.sh
`free -b` would truncate value if total memory is over 100GB, and TACHYON_WORKER_MEMORY_SIZE will not work as expected.
> [TACHYON-1450] TACHYON_WORKER_MEMORY_SIZE does not work as expected when bare metal total memory is over 100GB

- common/src/main/java/tachyon/conf/TachyonConf.java
Fixed the ```{@link ...}``` usage in ```checkUserFileBufferBytes``` method in the ```TachyonConf``` class.
> [SMALLFIX] Fixed documentation links for 'checkUserFileBufferBytes' in TachyonConf

- bin/tachyon-start.sh
- docs/Running-Tachyon-on-a-Cluster.md
Some users complain that when they start or restart Tachyon, their data on RAMFS, including the previous data in Tachyon's RAMFS, is lost. Acutally, our tachyon-start.sh comand does not explicitly tell the users about the formating RAMFS operation triggered by the Mount. Thus, the users that familiar with HDFS's or other file systems' commands may hardly be aware of the risk. I think it is necessary to add this prompt in the corresponding script and docs. This SMALLFIX address this issue. @calvinjia
> [SMALLFIX] Prompt users that the mount op in start script will format the RamFS

- common/src/main/java/tachyon/conf/TachyonConf.java
The ```getList``` method of the ```TachyonConf``` class has a ```delimiter``` parameter, but isn't actually using it. Instead it uses a comma as a hard-coded value. Added the parameter to the ```Splitter.on``` method to make use of it.
> [SMALLFIX] Added the usage of the delimiter parameter to the 'getList' method of the 'TachyonConf' class

- common/src/test/java/tachyon/security/UserTest.java
The ```usedInSecurityContextTest``` in the ```UserTest``` doesn't throw an ```Exception```. Removed it from the signature of the method.
> [SMALLFIX] Changed the signature of 'usedInSecurityContextTest' in 'UserTest'

- docs/Developer-Tips.md
I added the full list of the commands in bin/tachyon with detailed explanations of their meanings in  the Developer-Tips.md. It looks as below.
> [TACHYON-1379] Add docs for all commands in bin/tachyon

- docs/Configuration-Settings.md
https://tachyon.atlassian.net/browse/TACHYON-1402
I have added some properties to docs to match up with the ones in `tanchyon-default.properties`, except the following ones. The reasons are described as below.
**`tachyon.security.*`** - The security properties are related to [[TACHYON-789](https://tachyon.atlassian.net/browse/TACHYON-789)]Tachyon Security, which is WIP. So, I left them behind. I think when [[TACHYON-789](https://tachyon.atlassian.net/browse/TACHYON-789)]  is finished, we can add the `tachyon.security.*` into docs.
**`tachyon.version`** - This is the project-build property used inside the project, and it cannot be configured. So, we didn't add it into docs.
**`tachyon.*.hostname`** - These default values are undefined in `tachyon-default.properties` but Tachyon will …
> [TACHYON-1402] Handle parameter inconsistency between docs and default properties

- common/src/main/java/tachyon/Constants.java
- common/src/main/resources/tachyon-default.properties
- minicluster/src/main/java/tachyon/master/AbstractLocalTachyonCluster.java
- servers/src/main/java/tachyon/master/TachyonMaster.java
- servers/src/main/java/tachyon/worker/block/BlockWorker.java
This is better than a configuration parameter because we only modify
it for tests and we do not expect users to care about it.
> [SMALLFIX] Make thrift stop timeout a Constant

- common/src/main/java/tachyon/LeaderInquireClient.java
- integration-tests/src/test/java/tachyon/master/MasterFaultToleranceIntegrationTest.java
- minicluster/src/main/java/tachyon/master/LocalTachyonCluster.java
- minicluster/src/main/java/tachyon/master/LocalTachyonClusterMultiMaster.java
- minicluster/src/main/java/tachyon/master/LocalTachyonMaster.java
- servers/src/main/java/tachyon/master/TachyonMaster.java
Reverts amplab/tachyon#1587
Since merging this the build has been hanging in `MasterFaultToleranceIntegrationTest`
See https://amplab.cs.berkeley.edu/jenkins/view/Tachyon/job/Tachyon-Master/PROFILE=hdfs1Test,label=centos/1649/console and https://amplab.cs.berkeley.edu/jenkins/view/Tachyon/job/Tachyon-Master/PROFILE=hdfs1Test,label=centos/1648/console
> Revert "[TACHYON-987] Enable fault tolerant tests"

- bin/tachyon
When I use the bin/tachyon runTest following the runTest task usage help to test the OSSUnderFilssystem in a real environment, the test didn't work, then I found this is because the runTest usage help information is out of date.  
Fix it can help new users escape from been confused
> [TACHYON-1466] bin/tachyon runTest usage help info out of date

- common/src/main/java/tachyon/security/group/GroupMappingService.java
Removed the redundant ```public``` modifier from the ```GroupMappingService``` interface.
> [SMALLFIX] Removed public modifier from interface

- common/src/test/java/tachyon/collections/PrefixListTest.java
Removed the explicit ```String``` type which can be inferred.
> [SMALLFIX] Removed inferred type

- common/src/test/java/tachyon/util/network/NetworkAddressUtilsTest.java
The ```testGetBindAddress``` method in the ```NetworkAddressUtilsTest``` wasn't actually testing the binding of the addresses. The test is now pointing to the correct helper method. In this method the different service types are now setting the port for their specific configuration.
> [SMALLFIX] Fixed test in 'NetworkAddressUtilsTest'

- integration-tests/src/test/java/tachyon/client/UfsUtilsIntegrationTest.java
The test was checking the wrong directories for existence, so
a system with a directory at /tachyon would fail the test.
> [SMALLFIX] Fix bug in UfsUtilsIntegrationTest

- common/src/main/java/tachyon/util/io/BufferUtils.java
https://tachyon.atlassian.net/browse/TACHYON-1442
Only log the error message when the buffer is supposed to have a non-null Cleaner. Otherwise when the buffer is empty, the Cleaner is actually set as null during initialization.
> better error message for cleanDirectBuffer

- integration-tests/src/test/java/tachyon/client/table/RawTableIntegrationTest.java
As a Christmas present to Jenkins, I am ignoring this test which has been plaguing our build for months.
As a New Years resolution, we will get to the root of why this test is failing.
> [SMALLFIX] Ignore flaky test to stabilize build

- integration-tests/pom.xml
- integration-tests/src/test/java/tachyon/underfs/oss/OSSUnderStorageCluster.java
Add the OSSUnderStorageCluster for OSSUnderFilesystem integration test.
we should config the pom.xml in integration-test, change four properties below:
1, fs.oss.accessKeyId (the oss access id)
2, fs.oss.accessKeySecret (the oss access secret key)
3, fs.oss.endpoint (because the uri endpoint are different from range to another range,eg: hangzhou, shanghai, Singapore, HongKong...)
4, ossBucket (the bucket address when the tests run into)
The integration test of OSS is much like the test of S3UnderFileSystem,  but I noticed that in the current master ， the integration tests for S3 cannot run successfully. I use my own aws id and key to run and keeps fail like below:
```java
java.lang.IllegalArgumentException: All eligible Under File Systems were unable to create an instance for the given …
```
> [TACHYON-1460] Add integration test for the OSS UnderFileSystem

- conf/tachyon-env.sh.template
In the conf/tachyon-env.sh， TACHYON_RAM_FOLDER should be set to specify the worker's mem dirs. But I noticed that after I set :
TACHYON_RAM_FOLDER="/dev/shm"
in the begin line of tachyon-env.sh, the set never worked.  Look into the tachyon-env.sh, found that this is because the script below:
```shell
JAVA_HOME="/usr/lib/jvm/java"
TACHYON_UNDERFS_ADDRESS="hdfs://rs3g13002:9100/tachyon"
TACHYON_MASTER_ADDRESS="rs3g13002"
TACHYON_WORKER_MEMORY_SIZE="20gb"
TACHYON_RAM_FOLDER="/dev/shm"
#=======  I add some config as above =======
if [[ $(uname -s) == Darwin ]]; then
export JAVA_HOME=${JAVA_HOME:-$(/usr/libexec/java_home)}
export TACHYON_RAM_FOLDER=/Volumes/ramdisk
export TACHYON_JAVA_OPTS="-Djava.security.krb5.realm= -Djava.security.krb5.kdc="
else
if [[ -z "$JAVA_HOME" ]]; then
if [ -d …
```
> [TACHYON-1465] TACHYON_RAM_FOLDER in tachyon-env.sh not working

- clients/unshaded/src/main/java/tachyon/client/block/LocalBlockInStream.java
Removed the redundant ```null``` initialization in ```LocalBlockInStream```.
> [SMALLFIX] Removed redundant 'null'

- integration-tests/pom.xml
- integration-tests/src/test/java/tachyon/underfs/s3/S3UnderStorageCluster.java
when I run the S3UnderStorageCluster integration test using below command, 
```shell
mvn clean -Dtest=UnderStorageSystemInterfaceIntegrationTest -DfailIfNoTests=false test -Ps3Test
```
the test will fail:
```
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running tachyon.underfs.UnderStorageSystemInterfaceIntegrationTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.594 sec <<< FAILURE!
tachyon.underfs.UnderStorageSystemInterfaceIntegrationTest  Time elapsed: 0.594 sec  <<< ERROR!
java.lang.IllegalArgumentException: All eligible Under File Systems were unable to create an instance for the given path: s3n://luolis3first/d9a94bf2-04c8-4e21-8b78-3e03e1f30d90/journal6997639942459671163 …
```
> [TACHYON-1469] S3UnderStorageCluster integration test fail

- integration/yarn/src/main/java/tachyon/yarn/ApplicationMaster.java
The previous code would fail if `resourcePath` didn't end with a "/", e.g. 
`./tachyon-yarn.sh 2 hdfs://TachyonMaster:9000/tmp`
> Concatenate paths with PathUtils.concatPath

- integration-tests/src/test/java/tachyon/underfs/s3/S3UnderStorageCluster.java
No longer have weird file names when the user specifies a bucket without a trailing slash.
> [SMALLFIX] Clean up s3 cluster

- common/src/main/java/tachyon/util/FormatUtils.java
I was receiving the error below when I was executing 'mvn install' under tachyon dir:
getSizeFromBytesTest(tachyon.util.FormatUtilsTest)  Time elapsed: 0.007 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<4[.]00B> but was:<4[,]00B>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at tachyon.util.FormatUtilsTest.getSizeFromBytesTest(FormatUtilsTest.java:188)
So I fixed a Locale output format for the decimal numbers as 'Locale.ENGLISH' .
> [SMALLFIX] Update decimal number format

- servers/src/main/java/tachyon/worker/block/allocator/RoundRobinAllocator.java
- servers/src/test/java/tachyon/worker/block/allocator/AllocatorContractTest.java
- servers/src/test/java/tachyon/worker/block/allocator/BaseAllocatorTest.java
- servers/src/test/java/tachyon/worker/block/allocator/GreedyAllocatorTest.java
- servers/src/test/java/tachyon/worker/block/allocator/MaxFreeAllocatorTest.java
- servers/src/test/java/tachyon/worker/block/allocator/RoundRobinAllocatorTest.java
https://tachyon.atlassian.net/browse/TACHYON-1511
Previously we stored a Map from tier to latest directory index
for that tier. However, the keys were references to StorageTierViews,
which are not globally unique. This resulted in lookups always
returning null. This change uses the String tier aliases as keys
instead.
> [TACHYON-1511] Fix tier lookup in RoundRobinAllocator

- servers/src/main/java/tachyon/master/file/FileSystemMaster.java
Add comments for the confused logic in `FileSystemMaster.checkPermission()` method.
@apc999 , please let me know if any more comments is needed to help readers to understand easily.
> [SMALLFIX] Add comments for confused logic in checkPermission method

- underfs/swift/pom.xml
Removed the duplicate JUnit dependency declaration in the Swift module.
> [SMALLFIX] Removed duplicate JUnit dependency

- clients/unshaded/src/main/java/tachyon/hadoop/AbstractTFS.java
Hdfs 1.x doesn't have a `FileSystem#getScheme` method, so we can't put `@Override`
> [SMALLFIX] Fix AbstractTFS compilation with hdfs1

- bin/tachyon-stop.sh
When people run bin/tachyon-stop.sh, he(she) may think that the stop shell will print usage as tachyon-start.sh does. And following the usage, people can specify which component(s) he(she) want to stop. 
But now, when people run bin/tachyon-stop.sh, the script will stop master and all workers by default. And this probably is not what people want and all components has been stopped.
Maybe we can follow the tachyon-start.sh custom, print usage by default in tachyon-stop.sh
> [TACHYON-1528] tachyon-stop.sh should not stop all but print usage by default

- common/src/main/java/tachyon/network/protocol/databuffer/DataBuffer.java
https://tachyon.atlassian.net/browse/TACHYON-1354
All "public" keywords of methods in DataBuffer interface have been removed
> [TACHYON-1354] Remove "public" keywords from DataBuffer interface

- underfs/oss/src/main/java/tachyon/underfs/oss/OSSInputStream.java
OSSInputStream should not throw exception in skip(long n), that will make lots of the integration test of oss fail. And the skip logic can just like the java.io.InputStream: read n bytes and just discards them , just this logic will work.
I added a TODO to remind that after oss sdk support getObject in a special position, I will update the implements of this method.
Please see https://tachyon.atlassian.net/browse/TACHYON-1527
> [TACHYON-1527] OSSInputStream should not throw exception in skip()

- integration-tests/src/test/java/tachyon/security/BlockWorkerClientAuthenticationIntegrationTest.java
- minicluster/src/main/java/tachyon/master/LocalTachyonCluster.java
- servers/src/main/java/tachyon/master/block/BlockMaster.java
- servers/src/main/java/tachyon/master/block/BlockMasterWorkerServiceHandler.java
- servers/src/main/java/tachyon/master/block/meta/MasterWorkerInfo.java
- servers/src/main/java/tachyon/worker/TachyonWorker.java
- servers/src/main/java/tachyon/worker/WorkerContext.java
- servers/src/main/java/tachyon/worker/WorkerIdRegistry.java
- servers/src/main/java/tachyon/worker/block/BlockMasterSync.java
- servers/src/main/java/tachyon/worker/block/BlockWorker.java
- servers/src/test/java/tachyon/master/MasterSourceTest.java
- servers/src/test/java/tachyon/master/block/BlockMasterTest.java
- servers/src/test/java/tachyon/master/block/meta/MasterWorkerInfoTest.java
- servers/src/test/java/tachyon/master/file/FileSystemMasterTest.java
Purpose of this PR is to use `NetAddress` which is a defined class, rather than thrift-derived class, as possible in the code. So the detail of RPC framework is abstracted away
> [SMALLFIX] Switch to using NetAddress from thrift defined WorkerNetAddress

- bin/tachyon-start.sh
- docs/Building-Tachyon-Master-Branch.md
- docs/Configuring-Tachyon-with-GlusterFS.md
- docs/Configuring-Tachyon-with-HDFS.md
- docs/Configuring-Tachyon-with-OSS.md
- docs/Configuring-Tachyon-with-S3.md
- docs/Configuring-Tachyon-with-Swift.md
- docs/Running-Hadoop-MapReduce-on-Tachyon.md
- docs/Running-Tachyon-Locally.md
- docs/Running-Tachyon-on-EC2-Yarn.md
- examples/src/main/java/tachyon/examples/JournalCrashTest.java
[TACHYON-1528](https://tachyon.atlassian.net/browse/TACHYON-1528) changed the stop logic to print usage info by default when run the `bin/tachyon-stop.sh`. With this update, `bin/tachyon-start.sh`'s logic has been changed when start tachyon because the start should stop all the previously running Tachyon services.
The `bin/tachyon-start.sh` should been updated to meet the logic changes of `bin/tachyon-stop.sh`
Also update the docs.
> [TACHYON-1531] update tachyon-start.sh to meet the tachyon-stop.sh changes

- servers/src/main/java/tachyon/master/journal/JournalWriter.java
This is needed because OSS like S3 doesn't support flush buffering. @calvinjia @luoli523
> [SMALLFIX] Sync with OSS when journal flushes to OSS as under FS

- common/src/main/java/tachyon/util/network/NetworkAddressUtils.java
https://tachyon.atlassian.net/browse/TACHYON-1355
The outer parens in NetworkAddressUtils.isValidAddress were unnecessary and have been removed
> [TACHYON-1355] Remove unnecessary parens in NetworkAddressUtils.isValidAddress

- integration-tests/src/test/java/tachyon/shell/TfsShellTest.java
regarding test case setIsPinnedTest, I found the file to be already pinned if it was created via TachyonFSTestUtils.createByteFile , but if the file was created via tfs command line it will not be already pinned. 
regarding use case setPinTest() . I assumed that the limit on the tachyon worker memory is 15MB. I am not sure if that is always the case!!!
> [TACHYON-1376] added two test cases for pin tfs command

- integration-tests/src/test/java/tachyon/shell/TfsShellTest.java
- shell/src/main/java/tachyon/shell/command/FileInfoCommand.java
Camel case the fileinfo shell command.We should use fileInfo to be consistent in file "shell\src\main\java\tachyon\shell\command\FileInfoCommand.java" and "integration-tests\src\test\java\tachyon\shell\TfsShellTest.java".
> [TACHYON-1398] Camel case the fileinfo shell command

- common/src/main/java/tachyon/Constants.java
- integration-tests/src/test/java/tachyon/shell/TfsShellTest.java
- integration-tests/src/test/java/tachyon/shell/command/CommandUtilsTest.java
- shell/src/main/java/tachyon/shell/command/AbstractLsCommand.java
- shell/src/main/java/tachyon/shell/command/CommandUtils.java
Display permission information for ls command
'd' represents it is a directory
d---------                    0.00B     01-07-2016 16:27:55:076                 /test/huge/tachyon-tiered-hdd-patched
d---------                    0.00B     01-07-2016 16:27:56:433                 /test/huge/tachyon-tiered-hdd-new
d---------                    0.00B     01-07-2016 16:27:57:929                 /test/huge/tachyon-tiered
d---------                    0.00B     01-07-2016 16:27:59:329                 /test/huge/mem-and-disk-ser
----------                     9.64MB    01-07-2016 16:28:01:113  In Memory      /test/huge/huge.tar.gz
> [TACHYON-1519] Display permission information for ls command

- common/src/main/java/tachyon/exception/PreconditionMessage.java
- integration-tests/src/test/java/tachyon/underfs/s3/S3UnderStorageCluster.java
This explains the problem instead of throwing NPE when the
user fails to set the s3Bucket but tries to test with s3.
> [SMALLFIX] Improve S3 test error message

- integration-tests/src/test/java/tachyon/shell/TfsShellTest.java
JIRA: https://tachyon.atlassian.net/browse/TACHYON-1534
Fix flaky tachyon.shell.TfsShellTest#lsTest. The clean and re-login is not a atomic operation, so that the re-login user sometimes is not expected. This patch put them into a synchronized block.
@apc999 , @sundapeng , would you like to take a look at this?
> [TACHYON-1534] Fix flaky tachyon.shell.TfsShellTest#lsTest

- shell/src/main/java/tachyon/shell/TfsShell.java
https://tachyon.atlassian.net/browse/TACHYON-1551
Change public method tachyon.shell.TfsShell#printUsage to private, since no other class is invoking this method.
> [TACHYON-1551]Change public method tachyon.shell.TfsShell#printUsage to private

- clients/unshaded/src/main/java/tachyon/client/ClientContext.java
Regular shutdown() just prevents more tasks from being started.
shutdownNow() is needed to interrupt existing tasks. If heartbeat
threads aren't interrupted, they will continue until the JVM stops.
> [SMALLFIX] Fix client heartbeat thread leak

- integration-tests/src/test/java/tachyon/LocalTachyonClusterResource.java
- integration-tests/src/test/java/tachyon/hadoop/contract/TachyonFSContract.java
- integration-tests/src/test/java/tachyon/hadoop/contract/TachyonFSContractCreateIntegrationTest.java
- integration-tests/src/test/java/tachyon/hadoop/contract/TachyonFSContractDeleteIntegrationTest.java
- integration-tests/src/test/java/tachyon/hadoop/contract/TachyonFSContractLoadedIntegrationTest.java
- integration-tests/src/test/java/tachyon/hadoop/contract/TachyonFSContractMkdirIntegrationTest.java
- integration-tests/src/test/java/tachyon/hadoop/contract/TachyonFSContractOpenIntegrationTest.java
- integration-tests/src/test/java/tachyon/hadoop/contract/TachyonFSContractRenameIntegrationTest.java
- integration-tests/src/test/java/tachyon/hadoop/contract/TachyonFSContractSeekIntegrationTest.java
https://tachyon.atlassian.net/browse/TACHYON-1572
Previously, `LocalTachyonCluster`s were created in `TachyonFSContract`, but there is no hook to clean up these clusters, so this PR moves ownership to the individual contract tests so that they can use `@Rule` to manage cluster creation and cleanup.
> [TACHYON-1572] Clean up contract test local clusters

- underfs/hdfs/src/main/java/tachyon/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/hdfs/src/test/java/tachyon/underfs/hdfs/HdfsUnderFileSystemTest.java
There are really not that much utility methods in HdfsUnderFileSystem good for unit test. The apis of FileSystem are better tested by integration tests.
I added a little tests to check some configuration.
> [TACHYON-1592] Add unit test coverage for HdfsUnderFileSystem

- clients/unshaded/src/main/java/tachyon/client/ClientContext.java
- clients/unshaded/src/main/java/tachyon/client/lineage/LineageContext.java
- integration-tests/src/test/java/tachyon/master/lineage/LineageMasterIntegrationTest.java
Lineage context needs to be reset whenever client context is reset because lineage context depends on the value of `ClientContext.getMasterAddress()`. Without this change, all tests use the cluster created for the first lineage test.
> [SMALLFIX] Add lineage integration test

- clients/unshaded/src/main/java/tachyon/client/lineage/LineageMasterClient.java
- common/src/main/java/tachyon/exception/ExceptionMessage.java
- docs/Lineage-API.md
- integration-tests/src/test/java/tachyon/master/lineage/LineageMasterIntegrationTest.java
- servers/src/main/java/tachyon/master/lineage/LineageMaster.java
This also fixes an issue where creating a file through the lineage file system would throw an exception if the file wasn't already an output file of a lineage.
> [SMALLFIX] Test documented lineage code

- keyvalue/clients/src/main/java/tachyon/client/keyvalue/hadoop/KeyValueOutputCommitter.java
- keyvalue/clients/src/main/java/tachyon/client/keyvalue/hadoop/KeyValueOutputFormat.java
This is needed to fix the hdfs1 build
> [SMALLFIX] Use hdfs1 API in KeyValueOutputCommitter

- deploy/vagrant/Vagrantfile
- deploy/vagrant/conf/ufs.yml
- deploy/vagrant/core/EnvSetup.rb
But the S3 bucket still needs to be specified since we could not specify a default bucket name.
> [SMALLFIX] Use S3 as default ufs when provider is ec2 in vagrant module

- common/src/main/java/tachyon/security/authorization/PermissionStatus.java
In tachyon.security.authorization.PermissionStatus, three private members mUserName, mGroupName and mPermission should be marked as final.
https://tachyon.atlassian.net/browse/TACHYON-1618
> [TACHYON-1618] Mark members final in tachyon.security.authorization.PermissionStatus

- deploy/vagrant/conf/ec2.yml.template
us-east-1a has never worked for me. Running the aws CLI I get
```
➜  vagrant git:(e05a323) ✗ aws ec2 describe-availability-zones --zone-names
{
"AvailabilityZones": [
{
"State": "available",
"RegionName": "us-east-1",
"Messages": [],
"ZoneName": "us-east-1b"
},
{
"State": "available",
"RegionName": "us-east-1",
"Messages": [],
"ZoneName": "us-east-1c"
},
{
"State": "available",
"RegionName": "us-east-1",
"Messages": [],
"ZoneName": "us-east-1d"
},
{
"State": "available",
"RegionName": "us-east-1",
"Messages": [],
"ZoneName": "us-east-1e"
}
]
}
```
> [SMALLFIX] Fix default ec2 deploy availability zone

- deploy/vagrant/ansible.cfg
https://tachyon.atlassian.net/browse/TACHYON-1675
EC2 instance DNS name length can exceed Unix socket size limit, causing ssh error.
http://docs.ansible.com/ansible/intro_configuration.html#control-path
> [TACHYON-1675] Fix a ssh problem when deploying EC2 with Vagrant.

- clients/unshaded/src/main/java/tachyon/client/TachyonFS.java
- clients/unshaded/src/main/java/tachyon/client/TachyonFile.java
Supports APIs Spark uses in its native integration with Tachyon in Spark 1.6 or lower versions.
> [FIX] Spark Compatibility

- docs/_includes/Unified-and-Transparent-Namespace/create-file.md
- docs/_includes/Unified-and-Transparent-Namespace/delete.md
- docs/_includes/Unified-and-Transparent-Namespace/ls-demo-hello.md
- docs/_includes/Unified-and-Transparent-Namespace/mkdir.md
- docs/_includes/Unified-and-Transparent-Namespace/mount-demo.md
- docs/_includes/Unified-and-Transparent-Namespace/mounting-API.md
- docs/_includes/Unified-and-Transparent-Namespace/rename.md
- docs/_includes/Unified-and-Transparent-Namespace/unmount.md
- docs/cn/Unified-and-Transparent-Namespace.md
- docs/en/Unified-and-Transparent-Namespace.md
https://tachyon.atlassian.net/browse/TACHYON-1660
Add the Chinese version of documentation page 'Unified-and-Transparent-Namespace'
> [TACHYON-1660] Add the Chinese version of documentation page 'Unified-and-Transparent-Namespace'

- docs/_data/table/README.md
- docs/_includes/README.md
- docs/_includes/Running-Tachyon-on-Virtual-Box/destroy.md
- docs/_includes/Running-Tachyon-on-Virtual-Box/download-tachyon.md
- docs/_includes/Running-Tachyon-on-Virtual-Box/install-pip.md
- docs/_includes/Running-Tachyon-on-Virtual-Box/install-vagrant.md
- docs/_includes/Running-Tachyon-on-Virtual-Box/launch-cluster.md
- docs/_includes/Running-Tachyon-on-Virtual-Box/runTests.md
- docs/_includes/Running-Tachyon-on-Virtual-Box/shell-output.md
- docs/_includes/Running-Tachyon-on-Virtual-Box/ssh-TachyonMaster.md
- docs/_includes/Running-Tachyon-on-Virtual-Box/ssh-other-node.md
- docs/_includes/Running-Tachyon-on-Virtual-Box/ssh.md
- docs/cn/README.md
- docs/cn/Running-Tachyon-on-Virtual-Box.md
- docs/en/Running-Tachyon-on-Virtual-Box.md
https://tachyon.atlassian.net/browse/TACHYON-1656
Add the Chinese version of documentation page 'Running-Tachyon-on-Virtual-Box'.
And the code fragments in this page have been extracted into `_includes/Running-Tachyon-on-Virtual-Box/` folder.
A new Running-Tachyon-on-Virtual-Box.md page file of Chinese version has been created in `cn/` folder.
> [TACHYON-1656] Add the Chinese version of documentation page 'Running-Tachyon-on-Virtual-Box'

- conf/tachyon-env.sh.swift
- conf/tachyon-env.sh.template
- deploy/vagrant/provision/roles/lib/files/tachyon_tiered.sh
- docs/en/Tiered-Storage-on-Tachyon.md
- integration/bin/tachyon-worker-mesos.sh
The configuration constant defined in `Constants` is `tachyon.worker.tieredstore.levels`. After this change `tachyon.worker.tieredstore.level.max` will no longer appear in our codebase.
> [SMALLFIX] Fix references to tier count configuration

- docs/_data/table/Tachyon-FUSE-parameter.csv
- docs/_data/table/cn/README.md
- docs/_data/table/cn/Tachyon-FUSE-parameter.yml
- docs/_data/table/en/README.md
- docs/_data/table/en/Tachyon-FUSE-parameter.yml
- docs/_includes/Mounting-Tachyon-FS-with-FUSE/tachyon-fuse-mount.md
- docs/_includes/Mounting-Tachyon-FS-with-FUSE/tachyon-fuse-stat.md
- docs/_includes/Mounting-Tachyon-FS-with-FUSE/tachyon-fuse-umount.md
- docs/cn/Mounting-Tachyon-FS-with-FUSE.md
- docs/en/Mounting-Tachyon-FS-with-FUSE.md
https://tachyon.atlassian.net/browse/TACHYON-1646
Add the Chinese version of documentation page 'Mounting-Tachyon-FS-with-FUSE'
Also correct some md grammar mistakes in `Mounting-Tachyon-FS-with-FUSE.md` in `en/`
Most tables in the site have three columns, with first two (i.e. property name and default value) being language-independent and last one (description) being language-specific. I extract the language-independent parts into a `.csv` file and write the language-specific parts in a `.yml` file.
> [Tachyon 1646] Add the Chinese version of documentation page 'Mounting-Tachyon-FS-with-FUSE'

- docs/en/Java-Setup.md
"A Finder window appears containing an icon of an open box and the name of the .pkg file Double click the package icon to launch the **Install** app." in Java-Setup.md lose a period between "file" and "Double".
> [SMALLFIX-DOC-INSTALLJAVA]Add a period between 'file' and 'Double' in Java-Setup.md

- core/client-internal/pom.xml
- core/client-internal/src/main/java/tachyon/client/ClientContext.java
- core/client-internal/src/main/java/tachyon/hadoop/AbstractTFS.java
- core/client-internal/src/test/java/tachyon/client/block/BlockMasterClientTest.java
- core/client-internal/src/test/java/tachyon/client/block/TachyonBlockStoreTest.java
- core/client-internal/src/test/java/tachyon/client/file/BaseFileSystemTest.java
- core/client-internal/src/test/java/tachyon/client/file/FileInStreamTest.java
- core/client-internal/src/test/java/tachyon/client/file/FileOutStreamTest.java
- core/client-internal/src/test/java/tachyon/client/file/FileSystemMasterClientTest.java
- core/client-internal/src/test/java/tachyon/client/file/options/InStreamOptionsTest.java
- core/client-internal/src/test/java/tachyon/client/file/options/OutStreamOptionsTest.java
- core/client-internal/src/test/java/tachyon/client/lineage/LineageMasterClientTest.java
- core/client-internal/src/test/java/tachyon/client/lineage/TachyonLineageTest.java
- core/client-internal/src/test/java/tachyon/client/util/ClientTestUtils.java
- core/client-internal/src/test/java/tachyon/hadoop/TFSTest.java
- core/server/pom.xml
- core/server/src/test/java/tachyon/worker/block/SpaceReserverTest.java
- examples/src/main/java/tachyon/examples/BasicNonByteBufferOperations.java
- examples/src/main/java/tachyon/examples/BasicOperations.java
- examples/src/main/java/tachyon/examples/Performance.java
- examples/src/main/java/tachyon/examples/keyvalue/KeyValueStoreOperations.java
- keyvalue/client-internal/pom.xml
- keyvalue/client-internal/src/test/java/tachyon/client/keyvalue/BaseKeyValuePartitionWriterTest.java
- keyvalue/server/pom.xml
- minicluster/pom.xml
- minicluster/src/main/java/tachyon/master/LocalTachyonCluster.java
- minicluster/src/main/java/tachyon/master/LocalTachyonClusterMultiMaster.java
- tests/src/test/java/tachyon/client/FileSystemUtilsIntegrationTest.java
- tests/src/test/java/tachyon/security/BlockWorkerClientAuthenticationIntegrationTest.java
https://tachyon.atlassian.net/browse/TACHYON-1623
Instead of resetting the client context to cause `TachyonConf` changes, it is enough to directly modify the current `TachyonConf`. This can be done by acting directly on `ClientContext.getConf()`.
In tests, it is often useful to reset the context so that changes to `TachyonConf` don't trample on other tests. The new `ClientTestUtils.resetClientContext` method fulfills this need, and is only available on the `src/test` side. Occasionally we want to modify configuration and then re-initialize contexts so that they pick up the conf change. `ClientTestUtils.reinitializeClientContext()` covers this use case, and re-initializes contexts without resetting the configuration.
This PR is the first of a few PRs which will remove public reset methods …
> [TACHYON-1623] Remove ClientContext.reset

- minicluster/src/main/java/tachyon/master/AbstractLocalTachyonCluster.java
Reverts amplab/tachyon#2617
This commit seems to have broken the hdfs builds, e.g. https://amplab.cs.berkeley.edu/jenkins/view/Tachyon/job/Tachyon-Master/1892/PROFILE=hdfs1Test,label=centos/console
> Revert "[TACHYON-1685] Delete temporary directories created in integration tests"

- docs/en/Running-Hadoop-MapReduce-on-Tachyon.md
http://www.tachyon-project.org/documentation/master/en/Running-Hadoop-MapReduce-on-Tachyon.html
There are 2 main alternatives for distributing the Tachyon client jar. However, The 2nd approach has same number as the 1st. So I think the number of "Distributing the jars to all nodes manually" should be 2.
> [SMALLFIX-DOC-MAPREDUCE-CHANGENUMBER]number 2 main alternatives in sequence

- core/server/src/test/java/tachyon/master/lineage/recompute/TestRecomputeExecutor.java
This build has failed a few times with timeouts in this test. I took a look and couldn't find any particular race conditions (or get it to fail), but waiting only 1 second seems a little on the short side. Lets wait a bit longer and see if it's just slow or actually failing.
Example failure: https://amplab.cs.berkeley.edu/jenkins/view/Tachyon/job/Tachyon-Master/1900/PROFILE=developer,label=centos/console
> [SMALLFIX] Increase flaky test timeout

- pom.xml
Auto-generated codes are using Thrift compiler 0.9.3. We may apply the same version to libthrift.
> Update libthrift to 0.9.3

- core/server/src/main/java/tachyon/master/block/BlockMasterClientServiceHandler.java
- examples/src/main/java/tachyon/examples/Utils.java
- javadoc can't link to primitives
> [SMALLFIX] Javadoc fixes

- docs/_includes/Configuring-Tachyon-with-Swift/copy-tachyon-env.md
- docs/_includes/Configuring-Tachyon-with-Swift/functional-tests.md
- docs/_includes/Configuring-Tachyon-with-Swift/heap-dump.md
- docs/_includes/Configuring-Tachyon-with-Swift/runTests.md
- docs/_includes/Configuring-Tachyon-with-Swift/several-configurations.md
- docs/_includes/Configuring-Tachyon-with-Swift/start-tachyon.md
- docs/_includes/Configuring-Tachyon-with-Swift/stop-tachyon.md
- docs/_includes/Configuring-Tachyon-with-Swift/swift-files.md
- docs/_includes/Configuring-Tachyon-with-Swift/underfs-address.md
- docs/cn/Configuring-Tachyon-with-Swift.md
- docs/en/Configuring-Tachyon-with-Swift.md
https://tachyon.atlassian.net/browse/TACHYON-1636
In `Configuring-Tachyon-with-Swift.md`, it writes "it is adviced to set value of `<swift-auth-model>`  to `false`". However, possible values of `<swift-auth-model>` are `keystone`, `tempauth`, `swiftauth`. Is this a typo and what it wants to say is setting value of `<swift-use-public>` to `false`?
> [TACHYON-1636] Add the Chinese version of documentation page 'Configuring-Tachyon-with-Swift'

- docs/cn/Running-Tachyon-Locally.md
- docs/cn/index.md
A special invisible character was inserted in the two `md` page files, maybe due to the editor. Thus the `Overview` and `User Guide/Tachyon on local machine` pages don't have Chinese version in the language selector in http://tachyon-project.org/documentation/master/en/ because the two md files cannot be transferred to html files.
This special invisible character has been removed and can be seen by `git diff` command.
> [DOCFIX] Remove a special invisible character in two md page files of Chinese version

- docs/cn/Running-Alluxio-Fault-Tolerant-on-EC2.md
- docs/cn/Running-Alluxio-on-EC2-Mesos.md
- docs/cn/Running-Alluxio-on-EC2-Yarn.md
- docs/cn/Running-Alluxio-on-EC2.md
- docs/cn/Running-Alluxio-on-Virtual-Box.md
- docs/cn/Running-Flink-on-Alluxio.md
- docs/cn/Running-Spark-on-Alluxio.md
Running-Alluxio-Fault-Tolerant
Running-Alluxio-Fault-Tolerant-on-EC2
Running-Alluxio-Locally
Running-Alluxio-on-a-Cluster
Running-Alluxio-on-EC2
Running-Alluxio-on-EC2-Mesos
Running-Alluxio-on-EC2-Yarn
Running-Alluxio-on-Virtual-Box
Running-Flink-on-Alluxio
Running-Hadoop-MapReduce-on-Alluxio
Running-Spark-on-Alluxio
> [DOCFIX] Improve Chinese documentation of Running-Alluxio pages

- docs/cn/Powered-By-Alluxio.md
The group of current Chinese Powered-by page should be 'Resources' but not 'Dev Resources'. Otherwise, the page would be missing when generating the webpage.
> [DOCFIX] Correct the group of Powered-by Chinese page

- docs/cn/Running-Spark-on-Alluxio.md
I  think these contents in en/Running-Spark-on-Alluxio needs to be translated:
I add the translation in cn/Running-Spark-on-Alluxio:
> [DOCFIX]add some translation for docs/cn/Running-Spark-on-Alluxio

- core/server/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/test/java/alluxio/master/block/BlockMasterTest.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
https://tachyon.atlassian.net/browse/ALLUXIO-1718
Currently the block metadata is not deleted when a file is deleted, and therefore block master regards the blocks as lost. This handling slows the system down, because the lost block will trigger lost file detection, which will in turn lead to a FileNotFound exception in inodetree look up.
Therefore, we should distinguish between freeing and deleting files in Alluxio.
> [ALLUXIO-1718] Delete block metadata when a file is deleted.

- docs/css/main.css
The Portuguese-translated categories are a bit longer than the
English versions, so they will wrap to the next line if we don't
give them 5 extra pixels in the nav bar.
Before:
After:
> [DOCFIX] Fix Portuguese docs navbar

- core/client-internal/src/main/java/alluxio/client/block/BlockWorkerClient.java
- core/client-internal/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/common/src/main/java/alluxio/Configuration.java
- core/common/src/main/java/alluxio/network/protocol/RPCResponse.java
- core/common/src/main/java/alluxio/wire/BlockLocation.java
- core/common/src/main/java/alluxio/wire/WorkerNetAddress.java
- core/server/src/main/java/alluxio/web/UIFileInfo.java
- keyvalue/client-internal/src/main/java/alluxio/client/keyvalue/KeyValueWorkerClient.java
- keyvalue/client-internal/src/main/java/alluxio/hadoop/mapreduce/KeyValueInputFormat.java
This PR contains minor Javadoc clean up. In particular, fixing warnings produced by `mvn javadoc:aggregate`.
> [SMALLFIX] fixing Javadoc warnings

- core/server/pom.xml
- core/server/src/main/java/alluxio/master/block/BlockMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/master/file/FileSystemMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/master/lineage/LineageMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/worker/block/BlockWorkerClientRestServiceHandler.java
- pom.xml
Addresses: https://tachyon.atlassian.net/browse/ALLUXIO-1735
After `mvn test`, the `$ALLUXIO_HOME/core/server/target/miredot` will contain autogenerated HTML documenting the REST API. See the attached screenshots for a couple of examples.
@aaudiber
> [ALLUXIO-1735] Using MireDot for REST API documentation

- docs/en/Key-Value-System-API.md
the page "Key-Value-System-API" cannot display correctly because of the extra space:
After remove the extra space:
> [DOCFIX]Remove an extra space for docs/en/Key-Value-System-API

- core/client-internal/src/main/java/alluxio/client/file/BaseFileSystem.java
- logs/README.md
- shell/src/main/java/alluxio/shell/AlluxioShell.java
Because Alluxio is a filesystem, so logging which file or directory has created is useful to top applications.
Now the log records is more unreadable. So I add logging in BaseFilySystem.
> [ALLUXIO-1736] Add logging in BaseFileSystem.

- deploy/vagrant/provision/roles/alluxio/files/alluxio_jar.sh
In recent updates, the line "The Alluxio Open Foundation licenses this work under the Apache License, version 2.0" was added to the top of pom.xml.
This caused an issue when deploy/vagrant/provision/roles/alluxio/files/alluxio_jar.sh replaced ${VERSION} of /libexec/alluxio-config.sh with the Alluxio version found in pom.xml, because the script originally grep'd for the first instance of the word "version". Since "version" appears in this new line added to the top of pom.xml, alluxio_jar.sh would now replace ${VERSION} with an incorrect parameter.
I implemented a quick fix which grabs the second instance of the word "version", which grabs the correct xml element. This should probably be revisited at some point for a more portable fix.
Addresses: …
> [ALLUXIO-1752] Issue when using deploy module with EC

- conf/log4j.properties
The current default creates permissions issues writing to logs for client
operations with multiple users using the same cluster.
This will create a separate user_<login>.log file for all the client logging.
> [SMALLFIX] Use separate user log files

- docs/cn/Architecture.md
- docs/en/Architecture.md
The link referred to Alluxio Faut Tolerant Mode on EC2 machines, so we fixed the link to Alluxio Fault Tolerant Mode site.
> [DOCFIX] Corrected link from Architecture.md doc on both languages

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/test/java/alluxio/master/file/PermissionCheckTest.java
This PR makes sure that we load metadata from UFS for getStatus(path) arguments.
> [SMALLFIX] loading metadata for getFileInfo

- deploy/vagrant/ansible.cfg
https://alluxio.atlassian.net/browse/ALLUXIO-1761
The problem is that on the same host machine, all virtual machines' hosts are all 127.0.0.1, the host corresponds to the `%%h` in control path configuration, `%%r` is the remote login user name which is `vagrant`, so the control path is the same for all virtual machines, that means all machines share the same connection, which is incorrect, each machine should have a distinct connection. 
The solution is to add port `%%p` which is unique for different virtualbox machines.
> [ALLUXIO-1761] Fix the problem where ansible hangs for all script modules

- examples/src/main/java/alluxio/examples/BasicNonByteBufferOperations.java
- examples/src/main/java/alluxio/examples/BasicOperations.java
Otherwise client will use localhost as master address if it's failed to navigate system and configuration properties.
> [SMALLFIX] Initialize ClientContext on two basic operations examples

- docs/en/Accessing-Alluxio-from-Zeppelin.md
This PR fixes links that broke after Tachyon integration with Zeppelin was updated to Alluxio and Zeppelin main website has moved.
> [SMALLFIX] Updating Zeppeling documentation.

- core/server/src/main/java/alluxio/web/WebInterfaceMemoryServlet.java
- core/server/src/main/webapp/memory.jsp
https://alluxio.atlassian.net/browse/ALLUXIO-1829
Screenshot for when authorization is disabled (looks the same as current if enabled):
> [ALLUXIO-1829] Add permissions flag for in-memory files page.

- core/server/src/test/java/alluxio/worker/block/BlockWorkerTest.java
This prevents conflicts with an already running Alluxio server.
> [SMALLFIX] Select free dataserver port in tests

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/file/meta/MountTable.java
Unmounts mount points instead of directly deleting them. This operation is not journaled and is a side effect of the delete operation which will be journaled.
> [SMALLFIX] Unmount on delete

- core/server/src/main/java/alluxio/master/file/FileSystemMasterClientRestServiceHandler.java
Otherwise, when 
`curl -X POST "http://node1:19999/v1/api/master/file/mount?path=/sdfdsf&ufsPath=s3://dskfj"` or 
`curl -X POST "http://node1:19999/v1/api/master/file/mount?path=/sdfdsf&ufsPath=~/dskfj"`,
the response is a html like
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 Request failed.</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /v1/api/master/file/mount. Reason:
<pre>    Request failed.</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>
<br/>
</body>
</html>
```
After this PR, the result is like
```
No Under File System Factory found for: ~dksjf
```
> [SMALLFIX] Catch the exception thrown when there is no ufs for the ufsPath

- core/server/src/main/java/alluxio/master/journal/JournalProtoUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-1827
KeyValueMaster#ProcessJournalEntry call JournalProtoUtils#unwrap to return the message type of Key-Value,but there are none of these types, so I add them and fix the bug described in ALLUXIO-1827
> [ALLUXIO-1827] Fix Key-Value-journal bug

- core/server/src/main/java/alluxio/master/file/meta/InodeDirectory.java
This enables the shell or the UI to show number of objects in a directory without calling the client again to get the file infos under the directory after getting info of the directory.
> [SMALLFIX] Set length of a directory to the number of objects it contains

- examples/src/main/java/alluxio/examples/Performance.java
Performance.java should not be using URI to represent the master address `<host>:<port>`. This PR fixes that.
> [SMALLFIX] fixing address parsing in Performance.java

- core/server/src/test/java/alluxio/master/file/options/SetAttributeOptionsTest.java
The javadoc for defaultsTest() should refer to SetAttributeOptions.
> [ALLUXIO-1783] Fix Javadoc in SetAttributeOptionsTest.defaultsTest()

- core/common/src/main/java/alluxio/exception/ExceptionMessage.java
- core/common/src/main/java/alluxio/exception/InvalidPathException.java
- core/common/src/main/java/alluxio/util/io/PathUtils.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- Rename FILE_MUST_HAVE_VALID_PARENT to PATH_MUST_HAVE_VALID_PARENT since it's used for both files and directories.
- Add some javadoc
- Remove some unnecessary code
> [SMALLFIX] InvalidPathException cleanups

- deploy/vagrant/provision/roles/lib/files/maven.sh
An alternative approach is to add maven repo and `yum install` maven, so that we don't need to maintain this hard-coded link.
> [SMALLFIX] Fix a outdated maven link in deploy module

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/file/meta/Inode.java
- core/server/src/main/java/alluxio/master/file/meta/InodeDirectory.java
- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/src/test/java/alluxio/master/file/PermissionCheckerTest.java
- core/server/src/test/java/alluxio/master/file/meta/InodeDirectoryTest.java
- core/server/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
Followup to https://github.com/Alluxio/alluxio/pull/2771 - if we aren't hiding extendible-fluent-builder generics inside an `Inode.Builder` class, `Inode` needs to be referred to by `Inode<?>` to avoid raw type warnings.
> [SMALLFIX] Add generics to raw usages of Inode

- underfs/s3/pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-1824
Updates jets3t to latest stable version: http://www.jets3t.org/downloads.html
Because:
- Hadoop has upgraded its jets3t dependency to 0.9
- This also paves the road for adding GCS integration.
> [ALLUXIO-1824] Update jets3t to latest stable version.

- docs/_data/table/cn/master-configuration.yml
- docs/_data/table/en/master-configuration.yml
- docs/_data/table/master-configuration.csv
`alluxio.master.ttlchecker.interval.ms` has been renamed to `alluxio.master.ttl.checker.interval.ms`, but documentation is not updated.
> [SMALLFIX] Fix outdated configuration parameter in doc

- core/server/src/main/java/alluxio/master/block/BlockMaster.java
- core/server/src/test/java/alluxio/master/MasterSourceTest.java
- core/server/src/test/java/alluxio/master/block/BlockMasterTest.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- tests/src/test/java/alluxio/client/FreeAndDeleteIntegrationTest.java
- tests/src/test/java/alluxio/shell/command/FreeCommandTest.java
In current `remove` I/O flow, the Block Master doesn't update the removed blocks received from worker' heartbeat when their metadata removed. This makes all works repeat sending update information after a file is deleted. Eventually, RPC communication to master server gets blocked, and client throws SocketTimeoutException: read timed out.
> [ALLUXIO-1804] Block Master shouldn't send free commands on those removed blocks.

- core/common/src/main/java/alluxio/exception/FileDoesNotExistException.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/src/main/java/alluxio/master/lineage/LineageMaster.java
- core/server/src/test/java/alluxio/master/MasterSourceTest.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- core/server/src/test/java/alluxio/master/file/PermissionCheckTest.java
- core/server/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
- core/server/src/test/java/alluxio/master/lineage/LineageMasterTest.java
- keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMaster.java
There were many places where we would throw InvalidPathException due to a file not existing. This PR throws FileDoesNotExistException in those places instead.
As a next step, I would like to rename FileDoesNotExistException to PathDoesNotExistException since that is already what it represents.
> [SMALLFIX] Improve handling of FileDoesNotExistException

- core/server/src/main/java/alluxio/worker/block/BlockMasterSync.java
`IOException` can have many causes, not necessarily just concurrent reads.
> [SMALLFIX] Remove misleading part of error message

- core/common/src/main/java/alluxio/util/io/FileUtils.java
- core/common/src/test/java/alluxio/util/io/FileUtilsTest.java
- core/server/src/main/java/alluxio/worker/block/TieredBlockStore.java
One particular advantage of doing this is that we will now get more descriptive delete error messages instead of just "Failed to delete blah".
> [SMALLFIX] Use Files.delete instead of writing our own util method

- core/common/src/main/java/alluxio/exception/AlluxioException.java
- core/common/src/main/java/alluxio/exception/UnexpectedAlluxioException.java
- core/server/src/main/java/alluxio/RpcUtils.java
- core/server/src/main/java/alluxio/master/block/BlockMasterClientServiceHandler.java
- core/server/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
- core/server/src/main/java/alluxio/master/lineage/LineageMasterClientServiceHandler.java
- core/server/src/main/java/alluxio/worker/block/BlockWorkerClientServiceHandler.java
- keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMasterClientServiceHandler.java
- keyvalue/server/src/main/java/alluxio/worker/keyvalue/KeyValueWorkerClientServiceHandler.java
https://alluxio.atlassian.net/browse/ALLUXIO-1855
With server-side exceptions centralized, this PR also changes the handling so that runtime exceptions are converted to AlluxioExceptions. This is necessary because allowing these exceptions to propagate will cause the client to receive a Thrift exception and retry.
> [ALLUXIO-1855] Add central handling for server-side exceptions

- core/common/src/main/java/alluxio/util/CommonUtils.java
- core/common/src/main/java/alluxio/util/FormatUtils.java
- core/server/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
- core/server/src/main/java/alluxio/master/block/BlockMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/master/file/FileSystemMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/master/lineage/LineageMasterClientRestServiceHandler.java
- core/server/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
- core/server/src/main/java/alluxio/worker/block/BlockWorkerClientRestServiceHandler.java
- pom.xml
- tests/src/test/java/alluxio/master/file/FileSystemMasterClientRestApiTest.java
- tests/src/test/java/alluxio/master/lineage/LineageMasterClientRestApiTest.java
- tests/src/test/java/alluxio/rest/TestCase.java
- tests/src/test/java/alluxio/rest/TestCaseFactory.java
- tests/src/test/java/alluxio/worker/block/BlockWorkerClientRestApiTest.java
This PR works around a limitation in the Jackson framework, which fails to properly encode String return values as JSON.
> [SMALLFIX] fixing encoding of strings in REST API endpoints

- docs/pt/Running-Spark-on-Alluxio.md
The resource file names were recently updated from the branch-1.0 merge. Updates the names in the PT docs so we can still build the documentation.
> [DOCFIX] Pt docs use new file resource names.

- bin/alluxio-mount.sh
- bin/alluxio-start.sh
- conf/alluxio-env.sh.template
https://alluxio.atlassian.net/browse/ALLUXIO-1871
Right now sudo access is required to start Alluxio because of ramfs. This issue is to track tasks to make it easier to start alluxio for people without sudo access.
Summary:
1.  Use tmmFS (pre-mounted on /dev/shm) in linux machines. 
2. Mac OS-X is not supported.
How to use: (Linux only)
./bin/alluxio-start.sh local NoMount
> [ALLUXIO-1871] Improve Alluxio scripts for non-sudo deployment

- docs/cn/Running-Alluxio-on-a-Cluster.md
`to sync files and folders to all hosts specified in the alluxio/conf/workers file` should be translated as `同步所有文件和文件夹到alluxio/conf/workers 文件中指定的主机里`.
> [DOCFIX] Fix the translation errors in Running-Alluxio-on-a-Cluster.md

- keyvalue/client/src/main/java/alluxio/client/keyvalue/KeyValuePartitionWriter.java
https://alluxio.atlassian.net/browse/ALLUXIO-1850
> [ALLUXIO-1850] Set the max size of a block in CreateFileOptions when creating a partition file in key-value store

- tests/src/test/java/alluxio/client/AbstractFileOutStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/BufferedBlockInStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/FileInStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/FileSystemIntegrationTest.java
- tests/src/test/java/alluxio/client/FileSystemUtilsIntegrationTest.java
- tests/src/test/java/alluxio/client/FreeAndDeleteIntegrationTest.java
- tests/src/test/java/alluxio/client/IsolatedFileSystemIntegrationTest.java
- tests/src/test/java/alluxio/client/LocalBlockInStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/ReadOnlyMountIntegrationTest.java
- tests/src/test/java/alluxio/client/RemoteBlockInStreamIntegrationTest.java
- tests/src/test/java/alluxio/client/StreamOptionUtils.java
- tests/src/test/java/alluxio/client/concurrent/FileInStreamConcurrencyIntegrationTest.java
The methods in StreamOptionUtils took a config but didn't use it. This PR removes the parameter and cleans up call sites.
> [SMALLFIX] Remove unused configuration

- shell/src/main/java/alluxio/shell/command/CopyToLocalCommand.java
https://alluxio.atlassian.net/browse/ALLUXIO-1876
Simply copyToLocal from a 1GB remote file comparison:
With TempFile:
```
[ec2-user@AlluxioWorker1 alluxio]$ time ./bin/alluxio fs copyToLocal /file.txt file.txt
AlluxioShell milliseconds: 452
Copied /file.txt to file.txt
copyFileToLocal milliseconds: 16974
shell.run milliseconds: 16981
shell.close() milliseconds: 0
It takes 18 seconds to complete the shell...
real	0m17.780s
user	0m6.576s
sys	0m2.320s
```
Without tempFile:
```
[ec2-user@AlluxioWorker1 alluxio]$ time ./bin/alluxio fs copyToLocal /file.txt file.txt
AlluxioShell milliseconds: 446
Copied /file.txt to file.txt
copyFileToLocal milliseconds: 8887
shell.run milliseconds: 8893
shell.close() milliseconds: 0
It takes 9 seconds to complete the shell...
real	0m9.663s
user	0m6.524s
sys …
```
> [ALLUXIO-1876] Improve copyToLocal shell efficiency by getting rid of tempFile

- docs/en/Running-Hadoop-MapReduce-on-Alluxio.md
We fixed this issue at https://github.com/Alluxio/alluxio/pull/2718. It looks like [Back port branch-1.0 to master](https://github.com/Alluxio/alluxio/pull/2975) reintroduced it back to master branch.
> [DOCFIX] Remove the redundant configuration on Hadoop 1.x and 2.x.

- bin/alluxio-start.sh
Small style fix in alluxio-start.sh
> [ALLUXIO-1871 ] Load env variables again after overriding ALLUXIO_RAM_FOLDER

- core/common/src/main/java/alluxio/resource/ResourcePool.java
- core/server/src/main/java/alluxio/worker/block/BlockLockManager.java
- core/server/src/main/java/alluxio/worker/block/ClientRWLock.java
- core/server/src/test/java/alluxio/worker/block/BlockLockManagerTest.java
- core/server/src/test/java/alluxio/worker/block/ClientRWLockTest.java
This commit also fixes an issue which could occur when the lock pool is empty. If two threads tried to  acquire the last lock in the rwlock pool for the same block id, the second acquire would hang until a rwlock was returned to the pool. It should instead share the block lock acquired by the first thread. As a result, you could have n blocks and n locks, but not be able to lock all the blocks at once.
> [SMALLFIX] Add block lock manager test

- core/server/src/test/java/alluxio/worker/block/BlockLockManagerTest.java
We are occasionally failing this test due to timeout on the hdfs profile. The point is correctness, not performance, so I've lowered the stress level.
> [SMALLFIX] Ease up on block lock manager stress test perf requirement

- core/server/src/main/java/alluxio/worker/block/BlockStoreMeta.java
> [SMALLFIX] Fix a typo in the blockstoremeta javadoc.

- core/common/src/main/java/alluxio/network/protocol/RPCBlockReadRequest.java
- core/common/src/main/java/alluxio/network/protocol/RPCBlockWriteRequest.java
> [SMALLFIX] Fix typos in rpc messages.

- core/server/src/main/java/alluxio/worker/AlluxioWorker.java
- core/server/src/main/java/alluxio/worker/DataServer.java
- core/server/src/main/java/alluxio/worker/netty/DataServerHandler.java
- core/server/src/main/java/alluxio/worker/netty/NettyDataServer.java
- core/server/src/test/java/alluxio/worker/block/SpaceReserverTest.java
Since we've moved the dataserver to be at the Alluxio Worker level, we should pass the Alluxio worker instead of the block worker.
> [ALLUXIO-1739] Use Alluxio Worker for DataServerHandler

- core/common/src/main/java/alluxio/AbstractMasterClient.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
- core/server/src/main/java/alluxio/web/WebInterfaceHeaderServlet.java
In master fault tolerance mode, the link of " return to master " in work web UI is borken.
Because we should get the master address from zookeeper, rather than from the configuration.
Suggestions and reviews are welcomed~
> [SMALLFIX] Fix the broken master link in worker web UI for master fault tolerance mode

- core/client/src/main/java/alluxio/client/block/RemoteBlockInStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-1898
> [ALLUXIO-1898] Check LockBlockResult to be not null in RemoteBlockInStream#constructor

- core/server/pom.xml
Dear maintainers of Alluxio,
We noticed you were using a free Miredot license for Alluxio. We thought we'd help you out and upgrade that license to an open-source license.
With this license you get access to all the paying features, free of charge. 
I tried building the project myself in order to fully test the license, but was not able to do that on my windows machine. It should be fine though. If you have any questions, problems or feedback, please let us know!
Kind Regards,
Ewout & The Miredot team.
P.S.: It will expire on 28/04/2018, we will send you another pull request with a license update before that happens.
Edit: added what I think was the original JIRA ticket for adding rest docs. 
Link: https://alluxio.atlassian.net/browse/ALLUXIO-1735
> [ALLUXIO-1735] Upgrades free Miredot license to open-source license.

- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1914
The TTL needs to be 0 to guarantee that the file will be expired at the time of the TTL check.
> [ALLUXIO-1914] Fix flaky test

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
Those are critical issues for Spark-Alluxio-Swift
1. When objectname/_SUCCESS is created, there is need to create also 0 byte size objectname. Otherwise it's not possible to read data back from Swift ( directly with Spark)
2. Fixing bug in copy
3. Swift driver doesn't create _temporary directory, however exists method for _temporary should return true. This is important for Spark
> [ALLUXIO-1852] Fixing Swift underfs issues when working with Spark

- core/server/src/main/java/alluxio/master/lineage/LineageMaster.java
- keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMaster.java
We should use FileDoesNotExistException when a file doesn't exist, and InvalidPathException for other path-related errors.
> [SMALLFIX] Improve missing file exception handling

- tests/src/test/java/alluxio/worker/DataServerIntegrationTest.java
Removed an unneeded explicit type argument in ```DataServerIntegrationTest```.
> [SMALLFIX] Removed explicit type argument in DataServerIntegrationTest

- tests/src/test/java/alluxio/worker/block/meta/TieredStoreIntegrationTest.java
Removed two redundant initializers in ```TieredStoreIntegrationTest```.
> [SMALLFIX] Removed redundant intializer in TieredStoreIntegrationTest

- integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
Removed some redundant initializers in ```AlluxioFuseFileSystem```.
> [SMALLFIX] Removed redundant initializers in AlluxioFuseFileSystem

- core/client/src/main/java/alluxio/client/file/options/ExistsOptions.java
Simplified the ```equals``` of the *ExistsOptions* class.
> [SMALLFIX] Simplified equals implementation of ExistsOptions

- core/client/src/main/java/alluxio/client/file/options/ListStatusOptions.java
Simplified the ```equals``` of the *ListStatusOptions* class.
> [SMALLFIX] Simplified equals implementation of ListStatusOptions

- core/client/src/test/java/alluxio/client/file/options/CompleteFileOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/CreateDirectoryOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/CreateFileOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/DeleteOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/FreeOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/InStreamOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/LoadMetadataOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/MountOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/OpenFileOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/OutStreamOptionsTest.java
- core/client/src/test/java/alluxio/client/file/options/SetAttributeOptionsTest.java
- core/client/src/test/java/alluxio/client/lineage/options/CreateLineageOptionsTest.java
- core/client/src/test/java/alluxio/client/lineage/options/DeleteLineageOptionsTest.java
- core/client/src/test/java/alluxio/client/lineage/options/GetLineageInfoListOptionsTest.java
- core/server/src/test/java/alluxio/master/file/options/CompleteFileOptionsTest.java
- core/server/src/test/java/alluxio/master/file/options/CreateDirectoryOptionsTest.java
- core/server/src/test/java/alluxio/master/file/options/CreateFileOptionsTest.java
- core/server/src/test/java/alluxio/master/file/options/MountOptionsTest.java
- core/server/src/test/java/alluxio/master/file/options/SetAttributeOptionsTest.java
Changed all tests in the form on `testEquals` to `equalsTest`. In the one case where there is a test against the `CommonTestUtils` titled `testEqualsTest` I figured that:
1. since it ends with `Test` it conforms to the Alluxio naming conventions
2. it is accurately testing a function (not a test) called `testEquals` 
[ALLUXIO-1918 here](https://alluxio.atlassian.net/browse/ALLUXIO-1918)
> [ALLUXIO-1918]: Change name testEquals to equalsTest

- core/client/src/main/java/alluxio/client/file/options/GetStatusOptions.java
Simplified the ```equals``` of the *GetStatusOptions* class.
> [SMALLFIX] Simplified equals implementation of GetStatusOptions

- core/client/src/main/java/alluxio/client/lineage/AbstractLineageClient.java
Removed an explicit parameter type in the *AbstractLineageClient* class.
> [SMALLFIX] Removed explicit parameter type in AbstractLineageClient

- bin/alluxio-start.sh
Support NoMount when ALLUXIO_RAM_FOLDER is set to a subdir in a mount point.
Usecase:
/mnt/ramdisk is mounted by a sudo user.
A non-sudo user can do this:
export ALLUXIO_RAM_FOLDER="/mnt/ramdisk/myfolder"
./bin/alluxio-start.sh local NoMount
https://alluxio.atlassian.net/browse/ALLUXIO-1871
> [ALLUXIO-1871] Support NoMount when ALLUXIO_RAM_FOLDER is set to a subdir in a mount point.

- tests/src/test/java/alluxio/hadoop/fs/DFSIOIntegrationTest.java
Updated all tests to be in the naming convention of `*Test` rather then `test*`.
[ALLUXIO-1917 here](https://alluxio.atlassian.net/browse/ALLUXIO-1917)
> [ALLUXIO-1917]: Improve name consistency in alluxio.hadoop.fs.DFSIOIntegrationTest

- pom.xml
Set the max size of JVM's heap for maven-surefire-plugin. Also disabled the GCOverheadLimit rule
> [SMALLFIX] set the max size of heap

- core/client/src/main/java/alluxio/client/file/options/UnmountOptions.java
Simplified the ```equals``` implementation of the *UnmountOptions* class.
> [SMALLFIX] Simplified equals implementation of UnmountOptions

- core/client/src/main/java/alluxio/client/file/policy/MostAvailableFirstPolicy.java
Simplified the ```equals``` implementation of the *MostAvailableFirstPolicy* class.
> [SMALLFIX] Simplified equals implementation of MostAvailableFirstPolicy

- core/client/src/main/java/alluxio/client/lineage/options/CreateLineageOptions.java
Simplified the ```equals``` implementation of the *CreateLineageOptions* class.
> [SMALLFIX] Simplified equals implementation of CreateLineageOptions

- core/client/src/main/java/alluxio/client/lineage/options/GetLineageInfoListOptions.java
Simplified the ```equals``` implementation of the *GetLineageInfoListOptions* class.
> [SMALLFIX] Simplified equals implementation of GetLineageInfoListOptions

- core/client/src/main/java/alluxio/client/lineage/LineageMasterClient.java
Removed an explicit argument type in the *LineageMasterClient* class.
> [SMALLFIX] Removed explicit type argument in LineageMasterClient

- core/client/src/main/java/alluxio/client/lineage/LineageFileOutStream.java
Removed an unnecessary return statement in the *LineageFileOutStream* class.
> [SMALLFIX] Removed unnecessary return statement in LineageFileOutStream

- core/client/src/main/java/alluxio/client/netty/ClientHandler.java
Removed an explicit argument type in the *ClientHandler* class.
> [SMALLFIX] Removed explicit type argument in ClientHandler

- core/client/src/main/java/alluxio/client/file/options/RenameOptions.java
Simplified the ```equals``` implementation of the *RenameOptions* class.
> [SMALLFIX] Simplified equals implementation of RenameOptions

- core/client/src/main/java/alluxio/client/FileSystemTestUtils.java
Removed an explicit type argument in the *FileSystemTestUtils* class.
> [SMALLFIX] Removed explicit type argument in FileSystemTestUtils

- core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
Merged variable and return statement in the *AbstractFileSystem* class.
> [SMALLFIX] Removed redundant variable in AbstractFileSystem

- core/client/src/main/java/alluxio/hadoop/HdfsFileInputStream.java
Removed redundant initializer in the *HdfsFileInputStream* class.
> [SMALLFIX] Removed redundant intializer in HdfsFileInputStream

- core/client/src/test/java/alluxio/client/file/FileOutStreamTest.java
Simplified a return statement and converted a field to a local variable in the *FileOutStreamTest* class.
> [SMALLFIX] Converted field to local variable and simplified return statement in FileOutStreamTest

- core/common/src/main/java/alluxio/collections/DirectedAcyclicGraph.java
Removed some explicit parameter types in the *DirectedAcyclicGraph* class.
> [SMALLFIX] Removed explicit parameter type in DirectedAcyclicGraph

- pom.xml
It's better to fail fast when we are running out of memory.
> [SMALLFIX] Enable GCOverheadLimit

- core/common/src/main/java/alluxio/collections/ConcurrentHashSet.java
- pom.xml
this PR reduces the InodeDirectory overhead of adding a child from 16kB to 64B
> [SMALLFIX] reducing heap overhead

- core/common/src/main/java/alluxio/network/protocol/databuffer/DataFileChannel.java
Removed a redundant initializer in the *DataFileChannel* class.
> [SMALLFIX] Removed redundant initializer in DataFileChannel

- core/common/src/main/java/alluxio/collections/PrefixList.java
Removed explicit parameter types in the *PrefixList* class.
> [SMALLFIX] Removed explicit parameter types in PrefixList

- core/common/src/main/java/alluxio/network/protocol/RPCMessageDecoder.java
- core/common/src/main/java/alluxio/network/protocol/RPCMessageEncoder.java
- core/common/src/main/java/alluxio/security/authentication/AuthenticatedClientUser.java
- core/common/src/main/java/alluxio/security/authentication/AuthenticationProvider.java
- core/common/src/main/java/alluxio/security/authentication/PlainSaslServer.java
- core/common/src/main/java/alluxio/security/authentication/SimpleAuthenticationProvider.java
- core/common/src/main/java/alluxio/security/authentication/TransportProvider.java
- core/common/src/main/java/alluxio/security/group/GroupMappingService.java
- core/common/src/main/java/alluxio/security/group/provider/IdentityUserGroupsMapping.java
- core/common/src/main/java/alluxio/security/group/provider/ShellBasedUnixGroupsMapping.java
https://alluxio.atlassian.net/browse/ALLUXIO-1322
Prepared some classes for the upcoming *MissingCtor* rule in Checkstyle. It checks that classes (except abstract ones) define a constructor and don't rely on the default one. The rule will look like the following
```<module name="MissingCtor"/>```
This ticket is WIP and needs some additional PRs.
> [ALLUXIO-1322] Prepared classes for MissingCtor rule in Checkstyle

- core/common/src/main/java/alluxio/replay/ReplayCache.java
Removed explicit parameter types in the *ReplayCache* class.
> [SMALLFIX] Removed explicit parameter types in ReplayCache

- core/common/src/main/java/alluxio/network/protocol/RPCResponse.java
Removed explicit parameter types in the *RPCResponse* class.
> [SMALLFIX] Removed explicit parameter types in RPCResponse

- core/common/src/main/java/alluxio/AbstractClient.java
All RPCs can potentially throw runtime exceptions which get converted to AlluxioTExceptions. We should handle this by propagation instead of retrying.
> [SMALLFIX] Avoid retrying unrecoverable alluxio exceptions

- core/common/src/main/java/alluxio/security/group/provider/ShellBasedUnixGroupsMapping.java
Removed an explicit parameter type in the *ShellBasedUnixGroupsMapping* class.
> [SMALLFIX] Removed explicit parameter types in ShellBasedUnixGroupsMapping

- core/common/src/main/java/alluxio/collections/PrefixList.java
the following code of "toString()" indicates that there must be a ";" at the end of the string representation, so I think we should add a ";" in the example of the string representation.
> [SMALLFIX]improve the javadoc of "PrefixList#toString()"

- core/common/src/main/java/alluxio/heartbeat/HeartbeatThread.java
I think {@link Runnable} is more suitable because Runnable is a class name.
> [SMALLFIX]change "{@code Runnable}" to "{@link Runnable}" in HeartbeatThread javadoc

- core/server/src/main/java/alluxio/cli/Format.java
Removed an unused import in the *Format* class.
> [SMALLFIX] Removed unused import in Format class

- core/common/src/main/java/alluxio/heartbeat/ScheduledTimer.java
the method "#tick()" uses an explicit lock "mLock", I think there is no need to use "synchronized".
> [SMALLFIX]remove the extra "synchronized" keyword in ScheduledTimer

- docs/_includes/Key-Value-Store-API/get-key-value-system.md
the "create()" is a static method, and I can only use the "KeyValueSystem.Factory.create()" when I use KeyValue API.
> [DOCFIX]change "KeyValueSystem.Factory()" to "KeyValueSystem.Factory"

- core/server/src/main/java/alluxio/worker/block/evictor/LRFUEvictor.java
Removed some explicit type arguments in the *LRFUEvictor* class.
> [SMALLFIX] Removed explicit type arguments in LRFUEvictor

- core/common/src/main/java/alluxio/security/login/LoginModuleConfiguration.java
Removed an explicit parameter type in the *LoginModuleConfiguration* class.
> [SMALLFIX] Removed explicit parameter type in LoginModuleConfiguration

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
InodeTree.java, line 284. It checks whether the path is root. If it root, it throws "FileAlreadyExistsException". I have changed loadMetadata function so that it throws a runtime exception if it catches FileAlreadyExistsException .
> [SMALL FIX] Fix a bug in FileSystemMaster

- core/server/src/main/java/alluxio/worker/block/meta/StorageTier.java
Removed an explicit type argument in the *StorageTier* class.
> [SMALLFIX] Removed explicit type argument in StorageTier

- core/server/src/main/java/alluxio/worker/block/SpaceReserver.java
Removed an explicit type argument in the *SpaceReserver* class.
> [SMALLFIX] Removed explicit type argument in SpaceReserver

- core/server/src/main/java/alluxio/worker/file/FileDataManager.java
Removed some explicit type arguments in the *FileDataManager* class.
> [SMALLFIX] Removed explicit type arguments in FileDataManager

- core/common/src/main/java/alluxio/util/io/BufferUtils.java
the "#equalConstantByteArray()" @return is not consistent with the code.
the "#equalIncreasingByteArray()" @return uses "{@code start}", but uses "value" at other places, but many methods in BufferUtils uses "start" such as ""#equalIncreasingByteBuffer()" ":
> [SMALLFIX]improve the javadoc of "BufferUtils"

- core/server/src/main/java/alluxio/worker/file/FileSystemWorker.java
Removed an explicit type argument in the *FileSystemWorker* class.
> [SMALLFIX] Removed explicit type argument in FileSystemWorker

- core/server/src/main/java/alluxio/worker/block/meta/StorageTierView.java
Removed an explicit type argument in the *StorageTierView* class.
> [SMALLFIX] Removed explicit type argument in StorageTierView

- core/server/src/main/java/alluxio/StorageTierAssoc.java
Removed some explicit type arguments in the *StorageTierAssoc* class.
> [SMALLFIX] Removed explicit type arguments in StorageTierAssoc

- core/server/src/main/java/alluxio/worker/file/FileWorkerMasterSyncExecutor.java
Removed a redundant initializer in the *FileWorkerMasterSyncExecutor* class.
> [SMALLFIX] Removed redundant initializer in FileWorkerMasterSyncExecutor

- core/server/src/test/java/alluxio/master/file/PermissionCheckerTest.java
Removed an explicit type argument in the *PermissionCheckerTest* class.
> [SMALLFIX] Removed explicit type argument in PermissionCheckerTest

- core/server/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
Removed some explicit type arguments in the *InodeTreeTest* class.
> [SMALLFIX] Removed explicit type arguments in InodeTreeTest

- core/server/src/test/java/alluxio/master/block/BlockMasterTest.java
Removed an explicit type argument and a redundant cast in the *BlockMasterTest* class.
> [SMALLFIX] Removed explicit type argument and redundant casts in BlockMasterTest

- core/server/src/test/java/alluxio/worker/block/allocator/AllocatorContractTest.java
Removed some explicit type parameters in the *AllocatorContractTest* class.
> [SMALLFIX] Removed explicit type arguments in AllocatorContractTest

- core/server/src/test/java/alluxio/master/file/PermissionCheckTest.java
Removed an explicit type parameter in the *PermissionCheckTest* class.
> [SMALLFIX] Removed explicit type argument in PermissionCheckTest

- core/server/src/test/java/alluxio/master/lineage/meta/LineageStoreTest.java
Removed an explicit type argument in the *LineageStoreTest* class.
> [SMALLFIX] Removed explicit type argument in LineageStoreTest

- core/common/src/main/java/alluxio/util/io/PathUtils.java
- core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
the method "#replaceHostName()"  checks the condition "path.getPort() != -1" repeatedly, I think we can remove the outer one.(this is because an AlluxioURI doesn't ensure an authority has a port)
Or remove the inner one?
> [SMALLFIX]improve javadoc and change the code of "#replaceHostName(URI)"

- core/server/src/test/java/alluxio/worker/block/evictor/LRFUEvictorTest.java
Removed some explicit type arguments in the *LRFUEvictorTest* class.
> [SMALLFIX] Removed explicit type arguments in LRFUEvictorTest

- core/server/src/test/java/alluxio/worker/block/evictor/EvictorContractTest.java
Removed some explicit type arguments in the *EvictorContractTest* class.
> [SMALLFIX] Removed explicit type arguments in EvictorContractTest

- core/server/src/test/java/alluxio/worker/block/meta/StorageDirTest.java
Removed some explicit type arguments in the *StorageDirTest* class.
> [SMALLFIX] Removed explicit type arguments in StorageDirTest

- core/client/src/main/java/alluxio/client/file/UnderFileSystemFileInStream.java
- core/client/src/main/java/alluxio/client/netty/NettyUnderFileSystemFileReader.java
- core/client/src/test/java/alluxio/client/file/UnderFileSystemFileInStreamTest.java
- core/server/src/main/java/alluxio/worker/file/UnderFileSystemManager.java
- core/server/src/main/java/alluxio/worker/netty/DataServerHandler.java
- core/server/src/main/java/alluxio/worker/netty/UnderFileSystemDataServerHandler.java
Wrap the correct portion of the byte array and consume the data on the client side properly. Also a cosmetic fix in the server exception logging.
> [SMALLFIX] Fix some bugs in ufsdataserver logic

- conf/alluxio-site.properties.template
- core/common/src/main/resources/alluxio-default.properties
- docs/_data/table/en/user-configuration.yml
- docs/_data/table/en/worker-configuration.yml
- docs/_data/table/user-configuration.csv
This changes prevents a highly concurrent Alluxio client from depleting the Alluxio worker connection pool.
> [SMALLFIX] reducing the default max size of the block worker Thrift client pool

- core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client/src/test/java/alluxio/client/util/ClientTestUtils.java
- core/client/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
- core/client/src/test/java/alluxio/hadoop/HadoopClientTestUtils.java
Enforces the assumption we only init the hadoop client once.
> [SMALLFIX] Hadoop fs init fix

- core/common/src/main/java/alluxio/AbstractClient.java
in the previous logic, if `beforeDisconnect()` invokes any RPC, additional connection is be created and the first one is never be closed
> [SMALLFIX] fixing a possible resource leak in AbstractClient

- core/server/src/main/java/alluxio/SessionInfo.java
- core/server/src/main/java/alluxio/Sessions.java
Any other methods in "Sessions" synchronize on "mSessions", only "#removeSessions(sessionid)" uses
synchronize on the method and "mSessions" both, I think we can remove the "synchronize" which on the method
> [SMALLFIX] improve javadoc and chenge code in "Sessions"

- core/server/src/test/java/alluxio/worker/block/BlockLockManagerTest.java
Fixed Javadoc in the *BlockLockManagerTest* class.
> [SMALLFIX] Fixed Javadoc in BlockLockManagerTest

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
Now, both call sites of renameInternal() have the correct lock modes.
> [SMALLFIX] Fix renameFromEntry locking modes

- core/client/src/main/java/alluxio/client/netty/NettyRemoteBlockReader.java
- core/client/src/main/java/alluxio/client/netty/NettyRemoteBlockWriter.java
- core/client/src/main/java/alluxio/client/netty/NettyUnderFileSystemFileReader.java
- core/client/src/main/java/alluxio/client/netty/NettyUnderFileSystemFileWriter.java
Cleans up the listener so long living Netty readers do not have an infinitely growing set of listeners.
> [SMALLFIX] Cleanup netty listeners on read path

- core/client/src/main/java/alluxio/client/file/FileSystemContext.java
In other places we throw `RuntimeException`, but I think the error is not so serious and applications can retry if desired.
> [SMALLFIX] Throw an exception if there are no workers available

- keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMaster.java
Removed some explicit argument types in the *KeyValueMaster* class.
> [SMALLFIX] Removed explicit argument types in KeyValueMaster

- core/server/src/main/java/alluxio/master/block/BlockContainerIdGenerator.java
This class has only one single variable "mNextContainerId" which type is AtomicLong, Atomic variables supports lock-free thread-safe programming on single variables. I think we can delegate the thread-safety to this atomic variable and don't need to use intrinsic lock.
> [SMALLFIX]remove "synchronized" in "BlockContainerIdGenerator"

- core/server/src/main/java/alluxio/worker/file/FileSystemWorker.java
- core/server/src/main/java/alluxio/worker/file/UnderFileSystemManager.java
- core/server/src/main/java/alluxio/worker/netty/UnderFileSystemDataServerHandler.java
- core/server/src/test/java/alluxio/worker/file/UnderFileSystemManagerTest.java
It isn't guaranteed the underlying under storage stream will support skip to or past end of file. Also reduces one communication to the under storage.
> [SMALLFIX] Faster return on EOF in under storage read path.

- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
Removed an explicit argument type in the *AbstractLocalAlluxioCluster* class.
> [SMALLFIX] Removed explicit argument type in AbstractLocalAlluxioCluster

- core/client/src/main/java/alluxio/hadoop/FaultTolerantFileSystem.java
- core/client/src/main/java/alluxio/hadoop/FileSystem.java
When we added the "default" constructor we forgot to call the super constructor
> Add missing super calls to hadoop FileSystem client

- core/common/src/main/java/alluxio/util/io/BufferUtils.java
Removed an explicit parameter type in the *BufferUtils* class.
> [SMALLFIX] Removed explicit parameter type in BufferUtils

- core/common/src/main/java/alluxio/util/io/PathUtils.java
Removed an explicit parameter type in the *PathUtils* class.
> [SMALLFIX] Removed explicit parameter type in PathUtils

- keyvalue/client/src/test/java/alluxio/client/keyvalue/ByteBufferKeyValuePartitionReaderTest.java
Converted some fields to local variables in the *ByteBufferKeyValuePartitionReaderTest* class.
> [SMALLFIX] Converted fields to local variables in ByteBufferKeyValuePartitionReaderTest

- keyvalue/server/src/main/java/alluxio/worker/keyvalue/KeyValueWorker.java
Removed some explicit parameter types in the *KeyValueWorker* class.
> [SMALLFIX] Removed explicit argument types in KeyValueWorker

- minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java
Removed an explicit argument type in the *MultiMasterLocalAlluxioCluster* class.
> [SMALLFIX] Removed explicit argument type in MultiMasterLocalAlluxioCluster

- tests/src/test/java/alluxio/client/AbstractFileOutStreamIntegrationTest.java
Removed an explicit argument type in the *AbstractFileOutStreamIntegrationTest* class.
> [SMALLFIX] Removed explicit argument type in AbstractFileOutStreamIntegrationTest

- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
Removed an explicit argument type in the *S3UnderFileSystem* class.
> [SMALLFIX] Removed explicit argument type in S3UnderFileSystem

- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
Valid prefixes ending in a path separator will be counted as "existing" paths.
> [SMALLFIX] Implement isDirectory in Swift UFS

- core/common/src/main/java/alluxio/network/protocol/RPCFileReadResponse.java
Addresses the TODO, also is more efficient.
> [SMALLFIX] Use DataNettyBuffer on ufs read.

- core/client/src/main/java/alluxio/client/block/UnderStoreBlockInStream.java
- core/client/src/main/java/alluxio/client/file/FileOutStream.java
- core/client/src/main/java/alluxio/client/file/UnderFileSystemFileInStream.java
- core/client/src/main/java/alluxio/client/file/UnderFileSystemFileOutStream.java
- core/client/src/test/java/alluxio/client/block/DelegatedUnderStoreBlockInStreamTest.java
- core/client/src/test/java/alluxio/client/block/DirectUnderStoreBlockInStreamTest.java
- core/client/src/test/java/alluxio/client/file/FileInStreamTest.java
- core/client/src/test/java/alluxio/client/file/FileOutStreamTest.java
- core/common/src/main/java/alluxio/Constants.java
- core/common/src/main/resources/alluxio-default.properties
- docs/_data/table/en/user-configuration.yml
- docs/_data/table/user-configuration.csv
Makes specific constants for ufs ops through the worker instead of using constants intended for other purposes.
> [SMALLFIX] Ufs delegation constants.

- core/server/src/main/java/alluxio/master/block/BlockMaster.java
The code path is hit even in expected cases.
> [SMALLFIX] Disable excessive logging.

- shell/src/main/java/alluxio/shell/command/PersistCommand.java
Removed an explicit argument type in the *PersistCommand* class.
> [SMALLFIX] Removed explicit argument type in PersistCommand

- shell/src/main/java/alluxio/shell/command/CopyToLocalCommand.java
Removed some explicit argument types and a redundant initializer in the *CopyToLocalCommand* class.
> [SMALLFIX] Removed explicit argument types and redundant initializer in CopyToLocalCommand

- tests/src/test/java/alluxio/client/BufferedBlockInStreamIntegrationTest.java
Removed an explicit argument type in the *BufferedBlockInStreamIntegrationTest* class.
> [SMALLFIX] Removed explicit argument type in BufferedBlockInStreamIntegrationTest

- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
https://alluxio.atlassian.net/browse/ALLUXIO-1950
A conservative approach to cleaning up temporary directories. This won't delete anything until the JVM is exiting.
> [ALLUXIO-1950] Clean up temporary testing directories

- tests/src/test/java/alluxio/client/FileInStreamIntegrationTest.java
Removed an explicit argument type in the *FileInStreamIntegrationTest* class.
> [SMALLFIX] Removed explicit argument type in FileInStreamIntegrationTest

- tests/src/test/java/alluxio/client/RemoteBlockInStreamIntegrationTest.java
Removed an explicit argument type in the *RemoteBlockInStreamIntegrationTest* class.
> [SMALLFIX] Removed explicit argument type in RemoteBlockInStreamIntegrationTest

- tests/src/test/java/alluxio/client/LocalBlockInStreamIntegrationTest.java
Removed an explicit argument type in the *LocalBlockInStreamIntegrationTest* class.
> [SMALLFIX] Removed explicit argument type in LocalBlockInStreamIntegrationTest

- tests/src/test/java/alluxio/client/IsolatedFileSystemIntegrationTest.java
Removed some explicit argument types in the *IsolatedFileSystemIntegrationTest* class.
> [SMALLFIX] Removed explicit argument types in IsolatedFileSystemIntegrationTest

- tests/src/test/java/alluxio/client/FileSystemUtilsIntegrationTest.java
Removed some redundant initializers in the *FileSystemUtilsIntegrationTest* class.
> [SMALLFIX] Removed redundant initializers in FileSystemUtilsIntegrationTest

- underfs/swift/src/main/java/alluxio/underfs/swift/http/SwiftDirectClient.java
Simplified the return statement in the *SwiftDirectClient* class.
> [SMALLFIX] Inlined variable in SwiftDirectClient

- docs/_includes/Key-Value-Store-API/set-output-format.md
- keyvalue/client/src/main/java/alluxio/hadoop/mapreduce/KeyValueOutputCommitter.java
- keyvalue/client/src/main/java/alluxio/hadoop/mapreduce/KeyValueOutputFormat.java
https://alluxio.atlassian.net/browse/ALLUXIO-1972
Originally, the key-value mapreduce interface uses hadoop1.x API, after upgrading to hadoop2.x API, the original implementation is not quite correct, the problem is caused by the different handling of task output directory and job output directory by output committer in different API versions.
This PR is tested against hadoop1.2.1 and hadoop2.4.1 with Alluxio tag v1.1.0-RC4, on a local deployment.
> [ALLUXIO-1972] Update key-value mapreduce interface

- tests/src/test/java/alluxio/IntegrationTestUtils.java
- tests/src/test/java/alluxio/client/FreeAndDeleteIntegrationTest.java
- tests/src/test/java/alluxio/shell/command/FreeCommandTest.java
The reason for flakiness seems to be that the test is only waiting for https://github.com/Alluxio/alluxio/blob/master/core/server/src/main/java/alluxio/worker/block/TieredBlockStore.java#L302 finishes, where it removes the block metadata. There's a slight chance that the test issues the second heartbeat while the listener has not been fired in line 305, thus the removed blocks are not sent to the master in the second heartbeat.
@aaudiber
> [ALLUXIO-1907] second attempt to deflake free tests

- conf/alluxio-site.properties.template
- core/common/src/main/resources/alluxio-default.properties
- docs/_data/table/user-configuration.csv
Remote read microbench result shows that 4KB remote buffer size performs better than 4MB/8MB.
> [SMALLFIX] Change the default remote buffer size to 4KB.

- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
Removed some explicit argument types in the *FileSystemMasterIntegrationTest* class.
> [SMALLFIX] Removed explicit argument types in FileSystemMasterIntegrationTest

- tests/src/test/java/alluxio/master/JournalIntegrationTest.java
Removed an explicit argument type in the *JournalIntegrationTest* class.
> [SMALLFIX] Removed explicit argument type in JournalIntegrationTest

- tests/src/test/java/alluxio/hadoop/FileSystemBlockLocationIntegrationTest.java
Removed some redundant initializers in the *FileSystemBlockLocationIntegrationTest* class.
> [SMALLFIX] Removed redundant intializers in FileSystemBlockLocationIntegrationTest

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
Do not throw exception when loading metadata on a non-existing file/dir.
> [SMALL FIX] Do not load metadata for non-persisted directory

- shell/src/main/java/alluxio/shell/command/WithWildCardPathCommand.java
Removed an explicit argument type in the *WithWildCardPathCommand* class.
> [SMALLFIX] Removed explicit argument type in WithWildCardPathCommand

- tests/src/test/java/alluxio/master/MasterFaultToleranceIntegrationTest.java
Removed some explicit argument types in the *MasterFaultToleranceIntegrationTest* class.
> [SMALLFIX] Removed explicit argument types in MasterFaultToleranceIntegrationTest

- underfs/glusterfs/src/test/java/alluxio/underfs/glusterfs/GlusterFSUnderFileSystemFactoryTest.java
- underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
- underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSInputStream.java
- underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Small clean up of some classes in the *underfs* package
GlusterFSUnderFileSystemFactoryTest:
- Made a field a local variable
HdfsUnderFileSystem:
- Removed explicit argument types
LocalUnderFileSystem:
- Removed explicit argument types
OSSInputStream:
- Simplified return statement
OSSUnderFileSystem:
- Removed explicit argument type
> [SMALLFIX] Clean up in underfs package

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
The `LOG.error` in here may be an expected case.
> [SMALLFIX] Move a master log message from error to debug

- tests/src/test/java/alluxio/network/protocol/RPCMessageIntegrationTest.java
- tests/src/test/java/alluxio/shell/AlluxioShellUtilsTest.java
- tests/src/test/java/alluxio/underfs/hdfs/LocalMiniDFSCluster.java
- tests/src/test/java/alluxio/worker/BlockServiceHandlerIntegrationTest.java
- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
Small clean up of some classes in the *underfs* and *test* package.
RPCMessageIntegrationTest:
- Simplified return statement
AlluxioShellUtilsTest:
- Removed explicit argument types
LocalMiniDFSCluster:
- Removed unnecessary cast
BlockServiceHandlerIntegrationTest:
- Made a field a local variable
GCSUnderFileSystem:
- Removed explicit argument type
> [SMALLFIX] Clean up in underfs and test module

- core/server/src/main/java/alluxio/worker/file/UnderFileSystemManager.java
- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSInputStream.java
- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3InputStream.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
This PR includes an improvement for `openAtPosition` when delegation is turned on. Implementation of `openAtPosition` is added for S3UnderFileSystem, to save redundant close and reopen S3InputStream.
A simple benchmark was run locally, doing a Read from a 10MB S3 THROUGH file, with read buffer size = 2M. That being said, with delegation on, `openAtPosition` will be called for 5 times. The logs measure the time elapsed for `OpenAtPosition`. The data shows that this PR would save > 40% time of `OpenAtPosition` call, for each 2M chunk.
Before this PR.
```
➜  tachyon git:(branch-1.1-s3) ✗ time ./bin/alluxio fs copyToLocal /file10M.txt /tmp/file10M.txt
Copied /file10M.txt to /tmp/file10M.txt
./bin/alluxio fs copyToLocal /file10M.txt /tmp/file10M.txt
1.18s user 0.15s system 6% cpu 20.415 total …
```
> [SMALLFIX] Improvement to openAtPosition when delegation is turned on, for S3/GCS.

- conf/alluxio-site.properties.template
- core/common/src/main/resources/alluxio-default.properties
- core/common/src/test/java/alluxio/ConfigurationTest.java
- docs/_data/table/user-configuration.csv
In RC5 testing, we found setting alluxio.user.block.remote.read.buffer.size.bytes=4KB would cause significant remote read performance drop, when client-size buffer size is also set to a small value, like 4KB. We should keep the remote read buffer size to be 8MB.
> [Revert] Revert default remote read buffer size to 8MB

- core/server/src/main/java/alluxio/worker/block/evictor/EvictorUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-1994
> The code "maxFreeSize = dirView.getAvailableBytes()" in line 68 of EvictorUtils is not needed because the code is not in a for-loop like the code before and we can delete it.
> [ALLUXIO-1994] Delete the code in line 68 in EvictorUtils

- core/common/src/main/resources/alluxio-default.properties
- docs/_data/table/user-configuration.csv
Since delegation is being introduced in this version, turn it off by default. Also updates the ufs read buffer size to be equal to our remote read buffer size.
> [SMALLFIX] Disable delegation by default

- docs/cn/Configuring-Alluxio-with-HDFS.md
This PR fixes issue with JIRA ticket [ALLUXIO-1979](https://alluxio.atlassian.net/browse/ALLUXIO-1979)
In `docs/en/Configuring-Alluxio-with-HDFS.md` of the English version there is a `bootstrap-conf` command snippet added in the `Configuring Alluxio` section. This PR translate it into Chinese and add it in the corresponding page of the Chinese version.
> [DOCFIX] Add a `bootstrap-conf` command snippet in the Chinese version of `docs/en/Configuring-Alluxio-with-HDFS.md`

- docs/cn/Configuring-Alluxio-with-Swift.md
This PR fixes issue with JIRA ticket [ALLUXIO-1982](https://alluxio.atlassian.net/browse/ALLUXIO-1982)
In `docs/en/Configuring-Alluxio-with-Swift.md` of the English version there is a `bootstrap-conf` command snippet added in the `Initial Setup` section. This PR translate it into Chinese and add it in the corresponding page of the Chinese version.
> [DOCFIX] Add a `bootstrap-conf` command snippet in the Chinese version of `docs/en/Configuring-Alluxio-with-Swift.md`

- docs/cn/Web-Interface.md
"System Configuration" has been updated to "Configuration" in the Web UI navigation bar.
> [DOCFIX]Update "System Configuration" to "Configuration" in docs to be consistent with the Web UI navigation bar

- docs/cn/Configuring-Alluxio-with-secure-HDFS.md
This PR fixes issue with JIRA ticket [ALLUXIO-1983](https://alluxio.atlassian.net/browse/ALLUXIO-1983)
(**Note**: The fixed file is *different* from that in #3459 which fixed Configuring-Alluxio-with-**HDFS**.md, while this PR fixes Configuring-Alluxio-with-**secure-HDFS**.md. I also left some comment under #3466)
In `docs/en/Configuring-Alluxio-with-secure-HDFS.md` of the English version there is a `bootstrap-conf` command snippet added in the `Configuring Alluxio` section. This PR translate it into Chinese and add it in the corresponding page of the Chinese version.
> [DOCFIX] Add a `bootstrap-conf` command snippet in the Chinese version of `docs/en/Configuring-Alluxio-with-secure-HDFS.md`

- core/common/src/main/java/alluxio/heartbeat/HeartbeatScheduler.java
- core/common/src/main/java/alluxio/heartbeat/ScheduledTimer.java
- core/server/src/test/java/alluxio/master/MasterSourceTest.java
- core/server/src/test/java/alluxio/master/file/FileSystemMasterTest.java
- core/server/src/test/java/alluxio/master/lineage/LineageMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-1975
Previously we had flakiness due to the following flow:
1. Unit test 1 creates a Master, e.g. FileSystemMaster, which uses a heartbeat thread. The heartbeat thread X is initialized to use the scheduled timer.
2. The scheduled timer becomes ready to schedule and adds itself to the `sTimers` map in `HeartbeatScheduler`. This creates a mapping from the string "X" to the timer object.
3. The test calls schedule, removing the timer from `sTimers` and executing a heartbeat. After the heartbeat has executed, the timer adds itself back to `sTimers`.
4. Unit test 1 ends and the Master is stopped. `sTimers` is static and doesn't care (it still holds the mapping from "X" to the timer).
5. Unit test 2 begins and creates a new Master and new timer named …
> [ALLUXIO-1975] Fix issue with manual heartbeat scheduling

- core/common/src/main/java/alluxio/exception/PreconditionMessage.java
- core/server/src/main/java/alluxio/worker/block/meta/StorageTier.java
- core/server/src/test/java/alluxio/worker/block/meta/StorageTierTest.java
Previously this would generate a number format exception with no reference to where it came from.
> [SMALLFIX] Improve blank tier quota error

- core/client/src/main/java/alluxio/client/block/BufferedBlockInStream.java
- core/client/src/main/java/alluxio/client/file/UnderFileSystemFileInStream.java
- core/client/src/test/java/alluxio/client/block/BufferedBlockInStreamTest.java
- core/client/src/test/java/alluxio/client/file/UnderFileSystemFileInStreamTest.java
Fixes a bug where the buffer would not be read from if the read goes exactly to the end of the buffer.
> [SMALLFIX] Read entire buffer in buffered instreams

- bin/alluxio
- bin/alluxio-mount.sh
- bin/alluxio-start.sh
- bin/alluxio-stop.sh
- bin/alluxio-workers.sh
This is an issue when our scripts are run through 3rd-party applications which may only report stderr when errors occur.
> [SMALLFIX] Write shell error messages to stderr

- core/server/src/main/java/alluxio/worker/file/FileSystemWorker.java
- core/server/src/main/java/alluxio/worker/file/UnderFileSystemManager.java
- core/server/src/main/java/alluxio/worker/netty/UnderFileSystemDataServerHandler.java
- core/server/src/test/java/alluxio/worker/file/UnderFileSystemManagerTest.java
Keeps state to improve the performance when reading from an under storage like S3 where each open is fairly expensive. Performance is about the same as no delegation.
> [ALLUXIO-1739] Keep state on delegation reads

- core/client/src/main/java/alluxio/client/file/BaseFileSystem.java
- core/client/src/main/java/alluxio/client/file/FileSystemUtils.java
- core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
- core/client/src/main/java/alluxio/hadoop/HadoopUtils.java
- core/client/src/main/java/alluxio/hadoop/HdfsFileInputStream.java
- core/client/src/test/java/alluxio/client/lineage/LineageFileSystemTest.java
Some minor fixed in the **core** module.
*BaseFileSystem*: Collapsed exception handling
*FileSystemUtils*: Fixed documentation
*AbstractFileSystem*: Collapsed exception handling
*HadoopUtils*: Fixed deprecation
*HdfsFileInputStream*: Removed redundant initializer
*LineageFileSystemTest*: Simplified ```instanceof``` statement
> [SMALLFIX] Clean up in the core module

- examples/src/main/java/alluxio/cli/JournalCrashTest.java
- examples/src/main/java/alluxio/examples/BasicNonByteBufferOperations.java
- examples/src/main/java/alluxio/examples/Performance.java
- examples/src/main/java/alluxio/examples/keyvalue/KeyValueStoreOperations.java
- examples/src/main/java/alluxio/examples/keyvalue/ShowKeyValueStore.java
Minor fixes in the **examples** module.
*JournalCrashTest*: Removed the exception rethrows and fixed deprecation
*BasicNonByteBufferOperations*: introduced automatic resource management in try
*Performance*: Made field a local variable
*KeyValueStoreOperations*: Made a field a local variable
*ShowKeyValueStore*: Converted if-else-statements into switch statement
> [SMALLFIX] Clean up in the examples module

- minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java
- shell/src/main/java/alluxio/shell/command/CatCommand.java
- shell/src/main/java/alluxio/shell/command/CopyToLocalCommand.java
- shell/src/main/java/alluxio/shell/command/TailCommand.java
Minor fixes in the **shell** module.
*MultiMasterLocalAlluxioCluster*: Changed the usage from StringBuilder to String to simply the return statement.
*CatCommand*: Introduced automatic resource management in try statement.
*CopyToLocalCommand*: Introduced automatic resource management in try statement.
*TailCommand*: Introduced automatic resource management in try statement.
> [SMALLFIX] Clean up in the shell module

- tests/src/test/java/alluxio/client/keyvalue/KeyValueSystemIntegrationTest.java
- tests/src/test/java/alluxio/hadoop/FileSystemRenameIntegrationTest.java
- tests/src/test/java/alluxio/hadoop/FileSystemStatisticsTest.java
- tests/src/test/java/alluxio/hadoop/fs/DFSIOIntegrationTest.java
- tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
Minor fixes in the **test** module.
*KeyValueSystemIntegrationTest*: Introduced automatic resource management in try statement.
*FileSystemRenameIntegrationTest*: Fixed deprecation.
*FileSystemStatisticsTest*: Fixed deprecation.
*DFSIOIntegrationTest*: Added documentation.
*FileSystemMasterIntegrationTest*: Removed explicit argument type and simplified exception handling.
> [SMALLFIX] Clean up in the test module

- core/client/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
This fixes the following compilation error reported on the mailing list:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /dfml/dfml_installs/alluxio-1.1.0/core/client/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java:[126,11] reference to assertEquals is ambiguous
both method assertEquals(java.lang.Object,java.lang.Object) in org.junit.Assert and method assertEquals(long,long) in org.junit.Assert match
[ERROR] /dfml/dfml_installs/alluxio-1.1.0/core/client/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java:[127,11] reference to assertEquals is ambiguous
both method assertEquals(java.lang.Object,java.lang.Object) in org.junit.Assert and method assertEquals(long,long) in org.junit.Assert match
[ERROR] …
```
> [SMALLFIX] Fixing ambiguous reference compilation error.

- core/common/pom.xml
upgrade commons-lang's version to 2.6. We are compiling commons-lang to our client jars (with dependency). Spark uses 2.6 which has a function ClassUtils#isAssignable(a, b, c) that doesn't appear in 2.4
stack trace:
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.NoSuchMethodError: org.apache.commons.lang.ClassUtils.isAssignable([Ljava/lang/Class;[Ljava/lang/Class;Z)Z
at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$makeCopy$1$$anonfun$7.apply(TreeNode.scala:393)
at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$makeCopy$1$$anonfun$7.apply(TreeNode.scala:384)
at scala.collection.IndexedSeqOptimized$$anonfun$1.apply(IndexedSeqOptimized.scala:50)
at …
> [SMALLFIX] upgrade commons-lang's version to 2.6

- docs/_includes/Running-Alluxio-on-EC2-Yarn/script-output.md
- docs/en/Running-Alluxio-on-EC2-Yarn.md
- integration/bin/alluxio-application-master.sh
- integration/bin/alluxio-yarn.sh
- integration/bin/common.sh
- integration/yarn/src/main/java/alluxio/yarn/ApplicationMaster.java
- integration/yarn/src/main/java/alluxio/yarn/Client.java
- Set the logger type for Yarn Client and Application Master(AM) so that we can see their logs in userlogs/.../stdout.
- Exit the client after it launches the AM to make it easier to run the client programmatically, and because the information it provided after launch wasn't very useful.
- Add command-line option for providing the name of the yarn node to run Alluxio Master on. This is especially useful on EC2 where yarn names its nodes using internal DNS names, which might differ from ALLUXIO_MASTER_HOSTNAME.
> [SMALLFIX] Yarn improvements

- docs/cn/Configuring-Alluxio-with-S3.md
@aaudiber @gpang Fixed a bad file reference in the docs which was causing the jekyll build to fail. Reference `docs/_includes/Configuring-Alluxio-with-s3/` for the directory which the reference was to.
> [Doc fix] Fixed bad reference in docs

- docs/en/Configuration-Settings.md
@aaudiber @gpang Noticed an issue with an erroneous `</pre>` tag showing up in the rendered view of this doc. Removed the tag.
> [DOCFIX] Remove erroneous `</pre>` tag

- core/common/src/test/java/alluxio/CommonTestUtils.java
- minicluster/pom.xml
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
https://alluxio.atlassian.net/browse/ALLUXIO-1950
Instead of creating temp directories in /tmp, we will create them in /tmp/alluxio-tests/ and delete this directory at the start and end of testing.
> [ALLUXIO-1950] Improve cleanup of test cluster directories

- docs/_config.yml
master hasn't been released yet, so we should call its "released version" master
> [DOCFIX] Update master docs version to master

- core/common/src/test/java/alluxio/CommonTestUtils.java
Sometimes this cleanup will fail due to files/directories being created by other threads while the cleanup is happening.
> [SMALLFIX] Permit failure to clean up after previous tests.

- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystem.java
- underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
Addresses: https://alluxio.atlassian.net/browse/ALLUXIO-2032
Prior to this fix, it was not possible GCS folders that were not created through Alluxio.
> [ALLUXIO-2032] GCS mount fix

- bin/alluxio-workers.sh
- core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2025
if there is a FileDoesNotExistException throw FileNotFoundException ,so the user like hbase can handle
exception more accurate.
> [ALLUXIO-2025] Improve AbstractFileSystem.listStatus(Path path) method for exception process

- docs/_config.yml
- docs/_layouts/global.html
categories is a reserved word in Jekyll and our usage breaks in
later versions.
> [DOCFIX] Rename reserved categories variable

- core/common/src/test/java/alluxio/AlluxioTestDirectory.java
- core/common/src/test/java/alluxio/CommonTestUtils.java
- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
Previously we made the dangerous assumption that only one
process would run the tests at a time per node. This was
violated by pull request builds running at the same time as
Alluxio master builds. This change removes the assumption by
only deleting files older than 2 hours.
> [SMALLFIX] Improve handling of Alluxio test directory

- docs/_config.yml
Reverts Alluxio/alluxio#3577
The released version is used to create a link to the latest version of alluxio, so it should point to 1.1.0 on master.
> Revert "[DOCFIX] Update master docs version to master"

- docs/_config.yml
The latest 1.0 docs should display themselves as 1.0.1 docs, not as 1.0.2-SNAPSHOT docs
> [DOCFIX] Update master version in 1.0

- docs/_config.yml
The latest 0.8 docs should display themselves as 0.8.2 docs, not as 0.8.3-SNAPSHOT docs.
> [DOCFIX] Update master version in 0.8

- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
Current approach always make two RPCs to delete files on UFS even on expected case, which could potentially slow down the master.
> [SMALLFIX] Save one RPC on expected case when deleting a file from UFS

- tests/src/test/java/alluxio/master/lineage/LineageMasterIntegrationTest.java
This has occasionally been timing out. This PR increases the timeout to make it clearer whether jenkins is just running slowly, or the test is actually getting stuck.
> [SMALLFIX] Increase lineageRecoveryTest timeout

- core/client/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
Reverts Alluxio/alluxio#3606
The test fails when running with hdfs as the UFS
> Revert "fix ALLUXIO-2036"

- core/client/src/main/java/alluxio/hadoop/HdfsFileInputStream.java
The test requires that available throws an IOException when the stream is closed.
Followup to https://github.com/Alluxio/alluxio/pull/3618
> [SMALLFIX] Fix seek contract test

- core/server/src/main/java/alluxio/master/file/meta/InodeDirectory.java
- core/server/src/test/java/alluxio/master/file/meta/InodeDirectoryTest.java
The id index in Inode directory is only used by test file while it takes a lot of memory. We can remove this index to optimize memory.
> [ALLUXIO-2048] remove id index in inode directory

- core/client/src/main/java/alluxio/hadoop/HdfsFileInputStream.java
- tests/src/test/java/alluxio/hadoop/HdfsFileInputStreamIntegrationTest.java
Right now, the read type of `HdfsFileInputStream` is hardcoded and can not accept the user's specification defined in configuration file `alluxio-site.properties`. This PR is used to activate the setting of `alluxio.user.file.readtype.default` for Hadoop and Spark workloads.
> [SMALLFIX] Remove the hardcoded read type (CACHE) from HdfsFileInputStream

- underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystemFactory.java
- underfs/s3/src/main/java/alluxio/underfs/s3/S3UnderFileSystemFactory.java
`configuration.get` will throw `RuntimeException` when key is not recognized with default value.
The current code may trigger the wrong exception when aws/gcs credential not set, confusing users.
Before this fix, the error message in master.log is like "invalid configuration key fs.gcs.accessKeyId` when user forget to set this key, which is very confusing. 
After this fix, the error message becomes: "Google Credentials not available, cannot create GCS Under File System."
> [SMALLFIX] Fix wrong use of Configuration in ufs creation

- minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
- minicluster/src/main/java/alluxio/underfs/UnderFileSystemCluster.java
- minicluster/src/test/java/alluxio/underfs/UnderFileSystemClusterTest.java
- tests/src/test/java/alluxio/client/AbstractFileOutStreamIntegrationTest.java
This fix intends to set the correct UNDERFS_ADDRESS for gcs, swift, glusterfs in addition to the previously hard coded hdfs, s3 and oss.
> [ALLUXIO-2044] Correct UFS not initialized for some UnderStorageClusters during integration test

- core/client/src/main/java/alluxio/client/file/FileSystemUtils.java
- core/server/src/main/java/alluxio/master/file/FileSystemMaster.java
- core/server/src/main/java/alluxio/master/file/meta/InodeTree.java
- core/server/src/main/java/alluxio/worker/file/FileDataManager.java
- tests/src/test/java/alluxio/client/PersistPermissionIntegrationTest.java
- tests/src/test/java/alluxio/hadoop/FileSystemAclIntegrationTest.java
One TODO still left in `FileDataManager.java` when delegation is turned on, because worker can't easily get the status of a Alluxio directory.
> [SMALLFIX] Improve directories permission propagation to UFS.

- bin/alluxio-start.sh
The -f option are not using in the getopts in the bin/alluxio-start.sh shell script anymore, the getopts just contains "hNw" options, not "fhNw" anymore.
I also noticed that the "-f" option should given(or not) after the "MOPT" or as the "MOPT",so we should remove the "-f" option from [-fhNw] and move it to the tail of command as another option?
like below:
```
bin/alluxio-start.sh all NoMount
bin/alluxio-start.sh local NoMount -f
bin/alluxio-start.sh -N master -f
```
> [ALLUXIO-2053] alluio-start.sh not use -f in the getopts anymore

- shell/src/main/java/alluxio/shell/command/LsCommand.java
Addresses: https://alluxio.atlassian.net/browse/ALLUXIO-1481
Before this PR:
```
$ ./bin/alluxio fs ls -R /
24.00B    07-08-2016 12:20:41:998                 /default_tests_files
80.00B    07-08-2016 12:20:41:998  In Memory      /default_tests_files/Basic_CACHE_PROMOTE_MUST_CACHE
...
```
After this PR:
```
$ ./bin/alluxio fs ls -R /
24.00B    07-08-2016 12:20:41:998  Directory      /default_tests_files
80.00B    07-08-2016 12:20:41:998  In Memory      /default_tests_files/Basic_CACHE_PROMOTE_MUST_CACHE
...
```
> [ALLUXIO-1481] More informative 'ls' output.

- conf/alluxio-env.sh.template
Currently, the worker's JVM size is specified as an integration property `alluxio.integration.worker.resource.mem`. It is only applied to YARN and Mesos clusters but not to standalone cluster. It's necessary to setup a default heap size to control the memory resource consumed by the worker's JVM.
In addition, https://github.com/Alluxio/alluxio/pull/3557 is used to fix the memory "leak" caused by the use of MappedByteBuffer.
> [ALLUXIO-2015] Allocate a default heap size for workers (standalone cluster)

- core/client/src/main/java/alluxio/hadoop/AbstractFileSystem.java
the method name is "getScheme()", however the javadoc uses schema,can I change it?
> [SMALLFIX]improve javadoc

- core/common/src/test/java/alluxio/AlluxioTestDirectory.java
- minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java
If we don't specify that we want it to use our temporary tests folder as its work directory, it will create a "TIMESTAMP-0" directory in the java temp directory.
> [SMALLFIX] Clean up temporary zookeeper directory

- tests/src/test/java/alluxio/master/lineage/LineageMasterIntegrationTest.java
The current timeout makes it hard to tell whether the build
node is running slowly, or an actual deadlock has occurred.
> [SMALLFIX] Increase test timeout

- docs/_includes/Configuring-Alluxio-with-GlusterFS/glusterfs-file.md
- docs/_includes/Configuring-Alluxio-with-GlusterFS/underfs-address.md
- docs/_includes/Configuring-Alluxio-with-NFS/nfs-file.md
- docs/_includes/Configuring-Alluxio-with-NFS/underfs-address.md
- docs/en/Configuring-Alluxio-with-GlusterFS.md
- docs/en/Configuring-Alluxio-with-NFS.md
Rename the mount point to be more obviously a mount point since `vol` can mean something else.
> [DOCFIX] Clarify mounting in gluster/nfs docs
