Alluxio/alluxio

tests/src/test/java/alluxio/master/file/ConcurrentFileSystemMasterSetTtlTest.java
=> [SMALLFIX] Issue23: Rename ConcurrentFileSystemMasterSetTtlTest.java to ConcurrentSetTtlIntegrationTest.java

core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
Improve core/client/fs/src/main/java/alluxio/client/file/FileInStream.java as mStatus can be marked as final.
Change
protected URIStatus mStatus;
to
protected final URIStatus mStatus;
=> [SMALLFIX]Change protected URIStatus mStatus to protected final URIStatus mStatus 

tests/src/test/java/alluxio/master/JournalShutdownIntegrationTest.java
=> [SMALLFIX] Issue31: Update comment in JournalShutdownIntegrationTest.java

core/common/src/main/java/alluxio/PropertyKey.java
https://alluxio.atlassian.net/browse/ALLUXIO-6286
=> [ALLUXIO-6286] modify core/common/src/main/java/alluxio/PropertyKey.java

core/common/src/test/java/alluxio/retry/CountingRetryTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2663
Make CountingRetryTest final. V2
=> [ALLUXIO-2663]

core/common/src/main/java/alluxio/underfs/UnderFileSystem.java, pom.xml, underfs/hdfs/pom.xml, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java, underfs/pom.xml, underfs/wasb/pom.xml, underfs/wasb/src/main/java/alluxio/underfs/wasb/WasbUnderFileSystem.java, underfs/wasb/src/main/java/alluxio/underfs/wasb/WasbUnderFileSystemFactory.java, underfs/wasb/src/main/resources/META-INF/services/alluxio.underfs.UnderFileSystemFactory, underfs/wasb/src/test/java/alluxio/underfs/wasb/WasbUnderFileSystemContractTest.java, underfs/wasb/src/test/java/alluxio/underfs/wasb/WasbUnderFileSystemFactoryTest.java, underfs/wasb/src/test/resources/log4j.properties
https://alluxio.atlassian.net/browse/ALLUXIO-3044
=> [ALLUXIO-3044] Add wasb as a top-level UFS

assembly/server/pom.xml, pom.xml, underfs/gcs/pom.xml, underfs/hdfs/pom.xml, underfs/local/pom.xml, underfs/oss/pom.xml, underfs/pom.xml, underfs/s3a/pom.xml, underfs/swift/pom.xml, underfs/wasb/pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-3044
=> [ALLUXIO-3044] Use classload for all core UFS connectors

tests/src/test/java/alluxio/cli/fs/AbstractAlluxioShellTest.java
=> [SMALLFIX] fix imports

core/server/master/src/main/java/alluxio/underfs/MasterUfsManager.java
=> [SMALLFIX] Issue23: Improve javadoc for MasterUfsManager

core/common/src/main/java/alluxio/underfs/options/FileLocationOptions.java
=> [SMALLFIX]Correct javadoc reference in FileLocationOptions.java #70

tests/src/test/java/alluxio/master/block/BlockMasterJournalIntegrationTest.java
[SMALLFIX]Use static imports for standard test utilities for class BlockMasterJournalIntegrationTest
=> [SMALLFIX]Use static imports for standard test utilities for class BlockMasterJournalIntegrationTest

docs/cn/Configuring-Alluxio-with-HDFS.md
docs/cn/Configuring-Alluxio-with-HDFS.md
=> [DOCFIX] docs/cn/Configuring-Alluxio-with-HDFS.md

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/underfs/UnderFileSystemConfiguration.java, core/common/src/test/java/alluxio/PropertyKeyTest.java, docs/en/Configuring-Alluxio-with-Azure-Blob-Store.md, underfs/wasb/src/main/java/alluxio/underfs/wasb/WasbUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-3044
- Improve the code to set Azure credential (changing `core-site.xml` is no more required)
- Update the doc---the steps are much simplified now
I have verified my change and doc locally.
=> [ALLUXIO-3044] Update Wasb integration doc and improve how to set Wasb credential

core/server/worker/src/main/java/alluxio/worker/netty/AbstractReadHandler.java
[SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class AbstractReadHandler
=> [SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class AbstractReadHandler

core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java, core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java, underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Conflict resolved in last commit
=> [MERGE] Merge 1.6

core/client/runtime/pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-3040
Tested with Hadoop and Spark
=> [ALLUXIO-3040] Shade runtime client jar: no profiles are required

docs/en/Running-Hive-with-Alluxio.md
- Clarify whether to set Alluxio as default fs
- Word tuning
This PR is motivated by [a mailing list question](https://groups.google.com/forum/#!topic/alluxio-users/ehkVIcyyfdA)
=> [DOCFIX] Improve Hive integration doc 

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java, tests/src/test/java/alluxio/master/file/CheckConsistencyIntegrationTest.java
(https://alluxio.atlassian.net/browse/ALLUXIO-2904)
=> [ALLUXIO-2904]add mode owner group check on checkConsistency

docs/cn/Configuring-Alluxio-with-Azure-Blob-Store.md
docs/cn/Configuring-Alluxio-with-Azure-Blob-Store.md
=> [DOCFIX] docs/cn/Configuring-Alluxio-with-Azure-Blob-Store.md

.gitignore, core/client/runtime/pom.xml, dev/scripts/generate-tarball.sh, docs/_config.yml, docs/en/Building-Alluxio-Master-Branch.md, docs/en/Running-Flink-on-Alluxio.md, docs/en/Running-HBase-on-Alluxio.md, docs/en/Running-Hadoop-MapReduce-on-Alluxio.md, docs/en/Running-Hive-with-Alluxio.md, docs/en/Running-Presto-with-Alluxio.md, docs/en/Running-Spark-on-Alluxio.md, pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-3040
=> [ALLUXIO-3040] Update scripts and docs to remove per-compute build profiles

core/common/src/main/java/alluxio/util/LogUtils.java
Improve setLogLevel method in core/common/src/main/java/alluxio/util/LogUtils.java
=> [SMALLFIX]Improve setLogLevel method in core/common/src/main/java/alluxio/util/LogUtils.java

core/server/worker/src/main/java/alluxio/worker/block/allocator/GreedyAllocator.java
[SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class GreedyAllocator
=> [SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class GreedyAllocator

core/common/src/main/java/alluxio/wire/FileInfo.java
core/common/src/main/java/alluxio/wire/FileInfo.java
=> [SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class FileInfo

core/common/src/main/java/alluxio/cli/CommandUtils.java
=> [SMALLFIX]Deprecate Throwables.propagate with RuntimeException in CommandUtils.java

core/common/src/main/java/alluxio/wire/BlockLocation.java
Supply the name of variable to Preconditions.checkNotNull
=> [SMALLFIX] Supply the name of variable to Preconditions.checkNotNull

core/server/worker/src/main/java/alluxio/worker/block/BlockStore.java
=>  [SMALLFIX] Correct Javadoc in BlockStore.java

docs/_data/table/en/operation-command.yml
=> [SMALLFIX]Update wording for leader command in docs/_data/table/en/operation-command.yml#95

core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
=> [SMALLFIX]Java 8 Improvement: replace anonymous type with lambda in alluxio.client.file.RetryHandlingFileSystemMasterClient#checkConsistency

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
for the issues [#140](https://github.com/Alluxio/new-contributor-tasks/issues/140)
=> [SMALLFIX]Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.DefaultFileSystemMaster.Metrics#registerGauges #140

core/common/src/main/java/alluxio/PropertyKey.java
=> [SMALLFIX]update the PropertyKey.java

core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
finish the update in core/client/fs/src/main/java/alluxio/client/RetryHandlingMetaMasterClient.java
of retryRPC  function
=> [SMALLFIX]Replace anonymous type with lambda 

core/server/worker/src/main/java/alluxio/SessionInfo.java
In alluxio/SessionInfo.java, line 27, change
private int mSessionTimeoutMs;
to
private final int mSessionTimeoutMs;
=> [SMALLFIX]Change variable type of 'mSessionTimeoutMs'(private int->private final int)

docs/en/Configuring-Alluxio-with-Minio.md
=> [SMALLFIX]Improve s3a:// scheme in docs/en/Configuring-Alluxio-with-Minio.md

docs/cn/Building-Alluxio-Master-Branch.md
[DOCFIX]Update docs/cn/Building-Alluxio-Master-Branch.md
=> [DOCFIX]Update docs/cn/Building-Alluxio-Master-Branch.md

docs/cn/Running-HBase-on-Alluxio.md
docs/cn/Running-HBase-on-Alluxio.md
=> [DOCFIX] docs/cn/Running-HBase-on-Alluxio.md

docs/cn/Running-Spark-on-Alluxio.md
docs/cn/Running-Spark-on-Alluxio.md
=> [DOCFIX] docs/cn/Running-Spark-on-Alluxio.md

docs/cn/Running-Flink-on-Alluxio.md
English version is /docs/en/Running-Flink-on-Alluxio.md
=> [DOCFIX] Translate chinese verison of revised part in Running-Flink-on-Alluxio.md

docs/en/Configuring-Alluxio-with-Azure-Blob-Store.md
=> [SMALLFIX] Add a missing period to docs/en/Configuring-Alluxio-with-Azure-Blob-Store.md

docs/cn/Running-Hadoop-MapReduce-on-Alluxio.md
[DOCFIX]Update docs/cn/Running-Hadoop-MapReduce-on-Alluxio.md
=> [DOCFIX]Update docs/cn/Running-Hadoop-MapReduce-on-Alluxio.md

core/common/src/main/java/alluxio/Configuration.java, core/common/src/test/java/alluxio/ConfigurationTest.java
=> [SMALLFIX] Trim whitespace for keys values set in site-properties

tests/src/test/java/alluxio/master/AlluxioMasterRestApiTest.java
Use static imports for standard test utilities for AlluxioMasterRestApiTest
=> [SMALLFIX] Use static imports for standard test utilities for AlluxioMasterRestApiTest

docs/cn/Running-Presto-with-Alluxio.md
English version /docs/en/Running-Presto-with-Alluxio.md
=> [DOCFIX]Translate chinese verison of revised part in Running-Presto-with-Alluxio.md

core/server/worker/src/main/java/alluxio/worker/block/allocator/Allocator.java
change Preconditions.checkNotNull(view) to Preconditions.checkNotNull(view, "view"), 有个逗号
=> [SMALLFIX] change Preconditions.checkNotNull(view) to Preconditions.checkNotNull(view, "view")

core/common/src/test/java/alluxio/util/JvmPauseMonitorTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3059
=> [ALLUXIO-3059] Ignore JVM pause monitor test

core/server/common/src/main/java/alluxio/master/journalv0/JournalFormatter.java
https://github.com/Alluxio/new-contributor-tasks/issues/115
=> [SMALLFIX] Deprecate Throwables.propagate with RuntimeException in JournalFormatter.java(issue115)

docs/cn/Running-Alluxio-Fault-Tolerant.md
=> [SMALLFIX]fix configuration in Running-Alluxio-Fault-Tolerant.md

core/common/pom.xml, core/common/src/test/java/alluxio/wire/AlluxioMasterInfoTest.java, core/common/src/test/java/alluxio/wire/AlluxioProxyInfoTest.java, core/common/src/test/java/alluxio/wire/AlluxioWorkerInfoTest.java, core/common/src/test/java/alluxio/wire/BlockInfoTest.java, core/common/src/test/java/alluxio/wire/BlockLocationTest.java, core/common/src/test/java/alluxio/wire/CapacityTest.java, core/common/src/test/java/alluxio/wire/CommandLineJobInfoTest.java, core/common/src/test/java/alluxio/wire/FileBlockInfoTest.java, core/common/src/test/java/alluxio/wire/FileInfoTest.java, core/common/src/test/java/alluxio/wire/JobConfInfoTest.java, core/common/src/test/java/alluxio/wire/LineageInfoTest.java, core/common/src/test/java/alluxio/wire/MountPointInfoTest.java, core/common/src/test/java/alluxio/wire/WorkerInfoTest.java, core/common/src/test/java/alluxio/wire/WorkerNetAddressTest.java, pom.xml, underfs/swift/pom.xml, underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-3061
=> [ALLUXIO-3061] Upgrade to Jackson 2

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
=> [SMALLFIX]replace anonymous type

core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
[SMALLFIX]Java 8 Improvement: replace anonymous type with lambda in alluxio.client.file.RetryHandlingFileSystemMasterClient#getMountTable #150
=> [SMALLFIX]Java 8 Improvement: replace anonymous type with lambda in alluxio.client.file.RetryHandlingFileSystemMasterClient#getMountTable #150

keyvalue/client/src/main/java/alluxio/client/keyvalue/KeyValuePartitionWriter.java
keyvalue/client/src/main/java/alluxio/client/keyvalue/KeyValuePartitionWriter.java
=> [SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class KeyValuePartitionWriter

keyvalue/client/src/main/java/alluxio/client/keyvalue/KeyValueStoreIterator.java
[SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class KeyValueStoreIterator
=> [SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class KeyValueStoreIterator

core/server/master/src/main/java/alluxio/master/file/meta/FileSystemMasterView.java
[SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class FileSystemMasterView
=> [SMALLFIX]Supply the variable name to Preconditions.checkNotNull for class FileSystemMasterView

core/common/src/main/java/alluxio/util/IdUtils.java, core/server/worker/src/main/java/alluxio/Sessions.java, core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
https://alluxio.atlassian.net/browse/ALLUXIO-3065
=> [ALLUXIO-3065] Use internal session id for evicting blocks

docs/en/Powered-By-Alluxio.md
Add ZTE and Ceph info in Powered-By-Alluxio.md
=> [DOCFIX] Add ZTE and Ceph info in Powered-By-Alluxio.md

docs/_data/table/en/operation-command.yml
Update
"Display the size of a file or a directory specified by the input path."
to
"Display the size of the file or a directory specified by the input path."
=> [SMALLFIX]Update wording for du command in docs/_data/table/en/operation-command.yaml

docs/cn/Getting-Started.md
Translate some English words into Chinese
=> [DOCFIX] Translate some English words into Chinese

keyvalue/client/src/main/java/alluxio/client/keyvalue/BaseKeyValueStoreWriter.java
Supply the variable name to Preconditions.checkNotNull in BaseKeyValueStoreWriter.java
=> [SMALLFIX] Supply the variable name to Preconditions.checkNotNull in BaseKeyValueStoreWriter.java

core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java
add final in alluxio/worker/block/BlockMasterSync.java
=> [SMALLFIX]Add final in alluxio/worker/block/BlockMasterSync.java

docs/cn/Running-Alluxio-Fault-Tolerant.md
修改：      docs/cn/Running-Alluxio-Fault-Tolerant.md
in the second paragraph.自动从可用的备 用master中选举一个作为新的leader,这句话前面添加了 系统 二字.
=> [DocFix]Update Chinese doc Running-Alluxio-Fault-Tolerant.md

core/server/master/src/test/java/alluxio/master/file/meta/AsyncUfsAbsentPathCacheTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2942
=> [ALLUXIO-2942] Simplify logic in AsyncUfsAbsentPathCacheTest.java

docs/cn/Contributing-to-Alluxio.md
[DOCFIX]Update docs/cn/Contributing-to-Alluxio.md
=> [DOCFIX]Update docs/cn/Contributing-to-Alluxio.md

core/client/fs/src/test/java/alluxio/client/block/options/LockBlockOptionsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-873
=> [ALLUXIO-873] Add Unit Tests for the Block package

core/server/master/src/main/java/alluxio/master/file/meta/TtlBucket.java
This PR reverts changes in https://github.com/Alluxio/alluxio/pull/6513 and adds a comment explaining why those changes should not be done.
=> [SMALLFIX] Fix ttl tests

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java, core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java, core/client/fs/src/main/java/alluxio/client/block/stream/BlockOutStream.java, core/client/fs/src/main/java/alluxio/client/block/stream/UnderFileSystemFileOutStream.java, core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java, core/client/fs/src/main/java/alluxio/client/file/policy/LocalFirstAvoidEvictionPolicy.java, core/client/fs/src/main/java/alluxio/client/file/policy/LocalFirstPolicy.java, core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java, core/client/fs/src/test/java/alluxio/client/block/stream/BlockOutStreamTest.java, core/client/fs/src/test/java/alluxio/client/block/stream/TestBlockInStream.java, core/client/fs/src/test/java/alluxio/client/block/stream/TestBlockOutStream.java, core/client/fs/src/test/java/alluxio/client/block/stream/TestUnderFileSystemFileOutStream.java, core/client/fs/src/test/java/alluxio/client/file/FileInStreamTest.java, core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java, core/client/fs/src/test/java/alluxio/client/file/policy/LocalFirstAvoidEvictionPolicyTest.java, core/client/fs/src/test/java/alluxio/client/file/policy/LocalFirstPolicyTest.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/network/TieredIdentityFactory.java, core/common/src/main/java/alluxio/wire/TieredIdentity.java, core/common/src/main/java/alluxio/wire/WorkerNetAddress.java, core/common/src/test/java/alluxio/PropertyKeyTest.java, core/common/src/test/java/alluxio/wire/TieredIdentityTest.java, core/server/worker/src/main/java/alluxio/worker/WorkerProcess.java, keyvalue/hadoop/src/main/java/alluxio/hadoop/mapreduce/KeyValueInputSplit.java, shell/src/main/java/alluxio/cli/LogLevel.java, tests/src/test/java/alluxio/master/MasterFaultToleranceIntegrationTest.java, tests/src/test/java/alluxio/network/LocalFirstPolicyIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3060
This PR completes the code-side changes for Tiered Locality. The next PR will contain documentation updates.
Changes:
- Consolidate LocalFirstAvoidEvictionPolicy into LocalFirstPolicy.
- Use Tiered Locality for block store locality decisions.
=> [ALLUXIO-3060] Implement remaining tiered locality functionality

docs/_data/table/en/operation-command.yml
https://alluxio.atlassian.net/browse/ALLUXIO-1118
Update
"Change the group of the directory or file."
to
"Change the group of a file or directory."
=> [ALLUXIO-1118]Update wording for chgrp command in docs/_data/table/en/operation-command.yml

docs/_layouts/global.html, docs/cn/Remote-Logging.md
Gets rid of the warnings when starting the jekyll server.
=> [SMALLFIX] Clean up doc site generation

docs/cn/Powered-By-Alluxio.md
Add ZTE and Ceph info in Powered-By-Alluxio.md cn version
Forgot to push cn version in #6516 , sorry about that.
=> [DOCFIX] Add ZTE and Ceph info in Powered-By-Alluxio.md cn version

core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
https://github.com/Alluxio/new-contributor-tasks/issues/156
=> [ALLUXIO-156]modified function scheduleAsyncPersist

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
=> [SMALLFIX]Explicit type can be replaced

core/client/fs/src/main/java/alluxio/client/file/policy/LocalFirstPolicy.java
…e String mLocalHostName; to private final String mLocalHostName;
=> [SMALLFIX]modify alluxio/client/file/policy/LocalFirstPolicy.java change 'private String mLocalHostName;' to 'private final String mLocalHostName;'

docs/en/Tiered-Locality.md
https://alluxio.atlassian.net/browse/ALLUXIO-3060
=> [ALLUXIO-3060] Add doc for tiered locality

core/common/src/test/java/alluxio/AuthenticatedUserRuleTest.java
Use static imports for standard test utilities in AuthenticatedUserRuleTest.java
=> [SMALLFIX] Use static imports for standard test utilities in AuthenticatedUserRuleTest.java

docs/en/Running-Spark-on-Alluxio.md
Added a section in doc to help user running into exception with using Alluxio with Spark on YARN.
=> [DOCFIX] Add issue resolution doc for running Spark on Yarn with Alluxio

core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java, core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java, core/common/src/main/java/alluxio/AbstractClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-2946
=> [ALLUXIO-2946] Throw more fine-grained exceptions in RPC client calls

core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
Remove
import alluxio.thrift.UfsInfo;
=> [SMALLFIX]Remove unused import in AbstractUfsManager.java 

core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java, core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
To follow our method naming conventions.
=> Update BlockInStream method name.

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
@calvinjia 
Could you take a look? Thanks!
=> [SMALLFIX] Set classloader for HdfsUnderFileSystem

README.md
=> [SMALLFIX] Update README.

docs/en/Java-Setup.md
https://alluxio.atlassian.net/browse/ALLUXIO-2936
=> [ALLUXIO-2936] Add missing period in Java-Setup

docs/cn/index.md
[DOCFIX]Update docs/cn/index.md
=> [DOCFIX]Update docs/cn/index.md

docs/en/Logging-Conventions.md
Make it explicit on how to enable client-side logging.
=> [DOCFIX] Tips for client-side logging

docs/_includes/Command-Line-Interface/rm.md
Now,' /data/2014*' is  in quotes
=> [DOCFIX] add quotes in docs/_includes/Command-Line-Interface/rm.md 

docs/cn/Configuration-Properties.md, docs/css/main.css, docs/en/Configuration-Properties.md
Also fix styles so clicking an anchor also considers the header height.
=> [DOCFIX] Make configuration properties bookmarkable, by adding anchors.

core/server/worker/src/main/java/alluxio/worker/file/FileDataManager.java
=> [SMALLFIX]Improve comment style in FileDataManager

core/server/common/src/test/java/alluxio/master/journal/AsyncJournalWriterTest.java
[SMALLFIX]Use static imports for standard test utilities for class AsyncJournalWriterTest
=> [SMALLFIX]Use static imports for standard test utilities for class AsyncJournalWriterTest

docs/cn/Running-Alluxio-On-Kubernetes.md
[DOCFIX]Create docs/cn/Running-Alluxio-On-Kubernetes.md
=> [DOCFIX]Create docs/cn/Running-Alluxio-On-Kubernetes.md

docs/cn/Architecture.md
Modify chinese version of Architecture.md corresponding to revised English version
=> [DOCFIX] Modify docs/cn/Architecture.md

docs/cn/Running-Spark-on-Alluxio.md
Use alluxio-site.prorperties instead of alluxio-env.sh
=> [DOCFIX] Update docs/cn/Running-Spark-on-Alluxio.md

docs/cn/Running-Alluxio-Fault-Tolerant.md
[DOCFIX]Update docs/cn/Running-Alluxio-Fault-Tolerant.md
=> [DOCFIX]Update docs/cn/Running-Alluxio-Fault-Tolerant.md

docs/cn/Configuring-Alluxio-with-secure-HDFS.md
Modify the cn/Configuring-Alluxio-with-secure-HDFS.md corresponding to latest two commits in en/Configuring-Alluxio-with-secure-HDFS.md
=> [DOCFIX] Update docs/cn/Configuring-Alluxio-with-secure-HDFS.md

docs/cn/Remote-Logging.md
[DOCFIX]Update docs/cn/Remote-Logging.md
=> [DOCFIX]Update docs/cn/Remote-Logging.md

core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java, core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java, core/common/src/main/java/alluxio/underfs/UnderFileSystem.java, core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java, core/common/src/test/java/alluxio/underfs/AbstractUnderFileSystemContractTest.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java, underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-3063
=> [ALLUXIO-3063] Optimize retrieval of ufs status

core/common/src/main/java/alluxio/exception/status/AlluxioStatusException.java, core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
Added a couple improvements related to safe mode:
- Move safe mode entrance to a common code path executed by both `AlluxioMasterProcess` and `FaultTolerantAlluxioMasterProcess`. This makes safe mode kick in for fault tolerant mode as well.
- Make `AlluxioStatusException .fromCheckedException` handle pass through of `AlluxioStatusException` so master REST APIs returns the correct status for `UnavailableException` instead of an unknown error.
=> [SMALLFIX] Safe Mode Improvements

core/server/common/src/main/java/alluxio/cli/ValidateEnv.java, core/server/common/src/main/java/alluxio/cli/validation/AbstractValidationTask.java, core/server/common/src/main/java/alluxio/cli/validation/HdfsValidationTask.java, core/server/common/src/main/java/alluxio/cli/validation/SecureHdfsValidationTask.java, core/server/common/src/main/java/alluxio/cli/validation/ValidationTask.java
@aaudiber This should solve your issue.
@bf8086 Could you take a look at this PR? Thanks!
=> [SMALLFIX] Skip HDFS configuration check if UFS is not HDFS.

core/common/src/test/java/alluxio/cli/AbstractShellTest.java
=> [SMALLFIX] Use static imports for standard test utilities in class AbstractShellTest

docs/cn/Architecture.md, docs/cn/Tiered-Locality.md
=> [DOCFIX] Fix some hash key and typos

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/test/java/alluxio/PropertyKeyTest.java, shell/src/main/java/alluxio/cli/ConfigurationDocGenerator.java, underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Added a workaround for S3 compatible UFS with no bulk delete support.
=> [SMALLFIX] workaround bulk delete limitation

docs/cn/Clients-Hadoop.md
[DOCFIX]Update docs/cn/Clients-Hadoop.md
=> [DOCFIX]Update docs/cn/Clients-Hadoop.md

core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectory.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeFile.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java, deploy/vagrant/conf/alluxio.yml, docs/en/Logging-Conventions.md, docs/en/Running-Presto-with-Alluxio.md, integration/docker/Dockerfile
=> [MERGE] Merge 1.6 to 1.7

core/common/src/main/java/alluxio/PropertyKey.java, docs/en/Running-Alluxio-on-Mesos.md, integration/mesos/src/main/java/alluxio/mesos/AlluxioScheduler.java
The site-properties change is a consequence of exclusive alluxio-env properties introduced recently
=> [SMALLFIX] Update mesos integration jdk

core/server/common/src/main/java/alluxio/cli/extensions/command/InstallCommand.java, dev/scripts/generate-tarball.sh
Create extensions directory if does not exist
=> [SMALLFIX] Fix bug when extensions directory is not present

core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
@aaudiber Could you PTAL? Thanks!
=> [SMALLFIX] Remove duplicate import.

docs/en/Configuring-Alluxio-with-MapR-FS.md
=> [DOCFIX] Update maprfs docs

deploy/vagrant/provision/roles/common/files/java.sh, docs/en/Running-Alluxio-on-GCE.md
=> [SMALLFIX] Update Alluxio on GCE docs

docs/_data/table/en/ReadType.yml, docs/en/Clients-Alluxio-Java.md
Partial caching is now always available.
=> [DOCFIX] Update read type documentation.

core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java, shell/src/main/java/alluxio/cli/fs/command/CpCommand.java, tests/src/test/java/alluxio/cli/fs/command/CpCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3084
=> [ALLUXIO-3084] CopyFromLocal creates an empty file if an error occurs

core/server/worker/src/test/java/alluxio/worker/block/UfsInputStreamManagerTest.java
Cherry-pick https://github.com/Alluxio/alluxio/pull/6703
=> [SMALLFIX] Deflake test 1.7

docs/en/Running-Alluxio-Yarn-Standalone.md
The information is about the same, but now the doc is more succinct and clear.
=> [DOCFIX] Yarn standalone doc update

docs/en/Running-Presto-with-Alluxio.md
=> [DOCFIX] Update presto version

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
Updated java doc for Jira ticket # [ALLUXIO-2953](https://alluxio.atlassian.net/browse/ALLUXIO-2953)
=> [ALLUXIO-2953] Update javadoc ObjectUnderFileSytem#createEmptyObject

core/server/master/src/main/java/alluxio/master/block/BlockMasterClientServiceHandler.java, core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMasterWorkerServiceHandler.java
Example debug log before this fix
```
2018-01-12 10:55:54,709 DEBUG FileSystemMasterWorkerServiceHandler - Enter: alluxio.master.file.FileSystemMasterWorkerServiceHandler$3@3bc04677
2018-01-12 10:55:54,711 DEBUG FileSystemMasterWorkerServiceHandler - Enter: alluxio.master.file.FileSystemMasterWorkerServiceHandler$1@64564270
2018-01-12 10:55:54,711 DEBUG FileSystemMasterWorkerServiceHandler - Exit (OK): alluxio.master.file.FileSystemMasterWorkerServiceHandler$3@3bc04677
2018-01-12 10:55:54,712 DEBUG TSaslTransport - writing data length: 41
2018-01-12 10:55:54,718 DEBUG FileSystemMasterWorkerServiceHandler - Exit (OK): alluxio.master.file.FileSystemMasterWorkerServiceHandler$1@64564270
2018-01-12 10:55:54,719 DEBUG BlockMasterWorkerServiceHandler - Enter: …
```
=> [SMALLFIX] Fix RPC logging on block and filesystem master

core/server/master/src/test/java/alluxio/master/file/meta/TtlBucketTest.java
Improved JavaDoc for issue # [ALLUXIO-2944](https://alluxio.atlassian.net/browse/ALLUXIO-2944)
=> [ALLUXIO-2944] Improved javadoc in TtlBucketTest.java

docs/en/Running-HBase-on-Alluxio.md
[DOCFIX] docfix in docs/en/Running-HBase-on-Alluxio.md
=> [DOCFIX] docfix in docs/en/Running-HBase-on-Alluxio.md

core/common/src/main/java/alluxio/AlluxioURI.java, core/common/src/main/java/alluxio/StandardURI.java, core/common/src/test/java/alluxio/AlluxioURITest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3082
=> [ALLUXIO-3082] "bin/alluxio fs ls ." produces weird output

core/common/src/test/java/alluxio/util/io/FileUtilsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3093
=> [ALLUXIO-3093] Fix tests to work when using sudo

core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java, core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java, core/server/worker/src/main/java/alluxio/worker/block/RemoteBlockReader.java
Otherwise blocks only in Alluxio will not be fetched.
=> [SMALLFIX] Use the correct blocksize in async cache

bin/alluxio
@aaudiber 
Can you PTAL? Thanks!
=> [SMALLFIX] Fix an inaccurate print message during shutdown.

docs/cn/Running-Presto-with-Alluxio.md
[DOCFIX]Update docs/cn/Running-Presto-with-Alluxio.md
=> [DOCFIX]Update docs/cn/Running-Presto-with-Alluxio.md

docs/cn/Running-Alluxio-Locally.md
[DOCFIX]Update docs/cn/Running-Alluxio-Locally.md
=> [DOCFIX]Update docs/cn/Running-Alluxio-Locally.md

docs/cn/Admin-CLI.md
[DOCFIX]Update docs/cn/Admin-CLI.md
=> [DOCFIX]Update docs/cn/Admin-CLI.md

docs/cn/Configuring-Alluxio-with-Azure-Blob-Store.md
Update docs/cn/Configuring-Alluxio-with-Azure-Blob-Store.md
=> [DOCFIX] Update docs/cn/Configuring-Alluxio-with-Azure-Blob-Store.md

docs/cn/Configuring-Alluxio-with-MapR-FS.md
Update docs/cn/Configuring-Alluxio-with-MapR-FS.md
=> [SMALLFIX] Update docs/cn/Configuring-Alluxio-with-MapR-FS.md

tests/src/test/java/alluxio/client/FileSystemIntegrationTest.java
(https://alluxio.atlassian.net/browse/ALLUXIO-2934)
=> [ALLUXIO-2934]Modify javaDoc

docs/cn/Running-Alluxio-Yarn-Integration.md
[DOCFIX]Update docs/cn/Running-Alluxio-Yarn-Integration.md
=> [DOCFIX]Update docs/cn/Running-Alluxio-Yarn-Integration.md

core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java, core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java, core/common/src/test/java/alluxio/RedirectOutputRule.java, core/common/src/test/java/alluxio/SystemErrRule.java, core/common/src/test/java/alluxio/SystemErrRuleTest.java, core/common/src/test/java/alluxio/util/network/NetworkAddressUtilsTest.java, shell/src/main/java/alluxio/cli/fs/command/LeaderCommand.java, tests/src/test/java/alluxio/cli/fs/AbstractAlluxioShellTest.java, tests/src/test/java/alluxio/cli/fs/command/LeaderCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3083
=> [ALLUXIO-3083] Ping leader in alluxio fs leader command

docs/en/UFSExtensions.md
https://alluxio.atlassian.net/browse/ALLUXIO-3090
=> [ALLUXIO-3090] Add OBS to the list of UFS extensions.

docs/en/Configuring-Alluxio-with-OBS.md, docs/en/Configuring-Alluxio-with-OSS.md
https://alluxio.atlassian.net/browse/ALLUXIO-3090
This PR adds documentation for integrating with Huawei OBS.
=> [ALLUXIO-3090] Add doc for Huawei OBS.

core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, tests/src/test/java/alluxio/hadoop/FileSystemIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3091
=> [ALLUXIO-3091] Fix NPE in AbstractFileSystem

docs/cn/UFSExtensions.md
[DOCFIX]Update docs/cn/UFSExtensions.md
=> [DOCFIX]Update docs/cn/UFSExtensions.md

docs/cn/Running-Alluxio-On-Docker.md
[DOCFIX]Update docs/cn/Running-Alluxio-On-Docker.md
=> [DOCFIX]Update docs/cn/Running-Alluxio-On-Docker.md

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, tests/src/test/java/alluxio/master/file/ConcurrentFileSystemMasterLoadMetadataTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3095
See ticket for details about the deadlock conditions
=> [ALLUXIO-3095] Fix deadlock when concurrently loading subdirectories

core/common/src/main/java/alluxio/exception/ExceptionMessage.java, docs/en/Command-Line-Interface.md, shell/src/main/java/alluxio/cli/fs/command/LsCommand.java, tests/src/test/java/alluxio/cli/fs/command/LsCommandIntegrationTest.java
[Jira](https://alluxio.atlassian.net/browse/ALLUXIO-3029)
Hi,
Wanted to check out the project and look a bit around. Then I found these tickets in jira and thought it;d be fun to solve one of them. 
Let me know if this is needed/needs improvement
=> [ALLUXIO-3029] shell ls sort option

docs/cn/Running-Alluxio-On-Docker.md
Update docs/cn/Running-Alluxio-On-Docker.md
=> [DOCFIX] Update docs/cn/Running-Alluxio-On-Docker.md

docs/cn/Configuring-Alluxio-with-OSS.md
Update docs/cn/Configuring-Alluxio-with-OSS.md
=> [DOCFIX] Update docs/cn/Configuring-Alluxio-with-OSS.md

docs/cn/Configuring-Alluxio-with-OBS.md
Add docs/cn/Configuring-Alluxio-with-OBS.md
=> [DOCFIX] Add docs/cn/Configuring-Alluxio-with-OBS.md

docs/cn/Running-Spark-on-Alluxio.md
[DOCFIX]Update docs/cn/Running-Spark-on-Alluxio.md
=> [DOCFIX]Update docs/cn/Running-Spark-on-Alluxio.md

docs/cn/Running-Presto-with-Alluxio.md
Update docs/cn/ Running-Presto-with-Alluxio.md
=> [DOCFIX] Update docs/cn/ Running-Presto-with-Alluxio.md

docs/cn/Running-Alluxio-On-Kubernetes.md
Update docs/cn/Running-Alluxio-On-Kubernetes.md
=> [DOCFIX] Update docs/cn/Running-Alluxio-On-Kubernetes.md

docs/cn/Running-Alluxio-on-a-Cluster.md
[DOCFIX]Update docs/cn/Running-Alluxio-on-a-Cluster.md
=> [DOCFIX]Update docs/cn/Running-Alluxio-on-a-Cluster.md

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/heartbeat/SleepingTimer.java, core/common/src/main/java/alluxio/time/ThreadSleeper.java, core/common/src/main/java/alluxio/util/CommonUtils.java, core/common/src/test/java/alluxio/clock/ManualClock.java
Javadoc improvements, do a better job of implementing `Clock` in `ManualClock`
=> [SMALLFIX] Minor improvements

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3101
=> [ALLUXIO-3101] Fix journaling of persist propagation

core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java, tests/src/test/java/alluxio/master/file/TtlIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3100
=> [ALLUXIO-3100] Avoid spurious errors when TTL hits deleted files

core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
https://alluxio.atlassian.net/browse/ALLUXIO-3102
=> [ALLUXIO-3102] Kill when serving fails

core/common/src/main/java/alluxio/underfs/AtomicFileOutputStream.java, core/common/src/main/java/alluxio/underfs/options/CreateOptions.java, core/common/src/main/java/alluxio/underfs/options/MkdirsOptions.java, core/common/src/test/java/alluxio/underfs/options/CreateOptionsTest.java, core/common/src/test/java/alluxio/underfs/options/MkdirsOptionsTest.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java, underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-3103
=> [ALLUXIO-3103] Selectively setOwner during mkdirs

core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java, core/server/worker/src/main/java/alluxio/worker/block/meta/StorageDirView.java, core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3089
=> [ALLUXIO-3089]change to ConcurrentHashSet to void endless-loop

core/common/src/main/java/alluxio/underfs/UnderFileSystem.java, core/common/src/main/java/alluxio/underfs/UnderFileSystemFactoryRegistry.java
https://alluxio.atlassian.net/browse/ALLUXIO-3104
=> [ALLUXIO-3104] Make factory caching optional

checker/bin/alluxio-checker.sh, checker/bin/mapreduce-checker.sh, checker/bin/spark-checker.sh, checker/pom.xml, checker/src/main/java/alluxio/checker/CheckerUtils.java, checker/src/main/java/alluxio/checker/CommonCheckerUtils.java, checker/src/main/java/alluxio/checker/MapReduceIntegrationChecker.java, checker/src/main/java/alluxio/checker/SparkIntegrationChecker.java, docs/en/Running-Hadoop-MapReduce-on-Alluxio.md, docs/en/Running-Spark-on-Alluxio.md
https://alluxio.atlassian.net/browse/ALLUXIO-3097
Do not support CDH, HDP currently.
=> [ALLUXIO-3097] MapReduce Integration Checker

core/common/src/main/java/alluxio/Configuration.java
Issue: https://alluxio.atlassian.net/browse/ALLUXIO-3108
=> [SMALLFIX] Load unrecognized properties to workaround Ufs extensions configuration issue

bin/alluxio-workers.sh
Cherry-picked from https://github.com/Alluxio/alluxio/pull/6892
=> [SMALLFIX] Fix script for paths with spaces (#6892)

docs/cn/Logging-Conventions.md
=> [DOCFIX]Modify the markdown format of doc

core/server/common/src/main/java/alluxio/cli/Format.java
https://alluxio.atlassian.net/browse/ALLUXIO-3107
=> [ALLUXIO-3107] Format should be like a master process

core/common/src/main/java/alluxio/PropertyKey.java, shell/src/main/java/alluxio/cli/GetConfKey.java
This reverts commit a85a730d6a3dda2898ba4192f706b52d80fa8501.
No longer needed after https://github.com/Alluxio/alluxio/pull/6889
=> [SMALLFIX] Revert Add OBS constants and property keys (#6877)

core/common/src/main/java/alluxio/AbstractClient.java, core/common/src/main/java/alluxio/Configuration.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/heartbeat/SleepingTimer.java, core/common/src/main/java/alluxio/retry/ExponentialTimeBoundedRetry.java, core/common/src/main/java/alluxio/retry/RetryPolicy.java, core/common/src/main/java/alluxio/retry/RetryUtils.java, core/common/src/main/java/alluxio/retry/TimeBoundedRetry.java, core/common/src/main/java/alluxio/time/Sleeper.java, core/common/src/main/java/alluxio/time/ThreadSleeper.java, core/common/src/main/java/alluxio/time/TimeContext.java, core/common/src/test/java/alluxio/clock/ManualClock.java, core/common/src/test/java/alluxio/heartbeat/SleepingTimerTest.java, core/common/src/test/java/alluxio/retry/ExponentialTimeBoundedRetryTest.java, core/common/src/test/java/alluxio/retry/RetryUtilsTest.java, core/common/src/test/java/alluxio/time/ManualSleeper.java, core/common/src/test/java/alluxio/time/ManualSleeperTest.java, core/server/worker/src/main/java/alluxio/worker/block/BlockStore.java, core/server/worker/src/main/java/alluxio/worker/block/BlockWorker.java, core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java, core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java, core/server/worker/src/main/java/alluxio/worker/block/evictor/AbstractEvictor.java, core/server/worker/src/main/java/alluxio/worker/block/evictor/Evictor.java, core/server/worker/src/main/java/alluxio/worker/block/evictor/GreedyEvictor.java, core/server/worker/src/main/java/alluxio/worker/block/evictor/LRFUEvictor.java, core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java, docs/en/Powered-By-Alluxio.md, pom.xml
Conflicts resolved in last commit
@yupeng9 to confirm his changes should merge to master
@madanadit to confirm his changes should merge to master
@calvinjia for overall review and sync resolutions
=> [MERGE] Merge 1.7

underfs/swift/src/main/java/alluxio/underfs/swift/SwiftOutputStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-2932
=> [ALLUXIO-2932] Improve comment style in SwiftOutputStream.java

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java, core/client/fs/src/main/java/alluxio/client/block/stream/NettyPacketReader.java, core/client/fs/src/main/java/alluxio/client/file/FileInStream.java, core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java, core/client/fs/src/test/java/alluxio/client/file/FileInStreamTest.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/exception/ExceptionMessage.java, core/common/src/main/java/alluxio/retry/CountingRetry.java, tests/src/test/java/alluxio/master/block/MultiWorkerIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3098
This is https://github.com/Alluxio/alluxio/pull/6870 retargeted to `branch-1.7`
=> [ALLUXIO-3098] Make client read recover from lost worker

core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2941
=> [ALLUXIO-2941] make createPath method in InodeTreeTest.java private.

core/common/src/main/java/alluxio/AbstractClient.java, core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java, core/common/src/main/java/alluxio/retry/CountingRetry.java, core/common/src/main/java/alluxio/retry/ExponentialBackoffRetry.java, core/common/src/main/java/alluxio/retry/RetryPolicy.java, core/common/src/main/java/alluxio/retry/RetryUtils.java, core/common/src/main/java/alluxio/retry/SleepingRetry.java, core/common/src/main/java/alluxio/retry/TimeBoundedRetry.java, core/common/src/main/java/alluxio/retry/TimeoutRetry.java, core/common/src/main/java/alluxio/retry/package-info.java, core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java, core/common/src/test/java/alluxio/retry/CountingRetryTest.java, core/common/src/test/java/alluxio/retry/ExponentialBackoffRetryTest.java, core/common/src/test/java/alluxio/retry/TimeoutRetryTest.java, core/server/common/src/main/java/alluxio/master/journal/MasterJournalContext.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java, core/server/worker/src/main/java/alluxio/worker/netty/BlockReadHandler.java, core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java, tests/src/test/java/alluxio/cli/fs/command/LeaderCommandIntegrationTest.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-3111
=> [ALLUXIO-3111] Improve RetryPolicy Interface

core/common/src/main/java/alluxio/underfs/options/OpenOptions.java, core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalReader.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-3115
=> [ALLUXIO-3115] Enable recoverLease for HDFS journal

core/server/common/src/main/java/alluxio/cli/ValidateEnv.java, core/server/common/src/main/java/alluxio/cli/validation/UfsSuperUserValidationTask.java
https://alluxio.atlassian.net/browse/ALLUXIO-3119
=> [ALLUXIO-3119] Add a new task to check super user privilege on HDFS under file system

core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
This is to fix extra client retry due to recent refactor of `RetryPolicy`.
=> [SMALLFIX] Fix client read retry count

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java, core/common/src/main/java/alluxio/retry/TimeBoundedRetry.java, core/common/src/main/java/alluxio/util/io/PathUtils.java, core/common/src/test/java/alluxio/AlluxioURITest.java, core/common/src/test/java/alluxio/retry/ExponentialTimeBoundedRetryTest.java, core/common/src/test/java/alluxio/util/io/PathUtilsTest.java, core/server/common/src/main/java/alluxio/cli/ValidateEnv.java, core/server/common/src/main/java/alluxio/cli/validation/UfsSuperUserValidationTask.java, core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalReader.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java, tests/src/test/java/alluxio/cli/fs/command/MkdirCommandIntegrationTest.java
The conflicts are resolved in the last commit.
=> [MERGE] Merge branch 1.7

core/common/src/main/java/alluxio/PropertyKey.java, core/server/common/src/main/java/alluxio/master/journal/MasterJournalContext.java, core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java, core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSystem.java, minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java, tests/src/test/java/alluxio/master/journal/ufs/RenameFailureJournalTest.java, tests/src/test/java/alluxio/underfs/delegating/DelegatingUnderFileSystem.java, tests/src/test/java/alluxio/underfs/delegating/DelegatingUnderFileSystemFactory.java
https://alluxio.atlassian.net/browse/ALLUXIO-3117
=> [ALLUXIO-3117] Retry failed renames

core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
In some extreme cases, UfsFactory.create was invoked multiple times on race to create the same ufs, and one of them will win but others will be discarded.
This adds logging from certain workloads. 
Fix this cosmetic issue.
=> [SMALLFIX] Prevent the same UfsFactory created multiple times on race

core/common/src/main/java/alluxio/PropertyKey.java, core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java, docs/en/Alluxio-Storage.md, tests/src/test/java/alluxio/client/IsolatedFileSystemIntegrationTest.java, tests/src/test/java/alluxio/master/block/MultiWorkerIntegrationTest.java, tests/src/test/java/alluxio/worker/block/meta/SpecificTierWriteIntegrationTest.java, tests/src/test/java/alluxio/worker/block/meta/TierPromoteIntegrationTest.java, tests/src/test/java/alluxio/worker/block/meta/TieredStoreIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3055
=> [ALLUXIO-3055] change async evictor as default evictor

core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Also, move some logs to DEBUG since they may be expected/normal cases.
=> [SMALLFIX] Avoid UFS syncing TO_BE_PERSISTED files

core/common/src/main/java/alluxio/underfs/Fingerprint.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/UfsSyncUtils.java, tests/src/test/java/alluxio/master/file/UfsSyncIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3123
=> [ALLUXIO-3123] Enable dir syncing for UFS sync

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
=> [SMALLFIX] Add mesos to distribution

core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3125
=> [ALLUXIO-3125] Fix unavailable ufs during recursive create

integration/mesos/src/main/java/alluxio/mesos/AlluxioFramework.java
https://alluxio.atlassian.net/browse/ALLUXIO-2108
=> [ALLUXIO-2108] Add support to publish AlluxioMaster WebUI url to mesos UI under alluxio framework

core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java, core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java, tests/src/test/java/alluxio/master/block/BlockMasterHeartbeatIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-818
=> [ALLUXIO-818] Clean up orphaned blocks on register.

core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java, core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java, core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java, tests/src/test/java/alluxio/master/block/BlockMasterHeartbeatIntegrationTest.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
=> [MERGE] 1.7 -> master

dev/scripts/src/alluxio.org/build-distribution/cmd/common.go
For the build distribution script, when -debug is turned on, this PR streams the output of the command being executed to stdout, so that developers can know what's going on instead of waiting without any indication of the progress.
=> [SMALLFIX] Stream dev scripts' command line outputs to stdout during debugging.

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
cherry-pick of #6885 to branch-1.7
=> [SMALLFIX] Improve error message (#6885)

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/UfsSyncUtils.java, tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3123
=> [ALLUXIO-3123] Fix journal for dir syncing

bin/alluxio-start.sh
https://alluxio.atlassian.net/browse/ALLUXIO-3126
=> [ALLUXIO-3126] Consistency with stopping services before starting them

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java
https://alluxio.atlassian.net/browse/ALLUXIO-3120
=> [ALLUXIO-3120] Fix issue where secondary deletes completed log 

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/util/CommonUtils.java, core/common/src/test/java/alluxio/util/CommonUtilsTest.java, underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSOutputStream.java, underfs/oss/src/main/java/alluxio/underfs/oss/OSSOutputStream.java, underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AOutputStream.java, underfs/swift/src/main/java/alluxio/underfs/swift/SwiftMockOutputStream.java
https://alluxio.atlassian.net/browse/ALLUXIO-3128
=> [ALLUXIO-3128] Allow temporary directories to be configurable.

core/server/common/src/main/java/alluxio/ProcessUtils.java
We want to see things like AssertionError, LinkageError, NoClassDefFoundError, etc
=> [SMALLFIX] Handle throwable

pom.xml, underfs/hdfs/pom.xml, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileOutputStream.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-3131
Introduce java comment preprocessor to avoid code duplication, while still interfacing with different HDFS client. Let me know what you think @calvinjia @aaudiber
=>  [ALLUXIO-3131] Support HDFS 3 as UFS

core/server/worker/src/main/java/alluxio/worker/block/SpaceReserver.java
backport https://github.com/Alluxio/alluxio/pull/6867
=> [SMALLFIX] Check the low watermark is smaller than the high watermark

docs/cn/Powered-By-Alluxio.md, docs/cn/Running-Alluxio-On-Kubernetes.md
Update Chinese documents
- docs/cn/Running-Alluxio-On-Kubernetes.md
- docs/cn/Powered-By-Alluxio.md
=> [DOCFIX] Update Chinese docs

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, tests/src/test/java/alluxio/master/file/ConcurrentFileSystemMasterLoadMetadataTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3095
Cherry-picked from master branch to 1.7 branch
=> [ALLUXIO-3095] Fix deadlock when concurrently loading subdirectories (#6848)

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java, core/server/master/src/main/java/alluxio/master/block/BlockMaster.java, core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java, core/server/master/src/main/java/alluxio/master/file/BlockIntegrityChecker.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java, tests/src/test/java/alluxio/master/block/BlockMasterIntegrityIntegrationTest.java
Need to use whitebox for unit test since this is not expected to happen under normal operation.
=> [SMALLFIX] Add an option to check FileSystem and BlockMaster integrity

core/common/src/main/java/alluxio/underfs/UfsDirectoryStatus.java, core/common/src/main/java/alluxio/underfs/UfsFileStatus.java, core/common/src/main/java/alluxio/underfs/UfsStatus.java, core/common/src/test/java/alluxio/underfs/UfsFileStatusTest.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, shell/src/main/java/alluxio/cli/fs/command/LsCommand.java, tests/src/test/java/alluxio/cli/fs/command/LsCommandIntegrationTest.java, tests/src/test/java/alluxio/master/file/FileSystemMasterIntegrationTest.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java, underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-3132
=> [ALLUXIO-3132] Sync file last modification time with UFS

core/common/src/main/java/alluxio/extensions/ExtensionsClassLoader.java
So format command is less chatty.
=> [SMALLFIX] Move extension class loader log to debug

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go, integration/yarn/bin/alluxio-yarn.sh
This updates the YARN integration to work with our new distribution tarball format.
=> [SMALLFIX] Update YARN to work with new tarball format

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java, core/server/master/src/main/java/alluxio/master/file/meta/UfsSyncUtils.java, tests/src/test/java/alluxio/master/file/UfsSyncIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3135
=> [ALLUXIO-3135] Allow ufs sync to have out-of-sync dirs, for mount points

docs/_includes/Common-Commands/download-alluxio.md, docs/_includes/Running-Alluxio-Locally/download-Alluxio-binary.md, docs/_includes/Running-Alluxio-on-a-Cluster/download-extract-Alluxio-tar.md, docs/en/Running-Alluxio-Yarn-Integration.md
It's no longer necessary to recompile.
=> [DOCFIX] Update yarn integration docs

checker/bin/hive-checker.sh, checker/bin/mapreduce-checker.sh, checker/src/main/java/alluxio/checker/CheckerUtils.java, checker/src/main/java/alluxio/checker/HiveIntegrationChecker.java, checker/src/main/java/alluxio/checker/MapReduceIntegrationChecker.java, checker/src/main/java/alluxio/checker/SparkIntegrationChecker.java
=> [SMALLFIX] fix integration checker bugs

core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientRestServiceHandler.java
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.FileSystemMasterClientRestServiceHandler#getServiceVersion #201
151220045 蒋雨霖
=> [SMALLFIX]Replace anonymous type with lambda

docs/cn/Running-Alluxio-on-EC2.md, docs/cn/Running-Alluxio-on-GCE.md, docs/cn/Running-Alluxio-on-Virtual-Box.md, docs/cn/Running-Alluxio-on-a-Cluster.md
update four files:  
1.  docs/en/Running-Alluxio-on-EC2.md
2.  docs/en/Running-Alluxio-on-GCE.md
3.  docs/en/Running-Alluxio-on-Virtual-Box.md
4.  docs/en/Running-Alluxio-on-a-Cluster.md
=> [DOCFIX] Update chinese doc

core/common/src/main/java/alluxio/util/ConfigurationUtils.java
This is Ruize Tang(ID: 151220100)'s small fix.
=> [SMALLFIX]Ruize Tang's small fix: Add @Nullable annotation.

core/server/master/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
=>  [SMALLFIX] CHANGE AlluxioMasterRestServiceHandler.java

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/RpcContext.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/test/java/alluxio/master/file/PermissionCheckerTest.java, core/server/master/src/test/java/alluxio/master/file/RpcContextTest.java, core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java, tests/src/test/java/alluxio/master/block/BlockMasterIntegrityIntegrationTest.java
This is a pure refactor, no functionality should be affected
=> [SMALLFIX] Use RpcContext to organize contexts during RPCs

core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
Use static imports for standard test utilities in alluxio.master.file.meta.InodeTreeTest.
=> [SMALLFIX] Change for InodeTreeTest

core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
replace anonymous type with lambda in alluxio.worker.AlluxioWorkerRestServiceHandler#getUptimeMs
=> [SMALLFIX] replace anonymous type with lambda in alluxio.worker.AlluxioWorkerRestServiceHandle

core/server/master/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
alluxio.master.file.AlluxioMasterRestServiceHandler#getConfiguration
=> [SMALLFIX]Java 8 Improvement: replace anonymous type with lambda in 

core/server/master/src/main/java/alluxio/master/lineage/LineageMasterClientServiceHandler.java
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.lineage.LineageMasterClientServiceHandler#reportLostFile #229
=> [SMALLFIX]Replace anonymous type with lambda in alluxio.master.lineage.LineageMasterClientServiceHandler

core/server/master/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
Replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#gatCapacityBytesOnTiers
=> [SMALLFIX] Change of AlluxioMasterRestServiceHandler.java

core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
replace anonymous type with lambda in alluxio.worker.AlluxioWorkerRestServiceHandler#getCapacityBytes
=> [SMALLFIX] replace anonymous type with lambda

core/common/src/main/java/alluxio/thrift/CompleteFileTResponse.java, docs/en/Security.md
Rephrase a sentence in docs/en/Security.md
=> [SMALLFIX] Rephrase a sentence in docs/en/Security.md #75

core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
[SMAILLFIX] Replace anonymous type with lambda in alluxio.worker.AlluxioWorkerRestServiceHandler#getStartTimeMs
=> [SMALLFIX] Replace anonymous type with lambda in alluxio.worker.AlluxioWorkerRestServiceHandler#getStartTimeMs

bin/alluxio
https://alluxio.atlassian.net/browse/ALLUXIO-3146
=> [ALLUXIO-3146] Fixed bin/alluxio copyDir failure on Mac

core/common/src/main/java/alluxio/metrics/MetricsConfig.java
This is a small fix to improve javadoc for MetricsConfig.
=> [SMALLFIX] improve javadoc for MetricsConfig

logserver/src/main/java/alluxio/logserver/AlluxioLogServerProcess.java
add dot(.) in the first line of java doc in AlluxioLogServerProcess.java
=> [SMALLFIX] update java doc in AlluxioLogServerProcess.java

core/server/master/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
fix in AlluxioMasterRestServiceHandler
=> [SMALLFIX]replace anonymous type with lambda in 

core/server/master/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
First homework for me is to using a lambda.
=> [SMALLFIX]Using a lambda

core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTierView.java
Supply the variable name to Preconditions.checkNotNull in alluxio.worker.block.meta.StorageTierView#StorageTierView
=> [SMALLFIX] Supply the variable name to Preconditions.checkNotNull in alluxio.worker.block.meta.StorageTierView#StorageTierView

core/server/worker/src/main/java/alluxio/worker/netty/UfsFileWriteHandler.java, core/server/worker/src/main/java/alluxio/worker/netty/UfsFileWriteRequestContext.java
https://alluxio.atlassian.net/browse/ALLUXIO-3152
=> [ALLUXIO-3152] Set correct owner for written ufs file

conf/metrics.properties.template, core/server/common/pom.xml, core/server/common/src/main/java/alluxio/metrics/sink/PrometheusMetricsServlet.java, core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java, pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-3148
This pull request adds a new Metrics servlet that formats the codahale metrics as [prometheus](https://prometheus.io/) metrics.
This contribution is entirely my own, done on my personal time and machine although it will be very useful during my office hours should it be merged.
Thanks for your attention!
=> [ALLUXIO-3148] PrometheusMetricsServlet

core/server/worker/src/main/java/alluxio/worker/netty/UfsFileWriteHandler.java, core/server/worker/src/main/java/alluxio/worker/netty/UfsFileWriteRequestContext.java
https://alluxio.atlassian.net/browse/ALLUXIO-3152
cherry-pick of #7070
=> [ALLUXIO-3152] Set correct owner for written ufs file (#7070)

core/common/src/main/java/alluxio/AbstractClient.java, core/common/src/test/java/alluxio/AbstractClientTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3157
=> [ALLUXIO-3157] Improve rpc connect error messages

core/server/master/src/main/java/alluxio/master/lineage/LineageMasterClientRestServiceHandler.java
I have replaced anonymous type with lambda in alluxio.master.lineage.LineageMasterClientRestServiceHandler
=> [SMALLFIX] I have replaced anonymous type with lambda.

core/client/fs/src/test/java/alluxio/client/file/FileInStreamTest.java, dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go, dev/scripts/src/alluxio.org/build-distribution/cmd/root.go
Ran go fmt and reverted some style changes.
=> [SMALLFIX] Clean up style.

core/server/master/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getMetrics #168
=> [SMALLFIX]replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getMetrics

core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectory.java
Use @Nullable annotation for getChildReadLock.
=> [SMALLFIX]Use @Nullable annotation

docs/en/Alluxio-Storage.md
Fix typo in example low watermark for level0
Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>
=> [DOCFIX] docs/en/Alluxio-Storage.md

core/common/src/main/java/alluxio/thrift/GetMasterInfoTOptions.java, core/common/src/main/java/alluxio/thrift/GetMetricsTResponse.java, core/common/src/main/java/alluxio/thrift/MasterInfo.java, core/common/src/main/java/alluxio/thrift/MasterInfoField.java, core/common/src/main/java/alluxio/wire/MasterInfo.java, core/common/src/test/java/alluxio/wire/MasterInfoTest.java, core/common/src/thrift/meta_master.thrift, core/server/master/src/main/java/alluxio/master/MetaMasterClientServiceHandler.java, shell/src/main/java/alluxio/cli/fsadmin/report/SummaryCommand.java, shell/src/test/java/alluxio/cli/fsadmin/command/SummaryCommandTest.java, tests/src/test/java/alluxio/cli/fsadmin/command/ReportCommandIntegrationTest.java
Add Zookeeper Enabled and Zookeeper Addresses information in report summary command.
=> [SMALLFIX] add Zookeeper information to report summary CLI

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
* slight refactor for underlying hdfs object
* Refactor to enable users in future
cherry-pick of #7129
=> [SMALLFIX] Refactor to enable multiple HDFS users (#7129)

core/common/src/main/java/alluxio/metrics/MetricsSystem.java, core/server/worker/src/test/java/alluxio/worker/block/BlockWorkerMetricsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2182?jql=text%20~%20%22metrics%22
Increase the test coverage for metrics
=> [ALLUXIO-2182]  Add tests for block worker metrics

core/server/worker/src/test/java/alluxio/worker/block/BlockWorkerTest.java
Use static imports for standard test utilities in alluxio.worker.block.BlockWorkerTest
=> [SMALLFIX] Use static imports for standard test utilities in alluxio.worker.block.BlockWorkerTest

core/server/master/src/test/java/alluxio/master/lineage/LineageMasterTest.java
static import org.mockito.Mockito
=> [SMALLFIX]static import org.mockito.Mockito

core/server/worker/src/main/java/alluxio/worker/file/FileSystemMasterClient.java
replace anonymous type with lambda in alluxio.worker.file.FileSystemMasterClient#getFileInfo
=>  [SMALLFIX]update FileSystemMasterClient.java

core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java, core/server/master/src/test/java/alluxio/master/block/BlockMasterMetricsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2182?jql=text%20~%20%22metrics%22
Increase the test coverage for metrics
=> [ALLUXIO-2182] Add unit tests for block master metrics

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterMetricsTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2182?jql=text%20~%20%22metrics%22
Increase the test coverage for metrics
=> [ALLUXIO-2182]   Add unit tests for file system master metrics

core/common/src/main/java/alluxio/underfs/Fingerprint.java, core/common/src/test/java/alluxio/underfs/FingerprintTest.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-3165
Optimize UFS sync to extract UfsStatus information from the fingerprint, instead of retrieving the UfsStatus again
=> [ALLUXIO-3165] Generate ufsStatus from fingerprint instead of calling ufs again.

docs/en/Unified-and-Transparent-Namespace.md
=> [SMALLFIX]Fix a typo in docs/en/Unified-and-Tranparent-Namespace.md #78 

core/server/master/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getWorkerCount
=> [SMALLFIX]JAVA 8 Changed getWorkerCount

core/server/worker/src/main/java/alluxio/worker/block/allocator/MaxFreeAllocator.java, pom.xml
Change
`mManagerView = Preconditions.checkNotNull(view);`
to
`mManagerView = Preconditions.checkNotNull(view, "view");`
in alluxio.worker.block.allocator.MaxFreeAllocator
with error
[Error] transferring file...: Connection refused: connect...
=> [SMALLFIX]Supply the variable name to Preconditions.checkNotNull#allocateBlockWithView

core/server/master/src/main/java/alluxio/master/file/async/DefaultAsyncPersistHandler.java
Supply the variable name to Preconditions.checkNotNull in alluxio.master.file.async.DefaultAsyncPersistHandler#DefaultAsyncPersistHandler
=> [SMALLFIX]Supply the variable name

core/server/master/src/main/java/alluxio/master/AlluxioMasterRestServiceHandler.java
=>  [SMALLFIX] Replace anonymous type with lambda

logserver/src/main/java/alluxio/logserver/AlluxioLogServerProcess.java
https://alluxio.atlassian.net/browse/ALLUXIO-3169
=> [ALLUXIO-3169] Log server graceful shutdown

core/server/common/src/main/java/alluxio/master/journalv0/JournalTool.java
https://alluxio.atlassian.net/browse/ALLUXIO-3171
Use try-with-resources construct
=> [ALLUXIO-3171] JournalInputStream should be closed in JournalTool#main

docs/cn/index.md
Improve documents in docs/cn/index.md.
=> [SMALLFIX] Improve documents in docs/cn/index.md

build/checkstyle/suppressions.xml, tests/pom.xml, tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java, underfs/hdfs/pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-3173
Add preprocessing to FileSystemRenameIntegrationTest
=> [ALLUXIO-3173] Fix compilation against hadoop 3

docs/cn/File-System-API.md, docs/en/Clients-Alluxio-Java.md, docs/pt/File-System-API.md
We removed some file includes that were still being used.
This PR inlines them.
Issue was introduced in https://github.com/Alluxio/alluxio/pull/7126
=> [DOCFIX] Fix doc build

core/common/src/main/java/alluxio/PropertyKey.java, core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java, core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java, core/server/master/src/main/java/alluxio/master/thrift/SocketTrackingTServerSocket.java
https://alluxio.atlassian.net/browse/ALLUXIO-3181
=> [ALLUXIO-3181] Close client sockets during stepdown

core/common/src/main/java/alluxio/Constants.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/exception/ExceptionMessage.java, core/common/src/main/java/alluxio/security/authentication/ImpersonationAuthenticator.java, core/common/src/main/java/alluxio/security/authentication/PlainSaslServer.java, core/common/src/main/java/alluxio/security/authentication/PlainSaslServerCallbackHandler.java, core/common/src/main/java/alluxio/security/authentication/PlainSaslTransportProvider.java, core/common/src/main/java/alluxio/security/authentication/TransportProviderUtils.java, core/common/src/test/java/alluxio/security/authentication/TransportProviderTest.java, docs/en/Security.md, minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java, minicluster/src/main/java/alluxio/master/ClientPool.java, minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java, minicluster/src/main/java/alluxio/master/LocalAlluxioMaster.java, minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java, tests/src/test/java/alluxio/client/fs/ImpersonationIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3191
=> [ALLUXIO-3191] Add support for Alluxio client impersonation

docs/cn/Running-Deep-Learning-on-Alluxio.md
add one chinese doc, the path is:
docs/cn/Running-Deep-Learning-on-Alluxio.md
=> [DOCFIX] Add chinese doc

core/common/src/main/java/alluxio/network/protocol/databuffer/DataByteBuffer.java
I have already removed the blank line before the parameters in DataByteBuffer.java
=> [SMALLFIX] update the java source file

core/server/master/src/main/java/alluxio/master/lineage/LineageMasterClientRestServiceHandler.java
replace anonymous type with lambda in alluxio.master.lineage.LineageMasterClientRestServiceHandler#reportLostFile #222
=> [SMALLFIX] Code improvement in LineageMasterClientRestServiceHandler.java

docs/cn/Running-Alluxio-Fault-Tolerant-on-EC2.md
Inline documentation snippets in docs/cn/Running-Alluxio-Fault-Tolerant-on-EC2.md
=> [DOCFIX]Inline documentation snippets in docs

docs/cn/Security.md
change one chinese doc, add some content . The file path is `/doc/cn/Security.md`
=> [DOCFIX]Change chinese doc

tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterCreateTest.java
Adding some additional diagnostic messages in tests to understand it better.
=> [SMALLFIX] Adding some additional diagnostic messages in tests to understand it better.

tests/src/test/java/alluxio/server/ft/journal/JournalShutdownIntegrationTest.java
=> Revert "[SMALLFIX] ignore JournalShutdownIntegerationTest for now"

tests/src/test/java/alluxio/testutils/BaseIntegrationTest.java
This adds a new appender for the life of every integration test. The appender writes to a file named "tests-{{classname}}-{{methodname}}.log". When the test finishes, we unregister the appender, and delete the log file if the test succeeded.
@yuzhu
=> [SMALLFIX] Use a separate log file for every integration test

underfs/hdfs/pom.xml, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsAclProvider.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/NoopHdfsAclProvider.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/acl/SupportedHdfsAclProvider.java
=> [ALLUXIO-3164] Add profile for selective HDFS ACL support

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java, core/common/src/main/java/alluxio/master/MasterInquireClient.java, core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java, core/common/src/main/java/alluxio/master/SingleMasterInquireClient.java, core/common/src/main/java/alluxio/master/ZkMasterInquireClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-3214
=> [ALLUXIO-3214] Avoid resetting filesystem context in HA mode

underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2477
Make sure that comments which start with a capital letter end with a period in S3AUnderFileSystem
=> [ALLUXIO-2477] Improve comment style in S3AUnderFileSystem

core/common/src/main/java/alluxio/PropertyKey.java, tests/src/test/java/alluxio/testutils/LocalAlluxioClusterResource.java
=> [SMALLFIX]Disable the client metrics collection

core/common/src/main/java/alluxio/util/interfaces/Scoped.java, core/server/common/src/main/java/alluxio/master/AbstractPrimarySelector.java, core/server/common/src/main/java/alluxio/master/PrimarySelector.java, core/server/common/src/main/java/alluxio/master/PrimarySelectorClient.java, core/server/common/src/main/java/alluxio/master/journal/AbstractJournalSystem.java, core/server/common/src/main/java/alluxio/master/journal/JournalSystem.java, core/server/common/src/main/java/alluxio/master/journal/noop/NoopJournalSystem.java, core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSystem.java, core/server/common/src/test/java/alluxio/master/AbstractPrimarySelectorTest.java, core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java, core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java, tests/src/test/java/alluxio/testutils/master/MasterTestUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-3218
=> [ALLUXIO-3218] Make gaining primacy interruptible

core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java, tests/src/test/java/alluxio/client/cli/fsadmin/command/MetricsCommandIntegrationTest.java
=> [ALLUXIO-3204] Add metrics for async caching.

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/main/java/alluxio/master/file/options/CompleteFileOptions.java, core/server/master/src/main/java/alluxio/master/file/options/CreateDirectoryOptions.java
This will speed up list recursive.
=> [SMALLFIX] use fingerprint from ufsstatus if possible

core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java, core/common/src/main/java/alluxio/AbstractClient.java
@yupeng9 When you refactor the `getMetricName` methods, do you think it makes sense to also include general tags like user in that logic (since we will want to get tag all metrics with user if possible)?
=> [ALLUXIO-3204] Add client side FileSystem RPC metrics.

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/main/java/alluxio/client/metrics/ClientMasterSync.java, core/client/fs/src/main/java/alluxio/client/metrics/MetricsMasterClient.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/util/IdUtils.java
=> [ALLUXIO-3204] Allow users to set app id

core/common/src/main/java/alluxio/metrics/MetricsSystem.java
=> [ALLUXIO-3204] Add jvm attribute metrics.

bin/alluxio-start.sh, docs/en/Getting-Started-on-Cluster.md, docs/en/Getting-Started.md, docs/en/Remote-Logging.md, docs/en/Running-Hadoop-MapReduce-on-Alluxio.md
Avoid accidentally formatting the worker
=> [SMALLFIX] Change default to Nomount

core/common/src/main/java/alluxio/Constants.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/security/authentication/TransportProviderUtils.java, docs/en/Security.md, tests/src/test/java/alluxio/client/fs/ImpersonationIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3191
=> [ALLUXIO-3191] Disallow arbitrary client impersonation

core/common/src/main/java/alluxio/AbstractClient.java, core/common/src/main/java/alluxio/metrics/CommonMetrics.java, core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
=> [ALLUXIO-3204] Add metrics for UFS calls.

core/client/fs/src/main/java/alluxio/client/block/stream/LocalFilePacketReader.java, core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/common/src/main/java/alluxio/AbstractClient.java, core/common/src/main/java/alluxio/metrics/MetricsSystem.java, core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java, core/common/src/test/java/alluxio/metrics/MetricsSystemTest.java, core/server/common/src/main/java/alluxio/underfs/UfsManager.java, core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, core/server/master/src/main/java/alluxio/web/WebInterfaceMasterMetricsServlet.java, core/server/master/src/test/java/alluxio/master/block/BlockMasterMetricsTest.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterMetricsTest.java, core/server/master/src/test/java/alluxio/master/meta/AlluxioMasterRestServiceHandlerTest.java, core/server/worker/src/main/java/alluxio/web/WebInterfaceWorkerMetricsServlet.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java, core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java, core/server/worker/src/main/java/alluxio/worker/block/BlockMetricsReporter.java, core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java, core/server/worker/src/main/java/alluxio/worker/netty/BlockReadHandler.java, core/server/worker/src/main/java/alluxio/worker/netty/BlockWriteHandler.java, core/server/worker/src/main/java/alluxio/worker/netty/UfsFileWriteHandler.java, core/server/worker/src/test/java/alluxio/worker/block/BlockWorkerMetricsTest.java, tests/src/test/java/alluxio/client/cli/fsadmin/command/MetricsCommandIntegrationTest.java, tests/src/test/java/alluxio/client/rest/AlluxioMasterRestApiTest.java, tests/src/test/java/alluxio/client/rest/AlluxioWorkerRestApiTest.java
=> [ALLUXIO-3204] Refactor metrics system.

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/util/io/FileUtils.java, core/server/common/src/main/java/alluxio/cli/Format.java, core/server/common/src/test/java/alluxio/cli/FormatTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3224
=> [ALLUXIO-3224] Configurable worker dir permissions

core/common/src/main/java/alluxio/util/FormatUtils.java, core/common/src/test/java/alluxio/util/FormatUtilsTest.java, core/server/common/src/main/java/alluxio/web/UIFileInfo.java, shell/src/main/java/alluxio/cli/fs/command/LsCommand.java, tests/src/test/java/alluxio/client/cli/fs/command/LsCommandIntegrationTest.java
=> [ALLUXIO-3164] Implement extended acl for ls

core/server/common/src/main/java/alluxio/cli/validation/ClusterConfConsistencyValidationTask.java
Fix an issue where non-Alluxio properties in the system causes the validateEnv command to throw an exception.
=> [SMALLFIX] fix validateEnv check conf command

core/server/common/src/main/java/alluxio/ProcessUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-3221
Also added a name for the shutdown hook thread so that it's easier to identify in a jstack
=> [ALLUXIO-3221] Log error instead of exiting in shutdown hook

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
=> [SMALLFIX] Remove unnecessary try-catch

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go, integration/checker/pom.xml
cherry-picked from https://github.com/Alluxio/alluxio/pull/7417
=> [SMALLFIX] Fix build for hadoop 1 (#7417)

tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterCreateTest.java
* Improve limit in test
* Improve buffer factor
=> [SMALLFIX] Improve limit in test (branch-1.8)

docs/en/Configuring-Alluxio-with-Azure-Blob-Store.md, underfs/wasb/src/main/java/alluxio/underfs/wasb/WasbUnderFileSystem.java
=> [SMALLFIX] Fix wasb ufs and update docs

docs/en/Running-Alluxio-on-Virtual-Box.md
need to checkout repo rather than download release from the website.
=> [DOCFIX] virtualbox instructions update

docs/en/FAQ.md
Updated a bunch of links that are renamed or removed.
=> [DOCFIX] Fix broken links on FAQ page

core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
Configuration checker created a new requirement that even non-HA masters must be configured with `alluxio.master.hostname`. This PR removes the requirement, fixing the YARN integration in particular
=> [SMALLFIX] Avoid requiring master address on non-HA master

core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
Cherry-picked from https://github.com/Alluxio/alluxio/pull/7443
=> [SMALLFIX] Avoid requiring master hostname on master in non-HA mode (#7443)

core/client/fs/src/main/java/alluxio/client/file/options/CreateDirectoryOptions.java, core/client/fs/src/main/java/alluxio/client/file/options/CreateFileOptions.java, core/client/fs/src/main/java/alluxio/client/file/options/GetStatusOptions.java, core/client/fs/src/main/java/alluxio/client/file/options/ListStatusOptions.java, core/client/fs/src/test/java/alluxio/client/file/options/CreateDirectoryOptionsTest.java, core/client/fs/src/test/java/alluxio/client/file/options/CreateFileOptionsTest.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/thrift/CreateDirectoryTOptions.java, core/common/src/main/java/alluxio/thrift/CreateFileTOptions.java, core/common/src/main/java/alluxio/thrift/FileSystemMasterCommonTOptions.java, core/common/src/main/java/alluxio/wire/CommonOptions.java, core/common/src/thrift/file_system_master.thrift, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/main/java/alluxio/master/file/options/CreateDirectoryOptions.java, core/server/master/src/main/java/alluxio/master/file/options/CreateFileOptions.java, core/server/master/src/main/java/alluxio/master/file/options/CreatePathOptions.java, core/server/master/src/main/java/alluxio/master/file/options/LoadMetadataOptions.java
https://alluxio.atlassian.net/browse/ALLUXIO-3167
Cherry-picks https://github.com/Alluxio/alluxio/pull/7317 to the 1.8 branch
=> [ALLUXIO-3167] Allow application level TTL (#7317)

shell/src/main/java/alluxio/cli/fsadmin/report/CapacityCommand.java, shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3145
Cherry pick https://github.com/Alluxio/alluxio/pull/7402 to the 1.8 branch
=> [ALLUXIO-3145] Support report capacity command for handling long names (#7402)

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
* more efficient locking
* style fix
* addressed comments
=> [SMALLFIX] more efficient locking for listStatus (#7416)

docs/en/Configuring-Alluxio-with-NFS.md
Cherry-picks #7456  to the 1.8 branch
=> [DOCFIX] improve NFS docs (#7456)

docs/en/Getting-Started.md
major change: `fs cat` now can cache
=> [DOCFIX] Clean up get started page

docs/en/Running-Alluxio-on-GCE.md
=> [DOCFIX] Improve GCE docs

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/main/java/alluxio/client/metrics/ClientMasterSync.java, core/client/fs/src/test/java/alluxio/client/util/ClientTestUtils.java, core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java, core/client/hdfs/src/test/java/alluxio/hadoop/HadoopClientTestUtils.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/metrics/Metric.java, core/common/src/main/java/alluxio/metrics/MetricsSystem.java, core/common/src/main/java/alluxio/metrics/WorkerMetrics.java, core/common/src/main/java/alluxio/metrics/aggregator/SingleTagValueAggregator.java, core/common/src/main/java/alluxio/underfs/UnderFileSystem.java, core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java, core/common/src/test/java/alluxio/metrics/MetricTest.java, core/server/common/src/main/webapp/metrics-summary.jsp, core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java, core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java, core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java, core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java, core/server/master/src/main/java/alluxio/web/WebInterfaceMasterMetricsServlet.java, core/server/master/src/test/java/alluxio/master/metrics/MetricsMasterTest.java, minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java, tests/src/test/java/alluxio/client/fs/ImpersonationIntegrationTest.java, tests/src/test/java/alluxio/server/ft/journal/JournalShutdownIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-2182
cherry-pick https://github.com/Alluxio/alluxio/pull/7392
=> [ALLUXIO-2182]  Display per-UFS IO metrics (#7392)

core/server/master/src/main/java/alluxio/web/WebInterfaceGeneralServlet.java
https://alluxio.atlassian.net/browse/ALLUXIO-3233
=> [ALLUXIO-3233] Use mount info for web ufs info

core/common/src/main/java/alluxio/PropertyKey.java, core/server/common/src/main/java/alluxio/web/WebInterfaceBrowseLogsServlet.java, core/server/common/src/main/java/alluxio/web/WebInterfaceHeaderServlet.java, core/server/common/src/main/webapp/browse-body.jsp, core/server/common/src/main/webapp/header.jsp, core/server/common/src/main/webapp/memory.jsp, core/server/common/src/main/webapp/worker/blockInfo.jsp, core/server/master/src/main/java/alluxio/web/WebInterfaceBrowseServlet.java, core/server/master/src/main/java/alluxio/web/WebInterfaceDownloadServlet.java, core/server/master/src/main/java/alluxio/web/WebInterfaceMemoryServlet.java, core/server/worker/src/main/java/alluxio/web/WebInterfaceWorkerBlockInfoServlet.java
https://alluxio.atlassian.net/browse/ALLUXIO-3230
=> [ALLUXIO-3230] Add a property to enable/disable detailed file info in Web  UI

tests/src/test/java/alluxio/server/tieredstore/TieredStoreIntegrationTest.java
=> [SMALLFIX] Cherrypick - Deflake test. (#7463)

docs/en/Running-Alluxio-Fault-Tolerant-on-EC2.md
=> [DOCFIX] Update EC2 HA doc

core/server/common/src/main/java/alluxio/RpcUtils.java, core/server/master/src/main/java/alluxio/master/block/BlockMasterClientServiceHandler.java, core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMasterWorkerServiceHandler.java, core/server/master/src/main/java/alluxio/master/lineage/LineageMasterClientServiceHandler.java, core/server/master/src/main/java/alluxio/master/meta/MetaMasterClientServiceHandler.java, core/server/master/src/main/java/alluxio/master/meta/MetaMasterMasterServiceHandler.java, core/server/master/src/main/java/alluxio/master/metrics/MetricsMasterClientServiceHandler.java, core/server/worker/src/main/java/alluxio/worker/netty/ShortCircuitBlockReadHandler.java, core/server/worker/src/main/java/alluxio/worker/netty/ShortCircuitBlockWriteHandler.java, keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMasterClientServiceHandler.java, keyvalue/server/src/main/java/alluxio/worker/keyvalue/KeyValueWorkerClientServiceHandler.java
I would suggest to review commit by commit.
This makes the call signature more similar to the client side.
Some benefits of doing this include not having junk metrics due to some methods not implementing a good `toString`.
=> [ALLUXIO-3204] Refactor RpcUtils

core/common/src/main/java/alluxio/underfs/UfsDirectoryStatus.java, core/common/src/main/java/alluxio/underfs/UfsFileStatus.java, core/common/src/main/java/alluxio/underfs/UfsStatus.java
Updates toString to include all fields of the status instead of just the name
=> [SMALLFIX] Implement toString for ufsStatus

core/server/common/src/main/java/alluxio/RpcUtils.java, core/server/master/src/main/java/alluxio/master/block/BlockMasterClientServiceHandler.java, core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMasterWorkerServiceHandler.java, core/server/master/src/main/java/alluxio/master/lineage/LineageMasterClientServiceHandler.java, core/server/master/src/main/java/alluxio/master/meta/MetaMasterClientServiceHandler.java, core/server/master/src/main/java/alluxio/master/meta/MetaMasterMasterServiceHandler.java, core/server/master/src/main/java/alluxio/master/metrics/MetricsMasterClientServiceHandler.java, core/server/worker/src/main/java/alluxio/worker/netty/ShortCircuitBlockReadHandler.java, core/server/worker/src/main/java/alluxio/worker/netty/ShortCircuitBlockWriteHandler.java, keyvalue/server/src/main/java/alluxio/master/keyvalue/KeyValueMasterClientServiceHandler.java, keyvalue/server/src/main/java/alluxio/worker/keyvalue/KeyValueWorkerClientServiceHandler.java
=> [ALLUXIO-3204] Cherry-pick metrics refactoring

core/common/src/main/java/alluxio/Constants.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/network/TieredIdentityFactory.java, core/common/src/test/java/alluxio/ConfigurationTest.java, core/common/src/test/java/alluxio/network/TieredIdentityFactoryTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3234
=> [ALLUXIO-3234] Allow tiered locality to be configured via classpath

assembly/pom.xml, integration/checker/pom.xml, pom.xml
Cherry-pick from master branch
=> [SMALLFIX] Replace hadoop profiles with hadoop-{1,2,3}

docs/cn/Configuring-Alluxio-with-Azure-Blob-Store.md, docs/cn/Configuring-Alluxio-with-MapR-FS.md, docs/cn/FAQ.md, docs/cn/Getting-Started.md, docs/cn/Remote-Logging.md, docs/cn/Running-Alluxio-on-Mesos.md, docs/cn/Running-Alluxio-on-Virtual-Box.md, docs/cn/Running-Hadoop-MapReduce-on-Alluxio.md, docs/cn/Running-Spark-on-Alluxio.md, docs/cn/Security.md
Cherry-picking Chinese doc fixes to branch-1.8
=> [DOCFIX] cherry-pick cn doc updates to branch-1.8

docs/_data/table/en/fsadmin-command.yml, docs/_data/table/fsadmin-command.csv, docs/en/Admin-CLI.md
Update the fsadmin doc to include doctor command and make some modification.
=> [DOCFIX] improve fsadmin doc

docs/_data/table/en/fsadmin-command.yml, docs/_data/table/fsadmin-command.csv, docs/en/Admin-CLI.md
cherry pick https://github.com/Alluxio/alluxio/pull/7488
=> [DOCFIX] improve fsadmin doc (#7488)

core/common/src/main/java/alluxio/metrics/Metric.java, core/server/common/src/main/java/alluxio/RpcUtils.java
=> [SMALLFIX] Slightly improve metrics string costs

core/common/src/main/java/alluxio/metrics/MetricsSystem.java, core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
=> [SMALLFIX] Slight performance optimizations. 

docs/en/Configuration-Settings.md
* Improve Configuration webpage with cluster default
* Address comments
* Further cleanup
=> [DOCFIX] Cherry-pick Improve Configuration webpage with cluster default (#7491)

docs/en/Time-To-Live.md
https://alluxio.atlassian.net/browse/ALLUXIO-3235
@Reidddddd if you want to add anything, especially related to the passive TTL portion
=> [ALLUXIO-3235] Add TTL docs.

core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
=> [SMALLFIX] Remove @Override to fix hadoop-1 build

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java, core/server/master/src/main/java/alluxio/master/file/meta/MutableLockedInodePath.java
* style fix
* attempt to address slow listDir
* enable getPathComponents optimization
* address comments
* address comments
=> [SMALLFIX] perf fix for listDir (#7497)

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java, core/common/src/main/java/alluxio/metrics/Metric.java, core/common/src/main/java/alluxio/metrics/MetricsSystem.java, core/common/src/main/java/alluxio/security/authentication/AuthenticatedClientUser.java, core/server/common/src/main/java/alluxio/RpcUtils.java, core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java, core/server/master/src/test/java/alluxio/master/metrics/MetricsMasterTest.java
=> [SMALLFIX] Cherry pick metrics changes

docs/en/Configuring-Alluxio-with-Ceph.md
https://alluxio.atlassian.net/browse/ALLUXIO-2922
=> [ALLUXIO-2922] Simplified Ceph Config Language

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/common/src/main/java/alluxio/network/netty/NettyClient.java
=> [SMALLFIX] Propagate subject to netty client

deploy/vagrant/create
https://alluxio.atlassian.net/browse/ALLUXIO-3239
=> [ALLUXIO-3239] Increase the sleep time to 20 secs for curl command deploy/vagrant/create

shell/src/main/java/alluxio/cli/fsadmin/report/MetricsCommand.java, shell/src/test/java/alluxio/cli/fsadmin/report/MetricsCommandTest.java, tests/src/test/java/alluxio/client/cli/fsadmin/command/MetricsCommandIntegrationTest.java
cherry-pick #7524 to 1.8 branch
=> [SMALLFIX] fix report metrics null issue (#7524)

tests/src/test/java/alluxio/client/cli/fsadmin/command/MetricsCommandIntegrationTest.java
cherry pick #7526 to 1.8 branch
=> [SMALLFIX] remove @Ignore in metrics command integration test (#7526)

core/common/src/main/java/alluxio/security/authorization/DefaultAccessControlList.java, core/server/master/src/main/java/alluxio/master/file/meta/Inode.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java, core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java, tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java
Make create dir and file respect default ACLs.
=> [SMALLFIX]  Use default ACL when creating files and directories

docs/en/Configuring-Alluxio-with-HDFS.md, docs/en/Configuring-Alluxio-with-secure-HDFS.md
* Correct documentation on HDFS and secure HDFS
* Futher improvement
=> [DOCFIX] Cherry-pick: Correct documentation on HDFS and secure HDFS (#7521)

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/test/java/alluxio/PropertyKeyTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3241
=> [ALLUXIO-3241] Fix impersonation regex

core/common/src/main/java/alluxio/exception/ExceptionMessage.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3242
=> [ALLUXIO-3242] Fix read only mount

core/common/src/main/java/alluxio/util/io/PathUtils.java
https://alluxio.atlassian.net/browse/ALLUXIO-3243
This creates a StringBuilder of the correct size, so it does not have to be constantly resized.
=> [ALLUXIO-3243] Optimize concatPath

core/server/master/src/main/java/alluxio/master/file/meta/InodeLockList.java
https://alluxio.atlassian.net/browse/ALLUXIO-3243
=> [ALLUXIO-3243] Use initial capacity for locklist

core/server/master/src/main/java/alluxio/master/file/meta/CompositeInodeLockList.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeLockList.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java
https://alluxio.atlassian.net/browse/ALLUXIO-3243
=> [ALLUXIO-3243] Optimize getInode

core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
https://alluxio.atlassian.net/browse/ALLUXIO-3246
=> [ALLUXIO-3246] Fix unit for master client thread pool keep-alive time

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-release-tarballs.go
=> [SMALLFIX] Include -bin in the name for release tarballs

core/common/src/main/java/alluxio/security/authorization/AccessControlList.java, core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java, core/common/src/main/java/alluxio/underfs/Fingerprint.java, core/common/src/test/java/alluxio/underfs/FingerprintTest.java
=> [ALLUXIO-3164] fingerprint with ACL

core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java, core/common/src/main/java/alluxio/underfs/UnderFileSystem.java, core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/Inode.java, tests/src/test/java/alluxio/testutils/underfs/delegating/DelegatingUnderFileSystem.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsAclProvider.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/NoopHdfsAclProvider.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/acl/SupportedHdfsAclProvider.java
=> [ALLUXIO-3164] [WIP] ufs setfacl for hdfs

core/common/src/main/java/alluxio/AlluxioURI.java, core/common/src/main/java/alluxio/MultiPartSchemeURI.java, core/common/src/main/java/alluxio/StandardURI.java, core/common/src/main/java/alluxio/URI.java, core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java, core/common/src/main/java/alluxio/util/URIUtils.java, core/common/src/test/java/alluxio/AlluxioURITest.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
https://alluxio.atlassian.net/browse/ALLUXIO-3244
=> [ALLUXIO-3244] Optimize AlluxioURI

core/server/common/src/main/java/alluxio/underfs/UfsManager.java
https://alluxio.atlassian.net/browse/ALLUXIO-3243
=> [ALLUXIO-3243] Remove sync from acquireUfsResource

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/test/java/alluxio/PropertyKeyTest.java
* Fix impersonation regex
* Improve regex
* Improve regex
https://alluxio.atlassian.net/browse/ALLUXIO-3241
=> [ALLUXIO-3241] Fix impersonation regex (#7571)

core/common/src/main/java/alluxio/exception/ExceptionMessage.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
@gpang cherry-pick to branch-1.8
https://alluxio.atlassian.net/browse/ALLUXIO-3242
=> [ALLUXIO-3242] Fix read only mount (#7574)

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
=> [ALLUXIO-3164] recursive setfacl

core/common/src/main/java/alluxio/exception/ExceptionMessage.java, core/common/src/main/java/alluxio/security/authentication/AuthenticatedClientUser.java, core/common/src/test/java/alluxio/AuthenticatedClientUserResource.java, core/common/src/test/java/alluxio/AuthenticatedClientUserResourceTest.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
@gpang cherry-pick to branch-1.8
https://alluxio.atlassian.net/browse/ALLUXIO-3245
=> [ALLUXIO-3245] Fix recursive delete permission checking

docs/cn/Clients-Python.md, docs/cn/Getting-Started-on-Cluster.md, docs/cn/Running-Alluxio-On-Kubernetes.md
Updated:
`docs/cn/Clients-Python.md` (Add missing links)
`docs/cn/Running-Alluxio-On-Kubernetes.md` (Fix a bug which caused its absence from the sidebar)
Added:
`docs/cn/Getting-Started-on-Cluster.md`
=> [DOCFIX] Update Chinese docs, and add missing doc

shell/src/main/java/alluxio/cli/GetConf.java, tests/src/test/java/alluxio/client/cli/fs/GetConfTest.java
cherry-pick this bug fix to branch 1.8
=> [SMALLFIX] Fix getConf bug on alias

minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java, tests/src/test/java/alluxio/testutils/AlluxioOperationThread.java
=> [SMALLFIX] Small fixes to improve tests

core/server/common/src/main/java/alluxio/master/journal/JournalEntryAssociation.java, core/server/common/src/test/java/alluxio/master/journal/JournalEntryAssociationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3251
Will cherry-pick to branch-1.8 after
=> [ALLUXIO-3251] Fix journal association and add test

core/server/common/src/main/java/alluxio/master/journal/JournalEntryAssociation.java, core/server/common/src/test/java/alluxio/master/journal/JournalEntryAssociationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3251
=> [ALLUXIO-3251] Cherry pick journal association fix

core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java, minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java, tests/src/test/java/alluxio/server/ft/journal/JournalCheckpointIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3254
=> [ALLUXIO-3254] Journal the correct mount id.

core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java, minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java, tests/src/test/java/alluxio/server/ft/journal/JournalCheckpointIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3254
Cherry-pick of #7645
=> [ALLUXIO-3254] Journal the correct mount id. (#7645)

core/common/src/main/java/alluxio/AbstractClient.java
Add `beforeConnect` in `AbstractClient` so different implementation client can choose the right preparation based on their type
=> [SMALLFIX] Move loading cluster default configuration into beforeConnect

core/common/src/main/java/alluxio/exception/ExceptionMessage.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/underfs/MasterUfsManager.java, tests/src/test/java/alluxio/server/ft/journal/JournalCheckpointIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3255
=> [ALLUXIO-3255] Fix issue where ufs mode is not set in snapshots

core/common/src/main/java/alluxio/security/authorization/AccessControlList.java, core/common/src/main/java/alluxio/security/authorization/AclEntry.java, core/common/src/main/java/alluxio/security/authorization/DefaultAccessControlList.java, core/common/src/main/java/alluxio/security/authorization/ExtendedACLEntries.java, core/common/src/main/java/alluxio/security/authorization/Mode.java, core/common/src/test/java/alluxio/security/authorization/AccessControlListTest.java, core/common/src/test/java/alluxio/security/authorization/ModeBitsTest.java, core/server/master/src/main/java/alluxio/master/file/DefaultPermissionChecker.java
https://alluxio.atlassian.net/browse/ALLUXIO-3256
=> [ALLUXIO-3256] Reduce mem usage of ACLs

core/common/src/main/java/alluxio/exception/ExceptionMessage.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/underfs/MasterUfsManager.java, tests/src/test/java/alluxio/server/ft/journal/JournalCheckpointIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3255
=> [ALLUXIO-3255] Cherry-pick ufs mode fix

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeDirectoryIdGenerator.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/test/java/alluxio/master/file/PermissionCheckerTest.java, core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
* Journal the creation of the root directory
* Remove unused method
=> [SMALLFIX] Journal the creation of the root directory (#7644)

core/server/common/src/main/webapp/metrics-summary.jsp
=> [SMALLFIX] Display set acl ops in UI metrics

core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-3258
This should be cherry-picked to branch-1.8 after
=> [ALLUXIO-3258] Ensure that UFS stream is closed during journal backup

core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-3258
=> [ALLUXIO-3258] Ensure that UFS stream is closed during journal backup (#7654)

core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, core/server/master/src/test/java/alluxio/master/meta/AlluxioMasterRestServiceHandlerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3248
=> [ALLUXIO-3248] Improve rest handler memory usage

docs/en/Running-Presto-with-Alluxio.md
make the presto cli example easier to follow.
=> [DOCFIX] improve docs/en/Running-Presto-with-Alluxio.md

core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, core/server/master/src/test/java/alluxio/master/meta/AlluxioMasterRestServiceHandlerTest.java
* Improve rest handler
* Fix findbugs
* Fix test
https://alluxio.atlassian.net/browse/ALLUXIO-3248
cherry-pick from master branch
=> [ALLUXIO-3248] Improve rest handler memory usage (#7659)

docs/en/Running-Presto-with-Alluxio.md
cherry pick #7657 to branch 1.8
=> [DOCFIX] improve docs/en/Running-Presto-with-Alluxio.md (#7657)

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-3275
The NPE happens when there are concurrent createFile and listFile happening, and the createFile happen to finish between two `getChildren` calls.
=> [ALLUXIO-3275] Fix NPE while running concurrentListFiles

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-3275
* Fix NPE while running concurrent listStatus and creates
* style fix
=> [ALLUXIO-3275] CHERRYPICK - Fix NPE while running concurrentListFiles (#7662)

core/common/src/main/java/alluxio/PropertyKey.java
https://alluxio.atlassian.net/browse/ALLUXIO-3277
=> [ALLUXIO-3277] Increase worker timeout

core/client/runtime/pom.xml
Cherry-pick of #7680 from master branch to 1.8 branch
=> [ALLUXIO-3278] Enforce no unshaded protobuf and thrift classes in the output (#7680)

core/client/runtime/pom.xml
=> [ALLUXIO-3278] Remove unsafe filter on thrift

core/client/runtime/pom.xml
=> [ALLUXIO-3278] Remove unsafe filter on thrift (#7686)

core/server/worker/src/test/java/alluxio/worker/block/UfsInputStreamManagerTest.java
[https://alluxio.atlassian.net/browse/ALLUXIO-3270](https://alluxio.atlassian.net/browse/ALLUXIO-3270)
change Mockito.mock(...) to mock(...) for all function of class alluxio.worker.block.UfsInputStreamManagerTest and change import org.mockito.Mockito; to import static org.mockito.Mockito.mock; Mockito.when(...) and Mockito.eq(...) Mockito.any(...) Mockito.verify(..) are the same.
=> [ALLUXIO-3270] Use static imports for standard test utilities for class UfsInputStreamManagerTest

docs/cn/Running-Hive-with-Alluxio.md, docs/css/main.css, docs/en/Building-Alluxio-From-Source.md, docs/en/Clients-Alluxio-Java.md, docs/en/Clients-Go.md, docs/en/Clients-Python.md, docs/en/Clients-S3.md, docs/en/Compatibility.md, docs/en/Configuration-Properties.md, docs/en/Configuration-Settings.md, docs/en/Debugging-Guide.md, docs/en/DevelopingUFSExtensions.md, docs/en/Journal.md, docs/en/Logging-Conventions.md, docs/en/Running-Alluxio-Locally.md, docs/en/Running-Hive-with-Alluxio.md, docs/en/Running-Presto-with-Alluxio.md, docs/en/Tiered-Locality.md, docs/en/UFSExtensions.md, docs/en/Unit-Testing.md
Attached picture shows the Hive doc after this change
=> [DOCFIX] Use numbered headings for documentation pages

core/client/runtime/pom.xml
=>  [ALLUXIO-3278]  Enforce no unshaded protobuf classes in the output

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/test/java/alluxio/client/file/FileSystemContextTest.java, core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java, core/client/hdfs/src/test/java/alluxio/hadoop/HadoopClientTestUtils.java, minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java, tests/src/test/java/alluxio/client/fs/ImpersonationIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3284
=> [ALLUXIO-3284] Cache contexts based on subject

docs/en/Configuring-Alluxio-with-secure-HDFS.md
=> [DOCFIX] Improve secure hdfs docs

dev/jenkins/Dockerfile
See https://hub.docker.com/r/alluxio/alluxio-maven/ for instructions on running the image
=> [SMALLFIX] Add dockerfile for building alluxio-maven image

core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java, core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
https://alluxio.atlassian.net/browse/ALLUXIO-3286
=> [ALLUXIO-3286] Use correct lock for MasterWorkerInfo

underfs/oss/src/main/java/alluxio/underfs/oss/OSSOutputStream.java, underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
cherry-pick from 1.9-SNAPSHOT to 1.8 branch
=> [SMALLFIX] Improvements on OSS UFS (#7754)

core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
applyAndJournal is never expected to throw an exception. But if it does find a way to throw an exception, we could end up in an inconsistent state that we can't recover from, possibly with a corrupted journal. Better to bail out before this happens.
=> [SMALLFIX] Fatal error if applyAndJournal fails

.gitignore, core/common/src/main/java/alluxio/PropertyKey.java, core/server/common/src/main/java/alluxio/web/WebServer.java, tests/src/test/java/alluxio/server/web/WebServerIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3292
Make jetty to extract web resources to a non system temp folder.
=> [ALLUXIO-3292] Move temporary web resource directory out of system temp folder

core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
=> [SMALLFIX] Add test for removing extended acl masks

core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3267
change Mockito.verify(...) to verify(...) for all function of class alluxio.worker.block.TieredBlockStoreTest and change import org.mockito.Mockito; to import static org.mockito.Mockito.verify;
Mockito.mock(...),Mockito.when(...), Mockito.any(...) are the same.
=> [ALLUXIO-3267] Update TieredBlockStoreTest.java

bin/alluxio-start.sh
Cherry-pick #7769 to branch-1.8
=> [SMALLFIX] Fix mount check for alluxio-start.sh #7769

core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3282
=> [ALLUXIO-3282] Ignore ufs paths containing '?'

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/test/java/alluxio/ConfigurationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3259
I will cherrypick this to 1.8 branch
=> [ALLUXIO-3259] Fix NPE when passing an option to UFS root from extension

core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3282
Cherry-picked from https://github.com/Alluxio/alluxio/pull/7783
=> [ALLUXIO-3282] Ignore ufs paths containing '?' (#7783)

core/protobuf/src/proto/journal/journal.proto, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Removes a bunch of unnecessary code
=> [SMALLFIX] File system master cleanups

docs/en/Loading-Under-File-Storage-Metadata.md
Feel free to suggest additional sections to include
=> [DOCFIX] Add doc for loading UFS metadata

core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
https://alluxio.atlassian.net/browse/ALLUXIO-3300
further speed up recursive ls by not syncpersist when we are create a file as part of loadMetadata
=> [ALLUXIO-3300] more speed up to lsr and du -r

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/underfs/MasterUfsManager.java, tests/src/main/java/alluxio/master/backcompat/BackwardsCompatibilityJournalGenerator.java, tests/src/main/java/alluxio/master/backcompat/ops/UpdateUfsMode.java
https://alluxio.atlassian.net/browse/ALLUXIO-3290
=> [ALLUXIO-3290] Update UFS mode to journal as a part of modify

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
https://alluxio.atlassian.net/browse/ALLUXIO-3304
=> [ALLUXIO-3304] Limit metrics heartbeat shutdown hook time

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java, integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3306
=> [ALLUXIO-3306] delay fuse open if file is not completed

core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
https://alluxio.atlassian.net/browse/ALLUXIO-3299
Cherry-pick from branch-1.8
=> [ALLUXIO-3299] worker should only be exposed in master after register (#7780)

docs/en/Running-HBase-on-Alluxio.md
Added a troubleshooting section for HBase doc for a particular issue encountered by some users.
=> [DOCFIX] Add "offsets do not match" troubleshooting section for HBase doc

bin/alluxio-start.sh
https://alluxio.atlassian.net/browse/ALLUXIO-3257
=> [ALLUXIO-3257] use the is_ram_folder_mounted function to avoid erasing and re-mounting ramdisk

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java, core/client/fs/src/main/java/alluxio/client/file/FileInStream.java, core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3293
@apc999 @aaudiber 
I'm sorry to miss closing PR in https://github.com/Alluxio/alluxio/pull/7785, and try hard to re-open it, but no effect. So I create a new one here.
=> [ALLUXIO-3293] Fix retry policy being invalid when reading local block from a crashed local worker

core/common/src/main/java/alluxio/exception/ExceptionMessage.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java, core/server/master/src/test/java/alluxio/master/file/meta/MountTableTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3310
@gpang @bf8086
=> [ALLUXIO-3310] Enable Nested Mountpoint

core/common/src/main/java/alluxio/util/network/NettyUtils.java
Now we'll just check and log once
=> [SMALLFIX] Avoid double-logging that EPOLL is available

underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-2928
2/2 New Contributor tasks.
=> [ALLUXIO-2928] Added period as per task.

bin/alluxio-mount.sh, bin/alluxio-start.sh
This adds `Umount` and `SudoUmount` alongside the existing `Mount` and `SudoMount`.
=> [SMALLFIX] Support unmounting in alluxio-mount.sh

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
forgot to push this to remote in the last PR..
=> [SMALLFIX] Actually adding catch and log to loadMetadataInternal

docs/en/Running-Hive-with-Alluxio.md, docs/en/Running-Presto-with-Alluxio.md
- Rewrite Presto doc to simplify the setup and re-organize the flow
- Minor tuning on Hive doc
=> [DOCFIX] Improve Presto and Hive doc

docs/en/advanced/Command-Line-Interface.md, docs/en/operation/Admin-CLI.md
Doc improvement phase 1 for Command-Line-Interface.md and Admin-CLI.md
=> [DOCFIX] TODOs for Command-Line-Interface.md and Admin-CLI.md

integration/mesos/src/main/java/alluxio/mesos/AlluxioMasterExecutor.java
https://alluxio.atlassian.net/browse/ALLUXIO-3315
=> [ALLUXIO-3315] Avoid re-formatting journal on Mesos master executor start

docs/en/deploy/Running-Alluxio-On-a-Cluster.md
=> [DOCFIX] TODOs for cluster deployment

docs/en/operation/Troubleshooting.md
=> [DOCFIX] Add todos for troubleshooting page

core/common/src/main/java/alluxio/conf/InstancedConfiguration.java, core/common/src/main/java/alluxio/exception/ExceptionMessage.java, core/common/src/test/java/alluxio/ConfigurationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3323
@aaudiber @apc999
=> [ALLUXIO-3323] - InstancedConfiguration.isSet should lookup keys recursively.

docs/en/advanced/Configuration-Settings.md
=> [DOCFIX] TODOs for config

docs/en/advanced/Namespace-Management.md
=> [DOCFIX] TODOs for namespace management

core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
https://alluxio.atlassian.net/browse/ALLUXIO-2919
=> [SMALLFIX] [ALLUXIO-2919] Improve javadoc for DynamicResourcePool#acquire

docs/en/operation/Logging-Conventions.md
=> [DOCFIX] Logging doc todos

docs/en/compute/Compute-Hive.md, docs/en/compute/Compute-Presto.md
Improve the doc for Hive and Presto according to the doc guide
=> [DOCFIX] Improve Hive and Presto docs

core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
=> [CHERRY-PICK] further speed up recursive ls by not syncpersist when we are create file as part of a loadMetadata operation. (#7782)

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-release-tarballs.go
cherry-pick from https://github.com/Alluxio/alluxio/pull/7593
=> [SMALLFIX] Include -bin in generated release tarballs (#7593)

core/common/src/main/java/alluxio/Constants.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java, dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go, underfs/cos/pom.xml, underfs/cos/src/main/java/alluxio/underfs/cos/COSInputStream.java, underfs/cos/src/main/java/alluxio/underfs/cos/COSOutputStream.java, underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java, underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystemFactory.java, underfs/cos/src/main/resources/META-INF/services/alluxio.underfs.UnderFileSystemFactory, underfs/pom.xml
Cherry-pick from #7380 to 1.8 branch
*  add the cos into underfs module
* fix the bugs based-on the review of PR https://github.com/Alluxio/alluxio/pull/7380
* fix the bugs, PR https://github.com/Alluxio/alluxio/pull/7380
* 1) Modify the underfs/pom.xml; 2) Correct indentation;
* Fix build
* change the property name
* A bunch of property key naming update
* Fix build after merge with master
=> [ALLUXIO-3223] Add the cos into underfs module (#7380)

docs/en/compute/Compute-Hadoop-MapReduce.md, docs/en/contributor/Building-Alluxio-From-Source.md, docs/en/contributor/Code-Conventions.md, docs/en/contributor/Developer-Tools.md
@aaudiber Sorry I thought I pushed these but I guess they didn't make it in the last PR
=> [DOCFIX] - Contributor improvements

docs/en/advanced/Tiered-Locality.md
=> [DOCFIX] Tiered locality doc update

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/test/java/alluxio/client/file/FileSystemContextTest.java, core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java, minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java, tests/src/test/java/alluxio/client/fs/ImpersonationIntegrationTest.java
Cherrypick of #7723 
Only conflicts in imports for FileSystemContext
=> [ALLUXIO-3284] [CHERRY-PICK] Cache contexts based on subject (#7723)

core/common/src/main/java/alluxio/exception/PreconditionMessage.java, core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java
Preconditions only work with `%s`
=> [SMALLFIX] Clean up some error messages.

core/common/src/main/java/alluxio/exception/PreconditionMessage.java, core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java
=> [SMALLFIX] Clean up some error messages. (#7902)

docs/en/Mounting-Alluxio-FS-with-FUSE.md, integration/fuse/bin/alluxio-fuse
https://alluxio.atlassian.net/browse/ALLUXIO-2231
=> [ALLUXIO-2231] support allow_other/allow_root Fuse mount options

integration/yarn/pom.xml
=> [SMALLFIX] fix integration/yarn pom file

integration/mesos/src/main/java/alluxio/mesos/AlluxioMasterExecutor.java
https://alluxio.atlassian.net/browse/ALLUXIO-3315
cherry-picking to `branch-1.8`
=> [ALLUXIO-3315] Avoid re-formatting journal on Mesos master executor start (#7839)

bin/alluxio-monitor.sh, bin/alluxio-start.sh, shell/src/main/java/alluxio/common/RpcPortHealthCheckClient.java, shell/src/main/java/alluxio/jobmaster/AlluxioJobMasterMonitor.java, shell/src/main/java/alluxio/jobmaster/JobMasterHealthCheckClient.java, shell/src/main/java/alluxio/jobworker/AlluxioJobWorkerMonitor.java, shell/src/main/java/alluxio/jobworker/JobWorkerHealthCheckClient.java, shell/src/main/java/alluxio/worker/WorkerHealthCheckClient.java, tests/src/test/java/alluxio/server/health/JobMasterHealthCheckClientIntegrationTest.java, tests/src/test/java/alluxio/server/health/JobWorkerHealthCheckClientIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3333
=> [ALLUXIO-3333]Support cluster startup monitoring for job service

core/common/src/main/java/alluxio/Configuration.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/test/java/alluxio/ConfigurationTest.java, core/common/src/test/java/alluxio/PropertyKeyTest.java, core/common/src/test/java/alluxio/security/LoginUserTest.java, core/common/src/test/java/alluxio/util/network/NetworkAddressUtilsTest.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java, core/server/worker/src/test/java/alluxio/worker/block/meta/AbstractBlockMetaTest.java, core/server/worker/src/test/java/alluxio/worker/block/meta/BlockMetaTest.java, core/server/worker/src/test/java/alluxio/worker/block/meta/StorageDirTest.java, core/server/worker/src/test/java/alluxio/worker/block/meta/StorageTierTest.java, core/server/worker/src/test/java/alluxio/worker/block/meta/TempBlockMetaTest.java, tests/src/test/java/alluxio/client/hadoop/FileSystemAclIntegrationTest.java, tests/src/test/java/alluxio/server/web/ServiceSocketBindIntegrationTest.java, tests/src/test/java/alluxio/testutils/LocalAlluxioClusterResource.java, underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-3334
=> [ALLUXIO-3334] Remove usages of empty string from configuration properties

core/common/src/main/java/alluxio/util/CommonUtils.java
=> [SMALLFIX] Increase accuracy of timeout message

core/server/master/src/main/java/alluxio/master/block/BlockMasterClientRestServiceHandler.java
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.block.BlockMasterClientRestServiceHandler#getServiceVersion
=> [SMALLFIX] Java 8 Improvement

job/common/src/main/java/alluxio/job/meta/JobInfo.java, job/server/src/main/java/alluxio/master/job/JobCoordinator.java, job/server/src/main/java/alluxio/master/job/JobMaster.java, job/server/src/test/java/alluxio/master/job/JobCoordinatorTest.java, job/server/src/test/java/alluxio/master/job/JobMasterTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3339
Approach in this work for addressing scalability of job master is mainly to improve concurrency of worker heartbeats. With these changes worker heartbeats will run concurrently and synchronize on registration of a new worker and removal of an existing [lost] worker.
Also, write path for JobInfo object is merged with JobCoordinator and synchronized there.
=> [ALLUXIO-3339] Address job master scalability

docs/_includes/Command-Line-Interface/du.md, docs/en/Command-Line-Interface.md, shell/src/main/java/alluxio/cli/fs/command/AbstractFileSystemCommand.java, shell/src/main/java/alluxio/cli/fs/command/DuCommand.java, tests/src/test/java/alluxio/client/cli/fs/command/DuCommandIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3340
=> [ALLUXIO-3340] support -h -s --memory --header options in du CLI

core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
Replace multiple if-else with switch in alluxio.client.file.BaseFileSystem#checkUri #275
=> [SMALLFIX]Replace multiple if-else with switch in alluxio.client.file.BaseFileSystem#checkUri #275

core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
Replace compare with integer.compare in alluxio.master.meta.AlluxioMasterRestServiceHandler#getTierAliasComparator #310
=> [SMALLFIX] Replace compare with integer.compare in alluxio.master.meta.AlluxioMasterRestServiceHandler#getTierAliasComparator #310

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java, core/client/fs/src/main/java/alluxio/client/file/FileInStream.java, core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/refresh/RefreshPolicy.java, core/common/src/main/java/alluxio/refresh/TimeoutRefresh.java, core/common/src/test/java/alluxio/refresh/TimeoutRefreshTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3338
=> [ALLUXIO-3338] Address client side scalability issues

core/common/src/test/java/alluxio/test/util/ConcurrencyUtils.java
I have change the code in  "core/common/src/test/java/alluxio/test/util/ConcurrencyUtils.java".
=> [SMALLFIX] Use lambda in ConcurrencyUtils.java

core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
Replace compare with integer.compare in  alluxio.worker.AlluxioWorkerRestServiceHandler#getTierAliasComparator #311
=> [SMALLFIX] A smallfix for task#311 to use Integer.compare

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
replace anonymous type with lambda in alluxio.master.file.DefaultFileSystemMaster
=> [SMALLFIX] Java 8 Improvement using Lambda Expression in DefaultFileSystemMaster.java

core/server/master/src/test/java/alluxio/master/meta/AlluxioMasterRestServiceHandlerTest.java
Replace
Gauge<Integer> filesPinnedGauge = new Gauge<Integer>() {
@Override
public Integer getValue() {
return FILES_PINNED_TEST_VALUE;
}
};
with
Gauge<Integer> filesPinnedGauge = () -> FILES_PINNED_TEST_VALUE;
=> [SMALLFIX] Java 8 Improvement: replace anonymous type with lambda in alluxio.master.meta.AlluxioMasterRestServiceHandlerTest#getMetrics #285

core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
=> [SMALLFIX] Use Long.compare to improve S3RestServiceHandler#compare

core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
[SMALLFIX] Java 8 Improvement: replace anonymous type with lambda in alluxio.worker.AlluxioWorkerProcess#AlluxioWorkerProcess #286
=> [SMALLFIX] Java 8 Improvement: replace anonymous type with lambda in alluxio.worker.AlluxioWorkerProcess#AlluxioWorkerProcess #286

docs/cn/Configuring-Alluxio-with-Ceph.md
=> [DOCFIX] Inline documentation snippets in docs/cn/Configuring-Alluxio-with-Ceph.md #303

core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
[SMALLFIX] Java 8 Improvement: replace anonymous type with lambda in alluxio.underfs.AbstractUfsManager#addMount
=> [SMALLFIX] Java 8 Improvement: replace anonymous type with lambda in alluxio.underfs.AbstractUfsManager#addMount

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java, core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3346
=> [ALLUXIO-3346] Improve error when no worker to read from UFS can be found

docs/en/advanced/Alluxio-Storage-Management.md, docs/en/advanced/Performance-Tuning.md
@apc999 @madanadit @gpang Please list any other perf tuning tips you can think of
=> [DOCFIX] Perf tuning doc

core/common/src/main/java/alluxio/PropertyKey.java, docs/_data/table/en/common-configuration.yml, docs/en/Mounting-Alluxio-FS-with-FUSE.md, integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java, integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java, integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3344
=> [ALLUXIO-3344] Fuse user group translation

job/server/src/main/java/alluxio/worker/AlluxioJobWorkerRestServiceHandler.java
replace anonymous type with lambda in alluxio.worker.AlluxioJobWorkerRestServiceHandler
=> [SMALLFIX] Java 8 Improvement:replace anonymous type with lambda in alluxio.worker.AlluxioJobWorkerRestServiceHandler

docs/cn/Command-Line-Interface.md
change several words in docs/cn/Command-Line-Interface.md
=> [SMALLFIX] Improve Chinese document to make it more native

core/server/common/src/main/java/alluxio/master/PrimarySelectorClient.java
https://alluxio.atlassian.net/browse/ALLUXIO-3350
=> [ALLUXIO-3350]Use ephemeral leader node in ZK

docs/cn/Java-Setup.md
=> [DOCFIX] Upgrade to java8 in docs/cn/Java-Setup.md

minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.AbstractLocalAlluxioCluster#startProxy #278
=> [SMALLFIX] Java 8 Improvement: replace anonymous type with lambda in alluxio.master.AbstractLocalAlluxioCluster#startProxy #278

docs/README.md
=> [DOCFIX],fix docs/README

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-3348
=> [ALLUXIO-3348] support Fuse chgrp and chown :groupName

examples/src/main/java/alluxio/cli/RunOperation.java
@aaudiber whenever you have the time PTAL, thanks!
=> [SMALLFIX] add CreateFile option to RunOperation

core/server/worker/src/main/java/alluxio/worker/block/BlockHeartbeatReport.java
I'm not the student in the class, but is interested in this project.
=> [DOCFIX]Add '-' between words in a line in BlockHeartbeatReport.java

docs/cn/api/Clients-Python.md
Change
命令：$ pip install alluxio
to
```bash
$ pip install alluxio
```
=> [DOCFIX]Update Chinese document docs/cn/Clients-Python.md

docs/cn/Overview.md
Change
[阿里巴巴](http://www.alibaba.com), [Alluxio](http://www.alluxio.com/), [百度](https://www.baidu.com),
[卡内基梅隆大学](https://www.cmu.edu/),[Google](https://www.google.com)，[IBM](https://www.ibm.com)，[Intel](http://www.intel.com/),
[南京大学](http://pasa-bigdata.nju.edu.cn/),
[Red Hat](https://www.redhat.com/)，[UC Berkeley](https://amplab.cs.berkeley.edu/)和
to
[阿里巴巴](https://www.alibaba.com/)、[Alluxio](https://www.alluxio.com/)、[百度](https://www.baidu.com/)、
[卡内基梅隆大学](https://www.cmu.edu/)、[Google](https://www.google.com/)、[IBM](https://www.ibm.com/)、[Intel](https://www.intel.com/)、
[南京大学](http://pasa-bigdata.nju.edu.cn/)、
[Red Hat](https://www.redhat.com/)、[UC Berkeley](https://amplab.cs.berkeley.edu/)和
=> [DOCFIX] Update Chinese document docs/cn/Overview.md to make it more native

core/server/worker/src/main/java/alluxio/worker/netty/BlockWriteRequest.java, core/server/worker/src/main/java/alluxio/worker/netty/Error.java, core/server/worker/src/main/java/alluxio/worker/netty/UfsFileWriteRequest.java, core/server/worker/src/main/java/alluxio/worker/netty/WriteRequest.java
Sometimes we print these in error/warning messages.
=> [SMALLFIX] Add a toString for Error and WriteRequests.

docs/cn/Overview.md
Change
(如Apache Spark，Apache MapReduce，Apache HBase，Apache Hive，Apache Flink)
to
（如 Apache Spark、Apache MapReduce、Apache HBase、Apache Hive、Apache Flink）
and change
（如Amazon S3，Google Cloud Storage, OpenStack Swift，GlusterFS，HDFS，MaprFS，Ceph，NFS，OSS）
to
（如 Amazon S3、Google Cloud Storage、OpenStack Swift、GlusterFS、HDFS、MaprFS、Ceph、NFS、OSS）
change“，” to "、"
=> [DOCFIX] Improve Chinese document docs/cn/Overview.md to make it more native

docs/cn/deploy/Running-Alluxio-on-Mesos.md
=> [SMALLFIX] fix markdown syntax

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
…ter.file.DefaultFileSystemMaster#registerGauges
=> [SMALLFIX] Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.DefaultFileSystemMaster#registerGauges

docs/cn/basic/Command-Line-Interface.md
Relpace something with real content
=> [SMALLFIX]Relpace something with real content

libexec/alluxio-config.sh
Cherry-pick https://github.com/Alluxio/alluxio/pull/7623
=> [SMALLFIX] Support for setting the JAVA_HOME environment variable in alluxio-config.sh file (#7623)

core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-3356
=> [ALLUXIO-3356] Respect hostname/port set in hdfs URI

core/server/master/src/main/java/alluxio/master/block/BlockMasterClientRestServiceHandler.java
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.block.BlockMasterClientRestServiceHandler#getBlockInfo
=> [SMALLFIX] Java 8 Improvement: replace anonymous type with lambda

shell/src/main/java/alluxio/cli/fs/FileSystemShell.java, shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShell.java
https://alluxio.atlassian.net/browse/ALLUXIO-3343
this is a cherrypick from https://github.com/Alluxio/alluxio/pull/8089 from master to branch-1.8
=> [ALLUXIO-3343] Fix the issue that help subcommand requires alluxio.master.hostname set. (#8089)

core/common/src/main/java/alluxio/Constants.java, core/common/src/main/java/alluxio/PropertyKey.java, docs/cn/Configuring-Alluxio-with-KODO.md, docs/en/Configuring-Alluxio-with-KODO.md, underfs/kodo/pom.xml, underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoClient.java, underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoInputStream.java, underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoOutputStream.java, underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoUnderFileSystem.java, underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoUnderFileSystemFactory.java, underfs/kodo/src/main/resources/META-INF/services/alluxio.underfs.UnderFileSystemFactory, underfs/kodo/src/test/java/alluxio/underfs/kodo/KodoOutputStreamTest.java, underfs/kodo/src/test/java/alluxio/underfs/kodo/KodoUnderFileSystemContractTest.java, underfs/kodo/src/test/java/alluxio/underfs/kodo/KodoUnderFileSystemFactoryTest.java, underfs/kodo/src/test/java/alluxio/underfs/kodo/KodoUnderFileSystemTest.java, underfs/pom.xml
https://alluxio.atlassian.net/browse/ALLUXIO-3347
=> [ALLUXIO-3347]Integrate the new under storage based on Qiniu Kodo to Alluxio

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, tests/src/test/java/alluxio/client/fs/FileSystemConcurrencyTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3358
=> [ALLUXIO-3358] In some cases,DefaultFileSystemMaster#listStatus throws 'Path is no longer valid, possibly due to a concurrent delete.'

docs/cn/api/Ufs-Extension-API.md
replace META_INF with META-INF in file docs/cn/DevelopingUFSExtensions.md #332
Extension will not be loaded when putting meta in META_INF, using META-INF is correct
=> [SMALLFIX] update chinese doc replace META_INF with META-INF

bin/alluxio-start.sh
https://alluxio.atlassian.net/browse/ALLUXIO-3368
=> [ALLUXIO-3368] add wc to run_safe()

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/activesync/SupportedHdfsActiveSyncProvider.java
remove some excessive logging at debug level
=> [SMALLFIX] Adjust logging messages

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java, core/common/src/main/java/alluxio/thrift/BlockHeartbeatTOptions.java, core/common/src/main/java/alluxio/thrift/BlockMasterWorkerService.java, core/common/src/main/java/alluxio/thrift/RegisterWorkerTOptions.java, core/common/src/main/java/alluxio/util/io/FileUtils.java, core/common/src/thrift/block_master.thrift, core/server/master/src/main/java/alluxio/master/block/BlockMaster.java, core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java, core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java, core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java, core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java, core/server/master/src/test/java/alluxio/master/file/replication/ReplicationCheckerTest.java, core/server/worker/src/main/java/alluxio/worker/block/AbstractBlockStoreEventListener.java, core/server/worker/src/main/java/alluxio/worker/block/BlockHeartbeatReporter.java, core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java, core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java, core/server/worker/src/main/java/alluxio/worker/block/BlockMetricsReporter.java, core/server/worker/src/main/java/alluxio/worker/block/BlockStore.java, core/server/worker/src/main/java/alluxio/worker/block/BlockStoreEventListener.java, core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java, core/server/worker/src/main/java/alluxio/worker/block/SpaceReserver.java, core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java, core/server/worker/src/main/java/alluxio/worker/block/evictor/LRFUEvictor.java, core/server/worker/src/main/java/alluxio/worker/block/evictor/LRUEvictor.java, core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTier.java, core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java, tests/src/test/java/alluxio/server/ft/MasterFaultToleranceIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3373
=> [ALLUXIO-3373] Improve handling of SSD failures

core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java, core/server/master/src/main/java/alluxio/master/AlluxioSecondaryMaster.java, core/server/master/src/main/java/alluxio/master/CoreMasterContext.java, core/server/master/src/test/java/alluxio/master/MasterTestUtils.java, tests/src/test/java/alluxio/testutils/master/MasterTestUtils.java
This makes it easier to add new things to the context
=> [SMALLFIX] Use builder pattern in CoreMasterContext

tests/src/test/java/alluxio/job/persist/PersistIntegrationTest.java
With the new async persist feature, add a test for checking persist timeout.
=> [SMALLFIX] Add test for persist timeout

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointThread.java
Improved journal exception handling by catching more types of exceptions and logging them.
=> [SMALLFIX] minor improvement on journal exception handling

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/main/java/alluxio/client/metrics/ClientMasterSync.java, core/client/fs/src/main/java/alluxio/client/metrics/MetricsMasterClient.java, core/common/src/main/java/alluxio/metrics/MetricsSystem.java, core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java
https://alluxio.atlassian.net/browse/ALLUXIO-3370
Cherry-picked from https://github.com/Alluxio/alluxio/pull/8177
=> [ALLUXIO-3370] Client metrics fixes

core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java
Cherry-picked from https://github.com/Alluxio/alluxio/pull/8185
=> [SMALLFIX] Reduce scope of MetricsStore locking to avoid deadlock (#8185)

shell/src/main/java/alluxio/cli/fs/command/CatCommand.java
=> [SMALLFIX] Cherry pick of #8190 to 1.8

core/server/worker/src/test/java/alluxio/worker/netty/ReadHandlerTest.java
java 8 Improvement: replace lambda with method
=> [SMALLFIX] Java 8 Improvement: replace lambda with method

docs/en/basic/Command-Line-Interface.md, shell/src/main/java/alluxio/cli/fs/command/PersistCommand.java, tests/src/test/java/alluxio/client/cli/fs/command/PersistCommandTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3383
=> [ALLUXIO-3383] Add a parallelism option to the persist CLI

core/server/master/src/main/java/alluxio/master/file/async/DefaultAsyncPersistHandler.java, core/server/master/src/test/java/alluxio/master/file/async/DefaultAsyncPersistHandlerTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3380
=> [ALLUXIO-3380]The master process always outputs error log "FileDoesNotExistException: inodeId XXX does not exist"

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java, core/common/src/main/java/alluxio/util/executor/ControllableQueue.java, core/common/src/main/java/alluxio/util/executor/ControllableScheduler.java, core/common/src/test/java/alluxio/util/executor/ControllableSchedulerTest.java, core/server/common/src/main/java/alluxio/master/BackupManager.java, core/server/master/src/main/java/alluxio/master/meta/DailyMetadataBackup.java, core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java, core/server/master/src/test/java/alluxio/master/meta/DailyMetadataBackupTest.java, docs/en/operation/Journal.md
https://alluxio.atlassian.net/browse/ALLUXIO-3384
cherry pick daily backup to 1.8
=> [ALLUXIO-3384] daily backup cherry-pick

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java, integration/fuse/src/main/java/alluxio/fuse/OpenFileEntry.java, integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java, tests/src/test/java/alluxio/client/fuse/FuseFileSystemIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3391
=> [ALLUXIO-3391] only blocking fuse getAttr() in async release()

core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java, core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java, core/common/src/main/java/alluxio/uri/Authority.java, core/common/src/main/java/alluxio/uri/MultiMasterAuthority.java, core/common/src/test/java/alluxio/AlluxioURITest.java, core/common/src/test/java/alluxio/uri/AuthorityTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3392
=> [ALLUXIO-3392] embedded journal uri

core/server/master/src/test/java/alluxio/master/meta/InodeLockManagerTest.java
Make sure our locks are locking
=> Add inode lock manager unit test

docs/en/compute/Deep-Learning.md, docs/en/compute/Tensorflow.md
=> [DOCFIX] Tensorflow with fuse docs

core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java, core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java, core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataReader.java, core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java
For gRPC branch merge comments in https://github.com/Alluxio/alluxio/pull/8280
@calvinjia
=> more gRPC cleanup

core/client/fs/src/main/java/alluxio/client/block/BlockMasterClientPool.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClientPool.java, core/client/fs/src/test/java/alluxio/client/file/FileSystemContextTest.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/network/netty/NettyChannelPool.java, core/common/src/test/java/alluxio/ConfigurationTest.java, tests/src/test/java/alluxio/client/fs/ConcurrentDeleteIntegrationTest.java, tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterCreateTest.java, tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterSetTtlTest.java, tests/src/test/java/alluxio/client/fs/ConcurrentRenameIntegrationTest.java, tests/src/test/java/alluxio/client/fs/FileInStreamConcurrencyIntegrationTest.java
https://alluxio.atlassian.net/browse/ALLUXIO-3394
=> [ALLUXIO-3394] GC fs master client

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, tests/src/test/java/alluxio/client/fs/PinIntegrationTest.java
=> [SMALLFIX]  Ensure pinning and unpinning to recursively sync before the pin and unpin

shell/src/main/java/alluxio/cli/fs/command/CpCommand.java, tests/src/test/java/alluxio/client/cli/fs/command/CopyFromLocalCommandIntegrationTest.java, tests/src/test/java/alluxio/client/cli/fs/command/CpCommandIntegrationTest.java
Cherry picked from https://github.com/Alluxio/alluxio/pull/8305.
=> [ALLUXIO-3395] Concurrent copy from local

alluxio-ui/pom.xml
Tests seem to be preventing people from building. I will fix asap.
=> Disable UI testing temporarily

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
The original cherry-pick mistakenly used merge. cherry pick to 1.8 branch
=> [CHERRY-PICK3] support Fuse chgrp and chown :groupName 

shell/src/main/java/alluxio/cli/fs/command/CopyFromLocalCommand.java, shell/src/main/java/alluxio/cli/fs/command/CpCommand.java, tests/src/test/java/alluxio/client/cli/fs/command/CopyFromLocalCommandIntegrationTest.java
Cherrypick from https://github.com/Alluxio/alluxio/pull/8309.
=> [CHERRYPICK] Copy from local cherry pick

.gitignore
=> [SMALLFIX] Add port coordination to gitignore

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
=> Fix when we should reset state.

docs/cn/deploy/Running-Alluxio-On-Kubernetes.md, docs/en/deploy/Running-Alluxio-On-Kubernetes.md
[SMALLFIX] Update docs to use `--from-env-file`
=> [SMALLFIX][CHERRYPICK] Update k8s docs to use `--from-env-file` (#8327)

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java, core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointThread.java, core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSnapshot.java, tests/src/test/java/alluxio/server/ft/journal/MultiMasterJournalTest.java
Also the bug fix for the bug introduced by resetting master state.
=> [CHERRYPICK] Reset master state before recovering from a checkpoint

underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
`UNDERFS_GCS_OWNER_ID_TO_USERNAME_MAPPING` -> `UNDERFS_S3_OWNER_ID_TO_USERNAME_MAPPING`
=> Correct the owner id to username mapping in S3AUnderFileSystem

shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
cherry-pick of https://github.com/Alluxio/alluxio/commit/34d1dadb1c27829341bbbca2ae701ea86ff0c7da
=> display detailed file number in slow fs ls command (#8364)

shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
cherry-pick of https://github.com/Alluxio/alluxio/commit/38bd04c306248b1e27a9b88a5fa40838e74d5493
=> fix fs ls console message (#8368)

core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
pure refactor to make this code way more readable
=> Improve apply method names

core/base/src/main/java/alluxio/exception/status/AlluxioStatusException.java, core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java, core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java, core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java, core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java, core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java, core/common/src/main/java/alluxio/security/authentication/SaslStreamClientDriver.java, core/common/src/main/java/alluxio/security/authentication/SaslStreamServerDriver.java, core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java, shell/src/main/java/alluxio/common/RpcPortHealthCheckClient.java
* Add tracing for channel pooling/authentication
* Trace channel authentication failure with target host
* Repackage channel authentication error with inner cause
=> Add tracing for channel pooling/authentication (#8382)

core/base/src/main/java/alluxio/exception/ExceptionMessage.java, job/common/src/main/java/alluxio/job/migrate/MigrateConfig.java, job/server/src/main/java/alluxio/job/migrate/MigrateCommand.java, job/server/src/main/java/alluxio/job/migrate/MigrateDefinition.java, job/server/src/main/resources/META-INF/services/alluxio.job.JobDefinition, job/server/src/test/java/alluxio/job/migrate/MigrateDefinitionRunTaskTest.java, job/server/src/test/java/alluxio/job/migrate/MigrateDefinitionSelectExecutorsTest.java, shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java, tests/src/test/java/alluxio/job/migrate/MigrateIntegrationTest.java
`alluxio fs distributedCp src dst` will instruct job workers to copy files under src to dst in parallel, the parallel copy happens at file level, not block level.
=> Add distributed copy command.

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java
@madanadit @gpang PTAL. ActiveSync fixes cherrypicked to master.
=> [CHERRYPICK] ActiveSync fixes

core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
We retry `alluxio.exception.status.UnavailableException`, but not the gRPC `StatusRuntimeException` equivalent. This converts the gRPC exception to an `AlluxioStatusException` so that we can properly retry when the status is `Unavailable`
=> Convert grpc to alluxio exceptions in polling ping

docs/en/FAQ.md
=> [DOCFIX] Update FAQ doc

tests/src/test/java/alluxio/client/fs/ConcurrentRecursiveCreateTest.java
This tests for bug https://github.com/Alluxio/alluxio/issues/8430 discovered in branch-1.8. The bug was accidentally fixed by master locking changes
=> Add test for concurrent recursive creates

docs/en/api/FS-API.md
Update the FS API docs to use the new options type.
=> Update FS API docs

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
https://github.com/Alluxio/alluxio/issues/8254 Incorrect directories created metric
=> Remove unnecessary directory created metrics inc

docs/en/advanced/Alluxio-Storage-Management.md
We've updated the section name.
=> Fix broken link

alluxio-ui/common/src/components/Footer/Footer.tsx, alluxio-ui/common/src/components/Header/Header.tsx, alluxio-ui/master/src/constants/data/footerNavigation.tsx, alluxio-ui/master/src/containers/App/__snapshots__/App.test.tsx.snap, alluxio-ui/master/src/containers/pages/Browse/__snapshots__/Browse.test.tsx.snap, alluxio-ui/master/src/containers/pages/Configuration/__snapshots__/Configuration.test.tsx.snap, alluxio-ui/master/src/containers/pages/Data/__snapshots__/Data.test.tsx.snap, alluxio-ui/master/src/containers/pages/Logs/__snapshots__/Logs.test.tsx.snap, alluxio-ui/master/src/containers/pages/Metrics/__snapshots__/Metrics.test.tsx.snap, alluxio-ui/master/src/containers/pages/Overview/__snapshots__/Overview.test.tsx.snap, alluxio-ui/master/src/containers/pages/Workers/__snapshots__/Workers.test.tsx.snap, alluxio-ui/npm-shrinkwrap.json, alluxio-ui/worker/src/constants/data/footerNavigation.tsx, alluxio-ui/worker/src/containers/App/__snapshots__/App.test.tsx.snap, alluxio-ui/worker/src/containers/pages/BlockInfo/__snapshots__/BlockInfo.test.tsx.snap, alluxio-ui/worker/src/containers/pages/Logs/__snapshots__/Logs.test.tsx.snap, alluxio-ui/worker/src/containers/pages/Metrics/__snapshots__/Metrics.test.tsx.snap, alluxio-ui/worker/src/containers/pages/Overview/__snapshots__/Overview.test.tsx.snap
Update header and footer to accept attributes.
Update all pages' test snapshots (all use the footer).
=> Add a slack link in the application footer

core/common/src/main/java/alluxio/conf/PropertyKey.java
@calvinjia @ggezer removed property not in use
=> Remove left over property

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go, underfs/hdfs/pom.xml, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystemFactory.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsVersion.java
Allow users to build an HDFS UFS module of their own
Remove dependency on HdfsVersion.java
Add logger classes to HdfsVersion.java
=> Enable support for custom UFS jar versions

core/server/master/src/test/java/alluxio/master/metastore/caching/CachingInodeStoreTest.java
need to add 1 to count the inode added in the `@Before`
=> Fix flaky test

bin/alluxio, core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java, docs/_data/table/Developer-Tips.csv, docs/_data/table/cn/Developer-Tips.yml, docs/_data/table/en/Developer-Tips.yml, docs/cn/contributor/Code-Conventions.md, docs/en/contributor/Developer-Tools.md
- Removed the ./bin/alluxio loadUfs command
- Removed references throughout documentation (en and cn)
Fixes #8479
=> [#8479] Remove loadUfs command

docs/en/ufs/S3.md
Improves the flow of the s3 documentation.
=> Update s3 docs

docs/en/ufs/Minio.md
Minor improvements for style in Minio docs. Added a section on verifying the setup once the user has entered the configuration.
=> [DOCFIX] Improve Minio docs

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java, core/common/src/test/java/alluxio/underfs/AbstractUnderFileSystemContractTest.java
* Fix list recursive for object store
* Improve lsr testing
* Use normalize to add the path separator
=> Fix list recursive for object store (#8491)

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/test/java/alluxio/ConfigurationTestUtils.java, core/common/src/test/java/alluxio/master/MasterInquireClientTest.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java, core/server/master/src/test/java/alluxio/master/file/PersistenceTest.java, core/server/master/src/test/java/alluxio/master/file/replication/ReplicationCheckerTest.java, minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java, minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java, minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
=> [#8483] Change default journal type to EMBEDDED

underfs/glusterfs/src/main/java/alluxio/underfs/glusterfs/GlusterFSUnderFileSystem.java
Alluxio/new-contributor-tasks/ALLUXIO-2930
https://alluxio.atlassian.net/browse/ALLUXIO-2930
=> [SMALLFIX] Improve comment style in GlusterFSUnderFileSystem

underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java
=> Fix pagination for listing COS

core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/security/authorization/Mode.java, core/common/src/test/java/alluxio/security/authorization/ModeTest.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java, tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java, underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Cherry-pick https://github.com/Alluxio/alluxio/pull/8520
=> Inherit owner/group if not discovered from ufs

docs/en/ufs/Azure-Blob-Store.md
- Minor tuning on docs on Azure blob store
=> Update documentation on using Azure blob store as UFS

docs/en/operation/Troubleshooting.md
@ggezer Could you take a look at the threadpool portion and see if there are any details you want to add?
=> Update troubleshooting doc

bin/alluxio
=> Fix formatting multiple masters

docs/en/ufs/S3.md
@apc999 let me know if the layout looks okay to you. then i'll copy this over to other object store docs
=> [DOCFIX] Add troubleshooting doc for object store

docs/_config.yml, docs/_includes/base.html, docs/_layouts/global.html
This change allows us to set baseurl in `_config.yml`. Setting baseurl
gives us the ability to compile the documentation site at different
locations. i.e. `/docs/1.8`, `/docs/master`, `/docs/latest`, by simply changing
the value in `_config.yml`.
=> Support base url in documentation

docs/_config.yml, docs/_layouts/global.html
Replace `..` with `{{site.baseurl}}`. The value for `site.baseurl` can be
set within `_config.yml`. This makes building docs for other locations
simpler.
=> Add baseurl support to docs - 1.6

bin/alluxio-masters.sh, bin/alluxio-workers.sh
=> Add more accurate stdout log for format command when ssh fails

core/client/fs/src/main/java/alluxio/client/MetaMasterClient.java, core/client/fs/src/main/java/alluxio/client/RetryHandlingMetaMasterClient.java, shell/src/main/java/alluxio/cli/fsadmin/command/BackupCommand.java, tests/src/main/java/alluxio/master/backcompat/BackwardsCompatibilityJournalGenerator.java, tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java, tests/src/test/java/alluxio/server/ft/journal/JournalCheckpointIntegrationTest.java, tests/src/test/java/alluxio/server/ft/journal/JournalMigrationIntegrationTest.java
This is consistent with how other clients take options
=> Change meta master client to use BackupOptions for backup RPC

docs/cn/deploy/Running-Alluxio-on-Mesos.md
In file docs/cn/deploy/Running-Alluxio-on-Mesos.md, replace all sentences like `{% include *.md %}` with the real contents.
=> [DOCFIX] Inline documentation code snippets in docs

docs/_plugins/relativize_url.rb
@ZacBlanco @apc999 
porting fix from https://github.com/Alluxio/alluxio/commit/abd316a240a55770a01f4506931b31caeae95687#diff-bf74dfaa927f6277038571d9a7b0c081
=> Fix relativize_url.rb for doc generation

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java, core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalWriter.java
=> Fix Raft Journal duplicate shutdown server issue

core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java, minicluster/src/main/java/alluxio/multi/process/PortCoordination.java, tests/src/test/java/alluxio/server/configuration/ConfigCheckerIntegrationTest.java
Standby master should register with leader master when HA mode is enabled (Zookeeper or Embedded journal)
=> [SMALLFIX] Support embedded journal HA mode in master register

core/common/src/main/java/alluxio/AbstractClient.java
Sometimes the `InetSocketAddress` given to the client is not resolved, causing gRPC to panic when connecting to the server. This change adds a retry mechanism and force a resolution of the hostname before performing connect.
=> Fix UnresolvedAddressException connecting to job master

bin/alluxio-masters.sh
Previously, we would start SecondaryMaster processes instead
of AlluxioMaster processes on all hosts in conf/masters
except the first. When using embedded journal, it makes more
sense to start regular AlluxioMaster processes to support
high availability.
=> Start multiple regular masters when using embedded journal

core/base/src/main/java/alluxio/master/file/StartupConsistencyCheck.java
Del "AlluxioURI" in "Status.RUNNING"
=> [SMALLFIX] Replace explicit type argument with lamda

core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockStoreMeta.java
…rker/src/main/java/alluxio/worker/block/DefaultBlockStoreMeta.java#getDirectoryPathsOnTiers
=> [SMALLFIX] Replace with Map.computeIfAbsent

core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
Replace
```java
Map<String, Counter> counters = mr.getCounters(new MetricFilter() {
@Override
public boolean matches(String name, Metric metric) {
return !(name.endsWith("Ops"));
}
});
Map<String, Counter> rpcInvocations = mr.getCounters(new MetricFilter() {
@Override
public boolean matches(String name, Metric metric) {
return name.endsWith("Ops");
}
});
```
with
```java
Map<String, Counter> counters = mr.getCounters((name, metric) -> !(name.endsWith("Ops")));
Map<String, Counter> rpcInvocations = mr.getCounters((name, metric) -> name.endsWith("Ops"));
```
=> [SMALLFIX] Replace anonymous type with lambda in getWebUIMetrics

job/common/src/main/java/alluxio/job/util/TimeSeries.java
in alluxio/job/common/src/main/java/alluxio/job/util/TimeSeries.java
=> [SMALLFIX] Replace with Map.getOrDefault

core/common/src/main/java/alluxio/underfs/Fingerprint.java
Add @Nullable annotation if the method may return null in /alluxio/core/common/src/main/java/alluxio/underfs/Fingerprint.java
=> [SMALLFIX] Update Fingerprint.java

core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java
The reauthentication code is missing after some merge conflicts. Adding it back.
=> Fix gRPC reauthentication

core/common/src/test/java/alluxio/test/util/ConcurrencyUtils.java
in file alluxio/core/common/src/test/java/alluxio/test/util/ConcurrencyUtils.java
Replace    final List<Throwable> exceptions = Collections.synchronizedList(new ArrayList<Throwable>());
with    final List<Throwable> exceptions = Collections.synchronizedList(new ArrayList<>());
=> [SMALLFIX]Replace explicit type with argument with <>

core/client/fs/src/test/java/alluxio/client/block/policy/LocalFirstPolicyTest.java
Modified in alluxio/core/client/fs/src/test/java/alluxio/client/block/policy/LocalFirstPolicyTest.java
=> [SMALLFIX] Use static imports in LocalFirstPolicyTest

core/server/master/src/main/java/alluxio/master/MasterUtils.java
It's a new contributor task from:
https://github.com/Alluxio/new-contributor-tasks/issues/394
=> [SMALLFIX] Use lambda in alluxio.master.MasterUtils#createMasters

core/common/src/main/java/alluxio/PropertyKey.java, underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
* Make GCS folder suffix configurable
* Copy paste error
=> Make GCS folder suffix configurable (#8355)

minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java
This is needed to fix the build
=> Fix import

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
Fix for https://github.com/Alluxio/alluxio/issues/8572
=> Initialize RAFT journal lazily

core/common/src/test/java/alluxio/security/LoginUserTest.java
Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/security/LoginUserTest.java.
Change 'import org.junit.Assert' to 'import static org.junit.Assert.assertNotNull' and 'import static org.junit.Assert.assertEquals'.
AND update relative methods.
AND Put the static imports before non-static imports.
=> [SMALLFIX] Change source code

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
=> Fix the wrong argument in UfsManager.addMount()

core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java, core/client/fs/src/main/java/alluxio/client/file/options/OutStreamOptions.java, core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java, core/client/fs/src/test/java/alluxio/client/file/options/OutStreamOptionsTest.java
Fix for https://github.com/Alluxio/alluxio/issues/8404
=> Propagate common options for async persist request

.gitignore
removes annoying untracked user directory
=> [SMALLFIX] Fix .gitignore to include userlog directory

docs/en/ufs/HDFS.md
Add a section in HDFS UFS page for using Hadoop native library.
=> Add a section for using Hadoop native library

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java, core/server/common/src/main/java/alluxio/underfs/UfsManager.java
https://github.com/Alluxio/alluxio/issues/8916
=> Enable managed-blocking for object stores only

bin/alluxio
Fixes https://github.com/Alluxio/alluxio/issues/8915
alluxio copyDir files to masters(HA)
=> Fix cmd alluxio copyDir include masters

core/common/src/test/java/alluxio/wire/AlluxioProxyInfoTest.java
Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/wire/AlluxioProxyInfoTest.java
=> [SMALLFIX] Use static test imports for AlluxioProxyInfoTest

core/common/src/test/java/alluxio/underfs/UnderFileSystemTest.java
…n/src/test/java/alluxio/underfs/UnderFileSystemTest.java
=> [SMALLFIX]Use static test imports for UnderFileSystemTest

core/server/master/src/main/java/alluxio/master/file/BlockDeletionContext.java
replace lambda with method reference in /alluxio/core/server/master/src/main/java/alluxio/master/file/BlockDeletionContext.java#registerBlocksForDeletion
Change
blockIds.forEach(id -> registerBlockForDeletion(id));
to
blockIds.forEach(this::registerBlockForDeletion);
=> [SMALLFIX] Replace lambda with method reference

core/common/src/main/java/alluxio/AbstractClient.java
alluxio/core/common/src/main/java/alluxio/AbstractClient.java#AbstractClient 
Replace
mContext = Preconditions.checkNotNull(context);
with
mContext = Preconditions.checkNotNull(context, "context");
=> [SMALLFIX]Supply the name of variable to Preconditions

docs/cn/deploy/Running-Alluxio-Locally.md
update some contents at docs/cn/deploy/Running-Alluxio-Locally.md
=> [DOCFIX] Update docs/cn/deploy/Running-Alluxio-Locally.md

docs/en/ufs/MapR-FS.md
Partial substitution to a part of a certain profile.
=> [DOCFIX] Inline documentation code snippets in MapR-FS.md

shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
=> [SMALLFIX] Fix shell command ls sort by size (#8553)

docs/en/Configuring-Alluxio-with-GCS.md
https://alluxio.atlassian.net/browse/ALLUXIO-2923
=> [SMALLFIX] Simplify doc for gcs

docs/en/deploy/Running-Alluxio-On-Docker.md
This reflects the changes from https://github.com/Alluxio/alluxio/pull/8614 into branch-2.0-preview
=> Update docker doc in branch-2.0-preview

core/common/src/test/java/alluxio/metrics/MetricsConfigTest.java
Changed some sentences corresponding to the package "org.junit.Assert".
=> [SMALLFIX]Update MetricsConfigTest.java

core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java
https://github.com/Alluxio/new-contributor-tasks/issues/481
Use the method mentioned in the above url to upgrade the Java syntax.
=> [SMALLFIX] Replace lambda with new method

docs/cn/deploy/Running-Alluxio-Fault-Tolerant-on-EC2.md
Change Running-Alluxio-Fault-Tolerant-on-EC2.md
=> [SMALLFIX]Change Running-Alluxio-Fault-Tolerant-on-EC2.md

docs/cn/compute/Presto.md, docs/cn/compute/Spark.md
Update the Chinese documents of Presto and Spark for Alluxio 1.8.
=> [DOCFIX] Update cn docs Presto.md and Spark.md

docs/cn/Getting-Started.md, docs/cn/Overview.md
Update the Chinese documents of Getting-Started and Overview for Alluxio 1.8.
=> [DOCFIX] Update cn docs Getting-Started and Overview

core/client/fs/src/test/java/alluxio/client/block/stream/BlockInStreamTest.java
Change
`import org.junit.Assert;`
to
`import org.junit.Assert;`
**AND**
Update all
`Assert.{{ method }}*`
to
`{{ method }}*[](url)`
=> Use static imports for standard test utilities

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/server/common/src/main/java/alluxio/master/BackupManager.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java, core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
Fixes https://github.com/Alluxio/alluxio/issues/8571
=> Do multi-threaded backups

docs/en/deploy/Running-Alluxio-On-Docker.md
Some embedded journal docs slipped in when cherry-picking from master
=> Fix docker doc

docs/en/compute/AWS-EMR.md, integration/emr/alluxio-emr.sh, integration/emr/alluxio-presto.json
Docs for AWS EMR integration. Bootstrap for Alluxio and configurations for Presto/Glue provided.
=> Add EMR bootstrap scripts and docs

alluxio-ui/npm-shrinkwrap.json, core/server/master/src/main/java/alluxio/master/file/meta/LazyUfsBlockLocationCache.java
Use the @Nullable annotation for all methods which may return null in /alluxio/core/server/master/src/main/java/alluxio/master/file/meta/LazyUfsBlockLocationCache.java
=> [SMALLFIX]Use the @Nullable annotation

integration/kubernetes/conf/alluxio.properties.template
Fix spec to use JAVA_OPTS instead of capitalized env variables following https://github.com/Alluxio/alluxio/pull/9040
=> Use JAVA_OPTS for k8s config

underfs/web/src/main/java/alluxio/underfs/web/WebUnderFileSystem.java, underfs/web/src/main/java/alluxio/underfs/web/WebUnderFileSystemFactory.java
=> Fix WebUnderFileSystem after removing UFS Singleton

docs/cn/ufs/COS.md, docs/cn/ufs/OSS.md
Some links(i.e html anchors) of the page are unavailable
=> [DOCFIX] Fix the url link related issues for object store underfs

core/common/src/main/java/alluxio/resource/DynamicResourcePool.java, docs/cn/advanced/Security.md
=> Fix Chinese character errors in Security.md

docs/en/advanced/Performance-Tuning.md
Documents the newly added async through + persist on rename feature.
=> Add docs for optimized commits for object stores

core/server/master/src/test/java/alluxio/master/journal/ufs/UfsJournalLogWriterTest.java, underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
https://alluxio.atlassian.net/browse/ALLUXIO-3376
=> Optimize read and write performance of LocalUnderFileSystem

bin/alluxio-mount.sh
behavior before this change: if we have multiple path on tier 0, mounting will fail
behavior after this change: if we have multiple path on tier 0, we will mount any path that has a medium type of "MEM"
=> Use medium type to determine whether we mount a path as ramdisk or not

docs/README.md, docs/_includes/Command-Line-Interface/alluxio-path.md
Fixed Alluxio/new-contributor-tasks#399
=> [DOCFIX] Improve allxio-path.md and docs/README.md

core/common/src/main/java/alluxio/wire/WorkerInfo.java, core/common/src/main/java/alluxio/wire/WorkerNetAddress.java, core/server/master/pom.xml, core/server/proxy/pom.xml, core/server/proxy/src/main/java/alluxio/proxy/PathsRestServiceHandler.java, core/server/proxy/src/main/java/alluxio/proxy/StreamsRestServiceHandler.java, job/server/pom.xml, job/server/src/main/java/alluxio/master/AlluxioJobMasterRestServiceHandler.java, job/server/src/main/java/alluxio/worker/AlluxioJobWorkerRestServiceHandler.java
Adds documentation for the user facing rest endpoints. All non-internal rest endpoints should be documented after this PR is merged.
=> Add paths and streams api to rest docs

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
=> Catch the exception for setting default acl for a file

docs/cn/ufs/WEB.md, docs/en/ufs/WEB.md
add brief docs for both EN and CN versions
=> Add docs for WEB underfs

core/common/src/main/java/alluxio/util/webui/UIFileInfo.java
Fix Alluxio/new-contributor-tasks#455.
Java 8 improvement: replace with sinle Map method in alluxio/core/common/src/main/java/alluxio/util/webui/UIFileInfo.java#addBlock
=> [SMALLFIX] Replace with sinle Map method in UIFileInfo.java

docs/en/deploy/Running-Alluxio-On-Docker.md
Lets the user copy paste all the commands in the getting started portion.
=> Simplify the docker tutorial

docs/en/ufs/Ufs-Extension-API.md, docs/en/ufs/Ufs-Extensions.md
Update the UFS extension documentations
=> [DOCFIX] Update the UFS extension documentation

integration/kubernetes/alluxio-worker.yaml.template
set worker hostname to physical host ip
=> Fix k8s worker hostname

tests/src/test/java/alluxio/client/rest/TestCase.java
[SMALLFIX] Replace multi if with switch to make it more readable in alluxio/tests/src/test/java/alluxio/client/rest/TestCase.java
=> Use switch for readability in TestCase.java

docs/en/ufs/Qiniu-KODO.md
Move `docs/en/Configuring-Alluxio-with-KODO.md` to `docs/en/ufs/Qiniu-KODO.md`
=> Put KODO doc into the right directory

bin/alluxio-start.sh
Check if Alluxio is in EMBEDDED mode and if so, create the journal directory if it doesn't exist.
=> [SMALLFIX] Create journal directory on startup with Embedded

bin/alluxio-start.sh
Extra if and bad tab/spaces caused 'alluxio-start.sh to fail'
=> Remove extra if statement

core/common/src/main/java/alluxio/conf/InstancedConfiguration.java, docs/en/api/FS-API.md
Adds docs about modifying configuration programmatically.
=> Add docs for instanced conf

core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java
Fix for https://github.com/Alluxio/alluxio/issues/9278
=> Enable gRPC resolver for unresolved inet addresses

docs/en/basic/Web-Interface.md
Made some minor tweaks - typos
=> [DOCFIX] Update web interface doc

core/common/src/test/java/alluxio/util/IdUtilsTest.java
Task: https://github.com/Alluxio/new-contributor-tasks/issues/546
=> [SMALLFIX] Use static imports for standard test in IdUtilsTest

docs/en/basic/Command-Line-Interface.md, docs/en/contributor/contributor-tools.md
=> [DOCFIX] Add new sections to CLI docs

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java
=> Change the order that we reset state

docs/en/Overview.md
=> [DOCFIX]Improve the Overview page

docs/en/deploy/Running-Alluxio-On-Mesos.md
pr-link: Alluxio/alluxio#9272
change-id: cid-a2af7961c51306b7aaee8cee6dbffa2615e15660
=> [DOCFIX] Update Mesos doc

docs/en/ufs/Qiniu-KODO.md
- jenkins DocPublish build caught an issue with a case-sensitive path
- @ns1123 FYI
=> [DOCFIX] Fix relative path url

core/common/src/main/java/alluxio/grpc/GrpcChannel.java, core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java, core/common/src/main/java/alluxio/security/authentication/DefaultSaslHandshakeClientHandler.java, core/common/src/main/java/alluxio/security/authentication/SaslHandshakeClientHandler.java, core/common/src/main/java/alluxio/security/authentication/SaslStreamClientDriver.java, core/common/src/main/java/alluxio/security/authentication/SaslStreamServerDriver.java
Main purpose of this PR is to make gRPC authentication tracing to contain channel information in order to improve debugging.
=> Improve channel tracking for gRPC authentication traces

core/base/src/main/java/alluxio/exception/PreconditionMessage.java, core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTier.java, core/server/worker/src/test/java/alluxio/worker/block/meta/StorageTierTest.java
@ns1123 I will add a test case after this.
=> Add error message and better error checking

core/server/worker/src/main/java/alluxio/worker/block/BlockLockManager.java
ASYNC_THOUGH write type adds a lot of pressure to the `BlockLockManager`. The previous `synchronized` lock will cause some operations to unfairly waiting for the lock.
=> Change Lock in BlockLockManager to reentrantReadWriteLock

docs/en/deploy/Running-Alluxio-On-Kubernetes.md
Reminder to avoid a common mistake.
=> Clarify configuration requirements for k8s

core/server/worker/src/main/java/alluxio/worker/AlluxioWorker.java, job/server/src/main/java/alluxio/worker/AlluxioJobWorker.java
Fix https://github.com/Alluxio/alluxio/issues/9309.
Add "Please make sure that Alluxio master is running" to error message
=> Make message more helpful on failure of loading cluster default conf

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go, docs/en/compute/AWS-EMR.md
Include EMR scripts in generate-tarball
Fix docs to provide more information on bootstrap arguments
=> Include EMR scripts in generate-tarball

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java, integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java
=> Support specifying mode when create new file by Alluxio FUSE

docs/resources/pr/pr_title_words.md
=> Update PR title allowed words

tests/src/test/java/alluxio/server/ft/journal/ufs/UfsConfigurationJournalTest.java
Fix the integration test added in https://github.com/Alluxio/alluxio/pull/9413
=> Fix integration test

tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterUtils.java
Fix Alluxio/new-contributor-tasks#436.
Replace with lambda in alluxio/tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterUtils.java#unaryOperation#436
=> [SMALLFIX] Replace with lambda in ConcurrentFileSystemMasterUtils.java

bin/alluxio-monitor.sh
Fix https://github.com/Alluxio/alluxio/issues/9355
=> Do parallelize node monitoring during startup

docs/en/advanced/Alluxio-Storage-Management.md
=> Fix typo in storage management

core/base/src/main/java/alluxio/exception/ExceptionMessage.java, core/common/src/main/java/alluxio/RuntimeConstants.java, core/common/src/main/java/alluxio/security/authentication/ImpersonationAuthenticator.java
- Put more details to explain impersonation failure with a link to documentation on impersonation
- fix a wrong URL to `ALLUXIO_DEBUG_DOCS_URL`
=> Update exception messages on impersonation failure

core/base/pom.xml, core/client/fs/pom.xml, core/client/hdfs/pom.xml, core/common/pom.xml, pom.xml
- Add direct dependencies in modules in client, to prevent transitive dependencies introduce jar hell on conflict. I run `mvn dependency:analyze` to collect "Undeclared but used" dependencies 
- Fix #9403
=> Update depencencies in POM files in client module

underfs/hdfs/pom.xml
Follow up of PR #9428 to fix Issue https://github.com/Alluxio/alluxio/issues/9416
=> Fix ufs.hadoop.version in underfs/hdfs module

job/client/src/main/java/alluxio/worker/job/RetryHandlingJobMasterClient.java
Fixed Alluxio/new-contributor-tasks#452
=> Consolidate code in RetryHandlingJobMasterClient

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java, integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java
Signed-off-by: hongtongliu <hongtongliu@126.com>
Fix #9415
=> Support limit of name length by Alluxio FUSE #9415

docs/en/Getting-Started.md, docs/en/Overview.md
update getting started and overview with link to website post @haoyuan @ZacBlanco
=> [DOCFIX] Add links to alluxio-presto-sandbox guide

integration/kubernetes/alluxio-worker.yaml.template
Fix job worker java opts reported in https://github.com/Alluxio/alluxio/issues/9409
=> Fix k8s job worker hostname

docs/en/compute/AWS-EMR.md, integration/emr/alluxio-emr.sh
Includes Bin's fixes to the shellscript
Remove curl from Master Status check logic (AWS updated curl version which caused an error)
Remove monitor to prevent ssh attempt
=> Fix AWS EMR boostrap script and doc

core/server/master/src/main/java/alluxio/master/AlluxioSecondaryMaster.java, minicluster/src/main/java/alluxio/master/LocalAlluxioMaster.java, tests/src/test/java/alluxio/server/ft/journal/MultiMasterJournalTest.java, tests/src/test/java/alluxio/server/ft/journal/ufs/SecondaryMasterTest.java, tests/src/test/java/alluxio/testutils/IntegrationTestUtils.java
Cherry-pick of Alluxio/alluxio#8391
Cherry-pick commit is Alluxio/alluxio@14dc0bd30b358bc235575db14ce3706247357d0e
=> Fix secondary master to create checkpoints

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java, integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java
cherry-pick of #8155
cherry-pick commit is 0cfc866765
=> Fix fuse du command (#8155)

webui/common/src/components/FileView/FileView.test.tsx, webui/common/src/components/FileView/FileView.tsx, webui/common/src/components/FileView/__snapshots__/FileView.test.tsx.snap, webui/common/src/components/Paginator/Paginator.tsx, webui/master/src/containers/pages/Browse/Browse.tsx, webui/master/src/containers/pages/Browse/__snapshots__/Browse.test.tsx.snap, webui/master/src/containers/pages/Logs/Logs.tsx, webui/worker/src/containers/pages/Logs/Logs.tsx
- change for #9481 
- remove button disable logic for `FileView` and `Browse`
- kept disable logic in `Paginator` but changed color of selected item for extra clarity
=> Remove disabling of web ui buttons

integration/fuse/bin/alluxio-fuse, shell/src/main/java/alluxio/cli/fs/FileSystemShell.java
Cherry-pick of Alluxio/alluxio#8365
Cherry-pick commit is Alluxio/alluxio@4af760027df217f5833091465deaf33b77853869
=> Improve the alluxio-fuse script

integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java
cherry-pick of #8194
cherry-pick of commit 5811e1406fe8f8dea453c657b3ccbb62e3fab72d
=> Improve fuse integration test and unit test (#8194)

core/server/common/src/main/java/alluxio/master/PrimarySelectorClient.java
After bumping zk client version to 3.5.5, leader election was broken
against 3.4.x servers.
This fix restores the support by making sure unsupported features are
not used in write path.
pr-link: Alluxio/alluxio#9486
change-id: cid-55abefd1d6aa0f04a748e521566a3f939a5c6310
=> Support writing to zk 3.4.x servers
