core/common/src/main/java/alluxio/grpc/GrpcChannel.java, core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java, core/common/src/test/java/alluxio/grpc/GrpcManagedChannelPoolTest.java, job/server/src/main/java/alluxio/master/FaultTolerantAlluxioJobMasterProcess.java
ChannelKey's equals() method was wrong and was missing hashcode() implementation. This caused gRPC channel pooling to always create new managed channel upon every request. This PR fixes it and adds further optimization to delay actual channel destruction.
=> Fix gRPC channel pooling

core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClientPool.java, core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java, core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java, core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataReader.java, core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java, core/client/fs/src/main/java/alluxio/client/file/FileInStream.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/common/src/main/java/alluxio/PropertyKey.java, core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java, core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java, core/common/src/main/java/alluxio/resource/DynamicResourcePool.java, core/common/src/test/java/alluxio/resource/DynamicResourcePoolTest.java, job/server/src/main/java/alluxio/job/replicate/EvictDefinition.java
- Added an option to not reuse same gRPC channel for streaming data.
- Create a worker client pool to reuse the worker client if possible.
=> Use client pool for gRPC streaming

core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java, core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClientPool.java, core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java, core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java, core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java, core/common/src/main/java/alluxio/grpc/ChannelHealthChecker.java, core/common/src/main/java/alluxio/grpc/GrpcChannel.java, core/common/src/main/java/alluxio/security/authentication/AuthenticatedUserInjector.java
Fixing some issues that are discovered by issues in worker fault tolerance:
- Close BlockWorker clients before releasing when they are faulted.
- Authenticate bi-di calls before creating the stream
=> Remove blockworker upon failure + Autheticate bi-di calls before creating stream

core/common/src/main/java/alluxio/PropertyKey.java, docs/_data/table/en/common-configuration.yml, docs/en/api/FUSE-API.md, integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java, integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java, integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java
The previous user group mapping does not work, so I also think it's a bug. In addition, the user group translation is mistakenly included in the 1.8 doc (and a user asked about it in mailing list before) so we should cherry pick it to 1.8.
=> [CHERRY-PICK] Fuse 2: fuse user group mapping

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
The `CommonUtils.waitFor` in master branch throw TimeOutException when timeout, but return false in 1.8 branch.
=> [SMALLFIX] Fuse wait for fix

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/underfs/MultiRangeObjectInputStream.java, underfs/cos/src/main/java/alluxio/underfs/cos/COSInputStream.java, underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java, underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoInputStream.java, underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoUnderFileSystem.java, underfs/oss/src/main/java/alluxio/underfs/oss/OSSInputStream.java, underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java, underfs/oss/src/test/java/alluxio/underfs/oss/OSSInputStreamTest.java, underfs/swift/src/main/java/alluxio/underfs/swift/SwiftInputStream.java, underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
This fix adds the USER_MULTI_RANGE_CHUNK_SIZE_BYTES property key.
It should now be used in place of the block size parameter wen creating
MultiRangeObjectInputStreams. The default for the property key is the
same as USER_BLOCK_SIZE_BYTES_DEFAULT.
=> [SMALLFIX] Use a separate PropertyKey for MultiRangeObjectInputStream reads

docs/cn/deploy/Running-Alluxio-On-Kubernetes.md, docs/en/deploy/Running-Alluxio-On-Kubernetes.md
I had to use `--from-env-file` or else k8s dumps the whole config file into a single env var named after the file (lol).
=> [SMALLFIX] Update docs to use `--from-env-file`

core/server/master/src/main/java/alluxio/master/metastore/caching/CachingInodeStore.java, core/server/master/src/test/java/alluxio/master/metastore/caching/CachingInodeStoreTest.java
`entry.addChild()/entry.removeChild()` already increment/decrement the weight, so we don't need to do it at the call site. Also, calling `incrementAndGet()` in `removeEdge` makes no sense in the first place.
The added tests fail with either bug individually
The behavior with this bug is that the cache thinks it is full, but it's actually empty. As a result, all reads from the cache become cache misses
=> Fix weight tracking bug in caching inode store

core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, core/server/master/src/main/java/alluxio/web/MasterWebServer.java, core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java, core/server/worker/src/main/java/alluxio/web/WorkerWebServer.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
The web server rest handler instances are created every time a request
is propagated. We shouldn't be creating new client objects within the
service handlers.
Instead we initialize a client in the servlet's `init` method which will
only be called once. Then subsequent calls to the REST service handler
will only utilize the single client.
@aaudiber
=> [SMALLFIX] Create clients less often in REST handlers

tests/src/test/java/alluxio/client/cli/fs/AbstractFileSystemShellTest.java
This fixes a flaky failure observed in https://amplab.cs.berkeley.edu/jenkins/job/Alluxio-Pull-Request-Builder/1869/console, specifically 
> java.util.concurrent.TimeoutException: Timed out waiting for file to be completely freed options: WaitForOptions{interval=20, timeout=10000}
> 	at alluxio.client.cli.fs.command.PersistCommandTest.persistPartial(PersistCommandTest.java:242)
The problem occurs when a test (such as persistPartial) calls `checkFilePersisted` twice on the same file. The first call frees the data and then reads it from a worker. This read causes the worker to re-cache the data. However, the worker reports blocks to the master asynchronously, so the second call to `checkFilePersisted` could happen before the worker's block report. If the blocks are reported after the second …
=> Fix race condition in persist tests

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointThread.java, core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSnapshot.java, tests/src/test/java/alluxio/server/ft/journal/MultiMasterJournalTest.java
Without this fix, replaying a checkpoint is almost guaranteed to crash the master. 
The code-level issue is that `mJournalReader.getNextSequenceNumber()` always returns `0` while replaying a checkpoint, so the recently-added
```java
if (mJournalReader.getNextSequenceNumber() == 0) {	
mMaster.resetState();	
}
```
will reset state before applying every single entry of the checkpoint.
=> Fix checkpoint replay state reset bug

core/server/worker/src/main/java/alluxio/worker/grpc/AbstractWriteHandler.java, core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockWriteHandler.java, core/server/worker/src/test/java/alluxio/worker/grpc/AbstractWriteHandlerTest.java
In some Spark job, an error might be returned after cancelling a write request. It turns out that gRPC triggers an error on server when cancel is invoked from client side. This change added a check to avoid throwing errors after cancelling a request.
=> Fix request cancel error on gRPC write path

tests/src/test/java/alluxio/server/ft/MasterFailoverIntegrationTest.java
The important part is increasing the rpc duration to 60 seconds. 15 seconds can lead to a timeout if restarting the cluster doesn't happen fast enough.
=> Avoid flakiness in journal fencing test

core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/test/java/alluxio/master/file/PersistenceTest.java, job/server/src/main/java/alluxio/job/persist/PersistDefinition.java, tests/src/test/java/alluxio/job/persist/PersistIntegrationTest.java
Persisting a file only makes sense once the file is complete. When persist reads an incomplete file, it will treat the persist as successful even if the file wasn't completely written yet. Therefore, persist should not be able to read an incomplete file.
=> Disallow persist to read incomplete file

core/transport/pom.xml
- Clean auto-generated java files prior to proto/grpc code generation.
- Disable findbugs for core-transport module.
=> Clean auto-generated java files prior to proto/grpc code generation

core/common/src/main/java/alluxio/grpc/GrpcExceptionUtils.java
Remove some unnecessary exception serialization to improve file system metadata performance when it throws a lot of exceptions.
=> Remove some serialization logic for exception handling

core/server/master/src/main/java/alluxio/master/MasterUtils.java
10 minutes is long enough that exceeding the time limit
indicates that something is hanging. I hit the 10 seconds
limit due to cleaning up the rocks metastore from the
previous run. The metastore directory was over 100GB, so it
took around 10 seconds to remove.
=> Increase timeout for creating masters

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSystem.java
Now that the rocks metastore can support billions of files,
we may take more than an hour to replay the journal on
fresh startup. With no checkpoints, I see replay taking about
1 hour per 150 million files.
=> Increase timeout for replaying journal

core/common/src/main/java/alluxio/grpc/GrpcChannel.java, core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java, core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java, core/common/src/test/java/alluxio/grpc/GrpcManagedChannelPoolTest.java, tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java, tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTest.java
By moving the parameters ~into the channel key~ we can acquire and shutdown channels with timeouts based on per-client configurations rather than using a load-once-per-jvm strategy.
The advantage of doing this is that users who choose to modify timeouts within the same JVM across different client objects will have those timeouts respected by the channel pool when acquiring and releasing channels.
=> Move GrpcManagedChannelPool timeout parameters to GrpcChannel and GrpcChannelBuilder

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java, core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
GRPC performance improves if we use a dedicated thread pool for it and experimentation have shown that forkjoin pool performs the best for in mem operations. 
Hence, we are moving to use a forkjoin pool for gRPC threads.
=> Make GRPC use a separate forkjoin pool

core/client/fs/src/main/java/alluxio/client/block/stream/DataMessageClientResponseObserver.java, core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java, core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataMessageBlockingStream.java, core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java, core/client/fs/src/main/java/alluxio/client/block/stream/StreamSerializationClientInterceptor.java, core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/grpc/BufferRepository.java, core/common/src/main/java/alluxio/grpc/DataMessage.java, core/common/src/main/java/alluxio/grpc/DataMessageMarshaller.java, core/common/src/main/java/alluxio/grpc/DataMessageMarshallerProvider.java, core/common/src/main/java/alluxio/grpc/GrpcChannel.java, core/common/src/main/java/alluxio/grpc/GrpcSerializationUtils.java, core/common/src/main/java/alluxio/grpc/GrpcServerBuilder.java, core/common/src/main/java/alluxio/grpc/ReadResponseMarshaller.java, core/common/src/main/java/alluxio/grpc/ReadableDataBuffer.java, core/common/src/main/java/alluxio/util/proto/ProtoUtils.java, core/common/src/test/java/alluxio/grpc/ReadResponseMarshallerTest.java, core/server/worker/src/main/java/alluxio/worker/grpc/AbstractReadHandler.java, core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerImpl.java, core/server/worker/src/main/java/alluxio/worker/grpc/DataMessageServerStreamObserver.java, core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
Added APIs for intercepting gRPC client and server with custom data serialization/deserialization.
Also made the worker send read response asynchronously to improve throughput for single read request.
=> Implement zero copy for gRPC read path

integration/fuse/bin/alluxio-fuse, shell/src/main/java/alluxio/cli/fs/FileSystemShell.java
- Fix  https://github.com/Alluxio/alluxio/issues/8362: use `echo -e` rather than `echo` to respect the escaped characters in error messages
- Fix various typos and trailing whitespaces in this script
- Make `umount` the alias of `unmount` and make this convention consistent in Alluxio mount and fuse mount too. Previously we only support `unmount` in `alluxio fs` and only `umount` in `alluxio-fuse`
- Support `alluxio-fuse mount` without argument to list all fuse mount points, to be consistent with Alluxio mount command
=>  Fix various minor issues in alluxio-fuse script

core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java, core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java, core/server/common/src/test/java/alluxio/master/journal/AsyncJournalWriterTest.java
With gRPC timing of incoming RPCs changed in a way that they are contending heavily on the async-journal-writer. This fix aims to improve async-journal-writer's batching by:
* Keeping a dedicated thread for flushing the journal.
* Making RPC threads wait on flush progress.
=> Improve journal batching under heavy load

core/common/src/test/java/alluxio/master/PollingMasterInquireClientTest.java, core/server/master/src/main/java/alluxio/web/MasterWebServer.java, core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java, core/server/worker/src/main/java/alluxio/web/WorkerWebServer.java, core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java, core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerImpl.java, core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java, minicluster/src/main/java/alluxio/master/ClientPool.java, tests/src/test/java/alluxio/client/fs/FileSystemMasterClientIntegrationTest.java, tests/src/test/java/alluxio/job/persist/PersistIntegrationTest.java, tests/src/test/java/alluxio/server/ft/MasterFailoverIntegrationTest.java, tests/src/test/java/alluxio/server/ft/journal/JournalReplayIntegrationTest.java, tests/src/test/java/alluxio/testutils/LocalAlluxioClusterResource.java
Previously, none of the web servers closed their FIleSystem client. This
has been fixed. The AsyncCacheRequestManager created it's own
FileSystemContext upon instantiation. This has been changed such that
the GrpcDataServer is now reponsible for creating and closing the
FileSystemContext that the AsyncCacheRequestManager uses. Lastly,
the ClientPool, LocalAlluxioClusterResource, and PollingMasterInquireClientTest
all had cases where resources may not be released, so I made sure to close
them properly.
=> Diligently release resources - web servers, clients, and ports

core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java, core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java, core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java, core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java, core/common/src/main/java/alluxio/security/authentication/SaslStreamClientDriver.java, core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java, core/common/src/test/java/alluxio/security/authentication/GrpcSecurityTest.java, shell/src/main/java/alluxio/common/RpcPortHealthCheckClient.java
Throwing unavailable and unauthenticated exceptions from channel building logic is too simplistic for gRPC flow as we handle most of the channel/authentication logic internally. Rather than blanketing various issues into 2 categories, this PR makes them throw proper AlluxioStatusException types.
=> Revise gRPC exception flow for channel building and authentication

bin/alluxio-start.sh
Previously we would stop most processes, but not secondary_master or job.
This makes the behavior consistent across all processes
=> Stop job and secondary_master processes before starting them

core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java, core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java
These todos are out of date. The original issue from the managed
channel pool was taken care of by moving the configuration parameters
out of the managed channel pool.
The AsyncCacheRequestManager now has its FileSystemContext passed
in rather than creating one, rendering the TODO finished.
=> [SMALLFIX] Remove TODOs

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java, core/common/src/main/java/alluxio/metrics/TimeSeries.java, core/common/src/main/java/alluxio/wire/MasterWebUIMetrics.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java, core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, core/server/master/src/main/java/alluxio/master/metrics/TimeSeriesStore.java, core/server/master/src/test/java/alluxio/master/metrics/TimeSeriesStoreTest.java
@WilliamZapata 
This adds a field to the WebUIMetrics endpoint:
```
timeSeriesMetrics: [
MetricName: [
timestamp : value,
...
],
...
]
```
These metrics last for the lifetime of a single master and will be lost when the master restarts/fails over.
=> Add infra for in-memory time series metrics on the master

core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java, core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java, core/client/fs/src/main/java/alluxio/client/file/FileSystem.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemUtils.java, core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java, core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java, examples/src/main/java/alluxio/cli/RunOperation.java, shell/src/main/java/alluxio/cli/fs/FileSystemShellUtils.java, shell/src/main/java/alluxio/cli/fs/command/CheckConsistencyCommand.java, shell/src/main/java/alluxio/cli/fs/command/PersistCommand.java, tests/src/main/java/alluxio/master/backcompat/ops/PersistFile.java, tests/src/test/java/alluxio/client/cli/fs/FileSystemShellUtilsTest.java, tests/src/test/java/alluxio/client/cli/fs/command/PersistCommandTest.java, tests/src/test/java/alluxio/client/fs/FileSystemUtilsIntegrationTest.java, tests/src/test/java/alluxio/job/persist/PersistIntegrationTest.java
* Move FileSystemUtils into FileSystem
Tests were integrated into FileSystemIntegrationTest.
* Leave primitive methods in FileSystem client
Compound operations have been moved or left inside of FileSystemUtils
* Update perist command to add timeout
During testing RunOperation can't seem to create files any more unless
we default the CreatePOptions recursive value to true. So this has been
set for CreateFile.
Related shell utilities and tests have been updated
* Add persistence options to client API
ScheduleAsyncPersistencePOptions already existed. It needs to be
exposed on the client so that users can pass options to it in the future
if desired
* Remove unused options sWriteBoth
* Fix confusing argument in createUnpersistedFiles
* Address minor typos in PersistCommand output
* move …
=> [CHERRY-PICK] [#8366] Move FileSystemUtils into FileSystem (#8369)

core/base/src/main/java/alluxio/exception/status/AlluxioStatusException.java, core/base/src/main/java/alluxio/exception/status/Status.java, core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java, core/client/fs/src/main/java/alluxio/client/block/stream/GrpcBlockingStream.java, core/common/src/main/java/alluxio/AbstractClient.java, core/common/src/main/java/alluxio/grpc/GrpcExceptionUtils.java, core/common/src/main/java/alluxio/security/authentication/SaslStreamClientDriver.java, core/common/src/main/java/alluxio/security/authentication/SaslStreamServerDriver.java, core/common/src/main/java/alluxio/util/ConfigurationUtils.java, core/common/src/test/java/alluxio/TestLoggerRule.java, core/server/common/src/main/java/alluxio/RpcUtils.java, core/server/worker/src/main/java/alluxio/worker/grpc/AbstractReadHandler.java, core/server/worker/src/main/java/alluxio/worker/grpc/AbstractWriteHandler.java, core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockWriteHandler.java, tests/src/test/java/alluxio/client/cli/fs/command/CopyFromLocalCommandIntegrationTest.java, tests/src/test/java/alluxio/client/cli/fs/command/CpCommandIntegrationTest.java, tests/src/test/java/alluxio/client/cli/fsadmin/command/GetBlockInfoCommandIntegrationTest.java, tests/src/test/java/alluxio/client/fs/ReadOnlyMountIntegrationTest.java, tests/src/test/java/alluxio/job/replicate/ReplicateIntegrationTest.java
This PR moves conversion to/from grpc statuses and status exceptions into `AlluxioStatusException` and `alluxio.exception.status.Status`. This improves discoverability, and centralizes our exception conversion logic in one place.
=> Centralize exception conversion

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java
* Cherry-pick with conflicts
Various active sync related fixes (#1573)
Start initial active sync & safely remove from map
* fix cherry-pick conflict
* Stop master fail over from clearing state for Active Sync (#1580)
* Fix the fail over cleaning out state for active sync.
* add more comment
* address comments
* resolve conflicts
* fix checkstyle
=> [CHERRYPICK] ActiveSync fixes (#8400)

core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
Master branch cannot compile due to a symbol not found error.
=> Fix symbol not found error.

core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java, core/common/src/main/java/alluxio/grpc/GrpcChannel.java, core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java, core/common/src/main/java/alluxio/security/authentication/AuthenticatedChannel.java, core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java, core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerImpl.java, core/transport/src/grpc/block_worker.proto, core/transport/src/main/java/alluxio/grpc/BlockWorkerGrpc.java, core/transport/src/main/java/alluxio/grpc/BlockWorkerProto.java
In 2.0 RC1 we employed an extra health check for block worker client to make sure authentication kicks in if gRPC channel reconnects to a new worker. It introduced some overhead especially for small random reads. This change revert the previous fix and force reauthentication by informing the block worker client pool to drop the cached client when the client is disconnected.
=> Fix reauthentication without the overhead of extra health check

core/server/master/src/main/java/alluxio/master/file/UfsSyncChecker.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeView.java, core/server/master/src/main/java/alluxio/master/metastore/caching/CachingInodeStore.java, core/server/master/src/main/java/alluxio/master/metastore/heap/HeapInodeStore.java, shell/src/main/java/alluxio/cli/fs/command/DuCommand.java, tests/src/test/java/alluxio/client/cli/fs/command/LsCommandIntegrationTest.java
It's more efficient to leave children unsorted, and only sort when needed
=> Remove child sorting

core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java, core/common/src/main/java/alluxio/grpc/GrpcChannel.java, core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java, core/common/src/main/java/alluxio/security/authentication/AuthenticatedChannel.java, core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java, core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerImpl.java, core/transport/src/grpc/block_worker.proto, core/transport/src/main/java/alluxio/grpc/BlockWorkerGrpc.java, core/transport/src/main/java/alluxio/grpc/BlockWorkerProto.java
Cherrypicked from `master` (https://github.com/Alluxio/alluxio/pull/8406)
Original description:
In 2.0 RC1 we employed an extra health check for block worker client to make sure authentication kicks in if gRPC channel reconnects to a new worker. It introduced some overhead especially for small random reads. This change revert the previous fix and force reauthentication by informing the block worker client pool to drop the cached client when the client is disconnected.
=> [2.0-preview] Fix reauthentication without the overhead of extra health check

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
Instead of scanning the full tree on startup, we keep an index of files with persistence state TO_BE_PERSISTED, then only create persist jobs for those.
=> Avoid scanning tree for TO_BE_PERSISTED files during startup

core/server/master/src/main/java/alluxio/master/AlluxioSecondaryMaster.java, minicluster/src/main/java/alluxio/master/LocalAlluxioMaster.java, tests/src/test/java/alluxio/server/ft/journal/MultiMasterJournalTest.java, tests/src/test/java/alluxio/server/ft/journal/ufs/SecondaryMasterTest.java, tests/src/test/java/alluxio/testutils/IntegrationTestUtils.java
Previously, it wouldn't do anything. Now it creates
checkpoints like it's supposed to.
fixes #8390
=> Fix secondary master to create checkpoints

integration/yarn/pom.xml, integration/yarn/src/main/java/alluxio/yarn/Client.java
1. There are classes in alluxio-core-common that depend on grpc, grpc is only included in alluxio-core-transport, so it has to be included, otherwise, ClassNotFound issues will happen. Previously, we exclude alluxio-core-protobuf because of some shading hacks which no longer work for alluxio-core-transport.
2. Alluxio uses a newer version of Guava, an older version of Guava also exists in the YARN_APPLICATION_CLASSPATH, so without this change, the classloader will load the older version of Guava, so MethodNotFound exception might be thrown in some Alluxio  classes due to their needs for the newer version of Guava.
=> Fix Alluxio Yarn integration

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java, core/client/fs/src/main/java/alluxio/client/file/policy/LocalFirstAvoidEvictionPolicy.java, core/client/fs/src/main/java/alluxio/client/file/policy/LocalFirstPolicy.java, core/client/fs/src/test/java/alluxio/client/file/policy/LocalFirstPolicyTest.java, core/common/src/main/java/alluxio/util/TieredIdentityUtils.java, core/common/src/test/java/alluxio/wire/TieredIdentityTest.java
Changing the method signature makes passing arguments simpler.
=> Use configuration instead of boolean for tieredIdentity nearest

core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java
Some gRPC unit tests are failing because the test does not work well with zero-copy streaming. This fix  some code to attempt falling back to message buffer if zero copy buffer is not provided.
=> Fix gRPC unit test

core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, tests/src/test/java/alluxio/client/fs/ConcurrentRecursiveCreateTest.java
This fixes a bug where concurrent creation operations can lead to invalid inodes. The race condition looks like:
Initial state: Only inode in Alluxio is "/", ufs contains "/a/b/c"
Thread A: begins to create /a/b
Thread B: tries to create /a/b/c
Thread A: begins to create /a
Thread A: takes a write lock on /a
Thread A: creates a new inode for /a
Thread A: adds /a to the children list of "/"
Thread A: calls syncPersistDirectory to sync "/a" with the ufs
Out of band: /a/b/c gets removed in the UFS
Thread B: traverses to "/a/b/c" and finds "/a" as a child of "/"
Thread B: takes a read lock on "/a" and blocks since thread A still has the write lock
Thread A: throws InvalidPathException("Cannot create or load UFS directory")
Thread A: removes "/a" from the child list of "/"
Thread A: unlocks …
=> Fix issue with phantom inodes

core/common/src/main/java/alluxio/AbstractClient.java, core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java, core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java, core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java, core/common/src/main/java/alluxio/util/ConfigurationUtils.java, core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
Workers handles long running blocking streams which will exhaust the common `ForkJoinPool` (by default `cpu core - 1` parallelism) pretty quickly if user holds on to streams concurrently. This change makes the worker client use default gRPC executor which is not bounded by the number of CPU cores.
=> Use separate gRPC client executor for workers

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
ListStatus for ~20K files requires ~100MB of message buffer size...
=> Define a default value for gRPC client-side message size (100MB)

integration/fuse/bin/alluxio-fuse
With zero-copy implemented for read path, Alluxio client now uses more direct memory for buffering data. This has lead to OOM in Alluxio FUSE process which currently only can use 1GB of direct memory.
This change bumps up the direct memory limit for Alluxio FUSE process thus reduces the chance of getting OOM.
=> Give more direct memory to FUSE

alluxio-ui/master/src/store/data/reducer.tsx
The default fileInfo should be an empty list, the existing item should be only for debugging purpose during development.
=> Do not show anything in the data page where there is no file.

core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java, core/server/master/src/main/java/alluxio/master/metastore/caching/CachingInodeStore.java, core/server/master/src/test/java/alluxio/master/metastore/caching/CachingInodeStoreTest.java
If an entry is clean, there is no need to flush it
before eviction. This performance optimization can
help significantly in read-only workloads.
=> Skip flushing clean caching inode store entries

core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
This line was missing as a result of a recent merge. I am adding it back to fix the keep alive configuration.
=> Add back keep alive configuration

core/server/master/src/main/java/alluxio/master/metastore/caching/CachingInodeStore.java, core/server/master/src/test/java/alluxio/master/metastore/caching/CachingInodeStoreTest.java
This could happen when listing /a if edge a->b=3 has
been evicted to the backing store, but inode 3 exists
only in the cache. Calling getChildren("/a") on the backing
store will not find inode 3 because the backing store
doesn't know anything about inode 3.
This bug rarely happens in practice because the edge
leading to an inode and the inode itself are usually
accessed around the same time, so they are usually either
both in the cache, or both in the backing store.
=> Fix bug where listing caching inode store misses inodes

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
The return code already shows users the file does not exist or already exists or input path is invalid. There is no need to add duplicated error level logging which will make the log messy.
=> Move "file does not exist" or "already exists" to debug log level

core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java, core/server/master/src/main/java/alluxio/master/metastore/caching/CachingInodeStore.java, core/server/master/src/test/java/alluxio/master/metastore/caching/CachingInodeStoreTest.java
This prepares for supporting RocksDB-based snapshots. Before taking the RocksDB snapshot, we need to ensure that all data is flushed to RocksDB.
=> Support flushing cached data to the backing store

core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
The `DefaultReplicationHandler.replicate` will connect to the job master client and run the replication work. 
In this process, it will First use `PollingMasterInquireCient.pingMetaService` to ping job master client service and get the error out because the job master does not have the `Meta_Master_Cient_Service`.
So `pingMetaService` actually pings meta master client service and job master client service.
=> [SMALLFIX] Support pinging Job Master client service

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/test/java/alluxio/ConfigurationTestUtils.java, core/server/common/src/main/java/alluxio/master/MasterProcess.java
Removed `alluxio.master.worker.threads.min` which we no longer use with the new thread pool executor.
=> Remove deprecated property

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java, core/common/src/test/java/alluxio/underfs/AbstractUnderFileSystemContractTest.java
When recursively listing from an object store, Alluxio computes the prefixes from the object store results. However, the commonPrefixes returned by the object store include the path separators. Therefore, the Alluxio processing should follow the same convention and include the path separators. Further processing of the prefixes assume that the path separators are included.
=> Fix list recursive for object store

core/base/src/main/java/alluxio/wire/BlockLocationInfo.java, core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java, core/client/fs/src/main/java/alluxio/client/file/FileSystem.java, core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, tests/src/test/java/alluxio/client/fs/FileSystemIntegrationTest.java
There is a regression in `getFileBlockLocations()` API where the client does not return the block locations in their original order in file. This is causing Presto queries to fail because they are relying on the block orders.  This PR refactored the native API so it returns a list instead of an unordered map.
=> Fix block location order

core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java, core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java, core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java, core/server/master/src/test/java/alluxio/master/file/PermissionCheckTest.java, core/server/master/src/test/java/alluxio/master/file/PersistenceTest.java, core/transport/src/grpc/file_system_master.proto, core/transport/src/main/java/alluxio/grpc/CreateFilePResponse.java, core/transport/src/main/java/alluxio/grpc/CreateFilePResponseOrBuilder.java, core/transport/src/main/java/alluxio/grpc/FileSystemMasterProto.java, tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java
Instead of returning the file id, we return the file info. This can improve performance of create file by reducing the number of RPCs required.
=> Reduce the number of RPCs used for create file

core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java, core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, tests/src/test/java/alluxio/client/fs/FileSystemIntegrationTest.java
In SetAttribute on the filesystem client we previously merged the options
supplied to the client into the FileSystemOptions defaults based on
configuration. The issue is that SetAttribute is a unique operation in
that any value which is sent over the wire we assume was set explicitly by the
user. That's where the issue arose. We were merging default options
into the SetAttributePOptions when we shouldn't have been. The master was
taking the default options and setting the attributes which came from the
defaults.
This change now only explicitly sends a user's options if they are set.
No other options are merged in the setAttribute operation.
In this investigation I also found a bug in setting the TTL and
TtlAction on a file. Both TTL and TtlAction needed to be set in order
for the …
=> SetAttribute options are merged when they shouldn't be

integration/docker/Dockerfile
This dependency is needed by rocksdbjni
Tested locally and adding the dependency prevents us from hitting `java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni4519472487824987007.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/librocksdbjni4519472487824987007.so)`
@bf8086
=> Add libc6-compat to docker integration

core/common/src/main/java/alluxio/metrics/MasterMetrics.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java, core/server/master/src/main/java/alluxio/master/metastore/DelegatingReadOnlyInodeStore.java, core/server/master/src/main/java/alluxio/master/metastore/ReadOnlyInodeStore.java, core/server/master/src/main/java/alluxio/master/metastore/caching/CachingInodeStore.java, core/server/master/src/main/java/alluxio/master/metastore/heap/HeapInodeStore.java, core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterMetricsTest.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java, tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java
This change adds tracking for the exact number of inodes. Whenever we add or delete an inode, we increment or decrement the counter.
We track the number of inodes instead of requesting it from the inode store because some inode stores (e.g. RocksDB) don't have a fast way to count the number of inodes.
This change is motivated by a bug where calling estimateNumberOfPaths with a Rocks inode store would cause a segmentation fault if the inode store is in the process of being initialized.
This also addresses an issue where `CachingInodeStore#estimateNumberOfPaths()` was wildly inaccurate because it delegated to the backing store. With 5 million paths, the estimate would be `0` because the inodes still fit in the cache. It's very difficult for `CachingInodeStore` to determine how many inodes …
=> Keep track of number of inodes

shell/src/main/java/alluxio/cli/fs/command/CopyFromLocalCommand.java, shell/src/main/java/alluxio/cli/fs/command/CopyToLocalCommand.java, shell/src/main/java/alluxio/cli/fs/command/CpCommand.java, shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java, shell/src/main/java/alluxio/cli/fs/command/SetReplicationCommand.java
- use opts like `--replication` rather than `-replication` in CLI consistently
- clean up CLI command description
=> Clean up the options for CLI commands to be consistent

core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
Duplicate entries can happen often and spam the logs.
They don't indicate a real error, so this PR moves the
log message to the debug level.
=> Change duplicate entry log to debug level

core/common/src/main/java/alluxio/util/ExceptionUtils.java, core/common/src/test/java/alluxio/util/ExceptionUtilsTest.java, core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointThread.java
This PR makes two changes:
1. During checkpoint thread shutdown, only interrupt the journal checkpoint thread if it is in the process of creating a checkpoint. Interrupting is unnecessary outside of checkpointing, and may cause the thread to exit early instead of replaying all logs and waiting the quiet period.
2. When checkpointing throws an exception, inspect the causal chain to determine whether the root cause was interruption. If it wasn't, log an error. Either way, continue instead of crashing the checkpoint thread.
Previously we would catch `InterruptedException` thrown during `writeToCheckpoint()`, but this isn't enough because interrupted exceptions can get converted to `InterruptedIOException` or wrapped in a `RuntimeException` like `KyroException` (or both, like below).
> ERROR …
=> Fix the way we shut down the checkpoint thread

underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
when listing operation getNextChunk trap infinity loop without filling correct paging information for next round request
=> Avoid infinite loop for OSSUnderFileSystem getNextChunk listing

core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java, core/server/master/src/test/java/alluxio/master/file/PersistenceTest.java, minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java, minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java, minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
Changes the default metastore to heap for integration tests and multi-cluster tests. We currently do not support lifecycle management for the metastore, which causes problems when trying to reinit a rocks metastore.
=> Fix test metastore path

core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/util/ConfigurationUtils.java, core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java, core/common/src/test/java/alluxio/util/ConfigurationUtilsTest.java, core/common/src/test/java/alluxio/util/network/NetworkAddressUtilsTest.java, core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalConfiguration.java, core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java, core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalConfigurationTest.java
If the embedded journal local address isn't included in the cluster addresses, it will cause the journal to hang when it tries to bootstrap. Today, our default configuration will use `"localhost:19200"` for the cluster address and `"${alluxio.master.hostname}:19200"` for the local address. If the master hostname is unset or set to something other than "localhost", the master will hang at startup. This PR changes the defaults cluster addresses to `"${alluxio.master.hostname}:19200"` to match the local address. This PR also adds a validation check so that the master will crash with an exception if the local address isn't included in the list of cluster addresses.
This PR also adds unit tests for how we generate embedded journal configuration
=> Improve embedded journal conf defaults

core/base/src/main/java/alluxio/exception/PreconditionMessage.java, core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
When HBase gets FileSystem through Hadoop, both Hadoop and HBase will call initialize.
=> Fix concurrent initialization in hadoop compatible FileSystem

alluxio-ui/master/src/containers/pages/Metrics/Metrics.tsx, alluxio-ui/master/src/containers/pages/Metrics/__snapshots__/Metrics.test.tsx.snap
Client metrics collection is not guaranteed (in fact off by default), so the short circuit and cache rate metrics will be inaccurate most of the time. Therefore we remove them from the display. Users can still hit the rest endpoint to retrieve the values if the environment is setup to accurately measure them.
=> Hide short-circuit metrics

core/common/src/main/java/alluxio/conf/PropertyKey.java
This lets us keep more inodes cached while still giving
the eviction thread multiple seconds worth of work each
time it wakes up.
=> Increase default low water mark for inode cache.

docs/en/compute/Presto.md
prestosql.io is the new website to replace the old prestodb.io.
=> Update URL to Presto website

shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
https://alluxio.atlassian.net/browse/ALLUXIO-3029
This issue has actually been solved by others, but I found a minor bug regarding the implementation of the sort-by-size option.
Previously, sorting by file size checks "URIStatus::getBlockSizeBytes", which is not correct as it compares the default block size rather than the file size. Wrong sorting results can be observed as follows,
Replacing "getBlockSizeBytes" with "getLength" solves the problem.
=> [SMALLFIX] Fix shell command ls sort by size

core/base/src/main/java/alluxio/exception/ExceptionMessage.java, core/common/src/main/java/alluxio/util/ConfigurationUtils.java, core/common/src/test/java/alluxio/util/ConfigurationUtilsTest.java, core/server/proxy/src/main/java/alluxio/proxy/AlluxioProxy.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorker.java, job/server/src/main/java/alluxio/worker/AlluxioJobWorker.java, shell/src/main/java/alluxio/cli/fs/FileSystemShell.java, shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShell.java, shell/src/main/java/alluxio/cli/job/JobShell.java
The same or similar message is used throughout the code base
when the proper hostname isn't configured and doesn't include
embedded journal configuration. This change adds a new
message to ExceptionMessage and some utility methods to
generate it due to the number of parameters.
ExceptionMessage exists in core/base which meant I couldn't
use PropertyKeys directly in the message itself. This is why
there are utility methods inside of ConfigurationUtils.
Fixes #8443
=> Add master hostname not configured exception message

bin/alluxio-masters.sh, bin/alluxio-workers.sh
For a freshman or even an experienced guy, sometimes it's really confusing to read the task.log since there is no 'datetime' for each line. For example, it's hard to judge whether the following part 3 in the illustrated figured below is the newest log or the last time's log, so we cannot decide whether the latest 'retry' or 'test' for our 'code change' or 'environment update' takes effect or not. thus it is very import the add the "datetime" for the logs in task.log to make us much more efficient to find the issues or bugs.
=> [SMALLFIX] Add datetime for contents in task.log

docs/_config.yml, docs/_layouts/global.html
Replace `..` with `{{site.baseurl}}`. The value for `site.baseurl` can be
set within `_config.yml`. This makes building docs for other locations
simpler.
=> Add baseurl support to docs - 1.7

docs/_config.yml, docs/_layouts/global.html, docs/cn/Command-Line-Interface.md, docs/cn/Configuration-Settings.md, docs/cn/Developer-Tips.md, docs/cn/File-System-API.md, docs/cn/Key-Value-System-API.md, docs/cn/Lineage-API.md, docs/cn/Mounting-Alluxio-FS-with-FUSE.md, docs/cn/Running-Alluxio-Fault-Tolerant.md, docs/cn/Tiered-Storage-on-Alluxio.md, docs/en/Command-Line-Interface.md, docs/en/Configuration-Settings.md, docs/en/Developer-Tips.md, docs/en/File-System-API.md, docs/en/Key-Value-System-API.md, docs/en/Lineage-API.md, docs/en/Mounting-Alluxio-FS-with-FUSE.md, docs/en/Running-Alluxio-Fault-Tolerant.md, docs/en/Tiered-Storage-on-Alluxio.md, docs/pt/Command-Line-Interface.md, docs/pt/Configuration-Settings.md, docs/pt/Developer-Tips.md, docs/pt/File-System-API.md, docs/pt/Key-Value-System-API.md, docs/pt/Lineage-API.md, docs/pt/Running-Alluxio-Fault-Tolerant.md, docs/pt/Tiered-Storage-on-Alluxio.md
Replace `..` with `{{site.baseurl}}`. The value for `site.baseurl` can be
set within `_config.yml`. This makes building docs for other locations
simpler.
=> Add baseurl support to docs - 1.4

docs/_config.yml, docs/_layouts/global.html
Replace `..` with `{{site.baseurl}}`. The value for `site.baseurl` can be
set within `_config.yml`. This makes building docs for other locations
simpler.
=> Add baseurl support to docs - 1.5

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalWriter.java
At 2 seconds, it's easy for garbage collection to trigger
failures. The only downside of increasing to 30 seconds is
that it's harder to detect slow journal processing.
=> Increase raft processing timeout from 2 to 30 seconds

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointWriter.java
The default FilterInputStream write(byte[], int, int)
implementation is to write one byte at a time...
=> Improve efficiency of checkpoint writes

docs/en/deploy/Running-Alluxio-On-Docker.md
fixes #8550 
To get networking to work on OSX, I switched to using a user-defined network.
To get mounting the ufs to work on OSX, I switched to using Docker volumes instead of host volumes. Using a host volume on OSX requires sudo to create the directory and set the permissions.
Now the doc should work equally well on both Linux and OSX
=> Update docker guide to work on OSX

core/client/fs/src/main/java/alluxio/client/block/stream/GrpcBlockingStream.java, core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java, core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java, core/client/fs/src/test/java/alluxio/client/block/stream/BlockInStreamTest.java, core/client/fs/src/test/java/alluxio/client/block/stream/GrpcDataReaderTest.java, core/common/src/main/java/alluxio/conf/PropertyKey.java, core/server/worker/src/main/java/alluxio/worker/grpc/AbstractReadHandler.java, core/server/worker/src/main/java/alluxio/worker/grpc/ReadRequestContext.java, core/transport/src/grpc/block_worker.proto, core/transport/src/main/java/alluxio/grpc/BlockWorkerProto.java, core/transport/src/main/java/alluxio/grpc/ReadRequest.java, core/transport/src/main/java/alluxio/grpc/ReadRequestOrBuilder.java
Current Alluxio worker uses gRPC stream isReady() signal for data path flow control. gRPC has a fixed buffer size of 32KB and is not configurable(See https://github.com/grpc/proposal/pull/135). This change work around this limitation by providing our own configurable flow control(client ack). In benchmark this shows 30% improvement on domain socket read with small number of concurrent streams.
=> Improve read throughput with larger worker side buffer

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
When Alluxio is used in container environment, it is common that user mounts an external directory as the journal location in the container. This will result in error when Alluxio formats embedded journal because the directory cannot be deleted. This fix solves the issue by not removing the journal directory but instead removing all the files inside.
=> Fix journal folder deletion error

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-release-tarballs.go, dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
The Alluxio client jar does not depend on the hadoop distribution, so there is no need to build multiple tarballs for multiple distributions.
=> Improve the generate tarball script

bin/alluxio-masters.sh, bin/alluxio-workers.sh
When tasks fail, users might not know where to find errors.
=> Add a hint to check task.log for errors

core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java
Two minor fixes:
- Build read receipt from original request to work better with server validations.
- Lower the log level to avoid excessive warnings on closing a read request.
=> Make read receipt more robust

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java, core/client/fs/src/main/java/alluxio/client/block/policy/RoundRobinPolicy.java, core/client/fs/src/main/java/alluxio/client/block/policy/options/GetWorkerOptions.java, core/client/fs/src/test/java/alluxio/client/block/policy/RoundRobinPolicyTest.java
Previously the round robin policy would ignore the input worker list. This causes problems with replication because the same block would be sent to the same worker multiple times.
=> Make RR policy work with replication

core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, core/server/master/src/test/java/alluxio/master/meta/AlluxioMasterRestServiceHandlerTest.java
When a ufs is unmounted, its metrics still exist in the metrics system, this PR filters out ufs metrics for the mounted ufs only.
=> Add support for filtering out metrics for mounted ufs

job/common/pom.xml, job/server/src/main/java/alluxio/job/JobMasterContext.java, job/server/src/main/java/alluxio/job/JobWorkerContext.java, job/server/src/main/java/alluxio/job/load/LoadDefinition.java, job/server/src/main/java/alluxio/job/migrate/MigrateDefinition.java, job/server/src/main/java/alluxio/job/persist/PersistDefinition.java, job/server/src/main/java/alluxio/job/replicate/EvictDefinition.java, job/server/src/main/java/alluxio/job/replicate/ReplicateDefinition.java, job/server/src/main/java/alluxio/master/AlluxioJobMasterProcess.java, job/server/src/main/java/alluxio/master/job/JobCoordinator.java, job/server/src/main/java/alluxio/master/job/JobMaster.java, job/server/src/main/java/alluxio/worker/AlluxioJobWorkerProcess.java, job/server/src/main/java/alluxio/worker/JobWorker.java, job/server/src/main/java/alluxio/worker/job/command/CommandHandlingExecutor.java, job/server/src/test/java/alluxio/job/command/CommandHandlingExecutorTest.java, job/server/src/test/java/alluxio/job/load/LoadDefinitionTest.java, job/server/src/test/java/alluxio/job/migrate/MigrateDefinitionRunTaskTest.java, job/server/src/test/java/alluxio/job/migrate/MigrateDefinitionSelectExecutorsTest.java, job/server/src/test/java/alluxio/job/persist/PersistDefinitionTest.java, job/server/src/test/java/alluxio/job/replicate/EvictDefinitionTest.java, job/server/src/test/java/alluxio/job/replicate/ReplicateDefinitionTest.java, job/server/src/test/java/alluxio/master/job/JobCoordinatorTest.java, job/server/src/test/java/alluxio/master/job/JobMasterTest.java
This change moves the creation of FileSystem/Context out of
the job definitions and into the respective master/worker
processes. The processes should aim to create clients as few
times as possible because of all the underlying threadpools
and resources that are needed to instantiate a client.
The JobMaster and JobWorkers now pass in a single instance
of a filesystem client+context when selecting executors and
running tasks. This greatly reduces the amount of resources
that the job master and workers consume when there are lots
of jobs being executed.
=> Refactor filesystem, fsContext into JobMaster/Worker contexts

core/common/src/main/java/alluxio/grpc/GrpcServerAddress.java
Fixed an NPE in `GrpcServerAddress` when the address is passed in unresolved.
=> Fix NPE in server address

shell/src/main/java/alluxio/cli/fs/command/CpCommand.java, tests/src/test/java/alluxio/client/cli/fs/AbstractFileSystemShellTest.java, tests/src/test/java/alluxio/client/cli/fs/command/ChownCommandIntegrationTest.java, tests/src/test/java/alluxio/client/cli/fs/command/CpCommandIntegrationTest.java
Sometimes user wants to preserve the original attributes of files and directories when using `cp` command. This change add a new `-p` option to the `cp` command to enable such functionality. Note that user will need to have the required permissions to perform the operation.
https://github.com/Alluxio/alluxio/issues/8685
=> Add an option to cp command to preserve file attributes

shell/src/main/java/alluxio/cli/fs/command/CpCommand.java, tests/src/test/java/alluxio/client/cli/fs/AbstractFileSystemShellTest.java, tests/src/test/java/alluxio/client/cli/fs/command/ChownCommandIntegrationTest.java, tests/src/test/java/alluxio/client/cli/fs/command/CpCommandIntegrationTest.java
#8685 
Porting of #8682 for `branch-1.8`. Support for ACL attributes preservation is removed because it does not exist in version 1.8.1
=> Add an option to cp command to preserve file attributes (branch-1.8)

job/server/src/main/java/alluxio/master/job/JobCoordinator.java
[SMALLFIX] Supply the name of variable to Preconditions.checkNotNull in /alluxio/job/server/src/main/java/alluxio/master/job/JobCoordinator.java line111
=> Supply the name of variable to Preconditions.checkNotNull

core/common/src/main/java/alluxio/conf/AlluxioConfiguration.java, core/common/src/main/java/alluxio/conf/AlluxioProperties.java, core/common/src/main/java/alluxio/conf/InstancedConfiguration.java, core/common/src/main/java/alluxio/conf/path/PathConfiguration.java, core/common/src/main/java/alluxio/conf/path/PrefixPathConfiguration.java, core/common/src/main/java/alluxio/conf/path/SpecificPathConfiguration.java, core/common/src/main/java/alluxio/util/ConfigurationUtils.java, shell/src/main/java/alluxio/cli/fsadmin/command/PathConfCommand.java, shell/src/main/java/alluxio/cli/fsadmin/pathconf/ShowCommand.java, tests/src/test/java/alluxio/client/cli/fsadmin/pathconf/ShowCommandIntegrationTest.java
Adds "pathConf show" to show path level configurations.
It has two modes:
1. only show configurations for the specific path;
2. show all configurations applicable to the path.
For example, suppose there are two path level configurations:
/a: property1=value1
/a/b: property2=value2
Then in mode 1, only property2=value2 will be shown for /a/b,
but in mode 2, since /a is the prefix of /a/b, both properties will be shown for /a/b.
=> Add "pathConf show" command

core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/underfs/MasterUfsManager.java, core/server/worker/src/main/java/alluxio/underfs/WorkerUfsManager.java, core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java, job/server/src/main/java/alluxio/underfs/JobUfsManager.java
#8236
Alluxio master currently initiates login for UFS by calling connectFromMaster when a UFS is mounted through commandline. However, this is not called when root ufs is mounted or when nested ufs is remounted on restart, therefore user has to rely on kinit to enable Alluxio to talk to Kerberized HDFS.
This change ensures before connecting to a UFS, it always logs in the user with the credentials from Alluxio properties, which frees up user from having to use kinit and activates HDFS client relogin mechanism, so user does not have to periodically kinit to refresh the Kerberos ticket.
=> Fix authentication with kerberized HDFS

job/client/src/main/java/alluxio/client/job/RetryHandlingJobMasterClient.java
replace anonymous type with lambda in alluxio/job/client/src/main/java/alluxio/client/job/RetryHandlingJobMasterClient.java
Replace
retryRPC(new RpcCallable<Void>() {
public Void call() {
mClient.cancel(CancelPRequest.newBuilder().setJobId(jobId).build());
return null;
}
});
with
retryRPC((RpcCallable<Void>) () -> {
mClient.cancel(CancelPRequest.newBuilder().setJobId(jobId).build());
return null;
});
=> [SMALLFIX] Replace anonymous type with lambda

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Below log message generates a lot of noise in ObjectStore UFS. Changing to debug.
=> Limit noisy logs for ObjectStore UFS

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, tests/src/test/java/alluxio/client/fs/ConcurrentCreateRenameIntegrationTest.java
fixes #8618 
There was a time tap in rename() operation between the source path is visible (createFile(source)can succeed and be journaled) and we journal the rename entry. This will cause the fail to replay journal issue. In this PR, we move the journal rename entry step before the making source path visible step to avoid the above issue.
=> Solve the journal replay issue in concurrent create rename

tests/src/test/java/alluxio/client/cli/JournalToolTest.java
Saw this test fail a new contributor's build.
Previously, the tests could fail if a checkpoint is written
too early, and the journalTool reads that checkpoint. This
PR increases the number of entries required to trigger a
checkpoint, so that we don't take a checkpoint until we
want to.
=> Deflake JournalToolTest

core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
Use the @Nullable annotation for method filterInvalidPaths
=> [SMALLFIX] Use the @Nullable annotation for method filterInvalidPaths

core/common/src/main/java/alluxio/util/io/FileUtils.java, core/server/common/src/main/java/alluxio/cli/Format.java, core/server/common/src/main/java/alluxio/master/journal/checkpoint/CheckpointType.java, core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java, core/server/master/src/test/java/alluxio/master/metastore/InodeStoreBench.java
Previously we used Rocks BackupEngine to create backups,
and build our checkpoints from those. That was slow because
backups require copying the full metastore. Checkpoints are
faster because they use hard links instead of copying. With
this change, the time needed to take checkpoints and restore
checkpoints is reduced by 40%.
=> Implement RocksStore checkpoints using Rocks Checkpoints

core/common/src/main/java/alluxio/security/authentication/AuthenticatedUserInjector.java
There are sporadic occurrences of "IllegalStateException: call already closed" in server logs. This PR fixes https://github.com/Alluxio/alluxio/issues/8857 by making sure we don't close an already closed or cancelled server call.
=> Stop intercepting closed/cancelled server calls

core/common/src/main/java/alluxio/conf/AlluxioProperties.java, core/common/src/test/java/alluxio/conf/AlluxioPropertiesTest.java
When a key is removed from AlluxioProperties, the source should also be removed. Otherwise, when getting the key, the default value will be returned, but getSource might not return Source.DEFAULT.
=> Remove source  when removing key from properties

core/common/src/main/java/alluxio/underfs/MultiRangeObjectInputStream.java, core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java, core/common/src/test/java/alluxio/underfs/AbstractUnderFileSystemContractTest.java, underfs/cos/src/main/java/alluxio/underfs/cos/COSInputStream.java, underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java, underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSInputStream.java, underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java, underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoClient.java, underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoInputStream.java, underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoUnderFileSystem.java, underfs/oss/src/main/java/alluxio/underfs/oss/OSSInputStream.java, underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java, underfs/oss/src/test/java/alluxio/underfs/oss/OSSInputStreamTest.java, underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AInputStream.java, underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java, underfs/swift/src/main/java/alluxio/underfs/swift/SwiftInputStream.java, underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java
Add back the retry in s3 read when failed to get object because key does not exist due to s3 eventual consistency issue.
=> Add back retry in S3 read when failed to get key

core/common/src/test/java/alluxio/refresh/TimeoutRefreshTest.java
Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/refresh/TimeoutRefreshTest.java
=> [SMALLFIX] Use static test imports in TimeoutRefreshTest

core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java, core/server/common/src/main/java/alluxio/underfs/UfsManager.java
After switching to ForkJoinPool, master RPC throughput with some UFS types have been degradation. This is due to UFS operations being slow on them, and ForkJoinPool not knowing that its worker is stuck on a blocking operation. This fix introduces a wrapper over UnderFileSystem that notifies the ForkJoinPool during certain UFS operations.
https://github.com/Alluxio/alluxio/issues/8870
=> Call UFS operations under ForkJoinPool managed blocking

core/common/src/main/java/alluxio/util/ConfigurationUtils.java
We end up with logs like
```
2019-04-18 20:10:52,612 INFO  ConfigurationUtils - Alluxio client (version 2.0.0-SNAPSHOT) is trying to bootstrap-connect with masters-2:19998
2019-04-18 20:10:52,614 WARN  ConfigurationUtils - Failed to handshake with master masters-2:19998 : Network closed for unknown reason
2019-04-18 20:10:52,614 WARN  AbstractClient - Failed to connect (40) with MetaMasterMaster @ masters-2:19998: Failed to handshake with master masters-2:19998 to load cluster default configuration values
2019-04-18 20:10:55,748 INFO  ConfigurationUtils - Alluxio client (version 2.0.0-SNAPSHOT) is trying to bootstrap-connect with masters-2:19998
2019-04-18 20:10:55,750 WARN  ConfigurationUtils - Failed to handshake with master masters-2:19998 : Network closed for unknown reason
2019-04-18 …
```
=> Remove redundant log message

core/common/src/main/java/alluxio/security/authentication/DefaultAuthenticationServer.java
Java 8 improvement: replace lambda with method reference in /alluxio/core/common/src/main/java/alluxio/security/authentication/DefaultAuthenticationServer.java#DefaultAuthenticationServer.
=> Replace lambda with method reference in DefaultAuthenticationServer

core/server/worker/src/test/java/alluxio/worker/block/evictor/LRUEvictorTest.java
I use static imports rather than Non-static imports for standard test utilities in alluxio/core/server/worker/src/test/java/alluxio/worker/block/evictor/LRUEvictorTest.java
=> [SMALLFIX] Use static imports for test utilities

docs/en/compute/Spark.md
In one of the sentences in the spark document, the word "node" is misspelled.
=> [DOCFIX] Fix a spelling error of Spark.md

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystemFactory.java
Only new InstancedConfiguration when path is NOT null to avoid unnecessary waste of resources
=> Avoid loading configuration for invalid paths

core/server/worker/src/main/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandler.java, core/server/worker/src/test/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandlerTest.java
When creating ufs blocks, Alluxio knows from its metadata that the file does not exist and should retry creating files. Change from create to createNonexistingFile here to add eventual consistency support.
=> Add eventual consistency support to createFile when creating ufs blocks

core/common/src/test/java/alluxio/underfs/AbstractUnderFileSystemContractTest.java
the `deleteExistingDirectory` is able to solve the create-then-delete eventual consistency issue, but the following `isFile` and `isDirectory` check does not support eventual consistency since they are the S3 current status check.
=> Fix the eventual consistency issue in S3 contract test

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java, core/server/worker/src/main/java/alluxio/worker/block/SpaceReserver.java, core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java, core/server/worker/src/test/java/alluxio/worker/block/SpaceReserverTest.java, core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java, tests/src/test/java/alluxio/client/cli/fs/command/CopyFromLocalCommandIntegrationTest.java, tests/src/test/java/alluxio/client/fs/IsolatedFileSystemIntegrationTest.java, tests/src/test/java/alluxio/client/fs/UfsFallbackFileOutStreamIntegrationTest.java, tests/src/test/java/alluxio/server/ft/MultiWorkerIntegrationTest.java, tests/src/test/java/alluxio/server/tieredstore/LostStorageIntegrationTest.java, tests/src/test/java/alluxio/server/tieredstore/SpecificTierWriteIntegrationTest.java, tests/src/test/java/alluxio/server/tieredstore/TierPromoteIntegrationTest.java
Removes the deprecated synchronous eviction code path.
Previously, Alluxio supported both synchronous and asynchronous eviction. Synchronous eviction was more straightforward but ultimately less efficient because each client request would evict a small amount of data (enough to satisfy the current request space call). Asynchronous eviction allows the evictor to use more information and do a more efficient batch eviction.
=> Remove non async eviction

docs/cn/compute/Spark.md
This syntax error prevents documentation from building properly.
=> [DOCFIX] Fix liquid syntax error

core/server/worker/src/main/java/alluxio/worker/block/allocator/GreedyAllocator.java
Use the @Nullable annotation for all methods which may return null in
/alluxio/core/server/worker/src/main/java/alluxio/worker/block/allocator/GreedyAllocator.java
=> [SMALLFIX] Use the @Nullable annotation

core/server/common/src/main/java/alluxio/metrics/sink/MetricsServlet.java
`text/json` is not a valid content type. See the following resource:
https://www.iana.org/assignments/media-types/media-types.xhtml
We should be using the standard `application/json` which also
defaults its charset to utf-8, so we won't need to specify it explicitly
either.
=> Update metrics servlet to respond with valid Content-Type

docs/en/deploy/Running-Alluxio-On-Docker.md, integration/docker/entrypoint.sh
Addresses https://github.com/Alluxio/alluxio/issues/8947
ALLUXIO_JAVA_OPTS can support any type of property key without
needing translation from environment variable name to property
key name. This PR fixes two bugs in supplying space-separated
options.
1. To iterate over environment variables, we need to set
IFS='\n'. Otherwise, environment variables with values
containing spaces will be parsed as multiple variables.
2. Since environment variables may contain spaces, we need to
wrap their values in strings when writing to alluxio-env.sh
e.g. ALLUXIO_JAVA_OPTS="-Dfoo=bar -Dbaz=bat" instead of
ALLUXIO_JAVA_OPTS=-Dfoo=bar -Dbaz=bat.
Now that ALLUXIO_JAVA_OPTS can support multiple options, it is
the preferred way to configure Alluxio in Docker. This PR
updates the Docker doc to use …
=> Support multiple ALLUXIO_JAVA_OPTS and update doc

core/server/common/src/main/java/alluxio/web/WebServer.java
No port is given in the exception message if the port to bind is taken
=> Add address in exception message when binding port for web server fails

core/common/src/main/java/alluxio/conf/PropertyKey.java
By default, set job worker hostname the same as alluxio worker hostname
=> Set JobWorker hostname to AlluxioWorker hostname by default

core/common/src/main/java/alluxio/cli/AbstractShell.java, core/common/src/main/java/alluxio/cli/Command.java, shell/src/main/java/alluxio/cli/fsadmin/command/PathConfCommand.java, shell/src/main/java/alluxio/cli/fsadmin/pathconf/AddCommand.java, shell/src/main/java/alluxio/cli/fsadmin/pathconf/ListCommand.java, shell/src/main/java/alluxio/cli/fsadmin/pathconf/RemoveCommand.java, shell/src/main/java/alluxio/cli/fsadmin/pathconf/ShowCommand.java, tests/src/test/java/alluxio/client/cli/fsadmin/command/PathConfCommandIntegrationTest.java, tests/src/test/java/alluxio/client/cli/fsadmin/pathconf/AddCommandIntegrationTest.java
Currently, if arguments or options are wrong, only the usage of `pathConf` will be displayed.
This PR makes sub-commands' help messages available when argument or option parsing fails.
A new integration test is added to enforce the new behavior.
=> Improve handling of errors when parsing pathConf commands

docs/en/compute/AWS-EMR.md
Example insert statement for presto fails as it expects a INT and the example uses a string.
=> Update example insert statement for EMR documentation

core/common/src/main/java/alluxio/underfs/UnderFileSystemConfiguration.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/options/MountInfo.java, core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, tests/src/test/java/alluxio/client/fs/MultiUfsMountIntegrationTest.java
This fix changed the API so we hides values of mount options that are credentials.
=> Hide credentials in mount command

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManagerView.java, tests/src/test/java/alluxio/client/fs/FileOutStreamAsyncWriteIntegrationTest.java
Changes the semantic of `getPinIdList` to return both the explicitly pinned inodes and inodes which are in `TO_BE_PERSISTED` state. Inodes in that state should not be evicted or users can experience data loss.
=> Add to be persisted files to pinned file list

core/transport/src/main/java/alluxio/grpc/MetricType.java
When generating the proto files from commit 
042f956bb055db9c0fadeb886d643eac9f95725b
They were not all generated with the latest updates.
This commit regenerates the proto files. It only adds
some comments to the enum MetricType which was
created during from that commit.
=> Update generated proto to include MetricType enum comments

core/common/src/test/java/alluxio/util/network/GetMasterWorkerAddressTest.java
Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/util/network/GetMasterWorkerAddressTest.java
Change
import org.junit.Assert;
to
import static org.junit.Assert.assertEquals;
Put the static imports before non-static imports.
AND
Update all
Assert.assertEquals*
to
assertEquals*
=> Use static imports for standard test utilities

core/client/fs/src/main/java/alluxio/client/block/policy/DeterministicHashPolicy.java
Change
Collections.sort(workerInfos, (o1, o2)
-> o1.getNetAddress().toString().compareToIgnoreCase(o2.getNetAddress().toString()));
to
workerInfos.sort((o1, o2)
-> o1.getNetAddress().toString().compareToIgnoreCase(o2.getNetAddress().toString()));
=> [SMALLFIX] Replace collections.sort() with list.sort

core/server/worker/src/main/java/alluxio/worker/block/allocator/RoundRobinAllocator.java
[SMALLFIX] Use the @Nullable annotation for all methods which may return null in /alluxio/core/server/worker/src/main/java/alluxio/worker/block/allocator/RoundRobinAllocator.java#allocateBlock #499
=> [SMALLFIX] Use @Nullable annotation for methods which may return null

core/common/src/main/java/alluxio/collections/LockCache.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/CompositeInodeLockList.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeLockList.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeLockManager.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java, core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePathList.java, core/server/master/src/main/java/alluxio/master/file/meta/SimpleInodeLockList.java, core/server/master/src/test/java/alluxio/master/file/meta/CompositeInodeLockListTest.java, core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java, core/server/master/src/test/java/alluxio/master/file/meta/LockedInodePathTest.java, core/server/master/src/test/java/alluxio/master/file/meta/SimpleInodeLockListTest.java, minicluster/src/main/java/alluxio/master/LocalAlluxioCluster.java, minicluster/src/main/java/alluxio/master/TestUtils.java, tests/src/test/java/alluxio/client/fs/FileOutStreamAsyncWriteJobIntegrationTest.java
Previously, we would skip taking "unnecessary" locks on inodes and edges. A lock was considered unnecessary if one of its ancestors was already write-locked, e.g. if we've write-locked /a/b, we don't need to acquire any more locks to lock /a/b/c/d. This is what we called implicit locking.
Implicit locking works well when all locks are taken starting from the root. However, we sometimes want to lock individual inodes without needing to lock their ancestors. In particular, CachingInodeStore needs to evict inodes from memory to RocksDB, which requires locking the inodes directly (locking their ancestors would be too expensive).
To support random locks, we remove the concept of implicit locking. With this PR, we replace implicit locks with explicit write locks. For the above example, we will …
=> Remove implicit inode locking

core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
This PR fixes two issues:
- Alluxio client can use ping service to query the health of Alluxio services. On client the authentication was incorrectly enabled by default causing it to fail to start when there is no client credentials given.
- Another problem is that the client fails to retry because the gRPC `UnavailableException` is not converted to the `AlluxioStatusException`, effectively render the retry logic invalid.
=> Fix ping service client

docs/en/deploy/Running-Alluxio-On-a-Cluster.md
Zookeeper client does session tracking and validation (pings) on separate threads. This could make sessions timeouts likely during high CPU utilization. With multi threaded backups, we have seen consistent session timeouts during backup of a cluster with 1 billion files, which causes the leader to change and backup to be interrupted.( See https://github.com/Alluxio/alluxio/issues/9023 for details) This PR adds a note to related doc section.
=> Update cluster docs with a note on zookeeper session timeouts

core/server/master/src/main/java/alluxio/master/metastore/DelegatingReadOnlyInodeStore.java, core/server/master/src/main/java/alluxio/master/metastore/InodeStore.java, core/server/master/src/main/java/alluxio/master/metastore/ReadOnlyInodeStore.java, core/server/master/src/main/java/alluxio/master/metastore/ReadOption.java, core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java, core/server/master/src/main/java/alluxio/master/metastore/caching/CachingInodeStore.java, core/server/master/src/main/java/alluxio/master/metastore/heap/HeapInodeStore.java, core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java, core/server/master/src/test/java/alluxio/master/metastore/caching/CachingInodeStoreMockedBackingStoreTest.java
Scanning all a large portion of the inode tree can thrash metastore when using the CachingInodeStore. Frequent eviction would negatively impact the performance of the cache.
This PR introduces an option to disable caching and eviction when getting inodes from CachingInodeStore.
=> Add option for skipping caching and eviction for scanning inode tree

core/client/fs/src/test/java/alluxio/client/file/FileSystemFactoryTest.java, core/common/src/main/java/alluxio/conf/PropertyKey.java, minicluster/src/main/java/alluxio/master/MultiMasterLocalAlluxioCluster.java
Currently the default leader path is "/leader" and the default election path is "/election". These defaults make sense when Zookeeper is being used for Alluxio only, but in real-world deployments, there will often be multiple services making use of Zookeeper. Change the defaults to something like "/alluxio/leader" and "/alluxio/election" so that there's a better chance that users will not have to change them. It is especially annoying to use non-default paths because clients need to be configured with the leader path, and this configuration can't be specified through a centralized cluster config, or by adding something to the URI.
=> Change Zookeeper path defaults

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
Will prevent the generation of ._* files when building on Mac
Addresses #8359
=> Skip generating OS X tmp files

core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java, core/server/master/src/test/java/alluxio/master/file/meta/BaseInodeLockingTest.java, core/server/master/src/test/java/alluxio/master/file/meta/LockedInodePathTest.java
Suppose WRITE_INODE on path /a/b/c, and only /a exists, then both inode a and edge a->b should be read locked, otherwise, a concurrent rename from /a/c -> a/b will succeed.
See the enhanced unit test in LockedInodePathTest.
=> Fix a bug where last edge is not locked in WRITE_INODE pattern

.gitignore, core/common/pom.xml, core/common/src/main/java/alluxio/wire/AlluxioJobMasterInfo.java, core/common/src/main/java/alluxio/wire/AlluxioJobWorkerInfo.java, core/common/src/main/java/alluxio/wire/TieredIdentity.java, core/server/master/pom.xml, core/server/master/src/main/java/alluxio/master/block/BlockMasterClientRestServiceHandler.java, core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, core/server/proxy/pom.xml, core/server/proxy/src/main/java/alluxio/proxy/AlluxioProxyRestServiceHandler.java, core/server/proxy/src/main/java/alluxio/proxy/PathsRestServiceHandler.java, core/server/proxy/src/main/java/alluxio/proxy/StreamsRestServiceHandler.java, core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java, core/server/worker/pom.xml, core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java, job/server/pom.xml, job/server/src/main/java/alluxio/master/AlluxioJobMasterRestServiceHandler.java, job/server/src/main/java/alluxio/worker/AlluxioJobWorkerRestServiceHandler.java, pom.xml, templates/markdown.hbs, templates/operation.hbs, templates/strapdown.html.hbs
Resulting documentation example is attached. We can change the styling to other bootswatch templates. I've chosen one that is similar to Alluxio colors (blue).
Docs are generated in `generated/<service>/index.html`. So far the job, master, worker, and proxy are supported. Deprecated APIs are not documented, and internal APIs (ie. for the web ui) are not documented because we do not want others to rely on them.
=> Use Swagger to generate rest docs

pom.xml
If we don't exclude `./generated` the `generate-tarballs` script
will fail when building UFS modules because of the license check
after compiling the codebase
=> Fix generate-tarballs - exclude generated restdoc from license check

core/client/hdfs/src/main/java/alluxio/hadoop/HdfsFileInputStream.java
The original code will only use cluster configurations, which suppresses path configurations in openFile. This behavior will cause long running clients like Presto to never be able to use path level configurations even after restarting.
=> Use default options in HdfsFileInputStream

core/server/master/src/main/java/alluxio/master/file/meta/SimpleInodeLockList.java
Although the Entry abstraction in SimpleInodeLockList makes code more readable, but it unnecessarily stores extra representations of Edges, each consumes a long and a String. Since Each FileSystemMaster operation will create at least one InodeLockList, the lower memory consumption the better.
This PR removes the Entry abstraction without sacrificing readability too much.
=> Reduce memory footprint of InodeLockList

core/common/src/main/java/alluxio/wire/SyncPointInfo.java
name matching of enums is tricky and i think this way is safer.
=> Fix sync point status not found error

bin/alluxio-start.sh
Previously, it requires redudant steps to start a local & single node cluster:
- Set `alluxio.master.hostname=localhost` in `conf/alluxio-site.properties`
- Pass `local` as an arg to `alluxio-start.sh`
After this PR, running `alluxio-start.sh local` implies setting `alluxio.master.hostname=localhost`. Therefore reduce the steps to test-drive alluxio in a local mode
=> Run alluxio-start.sh local without creating alluxio-site.properties

core/common/src/main/java/alluxio/underfs/UnderFileSystem.java, examples/src/main/java/alluxio/examples/UnderFileSystemCommonOperations.java, underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java
getStatus throws FileNotFoundException is path does not exist. `LocalUnderFileSystem` did not meet this behavior earlier.
=> Update ufs:getStatus contract to throw FileNotFoundException

bin/alluxio-start.sh
Otherwise running `bin/alluxio-start.sh logserver` or `safe` will fail due to monitoring not being supported.
=> Add a white list to the monitor script

integration/docker/entrypoint.sh, integration/kubernetes/alluxio-master.yaml.template, integration/kubernetes/alluxio-worker.yaml.template
- Remove unnecessary hostPID:true from default spec
- Do not format master or worker on restart
- Split job services into a separate container within the same pod
=> Improve k8s specs

examples/src/main/java/alluxio/cli/UnderFileSystemContractTest.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
If the `HdfsUnderFileSystemContractTest` is running from maven, the classloader will all be `AppClassLoader`. 
When running from `./bin/alluxio runUfsTests --path hdfs://<host>:<port>/dir`, the thread class loader is `ExtensionClassLoader`. However, when we are getting the filesystem, the class loader is `AppClassLoader`. 
We use `ExtensionClassLoader` to load `org.apache.hadoop.fs.FileSystem`, but use `AppClassLoader` to load `org.apache.hadoop.fs.LocalFileSystem`.  Because they are from two different class loader, `LocalFileSystem` cannot be recognized as implementing the interface `FileSystem`.
From https://www.ibm.com/developerworks/java/library/j-dyn0429/
```
when an interface and associated implementation are each loaded by two separate class loaders. 
Even though the names and …
```
=> [SMALLFIX] Fix the class loader for hadoop getFileSystem

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java, core/client/fs/src/main/java/alluxio/client/block/policy/LocalFirstPolicy.java, core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java, core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java, core/client/fs/src/main/java/alluxio/client/block/util/BlockLocationUtils.java, core/client/fs/src/test/java/alluxio/client/block/policy/LocalFirstAvoidEvictionPolicyTest.java, core/client/fs/src/test/java/alluxio/client/block/policy/LocalFirstPolicyTest.java, core/client/fs/src/test/java/alluxio/client/block/stream/BlockInStreamTest.java, core/client/fs/src/test/java/alluxio/client/block/util/BlockLocationUtilsTest.java, core/client/fs/src/test/java/alluxio/client/util/ClientTestUtils.java, core/common/src/main/java/alluxio/util/network/NettyUtils.java, core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java, integration/docker/entrypoint.sh, integration/kubernetes/alluxio-fuse.yaml.template
In a containerized env such as k8s, the worker and client hostname may not match. To determine if a worker is local, file system inspection is used instead when property `alluxio.worker.data.server.domain.socket.as.uuid=true` is set.
In this PR:
- update the method to choose a local worker for BlockInStream/OutStream
- if client container does not mount domain socket dir but has the same hostname as worker, do not attempt to open local file short circuit stream if worker supports domain socket (as /dev/shm is not accessible)
- unmount as part of fuse startup in case k8s shutdown hook is flaky
=> Fix locality in containerized environments

examples/src/main/java/alluxio/examples/UnderFileSystemCommonOperations.java
After the change of https://github.com/Alluxio/alluxio/pull/9148/files#diff-d782d1238759ec4b08c7197a4aebbbcfR104, when running `./bin/alluxio runUfsTests --path s3a://<>` the test throw exception because it fails to cast `UnderFileSystemWithLogging` to `ObjectUnderFileSystem`. These two classes may be loaded by two different class loaders. 
Without the change in the previous URL, we will have another Class loader exception in `HdfsUnderFileSystem`: 
```
org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback not org.apache.hadoop.security.GroupMappingServiceProvider
```
To avoid the conflicts, I remove the cast to `ObjectUnderFileSystem` in the ufs tests.
=> [SMALLFIX] Fix the cast exception in ufs contract test

core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java, core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java, core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java, core/server/worker/src/main/java/alluxio/worker/block/BlockStore.java, core/server/worker/src/main/java/alluxio/worker/block/BlockWorker.java, core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java, core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java, core/server/worker/src/main/java/alluxio/worker/grpc/BlockWriteHandler.java, core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockWriteHandler.java, core/server/worker/src/main/java/alluxio/worker/grpc/WriteRequest.java, core/server/worker/src/test/java/alluxio/worker/block/BlockWorkerTest.java, core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java, core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTestUtils.java, core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockReaderTest.java, core/server/worker/src/test/java/alluxio/worker/grpc/BlockWriteHandlerTest.java, core/transport/src/grpc/block_worker.proto, core/transport/src/main/java/alluxio/grpc/BlockWorkerProto.java, core/transport/src/main/java/alluxio/grpc/CreateLocalBlockRequest.java, core/transport/src/main/java/alluxio/grpc/CreateLocalBlockRequestOrBuilder.java, core/transport/src/main/java/alluxio/grpc/WriteRequestCommand.java, core/transport/src/main/java/alluxio/grpc/WriteRequestCommandOrBuilder.java, tests/src/test/java/alluxio/client/rest/BlockMasterClientRestApiTest.java
When a new block is written to Alluxio it becomes a candidate for eviction. The worker fetches the pinned list (including to be persisted file ids) from the master in a heartbeat to prevent eviction of files which are not yet persisted. If a worker is running near storage capacity, a to be persisted block may be evicted before the worker heartbeat fetches the pinned list from the master.
To overcome this issue, let’s look at different scenarios when a block is created on the worker TieredBlockStore. For each of these scenarios if the block create request contains the pinned flag at create time, we can prevent eviction.
- Client short-circuit writes to local worker: alluxio.grpc.CreateLocalBlockRequest will need an additional field
- Client remote writes to worker: …
=> Prevent async eviction of ASYNC_THROUGH because of race condition

tests/src/test/java/alluxio/client/cli/JournalToolTest.java
Reason for switching to multiprocess  cluster in journaltool test was to validate passive reading of embedded journal. Now that it's not supported, this PR reverts to a local cluster which also eliminates the flakiness of test.
=> Use local cluster for journaltool test

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/grpc/GrpcChannel.java, core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java, core/common/src/main/java/alluxio/grpc/GrpcServer.java, core/common/src/main/java/alluxio/grpc/GrpcServerBuilder.java, core/common/src/main/java/alluxio/security/authentication/AuthenticatedChannel.java, core/common/src/main/java/alluxio/security/authentication/AuthenticationServer.java, core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java, core/common/src/main/java/alluxio/security/authentication/DefaultAuthenticationServer.java, core/common/src/main/java/alluxio/security/authentication/SaslServerHandler.java, core/common/src/main/java/alluxio/security/authentication/SaslStreamClientDriver.java, core/common/src/main/java/alluxio/security/authentication/SaslStreamServerDriver.java, core/common/src/main/java/alluxio/security/authentication/plain/SaslServerHandlerPlain.java, core/common/src/test/java/alluxio/security/authentication/GrpcSecurityTest.java, tests/src/test/java/alluxio/client/fuse/FuseFileSystemIntegrationTest.java
`AuthenticationServer` has a setting for revoking authentication after a period of inactivity. To handle that on the client side, metadata clients, after a period of inactivity, will retry after getting `Unauthenticated` code. However, due to nature of streaming, data clients can not retry after getting the error because they might have pipelined more data before seeing the error. And since this revocation will not change the connection state, they used to continue getting `Unauthenticated`. See https://github.com/Alluxio/alluxio/issues/9089 for an instance of this problem.
This PR introduces long polling to authentication handshake. Client and server will not complete streams used for authentication and instead will use it for notifying end of an authentication session. With this change, …
=> Implement authentication long polling

underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUtils.java, underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUtilsTest.java
User reported when testing 2.0.0-RC1, S3 compatible UFS like minio may return user grantee without a ID associated, introducing NPE like
```
java.lang.NullPointerException
at alluxio.underfs.s3a.S3AUtils.isUserIdInGrantee(S3AUtils.java:57)
at alluxio.underfs.s3a.S3AUtils.translateBucketAcl(S3AUtils.java:47)
at alluxio.underfs.s3a.S3AUnderFileSystem.getPermissionsInternal(S3AUnderFileSystem.java:573)
at alluxio.underfs.s3a.S3AUnderFileSystem$1.firstTime(S3AUnderFileSystem.java:120)
at alluxio.underfs.s3a.S3AUnderFileSystem$1.get(S3AUnderFileSystem.java:115)
at alluxio.underfs.s3a.S3AUnderFileSystem.getPermissions(S3AUnderFileSystem.java:552)
at alluxio.underfs.ObjectUnderFileSystem.listInternal(ObjectUnderFileSystem.java:998)
at alluxio.underfs.ObjectUnderFileSystem.listStatus(ObjectUnderFi …
```
=> Fix a NPE issue for a corner case of S3 compatible UFS

bin/alluxio, core/common/src/main/java/alluxio/util/CommonUtils.java, examples/src/main/java/alluxio/cli/UnderFileSystemContractTest.java, examples/src/main/java/alluxio/examples/S3ASpecificOperations.java, examples/src/main/java/alluxio/examples/UnderFileSystemCommonOperations.java, job/client/src/main/java/alluxio/client/job/JobGrpcClientUtils.java, shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java, shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java, shell/src/main/java/alluxio/cli/fs/command/DistributedMvCommand.java, shell/src/main/java/alluxio/cli/fsadmin/command/CheckpointCommand.java
Previously, the `./bin/alluxio runUfsTests` will log all the messages on the console. When running against object stores, many retry messages will show on the console to make users confusing. Moving the logs to user.log. Fix one UFS test.
=> [SMALLFIX] Improve runUfsTests console message and tests

core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
The MASTER_HOSTNAME maybe set by other tests. In this unit test, I make sure the MASTER_HOSTNAME is unset before the test
=> [SMALLFIX] Deflake cannotInitializeWithoutMasterHostname test

core/server/master/src/main/java/alluxio/master/file/meta/InodeTreeBufferedIterator.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java, core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeBufferedIteratorTest.java
In current code there are cases where failure during inode buffering could go unnoticed. This could  raise false positives while taking a backup, and cause backup file to not contain the complete master state. This fix is to ensure buffering failures are not overlooked during enumeration.
=> Do harden exception handling for inode crawler

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
This PR corrects detection of FUSE installation on MacOS. It used be checking presence of installer in mounted list, now it validates the installed package list.
=> Improve detecting FUSE installation for test

bin/alluxio-start.sh
Fix #9185
After this PR running `$ bin/alluxio-start.sh local` with SSH  disabled on my local laptop:
```
[10:01:40]binfan@:alluxio (smallfix2)$ bin/alluxio-start.sh local
Assuming NoMount by default.
Killed 1 processes on MacBook-Pro-5
Killed 1 processes on MacBook-Pro-5
Killed 1 processes on MacBook-Pro-5
Killed 1 processes on MacBook-Pro-5
Killed 0 processes on MacBook-Pro-5
Killed 1 processes on MacBook-Pro-5
Starting master @ MacBook-Pro-5. Logging to /Users/binfan/Dropbox/Work/alluxio/alluxio/logs
Starting job master @ MacBook-Pro-5. Logging to /Users/binfan/Dropbox/Work/alluxio/alluxio/logs
Starting worker @ MacBook-Pro-5. Logging to /Users/binfan/Dropbox/Work/alluxio/alluxio/logs
Starting job worker @ MacBook-Pro-5. Logging to /Users/binfan/Dropbox/Work/alluxio/alluxio/logs …
```
=> Run alluxio-start.sh local without SSH

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/util/UnderFileSystemUtils.java, underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSInputStream.java, underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java, underfs/gcs/src/test/java/alluxio/underfs/gcs/GCSUnderFileSystemTest.java, underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
This PR improves the GCS UFS similar to our previous improvements to S3A UFS.
(1) move all permission related code to `GCSUnderFileSystem.getPermissionInternal()` and memorize the permission (only get the permission for once and remember it). This change mocks what S3A UFS does.
(2) In `GCSInputStream`, mainly reorganize the codes. Move create `inputStream` related codes in the `openStream()` other than in the constructor. The constructor suppose to not throw exceptions.  Use `openStream()` and `closeStream()` similar to what S3A UFS does.
(3) remove the `UnderFileSystemConfiguration mConf` in `S3AUnderFileSystem` since its super class `BaseUnderFileSystem` already have the member `UnderFileSystemConfiguration mUfsConf`.
=> Improve GCS UFS

core/common/src/main/java/alluxio/util/executor/ControllableQueue.java, core/common/src/test/java/alluxio/util/executor/ControllableSchedulerTest.java
There is a bug in `ControllableQueue.remove` where it is trying to remove the item from priority queue which holds a list of wrappers. This change fixed it by comparing the value of the wrapper to the item instead.
=> Fix remove function for ControllableQueue

core/common/src/main/java/alluxio/wire/FileInfo.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Expose `XAttr` on `FileInfo` so internal services can use it.
=> Add XAttr to FileInfo

examples/src/main/java/alluxio/examples/UnderFileSystemCommonOperations.java
Some `inputStream.read()` throws IOE exception when unable to read instead of returning -1.
This test consider the object store eventual consistency and allow retry `inputStream.read()` when fail to read.
=> [SMALLFIX] Fix the inputStream.read() in runUfsTests

underfs/cos/pom.xml, underfs/gcs/pom.xml, underfs/hdfs/pom.xml, underfs/kodo/pom.xml, underfs/oss/pom.xml, underfs/s3a/pom.xml, underfs/swift/pom.xml, underfs/wasb/pom.xml
the ufs contract test is moved from test scope to `./bin/alluxio runUfsTests`. The `UfsContractTest` profile is not needed any more
=> [SMALLFIX] Clean up the remaining pom code about ufs contract test

docs/en/contributor/Building-Alluxio-From-Source.md
alluxio-start.sh script started to override hostname for `local` profile. So we could simplify related section of this doc.
=> Remove redundant config file manipulation from doc

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
In generate release tarballs it states we are creating `alluxio-version-bin.tar.gz`
=> Add -bin suffix to genearted tarball

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/contexts/CreateDirectoryContext.java, core/server/master/src/main/java/alluxio/master/file/contexts/CreatePathContext.java, core/server/master/src/main/java/alluxio/master/file/contexts/LoadMetadataContext.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/main/java/alluxio/master/file/meta/MutableInodeDirectory.java, core/server/master/src/main/java/alluxio/master/file/meta/MutableInodeFile.java, core/transport/src/main/java/alluxio/proto/journal/File.java, core/transport/src/proto/journal/file.proto
This change aims to allow the calls to the UFS from the
FileSystemMaster to propagate into the inode tree. This will
allow developers in the future to leverage any xattr that are
returned from the UFS implementations in order to make
optimizations or other assumptions about the state of a node
past the standard set of fields.
Most of these changes are mechanical, it's just a matter of
finding exactly where to set the xattr and where not to.
For now, the only usecase for setting xattr is during sync or
loadMetadata calls. The implementation adds the xattr to the
create*Context so that the inode tree can utilize set the xattr
on inodes from within the inode tree class.
=> Propagate xattr from UfsStatus to Inode

docs/en/ufs/OBS.md
The OBS jars are not hosted in the `alluxio-extensions/underfs/obs/target` anymore. Users required to build them directly.
=> [DOCFIX] Fix the OBS docs

conf/log4j.properties, core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
- `org.apache.thrift.transport.TSaslTransport` is no more relevant but `io.grpc.netty.NettyServerHandler` becomes the new noisy logger
- `LOG.debug("Replacing {} with {}", matcher.group(1), value);` is very noisy during startup
=> Reduce noice level on DEBUG logging

core/common/pom.xml, core/common/src/main/java/alluxio/master/ZkMasterInquireClient.java, core/common/src/test/java/alluxio/master/ZkMasterInquireClientTest.java
ZkMasterInquireClient fails to break out of loop if there is no active participant under leader path.
=> Break infinite-loop during zk leader query

core/server/common/src/main/java/alluxio/Registry.java, core/server/common/src/main/java/alluxio/Server.java, core/server/common/src/main/java/alluxio/master/AbstractMaster.java, core/server/common/src/main/java/alluxio/master/NoopMaster.java, core/server/common/src/main/java/alluxio/worker/AbstractWorker.java, core/server/common/src/test/java/alluxio/master/RegistryTest.java, core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java, core/server/master/src/main/java/alluxio/master/AlluxioSecondaryMaster.java, core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java, core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/main/java/alluxio/master/metastore/BlockStore.java, core/server/master/src/main/java/alluxio/master/metastore/heap/HeapBlockStore.java, core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockStore.java, core/server/master/src/test/java/alluxio/master/MockMaster.java
Leaving `RocksBlockStore` unclosed, will block creating further stores at the same path. This prevents running fail-over scenarios in single process tests with ROCKS meta-store. This PR makes necessary plumbing to make sure `RocksBlockStore` is closed during master shutdown.
=> Implement close() for BlockStore interface

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointThread.java, core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java, core/server/master/src/test/java/alluxio/master/journal/ufs/UfsJournalLogWriterTest.java
For v1 UFS journals, flush failure handling will leave journal system in a state where 
- current log file is uncompleted. 
- subsequent journal writes will cause a new log file creation.
Since secondary journal skips incomplete files, this will create a gap in journal sequences it sees and its background thread will crash.
This PR:
- fixes flush failure handling. 
- crashes secondary process crashes when journal replaying encounters an issue.
=> Improve UFS journal flush/replay failure handling

core/common/src/main/java/alluxio/metrics/MetricsSystem.java, core/common/src/test/java/alluxio/metrics/MetricsSystemTest.java, core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java
Removed escape() logic in alluxio.metrics.MetricsSystem of replacing "/" with "_".
Now the escape only replaces "." with "_".
=> Fix slashes get converted to underscores in the metrics UI page

bin/alluxio, bin/alluxio-start.sh, libexec/alluxio-config.sh
- Move `bootstrapConf` to `case` as other commands in `bin/alluxio`. The reason is we no more change `conf/alluxio-env.sh` inside `bootstrapConf`
- Add more Java version check in `libexec/alluxio-config.sh` --- we require Java 1.8 to run Alluxio at least for now
- Continue support of `ALLUXIO_UNDERFS_ADDRESS` and add warning about deprecation
=> Apply a few shell improvement in start scripts

.gitignore, core/common/src/main/java/alluxio/conf/PropertyKey.java, core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
Change the default backup directory to be '/opt/alluxio/alluxio_backups' on the current Alluxio Primary Master
If a path is provided via CLI, then fall back to using UFS (same behaviour)
If a path is provided via CLI with the --local option, then backup to the specified directory on the primary master (same behaviour)
=> Change journal backup default

docs/en/ufs/Minio.md
Docs were straightforward. I had to follow MinIO's getting started page to get everything setup. 
- Changes are mainly small typos and changing 'Minio' to 'MinIO' to match their spelling
=> [DOCFIX] Update MinIO doc for 2.0

core/common/src/main/java/alluxio/security/authentication/DefaultAuthenticationServer.java, core/common/src/main/java/alluxio/security/authentication/SaslStreamServerDriver.java
Another round of tracing improvements for gRPC authentication.
Basically, long polling makes the code more prone to receive CANCELLED events.
=> Improve authentication tracing

job/server/src/main/java/alluxio/master/job/JobMaster.java
gRPC requires `io.grpc.Context` instance to be forked if an RPC implementation calls another RPC. Because termination of first call will invalidate context of the cascaded calls. Even if calls are contained within each other, with authentication long polling, authentication stream opened for the second call will be canceled after first call returns. That means every call to first RPC will cause tearing up of channel used for the second RPC. 
This PR forks gRPC context inside `JobMaster:run RPC call` since some job definitions require RPC calls during initialization.
=> Fix job-master gRPC context cascading

docs/_data/table/Alluxio-FUSE-parameter.csv, docs/_data/table/cn/Alluxio-FUSE-parameter.yml, docs/_data/table/en/Alluxio-FUSE-parameter.yml
Add the missing property `alluxio.fuse.user.group.translation.enabled` to the fuse property table.
=> [DOCFIX] Add a property in the fuse property table

core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java, core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/transport/src/grpc/file_system_master.proto, core/transport/src/main/java/alluxio/grpc/CompleteFilePOptions.java, core/transport/src/main/java/alluxio/grpc/CompleteFilePOptionsOrBuilder.java, core/transport/src/main/java/alluxio/grpc/FileSystemMasterProto.java
Current `FileOutStream` schedules async persistence after completing the file. In case of an error while scheduling persist job, content will be lost for `ASYNC_THROUGH`. This PS introduces a flag tot completeFile RPC for scheduling async persistence before returning the call. 
Removing extra RPC also gives about %10 throughput increase for ASYNC_THROUGH create.
=> Unify completing a file and scheduling persistence

underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java, underfs/local/src/test/java/alluxio/underfs/local/LocalUnderFileSystemTest.java
In the getDirectoryStatus javadoc:
- If a path is a file, this method should throw an exception
In the getFileStatus javadoc:
- If a path is a directory, this method should throw an
exception
Unit tests added for behavior verification.
=> Fix behavior of get*Status in LocalUnderFileSystem

core/common/src/main/java/alluxio/concurrent/ForkJoinPoolHelper.java, core/common/src/main/java/alluxio/concurrent/ManagedBlockingUfsForwarder.java, core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
If `ForkJoinPool` is saturated with max number of threads, doing managed blocking could fail with `RejectedExecutionException`. This will cause existing RPC to be failed. This PR makes callers of manage blocking to fall back to regular blocking, when such happens.
=> Revert to regular blocking if managed blocking fails

core/common/src/main/java/alluxio/cli/AbstractShell.java, shell/src/main/java/alluxio/cli/fs/FileSystemShell.java, shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShell.java, shell/src/main/java/alluxio/cli/fsadmin/FileSystemAdminShellUtils.java, shell/src/main/java/alluxio/cli/fsadmin/command/Context.java, shell/src/main/java/alluxio/cli/job/JobShell.java
Failure to close resources that has gRPC channels will cause abrupt channel termination, thus annoying `CANCELLED` exception in the master logs.
=> Close shell resources properly after command execution

docs/en/api/POSIX-API.md, docs/en/compute/Tensorflow.md, integration/fuse/bin/alluxio-fuse
Remove the solid requirement for setting of JAVA_HOME in alluxio-fuse script
=> Fix fuse docs and script

core/common/src/main/java/alluxio/conf/PropertyKey.java, docs/en/advanced/Namespace-Management.md
1. Updated PropertyKey.java description for 1 key
2. Updated Namespace-Management.md fixing 1 indentation.
=> [DOCFIX] Fix namespace mgmt and storage mgmt docs

tests/src/test/java/alluxio/server/ft/journal/ufs/UfsConfigurationJournalTest.java
@ns1123 @ZacBlanco @calvinjia FYI this was not an issue in 1.8 so only adding the integration test here.
=> Add integration test for read-only mount after restart

core/common/src/test/java/alluxio/metrics/MetricsSystemTest.java
The counter needs to be reset to 0 if we don't want tests stepping on each other.
=> Reset the counter in MetricsSystemTest

core/server/common/src/main/java/alluxio/ProcessUtils.java
Stack trace info was lost due to https://github.com/Alluxio/alluxio/pull/9343 on exceptions starting the process.  That pr introduced a side-effect that the stack trace is lost from the log. Note that the original logging will output the entire exception including stack trace of `t`:
```
LOG.error("Uncaught exception while running {}, stopping it and exiting.", process, t)
```
After this PR, one will see sth like, to me it actually becomes harder to debug.
```
ERROR ProcessUtils - Uncaught exception while stopping Alluxio worker, simply exiting. Exception java.lang.NullPointerException, Root Cause null
```
as supposed to
```
ProcessUtils - Uncaught exception while stopping Alluxio worker, simply exiting.
java.lang.NullPointerException
at …
```
=> Fix a regression in priting StackTrace on exception

shaded/hadoop/pom.xml
This is the quick fix for #9416 thanks to @asin929 in 2.0 branch.
This version string is correct to be `${ufs.hadoop.version}` in master (2.1.0-SNAPSHOT) branch but was updated and hardcoded to be `2.2.1-SNAPSHOT` in branch-2.0 due to maven release plugin.
Talked to @calvinjia , we should modify the POM to mark this module to be skipped during release process.
=> Fix version string in shaded-hadoop module

tests/src/test/java/alluxio/client/cli/fs/JobServiceFaultToleranceShellTest.java, tests/src/test/java/alluxio/server/ft/MasterFaultToleranceIntegrationTest.java, tests/src/test/java/alluxio/server/ft/journal/JournalMigrationIntegrationTest.java, tests/src/test/java/alluxio/server/ft/journal/JournalShutdownIntegrationTest.java, tests/src/test/java/alluxio/server/ft/journal/MultiMasterJournalTest.java, tests/src/test/java/alluxio/server/ft/journal/MultiProcessCheckpointTest.java, tests/src/test/java/alluxio/server/ft/journal/TriggeredCheckpointTest.java
Multi master test clusters makes use of embedded zookeeper server. This PR is an attempt to stabilize cluster initialization/termination code on some tests for making sure we don't leak embedded zookeeper servers, which could adversely effect following tests.
Since multi-master tests are usually run on a same JVM, one flake was causing whole bunch of tests to fail.
=> Fix leaking zk servers during various multi-master tests

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, tests/src/test/java/alluxio/client/fs/ReadOnlyMountIntegrationTest.java
Fix https://github.com/Alluxio/alluxio/issues/9399 where `pin` failed due to readonly mount
=> Fix failed Pin on readonly mount

docs/en/compute/AWS-EMR.md
2.0 was built before the change was made to generate-tarball. Updated docs to provide an alternate location to grab the emr files.
=> Add Github link for EMR docs

core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, webui/common/src/components/FileView/FileView.tsx, webui/common/src/utilities/misc/renderFileNameLink.tsx, webui/master/src/containers/pages/Browse/Browse.tsx, webui/master/src/containers/pages/Browse/__snapshots__/Browse.test.tsx.snap, webui/master/src/containers/pages/Logs/Logs.tsx, webui/worker/src/containers/pages/BlockInfo/BlockInfo.tsx, webui/worker/src/containers/pages/Logs/Logs.tsx
Fixes #9465 
Invariants -
Paths presented to the user are not encoded.
Paths in URLs/links are encoded, except for specific references to the root path (a constant `/`).
=> Fix unencoded paths for the web ui

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/DefaultPermissionChecker.java, core/server/master/src/main/java/alluxio/master/file/PermissionChecker.java, tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java
Currently owner of file/directory cannot change permission when they don't have write privilege. This is inconsistent with Unix and HDFS. This fix updated the permission requirement so the user should be able to perform chmod if and only if the user is the owner or super user.
=> Enable owner to chmod, even without write privilege

core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java, core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java, core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, tests/src/test/java/alluxio/client/fs/ReadOnlyMountIntegrationTest.java
The SetAttribute RPC in the client works via omission of
properties. If a property is included within the RPC options
object, then it is assumed the user set this property and
should then be set on the inode. This works for all fields
within the SetAttribute call except for the sync interval.
The metadata sync interval must be included on client RPCs.
Otherwise, if it is not included, then the
DefaultFileSystemMaster will assume that the user has
implicitly set a sync interval of 0 - which results in syncing
metadata for every RPC. Users can still override this value
from their configuration. However, by default it should be
sending a value of -1 (the default for the property key).
This change makes sure that the interval is set and adds a
small unit test.
Fixes #9470
=> Add metadataSyncInterval to client RPCs by default

webui/master/src/containers/pages/Browse/Browse.tsx, webui/master/src/containers/pages/Logs/Logs.tsx, webui/worker/src/containers/pages/Logs/Logs.tsx
- Fixes #9483
- making sure we initialize the field with `0` offset even if parsed query has `undefined` offset
=> Fix 'Display from byte offset' input

core/server/common/src/main/java/alluxio/master/PrimarySelectorClient.java
After bumping zk client version to 3.5.5, leader election was broken against 3.4.x servers.
This fix restores the support by making sure unsupported features are not used in write path.
=> Support writing to zk 3.4.x servers

webui/master/src/containers/pages/Logs/Logs.tsx, webui/master/src/containers/pages/Logs/__snapshots__/Logs.test.tsx.snap, webui/worker/src/containers/pages/Logs/Logs.tsx, webui/worker/src/containers/pages/Logs/__snapshots__/Logs.test.tsx.snap
- Fixes #9482 
- shouldn't use truthy/falsy values for this check - `data.fileData = ''` is still valid for a real file
=> Fix log file with 0 byte offset from end

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
cherry-pick of Alluxio/alluxio#8192
cherry-pick commits are:
change fuse get attr : Alluxio/alluxio@fb36eea63268
change the error message : Alluxio/alluxio@9c78eaa12b36
update status after file completed : Alluxio/alluxio@70eb188fa485
fix the getAttr error : Alluxio/alluxio@c270a101fad6
=> Wait for file completed in fuse getAttr (#8192)

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
Fix #9461
If umount an Alluxio FUSE mount point,
fs.mount() returns without any exception.
but fs.umount() will conflict with the running umount command,
that results in "target is busy" error and umount command failing.
=> Fix Unmount failure by Alluxio FUSE

webui/common/src/utilities/misc/renderFileNameLink.tsx
- `lastFetched` was used to visually show which link was previously clicked on. Didn't seem to work since when we switch from file view to directory view, we always send out a new fetch request, so `lastFetched` keeps getting cleared
- it's best to just remove it since it has no real usage
=> Fix UI issue with unused var

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
=> Remove close because there is no close API in 1.8

core/common/src/main/java/alluxio/conf/InstancedConfiguration.java, core/common/src/test/java/alluxio/ConfigurationTest.java
Fixes https://github.com/Alluxio/alluxio/issues/9020 and
https://github.com/Alluxio/alluxio/issues/8997
When users specify a unknown storage alias (e.g., "ssd" rather than
"SSD"), they will see the following error message on NPE:
```
2019-05-13 14:29:07,034 ERROR ProcessUtils - Uncaught exception while
stopping Alluxio worker, simply exiting.
java.lang.NullPointerException
at
alluxio.worker.block.DefaultBlockWorker.stop(DefaultBlockWorker.java:262)
at alluxio.Registry.stop(Registry.java:149)
at
alluxio.worker.AlluxioWorkerProcess.stopWorkers(AlluxioWorkerProcess.java:287)
at
alluxio.worker.AlluxioWorkerProcess.stop(AlluxioWorkerProcess.java:274)
at alluxio.ProcessUtils.run(ProcessUtils.java:41)
at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:69)
```
This PR makes alluxio service …
=> Add check on tiered storage configuration and avoid NPE

tests/src/test/java/alluxio/client/cli/JournalToolTest.java
When using async through there can be timing related issues with the persist step
=> Change journal tool test to use must cache instead of async

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
**Description**
The exception message "Active Syncing is not supported on this UFS type" + ufsResource.get().getUnderFSType() will get the result "Active Syncing is not supported on this UFS types3" for s3.
**Improvement**
Append : space for the message: "Active Syncing is not supported on this UFS type: ", And the result will be "Active Syncing is not supported on this UFS type: s3" for s3.
=> Add : space for exception message

core/common/src/main/java/alluxio/exception/AggregateException.java, shell/src/main/java/alluxio/cli/fs/command/CheckConsistencyCommand.java, tests/src/test/java/alluxio/client/cli/fs/command/CheckConsistencyCommandIntegrationTest.java
Instead of serially repairing each URI from the list of
inconsistent URIs this PR utilizes an ExecutorService on the
client to run the repairs in parallel. The default number of
threads to use is `2*<number of cpu cores>` but users can
optionally specify their own number with the `-t` or
`--threads` option
Fixes #9527
pr-link: Alluxio/alluxio#9555
change-id: cid-57899fc2ac10c1c739b249ad33e08243003a4710
=> Parallelize checkConsistency repairs

webui/master/src/containers/pages/Browse/Browse.tsx
- Fixes #9506 
- make sure parsed path comes in decoded or else it'll get into an unreliable state
=> Remove path encoding for UI Browse tab

core/client/fs/src/main/java/alluxio/client/file/options/SetAttributeOptions.java, core/client/fs/src/test/java/alluxio/client/file/options/SetAttributeOptionsTest.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/options/SetAttributeOptions.java, core/server/master/src/test/java/alluxio/master/file/PermissionCheckTest.java, core/server/master/src/test/java/alluxio/master/file/options/SetAttributeOptionsTest.java
TTL action in Alluxio create file/directory, set attribute are all default to `TtlAction.DELETE`.
Even after the file is created and users manually set ttl action to Free, some unrelated to setTtl set attribute operations will change the TtlAction back to DELETE.
In the workflow
```
createFile(path) .  <-- TtlAction = DELETE
setAttribute(TtlAction=FREE) .   
setAttribute(owner=new Owner) .  <-- TtlAction will change to DELETE because that's the default!
```
An example of `setAttributeOption` is 
```
SetAttributeOptions{commonOptions=CommonOptions{syncIntervalMs=-1}, pinned=null, ttl=null, ttlAction=DELETE, persisted=null, owner=NewOwner, group=null, mode=-1, recursive=false, operationTimeMs=1564102662737, ufsFingerprint=}
```
This PR change the default ttl action in setAttributeOptions to …
=> Change default TTLAction to null instead of DELETE for SetAttribute

core/common/src/test/java/alluxio/security/authorization/AccessControlListTest.java
Change "import org.junit.Assert;" to 
"import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertFalse;"
and remove all the "Assert."
Besides,when I use "mvn clean install -DskipTests",there will be an error in building Alluxio UI 2.1.0-SNAPSHOT. It occurs when frontend-maven-plugin:1.6:install-node-and-npm. It has to download https://nodejs.org/dist/v10.11.0/node-v10.11.0-linux-x86.tar.gz which is not exist.
=> [SMALLFIX] Change import of three functions in org.junit.Assert

tests/src/test/java/alluxio/client/cli/fs/command/LeaderCommandIntegrationTest.java
This is to deflake leader command integration test.
The reason for failure is that error output contains some netty error trace that we can't control. When netty receives a command for a stream that is closed or being closed, such traces are written to sys::err. In this case, it's the latter, that some stream is about to be closed when leader command hits the server. This flake is introduced by gRPC long polling. Reason for that is now that servers keep an open stream, closing a server attempts to close those as well. However that takes some time after actual complete call is called on the stream. Hence it increased exposure to receive cancelled/closed stream errors from netty.
=> Validate only last line for leader command test

core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
Await checks for the interrupted flag which will lead to an infinite loop.
=> Throw an exception on interrupt for DynamicResourcePool

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
This is to fix random flakes to `TriggeredCheckpointTest::embeddedJournal`, which becomes more common with upcoming gRPC transport due to slightly increased cost of creating new copycat clients.
This might deflake `JournalToolTest::dumpHeapCheckpointFromEmbeddedJournal` test as well considering it mostly fails during checkpoint command.
=> Read checkpointing start time before enabling snopshots

docs/en/deploy/Running-Alluxio-On-Kubernetes.md
- Made the explanations more explicit
- Highlight where domain socket must be mounted
Closes #9574
pr-link: #9575
change-id: cid-64d9819d9dc0a440b0b0a53de119761f27a42214
Also includes changes from #9586 
- Misleading information and typos were introduced in #9575
Resolving typos and misleading information
pr-link: #9586
change-id: cid-f1a439f8925533693ee2b5d540f524cfec45332b
=> Improve k8s short-circuit documentation

tests/src/test/java/alluxio/client/cli/fsadmin/command/QuorumCommandIntegrationTest.java, tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTest.java
Jenkins was keeping an artifact for these tests even when they were successful.
=> Remove missing test call for marking cluster as success

shell/src/main/java/alluxio/master/MasterHealthCheckClient.java
The MasterHealthCheckClient uses a hard-coded fully-qualified
class name in order to do a ps -ef to check for the process on
another node.
The class name of the job master was previously updated, but the
enum with  the value here was not. This change fixes the class
name so that the health check can pass when running in HA
mode.
Fixes #9526
Initially reported by github user @lodocj
=> Fix Job master monitor in HA mode to use correct class name

webui/master/src/containers/pages/Browse/Browse.tsx, webui/master/src/containers/pages/Browse/__snapshots__/Browse.test.tsx.snap
- Fixes #9484
- Removed `queryStringSuffix` for directory rendering since we should
only base it off the input path field
pr-link: Alluxio/alluxio#9551
change-id: cid-7603541c8a06d8c65e347b1ddc33074cc1aedc1b
=> Remove query parameters from UI browse button

core/common/src/main/java/alluxio/security/authentication/SaslStreamClientDriver.java
This is popping up quite often while bringing a cluster online and it's not very intuitive for users.
Stream errors are received asynchronous to channel building, which makes them harder to debug. Ignoring it for common case of UNAVAILABLE should be safe.
=> Do selective tracing for client stream errors

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
Sometimes shutting down journal can fail, causing journal writer to close incompletely, when this happens, any request to create a new journal context will end up with an NPE. This change add a defensive fix by checking the async writer first and throw `UnavailableException` instead.
=> Fix NPE in UFS journal when shutting down journal fails

core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java, core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/transport/src/grpc/file_system_master.proto, core/transport/src/main/java/alluxio/grpc/FileSystemMasterProto.java, core/transport/src/main/java/alluxio/grpc/GetStatusPOptions.java, core/transport/src/main/java/alluxio/grpc/GetStatusPOptionsOrBuilder.java, core/transport/src/main/java/alluxio/grpc/OpenFilePOptions.java, core/transport/src/main/java/alluxio/grpc/OpenFilePOptionsOrBuilder.java, core/transport/src/main/java/alluxio/proto/journal/File.java, job/server/src/main/java/alluxio/job/persist/PersistDefinition.java, tests/src/test/java/alluxio/job/JobIntegrationTest.java, tests/src/test/java/alluxio/job/persist/PersistIntegrationTest.java
Persist job uses `FileSystem.open` for reading file content from worker, which causes the access time to be updated. This change add an option to open file API to allow internal clients to indicate that access time should not be updated.
=> Prevent persist job from updating last access time

conf/alluxio-env.sh.template
The `ALLUXIO_PROXY_JAVA_OPTS` is missing from this template.
=> Update alluxio-env templete to contain proxy opts

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
This issue is encountered while authoring a new integration test for growing embedded journal cluster. Stopping a standby master was failing with NPE
=> Fix NPE during RaftJournal shut down

core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java, job/server/src/main/java/alluxio/master/AlluxioJobMasterProcess.java, minicluster/src/main/java/alluxio/master/LocalAlluxioJobCluster.java
This issue is encountered while authoring a new integration test for growing embedded journal cluster. Restarting an in-process master showed that journal system was not being closed during stopping standby masters.
=> Close journal system properly when stopping Alluxio processes

core/base/src/main/java/alluxio/collections/ConcurrentIdentityHashMap.java, core/base/src/test/java/alluxio/collections/ConcurrentIdentityHashMapTest.java, core/common/pom.xml, core/common/src/main/java/alluxio/grpc/DataMessageMarshaller.java
- Implementation of a ConcurrentIdentityHashMap to avoid using
Netty dependencies
- Removed the `io.netty` dependency in the core-common
module. The rest of the dependency cleanup throughout the POMs
is occurring in https://github.com/Alluxio/alluxio/pull/9455
Closes #9449
=> Implement a ConcurrentIdentityHashMap

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Cherry-picked for `branch-2.0`
Fixes Alluxio/alluxio#9294
Fixes Alluxio/alluxio#9295
Update audit logic to be more flexible when acquiring user information.
pr-link: Alluxio/alluxio#9645
change-id: cid-838211044d298fb42335b77f1c9c509fd42d185e
=> Avoid exception when audit log is used with NOSASL authentication

docs/en/Getting-Started.md, docs/en/Overview.md
Add HTML img links to Overview and Getting Started pages.
Images will look like:
=> [DOCFIX] Add img links to Overview and Getting Started docs with HTML

core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java, core/common/src/main/java/alluxio/metrics/ClientMetrics.java, core/common/src/main/java/alluxio/metrics/MetricsSystem.java, core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java, core/server/master/src/test/java/alluxio/master/metrics/MetricsStoreTest.java, tests/src/test/java/alluxio/client/rest/AlluxioMasterRestApiTest.java, tests/src/test/java/alluxio/testutils/LocalAlluxioClusterResource.java
Fixes #9442 
We need to consider tags in the uniqueness of our metrics, otherwise we may incorrectly override metrics (usually to 0) leading to inaccurate numbers.
=> Ensure tags are copied when overriding metrics

integration/docker/Dockerfile, integration/docker/Dockerfile.fuse
Add an alluxio user with uid `1000`, gid `1000`, and root group membership
Allows users to run the Alluxio Docker image as a non-root user
=> Add non-root user to Dockerfile

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/UfsSyncPathCache.java, tests/src/test/java/alluxio/client/fs/UfsSyncIntegrationTest.java
fixes #9545
This enables the ufs sync cache to inspect the ancestors of the path.
This allows the sync to be skipped if an ancestor was recently sync
recursively. This will potentially increase the time to check if sync
should be performed, since the path's parents have to be computed.
pr-link: Alluxio/alluxio#9668
change-id: cid-bd0cfe062c02c919585f5506bbe970d553dcc526
=> Improve sync cache to consider recursive sync of ancestors

core/common/src/main/java/alluxio/resource/DynamicResourcePool.java
Follow up to #9584 
Restoring the interrupted state can be helpful to callers if they catch IOException and check the interrupted flag (ie. a retry handler).
We can reset the interrupted flag because we break out of the while loop afterward.
=> Restore interrupted flag in DynamicResourcePool

shell/src/main/java/alluxio/cli/fsadmin/command/GetBlockInfoCommand.java, tests/src/test/java/alluxio/client/cli/fsadmin/command/GetBlockInfoCommandIntegrationTest.java
The getBlockInfo command may hit errors when contacting the block master or file system master. However, the command may still be able to print out useful information, even if some of the RPCs fail. Therefore, the RPC exceptions should be handled and ignored and print out any available information.
=> Allow getBlockInfo command to handle errors

core/common/src/main/java/alluxio/PropertyKey.java, core/server/common/src/main/java/alluxio/master/BackupManager.java
Use a buffer to batch more entries at a time to apply and journal, while applying a backup.
=> Prevent excessive flushing while applying a backup

bin/alluxio-start.sh
Loading UFS extensions can exceed the default metadata space and causes full GC during server start up, this can be problematic if Alluxio master uses a lot of heap space, for example due to large amount of files.
This change increases the default metadata space to reduce such chance. User can override it with larger numbers as needed.
=> Increase the default metadata space

core/server/common/src/main/java/alluxio/master/journal/JournalEntryStreamReader.java, core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalFileParser.java
Fixes #9698 
In the journal entry stream reader we keep a buffer to reuse for reading entries. Because this buffer might not be fully utilized, we cannot use protobuf's default `parseFrom(byte[])` and instead wrap the valid portion of the buffer in a ByteArrayStream. However this causes additional buffer allocations. We can instead use the lower level parser API to parse a slice of the existing buffer.
This does not affect the embedded journal implementation because we allocate a fresh buffer for each entry (exact size). Also I did not apply this optimization for the v0 journals as those are no longer in use aside for migrations.
The overall performance improvement is about 75% for a 10MB edit log file stored on local disk, this also reduces the number of new objects allocated which can …
=> Improve ufs journal parsing efficiency

core/common/src/main/java/alluxio/conf/PropertyKey.java
PropertyKey which are categorized as credential should have `DisplayType.CREDENTIALS`. Some PropertyKey are not marked correctly so they will not be masked when being displayed. This is a security risk that we must fix.
=> Add credential display type for credential property fields

integration/kubernetes/alluxio-master.yaml.template, integration/kubernetes/alluxio-worker.yaml.template, integration/kubernetes/helm/alluxio/templates/alluxio-master.yaml, integration/kubernetes/helm/alluxio/templates/alluxio-worker.yaml, integration/kubernetes/helm/alluxio/values.yaml
After https://github.com/Alluxio/alluxio/pull/9363 is merged, we now run the docker containers with user `alluxio` by default. `hostPath` volumes in the default k8s specs are owned by `root` and the `alluxio` user does not have access to write the journal to that location.
This PR allows choosing the user to run the Alluxio service on k8s in the helm chart and replaces the generated template files.
=> Run k8s as root by default

tests/src/test/java/alluxio/client/cli/fsadmin/command/QuorumCommandIntegrationTest.java
- This change should help reduce some of the test flakiness we're
seeing in builds on jenkins
=> Increase timeout in QuorumCommandIntegrationTest

core/common/src/main/java/alluxio/AbstractClient.java, core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java, core/common/src/main/java/alluxio/util/ConfigurationUtils.java, core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java, core/common/src/test/java/alluxio/master/MasterInquireClientTest.java, core/common/src/test/java/alluxio/master/PollingMasterInquireClientTest.java, core/common/src/test/java/alluxio/master/ZkMasterInquireClientTest.java, core/common/src/test/java/alluxio/util/ConfigurationUtilsTest.java, core/common/src/test/java/alluxio/util/network/GetMasterWorkerAddressTest.java, core/common/src/test/java/alluxio/util/network/NetworkAddressUtilsTest.java, core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalConfigurationTest.java, integration/docker/entrypoint.sh, tests/src/test/java/alluxio/server/web/ServiceSocketBindIntegrationTest.java
Fix https://github.com/Alluxio/alluxio/issues/9448 by delaying hostname resolution so that stale DNS entries can be refreshed.
Note: Client side InetSocketAddress should be created unresolved to tolerate DNS changes. Server bind socket addresses are an exception as those do not change during the lifetime of the JVM.
=> Fix hostname resolution for HA in k8s

bin/alluxio-start.sh, bin/launch-process
It is crucial to minimize full garbage collection pause in Alluxio master which could cause various issues including master fail over. This change switch to use Concurrent Mark Sweep garbage collector by default so it is less likely to enter a long full GC pause on master.
=> Use Concurrent Mark Sweep garbage collector for master by default

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java, core/server/master/src/test/java/alluxio/master/journal/ufs/UfsJournalLogWriterTest.java
Fixes #9722 
Fixes several edge cases in journal recovery.
1. If we fail to flush to the journal, do not try to recover, instead flag the stream as needsRecovery and handle the recovery on next operation
2. When recovering, make sure there is a previous journal entry
3. When recovering, create a new log file starting with the latest committed journal entry (instead of our current one)
4. When recovering, fail if the latest journal entry recovered from our buffer is not equal to our expected next sequence number - 1
5. When recovering, do not consider incomplete logs when inferring the last persisted sequence number from the file name (it will be INTEGER_MIN)
=> Fix bugs related to the journal recovering from a UFS failure

core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java, core/server/worker/src/test/java/alluxio/worker/grpc/AbstractWriteHandlerTest.java, core/server/worker/src/test/java/alluxio/worker/grpc/GrpcExecutorsTest.java
The proxy user information for impersonation is stored in the ThreadLocal object in AuthenticatedClientUser class. The thread pools in GrpcExecutors are not given this proxy user ThreadLocal when read/write tasks are submitted to them. We have to write a wrapper for ExecutorService that sets and unsets the ThreadLocal correctly.
=> Propagate thread-local AuthenticatedClientUser to gRPC executors

core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcClient.java, core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcClientConnection.java, core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcConnection.java, core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcServer.java, core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcServerConnection.java, core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcTransport.java, core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatMessageServiceClientHandler.java
Earlier, copycat catalyst `ThreadContext` was used to build connections for transport clients/servers. There are some cluster states that are managed by a single threaded `ThreadContext` and that could cause a node to loose contact with rest of cluster while a connection is being built. This PR offloads copycat connection building to a dedicated thread pool.
=> Perform copycat connection building in a dedicated thread pool

bin/launch-process
The launch-process script uses the `set -e` flag which tells bash to exit
if a command returns non-zero; In the case when the "contains"
function returned "1", (meaning that arg 1 contains arg 2 somewhere within
it), the script would exit.
This means that any users which set values through alluxio-env.sh could
possibly have their processes fail to start if setting things like Xmx
and MetaspaceSize that are checked in either the master or workers.
To remediate this issue the contains function was modified to
instead, echo "1" or "0". Callers then simply have to call the
function in a subshell and use the result in their conditional
checks. This approach offers a better and more consistent usage
with the rest of our scripts.
Fixes #9740
=> Update launch-process contains function so the script does not exit

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Currently when a user's request to startSync and stopSync fails, very little information is printed because the exception printing happens after a fatal error. Adding this to help with debugging in the future.
=> Add more debugging to activeSync startSync and stopSync

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
Replace kubernetes `conf/alluxio.properties` with `alluxio-configMap.yaml.template` in generated tarball. This reflects changes in https://github.com/Alluxio/alluxio/pull/9748.
=> Update kubernetes configMap in built tarball

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
The EMR scripts are removed, so they should not be included in the tarball build
=> Remove EMR scripts from tarball build

docs/en/deploy/Running-Alluxio-On-Kubernetes.md
The way to create the configMap was updated previously and docs are stale.
=> Update k8s doc to use the configMap file

integration/docker/Dockerfile, integration/docker/entrypoint.sh
Fixes: https://github.com/Alluxio/alluxio/issues/9760
The entry disabling DNS cache should be written at image build time instead run time (entrypoint). When the image is run as a non-root user (such as `alluxio`), the user may not have the permission to write to the desired location.
=> Disable DNS cache at docker build instead of entrypoint

docs/en/contributor/Building-Alluxio-From-Source.md
fixes #9251
For a user new to Alluxio and follows the Building-Alluxio-From-Source guide for the first time, the cloned repository doesn't have directory `./underFSStorage`. `bin/alluxio validateEnv local` will complain this directory doesn't exist and fail. 
I think it makes sense to add this step in the guide.
=> [DOCFIX] Add mkdir step to Alluxio building guide

tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java, tests/src/test/java/alluxio/testutils/master/MasterTestUtils.java
Currently in some integration tests we create a master replica from journal directory to check journal status. This can cause problems if the original master is not stopped when the new master is created. This change solves the issue by copying the journal to a separate directory and creating the new master based on the copy.
=> Copy journal files when creating new masters in integration test

core/base/src/main/java/alluxio/Constants.java, core/base/src/main/java/alluxio/exception/ExceptionMessage.java, core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java, core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java, core/client/hdfs/pom.xml, core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioShimFileSystem.java, core/client/hdfs/src/main/java/alluxio/hadoop/FileSystem.java, core/client/hdfs/src/main/java/alluxio/hadoop/ShimFileSystem.java, core/common/src/main/java/alluxio/ClientContext.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java, core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java, core/server/master/src/test/java/alluxio/master/file/meta/MountTableTest.java, tests/src/test/java/alluxio/client/fs/ShimFileSystemIntegrationTest.java
`ShimFileSystem` is an alternative to existing `AlluxioFileSystem` where foreign URIs are supported on client side. URIs that are sent to master as-is need to be translated to internal Alluxio URIs. This is done by a reverse lookup on master mount table. For `ShimFileSystem` to work properly, the file system that it has been attached to must be mounted on Alluxio.
Closes https://github.com/Alluxio/alluxio/issues/9231
=> Implement ShimFileSystem

core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
The DefaultBlockMaster was using a shaded version of the google
Preconditions class. Fixed to use the correct package
=> Use non-shaded Preconditions in DefaultBlockMaster

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
Setting "alluxio.underfs.object.breadcrumbs.enabled" to false will disable breadcrumb creation when doing a "list" operation.
=> Add property to skip breadcrumb creation on list for ObjectStore UFS

core/common/src/test/java/alluxio/client/file/URIStatusTest.java
* Fixes [Alluxio/new-contributor-tasks#516](https://github.com/Alluxio/new-contributor-tasks/issues/516)
* Use static imports for standard test utilities in  /alluxio/core/common/src/test/java/alluxio/client/file/URIStatusTest.java
*I use static imports rather than Non-static imports for standard test utilities in "/alluxio/core/common/src/test/java/alluxio/client/file/URIStatusTest.java"*
Hi, @gpang ,Please take a look , Thank you very much.
=> [SMALLFIX] Use static imports for standard test utilities (#516)

core/common/src/test/java/alluxio/util/ShellUtilsTest.java
* Fixed this [PR](https://github.com/Alluxio/new-contributor-tasks/issues/549)
* Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/util/ShellUtilsTest.java 
*I use static imports rather than Non-static imports for standard test utilities in "/alluxio/core/common/src/test/java/alluxio/util/ShellUtilsTest.java"*
=> [SMALLFIX] Use static imports for test utilities in ShellUtilsTest

core/common/src/main/java/alluxio/collections/TwoKeyConcurrentMap.java
Use the @Nullable annotation for all methods which may return null in /alluxio/core/common/src/main/java/alluxio/collections/TwoKeyConcurrentMap.java#removeInnerValue
=> Use @nullable annotation in TwoKeyConcurrentMap

core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java
For quicker diagnostics it is better for channel authentication failure message to contain underlying error code early in the message + some code improvements.
=> Improve diagnosibility of error message for channel authentication

core/common/src/main/java/alluxio/grpc/GrpcChannel.java, core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java
`Copycat` could invoke creation/shutdown of a connection concurrently. With gRPC transport, that translates to concurrently acquiring/releasing managed channels from `GrpcManagedChannelPool` for the same channel-key. `GrpcManagedChannelPool` was not handling this case properly and a bug was causing managed channel to remain shutdown. So a communication to a particular target was lost completely. (Other users of the channel pool were safe due to synchronous conventions they follow.)
This PR simplifies locking model for channel pooling which also fixes concurrency problems caused by copycat transport layer. Main changes are:
- the pool is never locked globally. Channels for different targets are built/destroyed without blocking each other.
- `acquire` and `release` acquires an exclusive …
=> Improve gRPC channel-pool concurrency

core/base/src/main/java/alluxio/exception/ExceptionMessage.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncer.java, core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java, core/server/master/src/test/java/alluxio/master/file/meta/MountTableTest.java, tests/src/test/java/alluxio/client/fs/ShimFileSystemIntegrationTest.java
Master should restrict foreign URI's access to its own mount only. To guarantee that this fix blocks foreign URI translation for mounts that have nested mounts.
=> Disallow foreign schemes on mounts that have nested mounts

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
This PR is a follow up to #9837 which removed all scripts
underneath `integration/docker/bin`
=> Remove docker/bin scripts from generate-tarball

core/server/common/src/main/java/alluxio/master/MasterProcess.java
Fixes https://github.com/Alluxio/alluxio/issues/9845
If leadership is lost during transitioning, `startMasters(false)` ends up being called back-to-back. That will cause earlier rejecting-server to be leaked and block the port for later. Fix ensures we don't recreate over a created rejecting-server.
=> Fix leaking rejecting-servers when primacy is unstable

tests/src/test/java/alluxio/job/migrate/MigrateIntegrationTest.java
This test became flaky when the default write type became async-through. This is because when the migrate is configured to delete the source, sometimes, that inode is NOT persisted, so it is not removed from the UFS. Then, on the `exists` call, it will loadMetadata from UFS, and it will load the file from UFS and the deleted file will "return".
=> Fix flakiness of migrate test

integration/docker/Dockerfile.fuse
=> Set networkaddress.cache.ttl=0 at docker fuse image build time

core/common/src/main/java/alluxio/grpc/GrpcChannel.java, core/common/src/main/java/alluxio/security/authentication/ClientIpAddressInjector.java, core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcClient.java, core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcClientConnection.java, core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcConnection.java, core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcServer.java, core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcServerConnection.java, core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatMessageServiceClientHandler.java, core/transport/src/grpc/copycat.proto, core/transport/src/main/java/alluxio/grpc/CopycatProto.java, core/transport/src/main/java/alluxio/grpc/CopycatResponseHeader.java, core/transport/src/main/java/alluxio/grpc/CopycatResponseHeaderOrBuilder.java
Without a transport level identifier, existing copycat transport traces were not sufficient in some cases to pinpoint source and destination of traffic. This PR makes necessary changes for that and does some improvements for tracing in overall.
=> Improve copycat transport traces

tests/src/test/java/alluxio/server/ft/MultiWorkerIntegrationTest.java
This test writes to 100% of the worker capacity, but the reserver does not allow 100% utilization. The async reserver sometimes evicts blocks, which causes problems with this test.
=> Remove flakiness of the writeLargeFile test

shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
distributedLoad traverses the specified path, distributes a load job of a file to job master and waits the job completed one by one, that is a serial process. So the performance may be not acceptable.
Now distributedLoad traverses the specified path, distributes a batch load job of files to job master and distributes a new job if one job completed, that is a intercurrent process.
Fix https://github.com/Alluxio/alluxio/issues/9791
=> Implement parallelism for the distributedLoad command

core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
This line is too noisy and provides little to no valuable information. Will only get worse if default block size is reduced.
=> Remove noisy log in BlockMaster

tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java, tests/src/test/java/alluxio/client/fs/MultiUfsMountIntegrationTest.java, tests/src/test/java/alluxio/server/auth/ClusterInitializationIntegrationTest.java, tests/src/test/java/alluxio/server/ft/journal/JournalShutdownIntegrationTest.java, tests/src/test/java/alluxio/server/ft/journal/ufs/UfsJournalIntegrationTest.java, tests/src/test/java/alluxio/testutils/master/FsMasterResource.java, tests/src/test/java/alluxio/testutils/master/MasterTestUtils.java
In some tests, the journal was not being closed when the master registry is closed. This caused some of the flaky checkpoint read failures.
=> Close journal in tests

core/common/src/test/java/alluxio/underfs/UfsDirectoryStatusTest.java
* Fixed this [PR](https://github.com/Alluxio/new-contributor-tasks/issues/537)
* Use static imports for standard test utilities in  /alluxio/core/common/src/test/java/alluxio/underfs/UfsDirectoryStatusTest.java
*I use static imports rather than Non-static imports for standard test utilities in "/alluxio/core/common/src/test/java/alluxio/underfs/UfsDirectoryStatusTest.java"*
=> [SMALLFIX] Use static imports for asserts in UfsDirectoryStatusTest

core/common/src/test/java/alluxio/util/JvmPauseMonitorTest.java
* Fixed this [PR](https://github.com/Alluxio/new-contributor-tasks/issues/547)
* Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/util/JvmPauseMonitorTest.java
*I use static imports rather than Non-static imports for standard test utilities in "/alluxio/core/common/src/test/java/alluxio/util/JvmPauseMonitorTest.java"*
=> [SMALLFIX] Use static imports for test utilities in JvmPauseMonitorTest

core/common/src/test/java/alluxio/underfs/options/FileLocationOptionsTest.java
* Fixed this [PR](https://github.com/Alluxio/new-contributor-tasks/issues/541)
* Use static imports for standard test utilities in  /alluxio/core/common/src/test/java/alluxio/underfs/options/FileLocationOptionsTest.java
*I use static imports rather than Non-static imports for standard test utilities in "/alluxio/core/common/src/test/java/alluxio/underfs/options/FileLocationOptionsTest.java"*
=> [SMALLFIX] Use static imports for asserts in FileLocationOptionsTest

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
The naming convention is not consistent with other properties
=> Make breadcrumb property key name consistent

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
fixes #9552
The original patch is contributed by @liuhongtong in #9622, but re-created to 2.1-snapshot and then cherry-picked to 2.0 and 1.8 branch.
If allow_other fuse option is given, the file/dir created by other users should show its actual creator instead of showing the user who mounted the fuse filesystem.
In this PR, create file and create directory will show real owner and group.
=> Port changes of [#9941] to branch-1.8

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
The naming convention is not consistent with other properties
pr-link: Alluxio/alluxio#9918
change-id: cid-269087023708a022f61b446b3ed71309a60f5aa6
=> Port changes of [#9918] to branch-2.0

experimental/table/client/pom.xml, pom.xml
Presto imports netty packages individually, so we exclude netty-all. We could also explicitly import each package, but the only one we need over what is provided is the native module for domain socket.
=> Add explicit dependency on netty-native

core/common/pom.xml, core/common/src/main/java-templates/alluxio/ProjectConstants.java, pom.xml, shell/src/main/java/alluxio/cli/Version.java
In light of preserving behavior, the command behaves the same as in
previous versions. This change adds the -r option which can be specified
optionally so that users can  see part or all of the revision output
appended to the end of the normal version string.
Added two new maven plugins to retrieve the git revision.
Closes #9930
=> Add git revision to ./bin/alluxio version

integration/kubernetes/helm/alluxio/templates/alluxio-master.yaml, integration/kubernetes/multiMaster-embeddedJournal/alluxio-master.yaml.template
The port name for embedded journal was `embedded-journal`. K8s has a restriction for a port name to be shorter than 15 characters, so the Pod creation will fail. This changes the port name to be short enough to be accepted.
=> Shorten k8s port name for embedded journal

job/common/src/main/java/alluxio/job/meta/JobInfo.java, job/server/src/main/java/alluxio/master/job/JobCoordinator.java
JobInfo had unnecessary synchronized blocks which caused deadlocks. `final` variables do not need `synchronized` block, and converted some to concurrent data structures.
fixes #9970
=> Use better locking in JobInfo to avoid deadlocks

tests/src/test/java/alluxio/client/cli/fs/AbstractShellIntegrationTest.java, tests/src/test/java/alluxio/client/cli/fs/command/PersistCommandTest.java
The default persistence checking intervals cause too much waiting for the persistence tests. Locally, these changes reduce the runtime of this suite from ~2m to ~45s.
=> Reduce intervals for faster persist tests

core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java, core/common/src/main/java/alluxio/grpc/GrpcChannelKey.java
- Rethrow `UnavailableException` coming form auth-layer to avoid confusion.
- Simplify channel traces by avoiding Optional field representation(`Optional["value"]`)
=> Improve gRPC exception flow and trace readibility

integration/docker/Dockerfile, integration/kubernetes/helm/alluxio/templates/alluxio-master.yaml, integration/kubernetes/helm/alluxio/templates/alluxio-worker.yaml, integration/kubernetes/helm/alluxio/values.yaml, integration/kubernetes/multiMaster-embeddedJournal/alluxio-master.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/alluxio-worker.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/alluxio-master.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/alluxio-worker.yaml.template, integration/kubernetes/singleMaster-localJournal/alluxio-master.yaml.template, integration/kubernetes/singleMaster-localJournal/alluxio-worker.yaml.template
This change will enable Alluxio to run as non-root user in Kubernetes cluster. 
The UFS local journal directory and the domain socket directory will have to be `chown` to `alluxio:alluxio`. This is done by adding `initContainers` which are executed before the containers. The `securityContext` are split up and moved to each container to provider security configuration in finer granularity.
Ref: [Kubernetes security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)
=> Enable Alluxio to run as non-root in Kubernetes cluster

core/common/src/main/java/alluxio/conf/PropertyKey.java
`HEARTBEAT_INTERVAL` to `3sec`: Heartbeat controls the frequency of communication between copycat nodes. So a larger value would stall entire communication.
`ELECTION_TIMEOUT` to `10sec` : Leader election timeout is effective during cluster startup as well.  A larger value would have been a bad user experience.
`APPENDER_BATCH_SIZE` to `512KB` : 512KB of data at every heartbeat (3sec) would utilize network bandwith better than `32KB` every `1sec` as before.
=> Adjust embedded journal properties

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
address https://github.com/Alluxio/alluxio/issues/9432
The version in shaded hadoop module pom file (`<version>${ufs.hadoop.version}</version> ` is resolved to its value (e.g. `2.2.0`) by the maven release plugin.  When generating tarball with other ufs versions (e.g. 2.7.3), the shaded hadoop module version should be 2.7.3 but remain to be 2.2.0. This is why we cannot generate tarball with tag v2.0.0 and v2.0.1. 
Instead of directly modify the last commit of the tag (which is hard and strange), this PR targets to make the generate tarball part works.
=> Replace the shaded hadoop version when generating tarballs

core/client/fs/src/main/java/alluxio/client/block/stream/GrpcBlockingStream.java, core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java, core/client/fs/src/test/java/alluxio/client/block/stream/LocalFileDataWriterTest.java
This PR addresses a memory leak in the Alluxio client for local file writes on the short-circuit data access path. The impact is most significant for long running processes, such as the job worker (with an embedded Alluxio client), as open files are not released until the JVM terminates and continue to occupy memory in the mean time.
In the issue reported, the worker and job worker run in the same container. Pinning a 2G file causes set replication = 1 and the replication checker creates a job for the job worker to load the file from the ufs. The job worker opens mmaped files for temporary blocks and does not cleanup temporary blocks correctly as reported by: 
```
bash-4.4# lsof +L1 | grep /dev/shm
...
166	/usr/lib/jvm/java-1.8-openjdk/jre/bin/java …
```
=> Fix local file writer client memory leak by cleaning up mmapped files

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
There is a case when `handleSuccess` is expensive (for example for object stores). This leads to a large number of `handleSuccess` calls being queued up, possibly conflicting with each other and consuming the threadpool / queue.
I validated it with S3, but unfortunately it is nontrivial to make a test for this case.
Fixes #9925
=> Remove from persist jobs synchronously

integration/kubernetes/alluxio-format-master.yaml.template, integration/kubernetes/helm-generate.sh, integration/kubernetes/helm/alluxio/templates/alluxio-format-master.yaml, integration/kubernetes/helm/alluxio/values.yaml, integration/kubernetes/multiMaster-embeddedJournal/alluxio-format-master.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/alluxio-format-master.yaml.template, integration/kubernetes/singleMaster-localJournal/alluxio-format-master.yaml.template
This changes adds a set of Helm YAML templates.
The YAML creates a K8s Job that formats the master log and dies after finishing. This provides a clean way for the user to format log without going into the Pods, especially helpful when the masters are not started or to clean up state without the need to start a master container.
=> Add K8s Job dedicated for formatting master journal

shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
For distributedCp command, make sure client write type configuration is passed to job service.
=> Improve distributedCp command to support write type parameter

core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java
This trace should have been removed as part of https://github.com/Alluxio/alluxio/pull/9973
=> Remove left-over warning trace in ChannelAuthenticator

integration/kubernetes/helm/alluxio/templates/alluxio-master.yaml, integration/kubernetes/multiMaster-embeddedJournal/alluxio-master.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/alluxio-master.yaml.template, integration/kubernetes/singleMaster-localJournal/alluxio-master.yaml.template
This change fixes the selector used by K8s Services to find the correct master Pods. Without this change the Services are not able to find the correct master Pods so the master Pods cannot be talked to. 
This bug was introduced by the previous change to use `app: alluxio` for all resource and `name: {{$masterName}}` for the master Pods. Only the selector for StatefulSet was updated, and the selector for Service was missed.
=> Fix K8s Service label selector

integration/kubernetes/alluxio-fuse.yaml.template
ALLUXIO_JAVA_OPTS is redundantly defined in the fuse container and the configMap which lead to configMap being ignored.
=> Use ALLUXIO_CLIENT_JAVA_OPTS in k8s fuse yaml to not override configMap

docs/en/ufs/S3.md
When backing up to root ufs with the following configuration
```
alluxio.master.mount.table.root.ufs=s3://bucket-name
```
The `fasdmin backup` command will fail because our Alluxio URI has problem processing uri with no path (without a trailing slash after authority).
This PR fixes the issue and allows s3://bucket-name as root ufs.
=> [DOCFIX] Require trailing slash when mounting whole s3 bucket

experimental/table/shell/src/main/java/alluxio/cli/catalog/CatalogShell.java, experimental/table/shell/src/main/java/alluxio/cli/catalog/command/AbstractCatalogCommand.java, experimental/table/shell/src/main/java/alluxio/cli/catalog/command/ListDatabasesCommand.java
This PR adds the `alluxio catalog ls` command which can used to
retrieve basic information about the schemas and tables which are
attached in the CatalogMaster.
The command serves three functions:
- dump the list of attached databases
- `./bin/alluxio catalog ls`
- dump the list of tables within a database
- `./bin/alluxio catalog ls <database>`
- dump all of the information about a table
- `./bin/alluxio catalog ls <database> <table>`
=> Add ListDatabasesCommand

integration/docker/Dockerfile, integration/docker/Dockerfile.fuse
The dockerfiles have now utilize a multi-stage build in order
to avoid running `chown ....` on the `/opt` directory at build time.
Additionally, building the container will now require a later version
of docker (19.03) due to the use of `ARG`s in the `--chown` flag
After these changes:
- alluxio/alluxio: 688M
- alluxio/alluxio-fuse: 1.08G
Closes #9896
=> Reduce docker image size

core/common/src/main/java/alluxio/metrics/MasterMetrics.java, core/server/common/src/main/java/alluxio/master/BackupManager.java
Adding metrics for backup and restore from backup to track number of entries and time taken for backup.
=> Add metrics to BackupManager for backup and restore of the journal

conf/log4j.properties, docs/en/operation/Server-Logging.md
This change updates the remote logging service to only accept log level of WARN and higher by default. Also the related doc is updated and refined.
The change will help the logging service pinpoint issues more easily. On the doc side, misleading sections in the doc are corrected and more detailed instruction on how to use `log4j.properties` for remote logging service are provided.
=> Set default remote logging service log level threshold to WARN

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java, core/common/src/main/java/alluxio/underfs/UfsFileStatus.java, core/common/src/main/java/alluxio/underfs/UnderFileSystem.java, core/common/src/test/java/alluxio/underfs/FingerprintTest.java, core/common/src/test/java/alluxio/underfs/UfsFileStatusTest.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/test/java/alluxio/master/meta/DailyMetadataBackupTest.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java, underfs/local/src/main/java/alluxio/underfs/local/LocalUnderFileSystem.java, underfs/web/src/main/java/alluxio/underfs/web/WebUnderFileSystem.java
Adds block size info to the `UfsFileStatus`. This mainly helps HDFS whos implementation of `getBlockSizeBytes` has 2(!) rpc calls.
This change should be fully backward compatible, but older servers using newer ufs jars will not work (because the constructor of UfsFileStatus is different). 
@apc999 A separate question is if we should enforce usage of UFS jars which are on the same version of the server so we don't need to maintain legacy code.
Fixes #10035
=> Add block size to information stored in UfsFileStatus

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go, integration/kubernetes/alluxio-configMap.yaml.template, integration/kubernetes/alluxio-configmap.yaml.template
This change fixes the incorrect upper/lower case in updated Helm chart files and `generate-tarball.go`. The file doesn't exist anymore so the tarball cannot be generated correctly.
=> Fix incorrect Helm chart file name upper/lower case

core/common/src/main/java/alluxio/cli/AbstractShell.java
Fixes https://github.com/Alluxio/alluxio/issues/10032
```
$ bin/alluxio fs mount --readOnly /input s3://apc999/emr/mid_input_alluxio_alluxio
Usage: mount [--readonly] [--shared] [--option <key=val>] <alluxioPath> <ufsURI>
Mounts a UFS path onto an Alluxio path.
```
The console output should say the `--readOnly` is unrecognized before showing the usage.
After fixed, the correct output is as follows:
```
$ bin/alluxio fs mount --readOnly  /mnt s3://alluxio-quick-start/data
Failed to parse args for mount: Unrecognized option: --readOnly
Usage: mount [--readonly] [--shared] [--option <key=val>] <alluxioPath> <ufsURI>
Mounts a UFS path onto an Alluxio path.
```
* Improve error message when passing wrong args to CLI, Here you can find the …
=> Improve error message when passing wrong args to CLI

core/common/src/main/java/alluxio/AbstractClient.java, core/common/src/main/java/alluxio/AbstractMasterClient.java, core/common/src/main/java/alluxio/Client.java, core/common/src/main/java/alluxio/master/MasterClientContext.java, core/common/src/main/java/alluxio/util/ConfigurationUtils.java, core/common/src/test/java/alluxio/AbstractClientTest.java, job/client/src/main/java/alluxio/client/job/RetryHandlingJobMasterClient.java, job/client/src/main/java/alluxio/worker/job/JobMasterClientContext.java, job/client/src/main/java/alluxio/worker/job/JobMasterClientContextBuilder.java, job/client/src/main/java/alluxio/worker/job/RetryHandlingJobMasterClient.java
The InetSocketAddress for configuration must always be the master.
While the address could be the master or the job master.
@calvinjia
=> Load Configuration from Meta Master for all clients

shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java, shell/src/main/java/alluxio/cli/fs/command/PersistCommand.java
Consolidate the option name in `distributedLoad` and `persist` regarding parallelism. Using `--thread` is confusing as it is not indicating how many working threads on that machine but number of concurrent operations across an Alluxio cluster
=> Update the option name in distributedLoad

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, tests/src/test/java/alluxio/client/cli/fs/command/PersistCommandTest.java
Fix https://github.com/Alluxio/alluxio/issues/10043
Files containing strings in the blacklist will not be persisted. This can be useful for Alluxio to avoid persisting results too early for workloads like Hive or MapReduce as they typically create temp results first into temp directories, before the entire directory was renamed (as commit).
=> Implement blacklist for persisting files

shell/src/main/java/alluxio/cli/fs/command/FreeCommand.java
Previous message of "xxx was successfully freed from memory" is not accurate. Change this to Alluxio space
=> Update the output message for FreeCommand

job/client/src/main/java/alluxio/client/job/JobGrpcClientUtils.java
Before, the reason of job failure is not returned in console to users. one needs to dig into user logs to find it out:
```console
$ bin/alluxio fs distributedCp /reason /reason2/
Failed to successfully complete the job.
```
After this patch:
```console
$ bin/alluxio fs distributedCp /reason /reason2/
Failed to successfully complete the job: /reason2 already exists
```
=> Improve error message for distributed{Mv,Cp,Load}

job/server/src/main/java/alluxio/job/migrate/MigrateDefinition.java, job/server/src/main/java/alluxio/job/persist/PersistDefinition.java, job/server/src/test/java/alluxio/job/migrate/MigrateDefinitionRunTaskTest.java, shell/src/main/java/alluxio/cli/fs/command/CpCommand.java, shell/src/main/java/alluxio/cli/fs/command/DistributedMvCommand.java
- Set readtype to `NO_CACHE` to `distributedCp` and `distributedMv` (in migration definition)
- Increase buffersize to 8 MB (from 8KB or less) for these jobs
- Make `distributedMv` carry writetype
=> Improve distributedCp and distributedMv and Persist

dev/scripts/src/alluxio.org/build-distribution/cmd/common.go
Removing HDFS 1.x from the default modules we build in our tarball
=> Remove HDFS 1.x from default built modules

core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/test/java/alluxio/client/block/BlockMasterClientPoolTest.java, core/client/fs/src/test/java/alluxio/client/file/FileSystemMasterClientPoolTest.java, core/client/fs/src/test/java/alluxio/client/metrics/MetricsHeartbeatContextTest.java, core/common/src/main/java/alluxio/master/MasterClientContextBuilder.java, core/common/src/main/java/alluxio/master/MasterInquireClient.java, core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorker.java, job/client/src/main/java/alluxio/client/job/JobContext.java, job/client/src/main/java/alluxio/worker/job/JobMasterClientContextBuilder.java, job/client/src/test/java/alluxio/client/job/JobContextTest.java, job/server/src/main/java/alluxio/worker/AlluxioJobWorker.java, minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java, shell/src/main/java/alluxio/cli/fs/command/MasterInfoCommand.java, shell/src/main/java/alluxio/cli/job/command/LeaderCommand.java, shell/src/main/java/alluxio/cli/job/command/ListCommand.java, shell/src/main/java/alluxio/cli/job/command/StatCommand.java, shell/src/main/java/alluxio/master/MasterHealthCheckClient.java, tests/src/test/java/alluxio/server/ft/MasterFaultToleranceIntegrationTest.java
Currently `PollingMasterInquireClient` uses a new `Subject` when querying master. If the call needs authentication using credentials from `Subject`, it will fail the request because the credentials are missing. This change add parameters to APIs to allow passing in the required `Subject`.
Manually tested with external `Subject` from Hadoop client.
=> Propagate UserState to PollingMasterInquireClient

core/transport/src/grpc/job_master.proto, core/transport/src/main/java/alluxio/grpc/JobInfo.java, core/transport/src/main/java/alluxio/grpc/JobInfoOrBuilder.java, core/transport/src/main/java/alluxio/grpc/JobMasterProto.java, core/transport/src/main/java/alluxio/grpc/JobServiceSummary.java, core/transport/src/main/java/alluxio/grpc/JobServiceSummaryOrBuilder.java, job/common/src/main/java/alluxio/job/wire/JobInfo.java, job/common/src/main/java/alluxio/job/wire/JobServiceSummary.java, job/common/src/test/java/alluxio/job/wire/JobServiceSummaryTest.java, shell/src/main/java/alluxio/cli/fsadmin/command/ReportCommand.java, shell/src/main/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommand.java, shell/src/test/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommandTest.java
Don't need this in 2.1.0 so it can wait
Examples:
=> Add recently modified/failed jobs to the report

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java, docs/en/deploy/Running-Alluxio-On-a-HA-Cluster.md
EmbeddedJournal cluster will take 2 election timeouts to elect a leader even when it's a single master. This change is to override election timeouts to lower values in single master cluster.
Fixes https://github.com/Alluxio/alluxio/issues/10122
=> Override EJ election timeout for single-master cluster

docs/en/api/POSIX-API.md
Modify the doc to document it support vi/vim.
Other than vi/vim, other operations which do the append, modify or override still not work.
Cp when destination file exist will file.
Append to a file will fail.
Sed to replace content in a file will fail.
Vi/Vim may just be sepcial case that it internally do create a new file, delete old file, rename the new file to old name operation combinations.
=> [DOCFIX] Add vi/vim support in Fuse docs

integration/kubernetes/alluxio-fuse.yaml.template, integration/kubernetes/helm-chart/alluxio/values.yaml, integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-localJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-localJournal/worker/alluxio-worker-daemonset.yaml.template
The securityContext for K8s containers has a typo in `runAsGroup` field that runs in GID 10000 instead of 1000. Group `alluxio` has GID 1000. This change fixed the GID to the correct one for user `alluxio`.
=> Fix K8s container runAsGroup typo

core/base/src/main/java/alluxio/exception/ServiceNotFoundException.java, core/common/src/main/java/alluxio/AbstractClient.java, core/common/src/main/java/alluxio/grpc/ServiceVersionClientServiceHandler.java, core/common/src/test/java/alluxio/AbstractClientTest.java
Currently if a service is not found on server, the client will throw `UnavailableException` which is confusing and causing unnecessary retries. This change makes it throw `NotFoundException` which is what the server is actually throwing. To differentiate it from other `NotFoundException` such as file not found, a `ServiceNotFoundException` is included as cause.
=> Make client throw NotFoundException when service is not found

integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml, integration/kubernetes/helm-chart/alluxio/values.yaml, integration/kubernetes/multiMaster-embeddedJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-localJournal/worker/alluxio-worker-daemonset.yaml.template
This change corrects start arguments for Alluxio worker containers, from `worker` to `worker-only`. Since we have worker and job-worker 2 separate processes, if we start worker with `worker` argument the ports will be occupied and the job-worker will not be able to start.
=> Fix K8s worker start arguments

docs/en/deploy/Running-Alluxio-On-a-Cluster.md
Retain permissions when unzipping the tarball so that user logs can be written correctly.
=> [DOCFIX] Add tar command that saves permissions

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Before this patch
```console
$ bin/alluxio fs mount --readonly /reason s3://apc999/presto-tutorial/reason/
Ufs path /presto-tutorial/reason does not exist
```
After this patch:
```console
$ bin/alluxio fs mount --readonly /reason s3://apc999/presto-tutorial/reason/
Ufs path s3://apc999/presto-tutorial/reason does not exist
```
=> Improve error message on failed mount

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
Netty event loop manages propagating of stream control messages. Alluxio's authentication streams are bound to life-time of logical channels and it's unexpected for a stream to loose its loop while still alive.
=> Fix close order for FSContext resources

job/server/src/main/java/alluxio/job/transform/format/ReadWriterUtils.java, job/server/src/main/java/alluxio/job/transform/format/csv/CsvReader.java, job/server/src/main/java/alluxio/job/transform/format/parquet/ParquetReader.java, job/server/src/main/java/alluxio/job/transform/format/parquet/ParquetWriter.java
For transformation jobs on structured table, the output should not be written to Alluxio memory space, which might evict other active dataset, instead, write directly through to the under storage. Also, when reading the source files, it should be read with NO_CACHE so that the big tables are not cached into Alluxio.
=> Skip caching data into Alluxio during transformation

core/client/runtime/pom.xml
fixes #10224
Exclude loggings from Alluxio client jar since it may conflict with application logging dependencies and affect performance.
Those loggings become runtime dependencies.
=> Exclude logging from client jar and make then runtime dependencies

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
https://github.com/Alluxio/alluxio/issues/10264
In most of the ObjectUnderFileSystem operations, we will strip prefix if exist. Prefix here refers to the specific object UFS root key (s3://bucket_name for example). 
However, in our ObjectUnderFileSystem.isRoot check, we still check if the stripped path ("/" for example) equals to the full root key (s3://bucket_name).
This fix consider the isRoot case for both stripped path and original full url.
=> Fix ObjectUnderFileSystem isRoot to check stripped path

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, tests/src/test/java/alluxio/client/fs/UfsSyncIntegrationTest.java
This fixes the issue #8531 . 
Previously, we do not add the path we are loading to the `UfsSyncPathCache`. So when only children need to be synced, we repeatedly request children information from the UFS but never call `loadMetadata` on the parent and therefore the parent is never in the `UfsSyncPathCache`, leaving the impression that we are syncing the parent repeatedly. 
Now with this change, we do sync the parent and add it to the `UfsSyncPathCache`, so we do not repeatedly make requests to the ufs.
=> Load metadata for the path that we are syncing

table/server/master/src/main/java/alluxio/master/table/Partition.java, table/server/master/src/main/java/alluxio/master/table/transform/TransformJobInfo.java
Since only `get` and `set` are used in these `AtomicReference`s, `volatile` can be used to save the memory cost of the extra `AtomicReference` instances.
=> Replace AtomicReference by volatile

job/server/src/main/java/alluxio/job/transform/format/csv/CsvReader.java
Since filesystem cache is disabled explicitly now because we want to pass in alluxio configuration, the created filesystem should be closed to release resources.
=> Close filesystem in CsvReader

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
Includes the hive udb library in generated tarballs.
=> Add hive udb to libs in generate tarball

job/server/src/main/java/alluxio/job/transform/CompactDefinition.java
When a CompactTask fails, delete the output file, so when JobMaster retry the job, it might succeed, otherwise, during retry, it always throws FileAlreadyExistsException.
=> Make Compact transformation idempotent

core/common/src/main/java/alluxio/util/ConfigurationUtils.java
These logs will be printed out during every config sync heartbeat, unnecessary to let users know the sync is happening if there is no error.
=> Update INFO to DEBUG level for config sync logs

core/common/src/main/java/alluxio/ClientContext.java
The UriValidationEnabled information in ClientContext should be remembered.
=> Fix uri validation in client context reinit

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
We get a lot of this warnings when running certain internal jobs. Downgrading it to avoid spamming log files.
=> Downgrade some noisy warning on HDFS UFS

integration/kubernetes/alluxio-fuse-client.yaml.template, integration/kubernetes/alluxio-fuse.yaml.template, integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/Chart.yaml, integration/kubernetes/multiMaster-embeddedJournal/alluxio-configmap.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/alluxio-configmap.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-localJournal/alluxio-configmap.yaml.template, integration/kubernetes/singleMaster-localJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/singleMaster-localJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/singleMaster-localJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-localJournal/worker/alluxio-worker-daemonset.yaml.template
According to [Helm Chart doc](https://helm.sh/docs/developing_charts/), `Chart.yaml` should have `apiVersion: v1`. The current implementation puts Alluxio version under this key. Some Helm versions will complain about this key not recognized.
Key `appVersion` is an optional field for the app version. I think the original implementation messed these two up. We don't really need `appVersion` in `Chart.yaml` because it has been defined in `values.yaml`.
=> Fix Helm chart apiVersion

docs/_config.yml, integration/kubernetes/alluxio-fuse.yaml.template, integration/kubernetes/helm-chart/alluxio/Chart.yaml, integration/kubernetes/helm-chart/alluxio/values.yaml, integration/kubernetes/multiMaster-embeddedJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-localJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/singleMaster-localJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-localJournal/worker/alluxio-worker-daemonset.yaml.template, integration/yarn/pom.xml, libexec/alluxio-config.sh, tests/pom.xml, webui/pom.xml
- Manually bumped versions (i.e. libexec, k8s)
- Removed skipTests from integration module
- Removed version from deploy plugin on webui/pom.xml
=> Update versions to 2.1.1-SNAPSHOT

core/common/src/main/java/alluxio/conf/AlluxioProperties.java, core/common/src/main/java/alluxio/conf/PropertyKey.java
There is a race condition when building multiple ufs configuration concurrently. Extension properties of the same name that are not built-in will be created as custom property but can throw due to duplication in the property registration.
Fixed by synchronizing registration of custom properties .
=> Fix race condition building extension properties

integration/kubernetes/alluxio-fuse-client.yaml.template, integration/kubernetes/alluxio-fuse.yaml.template, integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/Chart.yaml, integration/kubernetes/multiMaster-embeddedJournal/alluxio-configmap.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/alluxio-configmap.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-localJournal/alluxio-configmap.yaml.template, integration/kubernetes/singleMaster-localJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/singleMaster-localJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/singleMaster-localJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-localJournal/worker/alluxio-worker-daemonset.yaml.template
The original PR corrects `Chart.yaml` key `apiVersion` in Helm Chart.
pr-link: Alluxio/alluxio#10384
change-id: cid-cf15b0fd4caeee8b16cb68852f25ee55654fccd6
=> Port changes from [#10384] to branch-2.1

core/common/src/main/java/alluxio/underfs/UfsDirectoryStatus.java
In some UFSes like S3, directories will have a null lastModifiedTimeMs indicating the timestamp is not available. We used `long` as constructor parameter type which will throw when null is passed in for a S3 directory.
=> Fix NPE in UfsDirectoryStatus

core/common/src/main/java/alluxio/conf/PropertyKey.java
This change will reduce the load on the Alluxio Master when running a large number of workers. However, it will also impact the ability of the Alluxio Master to provide the most up-to-date block locations of a block in a cluster with a high eviction rate.
=> Increase block heartbeat interval from worker from 1s to 10s

core/server/common/src/main/java/alluxio/web/WebServer.java
This helps with the flakiness for testing, since we set the port reuse option for other server sockets. In unittests, a server socket is created, the port is retrieved ("reserved"), then the socket is closed, and then the actual server is started with that port. Port reuse is important for the actual server to start with that same port.
=> Set port reuse for web server

tests/src/test/java/alluxio/client/rest/RestApiTest.java, tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
Speed up the test by avoiding worker out of space exceptions. Decreasing the `USER_FILE_BUFFER_BYTES` then caused issues with too many open block worker connections, so had to reduce the file sizes too, to avoid that resource pool issue.
=> Improve and speed up S3 rest test

core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java, core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadRequest.java, job/server/src/main/java/alluxio/master/job/JobCoordinator.java
Confusing error message on failed reads are observed. This PR improves
or corrects the following items:
- Throw the right exception on failed `openBlock(context, response);`,
rather than always complaining missing fallback blocks
- Implement `toString` for `BlockReadRequest`, otherwise `request
alluxio.worker.grpc.BlockReadRequest@1becc9d9` is not very helpful.
- Add Job Id in Job master logs so we can correlate Job master logs and
master logs much easier by the job Id
Before
```
On Worker:
2019-10-29 14:48:40,984 DEBUG AbstractReadHandler - Exception occurred
while reading data for read request
alluxio.worker.grpc.BlockReadRequest@1becc9d9.
java.io.FileNotFoundException:
/Users/binfan/Dropbox/Work/alluxio/alluxio/underFSStorage/.alluxio_ufs_blocks.alluxio.0x1D91AC0E01AB0165.tmp/1325400064 …
```
=> Port #10353 to branch 2.1: Improve error message for Failed Block Reads

core/server/worker/src/main/java/alluxio/Sessions.java, core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java
- Differentiate `ASYNC_CACHE_WORKER_SESSION_ID` with `ASYNC_CACHE_UFS_SESSION_ID`: the former session is caching from a remote worker and the latter session is caching from UFS
- The goal of this PR is to enable more advanced allocator which can leverage the information: caching from UFS or caching for remote worker to make subtle decisions.
=> Use different session IDs for async cache requests

core/server/master/src/main/java/alluxio/master/block/BlockMasterClientServiceHandler.java
Removes some unnecessary typing and also fixes the name of some methods so we collect the correct metrics.
=> Clean up block master service handler

core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java
[`./profiler.sh -d 30 pid`](https://github.com/jvm-profiling-tools/async-profiler) => 
```
ns  percent  samples  top
----------  -------  -------  ---
15747991110   52.61%     1564  gettimeofday
12484184818   41.70%     1238  [unknown]
804458218    2.69%       80  alluxio.master.metastore.caching.Cache$EvictionThread.evictToLowWaterMark
333278940    1.11%       33  os::javaTimeMillis()
160014616    0.53%       16  alluxio.master.metastore.caching.Cache$EvictionThread.run
65950919    0.22%        8  KlassScanClosure::do_klass(Klass*)
40337398    0.13%        5  FastScanClosure::do_oop(oopDesc**)
31711313    0.11%        3  __pthread_cond_timedwait
22996059    0.08%        3  ClassLoaderData::oops_do(OopClosure*, KlassClosure*, bool)
21247918    0.07%        1  __pthread_disable_asynccancel …
```
=> Reduce the CPU usage of the alluxio master process

tests/src/test/java/alluxio/client/rest/AlluxioMasterRestApiTest.java, tests/src/test/java/alluxio/client/rest/AlluxioWorkerRestApiTest.java, tests/src/test/java/alluxio/client/rest/BlockMasterClientRestApiTest.java, tests/src/test/java/alluxio/client/rest/JobMasterClientRestApiTest.java, tests/src/test/java/alluxio/client/rest/JobMasterRestApiTest.java, tests/src/test/java/alluxio/client/rest/RestApiTest.java, tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java
This speeds up the REST tests, by reusing the LocalAlluxioCluster throughout each test class. This avoids tearing down and recreating the cluster between each individual test case. Minor modifications were required to be able to re-use an existing LocalAlluxioCluster between tests.
=> Reuse LocalAlluxioCluster to speedup REST tests

shell/src/main/java/alluxio/cli/fs/command/CpCommand.java, tests/src/test/java/alluxio/client/cli/fs/command/CpCommandIntegrationTest.java
Sometimes, the cp command does not succeed (like when there are no available workers). However, the destination is created and not cleaned up. This PR deletes the destination file if the copy fails.
=> Cleanup file after a failed cp command

tests/src/test/java/alluxio/job/master/JobMasterIntegrationTest.java
JobWorkerHealth requires a full heartbeat from a worker to be populated. So wait for it to be populated.
=> Fix JobMasterIntegrationTest flake

core/server/worker/src/main/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandler.java
UfsFallbackBlockWriteHandler#createRequestContext does not properly initialize the BlockWriteRequestContext instance
=> Fix NPE in UfsFallbackBlockWriteHandler

job/common/src/main/java/alluxio/job/plan/meta/PlanInfo.java, job/common/src/main/java/alluxio/job/wire/TaskInfo.java, job/server/src/main/java/alluxio/worker/JobWorker.java, job/server/src/main/java/alluxio/worker/job/command/CommandHandlingExecutor.java, job/server/src/main/java/alluxio/worker/job/task/TaskExecutorManager.java, job/server/src/test/java/alluxio/master/job/workflow/WorkflowTrackerTest.java
@ZacBlanco: made a point that workerAddress is way more available from the CommandHandlingExecutor than I originally anticipated. So moving one more to being in constructor.
Other Miscellaneous Change: 
getAndClearTaskUpdates now returns a wire object and the GRPC protoization method happens during the worker's heartbeat instead.
=> Add worker host in TaskInfo from construction inside JobWorker

shaded/hadoop/pom.xml
Shaded Hadoop should be versioned at `${ufs.hadoop.version}`
=> Update Shaded Hadoop POM

core/common/src/main/java/alluxio/grpc/GrpcServer.java, core/common/src/main/java/alluxio/grpc/GrpcServerBuilder.java, core/common/src/main/java/alluxio/grpc/GrpcService.java, core/common/src/main/java/alluxio/security/authentication/AuthenticationServer.java, core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java, core/server/master/src/main/java/alluxio/master/backup/BackupLeaderRole.java
Open gRPC streams prevents graceful server shutdown. This PR aims to provide infra for service implementations to provide closers to be invoked during server shutdown so they can close their active streams to allow for graceful shutdown.
There are currently 2 such services:
- Authentication service
- Backup leader service
=> Implement infra to close resources during gRPC server shutdown

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/server/common/src/main/java/alluxio/master/PrimarySelectorClient.java, minicluster/src/main/java/alluxio/multi/process/PortCoordination.java, tests/src/test/java/alluxio/server/ft/ZookeeperFailureIntegrationTest.java
Curator has 2 policies for managing zookeeper client state when connection errors happen.
- STANDARD; is finicky and treats leader state as dirty after any connection state change.
- SESSION; is for more stable leadership state as it leverages internal zookeeper session Ids.
Curator comes with STANDARD policy as default. 
This PR makes this setting configurable.
=> Support session level connection management for leader election

core/base/src/main/java/alluxio/collections/Pair.java, job/common/src/test/java/alluxio/job/SleepJobConfig.java, job/server/src/main/java/alluxio/job/plan/PlanDefinition.java, job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java, job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java, job/server/src/main/java/alluxio/job/plan/persist/PersistDefinition.java, job/server/src/main/java/alluxio/job/plan/replicate/EvictDefinition.java, job/server/src/main/java/alluxio/job/plan/replicate/MoveDefinition.java, job/server/src/main/java/alluxio/job/plan/replicate/ReplicateDefinition.java, job/server/src/main/java/alluxio/job/plan/transform/CompactDefinition.java, job/server/src/main/java/alluxio/master/job/plan/PlanCoordinator.java, job/server/src/test/java/alluxio/job/plan/SleepPlanDefinition.java, job/server/src/test/java/alluxio/job/plan/TestPlanDefinition.java, job/server/src/test/java/alluxio/job/plan/load/LoadDefinitionTest.java, job/server/src/test/java/alluxio/job/plan/migrate/MigrateDefinitionSelectExecutorsTest.java, job/server/src/test/java/alluxio/job/plan/persist/PersistDefinitionTest.java, job/server/src/test/java/alluxio/job/plan/replicate/EvictDefinitionTest.java, job/server/src/test/java/alluxio/job/plan/replicate/ReplicateDefinitionTest.java, job/server/src/test/java/alluxio/master/job/plan/PlanCoordinatorTest.java, job/server/src/test/java/alluxio/master/job/plan/PlanTrackerTest.java, tests/src/test/java/alluxio/job/cancel/CancelIntegrationTest.java, tests/src/test/java/alluxio/job/master/JobMasterIntegrationTest.java
From:
Map<WorkerInfo, Parameters> -> List<Pair<WorkerInfo, Parameters>>
This allows for each plans to submit more than one task perTaskWorker.
Other miscellaneous Change:
Pair's equal and hashcode was modified so that Pair accepts null as a valid input for First and/or Second.
=> Change return type of selectExecutors for PlanDefinition

core/common/src/main/java/alluxio/network/RejectingServer.java, core/common/src/test/java/alluxio/master/PollingMasterInquireClientTest.java, core/server/common/src/main/java/alluxio/master/MasterProcess.java
Rejecting server is listening on 0.0.0.0, this is possibly cause some security issue.
=> Make rejecting server listen on correct address

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java, core/server/master/src/test/java/alluxio/master/metrics/MetricsMasterTest.java
Fixes https://github.com/Alluxio/alluxio/issues/10470
Previously we process worker metrics synchronously in the MasterWorkerInfo lock and also the WorkerMetrics lock. This will 
(1) Make each worker heartbeat takes longer. Worker heartbeat need to wait for the submitted metrics to be processed.
(2) Make worker heartbeats block each other. We can only process one worker metrics at a time.
Process worker metrics asynchronously will help unblock worker heartbeats.
=> Process worker metrics asynchronously

core/base/src/main/java/alluxio/util/io/PathUtils.java, core/common/src/test/java/alluxio/util/io/PathUtilsTest.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
For incremental sync on large directories, a ufs listing at the sync point can be an expensive operation. This PR attempts to address the issue by calculating the lowest common ancestor of the changed file list reported by the ufs.
=> Refine ufs.listStatus granularity for incremental sync

core/common/src/main/java/alluxio/util/ShellUtils.java, core/common/src/main/java/alluxio/util/UnixMountInfo.java, core/common/src/test/java/alluxio/util/ShellUtilsTest.java
On the corner case when linux mount command returns invalid result during worker start-up, a NPE will be thrown [here](https://github.com/Alluxio/alluxio/blob/de0da9ccc26bb96f763ba78afc544c778023f646/core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTier.java#L148) as the `mMountOptions` will not be initialized. 
This PR will fix #10514
=> Fix potential NPE on worker start when local mount command fails

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java, core/client/fs/src/main/java/alluxio/client/file/FileInStream.java, core/client/fs/src/test/java/alluxio/client/file/FileInStreamTest.java, core/common/src/main/java/alluxio/client/file/URIStatus.java, core/common/src/main/java/alluxio/wire/FileInfo.java
In the FileInfo retrieved from master in openFile, there should be the latest block information, so there is no need to issue an RPC to get the block info again.
=> Remove extraneous client RPC to get block info from master

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
Some code paths synchronize on mOpenFiles.
For one case, the synchronization can be replaced by an AtomicLong.
For other cases, removing the synchronization won't affect thread-safety.
=> Remove synchronization on mOpenFiles in AlluxioFuseFileSystem

core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncer.java
The heartbeat thread waits for the master to finish an incremental or full sync before processing the next batch of events from the ufs. With this PR, both incremental and active syncs for different sync points proceed in parallel on the master.
=> Parallelize active sync across sync points

core/common/src/main/java/alluxio/metrics/Metric.java, core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java, core/common/src/main/java/alluxio/util/CommonUtils.java, core/common/src/main/java/alluxio/util/UnderFileSystemUtils.java, core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java, core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java, core/server/master/src/test/java/alluxio/master/metrics/MetricsMasterTest.java, underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java, underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
Fixes https://github.com/Alluxio/alluxio/issues/10470
This PR aims to improve concurrency in MetricsStore when processing worker/client metrics.
It removes the synchronized lock on the metrics sets.
Atomically updates metric values instead of removing and constructing new objects.
This memoizes the Metrics.getFullMetricName(), since it is costly in time and allocations.
When Metric.getFullMetricName() runs normally, it bumps up the heartbeats can be processed per second from 1000-3000 heartbeats/second to 2000-5000 heartbeats/second.
When Metric.getFullMetricName() is unexpectedly slow, the performance improvement can be really big (when 100 worker heartbeats with 50 executor threads, before my change takes 11 min, after my change takes 18 second if getFullMetricName sleep for 15ms).
=> Improve concurrency for MetricsStore

pom.xml
On-the-fly Jacoco instrumentation does not work for tests which use PowerMock. Therefore, offline instrumentation must be used.
=> Use Jacoco offline instrumentation to track PowerMock tests

core/server/proxy/src/main/java/alluxio/proxy/AlluxioProxy.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorker.java, job/server/src/main/java/alluxio/worker/AlluxioJobWorker.java
It turns out that our process creation can be quite heavy and we may see `java.lang.ExceptionInInitializerError` on constructors. Adding error handling to match how we are doing with alluxio master and alluxio job master on other processes. 
Prior to this change, the reasons of a failed process (e.g., a worker) may not be in `worker.log` but in `worker.out` instead, as the `ExceptionInInitializerError` is treated as a JVM runtime exception not logged. After this patch, users can tell the errors easier by looking at `{worker,proxy,job_worker}.log` similar as how they can reason at `{master,job_master}.log`
=> Improve error handling on creating Processes

job/common/src/main/java/alluxio/job/plan/transform/PartitionInfo.java, job/common/src/test/java/alluxio/job/workflow/composite/CompositeConfigTest.java, job/server/src/main/java/alluxio/job/plan/transform/format/csv/CsvReader.java, job/server/src/test/java/alluxio/job/plan/transform/format/ReadWriteTest.java, table/server/common/src/main/java/alluxio/table/common/layout/HiveLayout.java, table/server/common/src/main/java/alluxio/table/common/transform/action/TransformActionUtils.java, table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java, table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveTable.java, tests/src/test/java/alluxio/job/plan/transform/format/TableReaderIntegrationTest.java
Previously we were looking for lines to skip in the wrong properties. (serde properties) now look for it in table properties. 
Fixes #10557
=> Use correct properties for csv lines to skip

examples/src/main/java/alluxio/cli/UnderFileSystemContractTest.java
Currently `UnderFileSystemContractTest` uses `-Dxxx=yyy` to pass UFS options. This does not work if the UFS uses `getMountSpecificConf` to retrieve the options. This fix added some logic to merge system properties passed through `-D` into the UFS configuration as mount specific properties.
=> Fix UFS contract test options

dev/jenkins/build.sh, pom.xml, tests/pom.xml
Jacoco generates coverage data in .exec files, which are then used for the jacoco-report goal. However, integration tests are in a separate module from the source code they are testing. Therefore, all the coverage data is not included when reporting on the source code.
Therefore, to capture all the test coverage, the reporting has to be done in 2 steps:
- generate all coverage data (into the same data file)
- report the coverage data using the coverage data which includes all the tests
This is done with 2 separate profiles for the different steps:
- `jacoco` to generate the coverage data
- `jacocoReport` to generate the report using the coverage data
=> Include integration test results in code coverage

core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java
Creating the full description adds a nontrivial performance overhead. Provide a simplified description when debug logging is not enabled.
=> Use a simplified description for grpc data readers

core/client/fs/src/main/java/alluxio/client/block/stream/GrpcBlockingStream.java
The cost of formatting the error message and throwing the exception is nontrivial. Since this method does not ensure the channel is ready, we can simply log the failure (this is the previous behavior at the call site).
=> Log errors instead of throwing exceptions for best-effort send

core/transport/src/grpc/job_master.proto, core/transport/src/main/java/alluxio/grpc/JobMasterProto.java, core/transport/src/main/java/alluxio/grpc/JobWorkerHealth.java, core/transport/src/main/java/alluxio/grpc/JobWorkerHealthOrBuilder.java, job/common/src/main/java/alluxio/job/wire/JobWorkerHealth.java, job/common/src/test/java/alluxio/job/wire/JobWorkerHealthTest.java, job/server/src/main/java/alluxio/worker/job/command/CommandHandlingExecutor.java, job/server/src/main/java/alluxio/worker/job/command/JobWorkerHealthReporter.java, job/server/src/main/java/alluxio/worker/job/task/TaskExecutorManager.java, shell/src/main/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommand.java, shell/src/test/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommandTest.java
But only print UnfinishedTasks to jobservice report.
➜  alluxio git:(queue_length) ✗ ./bin/alluxio fsadmin report jobservice
Worker: 10.0.0.65   Unfinished Tasks: 1      Load Avg: 5.7861328125, 3.99169921875, 3.75390625
Status: CREATED   Count: 128
Status: CANCELED  Count: 0
Status: FAILED    Count: 0
Status: RUNNING   Count: 1
Status: COMPLETED Count: 1477
- Note here that unfinished task of a worker only contains jobs that are in "RUNNING" but not in "CREATED". 
- The Unfinished Tasks here is not very interesting because there is only one worker and not many running.
=> Add UnfinishedTasks to JobWorkerHealth

core/base/src/main/java/alluxio/exception/ExceptionMessage.java, core/base/src/main/java/alluxio/exception/FileIncompleteException.java, core/base/src/main/java/alluxio/exception/OpenDirectoryException.java, core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java, core/client/fs/src/main/java/alluxio/client/file/CachingFileSystem.java, core/client/fs/src/main/java/alluxio/client/file/FileSystem.java, core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java, core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java, core/client/fs/src/test/java/alluxio/client/file/CachingFileSystemTest.java, core/client/fs/src/test/java/alluxio/client/file/MetadataCacheTest.java, core/common/src/main/java/alluxio/conf/PropertyKey.java, integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java, integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java
1. in fuse openFile, a getStatus RPC is issued, but openFile will also issue a getStatus RPC internally, this redundant RCP is reduced in this PR.
2. when getting status of a file, or listing status of a directory, cache the status results so that future getStatus and listStatus calls do not need to issue RPCs to master.
This PR introduces a new class `CachingFileSystem extends BaseFileSystem` to cache path metadata.
=> Add CachingFileSystem

job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java, job/server/src/test/java/alluxio/job/plan/migrate/MigrateDefinitionSelectExecutorsTest.java
Using some of the API changes from before to make distributedCp and distributedMv faster (and take more resources).
The same logic can be applied to PersistCommand as well.
Test scenario: (r4.xlarge)
1. 4000 Files each with 100KB.
2. 2 Workers.
3. Deployed https://github.com/bradyoo/alluxio/pull/4/files for testing to see how different parallel factors impact this.
4. Async Through
Results:
The last parameter is the parallel factor: Which is not in this PR because this PR simply defaults that to 10 where as in this result, if you don't provide a parameter, it defaults to 1 (old behavior)
This is with alluxio.job.worker.threadpool.size set to 20. (Default is 10.)
$ time ./bin/alluxio fs distributedCp /async-write2/ /async-write20/
.................Copied /async-write2 to /async-write20 …
=> Parallelize MigrateDefinition within a worker

core/transport/pom.xml
Hello, I noticed that the direct dependency with compile scope `io.grpc:grpc-netty` is declared in the module `alluxio-core-transport`. However, this dependency is not used and, therefore, it can be removed safely to make the pom of this module clearer. 
This dependency also induces a set of transitive dependencies that are not used, as we can see from the dependency tree:
```
+- io.grpc:grpc-netty:jar:1.17.1:compile 
|  +- (io.grpc:grpc-core:jar:1.17.1:compile - omitted for duplicate)
|  +- io.netty:netty-codec-http2:jar:4.1.30.Final:compile
|  |  +- io.netty:netty-codec-http:jar:4.1.30.Final:compile
|  |  |  \- io.netty:netty-codec:jar:4.1.30.Final:compile
|  |  |     \- (io.netty:netty-transport:jar:4.1.30.Final:compile - omitted for duplicate)
|  |  \- …
```
=> Remove unused io.grpc:grpc-netty dependency from alluxio-core-transport

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/conf/RemovedKey.java, core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, tests/src/test/java/alluxio/client/fs/FileOutStreamIntegrationTest.java
After the changes in https://github.com/Alluxio/alluxio/pull/10485 to make metrics processing async, worker heartheat has not related to the latency of metrics. 
Change default worker heartbeat back to 1s can improve RPC performance.
=> Change default worker heartbeat back to 1s

core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java, core/common/src/main/java/alluxio/security/authentication/SaslStreamClientDriver.java
Calling `notifyWhenStateChanged()` on managed channel will cause accumulation of listeners and could potentially cause OOM in massive channel create/delete scenarios.
We can safely discard making this call since we keep channel's authentication stream active. Server state changes that effect authentication will reflect in authentication stream's `onError()` method as well. This provides more stable accounting as earlier tracking was sensitive to unrelated connection level state changes as well.
=> Avoid registering listener for channel state change

shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
Premise: Each job has an overhead of at least 1~2 seconds because of it takes at least JobWorker heartbeats (once for the work to go from JobMaster to JobWorker and once more for the JobWorker work completion to be reported backed to JobMaster) so it is important that when there are a lot of jobs to be done, that many jobs get submitted at the same time.
What was done:
- Remove creating threads per job (only 1 thread)
- Increase number of default outgoing jobs from 10 -> 1000 (also configurable)
- Client round robins all of the outgoing active jobs, handles retries, and when they succeed, remove from the list to be filled with new jobs.
Test Environment: 
- Local machine
- 12000 Files
- Approximately 450 bytes each
- Ran fs free followed by fs distributedLoad, checked that distributedLoad …
=> Optimize DistributedLoadCommand

shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
Premise: Each job has an overhead of at least 1~2 seconds because of it
takes at least JobWorker heartbeats (once for the work to go from
JobMaster to JobWorker and once more for the JobWorker work completion
to be reported backed to JobMaster) so it is important that when there
are a lot of jobs to be done, that many jobs get submitted at the same
time.
What was done:
- Remove creating threads per job (only 1 thread)
- Increase number of default outgoing jobs from 10 -> 1000 (also
configurable)
- Client round robins all of the outgoing active jobs, handles retries,
and when they succeed, remove from the list to be filled with new jobs.
Test Environment:
- Local machine
- 12000 Files
- Approximately 450 bytes each
- Ran fs free followed by fs distributedLoad, checked that
distributedLoad …
=> Port changes of [#10589] to branch-2.1

table/server/underdb/hive/pom.xml, table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java
The 2.3 client uses a new thrift API (`get_table_req`) which older HMS versions do not have. Therefore, for compatibility with older HMS versions, an older client must be used. 2.2 is the latest client version which still works with HMS versions <= 2.2.
This 2.2 hive client has been tested and works with HMS versions: 1.0.1, 1.1.0, 1.2.2, 2.0.1, 2.1.1, 2.2.0, 2.3.6, 3.0.0, 3.1.2
=> Use 2.2 hive client for greater compatibility

core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java, core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java, core/common/src/main/java/alluxio/conf/PropertyKey.java
I found short circuit has better performance than domain socket.
But when i enable short-circuit read/write, alluxio client prefer to use domain socket as default.
I want to use short-circuit read/write, even domain socket is ready in AlluxioWorker.
I use a new property `alluxio.user.short.circuit.preferred` to control the logic, which is backward compatible.
But i think it is better to use only `alluxio.user.short.circuit.enabled` to judge whether to enable short circuit.
=> Enable short circuit even domain socket is configured

job/server/src/main/java/alluxio/worker/job/task/TaskExecutor.java, job/server/src/main/java/alluxio/worker/job/task/TaskExecutorManager.java, job/server/src/test/java/alluxio/worker/job/task/TaskExecutorTest.java, tests/src/test/java/alluxio/job/master/JobMasterIntegrationTest.java
JobMaster.cancel() previously cleaned up properly only if the JobWorker thread was actually executing the task. But in reality, almost all of the tasks are in the executor queue.
=> Fix JobMaster.cancel(jobId)

core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java
`awaitTermination()` on channel that has been shutdown gracefully will not return if a health check was triggered on it. This causes `PollingMasterInquireClient` to be blocked for the full channel shutdown timeout per master. (master count x channel shutdown timeout)
=> Shutdown channel immediately if health-check failed

core/common/src/main/java/alluxio/conf/PropertyKey.java
@calvinjia: I would like to turn this off by default because developing with this on locally is too difficult and I'm not too confident having something I would like to be on during development to be on in production.
=> Turn off JobWorker throttling by default

core/common/src/test/java/alluxio/ConfigurationTestUtils.java
Occasionally, rpc auth takes longer than usual/expected, especially in a highly concurrent scenario (`ConcurrentFileSystemMasterCreateTest`). Anecdotally, I've seen some take over 4 seconds, as opposed to the usual sub-100ms auth. Therefore, 2s is sometimes too short for tests.
=> Increase auth timeout to reduce flaky tests

core/server/common/src/main/java/alluxio/master/BackupManager.java
Change to getMetricsName before registering.
Add a "Master." for the backup metrics.
=> Fix the backup restore metrics name

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
Default server selection policy will select a random server while connecting to cluster. When a connected server is not the leader, client requests will simply be forwarded to the leader.
We use raft clients for journal writes and writes are only allowed on leader. Forcing client to connect to leader will improve performance by eliminating extra hops and will make transport level traces less confusing for investigation.
=> Set raft-client policy to connect to leader for journal writes

tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterCreateTest.java, tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterLoadMetadataTest.java, tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterSetTtlTest.java
These fixes is to make sure master executor has enough thread to being with. Otherwise, delay on master ForkJoinPool's internal thread count adjustment might take several seconds. This can interfere with these tests' timing expectations.
=> Fix cluster configuration for concurency tests

core/common/src/main/java/alluxio/util/CommonUtils.java, job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java, job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java, job/server/src/test/java/alluxio/job/plan/load/LoadDefinitionTest.java, shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
Also removed active_jobs parameter from the command because it's needlessly confusing.
=> Parallelize load definition within a worker

docs/en/compute/Hive.md
Added one more config parameter to check in the tutorial. 
The use case is, Hive in HDP default file format is not TextFile so the tutorial does not work.
=> [DOCFIX] Improve Hive doc

docs/en/compute/Spark-On-Kubernetes.md
This changes which example job to run in Spark on K8s instruction.
Using built-in Spark example class has 3 benefits:
1. The existing Alluxio example doesn't close the SparkContext after it finishes so the driver + executors stay in RUNNING state unless killed manually. This is confusing for new users.
2. Removed dependency on an existing Alluxio example jar on S3. 
3. (minor) Word count has more output than line count so easier for the user to identify from the logs.
=> [DOCFIX] Use Spark built-in example for Spark on K8s example job

job/server/src/main/java/alluxio/worker/job/command/CommandHandlingExecutor.java, job/server/src/main/java/alluxio/worker/job/task/TaskExecutor.java, job/server/src/main/java/alluxio/worker/job/task/TaskExecutorManager.java, job/server/src/test/java/alluxio/job/command/CommandHandlingExecutorTest.java, job/server/src/test/java/alluxio/worker/job/task/TaskExecutorTest.java, tests/src/test/java/alluxio/job/master/JobMasterIntegrationTest.java
Previously, the order of commands was not honored by the workers because there were 4 threads handling the command handling service. But the benefit of these threads is minimal because underlying TaskExecutorManager is synchronized.
Resolve this by moving the expensive portion that could be executed in parallel under TaskExecutor and making CommandHandlingService single threaded.
=> Fix Command Execution order on workers

core/common/src/main/java/alluxio/shell/CommandReturn.java, core/common/src/main/java/alluxio/shell/ScpCommand.java, core/common/src/main/java/alluxio/shell/ShellCommand.java, core/common/src/main/java/alluxio/shell/SshCommand.java, core/common/src/main/java/alluxio/util/ShellUtils.java, core/common/src/test/java/alluxio/shell/ShellCommandTest.java, core/common/src/test/java/alluxio/util/ShellUtilsTest.java
This change adds a wrapper to SSH executing a command to ShellUtils, together with SCP commands.
`ShellUtils` class refactored with inner classed extracted to standalone classes.
PR https://github.com/Alluxio/alluxio/pull/10596 relies on this utility as it extensively invokes commands over SSH.
=> Add SSH and SCP command utility and refactor shell utility

docs/en/core-services/Caching.md
PropertyKey `alluxio.user.file.load.ttl` has been removed from Alluxio in https://github.com/Alluxio/alluxio/pull/9353/files
This fix removes the ref to this field from the doc. PR #9353 attempted to remove its reference in code block but missed the note part. This fix attempts to rephrase the note part to completely remove the trace of this property.
=> [DOCFIX] Remove file.load.ttl reference in doc

shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
Hypothetical Environment:
3 nodes, each with a job worker and a worker.
Suppose a file x.txt has 10 blocks to load but one of its blocks (**Block 1**) is in the middle of being read on (**Worker A**), Attempting to load this file creates 10 tasks and the task to load **Block 1** is assigned to be in **Worker A**.
Previous behavior:
The task in an attempt to load **Block 1** in **Worker A** fails. This fails the job but the other 9 tasks are still continuing. The client notices the failure and triggers a retry. Retry notices that none of the 10 blocks are still loaded yet and shuffles the location of where they are getting loaded.
New behavior:
The task in an attempt to load **Block 1** in **Worker A** fails. This fails the job but the other 9 tasks are still continuing. The client waits …
=> Fix Distributed Load Retry Logic

job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java, job/server/src/test/java/alluxio/job/plan/migrate/MigrateDefinitionRunTaskTest.java
1. When deleting the source, delete it unchecked because if the source is not fully persisted, move should still be successful.
2. When performing a move operation, change the writeType to THROUGH if the source is persisted to not make files unpersisted.
=> Change DistributedMv writeType and deleteSource

table/server/master/src/main/java/alluxio/master/table/transform/TransformManager.java, table/server/master/src/test/java/alluxio/master/table/transform/TransformManagerTest.java
Previously was printing something like:
`Existing job 1,578,584,820,526 is transforming table ratings in database movielens`
new message is:
`Existing job 1578584820526 is transforming table ratings in database movielens`
=> [SMALLFIX] Fix error message for existing transform job running

core/common/src/main/java/alluxio/metrics/MasterMetrics.java, core/server/common/src/main/java/alluxio/master/BackupManager.java
Previous we record the time of last backup/restore using Timer metrics.
Timer metrics has some problem of recording operation durations. 
In local backup restore tests, timer metrics cannot record the restore time correctly.
This PR change to use Gauge metrics.
=> Fix backup restore timer metrics

core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataReader.java, core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java, core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataReader.java, core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java, core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java, core/client/fs/src/test/java/alluxio/client/block/stream/BlockInStreamTest.java, core/client/fs/src/test/java/alluxio/client/block/stream/GrpcDataReaderTest.java, core/client/fs/src/test/java/alluxio/client/block/stream/GrpcDataWriterTest.java, core/client/fs/src/test/java/alluxio/client/block/stream/LocalFileDataWriterTest.java, core/client/fs/src/test/java/alluxio/client/block/stream/NoopClosableResource.java, core/client/fs/src/test/java/alluxio/client/block/stream/UfsFallbackLocalFileDataWriterTest.java, job/server/src/main/java/alluxio/job/plan/replicate/EvictDefinition.java, job/server/src/main/java/alluxio/job/plan/replicate/MoveDefinition.java, shell/src/main/java/alluxio/cli/fsadmin/metrics/ClearCommand.java, tests/src/test/java/alluxio/client/fs/BlockWorkerClientCloseIntegrationTest.java
This removes a resource leak which may occur when a thread on a client is interrupted while performing any kind of operation.
Because it's possible for a fs context re-initialization to occur while the resource is
acquired this solution removes the `blockReinit` which throws a runtime exception during
an interrupt and is the root cause of the resource leak.
There are three different cases to which may occur during the release of the resource
1. Release while the context is re-initializing
- The original mBlockMasterClientPool or mFileSystemMasterClientPool
may be null, closed, or overwritten with a difference pool. The inner class here saves
the original pool reference used to acquire the client initially. Releasing into the closed pool
is harmless.
2. Release after the context has been …
=> Release clients back into pools during even during context reinit

core/client/fs/src/main/java/alluxio/client/file/CachingFileSystem.java, core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java, core/client/fs/src/test/java/alluxio/client/file/CachingFileSystemTest.java
Note that after caching the list status results, if there are files added to or deleted from the directory, then these updates might not be reflected until the cache is invalidated.
=> Cache list status results

core/client/fs/src/main/java/alluxio/client/block/stream/GrpcDataWriter.java, core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataReader.java, core/client/fs/src/test/java/alluxio/client/block/stream/GrpcDataWriterTest.java, tests/src/test/java/alluxio/client/fs/BlockWorkerClientCloseIntegrationTest.java
This fix keeps the BlockWorkerClient open after returning the GrpcDataWriter.
Previously, we used a try-with-resources which would close the client before
being returned to the user. This could result in poor behavior if the writer
is used after the #create() call.
Also, to prevent a leak in the LocalFileDataReader, we attempt to close the
reader within the try block inside of its close method.
This is a follow-up to #10719
=> Keep worker client open after creating data reader/writer

job/server/src/main/java/alluxio/job/plan/transform/format/CachedPath.java, job/server/src/main/java/alluxio/job/plan/transform/format/JobPath.java, job/server/src/main/java/alluxio/job/plan/transform/format/csv/CsvReader.java, job/server/src/main/java/alluxio/job/plan/transform/format/parquet/ParquetReader.java, job/server/src/main/java/alluxio/job/plan/transform/format/parquet/ParquetWriter.java, job/server/src/test/java/alluxio/job/plan/transform/format/JobPathTest.java
JobServerContext provides a FileSystem to be shared amongst its workers.
However, Hadoop Path has its own API for getting FileSystem which ends up creating too many filesystems that can be shared.
This extends Path to cache values of getFileSystem to prevent opening of too many FileSystems.
As a result, CsvReader now no longer closes the FileSystem
Known Issue (For future fix):
Multiple threads can get into creating the same FileSystem at the same time. The problem with this is that, not only there can be 9 extra copies, because only one actually makes it into the cache, there are 9 that just never get closed.
=> Cache getFileSystem for path

core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java, core/client/fs/src/test/java/alluxio/client/metrics/MetricsHeartbeatContextTest.java
I ran these tests on an Ubuntu 18.04 server with a fresh install of the
latest  java and maven versions. The AlluxioFileInStreamTest failed due
to an issue with PowerMock. The MetricsHeartbeatContextTest took
\> 120s to complete due to needing to wait for the connect RPC to time
out.
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/zac/.local/apache-maven-3.6.3
Java version: 1.8.0_232, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-74-generic", arch: "amd64", family: "unix"
```
=> Fix tests on ubuntu

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/main/java/alluxio/client/file/cache/DefaultMetaStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java, core/client/fs/src/main/java/alluxio/client/file/cache/MetaStore.java, core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
Improve unit test of `LocalCacheManager` by
- removing PowerMock
- instead of asserting on internal implementation (counting func calls), assert on cache state before and after.
=> Cleanup LocalCacheManager  Unit Test

tests/src/test/java/alluxio/testutils/underfs/sleeping/SleepingUnderFileSystemFactory.java
Wrapping SleepingUnderFileSystem with a special forwarder to let master thread-pool know that threads will sleep on this UFS.
=> Make SleepingUnderFileSystem to make use of managed blocking

table/server/master/src/main/java/alluxio/master/table/AlluxioCatalog.java, table/server/master/src/main/java/alluxio/master/table/DefaultTableMaster.java, table/server/master/src/main/java/alluxio/master/table/TableMaster.java, table/server/master/src/main/java/alluxio/master/table/TableMasterClientServiceHandler.java, table/server/master/src/test/java/alluxio/master/table/AlluxioCatalogTest.java, tests/src/test/java/alluxio/server/ft/journal/TableMasterJournalIntegrationTest.java
Note here `getDatabase` returns an object that contains only the database name.
A subsequent PR will add more content into this database object and the associated Udb object to populate this database object.
=> Implement basic version of getDatabase in catalog service

shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java, shell/src/main/java/alluxio/cli/fs/command/DistributedMvCommand.java
Reason: overwrite has been broken. Overwrite hasn't appeared to have worked since at least 2.0 or perhaps further back.
Both the createDirectory and createFile calls in MigrateDefinition is not overwriting version.
Thus, retrying is pointless because retries will always fail with the message of being unable to overwrite.
=> Make DistributedCp/Mv not retry

pom.xml
1.6.1 relies on javassist 3.18 which is prone to the following bug: https://issues.redhat.com/browse/JASSIST-220?_sscc=t
=> Upgrade powermock from 1.6.1 to 1.6.2

core/client/fs/src/main/java/alluxio/client/metrics/MetricsHeartbeatContext.java, core/common/src/main/java/alluxio/conf/PropertyKey.java
This PR reduces the client heartbeat frequency by enlarging the heartbeat interval and add the initial delay.
To prevent incomplete client metrics for short-life clients, add the last heartbeat when close the last FileSystemContext with the same connect details.
=> Reduce client heartbeat frequency and heartbeat on context close

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java, core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java, core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreOptions.java, core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java, core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java, core/common/src/main/java/alluxio/conf/PropertyKey.java
Fixed index out of bound exception for cache manager locking.
Fixed exception when reading from stream with oversized buffer.
Added properties to configure page store directory and type.
=> Fix some bugs and add new properties for client-side cache

job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java
MigrateDefinition deletes the final directory in a different code path then all the other files and directories, make sure that is also deleted unchecked.
=> Delete the final directory in deleteSource of Migrate as unchecked

pom.xml
repo.spring.io recently started enforcing the use of `https` to connect and download artifacts. This change updates the root POM to reflect this requirement. Builds off of a fresh maven cache should now succeed.
=> Update spring maven repository to use HTTPS

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java, core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java, core/common/src/main/java/alluxio/metrics/ClientMetrics.java
Adds 3 metrics
number of bytes read from local cache
number of bytes read from external store
number of bytes requested from external store (may be less than bytes read because we read full pages)
=> Add metrics for cache hit/miss

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java, core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStore.java, core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java, core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreTest.java
Add a new offset read API on page store to eliminate buffer copy in `LocalCacheManager`.
=> Optimize offset read from page store

job/server/src/main/java/alluxio/master/job/workflow/WorkflowTracker.java, job/server/src/test/java/alluxio/master/job/JobMasterTest.java
For errors like ResourceExhaustedException and JobDoesNotExistException, the WorkflowTracker will only stamp Status.FAILED from a level above.
Reproduction: (see Test)
mJobMaster.run(new Composite..([new Composite(new DummyJob....
Expected:
Name: Composite
..
Status: FAILED
Message: The job definition for config bleh does not exist
Task 0
Name: Composite
...
Status: FAILED
Message: The job definition for config bleh does not exist
Actual:
Name: Composite
..
Status: FAILED
Message: The job definition for config bleh does not exist
Task 0
Name: Composite
...
Status: RUNNING
=> Fail nested jobs correctly in all of the jobs for JobMaster failures

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
This allows users to integrate client metrics with 3rd party metrics tools (similar to the servers)
=> Start sinks on client when client metrics are enabled

job/server/src/main/java/alluxio/worker/job/task/TaskExecutor.java, job/server/src/main/java/alluxio/worker/job/task/TaskExecutorManager.java, job/server/src/test/java/alluxio/worker/job/task/TaskExecutorTest.java
JobMaster.cancel() previously cleaned up properly only if the JobWorker
thread was actually executing the task. But in reality, almost all of
the tasks are in the executor queue.
pr-link: Alluxio/alluxio#10634
change-id: cid-a9af8ad612139b0540e8de972380f8f61c00bcb1
=> Fix cancel 2.1 (Port #10634 to branch-2.1)

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
When client-side configuration is wrong or missing, client heartbeat may have connection issues (ie due to security settings).  This PR adds client side load configuration before initializign metrics heartbeat to solve the issue.
=> Add client config load before initializing metrics heartbeat

core/common/src/main/java/alluxio/cli/AbstractShell.java, core/common/src/main/java/alluxio/cli/Command.java, shell/src/main/java/alluxio/cli/fs/command/CopyFromLocalCommand.java
`copyFromLocal`command creates its own fs-context but it never gets closed. This fix lays necessary plumbing and properly closes the command.
=> Fix client leaks of copyFromLocal command

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/test/java/alluxio/master/file/PersistenceTest.java
We used to update fingerprint for persisted files during worker heartbeat but that code is deprecated in favor of job based persistence. This fix add it to the persist job success handler to add the fingerprints to persisted files.
=> Fix fingerprints for persisted files

integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-statefulset.yaml.template
The secret volume mount is not indented uniformly b/w journal and secret volume mounts.
=> Fix K8s template indentation for secret volumes

docs/en/operation/Performance-Tuning.md
As part of some testing in a single node environment, I observed that for that the HDFS client become unresponsive when alluxio.worker.ufs.instream.cache.max.size >> dfs.datanode.handler.count. This PR adds a suggestion to tune the parameter based on HDFS config.
=> [DOCFIX] Add performance tuning doc for ufs instream

core/client/fs/src/main/java/alluxio/client/block/stream/LocalFileDataWriter.java, core/common/src/main/java/alluxio/metrics/ClientMetrics.java, core/common/src/main/java/alluxio/wire/MasterWebUIMetrics.java, core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java, docs/en/operation/Metrics-System.md, webui/master/src/containers/pages/Metrics/Metrics.tsx, webui/master/src/containers/pages/Metrics/__snapshots__/Metrics.test.tsx.snap, webui/master/src/store/metrics/reducer.tsx, webui/master/src/store/metrics/types.tsx
Add `ClientMetrics.BYTES_WRITTEN_LOCAL`
Modify master Web UI metrics `Local Alluxio (Short-circuit) Read` to use `cluster.BYTES_READ_LOCAL` and `Local Alluxio (Short-circuit) Write` to use `cluster.BYTES_WRITTEN_LOCAL`
Improve metrics system docs to include more worker metrics and have detailed description of web ui metrics.
=> Improve Metrics System docs and add description for web UI metrics

shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
Hypothetical Environment:
3 nodes, each with a job worker and a worker.
Suppose a file x.txt has 10 blocks to load but one of its blocks
(**Block 1**) is in the middle of being read on (**Worker A**),
Attempting to load this file creates 10 tasks and the task to load
**Block 1** is assigned to be in **Worker A**.
Previous behavior:
The task in an attempt to load **Block 1** in **Worker A** fails. This
fails the job but the other 9 tasks are still continuing. The client
notices the failure and triggers a retry. Retry notices that none of the
10 blocks are still loaded yet and shuffles the location of where they
are getting loaded.
New behavior:
The task in an attempt to load **Block 1** in **Worker A** fails. This
fails the job but the other 9 tasks are still continuing. The client
waits …
=> Port changes of [#10704] to branch-2.1

core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManager.java, core/server/worker/src/main/java/alluxio/worker/block/allocator/GreedyAllocator.java, core/server/worker/src/main/java/alluxio/worker/block/allocator/MaxFreeAllocator.java, core/server/worker/src/main/java/alluxio/worker/block/allocator/RoundRobinAllocator.java, core/server/worker/src/main/java/alluxio/worker/block/evictor/AbstractEvictor.java, core/server/worker/src/main/java/alluxio/worker/block/evictor/EvictorUtils.java, core/server/worker/src/main/java/alluxio/worker/block/evictor/GreedyEvictor.java, core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTier.java, core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTierAllocatorView.java, core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTierEvictorView.java, core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTierView.java, core/server/worker/src/test/java/alluxio/worker/block/TieredBlockStoreTest.java, core/server/worker/src/test/java/alluxio/worker/block/allocator/AllocatorContractTest.java, core/server/worker/src/test/java/alluxio/worker/block/evictor/EvictorContractTest.java, core/server/worker/src/test/java/alluxio/worker/block/meta/StorageTierTest.java, core/server/worker/src/test/java/alluxio/worker/block/meta/StorageTierViewTest.java
Worker uses directory index to find a directory in a tier. When a disk goes down we detect that and remove the dir, which mess up the index. To avoid the confusion, this fix makes the index absolute in the tier so removing any dir does not alter its index. As a side effect, `getDir(index)` can return null if the corresponding directory is removed. Evictors and Allocators have been updated to handle the null values.
=> Fix directory index after disk failure

core/server/common/src/main/java/alluxio/worker/AbstractWorker.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorker.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java, core/server/worker/src/main/java/alluxio/worker/SessionCleaner.java, core/server/worker/src/main/java/alluxio/worker/block/AsyncBlockRemover.java, core/server/worker/src/main/java/alluxio/worker/block/BlockMasterSync.java, core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java, job/server/src/main/java/alluxio/master/AlluxioJobMaster.java, job/server/src/main/java/alluxio/worker/AlluxioJobWorker.java, job/server/src/main/java/alluxio/worker/JobWorker.java
There are 3 main categories of fixes:
- Register shutdown hooks for all processes
- Make abstract worker implementation restartable in compliance with `Server` interface
- Fix various resource disposal issues
Thse all together will prevent many gRPC level warnings.
=> Stop Alluxio processes properly

examples/src/main/java/alluxio/examples/UnderFileSystemCommonOperations.java
Deleting directory in object UFS is eventual consistent. Use the new API in contract test that properly retries delete for object UFS.
=> Fix eventual consistency in contract test

job/common/src/main/java/alluxio/job/plan/transform/HiveConstants.java, job/common/src/test/java/alluxio/job/plan/transform/HiveConstantsTest.java, job/server/src/main/java/alluxio/job/plan/transform/format/csv/CsvRow.java, job/server/src/main/java/alluxio/job/plan/transform/format/csv/CsvSchema.java
Because of types like char(20) and what not, we use startswith instead of equals for some cases and this also prevents us from using switch statements. Standardize the types before checking to enable us to use switch statements.
=> Refactor HiveConstant type checking

core/common/src/main/java/alluxio/wire/WorkerWebUIMetrics.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java, webui/worker/src/store/metrics/reducer.tsx, webui/worker/src/store/metrics/types.tsx
The dividend of logical operation and rpc operation should only exist in the master web metrics. For worker web metric, normal operation is enough.
Removed the getRpcInvocationMetrics.
=> Remove unneeded logic in worker web

webui/common/package.json, webui/common/src/constants/scss/_themeVariables.scss, webui/common/src/index.tsx, webui/master/package.json, webui/master/src/index.tsx, webui/npm-shrinkwrap.json, webui/worker/package.json, webui/worker/src/index.tsx
The reason I'm proposing replacing SCP with AP is because there is a
bug in  firefox and/or MacOS which causes this  font to render
incorrectly.
See:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1534503
- https://bugzilla.mozilla.org/show_bug.cgi?id=1520157
Anonymous Pro is a bit more lightweight and has at least  been recently
updated  by its maintainers (1.44.0 was 3 months ago). SCP is definitely
more ubiquitous  and well-maintained but I would rather have a font that
works everywhere. As an added bonus, this font is *much* more
lightweight than SCP.
Additionally, it seems the maintainers of the project have no desire to
address or look into what triggered the regression:
https://github.com/adobe-fonts/source-code-pro/issues/217
=> Replace Source Code Pro with Anonymous Pro font

docs/_config.yml, docs/_layouts/global.html, docs/cn/contributor/Building-Alluxio-From-Source.md, docs/cn/deploy/Running-Alluxio-Locally.md, docs/cn/deploy/Running-Alluxio-On-Docker.md, docs/cn/overview/Getting-Started.md, docs/cn/ufs/GCS.md, docs/cn/ufs/S3.md, docs/en/cloud/AWS-EMR.md, docs/en/cloud/Google-Dataproc.md, docs/en/contributor/Building-Alluxio-From-Source.md, docs/en/core-services/Unified-Namespace.md, docs/en/deploy/Running-Alluxio-Locally.md, docs/en/deploy/Running-Alluxio-On-a-Cluster.md, docs/en/overview/Getting-Started.md, docs/en/ufs/HDFS.md, docs/en/ufs/S3.md
Update references to ALLUXIO_RELEASED_VERSION to be ALLUXIO_VERSION_STRING
Remove the even more obscure ALLUXIO_MASTER_VERSION_SHORT
Update ALLUXIO_MAJOR_VERSION on master to be "edge"
The concept of "most recently release version" changes as patches are released, but this update is not reflected outside of the branch where the patch was cut from
Instead of trying to update ALLUXIO_RELEASED_VERSION across multiple branches, use ALLUXIO_VERSION_STRING which will be correct in all branches except for master.
In the case of master, which is currently at 2.2.0-SNAPSHOT, it is likely there will be invalid references (ex. <version>2.2.0-SNAPSHOT</version> in the maven dependency declaration).
But I find this is to be more acceptable since it is a development branch.
In summary, this PR …
=> [DOCFIX] Remove ALLUXIO_RELEASED_VERSION from docs/_config.yml

core/transport/pom.xml, integration/checker/pom.xml, pom.xml, table/server/underdb/hive/pom.xml
Use maven 3.6+ with JDK 11 and the flag -Pjava11 to enable the Java 11
profile. However, maven should activate the profile by default if it detects
your default is JDK 11
There is a long list of changes and incompatibilities between Java 8
and Java 11, only a few affected us for the most part though.
- The `jdk.tools` system dependency which is transitively depended
upon by `org.apache.hbase:hbase-annotations` no longer exists in
Java 11, so we exclude `jdk.tools:jdk.tools` throughout the codebase.
- The javax annotations are no longer a part of the JDK distribution,
but they are available as a backwards-compatible maven dependency
so we add that if we're compiling with Java 11.
- The swagger maven plugin which is used to generate the REST API
docs depends on a JAXB class which isn't a …
=> Support compiling with Java 11

underfs/cos/src/main/java/alluxio/underfs/cos/COSUnderFileSystem.java, underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoUnderFileSystem.java, underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
Fix https://github.com/Alluxio/alluxio/issues/10842 but not only in OSS but a few other under storage to leave the server logs cleaner.
It is unnecessary to log again on non-existence of an object as the null value is already indicating the scenario.  Besides, the non-existence may be expected (e.g. when called from `deleteFileIfExists`
=> Remove unnecessary logging in under storage

shaded/client/pom.xml
In LoginModuleConfigurationUtils.java, we use `com.ibm.security` for login in IBM java. This package should be unshaded in Alluxio client jar to avoid errors like `Unable to find LoginModule class: alluxio.shaded.client.com.ibm.security.auth.module.LinuxLoginModule`
=> Exclude com.ibm package in shaded client jar to support ibm jvm

core/common/src/test/java/alluxio/AlluxioTestDirectory.java, core/server/common/src/main/java/alluxio/master/journal/JournalEntryAssociation.java, core/server/common/src/test/java/alluxio/master/journal/JournalEntryAssociationTest.java, core/transport/src/grpc/table/table_master.proto, core/transport/src/main/java/alluxio/grpc/MetricValue.java, core/transport/src/main/java/alluxio/grpc/table/Partition.java, core/transport/src/main/java/alluxio/grpc/table/PartitionOrBuilder.java, core/transport/src/main/java/alluxio/grpc/table/TableInfo.java, core/transport/src/main/java/alluxio/grpc/table/TableInfoOrBuilder.java, core/transport/src/main/java/alluxio/grpc/table/TableMasterProto.java, core/transport/src/main/java/alluxio/proto/journal/Journal.java, core/transport/src/main/java/alluxio/proto/journal/Table.java, core/transport/src/proto/journal/journal.proto, core/transport/src/proto/journal/table.proto, integration/docker/hms/Dockerfile, integration/docker/hms/README.md, integration/docker/hms/entrypoint.sh, integration/docker/hms/initialize.sh, table/server/common/src/main/java/alluxio/table/common/udb/UdbTable.java, table/server/master/src/main/java/alluxio/master/table/AlluxioCatalog.java, table/server/master/src/main/java/alluxio/master/table/Database.java, table/server/master/src/main/java/alluxio/master/table/Partition.java, table/server/master/src/main/java/alluxio/master/table/Table.java, table/server/master/src/test/java/alluxio/master/table/AlluxioCatalogTest.java, table/server/master/src/test/java/alluxio/master/table/TestUdbTable.java, table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java, table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveTable.java, tests/pom.xml, tests/src/test/java/alluxio/master/table/TableIntegrationTest.java
This allows the sync command to update the metadata of existing partitions, not only new partitions. This means, if an existing partition is updated in hive, it will be detected and updated during a sync command.
For this functionality, table version numbers and partition version numbers have been added. The concurrency model was also updated for these changes. It is an optimistic concurrency control model, where multiple updates can be concurrent, but only 1 will succeed in updating the metadata to the next version.
=> Update table metadata from changes in UDB

job/server/src/main/java/alluxio/job/plan/transform/format/parquet/ParquetWriter.java
The default row group size for Parquet is 128MB but for the purpose of querying, official Parquet documentation recommends large row groups https://parquet.apache.org/documentation/latest/.
Though for the purpose of performing potentially multiple transformations and ones that require merging them in specific order, it is much better to have much smaller row group size to reduce memory footprint.
=> Add row group size option to ParquetWriter.create

core/server/worker/src/main/java/alluxio/worker/block/meta/StorageDir.java, core/server/worker/src/main/java/alluxio/worker/block/meta/StorageTier.java
Filter out tmp blocks dir so worker doesn't throw error on start
=> Skip logging error on worker tmp folder

core/common/src/main/java/alluxio/util/CommonUtils.java, table/server/master/src/main/java/alluxio/master/table/AlluxioCatalog.java, table/server/master/src/main/java/alluxio/master/table/Database.java, table/server/master/src/main/java/alluxio/master/table/DefaultTableMaster.java, table/server/master/src/test/java/alluxio/master/table/AlluxioCatalogTest.java, table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java, table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveClientPool.java, tests/src/test/java/alluxio/master/table/TableIntegrationTest.java
This change sync a table in a thread, instead of sequentially. This should reduce the response times of databases with a large number of tables.
=> Enable parallel udb sync

core/client/fs/src/test/java/alluxio/client/metrics/MetricsHeartbeatContextTest.java, core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
The test currently runs for almost 3 minutes due to client retry
configuration. This change makes the PollingMasterInquireClient
respect the USER_RPC_RETRY* configuration values which
subsequently speeds up the test from ~3min to ~5sec
=> Improve performance of MetricsHeartbeatContextTest

conf/metrics.properties.template, core/common/src/main/java/alluxio/metrics/sink/JmxSink.java
Previously our domain was always `metrics` which is not very helpful, it now defaults to `org.alluxio`
=> Allow domain to be configured in jmx

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java, core/common/src/main/java/alluxio/metrics/Metric.java, core/common/src/main/java/alluxio/metrics/MetricKey.java, core/common/src/main/java/alluxio/metrics/MetricsSystem.java, core/common/src/test/java/alluxio/metrics/MetricTest.java, core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, core/server/master/src/main/java/alluxio/master/metrics/DefaultMetricsMaster.java, core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java, core/server/master/src/test/java/alluxio/master/metrics/MetricsMasterTest.java, core/server/master/src/test/java/alluxio/master/metrics/MetricsStoreTest.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java, tests/src/test/java/alluxio/client/cli/fsadmin/command/MetricsCommandIntegrationTest.java
Change to store the cluster counter value directly instead of remembering each counter reported by client or worker.
This is helpful: (1) to reduce the space needed to store reported metrics (2) because counter value is historical summarized value. There is no need to delete the orphaned counter value.
For all other metrics, we keep the original way: store all the original reported metrics and update the cluster metric value periodically. 
But to make it more accurate, a delete orphaned metrics logic is added. Metrics reported by worker/client which hasn't reported for a long period of time (configurable) will be deleted. This can help us to get more accurate throughput value. worker/client report throughput as the last 1 minute rate which does not make sense if it's orphaned.
=> Increment cluster counter and delete orphaned meter in MetricsStore

conf/log4j.properties
InternalParquetRecordReader/Writer gets very noisy when row group size of the parquet file writing/reading is small.
=> Set default logger level for InternalParquetRecordReader/Writer to WARN

core/common/src/main/java/alluxio/conf/PropertyKey.java, pom.xml
We don't support maprfs:// any more. This PR deletes some remaining
parts that still reference the dependency in the codebase.
=> Remove remnants of MapR FS

core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java, core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java, core/client/fs/src/main/java/alluxio/client/file/options/InStreamOptions.java, core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/underfs/options/OpenOptions.java, core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java, core/server/worker/src/main/java/alluxio/worker/block/BlockWorker.java, core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java, core/server/worker/src/main/java/alluxio/worker/block/UfsInputStreamManager.java, core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java, core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java, core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java, core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadRequest.java, core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockReaderTest.java, core/transport/src/grpc/block_worker.proto, core/transport/src/main/java/alluxio/grpc/BlockWorkerProto.java, core/transport/src/main/java/alluxio/grpc/ReadRequest.java, core/transport/src/main/java/alluxio/grpc/ReadRequestOrBuilder.java, tests/src/test/java/alluxio/client/fs/FileInStreamIntegrationTest.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileInputStream.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
This PR is a follow up to https://github.com/Alluxio/alluxio/pull/10763.
When the client buffer size is large ( > 2MB) and reads are guaranteed to be somewhat sequential, the `pread` API to HDFS is not as efficient as simple `read`. We introduce a heuristic to choose which API to use.
=> Choose HDFS read API based on Client buffer size

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java, core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java, core/client/fs/src/main/java/alluxio/client/file/cache/PageId.java, core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStore.java, core/client/fs/src/test/java/alluxio/client/file/cache/DefaultMetaStoreTest.java, core/client/fs/src/test/java/alluxio/client/file/cache/LRUCacheEvictorTest.java, core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java, core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java, core/client/fs/src/test/java/alluxio/client/file/cache/store/LocalPageStoreTest.java, core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreTest.java, core/common/src/main/java/alluxio/client/file/URIStatus.java, core/common/src/main/java/alluxio/wire/FileInfo.java, tests/src/test/java/alluxio/client/fs/LocalCacheManagerIntegrationTest.java
This allows certain client filesystem to use UUID as file id without worrying about collision.
=> Refactor the client cache to use string file id

core/common/src/main/java/alluxio/AbstractClient.java, core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
We recently moved relogin early before the retry loop to fix polling master client authentication. Now we start to see random unauthenticated exception during the relogin time. Since the polling master client does not really need the authentication, disabling it and move the relogin back inside the retry. The unauthenticated exception can no longer be observed after this change.
=> Fix unauthenticated exception during relogin

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java, core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncer.java
Fixes: https://github.com/Alluxio/alluxio/issues/10815
When stopSync is called, the thread performing the initial scan handles interrupt to return early. A full sync on a very large directory can take a long time to finish, this change enables us to cancel a full sync after partial completion.
=> Terminate initial scan on stop active sync

underfs/wasb/src/main/java/alluxio/underfs/wasb/WasbUnderFileSystem.java, underfs/wasb/src/main/java/alluxio/underfs/wasb/WasbUnderFileSystemFactory.java, underfs/wasb/src/test/java/alluxio/underfs/wasb/WasbUnderFileSystemFactoryTest.java
Azure Blob Storage over https is currently unsupported by the `wasb` underfile system; however, the version of [azure-hadoop ](https://hadoop.apache.org/docs/r2.7.3/hadoop-azure/index.html) used in the underfs supports the https scheme (wasbs). 
This PR merely changes the accepted `SCHEME` from `wasb://` to accepted `SCHEMES` including both `wasb://` and `wasbs://`
`wasbs` support was tested by running `runUfsTests` in a k8s installation. All tests were passed successfully.
=> Add Wasbs support to Wasb Underfs

core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStore.java, shaded/client/pom.xml
Tested with my local build, client jar size reduced from 40MB to 26MB
=> Exclude dependency on rocksdb from client jar

core/server/worker/src/main/java/alluxio/worker/SessionCleaner.java
To fix worker shutdown logging every time:
2020-02-13 22:31:55,587 WARN  SessionCleaner - sleep interrupted
java.lang.InterruptedException: sleep interrupted
........
=> Exit worker session-cleaner without interrupt message

core/server/master/src/main/java/alluxio/master/meta/UpdateCheck.java, core/server/master/src/test/java/alluxio/master/meta/UpdateCheckTest.java
Avoid NPE thrown in UpdateCheckTest by mocking all the methods called.
=> Fix UpdateCheckTest

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/DefaultPermissionChecker.java, core/server/master/src/main/java/alluxio/master/file/PermissionChecker.java, core/server/master/src/main/java/alluxio/master/file/activesync/ActiveSyncManager.java, docs/en/core-services/Unified-Namespace.md
A full scan for active sync acquires a write lock on the syncPoint which prevents the permission check for stopSync to proceed. This PR skips the read lock needed on the inode for the permission check if the user is a super user. This allows us to terminate a long-running full scan early.
=> Allow superuser to stopActiveSync w/o a lock

job/server/src/main/java/alluxio/master/job/plan/PlanCoordinator.java
Many jobs in SelectExecutors has an implementation that always prioritizes the first worker in the jobWorkerInfoList. Avoid this by creating a new list and always shuffling that new list for its JobDefinitions
=> Reorder (shuffle) workers info list before passing on to the jobs

table/server/master/src/main/java/alluxio/master/table/AlluxioCatalog.java
This code was not applying detachDatabase when .sync() crashed.
Fixes a regression from: #10897
=> Fix speedcore sync error behavior on attach

core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java, core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClientPool.java, core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
Currently only master client does relogin when needed. There is a slight chance that worker client will run into credential expiration therefore the same relogin logic should be also in the worker client. In the future we should unify the two clients.
=> Add worker client relogin

job/server/src/main/java/alluxio/job/plan/transform/CompactDefinition.java, job/server/src/test/java/alluxio/job/plan/transform/CompactDefinitionSelectExecutorsTest.java
The compression ratio for the compact job was not applied correctly, resulting in unexpected file sizes.
=> Fix coalesce max files behavior

core/common/src/main/java/alluxio/shell/ScpCommand.java, shell/src/main/java/alluxio/cli/bundler/CollectInfo.java, shell/src/main/java/alluxio/cli/bundler/command/CollectEnvCommand.java, shell/src/main/java/alluxio/cli/bundler/command/CollectMetricsCommand.java
Various improvements to `collectInfo` command:
1. scp now doesn't hardcode "localhost". Specifying `localhost` works on Mac but not on a CentOS machine.
2. If the command is invalid like `alluxio collectInfo bar /dir`, early reject before distributing the command and find out it's invalid locally.
3. Catch metrics collection errors when metrics are unavailable, instead of failing the command and subsequently skips collecting tarballs.
4. Misc bash command fixes.
=> Improve collectInfo command

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
#10960 claims that the file is unused. 
But the file is currently being copied over in the tarball. Remove this dependency.
=> Fix generate tarball

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/main/java/alluxio/client/metrics/ClientMasterSync.java, core/client/fs/src/main/java/alluxio/client/metrics/MetricsHeartbeatContext.java
When client metrics is enabled, the master starts up takes four more minutes. The four more minutes are taken by `PollingMasterInquireClient.getPrimaryRpcAddress`  in `FileSystemContext.initContext`. `getPrimaryRpcAddress()` retries 44 times and takes 2 minutes each call which heavily delays the master starts up. The primary rpc address is used for load configuration from the leading master and initialize metrics heartbeat.
This PR put the load configuration logics in the metrics heartbeat thread, so that client metrics logic in FileSystemContext will not block actual operations.
=> Make the addition of client metrics heartbeats asynchronous

integration/kubernetes/alluxio-fuse-client.yaml.template, integration/kubernetes/alluxio-fuse.yaml.template, integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/Chart.yaml, integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl, integration/kubernetes/helm-chart/alluxio/templates/job/format-journal-job.yaml, integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml, integration/kubernetes/helm-chart/alluxio/values.yaml, integration/kubernetes/multiMaster-embeddedJournal/alluxio-configmap.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/alluxio-configmap.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-localJournal/alluxio-configmap.yaml.template, integration/kubernetes/singleMaster-localJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/singleMaster-localJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/singleMaster-localJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-localJournal/worker/alluxio-worker-daemonset.yaml.template
After PR #10686 we use PVs for master journals created by `volumeClaimTemplates`. This changed how we should format journals. Now each master has its own journal PV.
https://github.com/Alluxio/alluxio/pull/10686
In Alluxio docker image there's no SSH capability (https://github.com/Alluxio/alluxio/issues/10945), so commands like `alluxio formatMasters` cannot work. We need to invoke `formatJournal` directly on each master.
Previously we use a Job to invoke `formatMasters` when there's only master (in HA mode the journal volumes are emptyDir), now we need multiple Jobs to each handle one master in HA mode.
=> Fix K8s format journal in HA mode

core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java, core/client/fs/src/main/java/alluxio/client/file/AlluxioFileOutStream.java, core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/test/java/alluxio/client/block/AlluxioBlockStoreTest.java, core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java, core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java, core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java, job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java, job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java, job/server/src/main/java/alluxio/job/plan/persist/PersistDefinition.java, job/server/src/main/java/alluxio/job/plan/replicate/EvictDefinition.java, job/server/src/main/java/alluxio/job/plan/replicate/MoveDefinition.java, job/server/src/main/java/alluxio/job/util/JobUtils.java, job/server/src/test/java/alluxio/job/plan/load/LoadDefinitionTest.java, job/server/src/test/java/alluxio/job/plan/migrate/MigrateDefinitionSelectExecutorsTest.java, job/server/src/test/java/alluxio/job/plan/replicate/ReplicateDefinitionTest.java, shell/src/main/java/alluxio/cli/LogLevel.java, shell/src/main/java/alluxio/cli/fsadmin/metrics/ClearCommand.java, tests/src/test/java/alluxio/server/ft/MasterFaultToleranceIntegrationTest.java, tests/src/test/java/alluxio/server/ft/MultiWorkerIntegrationTest.java
`AlluxioBlockStore` was originally a singleton before 2.0, so `AlluxioBlockStore.getWorkerInfoList` can keep worker info cached across Input and Output Streams. However after 2.0, `AlluxioBlockStore` becomes instance class and the cached worker info list can only benefit its owner stream, causing performance issues due to too many unnecessary client-master RPCs when reading / writing many small files, as described https://github.com/Alluxio/alluxio/issues/10959
This PR moves `getWorkerInfoList` and `getAllWorkers` to `FileSystemContext` as the shared state.
This PR also changes the job servers to use cached worker info list instead of keep getting the most updated worker info list.
Fix #10959  and close #9977
=> Reduce getWorkerInfoList RPCs on client and job servers

core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java, core/common/src/main/java/alluxio/conf/PropertyKey.java
Some applications (e.g. Presto) require the block locations not empty otherwise the jobs will fail. When the path doesn't have alluxio locations or ufs locations, always return the full worker locations.
=> Enable location fallback by default

integration/kubernetes/alluxio-fuse-client.yaml.template, integration/kubernetes/alluxio-fuse.yaml.template, integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/Chart.yaml, integration/kubernetes/helm-chart/alluxio/templates/fuse/client-daemonset.yaml, integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml, integration/kubernetes/helm-chart/alluxio/templates/job/format-journal-job.yaml, integration/kubernetes/helm-chart/alluxio/values.yaml, integration/kubernetes/helm-generate.sh, integration/kubernetes/multiMaster-embeddedJournal/alluxio-configmap.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/alluxio-configmap.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-localJournal/alluxio-configmap.yaml.template, integration/kubernetes/singleMaster-localJournal/job/alluxio-format-journal-job.yaml.template, integration/kubernetes/singleMaster-localJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/singleMaster-localJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-localJournal/worker/alluxio-worker-daemonset.yaml.template
This resolves https://github.com/Alluxio/alluxio/issues/10321
Added switched for fuse/fuse-client/jobs. The templates will be turned to empty on Helm deployment and generated for `kubectl` manual control.
=> Remove extra resources created by Helm deployment

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java, core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java
This will provide throughput numbers as well.
=> Use meter for io metrics in client cache

core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStoreOptions.java, core/client/fs/src/test/java/alluxio/client/file/cache/store/LocalPageStoreTest.java, core/common/src/main/java/alluxio/conf/PropertyKey.java
Adds a new configuration property that allows users to set the number of buckets to place files in the local page cache. Older local page caches are not compatible. Changing the number of buckets will invalidate older caches.
=> Add buckets for client cache on local page store

core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java, core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreTest.java
The file id in the `LocalPageStore` accepts any string. This fix updates the regex for extracting the ids from path so it accepts more than just digits.
=> Fix path pattern in local page store

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java, core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java, core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java, core/common/src/main/java/alluxio/metrics/MetricKey.java
Adds page eviction rate, cache hit rate, space utilization, and error counts.
=> Add additional metrics for client cache

shell/pom.xml, shell/src/main/java/alluxio/cli/fs/command/DuCommand.java, shell/src/test/java/alluxio/cli/fs/command/DuCommandTest.java
Previously, we were always using the "InMemoryPercentage" to calculate the
total amount in Alluxio. This is incorrect. We will now use the proper value
=> Fix "In Alluxio" calculation for DuCommand

shell/src/main/java/alluxio/cli/bundler/CollectInfo.java
This is to replace #11035 as it was based on 2.2 incorrectly.
This separates the code change from doc change in favor of #10926 
Improves description of `collectInfo` command, including a better usage description and mentioning credential risks.
=> Improve collectInfo command description

core/server/master/src/main/java/alluxio/master/block/BlockMaster.java, core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
A loading cache is used for caching worker info list results. In this way, the overhead to construct worker info list is reduced but the worker info list result is not up to date. 
Add a getWorkerAddresses() method which returns the most up-to-date live worker addresses.
Add an invalidate cache in registering worker to make sure getWorkerInfoList() call catchs up with the worker changes.
=> Add getWorkerAddresses and invalidate cache when registering worker

core/server/common/src/main/java/alluxio/web/WebServer.java
Disable these methods on REST services since they're not commonly used and they flag in network vulnerability scans
=> Disable TRACE and OPTIONS on REST services

core/server/master/src/main/java/alluxio/master/meta/MetaMasterFactory.java
All master factories currently return their respective implementations
of the Master interface. MetaMasterFactory only returns a Master.
This is a small PR to update the class to be the same as the other
implementations
=> Return MetaMaster from MetaMasterFactory

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/util/ConfigurationUtils.java, tests/src/test/java/alluxio/server/configuration/ConfigCheckerIntegrationTest.java
This PR aims to fix the configuration check in the Alluxio UI when running locally and all values are not configured except for `alluxio.master.hostname` set to `localhost`
By default this should be passing, or else the user may think they have configured something incorrectly.
There are two main changes.
1. Fix a failing check from a PK with `ConsistencyCheckLevel.ENFORCE` that gets it's trailing spaces trimmed when the pk is sent over the wire. I just removed the extra trailing spaces as the usage didn't seem to require it.
2. Use the resolved value for the PK rather than the raw value. There are many PKs with "warnings" because the check on the master uses the resolved value rather than the raw value sent from the other masters/workers. I don't really see a good use for using the raw …
=> Fix config check with default values

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Previously, when a sync is canceled on the last directory to be synced, no messages are logged. Now it will be logged.
=> Log a cancelled message when sync is cancelled due to exception

docs/en/compute/Tensorflow.md
Added a small note for Tensorflow 1.15. Using [Tensorflow 2.1.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0) will cause some minor issues when trying to run `classify_image.py`. Users would have to manually tweak the py file to get it to work.
=> [DOCFIX] Update Tensorflow doc

core/common/src/test/java/alluxio/ConfigurationTestUtils.java, core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java, minicluster/src/main/java/alluxio/master/AbstractLocalAlluxioCluster.java, tests/src/test/java/alluxio/testutils/LocalAlluxioClusterResource.java
Instead of relying on waiting for lost worker detection, force the workers to be lost.
=> Improve how tests handle restarting workers

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java, integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
With this PR, after setting `log4j.logger.alluxio.fuse.AlluxioFuseFileSystem=DEBUG` in `conf/log4j.properties`, one can find debug logs on FUSE operation in `logs/fuse.log`:
```
2020-03-03 14:33:35,129 DEBUG AlluxioFuseFileSystem - Enter: chmod(path=/aaa,mode=100644)
2020-03-03 14:33:35,131 DEBUG AlluxioFuseFileSystem - Exit (0): chmod(path=/aaa,mode=100644) in 2 ms
2020-03-03 14:33:35,132 DEBUG AlluxioFuseFileSystem - Enter: getattr(path=/aaa)
2020-03-03 14:33:35,135 DEBUG AlluxioFuseFileSystem - Exit (0): getattr(path=/aaa) in 3 ms
2020-03-03 14:33:35,135 DEBUG AlluxioFuseFileSystem - Enter: getattr(path=/._aaa)
2020-03-03 14:33:35,136 DEBUG AlluxioFuseFileSystem - Failed to get info of /._aaa, path does not exist or is invalid
2020-03-03 14:33:35,136 DEBUG AlluxioFuseFileSystem - Exit …
```
=> Add debug logging facilities for fuse

docs/en/operation/Troubleshooting.md, shell/src/main/java/alluxio/cli/bundler/CollectInfo.java
This adds `collectInfo` command to `Troubleshooting.md`.
The improvements to command printouts are addressed in #11037
=> [DOCFIX] Add collectInfo command to doc

tests/src/test/java/alluxio/client/cli/fs/command/CpCommandIntegrationTest.java
This test stops workers, so caching the worker list in the master or client is not desired.
=> Remove flakiness in CpCommandIntegrationTest

job/server/src/main/java/alluxio/master/job/workflow/WorkflowTracker.java, job/server/src/test/java/alluxio/master/job/workflow/WorkflowTrackerTest.java
Resolves #11118 
getStatus of a workflow job that contains no children crashed because it was expecting the list of children to be non-null. This fixes resolves it by making sure that the list is an empty list instead of null.
=> Complete Job Workflows without any children

integration/pom.xml
By excluding checker module which depends on yarn.
=> Fix Hadoop 1 build

core/common/src/main/java/alluxio/AbstractClient.java, core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/test/java/alluxio/AbstractClientTest.java, integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java, integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
by setting two new properties
```
alluxio.user.logging.threshold=2ms
alluxio.fuse.logging.threshold=2ms
```
Fuse or client-side RPC calls taking too long will be logged in WARN level like the following:
```
2020-03-08 23:40:44,374 WARN  BlockMasterClient - GetBlockMasterInfo(fields=[USED_BYTES, FREE_BYTES, CAPACITY_BYTES]) returned BlockMasterInfo{capacityBytes=11453246122, capacityBytesOnTiers={}, freeBytes=11453237930, liveWorkerNum=0, lostWorkerNum=0, usedBytes=8192, usedBytesOnTiers={}} in 6 ms
2020-03-08 23:40:44,374 WARN  AlluxioFuseFileSystem - statfs(path=/) returned 0 in 6 ms
2020-03-08 23:40:44,381 WARN  BlockMasterClient - GetBlockMasterInfo(fields=[USED_BYTES, FREE_BYTES, CAPACITY_BYTES]) returned BlockMasterInfo{capacityBytes=11453246122, capacityBytesOnTiers={}, …
```
=> Add logging when RPC or Fuse calls too long

docs/en/operation/User-CLI.md, table/server/master/src/main/java/alluxio/master/table/AlluxioCatalog.java, table/server/master/src/main/java/alluxio/master/table/CatalogProperty.java, table/server/master/src/main/java/alluxio/master/table/Database.java, table/server/master/src/main/java/alluxio/master/table/DefaultTableMaster.java, table/server/master/src/test/java/alluxio/master/table/AlluxioCatalogTest.java, table/server/master/src/test/java/alluxio/master/table/TestDatabase.java
This adds a configuration parameter to specify the number of threads to use for syncing a database.
Fixes #11160
=> Make parallel sync threads configurable

table/server/underdb/hive/pom.xml
Protobuf should be excluded from the jar, since it is already in the core module.
Fixes #11164
=> Exclude protobuf from hive udb jar

core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
Our master/workers also use clients, and they should not use the client cache. This should be fixed in a different way when we can better scope our property keys and separate the client-side client from the server-side client.
=> Enable local cache only when the process type is client

docs/en/deploy/Running-Alluxio-On-Kubernetes.md, integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml, integration/kubernetes/helm-chart/alluxio/values.yaml, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-statefulset.yaml.template
This resolves point 3 in https://github.com/Alluxio/alluxio/issues/10253
Alluxio master Pods now use PVC for RocksDB as metastore instead of `emptyDir`.
=> Change Alluxio master in K8s to use PVC for RocksDB

docs/en/deploy/Running-Alluxio-On-Kubernetes.md, integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl, integration/kubernetes/helm-chart/alluxio/values.yaml
This resolves worker tiered storage using PVC, as point 4 in https://github.com/Alluxio/alluxio/issues/10253
The PVC will be satisfied by either `hostPath` or `local` under the hood to provide local storage to the worker.
=> Support PVC for worker tiered store in K8s

integration/kubernetes/alluxio-fuse-client.yaml.template, integration/kubernetes/alluxio-fuse.yaml.template, integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/Chart.yaml, integration/kubernetes/multiMaster-embeddedJournal/alluxio-configmap.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/multiMaster-embeddedJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/alluxio-configmap.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/worker/alluxio-worker-daemonset.yaml.template, integration/kubernetes/singleMaster-localJournal/alluxio-configmap.yaml.template, integration/kubernetes/singleMaster-localJournal/master/alluxio-master-service.yaml.template, integration/kubernetes/singleMaster-localJournal/master/alluxio-master-statefulset.yaml.template, integration/kubernetes/singleMaster-localJournal/worker/alluxio-worker-daemonset.yaml.template
This change bumps up the helm chart version after a series of K8s changes are in.
#11171 
#11173 
#11175
=> Upgrade Helm chart version

docs/_config.yml, docs/en/deploy/Running-Alluxio-On-Kubernetes.md
Helm charts are now published in a gs bucket.
=> [DOCFIX] Add K8s docs pointer to public helm repo

integration/pom.xml
Sometimes we still need to build Alluxio without specify a hadoop profile. Move fuse back to the default profile to ensure it is built without an explicit profile.
=> Move fuse module back to default profile

docs/cn/ufs/Azure-Blob-Store.md
Fix typo in https://github.com/Alluxio/alluxio/blob/master/docs/cn/ufs/Azure-Blob-Store.md to modify work from 'Alluxi' to 'Alluxio'.
=> Fix typo from 'Alluxi' to 'Alluxio'

core/server/master/src/main/java/alluxio/master/backup/BackupWorkerRole.java
Without this fix, a backup on the backup-worker could have finished without sending the last heart-beat, causing the leader to abort after a timeout.
=> Fix backup heartbeat termination

core/server/master/src/main/java/alluxio/master/meta/MetaMasterConfigurationServiceHandler.java
For configuration sync we request raw values from master, however the API implementation dropped the options.
=> Fix configuration not getting raw values

core/common/src/main/java/alluxio/conf/PropertyKey.java, underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
The `AmazonS3Client` default retry policy retries `AmazonClientException`s caused by an `IOException` such as when the server does not respond with `NoHttpResponseException`.
This PR adds the ability to override the AWS default count for stress tests in which we observe the following error intermittently:
```
com.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1201)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1147)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.j …
```
=> Add ability to override S3 max error retry count

core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java, core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClientPool.java, core/client/fs/src/main/java/alluxio/client/file/ConfigHashSync.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, tests/src/test/java/alluxio/client/fs/FileSystemContextReinitIntegrationTest.java
When a FileSystemContext is re-initialized, any acquired clients are expected to be released back into the same pool.
Before this change, it's possible for the following scenario to occur:
- A thread would acquire a block worker client from the pool map with key `A`.
- The context is re-initialized. All pools in the map are closed, the pool map is cleared
- Another thread acquires a block worker client with key `A` as well. This creates a new pool map entry with the same key `A`.
- The original thread tries to release the client it acquired before, and it releases back into the new blockworker client pool. The pool is not the same as before, and an exception is thrown.
Fixes #11221
=> Create new client pool map during context reinit

job/common/src/main/java/alluxio/job/plan/transform/CompactConfig.java, job/common/src/main/java/alluxio/job/plan/transform/PartitionInfo.java, job/common/src/test/java/alluxio/job/workflow/composite/CompositeConfigTest.java, job/server/src/main/java/alluxio/job/plan/transform/CompactDefinition.java, job/server/src/main/java/alluxio/job/plan/transform/format/TableWriter.java, job/server/src/main/java/alluxio/job/plan/transform/format/parquet/ParquetWriter.java, job/server/src/test/java/alluxio/job/plan/transform/CompactDefinitionSelectExecutorsTest.java, job/server/src/test/java/alluxio/job/plan/transform/format/ReadWriteTest.java, table/server/common/src/main/java/alluxio/table/common/layout/HiveLayout.java, table/server/common/src/main/java/alluxio/table/common/transform/TransformDefinition.java, table/server/common/src/main/java/alluxio/table/common/transform/action/CompactAction.java, table/server/master/src/test/java/alluxio/master/table/AlluxioCatalogTest.java
**Supported compressions**
parquet.compression=snappy
-rw-r--r--  ec2-user       ec2-user             176773098       PERSISTED 03-19-2020 17:02:33:446 100% /catalog/movielens/tables/ratings/_internal_/ratings/20200319-170148-870-XX8Nm/part-0.parquet
parquet.compression=gzip
-rw-r--r--  ec2-user       ec2-user             123313059       PERSISTED 03-19-2020 17:16:04:797   0% /catalog/movielens/tables/ratings/_internal_/ratings/20200319-171507-662-AnOVT/part-0.parquet
parquet.compression=uncompressed
-rw-r--r--  ec2-user       ec2-user             208935017       PERSISTED 03-19-2020 17:11:50:626   0% /catalog/movielens/tables/ratings/_internal_/ratings/20200319-171107-547-xWDJC/part-0.parquet
**Can be supported but not yet**
parquet.compression=lzo
Class …
=> Add Parquet Compression option

core/common/src/main/java/alluxio/AbstractClient.java
`getServiceVersion()` is a simple unauthenticated code, that is called after a successful connection.
Calling it with `retryRpc` utility opens a way for some allowed exceptions to fuel an infinite loop.
Fixes #11228
=> Get service version out of retryRpc loop

shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
After submitting a large number of jobs to the JobService, the code previously checked if some of the jobs are complete in serial, this code changes that to be done in parallel so that new jobs can be scheduled more quickly.
=> Parallelize DistributedLoadCommand client's job completion check

core/common/src/main/java/alluxio/conf/PropertyKey.java
Defaults were set twice accidentally. Removed them.
=> Remove doubled PK defaults for master client gc threshold

core/common/src/main/java/alluxio/underfs/Fingerprint.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/main/java/alluxio/master/file/meta/MutableInode.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
This PR includes 2 changes:
- For S3, when `inherit_acl=false` any inodes created during loadmetadata should inherit owner/group from the parent directory in alluxio instead of being empty. This was broken because `setOwner` was called after `inheritOwnerAndGroupIfEmpty` in `InodeTree::createPath`
- When syncing metadata with s3, an `updateMetadata` sync plan could lead to setting the owner and group to `_` in `DefaultFileSystemMaster::setAttributeSingleFile`. The fix is to not set the options in `SetAttributePOptions` to avoid setting to an empty string or `_`.
This can be reproduced when a directory is created in alluxio only, the same directory is then later created in the ufs and then synced. Steps to reproduce:
```
$ aws s3 ls s3://adit-bucket-west/
PRE /
$ afs mkdir /adit …
```
=> Fix inheritance for empty owner on createPath and sync

core/common/src/main/java/alluxio/underfs/Fingerprint.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/meta/Inode.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java, core/server/master/src/test/java/alluxio/master/file/meta/InodeTreeTest.java
This PR includes 2 changes:
For S3, when inherit_acl=false any inodes created during loadmetadata should inherit owner/group from the parent directory in alluxio instead of being empty. This was broken because setOwner was called after inheritOwnerAndGroupIfEmpty in InodeTree::createPath
When syncing metadata with s3, an updateMetadata sync plan could lead to setting the owner and group to _ in DefaultFileSystemMaster::setAttributeSingleFile. The fix is to not set the options in SetAttributePOptions to avoid setting to an empty string or _.
This can be reproduced when a directory is created in alluxio only, the same directory is then later created in the ufs and then synced. Steps to reproduce:
$ aws s3 ls s3://adit-bucket-west/
PRE /
$ afs mkdir /adit
Successfully created directory /adit …
=> Port changes of [#11257] to branch-1.8

core/common/src/main/java/alluxio/security/authentication/DefaultAuthenticationServer.java, core/common/src/main/java/alluxio/security/authentication/ImpersonationAuthenticator.java, core/common/src/main/java/alluxio/security/authentication/plain/PlainSaslServerCallbackHandler.java, core/common/src/main/java/alluxio/security/authentication/plain/SaslServerHandlerPlain.java, core/common/src/test/java/alluxio/security/authentication/PlainSaslServerCallbackHandlerTest.java
Before this PR, the ImpersonationAuthenticator class could effectively
bottleneck the amount of concurrent channels that a worker could handle. 
The `<init>` for the ImpersonationAuthenticator class required iterating over
all keys within an Alluxio configuration, not only doing key lookups, but also
performing regex matching. For some keys this could be especially expensive
(i.e, default supplier which calls Runtime.getRuntime().availableProcessors()).
On top of that, performing regex matching is also quite expensive for a few
hundred keys.
After taking a quick peek at the code it seems that it's entirely unnecessary to
instantiate the impersonation authenticator for every new handler that we
create. Instead, it can just be a field within the DefaultAuthenticationServer.
Then, it only …
=> Improve performance of sasl authentication

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/templates/worker/domain-socket-pvc.yaml, integration/kubernetes/multiMaster-embeddedJournal/worker/alluxio-worker-pvc.yaml.template, integration/kubernetes/singleMaster-hdfsJournal/worker/alluxio-worker-pvc.yaml.template, integration/kubernetes/singleMaster-localJournal/worker/alluxio-worker-pvc.yaml.template
This change adds label selector to worker domain socket PVCs so that they only select volumes with alluxio and worker specific PVs. 
This setup should help if the users are provisioning `local` PVs which essentially constraint Pods to go to specific nodes. If there's no selector on the PVC, the worker Pods may claim volumes intended for other Pods and go to unintended nodes.
=> Apply K8s label matching to worker domain socket PVC

pom.xml
Updated the version of netty to address this CVE https://nvd.nist.gov/vuln/detail/CVE-2019-20444.
Since it is a patch update, existing unit tests should cover the update.
=> Update gRPC and netty version to address CVE

dev/scripts/src/alluxio.org/check-docs/main.go, docs/en/operation/Tiered-Locality.md
also update regex to catch links with anchor tags outside jekyll templating
=> [DOCFIX] Fix broken link in Tiered Locality

docs/_plugins/nav-tabs.rb, docs/css/main.css
enables navigational tabs to display content that achieves the same end with different methods
for example, we are able to describe how to launch EMR via the UI (what we currently have) vs using terraform (what we plan on adding) without bloating the page by placing them serially one after another
@madanadit fyi
sample page code:
```
---
layout: global
title: test page
group: Overview
priority: 1
---
Hello and see my nav:
{% navtabs section1 %}
{% navtab moo %}
i'm a cow!
{% endnavtab %}
{% navtab meow %}
i'm a cat!
{% endnavtab %}
{% endnavtabs %}
```
you can try playing with this locally by
- add the above content in a new file docs/en/TestPage.md
- run `jekyll serve` from docs/
- browse to http://localhost:4000/TestPage.html
=> Add nav tabs plugin to docs

core/common/src/main/java/alluxio/metrics/MetricsSystem.java
New `should report metrics` can be added as we report which will cause concurrent modification errors.
=> Use concurrent hashmap for should report metrics

core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
Previously, every single call to the UFS would perform a String.format and then String.split call to extract the method name. This is inefficient. Now, it will simply pull the method name from the callable object. After this, String.format is only called if the log statement is enabled.
Fixes #11237
=> Prevent format calls in UnderFileSystemWithLogging

integration/kubernetes/helm-chart/alluxio/templates/config/alluxio-conf.yaml, integration/kubernetes/helm-chart/alluxio/values.yaml
This change breaks the one-liner property for each Java option into one line for each single property. This makes the helm template more manageable.
This addresses https://github.com/Alluxio/alluxio/issues/11081
=> Format K8s Configmap helm template

core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingClient.java, core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingServer.java, pom.xml
Many connections can be created by the transport layer, but it is rare for copycat to close the client. Tracking the created connections is unnecessary because copycat closes them before closing the clients anyways. This prevents us from holding on to the connection references for extended periods of time, which then causes behavior resembling a memory leak.
Additionally we bump the copycat version to 1.2.15 to avoid cycling connections. 1.2.15 introduces a changes to the KeepAliveResponse serde to respect unresolved addresses.
Fixes #11355
=> Stop tracking connections in copycat client/server

core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClientPool.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java, core/client/fs/src/main/java/alluxio/client/file/FileSystemContextReinitializer.java, core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java, tests/src/test/java/alluxio/client/fs/FileSystemContextReinitIntegrationTest.java
Each FSContext instance creates a new single threaded executor pool for meta master config sync. For long running clients such as yarn RM, if the filesystem is not closed properly we would leak all non-static resources unless garbage collected. 
Fixes: https://github.com/Alluxio/alluxio/issues/11344
=> Make config reinit executor static

integration/kubernetes/helm-chart/alluxio/templates/config/alluxio-conf.yaml
This moves JavaOpts generation out of the multi-line properties, and puts them into the head section.
The reason for doing this is we cannot insert hashtag comments in a multi-line section like below. So if someone wants to generate comments in the helm code, that breaks the helm template.
```
ALLUXIO_MASTER_JAVA_OPTS: |-
{{- /* This will not appear in the generated YAML */}}
{{- $alluxioJavaOpts = printf "-Dalluxio.master.journal.type=%v" .Values.journal.type | append $alluxioJavaOpts }}
...omitted...
```
=> Improve Helm configmap template format

core/common/src/main/java/alluxio/util/ConfigurationUtils.java
I noticed after an upgrade to OpenJDK 8u252 I started getting exceptions thrown when starting the Alluxio services. Alluxio `getConf` was throwing a `ConcurrentModificationException` when trying to load the site properties. I'm not sure exactly who was modifying the properties concurrently, but it is not safe to iterate over `System.getProperties().entrySet()`, so we make a copy of the properties first now before merging.
```
Exception in thread "main" java.util.ConcurrentModificationException
at java.util.Hashtable$Enumerator.next(Hashtable.java:1387)
at alluxio.conf.AlluxioProperties.merge(AlluxioProperties.java:139)
at alluxio.util.ConfigurationUtils.reloadProperties(ConfigurationUtils.java:416)
at alluxio.util.ConfigurationUtils.defaults(ConfigurationUtils.java:399)
at …
```
=> Merge system properties in a thread-safe manner

integration/fuse/bin/alluxio-fuse
`echo -e "${USAGE_USAGE}"` -> `echo -e "${MOUNT_USAGE}"`
=> Fix typo in alluxio-fuse script

dev/jenkins/build.sh, dev/jenkins/run_docker.sh
we currently use this jenkins plugin to run our PR build checks: https://plugins.jenkins.io/ghprb/
the plugin defines an environment variable for the target branch that the PR is going to merge into. that means we can run `git --no-pager diff origin/master --name-only` to get a list of files that were changed in the PR. note this change also required a few tweaks to the jenkins job, most importantly the addition of pulling more refs so i can reference the ref marked as origin/master
since we have two checks, one for the maven build and one for docs, i defined two booleans that get set to true if a corresponding file is found in the diff. if this target branch variable is not available, it defaults to running all checks.
if there are more files or folders that we can incorporate into the …
=> Improve PR build by inspecting PR diff

docs/_plugins/nav-tabs.rb, docs/css/main.css
- can use multiple words to label the navbars section or the navbar tab; previously, using a space would make the navbar unusable
- can create multiple navbars with tabs containing the same name; previously, toggling a duplicated tab name in the second navbar would toggle the first navbar's corresponding tab
- added horizontal line after the navbar section to denote the end of the navbars section
- added spacing after the end of an accordion section
=> Improve navtabs and add accordion styling

integration/dataproc/alluxio.sh
Init actions install presto at `/opt/presto-server` whereas the optional component installs at `/usr/lib/presto`. We switch the default home directory to the optional component location.
Note: init actions are run before optional components are installed. We ignore an error with presto restart, as the service may be configured before or after Alluxio is installed.
=> Switch default to configure optional component for Presto

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsPositionedUnderFileInputStream.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java, underfs/hdfs/src/test/java/alluxio/underfs/hdfs/HdfsUnderFileSystemTest.java, underfs/hdfs/src/test/java/alluxio/underfs/hdfs/PreadSeekableStream.java
The heuristic works as follows :
1. it starts with a pread, because a lot of times the client only does a single large read, and we want to benefit from pread in that case. 
2. if there are certain number of sequential reads in a row, we switch to buffered read mode. In this mode, preads are serviced via pread calls, and read calls are services by read calls. A sequential read is defined as a read that is within a movement limit of the previous read. This is to guard against workloads such as read, skip(2), read, skip(3) etc.
3. any non-sequential read, we change back to pread mode.
=> Improve HdfsPositionedReadUnderFileInputStream with a heuristic

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
Previously, if a machine was too small the master can fail to start up.
The min pool size could have been greater than Runtime.getRuntime().availableProcessors() which would cause an IllegalStateException to be thrown
=> Fix default metadata sync executor sizes

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
The parameter was previously unused by accident. There also an overloaded version of the method which is unused, so I removed it.
=> Use isGetFileInfo when creating sync locking scheme

docs/en/deploy/Running-Alluxio-On-Docker.md
We have users that use customized bridge network policies that have firewall (container inbound & outbound) settings. The existing doc assumes all the ports within a bridge network are open to each other, which is not always true.
This change also elaborates docker network configs a bit more along the way.
=> [DOCFIX] Update port list on Docker doc

core/client/fs/src/main/java/alluxio/client/file/FileSystem.java, core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileSystem.java, core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java, core/common/src/main/java/alluxio/metrics/MetricKey.java
With this PR, a Presto query will fail with following error message when the cache is unable to create:
```
Query 20200522_072107_00001_4hg9d failed: cannot create caching file system
com.facebook.presto.spi.PrestoException: cannot create caching file system
at com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration.lambda$getConfiguration$0(HiveCachingHdfsConfiguration.java:80)
at com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration$CachingJobConf.createFileSystem(HiveCachingHdfsConfiguration.java:104)
at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:56)
at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
at com.facebook.presto.hive.HdfsEnvironment.lambda$getFileSystem$0(HdfsEnvironmen …
```
=> Throw exception when fail to create local cache

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
**Use-case:**
Alluxio superuser:
```
./bin/alluxio fs mkdir /tmp/
./bin/alluxio fs chown userA:userA /tmp/
```
UserA:
```
mkdir ./tmp
./integration/fuse/bin/alluxio-fuse mount ./tmp /tmp
mkdir ./tmp/d1
mkdir: ./tmp/d1: Permission denied
```
master.log
```
WARN  FileSystemMasterClientServiceHandler - Exit (Error): SetAttribute: request=path: "/tmp/d1"
options {
owner: "UserA"
group: "UserA"
commonOptions {
syncIntervalMs: -1
}
}
, Error=alluxio.exception.AccessControlException: Permission denied: UserA is not a super user or in super group
```
=> Fix permission denied while creating a directory

integration/emr/alluxio-emr.sh
Support users providing tarball with name `alluxio.tar.gz` for alluxio-emr.sh
=> Support alluxio.tar.gz in alluxio-emr.sh emr bootstrap

webui/common/src/components/SlackButton/SlackButton.scss
fixed position will keep the button in the bottom right of the screen regardless of scrolling
=> Update Web UI slack button position css to stay in place

core/base/src/main/java/alluxio/exception/ExceptionMessage.java, core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/resource/LockResource.java, core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java, core/server/master/src/main/java/alluxio/master/backup/BackupLeaderRole.java, core/server/master/src/main/java/alluxio/master/meta/DailyMetadataBackup.java, core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java, core/transport/src/main/proto/grpc/meta_master.proto, tests/src/test/java/alluxio/client/cli/fsadmin/BackupCommandIntegrationTest.java
This is to eliminate the impact of backups when the leader has hung RPCs.
Backup not backing off from an exclusive lock acquisition was causing a pile of shared acquisition attempts.
=> Implement non-intrusive locking for backups

integration/tools/pom.xml
Jetty all dependency is conflicted with the server jetty util dependency which causes the master web UI to fail to start.  
Error: Exception "java.lang.NoSuchMethodError: org.eclipse.jetty.server.Server.<init>(Lorg/eclipse/jetty/util/thread/ThreadPool;)V", Root Cause "null"
java.lang.NoSuchMethodError: org.eclipse.jetty.server.Server.<init>(Lorg/eclipse/jetty/util/thread/ThreadPool;
=> Remove jetty all dependencies from hive metastore jar

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java, core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java, core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, core/client/hdfs/src/main/java/alluxio/hadoop/HadoopConfigurationUtils.java, core/common/src/main/java/alluxio/metrics/MetricsSystem.java
Motivated by  issue https://github.com/Alluxio/alluxio/issues/11404, this PR updates logging level for certain logging messages 
After this PR, each query only introduced two info logging like the following;
```
2020-05-22T13:58:05.120-0700	INFO	hive-hive-6	alluxio.hadoop.AbstractFileSystem	Creating Alluxio configuration from Hadoop configuration Configuration: , uri configuration {}
2020-05-22T13:58:05.174-0700	INFO	20200522_205804_00001_nzuct.1.0.0-0-104	alluxio.hadoop.AbstractFileSystem	Creating Alluxio configuration from Hadoop configuration Configuration: , uri configuration {}
```
These two are required as currently each Presto query triggers a new Alluxio FileSystem to be created.
=> Reduce logging on FileSystem instantiation

core/client/fs/pom.xml, pom.xml
fixes #9403 again
commons-codec:1.2, which is included as part of the dependency chain, does not have the method that we want. need to explicitly include a newer version
=> Fix dependencies

webui/master/src/containers/pages/Browse/Browse.scss
increase browse input width to display long path better
before:
after:
=> Optimize browse input width

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/util/CommonUtils.java, underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java, underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
Fixes mount failure and NPE when a user tries to mount S3 bucket with a userid to username mapping configured. 
This addresses the NPE in #11509.
=> Fix NPE associated with s3 account owner

bin/alluxio, core/common/src/main/java/alluxio/cli/ValidationTool.java, core/common/src/main/java/alluxio/cli/ValidationToolFactory.java, core/common/src/main/java/alluxio/cli/ValidationToolRegistry.java, core/common/src/main/java/alluxio/cli/ValidationUtils.java, core/server/master/pom.xml, core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go, integration/tools/hms/pom.xml, integration/tools/hms/src/main/java/alluxio/cli/HmsValidationTool.java, integration/tools/hms/src/main/java/alluxio/cli/HmsValidationToolFactory.java, integration/tools/hms/src/main/resources/META-INF/services/alluxio.cli.ValidationToolFactory, integration/tools/pom.xml, pom.xml, shell/pom.xml, shell/src/main/java/alluxio/cli/HmsTests.java
Hms validation tool depends on hive metastore jar which internally has many dependencies that are conflicts with alluxio dependencies. 
Shade the whole hms validation tool and put it in alluxio/lib directory.
Load the hms validation tool when running hms tests.
=> Change hms validation tool to use extension class loader

integration/kubernetes/helm-chart/alluxio/templates/config/alluxio-conf.yaml, integration/kubernetes/helm-chart/alluxio/values.yaml
Alluxio worker container generated exception when it wont find alias option in configuration. Currently null value is passed to alluxio worker container and it generated exception. I have added the alias value for levels in tieredstore.
=> Add alias option for tieredstore levels

core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, core/client/hdfs/src/main/java/alluxio/hadoop/HadoopConfigurationUtils.java, core/client/hdfs/src/test/java/alluxio/hadoop/HadoopConfigurationUtilsTest.java, core/common/src/main/java/alluxio/conf/PropertyKey.java
In certain applications like Presto, frequently initializing FileSystem instance may be costly in CPU overhead. Further analysis shows when Hadoop configuration is large, regexp used in Alluxio to check whether an given configuration property from Hadoop can be recognized by Alluxio property template contributed a lot to the CPU overhead.
This PR aims to remove this cost. My initial attempt was to introduce extra logic to avoid  `PropertyKey.isValid`. However, this approach has a fairly large footprint in multiple most basic and important classes in Alluxio codebase, and increases complexity. I am concerned with the potential risk to reason and maintain the code after a patch like this.
Later I decided to instead  add a cache inside `PropertyKey.isValid`, given the inquiries are likely to …
=> Add a cache for PropertyKey.isValid

core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java, core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java, core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java, core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java, core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java, core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java, tests/src/test/java/alluxio/client/fs/LocalCacheManagerIntegrationTest.java
This PR fixes a potential race condition in LocalCacheManager and improves its robustness.
Though designed to be threadsafe, `LocalCacheManager` returns a `ReadableByteChannel` to 
`LocalCacheFileInStream`, where I/O operations like reading a file is actually done at `read` or `positionedRead` at `LocalCacheFileInStream`. This leaves an opportunity to multiple threads racing on the same `file` outside threadsafe `LocalCacheManager`. E.g., a super slow reader thread may contend with a evictor thread who wants to remove the same page file per LRU policy, leaving the reader thread risk undefined behavior (up to operating system).
Invariants after this PR:
(1) operating a page files is always protected inside the page lock.
(2) given no operation on the cache `LocalCacheFileInStream` (moved …
=> Improve robustness of LocalCacheManager

integration/emr/alluxio-emr.sh
allow empty ufs uri (means local hdfs mount)
-c flag which installs client jar and conf but do not start alluxio
The reason for these changes: 
1. so that we can launch an emr cluster where the hdfs of that cluster is mounted as root mount
2. so that we can load jars on to a cluster that does not need alluxio running. In this case, a hive metastore containing alluxio uris.
=> Update emr script

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/Chart.yaml, integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
1."RequiredDuringSchedulingIgnoredDuringExecution" is an invalid field in integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml and change it to "requiredDuringSchedulingIgnoredDuringExecution"
2."topologyKey" is required in podAffinity,but it is missing in integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
3.change chart version to 0.6.2
Fixes https://github.com/Alluxio/alluxio/issues/11542
=> Fix the bug that invalid field appears in alluxio helm chart

core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java, core/client/hdfs/src/main/java/alluxio/hadoop/HadoopConfigurationUtils.java, core/client/hdfs/src/test/java/alluxio/hadoop/HadoopConfigurationUtilsTest.java, core/common/src/main/java/alluxio/conf/PropertyKey.java
Cherry-pick https://github.com/Alluxio/alluxio/pull/11537 to branch-2.2
In certain applications like Presto, frequently initializing FileSystem
instance may be costly in CPU overhead. Further analysis shows when
Hadoop configuration is large, regexp used in Alluxio to check whether
an given configuration property from Hadoop can be recognized by Alluxio
property template contributed a lot to the CPU overhead.
This PR aims to remove this cost. My initial attempt was to introduce
extra logic to avoid `PropertyKey.isValid`. However, this approach has a
fairly large footprint in multiple most basic and important classes in
Alluxio codebase, and increases complexity. I am concerned with the
potential risk to reason and maintain the code after a patch like this.
Later I decided to instead add a …
=> Port changes of [#11537] to branch-2.2

core/common/src/main/java/alluxio/collections/LockPool.java, core/common/src/main/java/alluxio/resource/LockResource.java, core/common/src/main/java/alluxio/resource/RWLockResource.java, core/common/src/main/java/alluxio/resource/RefCountLockResource.java, core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java, core/server/master/src/main/java/alluxio/master/file/meta/CompositeInodeLockList.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeLockList.java, core/server/master/src/main/java/alluxio/master/file/meta/InodeLockManager.java, core/server/master/src/main/java/alluxio/master/file/meta/LockedInodePath.java, core/server/master/src/main/java/alluxio/master/file/meta/SimpleInodeLockList.java, core/server/master/src/main/java/alluxio/master/metastore/caching/CachingInodeStore.java, core/server/master/src/test/java/alluxio/master/file/meta/LockedInodePathTest.java, core/server/master/src/test/java/alluxio/master/file/meta/SimpleInodeLockListTest.java, tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java
Before this change lock downgrades did NOT work if the end
of the lock list had more than one write locked inode. This
hasn't burned us until now because the new syncing changes
assumed all inodes in the locklist would be downgraded when
calling LockedInodePath#downgradeToPattern(LockPattern).
This was not the case, which ended up causing a deadlock
when the lock list contained many write-locked entries
One common case where this can occur is when a user is
loading a deeply nested file or directory via some getStatus or
listStatus call which syncs metadata and in-turn, will create
the paths as it discovers them. In doing so, the lock list is
initially populated with write locks. We require them to all
be downgraded to read locks for the metadata sync to be
performed properly.
The new …
=> Simplify lock list downgrades

integration/emr/alluxio-emr.sh
User can pass in a list of relative paths of root UFS to enable active sync on
=> Support active sync for give list in EMR bootstrap

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java, core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java, core/client/hdfs/src/main/java/alluxio/hadoop/HadoopConfigurationUtils.java, core/common/src/main/java/alluxio/metrics/MetricsSystem.java
Cherry-pick #11411
Reduce logging on FileSystem instantiation
Motivated by issue https://github.com/Alluxio/alluxio/issues/11404, this
PR updates logging level for certain logging messages
After this PR, each query only introduced two info logging like the
following;
```
2020-05-22T13:58:05.120-0700 INFO hive-hive-6
alluxio.hadoop.AbstractFileSystem Creating Alluxio configuration from
Hadoop configuration Configuration: , uri configuration {}
2020-05-22T13:58:05.174-0700 INFO
20200522_205804_00001_nzuct.1.0.0-0-104
alluxio.hadoop.AbstractFileSystem Creating Alluxio configuration from
Hadoop configuration Configuration: , uri configuration {}
```
These two are required as currently each Presto query triggers a new
Alluxio FileSystem to be created.
pr-link: Alluxio/alluxio#11411
change-id: …
=> Port changes of [#11411] to branch 2.2

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/resource/LockResource.java, core/server/common/src/main/java/alluxio/master/AbstractMaster.java, core/server/common/src/main/java/alluxio/master/MasterContext.java, core/server/common/src/main/java/alluxio/master/StateLockManager.java, core/server/common/src/main/java/alluxio/master/StateLockOptions.java, core/server/common/src/main/java/alluxio/master/journal/StateChangeJournalContext.java, core/server/common/src/test/java/alluxio/master/StateLockManagerTest.java, core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java, core/server/master/src/main/java/alluxio/master/backup/BackupLeaderRole.java, core/server/master/src/main/java/alluxio/master/backup/BackupOps.java, core/server/master/src/main/java/alluxio/master/backup/BackupWorkerRole.java, core/server/master/src/main/java/alluxio/master/meta/DailyMetadataBackup.java, core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java, core/server/master/src/main/java/alluxio/master/meta/MetaMasterClientServiceHandler.java, core/server/master/src/test/java/alluxio/master/journal/JournalContextTest.java, core/server/master/src/test/java/alluxio/master/meta/DailyMetadataBackupTest.java, core/transport/src/main/proto/grpc/meta_master.proto, tests/src/test/java/alluxio/client/cli/fsadmin/BackupCommandIntegrationTest.java, tests/src/test/java/alluxio/client/cli/fsadmin/BackupCommandStateLockingIntegrationTest.java
This PR, in general, introduces a new locking framework over state-lock. Changes can be summarized as:
- Backups take the lock exclusive with an initial grace-cycle. Grace-cycle is defined as `tryLock-sleep` cycles until the lock is held. 3 graceful locking strategies have been implemented (TIMEOUT, FORCED)
- Immediate shared holders/waiters of state-lock may now be interrupted as part of interrupt-cycle task, which is activated before or after taking the lock.
- Shell/daily backups can now be configured for all grace modes via master config change. (Defaults for Shell: TIMEOUT, Daily: FORCED)
- A new maintenance duration( exclusive-only phase) is defined for masters, during which only exclusive locking will be allowed. This duration is effective after the first time masters are started, …
=> Implement interrupt based locking protocol over state-lock

shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java, tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java
Creating many clients in DistributedLoadCommand creates an issue in certain environments. Reduce the number of clients and also remove the parallelism around it to prevent race conditions when using the same client.
=> Reduce number of clients in DistributedLoadCommand

core/common/src/main/java/alluxio/cli/ValidationConfig.java, core/common/src/main/java/alluxio/cli/ValidationToolRegistry.java, integration/tools/hms/src/main/java/alluxio/cli/HmsValidationTool.java, integration/tools/hms/src/main/java/alluxio/cli/HmsValidationToolFactory.java, shell/src/main/java/alluxio/cli/HmsTests.java
Previously validation tool is hardcoded for hms validation tool. Since it may also be used for other tools, this PR makes the ValidationToolRegistry and Factory more generalize.
=> Make validation tool general

table/server/underdb/glue/src/main/java/alluxio/table/under/glue/GlueDatabase.java, table/server/underdb/glue/src/main/java/alluxio/table/under/glue/Property.java
Glue `getPartions` fetches a random number of partition from glue service without setting the `MaxResults` and `NextToken`. Add the `withMaxResults` and `withNextToken` to fix the partition fetching for Glue UDB.
=> Fix fetching partition for Glue UDB

core/server/common/src/main/java/alluxio/master/StateLockManager.java, core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java, core/server/master/src/main/java/alluxio/master/file/contexts/CallTracker.java, core/server/master/src/main/java/alluxio/master/file/contexts/CompositeCallTracker.java, core/server/master/src/main/java/alluxio/master/file/contexts/DeleteContext.java, core/server/master/src/main/java/alluxio/master/file/contexts/OperationContext.java
This change introduces a new FSM call-tracker that is attached to select
recursive APIs (`list`/`setAttributes`/`setAcl`) in order for them to
respect a pending backup and bail.
pr-link: Alluxio/alluxio#11592
change-id: cid-4a140127d2f37aa1bca4d1283ad035371abdaab0
=> Add a state-lock call-tracker for detecting interrupt-cycles

integration/tools/validation/src/main/java/alluxio/cli/hdfs/SecureHdfsValidationTask.java
This improves `SecureHdfsValidationTest` by:
1. Improve the principal pattern to accept realm to have dots like `@ALLUXIO.COM.NET`
1. Check the `core-site.xml` to see if the HDFS is secured
1. Add a doc link in the advice for the user
=> Improve SecureHdfsValidationTask

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/Chart.yaml, integration/kubernetes/helm-chart/alluxio/templates/config/alluxio-conf.yaml, integration/kubernetes/helm-chart/alluxio/templates/master/service.yaml, integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
1. Fix fuse crash issue. It's because the ALLUXIO_FUSE_OPTS are not in /opt/alluxio/conf/alluxio_env.sh, so it translates to ALLUXIO_FUSE_OPTS=" '-Dalluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME}' "
2. Make pod can access itself through service
3. Update change log
=> Fix Fuse crash in kubernetes in helmchart

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/Chart.yaml, integration/kubernetes/helm-chart/alluxio/templates/config/alluxio-conf.yaml, integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml, integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml, integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml, integration/kubernetes/helm-chart/alluxio/values.yaml
We need remove alluxio worker hostname from ALLUXIO_JAVA_OPTS  to avoid that it overrides the alluxio.worker.hostname in ALLUXIO_WORKER_JAVA_OPTS.
Without this change, the alluxio.worker.hostname is not ip address:
```
bash-4.4# alluxio fsadmin report capacity
Capacity information for all workers:
Total Capacity: 12.00GB
Tier: MEM  Size: 2048.00MB
Tier: SSD  Size: 10.00GB
Used Capacity: 2048.00MB
Tier: MEM  Size: 1024.00MB
Tier: SSD  Size: 1024.00MB
Used Percentage: 16%
Free Percentage: 84%
Worker Name                  Last Heartbeat   Storage       Total            MEM           SSD
iZj6c7rzs9xaeczn47omzcZ      0                capacity      12.00GB          2048.00MB     10.00GB
used          2048.00MB (16%)  1024.00MB     1024.00MB
```
=> Remove worker hostname from ALLUXIO_JAVA_OPTS in helmchart

core/common/src/main/java/alluxio/cli/ValidationUtils.java, integration/tools/validation/src/main/java/alluxio/cli/UfsSuperUserValidationTask.java, integration/tools/validation/src/main/java/alluxio/cli/hdfs/HdfsConfParityValidationTask.java, integration/tools/validation/src/main/java/alluxio/cli/hdfs/HdfsConfValidationTask.java, integration/tools/validation/src/main/java/alluxio/cli/hdfs/SecureHdfsValidationTask.java, stress/shell/src/main/java/alluxio/stress/cli/UfsIOBench.java
The hdfs mount validation tool and IO speed test tool will throw uncaught exceptions instead of returning a parsable JSON string, if the given path is not accessible. 
This change enables them to return parsable JSON results enclosing the invalid path exceptions, to whatever is consuming the results.
=> Improve hdfs tools to return error on invalid paths

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java, core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java, core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java, core/server/master/src/main/java/alluxio/master/file/meta/LockingScheme.java, core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java, core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java, core/server/master/src/test/java/alluxio/master/meta/AlluxioMasterRestServiceHandlerTest.java, tests/src/test/java/alluxio/client/fs/MultiUfsMountIntegrationTest.java, tests/src/test/java/alluxio/client/rest/AlluxioMasterRestApiTest.java
This deadlock occurs when concurrent clients submit requests to
paths where one is the parent of another. It is most likely to
occur one path is a direct parent of another. There needs to be
less threads in the executor than there are paths to sync.
When the deadlock occurs it is because the child path holds a read
lock on a path the parent may be attempting to sync. This prevents
the parent path from continuing to sync. The child path though may
keep queuing sync jobs which can prevent the child from completing
its sync and thus causing deadlock because the parent can never
finish.
In order to fix this there were two major issues to be solved:
1. Unlock the root path so the ancestry of one sync does not block
another. After internal discussion, we decided that because we
don't hold the …
=> Fix deadlock issue on metadata sync

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
The `alluxio-integration-tools-validation.jar` needs to be added to the Alluxio tarball
=> Add validation tool jar to tarball

pom.xml
Bump to address vulnerability:
https://github.com/advisories/GHSA-53x6-4x5p-rrvv
=> Bump commons-compress from 1.16.1 to 1.19

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/values.yaml
The journal formatting job has been removed from the helm chart. This removes its configuration properties.
=> Remove properties for journal formatting job in helm chart

docs/cn/compute/Presto.md, docs/en/compute/Presto.md
-Xbootclasspath/p is no longer a supported option.
https://prestosql.io/docs/current/connector/hive.html#alluxio-client-side-configuration
https://prestodb.io/docs/current/connector/hive.html#alluxio-client-side-configuration
=> [DOCFIX] Fix presto doc

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/values.yaml
`hostPID` is disabled by recommended `PodSecurityPolicy`. This change disables `hostPID` as default so our default setting works with the `PodSecurityPolicy` setup. 
The `hostPID` switch was added in https://github.com/Alluxio/alluxio/pull/11610
=> Disable hostPID by default

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java, underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java
When Alluxio mounts an HDFS UFS as a non superuser, any file persist action would fail because it does not have permission to set owner on HDFS. However, user would see the file is already persisted on HDFS but yet Alluxio still show the file as TO_BE_PERSISTED. Further attempt to persist the file would end up timeout with misleading error message "Failed to rename x.0x000001724B700242.tmp to x".
This problem occurs because the `setOwner` operation is done after the `rename` operation on UFS, so when `setOwner` fails it leaves the persisted file in UFS but keeps the Alluxio persistence state as "TO_BE_PERSISTED". Further persist attempts would then fails due to file already exist and thus keeps on retrying and failing. 
This PR moves the setOwner call to be before rename happens, so when …
=> Fix inconsistent persistence status after setOwner failed

core/common/src/main/java/alluxio/cli/ValidationUtils.java, integration/tools/validation/src/main/java/alluxio/cli/HdfsValidationTool.java, integration/tools/validation/src/main/java/alluxio/cli/ValidateEnv.java, stress/shell/src/main/java/alluxio/stress/cli/UfsIOBench.java
This PR contains a few improvements to the HDFS tools:
1. Set process type of `UfsIOBench` as JOB_WORKER as it always runs in a job, invoked by a job worker.
1. Added description to each of the `TaskResult` from `HdfsValidationTool`. Each description corresponds to what the validation task did.
1. Removed `UfsContractTest` from `HdfsValidationTool`, as we only care about the accessibility of the UFS path, not all possible UFS operations.
1. Catch more exceptions now in the tools.
=> Improve UfsIOBench and HdfsValidationTool

docs/en/compute/Tensorflow.md
tutorial directory was removed in [Tensorflow 2.0](https://github.com/tensorflow/models/releases/tag/v2.0)
=> Fix Tensorflow documentation classify_image.py url

core/common/src/main/java/alluxio/concurrent/jsr/ForkJoinPool.java, core/common/src/main/java/alluxio/util/ThreadFactoryUtils.java, core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
This PR introduces a thread-factory implementation for use by `ForkJoinPool` in order to provide a custom name for worker threads.
=> Add thread-factory for fork-join-pool threads

docs/_plugins/nav-tabs.rb
use string.gsub instead of string.sub to replace all instead of replace first occurrence
=> Fix spaces in navtab titles

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/Chart.yaml, integration/kubernetes/helm-chart/alluxio/values.yaml
Since the default direct memory is 2G, we should increase the default memory limit to 4G to make the Heap + direct memory can work.
=> Increase the memory limit of fuse in kubernetes

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java, core/server/common/src/main/java/alluxio/master/StateLockManager.java, core/server/master/src/main/java/alluxio/master/file/DefaultBlockDeletionContext.java
Based on my testing on a local machine these sites accounted for anywhere between 1% and 3% of the CPU time when processing the RPC.
- When calling getObjectListing on the ObjectUnderFileSystem, we should store the value of the breadcrumbs enabled as a boolean rather than always parsing from the config
- When calling `lockShared()` in the state lock manager, prevent a String.format call by wrapping with a conditional statement.
- When creating the DefaultBlockDeletionContext, initialize the array list with a size of 0 to prevent unnecessarily allocating small arrays over and over again with the default ArrayList constructor, when most times we won't even add to this ArrayList.
=> Add minor RPC optimizations

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java, underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
Path of s3://<bucket_name> currently doesn't work while s3://<bucket_name>/ does because
s3://<bucket_name>/ gets currently replaced with the empty string when using it with the correct client while
s3://<bucket_name> does not get replaced with the empty string.
=> Fix edge case for ObjectUFS when looking at root path

core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java, core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java, core/server/master/src/test/java/alluxio/underfs/UfsStatusCacheTest.java
This reverts a change from #11704 while also removing redundant UFS calls. The `ufs.exists` in `loadMetadata` is no longer necessary because every call to `loadMetadata` goes through call site place which will always set the `UfsStatus` in the `LoadMetadataContext`. The attempt to retrieve the `UfsStatus` from the `UfsStatusCache` will always pull the status from the internal map, or reach out to the UFS. If the status couldn't be retrieved on the call to `fetchStatusIfAbsent` then it does not exist in the UFS.
=> Simplify UfsStatus handling in loadMetadata

core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockStore.java, core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksBlockStoreTest.java
`setPrefixSameAsStart` does not work when there is a composite key, and both components need to be specified (2 longs). Therefore, use `setIterateUpperBound` instead.
Fixes #11753
=> Fix block location iteration with rocksdb

core/client/fs/src/main/java/alluxio/client/file/FileSystem.java, core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java, core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileSystem.java, core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioHdfsFileSystem.java, core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioHdfsInputStream.java, core/client/hdfs/src/main/java/alluxio/hadoop/HadoopConfigurationUtils.java, core/client/hdfs/src/main/java/alluxio/hadoop/HadoopUtils.java, core/client/hdfs/src/main/java/alluxio/hadoop/HdfsFileInputStream.java, core/client/hdfs/src/main/java/alluxio/hadoop/LocalCacheFileSystem.java, core/client/hdfs/src/main/java/alluxio/hadoop/LocalCachingFileSystem.java
- move `CacheManager` singleton to `CacheManager.Factory`, so multiple different classes can access this singleton.
- Change `LocalCachingFileSystem` from inheriting `AbstractFileSystem` to Hadoop Filesystem,  to reduce the complexity & reduce # of calls of merge hadoop conf (to 1 per LocalCachingFileSystem)
=> Add alluxio.hadoop.LocalCacheFileSystem.java

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/test/java/alluxio/conf/PropertyKeyTest.java
We occasionally create custom property keys containing strings like "accessKeyId" or "secretKey" (or other combinations) that should be treated as displayType credentials and thus not be sent back to the client.
=> Display PropertyKeys containing keywords as credentials

pom.xml
Junit 4.13 was released with jdk11 CI.
=> Upgrade Junit from 4.12 to 4.13

job/server/src/main/java/alluxio/job/plan/transform/CompactDefinition.java, pom.xml
Parquet libraries started having Java 11 CI from 1.11.0.
=> Upgrade parquet libraries version from 1.10.0 to 1.11.0

pom.xml
Jackson started adding CI from Java 11 on. aws-java-sdk-core seems to have a dependency on it but overall, seems safe.
=> Upgrade jackson from 2.10.1 to 2.11.1

stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
Using longs supports larger file sizes.
=> Use longs for file offsets in stress client io

pom.xml
hive-metastore has a dependency to commons-lang3 as well which will also get upgraded from 3.4 to 3.11.
=> Upgrade commons-lang3 from 3.4 to 3.11

pom.xml
hbase-client has a dependency to commons-io which also gets upgraded from this as a result but it seems okay.
=> Upgrade commons-io from 2.6 to 2.7

core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java, core/client/fs/src/test/java/alluxio/client/file/MetadataCacheTest.java
Fix #11765
Description:
meta data may be deleted in client cache although it is very hot. 
Now MetadataCache holds mStatus which stores the current file/dir status and mDirStatuses which stores the children status.
```
private class CachedItem {
private final URIStatus mStatus;
private final List<URIStatus> mDirStatuses;
```
1. For example, There is a path '/A/B/C'.
2. We run the listStatus request on the directory '/A/B'. After receiving result from alluxio master, it caches 'A/B' into the cache map which stores the children status for the path '/A/B' as mDirStatuses and its children '/A/B/C' into the cach map which stores the file/dir status as mStatus. 
3. Then we run the listStatus request on the directory '/A'. After receiving result from alluxio master, it caches '/A' into the cache …
=> Fix bug in meta cache in MetadataCachingBaseFileSystem

pom.xml
httpclient has dependency on httpcore and most others that depend on httpclient also depend on httpcore. Note also that httpclient 4.5.11 upgraded httpcore dependency to 4.4.13 accoridng to the changelogs. Here are the list of other dependencies with a dependency on httpclient/httpcore. 
libthrift
aws-java-sdk-core
cos_api
hadoop-auth
aliyun-sdk-oss
joss
hadoop-azure
hadoop-ozone-filesystem
hadoop-auth
=> Upgrade httpclient to 4.5.6 and upgrade httpcore to 4.4.13

core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
Small fix to make posRead behavior mimic normal read behavior. If the source is local, we have already cached the data. Unfortunately our testing framework is not fine grained enough to track the RPC calls (see AlluxioFileInStreamTest#L752). 
In general, our strategy of sending async cache requests has been aggressive because we believed it is cheap for the worker to filter out duplicate requests. If this is not the case, we can probably further decrease the number of async cache requests we make.
=> [SMALLFIX] Do not trigger async caching on posRead if source is local

pom.xml
Other dependencies that got it's guava updated as a result:
hive-metastore: 27.0.1-jre -> 29.0-jre
=> Update guava from 27.0.1-jre to 29.0-jre

integration/dataproc/alluxio-dataproc.sh
The previous sync link hardcorded the tarball version which may not be true in testing.
=> Modify alluxio client sync link for whatever version

core/common/pom.xml, pom.xml
Note that hive has a dependency on zookeeper that is pinned to 3.4.6 at the moment
We are still waiting for hive to be java compatible and it will be dealt with then.
Otherwise, all the dependencies seems to be from alluxio itself making this minor upgrade.
=> Upgrade zookeeper from 3.5.5 to 3.5.8

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md, integration/kubernetes/helm-chart/alluxio/Chart.yaml, integration/kubernetes/helm-chart/alluxio/templates/config/alluxio-conf.yaml, integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
Fuse YAML template uses `ALLUXIO_CLIENT_JAVA_OPTS`, whereas the correct env variable should be `ALLUXIO_USER_JAVA_OPTS`.
=> Fix Fuse YAML to use ALLUXIO_USER_JAVA_OPTS

core/common/src/main/java/alluxio/util/CommonUtils.java, core/common/src/test/java/alluxio/util/CommonUtilsTest.java, shell/src/main/java/alluxio/cli/bundler/CollectInfo.java, shell/src/main/java/alluxio/cli/bundler/command/AbstractCollectInfoCommand.java, shell/src/main/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommand.java, shell/src/main/java/alluxio/cli/bundler/command/CollectConfigCommand.java, shell/src/main/java/alluxio/cli/bundler/command/CollectLogCommand.java, shell/src/test/java/alluxio/cli/bundler/CollectInfoTest.java, shell/src/test/java/alluxio/cli/bundler/InfoCollectorTestUtils.java, shell/src/test/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommandTest.java, shell/src/test/java/alluxio/cli/bundler/command/CollectConfCommandTest.java, shell/src/test/java/alluxio/cli/bundler/command/CollectEnvCommandTest.java, shell/src/test/java/alluxio/cli/bundler/command/CollectLogCommandTest.java
This adds 3 features to `collectInfo`
1. With `--exclude-logs <filename-prefixes>`, `--include-logs <filename-prefixes>` and `--additional-logs` the user is able to specify log files to take or not take. By default only Alluxio-relevant files under `${ALLUXIO_HOME}/logs` are included and unrecognized files are ignored.
For example, `alluxio collectInfo --additional-logs alluxio_gc --exclude-logs master collectLog <tmp-dir>` will include all `alluxio_gc*` files (supposedly for GC logs) and exclude all `master*` files like `master.log.*` and `master.out`.
`alluxio collectInfo --include-logs master collectLog <tmp-dir>` will, however, take only the `master*` files like `master.log` and `master.out`.
2. With `--start-time <datetime>` and `--end-time <datetime>` the user can specify a certain …
=> Add more options to collectInfo command

pom.xml
We need our final artifact to be compatible with java 8 even if we are running jdk 11 compiler.
=> Force target to be java 8 even if we are using jdk 11 to compile

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go, dev/scripts/src/alluxio.org/build-distribution/cmd/version.go
version check logic was wrong (ex. if hadoop version = 3.0, comparison of "is greater than 2.4) returned was false) . added correct comparison via helper function
facepalm
=> Fix yarn version check in generate-tarball

pom.xml
dependency diff
```
< [INFO] |  |  |  |  \- com.jamesmurty.utils:java-xmlbuilder:jar:0.4:compile
---
> [INFO] |  |  |  |  \- com.jamesmurty.utils:java-xmlbuilder:jar:1.3:compile
> [INFO] |  |  |  |     \- net.iharder:base64:jar:2.3.8:compile
```
=> Upgrade java-xmlbuilder from 0.4 to 1.3

pom.xml
Jets3t and it's dependencies changed to 0.9.4 in alluxio-underfs-gcs, alluxio-table-server-underdb-glue and alluxio-underfs-wasb
=> Upgrade jets3t to 0.9.4

underfs/cos/pom.xml
```
5294c5294
< [INFO]    com.qcloud:cos_api:jar:5.4.0:compile
---
> [INFO]    com.qcloud:cos_api:jar:5.6.28:compile
5298c5298
< [INFO]    joda-time:joda-time:jar:2.9.6:compile
---
> [INFO]    joda-time:joda-time:jar:2.9.9:compile
5301a5302
> [INFO]    org.bouncycastle:bcprov-jdk15on:jar:1.64:compile
```
=> Upgrade cos_api to 5.6.28

bin/alluxio-start.sh
This prevents the start command from formatting an entire cluster if the journal directory doesn't exist. Original behavior was built to ensure that the journal folder existed in EMBEDDED mode. However, if a user accidentally removes the directory (e.g. during an upgrade), then we want to ensure that not all nodes are formatted.
=> Format only the local master to avoid wiping the whole cluster

pom.xml, underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
Jets3t targets AWS, changes from 0.8.1 to 0.9.4 are mostly AWS changes, not related to either GCS or Java 11.
Using 0.9.4 requires using custom classloader to run nearly all GCS APIs which is inefficient and reduce code cleanness.
Revert the version for now.
=> Revert jets3t to 0.8.1

integration/tools/hms/pom.xml, logserver/pom.xml, pom.xml, shaded/client/pom.xml, shaded/hadoop/pom.xml, underfs/pom.xml
This PR prepares for Java 11 by upgrading log4j to log4j2
=> Upgrade from log4j to log4j2

core/common/src/test/java/alluxio/security/authentication/CustomAuthenticationProviderTest.java
classNotProvider test has different thrown messages in Java 8 and Java 11.
Java 11 prefix the detailed class name with a "class" suffix.
The new messages support both formats.
=> Fix CustomAuthenticationProviderTest.classNotProvider test in Java 11

shaded/client/pom.xml
Solve Error creating shaded jar: duplicate entry: META-INF/services/alluxio.shaded.client.com.fasterxml.jackson.core.ObjectCodec
=> Fix shaded client duplicate jackson.core.ObjectCodec entry

docs/en/cloud/Google-Dataproc.md, integration/dataproc/alluxio-dataproc.sh
Modify dataproc doc.
Fix the bug that sync need to be run as `alluxio` user.
Add back the alluxio presto home.
pr-link: Alluxio/alluxio#11817
change-id: cid-82c7259efac11c0e9538c3a947df5b96e966603c
[This is a manual PR to cherry-pick committed PR #11817 into target branch branch-2.3]
=> Modify dataproc doc and fix small bugs

pom.xml
- Bump swagger-annotations from 1.5.22 to 1.6.2
- Bump plugin from 3.1.1 to 3.1.7 (3.1.8 confirmed to have a bug)
=> Update swagger annotations and plugin

integration/tools/validation/pom.xml, pom.xml
Updates for netty 4.1.48.Final and grpc 1.29.0 as outlined in #11923
grpc 1.31.0 had some changes that broke the build so I stopped at 1.29.0 since it had the needed Netty updates to resolve the CVE
=> Update grpc and netty to resolve CVEs

integration/tools/validation/src/test/java/alluxio/cli/ValidationTestUtils.java, integration/tools/validation/src/test/java/alluxio/cli/hdfs/HdfsProxyUserValidationTaskTest.java
Using Powermock makes it now such that you can no longer fetch the resource after Java 9 because (See https://stackoverflow.com/questions/54021754/why-does-the-getresource-method-return-null-in-jdk-11 UPDATE in the chosen answer)
=> Fix HDFSProxyUserValidationTaskTest

core/common/src/main/java/alluxio/conf/PropertyKey.java, core/common/src/main/java/alluxio/util/JvmPauseMonitor.java, core/common/src/test/java/alluxio/TestLoggerRule.java, core/common/src/test/java/alluxio/util/JvmPauseMonitorTest.java, core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java, core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java, core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
In addition to turning it on by default;
- Many new tests were added. Code coverage is 82/89 (92%)
- Minor tweaks and improvements to the class
=> Enable the JVM pause monitor by default

tests/src/test/java/alluxio/client/cli/fs/command/CopyFromLocalCommandIntegrationTest.java, tests/src/test/java/alluxio/client/cli/fs/command/CopyToLocalCommandIntegrationTest.java
Setting user.dir to test relative path no longer works as of Java 11 (See https://bugs.openjdk.java.net/browse/JDK-8202127)
There is not much value to this test because this ultimately just tests that new File(Relative Path) is a working behavior.
=> Ignore RelativePath tests in Java 11

table/server/underdb/glue/pom.xml, table/server/underdb/hive/pom.xml, table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/CompatibleMetastoreClient.java, table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HMSClientFactory.java, table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HMSShim.java, table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveClientPool.java, table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveCompatibility.java
Version 2.2.0 of hive metastore client worked with a wide range of server versions, but we have to upgrade it for java 11 support. Hence we add a compatibility library which proxies a number of calls to achieve compatibility with older versions.
=> Create a compatibility layer to handle older hive metastores

pom.xml
rockdsdb version upgrading to  6.11.4 cause the create file and delete file performance downgrade a lot when the alluxio system has a lot of files. Revert it back to previous version until we are clear about the downgradation reason
=> Revert rocksdb version

dev/jenkins/build.sh
Since  we compile everything with java 8, we want to force java 11 to use our java 8 compilation result. So we skip compilation stage for the java 11 maven invocation. This also reduces testing time from 28 mins to 18 mins.
=> Test skip compile

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java, core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStore.java, core/client/fs/src/test/java/alluxio/client/file/cache/store/LocalPageStoreTest.java, core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreTest.java
This patch aims to fix periodic `ClosedByInterruptException` thrown to local cache. 
```
2020-08-12T15:06:00.020-0700    ERROR   20200812_220058_08274_gyew8.1.0.9-586-95713     alluxio.client.file.cache.LocalCacheManager     Failed to get existing page PageId{FileId=47a1abdb3874925210b14e81720f4e8f, PageIndex=181}: {}
java.nio.channels.ClosedByInterruptException
at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:228)
at alluxio.client.file.cache.LocalCacheManager.getPage(LocalCacheManager.java:457)
at alluxio.client.file.cache.LocalCacheManager.get(LocalCacheManager.java:362)
at alluxio.client.file.cache.NoExceptionCacheManager.get(NoExceptionCacheManager.java:62)
at …
```
=> Fix ClosedByInterruptException issue in local cache

underfs/cos/src/main/java/alluxio/underfs/cos/COSInputStream.java, underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSInputStream.java, underfs/kodo/src/main/java/alluxio/underfs/kodo/KodoInputStream.java, underfs/oss/src/main/java/alluxio/underfs/oss/OSSInputStream.java, underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AInputStream.java
Do not log all failed attempts. Instead, set the exception message.
=> Reduce spammy logging for object store failed opens

dev/scripts/check-docs.sh, docs/en/deploy/Requirements.md, docs/en/operation/Scalability-Tuning.md
docs check script was broken since the jekyll command was added since it ignored the exit code of the link check script. fixed by adding `set -eux`
fixes for changes introduced in https://github.com/Alluxio/alluxio/pull/11958
=> Fix docs check script and fix links

core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java, core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java, shell/src/main/java/alluxio/cli/fs/command/AbstractFileSystemCommand.java
Add more obvious messaging for the previous "target unavailable" errors.
=> Add details for block worker client errors

core/common/src/test/java/alluxio/util/JvmPauseMonitorTest.java
Instead of giving leeway on assertEquals, just check that the total time paused now exceeds the base sleep threshold.
=> Fix more Flakiness of JVMPauseMonitorTest

pom.xml
GRPC upgrade  beyond 1.29 (included) introduces significant perf regression in alluxio metadata operations. 
We downgrade it to 1.28.1 but upgrade the problematic netty package to fix CVE. 
This addresses perf regression introduced in #11955 .
=> Downgrade grpc to 1.28.1 and upgrade netty to 4.1.51.Final

job/server/src/main/java/alluxio/job/plan/stress/StressBenchDefinition.java, stress/shell/src/main/java/alluxio/stress/cli/Benchmark.java
This affects running benchmarks because job master and command line processes spaces differently.
It can cause benchmark jobs to fail.
=> Trim java opts when applying them in the command line

core/client/fs/src/main/java/alluxio/client/file/cache/DefaultMetaStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java, core/client/fs/src/main/java/alluxio/client/file/cache/MetaStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java, core/client/fs/src/main/java/alluxio/client/file/cache/store/RocksPageStore.java, core/client/fs/src/test/java/alluxio/client/file/cache/DefaultMetaStoreTest.java, core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java, core/client/fs/src/test/java/alluxio/client/file/cache/store/PageStoreTest.java, core/common/src/main/java/alluxio/metrics/MetricKey.java
Fix two issues:
(1) Previously MetaStore and Evictor are both used as the state to make eviction decisions, but they are not put in the same critical section, and not coordinated to be consistent in tricky cases of failed page store deletes. This PR makes evictor a part of MetaStore so their content will always be consistent
(2) Eviction is a 2PC (phase 1 in metastore and phase 2 in pagestore), this PR fixes the undo logic when this 2PC failed in the middle.
=> Fix local cache locking

core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java
The max retry duration should be a bit longer to support slower test machines. The retry duration needs to be long enough for there to be at least 2 tries for some of the test cases.
=> Fix flaky AlluxioFileInStreamTest

minicluster/src/main/java/alluxio/multi/process/MultiProcessCluster.java
When running tests on less faster machines, the timeout for master serving timeout becomes an issue.
=> Increase master serving timeout for slower machines

pom.xml, webui/common/.eslintrc.js, webui/common/.prettierrc.js, webui/common/src/components/LineGraph/LineGraph.scss, webui/common/src/utilities/nivo/transformToNivoFormat.tsx, webui/master/.eslintrc.js, webui/master/.prettierrc.js, webui/master/src/store/init/reducer.tsx, webui/pom.xml, webui/worker/.eslintrc.js, webui/worker/.prettierrc.js
License check hasn't been properly working for a while on this. Adding the parent declaration will fix this. It will also allow us to run `mvn license:check` from the root of the repo. Before, `license:check` would fail on the webui because it would attempt to use a different plugin.
=> Add <parent> declaration to webui pom

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointThread.java
This fixes a bug when the checkpoint thread is shutdown, but there was a checkpoint in progress. Sometimes, the shutdown request can occur after the checkpoint output stream is created, but before anything is written to it. So, checkpoint stream is closed, which makes the checkpoint complete, but empty (which is incorrect).
This PR fixes the issue by canceling the stream when the thread is shutdown, instead of closing it. By canceling the stream, the checkpoint is not considered complete, but is removed. Therefore, the potentially empty file is not considered a valid checkpoint, and that file is removed.
Unfortunately, this is difficult to unittest because it depends heavily on timing. However, I ran a flaky test 500 times, and before this change it failed 14 / 500 times. With this …
=> Cancel in-progress checkpoints when thread is shutdown

pom.xml
maven-surefire-plugin occasionally crashes with 
pure virtual method called
terminate called without an active exception
=> Undo upgrade of maven-surefire-plugin

tests/src/test/java/alluxio/server/ft/journal/MultiProcessCheckpointTest.java
The second startMasters take a significantly longer time than the first one which causes it to timeout in smaller machines.
=> Increase timeout for second startMasters in MultiProcessCheckpointTest

core/client/fs/src/main/java/alluxio/client/file/ConfigHashSync.java
If the ConfigHashSync's Heartbeat thread is running, the client can't be closed. Unfortunately, the cancel on heartbeat thread that gets called can be unreliable at times and as a result, there is a possibility of a deadlock.
One Thread:
(waiting on ConfigHashSync synchronized)
at alluxio.client.file.ConfigHashSync.close(ConfigHashSync.java:112)
at alluxio.client.file.FileSystemContextReinitializer.close(FileSystemContextReinitializer.java:189)
(has FileSystemContext synchronized lock)
at alluxio.client.file.FileSystemContext.close(FileSystemContext.java:262)
HeartBeatThread:
(waiting on FileSystemContext's synchronized lock)
at alluxio.client.file.FileSystemContext.getMasterAddress(FileSystemContext.java:417)
at alluxio.client.file.FileSystemContext.reinit(FileSystemContext.java:348) …
=> Remove synchronized in ConfigHashSync

core/common/src/main/java/alluxio/util/JvmPauseMonitor.java
This assert came up a lot when running integration tests in smaller machine.
=> Remove assert in JVM Pause Monitor stop
