Alluxio/alluxio

docs/en/api/FUSE-API.md
integration/fuse/bin/alluxio-fuse

cherry-pick of Alluxio/alluxio#7900
cherry-pick commit is Alluxio/alluxio@4c22e33b8a61

Support allow_other/allow_root Fuse mount options (#7900)

---

core/server/common/src/main/java/alluxio/master/PrimarySelectorClient.java

pr-link: Alluxio/alluxio#9509
change-id: cid-89e061e62f9facc569ddfb570670b99f134af2ff

Start curator client before initial close

---

core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java

Address #9501
@guang7niu can you take a look for this fix?

Fix worker registration failure

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
tests/src/test/java/alluxio/client/fs/FileSystemIntegrationTest.java

cherry-pick of PR Alluxio/alluxio#8511
cherry-pick of commit Alluxio/alluxio@b6ede350964986fb51b26cf0304847bb53ebb3a3

Check for null TtlAction in DefaultFileSystemMaster

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java

Implement the unit test for fuse statfs method

Implement fuse statfs unit test

---

bin/alluxio

[SMALLFIX]Fix syntax error

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java

Manual cherry-pick of existing commit.
orig-pr: Alluxio/alluxio#9383
orig-commit: Alluxio/alluxio@2176eb6f7da48cb611f0ca01c1f8e1f3749f0855
orig-commit-author: liuhongtong <hongtongliu@126.com>
pr-link: Alluxio/alluxio#9383
change-id: cid-359916d627f77814b0a770745454672bddc8fdd1

Support specifying mode when create new file and dir by Alluxio FUSE

---

webui/master/src/containers/pages/Metrics/Metrics.tsx
webui/master/src/containers/pages/Metrics/__snapshots__/Metrics.test.tsx.snap

Add short-circuit read to metrics page

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
integration/fuse/src/main/java/alluxio/fuse/OpenFileEntry.java
integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java

Cherry-pick [ALLUXIO-3391] only blocking fuse getAttr() in async release()
cherry-pick of PR Alluxio/alluxio#8213
cherry-pick of commit Alluxio/alluxio@12637b09a305d3a01c3cf4a2107ec9a95ff883b8

Fix fuse get attr only wait in async release (#8213)

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md

- Made the explanations more explicit
- Highlight where domain socket must be mounted
Closes #9574

Improve k8s short-circuit documentation

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md

- Misleading information and typos were introduced in #9575 
Resolving typos and misleading information

[DOCFIX] Fix k8s Deployment Doc Typos

---

core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java

Check for null reference during block worker shutdown

---

core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcClient.java
core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcServer.java
core/server/common/src/test/java/alluxio/master/journal/raft/transport/CopycatGrpcTransportTest.java

Returning a completed future from connection creation was causing copycat to do a premature cleanup, which in turn was causing a race condition at copycat side. This PR makes relevant calls truly async.

Create and Close copycat transport clients/servers asynchronously

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java

orig-pr: Alluxio/alluxio#9418
orig-commit: Alluxio/alluxio@dcf782c8f057d07fe778980af6205e57da9803bd
orig-commit-author: liuhongtong <hongtongliu@126.com>
pr-link: Alluxio/alluxio#9563
change-id: cid-fdbc5bb9dbe116c0f3421d7b94ec36412d87be81

Support statfs by Alluxio FUSE

---

integration/kubernetes/alluxio-fuse.yaml.template

Set the physical ip for alluxio-fuse

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md
integration/kubernetes/helm/alluxio/templates/alluxio-master.yaml
integration/kubernetes/helm/alluxio/templates/alluxio-worker.yaml
integration/kubernetes/helm/alluxio/values.yaml

Adds support for secrets as files

Add helm template for secrets

---

docs/en/basic/Command-Line-Interface.md
shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
tests/src/test/java/alluxio/client/cli/fs/command/LsCommandIntegrationTest.java

Added some options for selecting which timestamp should be displayed when running `ls` command.

Add CLI options for listing last access time

---

docs/en/Getting-Started.md
docs/en/Overview.md

[DOCFIX] Remove HTML in Overview and Getting Started docs

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

Fixes Alluxio/alluxio#9294
Fixes Alluxio/alluxio#9295
Update audit logic to be more flexible when acquiring user information.

Avoid exception when audit log is used with NOSASL authentication

---

experimental/table/client/pom.xml
experimental/table/client/src/main/java/alluxio/client/catalog/CatalogMasterClient.java
experimental/table/client/src/main/java/alluxio/client/catalog/RetryHandlingCatalogMasterClient.java
experimental/table/pom.xml
experimental/table/server/master/pom.xml

Add required client interface with AlluxioStatusException

Add required meta service client interfaces

---

integration/docker/README.md
integration/docker/entrypoint.sh
integration/kubernetes/alluxio-fuse.yaml.template

fixes #9441
add a way for setting extra options for alluxio-fuse through args

Enable setting alluxio-fuse options for docker image

---

core/client/fs/pom.xml
core/server/master/pom.xml
core/server/worker/pom.xml
core/transport/pom.xml
pom.xml
tests/pom.xml

Cleaning up io.netty configuration from modules

Clean io.netty dependencies

---

core/common/src/main/java/alluxio/util/logging/SamplingLogger.java
core/common/src/test/java/alluxio/util/logging/SamplingLoggerTest.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

This is a backport of the same feature from the master branch. This sampling logger helps with spammy log messages.

Implement SamplingLogger

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/InodeTtlChecker.java
core/server/master/src/main/java/alluxio/master/file/LostFileDetector.java
core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java

Fixes https://github.com/Alluxio/alluxio/issues/9658

Handle interruptions on various heart beats

---

core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java

These log messages can be very spammy, so use the sampling logger.
pr-link: Alluxio/alluxio#9709
change-id: cid-749e87e3dec96958e9513b5c77155500c7c0f426

Reduce spammy logs

---

core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java

Thrift server doesn't interrupt its `ExecutorService` during shutdown. This PR makes it use an external `ExecutorService` that we own, and interrupt it after shutting down Thrift.

Manage thrift thread-pool and interrupt it during shutdown

---

bin/launch-process

Reverts Alluxio/alluxio#9706 due to performance impact

Revert "Use Concurrent Mark Sweep garbage collector for master"

---

core/common/src/main/java/alluxio/util/webui/UIFileInfo.java
core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java

- Fixes #9518 
- following up on style fixes for #9577

Remove duplicate entries in BlockInfo tab of worker WEBUI

---

integration/docker/Dockerfile
integration/docker/entrypoint.sh

Cherry-pick: https://github.com/Alluxio/alluxio/pull/9762

Disable DNS cache at docker build instead of entrypoint

---

core/server/common/src/main/java/alluxio/master/journal/NoopJournaled.java
core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalCheckpointThread.java

Throw exception when ufs journal reads unrecognized entry

---

core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java

**Description**
There is an extra close bucket.

Remove the extra close bucket

---

core/client/fs/src/main/java/alluxio/client/block/stream/DefaultBlockWorkerClient.java
core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
core/common/src/main/java/alluxio/AbstractClient.java
core/common/src/main/java/alluxio/grpc/GrpcChannel.java
core/common/src/main/java/alluxio/grpc/GrpcChannelBuilder.java
core/common/src/main/java/alluxio/grpc/GrpcChannelKey.java
core/common/src/main/java/alluxio/grpc/GrpcManagedChannelPool.java
core/common/src/main/java/alluxio/grpc/GrpcServer.java
core/common/src/main/java/alluxio/grpc/GrpcServerAddress.java
core/common/src/main/java/alluxio/grpc/GrpcServerBuilder.java
core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java
core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java
core/common/src/main/java/alluxio/security/authentication/SaslStreamClientDriver.java
core/common/src/main/java/alluxio/util/ConfigurationUtils.java
core/common/src/main/java/alluxio/util/network/NetworkAddressUtils.java
core/common/src/test/java/alluxio/grpc/GrpcManagedChannelPoolTest.java
core/common/src/test/java/alluxio/security/authentication/GrpcSecurityTest.java
core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcClient.java
core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcServer.java
core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
core/server/worker/src/main/java/alluxio/worker/grpc/GrpcDataServer.java
job/server/src/main/java/alluxio/master/AlluxioJobMasterProcess.java
job/server/src/main/java/alluxio/worker/AlluxioJobWorkerProcess.java
tests/src/test/java/alluxio/server/ft/ZookeeperFailureIntegrationTest.java

Below refactoring items are done with this PR. Main motivation is to improve diagnosability of issues from traces by including precise source/target information for client channels.
- Extend tracing to contain more descriptive information on client side. https://github.com/Alluxio/alluxio/commit/cbdaf0e4d17bf1160f77f6439e8da2ccb597620b https://github.com/Alluxio/alluxio/commit/cdec65517eff980b982a6a94d34e5fb99100fe6e
- Improve server side tracing and simplify server building code. https://github.com/Alluxio/alluxio/commit/269b4013a2bd22db202d00797f72a3cf3d554f46 https://github.com/Alluxio/alluxio/commit/d850b80302c9bcfa0056ec2317ad23665f952273
- Miscellaneous improvements. https://github.com/Alluxio/alluxio/commit/e5ee04ceec8b5dd92566adbe4b4cc50caae97568

Refactor gRPC channel/server building

---

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go

Add flag to skip generating the webui when running generate tarball

---

core/common/src/main/java/alluxio/wire/BackupResponse.java
core/server/common/src/main/java/alluxio/master/BackupManager.java
core/server/master/src/main/java/alluxio/master/meta/DailyMetadataBackup.java
core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
core/server/master/src/test/java/alluxio/master/meta/DailyMetadataBackupTest.java
core/transport/src/grpc/meta_master.proto
core/transport/src/main/java/alluxio/grpc/BackupPResponse.java
core/transport/src/main/java/alluxio/grpc/BackupPResponseOrBuilder.java
core/transport/src/main/java/alluxio/grpc/MetaMasterProto.java
shell/src/main/java/alluxio/cli/fsadmin/command/BackupCommand.java

Fixes https://github.com/Alluxio/alluxio/issues/8979

Show progress for taking/applying backups

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
tests/src/test/java/alluxio/client/fs/ShimFileSystemIntegrationTest.java

For handling foreign URIs that are not mounted to Alluxio. 
https://github.com/Alluxio/alluxio/issues/9231

Implement auto-mount for Transparent URIs

---

core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java

Resolves issue https://github.com/Alluxio/alluxio/issues/9739

Remove inode from TTL buckets when deleting the inode

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcClient.java
core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcServer.java

Fixes https://github.com/Alluxio/alluxio/issues/9851

Use seperate gRPC properties for copycat transport

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
dev/scripts/src/alluxio.org/build-distribution/cmd/common.go
dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
docs/cn/ufs/HDFS.md
docs/cn/ufs/secure-HDFS.md
docs/en/ufs/HDFS.md
pom.xml
shaded/hadoop/pom.xml
underfs/hdfs/pom.xml

Fix https://github.com/Alluxio/alluxio/issues/9753

Update default HDFS client version to 2.7

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalWriter.java

Fixes https://github.com/Alluxio/alluxio/issues/9852

Define a property for copycat write timeout

---

core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java

Improve the error message when Zookeeper and Raft are both configured

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java

Fixes https://github.com/Alluxio/alluxio/issues/9862

Define prop for setting copycat append batch size

---

core/common/src/main/java/alluxio/cli/AbstractShell.java
shell/src/main/java/alluxio/cli/fsadmin/command/JournalCommand.java
shell/src/main/java/alluxio/cli/fsadmin/journal/CheckpointCommand.java
shell/src/main/java/alluxio/cli/fsadmin/journal/QuorumCommand.java
shell/src/main/java/alluxio/cli/fsadmin/journal/QuorumInfoCommand.java
shell/src/main/java/alluxio/cli/fsadmin/journal/QuorumRemoveCommand.java
tests/src/test/java/alluxio/client/cli/fsadmin/command/JournalCommandIntegrationTest.java
tests/src/test/java/alluxio/client/cli/fsadmin/command/QuorumCommandIntegrationTest.java

Fixes https://github.com/Alluxio/alluxio/issues/9542

Unify journal related fsadmin commands

---

job/server/src/main/java/alluxio/master/job/JobMaster.java

Fix NullPointer bug in JobMaster.workerHeartbeat()

---

core/common/src/main/java/alluxio/heartbeat/HeartbeatThread.java

Fix comment in HeartbeatThread.HeartbeatThread()

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java

fixes #9552
Cherry-picking changes from #9622 
If allow_other fuse option is given, the file/dir created by other users should show its actual creator instead of showing the user who mounted the fuse filesystem.
In this PR, create file and create directory will show real owner and group.

Support true owner and group by Alluxio FUSE with allow_other options

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md

Refactor the layout depending on the chosen deployment mechanism and add more troubleshooting instructions.

Improve k8s docs

---

job/client/src/main/java/alluxio/client/job/JobGrpcClientUtils.java

Print retry count for JobGrpcClientUtils.run()

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

When FSM starts with many persist requests, parsing configuration values for every request has a high cost.

Move configuration parsing out of looping scope

---

docs/cn/Overview.md
docs/en/Overview.md

[DOCFIX] Update Chinese Overview.md and fix typo in English Overview.md

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md
integration/kubernetes/helm/alluxio/templates/alluxio-master.yaml
integration/kubernetes/helm/alluxio/templates/alluxio-worker.yaml
integration/kubernetes/multiMaster-embeddedJournal/alluxio-master.yaml.template
integration/kubernetes/multiMaster-embeddedJournal/alluxio-worker.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/alluxio-master.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/alluxio-worker.yaml.template
integration/kubernetes/singleMaster-localJournal/alluxio-master.yaml.template
integration/kubernetes/singleMaster-localJournal/alluxio-worker.yaml.template

This is a doc change adding doc on how to upgrade Alluxio in a K8s environment.

[DOCFIX] Add doc on how to upgrade Alluxio in K8s

---

core/base/pom.xml
core/client/runtime/pom.xml
shaded/client/pom.xml
shaded/pom.xml

Modify the Alluxio core client runtime module to publish alluxio core client runtime jar with dependencies when releasing Alluxio.
Fix https://github.com/Alluxio/alluxio/issues/9988

Add alluxio core client runtime shaded jar

---

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java

Add check when mounting an S3 bucket at root to see if bucket exists

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

Fix https://github.com/Alluxio/alluxio/issues/9647

Make Persist jobs write to dest directly on object store

---

experimental/table/server/common/src/test/java/alluxio/table/common/udb/UdbConfigurationTest.java
experimental/table/server/master/src/test/java/alluxio/master/catalog/AlluxioCatalogTest.java
experimental/table/server/under/hive/src/main/java/alluxio/table/under/hive/util/PathTranslator.java
experimental/table/server/under/hive/src/test/java/alluxio/table/under/hive/HiveDatabaseTest.java
experimental/table/server/under/hive/src/test/java/alluxio/table/under/hive/util/PathTranslatorTest.java

This PR adds a number of tests against some core portions
of the Alluxio catalog service. More tests to be added.

Add unit tests for Alluxio catalog service

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md

@apc999 @calvinjia fyi
@jiacheliu3 we can can update the docs further post-merge

Update stale K8s docs after directory restructure

---

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java

Reverts #9984 and reopens #9948

Revert isDirectory check due to issues with mounting empty buckets

---

dev/jenkins/build.sh
dev/jenkins/run_docker.sh

This prevents users from accidentally deleting local changes

Set the default to not clean the git repo

---

webui/package.json
webui/pom.xml

basically, maven puts a quote around each parameter, and forces npm to take the entire parameter as a single parameter.

Fix the way we pass parameters to lerna so it is happy

---

assembly/server/pom.xml
table/server/common/src/main/java/alluxio/table/common/LayoutRegistry.java
table/server/common/src/main/java/alluxio/table/common/udb/UnderDatabaseRegistry.java
table/server/master/src/main/java/alluxio/master/table/Table.java
table/server/under/hive/pom.xml
table/server/under/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java
table/server/under/pom.xml

Load libraries from the lib/ directory, instead of hard coding the dependency in the pom files.

Load libraries from lib/ directory

---

core/server/worker/src/main/java/alluxio/worker/block/UfsInputStreamManager.java

Print ExecutionException

---

docs/en/advanced/Performance-Tuning.md

Add docs on how to use persist blacklist

Add docs for persist blacklist

---

pom.xml
underfs/oss/src/main/java/alluxio/underfs/oss/OSSInputStream.java
underfs/oss/src/main/java/alluxio/underfs/oss/OSSOutputStream.java
underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
underfs/oss/src/test/java/alluxio/underfs/oss/OSSInputStreamTest.java
underfs/oss/src/test/java/alluxio/underfs/oss/OSSOutputStreamTest.java

- Make OSS Java Client up to date with 3.6.0.
- Change the new API interface.

Upgrade OSS Java Client to 3.6.0

---

core/transport/src/grpc/job_master.proto
core/transport/src/main/java/alluxio/grpc/JobInfo.java
core/transport/src/main/java/alluxio/grpc/JobInfoOrBuilder.java
core/transport/src/main/java/alluxio/grpc/JobMasterProto.java
job/common/src/main/java/alluxio/job/wire/JobInfo.java
job/common/src/test/java/alluxio/job/wire/JobInfoTest.java
job/server/src/test/java/alluxio/master/job/JobCoordinatorTest.java
shell/src/main/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommand.java
shell/src/main/java/alluxio/cli/job/command/StatCommand.java
shell/src/test/java/alluxio/cli/fsadmin/report/JobServiceMetricsCommandTest.java
tests/src/test/java/alluxio/client/cli/job/StatCommandTest.java

Add Job Definition Names to Job Stat command

---

core/common/src/main/java/alluxio/conf/PropertyKey.java

Original 3sec is too frequent.

Increase default user conf sync interval

---

integration/kubernetes/alluxio-fuse.yaml.template
integration/kubernetes/helm-chart/alluxio/values.yaml

This change sets resource limits and requests for fuse-client in K8s.

Set fuse resource in K8s YAML template

---

integration/kubernetes/alluxio-fuse-client.yaml.template
integration/kubernetes/alluxio-fuse.yaml.template
integration/kubernetes/helm-generate.sh
integration/kubernetes/multiMaster-embeddedJournal/alluxio-configmap.yaml.template
integration/kubernetes/multiMaster-embeddedJournal/job/alluxio-format-journal-job.yaml.template
integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-service.yaml.template
integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-statefulset.yaml.template
integration/kubernetes/multiMaster-embeddedJournal/worker/alluxio-worker-daemonset.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/alluxio-configmap.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/job/alluxio-format-journal-job.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-service.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-statefulset.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/worker/alluxio-worker-daemonset.yaml.template
integration/kubernetes/singleMaster-localJournal/alluxio-configmap.yaml.template
integration/kubernetes/singleMaster-localJournal/job/alluxio-format-journal-job.yaml.template
integration/kubernetes/singleMaster-localJournal/master/alluxio-master-service.yaml.template
integration/kubernetes/singleMaster-localJournal/master/alluxio-master-statefulset.yaml.template
integration/kubernetes/singleMaster-localJournal/worker/alluxio-worker-daemonset.yaml.template

Explicitly define release name in `helm-generate.sh`

Update helm release name

---

docs/en/advanced/Tiered-Locality.md
docs/en/compute/Hadoop-MapReduce.md
docs/en/compute/Spark-On-Kubernetes.md
docs/en/compute/Spark.md
docs/en/deploy/Running-Alluxio-On-Kubernetes.md

Docs updated in this PR:
- Tiered Locality
- Hadoop MapReduce
- Spark
- K8s
Changes are mostly mechanical/grammar. Content is not severely changed

[DOCFIX] Update some docs for 2.1.0

---

docs/en/basic/Command-Line-Interface.md

@gpang Could you update this page with a section on `table`?
@bradyoo Could you update this page with a section on `job`?
@chcn Could you update the page with sections on each of the `distributed*` commands `bin/alluxio fs`?

[DOCFIX] Update CLI docs

---

docs/en/advanced/Scalability-Tuning.md

Improves heap size calculations.

[DOCFIX] Update scalability tuning docs

---

docs/en/operation/Metastore.md

Added a section for migrating data between metastore types.
[skip ci]

[DOCFIX] Improve metastore doc

---

docs/en/ufs/HDFS.md

Update HDFS default version and remove reference to 1.x

---

docs/en/operation/Troubleshooting.md

Need to get rid of this old command. Purging with extreme prejudice.
[skip ci]

[DOCFIX] Remove reference to old command

---

shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
tests/src/test/java/alluxio/client/cli/fs/command/LsCommandIntegrationTest.java

Allow extra arguments as directories for ls command

---

docs/en/structured-data/transformation-service.md
table/shell/src/main/java/alluxio/cli/table/command/TransformTableCommand.java

Add doc for transformation

---

core/common/src/test/java/alluxio/concurrent/CountingLatchTest.java

Flaked at: https://amplab.cs.berkeley.edu/jenkins/job/Alluxio-Pull-Request-Builder/6593/console

Deflake CountingLatchTest

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md

This change:
1. Adds a bunch of notes on caveats
2. Removes redundant instruction on formatting journal job
3. Adds one note to Troubleshooting
4. Corrects a bunch of typos

[DOCFIX] Improve K8s doc

---

core/server/common/src/main/java/alluxio/master/journal/raft/transport/CopycatGrpcConnection.java

Closing client-side grpc streams will get pinged ponged from server for gRPC transport. This is to avoid scheduling a new task when it will exit immediately due to being closed already.

Avoid scheduling close task if connection is already closed

---

docs/en/deploy/Running-Alluxio-On-Docker.md

This change corrects the Alluxio-Docker deployment doc.
1. Correct JAVA OPTs for docker deployment in host network and bridge network
2. Simplify HA related doc by adding Refs
3. Various typos and format issues

[DOCFIX] Improve Docker documentation

---

shaded/client/pom.xml
tests/pom.xml
webui/pom.xml

These updates are required for us to be able to run a release with
- `mvn release:prepare -Pmesos`
- `mvn release:perform`

Update poms for release

---

docs/_config.yml

This is a one-liner fix for Helm version in doc, in complement of [#10384 ]
Ref: https://github.com/Alluxio/alluxio/pull/10396

Update Helm version in doc

---

pom.xml
shaded/client/pom.xml
shaded/pom.xml

Add alluxio shaded client jar
Fix https://github.com/Alluxio/alluxio/issues/9988
[This is a manual PR to cherry-pick committed PR #10004 into target branch branch-1.8]

Add alluxio shaded client jar

---

shaded/client/pom.xml

[This is a manual PR to cherry-pick committed PR #10351 into target branch branch-1.8]

Include sources for shaded client artifact

---

core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java

Because a semaphore is used to track all parties that requires a flush, ticket list need not be synchronized but could be accessed concurrently.

Remove unnecessary lock to improve async journal writer concurrency

---

docs/en/compute/HBase.md

This doc change updates how Alluxio can work with HBase 2.0. One extra parameter needs to be configured. Minor format updates besides that.

[DOCFIX] Improve HBase doc

---

docs/en/cloud/Google-Dataproc.md

syncing with tutorial: https://www.alluxio.io/products/google-cloud/gcp-dataproc-tutorial/

Update dataproc docs

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
core/server/master/src/main/java/alluxio/master/file/contexts/CallTracker.java
core/server/master/src/main/java/alluxio/master/file/contexts/GrpcCallTracker.java
core/server/master/src/main/java/alluxio/master/file/contexts/ListStatusContext.java
core/server/master/src/main/java/alluxio/master/file/contexts/OperationContext.java
core/server/master/src/main/java/alluxio/master/file/contexts/SetAclContext.java
core/server/master/src/main/java/alluxio/master/file/contexts/SetAttributeContext.java

Fixes https://github.com/Alluxio/alluxio/issues/10544

Implement support for terminating cancelled RPCs

---

docs/en/operation/Metrics-System.md

Improve the metrics-system docs to include detailed information of supported metrics.

[DOCFIX] Modify metric system docs

---

core/common/src/main/java/alluxio/conf/path/TrieNode.java
core/common/src/test/java/alluxio/conf/path/TrieNodeTest.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

This change adds new functions to the trie node to enable removing nodes and more ways to traverse the trie.

Improve trie search

---

docs/_plugins/accordion.rb
docs/_plugins/collapsible.rb
docs/en/cloud/AWS-EMR.md

and fix accordion blocks in EMR

Add accordion plugin files

---

docs/cn/contributor/Contributor-Getting-Started.md

Remove duplicate paragraphs from cn version

[DOCFIX] Remove duplicate paragraphs

---

underfs/hdfs/pom.xml

The version previously was 2.7.4-SNAPSHOT which was automatically
updated by the maven release plugin. 2.7.3 is the correct version.

Change ufs.hadoop.version to 2.7.3

---

tests/src/test/java/alluxio/job/master/JobMasterIntegrationTest.java
tests/src/test/java/alluxio/job/util/JobTestUtils.java

JobMaster has no guarantee that the jobs will be started in order. Route around this by actually waiting for the job to start running.

Fix Flaky JobMasterIntegrationTest

---

shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java

Handle too many attempts properly in DistributedLoadCommand

---

core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java

Populate worker webUI fileInfos when blocks are present

---

core/common/src/main/java/alluxio/metrics/MasterMetrics.java
core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalWriter.java
core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java
core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java

Add metrics to Alluxio journal for easy-debugging and monitoring.

Add journal flush, flush failure, ufs journal recover metrics

---

core/common/src/main/java/alluxio/metrics/MetricsSystem.java
core/server/common/src/main/java/alluxio/master/BackupManager.java
core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java
core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java

Add ResetAllMetrics logic to the existing MetricsSystem.

Add MetricsSystem resetAll logic

---

job/common/src/main/java/alluxio/job/wire/JobServiceSummary.java
job/common/src/test/java/alluxio/job/wire/JobServiceSummaryTest.java

Should be patched for 2.1 
Fixes https://github.com/Alluxio/alluxio/issues/10647
CC: @calvinjia

Fix JobServiceSummary for workflows

---

docs/en/api/POSIX-API.md
docs/en/compute/Hadoop-MapReduce.md
docs/en/compute/Hive.md
docs/en/compute/Presto.md
docs/en/compute/Spark.md
docs/en/core-services/Transformation.md
docs/en/deploy/Running-Alluxio-On-Kubernetes.md
docs/en/operation/Configuration.md
docs/en/operation/User-CLI.md
docs/en/ufs/S3.md

pr-link: Alluxio/alluxio#10670
change-id: cid-c73b1afe77b551e0a17ab12b467d0ead6300975b

[DOCFIX] Fix doc links and anchor tags

---

docs/en/cloud/AWS-EMR.md

Add a note on compatibility of AWS EMR command

---

core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
core/client/fs/src/main/java/alluxio/client/file/cache/CacheEvictor.java
core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileSystem.java
core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
core/client/fs/src/main/java/alluxio/client/file/cache/MetaStore.java
core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
core/common/src/main/java/alluxio/util/CommonUtils.java

Introduce local cache on client side

Add skeleton implementation

---

core/client/fs/src/main/java/alluxio/client/block/BlockMasterClientPool.java
core/client/fs/src/main/java/alluxio/client/file/CachingFileSystem.java
core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClientPool.java
core/client/fs/src/test/java/alluxio/client/file/FileSystemContextTest.java
core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
tests/src/test/java/alluxio/client/fs/ConcurrentDeleteIntegrationTest.java
tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterCreateTest.java
tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterLoadMetadataTest.java
tests/src/test/java/alluxio/client/fs/ConcurrentFileSystemMasterSetTtlTest.java
tests/src/test/java/alluxio/client/fs/ConcurrentRenameIntegrationTest.java
tests/src/test/java/alluxio/client/fs/FileInStreamConcurrencyIntegrationTest.java

orig-pr: #10717
orig-commit: b178d47
orig-commit-author: Zachary Blanco zac@alluxio.com

Use DynamicResourcePool for FS and Block clients

---

core/client/fs/src/test/java/alluxio/client/file/MockFileInStream.java
core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java

Some of these won't pass until we adopt the new APIs.

Add more tests for LocalCacheFileInStream

---

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java

This PR also uses the newer API to do partial page reads correctly.

Implement positioned read

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalConfiguration.java
core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingProxy.java
core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingServer.java
core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingTransport.java

Fixes https://github.com/Alluxio/alluxio/issues/10693

Add listening address for embedded journal

---

core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreOptions.java

combine the factory methods of `PageStore` and `PageStoreOptions`.

Simplify page store creation

---

core/server/common/src/main/java/alluxio/master/BackupManager.java

orig-pr: #10709
orig-commit: 2106231
orig-commit-author: LuQQiu luqiujob@gmail.com

Fix the backup restore metrics name

---

table/server/common/src/main/java/alluxio/master/table/DatabaseInfo.java
table/server/master/src/main/java/alluxio/master/table/AlluxioCatalog.java
table/server/master/src/main/java/alluxio/master/table/Database.java

Location and Comment are optional fields, so we must treat them as such..
Apparently, so is the Owner and OwnerType

Fix NPE in GetDatabase

---

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/activesync/SupportedHdfsActiveSyncProvider.java

Fix the counting of events for ActiveSync logging

Fix logging error in ActiveSync

---

core/common/src/main/java/alluxio/conf/RemovedKey.java

The keys were recently added back in another PR but this list wasn't
updated properly to reflect that change.

Remove keys from RemovedKeys list

---

core/common/pom.xml
core/common/src/main/java/alluxio/util/EnvironmentUtils.java
core/server/master/src/main/java/alluxio/master/meta/UpdateCheck.java
core/server/master/src/test/java/alluxio/master/meta/UpdateCheckTest.java

Add instance check

---

core/common/src/main/java/alluxio/grpc/GrpcChannel.java
core/common/src/main/java/alluxio/grpc/GrpcChannelKey.java
core/common/src/main/java/alluxio/grpc/GrpcServer.java
core/common/src/main/java/alluxio/grpc/GrpcServerAddress.java
core/common/src/main/java/alluxio/security/authentication/AbstractSaslClientHandler.java
core/common/src/main/java/alluxio/security/authentication/AuthenticatedChannelClientDriver.java
core/common/src/main/java/alluxio/security/authentication/AuthenticatedChannelServerDriver.java
core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java
core/server/common/src/main/java/alluxio/master/transport/GrpcMessagingClientConnection.java

Client level retries were sometimes ineffective due to narrow handling of exceptions.

Fix gRPC exception handling and improve traces

---

core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileSystem.java
core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
core/common/src/main/java/alluxio/conf/PropertyKey.java

Better division for the file system configuration and constructors.

Refactor for local cache

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/main/java/alluxio/heartbeat/HeartbeatContext.java
core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
core/server/master/src/main/java/alluxio/master/meta/MetaMaster.java
core/server/master/src/main/java/alluxio/master/meta/UpdateChecker.java

Change update check to check every 7 days instead of once when master starts.

Update check periodically

---

docs/_config.yml
docs/_layouts/global.html
docs/cn/Getting-Started.md
docs/cn/contributor/Building-Alluxio-From-Source.md
docs/cn/deploy/Running-Alluxio-Locally.md
docs/cn/deploy/Running-Alluxio-On-Docker.md
docs/cn/ufs/GCS.md
docs/cn/ufs/S3.md
docs/en/Getting-Started.md
docs/en/advanced/Namespace-Management.md
docs/en/contributor/Building-Alluxio-From-Source.md
docs/en/deploy/Running-Alluxio-Locally.md
docs/en/deploy/Running-Alluxio-On-a-Cluster.md
docs/en/ufs/HDFS.md
docs/en/ufs/S3.md

orig-pr: Alluxio/alluxio#10831
orig-commit: Alluxio/alluxio@0d1813bb8f8e7d7fa0ec84d0aea6aa5af74ad681
orig-commit-author: Rico Chiu <Xenorith@users.noreply.github.com>
pr-link: Alluxio/alluxio#10839
change-id: cid-07fa69cbfa91d587664ac1732917fd57ed28bdce

[DOCFIX] Remove ALLUXIO_RELEASED_VERSION from docs/_config.yml

---

examples/src/main/java/alluxio/examples/UnderFileSystemCommonOperations.java

Increase the retry timeout and interval for the ufs contract tests.

Allow eventual consistency in ufs contract tests

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
core/common/src/main/java/alluxio/metrics/MetricsSystem.java
core/server/worker/src/main/java/alluxio/worker/block/AsyncCacheRequestManager.java
core/server/worker/src/main/java/alluxio/worker/block/BlockMetricsReporter.java

Refactor async cache and block related metric keys

Refactor leftover metric keys

---

docs/en/operation/Admin-CLI.md

[DOCFIX] Fix Admin-CLI page typo

---

pom.xml

No more annoying stream warnings.

Bump gRPC/netty/protobuf versions

---

core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
core/client/fs/src/main/java/alluxio/client/file/DelegatingFileSystem.java
core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
core/client/fs/src/main/java/alluxio/client/file/FileSystemCache.java
core/client/fs/src/main/java/alluxio/client/file/LocalCacheFileSystem.java

to potentially save a RPC `getStatus`

Add openFile based on URIStatus

---

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheFileInStreamTest.java

This is consistent with InputStream's API.

Support external stores which do not read in full

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksBlockStore.java
core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksInodeStore.java
core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksUtils.java
core/server/master/src/test/java/alluxio/master/metastore/rocks/RocksBlockStoreTest.java
minicluster/src/main/java/alluxio/multi/process/PortCoordination.java
tests/src/test/java/alluxio/server/ft/journal/JournalBackupIntegrationTest.java

This is to get rocks db out of prefix seek mode, under which iterators seekToFirst/Last APIs are ineffective. See https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes for more context.
Fixes https://github.com/Alluxio/alluxio/issues/10858

Fix iteration for RocksBlockStore

---

core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
core/common/src/main/java/alluxio/client/file/URIStatus.java
core/common/src/main/java/alluxio/metrics/MetricKey.java
core/common/src/main/java/alluxio/wire/FileInfo.java

Improve local cache

---

job/common/src/main/java/alluxio/job/plan/transform/CompactConfig.java
shell/src/main/java/alluxio/cli/job/command/StatCommand.java

Also rearrange CompactConfig so that more important information comes first.

Increase job description print length

---

core/transport/src/grpc/job_master.proto
job/common/src/main/java/alluxio/job/plan/meta/PlanInfo.java
job/common/src/main/java/alluxio/job/wire/TaskInfo.java
job/common/src/test/java/alluxio/job/wire/TaskInfoTest.java
job/server/src/main/java/alluxio/master/job/plan/PlanCoordinator.java
job/server/src/main/java/alluxio/worker/job/task/TaskExecutorManager.java
shell/src/main/java/alluxio/cli/job/command/StatCommand.java
tests/src/test/java/alluxio/client/cli/job/StatCommandTest.java

Example:
```
ID: 1582304046978
Name: Compact
Description: CompactConfig{input=alluxio://SpeedcorePartitionedTable-masters-1:19998/catalog/movielens/tables/ratings_part/hive/rating=1.5, output=alluxio://SpeedcorePartitionedTable-masters-1:19998/catalog/mov...
Status: COMPLETED
Task 0
Worker: SpeedcorePartitionedTable-workers-1
Description: [CompactTask{inputs=[alluxio://SpeedcorePartitionedTable-masters-1:19998/catalog/movielens/tables/ratings_part/hive/rating=1.5/000004_0], output=alluxio://SpeedcorePartitionedTable-masters-1:19998/...	
Status: COMPLETED
```

Add description for Tasks in job stat

---

integration/kubernetes/alluxio-fuse-client.yaml.template
integration/kubernetes/alluxio-fuse.yaml.template
integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
integration/kubernetes/helm-chart/alluxio/Chart.yaml
integration/kubernetes/helm-chart/alluxio/templates/fuse/client-daemonset.yaml
integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
integration/kubernetes/helm-chart/alluxio/templates/job/format-journal-job.yaml
integration/kubernetes/helm-chart/alluxio/values.yaml
integration/kubernetes/helm-generate.sh
integration/kubernetes/multiMaster-embeddedJournal/alluxio-configmap.yaml.template
integration/kubernetes/multiMaster-embeddedJournal/job/alluxio-format-journal-job.yaml.template
integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-service.yaml.template
integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-statefulset.yaml.template
integration/kubernetes/multiMaster-embeddedJournal/worker/alluxio-worker-daemonset.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/alluxio-configmap.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/job/alluxio-format-journal-job.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-service.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-statefulset.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/worker/alluxio-worker-daemonset.yaml.template
integration/kubernetes/singleMaster-localJournal/alluxio-configmap.yaml.template
integration/kubernetes/singleMaster-localJournal/job/alluxio-format-journal-job.yaml.template
integration/kubernetes/singleMaster-localJournal/master/alluxio-master-service.yaml.template
integration/kubernetes/singleMaster-localJournal/master/alluxio-master-statefulset.yaml.template
integration/kubernetes/singleMaster-localJournal/worker/alluxio-worker-daemonset.yaml.template

orig-pr: #10997 
orig-commit: 1fd4789
orig-commit-author: Jiacheng Liu <jiacheliu3@gmail.com>

Port changes of [#10997] to branch-2.2

---

docs/en/contributor/Building-Alluxio-From-Source.md
docs/en/contributor/contributor-tools.md

Improves the expression and formats slightly. Also mention in IDE integration.

[DOCFIX] Improve doc for proto build

---

docs/en/api/POSIX-API.md

Update POSIX API documentation

---

docs/en/contributor/Building-Alluxio-From-Source.md
docs/en/contributor/contributor-tools.md

Improves the expression and formats slightly. Also mention in IDE integration.
pr-link: Alluxio/alluxio#11061
change-id: cid-3850948560d5325da060916849ae38b48a91b6f8

Port changes of [#11061] to branch-2.2

---

docs/en/deploy/Running-Alluxio-On-Docker.md

A minor change in expression due to version update

[DOCFIX] Update docker doc

---

core/common/src/main/java/alluxio/conf/PropertyKey.java

Update scope on a property

---

docs/en/cloud/AWS-EMR.md

Remove references to AMI from the doc
Add NVME usage to doc

[DOCFIX] Update EMR docs

---

table/server/master/src/main/java/alluxio/master/table/Database.java
table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java

Avoid NPE for optional ownerType field

---

docs/en/compute/Spark-On-Kubernetes.md
docs/en/deploy/Running-Alluxio-On-Kubernetes.md

Added multiple troubleshooting common issues.
Updated some instructions.

[DOCFIX] Update Spark-on-K8s doc

---

docs/en/operation/Admin-CLI.md

Reorder alphabetically
Update wording

[DOCFIX] Update admin CLI docs

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md

Add specification for Helm version in prerequisites. 
Add Format Journal section for Helm and kubectl deployments.
Add FUSE deployment config for Helm deployment

[DOCFIX] Update kubernetes documentation

---

docs/en/contributor/Contributor-Getting-Started.md

[DOCFIX] Fix link in contributor getting started

---

table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveUtils.java
table/server/underdb/hive/src/test/java/alluxio/table/under/hive/HiveUtilsTest.java

Avoid NPE when converting hive col stats to proto

---

integration/kubernetes/alluxio-fuse-client.yaml.template
integration/kubernetes/alluxio-fuse.yaml.template
integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
integration/kubernetes/helm-chart/alluxio/Chart.yaml
integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl
integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml
integration/kubernetes/multiMaster-embeddedJournal/alluxio-configmap.yaml.template
integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-service.yaml.template
integration/kubernetes/multiMaster-embeddedJournal/master/alluxio-master-statefulset.yaml.template
integration/kubernetes/multiMaster-embeddedJournal/worker/alluxio-worker-daemonset.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/alluxio-configmap.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-service.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/master/alluxio-master-statefulset.yaml.template
integration/kubernetes/singleMaster-hdfsJournal/worker/alluxio-worker-daemonset.yaml.template
integration/kubernetes/singleMaster-localJournal/alluxio-configmap.yaml.template
integration/kubernetes/singleMaster-localJournal/master/alluxio-master-service.yaml.template
integration/kubernetes/singleMaster-localJournal/master/alluxio-master-statefulset.yaml.template
integration/kubernetes/singleMaster-localJournal/worker/alluxio-worker-daemonset.yaml.template

This addresses https://github.com/Alluxio/alluxio/issues/11079

Add readiness and liveness probe to Alluxio containers in K8s

---

docs/_config.yml
docs/en/deploy/Running-Alluxio-On-Kubernetes.md

orig-pr: https://github.com/Alluxio/alluxio/pull/11187
orig-commit-author: Adit Madan <madanadit@gmail.com>

[DOCFIX] Add K8s docs pointer to public helm repo

---

core/transport/src/main/proto/grpc/job_master.proto
job/client/src/main/java/alluxio/client/job/JobMasterClient.java
job/client/src/main/java/alluxio/client/job/RetryHandlingJobMasterClient.java
job/server/src/main/java/alluxio/master/job/JobMaster.java
job/server/src/main/java/alluxio/master/job/JobMasterClientServiceHandler.java
shell/src/main/java/alluxio/cli/job/command/StatCommand.java

Fixes https://github.com/Alluxio/alluxio/issues/11184

Make Default JobMasterClient.getJobStatus non-verbose

---

bin/alluxio-mount.sh

With the changes above, we can use alluxio with FreeBSD.

Update alluxio-mount.sh for FreeBSD

---

webui/master/src/index.tsx
webui/worker/src/index.tsx

Add type to fix Web UI build bug

---

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
webui/common/package.json
webui/master/package.json
webui/npm-shrinkwrap.json
webui/pom.xml
webui/worker/package.json

Removing this linter for now due to issues with formatting during tarball generation.

Replace Web UI linter in build command with maven exec plugin

---

docs/en/operation/Journal.md

- This important property `alluxio.master.journal.type` was not mentioned at all in doc
Address https://github.com/Alluxio/alluxio/issues/11213
- Stating embedded journal is now the default
- Explain more on UFS journal and embedded journal

Improve Journal Operation doc

---

integration/fuse/bin/alluxio-fuse

- Fix https://github.com/Alluxio/alluxio/issues/11282
- Improve echo messages

Improve Fuse start script

---

docs/en/operation/Journal.md

add UFS journal options configuration

[DOCFIX] Update the Journal

---

core/common/src/main/java/alluxio/underfs/BaseUnderFileSystem.java
examples/src/main/java/alluxio/examples/UnderFileSystemCommonOperations.java

Fixes: https://github.com/Alluxio/alluxio/issues/11339

Fix recursive ufs listing

---

core/common/src/main/java/alluxio/security/user/BaseUserState.java

There are multiple classes extending `UserState` with specific logic for `login()`. When an Exception is thrown, the exact class name will be helpful.

Improve UserState log

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java

In addition, make remote the default configuration for hdfs ufs

Use pread for all remote hdfs api read calls

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md
integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
integration/kubernetes/helm-generate.sh

This addresses https://github.com/Alluxio/alluxio/issues/11319
We upgrade the helm template generation commands from Helm 2 to Helm 3.

Upgrade helm command to support only helm 3

---

docs/en/core-services/Catalog.md
docs/en/operation/User-CLI.md

[DOCFIX] Add glue udb into docs

---

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
integration/kubernetes/helm-chart/alluxio/Chart.yaml

This updates Alluxio helm chart version to reflect some missing changes:
https://github.com/Alluxio/alluxio/pull/11370
https://github.com/Alluxio/alluxio/pull/11315
https://github.com/Alluxio/alluxio/pull/11324 (Included as Helm 3.X compatibility is verified)

Update Helm chart version to reflect changes

---

core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalLogWriter.java
core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalSystem.java
core/server/master/src/test/java/alluxio/master/journal/ufs/UfsJournalCheckpointThreadTest.java
core/server/master/src/test/java/alluxio/master/journal/ufs/UfsJournalLogWriterTest.java
core/server/master/src/test/java/alluxio/master/journal/ufs/UfsJournalReaderTest.java

Prevent secondary UFS journal from modifying journal files

---

core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
core/client/fs/src/main/java/alluxio/client/file/cache/store/LocalPageStore.java

Introduce two changes:
(1) cleanup intermediate state when fail to add a new page
(2) make sure unchecked exception not esculated

Improve alluxio client local cache

---

docs/en/deploy/Requirements.md

The table of contents is missing.
Also there's a port on job worker not mentioned.

[DOCFIX] Improve software requirement doc

---

core/server/worker/src/main/java/alluxio/worker/block/annotator/DefaultBlockIterator.java
core/server/worker/src/main/java/alluxio/worker/block/annotator/SortedBlockSet.java

LRFU can generate sorted-fields with equal value.
This PR fixes bugs related to this edge case.

Fix termination conditions for LRFU

---

docs/en/api/FS-API.md

Based on feedback from users
- Add information about POM dependency (moved from original S3 doc)
- Add an example of using Hadoop compatible API

Improve FileSystem API doc

---

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java

When `LocalPageStore` failed to put a page due to reasons like disk full, the state was not cleaned in `LocalCacheManager`. This PR addes
- Logic to clean up the state on failed page put in meta store
- Logic to clean up a page on failed page get
- Tests

Clean up state on failed PUT

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md
integration/docker/entrypoint.sh
integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
integration/kubernetes/helm-chart/alluxio/Chart.yaml
integration/kubernetes/helm-chart/alluxio/templates/fuse/client-daemonset.yaml
integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
integration/kubernetes/helm-chart/alluxio/values.yaml

Fix fuse restart failed

---

docs/_config.yml
docs/en/cloud/AWS-EMR.md
docs/en/cloud/Alluxio-Presto-AMI.md
docs/en/cloud/Google-Dataproc.md
docs/en/deploy/Running-Alluxio-On-Kubernetes.md

Rename "Alluxio in the Cloud" to "Cloud Native"

Add Cloud Native section to docs

---

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
integration/kubernetes/helm-chart/alluxio/Chart.yaml
integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml
integration/kubernetes/helm-chart/alluxio/templates/worker/domain-socket-pvc.yaml
integration/kubernetes/helm-chart/alluxio/values.yaml

This resolves https://github.com/Alluxio/alluxio/issues/11526

Add a root/nonroot switch to helm chart

---

integration/emr/alluxio-emr.sh

Allow user properties to override generated properties in emr bootstrap

---

shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java

Creating many clients in DistributedLoadCommand creates an issue in
certain environments. Reduce the number of clients and also remove the
parallelism around it to prevent race conditions when using the same
client.
pr-link: Alluxio/alluxio#11573
change-id: cid-e71e5b880da9643a3e9b67e9f6f4261f68867a93

Reduce number of clients in DistributedLoadCommand

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md
integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl
integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml
integration/kubernetes/helm-chart/alluxio/templates/worker/daemonset.yaml
integration/kubernetes/helm-chart/alluxio/templates/worker/domain-socket-pvc.yaml
integration/kubernetes/helm-chart/alluxio/values.yaml

This resolves:
1. Feature request https://github.com/Alluxio/alluxio/issues/11555
1. Comments under feature request https://github.com/Alluxio/alluxio/issues/11526#issuecomment-641687729

Support emptyDir for volumes and infer dnsPolicy from hostNetwork

---

integration/tools/hms/src/main/java/alluxio/cli/HmsValidationTool.java

get_table_req and get_table_objects_by_name_req are not supported by some older version hms client. Remove this test case

Remove getTableObjectReq from hms tool

---

integration/emr/alluxio-emr.sh

StartSync may fail if master doesn't come up quick

Wait for alluxio master to come up before startSync

---

core/server/master/src/main/java/alluxio/web/MasterWebServer.java
core/server/worker/src/main/java/alluxio/web/WorkerWebServer.java
pom.xml

Vulnerability: https://github.com/advisories/GHSA-84q7-p226-4x5w

Bump jetty version from 9.2.28 to 9.4.28

---

docs/en/ufs/Ozone.md

Fixes #11657 
Add an example configuration file to help avoid making mistakes

[DOCFIX] Add example Ozone configuration files

---

docs/en/deploy/Requirements.md

Add the software requirements for FUSE

[DOCFIX] Add software requirements for FUSE

---

docs/en/cloud/Alibaba-Cloud-ACK.md

1.Add a document for installing Alluxio on Alibaba Cloud production: ACK.

Add Alibaba Cloud ACK document

---

table/server/underdb/glue/src/main/java/alluxio/table/under/glue/GlueDatabase.java

Add null value check for glue fields.

Resolve null value for Glue fields

---

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java

Adding / to the keys was not a good idea.

Fix Object UFS edge case again

---

core/common/src/main/java/alluxio/cli/ValidationConfig.java
shell/src/main/java/alluxio/cli/HmsTests.java

Expose hms option names for triggering hms tests in places other than shell.

Add hms option names to core/common module

---

integration/dataproc/alluxio-dataproc.sh

Fixes #10439
Install and start alluxio as alluxio user

Modify alluxio dataproc

---

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
integration/kubernetes/helm-chart/alluxio/Chart.yaml
integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl

This resolves https://github.com/Alluxio/alluxio/issues/11778

Fix comma-separated medium types parsing in Helm chart

---

docs/cn/contributor/Contributor-Getting-Started.md

introduced in https://github.com/Alluxio/alluxio/pull/11774

[DOCFIX] Fix broken link in cn Contributor Getting Started

---

docs/en/cloud/Google-Dataproc.md
integration/dataproc/alluxio-dataproc.sh

Modify dataproc doc. 
Fix the bug that sync need to be run as `alluxio` user.
Add back the alluxio presto home.

Modify dataproc doc and fix small bugs

---

docs/cn/deploy/Running-Alluxio-On-Kubernetes.md

Revert changes in https://github.com/Alluxio/alluxio/pull/11815

Revert kubernetes docs

---

docs/en/contributor/Code-Conventions.md

compiled result on website is wrong due to a missing empty line

Fix format in Code-Conventions.md

---

integration/docker/entrypoint.sh

pr-link: Alluxio/alluxio#11722
change-id: cid-f5402843fcd24b10ff6bff73de5dc45371652350

Make the "MOUNT_POINT" docker env configurable

---

docs/cn/deploy/Running-Alluxio-On-Docker.md
docs/en/overview/Architecture.md

[DOCFIX] Update Chinese Docker Doc

---

pom.xml

No other dependencies changed in mvn dependency tree

Upgrade commons-logging to 1.2

---

pom.xml

```
< [INFO]    com.beust:jcommander:jar:1.48:compile
---
> [INFO]    com.beust:jcommander:jar:1.78:compile
```

Upgrade jcommander to 1.78

---

pom.xml

```
5844c5844
< [INFO]    org.javaswift:joss:jar:0.9.10:compile
---
> [INFO]    org.javaswift:joss:jar:0.10.4:compile
5850d5849
< [INFO]    commons-lang:commons-lang:jar:2.6:compile
```

Upgrade joss to 0.10.4

---

underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java

alluxio runUfsTests --path gs://
has 
Caused by: org.jets3t.service.ServiceException: Request Error: Invalid class name: org.jets3t.service.utils.RestUtils$ConnManagerFactory issue.
Using classloader solve the issue

Fix jets3t class not found issue

---

pom.xml
webui/npm-shrinkwrap.json

Update maven plugins to modern versions
Also gives us ability to generate dependency update report etc

Update maven plugins

---

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
integration/kubernetes/helm-chart/alluxio/Chart.yaml
integration/kubernetes/helm-chart/alluxio/templates/_helpers.tpl
integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml

Solves https://github.com/Alluxio/alluxio/issues/11881

Change K8s liveness/readiness probe to TCP

---

underfs/wasb/src/main/java/alluxio/underfs/wasb/WasbUnderFileSystem.java

without this fix, WASB ufs always set block size to 512MB (default value returned by wasb UFS)
the block size for WASB is artificial since it is object store, but always having a constant block size so large could affect Alluxio performance

Fix Wasb UFS to respect block size

---

docs/cn/ufs/Ozone.md

Two consecutive empty lines at the end of the Ozone doc, remove one of them

[DOCFIX] Remove one of the empty lines at the end of Ozone doc

---

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
core/common/src/main/java/alluxio/metrics/MetricKey.java

- Improve metrics counting for put/get/delete operations in LocalCacheManager
- separate counting different possible failure reasons with different counters

Cleanup metrics for local cache

---

integration/tools/validation/src/main/java/alluxio/cli/ValidateEnv.java

Fixes https://github.com/Alluxio/alluxio/issues/11793

Fix validateEnv statistics

---

docs/en/deploy/Requirements.md
docs/en/operation/Scalability-Tuning.md

Includes suggestions for metrics to monitor and hardware requirements.

Add node sizing recommendations to scalability tuning document

---

table/server/master/src/test/java/alluxio/master/table/transform/TransformManagerTest.java

This is fixed to no longer depend on timing to pass.

Fix flaky table test

---

core/client/fs/src/main/java/alluxio/client/file/cache/DefaultMetaStore.java
core/common/src/main/java/alluxio/metrics/MetricKey.java

Adds space used and pages stored as counters.

Add counters for space used and pages stored

---

core/server/common/pom.xml
core/server/common/src/main/java/alluxio/master/journal/DefaultJournalMaster.java
core/server/common/src/main/java/alluxio/master/journal/JournalMaster.java
core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalWriter.java
core/server/common/src/main/java/alluxio/master/journal/raft/RaftPrimarySelector.java
core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
core/server/master/src/main/java/alluxio/master/journal/tool/RaftJournalDumper.java
pom.xml
tests/src/test/java/alluxio/client/cli/JournalToolTest.java
tests/src/test/java/alluxio/server/ft/journal/TriggeredCheckpointTest.java
tests/src/test/java/alluxio/server/ft/journal/raft/EmbeddedJournalIntegrationTest.java

Initial changes for hooking up embedded journal state machine with ratis API.  Implemented leader election, journal application and taking snapshot on followers.

Migrate state machine to ratis

---

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/activesync/SupportedHdfsActiveSyncProvider.java

Consolidate the multiple messages into 1 line, and make it less frequent if logging is at INFO level.

Improve hdfs sync messages and spamminess

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
docs/en/ufs/Azure-Data-Lake.md
underfs/adl/pom.xml
underfs/adl/src/main/java/alluxio/underfs/adl/AdlUnderFileSystem.java
underfs/adl/src/main/java/alluxio/underfs/adl/AdlUnderFileSystemFactory.java
underfs/adl/src/main/resources/META-INF/services/alluxio.underfs.UnderFileSystemFactory
underfs/adl/src/test/java/alluxio/underfs/adl/AdlUnderFileSystemFactoryTest.java
underfs/adl/src/test/resources/log4j.properties
underfs/pom.xml

Adds ADL Gen1 UFS extension as a HDFS extension.
Attn @apc999 @madanadit

Add Azure Data Lake Gen 1 support for UFS

---

core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java

When journal is suspended, snapshot should not be taken because some entries included up to the snapshot index might not have been applied by the suspended journal applier.

Avoid taking snapshot during journal suspension

---

integration/emr/alluxio-emr.sh

in order to set all configurations before starting alluxio processes

Move presto config in emr to before starting alluxio

---

core/server/worker/src/main/java/alluxio/worker/grpc/AbstractWriteHandler.java
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AOutputStream.java

Reply with errors correctly in AbstractWriteHandler abort

---

docs/cn/contributor/Code-Conventions.md

Fix https://github.com/Alluxio/alluxio/issues/12131

[DOCFIX] Fix typo in Code-Conventions.md

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

add time series for read and write throughput

Add time series for throughput

---

pom.xml

This broke job and worker REST API docs

Downgrade swagger-maven-plugin from 3.1.7 back to 3.1.1

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java

Added a deadline for master ping requests.

Make polling client timeout properly on unresponsive masters

---

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java

Sometimes a master attempts to join a quorum during leader election. This change extends the retry period so the retry can extends pass an election. Also lower the log severity given its best effort nature.

Make master try harder when joininig a quorum

---

core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java

Sometimes a snapshot is ordered when the journal log is not consistent with the state machine. This change makes it more restrictive that snapshots can only be taken when a follower is in running state.

Make it more restrictive when a snapshot can be taken

---

docs/cn/Overview.md
docs/en/Overview.md

Fix https://github.com/Alluxio/alluxio/issues/12158

[DOCFIX] Fix broken link in overview page

---

docs/en/deploy/Requirements.md

Add a note for embedded journal memory requirement.

[DOCFIX] Update memory requirement in doc

---

docs/cn/deploy/Running-Alluxio-On-Docker.md
docs/en/deploy/Running-Alluxio-On-Docker.md

fix #12207
Add a FAQ chapter to the document.

Add a faq chapter in Running-Alluxio-On-Docker.md

---

docs/en/cloud/Google-Dataproc.md

note that example 2 that uses LOCAL as the alluxio_root_ufs_uri does not work

[DOCFIX] Update dataproc docs

---

docs/en/operation/Troubleshooting.md

Mention the changes to how the alluxio properties are collected by the changes in `collectInfo`

[DOCFIX] Improve collectInfo doc

---

docs/en/cloud/Alibaba-Cloud-ACK.md

Various minor doc improvements on the grammar/expression/format etc.

[DOCFIX] Improve Alibaba ACK doc

---

libexec/alluxio-config.sh

Fix https://github.com/Alluxio/alluxio/issues/12250

Support setting JAVA_HOME in alluxio-env.sh

---

conf/log4j.properties

This change reduces the amount of logs generated on a leader when one of the follower is offline.

Suppress more spammy Ratis logs

---

docs/cn/ufs/Ozone.md
docs/en/ufs/Ozone.md
pom.xml
shaded/ozone/pom.xml
shaded/pom.xml
underfs/ozone/pom.xml

#12202 
Something I should clarify:
- Add a new ozone shade module to avoid classCaseException for the following code from `org.apache.hadoop.ipc.ProtobufRpcEngine#invoke`
```java
final Message theRequest = (Message) args[1];
```
- Update the Ozone.md

Upgrade Ozone ufs to 1.0.0 version

---

docs/en/overview/Architecture.md

[DOCFIX] Clarify the consistency and writing with ASYNC_THROUGH

---

libexec/alluxio-config.sh

addresses https://github.com/Alluxio/alluxio/issues/12332

Remove extra parenthesis in libexec/alluxio-config.sh

---

examples/src/main/java/alluxio/examples/Performance.java

Make folder of Performance can be specified by argument

---

pom.xml

Revert "Upgrade JUnit 4.13 to 4.13.1 to fix security vulnerability"

---

tests/src/test/java/alluxio/server/ft/journal/TableMasterJournalIntegrationTest.java

Ignore TableMasterJournalIntegrationTest#JournalTransformDb

---

.github/workflows/java11_integration_tests.yml
.github/workflows/java11_unit_tests.yml
.github/workflows/java8_integration_tests.yml
.github/workflows/java8_unit_tests.yml

Adding SKIPCI or DOCFIX in the title of your pull request will skip all tests (except for checkstyle, findbugs, doc check)

Add SKIPCI

---

docs/en/operation/Admin-CLI.md
docs/en/overview/FAQ.md
docs/en/overview/Getting-Started.md
docs/en/overview/JobService.md
docs/en/overview/Use-Cases.md

More Inspection CLI will be added later.

[DOCFIX] Add Job Service docs

---

core/client/fs/src/main/java/alluxio/client/file/MetadataCachingBaseFileSystem.java
core/client/fs/src/test/java/alluxio/client/file/MetadataCachingBaseFileSystemTest.java
core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java

Fix https://github.com/Alluxio/alluxio/issues/12373

Avoid duplicates with metadata caching client on iterateStatus

---

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go

Support specific version of hadoop by generate-tarball

---

pom.xml

Upgrade swagger-maven-plugin from 3.1.1 to 3.1.7

---

core/server/proxy/src/main/java/alluxio/proxy/s3/S3Constants.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java

Add etag header to s3 api proxy

---

dev/scripts/src/alluxio.org/build-distribution/cmd/generate-tarball.go
dev/scripts/src/alluxio.org/build-distribution/cmd/root.go

Support custom ufs module of hadoop by generate-tarball

---

tests/src/test/java/alluxio/server/ft/journal/TableMasterJournalIntegrationTest.java

A few different fixes to remove the flakiness of these tests.
- reset the cluster between tests
- detach the db to cleanup
- wait for workers to register

Remove flakiness for table journal test

---

integration/fuse/src/main/native/libjnifuse/Makefile
integration/fuse/src/main/native/libjnifuse/jnifuse_fs.cc
integration/fuse/src/main/native/libjnifuse/jnifuse_fs.h
integration/fuse/src/main/native/libjnifuse/jnifuse_helper.cc
integration/fuse/src/main/native/libjnifuse/jnifuse_impls.cc
integration/fuse/src/main/native/libjnifuse/jnifuse_impls.h
integration/fuse/src/main/native/libjnifuse/operation.cc

Add rename operation to the c++ fs layer.

Add rename op to libjnifuse

---

core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java

fix https://github.com/Alluxio/alluxio/issues/12163

Allocate accurate initial block size when reading UFS blocks

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
core/server/worker/src/main/java/alluxio/worker/block/AsyncBlockRemover.java
core/server/worker/src/main/java/alluxio/worker/block/BlockLockManager.java
core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
core/server/worker/src/main/java/alluxio/worker/grpc/ShortCircuitBlockReadHandler.java

#12444
The metrics from `metrics/prometheus` is 
Worker_Block_Remover_BlocksToRemoved_Success_Count_XX 2.0
Worker_Block_Remover_BlocksToRemoved_Take_Count_XX 2.0
Worker_Block_Remover_BlocksToRemoved_Size 0.0
Worker_Block_Remover_RemovingBlocks_Size 0.0

Add block lock related metrics and catch throwable

---

docs/cn/deploy/Running-Alluxio-On-Docker.md

[DOCFIX] Fix the Wrong title of the run alluxio on docker cn document

---

pom.xml

Upgrade XStream version to 1.4.14 to fix Secure issue

---

core/common/src/main/java/alluxio/util/io/BufferUtils.java

pr-link: Alluxio/alluxio#12580
change-id: cid-90eb8c3c9b7aeaf3f92f49edc8462b828cbcb987

Remove synchronization on releasing directByteBuffer

---

core/common/src/main/java/alluxio/util/webui/UIMountPointInfo.java
webui/master/src/store/mounttable/types.tsx

Improve the ufs Capacity and used size to human readable

---

core/base/src/test/java/alluxio/collections/PairTest.java

fix https://github.com/Alluxio/new-contributor-tasks/issues/502

[SMALLFIX] Use static imports for standard test utilities in PairTest

---

core/base/src/main/java/alluxio/Constants.java
docs/cn/ufs/COS.md
docs/cn/ufs/COSN.md
docs/en/ufs/COSN.md
pom.xml
shaded/cosn/pom.xml
shaded/pom.xml
underfs/cosn/pom.xml
underfs/cosn/src/main/java/alluxio/underfs/cosn/CosNUnderFileSystemFactory.java
underfs/cosn/src/main/resources/META-INF/services/alluxio.underfs.UnderFileSystemFactory
underfs/cosn/src/test/java/alluxio/underfs/cosn/CosNUnderFileSystemFactoryTest.java
underfs/cosn/src/test/resources/log4j.properties
underfs/pom.xml

Add cosn UFS to provide better ability to read and write cos

---

docs/en/operation/Journal.md

[DOCFIX] Add details about journal folder for embedded journal

---

docs/en/ufs/Azure-Data-Lake-Gen2.md

The current title name doesn't fit. See menu name in Storage Integrations for https://docs.alluxio.io/os/user/edge/en/ufs/Azure-Data-Lake-Gen2.html

[DOCFIX] Shorten Azure Storage Doc Title

---

core/common/src/main/java/alluxio/util/TieredIdentityUtils.java

when tier is null, there is no need to go into the following loop.

Reduce cycle times

---

core/common/src/main/java/alluxio/util/IdUtils.java
core/server/common/src/main/java/alluxio/cli/Format.java
core/server/common/src/main/java/alluxio/master/AbstractMaster.java
core/server/common/src/main/java/alluxio/master/MasterContext.java
core/server/common/src/main/java/alluxio/master/NoopMaster.java
core/server/common/src/main/java/alluxio/master/NoopUfsManager.java
core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournal.java
core/server/common/src/main/java/alluxio/underfs/AbstractUfsManager.java
core/server/common/src/main/java/alluxio/underfs/UfsManager.java
core/server/master/src/main/java/alluxio/master/CoreMasterContext.java
core/server/master/src/test/java/alluxio/master/MockMaster.java
job/server/src/main/java/alluxio/master/AlluxioJobMasterProcess.java

This PR contains the changes in #12366 to solve #12113
and fix the alluxio format errors when running with HDFS journal mentioned in #12637

Avoid loads ufs jars multiple times during journal formatting

---

integration/docker/entrypoint.sh

This enabled Alluxio logserver to run in a container

Enable logserver for docker/k8s

---

integration/fuse/pom.xml
integration/fuse/src/main/native/libjnifuse/Makefile

Add a native profile to build jnifuse in compile phase

---

docs/cn/ufs/COS.md

Fix https://github.com/Alluxio/alluxio/issues/12677

[DOCFIX] Fix COS_ALLUXIO_BUCKET Description

---

core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
core/server/proxy/src/main/java/alluxio/proxy/s3/logging/Logged.java
core/server/proxy/src/main/java/alluxio/proxy/s3/logging/RequestLoggingFilter.java
tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java

When the Key ends with a separator, it means a directory should be added

Add Directory support for S3 PutObject + Debug Logging Support

---

pom.xml

orig-pr: Alluxio/alluxio#12516
orig-commit: Alluxio/alluxio@c2f05d0d314c2f834d964de31d9ecc9d9133ff42
orig-commit-author: Gene Pang <gene.pang@gmail.com>
pr-link: Alluxio/alluxio#12731
change-id: cid-ae24dcc307c559f9676131407e576dffa0ef4beb

Port changes of [#12516] to branch-1.8

---

integration/fuse/src/main/java/alluxio/fuse/StackFS.java
integration/fuse/src/main/java/alluxio/fuse/StackMain.java

Add StackFs which tests the performance overhead of JNI-FUSE without Alluxio interactions.

Add JNI-FUSE StackFS

---

docs/cn/deploy/Running-AlluxioFuse-On-Docker.md
docs/en/deploy/Running-Alluxio-On-Docker.md
docs/en/deploy/Running-Alluxio-On-Kubernetes.md

Alluxio more details docs for installing POSIX API via Docker/Kubernetes

[DOCFIX] Add Fuse Docker/Kubernetes docs

---

underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java

fixes Alluxio/new-contributor-tasks#81
New contributor task: Alluxio/new-contributor-tasks#81

[SMALLFIX] Update summary javadoc of GCSUnderFileSystem

---

core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
core/server/common/src/main/java/alluxio/master/StateLockManager.java
core/server/common/src/test/java/alluxio/master/StateLockManagerTest.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
core/transport/src/main/proto/grpc/file_system_master.proto
shell/src/main/java/alluxio/cli/fsadmin/command/StateLockHoldersCommand.java

pr-link: Alluxio/alluxio#12769
change-id: cid-aafad65caf902aaf77bba0490d200f25ccd7ba0f

Port changes of [#12769] to branch-2.4

---

integration/docker/Dockerfile

fix issue 12781 https://github.com/Alluxio/alluxio/issues/12781

Fix security issue in base docker file

---

core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java

dirView has no toString implementation. So it is certainly not what you want.

[SMALLFIX] Fix "Allocation after freeing space" log message

---

shaded/hadoop/pom.xml

Fix https://github.com/Alluxio/alluxio/issues/12764

Fix tarball gen for 2.4 branch

---

integration/docker/Dockerfile
integration/docker/Dockerfile.fuse

Add arthas to alluxio docker image, then you can run the following command to check the performance issue.
```
java -jar /opt/arthas/arthas-boot.jar
```
Signed-off-by: cheyang <cheyang@163.com>

Add arthas to docker image of alluxio

---

docs/en/operation/User-CLI.md

Doc for https://github.com/Alluxio/alluxio/commit/4b403bf9253a14fd907d94582f370bdfb4368d20

[DOCFIX] Update doc for distributedCp/distributedLoad

---

core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java

Addresses https://github.com/Alluxio/alluxio/issues/11729

Limit the printed blocks when converting MasterWorkerInfo to string

---

integration/fuse/src/main/native/libjnifuse/jnifuse_fs.cc
integration/fuse/src/main/native/libjnifuse/jnifuse_fs.h
integration/fuse/src/main/native/libjnifuse/jnifuse_helper.cc
integration/fuse/src/main/native/libjnifuse/jnifuse_impls.cc
integration/fuse/src/main/native/libjnifuse/jnifuse_impls.h

Now jni-based fuse lack chmod operation implementation, this PR aim to complete it.

Support chmod for jni-fuse

---

docs/en/api/POSIX-API.md

Add some POSIX API configuration and modify the description of some existing one

[DOCFIX] Update POSIX API docs

---

docs/cn/Overview.md
docs/en/Overview.md
docs/en/overview/Getting-Started.md

pr-link: Alluxio/alluxio#12858
change-id: cid-6db243929240aa0f9f0a36ccf42302170cce81c6

Remove alluxio presto ami from docs

---

docs/en/api/POSIX-API.md

Improve and POSIX API docs, especially simplifying the setting due to https://github.com/Alluxio/alluxio/pull/12857/

[DOCFIX] Update POSIX API doc

---

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerTest.java
core/common/src/main/java/alluxio/conf/PropertyKey.java

Retry on benign racing for local cache

---

docs/en/Overview.md

Just some minor wording edits.

[DOCFIX] Adjust wording in en/Overview.md

---

core/client/fs/src/main/java/alluxio/client/block/stream/BufferCachingGrpcDataReader.java
core/client/fs/src/main/java/alluxio/client/block/stream/SharedGrpcDataReader.java
core/client/fs/src/test/java/alluxio/client/block/stream/BufferCachingGrpcDataReaderTest.java
core/client/fs/src/test/java/alluxio/client/block/stream/SharedGrpcDataReaderTest.java
core/client/fs/src/test/java/alluxio/client/block/stream/TestBufferCachingGrpcDataReader.java

Add the unit tests for SharedGrpcDataReader and BufferCachingGrpcDataReader

Add tests for SharedGrpcDataReader and BufferCachingDataReader

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
docs/en/ufs/GCS.md
underfs/gcs/pom.xml
underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystemFactory.java
underfs/gcs/src/main/java/alluxio/underfs/gcs/v2/GCSV2InputStream.java
underfs/gcs/src/main/java/alluxio/underfs/gcs/v2/GCSV2OutputStream.java
underfs/gcs/src/main/java/alluxio/underfs/gcs/v2/GCSV2UnderFileSystem.java

Add GCS Version 2 integration using Google cloud API

Add GCS Version 2 integration using Google cloud API

---

dev/scripts/src/alluxio.org/check-docs/main.go

accordion titles in docs cannot contain a space, ex. `{% accordion this is a bad title %}`

Add check for accordion titles in docs

---

table/shell/pom.xml
table/shell/src/main/java/alluxio/cli/table/TableShell.java
table/shell/src/main/java/alluxio/cli/table/command/AbstractTableCommand.java
table/shell/src/main/java/alluxio/cli/table/command/AttachDatabaseCommand.java
table/shell/src/main/java/alluxio/cli/table/command/DetachDatabaseCommand.java
table/shell/src/main/java/alluxio/cli/table/command/ListDatabasesCommand.java
table/shell/src/main/java/alluxio/cli/table/command/SyncDatabaseCommand.java
table/shell/src/main/java/alluxio/cli/table/command/TransformStatusCommand.java
table/shell/src/main/java/alluxio/cli/table/command/TransformTableCommand.java
table/shell/src/test/java/alluxio/cli/table/TransformTableCommandTest.java

Related with https://github.com/Alluxio/alluxio/issues/12690

Add data operation ability on AbstractTableCommand

---

docs/en/cloud/AWS-EMR.md

add link to aws cli cmd for emr create-clusters
describe alternative method to reference json configuration file

[DOCFIX] Update aws emr doc

---

docs/en/operation/Basic-Logging.md
docs/en/operation/Troubleshooting.md

A few small improvements on troubleshooting

[DOCFIX] Improve troubleshooting doc

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/worker/src/main/java/alluxio/worker/block/AsyncBlockRemover.java

Improve error messages on master and worker

---

core/common/src/main/java/alluxio/conf/PropertyKey.java

A format change, no logic involved.

Remove redundant blank in PropertyKey

---

docs/en/contributor/Contributor-Getting-Started.md

@apc999 is the new contributor task still a thing? i noticed the corresponding repository has not been updated for over a year.

[DOCFIX] Update contributor getting started docs

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
docs/en/operation/Journal.md

Modify journal docs

---

pom.xml

There are occasionally SIGSEGVs in RocksDB and there is some suggestion that this may help.

Upgrade RocksDB to 6.15.2

---

webui/common/src/components/LineGraph/LineGraph.test.tsx
webui/common/src/components/LineGraph/LineGraph.tsx
webui/common/src/components/LineGraph/__snapshots__/LineGraph.test.tsx.snap
webui/master/src/store/metrics/reducer.tsx
webui/master/src/store/metrics/test/reducer.test.tsx

Show correct Web UI metrics y-axis type for each graph

---

core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java

Fix https://alluxio.atlassian.net/browse/ALLUXIO-3402

Keep enum configuration backwards compatible

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java
core/server/master/src/main/java/alluxio/master/metastore/caching/CachingInodeStore.java
core/server/master/src/main/java/alluxio/master/metastore/caching/StatsCounter.java

There are 2 changes here:
1. Make it more specific that load times are loads that happened as a result of a cache miss.
2. Add Listing Cache statistics.

Add ListingCache metrics

---

underfs/cosn/src/main/java/alluxio/underfs/cosn/CosNUnderFileSystemFactory.java
underfs/ozone/src/main/java/alluxio/underfs/ozone/OzoneUnderFileSystemFactory.java

Add import statement to make link in Java doc workable

[SMALLFIX] Add import statement to make link in Java doc workable

---

pom.xml

A lot of the fork failures in current maven seems to be improved by this upgrade?

Upgrade maven surefire plugin version

---

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
core/common/src/test/java/alluxio/util/io/PathUtilsTest.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java

To help review https://github.com/Alluxio/alluxio/pull/12956/, I spin off some unrelated changes (formatting, logging) to here from that PR

Cleanup sync related master code

---

docs/en/compute/Trino.md

[DOCFIX] Add a doc for Trino

---

core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
shell/src/main/java/alluxio/cli/fs/command/LsCommand.java
tests/src/test/java/alluxio/client/fs/UfsSyncIntegrationTest.java

Note that this port no longer saves the one RPC request that was saved in the original commit.

Port changes of [#12441] to branch-2.3

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseFileSystemTest.java

Add a boundary check before fuse read

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
docs/en/ufs/GCS.md

Change GCS V2 to be the default GCS version

Change GCS V2 to be the default GCS version

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/main/java/alluxio/metrics/MetricKey.java
core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java

Add some metrics for the absent cache

Add absent cache metrics

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseFileSystem.java
integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
integration/fuse/src/main/java/alluxio/fuse/CreateFileEntry.java
tests/src/test/java/alluxio/client/fuse/AbstractFuseIntegrationTest.java

Add waitForFileComplete logics in JNI-FUSE

---

core/common/src/main/java/alluxio/collections/LockPool.java
core/common/src/main/java/alluxio/resource/ResourcePool.java
core/common/src/test/java/alluxio/collections/LockPoolTest.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeLockManager.java

Reuse refcount=0 lock in the LockPool

---

core/common/src/main/java/alluxio/exception/ExceptionMessage.java

Fixes Alluxio/new-contributor-tasks#572

[SMALLFIX] Remove unused enum field for exception messages

---

bin/alluxio
core/client/fs/src/main/java/alluxio/client/WriteType.java
shell/src/main/java/alluxio/cli/TestRunner.java

Small changes to the Alluxio binary and related components' comments which were forgotten in PR #12980 
- Note that no implementation is changing for the alluxio binary, just the usage comment

[SMALLFIX] Adjust alluxio binary and comments to match user cli docs

---

core/common/src/main/java/alluxio/ClientContext.java
core/common/src/main/java/alluxio/conf/PropertyKey.java

Fix https://github.com/Alluxio/alluxio/issues/13118

Load cluster conf only if property is set

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java

This reverts commit 8f618358891ca89f753b369316d58221e8fb9b74 to stablize tests

Revert "Wait file closed before unmount fuse"

---

core/common/src/main/java/alluxio/metrics/MetricKey.java

Fix accidental committed conflict

Fix compilation

---

integration/fuse/src/main/java/alluxio/fuse/StackFS.java
integration/fuse/src/main/java/alluxio/fuse/StackMain.java

Add stack fs metrics for testing purpose

Add StackFS metrics

---

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
integration/kubernetes/helm-chart/alluxio/Chart.yaml

Update helm chart version in favor of #13183

Update Helm chart version

---

core/common/src/main/java/alluxio/metrics/sink/CsvSink.java

[SMALLFIX] Create target path for csv sink

---

core/client/fs/src/main/java/alluxio/client/block/stream/BlockInStream.java
core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerDataReader.java
core/client/fs/src/test/java/alluxio/client/block/stream/TestBlockInStream.java
core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/main/java/alluxio/metrics/MetricKey.java
core/common/src/main/java/alluxio/metrics/MetricsSystem.java
integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
integration/fuse/src/main/java/alluxio/fuse/StackFS.java

Add some Fuse metrics for easy debugging and monitoring

Add metrics to JNIFuse and StackFS

---

integration/docker/Dockerfile
integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java

Add libfuse to Alluxio server dockerfile

Support FUSE on Worker in docker file

---

docs/en/ufs/Azure-Data-Lake-Gen2.md

or we have two pages titled as `Azure-Data-Lake`

[DOCFIX] Update Azure-Data-Lake-Gen2.md

---

core/common/src/main/java/alluxio/exception/ExceptionMessage.java

Fixes Alluxio/new-contributor-tasks#585

[SMALLFIX] Remove unused enum field for exception message

---

docs/cn/compute/Hive.md
docs/cn/ufs/Ceph.md

Alluxio configure S3 interface，we should add those configuration to conf/alluxio-site.properties and then restart alluxio.

[DOCFIX] Configuration files changed

---

shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java

Add index file option for distributedLoad command

---

docs/en/contributor/Contributor-Getting-Started.md

Updated the Contributor Getting Started doc due to UI changes on Github.

[DOCFIX] Update Contributor Getting Started Guide

---

table/server/underdb/glue/src/main/java/alluxio/table/under/glue/GlueUtils.java

Add null check for bucket column in Glue UDB

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java

This PR 
1. use default uid/gid on open/create when user translation is off . This will fix #13254 
2. add username/groupname cache to avoid frequent shell command that get username/groupname from ids.

Use default Uid/Gid on FUSE create/mkdir when translation is off

---

core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
core/server/master/src/main/java/alluxio/master/file/RpcContext.java
core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
core/server/master/src/test/java/alluxio/underfs/UfsStatusCacheTest.java

Revert "Cancel sync job in middle of ufs calls if client cancelled"

---

core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
core/server/master/src/main/java/alluxio/master/file/RpcContext.java
core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
core/server/master/src/test/java/alluxio/underfs/UfsStatusCacheTest.java

Revert "Port changes of [#13210] to branch-2.5"

---

core/server/master/src/main/java/alluxio/master/file/InodeSyncStream.java
core/server/master/src/main/java/alluxio/master/file/RpcContext.java
core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java
core/server/master/src/test/java/alluxio/underfs/UfsStatusCacheTest.java

Revert "Port changes of [#13210] to branch-2.4"

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
tests/src/test/java/alluxio/client/fuse/JNIFuseIntegrationTest.java
tests/src/test/java/alluxio/server/worker/WorkerFuseIntegrationTest.java

A follow-up PR for #13236 to change the logs and enable the touch test back.

Improve overwrite logs and enable touch test in JNIFuse

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

Each path in Alluxio will be compared with the underlying storage recursively. 
This PR aims to reduce unnecessary comparisons  with under storage path status (maybe an expansive operation) in nested directorys. 
E.g.
1. `/a/b/c` in Alluxio and UFS , then delete UFS directory `/a`, we can assert that `b`, `c` must be inconsistent with UFS. 
2. `/a/b/c` is only created in Alluxio, not on underlying storage , we can assert that  `b`, `c` must be inconsistent with UFS. 
3. .....
we can assert that the parent node is inconsistent, then the child nodes must be also inconsistent. 
remind : dir is considered consistent even if the dir's fingerprint was changed.
Existing test ：alluxio.client.fs.CheckConsistencyIntegrationTest

Improve check consistency with under storage behavior

---

core/server/common/src/main/java/alluxio/master/MasterProcess.java

I believe this is going to be greatly increase the stability of the unit tests.

Do not wait for web ui to be ready to be ready in tests

---

webui/master/src/containers/pages/Configuration/Configuration.scss
webui/master/src/containers/pages/Configuration/Configuration.test.tsx
webui/master/src/containers/pages/Configuration/Configuration.tsx
webui/master/src/containers/pages/Configuration/__snapshots__/Configuration.test.tsx.snap

A Search bar is added in order to filter the data by property name. There is a button to enter the search keyword and another to clear the search. Backspacing the whole search key will also clear the search.

Add Search Properties bar to the Web UI Configuration tab

---

dev/scripts/src/alluxio.org/build-distribution/cmd/common.go

needed to have the publish tarball build pass after https://github.com/Alluxio/alluxio/pull/13310

Remove underfs-cephfs from list of libs to copy to tarball

---

core/common/src/main/java/alluxio/conf/PropertyKey.java

[SMALLFIX] Add space to alluxio.job.worker.throttling description

---

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
integration/kubernetes/helm-chart/alluxio/Chart.yaml
integration/kubernetes/helm-chart/alluxio/templates/master/statefulset.yaml

Fix issue problem in https://github.com/Alluxio/alluxio/issues/13323
Need to change statefulset `podManagementPolicy` from default to `Parallel`, so that multi-master node can start at same time.

Add Master StatefulSet podManagementPolicy Parallel

---

tests/src/test/java/alluxio/client/fs/LoadMetadataIntegrationTest.java

Add a test to verify that symlinks work when the underlying ufs supports it

Add symlink test

---

shell/src/main/java/alluxio/cli/fs/command/FreeCommand.java

Trying to `./bin/alluxio free` an empty (0-bytes) files from Alluxio results in the corresponding Alluxio job workers to repeatedly attempt to free the file until reaching the job timeout.
This is because the implementation for `free` in [FreeCommand](https://github.com/Alluxio/alluxio/blob/master/shell/src/main/java/alluxio/cli/fs/command/FreeCommand.java#L81) uses `getInAlluxioPercentage() == 0` as the stopping condition, but empty (length 0) files in Alluxio are [hardcoded as having 100 in Alluxio percentage](https://github.com/Alluxio/alluxio/blob/40af661d15104813f74eeda3790b7a366f7cb28f/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java#L2114).

Add exception to FreeCommand for empty files

---

core/client/fs/src/test/java/alluxio/client/file/cache/FIFOEvictorTest.java

Add unit test for client side FIFO Evictor.

Add unit test for FIFOEvictor

---

docs/en/contributor/Code-Conventions.md
docs/en/operation/Basic-Logging.md

Improve logging convention docs

[DOCFIX] Improve logging convention docs

---

core/common/src/main/java/alluxio/Sessions.java
core/common/src/main/java/alluxio/collections/LockPool.java
core/common/src/main/java/alluxio/resource/ResourcePool.java
core/common/src/test/java/alluxio/ConfigurationRule.java
core/common/src/test/java/alluxio/resource/ResourcePoolTest.java
core/server/worker/src/main/java/alluxio/worker/block/BlockLockManager.java
core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClientPool.java
core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
core/server/worker/src/main/java/alluxio/worker/file/FileSystemMasterClient.java
core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java
core/server/worker/src/test/java/alluxio/worker/block/stream/BlockWorkerDataReaderTest.java
job/client/src/main/java/alluxio/client/job/JobMasterClientPool.java

Followup of https://github.com/Alluxio/alluxio/pull/13282/ to improve tests of `BlockWorkerDataReader`

Improve tests for BlockWorkerDataReader

---

job/server/src/main/java/alluxio/job/util/JobUtils.java
job/server/src/test/java/alluxio/job/plan/replicate/ReplicateDefinitionTest.java

Continuation of https://github.com/Alluxio/alluxio/pull/13362

Fix Replication Job

---

shaded/adl/pom.xml
shaded/cosn/pom.xml
shaded/ozone/pom.xml
shaded/pom.xml
underfs/adl/pom.xml

Fix #13377
Shade the ADL UFS to avoid hadoop version incompatible issue between ADL and default

Shade ADL UFS

---

underfs/wasb/pom.xml

Update wasb to use the same hadoop version as ufs.hadoop.version

---

pom.xml

https://x-stream.github.io/CVE-2021-29505.html

Fix xstream security issue CVE-2021-29505

---

core/common/src/main/java/alluxio/conf/PropertyKey.java

Fixes Alluxio/new-contributor-tasks#593

[DOCFIX] Reorder @see tags of PropertyKey.isDeprecated

---

core/common/src/main/java/alluxio/conf/PropertyKey.java

Fixes  Alluxio/new-contributor-tasks#592

[DOCFIX] Reorder @see tags of PropertyKey.isRemoved

---

pom.xml

Update the version of jnr-fuse to solve the following error:
```
Could not find artifact com.github.serceman:jnr-fuse:jar:0.5.3
```

Update jnr-fuse version

---

core/common/src/main/java/alluxio/metrics/MetricKey.java

Inlines all member strings of `MetricKey.Name` and removes the class.
Fixes Alluxio/new-contributor-tasks#600

Inline MetricKey.Name member strings

---

core/common/src/main/java/alluxio/worker/block/BlockStoreMeta.java
core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockStoreMeta.java
core/server/worker/src/test/java/alluxio/worker/block/DefaultBlockWorkerTest.java

1. add some description on methond (`getBlockList()` and `getBlockListByStorageLocation` ) in `BlockStoreMeta` to make it more clearer.
2. add some UT for `BlockStoreMeta`
fix
https://github.com/Alluxio/new-contributor-tasks/issues/588
https://github.com/Alluxio/new-contributor-tasks/issues/589

[SMALLFIX] Add description in method and add some UT in storeMeta

---

core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java

Separated this optimization into one standalone PR
https://github.com/Alluxio/alluxio/pull/13384 will be rebased after this

Save one copy in MasterWorkerInfo.register

---

core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
core/client/fs/src/main/java/alluxio/client/file/FileInStream.java
integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java

Fix throw CCE when using Fuse while enable client cache bug

---

bin/alluxio-masters.sh

Fixes alluxio/new-contributor-tasks#598, alluxio/new-contributor-tasks#599.

[SMALLFIX] Redirect error messages to STDERR in bin/alluxio-masters.sh

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java
table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveClientPool.java
table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveClientPoolCache.java

Make connection pools per connection instead of per db for hive udb

---

pom.xml
shell/pom.xml
shell/src/main/java/alluxio/cli/fs/command/MountCommand.java

This reverts commit c4428d5e711627f1be4a5368bb7082113c33750d to fix https://github.com/Alluxio/alluxio/issues/13490.

Revert "Convert the configuration files to mount options when Mount"

---

core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java

Prior to this fix, web ui metrics errors out on a NPE

Fix web ui empty response

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java
core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java
core/server/worker/src/main/java/alluxio/worker/grpc/BlockWriteHandler.java

This PR aims at adding metrics for tracking the number of active RPCs handled by the Alluxio worker.

Add metrics for Worker RPC counts

---

core/server/worker/src/main/java/alluxio/worker/block/BlockMetricsReporter.java

The previous PR #13448 was merged already, but the aggregation of the meter wasn't properly implemented.

Implement cluster aggregation for Worker block eviction rate metric

---

docs/cn/core-services/Caching.md

[DOCFIX] Update Caching.md

---

core/client/hdfs/src/main/java/alluxio/hadoop/HadoopUtils.java

Fix https://github.com/Alluxio/new-contributor-tasks/issues/602

Remove unused method toStringHadoopInputSplit

---

docs/en/contributor/Contributor-Tools.md

Only the gRPC version needs to be up-to-date

[DOCFIX] Improve contributing-tool doc

---

bin/alluxio

Fixes alluxio/new-contributor-tasks#595, alluxio/new-contributor-tasks#596, alluxio/new-contributor-tasks#597.

[SMALLFIX] Redirect error messages to STDERR in bin/alluxio

---

docs/en/operation/Scalability-Tuning.md

Some minor fixes
Mention direct memory requirement on the worker and a better mem size estimation

[DOCFIX] Improve scalability doc

---

docs/_data/table/cn/common-configuration.yml

[DOCFIX] Fix typo for common configuration doc

---

docs/en/operation/Scalability-Tuning.md

[DOCFIX] Update scalability tuning doc

---

underfs/cephfs/src/main/java/alluxio/underfs/cephfs/CephFSUnderFileSystem.java

Improve exceptional handling. Don't rethrow a new exception better

---

docs/en/ufs/S3.md

Improve S3 document
Better user experience
No

[DOCFIX] Improve S3 UFS documentation

---

docs/en/operation/Journal.md

[DOCFIX] Fix journal management doc

---

docs/en/core-services/Caching.md
docs/en/core-services/Unified-Namespace.md
docs/en/operation/Configuration.md

There are no serious changes to the documentation. Just minor grammar and conciseness fixes

[DOCFIX] Clean up for Unified NS, Caching, and Configuration

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/main/java/alluxio/metrics/MetricKey.java
core/common/src/main/java/alluxio/util/BucketCounter.java
core/common/src/test/java/alluxio/util/BucketCounterTest.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeCounter.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
core/server/master/src/main/java/alluxio/master/metastore/caching/Cache.java

Use AtomicLong with caution, it can have very bad perf when contention is high. 
Ref: https://www.overops.com/blog/java-8-longadders-the-fastest-way-to-add-numbers-concurrently/

Fix metrics performance regression

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

Log when it is a file

---

core/common/src/main/java/alluxio/collections/LockPool.java
core/common/src/main/java/alluxio/resource/ResourcePool.java
core/common/src/test/java/alluxio/collections/LockPoolTest.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeLockManager.java

This reverts commit 9a35c1aeeda9b61cffeb563ad8acd3efcfac9624.

Revert "Reuse refcount=0 lock in the LockPool"

---

docs/en/overview/Getting-Started.md

Adding question mark to a title question in FAQ, and fixing a grammar problem.

[DOCFIX] Fix minor typo

---

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java

Fixes Alluxio/new-contributor-tasks#594
The authority of default uri could be different with the current one. Just need check the path.
No

Consider comparing only URI when checking UFS path

---

docs/en/ufs/WEB.md

Highlighted the flag names in the description and reworded the description of alluxio.underfs.web.titles

[DOCFIX] Fix some grammar errors

---

.github/workflows/java8_integration_tests_webui.yml
.github/workflows/java8_unit_tests.yml

Temporarily disable codecov fail CI

Disable codecov fail CI

---

core/server/common/src/main/java/alluxio/Registry.java

Delete an unused constant
Delete unused code
No

Delete an unused constant

---

docs/en/ufs/Swift.md

[DOCFIX] Update swift doc

---

core/server/master/src/main/java/alluxio/master/file/meta/AsyncUfsAbsentPathCache.java

Remove leftover comment

---

docs/en/api/S3-API.md

[DOCFIX] Update S3 API doc

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
core/server/worker/src/main/java/alluxio/worker/block/AsyncBlockRemover.java

Updated some variable names and metric key descriptions

[SMALLFIX] Improve some worker metrics names and desc

---

core/common/src/main/java/alluxio/metrics/MetricKey.java

Update some vague metric descriptions 
Descriptions should be clearer to users to enhance understanding

Update embedded journal metric descriptions

---

core/common/src/main/java/alluxio/metrics/MetricKey.java

This improves and clarifies metrics description for journal metrics.

Improve metrics description for journal metrics

---

core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerWithShadowCacheTest.java
core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/main/java/alluxio/metrics/MetricKey.java

Address https://github.com/Alluxio/alluxio/issues/13260.

Implement Shadow Cache

---

core/client/fs/src/main/java/alluxio/client/block/policy/DeterministicHashPolicy.java
core/client/fs/src/main/java/alluxio/client/block/policy/LocalFirstAvoidEvictionPolicy.java
core/client/fs/src/main/java/alluxio/client/block/policy/LocalFirstPolicy.java
core/client/fs/src/main/java/alluxio/client/block/policy/MostAvailableFirstPolicy.java
core/client/fs/src/main/java/alluxio/client/block/policy/RoundRobinPolicy.java
core/client/fs/src/main/java/alluxio/client/block/policy/SpecificHostPolicy.java
docs/en/api/FS-API.md

This PR adjusts/adds javadoc links, adjusts some wording, and changed the ordering of sections for clarity in the Filesystem API doc.
Clarification on the Filesystem API doc.
Adjusted the public doc for the Filesystem API.

[DOCFIX] Add javadoc links to Filesystem API doc

---

docs/en/operation/User-CLI.md
table/server/common/src/main/java/alluxio/table/common/udb/UdbConfiguration.java
table/server/common/src/test/java/alluxio/table/common/udb/UdbConfigurationTest.java

Support using regex stand for schemeAuthority for udb mount options

---

core/common/src/main/java/alluxio/Constants.java
underfs/abfs/src/main/java/alluxio/underfs/abfs/AbfsUnderFileSystem.java
underfs/abfs/src/main/java/alluxio/underfs/abfs/AbfsUnderFileSystemFactory.java
underfs/adl/src/main/java/alluxio/underfs/adl/AdlUnderFileSystem.java
underfs/adl/src/main/java/alluxio/underfs/adl/AdlUnderFileSystemFactory.java
underfs/wasb/src/main/java/alluxio/underfs/wasb/WasbUnderFileSystem.java
underfs/wasb/src/main/java/alluxio/underfs/wasb/WasbUnderFileSystemFactory.java

Move UFS URI schemes to Constants and resort by the order of alphabet.
Use uniform UFS URI scheme style.
No

Move UFS URI schemes to Constants and resort

---

stress/common/src/main/java/alluxio/stress/client/ClientIOOperation.java
stress/common/src/main/java/alluxio/stress/client/ClientIOParameters.java
stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java

Change Format of ClientIOOperation Enums
To fix issue: https://github.com/Alluxio/new-contributor-tasks/issues/603

Change Format of ClientIOOperation Enums

---

core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
core/client/fs/src/test/java/alluxio/client/file/cache/CacheManagerTest.java

Use `CACHE_INIT_LOCK.lock()` instead of `CACHE_INIT_LOCK.tryLock()` when  calling 'CacheManager.Factory.get(conf)' concurrently, to make sure it gets non-null CacheManager.
This PR fixes https://github.com/Alluxio/alluxio/issues/13640
Returning null when calling 'CacheManager.Factory.get(conf)' concurrently.
I used Spark 3.1.1 + Alluxio Local Cache, when all tasks in one executor start concurrently, there are some tasks getting null CacheManager.
No

Fix null CacheManager when getting CacheManager concurrently

---

core/common/src/main/java/alluxio/conf/RemovedKey.java
core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManager.java

Fixing [issue-11699](https://github.com/Alluxio/alluxio/issues/11699)

Fix the worker failed to start issue due to deprecated configs

---

core/common/src/main/java/alluxio/wire/MasterWebUIOverview.java

Fix typo in MasterWebUIOverview.
Fix typo in MasterWebUIOverview.
No.

Fix typo in MasterWebUIOverview

---

docs/en/operation/User-CLI.md

Update `distributedLoad` doc
Some options are missing in doc
No

[DOCFIX] Update distributeLoad doc

---

integration/metrics/README.md

Update readme for tracing
Fix formatting
No

[DOCFIX] Update readme.md for tracing

---

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
core/common/src/main/java/alluxio/metrics/MetricKey.java

Improve the name and description of the client cache related metrics
metrics name and description of client cache related metrics will be updated

Improve client cache metrics description

---

integration/yarn/pom.xml

Update yarn version post release
no

Update yarn version post release

---

core/common/src/main/java/alluxio/util/webui/NodeInfo.java
core/common/src/main/java/alluxio/util/webui/WebUtils.java

Reduce code duplications in WebUtils
Reduce code duplications in WebUtils
No

Reduce code duplications in WebUtils

---

pom.xml

Remove aliyun maven repo, since we don't need it in the master branch
Fixes the build

Remove aliyun repo

---

docs/en/operation/User-CLI.md

[DOCFIX] Remove extra space

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java

With this change Alluxio will serve proxy rest API from root path as well as API specific path.

Add support for publishing REST from root path

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/server/proxy/src/main/java/alluxio/web/ProxyWebServer.java

This reverts commit d964cd4166ce374168c06f561eb22c4f15bdfb1b.

Revert "Add support for publishing REST from root path"

---

table/server/common/src/main/java/alluxio/table/common/udb/PathTranslator.java
table/server/common/src/test/java/alluxio/table/common/udb/PathTranslatorTest.java

This reverts commit 499d2b5686f9113c25e0ce665bf5c65c7eef3a7d.

Revert "Fix PathTranslator to compare path prefixes by path components"

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/main/java/alluxio/grpc/GrpcUtils.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
core/server/master/src/main/java/alluxio/master/file/meta/MutableInode.java
core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java
core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManager.java
core/transport/src/main/proto/grpc/file_system_master.proto
job/common/src/main/java/alluxio/job/plan/replicate/MoveConfig.java
job/common/src/main/java/alluxio/job/wire/JobInfo.java
job/common/src/main/java/alluxio/job/wire/PlanInfo.java
tests/src/test/java/alluxio/client/cli/fs/command/PinCommandMultipleMediaIntegrationTest.java

1. Added more comprehensive testing
2. Correct client side File Info
3. Have the pinning status of a directory propagated to the files
pr-link: Alluxio/alluxio#13516
change-id: cid-3ba56eedf8b0ff36c891127761c7aefce7be09b9

Port changes of [#13516] to branch-2.5

---

core/server/proxy/src/main/java/alluxio/proxy/s3/RangeFileInStream.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RangeSpec.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
core/server/proxy/src/test/java/alluxio/proxy/s3/S3RangeSpecTest.java

Implement https://alluxio.atlassian.net/browse/ALLUXIO-3321 feature

Support range header for s3 get object api

---

core/common/src/main/java/alluxio/grpc/DataMessageMarshaller.java

This change intends to fix a buffer leak under certain cases
Fixes https://github.com/Alluxio/alluxio/issues/13677
NA

Release buffer on exception

---

core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java

Fix typo and simplify the code in AlluxioMasterRestServiceHandler.
Fix typo and simplify the code in AlluxioMasterRestServiceHandler.
No.

Fix typo and simplify the code in AlluxioMasterRestServiceHandler

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java

Add a metrics to monitor grpc job pending queue
You can observe the pressure of the master through this metrics

Add a metrics to monitor grpc job pending queue

---

integration/kubernetes/operator/alluxio/pkg/common/constants.go
integration/kubernetes/operator/alluxio/pkg/controllers/dataset/v1alpha1/dataset_controller.go

Fix access bug and typo
Fix access bug and typo
No

Fix access bug and typo

---

core/server/master/src/main/java/alluxio/master/meta/MetaMasterConfigurationServiceHandler.java

Fixes Alluxio/new-contributor-tasks#605
In https://github.com/Alluxio/alluxio/blob/fb486603b981ef6c04c111799f9ef72630a5eb00/core/server/master/src/main/java/alluxio/master/meta/MetaMasterConfigurationServiceHandler.java#L88
Correct the spell of resquest to be request

Fix typo in MetaMasterConfigurationServiceHandler

---

docs/cn/operation/Metrics-System.md
docs/en/operation/Metrics-System.md

Fix #13726
Describe an easy way to export jvm related metrics
An example jmx metrics is 
```
jmx_config_reload_failure_total 0.0
jmx_exporter_build_info{version="0.16.0",name="jmx_prometheus_javaagent",} 1.0
jvm_threads_current 61.0
jvm_threads_daemon 48.0
jvm_threads_peak 69.0
jvm_threads_started_total 90.0
jvm_threads_deadlocked 0.0
jvm_threads_deadlocked_monitor 0.0
jvm_threads_state{state="WAITING",} 7.0
jvm_threads_state{state="NEW",} 0.0
jvm_threads_state{state="RUNNABLE",} 24.0
jvm_threads_state{state="BLOCKED",} 0.0
jvm_threads_state{state="TERMINATED",} 0.0
jvm_threads_state{state="TIMED_WAITING",} 30.0
jmx_config_reload_success_total 0.0
jvm_buffer_pool_used_bytes{pool="direct",} 1122307.0
jvm_buffer_pool_used_bytes{pool="mapped",} 0.0 …
```

[DOCFIX] Support export jvm metric by run jmx_exporter as an agent

---

core/server/worker/src/main/java/alluxio/worker/block/management/tier/PromoteTask.java
core/server/worker/src/main/java/alluxio/worker/block/management/tier/SwapRestoreTask.java

Related to issues seen in https://github.com/Alluxio/alluxio/issues/10429

Fix NPE during swap-restore plan generation

---

README.md

Update Readme
Various minor tunings on readme file
None

[DOCFIX] Update project Readme

---

core/common/src/main/java/alluxio/metrics/MetricsSystem.java
docs/en/reference/Metrics-List.md

Fix #13726
Export JVM related metrics
Add ClassLoadingGaugeSet and CachedThreadStatesGaugeSet to Alluxio MetricRegistry.
Add more metrics.

Support export jvm metric

---

integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
integration/kubernetes/helm-chart/alluxio/Chart.yaml
integration/kubernetes/helm-chart/alluxio/templates/csi/nodeplugin.yaml

Fix the wrong indentation to pass grammar check

---

docs/cn/operation/Security.md

Added description of common exceptions

[DOCFIX] Update Security.md

---

integration/csi/Dockerfile
integration/docker/README.md

Two  more references of alluxio-fuse image got fixed, pointed out by rico here: #13756

Fix some more alluxio-fuse image references

---

core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java
core/client/fs/src/main/java/alluxio/client/file/MetadataCachingBaseFileSystem.java
core/client/fs/src/test/java/alluxio/client/file/MetadataCachingBaseFileSystemTest.java
tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java

Invalidate cache after write operation

---

shell/src/main/java/alluxio/cli/bundler/CollectInfo.java

[SMALLFIX] Update indents for CollectInfo.java

---

shell/src/main/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommand.java

Change indentation on 'src/main/java/alluxio/cli/bundler/command/CollectAlluxioInfoCommand.java'

[SMALLFIX] Change indentation

---

docs/cn/Overview.md
docs/en/Overview.md

update the diagram in Overview landing page with relevant integrations and APIs

[DOCFIX] Update overview diagram

---

core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockReader.java
core/server/worker/src/main/java/alluxio/worker/block/UnderFileSystemBlockStore.java
core/server/worker/src/test/java/alluxio/worker/block/UnderFileSystemBlockReaderTest.java

Add user information to ufs block read counter metrics
Support showing user info in ufs block read metrics.
N/A

Add user info to ufs block read metrics

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
docs/en/reference/Metrics-List.md
integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java

Add Fuse data structure related size metrics and add fuse metrics docs
Those metrics can help users monitoring the load of the current fuse filesystem and understand the Fuse performance
Add metrics and improve metrics docs

Add Fuse data structure size metrics and improve metrics docs

---

integration/kubernetes/helm-generate.sh
integration/kubernetes/operator/alluxio/cmd/controller/main.go
integration/kubernetes/operator/alluxio/cmd/webhook/webhook-create-signed-cert.sh
integration/kubernetes/operator/alluxio/pkg/ddc/base/capacity.go
integration/kubernetes/operator/alluxio/pkg/ddc/base/engine.go
integration/kubernetes/operator/alluxio/pkg/ddc/base/template_engine.go
integration/kubernetes/operator/alluxio/pkg/ddc/base/utils.go

Fix unexpected err and typo
Fix unexpected err and typo
No

Fix unexpected err and typo

---

core/server/master/src/main/java/alluxio/master/metrics/MetricsStore.java

Modify the CACHE_HIT_RATE bug
the old code is lack of Metrics.CLUSTER_BYTES_READ_LOCAL
No

Modify CACHE_HIT_RATE bug

---

docs/en/operation/Metastore.md

Update docs for rocksdb default size.
Recent change in default onheap cache for rocksdb metastore. 
DocFix

[DOCFIX] Update rocksdb metastore doc

---

job/client/src/main/java/alluxio/job/plan/replicate/DefaultReplicationHandler.java

Release client pool resources
Address a client leak
None

Fix client pool leak

---

core/server/master/src/main/java/alluxio/master/file/meta/MountTable.java

Reverse-resolving a path was not safe against concurrent updates to the mount table.

Lock mount table while reverse resolving

---

docs/en/operation/User-CLI.md

Modify documents, add some examples for distributed load.
https://docs.alluxio.io/os/user/edge/en/operation/User-CLI.html#distributedload
Add some examples.
Document page in https://docs.alluxio.io/os/user/edge/en/operation/User-CLI.html#distributedload

[DOCFIX] Add examples for distributed load with host related options

---

core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
core/common/src/main/java/alluxio/AbstractClient.java
core/common/src/main/java/alluxio/AbstractMasterClient.java
core/common/src/main/java/alluxio/Client.java
core/common/src/test/java/alluxio/AbstractClientTest.java

Reverts Alluxio/alluxio#13883
Trigger merge by mistake.

Revert "[SMALLFIX] Merge conf address with server address"

---

table/server/underdb/glue/pom.xml
table/server/underdb/hive/pom.xml
table/server/underdb/pom.xml

Fix
[ERROR] sourceFile /alluxio/table/server/underdb/target/alluxio-table-server-underdb-2.7.0-SNAPSHOT-jar-with-dependencies.jar does not exist
pom file changes
N/A

Fix underdb jar error

---

core/common/src/main/java/alluxio/util/webui/NodeInfo.java

Add containerHost information on the worker page.

Add containerHost information

---

conf/log4j.properties
core/common/src/main/java/alluxio/metrics/EventCounter.java
core/common/src/main/java/alluxio/metrics/LogStateCounterSet.java
core/common/src/main/java/alluxio/metrics/MetricsSystem.java

Add metric of log

---

job/server/src/main/java/alluxio/master/job/plan/PlanCoordinator.java

Release a chunk of memory when the job finishes 
To help alleviate #13907 
No

Release workerInfoList when a job completes

---

docs/en/operation/Performance-Tuning.md
docs/en/operation/Scalability-Tuning.md

Doc update for tuning 
Help users to maximize Alluxio benefit
Doc fix

[DOCFIX] Update tuning docs

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/main/java/alluxio/grpc/GrpcConnectionPool.java
core/common/src/main/java/alluxio/grpc/GrpcNetworkGroup.java
core/common/src/main/java/alluxio/grpc/GrpcServerBuilder.java
core/common/src/main/java/alluxio/util/network/tls/DefaultSslContextProvider.java
core/common/src/main/java/alluxio/util/network/tls/SslContextProvider.java

Provides entry points for providing java based TLS security to gRPC channels.

Add scaffold for TLS

---

docs/en/operation/Admin-CLI.md
docs/en/operation/Journal.md

Added docs for the `fsadmin journal quorum elect` command

[DOCFIX] Add docs for the `fsadmin journal quorum elect` command

---

core/server/common/src/main/java/alluxio/master/AbstractMaster.java
core/server/master/src/test/java/alluxio/master/journal/JournalContextTest.java

Fix https://github.com/Alluxio/alluxio/issues/13904

Stop leaking state-lock when journal is closed

---

dev/github/component_owners.yaml

Update component assignee

---

job/server/src/main/java/alluxio/worker/JobWorker.java

Fix log error message in JobWorker.
Fix log error message in JobWorker.
None

Fix log error message in JobWorker

---

job/common/src/main/java/alluxio/job/plan/meta/PlanInfo.java
job/server/src/main/java/alluxio/master/job/plan/PlanCoordinator.java

Fix job completion logging
Prevent excessive logging
None

Fix job completion logging

---

docs/en/operation/StressBench.md

Add overview document for StressBench framework. This pr is only for the overview of the StressBench, will add the details for each benchmarks tool afterward.
N/A
N/A

[DOCFIX] Add overview of stress bench

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
core/server/master/src/main/java/alluxio/master/file/LostFileDetector.java

Add lost file metric to measure the lost file count.
Without this pr, we cannot measure the lost file count
No

Add master LostFile and lost blocks metric

---

stress/common/src/main/java/alluxio/stress/fuse/FuseIOParameters.java
stress/common/src/main/java/alluxio/stress/fuse/FuseIOTaskResult.java
stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java

Remove all random read related stuff from Fuse IO stress bench since we don't have a plan for implementing it.

Remove random read from Fuse IO stress bench

---

job/server/src/main/java/alluxio/master/job/JobMasterClientRestServiceHandler.java
tests/src/test/java/alluxio/client/rest/JobMasterClientRestApiTest.java

Fix job rest api test introduced in #13895

Fix job rest api test

---

integration/csi/README.md
integration/csi/alluxio/controllerserver.go
integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
integration/kubernetes/helm-chart/alluxio/README.md
integration/kubernetes/helm-chart/alluxio/values.yaml

Update version & fix typo.
Update version & fix typo.
None

Update version & fix typo

---

stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java

Add a whitespace between two words.

[SMALLFIX] Add whitespace between words

---

docs/cn/core-services/Unified-Namespace.md
docs/en/core-services/Unified-Namespace.md

Fix https://github.com/Alluxio/alluxio/issues/13970  wrong wording in docs 
Wrong unit in docs
Correct docs

[DOCFIX] Fix wrong unit in docs

---

docs/en/compute/Presto-Iceberg.md

A new documentation article on how to query Iceberg tables with Presto and Alluxio.

[DOCFIX] Add doc on Presto and Iceberg

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java

Fix #14014
Involve a new metric `Master.TotalBlockReplicaCount`

Support total block replica count metric

---

integration/docker/README.md

This is a follow up of #14035. Update the README.md in the docker directory.

Update docker README

---

core/client/fs/src/main/java/alluxio/client/block/stream/SharedGrpcDataReader.java
core/common/src/main/java/alluxio/AbstractClient.java
core/common/src/main/java/alluxio/annotation/SuppressFBWarnings.java
core/common/src/main/java/alluxio/concurrent/WeakSafeReentrantReadWriteLock.java
core/common/src/main/java/alluxio/grpc/GrpcServerBuilder.java
core/common/src/main/java/alluxio/grpc/ServiceVersionClientServiceHandler.java
core/common/src/main/java/alluxio/security/user/UserState.java
core/common/src/main/java/alluxio/util/executor/ControllableScheduler.java
core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
core/server/common/src/main/java/alluxio/util/EnvironmentUtils.java
core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
core/server/master/src/main/java/alluxio/master/journal/tool/JournalTool.java
core/server/worker/src/main/java/alluxio/worker/grpc/BlockWorkerClientServiceHandler.java
core/server/worker/src/main/java/alluxio/worker/grpc/BlockWriteHandler.java
core/server/worker/src/main/java/alluxio/worker/grpc/UfsFallbackBlockWriteHandler.java
core/server/worker/src/main/java/alluxio/worker/grpc/UfsFileWriteHandler.java
pom.xml
stress/common/src/main/java/alluxio/stress/common/SummaryStatistics.java
stress/common/src/main/java/alluxio/stress/jobservice/JobServiceBenchTaskResultStatistics.java
stress/common/src/main/java/alluxio/stress/master/MasterBenchTaskResultStatistics.java
stress/shell/src/main/java/alluxio/stress/cli/Benchmark.java
stress/shell/src/main/java/alluxio/stress/cli/StressJobServiceBench.java
stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java
stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java
tests/src/main/java/alluxio/master/backcompat/ops/Mount.java

Remove dependency on com.github.spotbugs:spotbugs-annotations
Reduce dependency on external annotations
n/a

Remove com.github.spotbugs:spotbugs-annotations

---

docs/en/operation/StressBench.md

Document common benchmark options.
Follow-up of PR #14001.
The benchmark CLI interface lacks documentation.
No.

[DOCFIX] Document common benchmark options

---

docs/en/deploy/Running-Alluxio-On-Docker.md

Add a short paragraph to introduce alluxio/alluxio-dev. What it is for and what's the difference between it and alluxio/alluxio.

[DOCFIX] Introduce alluxio-dev in Docker doc

---

docs/cn/compute/Hive.md

Fix #14085 
There is no guidance on how to move the Hive partitioned table in the Chinese document.
So I added related content.

[DOCFIX] Update Hive.md

---

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java

Fix a null pointer problem in journal system.
When construct the RaftJournalSystem, the member mStateMachine is null pointer, because the registerMetrics is called before mStateMachine initialized。
No
No

Fix a null pointer exception

---

docs/en/operation/StressBench.md

Update stressbench doc
mark it experimental
na

[DOCFIX] Update StressBench.md

---

core/common/src/main/java/alluxio/metrics/MetricsSystem.java
core/common/src/main/java/alluxio/resource/DynamicResourcePool.java

Add lock pool metrics
Give users a way to monitor lock pool usage. 
Additional metrics

Add lock pool metrics

---

core/common/src/main/java/alluxio/master/PollingMasterInquireClient.java

Fixes https://github.com/Alluxio/alluxio/issues/14109

Catch CancelledException during adress query

---

docs/en/operation/Performance-Tuning.md
docs/en/operation/Scalability-Tuning.md

Add descriptions of key metrics relevant to tuning
Make it more clear and easy to find critical metrics
Doc  changes

[DOCFIX] Add some key metrics to the tuning docs

---

core/common/src/main/java/alluxio/AbstractClient.java
core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java
core/common/src/main/java/alluxio/util/ConfigurationUtils.java
core/server/master/src/main/java/alluxio/master/meta/RetryHandlingMetaMasterMasterClient.java
core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
core/server/worker/src/main/java/alluxio/worker/file/FileSystemMasterClient.java
docs/en/operation/Scalability-Tuning.md
job/client/src/main/java/alluxio/client/job/RetryHandlingJobMasterClient.java
job/server/src/main/java/alluxio/master/file/FileSystemMasterClient.java
job/server/src/main/java/alluxio/worker/job/RetryHandlingJobMasterClient.java
table/client/src/main/java/alluxio/client/table/RetryHandlingTableMasterClient.java

Fixes https://github.com/Alluxio/alluxio/issues/14110

Introduce deadlines for sync RPC stubs

---

docs/en/operation/Performance-Tuning.md

Improve user documentation on async caching

[DOCFIX] Improve Async cache docs

---

dev/intellij/runConfigurations/AlluxioJobMaster_0.xml
dev/intellij/runConfigurations/AlluxioJobMaster_1.xml
dev/intellij/runConfigurations/AlluxioJobMaster_2.xml
docs/en/contributor/Contributor-Tools.md

Add tools for intellij to start local HA JobMaster process., this pr is a Is a supplement to pr #14042
It is convenient to debug and test job master in intellij. 
1. Add AlluxioJobMaster xml file to dev/intellij directory
2. Update the doc.
No
No

Support running HA JobMaster process in intellij

---

docs/en/core-services/Unified-Namespace.md

[DOCFIX] Update Unified-Namespace.md

---

core/common/src/main/java/alluxio/AbstractClient.java
core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/main/java/alluxio/security/authentication/ChannelAuthenticator.java
core/common/src/main/java/alluxio/util/ConfigurationUtils.java
core/server/master/src/main/java/alluxio/master/meta/RetryHandlingMetaMasterMasterClient.java
core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java
core/server/worker/src/main/java/alluxio/worker/file/FileSystemMasterClient.java
docs/en/operation/Scalability-Tuning.md
job/client/src/main/java/alluxio/client/job/RetryHandlingJobMasterClient.java
job/server/src/main/java/alluxio/master/file/FileSystemMasterClient.java
job/server/src/main/java/alluxio/worker/job/RetryHandlingJobMasterClient.java
table/client/src/main/java/alluxio/client/table/RetryHandlingTableMasterClient.java

This reverts commit fa5230706b429350160084268d1e925b67ce4ce9.

Revert "Introduce deadlines for sync RPC stubs"

---

docs/en/operation/Scalability-Tuning.md

Improve docs for when services are colocated

[DOCFIX] Add guidelines for resource allocation with colocated services

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java

Add metric of raft journal index

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
core/server/common/src/main/java/alluxio/master/audit/AsyncUserAccessAuditLogWriter.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java

Add metric of audit log

---

core/client/fs/src/main/java/alluxio/client/block/options/GetWorkerReportOptions.java
core/common/src/main/java/alluxio/util/webui/NodeInfo.java
core/common/src/main/java/alluxio/wire/WorkerInfo.java
core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
webui/master/src/constants/types/INodeInfo.tsx
webui/master/src/containers/pages/Workers/Workers.tsx
webui/master/src/containers/pages/Workers/__snapshots__/Workers.test.tsx.snap

Display block count of each worker in alluxio master ui.
Leverage this, we can clear found the skew of block storage.

Display block count for each worker in the master webui

---

docs/en/operation/Basic-Logging.md

Update docs
`AlluxioJniFilesystem` is the default FUSE implementation now.
Correct the docs.
No

[DOCFIX] Update Basic-Logging.md

---

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java

Fix leader master priority always 0

---

core/common/src/main/java/alluxio/conf/CredentialPropertyKeys.java
core/common/src/main/java/alluxio/conf/SensitiveConfigMask.java
core/common/src/test/java/alluxio/conf/CredentialConfigItemsTest.java
core/server/common/src/main/java/alluxio/RpcSensitiveConfigMask.java
core/server/common/src/main/java/alluxio/RpcUtils.java
core/server/common/src/test/java/alluxio/RpcSensitiveConfigMaskTest.java

In some rpc error or debug enabled, some credential would be printed,
those kinds of information should be masked.
This change is to mask the credential before printing it to log.
Without the fix, there is a potential credential leak issue.
No any user facing.
pr-link: Alluxio/alluxio#13971
change-id: cid-d1667eb155421e2906aaeb3c83a0fa73c11c8e10

Port changes of [#13971] to branch-2.6

---

core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java

Fix the Worker.BlocksEvicted is zero all the time issue

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java

Add a metrics to identify how many jobs started in master.
Give a way to know how many jobs are not completed yet, for example sometimes we want to know  the evict job number then get useful  information of remote read problem.
No
No

Add active job size  metric

---

docs/en/reference/Metrics-List.md

Fix the List of metrics page https://docs.alluxio.io/os/user/stable/en/reference/Metrics-List.html#fuse-metrics
docs

Fix Metrics page

---

docs/en/ufs/NFS.md

Make sure user do not use attribute cache in NFS. 
Otherwise the user will see failures because of the cache.

[DOCFIX] Add nfs attribute cache config to our NFS guide

---

core/client/fs/src/main/java/alluxio/client/file/AlluxioFileOutStream.java
core/client/fs/src/main/java/alluxio/util/FileSystemOptions.java
core/client/fs/src/test/java/alluxio/client/file/BaseFileSystemTest.java
core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/main/java/alluxio/metrics/MetricKey.java
core/common/src/main/java/alluxio/wire/OperationId.java
core/common/src/test/java/alluxio/AuthenticatedUserRule.java
core/server/common/src/main/java/alluxio/master/journal/raft/JournalStateMachine.java
core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalWriter.java
core/server/common/src/test/java/alluxio/master/journal/JournalEntryAssociationTest.java
core/server/common/src/test/java/alluxio/master/journal/raft/RaftJournalTest.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/RpcContext.java
core/server/master/src/main/java/alluxio/master/file/contexts/CompleteFileContext.java
core/server/master/src/main/java/alluxio/master/file/contexts/CreateDirectoryContext.java
core/server/master/src/main/java/alluxio/master/file/contexts/CreateFileContext.java
core/server/master/src/main/java/alluxio/master/file/contexts/DeleteContext.java
core/server/master/src/main/java/alluxio/master/file/contexts/OperationContext.java
core/server/master/src/main/java/alluxio/master/file/contexts/RenameContext.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/main/java/alluxio/master/file/meta/InodeTreePersistentState.java
core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
core/transport/src/main/proto/grpc/file_system_master.proto
core/transport/src/main/proto/proto/journal/journal.proto
tests/src/test/java/alluxio/client/fs/FileSystemMasterIntegrationTest.java
tests/src/test/java/alluxio/server/ft/FileSystemMasterFaultToleranceIntegrationTest.java

Fix https://github.com/Alluxio/alluxio/issues/14113

Implement FS operation tracking for improving partition tolerance

---

docs/en/operation/StressBench.md

Update the Fuse stressbench doc
Give users clear ideas of what is fuse stressbench
Doc

Improve Fuse stressbench doc

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
docs/en/ufs/S3.md
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java

Fixes #14133 
Solves the issue that S3 cannot recognize endpoint region and supports OCI object storage
add an s3 region property key

Set S3 endpoint region and support OCI object storage

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
docs/en/ufs/S3.md
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java

Fix #14354 accessing the S3 bucket in non-default region issue
Otherwise users cannot access s3 buckets in another region
Yes, affect how they accessing bucket in other regions

Fix s3 bucket region

---

bin/alluxio-start.sh

Update alluxio-start.sh for fix the hub manager command name

---

pom.xml

Bump rocksdb to 6.25.3 to possibly address segfault issue

Bump rocksdb version to 6.25.3

---

core/server/master/src/main/java/alluxio/master/file/meta/InodeTree.java
core/server/master/src/main/java/alluxio/master/file/meta/SimpleInodeLockList.java

These changes are being made to address the following leak message:
```
2021-10-23 18:17:29,940 ERROR AlluxioResourceLeakDetector - LEAK:
LockResource.close() was not called before resource is
garbage-collected. See
https://docs.alluxio.io/os/user/stable/en/operation/Troubleshooting.html#resource-leak-detection
for more information about this message.
Recent access records:
Created at:
alluxio.resource.LockResource.<init>(LockResource.java:46)
alluxio.resource.LockResource.<init>(LockResource.java:70)
alluxio.resource.RWLockResource.<init>(RWLockResource.java:39)
alluxio.resource.RefCountLockResource.<init>(RefCountLockResource.java:54)
alluxio.collections.LockPool.get(LockPool.java:210)
alluxio.master.file.meta.InodeLockManager.lockInode(InodeLockManager.java:169) …
```

Resolve lock leak during recursive delete

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
core/server/common/src/main/java/alluxio/master/AlluxioExecutorService.java
core/server/common/src/main/java/alluxio/master/ExecutorServiceBuilder.java
core/server/common/src/test/java/alluxio/master/ExecutorServiceBuilderTest.java
core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java
job/server/src/main/java/alluxio/master/job/plan/PlanTracker.java

Implement configurable ExecutorService creation for Alluxio processes

---

core/common/src/main/java/alluxio/metrics/MetricKey.java

Add some indication of the metric master rpc queue length

Add metric Master.RpcQueueLength description

---

docs/en/ufs/HDFS.md

[DOCFIX] Fix HDFS Doc minor stuff

---

docs/en/contributor/Contributor-Tools.md

Improve documentation on contributor tools.

[DOCFIX] Improve Contributor Tools documentation

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md
integration/kubernetes/README.md

This docfix isn't addressing any individual issue with the doc, but rather a slight refactor of various sections & their orders for general clarity.

[DOCFIX] Clarify Kubernetes documentation

---

docs/en/operation/Upgrade.md

This DOCFIX is just for some additional clarity & hyperlinks in the "Upgrading" doc.

[DOCFIX] Add ToC and links to Upgrading doc

---

core/common/src/main/java/alluxio/metrics/MetricKey.java
core/server/master/src/main/java/alluxio/master/file/LostFileDetector.java

Fix #14400, and tweak metric description.

Fix master lost file count metric is always 0

---

core/common/src/main/java/alluxio/AlluxioURI.java

fix some test case under winows.
When I run the test under windows I found that some test cases under `AlluxioURITest` can't pass. This PR fixes the problem.
No user facing change.

[SMALLFIX] Fix some test case under Windows

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
docs/en/operation/Journal.md
shell/src/main/java/alluxio/cli/fsadmin/command/BackupCommand.java

[DOCFIX] Fix `Journal.md` and related strings in code

---

docs/en/operation/Metrics-System.md

[DOCFIX] Update `Metrics-System.md`

---

docs/_data/table/s3-api-supported-operations.csv
docs/en/api/FS-API.md
docs/en/api/S3-API.md

documentation updates and improvements for the FS-API and S3-API pages
Many recent updates to the S3 API since the last release
no

[DOCFIX] Update FS and S3 API documentation

---

docs/en/overview/Getting-Started.md

Minor tweaks to the quick start guide.

[DOCFIX] Improve quick start guide

---

docs/en/operation/Performance-Tuning.md

[DOCFIX] Update perf doc

---

docs/en/operation/Metrics-System.md

[DOCFIX] Fix some formatting issues in Metrics-System.md

---

docs/en/core-services/Unified-Namespace.md

the alluxio fs ls -R / command with the R flag will list out the files recursively, including the /demo/hello file

[DOCFIX] Update unified namespace doc example comment

---

docs/en/contributor/Building-Alluxio-From-Source.md

[DOCFIX] Fix "building from source" doc

---

docs/en/operation/Admin-CLI.md

Add documentation for updateConf command

[DOCFIX] Add doc for updateConf command

---

integration/jnifuse/native/src/main/native/libjnifuse/jnifuse_helper.cc

Fix some codestyle

---

docs/en/deploy/Running-Alluxio-On-a-HA-Cluster.md
docs/en/operation/Journal.md

[DOCFIX] Update verbiage and some tutorials on deploying HA cluster

---

underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java

Fix S3 region when not value set in instance

---

dev/intellij/runConfigurations/AlluxioJobMaster.xml
dev/intellij/runConfigurations/AlluxioJobWorker.xml
dev/intellij/runConfigurations/AlluxioMaster.xml
dev/intellij/runConfigurations/AlluxioProxy.xml
dev/intellij/runConfigurations/AlluxioWorker.xml
dev/intellij/runConfigurations/FileSystemShell.xml

Use console as logger type when use intellij.
Outputting logs to the console is more developer friendly

Output logs to the console when use intellij

---

shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java

Fix distributedCp

---

docs/en/operation/User-CLI.md

[DOCFIX] Update job service api doc

---

shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
tests/src/test/java/alluxio/client/cli/fs/command/DistributedCpCommandTest.java
tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java
tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java

Fix recursive pool adding for distributedCP and distributedLoad
3. webui

Fix batch size in user CLI

---

shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
tests/src/test/java/alluxio/client/cli/fs/command/DistributedCpCommandTest.java
tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java

CherryPick master to Branch 2.7

---

core/server/worker/src/main/java/alluxio/worker/grpc/DataMessageServerStreamObserver.java

https://github.com/Alluxio/alluxio/issues/14466

Fix the memory leak in worker cancel scene

---

core/common/src/main/java/alluxio/AbstractJobMasterClient.java

Fix codestyle

---

core/common/src/main/java/alluxio/cli/AbstractShell.java

Remove an unnecessary judgement.
The judgement is redundant, need to remove
3. webui

Fix unnecessary judgement

---

docs/cn/ufs/Ozone.md
docs/en/ufs/Ozone.md
pom.xml
shaded/ozone/pom.xml

Ozone 1.1.0 has been released for a long time and 1.1.0 is more stable than 1.0.0. We can update the ozone version.

Update ozone from 1.0.0 to 1.1.0

---

docs/en/operation/StressBench.md
stress/shell/src/main/java/alluxio/stress/cli/StreamRegisterWorkerBench.java

Add documentation for RPC stress benchmarks.

[DOCFIX] Add doc for RPC stress benchmarks

---

core/server/proxy/src/main/java/alluxio/proxy/s3/ListBucketResult.java
core/server/proxy/src/main/java/alluxio/proxy/s3/S3RestServiceHandler.java
tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java

fix #14532
change S3 API with ListObject and ListObjectV2

Fix S3 API ListObject and ListObjectV2

---

docs/en/deploy/Running-Alluxio-On-Kubernetes.md

Create csi documentation under kubernetes posix-api section, as it is also using Alluxio Posix-api.
co-author Binyang

[DOCFIX] Create CSI Documentation

---

shell/src/main/java/alluxio/cli/fs/command/job/JobAttempt.java

DistributedLoad command cannot retry while encountered exception.

Support retry until policy give up

---

tests/src/test/java/alluxio/client/cli/fs/command/DistributedCpCommandTest.java
tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java

Try to fix the distributedCp test in https://github.com/Alluxio/alluxio/runs/4306117668?check_suite_focus=true
3. webui

Fix distributedCp test

---

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java
core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java

cherry-pick of https://github.com/Alluxio/alluxio/pull/14508 to branch-2.6
pr-link: Alluxio#14508
change-id: cid-bf8b7a723657e1b1e117bbeab6ce205c94e35073

Add more logs for FT and journaling

---

core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java

cherry-pick of https://github.com/Alluxio/alluxio/pull/14509 to branch-2.6
pr-link: #14509
change-id: cid-b6d73fb664837d50f8d6bab0fc9394d6fc2f4b11

Add more logs to RockStore

---

underfs/s3a/src/main/java/alluxio/underfs/s3a/S3ALowLevelOutputStream.java

This is for AmazonS3 client refresh extension

Modify S3ALowLevelOutputStream for potential AmazonS3 client refresh

---

core/server/worker/src/main/java/alluxio/worker/grpc/AbstractWriteHandler.java
core/server/worker/src/main/java/alluxio/worker/grpc/BlockReadHandler.java

Framework code for masking read/write request's potential credential.

Add mask in logging request

---

core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java

Add API to resolve mount id from ufs path in FileSystem

Add API to resolve mount id from ufs path in FileSystem

---

underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AInputStream.java
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3ALowLevelOutputStream.java
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AOutputStream.java

Modify the variable access modifier for usage in S3A ufs subclass

Modify the variable access modifier for usage in S3A ufs stream subclass

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java

Enabling standalone fuse JVM pause monitoring service
Know that whether Fuse process stuck 
No

Enable standalone fuse JVM pause monitoring service

---

docs/en/contributor/Contributor-Tools.md

Add description that another file should also be marked as “Generated Sources Root”.
So the controbuter will mark this file as “Generated Sources Root” and set upt the project.
No, it is only about the document.

[DOCFIX] Update The Contributor-Tools Doc

---

core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java

Minor fix of log message
Format string missing one position parameter.
Nope

Fix worker stream registration log msg

---

docs/en/operation/StressBench.md

[DOCFIX] Fix doc

---

core/server/master/src/main/java/alluxio/master/metastore/rocks/RocksStore.java

Fix logging message template in RocksStore
Fixes https://github.com/Alluxio/new-contributor-tasks/issues/615

Fix logging message template in RocksStore

---

core/common/src/main/java/alluxio/underfs/ObjectUnderFileSystem.java
core/common/src/main/java/alluxio/underfs/UfsFileStatus.java
core/common/src/main/java/alluxio/underfs/UfsStatus.java
core/server/common/src/main/java/alluxio/master/journal/ufs/UfsJournalGarbageCollector.java
core/server/common/src/main/java/alluxio/master/journalv0/ufs/UfsJournalReader.java
core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java
underfs/gcs/src/main/java/alluxio/underfs/gcs/GCSUnderFileSystem.java
underfs/gcs/src/main/java/alluxio/underfs/gcs/v2/GCSV2UnderFileSystem.java
underfs/obs/src/main/java/alluxio/underfs/obs/OBSUnderFileSystem.java
underfs/obs/src/test/java/alluxio/underfs/obs/OBSUnderFileSystemTest.java
underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystem.java
underfs/s3a/src/main/java/alluxio/underfs/s3a/S3AUnderFileSystem.java
underfs/s3a/src/test/java/alluxio/underfs/s3a/S3AUnderFileSystemTest.java
underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java

Fix #14640 
Fix NPE in Object stores getLastModifiedDate().getTime()
No

Fix NPE in UnderFileSystem getLastModifiedDate.getTime

---

core/common/src/main/java/alluxio/exception/ExceptionMessage.java
docs/en/operation/User-CLI.md
job/common/src/main/java/alluxio/job/plan/load/LoadConfig.java
job/common/src/test/java/alluxio/job/plan/load/LoadConfigTest.java
job/common/src/test/java/alluxio/job/workflow/composite/CompositeConfigTest.java
job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java
job/server/src/main/java/alluxio/job/plan/replicate/ReplicateDefinition.java
job/server/src/main/java/alluxio/job/util/JobUtils.java
job/server/src/test/java/alluxio/job/plan/BatchedJobDefinitionTest.java
job/server/src/test/java/alluxio/job/plan/load/LoadDefinitionTest.java
job/server/src/test/java/alluxio/job/plan/replicate/ReplicateDefinitionTest.java
shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
stress/shell/src/main/java/alluxio/stress/cli/StressJobServiceBench.java
tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java
tests/src/test/java/alluxio/job/plan/load/LoadIntegrationTest.java

Update DistributedLoad using cache request instead of read with passive cache.
using read to cache block is not efficient and error proune. Use cache request directly.
no

Update DistributedLoad using cache request

---

core/server/common/pom.xml
core/server/worker/src/main/java/alluxio/worker/block/management/BlockManagementTaskResult.java
pom.xml

Excludes findbugs dependency
Better compliance with third party open source license standards
nope

Exclude findbugs dependency

---

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java

reduce waiting time for change leader
currently, sleeping 20S is too long.
No
issue: https://github.com/Alluxio/alluxio/issues/14563

Reduce wait time for change leader

---

stress/shell/src/main/java/alluxio/stress/cli/fuse/FuseIOBench.java

Small fix for stressbench write test
Correct the stressbench warmup time and throw an exception when write finished before duration passed.
No

Fix for stressbench write test

---

job/server/src/main/java/alluxio/worker/job/task/TaskExecutorManager.java

Fix misleading log when cancel job
3. webui

[SMALLFIX]Fix misleading log

---

core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
core/common/src/main/java/alluxio/metrics/MetricKey.java
core/common/src/main/java/alluxio/metrics/MetricsSystem.java
integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java

Add FUSE and client metrics
Understand the Fuse or client load
Add two centralized metrics

Add Fuse and client alarm metrics

---

core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java

Modify the placeholder from "%s" to "{}" in the LOG statement.
1. The performance of `{}` is better than `%s`，considering `%s` will cause memory overhead and generate temporary objects.
No.
Fixes Alluxio/new-contributor-tasks#617

[SMALLFIX] Fix logging message template in AlluxioMasterProcess

---

core/common/src/main/java/alluxio/conf/PropertyKey.java

Fix some code style.
Code style
No

Use boolean instead of String as default value type

---

core/client/fs/src/main/java/alluxio/client/file/AlluxioFileOutStream.java
core/client/fs/src/main/java/alluxio/client/file/cache/CacheManager.java
core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
core/client/fs/src/main/java/alluxio/client/file/cache/DefaultMetaStore.java
core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheFileInStream.java
core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
core/client/fs/src/main/java/alluxio/client/file/cache/NoExceptionCacheManager.java
core/client/fs/src/main/java/alluxio/client/file/cache/TimeBoundPageStore.java
core/server/common/src/main/java/alluxio/RpcUtils.java
core/server/common/src/main/java/alluxio/master/journal/AsyncJournalWriter.java
job/common/src/main/java/alluxio/job/plan/meta/PlanInfo.java
job/server/src/main/java/alluxio/job/workflow/WorkflowExecution.java

Fixes https://github.com/Alluxio/alluxio/issues/14666
Timer/Meter metrics show incorrect value after clearing metrics
Show correct metrics

Fix metrics timer/meter after clearing metrics

---

core/common/src/main/java/alluxio/wire/WorkerWebUIOverview.java
core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerRestServiceHandler.java
webui/worker/src/containers/pages/Overview/Overview.tsx
webui/worker/src/containers/pages/Overview/__snapshots__/Overview.test.tsx.snap
webui/worker/src/store/overview/reducer.tsx
webui/worker/src/store/overview/types.tsx

Display worker block count in webui overview.
Let the user see this worker's block count more directly
Worker web ui change, display the block count on overview page.

Display worker block count in worker webui

---

core/server/common/src/main/java/alluxio/master/AbstractMaster.java

`Collections.emptySet()` returns a singleton so no new objects are created just as an empty set.

[SMALLFIX] Use Collection.emptySet to save new object

---

core/server/master/src/main/java/alluxio/underfs/UfsStatusCache.java

Specify size in HashSet init to avoid resizing

[SMALLFIX] Add size in HashSet init

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java

Fixes #14713
Show correct bytes written in Fuse.getattr() when file is writing to that fuse mount point

Set Fuse getattr size to output stream bytes written

---

hub/server/src/test/java/alluxio/hub/test/BaseHubTest.java

Hub tests require Cluster ID and also reducing registration time to speed up tests.
See above.
No

Add Hub property keys to fix and speed up tests

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java

Help identify write failure cases because of non-sequential write e.g. #14708
Write succeed doesn't mean the content are written correctly
Yeah, error out when non-sequential write detected

Improve write error message

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java

Support resolve override from open flag

---

logserver/src/main/java/alluxio/logserver/AlluxioLog4jSocketNode.java

This is to validate the input stream to perform validation

Fix logserver validation

---

docs/cn/core-services/Unified-Namespace.md

[DOCFIX] Update unified-namespace doc

---

core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java

Skip replica check when there are no workers.

Skip replica check when there are no workers

---

docs/en/compute/Tensorflow.md

[DOCFIX] Fix typo in tensorflow doc

---

logserver/src/main/java/alluxio/logserver/AlluxioLog4jSocketNode.java

Fix logserver

---

core/server/master/src/main/java/alluxio/master/file/replication/ReplicationChecker.java
core/server/master/src/test/java/alluxio/master/file/replication/ReplicationCheckerTest.java

Fix https://github.com/Alluxio/alluxio/issues/14760

Fix ReplicationChecker unit tests

---

docs/en/api/POSIX-API.md
docs/en/operation/Metrics-System.md
docs/en/reference/Metrics-List.md

Improve Fuse metrics docs

---

core/server/worker/src/main/java/alluxio/worker/block/io/StoreBlockReader.java
core/server/worker/src/main/java/alluxio/worker/block/io/StoreBlockWriter.java

Refactor for extension

---

tests/src/test/java/alluxio/client/fs/FileSystemMasterRestartIntegrationTest.java

Fix FileSystemMasterRestartIntegrationTest

Fix FileSystemMasterRestartIntegrationTest

---

core/client/fs/src/main/java/alluxio/client/file/cache/CacheManagerWithShadowCache.java
core/server/common/src/main/java/alluxio/AbstractStorageTierAssoc.java
core/server/master/src/main/java/alluxio/master/file/UfsSyncChecker.java
pom.xml

Try updating guava to resolve some CVEs.
Some CVEs are caused by guava. This PR updates guava to a fixed version.
No.

Update guava to fix some CVEs

---

core/common/src/test/java/alluxio/TestLoggerRule.java
core/common/src/test/java/alluxio/util/JvmPauseMonitorTest.java
tests/src/test/java/alluxio/job/plan/replicate/ReplicateIntegrationTest.java

fix jvm pause monitor unstable test
When GC happends while running this test it will cause test to fail.

Fix jvm pause monitor unstable test

---

pom.xml

Try updating jersey to resolve some CVEs.
Some CVEs are caused by jersey. This PR updates jersey to a fixed version.
No

Update jersey version

---

pom.xml

Try updating kubernetes packages to resolve some CVEs.
Some CVEs are caused by these packages. This PR updates them to fixed versions.
No.

Update kubernetes packages

---

stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java

1. log exceptions and stack trace other than only the error message.
2. add more logs to to provide feedback on where the benchmark is spending its time.

Add more logging messages to stress master bench

---

docs/cn/api/POSIX-API.md
docs/en/api/POSIX-API.md

FIx issue #14776
Add fuse shell doc 
No

Add fuse shell doc

---

core/server/master/src/main/java/alluxio/master/metastore/caching/StatsCounter.java

Bug Fix
fix cacheHitRatio calculation
No

Fix incorrect calc of cacheHitRatio

---

docs/en/ufs/HDFS.md

Add HDFS Versions of 2.10.
Alluxio also can be running on Hdfs-2.10.
NO

[DOCFIX] Add 2.10 to HDFS.md

---

core/client/hdfs/src/main/java/alluxio/hadoop/FileSystem.java

Remove final of FileSystem to support extension.
Just remove the final of Filesystem.
No

Remove final of FileSystem to support extension

---

core/server/common/src/main/java/alluxio/util/EnvironmentUtils.java

Fix a NPE error when running test

---

conf/alluxio-env.sh.template
integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java

add the descriptions of ALLUXIO_JOB_MASTER_JAVA_OPTS and ALLUXIO_JOB_WORKER_JAVA_OPTS
Better help others to configure the environment
no

Add the descriptions of JAVA_OPTS in alluxio-env.sh.template

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java

Support concurrent read() in Fuse.open(READ_WRITE open flag).
Otherwise Fuse.read() may create two FileInStream concurrently and cause problems.
To avoid concurrent read creates two file in stream concurrently
NA

Fix the concurrent read/write in Fuse.open(READ_WRITE)

---

core/server/master/src/main/java/alluxio/master/block/meta/StaticWorkerMeta.java
job/server/src/main/java/alluxio/master/job/JobMaster.java
job/server/src/main/java/alluxio/master/job/plan/PlanTracker.java

Fix annotation imports so we do not depend on unnecessary packages.

Fix annotation imports

---

underfs/hdfs/pom.xml

Modify the hdfs ufsConstants output path
Make it consistent with https://github.com/Alluxio/alluxio/blob/master/core/common/pom.xml#L206

[SMALLFIX] Modify the hdfs ufsConstants output path

---

docs/en/contributor/Code-Conventions.md

Fix wrong documentation in logging convention
Motivated by https://github.com/Alluxio/alluxio/pull/14278
Previous documentation on how to log is flawed
N/A

[DOCFIX] Update guide on logging convention

---

core/server/common/pom.xml
pom.xml

Related to https://github.com/Alluxio/alluxio/pull/14870

Separate ratis dependencies between alluxio server and ufs ozone

---

pom.xml

Update hadoop version to fix some CVEs.
3.3.0 hadoop libraries have vulnerable dependencies. 3.3.1 fixes some of them.
No.

Update hadoop dependencies

---

shell/src/main/java/alluxio/common/RpcPortHealthCheckClient.java

Show retry count as we retry to connect to keep the user informed.

Fix process checker error message to include retry count

---

dev/scripts/watch-metrics.sh

This is primarily a convenience script for devs to capture & observe Alluxio metrics. There are no affected components of the codebase since this is a standalone shell script.

Add dev shell script to capture metrics HTTP json sink

---

shell/src/main/java/alluxio/cli/fs/command/HelpCommand.java

Added terminal close code
Many warnings when executing command `alluxio fs help`
```shell
[root@centos /alluxio]# bin/alluxio fs help
Listening for transport dt_socket at address: 5005
Jan 25, 2022 7:41:06 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
Jan 25, 2022 7:41:48 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
Listening for transport dt_socket at address: 5005
Jan 25, 2022 7:48:12 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
Jan 25, 2022 7:48:12 PM org.jline.utils.Log logr
//.....
cat: Prints the …
```

Fix not closing terminal

---

core/server/common/src/main/java/alluxio/RpcUtils.java
pom.xml
shaded/hadoop/pom.xml
underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java

Fix shading so webhdfs support works.
3. webui

Fix shading for webHdfs

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseOpenUtils.java
integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
integration/fuse/src/test/java/alluxio/fuse/AlluxioFuseOpenUtilsTest.java
integration/fuse/src/test/java/alluxio/fuse/AlluxioJniFuseFileSystemTest.java

Fixes #14895
Fix Fuse open flag with O_TRUNC
Fix how Alluxio deal with Fuse open flags
Otherwise we cannot deal with fuse open flags correctly
Yeah, without O_TRUNC file will not be deleted
co-author liuyongqing

Fix fuse open flag with O_TRUNC

---

docs/en/deploy/Running-Alluxio-On-a-Cluster.md

add a statement describing that user must use sudo command without inputting password.
1. If not, the other nodes will waiting for inputting password but nobody will do it.
no

[DOCFIX] Add doc on running sudo without password

---

core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
core/client/fs/src/test/java/alluxio/client/file/MockFileSystemMasterClient.java
core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
core/server/master/src/main/java/alluxio/master/file/contexts/ExistsContext.java
core/transport/src/main/proto/grpc/file_system_master.proto
core/transport/src/main/proto/proto.lock
integration/fuse/src/test/java/alluxio/fuse/cli/MockFuseFileSystemMasterClient.java

Add `exists` API to file system master, fixes #8852.

Add exists API to FileSystemMaster

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java

Error out if rename while writing, until rename is supporting while writing.
https://github.com/Alluxio/alluxio/issues/14854
Error out if rename while writing, 
Otherwise, the write will error out because FileOutStream still think it's closing the original file.
Give user clear message when the functionality cannot be supported.
rename while writing will error out directly and give clear message

Avoid rename in Fuse while file is not completed

---

core/server/common/src/main/java/alluxio/master/AbstractMaster.java

Mark filed `mExecutorServiceFactory` in `AbstractMaster.java` as `final`
Close Alluxio/new-contributor-tasks#627

Fix Mark field as final in AbstractMaster.java

---

core/common/src/main/java/alluxio/conf/AlluxioProperties.java

Fix Property isSet function, make check scope the same as before applying #14887 
EE authentication unit test would fail without this change
NA

Fix Property isSet

---

core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
core/common/src/main/java/alluxio/conf/PropertyKey.java
core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
core/common/src/test/java/alluxio/conf/PropertyKeyTest.java

Add support for customize PropertyKey validation function

---

core/server/master/src/test/java/alluxio/master/AlluxioMasterProcessTest.java

Skip stopAfterStandbyTransition test.
This test is flaky in github action and we cover this case in internal test infra.
no

Skip stopAfterStandbyTransition test

---

core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java
core/common/src/test/java/alluxio/test/util/ConcurrencyUtils.java
tests/src/test/java/alluxio/client/fs/concurrent/ConcurrentFileInStreamIntegrationTest.java

Repro and fix flakiness in ConcurrentFileInStreamIntegrationTest#FileInStreamConcurrency

Fix flaky ConcurrentFileInStreamIntegrationTest

---

build/checkstyle/suppressions.xml
hub/server/src/main/java/alluxio/hub/manager/process/ManagerProcessContext.java

Fix Hub ManagerProcessContext checkstyle errors

---

docs/cn/ufs/S3.md

fix docs docs/cn/ufs/S3.md, change alluxio-env.sh to alluxio-site.properties
Fixes＃15035

[SMALLFIX] Fix S3 Document

---

core/common/src/main/java/alluxio/exception/JobDoesNotExistException.java

change jobId to number format
Fixes #15032

[SMALLFIX] Fix jobId format in JobDoesNotExistException

---

core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
core/client/fs/src/main/java/alluxio/client/file/cache/PageStore.java
core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStore.java
core/client/fs/src/main/java/alluxio/client/file/cache/store/MemoryPageStoreOptions.java
core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreOptions.java
core/client/fs/src/main/java/alluxio/client/file/cache/store/PageStoreType.java
core/client/fs/src/test/java/alluxio/client/file/cache/LocalCacheManagerWithMemPageStoreTest.java
core/client/fs/src/test/java/alluxio/client/file/cache/store/MemoryPageStoreTest.java

Add the third PageStore type: MEM, to support caching data in memory.
Please see the description in #14771 .
1. Add a new PageStore type: MEM

Support to cache data in memory when using Alluxio Local Cache

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioFuse.java
integration/fuse/src/main/java/alluxio/fuse/AlluxioFuseUtils.java
integration/fuse/src/main/java/alluxio/fuse/FuseSignalHandler.java
integration/jnifuse/fs/src/main/java/alluxio/jnifuse/AbstractFuseFileSystem.java

Improve Alluxio Fuse error handling and logs
1. To reduce the chance of unexpected throwable throws in java code and cause the native thread crash.
2. To improve logging when unexpected behaviors happen
improves logs for debugging

Improve Alluxio Fuse error handling and logs

---

job/common/src/main/java/alluxio/job/plan/meta/PlanInfo.java

1. Fix Alluxio/new-contributor-tasks#635
2. Close Alluxio/new-contributor-tasks#635
3. webui

[SMALLFIX]Fix logging message of PlanInfo

---

core/common/src/main/java/alluxio/wire/JournalDiskInfo.java
core/server/master/src/main/java/alluxio/master/meta/JournalSpaceMonitor.java
core/server/master/src/test/java/alluxio/master/meta/JournalSpaceMonitorTest.java

Add `mDiskType` property in class JournalDiskInfo.java and compose a complete disk path with schema based on disk type.
Fix https://github.com/Alluxio/alluxio/issues/14915
No.

Fix UI Overview page error when journal file type is nfs

---

hub/server/src/main/java/alluxio/hub/manager/process/ManagerProcessContext.java

Fix logging messages in hub/server/src/main/java/alluxio/hub/manager/process/ManagerProcessContext.java
Fix #634 https://github.com/Alluxio/new-contributor-tasks/issues/634
None

[SMALLFIX] Fix logging message in ManagerProcessContext.java

---

shell/src/main/java/alluxio/cli/bundler/command/ExecuteShellCollectInfoCommand.java

Fix Alluxio/new-contributor-tasks#633
Fix the logging message in ExecuteShellCollectInfoCommand.
Improve logging format.
No.

[SMALLFIX]Fix the logging message in ExecuteShellCollectInfoCommand

---

core/client/fs/src/main/java/alluxio/client/block/policy/CapacityBaseRandomPolicy.java
core/client/fs/src/test/java/alluxio/client/block/policy/CapacityBaseRandomPolicyTest.java

used for cluster of workers with different capacity.
Close Alluxio/alluxio#15012

Add capacity base random policy

---

stress/common/src/main/java/alluxio/stress/master/MasterBenchParameters.java
stress/shell/src/main/java/alluxio/stress/cli/StressJobServiceBench.java
stress/shell/src/main/java/alluxio/stress/cli/StressMasterBench.java
stress/shell/src/main/java/alluxio/stress/cli/client/StressClientIOBench.java
stress/shell/src/main/java/alluxio/stress/cli/worker/StressWorkerBench.java

Add description article to StressClientIOBench and StressWorkerBench to introduce their function and usage. Add description to the fixed-count parameter of StressMasterBench to describe its usage in some operation.
The description will help the user find understand the StressBench tool easier.
There is no changes to the user.

[SMALLFIX] Add description to some StressBench tool

---

core/server/master/src/test/java/alluxio/master/block/BlockMasterMetricsTest.java
core/server/worker/src/test/java/alluxio/worker/block/BlockWorkerMetricsTest.java

Fix missing unit tests
Some unit tests were not executed because of missing `@Test` annotation
NO

Fix missing unit tests

---

shell/src/main/java/alluxio/cli/bundler/command/CollectMetricsCommand.java

Fix Alluxio/new-contributor-tasks#632
Fix the logging message in CollectMetricsCommand when failed to get metrics.
Improve logging format.
No.

[SMALLFIX] Fix the logging message in CollectMetricsCommand

---

core/common/src/main/java/alluxio/exception/AlluxioException.java

Fixes https://github.com/Alluxio/new-contributor-tasks/issues/626
change "It must be able serialize" to "It must be able to serialize"
Fix a grammar mistake
No

[SMALLFIX] Fix a grammar mistake

---

docs/_data/table/en/env_vars.yml
docs/cn/operation/Configuration.md

[DOCFIX] Fix job service configuration doc

---

job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java
job/server/src/main/java/alluxio/worker/job/task/TaskExecutor.java
shell/src/main/java/alluxio/cli/fs/command/AbstractDistributedJobCommand.java
shell/src/main/java/alluxio/cli/fs/command/DistributedCpCommand.java
shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
shell/src/main/java/alluxio/cli/fs/command/DistributedLoadUtils.java
shell/src/main/java/alluxio/cli/fs/command/job/JobAttempt.java
tests/src/test/java/alluxio/client/cli/fs/command/DistributedCpCancelTest.java
tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java

Add patch to 2.7

---

dev/jenkins/Dockerfile-jdk11
dev/jenkins/Dockerfile-jdk8

Add libfuse-dev so we could compile native code of jnifuse in alluxio/alluxio-maven docker image

Add libfuse-dev into alluxio/alluxio-maven image

---

integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
integration/jnifuse/fs/src/main/java/alluxio/jnifuse/AbstractFuseFileSystem.java
integration/jnifuse/fs/src/main/java/alluxio/jnifuse/FuseFileSystem.java

Add `utimensCallback` in `AbstractFuseFileSystem` for consistency
For naming consistency
No

Fix utimens in JNIFuse

---

core/client/fs/src/main/java/alluxio/client/file/SeekableAlluxioFileOutStream.java
core/common/src/main/java/alluxio/conf/PropertyKey.java
integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java
tests/src/test/java/alluxio/client/fs/io/SeekableAlluxioFileOutStreamIntegrationTest.java
tests/src/test/java/alluxio/client/fuse/AbstractFuseIntegrationTest.java
tests/src/test/java/alluxio/client/fuse/JNIFuseIntegrationTest.java

Support read-write open through FUSE for specific files

---

integration/hub-elastic/filebeat/filebeat-start.sh
integration/hub-elastic/logstash/logstash-start.sh
integration/hub-elastic/metricbeat/metricbeat-start.sh

See title.
Prevents  potential `sed` syntax issues across different architectures.
No.

Use perl instead of sed for Hub Elastic helper scripts

---

bin/alluxio-monitor.sh

Fix port in use while use jmx jvm argument

---

docs/en/api/FS-API.md

Fix the code example in the document of fs-api
The code example is incorrect
n/a

Fix the code example in the document of fs-api

---

shaded/client/pom.xml

Include rocksdb into shaded client jar
Fix no class found exception when using rocksdb storage of the local cache
None

Include rocksdb into shaded client jar

---

core/common/src/main/java/alluxio/worker/block/BlockWorker.java
core/common/src/main/java/alluxio/worker/block/CreateBlockOptions.java
core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
core/server/worker/src/test/java/alluxio/worker/block/NoopBlockWorker.java

Add a new createBlock API

---

core/common/src/main/java/alluxio/conf/PropertyKey.java
integration/docker/entrypoint.sh
integration/fuse/bin/alluxio-fuse
integration/fuse/src/main/java/alluxio/fuse/AlluxioJniFuseFileSystem.java

Fixes #15161
Fix the alluxio-fuse umount behavior to match the linux syntax.
To support soft and hard alluxio-fuse umount behavior
Yes, related to how they unmount alluxio-fuse

Improve fuse umount

---

core/common/src/main/java/alluxio/conf/PropertyKey.java

Fixes the wrong property builder
For maven build to pass
NA

Fix the property builder

---

docs/cn/api/POSIX-API.md
docs/en/api/POSIX-API.md

Add docs about libfuse3.
#15002 adds support for libfuse3. This PR adds docs about FUSE with libfuse3.
No.

[DOCFIX] Add docs about libfuse3

---

core/server/common/src/main/java/alluxio/master/journal/raft/RaftJournalSystem.java

Remove useless code in raft journal system
This code is no longer useful, as it will be judged later.

Remove useless code in raft journal system

---

core/client/fs/src/main/java/alluxio/client/block/BlockStoreClient.java
core/client/fs/src/main/java/alluxio/client/file/AlluxioFileInStream.java
core/client/fs/src/main/java/alluxio/client/file/AlluxioFileOutStream.java
core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
core/client/fs/src/test/java/alluxio/client/block/BlockStoreClientTest.java
core/client/fs/src/test/java/alluxio/client/file/AlluxioFileInStreamTest.java
core/client/fs/src/test/java/alluxio/client/file/FileOutStreamTest.java
core/client/hdfs/src/test/java/alluxio/hadoop/AbstractFileSystemTest.java
job/server/src/main/java/alluxio/job/plan/replicate/EvictDefinition.java
job/server/src/main/java/alluxio/job/plan/replicate/ReplicateDefinition.java
job/server/src/main/java/alluxio/job/util/JobUtils.java
job/server/src/test/java/alluxio/job/plan/BatchedJobDefinitionTest.java
job/server/src/test/java/alluxio/job/plan/load/LoadDefinitionTest.java
job/server/src/test/java/alluxio/job/plan/migrate/MigrateDefinitionSelectExecutorsTest.java
job/server/src/test/java/alluxio/job/plan/persist/PersistDefinitionTest.java
job/server/src/test/java/alluxio/job/plan/replicate/EvictDefinitionTest.java
job/server/src/test/java/alluxio/job/plan/replicate/ReplicateDefinitionTest.java
shell/src/main/java/alluxio/cli/fs/command/GetCapacityBytesCommand.java
shell/src/main/java/alluxio/cli/fs/command/GetUsedBytesCommand.java
shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
shell/src/main/java/alluxio/cli/fs/command/LocationCommand.java
shell/src/main/java/alluxio/cli/fs/command/StatCommand.java
tests/src/test/java/alluxio/client/fs/RemoteReadIntegrationTest.java
tests/src/test/java/alluxio/server/ft/MasterFaultToleranceIntegrationTest.java
tests/src/test/java/alluxio/server/ft/MultiWorkerIntegrationTest.java

Rename AlluxioBlockStore to BlockStoreClient because it's a client indeed
1. Reduce confusion with blockstore
N/A

Rename AlluxioBlockStore to BlockStoreClient

---

docs/en/api/POSIX-API.md

Fix POSIX API doc for umount command
Have detailed instructions for how to umount fuse
alluxio-fuse CLI command

[DOCFIX] Fix POSIX API doc for umount command

---

shell/src/main/java/alluxio/cli/bundler/CollectInfo.java
shell/src/main/java/alluxio/cli/bundler/command/AbstractCollectInfoCommand.java
shell/src/main/java/alluxio/cli/bundler/command/CollectMetricsCommand.java

#14966 : Support collecting worker metrics in collectMetrics command. 
Support collecting worker metrics in collectMetrics command
None

Support collecting worker metrics in collectMetrics command

---

core/server/worker/src/main/java/alluxio/worker/block/meta/DefaultTempBlockMeta.java

Remove final attribute from DefaultTempBlockMeta for further usage.

Remove final from DefaultTempBlockMeta

---

integration/docker/entrypoint.sh
integration/fuse/bin/alluxio-fuse
integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
integration/kubernetes/helm-chart/alluxio/values.yaml

Add back Fuse mount environmental variable

---

underfs/hdfs/src/main/java/alluxio/underfs/hdfs/HdfsUnderFileSystem.java

Update log message to be more helpful for ActiveSync and ACL features in HDFS.

Update HDFS ACL and ActiveSync log message

---

docs/en/contributor/Building-Alluxio-From-Source.md

add `NullPointerException occurred while execute org.codehaus.mojo:buildnumber-maven-plugin:1.4:create`  in building alluxio from source doc
add a troubleshooting in building alluxio from source doc
no

Add NullPointerException occurred trouble shooting

---

docs/en/api/POSIX-API.md
docs/en/deploy/Running-Alluxio-On-Docker.md
docs/en/deploy/Running-Alluxio-On-Kubernetes.md

Improve Fuse documents about how to pass in fuse mount configuration.
Tell users how to pass in fuse mount configuration.
configuration

[DOCFIX] Improve Fuse mount docs

---

core/common/src/test/java/alluxio/collections/UnmodifiableArrayListTest.java

I added more unit test cases for UnmodifiableArrayList, including cases detecting illegal access and verifying ListIterator behaviors.
To better proof the correctness of the class UnmodifiableArrayList.
No.

Add more unit test cases for UnmodifiableArrayList

---

core/server/worker/src/main/java/alluxio/worker/block/BlockMetadataManager.java

Remove useless swapBlocks

---

core/client/fs/src/main/java/alluxio/client/block/stream/BlockWorkerClient.java

Add param tag

---

integration/fuse/bin/alluxio-fuse

Fix the alluxio-fuse script typo

[SMALLFIX] Fix the alluxio-fuse typo

---

tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java

see title
Sometime it would have fileAlreadyExistException
NA

Fix flaky DistributedLoadCommandTest
